### ISSUE TITLE
HTTP cache and conditional requests support in RestTemplate [SPR-5821]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#10491]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[SPR-5821](https://jira.spring.io/browse/SPR-5821?redirect=false)** and commented

The main goal is to create a `CachingClientHttpRequestInterceptor` which provides the following:

* Cache the received HTTP responses for further use, if those are marked as cacheable
* Cache those response in a `org.springframework.cache.Cache`
* if the Cache contains a valid response but its content is stale, then the Interceptor can issue conditional requests to revalidate the cached content
* by default, a sane configuration should be provided and the Cache should be backed by a `ConcurrentCacheMap`

This could be used like this:

```java
RestTemplate restTemplate = new RestTemplate();
restTemplate.setInterceptors(Collections.singletonList(new CachingClientHttpRequestInterceptor()));

// this response is cacheable and has appropriate headers
ResponseEntity<Book> response = restTemplate.getForEntity("http://example.org/resource", Book.class);
// it is now cached
String etag = response.getHeaders().getEtag();

// if the response is still fresh, then no network call should happen and the response should be reused
Book book = restTemplate.getForObject("http://example.org/resource", Book.class);
```

---

**Affects:** 3.0 M3

**Attachments:**
- [CachingHttpRequestFactory.java](https://jira.spring.io/secure/attachment/15536/CachingHttpRequestFactory.java) (_8.51 kB_)
- [ETagCachingRestTemplate.java](https://jira.spring.io/secure/attachment/15535/ETagCachingRestTemplate.java) (_7.98 kB_)

**Issue Links:**
- #12152 Introduce interceptors for RestTemplate (_**"depends on"**_)
- #16413 Server-side HTTP caching improvements
- #11967 Provide high-level cache API in Spring container

10 votes, 15 watchers

**Comment by bclozel** [comment]
In the meantime, `RestTemplate` has been put in maintenance mode, so we don't intend to invest more there.
