### ISSUE TITLE
Add support for @Transactional static methods [SPR-5999]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#10667]
**[Jukka Palomäki](https://jira.spring.io/secure/ViewProfile.jspa?name=duckbill)** opened **[SPR-5999](https://jira.spring.io/browse/SPR-5999?redirect=false)** and commented

Given the rich Entity model promoted by e.g. Spring Roo, it would be nice if Spring core would support `@Transactional` static methods via AspectJ. Have a look at the sample below.

```java
@Entity
class Reservation {

    @Transactional
    public void save() {
        // ...
    }
    
    @Transactional
    public void delete() {
        // ...
    }
    
    //...
    
    @Transactional
    public static void deleteAll() {
         // ...
    }
}
```

Currently this sort of design can work out for example by creating a (private) `@Transactional` instance method (e.g. `doDeleteAll()`), and delegating to it from within the static method. Though fairly concise, this approach feels sub-optimal. Another approach is to create a `@Service` bean to encapsulate this behavior, but for such a simple operation, it seems like overkill.

---

**Affects:** 3.0 M3

**Reference URL:** http://forum.springsource.org/showthread.php?t=76011

6 votes, 8 watchers

**Comment by sbrannen** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
