### ISSUE TITLE
Dependency injection of @Configurable objects should work across test suites [SPR-6121]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#10789]
**[Marc Ludwig](https://jira.spring.io/secure/ViewProfile.jspa?name=baronludwig)** opened **[SPR-6121](https://jira.spring.io/browse/SPR-6121?redirect=false)** and commented

#### Overview

We have a large number of unit/integration tests that assert behavior within our system and rely upon injection of dependencies into configurable domain objects.

These tests all work when executed individually; however, when executed within a suite (either through the IDE or Ant) certain tests fail as dependencies have not been injected into the `@Configurable` objects. We have also seen dependencies that were configured for test _X_ being injected into test _Y_ rather than the dependencies for test _Y_; but I have no test case for this.

---

#### Steps to Reproduce

I have created a set of three tests -- tests 1 and 3 are basically identical. If these are executed in a suite the third test will fail as the dependency is not injected into the `@Configurable` object even though it is available to the test. This only occurs if test 2 is a Spring test.

See attached zip file.

---

#### Further Resources

- [Spring Test Context Caching + AspectJ @Transactional + Ehcache pain](http://www.javacodegeeks.com/2014/04/spring-test-context-caching-aspectj-transactional-ehcache-pain.html) blog by Java Code Geeks

---

**Affects:** 2.5.6, 3.0.5

**Reference URL:** http://forum.springsource.org/showthread.php?t=77980

**Attachments:**
- [springtest.zip](https://jira.spring.io/secure/attachment/15724/springtest.zip) (_3.15 MB_)

**Issue Links:**
- #15989 SpringContexts not properly closed after test-class is finished (_**"is duplicated by"**_)
- #11019 TestContext framework should support one AspectJ instance per ApplicationContext
- #17123 AnnotationTransactionAspect retains reference to JpaTransactionManager from closed context

11 votes, 14 watchers

**Comment by sbrannen** [comment]
Superseded by #11019
