### ISSUE TITLE
Support for javax.validation annotations on @PathVariable, @RequestHeader, @RequestParam [SPR-6380]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11041]
**[Gerrit Brehmer](https://jira.spring.io/secure/ViewProfile.jspa?name=gbrehmer)** opened **[SPR-6380](https://jira.spring.io/browse/SPR-6380?redirect=false)** and commented

I thought this was already done, because support for controller method-parameter validation should be available for all parameters.

I there a reason to exclude annotated (`@RequestParam`, etc.) method parameters? Is it not possible to validate primitive values?

Simple example:
For Paging-Support i need two request parameters: "start" & "size". "start" must have a positive value or 0 and "size" must have a positive value and also a maximum set.

---

**Affects:** 3.0 RC2, 4.0.5

**Issue Links:**
- #14473 Support JSR 303 `@Valid` on `@PathVariable`

75 votes, 80 watchers

**Comment by oberlies** [comment]
> **[Thibaud Lepretre](https://jira.spring.io/secure/ViewProfile.jspa?name=kakawait)** commented
So is there something missing on current version of Spring?

Yes, the status code in case of validation errors on `@PathVariable`, `@RequestHeader`, and `@RequestParam` parmeters is incorrect: With the described solution, there is a 500. This is different from an invalid `@RequestBody`, which correctly results in a 400.

**Comment by membersound** [comment]
I'm having the same issue with `@RestController @Validated` and `@GetMapping... @RequestParam`.

**Comment by rehevkor5** [comment]
Is this the cause of https://github.com/spring-projects/spring-boot/issues/10471 or should a different issue be opened for that?

**Comment by chrylis** [comment]
@rehevkor5 Yes, it is. I've been using Spring for 11 years now and just again got bitten by this that I'd forgotten about. The dispatcher needs to handle it in order to produce consistent error behavior.

**Comment by rvplauborg** [comment]
Sot is still not possible to validate like: `@PathVariable @Positive int someParam`? Or what is the current status?

**Comment by pschichtel** [comment]
I'm processing the exception in my custom `GlobalErrorAttributes` instance with this crude hack now:

```kotlin
private class ViolationHelper(validator: Validator) : SpringValidatorAdapter(validator) {
    @Suppress("UNCHECKED_CAST")
    fun translateViolations(violations: Set<ConstraintViolation<*>>): BindingResult {
        val target = violations.map { it.invalidValue }.firstOrNull()
        val property = violations.map { it.propertyPath }.firstOrNull()
        val errors = DirectFieldBindingResult(target, property?.toString() ?: "")
        processConstraintViolations(violations as Set<ConstraintViolation<Any>>, errors)
        return errors
    }
}
```

the translateViolations function gives me a a BindingResult which I can put into the error attributes similar to how it's done for normal binding errors.

**Comment by Muddz-Nuuday** [comment]
As a Software Developer for a big telecom company heavily reliant on using Spring Boot, I welcome this feature request alot!!

**Comment by marwin1991** [comment]
Any progress?

**Comment by rstoyanchev** [comment]
This has been a long running issue, at first not possible until Hibernate Validator added method level validation, and later enabled in Spring Framework 4.x through a `MethodValidationPostProcessor`, see https://github.com/spring-projects/spring-framework/issues/11041#issuecomment-453343899. We're intend to add built-in support at the web framework level with #24913, so I'm closing this in favor of that.
