### ISSUE TITLE
Cannot access system properties in SpEL programmatically [SPR-6651]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11317]
**[Narada Sage](https://jira.spring.io/secure/ViewProfile.jspa?name=narada)** opened **[SPR-6651](https://jira.spring.io/browse/SPR-6651?redirect=false)** and commented

Hi,

As mentioned on forum post accessing system properties in SpEL programmatically does not work for me. The manual only refers to use of system properties in xml which I haven't tried. However shouldn't this work programmatically as well?

If you need further details please let me know.

Thanks.

---

**Affects:** 3.0 GA

**Reference URL:** http://forum.springsource.org/showthread.php?t=82259

**Attachments:**
- [SystemPropertiesAccessor.java](https://jira.spring.io/secure/attachment/20975/SystemPropertiesAccessor.java) (_2.10 kB_)
- [SystemPropertiesAccessorUnitTest.java](https://jira.spring.io/secure/attachment/20974/SystemPropertiesAccessorUnitTest.java) (_2.65 kB_)

2 votes, 4 watchers

**Comment by jhoeller** [comment]
Superseded by #27721 with a wider-ranging scope. At this point still left up to custom arrangements, in any case.
