### ISSUE TITLE
Using @Transactional in AspectJ mode with multiple application contexts [SPR-6661]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11327]
**[Janning Vygen](https://jira.spring.io/secure/ViewProfile.jspa?name=janning)** opened **[SPR-6661](https://jira.spring.io/browse/SPR-6661?redirect=false)** and commented

Using Multiple Transaction Managers with `@Transactional` works like a charme if you only have one BeanFactory.
doc reference is here:
http://static.springsource.org/spring/docs/3.0.x/reference/html/transaction.html#tx-multiple-tx-mgrs-with-attransactional

but i have a projects which depends on another spring project which is integrated by starting a second  beanFactory. Each BeanFactory has its own TransactionManager (and its own SessionFactory and DataSource). Even if i annotate all `@Transactional` Annotations with a qualifier like described in the docs, it does not work.

This is because TransactionAspectSupport.determineTransactionManager(TransactionAttribute txAttr) relies on a beanFactory reference for resolving a matching transactionManager. But transactionAspectSupport is a singleton aspect. So we have two beanFactories but only one instance of TransactionAspectSupport. So when i load my second beanFactory TransactionAspectSupport.setBeanFactory is called again and the initial beanFactory reference is lost.

this could be prevented if TransactionAspectSupport has a set of beanFactories and iterating over them when searching for a matching qualifier.

BTW, i think there is an documentation bug:
<http://static.springsource.org/spring/docs/3.0.x/reference/html/transaction.html#transaction-declarative-annotations>
it says: "<tx:annotation-driven/> only looks for `@Transactional` on beans in the same application context it is defined in." This is not true for mode="aspectj", isn't it?

---

**Affects:** 3.0 GA

5 votes, 7 watchers

**Comment by jhoeller** [comment]
This is effectively superseded by #11019 (also in the backlog with low priority).
