### ISSUE TITLE
Define alias for component-scanned bean via annotation [SPR-6736]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11402]
**[adrian](https://jira.spring.io/secure/ViewProfile.jspa?name=gonzalad)** opened **[SPR-6736](https://jira.spring.io/browse/SPR-6736?redirect=false)** and commented

I'm using Struts 1 with the Spring DelegatingTilesRequestProcessor plugin.
I define my actions as spring beans and would like to use `@Component` annotation and no XML configuration.

My problem is that an action path must correspond to the same Spring bean id.

And I can have the same spring bean used for multiple actions.

i.e /charge/view and /charge/save should map to the same bean.

I cannot do it with `@Component` annotation alone, and would need a `@Alias` or `@Role` annotation.

For instance something like :

```
@Component("/charge/view")
@Roles({`@Role`("/charge/remove"),
    @Role("/charge/edit"),
    @Role("/charge/save")})
public class EditChargeClienteleAction extends MappingDispatchAction {
```

---

**Affects:** 3.0 GA

**Reference URL:** http://forum.springsource.org/showthread.php?t=83133

16 votes, 12 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by foal** [comment]
Still relevant

**Comment by itsLucario** [comment]
This issue is open from 2010. Spring must look into this feature request.

**Comment by mauromol** [comment]
I also think this is a missing feature in Spring annotations. Probably an `alias` property of `@Component` or an `@Alias` annotation could do the trick?

**Comment by fibsifan** [comment]
+1

**Comment by snicoll** [comment]
Thanks for the suggestion but, after a careful consideration, we're going to decline this. `@Component` is a simple way of registering new beans in the bean factory that is decoupled from `BeanDefinition`. As such, adding an alias to it does not really make sense.

If you need to register a bean with multiple aliases, please use the `@Configuration` model with `@Bean` that provides a way for you to provide several bean names.
