### ISSUE TITLE
Deprecate SqlXmlObjectMappingHandler [SPR-6982]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#11647]
**[nicolas de loof](https://jira.spring.io/secure/ViewProfile.jspa?name=ndeloof)** opened **[SPR-6982](https://jira.spring.io/browse/SPR-6982?redirect=false)** and commented

SqlXmlObjectMappingHandler uses and returns Object, it should use generics to avoid casts

---

**Affects:** 3.0.1

**Comment by jhoeller** [comment]
@sdeleuze could we deprecate this in 5.1.5 already and remove it in 5.2 right away?
