### ISSUE TITLE
Allow @Bean in test classes to override beans loaded via @ContextConfiguration [SPR-7169]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11828]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[SPR-7169](https://jira.spring.io/browse/SPR-7169?redirect=false)** and commented

It would be cool if test classes executed with `SpringJUnit4ClassRunner` would be considered as `@Configuration` classes, too. This way the following would be possible.

```java
@RunWith(SpringJUnitClassRunner.class)
@ContextConfigLocation("classpath:foo.xml")
public class SampleTest {

  @Autowired
  private MyService myService;

  @Bean
  public MyRepository repository() {
    return Mockito.mock(MyRepository.class);
  }

  // Testcases
}
```

IMHO this has the benefit of not polluting the test resources with zillions of config files that you might want to declare to override certain beans from your default configuration (which you would additionally load inside `@ContextConfigLocation`). As this co-locates customization needed for the tests and the tests themselves it reduces scattering of artifacts needed for the tests.

---

**Affects:** 3.0.2

3 votes, 7 watchers

**Comment by loganmzz** [comment]
Why no use `@TestConfiguration` ?

**Comment by sbrannen** [comment]
> Why not use `@TestConfiguration`?

_This_ issue was raised in 2010 for the core Spring Framework; whereas, `@TestConfiguration` is a feature specific to Spring Boot.

**Comment by loganmzz** [comment]
Good points, I didn't catch it !

**Comment by sbrannen** [comment]
- superseded by #29917
