### ISSUE TITLE
Revisit AntPathMatcher's handling of patterns with file extensions [SPR-7336]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11995]
**[marc schipperheyn](https://jira.spring.io/secure/ViewProfile.jspa?name=mschipperheyn)** opened **[SPR-7336](https://jira.spring.io/browse/SPR-7336?redirect=false)** and commented

The AntPathMatchers in some cases prefers less specific matches over specific matches. This examples is from the case of
WebContentInterceptor

```xml
 
<property name="cacheMappings">
	<props>
		<prop key="/**/">1800</prop>
		<prop key="/**/*.html">1800</prop>
		<prop key="/**/offerform/**/*.html">-1</prop>
		<prop key="/**/offerform/*.html">-1</prop>
		<prop key="/**/cart/">-1</prop>
		<prop key="**/cart/**/*.html">-1</prop>
	</props>
</property>
```

The order doesn't matter. The issue occurs also if we put /**/ at the bottom

Example urlPath

```
/en/offerform/step4.html?offerId=17
matches /**/offerform/**/*.html
matches /**/offerform/*.html
matches /**/ [shouldn't match at all AFAIC]
matches /**/*.html
```

result: 1800. Should be -1

Example urlPath

```
/en/cart/
matches /**/
matches /**/cart/
```

result: -1 correct

It seems that the issue doesn't occur when the path ends with a / in stead of with an extension *.html

---

**Affects:** 3.0.3

2 votes, 4 watchers

**Comment by rstoyanchev** [comment]
Closing as outdated. We've deprecated and turned off support for suffix pattern match in #23915 and related issues. We've added support for pre-parsed `PathPattern`, created specifically for Web paths, and see that as the way forward. The `PathPattern` syntax also does not allow `"**`" in the middle of a path.
