### ISSUE TITLE
Provide proper @Value documentation in the reference documentation [SPR-7599]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#12255]
**[Gerson](https://jira.spring.io/secure/ViewProfile.jspa?name=gersonk)** opened **[SPR-7599](https://jira.spring.io/browse/SPR-7599?redirect=false)** and commented

Release notes of 3.0.0.M3 says:
- `@Value` values may use ${...} placeholders (driven by PropertyPlaceholderConfigurer)

Chris Beams says:
http://forum.springsource.org/showpost.php?p=234023&postcount=2

---

**Affects:** 3.0.4

**Issue Links:**
- #22171 Refactor core documentation to make it relevant for modern Spring applications

**Comment by sdeleuze** [comment]
Closed in favor of #23052.
