### ISSUE TITLE
Add Assert.noNullElements for Collections [SPR-7925]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#12580]
**[Eliran Bivas](https://jira.spring.io/secure/ViewProfile.jspa?name=bivas)** opened **[SPR-7925](https://jira.spring.io/browse/SPR-7925?redirect=false)** and commented

It's possible to add the following code to `Assert` utility class

```
public static void noNullElements(final Collection<?> collection, final String message) {
    for (Object object : collection) {
        if (object == null) {
            throw new IllegalArgumentException(message);
        }
    }
}
    
public static void noNullElements(Collection<?> collection) {
    noNullElements(collection, "[Assertion failed] - this collection must not contain any null elements");
}
```

---

**Affects:** 3.0.5

**Comment by rweisleder** [comment]
Commit https://github.com/spring-projects/spring-framework/commit/4000b244ff7b1db1f4eba9c4dbf2fc97162da254 added `Assert.noNullElements(...)` for collections.

**Comment by sbrannen** [comment]
Superseded by work performed in conjunction with #23151.

See 4000b244ff7b1db1f4eba9c4dbf2fc97162da254.
