### ISSUE TITLE
Revisit subsystem-oriented logging [SPR-8122]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#12774]
**[Chris Beams](https://jira.spring.io/secure/ViewProfile.jspa?name=cbeams)** opened **[SPR-8122](https://jira.spring.io/browse/SPR-8122?redirect=false)** and commented

---

**Issue Links:**
- #10000 Consider migrating from Commons-Logging to SLF4j
- #12438 Logging of SQL Params and Query when using JdbcTemplate
- #19081 Revisit Commons Logging vs java.util.logging vs SLF4J vs Log4j 2

**Referenced from:** commits https://github.com/spring-projects/spring-framework-issues/commit/65ac173b29825aa460bda47c5b751515138b5a4c

3 votes, 9 watchers

**Comment by bclozel** [comment]
Closing in favour of #19081
