### ISSUE TITLE
Support for ByteBuddy as an alternative to CGLIB [SPR-8190]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#12840]
**[Chris Beams](https://jira.spring.io/secure/ViewProfile.jspa?name=cbeams)** opened **[SPR-8190](https://jira.spring.io/browse/SPR-8190?redirect=false)** and commented

Tracking issue for CGLIB problems and possible solutions when moving to Javassist or, as recently suggested, Byte Buddy.

---

**Attachments:**
- [permgen-leak-spring.tar.gz](https://jira.spring.io/secure/attachment/21203/permgen-leak-spring.tar.gz) (_492.76 kB_)

**Issue Links:**
- #8831 Latest Spring AOP + CGLib caches classes from the same classloader causing CCE in Grails (_**"depends on"**_)
- #10325 Consider using javassist for proxy generation (_**"depends on"**_)
- #12142 `@Configuration` with AspectJ instead of CGLIB (_**"depends on"**_)
- #7964 Look at phasing out cglib with javaassist (_**"is duplicated by"**_)

44 votes, 45 watchers

**Comment by ma-sharifi** [comment]
Is there any update on this?

**Comment by jhoeller** [comment]
For the time being, we are going to hang on to your CGLIB fork in the 6.x generation. It does everything we need it do for AOT purposes and for JDK 17+ compatibility, with a pretty lean codebase that we can patch wherever and whenever we need. Supporting a different bytecode generation strategy is a huge maintenance burden that we're currently not ready to take on.

**Comment by Sineaggi** [comment]
@jhoeller perhaps the [Class-File API JEP](https://openjdk.org/jeps/8280389) might be interesting when it stabilizes?
