### ISSUE TITLE
Overhaul core container error reporting [SPR-8204]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#12854]
**[Chris Beams](https://jira.spring.io/secure/ViewProfile.jspa?name=cbeams)** opened **[SPR-8204](https://jira.spring.io/browse/SPR-8204?redirect=false)** and commented

Consider moving away from stack-trace based errors at container bootstrap time in favor of a more compiler-like output (think javac), where all errors are explained in a concise and intuitive manner, possibly with suggests for resolution.

See also CollatingProblemReporter, and the new ProblemCollector interface

---

**Issue Links:**
- #8389 Condense exception messages accumulated through recursion
- #10336 Support collated problem reporting
- #13696 Warn when attempting to inject values into fields marked final

**Comment by jhoeller** [comment]
Superseded by #25162 which got addressed for 6.0 already.
