### ISSUE TITLE
Provide a TilesView for partial rendering [SPR-8408]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13055]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-8408](https://jira.spring.io/browse/SPR-8408?redirect=false)** and commented

Modify the TilesView or provide a variant that can render a Tiles definition with or without its layout. The decision can be based on the presence of a request parameter, a request attribute, or another configurable approach.

**Background:** when using Tiles it is common for each page to have a layout. When the controller returns a view name, it is interpreted as a Tiles definition name and the page is rendered with its layout. Sometimes however it is helpful to render the same Tiles definition without the layout, for example during an Ajax request.

A few scenarios this simple approach can serve:
1. Simple page ("body" + layout) - update the main content area with a partial response
2. Container page (multiple content areas) - update each content area alone or render the entire page
3. Forms - on error return form content only; on success return form only (Ajax) or redirect

---

**Affects:** 3.0.5

**Issue Links:**
- #10318 Provide ability to determine if the current request is an ajax request

3 votes, 3 watchers

**Comment by rstoyanchev** [comment]
Closing since Tiles support has been dropped for 6.0 in #27423.
