### ISSUE TITLE
Allow 301 redirect from trailing slash to no trailing slash urls [SPR-8473]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13119]
**[Bozhidar Bozhanov](https://jira.spring.io/secure/ViewProfile.jspa?name=bozho)** opened **[SPR-8473](https://jira.spring.io/browse/SPR-8473?redirect=false)** and commented

It would be nice to use strict url matching and at the same time be able to redirect alternatives with 301 (permanent).

For example:
http://example.com/foo/bar -> no trailing slash, and it is specified that way in the `@RequsetMapping`
http://example.com/foo/bar/ -> 301 redirect to /foo/bar

This is to enforce consistency of urls and at the same time not loose traffic/SEO value if someone accidentally adds the wrong link. Logging could be configured to report these redirects.

---

**Affects:** 3.1 M2

**Referenced from:** commits https://github.com/spring-projects/spring-framework-issues/commit/5eacd228f7aa79661f087ecb42d90112fec189bf

5 votes, 6 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by OrangeDog** [comment]
I think this is still relevant? Especially as Spring 6 deprecated `useTrailingSlashMatch`.

**Comment by bclozel** [comment]
I think this will be covered with #31366
