### ISSUE TITLE
Detect circular dependencies within @Configuration classes and throw a helpful exception [SPR-8609]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13252]
**[Tomasz Nurkiewicz](https://jira.spring.io/secure/ViewProfile.jspa?name=nurkiewicz)** opened **[SPR-8609](https://jira.spring.io/browse/SPR-8609?redirect=false)** and commented

In the following `@Configuration` class assertion fails because the SpEL expression is not evaluated prior to running `bar()`:

```
@Configuration
public class ContextConfiguration {

	@Resource
	private Foo foo;

	@Value("#{2+3}")
	private int value;

	@Bean
	public Bar bar() {
		Assert.isTrue(value == 5, Integer.toString(value));
		return new Bar();
	}

}
```

Because cyclic dependency is introduced, `bar()` is executed by the container on `ContextConfiguration` that is not yet populated:

```
@Service
public class Foo {

	@Resource
	private Bar bar;

}

public class Bar {
}
```

I am aware that fixing this might be a bit challenging, but at least an exception should be thrown rather than silently calling `@Bean` method on uninitialized `@Configuration` class. Full failing test case is available [here](https://github.com/nurkiewicz/spring-no-xml/tree/spring-cyclic-dep-bug) (`spring-cyclic-dep-bug` branch).

---

**Affects:** 3.1 M2

**Issue Links:**
- #13226 unresolvable circular reference when bean defined in xml config refers to bean defined in outer java config

**Comment by bdshadow** [comment]
This issue can be closed. When the example above is run, exception is thrown as expected:

> 2023-06-16 15:30:11.392  WARN 45054 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contextConfiguration': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'foo': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'contextConfiguration': Requested bean is currently in creation: Is there an unresolvable circular reference?

> Description:
The dependencies of some of the beans in the application context form a cycle:
┌─────┐
|  contextConfiguration
↑     ↓
|  foo
└─────┘
Action:
Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Comment by snicoll** [comment]
Yes, I  agree that the failure analyzer in Spring Boot is providing a solution for this.
