### ISSUE TITLE
MessageListenerContainers should invalidate the Session properly in case of JMSException [SPR-8616]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13259]
**[Sam Brannen](https://jira.spring.io/secure/ViewProfile.jspa?name=sbrannen)** opened **[SPR-8616](https://jira.spring.io/browse/SPR-8616?redirect=false)** and commented

###### Status Quo

When an exception is caught in `AbstractPollingMessageListenerContainer`'s `doReceiveAndExecute()` method, `AbstractPollingMessageListenerContainer` delegates to `AbstractMessageListenerContainer`'s `handleListenerException()` method. If the supplied `Throwable` is a `JMSException`, it gets passed to `AbstractMessageListenerContainer`'s `invokeExceptionListener()` method for further processing. In turn, `invokeExceptionListener()` calls `onException()` on the JMS `ExceptionListener` that was registered with the `AbstractMessageListenerContainer`.

`AbstractMessageListenerContainer`'s `invokeExceptionListener()` method does **not** call `onException()` on the JMS `ExceptionListener` of the underlying JMS `Connection`.

Consequently, connection errors that occur while processing _inbound_ messages in a Spring MessageListenerContainer do not get propagated to the underlying connection. If the underlying connection is a shared connection that was created by Spring's `SingleConnectionFactory` or `CachingConnectionFactory`, that now broken connection will be reused by subsequent clients even though it should have been reset due to the connection failure. This leads to an endless loop of retries with invalid connections that will never work, and in the end the application will likely have to be restarted in order to obtain new connections.

###### Goal

`AbstractMessageListenerContainer`'s `invokeExceptionListener()` method should call `onException()`:

- on the JMS `ExceptionListener` that was registered with the `AbstractMessageListenerContainer` (i.e., the status quo)
- **and** on the JMS `ExceptionListener` of the underlying JMS `Connection`

Note that `DefaultMessageListenerContainer`'s `refreshDestination()` method already provides similar support for refreshing a possibly invalid destination name for a `CachingDestinationResolver`.

###### Work-around

The current work-around is to set the `exceptionListener` property of the `DefaultMessageListenerContainer` to the `CachingConnectionFactory`. This works since `CachingConnectionFactory` implements the JMS `ExceptionListener` interface, and `CachingConnectionFactory`'s `onException()` method will internally reset the connection (i.e., clear the cache). Note, however, that the `exceptionListener` property is unfortunately not exposed as an attribute via the `<jms:listener-container>` XML namespace. The following XML-based configuration has been tested as a suitable work-around configuration:

```xml
<bean class="org.springframework.jms.listener.DefaultMessageListenerContainer">
	<property name="connectionFactory" ref="cachingConnectionFactory" />
	<property name="exceptionListener" ref="cachingConnectionFactory" />
	<property name="destinationName" value="my.queue.name" />
	<property name="messageListener" ref="myMessageListener" />
</bean>
```

---

**Affects:** 3.0.5

**Reference URL:** http://forum.springsource.org/showthread.php?96821-DefaultMessageListenerContainer-CachingConnectionFactory-tomcat-and-WebSphere-MQ

**Comment by jhoeller** [comment]
Reading the description above, this sounds like misbehavior on the side of the JMS broker. The broker itself needs to notify the Connection-registered ExceptionListener, not the consumer. Once that works, a connection reset should work automatically, even with `CachingConnectionFactory`. As for resetting a particular session only, since they typically all come from the same connection, it seems sensible to always clear all sessions and start with a fresh setup there.
