### ISSUE TITLE
GenericConversionService should match target converters for compatible subclasses [SPR-8675]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13317]
**[David Smiley](https://jira.spring.io/secure/ViewProfile.jspa?name=dsmiley)** opened **[SPR-8675](https://jira.spring.io/browse/SPR-8675?redirect=false)** and commented

I registered this simple Converter (which by the way, I feel is something that should be out of the box):

```java
public class FileToResourceConverter implements Converter<File,Resource> {
  public Resource convert(File source) {
    return new FileSystemResource(source);
  }
}
```

I have code that would like to look up a converter for an InputStreamSource (a super-interface of Resource):

```java
InputStreamSource rsrc = this.getConversionService().convert(message.getPayload(), InputStreamSource.class);
```

But this fails because, apparently, GenericConversionService is unable to recognize instanceof relationships between the conversion target type and the desired target type. As a workaround, my code here has to be aware that the converter is for Resource and then ask the conversion service for a Resource even though it only needs an InputStreamSource.

---

**Affects:** 3.0.6

**Issue Links:**
- #13360 ClassCastException possible when converting to a target type that is a subtype of T for a Converter<S, T> convertible type.
- [INT-3556](https://jira.spring.io/browse/INT-3556) Use Converters that can convert to subtype of datatype channel

0 votes, 7 watchers

**Comment by chrylis** [comment]
Amusingly/frustratingly, I find myself once back at this same issue; while integrating with Spring Security's `PermissionEvaluator` (which expects an ID of type `Serializable`), I found that providing a `Converter<Entity, String>` would not work, which is Surprising Behavior.
