### ISSUE TITLE
AbstractSingleBeanDefinitionParser should handle depends-on, lazy-init, scope, etc. [SPR-8703]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13345]
**[Archie Cobbs](https://jira.spring.io/secure/ViewProfile.jspa?name=archie172)** opened **[SPR-8703](https://jira.spring.io/browse/SPR-8703?redirect=false)** and commented

`AbstractSingleBeanDefinitionParser` has support for setting bean name and aliases (via superclass), parent name, and bean class, but not depends-on, lazy-init, scope etc.

This seems arbitrarily incomplete. Ideally, this class would include support and default handling for all of the settable properties of the `BeanDefinition` interface.

A nice design would be for the superclass `AbstractBeanDefinitionParser` to have methods like this:

```
protected void parseDependsOn(BeanDefinition beanDefinition, String value, ParserContext parserContext) {
    ...
}
protected void parseScope(BeanDefinition beanDefinition, String value, ParserContext parserContext) {
    ...
}
```

so the subclass could easily use different attributes (or other sources) for these settings.

`AbstractSingleBeanDefinitionParser` could then invoke these helper methods by default with the usual attributes, but in an easily overridable way.

---

**Affects:** 3.0.6

1 votes, 1 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by archiecobbs** [comment]
> Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

... except Github won't let me reopen it...

**Comment by jhoeller** [comment]
We have no plans to revisit the XML namespace handlers at this late stage, given that the entire XML bean definition model is in a feature-frozen maintenance mode. Anything we add there at this point is not likely to get traction anymore before being phased out even further.
