### ISSUE TITLE
mvc rest services to generate a wadl [SPR-8705]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13347]
**[chris snow](https://jira.spring.io/secure/ViewProfile.jspa?name=snowch)** opened **[SPR-8705](https://jira.spring.io/browse/SPR-8705?redirect=false)** and commented

It would be good if Spring MVC Rest services could automatically generate a WADL.  This will make the rest services much each to use in service (e.g. SOA) environments.

---

25 votes, 33 watchers

**Comment by bclozel** [comment]
Several Spring and 3rd party projects are handling the API format spec and documentation aspects - there are still quite a few choices out there, but WADL isn't the popular choice these days. We won't be addressing this feature in Spring Framework as a result.
