### ISSUE TITLE
Publish TestStarted and TestCompleted events in the TestContext framework [SPR-8710]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#13352]
**[Stepan Koltsov](https://jira.spring.io/secure/ViewProfile.jspa?name=yozh)** opened **[SPR-8710](https://jira.spring.io/browse/SPR-8710?redirect=false)** and commented

#### Status Quo

AFAIU currently test initialization and finalization code must be placed into a test class (not in the application context), so code cannot be easily reused between unrelated test classes.

#### Proposal

`SpringJUnit4ClassRunner` could publish a `TestStartedEvent` before each test method and a `TestFinishedEvent` after each test in the application context. Listeners to these events could be used to clean caches from the previous test run, recreate database state before a test method, etc.

---

**Issue Links:**

- #18490 Publish TestExecutionListener events to the ApplicationContext under test
- #18606 Introduce support for test-scoped beans in the TestContext framework

**Comment by sbrannen** [comment]
This issue has been superseded by gh-18490.

Please continue the discussion there.
