### ISSUE TITLE
@DirtiesContext does not destroy all cached singleton beans [SPR-8857]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#13499]
**[Saurabh Chandra](https://jira.spring.io/secure/ViewProfile.jspa?name=saurabh.chandra)** opened **[SPR-8857](https://jira.spring.io/browse/SPR-8857?redirect=false)** and commented

Data from one test having data-source as H2 (in-memory database) seems to live on for the next test class. This persists even after using `@DirtiesContext` at class or method level.

Currently we have to clear any data from H2 before every a test.

**``@DirtiesContext`` should clear all that is bound to the context (including data-source).**

If it might help we are using JUnit 4.8.1.

---

**Issue Links:**
- #10532 Allow for concurrent test execution in the TestContext framework

5 votes, 9 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by MartaSwierczewska** [comment]
You can use @AutoConfigureTestDatabase annotation, worked for me
