### ISSUE TITLE
Detect whether parameter names are available for cache key computation [SPR-8893]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13534]
**[Eric Brun](https://jira.spring.io/secure/ViewProfile.jspa?name=erbru)** opened **[SPR-8893](https://jira.spring.io/browse/SPR-8893?redirect=false)** and commented

Hi,

I have annotated method of my class with the new cache abstraction feature.

a method by example :

`@Cacheable`(value="jackrabbitCache", key="#login+':'+#path")
public RessourceItem getPathContent(String path, String login) {...}

On MacOSX JVM 1.6 and Jetty + tomcat 7 libs when I put login and path parameter with for example 'JEAN-MICHEL.JULLIEN' and path '/JEAN-MICHEL.JULLIEN'
My traceback says :

02-12-2011 17:30:30:113 43707 DEBUG org.springframework.cache.interceptor.CacheInterceptor  - Computed cache key JEAN-MICHEL.JULLIEN:/JEAN-MICHEL.JULLIEN for operation CacheableOperation[public com.pentila.evalcomp.domain.transit.RessourceItem com.pentila.evalcomp.repository.Storage.getPathContent(java.lang.String,java.lang.String)] caches=[jackrabbitCache] | condition='' | key='#login+':'+#path'

=> Here it works

When I deploy on Linux JVM IBM 1.6 or JVM SUN 1.6.0_22 on tomcat 6.0.33 or tomcat 7.0.22

My traceback is always :

02-12-2011 18:51:28:829 848685 DEBUG org.springframework.cache.interceptor.CacheInterceptor  - Computed cache key null:null for operation CacheableOperation[public com.pentila.evalcomp.domain.transit.RessourceItem com.pentila.evalcomp.repository.Storage.getPathContent(java.lang.String,java.lang.String)] caches=[jackrabbitCache] | condition='' | key='#login+':'+#path'

=> Here Fail !

My key is wrong but I pass the right values for parameters (not null values).

Is there a bug in parameters interpretation in SpeL language expression ? Or a conflict libs with tomcat ?

Please Help

Thanks Eric

---

**Affects:** 3.1 RC2

**Comment by snicoll** [comment]
I believe this issue is outdated now so I am going to close it.
