### ISSUE TITLE
PropertySourcesPlaceholderConfigurer never calls "convertProperties" on merged properties [SPR-8928]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#13568]
**[Daniel Fernández](https://jira.spring.io/secure/ViewProfile.jspa?name=dfernandez)** opened **[SPR-8928](https://jira.spring.io/browse/SPR-8928?redirect=false)** and commented

org.springframework.context.support.PropertySourcesPlaceholderConfigurer is overriding the "postProcessBeanFactory" method defined in org.springframework.beans.factory.config.PropertyResourceConfigurer in order to register the required chain of PropertySource objects that will be use for resolving properties. This makes sense and is OK.

But the problem is that the PropertySource object for the local properties (those coming from the "location" attribute and also from the "properties" property) is being created like this:

PropertySource<?> localPropertySource =
new PropertiesPropertySource(LOCAL_PROPERTIES_PROPERTY_SOURCE_NAME, this.mergeProperties());

...whereas in the original "postProcessBeanFactory" method in PropertyResourceConfigurer these merged properties are post-processed by executing the "convertProperties" method:

Properties mergedProps = mergeProperties();
// Convert the merged properties, if necessary.
convertProperties(mergedProps);
// Let the subclass process the properties.
processProperties(beanFactory, mergedProps);

This means that the new PropertySourcesPlaceholderConfigurer class never calls "convertProperties", and so disables one of the extension mechanisms of the old pre-3.1 PropertyPlaceholderConfigurer class: overriding the "convertProperty(...)" and "convertPropertyValue(...)" methods.

I am jasypt's author http://www.jasypt.org and I am creating a Spring3.1-compatible EncryptedPropertySourcesPlaceholderConfigurer, but this bug doesn't allow me to transparently apply property decryption at the "convertProperty" method :-(

---

**Affects:** 3.1 GA

**Issue Links:**
- #18574 convertPropertyValue (for reading encrypted values) not working (_**"is duplicated by"**_)
- #13603 Allow the use of custom PropertySource annotations in @Configuration classes
- [SEC-3123](https://jira.spring.io/browse/SEC-3123) Encrypted property value support
- #15294 Add encryption support for PropertyPlaceholderConfigurer
- #17236 Backport encrypted property functionality from spring-cloud-config environment work

8 votes, 18 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by raduiacobescu** [comment]
It took me ages to get to your implementation example @spring-issuemaster 
This must be added somewhere in a documentation
