### ISSUE TITLE
Make flash attributes use cookie to enable stateless webapp [SPR-8997]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13637]
**[Ludovic Praud](https://jira.spring.io/secure/ViewProfile.jspa?name=ludovic.praud)** opened **[SPR-8997](https://jira.spring.io/browse/SPR-8997?redirect=false)** and commented

I was waiting the flash attributes feature in spring 3.1 but I was surprised that the attributes were stored in the HTTP session instead of cookie. My webapp is required to not have session because the infrastructure we use does not handle sticky session. I have done my own flash scope inspired from the one in playframework. It would be cool to be able to choose between http session or cookie.

---

**Affects:** 3.1 GA

**Issue Links:**
- #17354 FlashMap's cannot be easily serialized by means other than java serialization

4 votes, 10 watchers

**Comment by samuelstein** [comment]
What is the actual status of the ticket?   
I recently also experienced problems when using flash attributes in a replicated service.
For me it was not clear enough from the documentation that flash attributes don't use a cookie like [play framework](https://www.playframework.com/documentation/2.8.x/JavaSessionFlash#Working-with-Cookies) but instead a session. Especially when the session creation policy of the app is set to _stateless_.   
I wish at least a warning log entry in this case.

**Comment by bclozel** [comment]
I'm declining this issue as we haven't made progress on this for a very long time and there is a significant amount of work to be done still, for very little demand. There are still a few key issues to be worked out [in the implementation](https://github.com/trecloux/spring-flash-cookie): as mentioned earlier in this thread, the cookie size, encryption and integrity are important security problems.

In the meantime, [Spring Session provides secure session replication](https://spring.io/projects/spring-session) that's independent of the Servlet container and supports several data stores.
