### ISSUE TITLE
SimpleJdbcInsert does not quote table and column names [SPR-9236]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13874]
**[Michel Zanini](https://jira.spring.io/secure/ViewProfile.jspa?name=michelz)** opened **[SPR-9236](https://jira.spring.io/browse/SPR-9236?redirect=false)** and commented

If you have table or column names that are reserved SQL words, like "varchar", "values", "integer", etc... the generated insert SQL must have escaping.

For example, now `SimpleJdbcInsert` is generating this SQL:

```sql
INSERT INTO crud (text, integer, char, datetime, decimal, varchar) VALUES(?, ?, ?, ?, ?, ?)
```

but it should be generating this:

```sql
INSERT INTO `crud` (`text`, `integer`, `char`, `datetime`, `decimal`, `varchar`) VALUES(?, ?, ?, ?, ?, ?)
```

As a workaround I am able to make it work adding the escape char "`" to the column names like this:

```java
simpleJdbcInsert.withTableName("`" + tableName + "`");
simpleJdbcInsert.usingColumns("`" + column1 + "`", "`" + column2 + "`", "`" + column3 + "`");
```

but I believe `SimpleJdbcInsert` should support this out of the box. For example, it could have a boolean property like this:

```java
simpleJdbcInsert.withTableName(tableName);
simpleJdbcInsert.usingColumns(column1, column2, column3);
simpleJdbcInsert.usingEscaping(true);
```

and then `SimpleJdbcInsert` would do the escaping for me.

---

**Affects:** 3.1.1

4 votes, 6 watchers

**Comment by vgrankina** [comment]
We need the same functionality for PostgreSQL because we use a mix of uppercase and lowercase letters for table names and we need to escape them with double quotes. When I set table name with double quotes like so ```
new SimpleJdbcInsert(dataSource)
                .withTableName("\"Table_Name\"");
```
I see a log message that metadata for table not found.

**Comment by sadafskolon** [comment]
It's 2023 and simple JDBC insert still does not support keyword columns.

**Comment by sadafzohra19** [comment]
It worked for me. What I did is,

```
String[] columns = {"name", "desc",  "code", "`order`"}

SimpleJdbcInsert insert = new SimpleJdbcInsert(jdbcTemplate.getJdbcTemplate());
insert.withTableName(tableName);
insert.usingColumns(columns);
insert.usingGeneratedKeyColumns("id");

Number id = insert.executeAndReturnKey(parameterSource);
```

Note that in order to pass parameter for column "order", you need to pass it like this:
`params.put("`order`", 3);`

**Comment by sbrannen** [comment]
- superseded by #24013
