### ISSUE TITLE
Introduce removeApplicationListener in ConfigurableApplicationContext

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14023]
**[Archie Cobbs](https://jira.spring.io/secure/ViewProfile.jspa?name=archie172)** opened **[SPR-9387](https://jira.spring.io/browse/SPR-9387?redirect=false)** and commented

I have some object which need to receive some `ApplicationEvents` that are sent around in my application.

However, these objects have a lifecycle that does not match with the lifecycle of normal beans in the application context (their lifecycle is shorter).

Therefore, I have these beans marked `@Configurable`, and they are `ApplicationContextAware` so they can get a reference to the application context (which is assumed to be a `ConfigurableApplicationContext`.

Then, when they "start" they register as listeners for application events via `ConfigurableApplicationContext.addApplicationListener()`. However, when they "stop" there is no way for them to unregister themselves as listeners, because there is no corresponding method `ConfigurableApplicationContext.removeApplicationListener()`.

So this request is simply to add `ConfigurableApplicationContext.removeApplicationListener()`.

If there is some more elegant way to do what I'm trying to do please let me know. But just from the face of it, it seems weirdly asymmetrical to have a public `addFooListener()` method without a corresponding `removeFooListener()` method.

Thanks.

---

**Affects:** 3.1.1

**Issue Links:**
- #14027 Support DisposableBean on prototype and `@Configurable` beans using weak references

1 votes, 4 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by archiecobbs** [comment]
> Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

... except Github won't let me reopen it...

**Comment by sbrannen** [comment]
This feature was also considered in conjunction with the initial implementation for #25616.

**Comment by rstoyanchev** [comment]
Scheduling for 6.0 with a chance to explore a backport to 5.3.x.

**Comment by archiecobbs** [comment]
Woo-hoo! Just in time for it's 10th birthday on Sunday :)

Seriously, this is why I love Spring - most projects would never bother to fix a 10 year old minor feature request.
