### ISSUE TITLE
Avoid repeated attempts to load a failing `ApplicationContext` in the TestContext framework [SPR-9548]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14182]
**[Mukarram Baig](https://jira.spring.io/secure/ViewProfile.jspa?name=kilokahn)** opened **[SPR-9548](https://jira.spring.io/browse/SPR-9548?redirect=false)** and commented

Lets say I have a test class called `ServiceTest` with three test methods `test1`, `test2`, and `test3`. All three methods use some resources which are provided by Spring. In the current state of affairs, if there is a problem with the loading of the spring context, the context load is retried for each test method.

Is there a way that I can have it aborted on the first failure itself with existing hook-ins?

There might be good reasons behind it - but I fail to appreciate it. Any pointers would be helpful.

The real problem is that the context load takes a few minutes, and it is useless to keep reattempting to load the context if it has already failed for the first time and only seeks to prolong the time that the CI server takes to report failures.

I was thinking of having an `attemptMap` in `ContextCache` that the `TestContext` modifies when it encounters a failed `ApplicationContext`. A repeated load will be (on an opt-in flag set) disallowed via an exception. I have attached a rudimentary patch to indicate what I meant. Sorry that I haven't tested it (don't have gradle installed or an IDE plugin that can do it for me - am still a maven boy :))

---

**Affects:** 3.1 GA

**Reference URL:** http://stackoverflow.com/questions/11202535/ability-to-avoid-repeated-load-of-application-context-in-spring-testcontext-via

**Attachments:**
- [spring-test.patch](https://jira.spring.io/secure/attachment/20002/spring-test.patch) (_3.72 kB_)

6 votes, 8 watchers

**Comment by sbrannen** [comment]
Related Issues:

- https://github.com/spring-projects/spring-boot/issues/24888

**Comment by HzjNeverStop** [comment]
Is there any progress on this issue? Will it be implemented in spring framework 6.1？

**Comment by snicoll** [comment]
@sbrannen is there a reason this issue is moved from one milestone to the next? (see history). I think we've decided to use `x Backlog` for this.

**Comment by sbrannen** [comment]
> I think we've decided to use `x Backlog` for this.

I moved it to `6.0.x` last October: https://github.com/spring-projects/spring-framework/issues/14182#event-7555188932.

**Comment by sbrannen** [comment]
If you've voted for this issue, you'll be happy to know that...

Spring Framework 6.1 will finally have "test context failure threshold" support! 🍃 🥳

It's been a long time coming, but you can now rest assured that your test suite won't take forever due to failing `ApplicationContext` configuration.

Docs: https://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/testing/testcontext-framework/ctx-management/failure-threshold.html

Commit: https://github.com/spring-projects/spring-framework/commit/c5eb4ed978892aa9d005f99f1326f2318571706e
