### ISSUE TITLE
@Transactional with txManager name is cumbersome with base dao classes [SPR-9661]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#14295]
**[matthew inger](https://jira.spring.io/secure/ViewProfile.jspa?name=mattinger)** opened **[SPR-9661](https://jira.spring.io/browse/SPR-9661?redirect=false)** and commented

By embedding the transaction manager name in the `@Transactional` anotations, using base dao classes is cumbersome.  Example:

`@Transactional`
public class GenericDao<K extends Serializable,E> {
protected Class\<E> mappedClass;
protected SessionFactory sessionFactory;

    public GenericDao(Class<E> mappedClass, SessionFactory sessionFactory) {
        this.mappedClass = mappedClass;
        this.sessionFactory = sessionFactory;
    }
    
    @Transactional(readOnly=false)
    public E getById(K key) {
        return sessionFactory.getCurrentSession().get(mappedClass, key);
    }
    
    public E merge(E entity) {
        return sessionFactory.getCurrentSession().merge(entity);
    }

}

Now we have two subclasses, each of which will use different sessionfactory, and transaction manager (we don't need jta).

`@Transactional`("fooTxManager")
public class FooDao extends GenericDao<Long, Foo> {
...
}

`@Transactional`("barTxManager")
public class FooDao extends GenericDao<Long, Foo> {
...
}

The problem is that we'd have to override the getById() method otherwise that method will use the default transaction manager.  Not a big deal with 1 method, but it is a big deal when there's a bunch of methods.

`@Transactional`("barTxManager")
public class FooDao extends GenericDao<Long, Foo> {
`@Override`
`@Transactional`("barTxManager")
public Foo getById(Long key) {
return super.getById(key);
}
...
}

I think a better approach would be to either:

a) Allow the transaction manager name, when left blank, to fallback to the annotation at the class level.
b) Separate the transaction semantics from the manager name with a new annotation:

`@TransactionManager`("barTxManager")

---

**Affects:** 3.1.1

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by elab** [comment]
I have exact the same problem when trying to reuse methods from the base DAO class with transaction manager of the concrete DAO class. How to achieve that?

The workaround by @mattinger from 2012 is unfortunately not working anymore due to multiple changes in the Spring code.

Related: #14011
