### ISSUE TITLE
Support setting threadNamePrefix in the <task:executor> XML tag [SPR-9737]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14371]
**[Archie Cobbs](https://jira.spring.io/secure/ViewProfile.jspa?name=archie172)** opened **[SPR-9737](https://jira.spring.io/browse/SPR-9737?redirect=false)** and commented

The `<task:executor id="foo">` XML element automatically sets the thread name prefix to `foo-`.

This is usually sufficient, but I have a need to set a different thread name prefix from the bean name.

Request support for e.g. `<task:executor id="foo" threadNamePrefix="bar-">` which would set the thread name prefix to `bar-` for that executor.

---

**Affects:** 3.1.2

**Comment by archiecobbs** [comment]
> Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

... except Github won't let me reopen it...

**Comment by rstoyanchev** [comment]
Considering this is an old issue, today we would expect this to be declared in Java config. Can you clarify if this is still relevant and if so why? Generally, we don't intend to add additional attributes to the XML namespace.

**Comment by snicoll** [comment]
We have no plans to deprecate and/or remove xml configuration, but we don't plan to make additional changes to it so I am going to close this.
