### ISSUE TITLE
Override toString() in out-of-the-box implementations of SqlParameterSource [SPR-9753]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#14387]
**[João Loureiro](https://jira.spring.io/secure/ViewProfile.jspa?name=jloureiro)** opened **[SPR-9753](https://jira.spring.io/browse/SPR-9753?redirect=false)** and commented

MapSqlParameterSource and BeanPropertySqlParameterSource should override toString() appropriately, that is, the returned string should represent the object in terms of the parameter values it contains (at least; optionally, the types as well). The returned string can use a Map-like representation.

---

**Affects:** 3.2 M1

**Reference URL:** http://static.springsource.org/spring/docs/current/javadoc-api/org/springframework/jdbc/core/namedparam/SqlParameterSource.html

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/2080

**Comment by zeeshan58** [comment]
Hi, is anyone working on this issue, because I want to work on it.

**Comment by izeye** [comment]
This seems to be resolved via #2080.

**Comment by snicoll** [comment]
Good catch Johnny!

Duplicate of #2080
