### ISSUE TITLE
provide exact source location for live beans information [SPR-9975]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14609]
**[Martin Lippert](https://jira.spring.io/secure/ViewProfile.jspa?name=mlippert)** opened **[SPR-9975](https://jira.spring.io/browse/SPR-9975?redirect=false)** and commented

To improve the tooling experience around the live beans graph, it would be great to have exact source location information for bean definitions in the live beans information. That would allow us to highlight and navigate directly to the exact position in the source code (or the XML definition) without guessing where it is.

---

**Affects:** 3.2 RC1

**Comment by jhoeller** [comment]
Superseded by #25820.
