### ISSUE TITLE
Add ability to inject dependencies into JUnit 4 `@Rule` and `@ClassRule` instances [SPR-10252]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14885]
**[Eduards Sizovs](https://jira.spring.io/secure/ViewProfile.jspa?name=eduardsi)** opened **[SPR-10252](https://jira.spring.io/browse/SPR-10252?redirect=false)** and commented

In some situations it's convenient to inject dependencies into JUnit's `@Rule` and `@ClassRule` managed class' instances. Currently it can be achieved by extending `DependencyInjectionTestExecutionListener` (DITEL) with additional logic that looks for `@Rule` and `@ClassRule` fields and autowires them the same way as test instance is autowired. Even given the opportunity to extend class, I consider this functionality common enough.

---

**Affects:** 3.2.1

**Issue Links:**
- #20481 Autowired Rules do not work with SpringClassRule or SpringMethodRule

5 votes, 6 watchers

**Comment by kenwang-okta** [comment]
Any chance of this ever happening?

**Comment by eschulma** [comment]
I would love to know how this could work for `@ClassRule`.

**Comment by sbrannen** [comment]
> I would love to know how this could work for `@ClassRule`.

I've not implemented it, but in theory it should work the same as the code in `DependencyInjectionTestExecutionListener.injectDependencies()` except that the `bean` would be the value of the `@ClassRule` field.

**Comment by sbrannen** [comment]
Since the community has not displayed much interest in this feature over the years, I am closing this issue.

However, if you are using JUnit Jupiter instead of JUnit 4, please note that JUnit Jupiter extensions can access the `ApplicationContext` via `SpringExtension.getApplicationContext(...)` and directly retrieve the beans they need.
