### ISSUE TITLE
Allow Application Server to Supply Annotation Scanning [SPR-10354]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14986]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[SPR-10354](https://jira.spring.io/browse/SPR-10354?redirect=false)** and commented

These days every container has to do component scanning because more or less every EE specification — even servlets — requires the application server to discover classes annotated in a special way.

Since the application server controls the class loaders and deployments it's able to do so in an a reliable, stable and possibly more performant way compared to Spring. As application severs are beginning to fight over start up performance this an area that receives a lot of attention. Some like JBoss even go so far as to allow you to provide an [index](https://github.com/jbossas/jandex) build at compile time to speed this up even further.

As Spring has always been about taking advantage of services provided by applications servers in a portable way that doesn't lock you in I think you would be a great feature.

---

**Issue Links:**
- #16509 Spring-specific index file for component candidate classes

0 votes, 5 watchers

**Comment by jhoeller** [comment]
With spring-context-indexer and AOT processing, it looks externally provided annotation scanning is not in demand anymore, in particular not in a Spring Boot environment.
