### ISSUE TITLE
spring-core-sources JAR should include complete ASM, CGLIB, and Objenesis sources [SPR-10407]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#15040]
**[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch)** opened **[SPR-10407](https://jira.spring.io/browse/SPR-10407?redirect=false)** and commented

Now that Spring repacks asm and cglib in it we should include the source files in the spring-core sources to make debugging easier. There may be licensing issues that we need to look into before doing this.

PS: asm does not include debug info, but the best we can do short of recompiling it is include the source files. From the [developer guide](http://asm.ow2.org/doc/developer-guide.html#building):

> Note: by default tests are run with the optimized ASM classes, which do not contain debug info.

---

**Affects:** 3.2.2

**Comment by bclozel** [comment]
Unless I'm missing something, the `spring-core-6.1.0-SNAPSHOT-sources.jar` contains sources for ASM, cglib, javapoet and objenesis. Closing this issue as a result.
