### ISSUE TITLE
Injecting EntityManagers through constructor injection (and at non-@PersistenceContext injection points in general) [SPR-10443]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#15076]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[SPR-10443](https://jira.spring.io/browse/SPR-10443?redirect=false)** and commented

Currently you can inject any Spring bean into clients through constructor injection. A JPA `EntityManager` is an exception to that. Constructor injection has the benefit of being able to design classes in an immutable way. Also, you communicate required dependencies through it easily. Sadly, `@PersistenceContext` cannot be used on a constructor parameter and this probably won't change befor JPA 2.2 (giving 2.1 is close to final).

It would be cool to simply be able to inject `EntityManager` instances through either `@Autowired` or `@Inject`.

---

**Issue Links:**
- [DATAJPA-445](https://jira.spring.io/browse/DATAJPA-445) Enable support to inject EntityManager via constructor

12 votes, 17 watchers

**Comment by lucasoares** [comment]
Will this be fixed anytime soon?
