### ISSUE TITLE
Reconsider whether to generally allow bean overriding by name [SPR-10808]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#15434]
**[Emerson Farrugia](https://jira.spring.io/secure/ViewProfile.jspa?name=mers)** opened **[SPR-10808](https://jira.spring.io/browse/SPR-10808?redirect=false)** and commented

I've hit an issue where a single component scan was finding two `@Beans` with the same name. The beans weren't intentionally named the same, it was just an oversight. The container initialised one bean and ignored the other, logging at info instead of warn. The logging level is the first problem, since logging at info makes it much more likely the message is missed. The second problem is that the ignored bean was explicitly marked as `@Primary`. I've attached files with an example.

As far as I can tell, there's no way to control which bean gets picked in this situation. `@Order` on the `@Configuration` doesn't help.

In terms of fixes, I suggest the info message gets changed to warning. I'd personally even go one further. Given the functionality of `@Profile`, `@Primary`, and that autowiring by type is encouraged, does bean overriding still make sense in 3.1+.x? `@Profile` and `@Primary` give us a deterministic way of controlling autowire candidates. In contrast, quiet non-deterministic overrides by name seem too fragile to fit.

---

**Affects:** 3.2.3

**Attachments:**
- [Bar.java](https://jira.spring.io/secure/attachment/21323/Bar.java) (_101 bytes_)
- [BarConfiguration.java](https://jira.spring.io/secure/attachment/21321/BarConfiguration.java) (_446 bytes_)
- [Foo.java](https://jira.spring.io/secure/attachment/21324/Foo.java) (_101 bytes_)
- [FooConfiguration.java](https://jira.spring.io/secure/attachment/21322/FooConfiguration.java) (_378 bytes_)
- [Launcher.java](https://jira.spring.io/secure/attachment/21326/Launcher.java) (_712 bytes_)
- [SomeInterface.java](https://jira.spring.io/secure/attachment/21325/SomeInterface.java) (_90 bytes_)

**Issue Links:**
- #11690 Allow `@Bean` methods to override definitions in XML
- #12263 When a bean definition is overridden, detect whether the definition has changed and log accordingly
- #15236 Allow `@Bean` to override a dynamically registered bean definition
- #18552 `@Primary` annotation is not working for beans with the same name
- #17527 Regression: `@Primary` annotation not working when overriding bean definition with classpath scanning
- #19229 Auto-resolve bean name conflicts for scanned classes

2 votes, 7 watchers

**Comment by bclozel** [comment]
See spring-projects/spring-boot#13609 - bean overriding has been disabled by default in Spring Boot 2.1.

**Comment by jhoeller** [comment]
Superseded by #31288.
