### ISSUE TITLE
Port @ConditionalOn... from Spring Boot into Spring Core [SPR-10964]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#15592]
**[Eberhard Wolff](https://jira.spring.io/secure/ViewProfile.jspa?name=eberhardwolff)** opened **[SPR-10964](https://jira.spring.io/browse/SPR-10964?redirect=false)** and commented

Spring Boot provides many useful Conditional such as `@ConditionalOnMissingBean`, `@ConditionalOnClass` etc This should really be in the core framework. It would allow to detect the runtime environment (Java EE server? Which Java EE server?) and tweak the configuration accordingly.

---

**Affects:** 4.0 M3

**Issue Links:**
- #20614 Adopt a spring boot Condition  (_**"is duplicated by"**_)
- #15920 Include `@ConditionalOnMissingBean` and `@ConditionalOnClass` from Spring Boot

7 votes, 11 watchers

**Comment by sdeleuze** [comment]
I think this issue and #15920 are duplicated, I propose to keep the later since the description echoes to concerns I have as well.
