### ISSUE TITLE
Contribution documentation [SPR-11133]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#15759]
**[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum)** opened **[SPR-11133](https://jira.spring.io/browse/SPR-11133?redirect=false)** and commented

Currently most/all of the Spring Projects have their own documentation regarding contribution. In some of those valuable information is included (single commit, rebasing etc.) in others it is very short.

It would be an improvement if there would be some general contribution documentation for all the Spring Projects (maybe to reference or include).

---
No further details from [SPR-11133](https://jira.spring.io/browse/SPR-11133?redirect=false)

**Comment by jhoeller** [comment]
Closing this in our issue tracker here since there is no action item for the Spring Framework project, and contribution documentation should have improved overall in the past ten years :-)
