### ISSUE TITLE
Incorrect ContextClassLoader for CommonJ WorkManager worker threads when Quartz Scheduler is used [SPR-11125]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#15751]
**[Peter H](https://jira.spring.io/secure/ViewProfile.jspa?name=mag01)** opened **[SPR-11125](https://jira.spring.io/browse/SPR-11125?redirect=false)** and commented

When Quartz Scheduler is configured to utilize the CommonJ WorkManager, worker (WorkManager) threads have a different ContextClassLoader (CCL) than their caller.
This happens at WebSphere AS at least, not sure about WebLogic.

The reason is that Spring creates the main Quartz thread during scheduler startup (startScheduler method in SchedulerFactoryBean) on its own and that means that this thread is unmanaged.
This unmanaged thread is then used to control the all the Quartz activity and also to send jobs to the WorkManager.
While CCL is propagated properly from the any managed thread to an unmanaged thread, it is not propagated from any unmanaged thread to a managed thread.

This means that while the unmanaged Quartz main thread will have correct CCL, managed WorkManager threads will not. They will get SystemClassLoader instead.

This should be corrected so that jobs can execute with correct CCL and thus especially (hardly modifiable) 3rd party code that may utilizes this class loader won't fail.

Most likely, the run method in the DelegatingWork class should be modified to explicitly propagate the CCL. Also a cleanup action that resets the CCL back at the end of the run would be essential.

---

**Affects:** 3.0.7, 3.2.5

**Reference URL:** https://www.ibm.com/developerworks/community/forums/html/topic?id=7fe9a868-128c-41c2-9cf6-bcc87d9889ab

2 votes, 4 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by mag01** [comment]
Hello,
I'm original reporter of the issue and yes, it's definitely still relevant. I don't seem to be able to directly reopen this issue here though.

**Comment by snicoll** [comment]
@mag01 sorry but with the deprecation of `CommonJWorkManager` in Spring 5.1, and Quartz itself being dormant, we can't really justify spending more time on this.
