### ISSUE TITLE
JMS CachingConnectionFactory monitoring [SPR-11288]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#15912]
**[Ruslan](https://jira.spring.io/secure/ViewProfile.jspa?name=batter)** opened **[SPR-11288](https://jira.spring.io/browse/SPR-11288?redirect=false)** and commented

Hi,
we're using CachingConnectionFactory for JMS vendor specific Connection Factory.
The problem with CachingConnectionFactory is that it does a good thing, but no visibility over it.
Let's say i have 25 threads listening to MQ Queue, transforming messages and resending to 3 endpoints.
Currently all of them (4 endpoints) using same CachingConnectionFactory. Session cache size is 100.
How do i know how many sessions are cached and free at the moment?
* change logging to see TRACE logs (which is not good for Prod investigations)
* have public method returning LinkedList\<Session> size.
  Now it's private (Map which holding LinkedLists) so i can't extend to expose it via JMX.

---
No further details from [SPR-11288](https://jira.spring.io/browse/SPR-11288?redirect=false)

**Comment by jhoeller** [comment]
Superseded by #26811.
