### ISSUE TITLE
getBeanNamesForType should consider FactoryBean generics for early introspection of config classes as well [SPR-11480]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16105]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[SPR-11480](https://jira.spring.io/browse/SPR-11480?redirect=false)** and commented

Spring Boot was recently updated to consider FactoryBean generics. This could be ported into `BeanFactoryUtils` if useful.

See https://github.com/spring-projects/spring-boot/pull/355 & https://github.com/spring-projects/spring-boot/commit/5d591edbf81b271fe2b5152f883bc14cb7c4f99c

---

**Affects:** 4.0.2

**Issue Links:**
- #16146 Introspect factory method return type for type variable resolution at injection points
- #18558 Improve target bean type detection for FactoryBeans
- #16461 HttpInvokerProxyFactoryBean and co do not reliably expose correct type when declared via `@Bean`

0 votes, 5 watchers

**Comment by jhoeller** [comment]
Closing this in favor of the more general #18558. Optimized FactoryBean resolution is still a topic to be investigated but I don't see any specific action we can take for this ticket here.
