### ISSUE TITLE
Specify URL encoding on RestTemplate postForObject [SPR-11572]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#16196]
**[Leonard Saers](https://jira.spring.io/secure/ViewProfile.jspa?name=flow)** opened **[SPR-11572](https://jira.spring.io/browse/SPR-11572?redirect=false)** and commented

Thanks for a great work, and a grate framework.

It would be nice if it also was possible to specifying which URL encoding to use.

> Eg.
> The following call will now encode in Unicode. ø will be encoded as %F8
> `templateResult = template.postForObject(uri, parameters, DOMSource.class);`

Suggestion, make it possible to specify encoding:

> Eg.
> The follwing call should then encode in UTF-8. ø will be encoded as %C3%B8
> `templateResult = template.postForObject(uri, parameters, DOMSource.class,"UTF-8");`

To encode as UTF-8, The only solution now is to build and encode the URL as UTF-8. Then use:

> `templateResult = template.getForObject(uri, DOMSource.class);`

But this approach will not allow one to send UTF-8 encoded post data.

---

**Reference URL:** http://forum.springsource.org/showthread.php?110703-Change-RestTemplate-URL-encoding

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by sante85** [comment]
curl -X POST --header "Authorization: key=...key"     --Header "Content-Type: application/json;charset=ISO-8859-1"     https://fcm.googleapis.com/fcm/send     -d '{"to":"/topics/VgtARwhilq","notification":{"body":"\uD83D\uDD25","content_available":true,"priority":"high","title":"&#128514; "},"data":{"click_action":"FLUTTER_NOTIFICATION_CLICK","body":"\uD83D\uDD25","title":"&#128514; ","content_available":true,"priority":"high"}}

vs rest template not send \uD83D\uDD25 char correctely

**Comment by sante85** [comment]
i have a true example

**Comment by sante85** [comment]
i we want i send server key to test

**Comment by sante85** [comment]
![call with curl](https://user-images.githubusercontent.com/14055863/78966272-a4e5e380-7aff-11ea-8d8c-a58c2506ede2.jpeg)

**Comment by sante85** [comment]
with rest template send unicode char, not emojj
