### ISSUE TITLE
TilesConfigurer not safe to use in multiple DispatcherServlet definitions [SPR-11587]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16211]
**[Torsten Krah](https://jira.spring.io/secure/ViewProfile.jspa?name=tkrah)** opened **[SPR-11587](https://jira.spring.io/browse/SPR-11587?redirect=false)** and commented

Hi,

got some mysterious problem.

Just do a "gradle jettyRunWar" on the attached project and go to `http://localhost:8080/web/view/` and `http://localhost:8080/admin/view/` - it will render Apples and Tomatoes.
Stop the stuff and go to the web.xml and remove the comments from load-on-startup of the tomatoes servlet.

If you now go to `http://localhost:8080/web/view/` you get

```
javax.servlet.ServletException: Could not resolve view with name 'admin-index' in servlet with name 'apples'
```

I don't know exactly what the error is - but in another project we got 3 DispatcherServlets in one web.xml which are all mapped to different URLs and each got its own Tiles definitions.
Only one Servlet can found its mappings, the other Servlets fails to find their views.

It maybe related to `SpringWildcardServletTilesApplicationContext` which uses the ServletContext to store things (or the app key which is null) - but that only a guess, still searching the exact cause.

---

**Affects:** 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6

**Reference URL:** https://github.com/spring-projects/spring-framework/pull/1355

**Attachments:**
- [playground.tar.bz2](https://jira.spring.io/secure/attachment/21832/playground.tar.bz2) (_7.13 kB_)

**Comment by tkrah** [comment]
@jhoeller Any news here?

**Comment by rstoyanchev** [comment]
Closing since Tiles support has been dropped for 6.0 with #27423.
