### ISSUE TITLE
"org.springframework.beans.factory.support.DefaultListableBeanFactory", loaded by "org.apache.catalina.loader.StandardClassLoader" occupy 1,493,680,816 bytes [SPR-11612]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#16235]
**[Siva](https://jira.spring.io/secure/ViewProfile.jspa?name=kbsivacse)** opened **[SPR-11612](https://jira.spring.io/browse/SPR-11612?redirect=false)** and commented

We are noticing a memory leak and Spring objects loaded by system classloader are occupying 1.4 GB of memory.

"org.springframework.beans.factory.support.DefaultListableBeanFactory", loaded by "org.apache.catalina.loader.StandardClassLoader" occupy 1,493,680,816 (65.82%) bytes

---

**Affects:** 3.2.2

**Attachments:**
- [Dominator Tree.png](https://jira.spring.io/secure/attachment/21892/Dominator+Tree.png) (_62.17 kB_)
- [Dominator Tree 2.png](https://jira.spring.io/secure/attachment/21893/Dominator+Tree+2.png) (_30.81 kB_)
- [Histogram.png](https://jira.spring.io/secure/attachment/21891/Histogram.png) (_10.09 kB_)

3 votes, 9 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by hassibnkhoury** [comment]
so what is the solution? i am using the latest version of spring boot 3.2.1 and still the issue of memory appears:
One instance of “org.springframework.beans.factory.support.DefaultListableBeanFactory” loaded by “org.springframework.boot.loader.launch.LaunchedClassLoader @ 0xf006e300” occupies 1,025,792 (11.57%) bytes. The memory is accumulated in one instance of “org.springframework.beans.factory.support.DefaultListableBeanFactory”, loaded by “org.springframework.boot.loader.launch.LaunchedClassLoader @ 0xf006e300”, which occupies 1,025,792 (11.57%) bytes.

Keywords
org.springframework.beans.factory.support.DefaultListableBeanFactory
org.springframework.boot.loader.launch.LaunchedClassLoader
