### ISSUE TITLE
@Value annotation should be able to inject List<String> from YAML properties [SPR-11759]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#16381]
**[Adam Berlin](https://jira.spring.io/secure/ViewProfile.jspa?name=aberlin@pivotallabs.com)** opened **[SPR-11759](https://jira.spring.io/browse/SPR-11759?redirect=false)** and commented

Yaml file
&mdash;

```
 
foobar:  
  ignoredUserIds:
    - 57016311
    - 22588218
```

Class
&mdash;

```
 
    
public class Foobar {
    @Value("${foobar.ignoredUserIds}")
    List<String> ignoredUserIds;
}
 
```

Error
&mdash;

```
 
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.util.List foobar.Foobar.ignoredUserIds; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'foobar.ignoredUserIds' in string value "${foobar.ignoredUserIds}"

```

---

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/501

21 votes, 21 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by abccbaandy** [comment]
2019 and I need this feature.
`@Value` >>>>> `@ConfigurationProperties` when there is only one field :
`private List<String> someList;`

Why I need a Class when I only have one field?

**Comment by komidawi** [comment]
2021 and it's still needed 😉

**Comment by mimfgg** [comment]
how hard can it be ... a bit later in 2021 and still stumbling on this ...

**Comment by biuwsi** [comment]
Damn, spend 2 hours to find out, that it's not I am dumb ass, it's just a "feature"!

**Comment by devdynam0507** [comment]
2022 it's still needed 😀

**Comment by alexeytokar** [comment]
2023 ;)

**Comment by xzxiaoshan** [comment]
2023.11.2 Needed, looking forward to early support

**Comment by eritpchy** [comment]
2024😩

**Comment by chillb0nes** [comment]
+1 for this

**Comment by marcelstoer** [comment]
This just got me... The current behavior is inconsistent and totally unexpected. Further up it says

> Please, reopen if still relevant.

but none of us affected (no even the OP) can reopen it because it was created by bot.
