### ISSUE TITLE
Asynchronous method execution is always invoked before bean validation [SPR-11775]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16397]
**[baymon](https://jira.spring.io/secure/ViewProfile.jspa?name=baymon)** opened **[SPR-11775](https://jira.spring.io/browse/SPR-11775?redirect=false)** and commented

I want to use `@validated` on a `@Service` bean in combination with `@Async` methods. But the `order` property of my `MethodValidationPostProcessor` has no effect to the execution order of the validation interceptor. So a validation exception is always thrown within the new thread and never given to the caller.

I don't see any (working) way to configure the execution order of the method interceptors.

---

**Affects:** 4.0.4

**Reference URL:** https://github.com/spring-projects/spring-framework-issues/pull/77

**Issue Links:**
- #13635 Spring `@Async` should have some way of specifying UncaughtExceptionHandler
- #19878 MethodValidationPostProcessor not respecting aspect order

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/cee53e9330b1677921b466e255751dd28d0b4207

0 votes, 5 watchers

**Comment by snicoll** [comment]
I am wondering if that's something we could specify on `@EnableAsync`, a boolean flag that would explain a bit more high-level what the outcome is going to be. WDYT @jhoeller?

**Comment by jhoeller** [comment]
On review, I'm not convinced we should be making a different async-vs-validation order configurable at a first-class level. After all, regular programmatic assertions against incoming parameters are also only executing in the async thread in this case, and we generally recommend such programmatic assertions over declarative validation for such invocation parameter purposes.

If validation (whether programmatic or declarative) is expected to happen in the caller's thread, the invocation could also be split into two methods: one that validates/sanitizes the input in an entry-point facade and then delegates to another component/method for the actual async execution.
