### ISSUE TITLE
Provide a way to override annotated controllers (possibly reusing @Primary annotation?) [SPR-11809]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#16429]
**[Davide Cavestro](https://jira.spring.io/secure/ViewProfile.jspa?name=davide.cavestro)** opened **[SPR-11809](https://jira.spring.io/browse/SPR-11809?redirect=false)** and commented

When defining two beans annotated with `@Controller` and providing the same `@RequestMapping` the container throws an exception complaining

> java.lang.IllegalStateException: Ambiguous mapping found. Cannot map 'myStdController' bean method... There is already 'myCustomController' bean method

It would be really useful having a simple way to provide a customized version for a standard controller by simply adding a new controller annotated as `@Primary` and mapping to the same urls.
This kind of customization hack works quite well for beans that don't provide mappings (i.e. services).
An additional refinement could support some sort of overlaying: the urls not remapped by the `@Primary`/custom controller could be served by the standard/secondary controller.
If using `@Primary` for this purpose is considered unsafe, then an additional annotation could expose this behavior.

---

**Affects:** 3.2.8

3 votes, 5 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by a-sayyed** [comment]
In case someone is still looking for a workaround for this issue:
What you need to do, is deregister the existing handler methods from the other controller, and register your (new) handler method instead. This could be done as follows:
```java
    @Autowired
    public void registerOverriddenControllerEndpoint(final RequestMappingHandlerMapping handlerMapping,
            final NewController controller) throws NoSuchMethodException {

        final RequestMappingInfo mapping = RequestMappingInfo.paths("path/to/be/overridden")
           .methods(RequestMethod.GET) // or any other request method
           .build();

        handlerMapping.unregisterMapping(mapping);
        Class[] argTypes = new Class[]{/* The parameter types needed for the 'methodThatHandlesTheEndpoint' method */};
        handlerMapping.registerMapping(mapping, controller, NewController.class.getMethod("methodThatHandlesTheEndpoint", argTypes));
    }

    @Bean
    NewController httpAdapterResource2() {
        return new NewController();
    }
```
