### ISSUE TITLE
Bean Validation invocation API for use with individual values and constraints [SPR-11900]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16519]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-11900](https://jira.spring.io/browse/SPR-11900?redirect=false)** and commented

The logic in MethodValidationInterceptor is pretty useful. However it is currently not easy to use if not in the context of AOP method interception. I'd like to be able to use it for invoking an `@MVC` HandlerMethod with the ability to validate method arguments first and then the method return value as a separate step.

---

**Affects:** 4.0.5

**Issue Links:**
- #15017 Random results for JSR-303 method constraint validation on generically typed methods
- #18007 `@Validated` support on Iterables (and implementors)
- #19182 Validate values in top-level Map parameters

10 votes, 12 watchers

**Comment by jhoeller** [comment]
Superseded by #30645.
