### ISSUE TITLE
Introduce proxy-based REST client similar to HttpInvokerProxyFactoryBean [SPR-12131]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16747]
**[George Georgovassilis](https://jira.spring.io/secure/ViewProfile.jspa?name=g.georgovassilis)** opened **[SPR-12131](https://jira.spring.io/browse/SPR-12131?redirect=false)** and commented

This ticket proposes a new component that will work similarly to HttpInvokerProxyFactoryBean and allows binding a java interface to a remote REST/JSON service. Annotations on the interface and its methods would define the mapping of method invocations to concrete HTTP requests to the REST service.

The component would be a proxy factory which is given the mapping (possibly via a class name) and returns proxies which pass method invocations to the remote REST service.

For a possible implementation see https://github.com/ggeorgovassilis/spring-rest-invoker

---

**Affects:** 4.0.6, 4.3.3

**Reference URL:** https://groups.google.com/forum/#!topic/spring-framework-contrib/HTja1bE1TWY

**Issue Links:**
- #10929 Spring MVC REST: Provide interface definition model for generating HTTP client interface proxies wrapping RestTemplates (_**"duplicates"**_)
- #15682 Enable REST controller method parameter annotations on an interface
- #22154 `@RequestMapping` without `@Controller` registered as handler
- #16827 Consider reusing `@RequestMapping` annotations as an interface for HTTP clients
- #16712 Read RestTemplate Accept header from entity annotation

4 votes, 9 watchers

**Comment by rstoyanchev** [comment]
Superseded by #28386
