### ISSUE TITLE
Support for JSR-330 (DI for Java) 2.0 [SPR-12211]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16825]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-12211](https://jira.spring.io/browse/SPR-12211?redirect=false)** and commented

There are ongoing discussions towards a revision of JSR-330, in alignment with CDI 2.1.

---

0 votes, 6 watchers

**Comment by jhoeller** [comment]
Superseded by the Jakarta migration: #25354
