### ISSUE TITLE
Support @Profile + @PostConstruct/@PreDestroy [SPR-12433]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#16902]
**[Mordechai Tamam](https://jira.spring.io/secure/ViewProfile.jspa?name=mordechai.tamam@gmail.com)** opened **[SPR-12433](https://jira.spring.io/browse/SPR-12433?redirect=false)** and commented

I have a use case that I need a custom bean initialization for each profile, there fore I would like to have the ability to control the `@PostConstruct` initialization methods.

---
No further details from [SPR-12433](https://jira.spring.io/browse/SPR-12433?redirect=false)

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by marwin1991** [comment]
Would be nice to have this feature
