### ISSUE TITLE
Enable use of Servlet 3.1 Async I/O in SockJS server [SPR-12427]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#17033]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-12427](https://jira.spring.io/browse/SPR-12427?redirect=false)** and commented

---

**Affects:** 4.1.2

**Issue Links:**
- [SEC-2786](https://jira.spring.io/browse/SEC-2786) Allow use of Spring Security filters in applications that make use of Servlet 3.1 Async I/O  (_**"depends on"**_)

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/ab629a0e26d892404e8d29e74c13f97b8d0b4d34, https://github.com/spring-projects/spring-framework/commit/43d93712f1a827cf00a9b097dd546320ce841692

1 votes, 5 watchers

**Comment by rstoyanchev** [comment]
In practice this means re-writing or replicating the SockJS support.
