### ISSUE TITLE
GenericTypeResolver should be able to introspect generic arguments from lambdas [SPR-12525]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17130]
**[Artem Bilan](https://jira.spring.io/secure/ViewProfile.jspa?name=abilan)** opened **[SPR-12525](https://jira.spring.io/browse/SPR-12525?redirect=false)** and commented

See the external linked discussion.
The original issue is here: http://stackoverflow.com/questions/23863716/java-how-to-resolve-generic-type-of-lambda-parameter and its related SO question.
I can confirm that using that `typetools` in the Spring Integration Java DSL I can avoid an extra type parameter.
From this:

```java
.handle(Integer.class, (p, h) -> p * 2)
```

to this:

```java
.<Integer>handle((p, h) -> p * 2)
```

This fix allow us to fix other Lambda issues, e.g. #15303

---

**Reference URL:** https://github.com/jhalterman/typetools/issues/4

**Issue Links:**
- #18273 ResolvableType should support resolving lambda types (_**"duplicates"**_)
- #15303 Inferring an ApplicationListener's event type from a lambda or method reference
- #16427 `@Aspect` aspect not correctly applied to Java 8 lambda-defined `@Beans`
- #18681 Wrong detection of event type on ApplicationListener<> when using lambdas (ClassCast Exception)

0 votes, 8 watchers

**Comment by 8-bitLincoln** [comment]
Looks like https://github.com/jhalterman/typetools has resolved this problem

**Comment by sbrannen** [comment]
> Looks like [jhalterman/typetools](https://github.com/jhalterman/typetools) has resolved this problem

Well, that my be true but unfortunately only for Java 8 and 9.

> Lambda type argument resolution is currently supported for:
> * Oracle JDK 8, 9
> * Open JDK 8, 9

Source: https://github.com/jhalterman/typetools#on-lambda-support

So, that's not a valid option.

**Comment by sdeleuze** [comment]
I don't think Spring can build a feature that can cover all the lambdas use cases and JDK versions in a non brittle way, so I decline this feature request.
