### ISSUE TITLE
Exception thrown by TransactionSynchronization#afterCompletion is eaten and there is no way to catch and perform any operation [SPR-12560]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17162]
**[Mohammad](https://jira.spring.io/secure/ViewProfile.jspa?name=adnan)** opened **[SPR-12560](https://jira.spring.io/browse/SPR-12560?redirect=false)** and commented

Exception thrown in TransactionSynchronization's afterComplete method doesn't be propagated back to calling method. Reason is org.springframework.transaction.support.TransactionSynchronizationUtils class invokeAfterCompletion has below implementation -

> public static void invokeAfterCompletion(List\<TransactionSynchronization> synchronizations, int completionStatus) {
> if (synchronizations != null) {
> for (TransactionSynchronization synchronization : synchronizations) {
> try {
> synchronization.afterCompletion(completionStatus);
> }
> catch (Throwable tsex) {
> logger.error("TransactionSynchronization.afterCompletion threw exception", tsex);
> }
> }
> }
> }

Since it is calling multiple synchronizer in a row hence they are eating exception and just logging it(which is clearly written as java doc). I think there should be a way to throw exception so that if required client code can perform some operation.

One solution would be to run afterComplete method in different threads and propagate exceptions with that thread. For programmatic transaction management, we would get know exception (Considering declarative transaction interceptors would not help as control won't come to client code)

Reference question in stackoverflow is - http://stackoverflow.com/questions/27563561/transactionsynchronization-sallow-runtimeexception-that-is-thrown-while-aftercom?noredirect=1#comment43558721_27563561

---

**Affects:** 4.0.3

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by slinstaedt** [comment]
`org.springframework:spring-tx:jar:5.3.18` which should be part of spring boot 2.5.12.

**Comment by KSH-code** [comment]
it was fixed by https://github.com/spring-projects/spring-framework/pull/30776
so it is included in https://github.com/spring-projects/spring-framework/releases/tag/v6.0.11 and https://github.com/spring-projects/spring-framework/releases/tag/v5.3.29

**Comment by bclozel** [comment]
Thanks @KSH-code !

While the original issue was more about making that exception available through a callback of some sort, the reason for reopening it is indeed about the logging level.

Closing this issue as a superseded by #30776

**Comment by stefanrybacki** [comment]
still relevant, logging alone does not help
