### ISSUE TITLE
Add MQTT over WebSocket support [SPR-12581]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17182]
**[pascal gehl](https://jira.spring.io/secure/ViewProfile.jspa?name=paskos)** opened **[SPR-12581](https://jira.spring.io/browse/SPR-12581?redirect=false)** and commented

STOMP over websocket is really nice as starting point but for resource-constrained devices and low bandwidth (lots of mobile out there running on small data plans and not necessarily 4G) it would be nice to be able to choose MQTT instead of STOMP when implementing websocket based messaging.

---

**Issue Links:**
- #16288 Support WAMP messaging protocol

6 votes, 17 watchers

**Comment by rstoyanchev** [comment]
Closing as we have no plans to add this.
