### ISSUE TITLE
Add Optional Support to JdbcTemplate [SPR-12662]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17262]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[SPR-12662](https://jira.spring.io/browse/SPR-12662?redirect=false)** and commented

### Problem

From time to time we find ourselves working on queries that may return either one for no row. We feel this situation is currently not well addressed with `JdbcTemplate`. Current options include:

- using `#queryForObject` and catching `EmptyResultDataAccessException`
- using `#query` or `#queryForList` and checking the size of the list

Both of them feel rather cumbersome.

### Proposal

We feel Java 8 Optionals are ideally suited for this problem. We therefore propose to add new `queryForOptional` methods with the following behaviour

* no row: empty Optional
* one row: present Optional
* NULL: empty Optional
* more than one row: IncorrectResultSizeDataAccessException

We feel these semantics are natural match for `Optional`. Mapping both no row and SQL `NULL` to an empty `Optional` may be a bit surprising at first however an `Optional` can not contain Java `null` and returning Java `null` would seem against the sprit of `Optional`. We feel the name fits well into the existing naming pattern and gives users a clear indication of the behaviour to expect without having to read the Javadoc first.

As the master in now on 5 which has a minimum of Java 8 these can be added directly to `JdbcTemplate`.

---

**Issue Links:**
- #18474 Add iterable JDBC template to process large amount of data
- #20599 Customize PreparedStatementCreatorFactory in getPreparedStatementCreator

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/724

13 votes, 15 watchers

**Comment by zimmi** [comment]
@jhoeller If you don't mind, can you talk about the current plans on this? If a new abstraction is to be introduced, a possible inspiration could be [fluent-jdbc](https://github.com/zsoltherpai/fluent-jdbc). I find its API to be quite usable.

**Comment by rstoyanchev** [comment]
Closing as discussed under #724. For the time being we have no plans to introduce a fluent alternative, that is other than the R2DBC `DatabaseClient`.
