### ISSUE TITLE
Ability to query an ApplicationContext for annotations on a bean [SPR-12929]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17522]
**[Andres Almiray](https://jira.spring.io/secure/ViewProfile.jspa?name=aalmiray)** opened **[SPR-12929](https://jira.spring.io/browse/SPR-12929?redirect=false)** and commented

Currently the ApplicationContext is capable of resolving beans and beans names given an annotation but the reverse is not, that is, obtain an annotation given a bean name.

Currently annotation metadata is harvested and stored in `org.springframework.core.type.AnnotationMetadata` but the actual annotation is not.

For reference, this feature was discussed with Jürgen at Voxxed Days Ticino 2015 in the context of a generic, external JSR-330 compatible API on top of Spring and Guice.

---

**Affects:** 4.1.6

**Issue Links:**
- #17723 Support dynamic bean lookup a la CDI's Instance type
- #13532 Convenient programmatic bean retrieval with qualifiers

2 votes, 4 watchers

**Comment by SaiKrishnaKaushik** [comment]
Hi Is this still a requirement and there is a need for it?
