### ISSUE TITLE
Support caching annotations for `CompletableFuture` return values [SPR-12967]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17559]
**[Lukas Krecan](https://jira.spring.io/secure/ViewProfile.jspa?name=dart0)** opened **[SPR-12967](https://jira.spring.io/browse/SPR-12967?redirect=false)** and commented

It would be nice to support caching of ListenableFuture (CompletableFuture) results. Imagine that your method returns ListenableFuture and you want to cache the result (not the future itself). If I am not mistaken it is not currently supported.

I may send you a pull request, but I'd like to hear if it makes sense. It may be a bit confusing since the cache would be filled/evicted not upon the method exit but upon the future completion.

---

**Affects:** 4.1.6

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by jhoeller** [comment]
As explained in #17920 (specifically https://github.com/spring-projects/spring-framework/issues/17920#issuecomment-1646004504), we have a `CompletableFuture` based arrangement with the Caffeine AsyncCache as a primary provider now. That effort comes with equivalent reactive support but can be used standalone with just `CompletableFuture` as well, effectively addressing this ticket here too.
