### ISSUE TITLE
Introduce `AutodetectMode` enum for `MBeanExporter` [SPR-13137]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17728]
**[Mathieu Lachance](https://jira.spring.io/secure/ViewProfile.jspa?name=matlach)** opened **[SPR-13137](https://jira.spring.io/browse/SPR-13137?redirect=false)** and commented

It would be nice for the MBeanExporter#setAutodetectMode to accept a newly created enum for AutodetectMode.

The work has been done for MBeanExporter#setRegistrationPolicy but not for AutodectMode.

If you have a look at RegistrationPolicy#valueOf it re-use the MBeanRegistrationSupport constants. To keep backward compatibility we could leverage the same pattern and/or maybe consider to ditch the pattern as it's already marked with `@Deprecated`.

---

**Affects:** 4.1.6

**Issue Links:**
- #13583 Introduce `@EnableMBeanExport` equivalent to <context:mbean-export>

**Comment by jhoeller** [comment]
As part of #30874, we rather intend to reduce the number of options on `MBeanExporter`, deprecating the constants and reducing autodetection to a boolean flag.
