### ISSUE TITLE
Upgrade core framework build to JDK 17

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17778]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-13186](https://jira.spring.io/browse/SPR-13186?redirect=false)** and commented

#### Resources

- [JDK 9 early access builds](https://jdk9.java.net/download/)
- [Gradle 3.0 nightly builds](http://gradle.org/gradle-nightly-build/)
  - [nightly release notes](https://docs.gradle.org/nightly/release-notes)
- [Gradle JDK 9 Support](https://github.com/gradle/gradle/blob/master/design-docs/jdk9-support.md) wiki page

---

**Issue Links:**
- #17928 Compatibility with merged JDK 9 mainline (_**"depends on"**_)
- #19138 Upgrade build to Gradle 3.0 (_**"depends on"**_)
- #18092 Remove AbstractJpaTests and revise spring-orm test suite accordingly (_**"depends on"**_)
- #18079 Declare Spring modules with JDK 9 module metadata (_**"is depended on by"**_)
- #17779 Support for new JDK 9 HTTP Client API (_**"is depended on by"**_)

2 votes, 12 watchers

**Comment by jhoeller** [comment]
Repurposing this issue for our JDK 17 baseline in Spring Framewor 6.0, the basics have been covered by a few recent commits already, e.g. through #26901.

**Comment by jhoeller** [comment]
Closing this issue for 6.0 M1 since all the basic upgrade is complete.
Further steps towards the Java module system are planned for a later milestone, e.g. #18079.
