### ISSUE TITLE
Adding ConditionalOnProperty to spring-core [SPR-13244]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17835]
**[Meang Akira Tanaka](https://jira.spring.io/secure/ViewProfile.jspa?name=mat013)** opened **[SPR-13244](https://jira.spring.io/browse/SPR-13244?redirect=false)** and commented

This issue seems to be a variant of #16372, however I have created a new feature request as the description is not exactly the same thing.

I would like to suggest that beans can be enabled based upon whether some property or a value is set or not set in the Environment of the application context.

The concrete usage which I have is somewhat related to [SWS-911](https://jira.spring.io/browse/SWS-911), where a URL connection factory has to be created based upon proxy settings in the environment, however I can think that there must be other valid usage scenarios, where beans should be registered based on some settings in the environment.

Currently the spring core already has a limit support for Conditional Bean registration, however this is based on the profile.

It has been argued in #16372 that this feature exists in Spring-boot, however it is not necessary the case that one uses spring-boot.

As an alternative to provide an implementation I would like to suggest that ConditionalOnXX are moved to Spring-core from Spring-boot.

---

**Issue Links:**
- #20614 Adopt a spring boot Condition  (_**"is duplicated by"**_)
- #16372 Add `@Bean` condition based on a SpEL condition

**Comment by sdeleuze** [comment]
Related to #15920, not sure yet if that's a duplicate or not.

**Comment by snicoll** [comment]
It is yes. I think we should bring these somewhat consistently if we ever decided to do so.
