### ISSUE TITLE
Add ListenableScheduledFuture support to TaskScheduler [SPR-13407]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#17987]
**[Kevin Conaway](https://jira.spring.io/secure/ViewProfile.jspa?name=kevinconaway)** opened **[SPR-13407](https://jira.spring.io/browse/SPR-13407?redirect=false)** and commented

[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller) what are your thoughts on adding listenable support for the _TaskScheduler_ interface?  I'm envisioning an _AsyncListenableTaskScheduler_ interface that has _scheduleListenableXXX_ methods that mirror those in _TaskScheduler_ (similar to _AsyncListenableTaskExecutor -> TaskExecutor_)

The use case here is to register callbacks that fire for every execution of the scheduled task.

I'm happy to submit a PR for this if you think it would be worthwhile.  I have written an implementation for for _ListenableScheduledFuture<?> scheduleListenable(Runnable task, Trigger trigger);_ that we're using here but I would like to get a full featured version in to core if possible

---

**Affects:** 4.2 GA

**Issue Links:**
- #19475 Allow ReschedulingRunnable to receive a TriggerContext on creation

**Comment by jhoeller** [comment]
This approach got superseded by the deprecation of `ListenableFuture` in #27780.
