### ISSUE TITLE
@ModelAttribute support to builder pattern [SPR-13415]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#17994]
**[Raffaele Litto](https://jira.spring.io/secure/ViewProfile.jspa?name=r_litto)** opened **[SPR-13415](https://jira.spring.io/browse/SPR-13415?redirect=false)** and commented

Spring `@ModelAttribute` has no way to support builder pattern, unlike support introduced into Jackson: (check http://wiki.fasterxml.com/JacksonFeatureBuilderPattern)

Use cases where this could be worth being useful:

mapping query arguments to bean like in:

`/entity/search?id=23&status=OPEN&pageSize=10&page=1`

to a method like

```java
List<EntityDTO>  searchEntities(HttpServletRequest request, @ModelAttribute
    EntitySearchDTO searchDTO)
```

---

**Reference URL:** http://stackoverflow.com/questions/31141945/cannot-instantiate-a-pojo-with-jackson-3-with-builder-pattern

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by randakar** [comment]
Looks still relevant to me. Especially with lombok's Builder annotation this would be really useful.

**Comment by szewczykdawid** [comment]
Looks relevant to me as well.
