### ISSUE TITLE
Add @FormAttribute attributes to customize x-www-form-urlencoded [SPR-13433]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18012]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[SPR-13433](https://jira.spring.io/browse/SPR-13433?redirect=false)** and commented

As requested on the Spring Boot issue tracker:
https://github.com/spring-projects/spring-boot/issues/3890

&mdash;

When processing an `HttpRequest` with `x-www-form-urlencoded` content, we can use a controller with POJO matching the payload structure.

Example payload: `value_first=value1&value_second=value2`

```java
@RequestMapping(method = RequestMethod.POST, consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
 public String handlePost(@ModelAttribute Body body) {
 }
```

POJO:

```java
public class Body {
 private String value_first;
 private String value_second;
}
```

The problem is that the variable names must match the field names in the `HttpRequest` payload in order  to be processed by the controller. There is not way of naming them differently, for example, if I do not want to use underscores in Java variable and method names.

What I would appreciate would be using something like this:

```java
@FormAttribute
private String value1;
```

---

**Issue Links:**
- #13880 Provide a way to customize the names of JavaBean properties when they're read and written for data binding purposes
- #12403 Provide support for configuring the bindable properties of a form-backing object using field-level annotations
- #14816 Customizable parameter name when binding an object (_**"supersedes"**_)

20 votes, 16 watchers

**Comment by kang0921ok** [comment]
Hi I'm newbie ^^;
I hava a question.
Is that development over?

**Comment by sbrannen** [comment]
> Is that development over?

This issue is still "Open".

**Comment by nuno-aj-aniceto** [comment]
This would be a nice improvement & boost to the framework.

**Comment by HongyiFu** [comment]
No one mentioned hyphens? I feel it's not all that uncommon for a query param to be "team-id". Without this feature, it seems impossible to do this now?

**Comment by xfan-shop** [comment]
I have made a simple example in my project for form data  according to Zhang Jie 's suggestion.
https://stackoverflow.com/questions/38171022/how-to-map-multiple-parameter-names-to-pojo-when-binding-spring-mvc-command-obje/57217544#57217544

**Comment by mattbertolini** [comment]
I was encountering similar issues with query params and form data having different formats to my `@ModelAttribute` property names. I have attempted to solve my problem in a generic Spring-like way. Here is my attempt: https://github.com/mattbertolini/spring-annotated-web-data-binder. Posting here in case someone finds it useful.

**Comment by rstoyanchev** [comment]
Thanks @mattbertolini. Two things I'm wondering about. 

One is nested binding. Taking the Slack commands example from above with keys like `"channel_name"`, it seems unlikely that keys like `"channel.channel_name"` that match to a nested object structure would come into play. In the approach from @dogeared (i.e. converting the form data to a Map, and then using Jackson to map to a higher level Object via JSON) I don't expect that nested bindings would work. I do see that your solution does support nested bindings but is that something you expect as a valid case or is this primarily for binding to a flat object?

Two is the other side of parsing, i.e. formatting and displaying bound values and errors. Would you expect that a `BindingResult` would respect and use the original aliases from which values were bound.

**Comment by mattbertolini** [comment]
Hi @rstoyanchev. Thanks for the questions.

Re: nested binding: You are correct that in the slack commands example nested binding would be unnecessary. My vision for nested bindings was mainly for grouping together similarly linked parameters. More of a logical thing for the engineer than for modeling an external API. I mostly expect the library to be used for flat objects and nested binding to be a niche case. Since I was modeling my library after JAX-RS *Param annotations, I added nested binding in as well. I'm definitely looking for additional use cases for nested binding to highlight in my documentation so if anyone has some I'd love to hear about them.

Re: formatting and errors. You are correct that the `BindingResult` would lose the original aliases and only be aware of the bean property names. That can be confusing when reporting errors from and HTML form. I have worked around this limitation by compensating with more detailed error messages to help the user or engineer. It's not the best solution but it was an acceptable trade-off given the benefits I was getting in return.

I mostly use my approach for API development (`@RestController`) rather than form POSTs inside of browser applications. One of my design goals was to not modify the default behavior of Spring MVC so that the existing `@ModelAttribute` would still work as expected. That way I could mix and match depending on the use case I was encountering. I still use `@ModelAttribute` for a good portion of my web forms as I have control over the HTML as well.

I hope this answers your questions. Thanks for taking a look at my library. Much appreciated.

**Comment by fhansen87** [comment]
+1

**Comment by igorcavalcanti** [comment]
Simpler way:

Controller:

` @PostMapping(value = {"/status"}, consumes = MediaType.APPLICATION_FORM_URLENCODED)
    public ResponseEntity<String> statusWarning(SitefStatusWarningRequest request) {
             return ResponseEntity.ok("OK");
    }`


POJO:
`public class Body {
 private String value1;
 private String value2;

 public Body (String value_first, String value_second) {
    value1 = value_first;
    value2 = value_second;
 }
}`

**Comment by puertajennifer** [comment]
I found this article: [https://www.metakoder.com/blog/parse-snake-case-json-in-spring-boot/](url) I hope this help you as much as it did it to me!

**Comment by puertajennifer** [comment]
I my case, the Json I was receving it's in UpperCamelCaseStrategy, so I added this sentence just above the class definition of the POJO I´m receiving with @RequestBody

@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy.class)
public class MyClass{
}

**Comment by gavenkoa** [comment]
@puertajennifer `@JsonNaming` has nothing with POST form + `x-www-form-urlencoded`. Jackson is not used when you submit a form.

**Comment by gavenkoa** [comment]
Related questions with workarounds:

* https://stackoverflow.com/questions/34945172/binding-snake-case-request-parameters-to-a-spring-form
* https://stackoverflow.com/questions/8986593/how-to-customize-parameter-names-when-binding-spring-mvc-command-objects

I don't like `OncePerRequestFilter` which is global, not per mapping. Or custom `ExtendedServletRequestDataBinder` to accept new find on annotation on form parameters...

**Comment by Nasil** [comment]
I did this:

Controller:
``
@RequestMapping(value = "/slack", method = RequestMethod.POST, consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
public @ResponseBody SlackSlashCommand slack(@RequestBody MultiValueMap<String, String> reqMap) {
      ObjectMapper objectMapper = new ObjectMapper();
      objectMapper.enable(DeserializationFeature.UNWRAP_ROOT_VALUE);
      objectMapper.enable(DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS);
      SlackSlashCommand slackSlashCommand = objectMapper.convertValue(reqMap, SlackSlashCommand.class);
      return slackSlashCommand;
}
``
SlackSlashCommand class use @JsonProperty with underscore.

**Comment by CharlelieBouvier** [comment]
+1

**Comment by Ynnck123** [comment]
+1

**Comment by alex-semenk** [comment]
+1

**Comment by rstoyanchev** [comment]
For 6.1, we've added enhanced support for constructor binding in `DataBinder` including the option to customize the bind value name with an `@BindParam` annotation. For example:

```java
public class SlackSlashCommand {

    private String token;
    private String command;
    private String text;
    private String teamId;
    private String teamDomain;

    public SlackSlashCommand(
            String token, String command, String text, 
            @BindParam("team_id") String teamId, @BindParam("team_domain") String teamDomain) {

        // ...
    }

}
```

In light of this, I am closing this issue as superseded by #30947.

**Comment by gavenkoa** [comment]
@rstoyanchev Could you clarify the solution?

I have a `@Controller` with many `@RequestMapping` inside. Each method has an attribute marked as `@Model`. Should I mark arguments of a single all args constructor for a model with url-encoded names in `@BindParam`?

Like for your example if I write:

```
@PostRequest(path = "/something")
Object process(@Model SlackSlashCommand command) { ... }
```

for my POST form with `x-www-form-urlencoded` tring MVC will set `command.teamId` to `team_id` from a form?

**Comment by rstoyanchev** [comment]
@gavenkoa, yes that's how it is expected to work. Just minor note that it's `@ModelAttribute` rather than `@Model`.

**Comment by nkavian** [comment]
Does this solution support binding individual fields? Using / forcing a constructor is not ideal. For example, an object that uses Lombok, Jackson, or requires other annotations, versus the stated solution would funnel the fields through a constructor. I know they are slightly different concerns but it makes it harder to get them to work together.

```
@Data
public class Account {

    @BindParam("account_id") <--- Is this supported
    @JsonProperty("account_id")
    private String accountId;

}
```

**Comment by nkavian** [comment]
Thanks for replying. `@Data` does not give you a constructor you can annotate. The point of using Lombok was to write less boilerplate code. Lombok does have an `@AllArgsConstructor` but again that hides the actual boilerplate.

While `@BindParam` is `a` solution; it doesn't feel like it is `the` solution.
- Not using the `@BindParam` solution requires less code.
- Less code implies it's cleaner and potentially more safer to stick with.

**Comment by rstoyanchev** [comment]
What I said is that you do _not_ need to annotate the constructor, and also that you do _not_ need to use `@BindParam`.

**Comment by nkavian** [comment]
> A constructor is required and I think @Data gives you that.

Lombok doesn't provide a constructor.

**Comment by rstoyanchev** [comment]
Sorry, I'm no expert on Lombok. I was looking here https://projectlombok.org/features/Data.

**Comment by rstoyanchev** [comment]
@nkavian I gave the scenario with Lombok a try. If I change `accountId` to a final field, Lombok exposes a constructor, and it works. I uncovered a small issue that currently `@BindParam` can't be put on a field, but I will fix that shortly. That said, you don't need to use `@BindParam` at all. If you already have `@JsonProperty`, you just need to set a `NameResolver` for it similar to `BindParamNameResolver`.

**Comment by nkavian** [comment]
I'll avoid try to avoid any further replies, I've already tried to point out this solution is too narrow (that requires the client to do very specific things to make it work). It would be better to see a simpler solution with fewer dependencies on how the client writes their code.

1. Clients should not be forced to make fields final.
2. Clients should not be forced to create constructors when their original code didn't require it.
3. It would be better if Spring provided a builtin NameResolver to handle the mapping.
4. The constructors that Lombok creates can not be relied upon and we explicitly avoid generating Lombok constructors. Imagine a class with 3 String fields. Lombok will create a constructor for it. If some time later a develop reorders the string fields (or removes one, and then adds another), then their old code calling the constructor will not know about the order change; and silent bugs enter into the program. From this PRs point of view, it doesn't care if the fields are moved around, it will still work; but I now have exposed my team to a constructor that I didn't want to manage which can cause me headaches.

**Comment by rstoyanchev** [comment]
The solution doesn't require you do very specific things. It's rather meant for use with constructors and final fields, which I consider a good practice. It's fine if you prefer field injection, but we don't support that currently.

**Comment by linsmalldragon** [comment]
> The solution doesn't require you do very specific things. It's rather meant for use with constructors and final fields, which I consider a good practice. It's fine if you prefer field injection, but we don't support that currently.

@BindParam doesnot work in spring feign client form data post.

**Comment by fy-kenny** [comment]
I think this is easy way right now if you have one class or two, and it can compatible with application/json.

@Value
public class ValueObject {
    @JsonAlias("user_id")
    private String userId;
    @JsonAlias("user_name")
    private String userName;
    
    public ValueObject(String user_id, String user_name) {
        this.userId = user_id;
        this.userName = user_name;
    }
}
