### ISSUE TITLE
Server-side JavaScript improvements [SPR-13508]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18086]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-13508](https://jira.spring.io/browse/SPR-13508?redirect=false)** and commented

Spring Framework 4.2.x introduced [a generic support for script based templating](https://speakerdeck.com/sdeleuze/isomorphic-templating-with-spring-boot-nashorn-and-react) suitable for any kind of script technology. The scope of this issue is to keep track of potential server-side javascript improvements.

### Java to JSON object conversion

In the script template, the model object available on Javascript side is still a Java object. Most template engines requires to have a real JSON object instead of a `Map`, and a real JSON array instead of an `Iterable`. It should be useful to provide out of the box this functionality. A possible implementation is available [here](https://github.com/sdeleuze/spring-boot-sample-web-handlebars/blob/master/src/main/resources/static/render.js#L16).

### JS logging on server-side

Similarly to [this Spring Boot proposed feature](https://github.com/spring-projects/spring-boot/issues/3976), it should be possible to provide a `console.log()` interceptor that will forward client side logs to your Java log appender.

### Load easily file content from filesystem or classpath

Very useful to make it possible to implement easily nested template support for example.

### Script loader extension

Provide a JS extension for script loader like System.js/Require.js that loads lazily a Javascript dependency from the classpath (instead of an Ajax request) in order to improve maintainability of such app.

### EmberJS 2/Angular 2/React support

More helpers/guidance for [Angular 2](https://github.com/angular/universal), [EmberJS 2](http://emberjs.com/blog/2014/12/22/inside-fastboot-the-road-to-server-side-rendering.html) or React universal/isomorphic applications.

### Spring beans accessible on Javascript

Experiment about making Spring beans accessible from Javascript. [Wildfly support for similar functionality](http://wildfly.org/news/2015/08/10/Javascript-Support-In-Wildfly/) seems worth to have a look.

---

**Issue Links:**
- #16871 Support JavaScript Templating

12 votes, 19 watchers

**Comment by sdeleuze** [comment]
With no update in 5 years and Nashorn now removed from the JDK, I think it is better to close this and stay unopinionated at Spring Framework level.
