### ISSUE TITLE
Modify creation of the ScheduledTaskRegistrar to be a Spring managed bean [SPR-13506]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18084]
**[Tobias Montagna-Hay](https://jira.spring.io/secure/ViewProfile.jspa?name=tobiasm)** opened **[SPR-13506](https://jira.spring.io/browse/SPR-13506?redirect=false)** and commented

Would it be possible to modify the creation of the ScheduledTaskRegistrar to be a Spring managed bean in the ScheduledAnnotationBeanProcessor?

The reason for this is so that tasks that have been scheduled using the `@Scheduled` annotation can also be inspected.

Access has previously been made available to tasks that have been scheduled using the task xml prefix. #17345

I have submitted a pull request here: https://github.com/spring-projects/spring-framework/pull/878

---

**Affects:** 4.2.1

**Reference URL:** http://stackoverflow.com/questions/21791853/how-are-spring-taskscheduled-objects-represented-at-runtime/28753723#28753723

**Issue Links:**
- #17345 Allowing access to scheduled tasks in the ScheduledTaskRegistrar

6 votes, 9 watchers

**Comment by jhoeller** [comment]
This is effectively superseded by #21374 in combination with #20532. While that internal `ScheduledTaskRegistrar` is still not exposed as a bean itself, it can be provided on `ScheduledAnnotationBeanPostProcessor` construction, and there is a common `ScheduledTaskHolder` interface which allows for introspecting the tasks of that internal `ScheduledTaskRegistrar` as well.

**Comment by sbrannen** [comment]
Superseded by:

- #21374
- #20532
