### ISSUE TITLE
Move ChainedTransactionManager from spring-data commons to spring-tx [SPR-13735]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18308]
**[Attila Király](https://jira.spring.io/secure/ViewProfile.jspa?name=akiraly)** opened **[SPR-13735](https://jira.spring.io/browse/SPR-13735?redirect=false)** and commented

Spring-data common has a hidden gem: ChainedTransactionManager.
It is not mentioned in the [reference documentation](http://docs.spring.io/spring-data/commons/docs/current/reference/html/) only in [javadoc](http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/transaction/ChainedTransactionManager.html).
There is a good [blog entry](http://gharshangupta.blogspot.hu/2015/03/spring-distributed-transactions-using_2.html) about it which describes why it is useful.

[ChainedTransactionManager](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/transaction/ChainedTransactionManager.java) is in a [package](https://github.com/spring-projects/spring-data-commons/tree/master/src/main/java/org/springframework/data/transaction) which doesn't have any dependency on anything else in spring-data. Basically it only depends on `org.springframework.transaction` from spring-tx.

Considering that it is a pretty general functionality, could it be moved (and documented) into spring-tx itself?

---

**Affects:** 4.2.3, 5.0 M4

**Issue Links:**
- #8524 Provide a "best efforts" 1PC transaction manager out of the box

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1324

**Comment by snicoll** [comment]
With `ChainedTransactionManager` being deprecated in Spring Data, we have no intention to move this feature in the core framework. Thanks for the suggestion, in any case.
