### ISSUE TITLE
Configurable QoS properties for messages sent by @JmsListener [SPR-13775]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18349]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-13775](https://jira.spring.io/browse/SPR-13775?redirect=false)** and commented

As a follow-up to #18348, we should not just allow for programmatic customization through factory methods but also consider first-class QoS properties which can be configured on `JmsListenerAnnotationBeanPostProcessor` / `@EnableJms` / `jms:annotation-driven`.

---

**Affects:** 4.2.3

**Issue Links:**
- #18348 Allow for setting TTL on a response sent by `@JmsListener` (_**"depends on"**_)

1 votes, 2 watchers

**Comment by jhoeller** [comment]
Superseded by #19971.
