### ISSUE TITLE
Extract MockHttp from MockMvc [SPR-13818]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18391]
**[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch)** opened **[SPR-13818](https://jira.spring.io/browse/SPR-13818?redirect=false)** and commented

#### Status Quo

The `MockMvc` support provides an excellent API for testing Spring MVC applications. However, there are users that leverage Spring that may not be using Spring MVC. For example, Spring Security users do not necessarily use Spring MVC.

Without a dedicated API users are forced to manually apply things like `RequestPostProcessor`, `ResultActions`, `ResultMatchers`, etc. Not everything from the `MockMvc` support can be extracted out, but much of it can.

#### Proposal

It would be nice if an API that was not dependent on Spring MVC were extracted from `MockMvc`. A possible name might be `MockHttp`.

---

**Issue Links:**
- #19647 MockMvc compatible API for doing real HTTP tests
- #18393 Provide MockMvc support for Stateful HttpSession

0 votes, 7 watchers

**Comment by wagnerluis1982** [comment]
What is the status for this issue?

**Comment by rstoyanchev** [comment]
@wagnerluis1982 it's in the 5.x Backlog. Can you describe your use case?

**Comment by rstoyanchev** [comment]
I'm closing this as we have no plans to work on it.
