### ISSUE TITLE
Addressing Mass Assignment vulnerabilities with @NoBind annotation for domain objects [SPR-13835]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18408]
**[Anton Abashkin](https://jira.spring.io/secure/ViewProfile.jspa?name=springsecurityfan)** opened **[SPR-13835](https://jira.spring.io/browse/SPR-13835?redirect=false)** and commented

Most modern frameworks provide a convenience mechanism for binding form data to a domain object. Spring MVC is no exception.

While such a function is certainly indispensable, it exposes the application to the risk of a **mass assignment vulnerability** http://www.hpenterprisesecurity.com/vulncat/en/vulncat/java/mass_assignment_sensitive_field_exposure.html

A very serious vulnerability, this is actually how GitHub got hacked back in 2012 http://www.infoq.com/news/2012/03/GitHub-Compromised

Currently, Spring MVC does address this issue by providing two methods:

http://docs.spring.io/autorepo/docs/spring-framework/3.1.x/javadoc-api/org/springframework/validation/DataBinder.html#setAllowedFields%28java.lang.String...%29

http://docs.spring.io/autorepo/docs/spring-framework/3.1.x/javadoc-api/org/springframework/validation/DataBinder.html#setDisallowedFields%28java.lang.String...%29

While obviously a step in the right direction, this approach is not always optimal, the reason being the developer must set this in **each** controller using `@InitBinder`. This duplicates effort and is error prone.

One alternative for the developer is to create Data Transfer Objects (DTOs). While this does indeed provide protection, as well as other architectural benefits, it is not practiced by many developers.

I believe the optimal way to address this is to do something similar to what the the Play Framework does by providing a `@NoBind` annotation: https://www.playframework.com/documentation/1.4.x/controllers#nobinding

```java
public class User extends Model {

  @NoBinding("profile") public boolean isAdmin;

  @As("dd, MM yyyy") Date birthDate;

  public String name;
}
```

```java
public static void editProfile(@As("profile") User user) {
  // ...
}
```

Expressing these constraints directly in the domain object using annotations seems optimal from both a development and security auditing point of view

Thoughts?

---

**Issue Links:**
- #12403 Provide support for configuring the bindable properties of a form-backing object using field-level annotations
- #19337 Ability to suppress "rejectedValue" in error responses

2 votes, 5 watchers

**Comment by rstoyanchev** [comment]
For 6.1 we've added enhanced support for constructor binding in `DataBinder` including support for nested constructors (#20806). It is also possible to set a `declarativeBinding` flag (#30948) through an `@InitBinder` method locally on a controller, or globally in a controller advice, or via `ConfigurableWebBindingInitializer`. The declarative mode ensures that data binding is limited to constructor parameters, and properties explicitly allowed through the `allowedFields` property on `DataBinder`.

This provides an option to use data binding such that the request parameters used are determined by the Object structure, and not the other way around.

I am closing this as superseded for now, but we are open to further feedback.
