### ISSUE TITLE
Add support for YAML files to @PropertySource [SPR-13912]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18486]
**[Rob Moore](https://jira.spring.io/secure/ViewProfile.jspa?name=robmoore)** opened **[SPR-13912](https://jira.spring.io/browse/SPR-13912?redirect=false)** and commented

As the Spring documentation notes, the `@PropertySource` annotation does not support YAML files so one must use properties files in these cases.

This can be especially annoying with third party libraries using these annotations as a separate properties file must be created.

---

**Affects:** 4.2.4

**Reference URL:** https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml-shortcomings

18 votes, 27 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by mistriel** [comment]
I strongly agree with the supporters of this feature !  
YAML files should be supported as 1st class citizens in Spring F.W.

Should be reopened.

**Comment by maxmin13** [comment]
crap

**Comment by mazine-rr** [comment]
`.yaml` is far more enjoyable to write, read and modify than `.properties`. Please reopen.

**Comment by raahool** [comment]
My Use case is, 

1. organisation wide all our microservies are using YAML, so we cannot move from YAML to .properties.
2. In one of my recent app, I am using testcontainers for Unit tests, where testcontainers randomly selects any available port to start the container. So before running the tests I have to dynamically change the PORT property which is defined in the YAML file.

For .properties file, it was straightforward with `ApplicationContextInitializer `& `TestPropertyValues  `- like
`TestPropertyValues.of("spring.rabbitmq.port" + container.getMappedPort(5672)).applyTo(applicationContext);`

Not able to achieve this, being the port property is defined in the YAML file.

Any workaround / suggestions ?

**Comment by dlehammer** [comment]
I've included a working example (Spring Boot 2.7.0) for posterity below. To support those like me puzzled by the below quote from the [documentation](https://docs.spring.io/spring-boot/docs/2.7.2/reference/html/features.html#features.external-config.yaml.directly-loading), as there's no elaboration or example.
> You can also use the `YamlPropertySourceLoader` class if you want to load YAML as a Spring `PropertySource`.

(I haven't pursued the  `YamlPropertySourceLoader` approach, as I sense the time to deduce the "right approach" and the boiler-plate far exceeds the example I've provided)
The use-case in my case is simple, load a external .yml file into a `@ConfigurationProperties` annotated class ~ in this case the configuration contains some lists, which are readable in YAML less so in properties.

Seemingly in spite of "Easy doesn't necessarily means correct" this a desired approach, that has spawned tutorials as recent as 2022-07-22 [(@PropertySource with YAML Files in Spring Boot)](https://www.baeldung.com/spring-yaml-propertysource).

With a `PropertySourceFactory` like below (ex. from the Baeldung tutorial), the object binding is performed similarly to properties for a `@PropertySource(value = "classpath:foo.yml", factory = YamlPropertySourceFactory.class)`

```
public class YamlPropertySourceFactory implements PropertySourceFactory {

    @Override
    public PropertySource<?> createPropertySource(String name, EncodedResource encodedResource) throws IOException {
        YamlPropertiesFactoryBean factory = new YamlPropertiesFactoryBean();
        factory.setResources(encodedResource.getResource());

        return new PropertiesPropertySource(encodedResource.getResource().getFilename(),  factory.getObject());
    }
}
```

I too was surprised to discover (via this obscure issue) that Spring YAML support is missing feature-parity with properties ~ ie. consistently supported via externalized configuration, this violates[ the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and subsequently spawns unofficial workarounds  :/ 

I vote for an official approach 👍 

See also similar tutorials
- [Use @PropertySource with YAML files](https://deinum.biz/2018-07-04-PropertySource-with-yaml-files/) (2018-07-04)
- [Spring @PropertySource using YAML](https://newbedev.com/spring-propertysource-using-yaml) (2021?)

**Comment by gavenkoa** [comment]
There are two SO discussion dedicated to the report:

* https://stackoverflow.com/questions/45880494/configurationproperties-loading-list-from-yml/
* https://stackoverflow.com/questions/21271468/spring-propertysource-using-yaml/

`@PropertySource(value = "classpath:XXX.yml", factory = ...)` is a nice solution though you need to create own `PropertySourceFactory` (as @dlehammer presented). The best thing, in light of Spring dev denial, is to prepackage `YamlPropertySourceFactory`  implementation so no one needs to copy-paste some non-bullet proof implementation but relies on good default!

`@TestPropertySource` doesn't support factory but has a property to be loaded with highest priority ((

**Comment by hbourada** [comment]
What about a new annotation @YamlPropertySource with meta annotation @PropertySource ont it with the correct factory
