### ISSUE TITLE
spring-test HtmlUnit does not recognize files for multipart uploading [SPR-13979]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18551]
**[Stephen Liang](https://jira.spring.io/secure/ViewProfile.jspa?name=stephenliang)** opened **[SPR-13979](https://jira.spring.io/browse/SPR-13979?redirect=false)** and commented

#### Overview

The params method in `HtmlUnitRequestBuilder` does not check if a parameter contains a File payload, which results in a File input box to get its value (the path to the file) and submit it as a key/value rather than the payload being uploaded as multipart form data.

#### For Reference

https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/web/servlet/htmlunit/HtmlUnitRequestBuilder.java#L361

`webRequest.getRequestParameters()` is a `KeyDataPair` which contains a field called `fileObject_`. This field should be recognized and used in place of the `value_` field which is the name of the field, rather than the content of the file (when the parameter is has a file).

#### To Reproduce

1. Create a simple file upload form, e.g.:

```html
<html><head></head><body>
<form enctype='multipart/form-data' action='"/upload"' method='POST'>
<input type='file' name='image' />
<input type='submit' id='clickMe'>
</form>
</body>
</html>
```

1. Create a html unit test that sends the file path to the "file" input type
2. Click on the submit button

**Expected Result**: The file contents are read and sent as form data
**Actual Result**: The file's name is sent as a key/value pair

---

**Affects:** 4.2 GA

0 votes, 5 watchers

**Comment by djkirby** [comment]
Any update on this? Would be nice to have this functionality 🤞

**Comment by sbrannen** [comment]
I've added the `ideal-for-contribution` label so that someone from the community can pick this one up.

**Comment by govi20** [comment]
Would like to take it up.

**Comment by sbrannen** [comment]
@govi20, great!

Feel free to submit a PR.

If for some reason you cannot get to it, please post back here so that we know you're not actively working on it.

**Comment by govi20** [comment]
@sbrannen Apologies I missed this message. I will look into this over the weekend. One newbie question: is there a setting file that could be used to mark IntelliJ source and test root directories or it needs to be marked manually?

**Comment by kobaeugenea** [comment]
Hi. Created PR for this issue https://github.com/spring-projects/spring-framework/pull/24926

**Comment by sbrannen** [comment]
Superseded by #24926
