### ISSUE TITLE
Client-side polling delay as alternative for receive timeout for JMS [SPR-14225]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18799]
**[Erik Wramner](https://jira.spring.io/secure/ViewProfile.jspa?name=erik-wramner)** opened **[SPR-14225](https://jira.spring.io/browse/SPR-14225?redirect=false)** and commented

We are using Spring JMS with DefaultMessageListenerContainer using AQ JMS with very high volumes and we have spent quite some time on performance tuning. Finally we have found our silver (or at least copper) bullet: client-side waits.

The problem is how AQ handles receiveTimeout. If there are 100 threads waiting for a new message on a queue they consume virtually no resources as long as there is nothing to read. However, if a single message is posted all 100 threads try to get it, issuing a SQL SELECT statement. One will succeed, the others fail but still consume CPU in the database. As messages are posted this quickly adds up and the database is bogged down by pointless selects. When there is a backlog this is no issue, but when consumers keep up with producers it kills the database and eats resources that would be needed elsewhere.

We subclassed DefaultMessageListenerContainer and added a clientPollingDelay parameter. A receive call with a null message would sleep for clientPollingDelay milliseconds before proceeding. That improved our overall performance immensely. Our current implementation (subclassing and overriding a protected method) is not ideal, as it puts the delay inside a transaction. I will submit a pull request with a better option. The main point is to move the sleep from the database (JMS provider) to the application server (JMS client) as that works much better with AQ.

This is of major importance for us, but as we have a solution in place I have classified the issue as a minor one.

---

**Issue Links:**
- #18774 DefaultMessageListenerContainer doesn't shutdown gracefully if long recovery interval is set
- #18786 Support non-blocking receiveTimeout in AbstractPollingMessageListenerContainer

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1045

1 votes, 3 watchers

**Comment by snicoll** [comment]
The related PR has been closed and this didn't proposal didn't get a lot of traction so I suggest to close this one as well. If there is something that prevents a sub-class to do this we can adapt the core API to make that easier.
