### ISSUE TITLE
feasibility to cancel a task  [SPR-14219]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18793]
**[Balu Mahesh](https://jira.spring.io/secure/ViewProfile.jspa?name=balumahesh)** opened **[SPR-14219](https://jira.spring.io/browse/SPR-14219?redirect=false)** and commented

I would like to have a provision to cancel a scheduled task from ScheduledTaskRegistrar. the method destroy is to cancel all tasks. but i need a method where i can pass the task argument to cancel the specified Task.

---

**Affects:** 4.2.5

**Comment by jhoeller** [comment]
You'd need to hold on to the `ScheduledTask` handle that you receive from your schedule call on `ScheduledTaskRegistrar` which you can then use to cancel the task.
