### ISSUE TITLE
Enable Executor qualification with @Scheduled [SPR-14218]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18792]
**[Jonas Kongslund](https://jira.spring.io/secure/ViewProfile.jspa?name=kongslund)** opened **[SPR-14218](https://jira.spring.io/browse/SPR-14218?redirect=false)** and commented

`@Async` supports specifying [which target executor to use](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#scheduling-annotation-support-qualification). It would be useful if `@Scheduled` had the same support.

---

**Issue Links:**
- #11513 Enable Executor qualification with `@Async`

6 votes, 10 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by gghnisan** [comment]
Please, reopen.

**Comment by rLitto** [comment]
please reopen

**Comment by au-hao** [comment]
please reopen

**Comment by evpaassen** [comment]
This issue is duplicated by #20818 (SPR-16271).

**Comment by snicoll** [comment]
Good catch @evpaassen, thank you.
