### ISSUE TITLE
Make it possible to mock ApplicationEventPublisher in Spring Boot tests [SPR-14335]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18907]
**[Jean-Baptiste Nizet](https://jira.spring.io/secure/ViewProfile.jspa?name=jnizet)** opened **[SPR-14335](https://jira.spring.io/browse/SPR-14335?redirect=false)** and commented

This is a followup to this bug posted on the Spring Boot project:

- https://github.com/spring-projects/spring-boot/issues/6060

`ApplicationEventPublisher`, which is a direct dependency of application components that must publish events, can't be mocked as other beans in Spring Boot tests, because it's not a "regular" Spring bean. Just testing that an event has been fired by a method thus requires workarounds such as defining a fake listener bean, and I think that workaround shouldn't be necessary.

---

**Affects:** 4.3 RC2

5 votes, 6 watchers

**Comment by nekperu15739** [comment]
Hi, im facing the same problem, and for now i solve the problem using TestConfiguration:

```
@SpringBootTest
class MyUseCaseIT {

  @Autowired private ApplicationEventPublisher publisher;
  @Autowired private MyService service;

@Test
  void callUseCase() {
var event = mock(MyEvent.class);
    doNothing().when(publisher).publishEvent(event);

service.useCase();

    verify(publisher).publishEvent(event);
}


@TestConfiguration
  static class MockitoPublisherConfiguration {

    @Bean
    @Primary
    ApplicationEventPublisher publisher() {
      return mock(ApplicationEventPublisher.class);
    }
  }
```

**Comment by victordfb** [comment]
I'm having the same issue here. It would be nice to have such feature.

**Comment by LaSylv** [comment]
Maybe dig around `@RecordApplicationEvents`/ `org.springframework.test.context.event.ApplicationEvents` ?

**Comment by Cpt76** [comment]
> Ciao, sto affrontando lo stesso problema e per ora risolvo il problema utilizzando TestConfiguration:
> 
> ```
> @SpringBootTest
> class MyUseCaseIT {
> 
>   @Autowired private ApplicationEventPublisher publisher;
>   @Autowired private MyService service;
> 
> @Test
>   void callUseCase() {
> var event = mock(MyEvent.class);
>     doNothing().when(publisher).publishEvent(event);
> 
> service.useCase();
> 
>     verify(publisher).publishEvent(event);
> }
> 
> 
> @TestConfiguration
>   static class MockitoPublisherConfiguration {
> 
>     @Bean
>     @Primary
>     ApplicationEventPublisher publisher() {
>       return mock(ApplicationEventPublisher.class);
>     }
>   }
> ```

This workaround doesn't work when using webflux, I don't know why... single tests work in isolation, but when multiple tests are runned together flatMap is not working, it seems another thread is used.

**Comment by sbrannen** [comment]
Closing in favor of the `@RecordApplicationEvents` feature introduced in `spring-test` in Spring Framework 5.3.3. See the [reference documentation](https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/application-events.html) for details.

If you find that `@RecordApplicationEvents` does not meet your needs, please create a new ticket.

**Comment by imwower** [comment]
> Hi, im facing the same problem, and for now i solve the problem using TestConfiguration:
> 
> ```
> @SpringBootTest
> class MyUseCaseIT {
> 
>   @Autowired private ApplicationEventPublisher publisher;
>   @Autowired private MyService service;
> 
> @Test
>   void callUseCase() {
> var event = mock(MyEvent.class);
>     doNothing().when(publisher).publishEvent(event);
> 
> service.useCase();
> 
>     verify(publisher).publishEvent(event);
> }
> 
> 
> @TestConfiguration
>   static class MockitoPublisherConfiguration {
> 
>     @Bean
>     @Primary
>     ApplicationEventPublisher publisher() {
>       return mock(ApplicationEventPublisher.class);
>     }
>   }
> ```

also remember to import this configuration on your test class: 

```
@Import(MockitoPublisherConfiguration.class)
@SpringBootTest
class MyUseCaseIT {
 ...
```
