### ISSUE TITLE
Add a Basic Websocket Java Client with Reconnection capability as a new Package of Spring [SPR-14331]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18903]
**[Sergio Pinto](https://jira.spring.io/secure/ViewProfile.jspa?name=sergio%20p.)** opened **[SPR-14331](https://jira.spring.io/browse/SPR-14331?redirect=false)** and commented

I have found that sometime an application need a persistent connection with Websockets.

Since Spring 4.2 I see that integrated STOMP with WebSocket, I tried STOMP but I found that you can't reconnect. SockJS can do it, but is disabled when using STOMP with Spring and SockJS.

I think Spring must include a class to easy implement a websocket client that can reconnect.

Actually I implemented a Java client that initially was based in a JavaScript WebSocket implementation that can reconnect. I'm using a proxy pattern to add the _onReconnect()_ and_ reconnect()_ methods to my client.
It is using an log-back algorithm to retry a new connection.

This could be a big plus to the websocket API with Spring.

Maybe the reconnect ability could be added to the STOMP version that actually is used in Spring latter.

Is possible add this to the Spring framework as a new package/class that could be used as a **out-of-the-box basic websocket cliet with reconnection**

---

**Affects:** 4.3 RC2

**Issue Links:**
- #17968 Excessive SockJS Reconnection Attempts

2 votes, 3 watchers

**Comment by YBrecher** [comment]
I was doing some research on this issue, and I found that the common practice for getting a Websocket to reconnect is to create an onClose listener that automatically calls the connect method each time the connection closes. Is there a reason why this method would not be sufficient for Spring?

**Comment by rstoyanchev** [comment]
Yes, a callback when the connection is closed is essential for reconnect. 

It's unclear from the original description what the exact proposal or issue is. `SockJsClient` doesn't have reconnect feature, but the `WebSocketHandler` passed into it can implement `onClose`. At the level of `StompWebSocketClient`, there is a similar `handleTransportError` callback on `StompSessionHandler`.

I'm closing but would reconsider a more concrete proposal.
