### ISSUE TITLE
Introduce class-level execution phases for `@Sql` [SPR-14357]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18929]
**[urbanq](https://jira.spring.io/secure/ViewProfile.jspa?name=urbanq)** opened **[SPR-14357](https://jira.spring.io/browse/SPR-14357?redirect=false)** and commented

It would be helpful to introduce class-level support in the `ExecutionPhase` enum used by `@Sql`: `BEFORE_CLASS` and `AFTER_CLASS`.

So when executing integration test we can easily run one single SQL script for all test methods in the test class.

---

**Affects:** 4.2.6

**Reference URL:** https://stackoverflow.com/questions/32871817/using-annotation-sql-is-it-possible-to-execute-scripts-in-class-level-before-m

**Issue Links:**
- #20570 Introduce opt-in support for merging class-level and method-level `@Sql` declarations

4 votes, 5 watchers

**Comment by aahlenst** [comment]
@sbrannen I opened #27285 to get the ball rolling. Please let me know what you think and what I could do to improve the PR (like adding more tests).

**Comment by juzunoglu** [comment]
Is this still being implemented?

**Comment by sbrannen** [comment]
- superseded by #27285
