### ISSUE TITLE
Support additional file formats in `ReloadableResourceBundleMessageSource`

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#18990]
**[Loïc Dreux](https://jira.spring.io/secure/ViewProfile.jspa?name=ldreux)** opened **[SPR-14419](https://jira.spring.io/browse/SPR-14419?redirect=false)** and commented

`ReloadableResourceBundleMessageSource` could store and load Properties with a custom implementation of the PropertiesPersister like [YamlPropertiesPersister.java](https://github.com/calavera/ey_yaml_persister/blob/master/src/main/java/com/engineyard/appcloud/yaml/YamlPropertiesPersister.java) but the extensions ".properties" and ".xml" are hard coded in Java Source.

A good solution could be to add a property "customExtension" to support other file format like yaml.

---

**Affects:** 4.2.6

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by 62mkv** [comment]
I would say it's relevant!

**Comment by pierrickrouxel** [comment]
I think this is relevant too. All my application is YAML configured (properties, liquibase..) excepted messages. It's really frustrating.
Without this support we must use two different markup language to maintain our projects.

**Comment by Gorynych** [comment]
Is it possible to reopen an issue?

**Comment by MysteryMS** [comment]
i think it is relevant too

**Comment by tonyfarney** [comment]
It's relevant!

**Comment by ghahramani** [comment]
any updates on this?

**Comment by cristianchies** [comment]
Really waiting for it!!! It's relevant!

**Comment by ashutosh049** [comment]
At least tell us when will this be resolved.

**Comment by m-a-g-i-c** [comment]
This issue still relevant

**Comment by michafrometa** [comment]
I am here too. Seems relevant to me

**Comment by wesleyody** [comment]
Nice issue

**Comment by renanfranca** [comment]
I really like this issue! 💕

**Comment by 5452** [comment]
look forward

**Comment by christian-kocke** [comment]
I would really appreciate this feature!

**Comment by smunozudp** [comment]
@christian-kocke I found a repo with a work around of this issue, hope it helps. 
https://github.com/akkinoc/yaml-resource-bundle

**Comment by grzeg** [comment]
it is relevant for sure!

**Comment by viviendehorta** [comment]
yes, it's relevant

**Comment by LuisMarques99** [comment]
I agree, this is a very relevant feature

**Comment by jmussman** [comment]
Yep. Lots of us need this. Anything that's hard-coded is really bad code, so it's high time it was refactored anyways. Externalize it and use polymorphism to support Yaml!

**Comment by slimane-deb** [comment]
And here I am again too checking for any updates. Still find it relevant

**Comment by poutsma** [comment]
Thanks for your input everyone, we will be addressing this feature request in 6.1.

**Comment by malikalamgirian** [comment]
It is relevant for me as well :)

**Comment by MysteryMS** [comment]
> Thanks for your input everyone, we will be addressing this feature request in 6.1.

YES! it took almost 7 years... but we got it 🎉🎉🎉

**Comment by Thanthu** [comment]
> > Thanks for your input everyone, we will be addressing this feature request in 6.1.
> 
> YES! it took almost 7 years... but we got it 🎉🎉🎉

From which version of Spring Boot is this feature available ? Any resource available with example of its usage would be nice.

**Comment by sbrannen** [comment]
> From which version of Spring Boot is this feature available ? Any resource available with example of its usage would be nice.

@Thanthu, _this_ issue is still open, which means that the feature has not been released yet.

**Comment by sdeleuze** [comment]
Thanks everybody for your patience, this issue should be be fixed by [this commit](c942c04aa06df06ed2da93cc9216b9095e3d59fb).

I was a bit confused initially by the fact that the description of the changes proposed looked irrelevant to `ResourceBundleMessageSource`, but I understood after digging deeper that it was a typo, and that the change was targetting `ReloadableResourceBundleMessageSource` which allows to set a custom `PropertiesPersister` and had indeed `.properties` and `.xml` extensions hardcoded. The title and description of the issue have been updated accordingly.

In `ReloadableResourceBundleMessageSource`, it is now possible to customize the file extensions thanks to a new `setFileExtensions` setter, and combined to `setPropertiesPersister`, it is possible to implement support for custom file format.

Since that seems to be a popular use case, I have implemented an example of Yaml resource bundle support in https://github.com/sdeleuze/demo-yaml-message-source. The important bits are the [`YamlPropertiesLoader`](https://github.com/sdeleuze/demo-yaml-message-source/blob/main/src/main/java/com/example/YamlPropertiesLoader.java) leveraging `org.springframework.beans.factory.config.YamlMapFactoryBean` and the declaration of a custom `MessageSource` bean [here](https://github.com/sdeleuze/demo-yaml-message-source/blob/main/src/main/java/com/example/YamlMessageSourceApplication.java):
```java
@Bean
public MessageSource messageSource() {
	ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
	messageSource.setBasename("classpath:messages");
	messageSource.setPropertiesPersister(new YamlPropertiesLoader());
	messageSource.setFileExtensions(List.of(".yml", ".yaml"));
	return messageSource;
}
```
Spring does not provide out-of-the box such Yaml support yet, but hopefully that can serve as an example for the community for how to leverage that, and will allow the Spring team to observe how the community leverage those capabilites, what implementation get traction, etc.

**Comment by sbrannen** [comment]
> this issue has been closed. does that mean Spring framework out of the box finally support yaml format for message source?

@hannah23280, please read the closing comments for an issue before asking a question.

This was answered in the comment immediately preceding yours.

> Spring does not provide such out-of-the box YAML support yet, but hopefully that can serve as an example for the community for how to leverage this feature, and will allow the Spring team to observe how the community leverages those capabilities, which implementations get traction, etc.

**Comment by bclozel** [comment]
@hannah23280 we don't list all changes on this page. This feature has been delivered with milestone 4 as listed on this page and the release notes: https://github.com/spring-projects/spring-framework/releases/tag/v6.1.0-M4

**Comment by bclozel** [comment]
@hannah23280 I'm not sure what feature you're expecting in Spring Boot, but there's nothing scheduled at the moment in that area.

**Comment by sascha08-15** [comment]
> Thanks everybody for your patience, this issue should be be fixed by [this commit](c942c04aa06df06ed2da93cc9216b9095e3d59fb).
> 
> I was a bit confused initially by the fact that the description of the changes proposed looked irrelevant to `ResourceBundleMessageSource`, but I understood after digging deeper that it was a typo, and that the change was targeting `ReloadableResourceBundleMessageSource` which allows to set a custom `PropertiesPersister` and indeed had `.properties` and `.xml` extensions hard coded. The title and description of the issue have been updated accordingly.
> 
> In `ReloadableResourceBundleMessageSource`, it is now possible to customize the file extensions thanks to a new `setFileExtensions` setter, and combined with `setPropertiesPersister`, it is possible to implement support for custom file formats.
> 
> Since it seems to be a popular use case, I have implemented an example of YAML resource bundle support in https://github.com/sdeleuze/demo-yaml-message-source. The important bits are the [`YamlPropertiesLoader`](https://github.com/sdeleuze/demo-yaml-message-source/blob/main/src/main/java/com/example/YamlPropertiesLoader.java) leveraging `org.springframework.beans.factory.config.YamlMapFactoryBean` and the declaration of a custom `MessageSource` bean [here](https://github.com/sdeleuze/demo-yaml-message-source/blob/main/src/main/java/com/example/YamlMessageSourceApplication.java):
> 
> ```java
> @Bean
> public MessageSource messageSource() {
> 	ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
> 	messageSource.setBasename("classpath:messages");
> 	messageSource.setPropertiesPersister(new YamlPropertiesLoader());
> 	messageSource.setFileExtensions(List.of(".yml", ".yaml"));
> 	return messageSource;
> }
> ```
> 
> Spring does not provide such out-of-the box YAML support yet, but hopefully that can serve as an example for the community for how to leverage this feature, and will allow the Spring team to observe how the community leverages those capabilities, which implementations get traction, etc.

I tried your implementation and it works IFF one uses the yml with a flat list of attributes. But isn't the entire point of yml vs. properties file to have a more object oriented way to specify i8n texts?

So working with this:
```
hello.world: hellö
hello:
  world: Hello
```
Only the first one works with Thymeleaf using `<h1 th:text="#{hello.world}"></h1>` in the template. The second one, I fail to address - any ideas why that happens and how to work around it?

**Comment by Aniokrait** [comment]
@sascha08-15 
I had the same issue.  
I replcaed YamlMapFactoryBean with YamlPropertiesFactoryBean in load method of YamlPropertiesLoader and it worked. 
```java
public class YamlPropertiesLoader implements PropertiesPersister {

	@Override
	public void load(Properties props, InputStream is) {
//		YamlMapFactoryBean yaml = new YamlMapFactoryBean();
                YamlPropertiesFactoryBean yaml = new YamlPropertiesFactoryBean();
		yaml.setResources(new InputStreamResource(is));
		props.putAll(yaml.getObject());
	}
```

**Comment by sascha08-15** [comment]
Thanks for the quick answer! Works like a charm now!
