### ISSUE TITLE
Improve AOP pointcut supports meta-annotation [SPR-14439]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19010]
**[Yanming Zhou](https://jira.spring.io/secure/ViewProfile.jspa?name=quaff)** opened **[SPR-14439](https://jira.spring.io/browse/SPR-14439?redirect=false)** and commented

Spring supports `@GetMapping` and other `@MethodMapping` to replace `@RequestMapping` seamlessly since 4.3, but there is a problem with AOP pointcut.

```java
@Before("execution(public * *(..)) and @annotation(requestMapping)")
public void before(JoinPoint jp, RequestMapping requestMapping)  {
      ...
}
```

It works fine with `@RequestMapping` but failed with `@GetMapping`.

---

**Affects:** 4.3.1

**Comment by jhoeller** [comment]
Since the `@annotation` is part of AspectJ's pointcut language, I'm afraid there isn't anything that we can do about this from Spring's side.
