### ISSUE TITLE
Support timeout settings in MockRestServiceServer [SPR-14458]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19027]
**[Nikita Zhuravlev](https://jira.spring.io/secure/ViewProfile.jspa?name=nzhuravlev)** opened **[SPR-14458](https://jira.spring.io/browse/SPR-14458?redirect=false)** and commented

Since MockRestServiceServer simply replaces RestTemplate requestFactory and requestFactory serves as the holder of HttpClient and timeouts settings you will get irrelevant test results in case you'll make your own realisation of ResponseCreator with timeout simulation.

---

**Issue Links:**
- #20866 Limit thread synchronization in AbstractRequestExpectationManager

1 votes, 4 watchers

**Comment by christiangoudreau** [comment]
Is there any news on this?

**Comment by duclm2609** [comment]
Nearly 4 years later, any progress here? How do I test my interceptor behavior with MockRestServiceServer using @RestClientTest annotation?

**Comment by rstoyanchev** [comment]
Superseded by #1954.

**Comment by wn9237** [comment]
Hi, any updates on this?

**Comment by bclozel** [comment]
@wn9237 read the comment just above yours. This has been implemented.
