### ISSUE TITLE
Validate values in top-level Map parameters [SPR-14615]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19182]
**[Martin Asenov](https://jira.spring.io/secure/ViewProfile.jspa?name=martin.3361)** opened **[SPR-14615](https://jira.spring.io/browse/SPR-14615?redirect=false)** and commented

Class with RestController annotation
Method with RequestMapping annotation, method is POST
Map<String, CustomDto> is a parameter, annotated with `@Valid` and `@RequestBody`
CustomDto has `@NotNull` on one of its fields.
The input passes even though a CustomDto entry is not valid (null value on the `@NotNull` field)
When I try to change the Map with a single CustomDto, it is validated correctly, but when a map, it is not.

---

**Affects:** 4.2.5

**Issue Links:**
- #16519 Bean Validation invocation API for use with individual values and constraints
- #18007 `@Validated` support on Iterables (and implementors)
- #16917 Add support for validating a collection of objects

1 votes, 3 watchers

**Comment by rstoyanchev** [comment]
This is now supported with Bean Validation and the built-in Spring web method validation #30645.
