### ISSUE TITLE
Auto-resolve bean name conflicts for scanned classes [SPR-14665]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19229]
**[Caleb Cushing](https://jira.spring.io/secure/ViewProfile.jspa?name=xenoterracide)** opened **[SPR-14665](https://jira.spring.io/browse/SPR-14665?redirect=false)** and commented

so let's say I have two `WebSecurityConfig` classes which extend `WebSecurityConfigurerAdapter`. You will get a conflict like this

```
nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'webSecurityConfig' for bean class [com.xenoterracide.rpf.security.config.WebSecurityConfig] conflicts with existing, non-compatible bean definition of same name and class [com.xenoterracide.rpf.config.WebSecurityConfig]
```

this of course would be even worse if they were in jars you didn't control the source for (not that I've ever encountered that).

It occurs to me that I never need to use name injection for these. Perhaps spring could auto name them including the package name... or some other unique method (or perhaps do away with the name requirement?). Basically the idea is if you want a user friendly name to inject that you can still specify one.

This probably does break backwards compatibility so maybe it could be part of 5 if possible.

---

**Issue Links:**
- #15434 Reconsider whether to generally allow bean overriding by name

**Comment by jhoeller** [comment]
With the option of resolving this through an explicitly configured `BeanNameGenerator`, we do not intend to auto-resolve such scenarios.
