### ISSUE TITLE
Allow JMS listener instrumentation [SPR-14683]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19247]
**[Marcin Grzejszczak](https://jira.spring.io/secure/ViewProfile.jspa?name=mgrzejszczak)** opened **[SPR-14683](https://jira.spring.io/browse/SPR-14683?redirect=false)** and commented

In Spring Cloud Sleuth we would want to give the users a possibility to instrument all `@JmsListener` annotated methods in order to propagate tracing information. In the Issue Garry mentions that

```
It's not currently possible to customize the adapter.

Or, a tweak in JmsListenerAnnotationBeanPostProcessor to wrap the listener in a proxy or similar.
```

Can we give the possibility of adding listeners / proxies / whatever to instrument the listeners?

For all incoming messages from JMS we would like to be able to do some pre processing and post processing (let's assume that the message arrived from a destination "foo").

```java

class SomeMagicalClassThatWillHelpUsSolveThisProblem {

    private final  SpanExtractor<Message> messagingSpanExtractor;
    private final Tracer tracer;

// constructor

    public void magicalMethod(Message message, String destination, ProceedingPointcut pointcut) {
        // we need to extract tracing information from a message and inject it into a span
        Span parentSpan = messagingSpanExtractor.joinTrace(message);
        Span continuedSpan = tracer.continueSpan(span);
        tracer.addTag("method", pointcut.giveMeTheNameOfTheMethodThatWillProcessTheMessage());
        tracer.addTag("class", pointcut.giveMeTheNameOfTheClassThatWillProcessTheMessage());
        try {
            // let the normal method execution take place
            pointcut.proceed(...);
        } finally {
            // once the message has been processed we need to close the span
            tracer.close(span);
        }
    }

}
```

---

**Reference URL:** https://github.com/spring-cloud/spring-cloud-sleuth/issues/151#issuecomment-245828688

2 votes, 9 watchers

**Comment by clisterdmello** [comment]
I see this feature will be added in spring 6.x.x. 
is there a way we can be early adopters ?

**Comment by snicoll** [comment]
Superseded by #30335
