### ISSUE TITLE
get Class package and location returns null when use  <context:load-time-weaver/> [SPR-14736]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19302]
**[jasperMin](https://jira.spring.io/secure/ViewProfile.jspa?name=jaspermin)** opened **[SPR-14736](https://jira.spring.io/browse/SPR-14736?redirect=false)** and commented

Recently, I use   "<context:load-time-weaver/>" config to support `@Configurable` annotation in my project.I found serious problems below when I trace the errors in my project.
1.XXX.class.getPackage() returns null
2.XXX.class.getProtectionDomain().getCodeSource().getLocation() returns null
These problems disappear when I don't use "<context:load-time-weaver/>".
The code  "XXX.class.getPackage()" is used in many dependencies such as the static method in com.mysql.jdbc.Util:

packageName = MultiHostConnectionProxy.class.getPackage().getName();

The null result of Class.getPackage() causes NullPointerException.

---
No further details from [SPR-14736](https://jira.spring.io/browse/SPR-14736?redirect=false)

**Comment by jhoeller** [comment]
Closing this issue since it got addressed on the MySQL side: https://bugs.mysql.com/bug.php?id=83052
