### ISSUE TITLE
Allow setting the escape order for  [SPR-14787]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19353]
**[David Balažic](https://jira.spring.io/secure/ViewProfile.jspa?name=xerces8)** opened **[SPR-14787](https://jira.spring.io/browse/SPR-14787?redirect=false)** and commented

The spring:EscapeBody tag with the attributes htmlEscape="true" javaScriptEscape="true" first does a HTML escape on the body and then a JavaScript escape.

Is it possible to reverse the order of the operations? Maybe a new attribute or similar.

---

**Affects:** 4.3.3

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by xerces8** [comment]
I checked the current sources at https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/tags/EscapeBodyTag.java (at version 5.1.5 it seems) and this seems still relevant.

Consider the following code:
 `<a onclick='alert("${needescape}");'>Foo</a>`

If `<s:escapeBody htmlEscape="true" javaScriptEscape="true">` is used, and the string value  `a<b"x` , then it is first HTML escaped to `a&lt;b&quot;x` and then JS escaped to the same, as those characters do not need escaping for JS. 
So the result is:

JSP source:
`<c:set var="needescape" >a<b'x</c:set>`
`<a onclick='alert("<s:escapeBody htmlEscape="true" javaScriptEscape="true">${needescape}<s:escapeBody>");'>Foo</a>`

Generated HTML:
`<a onclick='alert("a&lt;b&quot;x");'>Foo</a>`

Which when evaluated for the attribute onclick, gives the value `alert("a<b"x");` which is invalid JavaScript.
When clicking that A element in the browser, it breaks with this message in the error console:
> SyntaxError: missing ) after argument list[Learn More] examplePage:1:11

So in this use case, escaping JS first, and then HTML second would be needed.

**Comment by meeque** [comment]
@xerces8 I've run into the same problem just today.

It would be great to document the escape order. According to the source code it's:

1. html encode
2. JS encode

But sadly that's documented nowhere. Do you think it's worthwhile to open a new issue to fix the documentation?

Btw, I'm ok with this issue getting closed without a solution. People who need a different order should invoke escapeBody (or similar) multiple times for the order that the need. But documentation would be great!
