### ISSUE TITLE
Cron Expression validation [SPR-14933]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19500]
**[Arcadius Ahouansou](https://jira.spring.io/secure/ViewProfile.jspa?name=arcadius)** opened **[SPR-14933](https://jira.spring.io/browse/SPR-14933?redirect=false)** and commented

With Spring, the 

```
CronSequenceGenerator.parse()
```
method does not seem robust enough....

It silently takes expressions such as 

```
0 0/05 * * * *SUN
```

```
0 0/05 * * * SUN*
```

```
0 0/05 *ANYTHING_HERE * * *
```

as valid cron expressions.

Moreover, 

```
0 0/05 * * * MON-SUN
```
throws 

```
java.lang.IllegalArgumentException: Overflow in day for expression "0 0/05 * * * MON-SUN"
```

Ideally, we want to have a proper and robust cron expression validator.

Note that this issue is related to #13621

---

**Affects:** 4.3.4

**Attachments:**
- [CronExpressionValidationEnhancement.java](https://jira.spring.io/secure/attachment/23626/CronExpressionValidationEnhancement.java) (_1.35 kB_)

**Issue Links:**
- #13621 Cron expression with fixed weekday and fixed date may or may not lead to IllegalStateException (runaway search for next trigger)
- #20163 Cron expression validation method in CronSequenceGenerator improved

**Comment by prasadram** [comment]
Hi Arcadius Ahouansou,

i would like to work on this issue, please let me know whether i can pick this issue or not ?
