### ISSUE TITLE
Add HTTP 1.0 support on Reactor Netty [SPR-14964]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19531]
**[Yevhenii Melnyk](https://jira.spring.io/secure/ViewProfile.jspa?name=yevhenii-melnyk)** opened **[SPR-14964](https://jira.spring.io/browse/SPR-14964?redirect=false)** and commented

**Scenario**

* Web application outputting a sequence of items produced by a `Flux<Item>`, serialized as JSON
* SSE not being used.
* Use Apache Benchmark to perform 1000 requests

**Results**

Web app based on Jetty,Tomcat and Undertow returns result in a reasonable amount of time.
Web app that runs using Reactor Netty or RxNetty doesn't finish. After benchmark timeouts server can't handle requests any more, even single ones from browser.
The following test was performed from localhost as well as from another computer in the same local network. The debug console output is attached.

```java
>ab -n 1000 -c 100 http://localhost:8083/items/10

This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
apr_pollset_poll: The timeout specified has expired (70007)
```

---

**Affects:** 5.0 M3

**Reference URL:** https://github.com/reactor/reactor-netty/issues/21

**Attachments:**
- [netty.log](https://jira.spring.io/secure/attachment/23640/netty.log) (_490.33 kB_)
- [rxjava.log](https://jira.spring.io/secure/attachment/23639/rxjava.log) (_490.31 kB_)

**Issue Links:**
- #19510 Buffering of output in Spring Web Reactive with Netty too aggressive (_**"duplicates"**_)

**Comment by bclozel** [comment]
Superseded by reactor/reactor-netty#21
