### ISSUE TITLE
Document functional configuration style [SPR-15049]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19615]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-15049](https://jira.spring.io/browse/SPR-15049?redirect=false)** and commented

We need to properly document our functional configuration style and other functional-style facilities in Spring 5.

---

**Issue Links:**
- #19398 Add a functional way to register a bean
- #19614 Kotlin extension for GenericApplicationContext with registerBean(KClass) variants
- #19763 Data binding with immutable objects (Kotlin / Lombok / `@ConstructorProperties`)
- #19719 Reference documentation for Groovy bean definition DSL
- #22171 Refactor core documentation to make it relevant for modern Spring applications

**Comment by sdeleuze** [comment]
Duplicate of #25773.
