### ISSUE TITLE
Deprecate RxJava 1 in favor of RxJava 2+3  [SPR-15062]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19628]
**[Juergen Zimmermann](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.zimmermann)** opened **[SPR-15062](https://jira.spring.io/browse/SPR-15062?redirect=false)** and commented

Dávid Karnok classifies reactive libraries into 0..4 generations at http://akarnokd.blogspot.de/2016/03/operator-fusion-part-1.html. IMHO Project Reactor and RxJava 2 belong to the 4th (and latest) generation while RxJava 1.x belongs to the 2nd generation.
https://github.com/ReactiveX/RxJava/tree/2.x shows the development activites for RxJava 2.

---

**Affects:** 5.0 M3

**Reference URL:** http://akarnokd.blogspot.de/2016/03/operator-fusion-part-1.html

**Issue Links:**
- #20056 Upgrade to RxJava 1.3 & 2.1
- #20934 Upgrade to RxJava 2.2

**Comment by poutsma** [comment]
I feel that the amount of RxJava 1.x code out there has not diminished, regardless of EOL. I vote to keep RxJava 1.x support in for 5.2.

**Comment by jhoeller** [comment]
With the launch of RxJava 3 next year, it'll be a good time to deprecate RxJava 1.x at least in our Spring Framework 5.3 timeframe.
