### ISSUE TITLE
Different behavior for @ResponseBody annotation between 4.2.5 and 4.3.5 [SPR-15157]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19723]
**[Niranjan H Rao](https://jira.spring.io/secure/ViewProfile.jspa?name=nhrdls)** opened **[SPR-15157](https://jira.spring.io/browse/SPR-15157?redirect=false)** and commented

We are trying to migrate from 4.2.5 to 4.3.5. We have a method like follows

```java
@ResponseBody
	public Map<String, Serializable> method() {}
```

This method works in 4.2.5, but in 4.3.5 it throws exception as follows

```java
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class java.util.HashMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: java.util.HashMap["result"])
```

After changing method signature to use Object instead of Serializable, it works in 4.3.5 release too. Something is different the way jackson is handled in 4.3.5.

```java
@ResponseBody
	public Map<String, Object> method() {}
```

---

**Affects:** 4.3.5

**Comment by bclozel** [comment]
I believe this is tied to the Jackson version and Jackson's behavior only.
Could you provide a project reproducing this issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
