### ISSUE TITLE
Spring MVC @RequestMapping should allow routing based on request body contents [SPR-15169]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19735]
**[Jacques Chester](https://jira.spring.io/secure/ViewProfile.jspa?name=jacques_chester)** opened **[SPR-15169](https://jira.spring.io/browse/SPR-15169?redirect=false)** and commented

Commonly, routing is based on a combination of HTTP method (POST, GET) and URI components (path, query params).

We have a product in which there are "generate" and "regenerate" operations, which can be applied to various "types" (vagueness for effect).

In a URI-based scheme, we might have done something like:

```
@PostMapping(path = "/a_type")
  public ResponseEntity generateAType( ... )  {
  generateAType();
 }

@PostMapping(path = "/a_type", params={"regenerate=true"})
  public ResponseEntity generateAType( ... )  {
  regenerateAType();
 }
```

Then `POST /a_type` would create a new record, and `POST /a_type?regenerate=true` would regenerate a record. (We're handwaving away some other details).

However, for customer reasons, we cannot encode either of type or operation into the URI. Instead we have to embed these into a JSON payload. Currently in Spring it seems we could route based on matrix variables, query params or request attributes.

What we'd like is something similar for JSON payloads. For example, something like:

```
@PostMapping(path = "/a_type", payloadParams={"regenerate=true"})
  public ResponseEntity generateAType( ... )  {
  regenerateAType();
 }
```

---

**Affects:** 4.3.5

**Comment by bclozel** [comment]
We didn't get much demand for this, so I'm closing this issue for now. Given the dramatic change in the web framework infrastructure, this requires a lot of changes and redesign. Currently this is not worth the effort it seems.

If we get more votes and compelling use cases for this, we might reconsider.
