### ISSUE TITLE
util:properties  write spring-el for ignore-resource-not-found to make it dynamic [SPR-15174]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19740]
**[Alireza Fattahi](https://jira.spring.io/secure/ViewProfile.jspa?name=afattahi)** opened **[SPR-15174](https://jira.spring.io/browse/SPR-15174?redirect=false)** and commented

It will be good idea if we can write spring-el for

```java
ignore-resource-not-found
```

of ```java
util:properties

```

and other tags.

Thanks!
```

---
No further details from [SPR-15174](https://jira.spring.io/browse/SPR-15174?redirect=false)

**Comment by jhoeller** [comment]
I'm afraid that at this point we don't intend to revise the XML configuration model at all anymore.
