### ISSUE TITLE
Property Source Preprocessor [SPR-15187]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19753]
**[Caleb Cushing](https://jira.spring.io/secure/ViewProfile.jspa?name=xenoterracide)** opened **[SPR-15187](https://jira.spring.io/browse/SPR-15187?redirect=false)** and commented

Maybe this is already possible somehow... due to security issues like https://github.com/flyway/flyway/issues/1500

it might be nice to be able to define a property preprocessor, where the property goes through a `String bifunction (String key, String value)` before further processing. Of course alternative APIs with specific types may be better.This would allow one to quote the value before it was handed to is destination (basically before you can get it from `Environment`)

---
No further details from [SPR-15187](https://jira.spring.io/browse/SPR-15187?redirect=false)

**Comment by snicoll** [comment]
Thanks for the suggestion. I find this a bit arbitrary and I find [this argument](https://github.com/flyway/flyway/issues/1500#issuecomment-272000549) particularly compelling. Closing as a result.
