### ISSUE TITLE
More specific RequestMapping is suddenly ignored when adding produces attribute [SPR-15185]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19751]
**[Stephen Harper](https://jira.spring.io/secure/ViewProfile.jspa?name=steveyh25)** opened **[SPR-15185](https://jira.spring.io/browse/SPR-15185?redirect=false)** and commented

I have a controller with a single `@RequestMapping(value = "test.htm")`.

I then have 2 methods annotated as follows:

```java
@GetMapping(params = "req=test", produces = MediaType.APPLICATION_JSON_VALUE)

@GetMapping
```

If I remove the produces attribute from method 1, then it is the one that always gets hit with a request like:

http://x.x.x.x/test.htm?req=test

however, adding produces `MediaType.APPLICATION_JSON_VALUE`, method 2 is always the one being hit even with request headers as follows:

```
Accept:application/json, text/javascript, */*;
```

If I change to produces to `MediaType = MediaType.ALL_VALUE`, then it starts working again...

---

**Affects:** 4.3.4

**Comment by rstoyanchev** [comment]
This is expected behavior. You [can configure](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-content-negotiation) how to resolve the content type for the response and for example decide to turn off use of path extensions.
