### ISSUE TITLE
Support RSS in Spring WebFlux [SPR-15224]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19789]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-15224](https://jira.spring.io/browse/SPR-15224?redirect=false)** and commented

---
No further details from [SPR-15224](https://jira.spring.io/browse/SPR-15224?redirect=false)

**Comment by bclozel** [comment]
Closing due to lack of demand for this feature.
