### ISSUE TITLE
InvocableHandlerMethod calls makeAccessible(getBridgedMethod()) on every call [SPR-15230]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19795]
**[Gary Russell](https://jira.spring.io/secure/ViewProfile.jspa?name=grussell)** opened **[SPR-15230](https://jira.spring.io/browse/SPR-15230?redirect=false)** and commented

This could be done once in the `HandlerMethod` ctor where the field is set up, although perhaps `getBridgedMethod()` should be `final` ?

---

**Affects:** 4.3.6

**Comment by rstoyanchev** [comment]
We generally re-create the `InvocableHandlerMethod` as a wrapper around `HandlerMethod` but you have a point that this could probably be moved up to `HandlerMethod` at the point where `bridgedMethod` is initialized. I'll have a closer look at all the `InvocableHandlerMethod` variants we have in web and messaging code.
