### ISSUE TITLE
should be (conveniently) enable/disable tasks based on external property in xml namespace of task [SPR-15228]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19793]
**[Kunal Patel](https://jira.spring.io/secure/ViewProfile.jspa?name=patelkunal)** opened **[SPR-15228](https://jira.spring.io/browse/SPR-15228?redirect=false)** and commented

As a developer, I would wish to enable/disable scheduled tasks based on some business condition (technically - its external properties or decide behavior programmatically).

**Scenarios**
* this is very common behavior in of many business application where you don't want to enable scheduler to schedule a task by default but you wish to have a way to toggle based on external property or programmatically decide to enable or disable.
* Another common case would be your test case setup - mostly we don't schedule a task instead we mock instead of scheduled-task to populate the state.

Currently we schedule any task like below but AFAIK its not possible to toggle behavior of task (enable/disable).

```xml
<task:scheduler id="serviceScheduler" pool-size="1"/>
<task:scheduled-tasks scheduler="serviceScheduler">
          <task:scheduled ref="service" method="scheduledMethod"
                        fixed-delay="${interval:180000}"
                        initial-delay="${start.delay:60000}"/>
</task:scheduled-tasks>
```

**Suggestion**
We should be conveniently toggle behavior of task:scheduled using property/value tag in xml (so value can be injected from property placeholders or invoke method to decide behavior programmatically.

Again this is improvement I am suggesting - it can be be taken up based on bandwidth.

Thanks,
/kp

---
No further details from [SPR-15228](https://jira.spring.io/browse/SPR-15228?redirect=false)

**Comment by poutsma** [comment]
As stated in that same SO link, this is now possible using Boot's `@ConditionalOnProperty`.
