### ISSUE TITLE
Ability to use `@ContextConfiguration` directly and as meta-annotation on the same class [SPR-15274]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19839]
**[Réda Housni Alaoui](https://jira.spring.io/secure/ViewProfile.jspa?name=reda-alaoui)** opened **[SPR-15274](https://jira.spring.io/browse/SPR-15274?redirect=false)** and commented

Hello,

We have a project split up into multiple modules. Among them there are:
- `database` module
- `stream` module

Each of them defines a test project (database-test, stream-test)

And there is a consumer of these modules:
- `cqrs` module

`cqrs` has a mandatory dependency on the `database` module and optional dependency on the `stream` module.
Therefore the `AbstractCqrsIntegrationTest` extends `AbstractDataIntegrationTest` and cannot extend an abstract `stream` test class.

What I wanted to do was to create this meta annotation in the `stream` module:

```java
@Target({ ElementType.TYPE, ElementType.ANNOTATION_TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@ContextConfiguration(
		classes = {StreamConfigurationTest.class},
		initializers = StreamEnvironmentInitializerTest.class
)
public @interface EnableStreamTest {

}
```

And use it in `cqrs`:

```java
@EnableStreamTest
@ContextConfiguration(
        classes = {CqrsConfigurationTest.class},
        loader = AnnotationConfigContextLoader.class,
		initializers = CqrsEnvironmentInitializer.class
)
public abstract class AbstractCqrsIntegrationTest extends AbstractDataIntegrationTest {

}
```

But `@ContextConfiguration` coming from meta annotation is ignored and replaced by the one declared directly on `AbstractCqrsIntegrationTest`.

I know that `@ContextConfiguration` are correctly merged by traversing only superclasses. But this doesn't apply to my need.

Would it be possible to fetch all declared `@ContextConfiguration` at the class level?
It seems it would require to add a method in `MetaAnnotationUtils` similar to:

```java
private static UntypedAnnotationDescriptor findAnnotationDescriptorForTypes(Class<?> clazz,
			Set<Annotation> visited, Class<? extends Annotation>... annotationTypes)}} 
```

that would return a list of descriptors and to use that list inside `AbstractTestContextBootstrapper.buildMergedContextConfiguration`.

---

**Issue Links:**
- #18245 `@ContextConfiguration` defined on a base class and a composed annotation do not merge

**Comment by snicoll** [comment]
@sbrannen I can see you've assigned yourself and I am wondering if that wouldn't be a duplicate of #26142 that has been declined.

**Comment by sbrannen** [comment]
- Duplicate of #26142
