### ISSUE TITLE
Allow for CachingMetadataReaderFactory cache size to be easily updated [SPR-15278]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19844]
**[Mikhail Dobrinin](https://jira.spring.io/secure/ViewProfile.jspa?name=mvd)** opened **[SPR-15278](https://jira.spring.io/browse/SPR-15278?redirect=false)** and commented

Currently there doesn't appear to be any good way to set the the cache limit (`CachingMetadataReaderFactory.setCacheLimit(int)`). For example you can't set this limit through AnnotationConfigApplicationContext since the scanner field doesn't have a setter and more importantly is final. This could be a potential setting for certain applications to improve their performance.

---

**Affects:** 4.2.9

**Issue Links:**
- #19219 Cache ASM metadata at the context level

**Comment by jhoeller** [comment]
Effectively superseded by the specifically managed context-level cache in #19219: for AnnotationConfigApplicationContext usage, a locally configured cache limit will not be used anymore to begin with.
