### ISSUE TITLE
Error in CORS WebFilter documentation of web-reactive

### ISSUE THREAD

**Issue by jvwilge** [spring-projects/spring-framework#19841]
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-cors-webfilter

I think the code sample in the link above is incorrect and should be : 
```
  @Bean
  public CorsConfigurationSource corsConfigurationSource(){
       CorsConfiguration config = new CorsConfiguration();

    // Possibly...
    // config.applyPermitDefaultValues()

    config.setAllowCredentials(true);
    config.addAllowedOrigin("http://domain1.com");
    config.addAllowedHeader("*");
    config.addAllowedMethod("*");

    UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
    source.registerCorsConfiguration("/**", config);
    return source;
  }
```

The class `ServerHttpSecurity.java` creates the corsFilter with a CorsConfigurationSource, so a CorsWebFilter is never injected :

```
public CorsSpec configurationSource(CorsConfigurationSource source) {
	this.corsFilter = new CorsWebFilter(source);
	return this;
}
```

https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L471

The javadoc also suggests you should use a CorsConfigurationSource so it can create a CorsWebFilter itself :
https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L421

**Comment by rstoyanchev** [comment]
What you're pointing out [is documented](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#cors) in Spring Security. The example in the Spring Framework reference is for the underlying mechanism, which is unware of the Spring Security configuration is layered on top.
