### ISSUE TITLE
Support of MockRestServiceServer for WebClient [SPR-15286]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19852]
**[Stéphane Nicoll](https://jira.spring.io/secure/ViewProfile.jspa?name=snicoll)** opened **[SPR-15286](https://jira.spring.io/browse/SPR-15286?redirect=false)** and commented

Spring Boot has a `@RestClientTest` for pure client-side tests. We currently auto-configure `MockRestServiceServer` and bind any `RestTemplate` created by the `RestTemplateBuilder` to it.

This would be pretty awesome if we could port that feature to `WebClient` transparently if webflux is on the classpath. That would require that `MockRestServiceServer` can be configured with a `WebClient` in addition to a `RestTemplate`

---

**Sub-tasks:**
- #19295 Document how to test WebClient code with a mock server

15 votes, 24 watchers

**Comment by membersound** [comment]
Using `WebClient` for client-side requests is pretty useless if there is no proper mock in spring for testing our code. Having rewritten my `RestTemplate` client code to `WebClient`, I'm disappointed there is no replacement for `MockRestServiceServer` yet...

**Comment by dsundarraj2** [comment]
@membersound Have you used wiremock ?
WireMock can be used for mocking the responses for WebClient. Check this code repo which has examples for the same.
Repo:
https://github.com/code-with-dilip/learn-wiremock/tree/master/learn-wiremock-spring-cloud
TestCases:
https://github.com/code-with-dilip/learn-wiremock/blob/master/learn-wiremock-spring-cloud/src/test/java/com/learnwiremock/service/UserServiceWireMockRuleTest.java.
Cheers!

**Comment by membersound** [comment]
While this might work, I'd prefer relying on some kind of "official" framework, eg something that's included and maintained by spring themselves. Otherwise, if WebClient evolves by time, and WireMock is left behind, that might led to rewrites for all of my projects. As we all know, time is money, so that's too risky...

**Comment by rstoyanchev** [comment]
@membersound I appreciate the point but there is also a lot of effort involved to create, maintain, and evolve something over time and it's hard to justify given the existing alternatives. HTTP provides loose coupling so implementations can exist and evolve independently. In this case we're even talking about mocking a server and shaping its behavior. I should think that switching from one to another shouldn't be as big a deal as it might seem at first. That said MockWebServer has more stars than the Spring Framework does and I don't think it is going to be a problem with longevity.

**Comment by SFBorland** [comment]
Is it listed somewhere in the official docs that MockWebServer is the recommended solution? I've spent a few days now looking for an official Spring version or trying to get existing stuff to work and finally stumbled on this thread..

**Comment by bclozel** [comment]
@SFBorland We [added a note about that in the reference documentation](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-client-testing).

**Comment by SFBorland** [comment]
@bclozel I see it now...thanks.

**Comment by rstoyanchev** [comment]
Closing as we have no further plans at this time.
