### ISSUE TITLE
MethodValidationPostProcessor not respecting aspect order [SPR-15315]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19878]
**[Mohana Rao S V](https://jira.spring.io/secure/ViewProfile.jspa?name=mohanraosv)** opened **[SPR-15315](https://jira.spring.io/browse/SPR-15315?redirect=false)** and commented

Not able to control the order of MethodValidationPostProcessor aspect.

Similar to #16397

---

**Affects:** 4.3.7

**Attachments:**
- [SPR-15315.zip](https://jira.spring.io/secure/attachment/23796/SPR-15315.zip) (_9.14 kB_)

**Issue Links:**
- #16397 Asynchronous method execution is always invoked before bean validation

**Comment by snicoll** [comment]
I am going to close this as the sample project has two tests and they work, changing the commented line that invokes `setBeforeExistingAdvisors` has no effect. At this point, I don't know how different it is from #13297. If the sample is updated or additional explanation is provided, we can reopen.
