### ISSUE TITLE
Make use of Servlet 4.0 mapping introspection when available [SPR-15320]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19883]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-15320](https://jira.spring.io/browse/SPR-15320?redirect=false)** and commented

Servlet 4.0 b03 is available now, introducing support for `HttpServletRequest.getServletMapping()`. As discussed, let's research what we can transparently infer from this when available at runtime, as an alternative to "guessing" about Servlet-level URL mappings in `UrlPathHelper`. If there isn't any distinct advantage, we can also keep our path-based code as it is, but we should make up our mind in time for 5.0 RC1 here.

---

**Issue Links:**
- #17273 Support for Servlet 4.0 API
- #19942 Compatibility with Servlet 4.0 final draft
- #20434 Upgrade to Servlet API 4.0 for MVC (PushBuilder and Servlet mocks)

**Comment by rstoyanchev** [comment]
This is superseded by #25100.
