### ISSUE TITLE
UriComponentsBuilder fromHttpRequest breaks with relative URIs [SPR-15327]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19890]
**[Tapio Rautonen](https://jira.spring.io/secure/ViewProfile.jspa?name=trautonen)** opened **[SPR-15327](https://jira.spring.io/browse/SPR-15327?redirect=false)** and commented

We are building relative URIs with `UriComponentsBuilder` `fromHttpRequest` method. Everything works fine if the `X-Forwarded-Proto` header is available because it sets the scheme, but same method can be used when there is no proxy in front of the service. In this case if `HttpRequest` `getURI` method returns a relative URI, eg. `/` a `NullPointerException` is thrown because scheme comparison is not null safe.

This can be easily reproduced with a following example.

```java
HttpRequest request = new HttpRequest() {
	@Override
	public HttpMethod getMethod() {
		return HttpMethod.GET;
	}

	@Override
	public URI getURI() {
		return UriComponentsBuilder.fromUriString("/").build().toUri();
	}

	@Override
	public HttpHeaders getHeaders() {
		return new HttpHeaders();
	}
};

UriComponentsBuilder.fromHttpRequest(request);
// java.lang.NullPointerException
```

---

**Affects:** 4.3.6

**Reference URL:** https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java#L738-L741

**Comment by poutsma** [comment]
I cannot reproduce this in 5.1.x nor in 5.2.x, so I am assuming that it has been fixed in the mean time. Closed as invalid.
