### ISSUE TITLE
Load Time Weaving not working after upgrading Tomcat from 7.0.60 to 7.0.70 [SPR-15328]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19891]
**[PalMurugan](https://jira.spring.io/secure/ViewProfile.jspa?name=palmuruganc)** opened **[SPR-15328](https://jira.spring.io/browse/SPR-15328?redirect=false)** and commented

Load Time Weaving not working after upgrading my tomcat version from 7.0.60 to 7.0.70. Please guide me to resolve this issue.

2017-03-08 09:20:23,637 |INFO [localhost-startStop-1] c.g.t.c.AspectWeavingConfiguredConditional$Condition - aspect.enabled is true
2017-03-08 09:20:28,470 |INFO [localhost-startStop-1] c.g.t.c.AspectWeavingConfiguredConditional$Condition - aspect.enabled is true
Mar 08, 2017 9:20:31 AM org.apache.catalina.loader.WebappClassLoaderBase addTransformer
INFO: Added class file transformer [org.springframework.context.weaving.AspectJWeavingEnabler$AspectJClassBypassingClassFileTransformer@b819e7a] to web application [/universalEngine].
[WebappClassLoader@6037c868] info register aspect org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect
[WebappClassLoader@6037c868] info register aspect org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspect
[WebappClassLoader@6037c868] info register aspect org.springframework.transaction.aspectj.AnnotationTransactionAspect
[WebappClassLoader@6037c868] info register aspect org.springframework.transaction.aspectj.JtaAnnotationTransactionAspect
[WebappClassLoader@6037c868] info register aspect org.springframework.cache.aspectj.AnnotationCacheAspect
[WebappClassLoader@6037c868] info register aspect org.springframework.cache.aspectj.JCacheCacheAspect
[WebappClassLoader@6037c868] info deactivating aspect 'org.springframework.cache.aspectj.JCacheCacheAspect' as it requires type 'javax.cache.annotation.CacheResult' which cannot be found on the classpath
[WebappClassLoader@6037c868] info register aspect com.ghx.testframework.aspect.BrokerComponentStatisticsAspect
[WebappClassLoader@6037c868] warning at com/ghx/testframework/aspect/BrokerComponentStatisticsAspect.java::0 no match for this type name: com.ghx.eventbroker.BrokerComponent [Xlint:invalidAbsoluteTypeName]
[WebappClassLoader@6037c868] info register aspect com.ghx.testframework.aspect.RuleEngineAspect
[WebappClassLoader@6037c868] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified

Note : Everything is registered properly but Intercept (Around - AOP) is not working.

Thank you,
Pal Murugan C

---
No further details from [SPR-15328](https://jira.spring.io/browse/SPR-15328?redirect=false)

**Comment by snicoll** [comment]
Unfortunately, there's nothing actionable on this issue, even more so on a such old version of tomcat and without a reproducer. Sorry this got overlooked.
