### ISSUE TITLE
Add support for I18n messages file with YAML [SPR-15353]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19916]
**[Sérgio Vale e Pace](https://jira.spring.io/secure/ViewProfile.jspa?name=svpace)** opened **[SPR-15353](https://jira.spring.io/browse/SPR-15353?redirect=false)** and commented

Add support for I18n messages files in YAML format like it has been added to application properties

---

**Affects:** 4.3.7

1 votes, 2 watchers

**Comment by snicoll** [comment]
Thanks for the suggestion but i18n message bundle are defined outside the scope of Spring so we'll stick to that.
