### ISSUE TITLE
StringToCollectionConverter splits string by comma [SPR-15356]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19919]
**[None](https://jira.spring.io/secure/ViewProfile.jspa?name=t3rm1)** opened **[SPR-15356](https://jira.spring.io/browse/SPR-15356?redirect=false)** and commented

When you submit a form (only tried post) with a parameter that includes a comma, and the parameter is bound to a List\<String> then this value is passed through to the method `org.springframework.core.convert.support.StringToCollectionConverter.convert(Object, TypeDescriptor, TypeDescriptor)`. That method then splits the String at the comma, resulting in a list with two elements instead of one.

I understand that comma is used to split array values in the url. I checked the raw request and the comma is translated to %2C so this shouldn't happen. It must be a bug somewhere in the call hierachy.

This problem only exists if **one** value is submitted for the list. If two or more values are submitted (e.g. two checkboxes checked) then a different converter is choosen (array to list) and no comma splitting is done.

---

**Affects:** 4.3.7

**Comment by RomainWilbert** [comment]
Same issue here...even if the comma is escaped (%2C) the string is split into 2 values :(

**Comment by rstoyanchev** [comment]
This is actually a duplicate of #23820.

**Comment by fy-kenny** [comment]
I redirect request parameters contains String arrays, but the dest request received `one,two,...` as only one param.  how can i delimiter automatically. @rstoyanchev

Class Pojo {
  List<String> list;
}

redirectAttributes.addAllAttributes(request.getParameterMap());
