### ISSUE TITLE
Spring classes and application proxies not collected after closing context [SPR-15380]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19943]
**[Christophe Bismuth](https://jira.spring.io/secure/ViewProfile.jspa?name=cbismuth)** opened **[SPR-15380](https://jira.spring.io/browse/SPR-15380?redirect=false)** and commented

Hi,

I have a memory leak issue, I may have misused Spring Java configuration capabilities.

* I start a Tomcat application server 8.5 instance with default management application and my Spring 4 application (the only Spring application in Tomcat)
* I stop only my application from the Tomcat manager UI
* I click on the "Find leaks" button from the Tomcat Manager UI to trigger a full Java GC
* Tomcat says my application causes memory leaks
* I open JProfiler and take a full Java Heap snapshot

As shown in attachments:

* Some Spring classes aren't collected
* My Spring components are all collected
* My Spring configuration CGLIB proxies are not collected
* It seems to exist to cyclic dependency between these proxies

Should everything related to Spring be collected after application being stopped?

---

**Affects:** 4.2.9, 4.3.7

**Attachments:**
- [Heap_Walker_Classes_Application.csv](https://jira.spring.io/secure/attachment/23820/Heap_Walker_Classes_Application.csv) (_1.26 kB_)
- [Heap_Walker_Classes_Spring.csv](https://jira.spring.io/secure/attachment/23819/Heap_Walker_Classes_Spring.csv) (_7.93 kB_)
- [javaconfig.png](https://jira.spring.io/secure/attachment/23824/javaconfig.png) (_198.87 kB_)
- [screencapture-file-home-cbismuth-Desktop-Heap_Walker_Classes_2-html-1490518670213.png](https://jira.spring.io/secure/attachment/23822/screencapture-file-home-cbismuth-Desktop-Heap_Walker_Classes_2-html-1490518670213.png) (_177.86 kB_)
- [screencapture-file-home-cbismuth-Desktop-Heap_Walker_Classes-html-1490518604963.png](https://jira.spring.io/secure/attachment/23821/screencapture-file-home-cbismuth-Desktop-Heap_Walker_Classes-html-1490518604963.png) (_859.39 kB_)
- [screencapture-file-home-cbismuth-Desktop-Heap_walker_Incoming_References-html-1490518709454.png](https://jira.spring.io/secure/attachment/23823/screencapture-file-home-cbismuth-Desktop-Heap_walker_Incoming_References-html-1490518709454.png) (_162.86 kB_)

**Comment by snicoll** [comment]
Closing as we established quite some time ago to not be related to the core container.
