### ISSUE TITLE
Add support for Kotlin coroutines [SPR-15413]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19975]
**[Konrad Kamiński](https://jira.spring.io/secure/ViewProfile.jspa?name=konrad-kaminski)** opened **[SPR-15413](https://jira.spring.io/browse/SPR-15413?redirect=false)** and commented

Since `1.1` Kotlin supports [coroutines](https://kotlinlang.org/docs/reference/coroutines.html). Its [library support](https://github.com/Kotlin/kotlinx.coroutines) includes [utility functions](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-jdk8) for converting _suspending functions/lambdas_ to/from [CompletableFuture](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) / [Deferred](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/-deferred/index.html). It would be nice to have such support [ListenableFuture](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/concurrent/ListenableFuture.html) as well.

The API could look as follows:

```kotlin
// a function for creating ListenableFuture from suspending lambda
fun <T> listenableFuture(context: CoroutineContext = CommonPool, block: suspend () -> T): ListenableFuture<T>

// a function for creating ListenableFuture from Deferred
fun <T> Deferred<T>.asListenableFuture(): ListenableFuture<T>

// an extension suspending function which awaits for ListenableFuture completion
suspend fun <T> ListenableFuture<T>.await(): T
```

---

**Affects:** 5.0 M5

**Issue Links:**
- #21058 Incorrect return type of Kotlin suspending functions

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1375

18 votes, 26 watchers

**Comment by sdeleuze** [comment]
Coroutines support for `WebClient` and WebFlux.fn has been merged in `master` branch via [this commit](https://github.com/spring-projects/spring-framework/commit/19f792db66231e95f19105c7e6067595431b3716) which is the first part of a more complete Coroutines support coming in Spring Framework 5.2. It introduces suspendable Kotlin extensions for `Mono` based  methods in WebFlux classes like `WebClient`, `ServerRequest`, `ServerResponse` as well as a Coroutines router usable via `coRouter { }`. See more details in the [Coroutines section](https://docs.spring.io/spring/docs/5.2.0.BUILD-SNAPSHOT/spring-framework-reference/languages.html#coroutines) of the reference documentation.

Coroutines extensions use `await` prefix or `AndAwait` suffix, and most are using names close to their Reactive counterparts, except `exchange` in `WebClient.RequestHeadersSpec` which translates to `awaitResponse`.

Upcoming expected changes are:
 - Leverage `Dispatchers.Unconfined` (Kotlin/kotlinx.coroutines#972)
 - Expose extensions for `Flux` based API (Kotlin/kotlinx.coroutines#254)
 - Introduce interop with `CoroutineContext` (Kotlin/kotlinx.coroutines#284)
 - Support Coroutines in `ReactiveAdapterRegistry`
 - Support Coroutines for WebFlux annotated controllers
 - Fix return type of Kotlin suspending functions (gh-21058)

A demo project is available in this [spring-boot-coroutines-demo](https://github.com/sdeleuze/spring-boot-coroutines-demo) repository.

**Comment by sdeleuze** [comment]
Support for WebFlux annotated controllers, including view resolution and `Deferred`, has been merged in `master` branch. See [this sample Coroutines controller](https://github.com/sdeleuze/spring-boot-coroutines-demo/blob/master/src/main/kotlin/com/example/CoroutinesController.kt) for a concrete example.

**Comment by sdeleuze** [comment]
With Coroutines `Flow` support, Spring Framework Coroutines support is now complete. See https://github.com/sdeleuze/spring-boot-coroutines-demo for concrete examples of `Flow` usage and also see :
 - [`Flow` documentation](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html)
 - [Preview status](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/compatibility.md#flow-preview-api)
 - [The related GitHub issue](https://github.com/Kotlin/kotlinx.coroutines/issues/254) for feedback since `Flow` API is not frozen yet

A detailed blog post is coming next week to present an overview of Spring Coroutines support.
