### ISSUE TITLE
ResolvableType.isInstance(Object) does not support dynamic proxies [SPR-15458]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20019]
**[Lukas Jusko](https://jira.spring.io/secure/ViewProfile.jspa?name=ljusko)** opened **[SPR-15458](https://jira.spring.io/browse/SPR-15458?redirect=false)** and commented

Method isInstance(object) returns false even if object is instance of given type. When incoming object is JDK proxy, object.getClass() returns com.sun.Proxy class instead of proxied class. Then this method evaluates to false, even if I'd expect to be true. Works only for CGLib proxies.

---
No further details from [SPR-15458](https://jira.spring.io/browse/SPR-15458?redirect=false)

**Comment by snicoll** [comment]
Closing due to the lack of feedback.
