### ISSUE TITLE
RootBeanDefinition does not return $-separated classname on inner classes anymore [SPR-15473]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20033]
**[Elis Edlund](https://jira.spring.io/secure/ViewProfile.jspa?name=elisedlund)** opened **[SPR-15473](https://jira.spring.io/browse/SPR-15473?redirect=false)** and commented

In previous version I got a correct classname in my custom DefaultListableBeanFactory by fetching it from the RootBeanDefinition, Example doing something like this:
private Class<?> figureOutClass(final RootBeanDefinition mbd) {
String className = mbd.getBeanClassName();
return Class.forName(className);
}
This still works fine for regular classes but not internal ones like the following:

```java
public class BeanTest {
    @Test
    public void someTest() {
      MyClass c = new MyClass() {
            public String getEscString() {
                return "\"'><&&";
            }
        };
    //some testing 
    }

        public class MyClass2() {
            public String getEscString() {
                return "\"'><&&";
            }
        };
}
```

both MyClass2 and MyClass will be resolved to the names:
com.somepackage.BeanTest.MyClass1
com.somepackage.BeanTest.MyClass2
when using mbd.getBeanClassName();
instead of the expected (and how it worked before)
com.somepackage.BeanTest$MyClass1
com.somepackage.BeanTest$MyClass2

---

**Affects:** 4.3.7

**Comment by snicoll** [comment]
I think this issue as run its course.
