### ISSUE TITLE
Local @Sql annotation is favored over @Sql in composed annotation [SPR-15493]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20053]
**[Heiko Kolter](https://jira.spring.io/secure/ViewProfile.jspa?name=okieh)** opened **[SPR-15493](https://jira.spring.io/browse/SPR-15493?redirect=false)** and commented

After switching from Version 4.2.5.RELEASE to   4.3.8 RELEASE  execution of Unit-Test fails

---

**Affects:** 4.3.8

**Comment by sbrannen** [comment]
> So mixing local `@SQL` with `@SQL` in composed annotation seems not to be the right approach, if order of execution matters.

That's correct.

> What would be a better approach from your point of view?

The only thing I can think of is to use composed annotations for all of your `@Sql` declarations, since you want to make use of composed annotations.

The order should still guaranteed if you use all local annotations _or_ all composed annotations.
