### ISSUE TITLE
Offer compile time support for `@Configuration` classes  [SPR-15512]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20071]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[SPR-15512](https://jira.spring.io/browse/SPR-15512?redirect=false)** and commented

During some discussion on the Spring Boot call about [this issue](https://github.com/spring-projects/spring-boot/issues/9068) we discussed the benefits of not needing to use CGLib for configuration classes.

A typical Spring Boot application will load 50-70 configurations and each one needs bytecode generation and increases the amount of memory used.

One option that Stephane suggested was to do the bytecode manipulation an compile time rather than runtime. We could possibly use an annotation processor to rewrite the methods and call some common SPI that both `ConfigurationClassEnhancer` and us could share.

---

0 votes, 6 watchers

**Comment by bclozel** [comment]
Closing as a duplicate of #28065.
In the meantime, we've decided to perform `@Configuration` classes analysis during the AOT phase and generate Java sources that describe the state of the resulting bean factory.
