### ISSUE TITLE
Add onChangeListener support to MutablePropertySources [SPR-15514]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20073]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[SPR-15514](https://jira.spring.io/browse/SPR-15514?redirect=false)** and commented

Spring Boot would like to track when property sources are changed on a `MutablePropertySources` instance. One way to do this would be to add listener support.

---
No further details from [SPR-15514](https://jira.spring.io/browse/SPR-15514?redirect=false)

**Comment by snicoll** [comment]
@philwebb I am wondering if Spring Boot still needs this. I've had a look on `main` and I couldn't find back the code you've referenced.

**Comment by philwebb** [comment]
@snicoll  I think this can be closed now, the caching approach we take has moved on a lot. We can always reopen the issue if do another round of performance work in that area.
