### ISSUE TITLE
Support nonblocking writing to Jetty Websocket with possibility to assign callback [SPR-15527]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20086]
**[Askar Ibragimov](https://jira.spring.io/secure/ViewProfile.jspa?name=askaribragimov)** opened **[SPR-15527](https://jira.spring.io/browse/SPR-15527?redirect=false)** and commented

Jetty websocket server has two ways to send messages:

* blocking Write http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/RemoteEndpoint.html#sendBytes-java.nio.ByteBuffer-
* non-blocking Write http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/RemoteEndpoint.html#sendBytes-java.nio.ByteBuffer-org.eclipse.jetty.websocket.api.WriteCallback- and http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/RemoteEndpoint.html#sendBytesByFuture-java.nio.ByteBuffer-

Presently Spring Websocket uses blocking write in Jetty adapter. Which means that the message engine of Spring (ExecutorSubscribableChannel) has to have many threads and a thread remains parked till client acknowledges the reception of message.

**There are few issues with this approach**
* If client never acknowledges the reception on TCP level, the thread (from TaskExecutorChannel's threadpool) remains blocked. Actually due to a very funny decision of Jetty engineers to not set a timeout on these connections, so the block is never lifted (https://github.com/eclipse/jetty.project/issues/272). In plain language, any Spring+Jetty app is exposed to a DDOS attack.
* This is a bad utilization of threads. I might want to write a logic that re-uses the thread for something else and just get notified via callback when web socket processed the message. This would allow me to have smaller thread pools and truly high-load-ready nonblocking architecture.

**Suggested improvement**
Permit in Spring usage of non-blockig websocket write with possibility to expose respective callback or future on upper level. Then custom or new ExecutorChannel implementation may use these callbacks to smartly utilize smaller number of threads and do not have blocked threads.

Useful contribution from Jetty people (caveats of using non blocking API of Jetty) http://stackoverflow.com/questions/43257736/make-websocket-sending-non-blocking

---

**Issue Links:**
- #18180 Jetty - use Async Send like Atmosphere does
- #18671 Expose asynchronous message sending in WebSocketSession

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/1b0e95d7d82435d7c532b597eab7cf86265fdbe1

1 votes, 3 watchers

**Comment by rstoyanchev** [comment]
WebFlux provides an async/non-blocking WebSocket API for Jetty included.
