### ISSUE TITLE
Inferred type does not conform to upper bound in AbstractClientHttpRequest/AbstractServerHttpResponse [SPR-15534]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20093]
**[fainted](https://jira.spring.io/secure/ViewProfile.jspa?name=fainted)** opened **[SPR-15534](https://jira.spring.io/browse/SPR-15534?redirect=false)** and commented

When building the latest spring-framework from GitHub, the code is not building and failing at module spring-web.

Just a brief for the issue

The code compiles for all previous modules, it only fails at spring-web with below error

E:\spring-framework-master\spring-web\src\main\java\org\springframework\http\client\reactive\AbstractClientHttpRequest.java:132: error: incompatible types: inferred type does not conform to upper bound(s)
.map(Supplier::get).collect(Collectors.toList());
^
inferred: ? extends Mono\<Void>
upper bound(s): Object
E:\spring-framework-master\spring-web\src\main\java\org\springframework\http\server\reactive\AbstractServerHttpResponse.java:197: error: incompatible types: inferred type does not conform to upper bound(s)
.map(Supplier::get).collect(Collectors.toList());
^
inferred: ? extends Mono\<Void>
upper bound(s): Object
2 errors

---

### +Environment Details+

**Java:**
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) Client VM (build 25.5-b02, mixed mode)

**Gradle:**

---

Gradle 2.14.1

---

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_05 (Oracle Corporation 25.5-b02)
OS:           Windows 7 6.1 x86

**I have also attached log file with stack trace and other debug info.**

---

**Affects:** 5.0 RC1

**Attachments:**
- [log.txt](https://jira.spring.io/secure/attachment/24918/log.txt) (_106.30 kB_)

**Comment by snicoll** [comment]
I am going to close this as this issue is no longer actionable.
