### ISSUE TITLE
Method to Intercept @Scheduled and @Async without AOP [SPR-15562]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20121]
**[Jon Schneider](https://jira.spring.io/secure/ViewProfile.jspa?name=jschneider)** opened **[SPR-15562](https://jira.spring.io/browse/SPR-15562?redirect=false)** and commented

Both Spring Cloud Sleuth and Spring Metrics (and less likely, security?) could benefit from a method to intercept and instrument `@Scheduled` and `@Async` methods that doesn't require AOP.

Perhaps interceptors could be folded into the registration process in `ScheduledAnnotationBeanPostProcessor`?

---

**Affects:** 5.0 RC2

**Comment by jhoeller** [comment]
@bclozel has this come up again with observability for task execution and scheduling? Or are we happy having metrics for the target executor/scheduler rather than the annotated methods?

**Comment by bclozel** [comment]
Indeed it's been superseded by #29883. Thanks!
