### ISSUE TITLE
HandlerMethodReturnValueHandlerComposite doesn't cache resolved return types although the javadoc claims it does [SPR-15594]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20153]
**[Lari Hotari](https://jira.spring.io/secure/ViewProfile.jspa?name=lhotari)** opened **[SPR-15594](https://jira.spring.io/browse/SPR-15594?redirect=false)** and commented

The javadoc of HandlerMethodReturnValueHandlerComposite contains this sentence:
["Previously resolved return types are cached for faster lookups."](https://github.com/spring-projects/spring-framework/blob/76b28a0cece1049fe5317cd76dfc774437f0d6b6/spring-web/src/main/java/org/springframework/web/method/support/HandlerMethodReturnValueHandlerComposite.java#L32)
However, the implementation of `HandlerMethodReturnValueHandlerComposite` doesn't contain a cache.

There is a cache in [HandlerMethodArgumentResolverComposite](https://github.com/spring-projects/spring-framework/blob/76b28a0cece1049fe5317cd76dfc774437f0d6b6/spring-web/src/main/java/org/springframework/web/method/support/HandlerMethodArgumentResolverComposite.java#L47) and perhaps something similar if missing from `HandlerMethodReturnValueHandlerComposite` .

The reason I'm filing this issue is that I'm optimizing performance of a legacy Spring MVC 3.2.x application. While load testing this application, I can see a large number of `java.lang.NoSuchMethodException` s being created. This is the stack trace of such exceptions:

```
java.lang.NoSuchMethodException.<init>(String)
    java.lang.Class.getDeclaredMethod(String, Class[])
    org.springframework.core.annotation.AnnotationUtils.findAnnotation(Method, Class)
    org.springframework.web.method.HandlerMethod.getMethodAnnotation(Class)
    org.springframework.web.method.HandlerMethod$HandlerMethodParameter.getMethodAnnotation(Class)
    org.springframework.web.method.annotation.ModelAttributeMethodProcessor.supportsReturnType(MethodParameter)
    org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.getReturnValueHandler(MethodParameter)
    org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(Object, MethodParameter, ModelAndViewContainer, NativeWebRequest)
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletWebRequest, ModelAndViewContainer, Object[])
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(HttpServletRequest, HttpServletResponse, HandlerMethod)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(HttpServletRequest, HttpServletResponse, HandlerMethod)
    org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(HttpServletRequest, HttpServletResponse, Object)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(HttpServletRequest, HttpServletResponse)
```

It seems that `AnnotationUtils.findAnnotation` has been optimized in more recent Spring versions and that's why I'm seeing this performance bottleneck in a Spring 3.2.x application.

---

**Affects:** 3.2.18, 4.2.9, 4.3.8

**Comment by DeCaMil** [comment]
Observations:
The `HandlerMethodReturnValueHandlerComposite` needs to consider whether the result is async. This can cause up to 2 passes through the `returnValueHandlers`. First via `isAsyncReturnValue`, to determine if the result is async. Now, if there are no async handlers, this will cause it to traverse the entire list. Then the list is traversed again via `selectHandler` to determine if a handler supports the return type.

For non-async results, they could be cached by return type. However, for async results this is harder. For an async result, the return type is a future or promise and it becomes necessary to examine the what type actually returns. It might be possible with a cache for whether a return type is immediate or deferred, then individual caches for the immediate and deferred types.

**Comment by rstoyanchev** [comment]
Old issue, but caching on the return value is not missing. It was originally present and later removed in #13856 because declared return parameters can be more general than the actual return value, which can in turn result in different handlers for the same method.
