### ISSUE TITLE
Consider improvements to handling suffixed URL patterns [SPR-15618]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20177]
**[Andy Clement](https://jira.spring.io/secure/ViewProfile.jspa?name=aclement)** opened **[SPR-15618](https://jira.spring.io/browse/SPR-15618?redirect=false)** and commented

See the discussion in #19112 and #20156. It feels like suffixes are a common thing
(patterns ending '.*', '.txt', '.html') and it could be worth special handling for them. Possibly
a new PathElement subtype specifically for suffixed PathElements (because currently `"{foo}.*"`) type patterns are captured as RegexPathElement instances (the least optimal of the PathElement subtypes).

Under #20156 a temporary fix was made to avoid treating '.*' as usage of a wildcard in the PathPattern comparator which feels wrong to some degree (because there is a wildcard there!) but it is what the AntPathMatcher comparator does (See PatternInfo#initCounters()) so it was done to make them consistent.

---

No further details from [SPR-15618](https://jira.spring.io/browse/SPR-15618?redirect=false)

**Comment by rstoyanchev** [comment]
Suffix patterns are already deprecated in Spring MVC and will be turned off by default in 5.3, eventually to be removed. We don't really want to add them here.
