### ISSUE TITLE
Consider using different ByteBuffers when reading the request body in Undertow integration [SPR-15615]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20174]
**[Violeta Georgieva](https://jira.spring.io/secure/ViewProfile.jspa?name=violetagg)** opened **[SPR-15615](https://jira.spring.io/browse/SPR-15615?redirect=false)** and commented

Hi,

The integration with Undertow is made in a way that when reading the request body the implementation uses the pooled ByteBuffer provided by Undertow:
https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/server/reactive/UndertowServerHttpRequest.java#L148

"PooledByteBuffer#getBuffer" returns always one and the same ByteBuffer. In some use case it might appear that more than one read will be performed. If the subscriber does not consume the ByteBuffer with the request body immediately when it is provided then the next read will override the data.

My proposal is to change the integration in a way that it is guaranteed that different ByteBuffers are returned as a result of request body reading.

What do you think?

Regards,
Violeta

---

**Affects:** 5.0 RC1

**Comment by poutsma** [comment]
I don't believe this issue is valid anymore, as we now do deallocate undertow buffers properly now (see https://github.com/spring-projects/spring-framework/blob/72dddfbc7be0e6aff25b710e62d8bb7101e78aab/spring-web/src/main/java/org/springframework/http/server/reactive/UndertowServerHttpRequest.java#L210)
