### ISSUE TITLE
EhCache: Ability to use CacheManager.newInstance for CacheManager creation [SPR-15619]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20178]
**[Hurelhuyag](https://jira.spring.io/secure/ViewProfile.jspa?name=hurelhuyag)** opened **[SPR-15619](https://jira.spring.io/browse/SPR-15619?redirect=false)** and commented

If I use **CacheManager.newInstance** instead of **new CacheManager** I can share same cacheManager for spring method cache and hibernate cache.

Something like this.

```java
if (this.acceptExisting) {
			// EhCache 2.5+: Reusing an existing CacheManager of the same name.
			// Basically the same code as in CacheManager.getInstance(String),
			// just storing whether we're dealing with an existing instance.
			synchronized (CacheManager.class) {
				this.cacheManager = CacheManager.getCacheManager(this.cacheManagerName);
				if (this.cacheManager == null) {
					this.cacheManager = CacheManager.newInstance(configuration);
				}
				else {
					this.locallyManaged = false;
				}
			}
		}
```

---

**Affects:** 4.3.7

**Issue Links:**
- #20180 Use ehcache.xml configuration defined name for CacheManager lookup.

**Comment by snicoll** [comment]
Sorry for overlooking this. In the meantime our support for EhCache [has been removed from the core framework](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#caching).
