### ISSUE TITLE
Use ehcache.xml configuration defined name for CacheManager lookup. [SPR-15621]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20180]
**[Hurelhuyag](https://jira.spring.io/secure/ViewProfile.jspa?name=hurelhuyag)** opened **[SPR-15621](https://jira.spring.io/browse/SPR-15621?redirect=false)** and commented

ehcache.xml can have name property for cacheManager instance name. EhCacheManagerFactoryBean is not using this property.

---

**Issue Links:**
- #20178 EhCache: Ability to use CacheManager.newInstance for CacheManager creation

**Comment by snicoll** [comment]
Sorry for overlooking this. In the meantime our support for EhCache [has been removed from the core framework](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#caching).
