### ISSUE TITLE
Provide insight of singleton instance [SPR-15625]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20184]
**[Rocky Shang](https://jira.spring.io/secure/ViewProfile.jspa?name=rocky)** opened **[SPR-15625](https://jira.spring.io/browse/SPR-15625?redirect=false)** and commented

spring-bean exposes beans information through LiveBeansView. But there is no such info for instance level.

Since fields can be inject or not if they are annotated by (`@autowired` required=false)
At runtime, we should know whether all fields are inject as the behavior may be different for that instance.

---

**Affects:** 4.3.8

**Comment by sbrannen** [comment]
Closing since `LiveBeansView` is now deprecated (see #25820).
