### ISSUE TITLE
Remote Invocation - Add attributes support to remote invocation result [SPR-15633]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20192]
**[Tomer Arbel](https://jira.spring.io/secure/ViewProfile.jspa?name=tomerarbel)** opened **[SPR-15633](https://jira.spring.io/browse/SPR-15633?redirect=false)** and commented

Spring's remote invocation infrastructure allows adding serializable attributes on a remote request in `org.springframework.remoting.support.RemoteInvocation`.
As the javadoc explains:

> This is very useful for adding additional invocation data without having to subclass `RemoteInvocation`. (RemoteInvocation#addAttribute(...))

While this is supported on the remote request side, the response side does not support that.
Meaning, if there is a need to add data to the remote response, `org.springframework.remoting.support.RemoteInvocationResult` must be subclassed to contain the extra data.

I suggest adding attributes support to `org.springframework.remoting.support.RemoteInvocationResult` to match the capabilities of  `org.springframework.remoting.support.RemoteInvocation`.

---

1 votes, 2 watchers

**Comment by rstoyanchev** [comment]
Closing since remoting support has been dropped for 6.0 in #27422.
