### ISSUE TITLE
RequestContextHolder for Reactive Web [SPR-15680]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20239]
**[Doron Gold](https://jira.spring.io/secure/ViewProfile.jspa?name=dorongold)** opened **[SPR-15680](https://jira.spring.io/browse/SPR-15680?redirect=false)** and commented

It is necessary to have a way to associate attributes with the current request and be able to fetch these attributes during the request lifetime.

The ability to set and get such attributes is essential for use-cases such as:
* Having a unique trace-id per request, which can be included in all log messages.
* Identifying the currently logged in user (the user associated with the request).
* In a micro-service architecture: receiving contextual data via request headers, then when calling other micro-services, pass the same contextual data that came with the original request.

In webmvc this is possible by calling a static methods on `org.springframework.web.context.request.RequestContextHolder`. A developer could implement HandlerInterceptor which intercepts all incoming requests and sets contextual attributes on RequestContextHolder. These attributes are then accessible from anywhere in the code (via a static method) during the request lifetime.

Since in Reactive Web a request is not bound to a single processing thread, a simple use of ThreadLocal (what RequestContextHolder does) is not enough.
The Spring framework should offer a more sophisticated solution.

A simple but extremely intrusive workaround would be to pass in ServerWebExchange to all methods in all components - starting from controller endpoints down to all services.
But even if this is done, there is no good way to have a logger take attributes form the request (for the purpose of including trace/correlation ID) without implementing a wrapper around the logger class that receives an extra parameter.

---

**Reference URL:** https://stackoverflow.com/questions/43975761/how-to-get-the-context-of-the-current-request-in-spring-webflux

**Issue Links:**
- #21746 Create a WebFilter for ServerWebExchange Reactor Context
- #20108 Upgrade to Reactor 3.1 RC1 (including Reactive Streams 1.0.1)

19 votes, 34 watchers

**Comment by archie-swif** [comment]
There is a working solution to put data from reactor context to mdc using hooks by @ivansenic https://www.novatec-gmbh.de/en/blog/how-can-the-mdc-context-be-used-in-the-reactive-spring-applications

And a java version for this solution: https://github.com/archie-swif/webflux-mdc/tree/master/src/main/java/com/example/webfluxmdc

**Comment by ivansenic** [comment]
> There is a working solution to put data from reactor context to mdc using hooks by @ivansenic https://www.novatec-gmbh.de/en/blog/how-can-the-mdc-context-be-used-in-the-reactive-spring-applications

We recognized that the solution above has a problem that a context is not correctly propagated in case of Exceptions in the reactive sequence. Just as a note.

**Comment by torstenwerner** [comment]
> We recognized that the solution above has a problem that a context is not correctly propagated in case of exceptions in the reactive sequence.

@ivansenic could you please elaborate on this problem or point us to a more correct solution?

**Comment by ivansenic** [comment]
> @ivansenic could you please elaborate on this problem or point us to a more correct solution?

I think the best guy to explain this is @carlosbarragan as he was the one to point the problem to me after I wrote my blog. He might have additional solutions as well. 

@carlosbarragan Carlos can you elaborate, please?

**Comment by archie-swif** [comment]
@torstenwerner @ivansenic @carlosbarragan I have tested few common error scenarios, with or w/o error handling. It seems to be working fine in [this sample](https://github.com/archie-swif/webflux-mdc/blob/feature/exceptions/src/main/java/com/example/webfluxmdc/WebfluxContextMdcApplication.java)

Do you recall by chance what was the faulty case? Thank you!

**Comment by carlosbarragan** [comment]
@archie-swif If I recall correctly, the problem with this approach arises when an error occurs immediately in a call.

```kotlin
mono.map{}
   .flatMap{}
  .onErrorMap{} // if an error occurs before one of the maps operations are called, the context is not copied
```

**Comment by carlosbarragan** [comment]
@archie-swif  I think a possible solution would be to try to copy the context on `MdcContextLifter.onError()` I haven't tried myself, but that could probably work

FYI: @ivansenic

**Comment by ivansenic** [comment]
@archie-swif 

I also tested this a bit and @carlosbarragan was correct. The `Mono.onErrorResume()` is not copying the MDC context correctly. And yes, to overcome this you should also copy the context to MDC on `MdcContextLifter.onError()`.

**Comment by archie-swif** [comment]
Thank you @ivansenic !

**Comment by scottjohnson** [comment]
👍 to @ivansenic's approach (gratitude to you and @archie-swif as well). We used this in conjunction with a `WebFilter` to copy request context information (conserved headers, correlation ids, etc) in to the `Context` like so:

```
public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        return chain.filter(exchange)
                .subscriberContext((context) -> {
		    context = context.put("foo", "bar")                   
                    return context;
                });
}
```

Looks promising so far.

**Comment by carlosbarragan** [comment]
@scottjohnson @archie-swif please be aware that the context should remain as small as possible. Instead of adding a new key-value entry, you should simply add a new key that references a map. That is what is recommended in the JavaDocs of the Context.

So you need to do something like this:

```java
.subscriberContext((context) -> {
                   Map<String, String> map = new HashMap();
                    map.put("foo","bar");
		    context = context.put("myContextKey",map)                   
                    return context;
                });
```

**Comment by membersound** [comment]
Could this be an option to retrain the MDC context?
```
.subscriberContext((context) -> {
		    context = context.put("mdc", MDC.getCopyOfContextMap())                   
                    return context;
                });
```

**Comment by SudBisht** [comment]
> 👍 to @ivansenic's approach (gratitude to you and @archie-swif as well). We used this in conjunction with a `WebFilter` to copy request context information (conserved headers, correlation ids, etc) in to the `Context` like so:
> 
> ```
> public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
>         return chain.filter(exchange)
>                 .subscriberContext((context) -> {
> 		    context = context.put("foo", "bar")                   
>                     return context;
>                 });
> }
> ```
> 
> Looks promising so far.

Can you share some example, I am trying to access context value in some services class but getting Empty context

```Mono.subscriberContext().flatMap(c -> {
					c.getOrDefault("version", "1");
					return c.get("version");
				}).subscribe();```

**Comment by VladimirRybalko** [comment]
@SudBisht I guess, it's impossible to do outside of WebFlux controllers.
@ivansenic and @archie-swif do you know how to use it outside of controllers.
At the first glance, it looks very ugly solution to pass a map everywhere from controller to low level abstractions.

**Comment by carlosbarragan** [comment]
@SudBisht you have to be sure that you are retrieving the `Context` from the same stream. Where are you calling `Mono.subscriberContext()` and, more important, where are you _creating_ the context?

**Comment by navjinderkaur** [comment]
@SudBisht Did you get a way out for this one ? I'm stuck with the same issue. 
@carlosbarragan When you say that we should be retrieving the `Context` from the same stream, do you mean we should be populating the `Context` and fetching it in a service in the same reactive chain ?

**Comment by rstoyanchev** [comment]
Thanks everyone. The original request here has been fulfilled through a combination of the [Reactor Context API](https://projectreactor.io/docs/core/release/reference/#context) and the `ServerWebExchangeContextFilter` from #21746 that makes `ServerWebExchange` available in all parts of the reactive execution chain.

In regards to logging with MDC, please check this [earlier comment](https://github.com/spring-projects/spring-framework/issues/20239#issuecomment-453457018) and the linked blog post from a member of the Reactor team. I've also created https://github.com/reactor/reactor-core/issues/1985 to for Reactor to provide official guidance. If you have further comments on the topic, please comment there.

**Comment by ankitp-kr** [comment]
We have implemented the java code for MdcContextLifter and we are logging a context called correlationId which is being sent in the header of a particular api request.
But also for other simultaneous api calls with no correlationId header, the same correlationId gets logged.
For ex: When we hit GET /offers endpoint with header correlationId abc’ , if there are simultaneous api calls for GET /metrics endpoint without any header correlationId, we get the same correlationId ‘abc’ for /metrics calls also.
How can we get rid of this issue?

**Comment by ankitp-kr** [comment]
In continuation to my first comment-
Also we are using the HttpWebHandlerAdapter debug logs(one for api path, other for success/error code) as inbound logs for our service, but we are getting the context for only 1 of the 2 HttpWebHandlerAdapter logs. Does anyone know how do I ensure that both the logs get the context?

**Comment by ivansenic** [comment]
@ankitp-kr The code you went for was written a long time ago, I am not sure if there were any changes in the reactor api and impl since then.. You should check first the official MDC guide as stated in the repo: https://projectreactor.io/docs/core/release/reference/#faq.mdc. You can also add logging statements in each subscriber method to print the current context, I guess there is some cleanup missing..

**Comment by alejandroarevalo** [comment]
> @torstenwerner @ivansenic @carlosbarragan @archie-swif
> We have followed https://github.com/archie-swif/webflux-mdc/tree/master/src/main/java/com/example/webfluxmdc and we are logging a context called correlationId which is being sent in the header of a particular api request.
> But also for other simultaneous api calls with no correlationId header, the same correlationId gets logged.
> For ex: When we hit GET /offers endpoint with header correlationId 'abc’ , if there are simultaneous api calls for GET /metrics endpoint without any header correlationId, we get the same correlationId ‘abc’ for /metrics calls also.
> How can we get rid of this issue?

Hi @ankitp-kr ,

I'm also trying to use `MdcContextLifter` proposed by @archie-swif , since unfortunately the approach recommended in https://projectreactor.io/docs/core/release/reference/#faq.mdc is not sufficient for my use case ( I need to produce some logging that come from internal libraries invoked within each operator, and I would like to have this libraries log the MDC variables as well)

So I've opted for a similar approach as the one @archie-swif used, but using a closeable MDC for adding my correlationId, could you maybe try this to see if you get rid of the problem in where simultaneous invocations, one with correlation ID and one without it, would print same value?

```
class MdcContextLifter<T> implements CoreSubscriber<T> {

    CoreSubscriber<T> coreSubscriber;

    public MdcContextLifter(CoreSubscriber<T> coreSubscriber) {
        this.coreSubscriber = coreSubscriber;
    }

    @Override
    public void onSubscribe(Subscription subscription) {
        coreSubscriber.onSubscribe(subscription);
    }

    @Override
    public void onNext(T obj) {
        injectMdc(() -> coreSubscriber.onNext(obj));
    }

    @Override
    public void onError(Throwable t) {
        injectMdc(() -> coreSubscriber.onError(t));
    }

    @Override
    public void onComplete() {
        injectMdc(() -> coreSubscriber.onComplete());
    }

    @Override
    public Context currentContext() {
        return coreSubscriber.currentContext();
    }

    /**
     * Adding correlationId in MDC as closeable statement.
     * @param task
     */
    private void injectMdc(Runnable task) {
        final Object mdcVal = coreSubscriber.currentContext().getOrDefault("correlationId", null);
        if(mdcVal != null ) {
            try(MDC.MDCCloseable ignored = MDC.putCloseable("correlationId", mdcVal.toString())) {
                task.run();
            }
        } else {
            task.run();
        }
    }
}
```

**Comment by HarinderDang-cnic** [comment]
> > @torstenwerner @ivansenic @carlosbarragan @archie-swif
> > We have followed https://github.com/archie-swif/webflux-mdc/tree/master/src/main/java/com/example/webfluxmdc and we are logging a context called correlationId which is being sent in the header of a particular api request.
> > But also for other simultaneous api calls with no correlationId header, the same correlationId gets logged.
> > For ex: When we hit GET /offers endpoint with header correlationId 'abc’ , if there are simultaneous api calls for GET /metrics endpoint without any header correlationId, we get the same correlationId ‘abc’ for /metrics calls also.
> > How can we get rid of this issue?
> 
> Hi @ankitp-kr ,
> 
> I'm also trying to use `MdcContextLifter` proposed by @archie-swif , since unfortunately the approach recommended in https://projectreactor.io/docs/core/release/reference/#faq.mdc is not sufficient for my use case ( I need to produce some logging that come from internal libraries invoked within each operator, and I would like to have this libraries log the MDC variables as well)
> 
> So I've opted for a similar approach as the one @archie-swif used, but using a closeable MDC for adding my correlationId, could you maybe try this to see if you get rid of the problem in where simultaneous invocations, one with correlation ID and one without it, would print same value?
> 
> ```
> class MdcContextLifter<T> implements CoreSubscriber<T> {
> 
>     CoreSubscriber<T> coreSubscriber;
> 
>     public MdcContextLifter(CoreSubscriber<T> coreSubscriber) {
>         this.coreSubscriber = coreSubscriber;
>     }
> 
>     @Override
>     public void onSubscribe(Subscription subscription) {
>         coreSubscriber.onSubscribe(subscription);
>     }
> 
>     @Override
>     public void onNext(T obj) {
>         injectMdc(() -> coreSubscriber.onNext(obj));
>     }
> 
>     @Override
>     public void onError(Throwable t) {
>         injectMdc(() -> coreSubscriber.onError(t));
>     }
> 
>     @Override
>     public void onComplete() {
>         injectMdc(() -> coreSubscriber.onComplete());
>     }
> 
>     @Override
>     public Context currentContext() {
>         return coreSubscriber.currentContext();
>     }
> 
>     /**
>      * Adding correlationId in MDC as closeable statement.
>      * @param task
>      */
>     private void injectMdc(Runnable task) {
>         final Object mdcVal = coreSubscriber.currentContext().getOrDefault("correlationId", null);
>         if(mdcVal != null ) {
>             try(MDC.MDCCloseable ignored = MDC.putCloseable("correlationId", mdcVal.toString())) {
>                 task.run();
>             }
>         } else {
>             task.run();
>         }
>     }
> }
> ```

The server does not start with this change, how stupid is this going to get ?

**Comment by HarinderDang-cnic** [comment]
Sorry, its starting now , must be something in my environment. 
Can some one please share 'when' the MDC gets cleared before the processing of the next request in the solution proposed by @archie-swif
