### ISSUE TITLE
Classpath Resource URL handling still wrong with Tomcat 8.5.12 [SPR-15681]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20240]
**[Moritz Kleine](https://jira.spring.io/secure/ViewProfile.jspa?name=mor7tz)** opened **[SPR-15681](https://jira.spring.io/browse/SPR-15681?redirect=false)** and commented

When building WAR files with resources residing in `/WEB-INF/classes` the following exception is raised when starting the webapp in tomcat 8.5.12:

```
org.springframework.beans.factory.BeanDefinitionStoreException: I/O failure during classpath scanning; nested exception is java.io.FileNotFoundException: file:/opt/apache-tomcat-8.5.12/webapps/test.war$/WEB-INF/classes/com/acme/test (No such file or directory)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:323) ~[sp
ring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:272) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEAS
E]
...
```

The very same setup used to work fine before https://bz.apache.org/bugzilla/show_bug.cgi?id=60728 and https://github.com/spring-projects/spring-boot/issues/7949. At least we're using this packaging successfully with tomcat 7.0.x,  <= 8.0.36 and websphere.

Known workarounds: Unpack webapp. Move resources to separate jar so that they are read from `/WEB-INF/lib/test.jar` instead of `/WEB-INF/classes`.

---

**Affects:** 4.3.9

**Attachments:**
- [SPR-15681.zip](https://jira.spring.io/secure/attachment/25028/SPR-15681.zip) (_7.29 kB_)
- [SPR-15681.zip](https://jira.spring.io/secure/attachment/25027/SPR-15681.zip) (_3.08 kB_)

**Issue Links:**
- #20115 ResourceUtils.extractArchiveURL fails to work under Tomcat 8.0.41 with unpackWARs=false

**Comment by wagnerluis1982** [comment]
Hi. A little question. Is this issue still relevant?

**Comment by bclozel** [comment]
Closing this issue as outdated.
