### ISSUE TITLE
Consider marking ConditionContext.getBeanFactory() @Nullable rather than asserting a non-null bean factory [SPR-15698]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20257]
**[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson)** opened **[SPR-15698](https://jira.spring.io/browse/SPR-15698?redirect=false)** and commented

It seems rather odd to allow the condition context to be created with a null registry, or one from which a bean factory cannot be obtained, and yet throw an exception from getBeanFactory() when it's null. I think `@Nullable` on getBeanFactory() might be better there.

---

**Affects:** 5.0 RC2

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/9584

1 votes, 3 watchers

**Comment by snicoll** [comment]
Duplicate #21405
