### ISSUE TITLE
Enable support for custom vnd types in messaging MappingJackson2MessageConverter [SPR-15712]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20269]
**[Vinicius Carvalho](https://jira.spring.io/secure/ViewProfile.jspa?name=vcarvalho)** opened **[SPR-15712](https://jira.spring.io/browse/SPR-15712?redirect=false)** and commented

The current implementation of converters will not allow conversion of vnd types such as application/vnd.springframework.type+json, although one could set the custom types beforehand, it is useful at least on Spring Cloud Stream use cases that we could support any type that has +json on the payload.

using subtypes from MimeType would not work as json and vnd... will be consider different types.

Spring AMQP takes a different approach using just a simple contains for the word json on the content type.

It would be nice to have some sort of support on this core component and avoid another snowflake implementation on Spring Cloud Stream to override the default behavior.

---

**Affects:** 4.3.9

**Comment by rstoyanchev** [comment]
We can add `"application/*+json"` as a supported MIME type, just like in the same converter for HTTP.
