### ISSUE TITLE
Simplify ReflectionUtils.getUniqueDeclaredMethods(…) [SPR-15741]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20297]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[SPR-15741](https://jira.spring.io/browse/SPR-15741?redirect=false)** and commented

`ReflectionUtils.getUniqueDeclaredMethods(…)` seems to check for covariant return types although it doesn't need to as `doWithMethods(…)` by definition traverses the type hierarchy bottom up.

---

**Affects:** 4.3.9, 5.0 RC2

**Comment by bclozel** [comment]
Sorry it took us so long to consider this issue.
We can't remove this covariant check as it's required to CGLIB-generated classes, see `ReflectionUtilsIntegrationTests`.
