### ISSUE TITLE
RequestMapping annotation to support regular expressions in header value. [SPR-15765]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20320]
**[Neto Fontes](https://jira.spring.io/secure/ViewProfile.jspa?name=netofontes)** opened **[SPR-15765](https://jira.spring.io/browse/SPR-15765?redirect=false)** and commented

Spring MVC already supports exact match binding for header name & value defined in `@RequestMapping`.

This improvement would additionally allow to map a request by defining a matching regular expression for the value field so that we wouldn’t need to create additional handler methods to map all variation of the possible header values.

E.g: For a given REST API that takes the header `X-Override` with possible values `true` or `false` which are case-insensitive we would need to have one `@RequestMapping` per each possible way to write `true`: `true`, `True`, `TRUE`, `tRue`, and on…

Instead we could have a regular expression in the header value which matches `true` in all possible ways to write it.

Proposal of usage:

```java
@RequestMapping(
        method = RequestMethod.PATCH,
        headers = "X-Override?=^(?i)(true)$"
)
public ResponseEntity overridingOperation( ... ) { ... }

@RequestMapping(
        method = RequestMethod.PATCH,
        headers = "X-Override?=^(?i)(false)$"
)
public ResponseEntity nonOverridingOperation( ... ) { ... }

@RequestMapping(
        method = RequestMethod.GET,
        headers = "X-Priority?=^(?i)(high|medium|low)$"
)
public ResponseEntity processRequest( ... ) { ... }
```

The `?=` would indicate that the following sequence is a regular expression.

---

1 votes, 2 watchers

**Comment by bclozel** [comment]
It seems that, given the current web programming model, it's not clear whether we should support that as a mapping feature or as a request binding feature with validation. This can be argued both ways and is hard to include by default as a result.

Given the lack of demand and clarity for this, we're closing this issue for now.
