### ISSUE TITLE
Beans defined by XML are skipped in @Configuration override [SPR-15805]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20360]
**[David Lopez](https://jira.spring.io/secure/ViewProfile.jspa?name=antdavidl)** opened **[SPR-15805](https://jira.spring.io/browse/SPR-15805?redirect=false)** and commented

When you define a bean in a XML, you cannot redefine it in a `@Component` or `@TestComponent` class using a `@Bean` declaration). It can, however, be redefined using another XML.

I have defined this as a Improvement since I do not think it explicitly violates anything .. simply it is a grey zone in the DI part fo Spring, but anyway, I consider this behaviour inconsistent and weird.

This issue is similar to #14201, but to the case when

---

**Affects:** 4.3.9, 5.0 RC2

**Attachments:**
- [XmlOverrideBug.zip](https://jira.spring.io/secure/attachment/25055/XmlOverrideBug.zip) (_5.35 kB_)

**Issue Links:**
- #14201 Beans defined by `@ComponentScan` are skipped in `@Configuration` override

1 votes, 1 watchers

**Comment by snicoll** [comment]
Thanks for the sample, I did upgrade it to a recent version and can reproduce the behavior. XML bean definitions can't be overridden by java config bean in the sense that these are "top-level" and `@Bean` methods aren't (only the `@Configuration` class is). 

In general, we feel that bean overriding shouldn't be used at all. This triggers the discussion of deprecating the feature altogether, see #31288
