### ISSUE TITLE
Advice is not called in some cases with Spring AOP [SPR-15809]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20364]
**[Yan Tuizhi](https://jira.spring.io/secure/ViewProfile.jspa?name=yantuizhi)** opened **[SPR-15809](https://jira.spring.io/browse/SPR-15809?redirect=false)** and commented

I have made the following test application with spring boot 1.5.3:

```java
@SpringBootApplication
public class TestApplication {
	public static void main(String[] args) {
		ApplicationContext context = SpringApplication.run(TestApplication.class);
		context.getBean(ClassA.class).init();
	}
}
```

```java
@Component
public class ClassA {
    private ApplicationContext context;

    @Autowired
    public void setContext(ApplicationContext context) {
        this.context = context;
    }

    public void init() {
        System.out.println("Test 1 (Works):");
        context.getBean(ClassB.class);

        System.out.println("Test 2 (Not Working):");
        context.getBean(ClassB.class, this);

        System.out.println("Test 3 (Not Working):");
        new ClassB(this);
    }

    @TestAnnotation
    public void annotatedMethod() { }
}
```

```java
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class ClassB {
    private ClassA classA;

    @Autowired
    public ClassB(ClassA classA) {
        classA.annotatedMethod();
    }
}
```

with the following annotation and aspect:

```java
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface TestAnnotation {
}
```

```java
@Aspect
@Component
public class TestAnnotationAspect {
    private static final Logger log = LoggerFactory.getLogger(TestAnnotation.class);

    @Before("@annotation(test.sscce.aspect.TestAnnotation)")
    public void log(JoinPoint joinPoint) {
        System.out.println("OK");
    }
}
```

The advice for the test annotation is called only in the first case (printing "OK"), in the other two cases not. Why does it only work in the first case? Shouldn't "this" already refer to the proxied instance? It would be a much more consistent design, if all three cases would work.  At least for the second case I would expect that it just works  like the first case, as here it is possible to intercept and replace "this" with the proxied instance. Please correct me, if am wrong.

Thank you very much for your efforts.

---
No further details from [SPR-15809](https://jira.spring.io/browse/SPR-15809?redirect=false)

**Comment by snicoll** [comment]
Indeed, the two last calls provides the raw instance, not the one that has been decorated so that's the expected behavior.
