### ISSUE TITLE
jaxws:client no more resolves the ${property placeholder} references [SPR-15827]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20382]
**[Manish](https://jira.spring.io/secure/ViewProfile.jspa?name=manishsingh11@hotmail.com)** opened **[SPR-15827](https://jira.spring.io/browse/SPR-15827?redirect=false)** and commented

This works with CXF 3.1.10 and Spring 4.1.6 but does not when I upgrade spring to 4.3.7
I also tried upgrading to Spring 4.3.10 but that does not help either.

I load the properties file as
<context:property-placeholder location="file:${prop.location:.}/${app.id}.properties , file:${prop.location:.}/${app.id}-secure.properties"
system-properties-mode="OVERRIDE"
ignore-unresolvable="true"
ignore-resource-not-found="true"
order="1"/>

above referenced file contains
session.manager.service.uri=http://some.com/url

and I need to use that property in below jaxws:client section

<jaxws:client id="sessionManagerServiceClient"
serviceClass="com.my.ws.stubs.session.SessionManagerService"
address="${session.manager.service.uri:http://enter.valid.session.manager.service.uri/}" />

BUT it never resolves the address and throws an error:
Could not find conduit initiator for address: ${session.manager.service.uri:http://enter.valid.session.manager.service.uri/} and transport:

---

**Affects:** 4.3.7, 4.3.10

1 votes, 3 watchers

**Comment by akuma8** [comment]
I have the same issue with Spring 4.3.18.RELEASE, where property defined here:
```
<jaxws:client id="ClientOne"
		serviceClass="com.app.soap.Service"
		address="${client.one.address}">   <!--This is not resolved --> 
	   <jaxws:handlers>
		   <ref bean="loggingSoapClientHandler"/>
	   </jaxws:handlers>
 </jaxws:client>
```
My workaround was to define a bean containing all addresses and use it with SpEL.
```
<jaxws:client id="ClientOne"
		serviceClass="com.app.soap.Service"
		address="#{jaxWsAdresses.clientOneAddress}">   
	   <jaxws:handlers>
		   <ref bean="loggingSoapClientHandler"/>
	   </jaxws:handlers>
 </jaxws:client>
```

**Comment by snicoll** [comment]
I am going to close this as the resolution happens outside of the core framework and we've provided some pointers already. I'd suggest to report that against CXF if that's still applicable. Alternatively, if we get a small sample that we can run ourselves to reproduce the problem we can have another go at it.
