### ISSUE TITLE
BeanCurrentlyInCreationException depending on order of bean creation [SPR-15843]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20398]
**[Thomas Vahrst](https://jira.spring.io/secure/ViewProfile.jspa?name=t.vahrst)** opened **[SPR-15843](https://jira.spring.io/browse/SPR-15843?redirect=false)** and commented

We experienced a `BeanCurrentlyInCreationException` in a Spring-Boot application when we introduced a BeanPostProcessor to wrap the current datasource. The problem was, that this exception occured randomly, so we tried to debug and reduce the problem. In the end we build a simple Spring testcase to demonstrate, that the order of `@Bean` definitions in a `@Configuration` class leads to different behavior, one time passing, one time failing with a `BeanCurrentlyInCreationException`.

Failing:

```java
	@Bean
	@DependsOn("datasource")  
	public TxManager txmanager(){
		return new TxManager();
	}

	@Bean
	public Datasource datasource(){
		return new Datasource();
	}

... so more beans...
```

Passing:

```java

	@Bean
	public Datasource datasource(){
		return new Datasource();
	}

	@Bean
	@DependsOn("datasource")  
	public TxManager txmanager(){
		return new TxManager();
	}

... some more beans
```

I put the complete testcase in github: https://github.com/tvahrst/spring_dependson_problem
In the original spring-boot application, it was not the order of `@Bean` methods in the `@Configuration`, but different `@Autowird` fields, which led to different order of bean creation.

It seems, that this 'flaky' behavior is due to the fact, that some 'dependsOn' metainformation for beans are analyzed during bean **creation**. The `dependenciesForBeanMap` in DefaultSingletonRegistry is filled during `preInstantiateSingletons`.

---

**Affects:** 4.3.10

**Comment by sbrannen** [comment]
Thanks for the feedback, @tvahrst.

We'll close this issue as a result.
