### ISSUE TITLE
[support] capacity extend when the bean just been autowired [SPR-15886]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20441]
**[zhangzhijia](https://jira.spring.io/secure/ViewProfile.jspa?name=jiahut)** opened **[SPR-15886](https://jira.spring.io/browse/SPR-15886?redirect=false)** and commented

we konw  spring can do something when the bean been created ,eg  implement InitializingBean

could we do something  when the bean had been autowired, export some hook which we can extend before  the bean used .

---
No further details from [SPR-15886](https://jira.spring.io/browse/SPR-15886?redirect=false)

**Comment by snicoll** [comment]
`BeanFactoryPostProcessor` allows you to control what happens before and after initialization, with a specialized usage with `InstantiationAwareBeanPostProcessor`. A bean could be autowired in many places so I don't think a callback for that is possible without being confusing. Thanks anyway for the suggestion.
