### ISSUE TITLE
List available media types for 406 Not Accepted response [SPR-15899]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20453]
**[Yi EungJun](https://jira.spring.io/secure/ViewProfile.jspa?name=eungjun.yi)** opened **[SPR-15899](https://jira.spring.io/browse/SPR-15899?redirect=false)** and commented

It would be helpful if the payload of 406 Not Accepted response contains a list of available media types so that client choose one of them, as outlined in RFC 7231.

> The server SHOULD generate a payload containing a list of available
> representation characteristics and corresponding resource identifiers
> from which the user or user agent can choose the one most
> appropriate.  A user agent MAY automatically select the most
> appropriate choice from that list.  However, this specification does
> not define any standard for such automatic selection, as described in
> Section 6.4.1.
> 
> https://tools.ietf.org/html/rfc7231#page-59

---
No further details from [SPR-15899](https://jira.spring.io/browse/SPR-15899?redirect=false)

**Comment by rstoyanchev** [comment]
Spring MVC does not send error details in the response. It's left to applications to determine how to format error responses, see [the docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-rest-exceptions). If you override the handling of `HttpMediaTypeNotAcceptableException` you can access the list of media types from it.

**Comment by izeye** [comment]
This looks meant to be closed.

**Comment by snicoll** [comment]
Indeed, thanks!
