### ISSUE TITLE
Autowiring a collection of beans thats optional should initialize an empty collection [SPR-15897]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20451]
**[Christoph Ellinger](https://jira.spring.io/secure/ViewProfile.jspa?name=christophellinger)** opened **[SPR-15897](https://jira.spring.io/browse/SPR-15897?redirect=false)** and commented

I can autowire a list of beans like this:

`@Autowired`(required = false)
List\<MyOptionalBeans> optionalBeanList;

If really no bean was supplied, optionalBeanList is now null. When I want to use this in my program later I have to include null checks.

I think it would be better to initialize an empty list.

---

**Affects:** 4.2.9

**Comment by snicoll** [comment]
I don't think so. The explicit flag of making it non required allows you to initialze the field differently if you wanted to. By initializing to an empty list, the container would force what the default value should be. Thanks anyway for the suggestion.
