### ISSUE TITLE
Huge performance issue with @Transactional [SPR-15909]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20463]
**[Ács Ádám](https://jira.spring.io/secure/ViewProfile.jspa?name=acsadam)** opened **[SPR-15909](https://jira.spring.io/browse/SPR-15909?redirect=false)** and commented

Enabling `@Transaction` on a spring service makes a method execution time 100x slower. I set up a minimum example, it shows the following:

1 spring bean + 1 pojo, both has a trivial method to execute. Mesured with spring stopwatch.

Without transaction:
pojo: 1ms
bean: 1ms

With transaction:
pojo: 1ms
bean: 89ms

---

**Affects:** 4.3.10

**Attachments:**
- [slow_transactional.zip](https://jira.spring.io/secure/attachment/25083/slow_transactional.zip) (_2.70 kB_)

**Comment by bclozel** [comment]
Closing as this doesn't point to any possible optimization.
