### ISSUE TITLE
Inconsistent bean definition visibility between @ComponentScan and @Import [SPR-15929]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20483]
**[Stéphane Nicoll](https://jira.spring.io/secure/ViewProfile.jspa?name=snicoll)** opened **[SPR-15929](https://jira.spring.io/browse/SPR-15929?redirect=false)** and commented

The use case is described [in a Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/5093#issuecomment-180405492)

---

**Affects:** 4.3.10

**Comment by jhoeller** [comment]
We do not have any larger rearrangement planned there for 6.x anymore, so let's rather close this issue.
