### ISSUE TITLE
Support null-safety at generics, varargs and array elements level [SPR-15942]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20496]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-15942](https://jira.spring.io/browse/SPR-15942?redirect=false)** and commented

As raised and discuss on [KT-19592 Kotlin issue](https://youtrack.jetbrains.com/issue/KT-19592), null-safety of Spring API does not apply to generic type arguments. To do so, after KT-19592 being fixed we would have to use `ElementType.TYPE_USE` but its scope is too wide to make it usable for us at `@TypeQualifierDefault` level of `@Nullable` and `@NonNullApi`.

Another solution would be to add `ElementType.TYPE_USE` at `@Target` and annotate every generic type argument of Spring API, maybe that could be done via introducing a `@NonNull` annotation that would also be useful for #20311.

---

**Issue Links:**
- #20311 Revisit nullability annotations towards GA (_**"depends on"**_)

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/0e1be82cfbc5b31bc8edcbec81feb08a99d9c3de, https://github.com/spring-projects/spring-framework/commit/1bc93e3d0f2bd3ffc6b48662073a427c31088b3d

**Comment by liuHongJie1217** [comment]
lol
