### ISSUE TITLE
ExceptionHandlerMethodResolver unwraps cause, but InvocableHandlerMethod does not support it [SPR-15951]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20503]
**[Mauro Molinari](https://jira.spring.io/secure/ViewProfile.jspa?name=mauromol)** opened **[SPR-15951](https://jira.spring.io/browse/SPR-15951?redirect=false)** and commented

In Spring Framework 4.3, the `org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver` should support exception unwrapping (i.e.: extracting the cause from a wrapping exception) to properly invoke methods annotated with `@ExceptionHandler` for an exception type which is the runtime type of the cause of the wrapping exception.

This is performed thanks to `org.springframework.web.method.annotation.ExceptionHandlerMethodResolver.resolveMethod(Exception)` performing an attempt with the exception cause if no method is resolved for the wrapping exception type.
By the way, my first question is: shouldn't `org.springframework.web.method.annotation.ExceptionHandlerMethodResolver.resolveMethod(Exception)` perform a recursive search on causes?

Anyway, suppose we do not need recursion here, as in my case. Once `org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(HttpServletRequest, HttpServletResponse, HandlerMethod, Exception)` has resolved the method and put it into a `org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod` instance, it calls `org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletWebRequest, ModelAndViewContainer, Object...)`, which fails because it can't unwrap the exception like the method resolver did. This is because neither `org.springframework.web.method.support.InvocableHandlerMethod.resolveProvidedArgument(MethodParameter, Object...)` nor anybody calling it performs such unwrapping.

Let's explain this with an example.

Suppose I have my controller method:

```java
public void doSomething() throws WrappingException {
  throw new WrappingException(new MyException());
}
```

And I have this in my controller advice:

```java
@ExceptionHandler(MyException.class)
@ResponseStatus(HttpStatus.FORBIDDEN)
@ResponseBody
public String handleMyException(final MyException e) {
  return "handled!";
}
```

By debugging I see that when the controller method throws its `WrappingException` with a `MyException` instance as its cause, the `handleMyException` handler method is correctly resolved by `ExceptionHandlerMethodResolver`, but then `org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletWebRequest, ModelAndViewContainer, Object...)` fails because `org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(NativeWebRequest, ModelAndViewContainer, Object...)` fires an `IllegalStateException` with message:

```
Could not resolve method parameter at index 0 in public void mypackage.MyControllerAdvice.handleMyException(mypackage.MyException): No suitable resolver for argument 0 of type 'mypackage.MyException'
```

This is because `org.springframework.web.method.support.InvocableHandlerMethod.resolveProvidedArgument(MethodParameter, Object...)` simply tries to match the method arguments by type, and hence expects a `WrappingException` to be passed to the handler method.

---

**Affects:** 4.3.10

**Comment by sarangajay** [comment]
Has this been fixed? I am on release 5.1.5.RELEASE and still face with this issue.
**Could not resolve parameter No suitable resolver.**
Appreciate an update.

**Comment by rstoyanchev** [comment]
I tried the above snippets going back to 4.3.10 and it works as expected. Please provide an isolated sample that demonstrates the demonstrates the issue.

A coupe more things:

1. The cause [is passed](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ExceptionHandlerExceptionResolver.java#L402) as a provided arg and available to resolve.

 > InvocableHandlerMethod.resolveProvidedArgument(MethodParameter, Object...) simply tries to match the method arguments by type, and hence expects a WrappingException to be passed to the handler method

2. It should not expect a `WrappingException` because the method parameter is declared with `MyException`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
