### ISSUE TITLE
AbstractMessageReaderArgumentResolver element type customization [SPR-15983]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20533]
**[Christoph Muck](https://jira.spring.io/secure/ViewProfile.jspa?name=d4muck)** opened **[SPR-15983](https://jira.spring.io/browse/SPR-15983?redirect=false)** and commented

Currently there is now way to customize which element type the org.springframework.web.reactive.result.method.annotation.AbstractMessageReaderArgumentResolver#readBody Method uses for deserialization.
It always uses the Type of the method parameter, which is retrieved [on line 118](https://github.com/spring-projects/spring-framework/blob/e7c45d986bc674240e18a7bf047a48543ab00699/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/AbstractMessageReaderArgumentResolver.java#L118).

I was thinking to add a new

```java
protected ResolvableType getCustomBodyType(MethodParameter bodyParameter, boolean isBodyRequired, BindingContext bindingContext, ServerWebExchange exchange) {
    return null;
}
```

method to that class and change the line 118 to

```java
ResolvableType customBodyType = getCustomBodyType(bodyParameter, isBodyRequired, bindingContext, exchange) ;
ResolvableType elementType = customBodyType != null ? customBodyType :  (adapter != null ? bodyType.getGeneric() : bodyType);
```

Would that be a viable solution to that problem or am I missing something?

---

**Affects:** 5.0 RC4

**Comment by rstoyanchev** [comment]
Shouldn't the element type match the target method parameter? What's the use case here?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
