### ISSUE TITLE
Consider Starting a Gitter Chat Room [SPR-15980]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20530]
**[Kyle Anderson](https://jira.spring.io/secure/ViewProfile.jspa?name=kanderson)** opened **[SPR-15980](https://jira.spring.io/browse/SPR-15980?redirect=false)** and commented

I would like to suggest starting a Gitter chat room for the Spring Framework itself.  Many other projects in the Spring portfolio use this tool as an alternative support channel to Jira/GitHub Issues and Stackoverflow.  It is most useful when a question or problem needs some back and forth interaction from others in the community.  Those scenarios are not well supported by Stackoverflow nor do they necessarily warrant a new Issue.

Thanks for your consideration.

---

**Reference URL:** https://jira.spring.io/browse/SPR-15265?focusedCommentId=135538&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-135538

**Comment by bclozel** [comment]
Declining as we didn't get much traction for this.
