### ISSUE TITLE
Safe Navigation Operator and Indexing [SPR-16003]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20552]
**[Eric Bottard](https://jira.spring.io/secure/ViewProfile.jspa?name=eric.bottard)** opened **[SPR-16003](https://jira.spring.io/browse/SPR-16003?redirect=false)** and commented

Is there a way to combine `?.` and array/map indexing?
If `labels` is a Map that can be `null`, I'd like a nice way to express this using `[]` indexing:
`#root.labels?.get('key')`

---
No further details from [SPR-16003](https://jira.spring.io/browse/SPR-16003?redirect=false)

**Comment by snicoll** [comment]
Duplicate of #21468
