### ISSUE TITLE
Support RegexPatternTypeFilter include filter for component index [SPR-16010]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20559]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[SPR-16010](https://jira.spring.io/browse/SPR-16010?redirect=false)** and commented

Using `ClassPathScanningCandidateComponentProvider` with an `RegexPatternTypeFilter` include filter prevents use of the component index.

It might be worth to evaluate regex on the component index so Spring Data's [custom repository implementation scan](https://github.com/spring-projects/spring-data-commons/blob/049970874dca2b648c9d2f3bfdd01f0e8a11de51/src/main/java/org/springframework/data/repository/config/CustomRepositoryImplementationDetector.java#L116) could benefit from component-index-based scanning. `RegexPatternTypeFilter` is used on every scan to limit component candidates with a simple class name.

It also might be worth introducing a `SimpleClassNameTypeFilter` dedicated to this style of filtering to eliminate regex pattern compilation and the associated matching cost.

---
No further details from [SPR-16010](https://jira.spring.io/browse/SPR-16010?redirect=false)

**Comment by snicoll** [comment]
The context indexer [has been deprecated](https://github.com/spring-projects/spring-framework/issues/30431) and we don't intent to make further changes to it.
