### ISSUE TITLE
Let Spring show the URL mappings for @MessageMapping in startup process [SPR-16015]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20564]
**[Manuel Jordan](https://jira.spring.io/secure/ViewProfile.jspa?name=dr_pompeii)** opened **[SPR-16015](https://jira.spring.io/browse/SPR-16015?redirect=false)** and commented

When I startup the Tomcat server I can see during the process all the `URL URI` available in the web app from all the `@Controller` and `@RestController` according their `@RequestMapping` and variations such as: `@GetMapping` etc. And of course taking in consideration the attributes, such as `produces`, `consumes` etc ...

I think for `websocket` the same should happen for `@MessageMapping`

---

**Affects:** 4.3.11

**Comment by rstoyanchev** [comment]
We could do something similar to the improvements for #21982.
