### ISSUE TITLE
WebFlux support for flash attributes [SPR-16026]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20575]
**[Adrien Sanchez](https://jira.spring.io/secure/ViewProfile.jspa?name=asanchez)** opened **[SPR-16026](https://jira.spring.io/browse/SPR-16026?redirect=false)** and commented

Hello,

I faced an issue when wanting to perform a redirection with redirect attributes on a Spring Webflux application.

In Spring MVC, I used to add the _RedirectAttributes_ parameter in my controller methods to configure the attributes/flash attributes that I wanted to transmit through my redirection.

However, in Spring Webflux, there seems to be no equivalent to the Spring MVC _RedirectAttributes_ class. This is a problem as Spring Webflux controllers should be able to perform redirections with attributes too.

I tried using the _redirectTo_ method of the reactive _Rendering_ API, that works to perform a redirection, but there's no way to transmit parameters here too. Maybe this API could evolve to include this possibility ? And do you have any workaround that could be used at the moment?

Thanks and regards,
Adrien

---

**Affects:** 5.0 RC3, 5.0 RC4, 5.0 GA

**Reference URL:** https://stackoverflow.com/questions/46474452/redirectattributes-not-working-with-spring-5

**Comment by shavz** [comment]
I have run into the same issue when trying to persist a user session info through redirects.  Currently working around by storing the data in state as a nonce:{data} but would like to see this built in Webflux so we can do it properly.

**Comment by benjamin-dreux** [comment]
Now that spring mvc as functional endpoints, that clearly draw inspiration from webflux, but also suffer from the same issue on the lack of support for flash attributes.

We have access to the session and flash attributes are in the end stored in the session.
But in my opinion this facility should be part of spring framework.

If it's now in the api, we miss at least a documentation for it

**Comment by bclozel** [comment]
With only 5 upvotes over the last 7 years, I don't think we can consider this as a highly upvoted feature.
Let's decline this feature for now and reconsider if there is much more demand in the future.
