### ISSUE TITLE
@Payload does not convert the message on a @JmsListener annotated method [SPR-16036]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20585]
**[Sebastiaan van Erk](https://jira.spring.io/secure/ViewProfile.jspa?name=sebster)** opened **[SPR-16036](https://jira.spring.io/browse/SPR-16036?redirect=false)** and commented

I have the following method:

```
@JmsListener(destination = "myDestination")
public void on(@Payload Object message) { ... }
```

However messages that are received are not converted (I get AMQTextMessage instances with the XML string in the body). If I change the method signature to:

```
@JmsListener(destination = "myDestination")
public void on(Message<Object> message) { ... message.getPayload() ... }
```

then everything works fine (the payload is unmarshalled using the configured JAXB unmarshaller).

---

**Affects:** 4.3.7

**Comment by snicoll** [comment]
Unfortunately, I can't reproduce this. `PayloadArgumentResolver` will not attempt to convert the payload if the type is assignable, but it will return the payload, not the JMS message. If you can reproduce this with a supported version, please attach a small sample we can run ourselves and we can reopen.
