### ISSUE TITLE
Unable to use WebTestClient with mock server in Kotlin

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20606]
**[Daniel Jones](https://jira.spring.io/secure/ViewProfile.jspa?name=jonesd9)** opened **[SPR-16057](https://jira.spring.io/browse/SPR-16057?redirect=false)** and commented

I'm trying to set up a Kotlin/Spring project using Spring Boot 2.0.0.M4 and Spring Framework 5.0.0.M4 and have ran into trouble with `WebTestClient` in a mocked-server test.

Essentially the following in Java works fine:

```java
class JavaHelper {
    static WebTestClient getMockWebTestClient(ApplicationContext ctx) {
        return WebTestClient.bindToApplicationContext(ctx)
                            .apply(springSecurity())
                            .configureClient()
                            .filter(basicAuthentication())
                            .build();
    }
}
```

But Kotlin is unable to infer the type T of apply method:

```java
<T extends B> T apply(MockServerConfigurer configurer)
```

With the following code:

```java
WebTestClient.bindToApplicationContext(context)
                .apply(springSecurity())
                .configureClient()
                .filter(basicAuthentication())
                .build()
```

The problem is to do with the generic typings, I'm still fairly new to Kotlin but if I write my test using the same package as `ApplicationContextSpec` (since they're package-private) and do the following, it works as expected:

```java
(WebTestClient.bindToApplicationContext(context) as ApplicationContextSpec)
                .apply<ApplicationContextSpec>(springSecurity())
                .configureClient()
                .filter(basicAuthentication())
                .build()
```

I think the following:

```java
static MockServerSpec<?> bindToApplicationContext(ApplicationContext applicationContext) {
    return new ApplicationContextSpec(applicationContext);
}
```

should be changed to return `ApplicationContextSpec` (or at least `AbstractMockServerSpec<ApplicationContextSpec>`):

and make the class `ApplicationContextSpec` public. The constructor can still be default visibility so users won't be able to misuse the class outside of the defined API, and users in Kotlin will be able to import it for type inference.

---

**Affects:** 5.0 GA

**Issue Links:**
- #20945 Upgrade to Kotlin 1.3 (_**"depends on"**_)
- #20251 Kotlin unable to inherit type for WebTestClient#BodySpec

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/b9a0e6bbf2b6fe5f0ed222f506efc644d0d9a4f0

2 votes, 11 watchers

**Comment by andriipivovarov** [comment]
Any work around?

**Comment by noah-iam** [comment]
Hey,
For the similar issue , I want to share you my piece of code that is giving me same error :

.webFilter<>(myfilter) . This is saying to give the generic type here.

Error : Type expected

val client: WebTestClient = WebTestClient.bindToWebHandler { Mono.empty() } .webFilter<>(myfilter) .build()

Error : Type argument is not within its bounds. Expected: Nothing! Found: WebFilter!

@sdeleuze can you help me in this

**Comment by maresja1** [comment]
@andriipivovarov Work around:

```kotlin
// copy of org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers.MutatorFilter
internal class MutatorFilter : WebFilter {

    override fun filter(exchange: ServerWebExchange, webFilterChain: WebFilterChain): Mono<Void> {
        val context = exchange.getAttribute<Supplier<Mono<SecurityContext>>>(ATTRIBUTE_NAME)
        if (context != null) {
            exchange.attributes.remove(ATTRIBUTE_NAME)
            return webFilterChain.filter(exchange)
                .subscriberContext(ReactiveSecurityContextHolder.withSecurityContext(context.get()))
        }
        return webFilterChain.filter(exchange)
    }

    companion object {
        const val ATTRIBUTE_NAME = "context"
    }
}
```

And apply:

```koltin
        WebTestClient.bindToApplicationContext(context)
            .configureClient()
            .baseUrl("https://api.example.com")
            .defaultHeader("Content-Type", MediaType.APPLICATION_JSON_VALUE)
// ...
            .apply { _, httpHandlerBuilder, _ ->
                httpHandlerBuilder?.filters { filters -> filters.add(0, MutatorFilter()) }
            }
```

If anyone knows about a better way, please let me know.

**Comment by sdeleuze** [comment]
This issue still happens with Kotlin 1.4.10 likely due to [KT-40804](https://youtrack.jetbrains.com/issue/KT-40804) and I agree we should try to find a solution. I am discussing that with Kotlin team.

**Comment by xetra11** [comment]
Any updates on this?

**Comment by sdeleuze** [comment]
Both Kotlin and Spring team agreed this issue should be fixed on Kotlin side. My current hope is that it will be fixed in Kotlin 1.6 (Kotlin 1.5 is just around the corner and Kotlin has now a 6 month release cycle so that won't be too far away).

**Comment by petukhovv** [comment]
Note that we (Kotlin team) supported given cases in the experimental mode in 1.5.30. In 1.5.30 the `-Xself-upper-bound-inference` compiler flag could be used to enabled the corresponding feature.
More information: https://youtrack.jetbrains.com/issue/KT-40804

**Comment by sdeleuze** [comment]
Indeed seems to work based on my tests, thanks! I will close this issue when we will be based on Kotlin 1.6 in order to add proper test.

@petrukhnov Could you please confirm this will be the default as of Kotlin 1.6?
