### ISSUE TITLE
Support for reactive relational database access [SPR-16069]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20618]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-16069](https://jira.spring.io/browse/SPR-16069?redirect=false)** and commented

As per JavaOne 2017, a Reactive JDBC API is "targeted for a near future release, Java 10 or equivalent" (see https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=CON1491). Let's pick this up in a programmatic form once available, with Spring Data providing its repository model on top of it.

---

**Reference URL:** https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=CON1491

12 votes, 19 watchers

**Comment by sdeleuze** [comment]
I am closing this issue since it is superseded by [Spring Data R2DBC](https://spring.io/projects/spring-data-r2dbc) which provide a nice programmatic API with `DatabaseClient`.

On framework side, we are likely to implement Reactive transactions, I will link the issue asap it will be created.
