### ISSUE TITLE
Add support for MockRestServiceServer to verify multipart request [SPR-16105]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20653]
**[Haruki Okada](https://jira.spring.io/secure/ViewProfile.jspa?name=ocadaruma)** opened **[SPR-16105](https://jira.spring.io/browse/SPR-16105?redirect=false)** and commented

It would be useful to add RequestMatcher to verify multipart/form-data request.

Such as:

```java
// in MockRestRequestMatchers
public static RequestMatcher multipart(final MultiValueMap<String, byte[]> items) {
	// assert equality
}
```

I would like to submit a pull request later.

---

1 votes, 5 watchers

**Comment by sbrannen** [comment]
This related to gh-23671 and should be assessed in conjunction with that.

**Comment by rstoyanchev** [comment]
This is now superseded by #23772.
