### ISSUE TITLE
Leniently bind "is" prefix for boolean properties (along the lines of Jackson) [SPR-16135]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20683]
**[gtxx](https://jira.spring.io/secure/ViewProfile.jspa?name=spxx)** opened **[SPR-16135](https://jira.spring.io/browse/SPR-16135?redirect=false)** and commented

I want to bind request parameters to User class instance, and there is a boolean field in User class.

```java
1. controller class
@GetMapping("/test")
UserBo ttt(User user){
        return user;
}
1. User.java
public class User {
    private String username;
    private Boolean isActive;
}
```

setter for isActive field works only if it's like this:

```java
public void setIsActive(Boolean active) {
        isActive = active;
}
```

If I use Intellij to generate setter and getter, setter is like this:

```java
public void setActive(Boolean active) {
        isActive = active;
}
```

with above setter, spring can't bind query parameter isActive to User.isActive.

Jackson can support both setters, I wonder if spring can improve query parameter binding like Jackson.

---

**Affects:** 4.3.10

**Reference URL:** https://stackoverflow.com/questions/16942193/spring-mvc-complex-object-as-get-requestparam

**Comment by wagnerluis1982** [comment]
I stumbled at this issue, I wonder if this is really relevant?
