### ISSUE TITLE
SpEL: Equality should honour canCompare  [SPR-16141]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20689]
**[Tin Pavlinic](https://jira.spring.io/secure/ViewProfile.jspa?name=triggernz)** opened **[SPR-16141](https://jira.spring.io/browse/SPR-16141?redirect=false)** and commented

The attached test fails. There are two issues:

1) StandardTypeComparator's canCompare is wrong, in the sense that it answers true to comparisons between integers and strings, but compare crashes.

2) Possibly as a workaround for (1) Operator.equalityCheck does checks to make sure the comparison is safe instead of delegating to canCompare.

The result is that implementing a custom TypeComparator does not always result in it being used in equality checks.

---

**Affects:** 5.0.1

**Attachments:**
- [AlternativeComparatorTests.java](https://jira.spring.io/secure/attachment/25202/AlternativeComparatorTests.java) (_1.96 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1581

**Comment by bclozel** [comment]
Closing in favor of #1581
