### ISSUE TITLE
Invalid instance injected for generic type in case of partial type variable [SPR-16179]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20727]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[SPR-16179](https://jira.spring.io/browse/SPR-16179?redirect=false)** and commented

The following test fails:

```java
package example;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class SpringInjectionTest {

	@Configuration
	static class Config {

		@Bean
		PageAssembler<?> assembler() {
			return new PageAssembler<>();
		}
	}

	@Autowired(required = false) Assembler<SomeOtherType> assembler;

	@Test
	public void testname() {
		assertThat(assembler, is(nullValue()));
	}

	interface Assembler<T> {}

	static class PageAssembler<T> implements Assembler<Page<T>> {}

	interface Page<T> {}

	interface SomeOtherType {}
}
```

Spring injects the configured bean instance here despite the fact that the generic declarations clearly don't match as `Page<T>` is not compatible with the requested `SomeOtherType`.

---

**Affects:** 4.3.12, 5.0.1

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/59d654b0cfa523fb9f5d2ff9961106ad46d92953, https://github.com/spring-projects/spring-framework/commit/e2bb06edbdd23716df7c265db28f65e6c432a2aa

**Comment by jhoeller** [comment]
This requires a dedicated matching step within `descriptor.fallbackMatchAllowed()` in `GenericTypeAwareAutowireCandidateResolver`:

```
	if (targetType.hasUnresolvableGenerics()) {
		return dependencyType.isAssignableWithinResolvedPart(targetType);
	}
	else if (targetType.resolve() == Properties.class) {
		return true;
	}
```

Within that special isAssignable check, matching the nested generics until an unresolvable part (`other.isUnresolvableTypeVariable()` or other `typeBounds` without `ourBounds`) is encountered on the other side and returning `true` then - but only after the nested generics matched up until that point. As far as the prototype goes, the test suite passes with such an arrangement. This might be too risky for 6.1.x but easy enough to roll into 6.2.
