### ISSUE TITLE
Spring 4 HibernateTransactionManager close session while executing hibernate entity-interceptor or event listener [SPR-16208]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20756]
**[Chintan](https://jira.spring.io/secure/ViewProfile.jspa?name=ctvisani)** opened **[SPR-16208](https://jira.spring.io/browse/SPR-16208?redirect=false)** and commented

I am upgrading spring and hibernate to 4.2.x from version 3.2.x .But after upgrading query executed inside entity-interceptor breaks transaction and session get closed from next transaction. If I comment out my interceptor logic than application works fine.I also tried with event listener but it happens same.So anything comes with spring newer version (4.2.2) related to interceptor that it wont work with localsessionfactorybean or anything I miss.

My Configuration for localsessionfactorybean :

<tx:annotation-driven transaction-manager="myTransaction"/>
\<bean id="myInterceptor" class="com.test.MyInterceptor">
\</bean>
\<bean id="sessionFactory" class="org.springframework.orm.hibernate4.LocalSessionFactoryBean">
......
\<property name="entityInterceptor" ref="myInterceptor" />
......
\<bean>
\<bean id="myTransaction" class="org.springframework.orm.hibernate4.HibernateTransactionManager">
\<property name="sessionFactory" ref="sessionFactory"/>
\</bean>

---
No further details from [SPR-16208](https://jira.spring.io/browse/SPR-16208?redirect=false)

**Comment by bclozel** [comment]
These versions are not supported anymore.
