### ISSUE TITLE
Expose parameter names from ParsedSql [SPR-16211]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20759]
**[Yanming Zhou](https://jira.spring.io/secure/ViewProfile.jspa?name=quaff)** opened **[SPR-16211](https://jira.spring.io/browse/SPR-16211?redirect=false)** and commented

I'm developing a query console using NamedParameterJdbcTemplate, I need get parameter names from sql to construct UI form let user input parameters

```java
ParsedSql parsedSql = NamedParameterUtils.parseSqlStatement(sql);
List<String> params = parsedSql.getParameterNames(); //NOT public
```

It's better if NamedParameterJdbcTemplate could provide a method to get parameter name and parameter type, using PreparedStatement.getParameterMetaData().getParameterType()

---

**Reference URL:** https://github.com/spring-projects/spring-framework/pull/1597

**Issue Links:**
- #15442 make org.springframework.jdbc.core.namedparam.ParsedSql public accessible  (_**"is duplicated by"**_)
- #20887 NamedParameterJdbcTemplate fails on PostgreSQL array
- #20908 SqlParameterSource needs method for extracting parameter names

**Comment by rengy-github** [comment]
Namedparameterutils is a tool class. I also want to use this class instead of copying one
