### ISSUE TITLE
Make UrlBasedViewResolver prefix/suffix nullability consistent [SPR-16220]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20768]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-16220](https://jira.spring.io/browse/SPR-16220?redirect=false)** and commented

---
No further details from [SPR-16220](https://jira.spring.io/browse/SPR-16220?redirect=false)

**Comment by sdeleuze** [comment]
I am closing this issue has we don't have any actionable item since we are blocked on [KT-6519](https://youtrack.jetbrains.com/issue/KT-6519#comment=27-2547893) which has been opened for 9 year.
