### ISSUE TITLE
MethodValidationPostProcessor does not work with Mono and Flux method parameters [SPR-16234]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20781]
**[Sanjaya Kumar Patel](https://jira.spring.io/secure/ViewProfile.jspa?name=skpatel20)** opened **[SPR-16234](https://jira.spring.io/browse/SPR-16234?redirect=false)** and commented

Traditionally (non-reactive), we had been doing method parameter validation as below:

```
@Validated
@Service
public class FooService

@Validated(SignUpValidation.class)
public void signup(@Valid UserCommand userCommand) {

    ...
}
```

In a reactive world, this might look like:

```
@Validated
@Service
public class FooService

@Validated(SignUpValidation.class)
public Mono<Void> signup(@Valid Mono<UserCommand> userCommand) {

    ...
}
```

But this is not working. So, in summary:

1. Support for Mono and Flux is missing when using MethodValidationPostProcessor
2. Also need support for [validation groups](https://docs.spring.io/autorepo/docs/spring-framework/current/javadoc-api/org/springframework/validation/beanvalidation/MethodValidationPostProcessor.html) (See `@Validated`(SignUpValidation.class) above)

---

**Affects:** 5.0.1

**Reference URL:** https://stackoverflow.com/questions/47244769/how-to-validate-mono-when-using-spring-reactive

**Comment by rstoyanchev** [comment]
Note that `@Valid` is supported in WebFlux in combination with reactive types. This ticket I believe is mainly for `MethodValidationPostProcessor` and use of method-level `Validated`.

**Comment by fgolygo** [comment]
Any update on that?

**Comment by rstoyanchev** [comment]
This is now supported by using `doOnNext` on the respective `Mono` and `Flux` in order to validate the actual values when they do materialize.
