### ISSUE TITLE
dependentBeanMap won't be rebuilt after destroySingleton and recreate it [SPR-16249]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20796]
**[Nick Allen](https://jira.spring.io/secure/ViewProfile.jspa?name=nicktheuncharted)** opened **[SPR-16249](https://jira.spring.io/browse/SPR-16249?redirect=false)** and commented

If we call destroySingleton it calls destroyBean which remove it's dependency from dependentBeanMap. Then if we call getBean which create that singleton again,  dependency won't be added back to dependentBeanMap (Because it should have been added in AutowiredAnnotationBeanPostProcessor.inject but it won't call registerDependentBeans if it is cached).

Solution: Remove metadataCache of bean in injectionMetadataCache when that bean get destroyed.

---

**Affects:** 4.3.10

**Issue Links:**
- #21663 BeanDefinition-aware BeanPostProcessors should clear cache in case of bean definition reset

**Comment by jhoeller** [comment]
Superseded by #21663.
