### ISSUE TITLE
Topic messages are not sent when using transacted JmsTemplate in 'TransactionSynchronization.afterCommit' phase [SPR-16270]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20817]
**[ofer baranes](https://jira.spring.io/secure/ViewProfile.jspa?name=ofer.baranes)** opened **[SPR-16270](https://jira.spring.io/browse/SPR-16270?redirect=false)** and commented

On the following scenario, an attempt to send message to a TOPIC using JmsTemplate is not effective (the message is never sent and there is no error):
1. Open Transaction using spring framework
2. Register TransactionSynchronization to the active Transaction
3. On the TransactionSynchronization, implement the 'afterCommit' as below:

* create JmsTemplate and set it to be 'transacted'
* send a message to a topic

4. commit the Transaction

The expectation is that the message would be send and the subscriber would handle it.
On real, the message is never handled by the subscriber. The reason is that the message wasn't truly send.

Other observations:
The expectation is fulfilled and the subscriber gets the message if:
a) Using 'afterCompletion' instead of 'afterCommit',
b) Using none transacted JmsTemplate (on the 'afterCommit')

It appears that Spring determines the existence of an ongoing transaction by checking state

_**TransactionSynchronizationManager**
public static boolean isSynchronizationActive()  {
return synchronizations.get() != null;
}
_

Since the 'synchronizations' thread local is not cleared when executing the 'afterCommit' callback, Spring mistakenly assumes that there is ongoing transaction and hence bounds the JMS operation to the ongoing transaction (instead of commiting it immediately) and since there is no ongoing transaction the JMS operation would never be committed.
(When using 'afterCompletion' it works since the 'synchronizations' thread local was cleared)

---

**Affects:** 4.3.11

**Issue Links:**
- #16214 TransactionSynchronizationManager - throw an Exception or log a warning if a Synchronization wants to add a Synchronization and afterCompletion is already called

**Comment by jhoeller** [comment]
We are initiating a late local JMS transaction commit in `JmsResourceSynchronization.afterCompletion` if necessary now, tracking whether our local `afterCommit` has been bypassed due to late registration and making up for it in `afterCompletion` then. This should hopefully lead to the expected outcome even in such a semantically questionable scenario,
