### ISSUE TITLE
More detailed information about failing bean on ImplicitlyAppearedSingletonException [SPR-16326]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20873]
**[Rahul Shinde](https://jira.spring.io/secure/ViewProfile.jspa?name=rsjira22)** opened **[SPR-16326](https://jira.spring.io/browse/SPR-16326?redirect=false)** and commented

At times, my application fails to boot up and the exception in the logs just shows the IllegalStateException /ImplicitlyAppearedSingletonException.
With the current code, there is no additional data on which bean triggered this exception.

With the changes in the PR, the offending bean can be identified easily.

---

**Affects:** 5.0.2

**Reference URL:** https://github.com/spring-projects/spring-framework/pull/1635

**Comment by snicoll** [comment]
The PR has been closed so I can't unfortunately access the code to asses if that's a change we want to merge.
