### ISSUE TITLE
@AspectJ @Component could not autowired its field [SPR-16331]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20878]
**[abdushkur ablimit](https://jira.spring.io/secure/ViewProfile.jspa?name=abdushkur)** opened **[SPR-16331](https://jira.spring.io/browse/SPR-16331?redirect=false)** and commented

console debug message says it is autowired but it is not, so debug and took pictures,
please review marked info
could you give me some advice?

---

**Affects:** 4.3.8

**Attachments:**
- [3.PNG](https://jira.spring.io/secure/attachment/25328/3.PNG) (_143.68 kB_)

**Comment by snicoll** [comment]
Unfortunately a screenshot is nowhere near enough for us to help. I am going to close this but if you're watching and you're still having the issue, we can reopen when you provide a sample we can run ourselves. Sorry this got overlooked.
