### ISSUE TITLE
NamedParameterJdbcTemplate fails on PostgreSQL array [SPR-16340]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20887]
**[Nikita Khateev](https://jira.spring.io/secure/ViewProfile.jspa?name=khatkit)** opened **[SPR-16340](https://jira.spring.io/browse/SPR-16340?redirect=false)** and commented

There is a possible bug while parsing SQL query for PostgreSQL DB. If you will try to execute a named query like this:

```sql
UPDATE table SET name = array[:param]
```

The name of param will be parsed as 'param]', which is incorrect. However, if you will try to execute this query:

```sql
UPDATE table SET name = array[:param ]
```

It will parse param name correctly.

---

**Affects:** 5.0.2

**Issue Links:**
- #12613 NamedParameterUtils.parseSqlStatement can't handle quote following comment end
- #21018 [Regression] NamedParameterUtils::parseSqlStatement cannot parse chinese param name
- #21017 NamedParameterUtils.isParameterSeparator throws ArrayIndexOutOfBoundsException for non ASCII characters
- #21204 NamedParameterUtils.parseSqlStatement should parse :{x} style parameter correctly
- #20759 Expose parameter names from ParsedSql
- #21055 NamedParameterJdbcTemplate doesn't support postgresql dollar quoting $$
- #20908 SqlParameterSource needs method for extracting parameter names

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1637

**Comment by sbrannen** [comment]
This appears to have been fixed in #27716.

If you still encounter this issue with Spring Framework 6.0.13 (or a later version), please create a new issue.

Thanks
