### ISSUE TITLE
Generic bean factory [SPR-16349]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20896]
**[Lovro Pandžić](https://jira.spring.io/secure/ViewProfile.jspa?name=lpandzic)** opened **[SPR-16349](https://jira.spring.io/browse/SPR-16349?redirect=false)** and commented

From https://stackoverflow.com/questions/45741395/spring-generic-bean-factory, I'd like to be able to define a factory which automatically creates beans for all beans declared of a certain type. The important part is that the factory has generic type available upon request.
If this is already possible, please provide an example in the documentation.

---

1 votes, 1 watchers

**Comment by snicoll** [comment]
I can see that you accepted the answer on SO. For prototype beans, `InjectionPoint` does give access to the member for which you can build the full generic signature using `ResolvableType`.
