### ISSUE TITLE
It's very boring to mock a lot of autowired fields in a complex service when writing a test case. [SPR-16355]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20902]
**[YushanGao](https://jira.spring.io/secure/ViewProfile.jspa?name=boroborome)** opened **[SPR-16355](https://jira.spring.io/browse/SPR-16355?redirect=false)** and commented

When write a unit test case for a service, we have to write code like this to mock every depend services:

ReflectionTestUtils.setField(targetService, "dependService1", dependService1Mock);
ReflectionTestUtils.setField(targetService, "dependService2", dependService2Mock);
ReflectionTestUtils.setField(targetService, "dependService3", dependService3Mock);
....

There will be many code like this in a complex service, we need an easy way to replace this code.

---

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1613

**Comment by sbrannen** [comment]
- Superseded by #1613
