### ISSUE TITLE
Provide gRPC support [SPR-16358]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20905]
**[Ashok](https://jira.spring.io/secure/ViewProfile.jspa?name=thekalinga)** opened **[SPR-16358](https://jira.spring.io/browse/SPR-16358?redirect=false)** and commented

gRPC is becoming defacto standard for service to service communication, due to its ubiquitous nature & use of HTTP2

Currently we have `grpc-java` which generates its own version of classes that handle request in their own proprietary way when compared to Spring MVC & Spring WebFlux.

Plus, modern service mesh frameworks like https://envoyproxy.io works very nicely with gRPC.

Developers in spring world requires this high performance, type safe service-service integration (tho we have integration with hystrix, gRPC is much more performant & support wide variety of languages).

Here are some pain points in using grpc-java in spring world

1. Since gRPC makes no assumption about Spring web framework, its request handling has a completely different path outside of WebFlux/MVC
2. Integrating that code with spring ecosystem like Security will be completely adhoc & fragile

If spring can scaffold a WebFlux/MVC project from grpc service definition, it will improve the development experience & at the sametime developers like me can enjoy the benefits of gRPC

---

**Issue Links:**
- #21292 RSocket client and server support
- #20331 Support Protobuf serialization in WebFlux
- #21011 Add Thrift RPC support to WebFlux

7 votes, 18 watchers

**Comment by ST-DDT** [comment]
There might be a good starting point for a spring(-boot) grpc library: [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter). There have been [discussions](https://github.com/yidongnan/grpc-spring-boot-starter/issues/164#issuecomment-449188681) to become a spring library already.

See also: https://github.com/spring-cloud/spring-cloud-sleuth/pull/1139#issuecomment-444302714

**Disclosure:** I'm one of the core maintainers of [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter).

**Comment by trustin** [comment]
You can also use Armeria's Spring Boot integration: https://line.github.io/armeria/advanced-spring-webflux-integration.html The integration looks like this:

- Armeria runs a Netty-based HTTP/2 server
- gRPC services and clients runs on top of Armeria
- Thrift services and clients run on top of Armeria
- WebFlux (or Spring MVC) runs on top of Armeria
  - reactor-netty is replaced with Armeria

I'm one of the maintainers of Armeria project.

**Comment by mattdkerr** [comment]
> There might be a good starting point for a spring(-boot) grpc library: [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter). There have been [discussions](https://github.com/yidongnan/grpc-spring-boot-starter/issues/164#issuecomment-449188681) to become a spring library already.
> 
> See also: [spring-cloud/spring-cloud-sleuth#1139 (comment)](https://github.com/spring-cloud/spring-cloud-sleuth/pull/1139#issuecomment-444302714)
> 
> **Disclosure:** I'm one of the core maintainers of [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter).

I've been using this one for a project at EA and have had good success with it. It would be great to have more developers contributing, as I haven't had as much time as I would have liked to do so myself. (I've updated it to Gradle 6 line to support newer protobuf-gradle plugin so far.)

**Comment by bclozel** [comment]
As we can see in the comments above, there are numerous existing Spring integrations for gRPC. Such integrations don't need to live within the web framework layer, but rather connect at the level of the HTTP layer. If a more in-depth Spring integration is needed, with a messaging style RPC stack on top of HTTP/2 or other transports, I think [RSocket is the de factor answer in Spring](https://docs.spring.io/spring-framework/reference/rsocket.html#rsocket-spring).

I'm declining this issue as a result.
