### ISSUE TITLE
Support for Jackson 3 [SPR-16389]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20935]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-16389](https://jira.spring.io/browse/SPR-16389?redirect=false)** and commented

Jackson 3 is currently in development, becoming a 5.1 or 5.2 topic for us.

---

**Issue Links:**
- #19492 Support for Jackson 2.9

**Comment by rstoyanchev** [comment]
[Jackson STrategic Enhancement Proposal](https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP) wiki page.

**Comment by jhoeller** [comment]
Closing this ticket on our side since Jackson keeps doing 2.x feature releases for the time being.
