### ISSUE TITLE
@Debounce annotation for debouncing a method/api call [SPR-16396]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20942]
**[Juzer Ali](https://jira.spring.io/secure/ViewProfile.jspa?name=juzerali)** opened **[SPR-16396](https://jira.spring.io/browse/SPR-16396?redirect=false)** and commented

Debouncing requests/method-calls is a common use case which arises in lots of scenarios. ```
`@Debounce`(value=30)

```will be a useful annotation to have. I can work on implementing this if the feature request is accepted.
```

---

2 votes, 3 watchers

**Comment by snicoll** [comment]
This looks like a client-side concept, based on the few info that was shared. In the absence of a concrete justification for adding whatever feature you were trying to describe, I am going to close this.
