### ISSUE TITLE
Upgrade to Kotlin 1.3 [SPR-16399]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20945]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-16399](https://jira.spring.io/browse/SPR-16399?redirect=false)** and commented

Since Kotlin 1.3 went GA shortly after Spring Framework 5.1, let's upgrade our build to Kotlin 1.3 as of Spring Framework 5.2.

---

**Issue Links:**
- #20606 Unable to use WebTestClient with mock server in Kotlin (_**"is depended on by"**_)
- #20786 Upgrade to Kotlin 1.2
- #20936 Compatibility with JDK 10
- #22049 Upgrade to Hibernate ORM 5.4
- #21998 Support for parameter name introspection on Kotlin inline classes
- #21546 Support for kotlinx.reflect.lite

2 votes, 7 watchers

**Comment by jhoeller** [comment]
I'm upgrading to Kotlin 1.3.20 along with Hibernate ORM 5.4.1, raising the Kotlin language level to 1.2 (since language level 1.1 is deprecated in the meantime).
