### ISSUE TITLE
Use SMTP Message instead of MimeMessage to get access to setEnvelopeForm [SPR-16443]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20988]
**[Janning Vygen](https://jira.spring.io/secure/ViewProfile.jspa?name=janning)** opened **[SPR-16443](https://jira.spring.io/browse/SPR-16443?redirect=false)** and commented

When you use a MimeMessageHelper you can't set the "envelope from" only by setting a property "mail.smtp.from" for the java mail session. But this property affects every mail. It makes sense to set an variable envelope return path ([VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path)) for every message to process bounces.

com.sun.mail.smtp.SMTPMessage extends MimeMessage and is supporting setEnvelopeFrom which overrides "mail.smtp.from".

At the moment you can achieve this only by building a new MimeMessage

```java
MimeMessageHelper helper;
SMTPMessage smtpMessage = new SMTPMessage(helper.getMimeMessage());
smtpMessage.setEnvelopeFrom(verpAddress)
javaMailSender.send(smtpMessage)
```

It would be quite easy to use SMTPMessage instead of MimeMessage

---

**Affects:** 5.0.3

**Reference URL:** http://cephas.net/blog/2006/06/09/using-apache-james-and-javamail-to-implement-variable-envelope-return-paths/

**Comment by jhoeller** [comment]
Since the `SMTPMessage` class is not part of the standard JavaMail / Jakarta Mail API, I'm afraid we'll have to leave its usage up to the application.
