### ISSUE TITLE
Support W3C Push API [SPR-16441]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20987]
**[Hans Desmet](https://jira.spring.io/secure/ViewProfile.jspa?name=desmethans)** opened **[SPR-16441](https://jira.spring.io/browse/SPR-16441?redirect=false)** and commented

With the rising succes of progressive web apps
there should be server sided support for push notifications:
* support the W3C Push API (https://tools.ietf.org/html/draft-ietf-webpush-protocol-12)
* support VAPID keys.
* support GCM keys.

---

**Affects:** 5.0.3

**Comment by bclozel** [comment]
This seems to be way broader than initially advertized. This is spec is not implemented by all modern browsers, and this spec has many other related specs for managing the push service and other features.

The core design of this spec is also strongly linked with:
* A message broker that stores messages when the browser is not connected to the app
* Encryption libraries to encrypt+sign push messages when stored by the push service

With that in mind and the current lack of demand, I'm closing this issue for now. We can revisit this decision in the future. Community members can of course share their experience here with that technology and 3rd party libraries supporting this.
