### ISSUE TITLE
Update advice on contentLength() in subclasses of InputStreamResource 

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20990]
**[bademus](https://jira.spring.io/secure/ViewProfile.jspa?name=bademux)** opened **[SPR-16445](https://jira.spring.io/browse/SPR-16445?redirect=false)** and commented

It seems the bug was introduced in #16633
org.springframework.http.converter.ResourceHttpMessageConverter#getContentLength

```java
// Don't try to determine contentLength on InputStreamResource - cannot be read afterwards...
// Note: custom InputStreamResource subclasses could provide a pre-calculated content length!
if (InputStreamResource.class == resource.getClass()) {
     return null;
}
```

In fact default behavior of InputStreamResource is not the same as for its children.

---

**Affects:** 4.3.14

**Issue Links:**
- #16633 RestTemplate with InputStreamResource does not work if Content-Length is not set
- #18147 resttemplate multipart post with InputStreamResource not working

**Comment by ger0nimo** [comment]
I encountered the same problem but this code below works for me. 
`
import org.springframework.core.io.ByteArrayResource;
import org.springframework.web.multipart.MultipartFile;

public class MultipartFileResource extends ByteArrayResource {

	private String filename;
	private long contentLength;

	public MultipartFileResource(MultipartFile multipartFile) throws IOException {
		super(multipartFile.getBytes());
		this.filename = multipartFile.getOriginalFilename();
		this.contentLength = multipartFile.getSize();
	}

	@Override
	public String getFilename() {
		return this.filename;
	}
	@Override
	public long contentLength() {
		return this.contentLength;
	}
	 
}`
