### ISSUE TITLE
Segregate BasicTraceInterceptor from CustomizableTraceInterceptor  [SPR-16451]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20996]
**[Sergii Karpenko](https://jira.spring.io/secure/ViewProfile.jspa?name=seka)** opened **[SPR-16451](https://jira.spring.io/browse/SPR-16451?redirect=false)** and commented

Segregate basic trace logic from logic responsible for log message construction.
Move out invokeUnderTrace to BasicTraceInterceptor
and parametrise it with entranceConsumer, exitConsumer, exceptionConsumer.

Except of violating single responsibility principle current implementation doesn't allow me to distinguish entrance message from exit massages.

This should fix both points and also will allow to avoid of expensive replacePlaceholders calls if necessary.

---
No further details from [SPR-16451](https://jira.spring.io/browse/SPR-16451?redirect=false)

**Comment by snicoll** [comment]
There is no longer a `BasicTraceInterceptor` so I can't know for sure what, if anything, is still applicable at this time. Sorry this got overlooked.
