### ISSUE TITLE
Order of JMS TransactionSynchronizations should be sortable programmatically [SPR-16491]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21034]
**[Ludovit Varga](https://jira.spring.io/secure/ViewProfile.jspa?name=ludovit.varga)** opened **[SPR-16491](https://jira.spring.io/browse/SPR-16491?redirect=false)** and commented

Scenario:
I have application that consume message from JMS Server A, update row in database and produce messages to multiple JMS queues on different servers. This must be done in transaction and without JTA. Application is written with Spring Boot 2.0.0.M7 (with Spring 5.0.2) with data-jpa and jms starters.

Problem:
Application can't use JTA transactions (requirement from client), so I implemented [Best effort 1PC pattern](https://www.javaworld.com/article/2077963/open-source-tools/distributed-transactions-in-spring--with-and-without-xa.html?page=2). It works nicely but client needs to have specific order of commit/rollback of JMS transactions. In my case he required that outbound messages are committed first and then are committed inbound message.

When i was reading thru code and documentation i found JmsResourceSynchronization and TransactionSynchronizationManager that are in middle of this functionality.

If i understand code correctly then while triggering afterCommit, JpaTransactionManager gets list of sorted TransactionSynchronization and sorting is done with AnnotationAwareOrderComparator.sort(). My observation is that order of commit/rollback is based on order in which JMS messages was send (and registered inside TransactionSynchronizationManager).

Because most methods are static and JmsResourceSynchronization is private, only what i can currently do is ugly and unreliable workaround like this:

```java
List<TransactionSynchronization> synchronizations = TransactionSynchronizationManager.getSynchronizations();
TransactionSynchronizationManager.clearSynchronization();
TransactionSynchronizationManager.initSynchronization();
synchronizations = Lists.reverse(synchronizations);
synchronizations.forEach(TransactionSynchronizationManager::registerSynchronization);
```

If this sorting of same implementation of TransactionSynchronization (in my case JmsResourceSynchronization) can be done programmatically from `@Configuration` classes, that would be great.

---

**Affects:** 5.0.2

**Comment by snicoll** [comment]
So it's been a while and this issue hasn't draw much attention from the community. Given the use case described (best effort 1PC) I am going to close this.
