### ISSUE TITLE
Support for read through / loading caches [SPR-16503]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21046]
**[Jens Wilke](https://jira.spring.io/secure/ViewProfile.jspa?name=cruftex)** opened **[SPR-16503](https://jira.spring.io/browse/SPR-16503?redirect=false)** and commented

The cache abstraction currently operates the cache in a cache aside pattern. Operating the cache via a cache loader would make it possible to use advanced caching features, such as refresh ahead or resilience.

Right now, it is possible to "hack up" a `CacheResolver` that creates a loading cache, in case there is only a single method annotated with `Cachable` and it only has a single argument.

IMHO, the current cache abstraction would provide enough to be able to create a loading cache, however, the current Spring internals don't make it possible.

Needed:

* A concept of a `StaticCacheResolver` that is only run once at startup and gets all needed information
* A reverse mapping for `KeyGenerator` to be able to call the loading method on behalf of the cache key

Thoughts?

---
No further details from [SPR-16503](https://jira.spring.io/browse/SPR-16503?redirect=false)

**Comment by snicoll** [comment]
There has been a number of requests in that direction and we don't think this is the right fit for the cache abstraction. There is a recent discussion in https://github.com/spring-projects/spring-framework/pull/30124 that elaborates on our thinking. Thanks anyway for the suggestion.
