### ISSUE TITLE
AbstractRoutingDataSource to try to load/create a new DataSource if determineTargetDataSource can not find a DataSource for the current lookup key. [SPR-16509]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21052]
**[Razvan Popian](https://jira.spring.io/secure/ViewProfile.jspa?name=razvan77@gmail.com)** opened **[SPR-16509](https://jira.spring.io/browse/SPR-16509?redirect=false)** and commented

org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource#determineTargetDataSource will throw an exception if it can not return a DataSource for the current lookup key. This class could be modified or extended so that if there is no DataSource for the current key, one could be loaded/created. This would be useful in scenarios where new data sources are created while the program using the routing data source is running. The program would not need to be restarted if the routing data source would lazily pick up newly created data sources.
I needed this feature on a project so I created a subclass of the AbstractRoutingDataSource, I attached it to the ticket, in case it is useful to somebody. The implementation is a bit messy because it uses reflection to access certain private things in the super class.

---

**Affects:** 4.3.10

**Attachments:**
- [AbstractNewDsAwareRoutingDataSource.java](https://jira.spring.io/secure/attachment/25401/AbstractNewDsAwareRoutingDataSource.java) (_9.11 kB_)
- [LazyAbstractRoutingDataSource.java](https://jira.spring.io/secure/attachment/25760/LazyAbstractRoutingDataSource.java) (_2.08 kB_)

1 votes, 3 watchers

**Comment by snicoll** [comment]
`AbstractRoutingDataSource` is really meant to work against a preset of existing datasources. Allowing datasources to be created on-the-fly has obvious concurrency problem that the current implementation doesn't handle at this time. We'd be open to open the contract a bit to offer more flexibility, but without dealing the concurrency bit I doubt it would be much useful.
