### ISSUE TITLE
Allow runtime detection of CGLib proxying VS. JDK proxying for different parts of the framework [SPR-16532]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21075]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[SPR-16532](https://jira.spring.io/browse/SPR-16532?redirect=false)** and commented

The change in Spring Boot 2.0's default proxying behavior (defaulting to CGLib proxies), prevents it to actually consider user configuration explicitly using e.g. `@EnableTransactionManagement(proxyTargetClass = false)` as they all end up in the registration of the `org.springframework.aop.config.internalAutoProxyCreator` bean. This would cause the singular use of e.g. `@ETM(pTC=true)` to disable the Boot default for all cases that – according to Boot's default – use proxying (general AOP, caching etc.).

It would be cool if there was a way for downstream projects to find out about for which part of the framework a particular proxy setting was activated explicitly, so that Boot can apply its default to all others. I guess another option would be to allow the default to be used in the framework to be configured externally, so that Boot could just forward the flag and would not have to consider the exclusions itself.

The effect of the current state of affairs is that you can have a Boot 2.0 application with e.g. transactions explicitly configured to use JDK proxies but Boot's default still trumping this. This is particularly worrying as it's AFAIK the only situation in which user configuration does not trump Boots defaults. Additionally, the Spring Framework log output in erroneous scenarios (e.g. the class to be proxied using final methods) hints at enabling JDK proxies, which is exactly what the user configuration does. This leaves users with hard to diagnose configuration issues.

---

**Affects:** 4.3.14, 5.0.4

**Comment by snicoll** [comment]
> If I now inspect my configuration and find @EnableTransactionManagement(proxyTargetClass = false) being configured explicitly, I think: "That's exactly what I have running." I now then have to find out that in contrast to every other area of Boot defaulting, it doesn't consider my explicit Spring Framework configuration and overrides it with it's own default.

Irrespective of Spring Boot, that configuration does not enforce in any way the use of Java-interface based proxies. Such configuration with a plain Spring Framework app would resort to Cglib proxies if the target class does not implement a relevant interface, for instance. 

@jhoeller and I discussed several options, including a global switch and deprecating the `proxyTargetClass` property, and we decided to keep things as they are.
