### ISSUE TITLE
Update Spring Annotation Programming Model to reflect status quo [SPR-16575]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21117]
**[Sam Brannen](https://jira.spring.io/secure/ViewProfile.jspa?name=sbrannen)** opened **[SPR-16575](https://jira.spring.io/browse/SPR-16575?redirect=false)** and commented

#### Overview

The [Spring Annotation Programming Model](https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model) has become a bit outdated due to changes in Spring 4.3 and 5.0.

#### Deliverables

- Update the _Spring Annotation Programming Model_ wiki page to reflect the status quo.
  - specifically removing references to obsolete annotations in the _Spring Composed_ project.

---

**Affects:** 5.0 GA

**Issue Links:**
- #16140 Document Spring Annotation Programming Model in the Wiki
- #21118 Document `@Autowired` support on method parameters

**Comment by sbrannen** [comment]
Closing this issue since the main focus was already addressed in June 2018.
