### ISSUE TITLE
`ResourceDatabasePopulator` should ignore MySQL single-line comments in SQL scripts by default [SPR-16594]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21135]
**[Urs Wiss](https://jira.spring.io/secure/ViewProfile.jspa?name=urswiss)** opened **[SPR-16594](https://jira.spring.io/browse/SPR-16594?redirect=false)** and commented

In MySQL, starting a line with a hash key is a valid comment (see https://dev.mysql.com/doc/refman/5.7/en/comments.html)

Currently, ResourceDatabasePopulator doesn't recognize lines starting with a hash key as comments. See the example https://github.com/urswiss/spring-jdbc-comment, it's based on h2 but it nonetheless illustrates the point I think.

---
No further details from [SPR-16594](https://jira.spring.io/browse/SPR-16594?redirect=false)

**Comment by prateekkapoor** [comment]
Can I pick this up?

**Comment by prateekkapoor** [comment]
I was facing this issue with spring for prepopulating data  in database. After analyzing sprring code I figured out that it can be fixed by adding "#" to DEFAULT_COMMENT_PREFIXES in ScriptUtils class.

Let me know if this correct approach and I can take this up.

**Comment by sbrannen** [comment]
> After analyzing spring code I figured out that it can be fixed by adding "#" to DEFAULT_COMMENT_PREFIXES in ScriptUtils class.
> 
> Let me know if this correct approach and I can take this up.

Yes, that would be the correct approach; however, doing so may be a breaking change for users whose SQL scripts utilize `#` for a different purpose.

So please hold off on submitting a PR until the team has decided if we want to make this change.
