### ISSUE TITLE
Spring JSTL form tag removes context path if servletRelativeAction starts with context path [SPR-16617]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21158]
**[Brett Ryan](https://jira.spring.io/secure/ViewProfile.jspa?name=brett.ryan)** opened **[SPR-16617](https://jira.spring.io/browse/SPR-16617?redirect=false)** and commented

Using the spring jstl form tag attribute `servletRelativeAction` with a value that starts with the context path strips off this from the value rendered.

# Steps to Reproduce

1. Create a new webapp deployed at location `/foo` with a spring MVC context mapped to `/`
2. Create a form JSP using the following content
```html
   <%@ page pageEncoding="UTF-8" trimDirectiveWhitespaces="true" %>
   <%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
   <form:form servletRelativeAction="/foo/my-action" method="POST">
   </form:form>
   <form:form servletRelativeAction="/bar/my-action" method="POST">
   </form:form>
```
3. Create a mapping to the above form and observe the output.

# Expected Behavior

Form should render as follows:

```html 
<form id="command" action="/foo/foo/my-action" method="POST">
</form>
<form id="command" action="/foo/bar/my-action" method="POST">
</form>
```

## Actual Behavior

Form is actually rendered without the leading context path for the first form entry:

```html
<form id="command" action="/foo/my-action" method="POST">
</form>
<form id="command" action="/foo/bar/my-action" method="POST">
</form>
```

# Workaround

Do not use the spring JSTL form implementation and instead use `<c:url value="/"/>` to provide the output context path.

```html
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<form action="<c:url value="/foo/my-action"/>" method="POST">
</form>
```

Alternatively using the spring `<form:form>` implementation use the `action` attribute by providing the pageContext's context path:

```html
<form:form action="${pageContext.request.contextPath}/foo/my-action" method="POST">
</form:form>
```

---

**Affects:** 5.0.4

**Comment by snicoll** [comment]
The Javadoc for `servletRelativeAction` states:

> Action reference to be appended to the current servlet path.

`/foo` shouldn't be added there as it should be the relative action.
