### ISSUE TITLE
Composed MessageSource [SPR-16614]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21155]
**[Dmytro Nosan](https://jira.spring.io/secure/ViewProfile.jspa?name=dnosan)** opened **[SPR-16614](https://jira.spring.io/browse/SPR-16614?redirect=false)** and commented

Sometimes to localize some bean we have to use several sources. e.g.

```java
MessageSource m1 = db.getTranslations()
MessageSource m2 = someService.getTranslations();
```

and then we will use a custom method for localizing

```java
private String translate(MessageSource m1, MessageSource m2, String code, Locale locale) {
		try {
			return m1.getMessage(code, null, locale);
		} catch (NoSuchMessageException ex) {
			return m2.getMessage(code, null, locale);
		}
	}
```

But this method has several disadvantages:
1. If m1 has (useCodeAsDefaultMessage) we will never get a message from m2.
2. A lot of exceptions could be thrown
3. What would we do, if we need one or more MessageSource(s)?

My idea is to create a new ComposedMessageSource class which should handle:
1. Resolve message from both MessageSources
2. Resolve situation when one of the MessageSources has a property **useCodeAsDefaultMessage** (we should find the best option for localization)
3. Unnecessary exception generation

also, it would be great to have a utility class for composing MessageSources.

```java
public abstract class MessageSources {
	@Nullable
	public static MessageSource compose(@Nullable MessageSource messageSource, @Nullable MessageSource parentMessageSource){
...
}
```

---

**Affects:** 5.0.4

**Attachments:**
- [ComposedMessageSource.java](https://jira.spring.io/secure/attachment/25429/ComposedMessageSource.java) (_4.30 kB_)
- [ComposedMessageSourceTests.java](https://jira.spring.io/secure/attachment/25424/ComposedMessageSourceTests.java) (_5.75 kB_)
- [MessageSource.java](https://jira.spring.io/secure/attachment/25428/MessageSource.java) (_3.86 kB_)
- [MessageSources.java](https://jira.spring.io/secure/attachment/25425/MessageSources.java) (_1.28 kB_)
- [MessageSourcesTest.java](https://jira.spring.io/secure/attachment/25423/MessageSourcesTest.java) (_686 bytes_)

**Comment by snicoll** [comment]
I believe this is more natural to use a hierarchy rather than the composite. Besides there hasn't been a lot of traction for this request so I am going to close it. Thanks for the suggestion, in any case!
