### ISSUE TITLE
Add "secure" attribute to RequestMapping annotation [SPR-16676]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21217]
**[Joshua White](https://jira.spring.io/secure/ViewProfile.jspa?name=joshuawhite929)** opened **[SPR-16676](https://jira.spring.io/browse/SPR-16676?redirect=false)** and commented

I have a use case where I only want to have a controller handle a request if the request is over a secure channel.  For this use case, secure and insecure requests are both valid and need to be handled differently.

Adding "secure" attribute, possible with an Enum indicating true/false to the RequestMapping would allow me to do this in a declarative way rather than having to check the servletRequest  (ex. servletRequest.isSecure()) for this attribute directly.

If this seems reasonable, I'd like to discuss the approach and submit a pull request.

---

**Affects:** 5.0.4

**Comment by rstoyanchev** [comment]
Closing for now as there hasn't been much interest.
