### ISSUE TITLE
NoSuchBeanDefinitionException when bean is created throught a factory which retuns a super type of bean [SPR-16694]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21235]
**[Osvaldo Pina](https://jira.spring.io/secure/ViewProfile.jspa?name=osvado.pina)** opened **[SPR-16694](https://jira.spring.io/browse/SPR-16694?redirect=false)** and commented

The problem appears when:
1-The bean and bean factory are registered through an ImportBeanDefinitionRegistrar
2-A bean is created through a factory that returns a bean supertype
3-The reference required to be injected is any subtype of factory method return
4-The bean instance is not created when the injection search happens

Upon inspecting what was happening, I discovered that the AbstractAutowireCapableBeanFactory.determineTargetType method sets the resolvedTargetType to be the value returned by the bean factory, without considering that the actual bean type could be a subtype of it.

```java
	protected Class<?> determineTargetType(String beanName, RootBeanDefinition mbd, Class<?>... typesToMatch) {
		Class<?> targetType = mbd.getTargetType();
		if (targetType == null) {
			targetType = (mbd.getFactoryMethodName() != null ?
					getTypeForFactoryMethod(beanName, mbd, typesToMatch) :
					resolveBeanClass(mbd, beanName, typesToMatch));
			if (ObjectUtils.isEmpty(typesToMatch) || getTempClassLoader() == null) {
				mbd.resolvedTargetType = targetType;
			}
		}
		return targetType;
	}

```

The problem only occurs if the bean search occurs before the bean instance is created because the AbstractAutowireCapableBeanFactory.doCreateBean sets the resolvedTargetType as the actual instance type.

```java
		...
		if (beanType != NullBean.class) {
			mbd.resolvedTargetType = beanType;
		}
		...

```

if this is actually confirmed as a bug a possible solution would be to consider both the bean class and the factory class in determining the bean's final class

```java
protected Class<?> determineTargetType(String beanName, RootBeanDefinition mbd, Class<?>... typesToMatch) {
		Class<?> targetType = mbd.getTargetType();
		if (targetType == null) {
			targetType = getBeanType(beanName,
					resolveBeanClass(mbd, beanName, typesToMatch),
					mbd.getFactoryMethodName() != null ? getTypeForFactoryMethod(beanName, mbd, typesToMatch) : null);

			if (ObjectUtils.isEmpty(typesToMatch) || getTempClassLoader() == null) {
				mbd.resolvedTargetType = targetType;
			}
		}
		return targetType;
	}

	private Class<?> getBeanType(String beanName, Class<?> beanType, Class<?> beanFactoryType) {

		if (beanType == null && beanFactoryType == null) {
			return null;
		}
		else if (beanType != null && beanFactoryType != null) {
			if (!beanType.isAssignableFrom(beanFactoryType) && !beanFactoryType.isAssignableFrom(beanType)) {
				throw new BeanCreationException(beanName, " bean type ["  + beanType.getName() +
						"] that is incompatible with bean factory type [" + beanFactoryType + "}");
			}
			else {
				return beanType;
			}
		}
		else {
			return beanType != null ? beanType : beanFactoryType;
		}

	}

```

Threre are 2 unit tests atteached that shows the problem

---

**Affects:** 4.3.15, 5.0.4

**Attachments:**
- [bug-spring.zip](https://jira.spring.io/secure/attachment/25466/bug-spring.zip) (_16.91 kB_)

**Comment by snicoll** [comment]
Declaring the most specific type is really what you should be doing. Even more so with modern Spring where that information can be used to optimize an application context ahead of time.
