### ISSUE TITLE
SimpleJdbcCall with rowMapper set fails on execution (on Postgres) [SPR-16709]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21250]
**[Ivan Vasilev](https://jira.spring.io/secure/ViewProfile.jspa?name=ivan.vasilev)** opened **[SPR-16709](https://jira.spring.io/browse/SPR-16709?redirect=false)** and commented

Further to my previous issue #21152.

spring-jdbc: 4.3.15
org.postgresql:postgresql: 9.4.1212.jre7

I've got 4.3.15 yesterday. And tested it with demo project which I attached to #21152. Test passes, so issue is resolved, thank you.

I wrote a stored function that returns a table row. When I call it returning a map of values, everything works properly. But when I set **jdbcCall.returningResultSet("resultvalue", rowMapper)**, something goes wrong:

> org.springframework.jdbc.BadSqlGrammarException: CallableStatementCallback; bad SQL grammar [{? = call find_customer(?, ?)}]; nested exception is org.postgresql.util.PSQLException: A CallableStatement function was executed and the out parameter 1 was of type java.sql.Types=4 however type java.sql.Types=1111 was registered.
> at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:140)
> at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:157)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
> at com.sun.proxy.$Proxy90.execute(Unknown Source)
> at org.springframework.jdbc.core.JdbcTemplate$6.doInCallableStatement(JdbcTemplate.java:1144)
> at org.springframework.jdbc.core.JdbcTemplate$6.doInCallableStatement(JdbcTemplate.java:1141)
> at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1089)
> at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1141)
> at org.springframework.jdbc.core.simple.AbstractJdbcCall.executeCallInternal(AbstractJdbcCall.java:406)
> at org.springframework.jdbc.core.simple.AbstractJdbcCall.doExecute(AbstractJdbcCall.java:366)
> at org.springframework.jdbc.core.simple.SimpleJdbcCall.execute(SimpleJdbcCall.java:197)
> at com.example.demo.DemoApplicationTests.callProcedureReturningResultSetWithRowMapper(DemoApplicationTests.java:54)

I attach the sample project below.

---

**Affects:** 4.3.15

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/25473/demo.zip) (_5.50 kB_)

**Issue Links:**
- #21152 CallMetaDataContext.reconcileParameters doesn't catch output parameters with DatabaseMetaData.procedureColumnResult type (on Postgres)

**Comment by adolin-negash** [comment]
Hello everyone.
I got same issue, when tried to call postgress function. Watch my [stackoverflow.com question](https://stackoverflow.com/questions/68217912/faild-to-call-postgress-function-with-spring-simplejdbccall)

**Comment by snicoll** [comment]
Thanks for the sample. Upgrading to a recent version of the framework and postgres, this leads to:

```
org.springframework.dao.InvalidDataAccessApiUsageException: Required input parameter 'id' is missing

	at org.springframework.jdbc.core.CallableStatementCreatorFactory$CallableStatementCreatorImpl.createCallableStatement(CallableStatementCreatorFactory.java:207)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1186)
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1246)
	at org.springframework.jdbc.core.simple.AbstractJdbcCall.executeCallInternal(AbstractJdbcCall.java:412)
	at org.springframework.jdbc.core.simple.AbstractJdbcCall.doExecute(AbstractJdbcCall.java:372)
	at org.springframework.jdbc.core.simple.SimpleJdbcCall.execute(SimpleJdbcCall.java:198)
```

I believe this should be fixed by https://github.com/spring-projects/spring-framework/issues/31550. We can get back to this problem once we've made progress there.

**Comment by snicoll** [comment]
I was wrong. I did investigate this a bit more but the function in the sample doesn't return a `ResultSet` so even if we change that flag, it doesn't fix the issue. I don't know enough about postgres to adapt the sample.  If someone  can then we can reopen this issue.

**Comment by snicoll** [comment]
@adolin-negash I've also tried to run your sample but didn't manage to get postgres to return a `ResultSet`. If you can attach a sample we can run, this can be reconsidered.
