### ISSUE TITLE
LazyResolutionMessage does not implement proper toString

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21265]
**[John](https://jira.spring.io/secure/ViewProfile.jspa?name=john.dorien)** opened **[SPR-16724](https://jira.spring.io/browse/SPR-16724?redirect=false)** and commented

When JMS listerner configured in spring reads JMS from queue/topic it can log the message just by enabling corresponding logger.
For produced (outgoing) messages it works without problem.
For consumed (incoming) messages logging is done by [MessagingMessageListenerAdapter](https://github.com/spring-projects/spring-framework/blob/19d311dcb251474dfaf731a83ba9a5b53b191068/spring-jms/src/main/java/org/springframework/jms/listener/adapter/MessagingMessageListenerAdapter.java#L75)  in method: onMessage but it is logged after transformation to MessagingMessage which is by default LazyResolutionMessage which means it breaks logging as no payload or headers are logged from this message class.
Is there some easy way to log messages and avoud this lazy message?

---

**Affects:** 4.3.10, 5.0.5

**Comment by snicoll** [comment]
Thanks for the report. Yes, I can see how that's really annoying that the toString doesn't log the message properly. I've scheduled it for 6.x
