### ISSUE TITLE
RSocket client and server support [SPR-16751]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21292]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-16751](https://jira.spring.io/browse/SPR-16751?redirect=false)** and commented

[RSocket](http://rsocket.io/) is a protocol for multiplexed streams comparable to gRPC in terms of interaction models, but transport independent (TCP, WebSockte, HTTP/2, Aeron) and with protocol-level support for Reactive Streams back pressure, among other unique features. RSocket does have multi-language client and server support but does not have built-in rpc-style code generation.

The [rsocket-java](https://github.com/rsocket/rsocket-java) project is built on Reactor Netty and Reactor Core, so the programming model and technology stack is closely aligned with WebFlux.

This ticket is to provide client and server RSocket support for Spring applications.

---

**Affects:** 5.0.5

**Sub-tasks:**
- #21987 Reactive infrastructure for annotated method invocation in spring-messaging

**Issue Links:**
- #20905 Provide gRPC support

14 votes, 26 watchers

**Comment by rstoyanchev** [comment]
Initial support available in master (and 5.2 snapshots), see [integration tests](https://github.com/spring-projects/spring-framework/tree/master/spring-messaging/src/test/java/org/springframework/messaging/rsocket).
