### ISSUE TITLE
Spring MVC in runtime fails when the locale is changed according with BCP 47 [SPR-16775]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21315]
**[Manuel Jordan](https://jira.spring.io/secure/ViewProfile.jspa?name=dr_pompeii)** opened **[SPR-16775](https://jira.spring.io/browse/SPR-16775?redirect=false)** and commented

I have the following infrastructure:

```java
@Bean
public LocaleChangeInterceptor localeChangeInterceptor(){
	LocaleChangeInterceptor localeChangeInterceptor = new LocaleChangeInterceptor();
	localeChangeInterceptor.setParamName("language");
	return localeChangeInterceptor;
}

@Bean(name="localeResolver")
public LocaleResolver cookieLocaleResolver(){
	CookieLocaleResolver cookieLocaleResolver = new CookieLocaleResolver();
	cookieLocaleResolver.setCookieName("language");
	cookieLocaleResolver.setDefaultLocale(Locale.forLanguageTag("en-US"));
	return cookieLocaleResolver;
}
```

I have confirmed that in `runtime` the following works:

(A): `[http://localhost:8080/thymeleaf-02/locale/changelocale?language=es_ES]`
Observe that the URL uses `_`, and the app works.

(B) `[http://localhost:8080/thymeleaf-02/locale/changelocale?language=es-ES]`
Observe that the URL uses `-`, and the app fails with:

```
HTTP Status 500 – Internal Server Error
Type Exception Report

Message Request processing failed; nested exception is java.lang.IllegalArgumentException: Locale part "es-ES" contains invalid characters

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Locale part "es-ES" contains invalid characters
	
...

Root Cause

java.lang.IllegalArgumentException: Locale part "es-ES" contains invalid characters
	org.springframework.util.StringUtils.validateLocalePart(StringUtils.java:817)
```

According with my experience in: #20999

Is valid use - and not _. Currently my `@Test` methods pass with `-` but fails in `runtime`.
Is it a bug? Or missing configuration? Because I think `runtime` and `testing` should have the same behavior.

I know that `BCP 47` for this case is about the `Accept-Language` header and the URL is working through a parameter. But I hope you see my point.

Not sure if it is the expected behavior, but could be confuse for the developer.

Thank You.

---

**Affects:** 5.0.4

**Issue Links:**
- #20999 MockHttpServletRequest.addHeader fails for invalid LanguageRange in Accept-Language

**Comment by charly077** [comment]
We have a similar issue with release 2.0.6.RELEASE. Is it fixed on the newest version?

**Comment by sbrannen** [comment]
Since Spring Framework 5.1, this should no longer be an issue (see commit 88e4006790dccbabc0ee).

From Spring Framework 4.3 to 5.0, you would need to set the `languageTagCompliant` property of `LocaleChangeInterceptor` to `true` for BCP 47 compliance (see commit 0dd320f92e31d516df9c5f).

I am therefore closing this issue.

However, if you find that the above is not the case, please add a comment here with details.
