### ISSUE TITLE
Support wildcard patterns in @PropertySource locations [SPR-16785]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21325]
**[Pratapi Hemant Patel](https://jira.spring.io/secure/ViewProfile.jspa?name=hemantsonu20@gmail.com)** opened **[SPR-16785](https://jira.spring.io/browse/SPR-16785?redirect=false)** and commented

Currently `@PropertySource` supports only absolute path

```java
@PropertySource("classpath:prod/a.properties") // supported
```

But regex are not supported.

```java
@PropertySource("classpath:prod/*.properties") // not supported
```

---

**Affects:** 4.3.16

**Reference URL:** https://stackoverflow.com/questions/50079355/add-all-properties-in-a-given-resources-folder-to-springs-environment-class

**Comment by tiagotds** [comment]
Any update regarding this subject?
