### ISSUE TITLE
LiveBeansView is not really fit for purpose any more [SPR-16787]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21327]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-16787](https://jira.spring.io/browse/SPR-16787?redirect=false)** and commented

I wanted to try and visualize the object graph. Various options exist, but the only ones that work rely on the LiveBeansView that comes from spring-context (also exposed by Spring Boot as an endpoint, which is used by all the viable visualization tools I found). Unfortunately, I think a modern Spring Boot application has too many beans that are not obviously dependent on one another according to the LiveBeansView, even though they clearly are. Probably this feature used to work  when all your beans were declared explicitly in XML files. Now that we have `@Configuration` and auto-configuration the same rules do not apply.

 

The quickest way to see the problem is probably with STS if you have it. Run an app in the Boot dashboard and open its "Properties" view. It renders the LiveBeansView as a tree (which isn't very helpful anyway, but that's a different story). Browse through it and you will see dozens of beans that are unconnected to anything else. E.g. `@Configuration` classes do not have an imprint of the beans they created.

 

Perhaps we can add more data to the LiveBeansView, either in the existing fields ("links" etc.) or in some new fields that express the changes that seem to have taken place?

---

**Affects:** 4.3.16

**Attachments:**
- [2018-05-02-103154_1368x768_scrot.png](https://jira.spring.io/secure/attachment/25705/2018-05-02-103154_1368x768_scrot.png) (_326.78 kB_)

**Issue Links:**
- #21438 LiveBeansView should support double quotes in application context id

**Comment by sdeleuze** [comment]
Based on recent discussions, I think we are not going to evolve `LiveBeansView`. Indeed Boot is not using it anymore, only STS does for non Boot apps, so I think it is reasonable to close this issue.

**Comment by dsyer** [comment]
I disagree. I do not mourn the passing of LiveBeansView, but I would like to have some high-quality metadata. Is there a better place to discuss that?

**Comment by sdeleuze** [comment]
I don't question the need, I just say `LiveBeansView` is likely to be deprecated and that the need should be discussed at another level, likely on Boot actuator side.

**Comment by bclozel** [comment]
Should we use this issue instead to deprecate `LiveBeansView` then?

**Comment by sdeleuze** [comment]
@bclozel I have chosen to create a dedicated issue for that since the original purpose of this issue is different and could cause potentially some confusion.
