### ISSUE TITLE
Get the last element from "LinkedMultiValueMap" [SPR-16792]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21332]
**[Md](https://jira.spring.io/secure/ViewProfile.jspa?name=nanofaroque04)** opened **[SPR-16792](https://jira.spring.io/browse/SPR-16792?redirect=false)** and commented

Currently, we can get the first element of list by using the Key but there is no way to get the last element. 

---

**Affects:** 5.0.5

**Reference URL:** https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/LinkedMultiValueMap.java

**Comment by DeCaMil** [comment]
There's not a way to directly get the last element, but the get(K key) returns the List<V> that can then be used to access any element in the list.

**Comment by sbrannen** [comment]
> There's not a way to directly get the last element, but the get(K key) returns the List that can then be used to access any element in the list.

That's correct.

@nanofaroque, can you elaborate on the use case you have for accessing the last element of the list?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
