### ISSUE TITLE
Allow creation of immutable collections through CollectionFactory [SPR-16797]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21337]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[SPR-16797](https://jira.spring.io/browse/SPR-16797?redirect=false)** and commented

Modelling application classes as immutable objects is a widely used pattern in Java and Kotlin which constantly gains adoption. We should allow creation of immutable collection types (`Map`, `List`, `Set`) through `CollectionFactory` or an adequate API that allows specification of the target type and the elements the result should contain.

It would be great to support:
* Java 9 immutable collections
* Google Guava collections
* Vavr Collections (previously JavaSlang)

 

---

**Issue Links:**
- [DATACMNS-1381](https://jira.spring.io/browse/DATACMNS-1381) Support for immutable collection types

2 votes, 7 watchers

**Comment by snicoll** [comment]
Checking with @mp911de, there's nothing that's needed from their side for this and we don't want to expand the scope further.
