### ISSUE TITLE
Use "internalSet" instead of normal setter. [SPR-16809]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21349]
**[Zhang Jie](https://jira.spring.io/secure/ViewProfile.jspa?name=nkjackzhang)** opened **[SPR-16809](https://jira.spring.io/browse/SPR-16809?redirect=false)** and commented

Using "internalSet" instead of normal setter can avoid checking int param, because if **constants.asNumber()** works as expected and does't throw exception, the param checking in normal setter will never fail.

---

**Affects:** 5.0.6

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1825

**Comment by snicoll** [comment]
You are correct but the delegation is to make sure that there is a single place that mutates the parameter. In practice, the optimization is not worth the additional code.
