### ISSUE TITLE
Capitalize strings with the correctly implementation [SPR-16827]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21367]
**[Allan Garcez](https://jira.spring.io/secure/ViewProfile.jspa?name=vandalvnl)** opened **[SPR-16827](https://jira.spring.io/browse/SPR-16827?redirect=false)** and commented

Hey everyone, 

I am a brazilian student and decide to use Spring as my main framework to developer my API's, so I find an inconsistency in StringUtils.capitalize. This method only capitalize the first letter of first word in string, when the "correctly way" is capitalize all first letter in all words (like in CSS text-transform property). So, I decide to code a solution for this, and add methods to my class sugestion. 

 

All unit tests in project are aprove and I hope you will accept and implement this class to the Spring ecosystem 

---

**Reference URL:** https://github.com/vandalvnl/capitalize-utils

**Comment by poutsma** [comment]
The goal of `StringUtils` is to provide string methods for internal use within the framework. And for our purposes, the current way `capitalize` work suffices.
