### ISSUE TITLE
When adding @ExceptionHandler for java.lang.Exception, handlers for nested exceptions stop working [SPR-16875]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21414]
**[Stanislav Bytsko](https://jira.spring.io/secure/ViewProfile.jspa?name=zbstof)** opened **[SPR-16875](https://jira.spring.io/browse/SPR-16875?redirect=false)** and commented

Consider Controller:

```
@GetMapping
public ResponseEntity doNastyStuff() throws Exception {
    throw new MyOuterException("Unexpected", new MyInnerException("Expected"));
}
```

and Controller Advice:

```
@ExceptionHandler
public ResponseEntity<String> handleInner(MyInnerException exception) {
    return status(I_AM_A_TEAPOT).body(exception.getMessage());
}
```

When get mapping is invoked, MyOuterException is thrown, but is caught in advice as MyInnerException and HTTP 418 is returned
But, if we add second, catch-all `@ExceptionHandler`:

```
@ExceptionHandler
public ResponseEntity<String> handleGeneric(Exception exception) {
    return status(INTERNAL_SERVER_ERROR).body(exception.getMessage());
}
```

... then invoking our controller will return 500, which is unexpected and requires us to implement workarounds in order to handle MyInnerException, like the following additional exception handler:

```
@ExceptionHandler
public ResponseEntity<String> handleOuter(MyOuterException exception) {
    if (getMostSpecificCause(exception) instanceof MyInnerException) {
        return status(I_AM_A_TEAPOT).body(getMostSpecificCause(exception).getMessage());
    } else {
        return status(INTERNAL_SERVER_ERROR).body(exception.getMessage());
    }
}
```

Moreover, if we modify controller to return deeply nested exception:

```
@GetMapping
public ResponseEntity doNastyStuff() throws Exception {
    throw new MyOuterException("Unexpected Outer", new MyMiddleException("Unexpected Middle", new MyInnerException("Expected")));
}
```

... then original `handleInner` exception handler stops working, even when no `handleGeneric` is present, so workaround is pretty much required

I think this behaviour is counter-intuitive, and all exceptions should be handled, no matter how deep in the chain of exception causes they are contained. Moreover, chain of exceptions should be parsed from deepest to shallowest, as usually root cause is the most specific one, and the one at the surface is the broadest

---

**Affects:** 5.0.6

**Comment by mvol** [comment]
I just stumbled upon the same problem but was able to resolve it by moving the fallback handler (`@ExceptionHandler({Exception.class})`) to a separate `@ControllerAdvice` class with a lower `@Order` than the specific exception handlers.

**Comment by rstoyanchev** [comment]
The current rules are that matching is based on outer exceptions in round one, and if that produces no matches, then we continue to try in additional rounds, one cause at a time. This is relatively simple and predictable. If this were collapsed into a single round, it would make it difficult to reason about and unpredictable. For example, an outer exception (of interest) that happens to wrap an IOException cause (not of interest).

One option is an `@ExceptionHandler` that takes an outer exception and then handles potential causes. That's predictable and don't see it as cumbersome.

Another option, if you have more general catch-all type handlers is to separate them in their own `@ControllerAdvice` with a higher order value as @mvol suggested.
