### ISSUE TITLE
LiveBeansView should support double quotes in application context id [SPR-16899]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21438]
**[Konstantin Aleev](https://jira.spring.io/secure/ViewProfile.jspa?name=kaleev)** opened **[SPR-16899](https://jira.spring.io/browse/SPR-16899?redirect=false)** and commented

result.append("{\n\"context\": \"").append(context.getId()).append("\",\n"); in org.springframework.context.support.LiveBeansView.generateJson(Set\<ConfigurableApplicationContext>) creates invalid JSON if context id already has double quotes.

 

The problem could be reproduced by assigning some string with double quotes to 'spring.application.name' in Spring Boot application.

---

**Affects:** 5.0.6

**Issue Links:**
- #18773 LiveBeansView doesn't contain singletons registered programmatically
- #21327 LiveBeansView is not really fit for purpose any more

**Comment by sbrannen** [comment]
Closing since `LiveBeansView` is now deprecated (see #25820).
