### ISSUE TITLE
Add JDBC SqlValue classes for arrays [SPR-16904]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21443]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[SPR-16904](https://jira.spring.io/browse/SPR-16904?redirect=false)** and commented

We are looking at converting some of our inlist usage to SQL arrays. We were a bit surprised that using arrays with `JdbcTemplate` requires implementing a custom `SqlValue`.

We propose introducing two classes.

- An abstract base class that binds and frees the array but that leaves creating the array to a concrete subclass.
- A concrete subclass that creates the array using `Connection.createArrayOf(String, Object[])`

The reason for this is that users might want to or may even have to use vendor extensions for creating arrays. We know of two such vendor extensions that might be interesting:

- Oracle requires using a vendor method to create an array as Oracle does not support anonymous arrays.
- PostgreS offers a vendor method for creating arrays from arrays of primitive arrays, therefore eliminating the need for boxing.

We do not propose to include subclasses for them.

Potentially, for convenience reasons `java.util.Collection` types could also be supported, for now we decided against this.

---

**Affects:** 5.0 GA

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1850

**Comment by bclozel** [comment]
Closing in favor of #1850
