### ISSUE TITLE
Use non-deprecated interfaces in HibernateJpaVendorAdapter [SPR-16916]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21455]
**[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum)** opened **[SPR-16916](https://jira.spring.io/browse/SPR-16916?redirect=false)** and commented

The `HibernateJpaVendorAdapter` pre-defines the values for the `entityManagerInterface` and `entityManagerFactoryInterface`.

The current values reference deprecated interfaces (on Hibernate 5.2) and the Hibernate team suggests to use `SessionFactory` and `Session` instead as those now extend `EntityManagerFactory` and `EntityManager`.

Current values

```
this.entityManagerFactoryInterface = org.hibernate.jpa.HibernateEntityManagerFactory.class;
this.entityManagerInterface = org.hibernate.jpa.HibernateEntityManager.class;
```

Suggested values

```
this.entityManagerFactoryInterface = org.hibernate.SessionFactory.class;
this.entityManagerInterface = org.hibernate.Session.class;
```

---

**Affects:** 5.0.6

**Comment by jhoeller** [comment]
This got addressed for 5.3 M2, along with #25533.
