### ISSUE TITLE
EnableAsync breaks load order of beans [SPR-16919]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21458]
**[Björn Eickvonder](https://jira.spring.io/secure/ViewProfile.jspa?name=eicki)** opened **[SPR-16919](https://jira.spring.io/browse/SPR-16919?redirect=false)** and commented

We use Spring 4.3.17.RELEASE and started using the EnableAsync annotation.

But just adding this to a single configuration class breaks our application. At the same time we include a ConversionServiceFactoryBean to enable mapping String values in configuration to Set\<String> in a bean. This works perfect, but once we add EnableAsync the ConversionServiceFactoryBean is created to late.

I traced the problem down to the following
* The ProxyAsyncConfiguration defines a bean of type AsyncAnnotationBeanPostProcessor
* The AbstractAsyncConfiguration uses Autowired to setConfigurers

```java
/**
 * Collect any {@link AsyncConfigurer} beans through autowiring.
 */
@Autowired(required = false)
void setConfigurers(Collection<AsyncConfigurer> configurers) {
  ...
}
```

And this is somehow breaking the order how beans are instantiated, if I remove the Autowiring here it works again.

---

**Affects:** 4.3.17

**Comment by snicoll** [comment]
Sorry this got overlooked. This has been fixed in the meantime, see #21559
