### ISSUE TITLE
JMS message listener container hangs after runningAllowed() returns false [SPR-16928]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21467]
**[Simon Lindhén](https://jira.spring.io/secure/ViewProfile.jspa?name=cadmium)** opened **[SPR-16928](https://jira.spring.io/browse/SPR-16928?redirect=false)** and commented

When using [AbstractJmsListeningContainer#runningAllowed](https://docs.spring.io/autorepo/docs/spring-framework/3.2.8.RELEASE/javadoc-api/org/springframework/jms/listener/AbstractJmsListeningContainer.html#runningAllowed()) to disable a listener it hangs on `lifecycleMonitor.wait()` in `DefaultMessageListenerContainer.AsyncMessageListenerInvoker.executeOngoingLoop()` and never wakes up. This means that `runningAllowed()` will never be called again so the listener can't be re-enabled.

---

**Affects:** 5.0.6

**Comment by snicoll** [comment]
I am afraid that there isn't enough information for us to investigate this, perhaps [this comment](https://github.com/spring-projects/spring-framework/issues/8575#issuecomment-453321822) helps clarifying how the flag should be used. If you can share a sample that showcases how you're customizing the container's `runningAllowed` method, we can reconsider.
