### ISSUE TITLE
Bean Validation API 2.0 does not work with Kotlin in MVC [SPR-16923]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21462]
**[Ankur Pathak](https://jira.spring.io/secure/ViewProfile.jspa?name=ankur%20pathak)** opened **[SPR-16923](https://jira.spring.io/browse/SPR-16923?redirect=false)** and commented

class Name : Serializable

{ `@NotBlank` var value: String? = null }

class Names

{ `@NotEmpty` var names: MutableList<`@Valid` `@NotNull` Name>? = null }

Bean Validation 2 constrains `@Valid` `@NotNull` does not work on Generics  Type Param in Kotlin with Spring Web MVC.

But if you replace kotlin Names class with java version of same it works.

public class Names {

`@NotEmpty`
private List<`@NotNull` `@Valid` Name> names;

public List\<Name> getNames() {
return names;
}

public void setNames(List\<Name> names) {
this.names = names;
}
}

But Bean Validation 2 constrains `@Valid` `@NotNull`  work on Generics  Type Param in Java with Spring Web MVC.

 

 

 

 

 

---

**Affects:** 5.0.1

**Comment by sdeleuze** [comment]
Looks like blocked on https://youtrack.jetbrains.com/issue/KT-13228.

@ankurpathak Could you please provide a repro for your use case?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
