### ISSUE TITLE
Performance degradation in SpEL expression evaluation [SPR-16942]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21481]
**[Kanthi Vaidya](https://jira.spring.io/secure/ViewProfile.jspa?name=kvaidya)** opened **[SPR-16942](https://jira.spring.io/browse/SPR-16942?redirect=false)** and commented

We are planning to move from Spring 4.3.6 to Spring 5. We noticed a considerable dip in performance. About 50% degradation.

#21421 talks about a specific hot spot. Please look at attached benchmarks in that JIRA.

 

 

Juergen, I saw your code changes for caching the SortedMethods. We don't benefit much if you don't make your ConcurrentHashMap of sorted methods  a static variable.

Even after making the ConcurrentHashMap a static variable, we still don't get back the original performance of the prior spring versions. It definitely helps of course.

This is just one hotspot. More benchmarking and profiling is needed to identify other hot spots. And it probably makes sense to add a test case to the CI infrastructure to catch any such degradations.

This performance degradation, is preventing us from migration to Spring 5.

 

---

**Affects:** 5.0.7

**Issue Links:**
- #21130 Support for SimpleEvaluationContext in SpEL
- #21421 ReflectivePropertyAccessor should cache sorted methods

0 votes, 5 watchers

**Comment by hradilf** [comment]
Hi @spring-issuemaster, 
please, is there any estimation when this issue will be solved? 
Thank you.

**Comment by hradilf** [comment]
@spring-issuemaster Any update please? Thanks.

**Comment by snicoll** [comment]
With #31617 being implemented now, we no longer see this issue as actionable. Please give Spring Framework 6.1.x a try. If you're still experiencing performance issue, a new issue with additional details is more than welcome. Thanks!
