### ISSUE TITLE
Introduce Servlet version HandlerFunction and RouterFunction [SPR-16952]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21490]
**[Arjen Poutsma](https://jira.spring.io/secure/ViewProfile.jspa?name=arjen.poutsma)** opened **[SPR-16952](https://jira.spring.io/browse/SPR-16952?redirect=false)** and commented

In Spring 5.0, we introduced the functional web framework consisting of `HandlerFunction`, `RouterFunction`, and related types that runs on Reactive runtimes like Netty (in short: webflux.fn, or the package `org.springframework.web.reactive.function.server`).

Users have since expressed interest in a similar framework, but then running on synchronous, servlet environments. This framework will not built on Reactor, but rather use Java 8 `Stream` and `Optional` instead. Package will most likely be `org.springframework.web.servlet.function`, short name webmvc.fn.

---

**Issue Links:**
- #21491 Create DSL for RouterFunction and RouterFunctions

**Comment by spencergibb** [comment]
Spring Cloud Gateway could use this to provide a servlet alternative to zuul.

**Comment by maciejwalkowiak** [comment]
@spencergibb what would be the benefits of bringing blocking option to Cloud Gateway?

**Comment by spencergibb** [comment]
@maciejwalkowiak continue gateway conversation here https://github.com/spring-cloud/spring-cloud-gateway/issues/36

**Comment by poutsma** [comment]
See my PR at #22540

**Comment by poutsma** [comment]
PR is merged!

**Comment by sdeleuze** [comment]
It is worth to notice that we have chosen to use the name `WebMvc.fn` instead of `Servlet.fn` for the sake of consistency.
