### ISSUE TITLE
Null bean value exception message confusing [SPR-16961]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21499]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-16961](https://jira.spring.io/browse/SPR-16961?redirect=false)** and commented

When a `@Bean` method returns null it becomes non-autowirable, but the exception message only says that there are "no beans" of the required type. In fact there was one, but it was null, and that would be more useful information.

---

**Affects:** 5.0.7

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/13531

**Issue Links:**
- #21498 Odd behaviour with null bean instance when an alternative autowire candidate is available

**Comment by snicoll** [comment]
This injects `null` now.
