### ISSUE TITLE
Scoped data container [SPR-16971]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21509]
**[László Stahorszki](https://jira.spring.io/secure/ViewProfile.jspa?name=rolaca11)** opened **[SPR-16971](https://jira.spring.io/browse/SPR-16971?redirect=false)** and commented

My suggestion would be some kind of a generic data container, whose scope can be parameterized. There could be some annotation, let's say

```java
@ScopedContainer(scope = "some_scope")
```

that can be applied to fields, or setter methods.

A typical use-case would be, when I want to store some data in a bean of scope _singleton_, but I need the data _List<String>_ to be session scoped. I could then write a code:

```java
@Component
public class MySingletonBean {

    @ScopedContainer(scope="session")
    private List<String> dataForSession;

    public List<String> getStrings() {
        return dataForSession;
    }
    ...
}
```

A work around for this feature is creating a generic bean for every scope and using proxy to inject, but I think we could all at some point make use of some feature like this.

---
No further details from [SPR-16971](https://jira.spring.io/browse/SPR-16971?redirect=false)

**Comment by snicoll** [comment]
Thanks for the suggestion but `@Scope` is what you should be doing for this.
