### ISSUE TITLE
CGLIB source code not included in source jar [SPR-16984]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21522]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-16984](https://jira.spring.io/browse/SPR-16984?redirect=false)** and commented

The ASM source code is available in the source jars that Spring repackages, but CGLib is not. It makes debugging hard.

---

**Affects:** 5.0.7

**Issue Links:**
- #21912 org.springframework.cglib (in particular org.springframework.cglib.proxy.Enhancer) are missing from the source code bundle (_**"is duplicated by"**_)

**Comment by rstoyanchev** [comment]
Duplicate of #15040.
