### ISSUE TITLE
Configure Eclipse test source sets in Gradle build [SPR-17004]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21542]
**[Sam Brannen](https://jira.spring.io/secure/ViewProfile.jspa?name=sbrannen)** opened **[SPR-17004](https://jira.spring.io/browse/SPR-17004?redirect=false)** and commented

## Overview

Since Eclipse Photon supports separation of test source sets in the classpath, we should configure that within the Gradle build.

## Workaround

The following workaround has been proposed by [howlger](https://github.com/howlger) until Gradle and Buildship properly support the new feature in Eclipse.

```groovy
apply plugin: 'eclipse'
eclipse.classpath.file.whenMerged {

	// separate output folders required to set the 'test' attribute
	entries.find { it.path == 'src/main/java' }.output = 'bin/main'
	def testSrc = entries.find { it.path == 'src/test/java' }
	testSrc.output = 'bin/test'
	testSrc.entryAttributes['test'] = 'true'

	// libraries visible for test sources only?
	entries.forEach { entry ->
		def entryIn = { it.find { file(entry.path).equals(it) } }
		if (entry.kind == 'lib') {
			entry.entryAttributes['test'] =
				entryIn(configurations.testRuntimeClasspath) &&
				!entryIn(configurations.runtimeClasspath)
		}
	}
}
```

## Related Issues

- [Gradle Issue](https://github.com/gradle/gradle/issues/4802#issuecomment-396165166)
- [Buildship Issue](https://github.com/eclipse/buildship/issues/689)

## Deliverables

- Configure test source sets in the Eclipse classpath.
- Update wiki.

---
No further details from [SPR-17004](https://jira.spring.io/browse/SPR-17004?redirect=false)

**Comment by sbrannen** [comment]
Closing since this is no longer valid.
