### ISSUE TITLE
Add support for cache-control: immutable [SPR-17013]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21551]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[SPR-17013](https://jira.spring.io/browse/SPR-17013?redirect=false)** and commented

Originally raised in the Spring Boot issue tracker ([#13715](https://github.com/spring-projects/spring-boot/issues/13715)):

> We are facing an issue where even we set all appropriate options delineated at: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html the caching still does not work completely on Firefox. The goal is to have static files cached on local browser for users, with no re-fetching if the cache has not expired. Whereas what we see is that the cache gets invalidated every other time (caches only half of the time, and the response code flip-flops between 200 and 304). Turns out that firefox relies on `cache-control: immutable` to make sure the cache does not get invalidated.
> 
> Looking at https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/CacheControl.html , there is no option to set that `immutable` flag, is it possible to add the option?

---
No further details from [SPR-17013](https://jira.spring.io/browse/SPR-17013?redirect=false)

**Comment by bclozel** [comment]
Browser support is still very poor and won't change apparently. I'm closing this issue now.
We can revisit this decision if the situation changes.
