### ISSUE TITLE
@Scheduled to execute once on start [SPR-17019]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21557]
**[Alex Panchenko](https://jira.spring.io/secure/ViewProfile.jspa?name=apanchenko)** opened **[SPR-17019](https://jira.spring.io/browse/SPR-17019?redirect=false)** and commented

In some cases an initialization operation could take some time and it would be better executing it in background.
In crontab it's possible to have tasks scheduled `@reboot`, so I think a similar approach would work the best.

---

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1875

**Comment by sbrannen** [comment]
- Superseded by #1875
