### ISSUE TITLE
CronSequenceGenerator - Friday 13th issue [SPR-17036]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21574]
**[Lauri Kimmel](https://jira.spring.io/secure/ViewProfile.jspa?name=laurikimmel)** opened **[SPR-17036](https://jira.spring.io/browse/SPR-17036?redirect=false)** and commented

Unit test below is failing with message
`Overflow in day for expression "0 0 0 13 * FRI"`

```java
    public void testFriday13Failure() {

        String cronExpression = "0 0 0 13 * FRI";

        assertThat(CronSequenceGenerator.isValidExpression(cronExpression), is(true));

        CronSequenceGenerator gen = new CronSequenceGenerator(cronExpression);

        Instant instant = Instant.parse("2018-07-13T11:47:14Z");

        gen.next(Date.from(instant));

    }

```

2018-07-13 is Friday 13th;
2019-09-13 is next Friday 13th;
there are 427 days between which is exceeding max limit 366 in `CronSequenceGenerator.findNextDay()`.

---

**Affects:** 4.3.10

**Issue Links:**
- #13621 Cron expression with fixed weekday and fixed date may or may not lead to IllegalStateException (runaway search for next trigger)

**Comment by sbrannen** [comment]
I have confirmed that this is a bug when running the supplied test against `master`.
