### ISSUE TITLE
Support for the "type" parameter for Atom Feed/Entry message conversion [SPR-17040]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21578]
**[Mark Hobson](https://jira.spring.io/secure/ViewProfile.jspa?name=markhobson)** opened **[SPR-17040](https://jira.spring.io/browse/SPR-17040?redirect=false)** and commented

`AtomFeedHttpMessageConverter` and `RssChannelHttpMessageConverter` currently discard any media type parameters that are supplied to `write()`. They are overwritten when adding the charset parameter.

---

**Affects:** 4.3.18, 5.0.7

**Issue Links:**
- #21670 Use parameters declared in consumes or produces condition to narrow the request mapping

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1885

**Comment by rstoyanchev** [comment]
This is superseded by #1885.
