### ISSUE TITLE
Qualified beans are not autowired [SPR-17056]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21594]
**[Thomas OLIVIERI](https://jira.spring.io/secure/ViewProfile.jspa?name=tholivieri)** opened **[SPR-17056](https://jira.spring.io/browse/SPR-17056?redirect=false)** and commented

Hello,

When defining multiple beans with the same qualifier, I expect the beans to end up in a list that can be autowired. It all works fine until a certain (weird) point.

 I have a bean called MyBean:

```java
public MyBean(String name, Function<String, String> function) {
    this.name = name;
    this.function = function;
}
```

 I configure multiple beans of the same type (see: RootConfiguration.java):

```java
@Bean
@Qualifier("myBean")
MyBean myBean1() {
    return new MyBean("bean1", this::functionMyBean1);
}

// ...

private String functionMyBean1(String in) {
    return in;
}

// ...
```

 Then I can retrieve them all using:

```java
@Autowired
private List<MyBean> myBeans;
```

 The weird issue is that if I overload the bean creation method to define the function passed as the constructor parameter, then the bean is not added to the autowired list:

```java
@Bean
@Qualifier("myBean")
MyBean myBean1() {
    return new MyBean("bean1", this::myBean1);
}

private String myBean1(String in) { // overloaded method -> bean is not added
    return in;
}
```

 That's not a big issue since the workaround is obvious but I really would like to understand what's going on behind the scenes so the DI does not work as expected.
Note that the bean that is not injected in the list is eventually created, but never acknowledged as part of its "siblings".

Thanks in advance for your insight !

---

**Affects:** 5.0.5

**Reference URL:** https://github.com/tdolivieri/spring-qualified-beans

**Comment by snicoll** [comment]
Thanks for the sample. The weirdness that you see is indeed confusing and we've decided to deprecate it, see #31073 for more  details.
