### ISSUE TITLE
@AssertTrue validation failure in private isFoo method causes 500 INTERNAL_SERVER_ERROR [SPR-17055]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21593]
**[Adam Chesney](https://jira.spring.io/secure/ViewProfile.jspa?name=adamchesneyvelo)** opened **[SPR-17055](https://jira.spring.io/browse/SPR-17055?redirect=false)** and commented

Attached is a zipped up Spring Boot 2.1 SNAPSHOT web project showing the problem.

A method like this:

```java
@JsonIgnore
@AssertTrue
private boolean isNameNotFoo(){
    return name != null && !name.equalsIgnoreCase("foo");
}
```

In a nested element that appears in a List of items in a request object causes a 500 when it fails validation.

So this json is fine and returns 200:

```json
{"things":[{"name":"bar"}]}
```

But this json:

```json
{"things":[{"name":"foo"}]}
```

blows up with 500:

```
> Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: JSR-303 validated property 'things[0].nameNotFoo' does not have a corresponding accessor for Spring data binding - check your DataBinder's configuration (bean property versus direct field access)] with root cause``org.springframework.beans.NotReadablePropertyException: Invalid property 'things[0].nameNotFoo' of bean class [com.example.validationfail.api.OuterThing]: Bean property 'things[0].nameNotFoo' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
> at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:622) ~[spring-beans-5.1.0.BUILD-SNAPSHOT.jar:5.1.0.BUILD-SNAPSHOT]
> at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:612) ~[spring-beans-5.1.0.BUILD-SNAPSHOT.jar:5.1.0.BUILD-SNAPSHOT]
> at org.springframework.validation.AbstractPropertyBindingResult.getActualFieldValue(AbstractPropertyBindingResult.java:104) ~[spring-context-5.1.0.BUILD-SNAPSHOT.jar:5.1.0.BUILD-SNAPSHOT]
> at org.springframework.validation.AbstractBindingResult.getRawFieldValue(AbstractBindingResult.java:284) ~[spring-context-5.1.0.BUILD-SNAPSHOT.jar:5.1.0.BUILD-SNAPSHOT]
```

---

**Affects:** 5.0.8

**Attachments:**
- [validation-fail.zip](https://jira.spring.io/secure/attachment/25772/validation-fail.zip) (_101.23 kB_)

**Comment by tapioko** [comment]
The mentioned stackoverflow [answer](https://stackoverflow.com/a/2155576/613628) solves this problem, but it requires two new classes and tens of lines of code. Using @AssertTrue is much simpler and it would be nice if it worked also in this case.

For the record this problem also occurs with directly nested objects, not just with objects nested within a list. And it doesn't seem to matter whether the validation is method is private or public.
