### ISSUE TITLE
Improve documentation for FactoryBean's getObject automatic call through @ManagedResource [SPR-17139]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21676]
**[Manuel Jordan](https://jira.spring.io/secure/ViewProfile.jspa?name=dr_pompeii)** opened **[SPR-17139](https://jira.spring.io/browse/SPR-17139?redirect=false)** and commented

I have the following situation about `FactoryBean` for the `getObject()` execution.

I have for example:

```java
@Bean
ActiveMQConnectionFactoryFactoryBean connectionFactoryInstanceARemoteHostFactoryBean(){
	logger.info("@Bean connectionFactoryInstanceARemoteHostFactoryBean ...");
	ActiveMQConnectionFactoryFactoryBean factoryBean = new ActiveMQConnectionFactoryFactoryBean();
	....
	logger.info("	{}", factoryBean.toString());
	return factoryBean;
}
```

Where:

```java
public class ActiveMQConnectionFactoryFactoryBean implements FactoryBean<ActiveMQConnectionFactory>{

...

       @Override
	public ActiveMQConnectionFactory getObject() throws Exception {
            ...
        }

}
```

From above:
* The `@Bean` method is created/managed by Spring
* In _other_ `@Bean` method that works with `@Conditional` I can call and execute manually the `getObject()` method.

Until here all work how is expected.

My problem is with `RabbitMQ`, I have the following:

```java
@Bean
RabbitMQCachingConnectionFactoryFactoryBean cachingConnectionFactoryInstanceARemoteHostFactoryBean() {
	logger.info("@Bean cachingConnectionFactoryInstanceARemoteHostFactoryBean ...");
	RabbitMQCachingConnectionFactoryFactoryBean factoryBean = new RabbitMQCachingConnectionFactoryFactoryBean();
        ...
	logger.info("	{}", factoryBean.toString());
	return factoryBean;
}
```

and

```java
public class RabbitMQCachingConnectionFactoryFactoryBean implements FactoryBean<CachingConnectionFactory> {

   ...
   @Override
   public CachingConnectionFactory getObject() throws Exception {

```

Thus the following:
* The `@Bean` method is created/managed by Spring
* In _other_ `@Bean` method that works with `@Conditional` I can call and execute manually the `getObject()` method.

When `@Conditional` is false that _other_ `@Bean` never calls and execute manually the `getObject()` method. It is expected.

**Problem**: but because `implements FactoryBean<ActiveMQConnectionFactory>` works with `ActiveMQConnectionFactory` and it is declared how:

```java
@ManagedResource
public class CachingConnectionFactory extends AbstractConnectionFactory
		implements InitializingBean, ShutdownListener, PublisherCallbackChannelConnectionFactory {
```

I did realise that because the component is marked with `@ManagedResource`, Spring through JMX, calls _automatically_ the `getObject()` method. Arising errors.

I have the following:

```java
@Configuration
@EnableMBeanExport
public class JmxConfig {

}
```

If I comment `@EnableMBeanExport` the app starts up without problem. But I need use JMX for other components, I need Spring does not execute automatically that `@ManagedResource`.

This behaviour about JMX triggers automatically the `getObject()` method when the `FactoryBean`'s type is marked with `@ManagedResource` (i.e: `CachingConnectionFactory`) is not covered neither [1.8.3. Customizing instantiation logic with a FactoryBean](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-factory-extension-factorybean) nor [4. JMX](https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#jmx)

---

**Affects:** 5.0.8

**Comment by jhoeller** [comment]
The common solution here is to declare the target bean definition as lazy-init. The `MBeanExporter` takes that into account already. I'll document that in the JMX chapter.
