### ISSUE TITLE
JdbcTemplate method names for lambdas [SPR-17148]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21685]
**[Alexandru-Constantin Bledea](https://jira.spring.io/secure/ViewProfile.jspa?name=apixandru)** opened **[SPR-17148](https://jira.spring.io/browse/SPR-17148?redirect=false)** and commented

I have encountered many times after changing the java8 code to use lambdas rather than strict objects that the compiler chooses the wrong method.

Because both RowCallbackHandler and ResultSetExtractor have the same lambda signature, the compiler can get confused sometimes and call the method that i wasn't intending to call.

I have found that in few places calls to jdbcTemplate.query(...,(rs) -> something(rs)) will be interpreted as calls to the RowCallbackHandler rather than ResultSetExtractor and there is no indication that this is happening.

Perhaps now with lambdas becoming more common place it would make sense to deprecate these methods and replace them with more explicit calls like queryWithHandler and queryWithExtractor so that we can be sure that we're calling the correct type?

 

---
No further details from [SPR-17148](https://jira.spring.io/browse/SPR-17148?redirect=false)

**Comment by snicoll** [comment]
`JdbcTemplate` (and others) have a long history and breaking users for this reason doesn't sound like an improvement. In the meantime, `JdbcClient` offers a more fluent interface that doesn't have the problem you've described. Thanks for the suggestion, in any case.
