### ISSUE TITLE
Support dependency injection in JPA AttributeConverter for EclipseLink [SPR-17159]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21696]
**[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum)** opened **[SPR-17159](https://jira.spring.io/browse/SPR-17159?redirect=false)** and commented

With JPA 2.2 it is finally possible to do injection into AttributeConverters. The standard describes that when using CDI that injection. It would be nice if when using Spring injection would be supported as well. 

JPA 2.1 introduced injecting in EntityListeners with CDI would be nice if injection would work for that as well. 

Added bonus would be if this would work with both JPA and plain Hibernate. 

---

**Affects:** 5.1 RC1

**Reference URL:** https://github.com/javaee/jpa-spec/issues/109

**Issue Links:**
- #20852 Support Hibernate 5.3's ManagedBeanRegistry for dependency injection

**Comment by wilx** [comment]
We use Eclipselink. It would be nice to have this. I wanted to use the converters for transparent encryption/decryption of some of the fields in entities but to do that I need to have access to some Spring beans.

**Comment by jhoeller** [comment]
Since https://github.com/eclipse-ee4j/eclipselink/issues/1089 has not got any traction, we're closing this issue from Spring's side.
