### ISSUE TITLE
Lambda-based mapping of an ObjectProvider's object when available or unique [SPR-17170]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21706]
**[Yanming Zhou](https://jira.spring.io/secure/ViewProfile.jspa?name=quaff)** opened **[SPR-17170](https://jira.spring.io/browse/SPR-17170?redirect=false)** and commented

ObjectProvider should accept Function as argument like Consumer #20550

```java
	public default <R> Optional<R> ifAvailable(Function<T, R> dependencyFunction) throws BeansException {
		T dependency = getIfAvailable();
		if (dependency != null) {
			return Optional.ofNullable(dependencyFunction.apply(dependency));
		}
		return Optional.empty();
	}

	public default <R> Optional<R> ifUnique(Function<T, R> dependencyFunction) throws BeansException {
		T dependency = getIfUnique();
		if (dependency != null) {
			return Optional.ofNullable(dependencyFunction.apply(dependency));
		}
		return Optional.empty();
	}
```

---

No further details from [SPR-17170](https://jira.spring.io/browse/SPR-17170?redirect=false)

**Comment by r-sharath** [comment]
@quaff , seems like this issue has been fixed in the latest [main](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/factory/ObjectProvider.java#L90). Can we close this ?

**Comment by quaff** [comment]
@r-sharath It's not been fixed, my proposal is accept map function beside consumer function, for now I didn't encounter such requirement in practice, I prefer to close it, but it is migrated by bot not created by me in github, I'm not able to do this, @sbrannen could you close it?
