### ISSUE TITLE
Add proxy capability to Netty4ClientHttpRequestFactory [SPR-17175]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21711]
**[Sergey Galkin](https://jira.spring.io/secure/ViewProfile.jspa?name=fred84)** opened **[SPR-17175](https://jira.spring.io/browse/SPR-17175?redirect=false)** and commented

We are heavily using RestTemplate and recently received requirement to use SOCKS5 proxy with authentication. So our requirements list for http client is:
- configurable timeout
- socks5 proxy with auth
- client ssl certificates

After researching available http clients I see following possible solutions:
- replace RestTemplate with reactive WebClient
- create ReactiveWebClientRequestFactory and use it with RestTemplate
- add proxy capability to Netty4ClientHttpRequestFactory and use it with existing RestTemplate

Last option requires minimal changes. The only downside is that Netty4ClientHttpRequestFactory is deprecated.
Is it worth creating PR for this improvement?

---

**Affects:** 5.0.8

**Comment by bclozel** [comment]
`Netty4ClientHttpRequestFactory` has been deprecated as of 5.0 and in general we don't want to invest time in new features in `RestTemplate`, as it's been put in maintenance mode.

Developers should now rely on `WebClient` for new use cases and suggest improvements for it.
I'm closing this issue and the related PR as a result.
