### ISSUE TITLE
Support For JDBC Exception Translation For Amazon Redshift and Snowflake Database [SPR-17185]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21720]
**[Ankur Pathak](https://jira.spring.io/secure/ViewProfile.jspa?name=ankur%20pathak)** opened **[SPR-17185](https://jira.spring.io/browse/SPR-17185?redirect=false)** and commented

Spring Exception Translation is very helpful when we are coding JDBC based

application. But it lacks support for Amazon Redshift and Snowflake(https://www.snowflake.com) database. It would

be great if we can have support for these two databases.

---

**Affects:** 4.3.14, 5.0.3

**Comment by snicoll** [comment]
Thanks for the suggestion and sorry this got overlooked. There hasn't been much interest for this feature by the community. As such, we can't justify spending the time implementing and supporting such feature.
