### ISSUE TITLE
Deprecate TransactionSynchronizationAdapter

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21725]
**[Yanming Zhou](https://jira.spring.io/secure/ViewProfile.jspa?name=quaff)** opened **[SPR-17190](https://jira.spring.io/browse/SPR-17190?redirect=false)** and commented

Those legacy adapter class should be marked as `@Deprecated` and removed in the future, such as `TransactionSynchronizationAdapter` and `HandlerInterceptorAdapter`.

---
No further details from [SPR-17190](https://jira.spring.io/browse/SPR-17190?redirect=false)

**Comment by rstoyanchev** [comment]
We missed 5.2 but seems straight-forward enough so let's do it for 5.3.

**Comment by sbrannen** [comment]
Removal of `TransactionSynchronizationAdapter` would require people to provide a concrete implementation of `getOrder()` since `Ordered` does not provide a `default` implementation of that method. So, we'd need to document that with the deprecation message.

**Comment by sbrannen** [comment]
Partially superseded by #25147 regarding `HandlerInterceptorAdapter`.

**Comment by jhoeller** [comment]
I've reduced the scope of this ticket for the remaining `TransactionSynchronizationAdapter` part, potentially making the `TransactionSynchronization` interface itself extend `Ordered` (to sort out the migration problem discussed above).

**Comment by nickcaballero** [comment]
Adding `Ordered` to the `TransactionSynchronization` has caused `@Order` annotations to be ignored in favor of the `getOrder` result, which by default has been set to `LOWEST_PRECEDENCE`.

From `AnnotationAwareOrderComparator`:

```java
	protected Integer findOrder(Object obj) {
		Integer order = super.findOrder(obj); // This uses getOrder()
		if (order != null) {
			return order;
		}
		return findOrderFromAnnotation(obj);
	}
```

From `TransactionSynchronizationManager#getSynchronizations`:

```java
	List<TransactionSynchronization> sortedSynchs = new ArrayList<>(synchs);
	AnnotationAwareOrderComparator.sort(sortedSynchs);
	return Collections.unmodifiableList(sortedSynchs);
```
