### ISSUE TITLE
Create a WebFilter for ServerWebExchange Reactor Context [SPR-17213]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21746]
**[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch)** opened **[SPR-17213](https://jira.spring.io/browse/SPR-17213?redirect=false)** and commented

Similar to RequestContextFilter, it would be nice if there was a WebFilter that populated the ServerWebExchange in the Reactor Context. This would be benefit to Spring Security's OAuth support. It would also likely provide value for logging, metrics, etc.

---

**Affects:** 5.1 RC2

**Issue Links:**
- #21477 Unable to retrieve user from reactive context in RequestCondition
- #20239 RequestContextHolder for Reactive Web

0 votes, 5 watchers

**Comment by gregturn** [comment]
This would also benefit Spring HATEOAS and reactive link creation.

**Comment by mkopylec** [comment]
I also need this feature.
