### ISSUE TITLE
Provide fine-grained configuration support for HTTP message converters created in WebMvcConfigurationSupport#addDefaultHttpMessageConverters [SPR-17218]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21751]
**[lgoldstein](https://jira.spring.io/secure/ViewProfile.jspa?name=lgoldstein1)** opened **[SPR-17218](https://jira.spring.io/browse/SPR-17218?redirect=false)** and commented

The current code creates and initializes said converters without providing the user any way to intervene and modify the defaults. E.g., provide some external `ObjectMapper` to the `MappingJackson2HttpMessageConverter`, modify the default charset of `StringHttpMessageConverter` etc... The only recourse currently available is to override `extendMessageConverters`, somehow detect the converter(s) of interest and re-initialize them - potentially repeating already existing code ([a.k.a. the D.R.Y. principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)). I propose the following (IMO simple) feature - add a `preConfigureDefaultHttpMessageConverter` method that allows users to re-configure the initial converter - e.g.:

```java

// if returns null then discard the converter
protected <T, C extends HttpMessageConverter<T>> C preConfigureDefaultHttpMessageConverter(C converter, ApplicationContext context) {
    return converter;    // by default do nothing
}

protected <T, C extends HttpMessageConverter<T>> C addDefaultHttpMessageConverter(
        List<HttpMessageConverter<?>> messageConverters, C converter, ApplicationContext context) {
    converter = preConfigureDefaultHttpMessageConverter(converter, context);
    if (converter != null) {
        messageConverters.add(converter);
    }
    return converter;    // echo the effective converter
}

protected final void addDefaultHttpMessageConverters(List<HttpMessageConverter<?>> messageConverters) {
    StringHttpMessageConverter stringHttpMessageConverter = new StringHttpMessageConverter();
    stringHttpMessageConverter.setWriteAcceptCharset(false);  // see SPR-7316
    addDefaultHttpMessageConverter(messageConverters, new ByteArrayHttpMessageConverter(), applicationContext);
    addDefaultHttpMessageConverter(messageConverters, stringHttpMessageConverter, applicationContext);
    ...etc...
}
```

---

**Affects:** 5.0.8

**Comment by rstoyanchev** [comment]
Fine idea but it's yet another option on top of multiple existing options, not to mention the 
extensive [further options](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-message-converters) in Spring Boot. Using Java 8 Stream API with a `filter` on the converter type should provide a pretty good compromise.
