### ISSUE TITLE
getMappingForMethod failed when implement a interface method(with @RequestMapping) in super class [SPR-17223]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21756]
**[s-mop](https://jira.spring.io/secure/ViewProfile.jspa?name=s-mop)** opened **[SPR-17223](https://jira.spring.io/browse/SPR-17223?redirect=false)** and commented

Here is the demo codes:

```java
@RequestMapping(value = "order/customer")
@RestController
public interface CunstomerOrderClient {    
    @PostMapping("rating")
    String rating();
}
```

```java
public class AbstractOrderService {    
    public String rating() {
        return "rated";
    }
}
```

```java
@Service
public class CustomerOrderService extends AbstractOrderService implements CunstomerOrderClient {    
}
```

"order/customer/rating" dosnt registered as I expected

 I tried to find reason and get these codes in spring-webmvc:

 

 org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.getMappingForMethod(Method, Class<?>)

```java
protected RequestMappingInfo getMappingForMethod(Method method, Class<?> handlerType) {
    RequestMappingInfo info = createRequestMappingInfo(method); 
    if (info != null) { 
        RequestMappingInfo typeInfo = createRequestMappingInfo(handlerType); 
        if (typeInfo != null) { info = typeInfo.combine(info); } 
    } 
    return info; 
}
```

and 

 org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.createRequestMappingInfo(AnnotatedElement)

```java
private RequestMappingInfo createRequestMappingInfo(AnnotatedElement element) { 
    RequestMapping requestMapping = AnnotatedElementUtils.findMergedAnnotation(element, RequestMapping.class); 
    RequestCondition<?> condition = (element instanceof Class ? getCustomTypeCondition((Class<?>) element) : getCustomMethodCondition((Method) element));
    return (requestMapping != null ? createRequestMappingInfo(requestMapping, condition) : null); 
}
```

These codes seems like try to find `@ReqeuestMapping` in super class or interface of witch i defined my 'ranking' method

 

Of course they can't find `@ReqeuestMapping` because the 'ranking' method is defined in AbstractOrderService, and AbstractOrderService is not implements CunstomerOrderClient.

---

**Affects:** 5.0.5

**Issue Links:**
- #15682 Enable REST controller method parameter annotations on an interface
- #22028 AOP support for SPR-17223 & #1950

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1950

**Comment by rstoyanchev** [comment]
So the issue here is that the implementing method is on an abstract class that isn't itself implementing the interface?

**Comment by s-mop** [comment]
> So the issue here is that the implementing method is on an abstract class that isn't itself implementing the interface. Would use of delegate classes be a better fit, especially in a situation akin to multiple inheritance (i.e. "Most controllers(90%+) only need some of methods (about 30%-50%) which are defined in CommonController")?

My purpose is let one Controller/Service register some common API by only Implement the common Interfaces what they need. Instead of implement every common API or call several Repositories
Im not quiet sure about the 'delegate classes'
If there is other ways to do so by minimum redundancy code. Please give me some hints

**Comment by rstoyanchev** [comment]
Sorry for the delayed response. To me it still feels like a case of multiple inheritance and the path for that in Java is through delegation. The scenario however is a bit involved and although you've provided some snippets, it's still not completely clear.

It would be best to provide an actual sample, sufficiently representative of the problem, which would allow us to reason about alternative approaches or possible changes in the framework. While the changes proposed in #1950 may be working for you, they could also cause side effects such as is the case with #22028.

I'm closing as possibly outdated, but we can re-consider if this is still of interest.
