### ISSUE TITLE
Provide code samples in Kotlin in addition to Java [SPR-17245]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21778]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-17245](https://jira.spring.io/browse/SPR-17245?redirect=false)** and commented

Even if we have a dedicated Kotlin section in our reference documentation, all the code samples are in Java, requiring an effort for Kotlin users to translate it. I would like to make our documentation more natively Kotlin friendly by translating our code example to Kotlin.

This could be done via a Kotlin tab (in addition to the Java one) on each code sample block, and by generating 2 versions of the documentation: one in Java, one in Kotlin.

---

1 votes, 3 watchers

**Comment by sdeleuze** [comment]
All major parts of the reference documentation now have Kotlin code samples: Core, Testing, WebFlux and WebMvc. Other places will be completed later.
