### ISSUE TITLE
Framework for idempotent requests [SPR-17260]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21793]
**[Deryl Spielman](https://jira.spring.io/secure/ViewProfile.jspa?name=dukethrash)** opened **[SPR-17260](https://jira.spring.io/browse/SPR-17260?redirect=false)** and commented

##### Story

As a distributed systems developer
I want a framework that can elegantly handle idempotency in web requests
So that failed and retried requests do not produce side-effects
So that we don't have to build this in to every microservice

##### Background

When dealing with a distributed system a web request can fail at any time during the option whether it's a client or server timing out, server/client crashing, network failure, server succeeding but failing to give the response, etc.. The pattern I've seen is providing an "idempotency-key", which acts as a unique identifier the client passes to the server so that in the event of failure the server will not repeat the request if the operation has already succeeded with that idempotency-key.

A simple example would be a user approves a document, which generates two e-mails. One to the user and one to the document creator. The implementation may be two microservices, a document approval service and an e-mail notification service. If there is any failure after the approval the two e-mails could be lost unless you persist the fact that they needed to be sent, and a process exists that can retry unsent e-mail notifications and stamp them as sent. We don't want the same e-mail to be sent twice so an "idempotency-key" is saved with e-mail notification and calls to the e-mail notification service will provide this key. The notification service would then read the idempotency-key and not send the e-mail if the key already exists.

See Stripe's blog and implementation of this:
* https://stripe.com/blog/idempotency
* https://stripe.com/docs/api#idempotent_requests 

Imagine this example but now we need the same for deleting a document, or for any kind of request that involves two or more services. The ability to pick up where you left off in an operation is difficult to build and multiply this by the amount of distributed services you interact with. This calls for a framework that can turn this pattern in to an abstraction, which is what Spring Framework does so well and similar to how Spring Session has made it easy to abstract the http session.

##### Potential solution

1. Provide a spring boot starter or dependency that gives you idempotency out of the box
2. Web requests are filtered for a header named "idempotency-key"
3. A web client passes in "idempotency-key" with its request
4. On the server, the controller method annotated with `@Idempotent` are intercepted and looked up against a persistent store
   * Perhaps the developer can provide a custom `@Component` class that is identified in the `@Idempotent` annotation if custom look up logic is needed
5. If the request is found with the idempotency-key then it is returned, otherwise the request is honored

---

1 votes, 2 watchers

**Comment by rstoyanchev** [comment]
Thank you for the suggestion but I don't think the Spring Framework is the right place for this. A Boot starter couldn't be in the framework to begin with. Aside from that I can see this as an independent module/project that can plug into different web frameworks.
