### ISSUE TITLE
Notification for db connection acquired when LazyConnectionDataSourceProxy is used [SPR-17278]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21811]
**[Keshav Gupta](https://jira.spring.io/secure/ViewProfile.jspa?name=guptakeshav24)** opened **[SPR-17278](https://jira.spring.io/browse/SPR-17278?redirect=false)** and commented

We are using LazyConnectionDataSourceProxy to lazily fetch DB connection. When DB connection is fetched from pool there is no notification fired which can tell that db connection has been acquired. This is really helpful whenever some action needs to be taken on acquiring db connection(eg. logging).

---

**Issue Links:**
- #16195 Add close() method to LazyConnectionDataSourceProxy
- #21749 HibernateTransactionManager should lazily acquire JDBC Connection (like HibernateJpaDialect)

**Comment by jhoeller** [comment]
With the options above in mind, I'm going to close this issue here.
