### ISSUE TITLE
Fallback for default persistence unit root location if classpath root is unresolvable [SPR-17297]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21830]
**[Liu Jichun](https://jira.spring.io/secure/ViewProfile.jspa?name=jliu666)** opened **[SPR-17297](https://jira.spring.io/browse/SPR-17297?redirect=false)** and commented

---

**Affects:** 5.0.9, 5.1 GA

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/14279

**Comment by jhoeller** [comment]
Superseded by #29137: We expose `null` in case of an unresolvable persistence unit root URL which works with Hibernate so far.
