### ISSUE TITLE
`@annotation` pointcut is not matched with complex hierarchy and generics against classes compiled by Eclipse [SPR-17310]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21843]
**[Yanming Zhou](https://jira.spring.io/secure/ViewProfile.jspa?name=quaff)** opened **[SPR-17310](https://jira.spring.io/browse/SPR-17310?redirect=false)** and commented

```
Persistable   <-  BaseUser   <-  User
```

```
BaseManager<T extends Persistable>   <-  BaseUserManager<T extends BaseUser>  <-     UserManager<User> 
```

```
 
BaseManagerImpl<T extends Persistable>  <-  BaseUserManagerImpl<T extends BaseUser>  <-     UserManagerImpl<User>
```

The mostSpecificMethod should return method UserManagerImpl.save(User), but return BaseUserManagerImpl.save(BaseUser) which doesn't annotated, it will cause `@annotation` pointcut broken.

---

**Affects:** 5.1 GA

**Attachments:**
- [DeclaringClassTest.zip](https://jira.spring.io/secure/attachment/26032/DeclaringClassTest.zip) (_10.66 kB_)
- [spr17310.zip](https://jira.spring.io/secure/attachment/26031/spr17310.zip) (_10.24 kB_)

**Comment by quaff** [comment]
Minimized unit test, It will fail in eclipse.
```
import static org.junit.Assert.assertEquals;

import java.lang.reflect.Method;

import org.junit.Test;
import org.springframework.aop.support.AopUtils;

public class AopUtilsTest {

	@Test
	public void testGetMostSpecificMethod() throws Exception {
		String methodName = "feed";
		Class<?> targetClass = DogService.class;
		Method targetMethod = targetClass.getDeclaredMethod(methodName, Dog.class);
		Method originalMethod = AnimalService.class.getDeclaredMethod(methodName, Animal.class);
		Method actualMethod = AopUtils.getMostSpecificMethod(originalMethod, targetClass);
		assertEquals("Please ensure class compiled with javac not eclipse", actualMethod, targetMethod);
	}

	public static class Animal {

	}

	public static abstract class Mammal extends Animal {

	}

	public static class Dog extends Mammal {

	}

	public static class AnimalService<T extends Animal> {
		public void feed(T obj) {
		}
	}

	public static class MammalService<T extends Mammal> extends AnimalService<T> {
		@Override
		public void feed(T obj) {
		}
	}

	public static class DogService extends MammalService<Dog> {
		@Override
		public void feed(Dog obj) {
		}
	}

}

```

**Comment by snicoll** [comment]
Courtesy of @wilkinsona, the test is still failing with the latest Spring Framework 6.1 milestone.

@jhoeller wondering if we could accommodate with this difference between the eclipse and Java compiler?

**Comment by jhoeller** [comment]
I've addressed this through a new combined `BridgeMethodResolver.getMostSpecificMethod(Method, Class)` delegate which does `ClassUtils.getMostSpecificMethod` and then resolves the bridge method against the same target class, being able to find a matching signature even if no bridge method has been generated at the same class hierarchy level (as with the Eclipse compiler).
