### ISSUE TITLE
Itextpdf Package Rename  [SPR-17309]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21842]
**[hammadirshad](https://jira.spring.io/secure/ViewProfile.jspa?name=hammadirshad)** opened **[SPR-17309](https://jira.spring.io/browse/SPR-17309?redirect=false)** and commented

Itextpdf moves its package from com.lowagie to com.itextpdf
Due to this AbstractPdfView is not compatible with the new version of Itextpdf 

---
No further details from [SPR-17309](https://jira.spring.io/browse/SPR-17309?redirect=false)

**Comment by rstoyanchev** [comment]
Closing since iText has been replaced with OpenPDF since 5.0 with #20899.
