### ISSUE TITLE
Support callable references without request param in Kotlin router DSL [SPR-17325]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21859]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-17325](https://jira.spring.io/browse/SPR-17325?redirect=false)** and commented

The goal is to avoid to put an unused request parameter just for the sake of callable references support.

---
No further details from [SPR-17325](https://jira.spring.io/browse/SPR-17325?redirect=false)

**Comment by sdeleuze** [comment]
After a second thought, I think this issue should be addressed on Kotlin side by [KT-23678](https://youtrack.jetbrains.com/issue/KT-23678).
