### ISSUE TITLE
DelegatingCompletableFuture.cancel() returns false for already cancelled future [SPR-17337]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21871]
**[Ivan Sopov](https://jira.spring.io/secure/ViewProfile.jspa?name=isopov)** opened **[SPR-17337](https://jira.spring.io/browse/SPR-17337?redirect=false)** and commented

Sorry - JIRA failed me many times in filling this issue (one time I retyped it from the beginning), so I filled it on Gist:
https://gist.github.com/isopov/b2dca9d7152f577741c8451d91e97e37
This is somewhat related to #21870

---

**Affects:** 5.1 GA

**Issue Links:**
- #21870 MonoToListenableFutureAdapter.cancel problems

**Comment by bclozel** [comment]
Thanks for raising this issue Ivan, and sorry it took us so long to reply.
I agree that this subtle difference is quite tricky. The JavaDoc of `Future` does say that `Implementations may provide stronger guarantees`, but here it's really a behavior change. Our delegation implementation... delegates and the `cancel()` behavior isn't well defined.

Anyway `ListenableFuture` has been deprecated as of 6.0 in the meantime, so I don't think we should change the behavior now right before retiring it completely.
