### ISSUE TITLE
Disconnected client exception logging should differentiate remote service exceptions too [SPR-17341]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21875]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-17341](https://jira.spring.io/browse/SPR-17341?redirect=false)** and commented

Currently HttpWebHandlerAdapter suppresses logging of unhandled exceptions from writing to the response that are associated with a client going away. This is useful with streaming responses and was introduced in #18523. However as is clear from #21790 similar exceptions may also occur during request handling while making calls to a remote service, and arguably logging for those should not be suppressed.

This ticket is to explore the possibility of differentiating between the two and suppressing logging only of the former, but not of the latter kind. One option may be to wrap exceptions from `ServerHttpResponse#writeWith` with something like the Reactor Netty AbortedException and use that to differentiate between server response writing and other socket exception.

---

**Affects:** 5.0.9

**Issue Links:**
- #21790 o.s.h.s.r.ReactorHttpHandlerAdapter is polluting the logs
- #18523 WebFlux SSE controller does not detect disconnected client

**Comment by rstoyanchev** [comment]
It looks like Reactor Netty differentiates server and client exceptions with `AbortedException` vs `PrematureCloseException` so we don't need this.
