### ISSUE TITLE
Generate a CacheCreatedEvent from the Spring Caching Abstraction [SPR-17350]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21884]
**[Tyler K Van Gorder](https://jira.spring.io/secure/ViewProfile.jspa?name=tkvangorder)** opened **[SPR-17350](https://jira.spring.io/browse/SPR-17350?redirect=false)** and commented

Now that Spring Boot 2.x uses Micrometer for its metrics abstraction, it is helpful to have the caching abstraction instrumented such that metrics around cache size, hits, misses, puts, and evictions are published through Micrometer.

Spring Boot does do some limited auto-configuration to instrument the caching abstraction but is limited to only those caches that are known at startup time. This limitation is due to the fact that there is no way to observe when a new, dynamic cache has been created by the Spring Caching abstraction.

The current functionality means that any methods that are marked as `@Cacheable` will NOT have their metrics recorded through Micrometer.

To solve this problem without having to embed knowledge of Micrometer into each cache manager implementation, it would be better to have those cache managers publish an application event, CacheCreatedEvent.

This would allow for Spring Boot to auto-configure a listener for that event and bind all caches, dynamic or otherwise, to Micrometer's meter registry.

Looking at the code, the CaceCreateEvent should be emitted from the CacheManager.getCache(String name) method. The event should have both the cache name and the cache manager that was used to create the cache.

Most of the cache manager implementations extend AbstractCacheManager, and therefore this will be a good place to publish the event. However, there are a couple of additional CacheManager implementations (CaffineCacheMAnager, ConcurrentMapCacheManager) that do not extends the abstract base class and will also need to be modified to publish the event.

---

**Affects:** 5.0.9, 5.1 GA

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/14576

4 votes, 6 watchers

**Comment by snicoll** [comment]
I've been spending a fair amount of time on this one and also brainstorming with @jhoeller. I am not keen to implement this at framework level at this point.

The use case is very specific, yet the impact at framework level is quite facing. I've prototyped a `MissingCacheCreatedEvent` which feels a bit odd as that's the only event that the `CacheManager` would fire. We've discussed the possibility to rename that to `CacheCreatedEvent` with a flag to indicate that the cache was loaded from config or missing. This would fire a number of events on startup and the presence of such flag is hard to resonate from a framework API perspective.

All in all, this is a nice way to fix the related problem in Spring Boot but the proposal as is is not generally useful so I don't think we should implement it that way. I am now considering other options to fix the related issue, potentially via some improvements in Micrometer or Spring Boot.
