### ISSUE TITLE
Add a section to the documentation for setting a Spring project using Maven or Gradle [SPR-17378]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21911]
**[Behrang Saeedzadeh](https://jira.spring.io/secure/ViewProfile.jspa?name=behrangsa)** opened **[SPR-17378](https://jira.spring.io/browse/SPR-17378?redirect=false)** and commented

At the moment, there's only a small section in the docs that suggests users to use Spring Boot to get started: https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/overview.html#overview-getting-started

But there are times where users want to
* Create plain old vanilla Spring projects, without any dependencies on Spring Boot.
* Migrate old Spring projects to newer versions

There are a number of blog posts of varying qualities about how to approach this around the Web:
* https://blog.frankel.ch/easier-spring-version-management/ (2014)
* https://www.baeldung.com/spring-with-maven (2018)

Even older versions of Spring had this documented:
* https://docs.spring.io/spring/docs/4.3.3.BUILD-SNAPSHOT/spring-framework-reference/html/overview.html
* https://docs.spring.io/spring/docs/5.0.0.M5/spring-framework-reference/html/overview.html#dependency-management

Looks like somehow this has been omitted from the docs for newer versions of Spring.

It would be nice if this information was added back to the reference docs.

 

---

**Affects:** 5.1 GA

**Reference URL:** https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/overview.html#overview-getting-started

**Comment by bclozel** [comment]
Removing this section was intentional, as the Spring Framework reference documentation is not meant to replace the build tools' documentation nor to provide best practices for them.
Opinions and best practices are conveyed by start.spring.io in a more efficient manner.
