### ISSUE TITLE
Increase the preprocessing when executing asynchronous calls [SPR-17390]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21923]
**[hqch0708](https://jira.spring.io/secure/ViewProfile.jspa?name=hqch0708)** opened **[SPR-17390](https://jira.spring.io/browse/SPR-17390?redirect=false)** and commented

When the method is marked `@async`, it allows developers to customize the pre-processing to meet functional requirements when performing asynchronous calls through a thread pool.

For example, you can customize ThreadFactory to pass information from ThreadLocal to asynchronous threads as ThreadName when you create a thread, and then perform pre-processing at the asynchronous call.

---

**Affects:** 5.1.1

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1994

**Comment by snicoll** [comment]
Duplicate of #1994
