### ISSUE TITLE
package org/springframework/core/log doesn't fit with future Java 9 Module [SPR-17398]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21931]
**[ClaudioElio](https://jira.spring.io/secure/ViewProfile.jspa?name=claudioelio)** opened **[SPR-17398](https://jira.spring.io/browse/SPR-17398?redirect=false)** and commented

Hi

I wonder why has been created this package instead of extending the spring-jcl

if needed, it would be necessary not to call inner implementation of common-logging or Java 9 Module mechanism (that I'm trying to fit to Spring Framework in my spare time) is giving duplicated module exception (split package)

Thanks 

---

**Affects:** 5.1.1

**Reference URL:** https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/log/CompositeLog.java

**Comment by bclozel** [comment]
Closing has this matter has been resolved.
