### ISSUE TITLE
Add bean definition attribute for ConfigurationClassPostProcessor to skip "lite" bean detection [SPR-17412]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21945]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-17412](https://jira.spring.io/browse/SPR-17412?redirect=false)** and commented

`ConfigurationClassPostProcessor` does a lot of wheel spinning, even in an app with zero `@Configuration` classes. If there was a bean definition attribute that told it "don't analyze this class" we could short circuit a lot of that processing in a higher level tool (e.g. in Spring Boot).

---

**Affects:** 5.1.1

**Issue Links:**
- #21379 A lite configuration class's member classes are processed when it's imported but not when it's registered directly
- #21739 Revisit `@Bean` introspection between `@Configuration` classes and 'lite' beans

1 votes, 2 watchers

**Comment by jhoeller** [comment]
It looks like this will be covered by our programmatic annotation exclusion facilities where certain bean classes can be registered as non-annotated, or only annotated with specific annotations. All of our common annotation introspection algorithms use a central `AnnotationUtils.isCandidateClass` hook for those purposes already, including `ConfigurationClassPostProcessor`. We just need to define a proper programmatic API for registering such exclusions that can be picked up by the `isCandidateClass` check still, along with our revised `spring-context-indexer` which populate the same annotation exclusion API.
