### ISSUE TITLE
[Enhancement] @Bean can only inject one dependency,can I inject many dependencies in one method? [SPR-17441]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21973]
**[Paleozoic](https://jira.spring.io/secure/ViewProfile.jspa?name=paleozoic)** opened **[SPR-17441](https://jira.spring.io/browse/SPR-17441?redirect=false)** and commented

When inject two beans,such as the following code:

```java
@Bean("bean1")
public Bean buildBean1(){
    Bean bean = new Bean();
    return bean ;
}
@Bean("bean2")
public Bean buildBean2(){
    Bean bean = new Bean();
    return bean ;
}
```

can I just write the code? such as:

```java
@Beans
public Map<String,Bean> buildBeans(){
    Map<String,Bean> beans = new HashMap<>();
    beans.put("bean1",new Bean());
    beans.put("bean2",new Bean());
   return beans ;
}
```

sometimes we can not confirm how many beans to inject,we have to write complex `BeanDefinition` and then `registerBeanDefinition`.
if we have `@Beans`,everything is easy~

---

**Affects:** 5.1.1

**Comment by snicoll** [comment]
There isn't such way to declare beans in a generic fashion but the framework offers several hooks points. You could import an `ImportBeanDefinitionRegistrar` on a configuration class and you'll get a callback to register any bean you want. If those beans are singleton, you can also register them programmatically.
