### ISSUE TITLE
Support @TestPropertySource as a repeated annotation [SPR-17454]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21986]
**[shollander](https://jira.spring.io/secure/ViewProfile.jspa?name=shollander)** opened **[SPR-17454](https://jira.spring.io/browse/SPR-17454?redirect=false)** and commented

`@TestPropertySource` should ideally be supported as a repeatable annotation, just like `@PropertySource` is.

One use case for me is to create custom composed annotations with different `@TestPropertySource` declarations to provide a clear and non-error prone method of setting various properties for integration tests.

It would be very useful to be able to use a combination of multiple composed annotations with different `@TestPropertySource` declarations.

---
No further details from [SPR-17454](https://jira.spring.io/browse/SPR-17454?redirect=false)

**Comment by sbrannen** [comment]
Superseded by gh-23320
