### ISSUE TITLE
Support for parameter name introspection on Kotlin inline classes [SPR-17466]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21998]
**[reckter](https://jira.spring.io/secure/ViewProfile.jspa?name=reckter)** opened **[SPR-17466](https://jira.spring.io/browse/SPR-17466?redirect=false)** and commented

In org.springframework.core.KotlinReflectionParameterDiscoverer::get ParameterNames() spring tries to get names of parameters, by getting the kotlin function and calling getParameters() on it.

If you use the new inline class feature (since kotlin 1.3) in data classes, spring data mongo can not build the mapper, because the function mentioned above, returns null.

The cause for this is, that kotlin create a syntetic constructer as the default constructor, that unboxes the inline classes.
Because of that, the ReflectJvmMapping.getKotlinFunction returns null, as the function is not a kotlin function, but a created one.

The getParameterNames function should support syntetic functions, if somehow possible, so we can use inline classes fully in the spring framework.

 

---

**Affects:** 5.1.2

**Issue Links:**
- #20945 Upgrade to Kotlin 1.3

**Comment by sdeleuze** [comment]
@reckter Inline classes are experimental in 1.3, so I am not sure we should do anything in 5.2, and I am wondering if that should not be raised on Kotlin side. Any thoughts?

**Comment by sdeleuze** [comment]
Spring Data now provides dedicated related support and Spring Framework 6.1 also improved value Kotlin value classe support, so as I am not sure this old issue is valid anymore, I close it.
