### ISSUE TITLE
Support Spring Boot style flexible Duration value parsing [SPR-17481]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22013]
**[manderson23](https://jira.spring.io/secure/ViewProfile.jspa?name=manderson23)** opened **[SPR-17481](https://jira.spring.io/browse/SPR-17481?redirect=false)** and commented

Spring Boot supports specifying duration values in property files using values such as 15ms, 10s etc. (See https://github.com/spring-projects/spring-boot/issues/11078).

However, this means that there are inconsistencies when trying to use the values of these properties with Spring Framework annotations. An example was provided in https://github.com/spring-projects/spring-boot/issues/15126 where I would like to use a property value in a Scheduled annotation e.g.

```java
@Scheduled(fixedRateString = "${my-prop.rate}")
```

In this case I have to specify the property value using java.time.Duration syntax instead of the Spring Boot flexible syntax as `ScheduledAnnotationBeanPostProcessor` is hardcoded to use java.time.Duration parsing.

It would be good if Spring Framework also supported the flexible syntax to allow consistent property values to be used.

---

**Affects:** 5.1.2

**Comment by simonbasle** [comment]
linked to #22474 and superseded by gh-30396

**Comment by psyskeptic** [comment]
Still does not read 15m, read only with PT prefix
