### ISSUE TITLE
AOP support for SPR-17223 & PR#1950 [SPR-17496]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22028]
**[s-mop](https://jira.spring.io/secure/ViewProfile.jspa?name=s-mop)** opened **[SPR-17496](https://jira.spring.io/browse/SPR-17496?redirect=false)** and commented

In previous commit at PR#1950 we supported register RequestMapping on Interface which implement in parent class.And it works well in our production environment for this 7 weks. See #21756

 

And several days ago I realized that I can't register a AOP cutpoint for the scenario.

So i tried to changed the logic of org.springframework.aop.support.AopUtils.getMostSpecificMethod(Method, Class<?>)

Now this logic will try to find specific method in targetClass's interfaces first.Instead of only do that in targetClass.

I hope this commit can make my PR more helpful;)

---

**Affects:** 5.1 GA

**Reference URL:** https://github.com/spring-projects/spring-framework/pull/1950/commits/c76f017172938a9883e14b6804550ec0ca35f035

**Issue Links:**
- #21756 getMappingForMethod failed when implement a interface method(with `@RequestMapping`) in super class

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1950

**Comment by rstoyanchev** [comment]
Closing along with #21756.
