### ISSUE TITLE
AnnotationUtils won't find javax annotations [SPR-17495]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22027]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[SPR-17495](https://jira.spring.io/browse/SPR-17495?redirect=false)** and commented

Given a class `Foo` annotated with `javax.transaction.Transactional` calling:

```java
AnnotatedElementUtils.getMergedAnnotation(Foo.class, javax.interceptor.InterceptorBinding.class)
```

Will result in `null` despite the fact that `Transactional` is meta-annotated with `InterceptorBinding`.

The root cause appears to be `AnnotationUtils.hasPlainJavaAnnotationsOnly` which does `name.startsWith("java")` and perhaps should do `name.startsWith("java.")`.

https://github.com/spring-projects/spring-framework/blob/b9603680bc1de8d472ee463d99c11cc229dad2aa/spring-core/src/main/java/org/springframework/core/annotation/AnnotationUtils.java#L953

---

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/15175

**Referenced from:** commits https://github.com/spring-projects/spring-boot/commit/79b5dd3ae701649f4a926827db84a6b6c7d9ffc0

**Comment by philwebb** [comment]
Not loading `javax` types appears to be intentional and changing the logic is likely to degrade performance. Since we've added a guard in the Spring Boot code, I think we should close this one for now.
