### ISSUE TITLE
Single TransactionTemplate to perform variations of transaction configurations [SPR-17491]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22023]
**[Tadaya Tsuyukubo](https://jira.spring.io/secure/ViewProfile.jspa?name=tadaya)** opened **[SPR-17491](https://jira.spring.io/browse/SPR-17491?redirect=false)** and commented

With TransactionTemplate, for example, setReadOnly(true) is called, all executions with this template becomes readOnly transactions. If I want to perform another transaction with non-readonly, I need to create another template and so for all variation of transactions.

Instead, It would be nice to perform various transaction configurations with single TransactionTemplate.

 

For example:

 

```java
public <T> T execute(Consumer<DefaultTransactionDefinition> txConfig, TransactionCallback<T> action) throws TransactionException 
```

 

 

```java
template.execute( txConfig -> {
   txConfig.setReadOnly(true);
   txConfig.setIsolationLevel(...);
   ...
 }, status -> {
   // action to perform in transaction
});
```

 

 

---
No further details from [SPR-17491](https://jira.spring.io/browse/SPR-17491?redirect=false)

**Comment by snicoll** [comment]
> With TransactionTemplate, for example, setReadOnly(true) is called, all executions with this template becomes readOnly transactions. If I want to perform another transaction with non-readonly, I need to create another template and so for all variation of transactions.

That's a common pattern with our template infrastructure. The same applies to `JmsTemplate` that can set some QoS values that are common to all executions. Thanks for the suggestion, in any case.
