### ISSUE TITLE
JmsTemplate/CachingConnectionFactory doesn't reset sessions if the underlying connection was physically closed [SPR-17499]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22031]
**[Kevin Möchel](https://jira.spring.io/secure/ViewProfile.jspa?name=kevin%20m%C3%B6chel)** opened **[SPR-17499](https://jira.spring.io/browse/SPR-17499?redirect=false)** and commented

If one uses the JmsTemplate to produce messages together with the CachingConnectionFactory it's possible to break the cached Sessions in a way that the application doesn't recover from this by itself, leaving no other options then to restart the application.
We use Oracle UCP and Oracle AQ for messaging. I think the problem cam occur with every JMS implementation though.

This is the exception we observe:

> org.springframework.jms.IllegalStateException: JMS-131: Session is closed; nested exception is javax.jms.IllegalStateException: JMS-131: Session is closed
> at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:279)
> at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:169)
> at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:497)
> at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:580)
> at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:668)
> at com.example.jms.SessionClosedTest.testJms131(SessionClosedTest.java:171)
> ...
> Caused by: javax.jms.IllegalStateException: JMS-131: Session is closed
> at oracle.jms.AQjmsError.throwIllegalStateEx(AQjmsError.java:471)
> at oracle.jms.AQjmsSession.checkSessionStarted(AQjmsSession.java:4450)
> at oracle.jms.AQjmsSession.getDBConnection(AQjmsSession.java:4392)
> at oracle.jms.AQjmsSession.getAQOwner(AQjmsSession.java:6447)
> at oracle.jms.AQjmsSession.createQueue(AQjmsSession.java:1387)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.springframework.jms.connection.CachingConnectionFactory$CachedSessionInvocationHandler.invoke(CachingConnectionFactory.java:386)
> at com.sun.proxy.$Proxy73.createQueue(Unknown Source)
> at org.springframework.jms.support.destination.DynamicDestinationResolver.resolveQueue(DynamicDestinationResolver.java:84)
> at org.springframework.jms.support.destination.DynamicDestinationResolver.resolveDestinationName(DynamicDestinationResolver.java:58)
> at org.springframework.jms.support.destination.JmsDestinationAccessor.resolveDestinationName(JmsDestinationAccessor.java:98)
> at org.springframework.jms.core.JmsTemplate.access$200(JmsTemplate.java:90)
> at org.springframework.jms.core.JmsTemplate$4.doInJms(JmsTemplate.java:583)
> at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:494)
> ... 33 more

### Application Configuration

Configuration of the connection pool:

```java
<bean id="appDataSource" class="oracle.ucp.jdbc.PoolDataSourceFactory" factory-method="getPoolDataSource"
    lazy-init="true">
    <property name="connectionFactoryClassName" value="oracle.jdbc.pool.OracleDataSource"/>
    <property name="user" value="${database.username}"/>
    <property name="password" value="${database.password}"/>
    <property name="URL" value="${database.url}"/>
    <property name="initialPoolSize" value="5"/>
    <property name="minPoolSize" value="2"/>
    <property name="maxPoolSize" value="20"/>
    <property name="connectionWaitTimeout" value="10"/>
    <property name="inactiveConnectionTimeout" value="180"/>
    <property name="timeToLiveConnectionTimeout" value="0"/>
    <property name="abandonedConnectionTimeout" value="3"/>
    <property name="maxConnectionReuseTime" value="3"/>
    <property name="maxConnectionReuseCount" value="0"/>
    <property name="validateConnectionOnBorrow" value="true"/>
    <property name="maxStatements" value="80"/>
    <property name="timeoutCheckInterval" value="3"/>
    <property name="connectionProperties">
        <props merge="default">
            <prop key="oracle.net.disableOob">true</prop>
            <prop key="oracle.net.CONNECT_TIMEOUT">10000</prop>
            <prop key="oracle.jdbc.ReadTimeout">12000</prop>
        </props>
    </property>
</bean>
```

For arguments sake I set the abandonedConnectionTimeout, maxConnectionReuseTime and timeoutCheckInterval to 3, in order to force the ConnectionPool to close all connections that haven't been used for a little while.

XML-Configuration of the CachingConnectionFactory and the JmsTemplate:

```java
<bean id="jmsConnectionFactory" class="org.springframework.jms.connection.CachingConnectionFactory">
    <property name="sessionCacheSize" value="4"/>
    <property name="targetConnectionFactory">
        <bean class="com.example.jms.oracleaq.OracleAqConnectionFactoryBean">
            <property name="datasource" ref="appDataSource"/>
        </bean>
    </property>
</bean>

<bean id="jmsTemplate" class="org.springframework.jms.core.JmsTemplate">
    <property name="connectionFactory" ref="jmsConnectionFactory"/>
    <property name="sessionAcknowledgeMode" value="0"/>
    <property name="sessionTransacted" value="true"/>
    <property name="deliveryPersistent" value="true"/>
    <property name="explicitQosEnabled" value="true"/>
    <property name="defaultDestinationName" value="SAMPLE_QUEUE"/>
</bean>
```

Implementation of OracleAqConnectionFactoryBean:

```java
public class OracleAqConnectionFactoryBean implements FactoryBean<QueueConnectionFactory> {
    ...
    public QueueConnectionFactory getObject() throws Exception {
        return oracle.jms.AQjmsFactory.getQueueConnectionFactory(datasource);
    }
    ...
}
```

.h3 Test

```java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(value = { "/resources/spring/jpa.xml" })
public class SessionClosedTest {
    @Autowired
    private JmsTemplate jmsTemplate;
    
    @Test
    public void testRF242() throws Exception {
        MyBusinessObject someObj = new MyBusinessObject();
        this.jmsTemplate.convertAndSend(someObj);
        // Funny note: If you type Thread.sleep(15000); in the line below and remove this comment, Jira is actually not able to create the issue and the "Create Issue"-dialog completly breaks. On our own Jira we don't have this problem.
        Thread.sleep(15000);
        this.jmsTemplate.convertAndSend(someObj);
    }
}
```

The first call of _convertAndSend_ works as expected. However the second call will fail with the exception at the beginning.

It's possible to get the test above to run successfully if you call _CachingConnectionFactory#resetConnection_ after the sleep.

Spring-JMS will call _CachingConnectionFactory#resetConnection_ on its own given any JmsException, but only for Message-Consumer. I couldn't find similar behaviour for Message-Producer.

Is this something that should be adressed by Spring? The easiest fix is probably to reset the connections in the JmsTemplate if a JmsException occurs.

---

**Affects:** 4.3.19

**Comment by ranganath2334** [comment]
Hi Juergen Hoeller,
We are also facing the same issue with the combination JmsTemplate/CachingConnectionFactory.
When the exception "org.springframework.jms.IllegalStateException: JMSCC0020" occured, we have called explicitly CachingConnectionFactory#resetConnection in the catch block and retried sending the message. But still the same exception occurred again

Could you please help on this

Thanks
