### ISSUE TITLE
SimpleNamingContextBuilder: Second builder does not change JNDI context after first has been deactivated [SPR-17505]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22037]
**[Eelco de Lang](https://jira.spring.io/secure/ViewProfile.jspa?name=armhart)** opened **[SPR-17505](https://jira.spring.io/browse/SPR-17505?redirect=false)** and commented

When creating the SimpleNamingContextBuilder for a second time, it doesn't work well. Different testcases can cause eachother to fail. The second will be missing it's JDNI settings.
This is caused by the fact that the first SimpleNamingContextBuilder is still connected to the NamingManager.

```java
@Test
public void testSimpleNamingContextBuilder()
	throws NamingException, MalformedURLException, IllegalStateException
{
	SimpleNamingContextBuilder builder = SimpleNamingContextBuilder.emptyActivatedContextBuilder();
	builder.bind("url/testname", "WillNotBeCleared");
	builder.deactivate();

	SimpleNamingContextBuilder builder2 = SimpleNamingContextBuilder.emptyActivatedContextBuilder();
	builder2.clear();
	builder2.bind("url/testname", "ThisIsNotSet");

	InitialContext initialContext2 = new InitialContext();
	assertEquals("WillNotBeCleared", initialContext2.lookup("url/testname"));
}
```

---

**Affects:** 4.3.14, 5.1.2

**Comment by snicoll** [comment]
Closing as we no longer ship the mock JNDI environment.
