### ISSUE TITLE
StringUtils.parseLocaleString parses invalid locales successfully [SPR-17516]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22048]
**[Petar Tahchiev](https://jira.spring.io/secure/ViewProfile.jspa?name=ptahchiev)** opened **[SPR-17516](https://jira.spring.io/browse/SPR-17516?redirect=false)** and commented

Prior to spring-core 5.1.x calling this method:

```
StringUtils.parseLocaleString("some-locale-that-does-not-exist")
```

would throw IllegalArgumentException. However in spring-core 5.1.x (tested with 5.1.3.BUILD-SNAPSHOT) it doesn't. It simply returns a java.util.Locale object with language="some-locale-that-does-not-exist", region="", country=""

---

**Affects:** 5.1.2

**Issue Links:**
- #21241 CookieLocaleResolver is not RFC6265 compliant when setting a locale and time zone

**Comment by DeCaMil** [comment]
Given that the Locale constructor itself does not validate that the Locale exists, I wouldn't expect StringUtils should do that either.

In my mind, it's no different than creating a Url object for a host that does not exist.

**Comment by sbrannen** [comment]
> Given that the Locale constructor itself does not validate that the Locale exists, I wouldn't expect StringUtils should do that either.

That's a very valid argument, and we note that the following have the same output accordingly.

```java
System.out.println(StringUtils.parseLocaleString("some-locale-that-does-not-exist"));
System.out.println(new Locale("some-locale-that-does-not-exist"));
```

> In my mind, it's no different than creating a Url object for a host that does not exist.

Yes, indeed. Moreover, the [Javadoc for `parseLocaleString()`](https://docs.spring.io/spring/docs/5.1.8.RELEASE/javadoc-api/org/springframework/util/StringUtils.html#parseLocaleString-java.lang.String-) states the following.

> For many parsing scenarios, this is an inverse operation of Locale's toString, in a lenient sense. This method does not aim for strict Locale design compliance; it is rather specifically tailored for typical Spring parsing needs.

In light of the above, I am closing this issue.
