### ISSUE TITLE
Efficient type matching support for large number of beans [SPR-17528]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22060]
**[Rahul Shinde](https://jira.spring.io/secure/ViewProfile.jspa?name=rsjira22)** opened **[SPR-17528](https://jira.spring.io/browse/SPR-17528?redirect=false)** and commented

During profiling the application, it was found that around 19% of time was spent in the various BeanFactory methods.
See JFR snapshot:

![sbf_jfr_before.png](https://jira.spring.io/secure/attachment/26106/sbf_jfr_before.png)

Our application has over 10K beans and around 3K beans loaded at startup (~10% of them during and remaining immediately after ApplicationContext refresh).
The current implementation of _DefaultListableBeanFactory::doGetBeanNamesForType_ invokes _AbstractBeanFactory::predictBeanType_ twice for every type lookup (one via _isFactoryBean_ and the other during _isTypeMatch_)
As the _doGetBeanNamesForType_ implementation iterates over all the available bean definitions, in our case, the number of calls to predictBeanType quickly escalate to 10K * 3K * 2 = 60M.

The existing cache inside of _DefaultListableBeanFactory_ does help for subsequent lookups though.
I initially tried to minimize the number of calls to predictBeanType by adding a caching layer however the code in doGetBeanNamesForType seemed a bit hard to understand given the various corner cases it deals with.

![sbf_code.png](https://jira.spring.io/secure/attachment/26108/sbf_code.png) (_107.01 kB_)

It gave 10 seconds improvements however the lookup in the cache started showing up as the new hotspot.

Since the iteration over all the 10K bean definitions for every type lookup seemed to be the root cause, after several attempts, this is what I came up with (See PR).
The implementation goes over all the bean definitions and caches the type to name mapping once. It grabs the super types as well to avoid supplying a partial list of bean names in some cases.

Here is the JFR Hot Methods after applying the change:

![sbf_jfr_after.png](https://jira.spring.io/secure/attachment/26107/sbf_jfr_after.png) (_89.60 kB_)

This has helped speed up our application by around 25 seconds with no other change.
So far, it has been working fine for us on all our automated tests.
I would like to get your opinion on the change and if you think this would cause any long term breakages as Spring evolves.

Also it would be great if the core implementation itself can support more efficient lookups for types with sizeable beans in the registry.

 

---

**Affects:** 5.1 GA

**Attachments:**
- [sbf_code.png](https://jira.spring.io/secure/attachment/26108/sbf_code.png) (_107.01 kB_)
- [sbf_jfr_after.png](https://jira.spring.io/secure/attachment/26107/sbf_jfr_after.png) (_89.60 kB_)
- [sbf_jfr_before.png](https://jira.spring.io/secure/attachment/26106/sbf_jfr_before.png) (_140.60 kB_)

**Issue Links:**
- #17677 Autowiring with `@Autowired`/`@Inject` get much slower than with `@Resource` as the number of classes increases
- #18188 Improve performance of #getBeanNamesForType() while the BeanFactory configuration is not yet frozen

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/2021

**Comment by jhoeller** [comment]
This should have significantly improved in 5.2 already, based on #23336 and #23337. So this is effectively a duplicate at this point.
