### ISSUE TITLE
XpathResultMatchers to support Hamcrest Matcher<NodeList> [SPR-17529]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22061]
**[Pat Turner](https://jira.spring.io/secure/ViewProfile.jspa?name=itchyknee)** opened **[SPR-17529](https://jira.spring.io/browse/SPR-17529?redirect=false)** and commented

While _org.springframework.test.web.servlet.result.XpathResultMatchers_ supports Hamcrest matcher against a single org.w3c.dom.Node, it doesn't allow matching against multiple nodes via the _org.w3c.dom.NodeList_.

 

Suggest addition of a new ResultMatcher method in _XpathResultMatchers_ and supporting _XpathExpectationsHelper_:

`public ResultMatcher nodeList(final Matcher<? super NodeList> matcher)`

 

My motivation for this is to allow checking that XHTML element IDs are unique across the document, and to do this, I need to match all elements with an ID.

E.g. 

`//*[@id]`

 

Happy to contribute if you think this is worthwhile adding to framework.

---

**Affects:** 5.1.2

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/2023

**Comment by rstoyanchev** [comment]
This is superseded by #2023.
