### ISSUE TITLE
Migrate JSON projection features from Spring Data [SPR-17530]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22062]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-17530](https://jira.spring.io/browse/SPR-17530?redirect=false)** and commented

Spring Data Commons has some really cool tools for projecting JSON onto a user provided interface. The basic machinery for that is re-usable far beyond Spring Data (web endpoints, messaging, RPC, etc.), so it would be good to find it a more central home. The main abstraction is `ProjectionFactory`: https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/projection/ProjectionFactory.java.

---

**Reference URL:** https://github.com/spring-projects/spring-data-commons

1 votes, 6 watchers

**Comment by rstoyanchev** [comment]
Closing but feel free to comment further.

**Comment by odrotbohm** [comment]
This stuff would also be incredibly helpful in Spring HATEOAS as it provides a lightweight mechanism to bind payloads in client code. Having this API integrated in Spring Framework proper would help.
