### ISSUE TITLE
Unable to configure more than one AsyncConfigurer implementation classes [SPR-17541]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22073]
**[Kannadasan](https://jira.spring.io/secure/ViewProfile.jspa?name=kanna)** opened **[SPR-17541](https://jira.spring.io/browse/SPR-17541?redirect=false)** and commented

I want to have a multiple implementation of AsyncConfigurer for my use cases.(i.e) I need to have a more than one ThreadPoolTaskExecutor with AsyncUncaughtExceptionHandler feature.

But I got an exception like IllegalStateException - Only one AsyncConfigurer may exist. For more detail PFA.

---

**Attachments:**
- [exception.log](https://jira.spring.io/secure/attachment/26112/exception.log) (_5.02 kB_)

**Comment by gendolf3d** [comment]
have the same use case.

**Comment by snicoll** [comment]
@gendolf3d that's the intended behavior. Only one `AsyncConfigurer` can be exposed as a bean and the configurer configures the default thread pool only.
