### ISSUE TITLE
Confusing mockMvc asserts on async result  [SPR-17543]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22075]
**[Lukas Krecan](https://jira.spring.io/secure/ViewProfile.jspa?name=dart0)** opened **[SPR-17543](https://jira.spring.io/browse/SPR-17543?redirect=false)** and commented

Let's take the following test of an asynchronous API

```
MvcResult mvcResult = mockMvc.perform(post("/asyncEndpoint")
            .andExpect(status().isOk()) // passes but should not
            .andReturn();

mockMvc.perform(asyncDispatch(mvcResult))
            .andExpect(status().isConflict()); // the real status
```

We execute the request and check the status at once. Surprisingly it passes, even if the result is not ready yet and the final status will be different. I would except first `.andExpect(status().isOk())`  to fail since the result has not yet arrived (IllegalStateException?).

It's especially surprising if you forget that you have to test async controllers differently. Then you spend nontrivial amount of time investigating why your controller is returning 200 when you expect it to return an error.

---

**Affects:** 5.1.2

**Comment by snicoll** [comment]
Closing based on the comment above.
