### ISSUE TITLE
Using @ComponentScan on a @Configuration class causes temporary unconditional bean registration [SPR-17552]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22084]
**[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson)** opened **[SPR-17552](https://jira.spring.io/browse/SPR-17552?redirect=false)** and commented

Please see the referenced Spring Boot issue for a sample that reproduces the problem and my analysis of the cause.

---

**Affects:** 5.1.3

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/15348

**Comment by jhoeller** [comment]
It does not look like we can do anything about this. During component scanning, the state of the bean factory is incomplete still, so the degree of condition checking that we can do there is limited. It seems sensible to put any such demanding conditions onto configuration classes only, not onto independent scanned bean classes.
