### ISSUE TITLE
Support concrete Map subtypes for @RequestParam arguments

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22094]
**[yl-yue](https://jira.spring.io/secure/ViewProfile.jspa?name=yl-yue)** opened **[SPR-17562](https://jira.spring.io/browse/SPR-17562?redirect=false)** and commented

[Problem description](https://github.com/spring-projects/spring-boot/issues/15377)

Github problem notes

#### _*expect*_

`@RequestParam` annotation Subclasses of map are supported, Not just HashMap.

#### implementation

As github described it.

Or you can override the default Argument Resolvers by customizing the Argument Resolvers, as in the comments below.

---

**Affects:** 5.0.10

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/15377

**Comment by yl-yue** [comment]
@spring-issuemaster Hello, has this enhancement been implemented?

**Comment by snicoll** [comment]
@yl-yue that's a bot, there's no need to mention it. Also, you don't need to ask either: this issue is opened so, no, it's not implemented yet.

**Comment by sbrannen** [comment]
From the class-level Javadoc for `@RequestParam`, we see:

> If the method parameter is `Map<String, String>` or `MultiValueMap<String, String>` and a parameter name is not specified, then the map parameter is populated with all request parameter names and values.

@yl-yue, if I understood your proposal, you would like to be able to declare a `@RequestParam` parameter with a concrete subtype of `Map` -- for example, `net.minidev.json.JSONObject` which extends `HashMap<String, Object>`.

Is that correct?

**Comment by yl-yue** [comment]
@sbrannen Yes, expect `@RequestParam` this annotation to support automatic parsing of `HashMap<String, Object>` extension classes

**Comment by rstoyanchev** [comment]
@yl-yue I think we could make a change so any Map type (with a default constructor) can be instantiated. However we might have to apply similar changes to other argument resolvers (e.g. for consistency) and it's important to understand what this is needed for and therefore which resolvers it might apply to. So could you explain why isn't `Map` sufficient? 

Looking at `net.minidev.json.JSONObject` that you mention, it has static methods that accept Map so couldn't you do something like.:

```java
public void handle(@RequestParam Map<String, ?> params) {
    String json = JSONObject.toJSONString(params);
}
```

**Comment by yl-yue** [comment]
@rstoyanchev [fastjson](https://github.com/alibaba/fastjson)
```xml
<dependency>
	<groupId>com.alibaba</groupId>
	<artifactId>fastjson</artifactId>
	<version>1.2.57</version>
</dependency>
```
```java
public void name(@RequestParam Map<String, Object> paramMap) {
	/**
	 * This way, if you want to get the value of the validated type
	 * , you also need to convert it through a utility class, such as MapUtils
	 */
	paramMap.get("id");
	
	// Map subclass, an enhanced Map
	JSONObject paramJson = new JSONObject(paramMap);
	paramJson.getLong("id");
	paramJson.getString("id");
	paramJson.getDouble("id");
	paramJson.getDouble("id");
	paramJson.getJSONObject("id");
	paramJson.getObject("id", Long.class);// More methods ...
	
	// As you mentioned above, the toJSONString() dot method
	paramJson.toJSONString();
	
	// JSONObject default constructor
	new JSONObject();
}
```
**expect**
```java
public void name(@RequestParam JSONObject paramJson) {
	// ...
}
```

**Comment by yl-yue** [comment]
`com.alibaba.fastjson.JSONObject` Will it be supported

**Comment by rstoyanchev** [comment]
@yl-yue I considered this but I'm not sure our own `RequestParamMapMethodArgumentResolver` is a good place for this, as it has to create the sub-map via reflection. Also that resolver supports quite a number of variations of maps (single value, multi-value, with MultipartFile or Part as values).

I think it would be much better if this was handled as a custom argument resolver which understands what map needs to be created and can do a simple instantiation. I would recommend creating a custom type, something like:

```java
public final class JsonParams {

    private final JSONObject jsonObject;

    public JsonParams(Map<String, String> params) {
        this.jsonObject = new JSONObject(params);
    }

    public JSONObject json() {
        return this.jsonObject.
    }
}
```

Then a custom argument resolver could support a controller method like below based on the target type, without the need for adding `@RequestParam` which in the case of a `Map` does not add any value:

```java
public void name(JsonParams params) {
    // ...
}
```
