### ISSUE TITLE
RestControllerAdvice with custom annotations is not working properly [SPR-17569]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22101]
**[volkanto](https://jira.spring.io/secure/ViewProfile.jspa?name=volkanto)** opened **[SPR-17569](https://jira.spring.io/browse/SPR-17569?redirect=false)** and commented

We have two different controllers for two different versions of the API. We are trying to distinguish the exception handling too. Regarding this need, we created custom annotations to distinguish the controllers.

 

Here are the custom annotations for the version definitions:

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface ApiV1 { }

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface ApiV2 { }
```

 

Here are the controller implementations with the custom version annotations:

```java
@ApiV1
@RequestMapping("/path")
@RestController
public class XYZControllerImpl implements com.xyz.XYZController { ... }

@ApiV2
@RequestMapping("/v2/path")
@RestController
public class XYZControllerV2Impl implements com.xyz.v2.XYZController { ... }
```

 

And here are the custom exception handlers regarding the version declarations:

```java
@RestControllerAdvice(annotations = ApiV1.class)
public class ExceptionHandlerForV1 {      
    private static final String ONLY_APPLICATION_JSON_SUPPORTED = "only 'application/json' supported";     
    ...        
    @ExceptionHandler(HttpMediaTypeNotSupportedException.class)    
    @ResponseStatus(HttpStatus.BAD_REQUEST)    
    public CustomResponse handleHttpMediaTypeNotSupportedException(HttpMediaTypeNotSupportedException e) {        
        return new CustomResponse(CustomResponse.Status.INVALID_REQUEST, ONLY_APPLICATION_JSON_SUPPORTED);    
    }     
    ... 
}

@RestControllerAdvice(annotations = ApiV2.class) 
public class ExceptionHandlerForV2 { ... }
```

 

If a **HttpMediaTypeNotSupportedException** occurs, it is not handled by **ExceptionHandlerForV1**. We are getting Spring's exception instead of our custom exception. But if I remove _*annotations = ApiV1.class*_ part from the **ExceptionHandlerForV1**, this class is getting a global exception handler and related exceptions caught by this handler in a correct way. And also same behavior happens for **MethodNotAllowedException** too. But other types of exceptions handled properly.

We are wondering why this two exceptions (we tried these two exceptions so far) not handled by our custom exception handlers. Is it a design decision or a bug? If this is a design decision, how can we handle all these in our custom exception handlers?

We also tried all these cases with _Spring 5.1.3.RELEASE_ too.

---

**Affects:** 5.0.6

**Reference URL:** #21502

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by matdelong** [comment]
I'm having this issue as well. It seems to me that certain exceptions that occur while deciding if an endpoint in a controller class match the request (correct http method, correct Accept and Content-Type headers, etc.) then the endpoint is never chosen, so the Controller class is never chosen, so the "annotation" property of the ControllerAdvice annotation won't be matched. This seems counter-intuitive to me, because the path has been matched well enough to know, for example, the client sent the wrong HTTP method, so it stands to reason the request should be attached to that endpoint's controller, and the advice class should be able to target an annotation from that controller.

**Comment by EghliDos** [comment]
> 
> 
> I'm having this issue as well. It seems to me that certain exceptions that occur while deciding if an endpoint in a controller class match the request (correct http method, correct Accept and Content-Type headers, etc.) then the endpoint is never chosen, so the Controller class is never chosen, so the "annotation" property of the ControllerAdvice annotation won't be matched. This seems counter-intuitive to me, because the path has been matched well enough to know, for example, the client sent the wrong HTTP method, so it stands to reason the request should be attached to that endpoint's controller, and the advice class should be able to target an annotation from that controller.

It seems to me, if annotations are explicitly specified on the controller handler, e.g. media type consumed or HTTP method is used, then Spring MVC takes it as part of its signature, and during the determination stage to which controller the request belongs to, it wouldn't find the match, and therefore it delegates the exception handling to the default Spring MVC handler. Hence none of the custom exception handlers will be called. It's a bit annoying, but if that's how their Servlet implementation behaves, then we just have to understand the behavior.
