### ISSUE TITLE
Fix potential leaks from Mono.just(dataBuffer) or Flux.just(dataBuffer) [SPR-17575]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22107]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-17575](https://jira.spring.io/browse/SPR-17575?redirect=false)**

When using `Mono.just` or `Flux.just` data buffers can be allocated before subscription and consequently won't even see a cancellation signal in case the connection is closed.

The second issue is that if `Mono.just` or `Flux.just` is passed into `response#writeWith` those will not see a cancellation signal because cancellation is not propagated to them (i.e. can't cancel what's already been materialized).

---

**Affects:** 5.1.3

**Comment by rstoyanchev** [comment]
We do have a few instances of `Mono.just` or `Flux.just` with an allocated `DataBuffer`, e.g. in [form writer](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/FormHttpMessageWriter.java#L139), [multipart writer](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/multipart/MultipartHttpMessageWriter.java#L235), [EncoderHttpMessageWriter](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/EncoderHttpMessageWriter.java#L127), [Jaxb2 encoder](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/xml/Jaxb2XmlEncoder.java#L119). While in the [SSE writer](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/ServerSentEventHttpMessageWriter.java#L185-L186) the same is wrapped with `Mono.defer`. 

Rescheduling for 5.1.6 to confirm those are issues and confirm the preferred fix, e.g. via `defer`? There is probably a small chance for the things that could go wrong before those are written. Nevertheless we should address it.

**Comment by poutsma** [comment]
>We do have a few instances of `Mono.just` or `Flux.just` with an allocated `DataBuffer`

most of these examples do not have any memory leaks:

- the [form writer](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/FormHttpMessageWriter.java#L139) decorates the `ByteBuffer` into a `DataBuffer` using `DataBufferFactory.wrap()`, which does not allocate.
- [multipart writer](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/multipart/MultipartHttpMessageWriter.java#L235) does indeed appear to leak: all `generate*` methods should probably be returning `Mono<DataBuffer>` and use `Mono.defer`.
- [EncoderHttpMessageWriter](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/EncoderHttpMessageWriter.java#L127) does not allocate buffers, so there is no need to release.
- [Jaxb2 encoder](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-web/src/main/java/org/springframework/http/codec/xml/Jaxb2XmlEncoder.java#L119) has a boolean `release` flag that is used in the `finally` block.

**Comment by rstoyanchev** [comment]
> EncoderHttpMessageWriter does not allocate buffers, so there is no need to release.

EncoderHMW itself does not but the encoder it delegates to, does, and the use of `flatMap` could request eagerly and cache before it has reached Reactor Netty.

> Jaxb2 encoder has a boolean release flag that is used in the finally block.

The boolean releases in case of an error. The scenario being discussed in this ticket is that the `DataBuffer` is produced eagerly before subscription, and a cancellation may occur before it is written.
