### ISSUE TITLE
Spring Boot 2.x not converting Protobuf to JSON Using ProtobufJsonFormatHttpMessageConverter [SPR-17578]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22110]
**[Brajveer Singh](https://jira.spring.io/secure/ViewProfile.jspa?name=brajveer)** opened **[SPR-17578](https://jira.spring.io/browse/SPR-17578?redirect=false)** and commented

I am using ProtobufJsonFormatHttpMessageConverter in Springboot 2.0
```Java
@bean
ProtobufJsonFormatHttpMessageConverter protobufJsonFormatHttpMessageConverter() {
    JsonFormat.Printer printer = JsonFormat.printer().omittingInsignificantWhitespace();
    JsonFormat.Parser parser = JsonFormat.parser().ignoringUnknownFields();
    return new ProtobufJsonFormatHttpMessageConverter(parser,printer,(ExtensionRegistry)null);
}
```
While running application, it's not converting output to JSON rather its printing as Protobuf text as below.

����Chris�
Richardson*�
�[crichardson@email.com|mailto:crichardson@email.com]��

---

**Affects:** 5.1.3

**Comment by bclozel** [comment]
@BrajveerSingh Spring Framework has unit tests covering this. I've successfully serialized a protobuf message to JSON with the following:

```java
JsonFormat.Printer printer = JsonFormat.printer().omittingInsignificantWhitespace();
JsonFormat.Parser parser = JsonFormat.parser().ignoringUnknownFields();
ProtobufJsonFormatHttpMessageConverter converter = new ProtobufJsonFormatHttpMessageConverter(parser, printer);
PersonProtos.Person chris = PersonProtos.Person.newBuilder()
		.setFirstName("Chris").setLastName("Richardson")
		.setEmail("crichardson@email.com").build();

MockHttpOutputMessage outputMessage = new MockHttpOutputMessage();
try {
	converter.write(chris, MediaType.APPLICATION_JSON, outputMessage);
	System.out.println(outputMessage.getBodyAsString());
	// prints {"firstName":"Chris","lastName":"Richardson","email":"crichardson@email.com"}
}
catch (IOException e) {
	e.printStackTrace();
}
```

I'm closing this issue as nothing shows that there's a bug in Spring Framework.
Please ask further questions on StackOverflow, or reopen this issue with a repro project I can clone and run that shows the issue.

Thanks

**Comment by fcabouat** [comment]
(had the same issue, it was just that I forgot to content negotiate / produces = MediaType.APPLICATION_JSON_VALUE on my controller)
