### ISSUE TITLE
Support for vararg message arguments in MessageSource [SPR-17600]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22132]
**[Ankur Pathak](https://jira.spring.io/secure/ViewProfile.jspa?name=ankur%20pathak)** opened **[SPR-17600](https://jira.spring.io/browse/SPR-17600?redirect=false)** and commented

Current message arguments are passed as Object Array and it is not elegant. Since now

Spring Framework is based on Java 8. We can support Vararg based message arguments

in MessageSource by using Java 8 Interface default methods which delegates calls to

Object Array based methods. And it will be a easy to go chage as we won't have to 

implement those methods in any implementation of MessageSource.

 

I will be providing a pull request for this issue.

---

**Affects:** 5.1.3

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/2053

**Comment by rstoyanchev** [comment]
Superseded by #2053.
