### ISSUE TITLE
DefaultExceptionHandler logs warning cannot be disabled [SPR-17628]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22159]
**[danielrohe](https://jira.spring.io/secure/ViewProfile.jspa?name=danielrohe)** opened **[SPR-17628](https://jira.spring.io/browse/SPR-17628?redirect=false)** and commented

Before the change the warn logger was not enabled for DefaultHandlerExceptionResolver and it only logged on warn level in case the exception was one of ConversionNotSupportedException, TypeMismatchException, HttpMessageNotReadableException, HttpMessageNotWritableException.

With the latest changes from #21916 the DefaultHandlerExceptionResolver warn logger got enabled by default in the constructor and can't be disabled (setting to null in Configuration class causes NPE). This leads to the state that all resolved exceptions are logged at warn level in AbstractHandlerExceptionResolver logException method. So not only the exceptions mentioned above but also HttpRequestMethodNotSupportedException, HttpMediaTypeNotSupportedException, HttpMediaTypeNotAcceptableException, MissingPathVariableException, MissingServletRequestParameterException, ServletRequestBindingException, MethodArgumentNotValidException, MissingServletRequestPartException, BindException, NoHandlerFoundException.

Can you please clarify what is the logging behavior of DefaultHandlerExceptionResolver?

In my opinion warn logging in this class should also be configurable and not enabled by default. So that developers are free to choose whether they want to have it disabled or enabled. As a side note: it should also honor the application property spring.mvc.log-resolved-exception

---

**Affects:** 5.1.3

**Comment by rstoyanchev** [comment]
In #21714 `DefaultHandlerExceptionResolver` was updated to consistently log all exceptions. So that's expected behavior, but I'll makes there is no NPE if you try to disable it. Also you can use the protected method `logException`.
