### ISSUE TITLE
Improve message for `HttpStatusCodeException` with empty status text

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22162]
**[Jerzy Krolak](https://jira.spring.io/secure/ViewProfile.jspa?name=jerzykrlk)** opened **[SPR-17631](https://jira.spring.io/browse/SPR-17631?redirect=false)** and commented

I noticed that in RestTemplate-based client, I'm getting error messages like `404 null` and similar. Then I found that the Spring Boot application returns error statuses like the following:

```java
> curl -v http://localhost:8080/page-not-found
(...)
< HTTP/1.1 404
< Content-Type: application/json;charset=UTF-8
```

which will look like this:

`org.springframework.web.client.HttpClientErrorException$NotFound: 404 null`

Others return results like:

```java
curl -v http://google.com/page-not-found
(...)
< HTTP/1.1 404 Not Found
< Content-Type: text/html; charset=UTF-8
```

Which results in a nice looking error message:

`org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found`

I'm not sure if I should raise is as a bug - it does not seem that the status message is mandatory.

Is this a bug, or a feature?

---

**Affects:** 5.1.3

**Issue Links:**
- #19967 Exception hierarchy under HttpClientException and HttpServerException for the RestTemplate

**Comment by poutsma** [comment]
Thanks for providing a test case!
