### ISSUE TITLE
Document synchronous use of WebClient [SPR-17644]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22173]
**[Pavlo Morozov](https://jira.spring.io/secure/ViewProfile.jspa?name=pm)** opened **[SPR-17644](https://jira.spring.io/browse/SPR-17644?redirect=false)** and commented

ResTemplate javaDoc says it will be deprecated

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html

Also this page mentions the new class to call over HTTP. It is possible to use it in **both synchronous and asynchronous** ways:

> WebClient offers a modern alternative to the RestTemplate with efficient support for both sync and async, as well as streaming scenarios

Though I not see in javaDoc for WebClient any note about synchronous way it works:

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.html

 

So it is not clear **how to use WebClient in synchronous way**?

 

Also I have wider question related on StackOverflow, any help would be nice: https://stackoverflow.com/questions/54078309/spring-boot-http-call-to-remote-web-service

---

**Affects:** 5.1.3

**Comment by pavelmorozov** [comment]
Thank you!
