### ISSUE TITLE
Refactor configuration code samples to be more relevant for modern Spring applications

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22171]
Current Spring Framework reference documentation can be challenging to use for people developing modern Spring Boot applications. To make it easier, this issue goal is to refactor the documentation in order to provide configuration snippets with tabs for Java, Kotlin and XML in order to avoid being exposed to XML configuration by default (except in dedicated sections).

**Comment by sdeleuze** [comment]
I have not the bandwidth to do that for Spring Framework 5.2, but that's probably a good candidate for Spring Framework 5.3.

**Comment by sdeleuze** [comment]
A significant part of the documentation has been updated, so let's close this issue and get feedback after `6.2.0-M1` release and follow-up with #32429 and #32600.
