### ISSUE TITLE
MockHttpServletRequestBuilder does not allow invalid content type for testing [SPR-17643]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22172]
**[dmitry87](https://jira.spring.io/secure/ViewProfile.jspa?name=dmitry87)** opened **[SPR-17643](https://jira.spring.io/browse/SPR-17643?redirect=false)** and commented

 

```java
Invalid mime type "yaml": does not contain '/'
org.springframework.http.InvalidMediaTypeException: Invalid mime type "yaml": does not contain '/'
 at org.springframework.http.MediaType.parseMediaType(MediaType.java:512)
 at org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder.contentType(MockHttpServletRequestBuilder.java:277)
```

One of the app in stack sends invalid content type. Currently it is impossible to cover this in Unit test because `MockHttpServletRequestBuilder` uses MediaType.parse(contentType: String).toString() to get the value and it fails to get to ExceptionHandler

I propose that `MockHttpServletRequestBuilder` could accept any string for contentType. In this case when we send payload with invalid(unparsable) contentType to our controller we will handle InvalidMediaTypeException with our exception handler in Unit tests

 

---

**Affects:** 5.1.3

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/2077

**Comment by rstoyanchev** [comment]
This is now superseded by #2079.
