### ISSUE TITLE
Add option for AbstractRequestLoggingFilter to blacklist certain headers

### ISSUE THREAD

**Issue by OhDearMoshe** [spring-projects/spring-framework#22244]
So issue [SPR-14245](https://github.com/spring-projects/spring-framework/issues/18818) requested the ability to log all headers coming in with a request be added to AbstractRequestLoggingFilter.

There are sometime headers that it would be beneficial not to log. Such as Authorization headers containing jwt tokens.

It would be useful to be able to provide a blacklist of some headers which are then not appended to the log message builder.

**Comment by rstoyanchev** [comment]
We could probably add a `Predicate<String>` property for header names.

**Comment by OhDearMoshe** [comment]
Thats a much better idea than the one I had in mind. 😅 

Updated my PR.
