### ISSUE TITLE
RedisTemplate support lua script when using lettuce factory in redis cluster mode

### ISSUE THREAD

**Issue by wenjian1314** [spring-projects/spring-framework#22248]
Can RedisTemplate support lua script when using lettuce factory in redis cluster mode?

In this case I met some problems: "Lua script attempted to access a non local key in a cluster node" when i am using "redis.call('hmget', 'key', 'hash')"

**Comment by bclozel** [comment]
This class belongs to the Spring Data Redis project.
Could you [open this issue against its tracker](https://jira.spring.io/projects/DATAREDIS/issues)?

Thanks,
