### ISSUE TITLE
How to add a HandlerInterceptorAdapter after AbstractHandlerMapping.CorsInterceptor

### ISSUE THREAD

**Issue by maketubo** [spring-projects/spring-framework#22247]
How to add a HandlerInterceptorAdapter after AbstractHandlerMapping.CorsInterceptor?

**Comment by rstoyanchev** [comment]
I don't see a way currently. Any details?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
