### ISSUE TITLE
ParameterNameDiscoverer does not work?

### ISSUE THREAD

**Issue by syswu** [spring-projects/spring-framework#22252]
The class "com.google.api.services.compute.Compute$Instances" is an inner class, and the method "start" has three parameters.
I think the method LocalVariableTableParameterNameDiscoverer.getParameterNames() is not work in this case, which cannot find any parameters.
Could you help to solve this problem. Here is my codes:

```
Class<?> clazz = Class.forName(Instances.class.getName());
		for (Method method : clazz.getMethods()) {
			if (method.getName().equals("start")) {
				System.out.println("Parameter number:" + method.getParameterCount());
				ParameterNameDiscoverer pnd = new LocalVariableTableParameterNameDiscoverer();
				String[] filedNames = pnd.getParameterNames(method);
				System.out.println("Parameter values:" + filedNames);
			}
		}
```
The wrong outputs:

```
Parameter number: 3
Parameter values: null 
```

In addition,  the maven dependency is:

```
<!-- https://mvnrepository.com/artifact/org.springframework/spring-core -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>5.1.4.RELEASE</version>
		</dependency>

<!-- https://mvnrepository.com/artifact/com.google.apis/google-api-services-compute -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-compute</artifactId>
			<version>v1-rev201-1.24.1</version>
		</dependency>
```

**Comment by snicoll** [comment]
The javadoc of `getParameterNames` clearly indicates that `null` is an acceptable outcome if it cannot determine the parameter names.

`google-api-services-compute` is most probably compiled without debug information and the parameter name information simply isn't available. There is nothing we can do about that.

In the future, please ask questions on StrackOverflow as we prefer to use GitHub issues only for bugs and enhancements.
