### ISSUE TITLE
Pass filename hint to the ResourceDecoder

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-framework#22267]
Currently the `ResourceDecoder` uses the `ByteArrayResource(byte[])` constructor. However, usually when working with `Resource` the `Content-Disposition` header can be used to send the filename of the resource. I think that in this case it would be helpful if that can be passed as the description.

**Comment by sdeleuze** [comment]
Thanks for your proposal.

`ResourceDecoder` lives in `spring-core` and has no knowledge of HTTP headers. Leveraging `Content-Disposition` header would require implementing and using a dedicated `ResourceHttpMessageReader` instead of the generic `DecoderHttpMessageReader`. Implementing your proposal would require additional infrastructure, so I would like to have more detail about your use case to evaluate if your need is common enough.

Also, if we decide to do something here, are we talking only about `description` or also about `filename` `Resource` property (currently not accessible from `ByteArrayResource`)?

**Comment by rstoyanchev** [comment]
FWIW there is similar logic in the converter equivalent:
https://github.com/spring-projects/spring-framework/blob/4fdfa4246ff24872e2e17d86cc86dd8471f0da17/spring-web/src/main/java/org/springframework/http/converter/ResourceHttpMessageConverter.java#L89-L98

I suppose we could pass a filename hint without having the `ResourceDecoder` deal with an HTTP header.

**Comment by sdeleuze** [comment]
Feature parity between converters and codecs would be nice, so I add this improvement request in our 5.2 bucket.

@filiphr If you need that with 5.1, you can probably wrap the decoder and decorate the resource as a temporary workaround.

**Comment by filiphr** [comment]
You were faster than me to resolve everything 😄.

>I suppose we could pass a filename hint without having the ResourceDecoder deal with an HTTP header.

I was indeed thinking about passing the filename in the hints, not making the `ResourceDecoder` aware about the HTTP headers, sorry about not being more specific, I thought the name of the issue would imply that.

>Also, if we decide to do something here, are we talking only about `description` or also about `filename` `Resource` property (currently not accessible from `ByteArrayResource`)?

I was thinking about `description` as I saw that the `filename` is not exposed in the `ByteArrayResource`. However, pointing into the `ResourceHttpMessageConverter` indeed shows that one can set the `filename` properly. 

I actually need the `filename` as that is more descriptive and something that I am looking for in the `Resource`.

>Feature parity between converters and codecs would be nice, so I add this improvement request in our 5.2 bucket.

Thanks for adding it to the 5.2 bucket.

Just my 2 cents, you might want to support passing the `filename` to a `ByteArrayResource` in order not to need to provide something like in the `ResourceHttpMessageConverter`. 

> @filiphr If you need that with 5.1, you can probably wrap the decoder and decorate the resource as a temporary workaround.

I'll look into on our side to see what would be the best approach. Thanks for the hint
