### ISSUE TITLE
Bean Validation should not throw 500 Internal Server Error even without explicitly provided error handlers 

### ISSUE THREAD

**Issue by yuranos** [spring-projects/spring-framework#22266]
I find it really surprising that while bean validation is so deeply ingrained into Spring core, with most of the code being placed in spring-context, default validation, when custom handlers are not provided, is not properly supported.
Why does `DispatcherServlet` have to throw a nasty exception when it's a controllable situation? Besides, we do keep control over the response body, but intentionally decide to lose control over HTTP response status.
Spring should have sensible defaults as much as possible. **Returning 4XX when something is wrong with the client's request** seems to be the case in point.

To make matters worse, it's "consistently bad" for both Servlet-based applications and WebFlux. And while for Servlet-based MVC application it's not a big deal to add a handler, **it's a lot more complicated for router functions**. What if I don't want to add `ControllerAdvice`. Come to think of it, for a typical reactive application, I don't even what to know or hear anything about controllers. I'm either implementing bidirectional endpoints for continually sending data back and force or a data ingestors that are not operating based on CRUD paradigm.
If I only use `@ResponseStatus` and try to catch validation exceptions, I'm losing control over forming a detailed response body. The option I am resorting to right now is to add `onErrorResume` to my reactive flow inside handler functions. As an alternative, I can implement my own `WebExceptionHandler`. But both options sound like overengineering when all I need is to change the HTTP status and nothing more.  

I would love to work on this myself if we agree that it should be improved for both `web` and `webflux`.

**Comment by yuranos** [comment]
@rstoyanchev , @bclozel , is it still to be triaged or can I start looking into it?

**Comment by rstoyanchev** [comment]
Can you provide more details please? What does "without explicitly provided error handlers" mean, i.e. describe how the application and specifically the web framework configured? In most setup scenarios there should be default exception handling so at the moment I don't understand the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
