### ISSUE TITLE
Ability to set max frame length in ReactorNettyWebSocketClient

### ISSUE THREAD

**Issue by benitocm** [spring-projects/spring-framework#22268]
Hi,

We are obtaining this exception  _Max frame length of 65536 has been exceeded_  in a ReactorNettyWebSocketClient that receive a big payload. Having a look to the code, it seems that all is ready for having this feature in the client side but the websocket  method without the additional params is being called instead of the one that provides a parameter for the max frame length is provided. In summary, currently this is being used  https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/socket/client/ReactorNettyWebSocketClient.java#L84
but this should be used:
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClient.java#L888

The versions that we are using are the following:
Spring Boot 2.1.1 with Netty 
Reactor Netty 0.8.3

**Comment by sdeleuze** [comment]
@rstoyanchev What do you think of adding `default int getMaxFramePayloadLength()` to `WebSocketHandler` that would return `65536` and allow customization if needed?

**Comment by rstoyanchev** [comment]
This is already supported on the server side:
https://github.com/spring-projects/spring-framework/blob/4fdfa4246ff24872e2e17d86cc86dd8471f0da17/spring-webflux/src/main/java/org/springframework/web/reactive/socket/server/upgrade/ReactorNettyRequestUpgradeStrategy.java#L78-L85

A similar property on `ReactorNettyWebSocketClient` makes sense. Notice that it's also passed into the session which uses it for frame aggregation, so it should be passed there too, in addition to the `sendWebSocket` method call.

**Comment by rstoyanchev** [comment]
This is superseded by #22268.

**Comment by philsttr** [comment]
#22367
