### ISSUE TITLE
Spring MVC 5 docments, has incorrect WebFlux references

### ISSUE THREAD

**Issue by pashazadeh** [spring-projects/spring-framework#22270]
It seems that the documents were written once for WebFlux and then copy-paste-and-edited for Spring MVC, but some of substitutions were missed.

For example in [1.1.2. Special Bean Types](https://docs.spring.io/spring/docs/5.1.3.RELEASE/spring-framework-reference/web.html#mvc-servlet-special-bean-types), 

> By “special beans” we mean Spring-managed Object instances that implement **WebFlux** framework contracts.

>The following table lists the special beans detected by the **DispatcherHandler**:

Which should be replaced by **Spring WebMVC** and **DisplatcherServlet**.

**Comment by rstoyanchev** [comment]
Thanks for the report. I wish they were written once :) ..

**Comment by pashazadeh** [comment]
It seems the second guff **DispatcherHandler** is not changed to **DispatcherServlet** yet.

**Comment by rstoyanchev** [comment]
Fixing, thanks.
