### ISSUE TITLE
Clarify documentation about Spring MVC views rendered with Jackson versus @JsonView

### ISSUE THREAD

**Issue by pashazadeh** [spring-projects/spring-framework#22280]
Provide some samples for [1.9.9. Jackson](https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/web.html#mvc-view-jackson) in documentations.

New view technologies (such as Anguler and React.js) motivate using Jackson JSON views more frequently, I believe this part needs some samples for advanced configurations, and what is described in [Jackson-based JSON Views](https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/web.html#mvc-view-json-mapping).

**Comment by sdeleuze** [comment]
@rstoyanchev I am not sure about the link you provided, I think JSON views are documented in the [Annotated Controller](https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/web.html#mvc-ann-jsonview) section.

@pashazadeh I guess you were confused between `@JsonView` support and our documentation about rendering Spring MVC views with Jackson. A search in the document about "JSON views" lead to the section you mention, I am going to update the documentation to avoid this kind of confusion.
