### ISSUE TITLE
Scheduled annotation not work in conjunction cron expression and fixedRate

### ISSUE THREAD

**Issue by antonioiorfino** [spring-projects/spring-framework#22285]
**Affects:** 5.1.4.RELEASE

---

Hi All, I had some problems to use in different `@Component` classes the `@Scheduled` annotation in different way.
I leave here an example about that:
Component A

`@Component`
`public class ComponentA {`
`  @Scheduled(fixedRate = 10000, initialDelay = 100)`
`  public void test() {`
`  //do something...`
` }`
`}`

`@Component`
`public class ComponentB {`
`  @Scheduled(cron = "0/15 * * * * *")`
`  public void test1() {`
`  //do something...`
`  }`
`}`

I see the scheduler create two different method scheduled, but the componentB with the cron expression will not work as request in the expression. It will have a weird behavior.

Can you check please?
Regards

**Comment by snicoll** [comment]
> the componentB with the cron expression will not work as request in the expression. 

You haven't really indicated what doesn't work so it's hard for us to help you. What makes you think this is a bug in Spring Framework?
