### ISSUE TITLE
@CachePut evaluates key before cache condition

### ISSUE THREAD

**Issue by juanavelez** [spring-projects/spring-framework#22294]
**Affects:** Spring Context 4.3.4 and higher

---

Trying to use `@CachePut` on a method that might return `null`.

```java
@CachePut(cacheNames = Constants.Caches.USER, key = "#result.id", unless = "#result == null")
public MyObject doSomething();
```

You would expect the key expression not to be evaluated if the `unless` condition is `true` but this is not happening. The key is being evaluated before the `unless` condition is evaluated which leads to a 

> org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 0): Property or field 'id' cannot be found on null

```java
                if (cacheHit != null && cachePutRequests.isEmpty() && !hasCachePut(contexts)) {
			// If there are no put requests, just use the cache hit
			cacheValue = cacheHit.get();
			returnValue = wrapCacheValue(method, cacheValue);
		}
		else {
			// Invoke the method if we don't have a cache hit
			returnValue = invokeOperation(invoker);
			cacheValue = unwrapReturnValue(returnValue);
		}

		// Collect any explicit @CachePuts
		collectPutRequests(contexts.get(CachePutOperation.class), cacheValue, cachePutRequests);

		// Process any collected put requests, either from @CachePut or a @Cacheable miss
		for (CachePutRequest cachePutRequest : cachePutRequests) {
			cachePutRequest.apply(cacheValue);
		}
```

The `collectPutRequests` tries to evaluate the key if the `condition` passes (there is no condition). I think the keys need to be evaluated only if `unless` is `false`?

**Comment by solarmicrobe** [comment]
+1
Just hit this today. Luckily for me it is in a demo application and I can submit with just a javadoc on my function.

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by snicoll** [comment]
Closing in favor of PR #22769
