### ISSUE TITLE
Spring analyzer for "mvn dependency:analyze"

### ISSUE THREAD

**Issue by johnlinp** [spring-projects/spring-framework#22296]
Currently, `mvn dependency:analyze` will treat dependencies that are only used by Spring as "unused declared dependencies". However, the Maven plugin `dependency:analyze` provides a way to implement custom analyzer. I wish Spring can provide such analyzer to let me distinguish the dependencies that are only used by Spring and the ones that are really unused. Thanks.

**Comment by bclozel** [comment]
This is a dependency managed by your project, Spring Framework is not responsible for that.
There's no way for that maven plugin to know whether that dependency will be used at runtime or not, just by looking at the bytecode.

I guess you're looking for the `usedDependencies` configuration option, see [the plugin documentation](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html). For future questions, especially not related to Spring Framework, please use StackOverflow.

Thanks,

**Comment by johnlinp** [comment]
I see. Thanks for the explanation.
