### ISSUE TITLE
Reactor (Webflux) cannot recognise type in Mono, "Could not find acceptable representation"

### ISSUE THREAD

**Issue by razorree** [spring-projects/spring-framework#22292]
I have a simple code forwarding requests:

```
   public Mono<ResponseEntity<?>> restProxy(ServerHttpRequest proxyRequest,
            @RequestBody(required = false) byte[] body) {
                URI uri = // new URI
                WebClient.RequestHeadersSpec<?> partBuiltRequest = webClientBuilder.build().method(method).uri(uri);

    return partBuiltRequest
       .exchange()
       .flatMap(clientResponse -> {

                 return Mono.just(ResponseEntity
                            .status(clientResponse.statusCode())
                            .headers(clientResponse.headers().asHttpHeaders())
                            .body(clientResponse.bodyToMono(byte[].class))
                           );
         });
}
```

with that code i have "Could not find acceptable representation"
exception is thrown at:  AbstractMessageWriterResultHandler:160   (Spring-webflux-5.1.4.RELEASE)
and it's because method writeBody parameter's: body arrives as MonoOnAssembly<T>
and code can't recognise proper type and can't find converter (elementType is just Object).

however, if in my method, main return will be replaced with:

return clientResponse.toEntity(byte[].class);

everything works, because body parameter in AbstractMessageWriterResultHandler.writeBody method
is byte[] type, so everything is correctly recognised.
And i could use this way,
but, with toEntity method, i cannot set headers in returned ResponseEntity.

**Comment by rstoyanchev** [comment]
Either the return type needs to declare the expected body type:

```java
public Mono<ResponseEntity<byte[]>> restProxy(...) {
   // ...
}
```

Or the body in the ResponseEntity should be a resolved value:

```java
return partBuiltRequest
	.exchange()
	.flatMap(response -> response.bodyToMono(byte[].class)
		.map(bytes -> ResponseEntity
			.status(response.statusCode())
			.headers(response.headers().asHttpHeaders())
			.body(bytes)));
```
