### ISSUE TITLE
ApplicationListenerMethodAdapter does not find @Ordered annotation for dynamic proxies

### ISSUE THREAD

**Issue by gviczai** [spring-projects/spring-framework#22307]
**Affects:** 5.1.x

Is there a specific reason for ApplicationListenerMethodAdapter to use the "method" variable instead of the "targetMethod" in its constructor when resolving Order annotations?
Because for dynamic proxies, this results in a funny situation: EventListener annotation is present on the target class's method, but the Order annotation must be placed on the interface's method, otherwise it is not found.

	...
	EventListener ann = AnnotatedElementUtils.findMergedAnnotation(this.targetMethod, EventListener.class);
	...
	this.order = resolveOrder(method);

later, in resolveOrder():
	Order ann = AnnotatedElementUtils.findMergedAnnotation(method, Order.class);

**Comment by jhoeller** [comment]
This will be available in the upcoming `5.1.5.BUILD-SNAPSHOT`, hopefully covering the dynamic proxy scenario as expected now. Please give it an early try if you have the opportunity...

**Comment by gviczai** [comment]
Sorry, no opportunity here. :( We are using the 4.3 branch. I've just checked the master and saw that this bug still present, so I thought I report it...

**Comment by jhoeller** [comment]
FWIW, this is available in `4.3.23.BUILD-SNAPSHOT` from https://repo.spring.io/snapshot as well now. Please note that the 4.3.23 release is only scheduled for late March; feel free to give the snapshot a try before...
