### ISSUE TITLE
NPE in AbstractHandlerMethodMapping when trace logging is enabled and a handler's class loader does not provide package information

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#22306]
**Affects:** 5.1.4.RELEASE

In the unlikely event of trace logging being enabled and a handler's class having been loaded by a class loader that does not provide package information, `Class.getPackage()` will return `null` and the following line will NPE:

https://github.com/spring-projects/spring-framework/blob/6bdf2c26852611b3c3fd1505cd3ddc782739ad52/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerMethodMapping.java#L289

**Comment by jhoeller** [comment]
Good catch! I've also adapted the logger initialization code in `DecoderHttpMessageReader` and `EncoderHttpMessageReader` accordingly, avoiding `Class.getPackage()` in favor of `ClassUtils.getPackageName(Class)` or plain `Class.getName()` checks.
