### ISSUE TITLE
MockHttpServletResponse setHeader() not checking if response is already committed

### ISSUE THREAD

**Issue by raphdg** [spring-projects/spring-framework#22304]
**Affects:** spring-test 4.3.16 (Maybe still the case in master)

Had a bug in my code where I was setting a header after the HttpResponse was committed. MockMvc tests were not failing but real-life app did not behave the same (with Tomcat)

https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/mock/web/MockHttpServletResponse.java#L556

compared to this

https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/connector/ResponseFacade.java#L532

Is it intentionally missing the isCommitted() check?

**Comment by rstoyanchev** [comment]
The change would make sense.
