### ISSUE TITLE
Incomplete fix for MethodParameter.isOptional() ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#22303]
As per the latest comment on #22160, the fix in the 5.1.4 release is incomplete and needs a condition against the lower index boundary as well.

**Comment by jhoeller** [comment]
@shollander any opportunity to give this an early try against `5.1.5.BUILD-SNAPSHOT` from https://repo.spring.io/snapshot, ideally before the official 5.1.5 release on Wednesday?

**Comment by shollander** [comment]
@jhoeller I did not have an opportunity to test this earlier, but I have now tested against `5.1.5.RELEASE` and the problem does appear to have been fixed.
Thank you.
