### ISSUE TITLE
Add @Transactional option to rollback on exception only if it's a new transaction

### ISSUE THREAD

**Issue by leonshaw** [spring-projects/spring-framework#22301]
Scenario:
There's a transactional method A with REQUIRED propagation.
When a consumer B calls A with an existing transaction and an exception is thrown by A, B should be able to choose whether to fail or, to catch the exception, fix the problem and continue without rolling-back.
When A is called without an existing transaction, it (its interceptor) will start a new one. If it throws an exception later, the transaction should be rolled-back.

I think an option could be added to rollback only if exception is thrown across the boundary where the transaction is started/ended.

**Comment by snicoll** [comment]
Thanks for the suggestion but that violates the semantics of the `REQUIRED` propagation type. If you want to be able to control whether part of your logic can differentiate from the caller, you must use the `REQUIRES_NEW` propagation type.

**Comment by leonshaw** [comment]
@snicoll Hi, I think REQUIRES_NEW will always start a new transaction which is not desired. Any suggestions on how to implement this?

**Comment by leonshaw** [comment]
@snicoll Thanks. I've already asked on stackoverflow: https://stackoverflow.com/questions/54319657 but haven't got a solution. I think the actual transaction boundary is where it's started and ended, if an exception doesn't cause the end of a transaction, it should not rollback. Anyway, can you confirm that this is not possible in spring and won't be supported? So that I can refactor my code.

**Comment by snicoll** [comment]
The answer on your StackOverflow question is correct.
