### ISSUE TITLE
Allow to override the strategy used in ReflectUtils.defineClass

### ISSUE THREAD

**Issue by j3rem1e** [spring-projects/spring-framework#22310]
**Affects:** Spring 5.1

Since #20414, Spring uses `MethodHandler.Lookup.defineClass` to define proxy classes. However, this method forces the proxy to be defined in the same classloader as the initial class, and this classloader should have a visibility for all the classes used by the proxy (spring-aop, cglib & co).

This is not necessary the case in a restricted environment, or in osgi applications.

In my case, I used to build a custom classloader which provide visibility for such proxies - but I can't use this classloader anymore, although I have control of the defineClass on my classloader.

I'd like t have a way to override the spring-cglib ReflectUtils.defineClass() strategy.

**Comment by jhoeller** [comment]
As per #22416 (to be shipped in 5.1.6), we only prefer the JDK 9+ `Lookup.defineClass` API if the ClassLoader matches the context class now. This should cover OSGi scenarios and similar custom class loader architectures out of the box now. Please give it a try, possibly against a 5.1.6.BUILD-SNAPSHOT ahead of the release, and let me know whether you still see a need for a custom defineClass strategy.

**Comment by jhoeller** [comment]
I'm closing this issue for the time being, assuming that the resolution for #22416 covers this case as well.
