### ISSUE TITLE
MongoWaitQueueFullException in Webflux + Reactive Mongo

### ISSUE THREAD

**Issue by cbornet** [spring-projects/spring-framework#22332]
**Affects:** 5.1.2.RELEASE

---

The latest  [TechEmpower's benchmark](https://www.techempower.com/benchmarks/#section=test&runid=8ca46892-e46c-4088-9443-05722ad6f7fb&hw=ph&test=query&l=zik0vz-7&d=e6) shows a lot of errors for Webflux + Spring data mongo.
I digged and found out that under load, we get a lot of
`com.mongodb.MongoWaitQueueFullException: Too many threads are already waiting for a connection. Max number of threads (maxWaitQueueSize) of 500 has been exceeded.
`
exceptions.

From our discussion on gitter, @mp911de thinks that "WebFlux could have a notion of connection backpressure and should limit subscription rate/demand rate to provide a sense of protection for downstream components within the application".

Code of the benchmark [here](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/spring-webflux) 

Related issue : #20338

**Comment by rstoyanchev** [comment]
One easy change would be to replace `Flux.merge` [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/886e1ad4c16b4113e7e1c16c0e5c66807be6eb9d/frameworks/Java/spring-webflux/src/main/java/benchmark/web/WebfluxHandler.java#L57) with `Flux.concat`. That would match to what Dropwizard and Vert.x are effectively doing as far as I can see.

**Comment by cbornet** [comment]
@rstoyanchev thanks for your answer. Unfortunately that doesn't work. Still getting `MongoWaitQueueFullException` ...

**Comment by rstoyanchev** [comment]
From the test summary:

> All tests are run at 512 concurrency.

So that will put it over the 500 limit indeed even if each request is (should be) using at most 1 connection to Mongo at any time. May the Mongo config could be updated to accommodate the expected max concurrency?

> WebFlux could have a notion of connection backpressure and should limit subscription rate/demand rate to provide a sense of protection for downstream components within the application

I don't see a way for WebFlux to influence the number of HTTP connections. We could try and limit the number of concurrently handled HTTP requests, and that might be a useful feature, but how would it help in this case. In other words I don't think we'd want to restrict the number of concurrent HTTP requests to 500, would we?

**Comment by mp911de** [comment]
The actual underlying issue is an overload of a particular resource. That can happen IMO with any kind of resource, regardless of the technology that is used as a data source. 

WebFlux has no knowledge of downstream resource capacity. 
The Reactive Streams protocol looks at backpressure from a subscriber perspective to not overwhelm a subscriber. It's not considering the the producer perspective, whether a producing `Publisher` has sufficient resources to perform its work.

/cc @smaldini @simonbasle @bsideup

**Comment by schauder** [comment]
I stumbled over this some time ago and cobbled together something that creates backpressure for resources that don't do so themselves: 

https://github.com/schauder/reactive-threads/tree/master/src/main/java/de/schauder/reactivethreads/limited

The implementation is probably really bad, but I think we (possibly Reactor) should have something like this for resources that don't provide backpressure themselves.

**Comment by simonbasle** [comment]
Yes, and I believe that would also be resolved by a reactive DB Connection pooled capped at 500 connections.

**Comment by cbornet** [comment]
The connection pool is currently managed by the mongo async/rx-streams driver. Does it mean that it should be modified to support backressure ?

**Comment by sdeleuze** [comment]
I think this would deserve an issue in https://jira.mongodb.org/projects/JAVARS/ indeed. See also that one: [Driver uses only one thread to process incoming data](https://jira.mongodb.org/browse/JAVARS-110).

**Comment by mp911de** [comment]
Not quite sure what problem we're trying to solve right now. The MongoDB driver respects backpressure. It starts allocating resources as soon as there is demand (calling `Subscription.request(n)`) and not earlier.

In fact, the driver gracefully queues database commands until reaching a limitation threshold. Once the request queue hits the limit, the driver rejects additional work.

What is the behavior you would like to see? (Note this part is probably rather data-specific than Spring Framework-specific)

**Comment by mp911de** [comment]
I checked the benchmark implementation and second @rstoyanchev regarding `Flux.concat(…)`.

Applying this fix allows scaling using a higher request concurrency while a high query level argument does not exhaust the MongoDB connection pool immediately. Serializing queries aligns with the behavior exposed in other benchmarks such as vert.x.

**Comment by cbornet** [comment]
> What is the behavior you would like to see?

Shouldn't the driver pull commands into the queue only when there's room available in it ? The current behavior looks like publishers are directly pushing there commands into the queue.

> Applying this fix allows scaling using a higher request concurrency while a high query level argument does not exhaust the MongoDB connection pool immediately. Serializing queries aligns with the behavior exposed in other benchmarks such as vert.x.

Yes, I agree. But that doesn't make the exception disappear...

**Comment by mp911de** [comment]
> Shouldn't the driver pull commands into the queue only when there's room available in it ?

MongoDB driver defaults to a connection pool of 100 connections. Once it hits that limit, up to 500 additional commands are queued. Once the queue limit is hit, the driver throws `MongoWaitQueueFullException`.

What kind of behavior would you expect beyond how the driver behaves right now?

**Comment by cbornet** [comment]
It seems to me that the driver should request commands to be queued so there is no `MongoWaitQueueFullException` possible because it's a pull operation, not a push one.

**Comment by mp911de** [comment]
Please note that the driver is a `Publisher` and not a `Subscriber`. Items are requested by subscribers. 

In any case, turning the behavior around (using the stack as queue) eventually exhausts your JVM memory without a proper mechanism to apply a limitation. 

If an unbounded number of HTTP requests is accepted by the server (controllers/the routing function/the data access API) assembles a corresponding number of reactive sequences that are held in memory. Typically, reactive sequences have references associated with the incoming payload (e.g. entities, query definitions, user data, …).

**Comment by cbornet** [comment]
> If an unbounded number of HTTP requests is accepted by the server (controllers/the routing function/the data access API) assembles a corresponding number of reactive sequences that are held in memory. Typically, reactive sequences have references associated with the incoming payload (e.g. entities, query definitions, user data, …).

So if I understand well, in WebFlux there is backpressure inside one request but not globally across requests. Is that correct ?
Then is a workaround to size the mongo wait queue based on the max concurrent HTTP requests that are expected ? Or maybe configure it to be unbounded (don't know if that's possible) ? My feeling is that the number of acceptable concurrent requests shouldn't be configured in the mongo driver...

**Comment by rstoyanchev** [comment]
> So if I understand well, in WebFlux there is backpressure inside one request but not globally across requests. Is that correct ?

Yes that is correct. The new reactive connection pool effort for Reactor Nettty 0.9 should provide such a cap globally, and we might further consider rate limiting on a more fine-grained level in WebFlux.

For the current use case here, I think the first step is to have a closer look to confirm `Flux.concat` does not help. It seems like it should with 100 connection + 500 queue size 512 concurrency. Only then we can reason about what should change if anything in the configuration.

**Comment by cbornet** [comment]
> For the current use case here, I think the first step is to have a closer look to understand why `Flux.concat` does not help. It seems like it should with 100 connections + 500 queue size > 512 concurrency. Only then we can reason about what should change if anything in the configuration.

So using `concat` instead of `merge` does have an effect on the number of items put in the wait queue. 
The number of concurrent connections is related to the queue size (with `concat` it's queue size + a little number). The pool size doesn't seem to have any effect. I guess all items go into the queue before being given a pool connection.
I can put a high `maxWaitQueueSize` (using  `waitqueuemultiple` parameter in connexion string) and then I don't see any issues both for `concat` and `merge`. I think I'll keep `merge` with a queue size of 512*20 since it gives better results for low concurrency requests (since the 20 requests are done concurrently).
For me this issue is understood and can be closed. Maybe there could be some documentation somewhere about the Mongo driver pool size.
I'll do the fix for the TechEmpower benchmark. Thanks to all.
