### ISSUE TITLE
SpringEL should not throw IllegalAccessError for invalid assignment

### ISSUE THREAD

**Issue by heyouxian** [spring-projects/spring-framework#22336]
I have Spring Framework 5.0.9.RELEASE.
When I run below codes, following exception raised:
> Exception in thread "main" java.lang.IllegalAccessError
> 	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.setValue(MethodReference.java:398)
> 	at org.springframework.expression.spel.ast.CompoundExpression.setValue(CompoundExpression.java:96)
> 	at org.springframework.expression.spel.ast.Assign.getValueInternal(Assign.java:42)
> 	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:111)
> 	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:328)

But I cannot catch Error for sonarlint checking rule in my project, could SpringEL wrap all java.lang.Throwable into ParseException? Or provide a solution to avoid Error crash my application? Thanks.

```
    public void run() {
        SpelExpressionParser parser = new SpelExpressionParser(
                new SpelParserConfiguration(SpelCompilerMode.IMMEDIATE, this.getClass().getClassLoader()));
        StandardEvaluationContext context = new StandardEvaluationContext();
        RootObject root = new RootObject();
        parser.parseExpression("vars['var_map']=new java.util.HashMap()").getValue(context, root);
        parser.parseExpression("vars['tmp_key']='key'").getValue(context, root);
        parser.parseExpression(
                "vars['var_map'].get(vars['tmp_key'])=(vars['var_map'].get(vars['tmp_key'])?:createList('value'))")
                .getValue(context, root);
        System.out.println(root);
    }

    public static class RootObject {
        public Map<String, Object> vars = new HashMap<>();
        public Object stored;

        public Object getStored() {
            return stored;
        }

        public void setStored(Object stored) {
            this.stored = stored;
        }

        public Map<String, Object> getVars() {
            return vars;
        }

        public List<String> createList(String listValue) {
            return Arrays.asList(listValue);
        }

        @Override
        public String toString() {
            return "RootObject [vars=" + vars + ", stored=" + stored + "]";
        }
    }
```

**Comment by jhoeller** [comment]
It turns out that `MethodValueRef.setValue` itself should not throw an `IllegalAccessError` to begin with but rather a `SpelEvaluationException` with `SpelMessage.NOT_ASSIGNABLE`, analogous to `NullValueRef`. I've revised this for 5.1.5.
