### ISSUE TITLE
Add a List-based constructor to Jackson2JsonEncoder and Jackson2JsonDecoder

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-framework#22349]
I'm working on making Spring HATEOAS extensible with an interface that has the following method:

```java
List<MediaType> getMediaTypes();
```

When it comes time to create a `Jackson2JsonEncoder` and `Jackson2JsonDecoder`, using this list of support `MediaTypes`, I can't because the only constructor calls are:

```java
public Jackson2JsonEncoder(ObjectMapper mapper, MimeType... mimeTypes)
```
and 
```java
public Jackson2JsonDecoder(ObjectMapper mapper, MimeType... mimeTypes)
```
These require that you spell out the desired types, instead of being able to supply them from elsewhere.

**Comment by sdeleuze** [comment]
Hey @gregturn, I am not sure to understand what a `List` based constructor would enable that the current varargs one can't? Can't you do [that list to array conversion](https://github.com/gregturn/spring-framework/commit/7295030e3ff34b5e348683c2c583f553d8c914b1#diff-df96209cb5b1605627e1b1cedcb655caR65) in Spring HATEOAS?

**Comment by gregturn** [comment]
Ahh. I tried that but it didn't work at first. Now I realize, I was doing `.toArray(new MediaTypes[]{})`, when it should have been `.toArray(new MimeTypes[]{})`.
