### ISSUE TITLE
PathMatchingResourcePatternResolver may double-wrap jar: URLs

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#22346]
**Affects:** 5.1.4

When `PathMatchingResourcePatternResolver` is adding all class loader jar roots, it may wrap a URL with `jar:` and `!/` even though it is already so wrapped:

https://github.com/spring-projects/spring-framework/blob/32c4f6eb1876bc19ab83fad8ac5a0cf2104c7964/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L373-L387

This results in URLs like this:

```
jar:jar:file:/Users/awilkinson/dev/temp/gh-15844/target/gh-15844-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-2.1.3.BUILD-SNAPSHOT.jar!/!/
```

While such URLs work, they cause some extra work for Spring Boot's fat jar support to strip the URL back down again.  The creation of the wrapped URL also results in the creation of a new `StringBuilder`, `String`, and `URL` that appears to be unnecessary. Perhaps the protocol of the URL could be checked, and if it's `jar`, it could be used as-is to create the `URL` resource?

**Comment by jhoeller** [comment]
@wilkinsona would Boot benefit from a backport to 5.0.13 here?

**Comment by wilkinsona** [comment]
Thanks for the offer, but I don't think it's worth it. We're winding down the 2.0.x branch now and things work fine as they are, just not quite as efficiently as they could.

**Comment by jhoeller** [comment]
@wilkinsona, alright, let's leave it as 5.1.x only then. So I assume that recent revision works for your purposes there?

**Comment by wilkinsona** [comment]
Yes, I works nicely. Thanks.
