### ISSUE TITLE
Add MediaType for CSV

### ISSUE THREAD

**Issue by bitsmag** [spring-projects/spring-framework#22343]
Hi,

can we have an entry added to `org.springframework.http.MediaType`  for comma-separated values, i.e `text/csv` ?

Best regards,
Sven

**Comment by rajagopalmani** [comment]
Hi, can I do this change as first time contributor if you guys are planning to include ? I would like to get hands on with the process flow here. Thanks.

**Comment by bclozel** [comment]
Thanks to both of you for your contribution.
These days, we're trying to limit the number of static `MediaType` instances there. I know it's not always been the case, but from now on I think we should only add new ones there if Spring Framework is providing dedicated support for that media type.

Declaring such an instance is quite easy to do in an application, and I don't think all applications should pay the price of new types when it's clearly not useful to most of them.

Thanks!

**Comment by ThrawnCA** [comment]
> For anyone stumbling across this the MediaType class does provide a method to create one by parsing a String into a MediaType

It also has a simple constructor, `new MediaType("text", "csv")`
