### ISSUE TITLE
WebFlux ServerResponse builders are dropping cookies

### ISSUE THREAD

**Issue by csabakos** [spring-projects/spring-framework#22351]
**Affects:** 5.1.4

---
The `ServerResponse` builder functions that return `Mono<ServerResponse>` behave inconsistently with regards to the `cookies` that might have been already set on the response. Some builder functions drop the `cookies` field, while some preserve it.

The desired behavior is that all builder functions should preserve `cookies`.

Example of builder function that behaves correctly:
```
Mono<ServerResponse> body(BodyInserter<?, ? super ServerHttpResponse> inserter)
```

List of builder functions that behave incorrectly (drop `cookies`):
```
<T, P extends Publisher<T>> Mono<ServerResponse> body(P publisher, Class<T> elementClass)
<T, P extends Publisher<T>> Mono<ServerResponse> body(P publisher, ParameterizedTypeReference<T> typeReference)
Mono<ServerResponse> syncBody(Object body)

Mono<ServerResponse> render(String name, Object... modelAttributes)
Mono<ServerResponse> render(String name, Map<String, ?> model)
```

Test case to reproduce the bug:
```
    @Test
    public void testCookiesPersistIncorrect() {
        final Mono<ServerResponse> serverResponse = ServerResponse.ok()
                .cookie(ResponseCookie.from("foo", "bar").build())
                .syncBody("body");

        assertFalse(serverResponse.block().cookies().isEmpty());
    }
```

Test case to show that `body(BodyInserter<?, ? super ServerHttpResponse> inserter)` behaves correctly:
```
    @Test
    public void testCookiesPersistCorrect() {
        final Mono<ServerResponse> serverResponse = ServerResponse.ok()
                .cookie(ResponseCookie.from("foo", "bar").build())
                .body(BodyInserters.fromObject("body"));

        assertFalse(serverResponse.block().cookies().isEmpty());
    }
```

It's worth noting that the `hints` field may be susceptible to the same issue.

**Comment by xJoeWoo** [comment]
Also I found the constructor which build from other `ServerResponse` drops this field. #22481
