### ISSUE TITLE
Adding @ModelAttribute is breaking Flux request body

### ISSUE THREAD

**Issue by lukasjapan** [spring-projects/spring-framework#22357]
On a controller method that processes `multipart/form-data` with `Flux<Part>`, adding a `@ModelAttribute` results in a `Request body input error` error (which wraps an `Only one connection receive subscriber allowed.` error).

Controller:

```kotlin
@RestController
class DemoController {
    @PostMapping("/working")
    fun working(@RequestBody body: Flux<Part>): Flux<String> = body.map { it.name() + "\n" }

    @PostMapping("/not-working")
    fun notWorking(@ModelAttribute foo: String, @RequestBody body: Flux<Part>): Flux<String> = body.map { it.name() + "\n" }
}
```

Making the request with curl:

```bash
curl -i -X POST http://localhost:8080/working --form 'name=@/path/to/some/file'
curl -i -X POST http://localhost:8080/not-working --form 'name=@/path/to/some/file'
```

Output:

```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
transfer-encoding: chunked
Content-Type: text/plain;charset=UTF-8

name
```

```
HTTP/1.1 100 Continue

HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Content-Type: application/json;charset=UTF-8
Content-Length: 148

{"timestamp":"2019-02-06T11:03:12.242+0000","path":"/not-working","status":500,"error":"Internal Server Error","message":"Request body input error"}
```

**Comment by lukasjapan** [comment]
Additional info:

Using `RequestPart` instead of `RequestBody` resolves the issue but you need to know the `name` of the in advance.

**Comment by rstoyanchev** [comment]
Isn't it the case you need to know the name with @ModelAttirbute too?

`Flux<Part>` is primarily for accessing parts one at a time, e.g. for streaming. If that's not a concern and you want access to all parts, you can use `@RequestBody MultiValueMap<String, Part> parts'.

**Comment by lukasjapan** [comment]
> Isn't it the case you need to know the name with @ModelAttirbute too?

Not sure about all possible use cases of `@ModelAttribute`, but at least in my (actual) case it is unrelated to the request parts.

Will also give `MultiValueMap<String, Part>` a try. I am going to handle 1 or more potentially big files. So I would definitely prefer a full streaming approach for performance/memory reasons.

**Comment by rstoyanchev** [comment]
> Not sure about all possible use cases of `@ModelAttribute`, but at least in my (actual) case it is unrelated to the request parts.

I'm not sure what you mean. In a multipart request everything is a part.

**Comment by lukasjapan** [comment]
I did some more research and came to the conclusion that I was using `@ModelAttribute` in a non-optimal way. (Binding data from something else than the request)

Not sure anymore if this issue qualifies as bug. Will close the issue.

Another another error message would be nice but seems trivial.

Thanks for the help!
