### ISSUE TITLE
EL1072E when evaluating compiled comparison expression

### ISSUE THREAD

**Issue by jdomigon** [spring-projects/spring-framework#22358]
[NullComparisonTestBean.java.txt](https://github.com/spring-projects/spring-framework/files/2836105/NullComparisonTestBean.java.txt)

**Affects:** 4.3.16
When evaluating an expresion involving a numeric comparison with a boxed integer, it fails when using the bytecode compiled expression.

Very similar to #SPR-16489. Can be reproduced using the attached test case.

The problem, apparently, resides in method `Operator.generateComparisonCode()`. Its generated code does append bytecodes for unboxing values when necessary, but doesn't take into account a potential NPE. In interpreted mode, null check is made in method `StandardTypeComparator.compare()`.

**Comment by jhoeller** [comment]
@aclement any chance you could look at this for next week's 5.1.5 release still? Otherwise we can still pick it up for 5.1.6 and backport it to 5.0.13 and 4.3.23 in late March.

**Comment by jdomigon** [comment]
Side note: This bug affects operators `OpGE`, `OpGT`, `OpLE `and `OpLT`. Operators `OpEQ `and `OpNE` are not affected, as generated code includes calls to static method `Operator.equalityCheck`, which makes the null check.

**Comment by jhoeller** [comment]
Moving this one to 5.1.6, to be sorted out for our triple release in late March.

**Comment by jdomigon** [comment]
Wouldn't it be possible to backport and include the fix for this bug also in versión 4.3.23?. We're still on that branch.

**Comment by jhoeller** [comment]
Once we have a fix for 5.1.6, I intend to backport this to 5.0.13 and 4.3.23 indeed.

**Comment by jhoeller** [comment]
We're about to release 5.1.6, 5.0.13 and 4.3.23 tomorrow, freezing them soon. It looks like this fix will take a while still, to be sorted out in the 5.2 timeframe and then backported to the next 4.3.x release.

**Comment by aclement** [comment]
I do have a working fix but it really disturbs the generated code a lot and I'm not sure I'm happy with that, I'm still thinking about it.

**Comment by jhoeller** [comment]
@aclement Any progress on this one? Could we try to roll it into 5.2 M2 in early May?

**Comment by aclement** [comment]
@jhoeller Ok Juergen, I did more and more rounds of polishing on it and added even more testcases. Pushed.

**Comment by jhoeller** [comment]
@aclement Thanks, very timely! I'll consider backporting it to 5.1.7 at least, maybe further.

**Comment by jhoeller** [comment]
Reopening for the 5.1.7 backport...
