### ISSUE TITLE
stomp with rabbitmq broker relay

### ISSUE THREAD

**Issue by vidyas78** [spring-projects/spring-framework#22369]
This is related to the issue https://github.com/spring-projects/spring-framework/issues/21182, and to overcome I was using a relay broker, rabbitmq. 
When the client subscribes for the topic `/topic/FORMS/{id}`, `"SessionSubscribeEvent"` at the Server receives the request and starts streaming the data. There is a race condition where the subscription isn’t ready yet but the message is published through the broker and hence client misses the data packet. Should I be publishing the data for a different event listener? Its important for the first data goes immediately after subscription and later updates are published on the same topic once additional from server. Please suggest.

**Comment by rstoyanchev** [comment]
This has been discussed multiple times. It has nothing to do with using the built-in broker or an external one. Simply the "SessionSubscribeEvent" is not meant to be used for initialization. Please see discussions under #21172, #21182, and also [the docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#websocket-stomp-subscribe-mapping) for using `@SubscribeMapping` on a controller as a single-use subscription to return initialization data directly to the client (i.e. before the actual subscription to the broker to start receiving updates).
