### ISSUE TITLE
MappingJackson2MessageConverter doesn't check if payload assignable to target type

### ISSUE THREAD

**Issue by tdorzhi** [spring-projects/spring-framework#22386]
https://github.com/spring-projects/spring-framework/blob/7cde28306600cdf47450f3dc5b20740ec749d2f8/spring-messaging/src/main/java/org/springframework/messaging/converter/MappingJackson2MessageConverter.java#L229

Given object with usual `toString` implementation (for example `Foo(field1=SomeString)` and sending it to messageChannel using `MessageBuilder#withPayload` factory method results in above mentioned line to be executed, which predictably throws

**Comment by rstoyanchev** [comment]
Yes we could check if the payload is already an instance of the target class and skip the conversion.
