### ISSUE TITLE
Consider conditional view caching

### ISSUE THREAD

**Issue by fred84** [spring-projects/spring-framework#22391]
Currently we are only able to set size for views cache in subclasses of [AbstractCachingViewResolver](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/view/AbstractCachingViewResolver.java). When cache size limit is reached, oldest entry is evicted.

In my project I have following access pattern:
1) several html views which are accessed frequently
2) many RedirectView, which differs only in path segment (`/returnfromsomewhere/SOMEIDENTIFIER`) and are accessed only once. I don't want them to stay in cache.

I added simple *view name filter* to check if viewName should be cached.

Configuration example:

```java
    @Configuration
    static class ViewResolverConfiguration {

        @Autowired
        private List<ViewResolver> viewResolvers;

        @PostConstruct
        public void configure() {
            viewResolvers.forEach(v -> {
                if (v instanceof AbstractCachingViewResolver) {
                    ((AbstractCachingViewResolver) v).setCacheFilter(n -> !n.startsWith("redirect"));
                }
            });
        }
    }
```

Is it worth creating PR?

**Comment by poutsma** [comment]
>Is it worth creating PR?

Yes, I think it would be useful for `AbstractCachingViewResolver` to be able to express cacheability of views. At first glance, it should probably be inserted [here](https://github.com/spring-projects/spring-framework/blob/81451aa8007319cbf104bdd603a9fa8ab34ed372/spring-webmvc/src/main/java/org/springframework/web/servlet/view/AbstractCachingViewResolver.java#L163).

The filter should operate on more than just the name, though. It should provide all available variables for the filter to make its decision. Looking at the line linked to above, `Locale` and `View` are also  available in the `AbstractCachingViewResolver`, so these should also be passed to the filter as well (i.e. it should be possible for a filter to decide on cacheability depending on the `View` instance itself or its locale, not just its name.)
