### ISSUE TITLE
Spring boot context path

### ISSUE THREAD

**Issue by sattamshobaki** [spring-projects/spring-framework#22397]
Hello, 
I encountered issue for spring boot application that all resources are not working 
it's giving me 404 always 
after that i found the issue because there was space in context-path value in the application.properties

So it's better to trim the context patch before applying it

**Comment by sdeleuze** [comment]
This bugtracker is dedicated to Spring Framework, not [Spring Boot](https://github.com/spring-projects/spring-boot), so I close this issue as invalid.
