### ISSUE TITLE
Documentation for CORS incorrect for WebFlux functional endpoints

### ISSUE THREAD

**Issue by lievendoclo** [spring-projects/spring-framework#22390]
The WebFlux documentation should reflect that using the global configuration  (as described in https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-cors-global) does not work for functional endpoints and that the `WebFilter` approach should then be used.

**Comment by sdeleuze** [comment]
After a quick check with @poutsma, global configuration should work with functional endpoints, see https://github.com/poutsma/spring-framework/blob/fc957e95bb8c65e042b5eeb5d11ead60c277c53d/spring-webflux/src/main/java/org/springframework/web/reactive/config/WebFluxConfigurationSupport.java#L210.

Could you provide a repro project if that's not the case?
