### ISSUE TITLE
Reintroduce XmlBeans support

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-framework#22403]
In the past support for [XmlBeans](http://xmlbeans.apache.org) has been dropped as it was a dead project. However as of late 2018 the project has been revived again as part of Apache POI. 

It might be worthwhile considering to reinstate the XmlBeans support in Spring (and to support version 3+).

**Comment by jhoeller** [comment]
Like with Velocity, we do not intend to reintroduce XMLBeans support out of the box anymore. If such integration is still desirable, our former marshalling adapter classes should be a fine starting point and could easily be part of the XMLBeans project itself, co-maintained along with its own further evolution.

In the end, we only aim for JAXB2 and XStream to be supported out of the box, with JiBX being deprecated as well in the meantime. This is in alignment with our abstractions in other places, e.g. only EclipseLink and Hibernate as out-of-the-box JPA vendor adapters.
