### ISSUE TITLE
DefaultConversionService fails to properly convert an Object[] to a int[]

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-framework#22410]
**Affects:** 5.1.5
 
Converting an array of `Object` to an array of `int` behaves very different from converting it to an array of `Integer`.

```
DefaultConversionService.getSharedInstance().convert(new Object[]{23, 47, 4711}, Integer[].class);
```
results in `new Integer[]{23,47,4711}` as expected..

```
DefaultConversionService.getSharedInstance().convert(new Object[]{23, 47, 4711}, int[].class);
```
results in `new int[]{23}`, i.e. an array only containing the first element.

The result of the second expression should be `new int[]{23,47,4711}`

A preliminary analysis of what is going on by @odrotbohm :

> The different path is taken in the assignability check-in `ConversionUtils.canConvertElements(…)`. `Integer` is assignable to `Object`, `int` is not. That's why the `ArrayToArrayConverter` is ruled out eagerly.

**Comment by jhoeller** [comment]
This works fine if the incoming array is declared as `Integer[]` (or `String[]` or anything that matches its actual element type), i.e. it just fails with the generic `Object[]` declaration. Of course that's not intuitive.

Changing that {{Class.isAssignableFrom}} check to {{ClassUtils.isAssignable}} which understands primitive wrapper types solves the problem, so we can easily sort this out for 5.1.6.
