### ISSUE TITLE
Cannot define custom XmlFactory with Jackson2ObjectMapperBuilder.xml()

### ISSUE THREAD

**Issue by ndionisi** [spring-projects/spring-framework#22428]
When building an `XMLMapper` thanks to `Jackson2ObjectMapperBuilder.xml()`, it seems to be impossible to supply a custom `XmlFactory`.
In the following snippet:
```java
Jackson2ObjectMapperBuilder.xml()
                .factory(new MyXmlFactory())
                .build();
```
A `XmlMapper` will be constructed, but with the default `XmlFactory`, not the supplied instance of `MyXmlFactory`.
Reproduced in spring-web 5.1.3

**Comment by rstoyanchev** [comment]
@sdeleuze how about something like:

```java
public static Jackson2ObjectMapperBuilder builder(Supplier<ObjectMapper> initializer) {
    return new Jackson2ObjectMapperBuilder().objectMapperInitializer(initializer);
}
```

That would later be used in the builder method before the call to `configure`. Then one could provide:

```java
() -> new XmlMapper(...)
```

**Comment by sdeleuze** [comment]
@rstoyanchev I am not sure we need to introduce a new API to solve this issue, what about just doing [that](https://github.com/sdeleuze/spring-framework/commit/gh-22428)?
