### ISSUE TITLE
Gradle asciidoctor task fails on Windows

### ISSUE THREAD

**Issue by repos-hb** [spring-projects/spring-framework#22422]
I am trying to build the Spring sources from the latest release (5.1.5.RELEASE), but the `asciidoctor` task is failing every time.

`build.gradle` has the following entries.

```groovy
dependencies {
		classpath("io.spring.gradle:propdeps-plugin:0.0.9.RELEASE")
		classpath("org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16")
	}
}

// 3rd party plugin repositories can be configured in settings.gradle
plugins {
	id "io.spring.dependency-management" version "1.0.5.RELEASE" apply false
	id "org.jetbrains.kotlin.jvm" version "1.2.71" apply false
	id "org.jetbrains.dokka" version "0.9.17"
	id "org.asciidoctor.convert" version "1.5.8"
}
```

The stack trace is attached: [log.txt](https://github.com/spring-projects/spring-framework/files/2872045/log.txt)

**Comment by sbrannen** [comment]
@repos-hb, can you please try again against the current state of `master` and let us know if the `asciidoctor` task still fails for you?

Thanks in advance!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
