### ISSUE TITLE
Mono context inside Mono methods like doOnSuccess(), doOnError(), retry(), etc is unavailable

### ISSUE THREAD

**Issue by igorewka** [spring-projects/spring-framework#22427]
Make those methods Mono context aware.
Atm, it's possible to use doOnEach() to workaround the issue for doOnSuccess() and doOnError(). The result of logging in doOnSuccess() is different from logging in doOnEach(){if (signal.isOnComplete()){...}}. Looks like the time of executing those callbacks is different. So even this workaround is not quite good.
Any available workaround for the retry() is unknown.
The point of getting the context is to be able to log some unique request id in those methods if necessary.

**Comment by bclozel** [comment]
I think you meant to open this issue against the reactor core project. Spring Framework supports Flux and Mono but does not maintain those classes. 

Could you open an issue here?
https://github.com/reactor/reactor-core/issues

**Comment by igorewka** [comment]
My bad, thank you! 
https://github.com/reactor/reactor-core/issues/1531
