### ISSUE TITLE
HandlerInterceptorAdapter should honor ordering

### ISSUE THREAD

**Issue by fededonna** [spring-projects/spring-framework#22434]
**Affects:** \<Spring Framework version>

---

Hi, I've found that this feature was introduced in in Spring 5.x. Would it be possible to backport this to Spring 4.x and also to Spring boot 1.5.x?

this is the fix that needs to be backported.

https://github.com/spring-projects/spring-framework/commit/782c595cf7f839d2d6bf4c6bfc0502fc8c2c4ae0

Thanks.

**Comment by rstoyanchev** [comment]
It wasn't a fix really, but of cleaning up. Can you explain the problem you're having?

**Comment by fededonna** [comment]
It’s a feature to be honest. The problem is that I’m importing a starter that we have and I need to put an interceptor in the middle of those and since interceptors don’t honor @Order in SB 1.x I can’t do this without doing nasty things.

**Comment by rstoyanchev** [comment]
I think you're referring to #20179 which is a change in the Spring Framework. To my knowledge there isn't anything specific in Boot on top of that. 

If we did backport that how would it help your case? Wouldn't the interceptors in the imported starter have to make use of the (new) order property so you can insert in the middle?

**Comment by fededonna** [comment]
They are all using ordered but since I checked the class I mention in this case the class is only using an array list and inserting in the order they came. This will really help my case if you make it honor ordered. Thanks in advance.

**Comment by fededonna** [comment]
I also think that making it respect the order interface as you are doing in all the other places is a more clear solution that to hack it calling a method that receives the order provided by the method implemented in the class that implements the interface. Just my two cents here.

**Comment by rstoyanchev** [comment]
The https://github.com/spring-projects/spring-framework/commit/ac68cc35c2cf776d66c41e8544663f0db1f17166 sorts `HandlerInterceptorRegistration` instances based on the order property, which was added and did not exist before. How can they all have it?

**Comment by fededonna** [comment]
Ok, let me explain a little bit. I'm using spring boot 1.5.15 which depends on spring-webmvc 4.3.18

When I register my Handler interceptor in the class:

InterceptorRegistry

I see this code that is not honoring @Order which all of my HandlerInterceptorAdapters are implementing


`
	/**
	 * Return all registered interceptors.
	 */
	protected List<Object> getInterceptors() {
		List<Object> interceptors = new ArrayList<Object>(this.registrations.size());
		for (InterceptorRegistration registration : this.registrations) {
			interceptors.add(registration.getInterceptor());
		}
		return interceptors ;
	}  
`

which doesn't seem to honor the order and I'm facing the problem that, despite of having the correct order in my config, one HandlerInterceptor is being called before the one that is supposed to be called.

**Comment by rstoyanchev** [comment]
Okay thanks. 

BTW the reason for `InterceptorRegistration` to not implement `Ordered` is because it's part of the public config API where we aim to show options to change only. Accessors are protected for internal use. This is consistent with the rest of the Java MVC config.

**Comment by fededonna** [comment]
It makes sense but it won’t hurt having extra options. Do you think that this change is going to be part of 4.x or you won’t port this back?
Thanks.

**Comment by spring-issuemaster** [comment]
Fixed via dba9c9028006749c19cfc7efaf683e41d9efd2d9
