### ISSUE TITLE
The for loop in AspectJProxyUtils should add break

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#22449]
When local variable 'foundAspectJAdvice' is set to true, there is no need to continue checking, it should end with break.

![image](https://user-images.githubusercontent.com/13413715/53161843-b9b69d80-3605-11e9-8988-56197c4c06ce.png)

**Comment by rhamedy** [comment]
@jhoeller I know this does not have the `ideal for contribution` label but, I could not resist offering my assistance :slightly_smiling_face:
