### ISSUE TITLE
HierarchicalUriComponents expanding order

### ISSUE THREAD

**Issue by vitaly-sourikov** [spring-projects/spring-framework#22447]
The order, in which URI template variables are applied in org.springframework.web.util.HierarchicalUriComponents.expandInternal(UriTemplateVariables) is wrong. It should be in the order of URI parts: scheme, user, host, port, path, query, fragment. Instead, fragment is expanded after the schema. So, if variables are passed into UriComponentsBuilder.buildAndExpand, as an array, and there is a variable for the URI fragment going after other variables, the result will be incorrect. The bug was introduced in commit [f813712](https://github.com/spring-projects/spring-framework/commit/f813712f5b413b354560cd7cc006352e9defa9a3#diff-774d5dc1a5c7494860b8f715e5976d04).

**Comment by rstoyanchev** [comment]
You're right, this is a bug but the commit that introduced was cc74a2891a4d2a4c7bcec059f20c35aa80bcf668 (the one right after).
