### ISSUE TITLE
Data-Redis: JedisConnectionFactory ignores ssl settings in JedisCluster constructor call

### ISSUE THREAD

**Issue by hannes-angst** [spring-projects/spring-framework#22440]
**Affects:** data-redis:2.1.4

JedisConnectionFactory:418

     return StringUtils.hasText(getPassword())
				? new JedisCluster(hostAndPort, connectTimeout, readTimeout, redirects, 
     getPassword(), poolConfig)
				: new JedisCluster(hostAndPort, connectTimeout, readTimeout, redirects, poolConfig);

Use the `JedisCluster` constructor with ssl parameter, if `clientConiguration.useSsl` is true.

The current implementation fails without any logs when sending `sendCommand(AUTH)` because SSL ist not considered.
This results in a successful app start. The app will fail on the first redis server call, because the `JedisClusterConnectionHandler` class variable `cache` is empty.

**Comment by snicoll** [comment]
@hannes-angst thanks for the report but this is not the issue tracker for [Spring Data Redis](https://jira.spring.io/browse/DATAREDIS).

**Comment by hannes-angst** [comment]
I was actually able to fix this problem but it involved multiple dependencies going to all the way down to the jedis library. Core issue is the lack of having a  jedis constructor to pass ssl option in cluster mode. 
However, since the Spring Data Redis Team uses a different - not accessible  - Bug Tracker - and switched to lettuce anyways, closing this report its fine for me.
