### ISSUE TITLE
SpringFactoriesLoader.instantiateFactory(…) should report offending class on error

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#22453]
`SpringFactoriesLoader.instantiateFactory(…)` reports the name of the interface that implementations are looked up for. However, it does not report the name of the actual implementation class whose failed creation is likely to have caused the exception.

**Comment by jhoeller** [comment]
Isn't the implementation class name usually part of the nested exception anyway?

**Comment by odrotbohm** [comment]
It is indeed. I just thought that the primary exception message could reveal the original offender, especially as it states "Unable to instantiate *factory class*" but then prints the *interface* name.

**Comment by sbrannen** [comment]
@jhoeller, are you actively working on this?

**Comment by sbrannen** [comment]
I actually did something similar for the TestContext framework which uses `SpringFactoriesLoader` behind the scenes to find the factory class names:

https://github.com/spring-projects/spring-framework/blob/777b4c809d27575334abb4b954dd0089ceb8e1d4/spring-test/src/main/java/org/springframework/test/context/support/AbstractTestContextBootstrapper.java#L216-L231

So I'll improve the exception message in `SpringFactoriesLoader.instantiateFactory(…)` in a similar fashion.

**Comment by sbrannen** [comment]
@odrotbohm, are you satisfied with the outcome in f087fd5a93dbd43700e96f81088d1372263087c2?

**Comment by odrotbohm** [comment]
LGTM.
