### ISSUE TITLE
Consider consolidating WebMVC and WebFlux  CorsRegistry and CorsRegistration into Spring Web

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#22458]
`CorsRegistry` and `CorsRegistration` exist in both Spring WebMVC and WebFlux but look quite similar. None of the variants actually depend on anything stack specific and thus could live alongside the rest of the CORS code in the web module.

The code residing in stack specific modules causes issues in Spring Data REST, as (the WebMVC) `CorsRegistry` is referenced in its core `RepositoryRestConfiguration` that lives in a package that currently doesn't have a dependency on MVC and I'd prefer it to stay that way.

What's the reason these two very similar (if not identical) flavors of those classes exist?

**Comment by rstoyanchev** [comment]
Those are part of the public web framework config API, `@EnableWebMvc` and `@EnableWebFlux` respectively, all of which is co-located in one package in their respective module.

I don't fully understand the problem that this is causing. Why do you need to add a dependency on spring-webmvc now? It sounds like you were already using CorsRegistry.

**Comment by odrotbohm** [comment]
Up until now Spring HATEOAS had a mandatory dependency to Spring WebMVC. With our introduction of support for Spring WebFlux in that we made that optional. Thus, Spring Data REST Core doesn't transitively pull in Spring WebMVC anymore.

SD REST Core is designed to not depend on anything stack specific an we reference `CorsRegistry` from our generic `RepositoryRestConfiguration`. The dependency into Spring WebMVC went unnoticed so far due to Spring HATEOAS sneaking that in.

There doesn't seem to be anything stack specific in Spring's general CORS support. So I wondered if  `CorsRegistry` could live in the core web module with the stack specific implementations (annotations etc.) referring to that.

**Comment by rstoyanchev** [comment]
I'm afraid I don't see any easy ways to do that. Those are public API classes dating back to 4.2 and 5.0 respectively. We would have to add deprecate them, then add the replacements in spring-web, then add extra methods in `WebMvcConfigurer` and `WebFluxConfigurer` to accept them, and eventually remove the deprecated methods.

I still don't understand how Spring HATEOAS could be using these classes without using `WebMvcConfigurer#addCorsMappings` and `WebFluxConfigurer#addCorsMappings` which would imply some type of dependency (probably optional one) on spring-webmvc or spring-webflux.
