### ISSUE TITLE
Transaction Interceptor invoked twice for each method call

### ISSUE THREAD

**Issue by ZhangChaoWN** [spring-projects/spring-framework#22465]
**Affects:** \<Spring Framework version 4.3.11>

---

I add @Transactional on some methods, in the log I see that spring Transaction Interceptor invoked twice for each method call

by a debug tool, I found the service bean was proxied twice, transaction interceptor was invoke once in each proxy, for example, the original class name of service is FooService, there was a proxy class FooService$$***EnhancerBySpringCGLIB***4c8a0940@19210, I can see that proxy target is FooService, and there was another proxy class FooService$$***EnhancerBySpringCGLIBfa164332@13981, target is previous previous CGLIB proxy class FooService$$***EnhancerBySpringCGLIB***4c8a0940@19210.

I'm  not sure is this my configuration wrong or not, there are two behavior not expected: spring transaction should not enter transaction twice for single point cut of single method call and, spring AOP should not created multiple proxy class for single bean.

**Comment by ZhangChaoWN** [comment]
reason found, it's a configuration problem, I will close this issue.

**Comment by snicoll** [comment]
Thanks for the feedback.

**Comment by guilhermehenriquelopes** [comment]
@ZhangChaoWN, what configuration was the problem? I have the same issue.

**Comment by ZhangChaoWN** [comment]
> @ZhangChaoWN, what configuration was the problem? I have the same issue.

in my case, i found a bean of class: `org.springframework.aop.framework.autoproxy.DefaultAdvisorAutoProxyCreator` in my spring beans configuration, problem resolve after remove this bean.
