### ISSUE TITLE
Spring WebFlux and Undertow high cpu usage after perfromance test

### ISSUE THREAD

**Issue by lukidzi** [spring-projects/spring-framework#22467]
# Spring Boot Version
- spring-boot-starter-web:2.1.3.RELEASE 
- spring-boot-starter-undertow:2.1.3.RELEASE
- spring-boot-starter-webflux:2.1.3.RELEASE
- jdk 1.8.0.191
# Problem

Hi,

I was testing performance of 2 microservices(genareted from start.spring.io):
 - first microservice has one endpoint which returns String. I used spring-boot-starter-web:2.1.3.RELEASE and spring-boot-starter-undertow:2.1.3.RELEASE
 - second microservice has one endpoint which consume data from first microservice though WebClient and returns Mono<String>. I used spring-boot-starter-webflux:2.1.3.RELEASE and spring-boot-starter-undertow:2.1.3.RELEASE

After services started I ran performance test using wrk. After test finished I ran htop to check cpu usage and it was still high. Only restart of application helps.

After test cpu usage: 

<img width="830" alt="screenshot 2019-02-19 at 20 44 00" src="https://user-images.githubusercontent.com/13002762/53044221-b2b75000-348a-11e9-95bf-49b613b652f0.png">

 Also tested 2 other cases:
- replaced WebClient with RestTemplate
- changed server to Netty 

and high cpu problem didn't occurs.

So it must be the problem with combination of WebClient and Undertow. In profiler I saw that 2 NIO threads were busy for 993ms/1000ms after test. Problem shows up only after high load.

I tried to debug through code and I found that state is REQUESTED and it looks like infinite loop which process same event.
![screen](https://user-images.githubusercontent.com/13002762/53044398-28bbb700-348b-11e9-999b-dce99205c65b.png)

# Reproduction steps
Repository to reproduce problem with steps: https://github.com/lukidzi/springboot-undertow

**Comment by rstoyanchev** [comment]
The `FixedLengthOverflowException` is also reported under #22690.

**Comment by SillyMoo** [comment]
I have just come across this problem, digging a bit further I found that there is a loop where the onWritePossible handler in 'AbstractListenerWriteProcessor' is constantly called, the current state is 'REQUESTED'.

**Comment by colinmorelli** [comment]
Following up on @SillyMoo comments above, I'm seeing the same behavior. I have noticed that it does _not_ happen when the computation of the response can happen synchronously

I.E. The following route _will_ trigger this behavior:

```
POST("/test") {
    CompletableFuture.supplyAsync(Supplier { "test" }, executor).toMono().flatMap {
      ok().body(BodyInserters.fromObject(it))
    }
}
```

Whereas the following route _will not_ cause this:
```
POST("/test") {
    CompletableFuture.completedFuture("test').toMono().flatMap {
      ok().body(BodyInserters.fromObject(it))
    }
}
```

(CompletableFuture is being used in this example as that's where I discovered the issue in my app)

**Comment by rstoyanchev** [comment]
> I found that there is a loop where the onWritePossible handler in 'AbstractListenerWriteProcessor' is constantly called, the current state is 'REQUESTED'.

There was recent fix in `AbstractWriteListenerProcessor` in exactly this parts, see dd22b8fd3971c7b0cdc1976d45c81ba12d5da604. I confirmed that with Spring Framework 5.1.10.BUILD-SNAPSHOT the CPU returns to normal. I believe this issue has the same underlying cause as  #23096.
