### ISSUE TITLE
Unwrap CompletionException for MVC handlers that return CompletableFuture

### ISSUE THREAD

**Issue by sviperll** [spring-projects/spring-framework#22475]
CompletableFuture exceptions are always wrapped into CompletionException.
We need to unwrap CompletionException to properly handle exceptions in MVC handlers that return CompletableFuture.
Otherwise it's impossible to implement `@ExceptionHandler` in `@ControllerAdvice` to handle underlying exception.
See https://stackoverflow.com/questions/49676889/spring-controller-advice-does-not-correctly-handle-a-completablefuture-completed

**Comment by snicoll** [comment]
Duplicate of #22475

@sviperll if you intend to submit a PR, an issue is no necessary anymore.
