### ISSUE TITLE
@PathVariable causes other annotations to fail

### ISSUE THREAD

**Issue by SQDYY** [spring-projects/spring-framework#22479]
```java
    @GetMapping(value = "/info/{userid}")
    public Result info(@PathVariable("userid") @Min(value = 5,message = "测试") Long userid) {
        // ...
        return new Result().success();
    }
```

Example：`@Min`  from `javax.validation`，`@PathVariable` causes this annotation to fail

**Comment by sbrannen** [comment]
> Example：`@Min` from `javax.validation`，`@PathVariable` causes this annotation to fail

What do you mean by it causes it to fail?

What exactly does not work as you would expect?

Can you provide an error message or stack trace demonstrating the failure you encounter?

**Comment by sbrannen** [comment]
Also, is your controller class annotated with `@Validated`?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
