### ISSUE TITLE
'+'(Plus sign) interpreted as a ' ' (space) when using RestTemplate

### ISSUE THREAD

**Issue by morDevelop** [spring-projects/spring-framework#22488]
Hi,
I'm using Spring version: 5.0.6.RELEASE.
I have exactly the same issue as described here: [Stackoverflow#54294843](https://stackoverflow.com/questions/54294843/)

I'm sending the following GET request using the RestTemplate:
`GET http://localhost:9092/sites/?email=test+f@gmail.com`
When I'm using RestTemplate in attempt to send the request above,
`test+f@gmail.com` is being interpreted as`test f@gmail.com` ('+'  interpreted as ' ')

I'm looking for a solution that doesn't involve workarounds.

Bests.

**Comment by bclozel** [comment]
Hello @morDevelop 

See [this part of the reference documentation for the full picture](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#mvc-uri-building).

See [this particular issue](https://github.com/spring-projects/spring-framework/issues/21399) for a similar case and [this other issue which improves things](https://github.com/spring-projects/spring-framework/issues/21577).

In your particular case, you could go:

    URI uri = UriComponentBuilder.fromHttpUrl("http://localhost:9092/sites/")
        .queryParam("email", "{email}").encode().buildAndExpand("test+f@gmail.com"); 

Feel free to submit a better answer to this question on StackOverflow.

Thanks!
