### ISSUE TITLE
Integrates checkstyle build in PR checks

### ISSUE THREAD

**Issue by ledoyen** [spring-projects/spring-framework#22487]
Today, when submitting a PR, there is no community feedback if proposed code does not comply with checkstyle rules.

Only the core team can detect such an oversight and provides a feedback to external commiters.
It is time consuming for the core team (I assume :smile:), and does not avoid code containing new violations from being merged.

A quick action _could be_ to integrate a Travis build running `gradle check` to PR workflow.

**Comment by snicoll** [comment]
@ledoyen thanks for the feedback, we intend to move to concourse and add a pipeline to build pull requests.

**Comment by snicoll** [comment]
Superseded by #22490
