### ISSUE TITLE
Spring cache bug uses a method to call two methods that use the spring cache annotation (@CacheEvict and @Cacheable)

### ISSUE THREAD

**Issue by Bryce-huang** [spring-projects/spring-framework#22483]
i uses a method to call two methods that use the spring cache annotation (@CacheEvict and @Cacheable)
It does not work,
the code is like that:

    public class Cache{
    public void refreshCache(Long id){
    deleteCache(id);
    getCache(id);
    }
    @Cacheable(CacheNames="cache",key="#id")
    public List<String> getCache(Long id){
    do something
    }
    @CacheEvict(CacheNames="cache",key="#id")
    public void deleteCache(Long  id){}
    the version of srpingboot is 2.0.6 release
    }

when i use the method refreshCache（）,it does work.
but i use the deleteCache（） and getCache（） ，it works。
I don't like this code, it makes my code untidy。
it is a bug in the version of springboot 2.0.6 release?

**Comment by snicoll** [comment]
@Bryce-huang thanks for getting in touch, but as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. This looks like a question and I didn't understand what it was.

Rather than a code snippet, please share a minimal sample that we can run ourselves that demonstrates the problem you're describing (a zip or link to a github repo)

**Comment by Bryce-huang** [comment]
@snicoll thanks for your attention，i make a demo to reproduce the bug 。[spring bug demo](https://github.com/Bryce-huang/reproduce-bug)
please check the application.yml and than see com.bryce.spring.bug.BugApplicationTests。

**Comment by snicoll** [comment]
@Bryce-huang Thanks for the sample, that is very useful. Both those tests are passing with a in memory cache so there doesn't seem to be a problem with the cache abstraction.

The Spring Boot redis starer uses Lettuce, not Jedis so the `jedis.pool` part of your configuration is not taken into account. Perhaps you're upgrading from 1.5.x and you missed [that section in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#redis)?

I am going to close this as there is no indication of a bug in the framework. If you have more questions, please ask on StackOverflow.

**Comment by Bryce-huang** [comment]
@snicoll thanks bro， maybe I need to go to StackOverflow, but I still think this design is not friendly.
thanks anyway
