### ISSUE TITLE
Move CI to Concourse

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#22490]
A number of teams have moved their builds to https://ci.spring.io/ and crafted/shared scripts to automate the release process. That part alone is interesting as it is vastly superior to what the Bamboo integration can do.

I suggest we harmonize here as well, moving our `master` branch to Concourse, potentially cherry-picking in the `5.1.x` branch depending on the outcome of that work.

**Comment by bclozel** [comment]
I've done a first round of changes on master and we're publishing SNAPSHOTs with Concourse now. We also JDK variants (JDK11, JDK14 and JDK15) testing our build once a day.

I'm not closing this issue now as I'm working on the release pipeline now.

**Comment by bclozel** [comment]
Next steps:
- [ ] release a first version of [Concourse Release Scripts](https://github.com/spring-io/concourse-release-scripts)
- [ ] release a new version of [Concourse Java Scripts to support our new version scheme](https://github.com/spring-io/concourse-java-scripts/pull/10)
- [ ] add a Release group in the pipeline for Milestones (for a start)
