### ISSUE TITLE
JdbcTemplate.extractOutputParameters should preserve order of parameters

### ISSUE THREAD

**Issue by rhandsch** [spring-projects/spring-framework#22491]
While JdbcTemplate.call returns a LinkedHashMap created by createResultsMap() in order to preserve the order of output parameters of a stored procedure call, the method extractOutputParameters uses just a HashMap thus loosing the order of declared SqlOutParameters.
Please replace the HashMap my a LinkedHashMap so that the Map returned by call() uses the order of declared parameters.
Version: spring-jdbc:5.1.5

**Comment by jhoeller** [comment]
Good point, we're consistently using `LinkedHashMaps` for all stored procedure results processing now (and generally use smaller-sized maps for the intermediate results).

**Comment by rhandsch** [comment]
Wow, that was a quick response. Thanks, Jürgen!
