### ISSUE TITLE
Introduce `mode` attribute in @Transactional

### ISSUE THREAD

**Issue by 1991wangliang** [spring-projects/spring-framework#22492]
## Overview

I‘m TX-LCN distributed transaction framework developer (https://github.com/codingapi/tx-lcn).

Different distributed services may have different transaction modes under distributed systems. For example, there are three services A, B, and C, where A and C are relational databases. B is the NoSql variant. When A, B, and C participate in a transaction together, B cannot use the database variant for transaction management. B can adopt the TCC mode. Therefore, there are problems of coexistence of multiple transaction modes under this transaction. Our framework attempts to be unified with the JTA specification, but the extension of distributed transactions under tx is still annotated with `@Transactional`

Distributed transaction modes: TCC  LCN XA MQ TXC 

## Proposal

Introduce `mode` attribute in `@Transactional`.

```java
public @interface Transactional {


	//....
	
	/**
	 * Transactional model ,local Transactional used default value 'local'. distributed transaction can change this param.
	 * @return Transactional model default local . 
	 */
	String mode() default "local";

	//....
}
```

**Comment by sbrannen** [comment]
@1991wangliang,

Have you written your own custom `PlatformTransactionManager`?

Also, how would you foresee Spring supporting your proposed `mode` attribute in `@Transactional`?

**Comment by 1991wangliang** [comment]
@sbrannen ,Thanks for answers,With the development of Spring Cloud, microservice frameworks are becoming more and more popular. However, in a large-scale system, there are often many services that need to be involved, some using relational databases, some non-relational databases. Therefore, there must be a request that will span multiple modules, in the context of relational databases and non-relational databases, even in the case of file databases, it is necessary to adopt other ways to control coordination transactions.

**Comment by 1991wangliang** [comment]
Spring支持JTA模式，我们发现在Spring在配置事务信息的时候可以通过AOP方式控制，也可以通过@Transactional注解控制，但是我觉得@Transactional在事务支持是还是不够的，没法应对各种场景，需要增加提供模式切换的方式。
Spring supports JTA mode. We find that Spring can be controlled by AOP mode or @Transactional annotation when configuring transaction information. But I think @Transactional is not enough for transaction support. It is unable to deal with various scenarios, so we need to increase the mode switching mode.

**Comment by 1991wangliang** [comment]
![image](https://user-images.githubusercontent.com/5245347/53959406-83f1d880-411e-11e9-9b7d-d79f36ff88fd.png)
For example, there are service modules A, B, C. Module A is the service of MySQL as data source, module B is the service based on redis as data source, and module C is the service based on Mongo as data source. If they need to solve their transaction consistency, they need to adopt different schemes for different nodes, and coordinate the processing of distributed transactions.

**Comment by sbrannen** [comment]
@1991wangliang, thanks for providing more background information.

That helps to get a better overview, but I would still appreciate it if you could answer the following question.

> how would you foresee Spring supporting your proposed `mode` attribute in `@Transactional`?

In other words, do you expect Spring to _support_ your proposed `mode` attribute (and if so, how?), or do you expect Spring to simply make it available for others to process as they see fit?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
