### ISSUE TITLE
Jackson2Tokenizer ignores USE_BIG_DECIMAL_FOR_FLOATS deserialization feature

### ISSUE THREAD

**Issue by ilya-murzinov** [spring-projects/spring-framework#22510]
**Affects:** `spring-web-5.1.3.RELEASE`

---

In `org.springframework.http.codec.json.Jackson2Tokenizer` ctor `TokenBuffer` is created without passing `DeserializationContext` inside `com.fasterxml.jackson.databind.util.TokenBuffer`. This leads to `USE_BIG_DECIMAL_FOR_FLOATS` being ignored when parsing.

```java
private Jackson2Tokenizer(JsonParser parser, boolean tokenizeArrayElements) {
    Assert.notNull(parser, "'parser' must not be null");

    this.parser = parser;
    this.tokenizeArrayElements = tokenizeArrayElements;
    this.tokenBuffer = new TokenBuffer(parser); // <--- here
    this.inputFeeder = (ByteArrayFeeder) this.parser.getNonBlockingInputFeeder();
}
```

**Comment by ilya-murzinov** [comment]
@jhoeller unfortunately, this issue is not fixed, see https://github.com/spring-projects/spring-framework/commit/f6693e790a4ac10edb324e3051ca045478c796ae#r33105391

**Comment by jhoeller** [comment]
I've revised this to create a fully configured `DefaultDeserializationContext` within the tokenizer, analogous to Jackson's own standard code paths. This will make it into 5.2 M1 tomorrow and into 5.1.7 in early May.

**Comment by ilya-murzinov** [comment]
Thanks @jhoeller, I just tested your change and it works!
