### ISSUE TITLE
@AutoConfigureWireMock(port = 0) complains about using 'fixed port'

### ISSUE THREAD

**Issue by kiesslingh** [spring-projects/spring-framework#22528]
**Affects:** Spring Cloud Contract, 2.1.0.RELEASE

When annotating a class with `@AutoConfigureWireMock(port = 0)`, WireMock allocates a random port. However, in the log we find the following confusing message from `org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener`:
"You've used fixed ports for WireMock setup - will mark context as dirty. Please use random ports, as much as possible. Your tests will be faster and more reliable and thiswarning will go away".

This seems to be untrue on several accounts:
- A random port is used as expected, as is verifiable in the debugger
- Marking the context as dirty makes the tests way slower, as can be seen when using `@DirtiesContext` explicitly
- Nevertheless, the warning does not go away

---

**Comment by sbrannen** [comment]
Hi @kiesslingh,

This is the issue tracker for the core Spring Framework.

For Spring Cloud Contract, please [open an issue here](https://github.com/spring-cloud/spring-cloud-contract/issues).
