### ISSUE TITLE
STOMP WebSocket not working on Spring Boot 2.1.3

### ISSUE THREAD

**Issue by SaeedMasoumi** [spring-projects/spring-framework#22527]
I run [this](https://github.com/spring-guides/gs-messaging-stomp-websocket) sample using gradle and connect to the socket from my android client using this [library](https://github.com/NaikSoftware/StompProtocolAndroid).

It works fine, but when I upgrade the Spring Boot version to `2.1.3-RELEASE` my clients (except the web panel in the project) can't send or receive messages.

**Comment by rstoyanchev** [comment]
What version does it work with? How does it fail, any errors, log messages? Please provide a more complete description.

**Comment by SaeedMasoumi** [comment]
It works with the version in the sample project (`2.0.5-RELEASE`). It doesn't show any errors.
For a sample project, just bump the version in the sample project .

**Comment by chc123456** [comment]
Starting from 2.1.0, the HandshakeHandler setting does not work.

**Comment by chc123456** [comment]
Like this
```Java
    registry.addEndpoint("/message-webSocket").setHandshakeHandler(
                new DefaultHandshakeHandler() {
                    @Override
                    protected Principal determineUser(ServerHttpRequest request, WebSocketHandler wsHandler, Map<String, Object> attributes) {
                        String query = request.getURI().getQuery();
                        String[] q = query.split("=");
                        return new StompPrincipal(q[1]);
                    }
                }

        ).setAllowedOrigins("localhost", "*").withSockJS();
```
These codes work fine in version 2.0.x but not on 2.1.x.

**Comment by rstoyanchev** [comment]
The sample works with 2.1.6 (and 2.1.3). It works with the given `HandshakeHandler` snippet too. I am unable to reproduce the issue with the given instructions.
