### ISSUE TITLE
Revisit BeanUtils.instantiateClass to work consistently with Kotlin and Java classes

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#22531]
`BeanUtils.instantiateClass` is an interesting way to create a class as it takes care of kotlin features behind the scenes for you. There is a slightly mismatch with Java though.

If a parameter is not available for a primitive type, we need to specify the default value for the primitive type (i.e. `0` for `int` and `false` for `boolean`). With Kotlin, you have to pass `null` as the parameter may have a default value that we shouldn't be overriding. 

Consider the following example:

```java
class JavaExample {

  JavaExample(int counter, boolean flag, String value) { ... }
}
```

```kotlin
class KotlinExample(val counter : Int = 0, val flag: Boolean = false, val value : String?) { ... }
```

Let's assume we have a value for the `value` parameter and no information for the `counter` or `flag`. 

Java requires us to provide `[0, false, "my value"]`
Kotlin requires us to provide `[null, ,null, "my value"]`

An improvement would be to provide only the latter and let the internal implementation translates `null` to the proper default value if the parameter is primitive.

This will benefit https://github.com/spring-projects/spring-boot/issues/8762 where we're currently computing the array differently depending on the fact the target type is kotlin or not.

**Comment by sdeleuze** [comment]
We can probably get an even more consistent behavior between Java and Kotlin by leveraging `KParameter.isOptional` to set the default value of Kotlin equivalent of Java's primitive types when no default value is provided.

**Comment by snicoll** [comment]
Indeed, thanks for following-up. In the case of my example, this would mean that the following declaration works consistently:

```kotlin
class KotlinExample(val counter : Int, val flag: Boolean, val value : String?) { ... }
```

**Comment by sdeleuze** [comment]
Fixed on `master`, `KParameter.isOptional` was already used on Kotlin side so I just added support for Java primitive types.
