### ISSUE TITLE
ServletWebRequest.getHeaderValues throwing NPE when header information is not available

### ISSUE THREAD

**Issue by ketsorbit** [spring-projects/spring-framework#22547]
in ServletWebRequest class -> getHeaderValues() method:

getRequest().getHeaders(headerName) may return null .. and so, StringUtils.tostringArray() throws Null Pointer Exception.

**Comment by philwebb** [comment]
This looks like a framework bug so I've transferred the issue.

**Comment by jhoeller** [comment]
A `null` return value is defined to only happen if "the container does not allow access to header information" according to the `HttpServletRequest` javadoc... In any case, we should handle this defensively.

**Comment by jhoeller** [comment]
This turns out to be a regression from 4.3.x, introduced during our 5.0 nullability revision of `StringUtils`.
