### ISSUE TITLE
FormHttpMessageConverter should use ISO-8859-1 charset as default for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-framework#22548]
FormHttpMessageConverter currently uses utf-8 as the default encoding for reading and writing the `application/x-www-form-urlencoded` content type when no `charset` parameter is specified.

However, the default really should be ISO-8859-1 (aka ASCII aka Windows-1252) as that's what specified in the IANA registration: https://www.w3.org/TR/2016/WD-html51-20160310/iana.html#application-x-www-form-urlencoded

It's also what browsers and servers expect when no charset parameter is specified.

I'm reporting this issue as FormHttpMessageConverter always writes forms as `application/x-www-form-urlencoded;charset=utf-8` and the application receiving that data doesn't expect that - it requires `application/x-www-form-urlencoded` (notably without the charset), and it (correctly) expects that since there is no charset specified it will receive ISO-8859-1 encoded data.

Also, if the charset is ISO-8859-1 when writing `application/x-www-form-urlencoded`, then the content-type written should be `application/x-www-form-urlencoded` without the charset set (since the charset is the default, it should not be specified).

**Comment by rstoyanchev** [comment]
The switch from "ISO-8859-1" to "UTF-8" as the default dates back to version 3.0.6, issue #12445. Switching to the previous default 8+ years later would be odd to say the least and more importantly it would be a step back to switch to ISO-8859-1 as a default for anything in 2019! 

The recommendation from `URLEncoder#encode` which we use for encoding:

> Note: The World Wide Web Consortium Recommendation states that UTF-8 should be used. Not doing so may introduce incompatibilities.

HTML 5.2 points to UTF-8 consistently as the default encoding in the [form submission](https://www.w3.org/TR/html52/sec-forms.html#selecting-a-form-submission-encoding) section. 

I don't see what evidence you have. The link you provided is from a 5.1 draft which doesn't contradict and simply says it's octets (i.e. encoded).
