### ISSUE TITLE
Skip more classes when processing beans in EventListenerMethodProcessor

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22564]
The `EventListenerMethodProcessor` currently skips beans where`isSpringContainerClass` returns true. There are a few more types that we could also consider skipping:

* Anything in `java.lang` classes
* Any `java.util` classes
* Any `javax.servlet` classes

All of these turn out to be pretty common beans in Spring Boot applications.

**Comment by philwebb** [comment]
This may have been superseded by e3a9826e56e8fcb9e57f31b255998a095d8f8155 which by default will skip `java*` types.

**Comment by jhoeller** [comment]
I'll consider this for a backport to 5.1.6, even if it is generally covered on master already.
