### ISSUE TITLE
Add AssertJ for use in our own tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22561]
AssertJ provides a very nice fluent assertions style that in my opinion is easier to read and more consistent than Hamcrest. I'd like to add it as a test dependency and make use of it when testing the new `MergedAnnotations` API. Using AssertJ `assertThatExceptionOfType...` calls instead of `@Rule ExpectedException` will also help if we decide to migrate our tests to JUnit5.

Spring Boot tests have been written exclusively with AssertJ for some time now.

**Comment by sbrannen** [comment]
I'm totally in favor of using AssertJ in our own test suite. I miss it each time I write/update a test.

**Comment by sbrannen** [comment]
**Team Decision**: Allow the use of AssertJ within our test suite but do not migrate all existing assertions to AssertJ for the time being.
