### ISSUE TITLE
PDF Documentation Spring-Core 5.1.5: Occurrences of a STRONG tag, where we should see a bold font

### ISSUE THREAD

**Issue by molzb** [spring-projects/spring-framework#22577]
Documentation Spring-Core 5.1.5 as PDF
https://docs.spring.io/spring/docs/current/spring-framework-reference/pdf/core.pdf

There are code samples with a (written) `<strong>` tag, where we should see the code section with a bold font.

Examples:
Page 50:  `<strong>@RequestScope</strong>`
Page 62: `<strong>@SessionScope</strong>`
and 29 more occurrences. Please use Ctrl+F.

**Comment by jhoeller** [comment]
@bclozel Could you have a look at this please? I suppose those tags were in actual effect at some point but got turned to literal text through some general formatting changes...

**Comment by sbrannen** [comment]
My guess is that it is the presence of asterisks within code blocks that were carried over from the Docbook days and that the PDF generator simply doesn't support that.

**Comment by sbrannen** [comment]
> @bclozel Could you have a look at this please?

@bclozel, I'd be happy to take it over unless you want to. Just let me know...

**Comment by jhoeller** [comment]
@sbrannen, volunteering is always appreciated, so it's yours now :-)

I was just asking Brian since he did some recent doc formatting stuff for 5.2.
