### ISSUE TITLE
Add public getDeclaredMethods method to ReflectionUtils

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22580]
Although we can't directly expose the raw array of declared methods that we cache, there is still some benefit in having a public method that exposes a cloned copy. Specifically allows us to save security checks and it reduces the number of `Method` instances created. It's also often faster than calling `doWithLocalMethods` and needing to create a callback.

**Comment by mrifni** [comment]
can I pick this up with some guidance ?
