### ISSUE TITLE
Migrate InitDestroyAnnotationBeanPostProcessor to MergedAnnotations

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22583]
`InitDestroyAnnotationBeanPostProcessor` would benefit from using the new `MergedAnnotations` API directly.

**Comment by jhoeller** [comment]
On review, for direct checks against plain annotations which will are never to be merged, we're better off with direct `AnnotatedElement.isAnnotationPresent` checks which work against internally cached data structures in the element and don't cause any GC overhead. `InitDestroyAnnotationBeanPostProcessor` is a good example here, and so is `CommonAnnotationBeanPostProcessor` which I'll revert back to direct `isAnnotationPresent` checks. This is also in line with `PersistenceAnnotationBeanPostProcessor` which can stay as-is then.
