### ISSUE TITLE
Short circuit merged annotation searches for marker annotations

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#22610]
## Status Quo

Annotation search algorithms that return merged annotations (e.g., `getMergedAnnotation()` and `findMergedAnnotation()` in `AnnotatedElementUtils`) currently perform a complex search, conversion of attributes to a map, and conversion back into a merged, synthesized annotation _even if_ the sought annotation is a "marker annotation" (i.e., an annotation with no attributes).

One could argue that the caller should never request Spring to find/get a merged annotation for a sought marker annotation; however, I have recently seen such a use case where the implementer was simply unaware of the fact that it doesn't make sense to merge non-existing attributes. On the other hand, some framework code may blindly invoke "merging" search algorithms simply because it is not known in advance if the sought annotation type is a marker annotation.

## Proposal

Update affected search algorithms to forgo the expensive "merged" search and instead perform a simple search for the marker annotation (e.g., potentially via `getAnnotation()` or `findAnnotation()` in `AnnotationUtils`).

Note that if `AnnotationUtils.getAttributeMethods(Class<? extends Annotation> annotationType)` returns an empty list, that means that the `annotationType` is a marker annotation.

**Comment by sbrannen** [comment]
@philwebb, does your `MergedAnnotation` work make this proposal obsolete?

**Comment by sbrannen** [comment]
Actually, now that I think about it, we could probably short circuit all annotation searches that involve the creation of `AnnotationAttributes` behind the scenes if the sought annotation is a marker annotation since `AnnotationAttributes` would always be empty for such annotations.

**Comment by philwebb** [comment]
The new code no longer creates `AnnotationAttributes`. `TypeMappedAnnotation` stores a `rootAttributes` instance (usually the raw annotation) and a `valueExtractor` function (usually `ReflectionUtils::invokeMethod` so I'm not sure there's much to optimize.

**Comment by sbrannen** [comment]
OK, @philwebb. Thanks for the feedback and explanation.
