### ISSUE TITLE
Update documentation for WebJar support

### ISSUE THREAD

**Issue by xak2000** [spring-projects/spring-framework#22613]
Following the discussion in https://github.com/spring-projects/spring-framework/pull/1685#issuecomment-474042425 the documentation should be updated to reflect the fact that dependency should be `org.webjars:webjars-locator-core` instead of `org.webjars:webjars-locator`:

- webmvc.adoc
- webflux.adoc
- org.springframework.web.reactive.resource.WebJarsResourceResolver
- org.springframework.web.servlet.resource.WebJarsResourceResolver

**Comment by sbrannen** [comment]
Thanks for raising the issue.

I've made the changes and pushed them to `5.0.x`, `5.1.x`, and `master`.
