### ISSUE TITLE
RequestMapping produces 406 Not Acceptable

### ISSUE THREAD

**Issue by zollty** [spring-projects/spring-framework#22623]
I am running on Spring/Spring MVC 4.3.22. I have a controller as follows:
```java
@RequestMapping(value = "byclientid/{clientId}", produces = MediaType.APPLICATION_JSON_VALUE)
public String statsByClientId(@PathVariable("clientId") String clientId, ModelMap m) {
    ClientStat e = statsService.getCountForClientId(clientId);

    m.put(JsonEntityView.ENTITY, e);

    return JsonEntityView.VIEWNAME;
}
```
URIs in this format:
[http://x.x.x.x/api/stats/byclientid/{clientId}](http://x.x.x.x/api/stats/byclientid/{clientId})
will be matched.    

When I make a request to     
[http://x.x.x.x/openid-connect-server/api/stats/byclientid/27461968070-nu8bpk3k0lvdnoin97vu9vj278e1lo80.usercontent.github.io?_=1553139119816](http://x.x.x.x/openid-connect-server/api/stats/byclientid/27461968070-nu8bpk3k0lvdnoin97vu9vj278e1lo80.usercontent.github.io?_=1553139119816),     
 it's OK, but when I request to     
[http://x.x.x.x/openid-connect-server/api/stats/byclientid/167480702619-8e1lo80dnu8bpk3k0lvvj27noin97vu9.apps.googleusercontent.com?_=1553139120932](http://x.x.x.x/openid-connect-server/api/stats/byclientid/167480702619-8e1lo80dnu8bpk3k0lvvj27noin97vu9.apps.googleusercontent.com?_=1553139120932)，   
I got an `406 Not Acceptable` error.

This problem confused me, The two URLs are similar, but got the totally different results!   
so I debugged the source code. I found `AbstractMappingContentNegotiationStrategy` as follows: 

```java
public abstract class AbstractMappingContentNegotiationStrategy ...{
	@Override
	public List<MediaType> resolveMediaTypes(NativeWebRequest webRequest)
			throws HttpMediaTypeNotAcceptableException {

		return resolveMediaTypeKey(webRequest, getMediaTypeKey(webRequest));
	}

	/**
	 * An alternative to {@link #resolveMediaTypes(NativeWebRequest)} that accepts
	 * an already extracted key.
	 * @since 3.2.16
	 */
	public List<MediaType> resolveMediaTypeKey(NativeWebRequest webRequest, String key)
			throws HttpMediaTypeNotAcceptableException {

		if (StringUtils.hasText(key)) {
			MediaType mediaType = lookupMediaType(key);
			if (mediaType != null) {
				handleMatch(key, mediaType);
				return Collections.singletonList(mediaType);
			}
			mediaType = handleNoMatch(webRequest, key);
			if (mediaType != null) {
				addMapping(key, mediaType);
				return Collections.singletonList(mediaType);
			}
		}
		return Collections.emptyList();
	}
}
```
the `getMediaTypeKey(webRequest)` method return `"com"`, and the `mediaType` = `"application/x-msdownload"`. So I understand what's going on. The ProduceMediaType doesn't match the `"application/x-msdownload"`.

But I don't think that should happen. Can I say this is a bug?

Affects: 4.3.22
See also #19751

**Comment by nkjackzhang** [comment]
You can try to use encodeURL the param.If a URL end with ".com",".txt" or something else, it's make spring easily thinking of you are downloading something.

**Comment by rstoyanchev** [comment]
How to resolve the content type to use is in your control and [can be configured](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-content-negotiation) so no this isn't a bug. You can turn off matching by path extension completely, or you can configure the exact extensions that should be matched. 

Note that for some time now we recommend turning off matching by path extension completely and relying mainly on the Accept header. Please [read this](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-requestmapping-suffix-pattern-match) in the docs.

**Comment by zollty** [comment]
Thanks for the explanation.    

According to this docs, to completely disable the use of file extensions, we must set both of the following:    
+ `useSuffixPatternMatching(false)`, see [PathMatchConfigurer](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-path-matching)
+ `favorPathExtension(false)`, see [ContentNegotiationConfigurer](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-content-negotiation)

Why not turn it off by default?   
I think most people don't know what's going on when they encounter this problem.
And URIs in this format:
http://x.x.x.x/api/stats/byclientid/{clientId}
It's a little special, the `clientId` may include `".com"`,`".123"`,`".io"` which we can't predict, and it's hard to find this problem during testing.
