### ISSUE TITLE
[RestTemplate] buffering of POST request cause OutOfMemory

### ISSUE THREAD

**Issue by theghost5800** [spring-projects/spring-framework#22627]
**Affects:** spring-framework-5.1.2.RELEASE

---
I have spring application which upload zip files to server(which I don't own). My issue is related with uploading large ZipFiles using RestTemplate. When I try to make http request RestTemplate load in-memory the whole file before start uploading. I have tried to use  [Http Streaming feature](https://github.com/spring-projects/spring-framework/pull/312) but the server doesn't support chunks streaming, it is require to set http header `Content-Length` to upload content. I found that in Apache Http Client version 4.4 provides HttpEntity interface which do not cache the whole request in-memory. If you add File in MultiparEntityBuilder `Content-Length` of the request is calculated without reading and loading the file in-memory.  When http request has been executed apache httpclient open FileStream to the file and directly send bytes to the server. I would like to ask why in Spring RestTemplate this is not implemented in this way? Is it possible RestTemplate to be enhanced to calculate Content-Length size of request without loading content in-memory?

**Comment by rstoyanchev** [comment]
As [mentioned in the docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#webmvc-client) and on other issues here, we don't intend to make further enhancements to the `RestTemplate`. If the same scenario does not work with the `WebClient` we will consider changes there. However if you set the Content-Length there and provide a Resource it should just work.
