### ISSUE TITLE
Custom CacheInterceptor is being randomly overridden by default Spring's CacheInterceptor

### ISSUE THREAD

**Issue by YashchenkoN** [spring-projects/spring-framework#22641]
I've asked a question on the stackoverflow https://stackoverflow.com/questions/55299059/custom-cacheinterceptor-is-being-overridden-by-default-springs-cacheinterceptor

I've create this issue because of strange behaviour of Spring: sometimes it overrides my custom bean, sometimes it doesn't override it. I didn't find any reason of such behaviour.

Looks like a bug.

Versions
Spring - 5.0.7.RELEASE
Spring Boot - 2.0.0.RELEASE

**Comment by snicoll** [comment]
In the interest of keeping the conversation in one place, let’s follow up on stackoverflow.
