### ISSUE TITLE
JdbcOperationsExtensions.queryForObject overload which takes in lambda - allow null value to be returned?

### ISSUE THREAD

**Issue by yonigibbs** [spring-projects/spring-framework#22682]
In `JdbcOperationsExtensions.kt`, there is [this](https://github.com/spring-projects/spring-framework/blob/0ace0be29b43ca5a567d69f6804ba41880c63c29/spring-jdbc/src/main/kotlin/org/springframework/jdbc/core/JdbcOperationsExtensions.kt#L37) overload of `queryForObject`:

```
fun <T : Any> JdbcOperations.queryForObject(sql: String, vararg args: Any, function: (ResultSet, Int) -> T): T? =
    queryForObject(sql, RowMapper { resultSet, i -> function(resultSet, i) }, *args)
```

This calls down to [this](https://github.com/spring-projects/spring-framework/blob/0ace0be29b43ca5a567d69f6804ba41880c63c29/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcOperations.java#L574) method in `JdbcOperations.java`:

```
<T> T queryForObject(String sql, RowMapper<T> rowMapper, @Nullable Object... args) throws DataAccessException;
```

The JavaDocs for that Java method states this:

```
@return the single mapped object (may be {@code null} if the given
{@link RowMapper} returned {@code} null)
```

This suggests that it's valid for this method to return null, which also corresponds with the Kotlin overload returning `T?` (as opposed to the non-nullable `T`).  However, the lambda passed into the Kotlin method (which is translated into a `RowMapper` when calling the Java code) **cannot** return null:

`function: (ResultSet, Int) -> T`

Is that a mistake?  Should this lambda be declared as returning `T?` instead?

Note that a similar (but not identical) issue was discussed in #1603.

Also see discussion in [this](https://stackoverflow.com/a/55341087/10326373) SO answer.

**Comment by yonigibbs** [comment]
@sdeleuze: as you can see in the comments in the [SO answer I linked](https://stackoverflow.com/a/55341087/10326373), Alexey Romanov also suggested maybe these overloads should be `inline`. Do you agree? If so, do you want me to log a separate issue for this?

**Comment by sdeleuze** [comment]
I only targeted 5.1.x because this change implies changing API nullability of `JdbcOperations` extensions.

@yonigibbs We can discuss that in the SO before creating another issue.

On a related note, be aware that I also plan to update `JdbcOperationsExtensions` to infer nullability of return types

**Comment by yonigibbs** [comment]
Thanks @sdeleuze. Very quick turnaround! :-)

One quick question about the fix. The new line of code is now this:

```
fun <T : Any?> JdbcOperations.queryForObject(sql: String, vararg args: Any, function: (ResultSet, Int) -> T): T? = ...
```

So you can make `T` some nullable type, and that way the lambda, `function`, can return null, as `T` is nullable.  But the actual method, `queryForObject`, is marked as returning `T?` rather than `T`, which I almost read as "a nullable version of a nullable type". Is it right that this method returns `T?` when the lambda returns `T` ?  Shouldn't they both return the same type?

(Maybe this whole question is moot given your comment about updating this class to infer the nullability of the return types.)

**Comment by sdeleuze** [comment]
This is intentional, I only did a partial update of the API in order to avoid breaking APIs while still leveraging type inference to infer what should be the lambda return type.

What you describe is indeed the changes I am about to commit on `master` branch only as part of #22687.

**Comment by alexeyr** [comment]
If you do

    fun <T> JdbcOperations.queryForObject(sql: String, vararg args: Any, function: (ResultSet, Int) -> T): T

(note no constraint) you'll get nullable return type iff `function`'s return type is nullable, which expresses exactly what `RowMapper`'s documentation does.

**Comment by sdeleuze** [comment]
Good point, but I will do these changes as part of #22687.
