### ISSUE TITLE
AnnotationUtils.isAnnotationMetaPresent(…) no longer considers javax.annotation.Nonnull

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#22685]
Consider the following code in which a package is annotated with `@NonNullApi`:

`package-info.java`

```java
@NonNullApi
package foo;

import org.springframework.lang.NonNullApi;
```

Reproducer

```java
package foo;

import javax.annotation.Nonnull;

import org.junit.Test;

import org.springframework.core.annotation.AnnotationUtils;
import org.springframework.lang.NonNullApi;

import static org.junit.Assert.*;

public class ReproducerTest {

	@Test
	public void shouldFindMetaAnnotation() {

		NonNullApi annotation = getClass().getPackage().getAnnotation(NonNullApi.class);

		assertTrue(AnnotationUtils.isAnnotationMetaPresent(annotation, javax.annotation.Nonnull.class));
	}
}
```

Using `AnnotationUtils.isAnnotationMetaPresent(…)` for annotation discovery fails to report that `NonNullApi` is a meta-annotation for `javax.annotation.Nonnull`.

Spring Data uses [JSR 305-based nullability inference](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/util/NullableUtils.java) for repository method arguments and return value inspection

**Comment by mp911de** [comment]
We have the same issue for meta-annotations originating from JSR305, e.g. `javax.annotation.ParametersAreNonnullByDefault`. This is a meta-annotation for `javax.annotation.Nonnull`. Do you want to fix the issue with the same ticket or should we create a new ticket?

**Comment by jhoeller** [comment]
Let's use the same ticket. It seems we need to apply the same code path to meta-annotated `javax.annotation` types.

**Comment by jhoeller** [comment]
A quick note: `AnnotationUtils.isAnnotationMetaPresent` is deprecated as of 5.2, along with several other too-specific utility methods. Alternatively, for a unified method, `AnnotatedElementUtils.isAnnotated` (which covers meta-annotations as well) remains non-deprecated.
