### ISSUE TITLE
Upgrade to reactor-netty 0.8.6 for Webflux

### ISSUE THREAD

**Issue by lpellegr** [spring-projects/spring-framework#22693]
Version 0.8.6 fixes an important issue with IPv6:

https://github.com/reactor/reactor-netty/issues/625

Here are the full release notes:

https://github.com/reactor/reactor-netty/releases

**Comment by jhoeller** [comment]
We've upgraded to Reactor Californium SR6 (which includes Reactor Netty 0.8.6) for the upcoming Spring Framework 5.1.6 release. However, please note that it is an optional dependency at the core level; the dependency management upgrade for applications will happen in Spring Boot 2.0.9.
