### ISSUE TITLE
AnnotatedElementUtils.getAllAnnotationAttributes(…, "javax.annotation.Nonnull") returns null

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#22696]
Calling `AnnotatedElementUtils.getAllAnnotationAttributes(…, "javax.annotation.Nonnull")` with version `5.2.0.BUILD-SNAPSHOT` for `org.springframework.lang.NonNullApi.class` and `javax.annotation.ParametersAreNonnullByDefault.class` annotation types returns `null`. 

Previously (5.1 and earlier), the method returned `MultiValueMap` containing annotation attributes.

**Comment by jhoeller** [comment]
Aside from this being a regression that's worth fixing: What kind of algorithm is this? Couldn't you simply use the standard reflection API for annotation introspection purposes there? I'm surprised that standard javax annotations are introspected as attribute value maps...

**Comment by mp911de** [comment]
In Spring Data we support annotations and meta-annotations that are annotated with JSR305 annotations to discover whether a package, class or method has opted-in for non-nullability. We do not express a limit on meta-annotation nesting, so one can use either directly JSR305 annotations, Spring Framework annotations (that are annotated with JSR305) or further, composed annotations. 

That's, why we are using `AnnotatedElementUtils`. `@Nonnull`'s `when` attribute expresses non-nullability or allows opting out to express that a particular argument or return value may be null.
