### ISSUE TITLE
Add route(RequestPredicate, HandlerFunction) variant to RouterFunctions builder

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-framework#22701]
Hi 

I really like the new functional reactive endpoint style 

```
route()
 .GET("/foo" , getHandlerFunction)
 .POST("/foo", postHandlerFunction)
 .build()
``` 

Sometimes however I don't want to use the existing `RequestPredicate` shortcuts. I'd like to use my own `RequestPredicate` implementation. In the old style this was easy enough to do. I could say 

```
RequestPredicate rp = r -> Math.random() > .5 ;
return route(rp, myHandlerFunction)
      .andRoute( ...) 
```

i'm now not quite sure on what the best way to do that in the new style is. this works, but i get the feeling that its re-creating things that dont need to be re-created. 

```

 Consumer<RouterFunctions.Builder> handler() {
  RouterFunction<ServerResponse> handler = r -> Mono.just(r1 -> ok()
	   .syncBody("Hello, " + r1.queryParam("name").orElse("world") + "!"));
		return builder -> builder.add(route().add(handler).build());
	}


RequestPredicate rp = ... ; 

return route()
  .nest(rp, handler())
  .build();
```

please provide a shortcut for something like: 

```
route()
 .route(RequestPredicate, HandlerFunction<ServerResponse>)
 .build()
```

**Comment by poutsma** [comment]
There is `add`, which you can combine with the "old-style" `route`, like so:

```
RequestPredicate rp = r -> Math.random() > .5 ;
route()
 .GET("/foo" , getHandlerFunction)
 .POST("/foo", postHandlerFunction)
 .add(route(rp, myHandlerFunction))
 .build()
```

Is this good enough? Or do you still prefer to have a separate `route.route(RequestPredicate, HandlerFunction)` method added to the builder?

**Comment by joshlong** [comment]
A separate `route`/`add` or whatever you prefer that takes RequestaPredicare / HandlerFunction Would be preferable as it’s not clear to me, at least, that you’d need to call `route(...)` to build a thing that add could accept. This is probably because everything is a lambda and I don’t spend a lot of time looking at actual types. Either way, would be nice to have a method that looks like route(..) in the older DSL. Thanks in advance
