### ISSUE TITLE
Deprecate ClassUtils.isCglibProxy methods

### ISSUE THREAD

**Issue by akiraly** [spring-projects/spring-framework#22706]
**Affects:** Spring Framework Core 4.x, 5.x with both Java 8 and Java 11

This test fails at the second assertion:

```java
  @Test
  public void testLambdaIsNotACglibProxy() {
    
    Runnable anonymous = new Runnable() {
      @Override
      public void run() { 
      }
    };

    System.out.println(anonymous.getClass());
    assertFalse(ClassUtils.isCglibProxy(anonymous));

    Runnable lambda = () -> {};
  
    System.out.println(lambda.getClass());
    assertFalse(ClassUtils.isCglibProxy(lambda)); // <-- fails
  }
```

It fails because the lambda expression will have a class name like: `class spring.ClassUtilsTest$$Lambda$231/0x0000000800149440` and `isCglibProxy()` treats everything as a cglib proxy which has a `$$` in the class name.

`isCglibProxy()` should have a better check so it would return false for lambda objects.

**Comment by jhoeller** [comment]
This entire `isCglibProxy` business at the `ClassUtils` is a candidate for deprecation. We only really need it in `spring-aop` when testing proxy superclasses (which are never lambdas to begin with), so we should have a semantically narrower test there instead of the general utility methods at `ClassUtils` level.

**Comment by akiraly** [comment]
To give some more background: Apache CXF is also [using these methods](https://github.com/apache/cxf/blob/540bb76f6f3d3d23944c566905f9f395c6f86b79/core/src/main/java/org/apache/cxf/common/util/SpringAopClassHelper.java#L86) and in that case it is possible to hit this method using lambda expressions.

I have opened a [ticket ](https://issues.apache.org/jira/browse/CXF-8009)for CXF to not to use `ClassUtils` for cglib checks.

**Comment by sbrannen** [comment]
@akiraly, thanks for raising the issue with the CXF team.
