### ISSUE TITLE
Too many NotWritablePropertyExceptions if a Spring MVC controller binds request parameters onto multiple command objects

### ISSUE THREAD

**Issue by gihub-zuoyan** [spring-projects/spring-framework#22712]
springboot 1.5.13.RELEASE

Given code like this:

```java
    @RequestMapping("query")
    public Object queryAd(@Validated QueryRequest v1, @Validated ADRequest  v2) {
    }
```

I find if the HTTP request parameters should bind onto `ADRequest`, Spring throws a `NotWritablePropertyException`.

I found the following code in `org.springframework.validation.DataBinder`. 

```java
	protected void applyPropertyValues(MutablePropertyValues mpvs) {
		try {
			// Bind request parameters onto target object.
			getPropertyAccessor().setPropertyValues(mpvs, isIgnoreUnknownFields(), isIgnoreInvalidFields());
		}
		catch (PropertyBatchUpdateException ex) {
			// Use bind error processor to create FieldErrors.
			for (PropertyAccessException pae : ex.getPropertyAccessExceptions()) {
				getBindingErrorProcessor().processPropertyAccessException(pae, getInternalBindingResult());
			}
		}
	}
```

And the following code in `org.springframework.beans.AbstractNestablePropertyAccessor`.

```java
	@Override
	public void setPropertyValue(PropertyValue pv) throws BeansException {
		PropertyTokenHolder tokens = (PropertyTokenHolder) pv.resolvedTokens;
		if (tokens == null) {
			String propertyName = pv.getName();
			AbstractNestablePropertyAccessor nestedPa;
			try {
				nestedPa = getPropertyAccessorForPropertyPath(propertyName);
			}
			catch (NotReadablePropertyException ex) {
				throw new NotWritablePropertyException(getRootClass(), this.nestedPath + propertyName,
						"Nested property in path '" + propertyName + "' does not exist", ex);
			}
			tokens = getPropertyNameTokens(getFinalPath(nestedPa, propertyName));
			if (nestedPa == this) {
				pv.getOriginalPropertyValue().resolvedTokens = tokens;
			}
			nestedPa.setPropertyValue(tokens, pv);
		}
		else {
			setPropertyValue(tokens, pv);
		}
	}
```

My classes look like this:

```java
class QueryRequest {
        private String qr1;
        private String qr2;
        private String qr3;
}

class ADRequest {
        private String ar1;
        private String ar2;
        private String ar3;
        private String ar4;
        private String ar5;
        private String ar6;
        private String ar7;
        private String ar8;
        private String ar9;
        private String ar10;
        private String ar11;
        // ...
        private String ar100;
}
```

My request URL looks like this `/query?qr1=123&qr2=133&qr3=2333&ar1=ar123&ar2=ar133&.ar3=ar2333...&ar100=ar1233`

When Spring binds data to `QueryRequest`, it cannot find fields (ar1,ar2, ...,  ar100) and will throw almost 100 `NotWritablePropertyException`s. This makes my app slower and results in more young GC.

I hope when binding parameters onto `QueryRequest` (that should bind to `ADRequest`) will not throw `NotWritablePropertyException`.

**Comment by rstoyanchev** [comment]
@gihub-zuoyan, outside of some more significant internal changes to optimize, one option for you today is to write code like this in your controller:

```java 
@InitBinder("queryRequest")
public void initQueryRequestDataBinder(WebDataBinder binder) {
	binder.setAllowedFields("qr1", "qr2", "qr3");
}

@InitBinder("aDRequest")
public void initADRequestDataBinder(WebDataBinder binder) {
	binder.setAllowedFields("ar1", "ar2", "ar3", ...);
}
```

You might be able to automate the determination of the fields to bind to (e.g. via reflection + assuming certain coding/naming conventions, etc), so they don't have to be explicitly listed and maintained. You might even do that initialization once on startup, so it doesn't have to be performed every time at request time.

Another option is to create a single command object for the entire input and then, if you must expose subsets of fields via interfaces. In other words one `RequestInput` command object that implements and can then be passed elsewhere as a `QueryRequest` or `ADRequest` interface.

**Comment by gihub-zuoyan** [comment]
Thanks for reply! I have merged QueryRequest into ADRequest, just use ADRequest. My Question is "throw new NotWritablePropertyException" is not a good way

**Comment by rstoyanchev** [comment]
Generally the command object should match the expected input fields, or otherwise the fields should be customized. I don't see more options here. We have to find out somehow if a field matches the request parameter.
