### ISSUE TITLE
API to check architecture

### ISSUE THREAD

**Issue by desmethans** [spring-projects/spring-framework#22716]
Spring is often used to write **large** applications.
In large applications a good architecture is important.
I propose an API to check the architecture of an Spring project:
-  Are beans not directly, but via interfaces injected in other beans ?
-  Are repository beans only injected in service beans, not directly in controller beans ?
- Do beans have package visibility so that they are invisble in other layers ?
-  ...

These classes can be used in integrations tests.

I imagine an API like this:
First, you need a class to look up the beans you want to inspect:
```
public class BeanFinder {
	public static ArchitectureAssertions beans(Class<?> ... classes) {
		...
	}
	public static ArchitectureAssertions beansInPackage(String packageName) {
		...
	}
	public static ArchitectureAssertions beansInSamePackageAs(Class<?> clazz) {
		...
	}	
}
``` 
Next, ArchitectureAssertions contains methods to check the architecture:
```
public interface ArchitectureAssertions {
	public boolean havePackageVisibility();
	public boolean containOnlyBeansInjectedViaInterfaces();
	public boolean areOnlyViaInterfacesInjectedInOtherBeans();
	public boolean areOnlyInjectedInBeans(Class<?> ... classes);
	public boolean areOnlyInjectedInBeansInPackage (String packageName);
	public boolean areOnlyInjectedInBeansInSamenPackageAs(Class<?> clazz);
	public boolean areNotInjectedInBeans(Class<?> ... classes);
	public boolean areNotInjectedInBeansInPackage (String packageName);
	public boolean areNotInjectedInBeansInSamenPackageAs(Class<?> clazz);
	public boolean haveNoDirectDependenciesOnBeans(Class<?> clazz);
	public boolean haveNoDirectDependenciesOnBeansInPackage(String packageName);
	public boolean haveNoDirectDependenciesOnBeansInSamePackageAs(Class<?> clazz);
	public boolean haveOnlyDependenciesOnBeans(Class<?> clazz);
	public boolean haveOnlyDependenciesOnBeansInPackage(String packageName);
	public boolean haveOnlyDependenciesOnBeansInSamePackageAs(Class<?> clazz);	
}
```
Examples of using this API in an integration test:
``` 
assertTrue(beans(ClientService.class, ProductService.class).havePackageVisibility());
assertTrue(beansInPackage("org.example.app.services").areOnlyViaInterfacesInjectedInOtherBeans());
assertTrue(beansInSamePackageAs(ClientController.class).haveOnlyDependenciesOnBeansInSamePackageAs(ClientService.class));
```

**Comment by sbrannen** [comment]
Are you familiar with Spring Boot's [`AssertableApplicationContext`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/context/assertj/AssertableApplicationContext.java) and related classes in that same package?

It seems to me that your proposal would be better suited as extensions to that feature set in Spring Boot.

**Comment by snicoll** [comment]
The reporter has created a duplicate issue so I am going to close this one, see https://github.com/spring-projects/spring-boot/issues/16408
