### ISSUE TITLE
Typo in documention (webflux-functional.adoc)

### ISSUE THREAD

**Issue by stephane-deraco** [spring-projects/spring-framework#22717]
In the documentation for Spring Webflux, specifically for functional endpoints, there is a typo line 140 of `webflux-functional.adoc` : `BodyExtractos` instead of `BodyExtractors`

**Affects:** 5.1.6
**Reference url:** https://docs.spring.io/spring/docs/5.1.6.RELEASE/spring-framework-reference/web-reactive.html#spring-webflux

I am willing to do the correction if you want. Reading the CONTRIBUTING file, it seems that as it is a trivial change, I could make the modification directly through Github. If you are ok with that, should I use the master branch?

**Comment by snicoll** [comment]
@stephane-deraco thank you. Next time, please go ahead and submit the PR directly (there is no need for an issue and a PR).
