### ISSUE TITLE
STOMP command ignored by SimpleBrokerMessageHandler

### ISSUE THREAD

**Issue by HugoSart** [spring-projects/spring-framework#22722]
**Affects:** \<Spring Framework version>

---

STOMP commands are ignored by the SimpleBrokerMessageHandler, while the expected behaviour is to process STOMP commands as CONNECT commands.

Changing the client to send CONNECT instead of STOMP fixs the problem temporarily.

Using Spring Boot 2.1.3.
Using stomp and w_transport packages on the client (written in Dart).

**Comment by rstoyanchev** [comment]
This was reported and fixed not long ago #22652.
