### ISSUE TITLE
Acknowledge that HttpHeaders are case-insensitive

### ISSUE THREAD

**Issue by cac03** [spring-projects/spring-framework#22723]
**Affects:** 5.1

Hello,

currently [`HttpHeaders`' documentation](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html) does not acknowledge that `HttpHeaders` behave in case-insensitive manner.

Per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2):

>  Each header field consists of a **case-insensitive** field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

It may be confusing in the presence of publicly exposed [`HttpHeaders(MultiValueMap<String, String>)`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html#HttpHeaders-org.springframework.util.MultiValueMap-) constructor by [this](https://github.com/spring-projects/spring-framework/commit/ce7278aaf4f20348862267c2081c20dc5bd77128#diff-82531305a6405134645740523e37b36f) commit.

Do I understand right that [the constructor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html#HttpHeaders-org.springframework.util.MultiValueMap-) is intended to be used by the framework itself only? @bclozel 

---

Here is a [question](https://stackoverflow.com/questions/52224422/httpheaders-getfirst-case-insensitivity/52225005#52225005) on StackOverflow asking whether the `HttpHeaders` are case-insensitive.

I [had answered](https://stackoverflow.com/revisions/52225005/1) the question relying on the fact that there had been only one publicly available [constructor](https://github.com/spring-projects/spring-framework/blob/5.0.x/spring-web/src/main/java/org/springframework/http/HttpHeaders.java#L418) utilized `LinkedCaseInsenitiveMap` underneath. 

But now I'm a little bit doubtful because of the `HttpHeaders(MultiValueMap<String, String>)` constructor.

I've edited the [answer](https://stackoverflow.com/a/52225005/6486622) accordingly  

---

May I submit a pull request clarifying the documentation that:

* `HttpHeaders` are case-insensitive
* `HttpHeaders(MultiValueMap<String, String>)` is only for internal use *(if the fact is acknowledged)* 
?

*Thank you for your time*

---

**Comment by jhoeller** [comment]
Thanks for raising this, we should indeed explicitly state the case-insensitive nature there. No need for a PR, I'll pick this up in my current round of 5.1 polishing.
