### ISSUE TITLE
Consider changes to MergedAnnotation.asMap

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22738]
It's currently quite hard to convert a `MergedAnnotation` to an `AnnotationAttributes` instance. At one point early in the design we had a factory method on `AnnotationAttributes` that allowed it to be used with `asMap`:

```java
mergedAnnotation.asMap(AnnotationAttributes::ifPresent);
```

We removed that because it wasn't great having an `asMap` method that could return `null`.

Originally I didn't want to tie `MergedAnnotation` to `AnnotationAttributes` because I thought there was too much overlap. In hindsight, I'm not sure we can ever remove `AnnotationAttributes` so perhaps we should just embrace it and add an `asAnnotationAttributes` method. We could even drop `asMap` and the custom factory version which probably only exists to support `AnnotationAttributes`.

We should also reconsider the `MapValues` enum name. It's not that great.

**Comment by jhoeller** [comment]
Let's try to sort this out for 5.2 M1 still since we got time until Tuesday now.

**Comment by philwebb** [comment]
Replacing the `asMap` method might be a little more tricky that I first thought. We use the factory method ourselves to create `AnnotationAttributes` with different constructors. I think we'll need a bit more feedback from @odrotbohm to see how he's making use of those methods.

**Comment by philwebb** [comment]
I added an extra `asAnnotationAttributes` method and also renamed `MapValue`. Feel free re-open or comment if anything else can be improved.
