### ISSUE TITLE
Avoid exceptions in ReflectionUtils.isObjectMethod(…)

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#22730]
Currently, `ReflectionUtils.isObjectMethod(…)` calls `Object.class.getDeclaredMethod(…)`, which, for every method that is not an object method, will cause an exception being thrown. I.e. if you call that method heavily with non-`Object` methods, you create a lot of exceptions.

I suggest to replace that method lookup by a `Map` lookup of all `Object` methods by name (with their parameter type arrays as value for subsequent comparison on a hit of the first lookup).

**Comment by jhoeller** [comment]
Replaced with a direct check for `Object` as declaring class and delegation to the existing `isEqualsMethod`/`isHashCodeMethod`/`isToStringMethod` checks (which are the only overridable ones).
