### ISSUE TITLE
End Of Life for Spring 4.2.x  is not clear

### ISSUE THREAD

**Issue by JoelBarsotti** [spring-projects/spring-framework#22733]
**Affects: 4.3.x**

The documentation on the https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions page is not clear as to when 4.3.x will no longer be supported.

When you say Until 2020, does that mean 12/31/2019, 12/31/2020, or x/x/2020?

This is an important distinction and is not clear in that document.

**Comment by jhoeller** [comment]
Indeed, we have not set an actual EOL date yet; we usually communicate a concrete date 12 months in advance. At this point it looks like we'll go with the 30th of June, 2020 (unless a strong reason for an extended timeframe comes up) which we would communicate in June this year. I'll update the wiki to say "at least until June 2020".
