### ISSUE TITLE
Spring Cloud Consul not closing connections and overwhelming Consul server

### ISSUE THREAD

**Issue by jacobomarquis** [spring-projects/spring-framework#22749]
**Affects:** \<Spring Framework version>

---

**Comment by jacobomarquis** [comment]
We have a very strange case: Enabled Consul service discovery on a dockerized Srping service and everything works fine, but connections opened from Spring to Consul keep rising and using all available goroutines in Consul

Any ideas why Spring will not close opened connections to Consul? Any clues?

Thanks in advance

**Comment by snicoll** [comment]
This is the issue tracker for the Spring Framework, Spring Cloud has dedicated issue trackers. 

Regardless and,  as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
