### ISSUE TITLE
Install jmxremote_optional.jar in Java 8 JVM used for Spring performance builds

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#22757]
Spring Framework nightly performance builds are [failing](https://build.spring.io/browse/SPR-PERF-JOB1-1604/test/case/119934393) since the `jmxmp` protocol is not available by default.

For details on what needs to be done, see gh-15289.

**Comment by trevormarshall** [comment]
Corrected on all recently upgraded Bamboo agents.

**Comment by sbrannen** [comment]
Thanks for the speedy turnaround, @trevormarshall!

I just kicked off a build, so let's see if it works now...
