### ISSUE TITLE
WebClient request header is not sent during request/response exchange

### ISSUE THREAD

**Issue by dancingfrog** [spring-projects/spring-framework#22751]
**Affects:** \5.0.5.RELEASE
 
Spring: 5.0.5.RELEASE
Spring Webflux: 5.0.5.RELEASE
Spring Boot: 2.0.6.RELEASE

Within an application that uses the WebClient class to make requests to an API which requires an Authorization header, after upgrading the application libraries from Spring Boot 2.0.1.RELEASE to 2.0.6.RELEASE, the client fails to send headers which are set by `.header("Authorization", "Bearer " + this.apiKey)`.

Ex.
    
        Mono<ClientResponse> request = wc.get().uri("/families")
                .accept(MediaType.APPLICATION_JSON)
                .header("Authorization", "Bearer " + this.apiKey)
                .exchange();

This happens regardless of whether I resolve the response asynchronously or using block():
    
         response = request
            .doOnRequest(req -> {
                LOGGER.info(this.apiUrl +"/families");

            })
            .doOnSuccess((ClientResponse res) -> {
                LOGGER.info(res.toString)
            });
            //.block();

Oddly enough, I'm using a .filter() when I build the WebClient and it reports that the headers are part of the request. Compare a WebClient/Reactor/Netty request v.s. ngninx log:
 
     2019-04-05 11:32:29.884  INFO 42008 --- [atcher-worker-1] : Getting product details for all product families
     2019-04-05 11:32:31.367  INFO 42008 --- [atcher-worker-1] : Request: GET http://localhost:8080/mcapi/families
     2019-04-05 11:32:31.369  INFO 42008 --- [atcher-worker-1] : Accept: application/json
     2019-04-05 11:32:31.369  INFO 42008 --- [atcher-worker-1] : Authorization: Bearer blahblahblahblah...
     2019-04-05 11:32:39.315  INFO 42008 --- [atcher-worker-1] : http://localhost:8080/mcapi/families
 
 `
     CUSTOM_LOG: 172.17.0.1 - - [05/Apr/2019:15:32:39 +0000] "GET /mcapi/families HTTP/1.1" 200 3852 "-" "ReactorNetty/0.7.4.BUILD-SNAPSHOT" "-""-" "-"
 `

... to a curl request v.s. nginx log:
 `
     $ curl -XGET "http://localhost:8080/mcapi/families" -H "Authorization: Bearer blahblahblahblah..."
 `

 `
     CUSTOM_LOG: 172.17.0.1 - - [05/Apr/2019:15:09:12 +0000] "GET /mcapi/families HTTP/1.1" 200 3852 "-" "curl/7.54.0" "-""Bearer blahblahblahblah..." "-"
 `

**Comment by rstoyanchev** [comment]
I've tried this with the current 2.0.9 and also 2.0.6 and it works fine.

```java
@SpringBootApplication
public class LocationServiceApp {

    @Autowired
    WebClient.Builder builder;


    public static void main(String[] args) {
        SpringApplication.run(LocationServiceApp.class, args);
    }


    @Bean
    public CommandLineRunner initData(MongoOperations mongo) {
        return (String... args) -> {
            builder.build().get().uri("http://httpbin.org/get")
                    .accept(MediaType.APPLICATION_JSON)
                    .header("Authorization", "Bearer blahblahblahblah")
                    .exchange()
                    .flatMap(response -> response.bodyToMono(String.class))
                    .doOnNext(System.out::println)
                    .block();
        };
    }
}
```

Prints:

```
{
  "args": {}, 
  "headers": {
    "Accept": "application/json", 
    "Accept-Encoding": "gzip", 
    "Authorization": "Bearer blahblahblahblah", 
    "Host": "httpbin.org", 
    "User-Agent": "ReactorNetty/0.7.10.RELEASE"
  }, 
  "origin": "88.97.72.61, 88.97.72.61", 
  "url": "https://httpbin.org/get"
}
```

Whatever the issue, it's something else. If you still feel there is an issue please provide an isolated sample.

**Comment by dancingfrog** [comment]
> ```
> {
>   "args": {}, 
>   "headers": {
>     "Accept": "application/json", 
>     "Accept-Encoding": "gzip", 
>     "Authorization": "Bearer blahblahblahblah", 
>     ...
> }
> ```
If you *read the second half* of the bug report, you will note that I got this same result when printing from the *client*, as you did above:
> Oddly enough, I'm using a .filter() when I build the WebClient and it reports that the headers are part of the request. Compare a WebClient/Reactor/Netty request v.s. ngninx log:
> 
> ```
>  2019-04-05 11:32:29.884  INFO 42008 --- [atcher-worker-1] : Getting product details for all product families
>  2019-04-05 11:32:31.367  INFO 42008 --- [atcher-worker-1] : Request: GET http://localhost:8080/mcapi/families
>  2019-04-05 11:32:31.369  INFO 42008 --- [atcher-worker-1] : Accept: application/json
>  2019-04-05 11:32:31.369  INFO 42008 --- [atcher-worker-1] : Authorization: Bearer blahblahblahblah...
>  2019-04-05 11:32:39.315  INFO 42008 --- [atcher-worker-1] : http://localhost:8080/mcapi/families
> ```
... however, the **server** does not log the above "Authorization" header key or value, because it's *not* present:
> `CUSTOM_LOG: 172.17.0.1 - - [05/Apr/2019:15:32:39 +0000] "GET /mcapi/families HTTP/1.1" 200 3852 "-" "ReactorNetty/0.7.4.BUILD-SNAPSHOT" "-""-" "-"`
> 

Please *look* at your server log, when attempting to reproduce this issue.

**Comment by dancingfrog** [comment]
It might also be wise to test an endpoint that actually uses basic auth or some other header to validate the request and sends an appropriate response, since that's the case in which you would be effected this bug.

**Comment by rstoyanchev** [comment]
> I got this same result when printing from the client, as you did above

Those are not printed from the client. That's the sever echoing back the headers it sees. See http://httpbin.org/#/HTTP_Methods/get_get.

If you'd like us to look into this further, please provide sample that demonstrates the issue.

**Comment by dancingfrog** [comment]
@rstoyanchev 
> If you'd like us to look into this further, please provide sample that demonstrates the issue.

Please use this sample repository: https://github.com/Real-Currents/web-client-sample.git

It's a server that will accept a request @ http://localhost:8080/sendAuthRequest/<sampleAuthKey> and create a WebClient request with an "Authentication" header of "Bearer <sampleAuthKey>". This is implemented by the [sendAuthRequest](https://github.com/Real-Currents/web-client-sample/blob/2872ebeaff44d0ab40f3f1e8ec058752512faaa1/src/main/kotlin/com/realcurrents/controllers/WebClientSampleController.kt#L47) method within WebClientSampleController.

Checkout the **working-request-headers** branch to test an example that is **working** with Spring Boot **2.0.0.M7**

Checkout the **broken-request-headers** branch to test an example that is **broken** with Spring Boot **2.0.6.RELEASE** (...or start with working-request-headers and simply change the value of springBootVersion in build.gradle to '2.0.6.RELEASE')

Thanks.

**Comment by dancingfrog** [comment]
@rstoyanchev 
In each branch pay close attention to what is printed in the console after "Server Response: "

**Comment by rstoyanchev** [comment]
I don't know why you're fixing the versions of Spring Security, Reactor, and Reactor Netty vs allowing Spring Boot to manage those. As a result the ones you have do not match Boot 2.0.6. Also no reason to include spring-webflux if you have starter-webflux. Also spring-security-core doesn't seem to be used. So first step, cleaning dependencies:

```
dependencies {
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jre8', version:"${kotlinVersion}"
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version:"${kotlinVersion}"
    compile group: 'org.jetbrains.kotlinx', name: 'kotlinx-coroutines-core', version:'0.21.2'
    compile group: 'org.funktionale', name: 'funktionale-all', version:'1.0.1'
    compile group: 'com.fasterxml.jackson.module', name: 'jackson-module-kotlin', version:'2.9.2'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-webflux', version:"${springBootVersion}"

    testCompile group: 'io.projectreactor', name: 'reactor-test'
    testCompile group: 'org.springframework.boot', name: 'spring-boot-starter-test', version:"${springBootVersion}"
}
```
Now with a version of Reactor that corresponds to Boot 2.0.6, the following happens:

```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-2
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:77) ~[reactor-core-3.1.10.RELEASE.jar:3.1.10.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1183) ~[reactor-core-3.1.10.RELEASE.jar:3.1.10.RELEASE]
	at com.realcurrents.controllers.WebClientSampleController.sendAuthRequest(WebClientSampleController.kt:70) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
```

This is expected because you are not allowed to [block in a WebFlux controller](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-concurrency-model) where you're blocking one of a limited number of event loop threads. So I updated the controller to eliminate blocking:

```java
@GetMapping("/sendAuthRequest/{authKey}")
fun sendAuthRequest (@PathVariable("authKey") authKey: String): Mono<ResponseEntity<String>> {
    var recRequest: ClientResponse? = null

    return wc.get().uri("/get")
      .accept(MediaType.APPLICATION_JSON)
      .header("Authorization", "Bearer ${authKey}")
      .exchange()
      .doOnError { r ->
          println(r.message.toString())
          r.printStackTrace()
      }
      .doOnNext{ r ->
          recRequest = r
      }
      .doOnRequest { req ->
          println("Sending request with Authorization: Bearer ${authKey}")
      }
      .doOnSuccess { res: ClientResponse ->
          println("Completed request: ${res.statusCode()}")
      }
      .flatMap { r ->
          r.bodyToMono(String::class.java)
                  .map { s ->
                      println("Server Response: ")
                      println(s)
                      ResponseEntity.ok(s)
                  }
      }
}
```

Now it works as expected:

```
$ curl -v http://localhost:8080/sendAuthRequest/1234
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /sendAuthRequest/1234 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
< Content-Length: 298
< 
{
  "args": {}, 
  "headers": {
    "Accept": "application/json", 
    "Accept-Encoding": "gzip", 
    "Authorization": "Bearer 1234", 
    "Host": "httpbin.org", 
    "User-Agent": "ReactorNetty/0.7.10.RELEASE"
  }, 
  "origin": "73.10.47.247, 73.10.47.247", 
  "url": "https://httpbin.org/get"
}
* Connection #0 to host localhost left intact
```

**Comment by dancingfrog** [comment]
Thank you!

I didn't know any of that, but particularly the advice about allowing
Spring Boot to manage other gradle dependencies, of which it has many. Is
there a specific section of the documentation that provides guidance in
this regard?

**Comment by dancingfrog** [comment]
https://github.com/Real-Currents/web-client-sample/pull/1
