### ISSUE TITLE
Avoid SourceClass creation for annotations that are always ignored

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#22750]
In a small Spring Boot app, `ConfigurationClassParser$SourceClass.getAnnotations()` creates 200 `SourceClass` instances each for `@Target`, `@Retention`, and `@Documented`. They are then skipped as they're in a `java.*` package:

https://github.com/spring-projects/spring-framework/blob/898494a5380f04469d92f2d5db3fb1b8a128514d/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java#L531-L543

It doesn't take long (a handful of milliseconds), but I still think it would be worth avoiding the unnecessary time that's spent and the unnecessary garbage that's created by changing `SourceClass.getAnnotations()` to only create `SourceClass` instances for annotations that are then processed.

**Comment by jhoeller** [comment]
Relates to #22563.
