### ISSUE TITLE
Add CBOR codec (single value only)

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#22767]
It seems RSocket only requires single value support for codecs, which mean we probably could add CBOR codec with only that scope and add such support to RSocket, and even configure it by default in Boot since that's a popular binary format that does not require code generation from a schema.

Related to #20513 which targets full support and configuration for WebFlux.

**Comment by rstoyanchev** [comment]
I've added methods to `Encoder` and `Decoder` for encoding/decoding single value and DataBuffer, so give this here a go with those changes.
