### ISSUE TITLE
build source failed

### ISSUE THREAD

**Issue by LiuWillow** [spring-projects/spring-framework#22760]
**Affects:** \<5.0.x>

---
when I run `gradle :spring-oxm:compileTestJava`  
it occurred that 
```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:spring-beans:compileGroovy
\--- :spring-beans:compileJava
     \--- :spring-beans:compileKotlin
          \--- :spring-beans:compileGroovy (*)
```
I tried to change kotlin compiler version but had no effect：
![image](https://user-images.githubusercontent.com/25578789/55702887-8d66ad00-5a0a-11e9-8a31-bf075438b5ff.png)
![image](https://user-images.githubusercontent.com/25578789/55702900-95bee800-5a0a-11e9-9388-028dd47fe9db.png)

**Comment by lgxbslgx** [comment]
I had a try just now. The code compiles successfully.

Maybe you should read the documentation carefully at [Build-from-Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) and [import-into-idea.md](https://github.com/spring-projects/spring-framework/blob/master/import-into-idea.md), and follow the steps to build.

**Comment by snicoll** [comment]
@LiuWillow I tried on the `5.0.x` branch (on 0e0e784620 at the time of writing) and this works as expected.

I can see your command does not include the Gradle wrapper so perhaps you have an incompatible gradle version? What is the output of `gradle --version`? `5.0.x` uses `4.4.1`. Try to use the gradle wrapper for a start: `./gradlew :spring-oxm:compileTestJava`

**Comment by LiuWillow** [comment]
@snicoll my gradle version is 4.9. I also tried `./gradlew :spring-oxm:compileTestJava` and `./gradlew.bat :spring-oxm:compileTestJava` but it came the same result

**Comment by lgxbslgx** [comment]
> 5.0.x uses 4.4.1

@LiuWillow Branch `5.0.x` uses `gradle 4.4.1`. You could use the `gradle 4.4.1` to try it again.

**Comment by LiuWillow** [comment]
@lgxbslgx I tried `gradle 4.4.1`
![image](https://user-images.githubusercontent.com/25578789/55772584-5a322580-5abf-11e9-8215-7212104801f0.png)
but failed again
![image](https://user-images.githubusercontent.com/25578789/55772635-8ea5e180-5abf-11e9-8e3e-3b804e4f646f.png)

**Comment by LiuWillow** [comment]
@lgxbslgx I tried `gradle 4.4.1`
![image](https://user-images.githubusercontent.com/25578789/55772777-4d620180-5ac0-11e9-9b35-94a626e58728.png)
but failed again....
![image](https://user-images.githubusercontent.com/25578789/55772801-623e9500-5ac0-11e9-92c4-e5aaec8827d4.png)

**Comment by LiuWillow** [comment]
@sbrannen 
output of `gradlew -version`: 
![image](https://user-images.githubusercontent.com/25578789/55847461-f1f54980-5b7b-11e9-82b1-e4f8213f3929.png)
when I execute `gradlew --no-daemon clean test` it happens: 
![image](https://user-images.githubusercontent.com/25578789/55847487-05081980-5b7c-11e9-8dbe-aa64a21be32e.png)

**Comment by snicoll** [comment]
@LiuWillow there's no need for a screenshot, pasting the text is enough. This goal fail too and they don't for me.

What is the output of `git rev-parse HEAD` and `git status` ?

**Comment by LiuWillow** [comment]
@snicoll my bad. I noted `compileGroovy.dependsOn = compileGroovy.taskDependencies.values - "compileJava"` in spring-beans.gralde. There's no more problems, thank you so much

**Comment by sbrannen** [comment]
Thanks for confirming that you sorted it out.
