### ISSUE TITLE
[Reopening] Ability to specify default-lazy-init behavior for imported bean definitions [SPR-5146]

### ISSUE THREAD

**Issue by Avinm** [spring-projects/spring-framework#22772]
I would like to reopen the issue **[SPR-5146](https://jira.spring.io/browse/SPR-5146?redirect=false)** (https://github.com/spring-projects/spring-framework/issues/12983) as this seems to be bulk-closed and not yet fixed in 4.3:

There doesn't seem to be a way to configure Spring so that imported bean definition files inherit the default-lazy-init behavior from the parent.

For example:

<beans ...
default-lazy-init="true">

```
<import resource="classpath:META-INF/cxf/cxf.xml"/>
<import resource="classpath:META-INF/cxf/cxf-extension-soap.xml"/>
<import resource="classpath:META-INF/cxf/cxf-servlet.xml"/>
```

</beans>

The CXF beans are "eagerly" instantiated even though the parent bean XML speficies "default-lazy-init=true". Is there a way to get the CXF beans to obey the lazy-init behavior that I want (aside from editing the META-INF/cxf/cxf.xml files myself and re-jarring CXF?). (the CXF beans take a few seconds to initialize and this is a problem with client apps in short-running JVMs that may not hit CXF on all code paths)

It seems like either:

1. 'default-lazy-init' should be inherited from the parent bean definition reader
2. There should be an attribute on the import element that allows for specifying the desired default-lazy-init behavior for the imported bean defs.

**Affects:** 2.5.5 - 4.3

**Comment by rstoyanchev** [comment]
I've re-opened the original ticket (sorry for the badly phrased bulk closing comment). Please copy and paste your comment above there, so we have a single ticket and history.
