### ISSUE TITLE
Misleading comment in AbstractHandlerExceptionResolver

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22794]
See https://github.com/spring-projects/spring-boot/issues/16558 for background.

The `AbstractHandlerExceptionResolver` contains this comment in `resolveException`:

```java
// warnLogger with full stack trace (requires explicit config)
logException(ex, request);
```

Unfortunately since a08c9f3137d114bbdd0cdb2800024d45a6a21e3a (for #17691) this is no longer the case.

**Comment by sbrannen** [comment]
@sdeleuze, since you took care of gh-17691, would you mind taking a quick look at this?
