### ISSUE TITLE
Disable ShallowEtagHeaderFilter when ETag handled in application

### ISSUE THREAD

**Issue by mickaeltr** [spring-projects/spring-framework#22797]
**Affects:** 5.1.6.RELEASE

---
Hello,

I am working on a web application that serves some files stored in AWS S3, acting as a proxy. S3 provides ETags for these files. I would like to reuse those ETags but `ShallowEtagHeaderFilter` does not seem to allow it.

When I let the `ShallowEtagHeaderFilter` to generate the ETag, it consumes too much memory for big files.

When I set the ETag manually in the controller, the `If-None-Match` header does not seem to be considered. I would need to copy some pieces of code from `ShallowEtagHeaderFilter` in order to have a full working feature.

So I ended up not using ETags for this endpoint for now: `ShallowEtagHeaderFilter.disableContentCaching(request);` 

I would expect `ShallowEtagHeaderFilter` to be able to consider the existing ETag instead of regenerating it.

Thanks

**Comment by rstoyanchev** [comment]
> When I set the ETag manually in the controller, the If-None-Match header does not seem to be considered

How are you doing that? Can you show a snippet of controller code?

? I would expect ShallowEtagHeaderFilter to be able to consider the existing ETag instead of regenerating it.

ShallowEtagHeaderFilter wraps the response and buffers output content, so it can then calculate a hash based on the buffered content. I'd think the filter should not be used at all for requests where the ETag is already determined.

**Comment by mickaeltr** [comment]
I was hoping that thanks to the following snippet, the filter could just skip the ETag generation but still handle the `If-None-Match` behavior:
`response.setHeader(HttpHeaders.ETAG, s3.document.getObjectMetadata().getETag());

**Comment by rstoyanchev** [comment]
No it doesn't work like that. Please check [the documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-caching-etag-lastmodified) on that.

**Comment by mickaeltr** [comment]
I see. My controller method is special because it is a proxy to an AWS S3 document:
```java
response.setContentType(document.getObjectMetadata().getContentType());
response.setHeader(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + FilenameUtils.getName(location) + "\"");
response.setIntHeader(HttpHeaders.CONTENT_LENGTH, (int) document.getObjectMetadata().getContentLength());
IOUtils.copy(document.getObjectContent(), response.getOutputStream());
```
Tomorrow, I'll see if I can convert it to an `InputStreamResource` and make the ETag work that way.

Thannos @rstoyanchev

**Comment by mickaeltr** [comment]
Hello,
I was finally able to use ResponseEntity and get `304 Not Modified` responses:
```java
return ResponseEntity.ok()
  .contentType(MediaType.parseMediaType(document.getObjectMetadata().getContentType()))
  .eTag(document.getObjectMetadata().getETag())
  .contentLength(document.getObjectMetadata().getContentLength())
  .body(new InputStreamResource(document.getObjectContent()));
```
However I still need to turn off the `ShallowEtagHeaderFilter`, otherwise my ETag and Content-Length are ignored and recalculated, which uses a lot of memory for big documents:

```java
ShallowEtagHeaderFilter.disableContentCaching(request);
```

Should I rename or create a new issue for skipping the ShallowEtagHeaderFilter when an ETag was already set?

**Comment by rstoyanchev** [comment]
No need, I re-purposed this ticket.

**Comment by mickaeltr** [comment]
Hi @rstoyanchev,

I upgraded my application to Spring 5.1.9 and unfortunately, I still need to explicitly `disableContentCatching` if I don't want ETag and Content-Length to be recalculated…

```java
  @GetMapping
  public ResponseEntity<InputStreamResource> downloadDocument(HttpServletRequest request) {
    // ShallowEtagHeaderFilter.disableContentCaching(request);

    S3Object documentFile = …

    return ResponseEntity.ok()
      .contentType(MediaType.parseMediaType(documentFile.getObjectMetadata().getContentType()))
      .eTag(documentFile.getObjectMetadata().getETag())
      .contentLength(documentFile.getObjectMetadata().getContentLength())
      .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + FilenameUtils.getName(documentFile.getKey()) + "\"")
      .cacheControl(CacheControl.maxAge(1, TimeUnit.HOURS).cachePrivate())
      .body(new InputStreamResource(documentFile.getObjectContent()));
  }
```

I will try to dig more into it…

**Comment by rstoyanchev** [comment]
If you see the commit reference above, maybe you can put a breakpoint and step through to see what happens.

**Comment by mickaeltr** [comment]
Hi @rstoyanchev,

I had a look at it. I saw 2 places in https://github.com/spring-projects/spring-framework/commit/1a97a26eb7ed21f5c12f0d89aa67ad518d213e89 were the ShallowEtagHeaderFilter is turned off.

1. [HttpEntityMethodProcessor](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/HttpEntityMethodProcessor.java#L211): does not apply to my request because `isResourceNotModified(inputMessage, outputMessage)` returns false
2. [ServletInvocableHandlerMethod](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ServletInvocableHandlerMethod.java#L110): does not apply to my request because `returnValue` is not null (it is a `ResponseEntity<InputStreamResource>`)

Thanks

**Comment by mickaeltr** [comment]
Hello,

Despite #23775 bug fix, I am still having an issue with ETag and Content-Length being overwritten by the ShallowETagHeaderFilter (using Spring Boot 2.2.4 / Spring 5.2.3), when not disabled.

This is related to what I already documented here https://github.com/spring-projects/spring-framework/issues/22797#issuecomment-484496140 and there #https://github.com/spring-projects/spring-framework/issues/22797#issuecomment-520486211

Please let me know if / how I can help…

**Comment by mickaeltr** [comment]
I created a project with unit tests that demonstrate the issue I am facing with ShallowEtagHeaderFilter: https://github.com/mickaeltr/Spring-ShallowEtagHeaderFilter-issue/blob/master/src/test/java/com/example/demo/DemoControllerTest.java
