### ISSUE TITLE
Add leading slash for path predicate if not present

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-framework#22795]
I have tried the latest Kotlin Coroutines, but  I encountered a small issue when using coRouter DSL.

Spring Boot 2.2.0.BUILD-SNAPSHOT, Spring 5.2.0.M1, Kotlin 1.3, Java 8

For the `nest` path, I have to append "/" to make it work.  Check the source codes [here](https://github.com/hantsy/spring-kotlin-coroutines-sample/blob/master/data-r2dbc-fn/src/main/kotlin/com/example/demo/DemoApplication.kt).

 
```kotlin
    @Bean
    fun routes(postHandler: PostHandler) = coRouter {
        "/posts".nest {
            GET("", postHandler::all)
            GET("/{id}", postHandler::get)
            POST("", postHandler::create)
            PUT("/{id}", postHandler::update)
            DELETE("/{id}", postHandler::delete)
        }
```

But in my before experience,  for nest paths,  it should work without a "/" prefix in both annotated controllers and router DSL,  [example](https://github.com/hantsy/spring-reactive-sample/blob/master/boot-kotlin-dsl/src/main/kotlin/com/example/demo/DemoApplication.kt#L121-L130).

```kotlin
 fun routes() = router {
        "/posts".nest {
            GET("", postHandler::all)
            GET("{id}", postHandler::get)
            POST("", postHandler::create)
            PUT("{id}", postHandler::update)
            DELETE("{id}", postHandler::delete)
        }
}
```

**Comment by sdeleuze** [comment]
Based on my tests with both Spring Boot 2.1.4 and 2.2.0.M2, it seems you have to currently append `/` to make it work for all variants : WebFlux.fn Reactive, WebFlux.fn Coroutines or WebMvc.fn.

That said, maybe we could turn this issue into an improvement one to make functional routing more lenient when the leading slash is not specified.

Any thoughts @poutsma?

**Comment by poutsma** [comment]
> Any thoughts @poutsma?

Sounds good to me.
