### ISSUE TITLE
ResponseBodyAdvice If you capture everything

### ISSUE THREAD

**Issue by maojx0630** [spring-projects/spring-framework#22802]
Returning null in version 5.1.6 can't be captured. How can I get all the information correctly?

**Comment by rstoyanchev** [comment]
I'm not sure what you mean. Could you elaborate please?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by maojx0630** [comment]
sorry use fastjson is ok
