### ISSUE TITLE
Expose StompSubProtocolWebSocketHandler metrics

### ISSUE THREAD

**Issue by krm1312** [spring-projects/spring-framework#22807]
Currently WebSocketMessageBrokerStats hides the actual metrics behind nested toString()s.  This makes it difficult to expose these metrics (for example with micrometer) without resorting to brittle access to private fields.

https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-websocket/src/main/java/org/springframework/web/socket/config/WebSocketMessageBrokerStats.java#L197

ie:

```
    @PostConstruct
    public void init() {
        webSocketMessageBrokerStats.setLoggingPeriod(statsIntervalMs);

        // https://github.com/spring-projects/spring-framework/issues/22807
        Object handler = new DirectFieldAccessor(webSocketMessageBrokerStats).getPropertyValue("webSocketHandler");
        Object stats = new DirectFieldAccessor(handler).getPropertyValue("stats");
        DirectFieldAccessor statsAccessor = new DirectFieldAccessor(stats);
        Gauge.builder("sockjs.connection", () ->
            ((AtomicInteger)statsAccessor.getPropertyValue("webSocket")).get()).tags("protocol", "WS")
            .register(meterRegistry);
        Gauge.builder("sockjs.connection", () ->
            ((AtomicInteger)statsAccessor.getPropertyValue("httpStreaming")).get()).tags("protocol", "HttpStream")
            .register(meterRegistry);
        Gauge.builder("sockjs.connection", () ->
            ((AtomicInteger)statsAccessor.getPropertyValue("httpPolling")).get()).tags("protocol", "HttpPoll")
            .register(meterRegistry);
    }```

**Comment by rstoyanchev** [comment]
Yes we could expose the Stats object from `SubProtocolWebSocketHandler`.

You can get the `SubProtocolWebSocketHandler` directly from the ApplicationContext. It's declared in `WebSocketMessageBrokerConfigurationSupport` as a bean named "subProtocolWebSocketHandler".
