### ISSUE TITLE
NullPointerException in Base64Utils.encodeToString

### ISSUE THREAD

**Issue by latuszek** [spring-projects/spring-framework#22812]
The JavaDoc says `@param src the original byte array (maybe {@code null})` but the implemetation  does not allow `null` -> `if (src.length == 0) {`.
Either documentation or the implementation should be fixed.

**Comment by sbrannen** [comment]
Thanks for bringing this to our attention.

Since none of other methods in `Base64Utils` accept `null` arguments, I will change the Javadoc to reflect that `null` is not permitted here either.

This also aligns with the package-level `@NonNullApi` declaration.
