### ISSUE TITLE
HttpClientErrorException getResponseBodyAsString() returning byte string

### ISSUE THREAD

**Issue by gerwin123** [spring-projects/spring-framework#22811]
I have a problem getting the response body from an 403 http code response from third party server. Before april 5 2019 I was able to get the response body from third party correctly but for now I'm retrieving a byte string from getResponseBodyAsString. Is this an issue from package org.springframework.web.client?
```
try{
    //Request via restTemplate..
    } catch (HttpClientErrorException | HttpServerErrorException ex) {
                loggingService.writeLogs("Error From Third Party Request, Message: " + ex.getMessage() + "| Response Body: " + ex.getResponseBodyAsString(), this.getClass(), LoggingEnum.ERROR, BatchConstants.moduleId);
```

Here is sample value I get when debugging the code: 
![stackover1](https://user-images.githubusercontent.com/26607878/56283159-7e3ada00-6143-11e9-93ba-5dc6a030e336.PNG)

Response on hitting third party api directly
![stack2](https://user-images.githubusercontent.com/26607878/56283267-cc4fdd80-6143-11e9-9eb7-1c7894dc3c5c.PNG)

     ...

**Comment by snicoll** [comment]
See https://github.com/spring-projects/spring-boot/issues/16590#issuecomment-484032532
