### ISSUE TITLE
Allow collapsing the menu of the reference documentations

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-framework#22826]
Thanks on the continuous enhancements in the spring documentation.

One thing I myself miss - and had to work on the DOM to achieve it - is to have the ability to hide/show the left menu.
![Annotation 2019-04-23 110622](https://user-images.githubusercontent.com/1086049/56565008-0132b900-65b8-11e9-8239-30b5ca4fb144.jpg)

**Comment by rstoyanchev** [comment]
We're using a library [https://tscanlin.github.io/tocbot/](tocbot.js). Probably best to suggest a change there, or if you find an option to customize it, feel free to suggest a change here. I believe the idea is for the menu on the left to autoscroll with the content on the right, which is opposite of controlling it.

**Comment by mhewedy** [comment]
I think it is not possible according to https://github.com/tscanlin/tocbot/issues/131

for now, I just work around it by downloading the asciidoc files and convert to epub and read on my iPad which is in most cases works fine.
