### ISSUE TITLE
Cannot parse byte array to string on HttpClientErrorException getResponseBodyAsString when http code of client server is 403 (Forbidden) and on a kubernetes environment 

### ISSUE THREAD

**Issue by gerwin123** [spring-projects/spring-framework#22824]
Hi please see screenshot below , this is on debugging mode (org.springframework.web.client  class HttpClientErrorException)

This is when client api server returning 403 http  code with a body (see ex.getResponseBodyAsString on debugging console)
![stackover1](https://user-images.githubusercontent.com/26607878/56485013-df2c2e80-6504-11e9-8ab5-9d05817077ab.PNG)

Expected result should get  even 403 response code( tried directly hitting api on postman)
![stack2](https://user-images.githubusercontent.com/26607878/56485059-261a2400-6505-11e9-8ae4-643705cb55f5.PNG)

While i requested client server to adjust their http code to 400 , this is what happens  (see ex.getResponseBodyAsString on debugging console), works normally upon changing http code
![stack4](https://user-images.githubusercontent.com/26607878/56485185-9e80e500-6505-11e9-97a1-d92e20a02deb.PNG)

**Comment by lgxbslgx** [comment]
@gerwin123 i can't reproduce your problem. Could you give a demo or some steps to reproduce?

**Comment by gerwin123** [comment]
> @gerwin123 i can't reproduce your problem. Could you give a demo or some steps to reproduce?
ok, I will give you a step and also some snippet of code i used, but you have to provide/create a sample api that produces 403 response code
1. Create a Restful api that produces 403 http code (Any response body of your choice.. eg. {
"message":"403 Forbidden Sample" 
} and any request body of your choice eg. {"test":"sample body"}

2. request via POST Request via restTemplate .
  Below is my sample function to create a post request via RestTemplate
    ` public ResponseEntity<String> makeClientRequestJson(String url, HttpMethod httpMethod, HttpHeaders headers, String jsonBody, String moduleId) {
        RestTemplate restTemplate = new RestTemplate();

        HttpEntity<String> entity = new HttpEntity<>(jsonBody, headers);

        ResponseEntity<String> response = restTemplate.exchange(url, httpMethod, entity, String.class);
        return response;
    }`
Here is the function to make an HttpHeader object
`public HttpHeaders makeHttpHeader(Boolean basicAuth, String username, String password,
                                      Boolean contentType, MediaType mediaType,
                                      Boolean customHeaders, Map<String, String> headers
    ) {
        HttpHeaders httpHeaders = new HttpHeaders();
        if (basicAuth) {
            httpHeaders.setBasicAuth(username, password);
        }
        if (contentType) {
            httpHeaders.setContentType(mediaType);
        }
        if (customHeaders) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                httpHeaders.set(entry.getKey(), entry.getValue());
            }
        }
        return httpHeaders;

    }`
3. Make a POST request via function above and catch using HttpClientErrorException
Sample Code: 
` HttpHeaders httpHeaders = restClient.makeHttpHeader(
                false, null, null,
                true, MediaType.APPLICATION_JSON,
                false, null
        );
 try {
            ResponseEntity<String> responseEntity = restClient.makeClientRequestJson(<your endpoint here>, HttpMethod.POST, httpHeaders, "{\"test\":\"sample body\"}", null);
} catch (HttpClientErrorException | HttpServerErrorException ex) {
//log ex.getResponseBodyAsString() here
System.out.println(ex.getResponseBodyAsString();
}
`

**Comment by lgxbslgx** [comment]
@gerwin123 I use the code below to create a restful api.
```Java
@RequestMapping("test22824")
public ResponseEntity test22824() {
	return new ResponseEntity("{\"message\":\"403 Forbidden Sample\"}", HttpStatus.FORBIDDEN);
}
```
But I don't get the messy code as you describe. The result of `ex.getResponseBodyAsString()` in the debugger is `{"message":"403 Forbidden Sample"}`.

**Comment by gerwin123** [comment]
@lgxbslgx  Your right, we cannot replicate it on the same spring api and on the local, I think the real issue is when deploying  it in a kubernetes environment

here is the response header when deploying via kubernetes


 0 = {LinkedHashMap$Entry@13938} "Content-Type" -> " size = 1"
  key = "Content-Type"
  value = {LinkedList@13955}  size = 1
   0 = "application/json"
 1 = {LinkedHashMap$Entry@13939} "Server" -> " size = 1"
  key = "Server"
  value = {LinkedList@13957}  size = 1
   0 = "nginx/1.14.0 (Ubuntu)"
 2 = {LinkedHashMap$Entry@13940} "Access-Control-Allow-Origin" -> " size = 1"
  key = "Access-Control-Allow-Origin"
  value = {LinkedList@13959}  size = 1
   0 = "*"
 3 = {LinkedHashMap$Entry@13941} "Access-Control-Allow-Methods" -> " size = 1"
  key = "Access-Control-Allow-Methods"
  value = {LinkedList@13961}  size = 1
   0 = "POST, GET, OPTIONS, PUT, DELETE"
 4 = {LinkedHashMap$Entry@13942} "Access-Control-Allow-Credentials" -> " size = 1"
  key = "Access-Control-Allow-Credentials"
  value = {LinkedList@13963}  size = 1
   0 = "true"
 5 = {LinkedHashMap$Entry@13943} "Access-Control-Max-Age" -> " size = 1"
  key = "Access-Control-Max-Age"
  value = {LinkedList@13965}  size = 1
   0 = "86400"
 6 = {LinkedHashMap$Entry@13944} "Access-Control-Allow-Headers" -> " size = 1"
  key = "Access-Control-Allow-Headers"
  value = {LinkedList@13967}  size = 1
   0 = "Content-Type, Authorization, X-Requested-With, Token"
 7 = {LinkedHashMap$Entry@13945} "Content-Encoding" -> " size = 1"
  key = "Content-Encoding"
  value = {LinkedList@13969}  size = 1
   0 = "gzip"
 8 = {LinkedHashMap$Entry@13946} "X-Kong-Upstream-Latency" -> " size = 1"
  key = "X-Kong-Upstream-Latency"
  value = {LinkedList@13971}  size = 1
   0 = "96"
 9 = {LinkedHashMap$Entry@13947} "X-Kong-Proxy-Latency" -> " size = 1"
  key = "X-Kong-Proxy-Latency"
  value = {LinkedList@13973}  size = 1
   0 = "1"
 10 = {LinkedHashMap$Entry@13948} "Content-Length" -> " size = 1"
  key = "Content-Length"
  value = {LinkedList@13975}  size = 1
   0 = "112"
 11 = {LinkedHashMap$Entry@13949} "Expires" -> " size = 1"
  key = "Expires"
  value = {LinkedList@13977}  size = 1
   0 = "Tue, 30 Apr 2019 01:31:02 GMT"
 12 = {LinkedHashMap$Entry@13950} "Cache-Control" -> " size = 1"
  key = "Cache-Control"
  value = {LinkedList@13979}  size = 1
   0 = "max-age=0, no-cache, no-store"
 13 = {LinkedHashMap$Entry@13951} "Pragma" -> " size = 1"
  key = "Pragma"
  value = {LinkedList@13981}  size = 1
   0 = "no-cache"
 14 = {LinkedHashMap$Entry@13952} "Date" -> " size = 1"
  key = "Date"
  value = {LinkedList@13983}  size = 1
   0 = "Tue, 30 Apr 2019 01:31:02 GMT"
 15 = {LinkedHashMap$Entry@13953} "Connection" -> " size = 1"
  key = "Connection"
  value = {LinkedList@13985}  size = 1
   0 = "close"

**Comment by rstoyanchev** [comment]
By default `RestClientResponseException` uses "ISO_8859_1" when you call `getResponseBodyAsString` (unless the Content-Type of the response has a charset) so my guess is that in the 403 case the content is something like UTF-8 so it's using the wrong charset. Try using this instead:

```java
new String(getResponseBodyAsByteArray(), StandardCharsets.UTF_8)
```

**Comment by gerwin123** [comment]
@rs017991  is that need to do? specifying charset for every http code? what if you get a different http code  and is there a need to specify the charset for each? cause when I change the http code to 400 from 403 it works without an issue

**Comment by rstoyanchev** [comment]
I'm operating with very little information and nothing to debug, so I can't give you definitive answers but it's clear this isn't an issue with `RestClientResponseException`. Effectively `getResponseBodyAsString` is nothing but a shortcut for turning the response into a String using the `charset` from the `"Content-Type"` header, or if a charset is not specified, then falling back on a default charset (ISO-8859-1) which may or may not match the one by the server. If that shortcut doesn't work then yes you can't use it, but the thing I would focus on is comparing the 400 vs 403 responses, how is each encoded, what if any charset is in the content-type header, and if they're different, as I suspect they are, find out why the server behaves that way.

**Comment by rs017991** [comment]
@gerwin123 was I mentioned by accident? I'm thinking so, but the topic is not unrelated to my work, so just making sure...
