### ISSUE TITLE
Spring Web Services Reference Documentation have invalid maven command example.

### ISSUE THREAD

**Issue by Funnjy** [spring-projects/spring-framework#22831]
**Spring Web Services Reference Documentation** contains insignificant error under the paragraph [3.5 Creating the project](https://docs.spring.io/spring-ws/docs/3.0.7.RELEASE/reference/#tutorial-creating-project). 

Instead of  `mvn archetype:create ...` it should be `mvn archetype:generate...` due to the support of the "create" goal have been removed, ref. JIRA: [ARCHETYPE-437](https://issues.apache.org/jira/browse/ARCHETYPE-437)
[](url)

**Affects:** \<3.0.7.RELEASE>

---

**Comment by rstoyanchev** [comment]
@Funnjy this issues is for https://github.com/spring-projects/spring-ws.
