### ISSUE TITLE
Why dont' you use BufferedOutputStream?

### ISSUE THREAD

**Issue by MarcoSulla** [spring-projects/spring-framework#22849]
I noticed that in `MultipartFile.transferTo()` methods, and probably also in other point of the code, you don't use `BufferedOutputStream`. Why?

**Comment by rstoyanchev** [comment]
It is using `FileCopyUtils` which reads in 4K chunks.

**Comment by MarcoSulla** [comment]
Well, `BufferedOutputStream` uses a buffer of 8k chunk by default, it's configurabke and furthermore it's standard ;)

**Comment by rstoyanchev** [comment]
All of that is correct but unless it impacts you, it should not matter to you.
