### ISSUE TITLE
就没看到中文评？

### ISSUE THREAD

**Issue by AconHu** [spring-projects/spring-framework#22841]
**Affects:** \<Spring Framework version>

---

**Comment by snicoll** [comment]
> Didn't see the Chinese comment?

@AconHu sorry but I don't understand what you mean and, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements anyway. If you have a question, please ask on StackOverflow.
