### ISSUE TITLE
Could not refresh JMS Connection for destination

### ISSUE THREAD

**Issue by xiangyang-gao** [spring-projects/spring-framework#22848]
Could not refresh JMS Connection for destination 'queue://Consumer.tag.VirtualTopic.order.pay' - retrying using FixedBackOff{interval=5000, currentAttempts=0, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool

**Comment by zuowenmou** [comment]
Hello, when will this happen?

**Comment by snicoll** [comment]
With the amount of details, there is no way to know if that's an issue in Spring Framework, in your application code or somewhere else. If you can share a sample that reproduces that error (a zip or a link with a github repo with instructions), we can have a look.

> Hello, when will this happen?

The issue tracker is not a support forum and asking an hour after creating an issue on a Sunday is a bit rude. Please be patient.

**Comment by zuowenmou** [comment]
I'm terribly sorry。 I'm not proficient with git. 

    <bean id="consumerProperty" class="com.queue.client.core.model.ConsumerProperty">
        <property name="concurrentConsumers">
            <value>5</value>
        </property>
    </bean>
    <bean id="orderPayedTagHandler" class="com.order.event.mq.consumer.payed.OrderPayedTagHandler">
        <property name="groupName" value="order"></property>
        <property name="queueName" value="Consumer.tag.VirtualTopic.order.pay"/>
        <property name="properties" ref="consumerProperty"></property>
    </bean>
Thank you very much.

**Comment by snicoll** [comment]
> I'm terribly sorry。 I'm not proficient with git.

No need to be. A bit of config is not the sample I was looking for I am afraid. If you can share a zip somewhere with a small sample we can run and instructions we can have a look.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snicoll** [comment]
Closing due to the lack of requested feedback.
