### ISSUE TITLE
Pass URI Template to RestTemplate Interceptors

### ISSUE THREAD

**Issue by msmsimondean** [spring-projects/spring-framework#22852]
**Affects:** 5.1.6

---

This is an enhancement request, to change `RestTemplate` so that it passes the original URI template to its interceptors when processing a HTTP request.  The reason for this change is to enable the implementation of feature https://github.com/spring-cloud/spring-cloud-sleuth/issues/1331 in the Spring Cloud Sleuth project.

**Comment by rstoyanchev** [comment]
I don't see a way to pass this all the way through to an interceptor. The `ClientHttpRequestFactory` which creates the request accepts `URI` and `HttpMethod`.

There is another plugin point on the RestTemplate that might help. It is possible to set a `UriTemplateHandler` which is used to expand URI templates. This could be used potentially to save the URI template in a ThreadLocal. I don't really see another way and in general we [don't intend](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#webmvc-client) to make major changes to RestTemplate related contracts any more.
