### ISSUE TITLE
Forward duplicates parameter values (jetty)

### ISSUE THREAD

**Issue by SerCeMan** [spring-projects/spring-framework#22858]
Hi, Spring engineers!

I faced a problem that the async forwarding in spring mvc (`5.1.6.RELEASE`) results in duplicating query parameters. This can be better illustrated by the following example. Consider the [following controller](https://github.com/SerCeMan/jettyredirect/blob/7b3c9b7105637cb038bba1dc4e890c2c6eeeb002/src/main/kotlin/main.kt#L10-L18):
```kotlin
@Controller("/")
open class Page {
    @GetMapping("/page1")
    open fun page1(str: String) = CompletableFuture.completedFuture("forward:/page2")

    @GetMapping("/page2")
    @ResponseBody
    open fun page2(str: String) = "params: $str"
}
```

Requesting `/page1?str=test` results in duplicating the parameters:
```bash
$ curl http://localhost:8070/page1?str=test
params: test,test
```

Returning forward synchronously fixes the issue, but there are certain use cases where forwarding can be returned only after an asynchronous call finishes. 
The project reproducer: https://github.com/SerCeMan/jettyredirect

As far as I can tell, the problem only occurs when spring is configured on top of jetty, and it's likely to be related to this issue: https://github.com/eclipse/jetty.project/issues/2074. However, I can't tell if this is due to spring behaviour or jetty behaviour. As far as I understood from the comments on the issue, the servlet spec is ambiguous. 

Please let me know if I can do anything to move this issue forward. 

Thanks :)

**Comment by rstoyanchev** [comment]
For the async case, we [create an AsyncContext](https://github.com/spring-projects/spring-framework/blob/07c9a0e1f539166a0de15b6eae969118e92c31a8/spring-web/src/main/java/org/springframework/web/context/request/async/StandardServletAsyncWebRequest.java#L121) with the request and response, and later when the async value is resolved, [call dispatch](https://github.com/spring-projects/spring-framework/blob/07c9a0e1f539166a0de15b6eae969118e92c31a8/spring-web/src/main/java/org/springframework/web/context/request/async/StandardServletAsyncWebRequest.java#L131) on that `AsyncContext`. Right before the call to `dispatch` the parameter has 1 value, and after that during the async dispatch it already has two values. So I think this is not related to Spring. I did not try but I think the same could be reproduced easily without Spring, i.e. Servlet that calls startAsync and then dispatch.
