### ISSUE TITLE
Support quality values for MVC `@RequestHeader` 

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-framework#22866]
As of 5.1.6, the `RequestHeaderMethodArgumentResolver` helpfully supports multi-valued headers including appropriate type conversion into a collection container. However, quality values are not supported and result in a `MethodArgumentTypeMismatchException` at request time. I request the ability to parse quality values for `@RequestHeader`.

Specifically, the use case that I am trying to support is rendering document templates on demand. Various templates may be available in various translations, and it is preferable to fall back to rendering, e.g., `en_US` instead of `es_MX` rather than fail entirely. However, the default locale resolution happens at the container level and presents a single preferred locale to the controller instead of a sequence of optional locales.

When not using quality values, this header is mapped into the controller as expected:

```
Accept-Language: es_MX,en_US
```

Adding `;q=0.8`, however, results in an exception. 

I understand that a change of this sort might collide with other uses of `@RequestHeader`, and propose that an annotation element such as `boolean useQualityValues default false` might make sense. When active, the handler should order multiple values according to weight.

**Comment by rstoyanchev** [comment]
> As of 5.1.6, the RequestHeaderMethodArgumentResolver helpfully supports multi-valued headers including appropriate type conversion into a collection container. 

I don't know which change you are referring to as I don't see it neither in [commits](https://github.com/spring-projects/spring-framework/blob/5.1.x/spring-web/src/main/java/org/springframework/web/method/annotation/RequestHeaderMethodArgumentResolver.java) nor [release notes](https://github.com/spring-projects/spring-framework/releases/tag/v5.1.6.RELEASE).

> Adding ;q=0.8, however, results in an exception.

Assuming you mean:

```java
@GetMapping("/path")
public void handle(@RequestHeader("Accept-Language") List<Locale> value) {
}
```

This is handled though the ConversionService and  `StringToLocaleConverter` converting each String individually. Quality parameters would have to be handled earlier in the resolver. This is doable but I'm not sure about going down the route of `@RequestHeader(name="Accept-Language", useQualityValues=true) List<Locale> locales`. That's quite long already compared to alternatives below. Also with more such flags to be requested potentially.

I can suggest:
``` Java
@GetMapping("/path")
public void handle(@RequestHeader("Accept-Language") String value) {
    List<Locale.LanguageRange> ranges = Locale.LanguageRange.parse(value);
}
```

Or:
``` Java
@GetMapping("/path")
public void handle(@RequestHeader HttpHeaders headers) {
    List<Locale> locales = headers.getAcceptLanguageAsLocales();
}
```
