### ISSUE TITLE
Improve Kotlin integration testing documentation

### ISSUE THREAD

**Issue by mattbaumann** [spring-projects/spring-framework#22875]
**Affects:** \5.2.0.M1

---
I just read the [kotlin documentation for spring testing framework](https://docs.spring.io/spring/docs/5.2.0.M1/spring-framework-reference/languages.html#testing)

In my opinion is the unit test documentation is mature.
On the other hand, I would like to see a more detailed documentation related to integration testing. Specially, how I can mock _transitive dependencies_ with _mockk_ in the component testing environment.

Example:
I test _SampleController_ which depends on _SampleService_. In an `@WebMvcTest(SampleController::class)`-Test, how can I inject a mock of the SampleService into the SampleController, which is under integration test?

Context:
The bean _SampleService_ Bean is not loaded in the test application-context with the `@WebMvcTest`-Annotation. Therefore, instead of dependency injection, I would like to do mock injection. Preferably with [mockk](mockk.io) mocks. I chose mockk to be in line with unit test mocking framework under kotlin.

**Comment by sbrannen** [comment]
@sdeleuze, can you provide any insight here?

**Comment by mattbaumann** [comment]
I'm currently using [springmockk](https://github.com/Ninja-Squad/springmockk) for doing the job. The [technical issue](https://github.com/spring-projects/spring-boot/issues/15749) was denied. I agree with the denial, but would appreciate, when the spring team gives another guideline to do the job.

**Comment by sdeleuze** [comment]
SpringMockk is indeed great but is a Spring Boot level feature, and is mentioned in [Spring Boot reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-kotlin-testing).

I understand that the split can be sometimes confusing for developers, but we need to respect this split in our documentation. Maybe we could add more links from Framework to Boot documentation here @sbrannen ?

**Comment by sbrannen** [comment]
> Maybe we could add more links from Framework to Boot documentation here @sbrannen ?

Sure. Feel free to propose where you think we should cross-reference Boot.

For starters, we could add links to Spring Boot's testing chapter and SpringMockK in the [Further Resources](https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testing-resources) section of the _Testing_ chapter.
