### ISSUE TITLE
MockHttpServletRequest raises IndexOutOfBoundsException when Accept-Language is not set

### ISSUE THREAD

**Issue by matze1610** [spring-projects/spring-framework#22877]
**Affects:** 5.1.6.RELEASE

MockHttpServletRequest causes the exeption in 
`	public Locale getLocale() {
		return this.locales.get(0);
	}`

as soon as the request das not have an Accept-Language header set. 
When I set an empty Accept-Language header for my tests 

`mockMvc.perform(get("/some/request")
				.header(ACCEPT_LANGUAGE, "")
				.andExpect(status().isBadRequest());`

method adddHeader does :

`HttpHeaders headers = new HttpHeaders();
headers.add(HttpHeaders.ACCEPT_LANGUAGE, value.toString());
List<Locale> locales = headers.getAcceptLanguageAsLocales();
this.locales.clear();
this.locales.addAll(locales);`

_locales_ receives an empty List. So instead of checking for Bad Request I get the OutOfBound exception from _getLocale()_.
 
Not sure what the better solution is: 

- returning Locale.ROOT from `getLocale` in case of an empty list
- rejecting an empty value in `addHeader` with an exception
- translating an empty value in `addHeader` into Locale.ROOT

Best regards
   Mathias

**Comment by jhoeller** [comment]
Since `MockHttpServletRequest` sets `Locale.ENGLISH` by default already, we should simply restore that same locale as a default if the accept header is empty. I'll roll such a revision into 5.1.7.
