### ISSUE TITLE
Review usage of collectList with DataBuffers

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-framework#22878]
We have to make sure that, when using collectList on a `Flux<DataBuffer>`, we add a `doOnDiscard` hook for the `List` as well as data buffers.

**Comment by rstoyanchev** [comment]
After some further checks it seems `collectList` does iterate over each item on the list and calls `doOnDiscard` for it, so we should be okay with just matching by `PooledDataBuffer.class`.
