### ISSUE TITLE
Unify standard and ASM AnnotatedTypeMetadata retention behavior

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22886]
Reflection based `AnnotatedTypeMetadata` implementations only support `@RetentionPolicy(RetentionPolicy.RUNTIME)` annotations. ASM implementations however currently ignore the `visible` attribute and will read both `RetentionPolicy.CLASS` and `RetentionPolicy.RUNTIME` annotations.

I would like to unify the two implementations if possible.

**Comment by philwebb** [comment]
@jhoeller any problem with this? Is the current behavior intentional?

We have a few tests that fail when I make such a change, but I believe that they have just forgotten to use `@RetentionPolicy(RetentionPolicy.RUNTIME)`.

**Comment by jhoeller** [comment]
Indeed, this was only ever meant to work with `@RetentionPolicy(RetentionPolicy.RUNTIME)`...

**Comment by philwebb** [comment]
Thanks, I'll fix this when I look at #22884
