### ISSUE TITLE
encoding in wrong place

### ISSUE THREAD

**Issue by leassis** [spring-projects/spring-framework#22882]
In this piece of code, the encoding is done after build method so having no effect over the call.

https://github.com/spring-projects/spring-framework/blob/83046531da12dde914fb677b65c2d2b449e039df/spring-test/src/main/java/org/springframework/test/web/client/match/MockRestRequestMatchers.java#L100

**Comment by rstoyanchev** [comment]
I'm not sure which do you mean? That it isn't encoding (which it is) or that it should be using `encode()` on `UriComponentsBuilder` instead? If it is the latter, I don't think we could change that. The best I could suggest is to create your own static method wrapper that prepares the URI and then calls `request(URI)`.

**Comment by leassis** [comment]
tks for the feedback.

What I mean is that when you call encode after buildAndExpand you do not encode you params properly.

Indeed I've created my own class to do it and it uses request(URI)
