### ISSUE TITLE
CONTRIBUTING.md missing word in commit message formatting description

### ISSUE THREAD

**Issue by rewolf** [spring-projects/spring-framework#22890]
> Format commit messages using 55 characters for the subject line, 72 lines for the description, followed by the issue fixed, e.g. Fixes #22276.

"72 lines" should read 72-character lines to explain that lines in the description should not exceed 72 characters in width.

**Comment by snicoll** [comment]
@rewolf thank you for the report. FTR, there is no need to create both an issue and a PR as one supersedes the other.

Closing in favour of PR #22891
