### ISSUE TITLE
Reference to response payload is kept in each thread

### ISSUE THREAD

**Issue by smaxi** [spring-projects/spring-framework#22895]
Each thread of the application keeps reference to response payload. This reference is getting cleaned/reused when thread gets used again. 
This behavior is abnormal, because keeping reference to payload causes OoM when number of threads is high and payloads are big. It is not question of sizing of jvm as permanent heap requirements are n*m where n is the max size of the pool and m is the biggest size of response of the application.

How to reproduce:

Consider a method that returns `StreamSource`.

```java
@PayloadRoot(namespace = PULLACK_NAMESPACE_URI, localPart = "PullRequest")
@ResponsePayload
public StreamSource requestDataGetEvents(@RequestPayload XMLStreamReader reader) throws DurableStorageException{……
```

and ensure that reply is big enough, then memory footprint would look similar to:
![image](https://user-images.githubusercontent.com/50314851/57211152-88802380-6fdf-11e9-87d3-32419659a846.png)

The reference to memory is kept and thread goes back to pool after processing the reply to the client. This reference is replaced by new reference once thread gets reused.

Ideas about resolution: either output stream is not closed, either reference to payload is not cleaned correctly.

Workaround: manipulate streams directly in the application which is not the objective here.

**Comment by jhoeller** [comment]
@snicoll Isn't this a Spring Web Services issue? Any specific reason why this got moved to Spring Framework?

**Comment by snicoll** [comment]
@jhoeller yep oversight on my end. Perhaps @poutsma can transfer it?

**Comment by poutsma** [comment]
Surely you mean @gregturn ?

**Comment by snicoll** [comment]
Sorry for the back and forth. @smaxi this issue looks related to Spring Web Services and [the issue tracker](https://jira.spring.io/projects/SWS/issues/) of that project is using Jira so we can't transfer the issue. 

Please report that issue again in the appropriate project.

**Comment by rstoyanchev** [comment]
@poutsma permissions are required on both sides to transfer.
