### ISSUE TITLE
@Configuration(proxyBeanMethods = false) cannot implement ImportAware

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-framework#22920]
When a configuration class is annotated with `@Configuration(proxyBeanMethods = false)` and also implements `ImportAware`, the method `setImportMetadata` never gets called.

I have created a sample that demonstates this behaviour through a failing test
https://github.com/eleftherias/spring-import-aware-no-proxy/blob/master/src/test/java/com/example/importawarenoproxy/ImportAwareNoProxyApplicationTests.java

It seems to be cause by this line https://github.com/spring-projects/spring-framework/blob/c366e205e5b9f4834eb8e4420705c183e7282ac4/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassPostProcessor.java#L463

When a configuration class e.g `BasicConfig` is annotated with `@Configuration` the bean class is `BasicConfig$$EnhancerBySpringCGLIB` and the superclass name is `BasicConfig`.
However, when the class is annotated with `@Configuration(proxyBeanMethods = false)` the bean class is `BasicConfig` and the superclass is `Object`, which causes the `importingClass` to be null.

**Comment by jhoeller** [comment]
Well spotted, @eleftherias, and very timely!

**Comment by eleftherias** [comment]
Thanks for the fix, this solved our issue.
