### ISSUE TITLE
Minor documentation issue for Validators

### ISSUE THREAD

**Issue by Anticom** [spring-projects/spring-framework#22945]
**Affects:** \5.0.0.M1

Hi, in the code snippet for the [`CustomerValidator`](https://docs.spring.io/spring-framework/docs/5.0.0.M1/spring-framework-reference/html/validation.html#validator) a quote went missing

Actual:
```java
//...
    public CustomerValidator(Validator addressValidator) {
        // ...
        if (!addressValidator.supports(Address.class)) {
            throw new IllegalArgumentException("The supplied [Validator] must " +
                support the validation of [Address] instances.");
        }
        // ...
    }
//...
```

Expected:
```java
//...
    public CustomerValidator(Validator addressValidator) {
        // ...
        if (!addressValidator.supports(Address.class)) {
            throw new IllegalArgumentException("The supplied [Validator] must " +
                "support the validation of [Address] instances.");
        }
        // ...
    }
//...
```

Hope this is the right issue tracker to submit it to. If there's a repo for the documentation, please let me know and I can attach a PR to the issue next time :smile: 

---

**Comment by snicoll** [comment]
@Anticom thanks for reporting but the first milestone of Spring 5.0 is quite old so I'd check first that a more recent release has a fix.

Turns out this [was fixed](https://docs.spring.io/spring-framework/docs/5.0.0.M2/spring-framework-reference/html/validation.html#validator) in `5.0.0.M2` (see #1181)
