### ISSUE TITLE
Add HttpHeaders.getOrEmpty(…) to avoid clients having to default to an empy list

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#22949]
I know that the semantics of the existing `get(…)` method align with what `Map` defines. However as headers are always multi-value and the method returns a list, it would be useful to have an additional method that simply defaults to an empty list instead of `null` as it's good practice for methods that return lists.

**Comment by sbrannen** [comment]
Sounds reasonable to me.

I'm slating this for inclusion in 5.2 M3... unless someone raises any objections in the interim.

**Comment by rstoyanchev** [comment]
No objections from me. In fact all getXyz methods that return a List already return an empty List.
