### ISSUE TITLE
Why is query sign '=' encoded ? Is it in accordance with rfc3986 ? 

### ISSUE THREAD

**Issue by antonysychov** [spring-projects/spring-framework#22940]
https://github.com/spring-projects/spring-framework/blob/de69871354d4d264e28b3e7f5b2eab4a69b7ae73/spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java#L642

**Comment by antonysychov** [comment]
we are trying to encode the whole uri
the proposed way after UriUtils.encodeUri became deprecated is to use UriComponentsBuilder.
We use it in the following way 
```
        UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromUriString("http:/test.com?p=some=value");
        UriComponents uriComponents = uriComponentsBuilder.encode(Charset.forName("UTF-8")).build();
        System.out.println(uriComponents.toUriString());
```
this code gives us the link with a replaced encoded equals sign 
before: http:/test.com?p=some=value
after: http:/test.com?p=some%3Dvalue

according to rfc3986, allowable signs in query part are 
      query       = *( pchar / "/" / "?" )
      pchar includes sub-delims which in turn include equals sign '='

**Comment by rstoyanchev** [comment]
As a sub-delimiter "=" is legal in a query. However we parse the query into query params and within that a query param's name and value do not allow "=". This comes not from the URI spec but rather from a long standing convention that probably originated with browsers and URL-encoded form data.

This is not something we're going to change. In general servers should be decoding the query value so it should work still but in case if you really need it like this, the best I can suggest is to prepare the URI query (or the whole URI) outside of `UriComponentsBuilder`. Or if using RestTemplate or WebClient, you might find some a way to [customize URI template handling](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#web-uri-encoding).
