### ISSUE TITLE
Deprecate AopUtils.isCglibProxy

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-framework#22947]
While I was poking around how to handle deprecated methods in `ClassUtils` i.e. `isCglibProxyClass`:

https://github.com/spring-projects/spring-framework/blob/73dbd06361c5b902857d3dae68b770523318288d/spring-core/src/main/java/org/springframework/util/ClassUtils.java#L855-L860

As `AopUtils.isCglibProxy` is effectively using same deprecated concept, it should probably get deprecated as well.

https://github.com/spring-projects/spring-framework/blob/73dbd06361c5b902857d3dae68b770523318288d/spring-aop/src/main/java/org/springframework/aop/support/AopUtils.java#L93-L96

**Comment by jhoeller** [comment]
In combination with the `SpringProxy` condition, that check is actually still reliable. From that perspective, the `AopUtils` variant can remain non-deprecated.
