### ISSUE TITLE
spring.ftl is missing in spring-webflux

### ISSUE THREAD

**Issue by DerThanne** [spring-projects/spring-framework#22950]
**Affects:** `spring-webflux` 5.1.6

In `org.springframework.web.reactive.result.view.freemarker.FreeMarkerConfigurer` the `spring.ftl` is mentioned, but actually does not exist.

I tried to use the one shipped with `spring-webmc`, but that led to further problems.

Please provide a webflux ready version of the ftl. 

Thank you!

**Comment by rstoyanchev** [comment]
Indeed we're missing the `spring.ftl` macros in WebFlux. It should be the same more or less, as the one in `spring-webmvc`, but without any macros that rely on methods not present in the WebFlux [RequestContext](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/result/view/RequestContext.java) like the ones related to themes.

**Comment by AmbeeBee** [comment]
Sorry partner, didn't mean to.. nut can you put my cell all back on.. please note thank u.

**Comment by ielatif** [comment]
@rstoyanchev  I would like to pick up this plz

**Comment by rstoyanchev** [comment]
Just go ahead and submit a PR.

**Comment by sbrannen** [comment]
Superseded by PR #23002
