### ISSUE TITLE
service blocks when content-length in request set too large 

### ISSUE THREAD

**Issue by maxvandewiel** [spring-projects/spring-framework#22974]
Adding a custom content-length header in request send to spring webflux service deliberately setting its value too high causes service to hang while connection is kept alive.

I need to validate/limit the request payload size in the spring service and this works fine as long as the content length header in the request complies with the actual size of the request body in octets OR is set too low. But whenever I test with a value in content-length where the value is higher than the actual size of the request body the spring webflux services seem to hang!? 

kind regards,

**Comment by rstoyanchev** [comment]
@maxvandewiel, what you mean by "validate/limit", a limit on the max size of the request body, or something else? 

If the Content-Length is N and the client has sent less than that + keeps the connection open, the server is simply waiting for more data. You can [configure a connection timeout](https://projectreactor.io/docs/netty/snapshot/reference/index.html#_tcp_level_configurations).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by maxvandewiel** [comment]
It is understandable the server waits for more data when the content-length header implies more octets to come. However of the size of the request payload is actual smaller no more data ‘will’ come. The issue popped up when I was testing the Spring services and deliberately increased the mentioned header value knowing the actual size of the body was less than implied in the meta data (header) information of the request. The point is that during these test cases to client waited for a long time for a response to come back but it did not receive any response from the spring service until the ‘client’ gave up. My concern is that the server side (spring) service waits long for any octets to come in while claiming resources within that time on the system; when a client consumes the service where the content-length header value is too large there is a risk the resources on the server side get occupied until a resource limit occurs (i.e. io.netty.util.internal.OutOfDirectMemoryError)

Up to you to decide if it is worth looking into what I report. For now I read the body In the RouteLocatorBuilder configuration of Spring cloud Gateway and actually validate the actual cached response body size in octets against the content length header size declared in the http request ‘before’ the gateway forwards thus request to any underlying service.

Kind regards,
Max

**Comment by rstoyanchev** [comment]
> However of the size of the request payload is actual smaller no more data ‘will’ come.

The `Content-Length` is supposed to communicate how large the request body is, in the first place. The server has no other knowledge and no other way to decide that no more content will ever arrive. 

If you want to limit how much memory the server will buffer at most, see ["Codecs Limits"](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-limits). If you want to limit the amount of waiting, [configure](https://projectreactor.io/docs/netty/snapshot/reference/index.html#_lifecycle_callbacks) a `ReadTimeoutHandler`.
