### ISSUE TITLE
Enhancement - MockHttpServletRequestBuilder - Add ability to manually set queryString

### ISSUE THREAD

**Issue by mjohns39** [spring-projects/spring-framework#22978]
I will go ahead and admit that this use case is probably unconventional, but such is life when maintaining/upgrading legacy systems.

Essentially, I need to stream a report file to the browser and I have to do it via a GET request.  Since GET requests don't support a Request Body, and my UI can apply filters to the report, I need to send the filters as an encoded query string...I'll pause for a second so you can process.

This was something I found that was mildly annoying and would have made writing my test a bit easier:

```
this.mockMvc.perform(
    get("/api/reports/download")
    .session(mockHttpSession)
    .queryString(encodedQueryString)) //this is the part I want added
    .andExpect(status().isOk());
```
Let me know if anyone else out there thinks this would be a nice thing to have.  I'm essentially thinking that .queryString() and .param() would be mutually exclusive.  This Builder is for testing, so it would be nice to just have the flexibility.

**Comment by mjohns39** [comment]
As a work around, it's possible to do the following.  I still think this would be a nice feature to have though to help keep tests a bit cleaner.

```
ObjectMapper mapper = new ObjectMapper();
String modelAsString = mapper.writeValueAsString(model);
UriComponents uri = UriComponentsBuilder
				.fromPath("/api/reports/download")
				.replaceQuery(modelAsString)
				.build();
this.mockMvc.perform(get(uri.toUri())
	.characterEncoding("UTF-8")
	.andExpect(status().isOk())
```

**Comment by rstoyanchev** [comment]
Fair point that `HttpServletRequest` exposes `getQueryString()` while the builder doesn't. The reason for that is in the MockMvc API you start with the URI which is where the query is expected. This is [covered in the docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#spring-mvc-test-server-performing-requests) as well.

```java
this.mockMvc.perform(
    get("/api/reports/download?" + queryString)
    .session(mockHttpSession)
    .andExpect(status().isOk());
```
