### ISSUE TITLE
SimpleMessageListenerContainer - add possibility do disable manual recovery

### ISSUE THREAD

**Issue by maciejmiklas** [spring-projects/spring-framework#22987]
The method _SimpleMessageListenerContainer#onException(JMSException)_  starts recovery process. In my opinion it should be configurable, because many JMS Providers can recover automatically, for example ActiveMQ. 

This gest even more interesting - in our case we have observed dropped connections to JMS Listeners. After some debugging I've discovered, that ActiveMQ will throw JMS Exception in like 99% cases, but sometimes it's just not comming. The _SimpleMessageListenerContainer_ starts recovery, closes connection pool and relies of fact, that each not successful reconnection attempt will throw JMSException, but sometimes it does not.

So far we are using such workaround:
```
public static class ActiveMqMessageListenerContainer extends SimpleMessageListenerContainer {

   @Override
   public void onException(JMSException ex) {
   }
}
```

But I would prefer a possibility to disable manual Failover in _SimpleMessageListenerContainer_

**Comment by maciejmiklas** [comment]
Thank you!

**Comment by jhoeller** [comment]
Ah yes, I forgot to mention :-)
There's a new flag called `recoverOnException` now, "true" by default, than can be turned off accordingly.
