### ISSUE TITLE
Why is the SPEL ReflectionHelper class not named ReflectionUtils?

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#22980]
Hello Spring Team

I would create this question to SO, but because it is an opinionated situation I am creating this post here.

I have read this post:

* [What are the differences between Helper and Utility classes?](https://stackoverflow.com/questions/12192050/what-are-the-differences-between-helper-and-utility-classes)

I understand the answer.

Now if we see the [ReflectionHelper](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/expression/spel/support/ReflectionHelper.html) class (located in the `org.springframework.expression.spel.support` package), it has only `static` methods, so why is not named `ReflectionUtils` instead?

I have seen many other classes through the APIs/javadoc in SF, SB, SI, SS projects, and practically the answer available in SO is accomplished or applied through these projects, but this `ReflectionHelper` class is the exception

It would be confuse for possible contributors

Consider please this issue how trivial.

Thanks

**Observation**: exists the [ReflectionUtils](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/util/ReflectionUtils.html) class located in the `org.springframework.util` package. Where it has all the methods declared how `static`

**Comment by sbrannen** [comment]
According to our naming conventions, that class should in fact be called `ReflectionUtils` or something similar. In any case, it's essentially internal to the SPEL implementation, but it's a `public` type. So renaming it is not really an option at this point. @aclement may have further background information regarding the choice of the name.

**Comment by manueljordan** [comment]
Thanks for the reply Sam, I see, because is public it would have an impact for the community, a change about API.

Consider this post just a friendly question or report. 

Sam, because you an expert about Software Developing (same thought about the other members in Pivotal)

Please in your convenience, could you share your thoughts here?

* [Java Naming Classes: when use Support? But taking in consideration the Helper and Utils too](https://stackoverflow.com/questions/56159334/java-naming-classes-when-use-support-but-taking-in-consideration-the-helper-an)

Thanks in advance
