### ISSUE TITLE
DefaultNamespaceHandlerResolverTests.testResolveInvalidHandler doesn't pass

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22994]
Whilst migrating `DefaultNamespaceHandlerResolverTests.testResolveInvalidHandler` to AssertJ I discovered the current tests doesn't fail as expected.

```java
@Test
public void testResolveInvalidHandler() throws Exception {
	String mappingPath = "org/springframework/beans/factory/xml/support/invalid.properties";
	try {
		new DefaultNamespaceHandlerResolver(getClass().getClassLoader(), mappingPath);
		fail("Should not be able to map a class that doesn't implement NamespaceHandler");
	}
	catch (Throwable expected) {
	}
}
```

The constructor does not actually throw an exception, the `fail` method is called but the `AssertionError` is then swallowed by the catch block so the test passes.

**Comment by jhoeller** [comment]
@philwebb I'll remove that test in the 5.1.x branch upfront, ideally forward-merging it before your large-scale test revision gets pushed.
