### ISSUE TITLE
WebFlux documentation states incorrectly that BindingResult is supported after @RequestBody

### ISSUE THREAD

**Issue by flezsoftware** [spring-projects/spring-framework#22997]
According to Webflux documentation:
https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/web/webflux.adoc

> You can use `@RequestBody` in combination with `javax.validation.Valid` or Spring’s `@Validated` annotation, which causes Standard Bean Validation to be applied. By default, validation errors cause a `WebExchangeBindException`, which is turned into a 400 (BAD_REQUEST) response. Alternatively, you can handle validation errors locally within the controller through an Errors or a `BindingResult` argument. 

The following example uses a `BindingResult` argument:

```java
@PostMapping("/accounts")
public void handle(@Valid @RequestBody Account account, BindingResult result) {
	// ...
}
```

This part throws an following exception :

> java.lang.IllegalStateException: An Errors/BindingResult argument is expected immediately after the `@ModelAttribute` argument to which it applies. For `@RequestBody` and `@RequestPart` arguments, please declare them with a reactive type wrapper and use its onError operators to handle WebExchangeBindException

Sample code :
https://github.com/flezsoftware/requestbody-bindingresult

Suggested changes to documentation :
https://github.com/spring-projects/spring-framework/pull/22993/files

and comment by @rstoyanchev https://github.com/spring-projects/spring-framework/pull/22993#issuecomment-493975726

**Comment by rstoyanchev** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by rstoyanchev** [comment]
@flezsoftware, thanks for the sample and my apologies for not seeing this sooner. To my surprise, you are correct that `BindingResult` isn't supported with `@RequestBody` on WebFlux. It's something we should correct but we can correct the documentation to start.
