### ISSUE TITLE
Improve FreeMarker Unit Tests in spring-webflux

### ISSUE THREAD

**Issue by ielatif** [spring-projects/spring-framework#23009]
**Affects:** 5.1.7

---
While working on #22950 I noticed that Unit Tests `FreeMarkerConfigurerTests` and `FreeMarkerMacroTests` (like those in spring-webmvc) are missing.

Is it a deliberate choice or should we add them?

**Comment by sbrannen** [comment]
I think it's a good idea to have unit tests in place for the Webflux variants as well.

Feel free to submit a PR for that.

**Comment by ielatif** [comment]
Ok I will submit a PR.

**Comment by sbrannen** [comment]
I actually requested the introduction of tests in https://github.com/spring-projects/spring-framework/pull/23002#pullrequestreview-241193221.

So, please introduce those tests in your existing PR (#23002).

Superseded by #23002.
