### ISSUE TITLE
Support separate annotation introspectors in Jackson2ObjectMapperBuilder

### ISSUE THREAD

**Issue by otheriault** [spring-projects/spring-framework#23017]
I would like to be able to reuse the existing `Jackson2ObjectMapperBuilder` to set an `AnnotationIntrospector` for serialization only.

This is currently not possible since the `Jackson2ObjectMapperBuilder` only supports a single `AnnotationIntrospector` which will be used for both serialization and deserialization.

**Comment by sdeleuze** [comment]
Does `ObjectMapper#setAnnotationIntrospectors` supports nullable parameters?

**Comment by otheriault** [comment]
If `null` is provided, then the annotation introspector in the underlying `BaseSettings` will have a `null` introspector. This would probably lead to `NullPointerException` at runtime.

It would be better to check that the annotation introspector is not null when set in the `Jackson2ObjectMapperBuilder`.

**Comment by rstoyanchev** [comment]
@otheriault I think we can achieve this with #24824 by providing more control for such situations. I'm closing this in favor of that.

**Comment by rstoyanchev** [comment]
On closer look we'll add a `Consumer<ObjectMapper>` for this issue while #24824 can be done separately through an explicit property.
