### ISSUE TITLE
HierarchicalUriComponents Url Encode removed char +

### ISSUE THREAD

**Issue by wusthuke** [spring-projects/spring-framework#23025]
why HierarchicalUriComponents,  QUERY_PARAM removed char "+" for encode。
when I used TestRestTemplate，In my case, i hava param key=ab+12, server accept is "ab 12".  when i use param key=ab%2B12，and the sever accept is "ab%2B12", because char "%" will be encode。

1.  spring-web-4.3.4.RELEASE
```java 
QUERY_PARAM {
			@Override
			public boolean isAllowed(int c) {
				if ('=' == c || '+' == c || '&' == c) {
					return false;
				}
				else {
					return isPchar(c) || '/' == c || '?' == c;
				}
			}
		}
```
2. spring-web-5.0.7.RELEASE
```java
QUERY_PARAM {
			@Override
			public boolean isAllowed(int c) {
				if ('=' == c || '&' == c) {
					return false;
				}
				else {
					return isPchar(c) || '/' == c || '?' == c;
				}
			}
		}
```

**Comment by rstoyanchev** [comment]
The reason for the change is described in #19394 and there have been _many_ subsequent discussions. I will not repeat that here.

To save you time, see the revised [URI Encoding](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#web-uri-encoding) section in the docs. You'll probably want an option that encodes URI variables more strictly such as using `encode()` at the `UriComponentsBuilder` level. There are also examples how to do that with the `RestTemplate`.
