### ISSUE TITLE
SpringMVC 5.1.7 application/json not support？

### ISSUE THREAD

**Issue by GreatPencil** [spring-projects/spring-framework#23021]
**Affects:** \<Spring Framework version>

---

**Comment by rstoyanchev** [comment]
Yes it's supported. Please provide details.

**Comment by GreatPencil** [comment]
I add Jackson in my classpath but i got this problem when covert a json string to pojo.And I checked default HttpMessageConverter by print the parameter “converters” in method extendMessageComverter(), I did not find Default JSON comverter.
