### ISSUE TITLE
Migrate tests to AssertJ

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23022]
Commits d7320de871dba75e0bbc4f5307d37005c3198379 and 02850f357f29f3dabe64750a3ab9405a94501b3a for #22894 have already started the process of migrating exception checking tests to AssertJ but there's a lot of benefit in migrating all remaining assertions as well. Tests will be easier to read if they all use the same assertion style, and a wholesale migration to JUnit 5 will be much easier.

**Comment by sbrannen** [comment]
JUnit Jupiter assertions have been migrated to AssertJ now as well (5a1217cafed02d1af941d5fba85f4e69e68f0d6e).

**Comment by sbrannen** [comment]
TestNG assertions have been migrated to AssertJ now as well (https://github.com/spring-projects/spring-framework/commit/4f4427f550d132c1b4815f121fbde2465034fb20).
