### ISSUE TITLE
Should it add a another way to get the bean [jmsListenerContainerFactory] ?

### ISSUE THREAD

**Issue by MaxNgai** [spring-projects/spring-framework#23035]
This is a proposition of enhancement.
In spring 5, it seems that the bean [jmsListenerContainerFactory], referring to asynchronous message handling, can **only** be registered in Configuration class successfully when specify the bean's name as "jmsListenerContainerFactory". If we use other bean name, then we will have an initialization error.

for example, if we use the following way to register bean, it won't work. 
`
@Configuration
@EnableJms
public class conf {
	
	@Bean
	public DefaultJmsListenerContainerFactory getListenerContainerFactory() { 
		DefaultJmsListenerContainerFactory factory=new DefaultJmsListenerContainerFactory();
		factory.setConnectionFactory(getMQfactory());
		return factory;
	}
}
`

It means this bean has to be registered with a proper bean name.

But generally, like any other customized beans,  Lots of them can be accessed without specifying a bean name as long as the object type information is correct.

I think an additional way to access this bean should be enhanced. Because the error mentioned above is quite difficult to locate, especially for those who are used to access bean by 
`getBean(Class<?> clazz)` 
rather than
`getBean(String beanName)`

**Comment by snicoll** [comment]
Thanks for the suggestion but this behaviour is intended and [described in the documentation](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#jms-annotated-support). The idea behind using a given name is to provide a convenience (no need to specify `containerFactory`) without picking up the wrong default.

If you always specify a `containerFactory` you don't need to use that default bean name. And you can also register the default explicitly using `JmsListenerConfigurer`. Check the doc link for more details.
