### ISSUE TITLE
Add copyright and authors list to reference manual

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#23048]
The copyright and authors list are both missing from the current versions of the Spring Framework reference manual.

https://docs.spring.io/spring/docs/5.2.0.M2/spring-framework-reference/

https://docs.spring.io/spring/docs/5.2.0.BUILD-SNAPSHOT/spring-framework-reference/

**Comment by sbrannen** [comment]
@Buzzardo, it appears that I cannot assign this issue to you.

**Comment by Buzzardo** [comment]
I don't know you wouldn't be able to assign it to me. Sorry about that.

I made this PR to fix it: https://github.com/spring-projects/spring-framework/pull/23049

**Comment by sbrannen** [comment]
Thanks for the quick turnaround!

I'll get that merged in.

Superseded by gh-23049
