### ISSUE TITLE
FreeMarkerConfigurerTests in spring-webmvc is testing against FreeMarkerConfigurationFactoryBean but not FreeMarkerConfigurer

### ISSUE THREAD

**Issue by ielatif** [spring-projects/spring-framework#23055]
**Affects:**  5.1.7

---

`FreeMarkerConfigurerTests` in `spring-webmvc` is testing against `FreeMarkerConfigurationFactoryBean` but not `FreeMarkerConfigurer`

https://github.com/spring-projects/spring-framework/blob/82d0e49de96b085e8d1d2e4b9ded8e6d82cd535a/spring-webmvc/src/test/java/org/springframework/web/servlet/view/freemarker/FreeMarkerConfigurerTests.java#L57-L64

The test above will succeed when running against `FreeMarkerConfigurationFactoryBean` but fail against `FreeMarkerConfigurer` because in this case `TemplateLoader` for `FreeMarkerConfigurer` is a `MultiTemplateLoader` that contains `SpringTemplateLoader` and `ClassTemplateLoader`

Proposal :

- Test against `FreeMarkerConfigurer` to have good coverage

- Move `FreeMarkerConfigurationFactoryBean` tests to `org.springframework.ui.freemarker.FreeMarkerConfigurationFactoryBeanTests`

**Comment by sbrannen** [comment]
Good catch.

Your proposal sounds reasonable to me.

Would you like to submit a PR?

**Comment by ielatif** [comment]
Yes sure.

**Comment by sbrannen** [comment]
Superseded by #23073
