### ISSUE TITLE
Guard against ConcurrentModificationExceptions in the systemProperties PropertySource

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23063]
The `StandardEnvironment` currently adds a `MapPropertySource` containing `System.getProperties()` to allow them to be used from the `Environment`. Since the underlying `Properties` can be changed in other threads, it's possible that calls to `propertySource.getPropertyNames()` will throw a `ConcurrentModificationException`.

This can be seen in [the following Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/17013). Although we can add guards in the Spring Boot code, It might be useful if these exceptions could be handled transparently by the property source.

**Comment by philwebb** [comment]
Using `synchronized` alone might not be enough since it depends on every other access also adopting the same conventions. See https://github.com/spring-projects/spring-boot/issues/17013#issuecomment-504182522

**Comment by wilkinsona** [comment]
AFAIK, the only way to avoid this is to take a snapshot of the property names using `stringPropertyNames()`. The snapshot is taken in a thread-safe manner and isn't linked back to the underlying `Properties` object so it can't suffer from concurrent modification problems.

**Comment by wilkinsona** [comment]
On closer inspection, Framework’s newly added synchronization is equivalent to using `stringPropertyNames`. That should be sufficient to address the reported Boot problem I believe.
