### ISSUE TITLE
I think that 0(zero) is appropriate as ControllerAdvice's order default.

### ISSUE THREAD

**Issue by jaoromi** [spring-projects/spring-framework#23079]
**Affects:** \Spring framework 5.1.6.RELEASE

---

I think that 0(zero) is appropriate as ControllerAdvice's order default better than current default value Ordered.LOWEST_PRECEDENCE.
I used `@Order(Ordered.LOWEST_PRECEDENCE)` and expected that is lower priority than `@Order` unannotated. However, `@Order(Ordered.LOWEST_PRECEDENCE)` ControllerAdviser and `@Order` unannotated ControllerAdviser are in contention. So, A Exception handled sometimes `@Order(Ordered.LOWEST_PRECEDENCE)` ControllerAdviser, sometimes `@Order` unannotated ControllerAdviser. Of course, This priority not changed after running Spring application, But changed after packaging for build situations.
The method `initOrderFromBeanType` in `org.springframework.web.method.ControllerAdviceBean` is return default Ordered.LOWEST_PRECENDENCE if order is null.
I think spring users want to divide into low priority groups, high priority groups and general groups.
For now, If I want to assign Ordered.LOWEST_PRECEDENCE to a ControllerAdviser's order, I should annotated something like `@Order(0)` for all even uninteresting ControllerAdviser.
But, If ControllerAdviser's default priority is 0(zero), spring users use `@Order(Ordered.LOWEST_PRECEDENCE)` to assign lowest priority than other ControllerAdviser components.

how do you think of this suggestion?

**Comment by rstoyanchev** [comment]
Changing the default order of `ControllerAdvice` beans at this point is not an option, as something could be using `LOWEST_PRECEDENCE - 100` to get ahead, and switching the default order would impact that. 

If you have a `ControllerAdvice` that needs to be behind others, I'm afraid you will need to assign an explicit order to those others too, but perhaps that's all `ControllerAdvice` beans and only some.
