### ISSUE TITLE
Rename TransactionSynchronizationManager#currentTransaction to something more meaningful

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-framework#23086]
I am working currently on implementing reactive Transactions with our new Neo4j reactive driver and need to access the reactive transaction synchronisation manager through

```
...reactive.TransactionSynchronizationManager#currentTransaction
```

The JavaDoc says "…Return the TransactionSynchronizationManager of the current transaction…"

I understand that `TransactionSynchronizationManager` is merely a wrapper around the `TransactionContext`.

Neither the manager nor the context are the transaction itself and therefor I think that the `currentTransaction()` would benefit from another name, like `current TransactionSynchronizationManager()` or `currentTransactionContext()`; it's intentions would be clearer.

cc @mp911de

**Comment by sbrannen** [comment]
Tentatively slated for 5.2 M3

**Comment by mp911de** [comment]
To add a bit of background: The reactive `TransactionSynchronizationManager` isn't associated with a transaction/`TransactionContext`, it is a wrapper to interact with resources and synchronizations stored in `TransactionContext`. 

Renaming that method to `forCurrentTransaction()` could be more expressive. `current TransactionSynchronizationManager` is rather bulky. As Javadoc could be always improved, we could refine it along the lines of `Return the TransactionSynchronizationManager that is associated with the current transaction context`.

**Comment by michael-simons** [comment]
A big +1 for `forCurrentTransaction()`. That reads nice and shows the purpose.

**Comment by sbrannen** [comment]
> A big +1 for `forCurrentTransaction()`. That reads nice and shows the purpose.

That sounds better to me as well.

So, unless someone objects, I'll go ahead and make the proposed name change and Javadoc improvement.

**Comment by snicoll** [comment]
@sbrannen shouldn't we keep the existing method in a deprecated fashion at least for one feature release?

**Comment by jhoeller** [comment]
@snicoll this just affects the reactive transaction support, so it's new API in 5.2 anyway.

**Comment by davidkiss** [comment]
This is a breaking change for spring-data-r2dbc v1.0 M2 (see https://github.com/spring-projects/spring-data-r2dbc/issues/154) and spring-fu's latest version.

**Comment by sbrannen** [comment]
> This is a breaking change for spring-data-r2dbc v1.0 M2 (see [spring-projects/spring-data-r2dbc#154](https://github.com/spring-projects/spring-data-r2dbc/issues/154)) and spring-fu's latest version.

As @jhoeller already pointed out in https://github.com/spring-projects/spring-framework/issues/23086#issuecomment-500118489, the API in question is new in Spring Framework 5.2 and is therefore allowed to be renamed before the 5.2 GA release.
