### ISSUE TITLE
Strange behavior of WebMvcConfigurer (it stops calling)

### ISSUE THREAD

**Issue by DrWifey** [spring-projects/spring-framework#23109]
I use the same pattern in a few project to log income requests (just the url and ip address)
That is:

```
public class RequestHandlerInterceptor extends HandlerInterceptorAdapter {

    @Override
    public boolean preHandle(HttpServletRequest request,
                             HttpServletResponse response, Object handler) throws Exception {
        
        log.info(""); //logging required information here
        return super.preHandle(request, response, handler);    
    }
}
```

And WebMvcConfigurer implementaition
```
@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new RequestHandlerInterceptor());
    }
}
```

And today I noticed that this interceptor doesn't triggers, I mean `addInterceptors` doesn't fire.
The only difference I found is `spring-boot` version.
I took one working project (with 2.1.2 version) and changed it to 2.1.5 and it stopped working. But when I changed it back to 2.1.2 it didn't start working again... Also downgrading 2.1.5 version to 2.1.2 didn't help.
What do I do wrong?
P.S. `@EnableWebMvc` added to AppConfig

**Comment by DrWifey** [comment]
So I finally figured it out... As usually beans construction order is unpredictable and differentiate dependent on an environment your app is running. So I've searching through same problem and found that I have a bean that extends `WebMvcConfigurationSupport` and it was called first, so expected bean hasn't been called at all. So I left only one configuration, e.g:

> @Configuration
> public class WebMvcConfig extends WebMvcConfigurationSupport {
> 
>     private RequestHandlerInterceptor requestHandlerInterceptor;> 
> 
>     @Bean
>     public RequestMappingHandlerMapping requestMappingHandlerMapping() {
>         RequestMappingHandlerMapping requestMappingHandlerMapping = super.requestMappingHandlerMapping();
>         requestMappingHandlerMapping.setInterceptors(requestHandlerInterceptor);
>         return requestMappingHandlerMapping;
>     }
> 
>     @Override
>     public FormattingConversionService mvcConversionService() {
>         FormattingConversionService f = super.mvcConversionService();
>         f.addConverter(new StringToMatchTypeConverter());
>         return f;
>     }
> }

**Comment by sbrannen** [comment]
Glad you figured it out.

I'm now closing this issue.

**Comment by rstoyanchev** [comment]
Note that you might not even need to extend `WebMvcConfigurationSupport` based on the given snippets.
