### ISSUE TITLE
Allow Printers and Parsers to be registered individually to FormatterRegistry

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23110]
Currently `FormatterRegistry` has a `registerFormatter` method but no `registerPrinter` or `registerParser` methods. This makes [this Spring Boot pull-request](https://github.com/spring-projects/spring-boot/pull/17064) a little more verbose than it should be because it's copied the private `PrinterConverter` and `ParserConverter` classes.

**Comment by sbrannen** [comment]
SGTM.

@philwebb, do you want to tackle this one yourself in time for 5.2 RC1? Or shall one of us take it over?

**Comment by philwebb** [comment]
Sorry, forgot to assign it. Working on it currently.

**Comment by renjie-rm** [comment]
Does the print method of formatter need to inject the bean itself and then call the formatting method? @philwebb

**Comment by renjie-rm** [comment]
It cannot be called through Spring like parse？

**Comment by renjie-rm** [comment]
Looking forward to your reply. Thank you！@philwebb

**Comment by philwebb** [comment]
@renjie-rm I'm not sure I understand your question. Perhaps you could rephrase it and ask on stackoverflow.com. Feel free to paste a link to the question back here.

**Comment by renjie-rm** [comment]
@philwebb  https://stackoverflow.com/questions/69053343/how-to-use-org-springframework-format-formatter-print 
Thank you for looking at it
