### ISSUE TITLE
provide `.queryParam(String name, Collection<?> items)` to provide multiValued query parameters

### ISSUE THREAD

**Issue by bjconlan-fc** [spring-projects/spring-framework#23114]
When using the `UrlBuilder` (via the `WebClient`) you can pass a collection as the query parameter value like:

```java
webClient.get().uri(uriBuilder -> uriBuilder.path("/find")
  .queryParam("items", List.of("dogs", "cats"))                   // <!-- this
  .build()
```

This doesn't generate the expected 'multivalued' query param (ie `?items=dogs&items=cats` or `?items=dogs,cats`).

It would be good if it were possible to do something like this.

NOTE: `.queryParam(String name, Object... varargs)` does solve this problem, but having 1st class collection support would be much nicer than shimming things to work with this (or using `StringUtils.collectionToDelimitedString(List.of("dogs", "cats"), ",")`).

**Comment by nosan** [comment]
May I tackle this issue?

**Comment by rstoyanchev** [comment]
Superceded by pull request #23119.
