### ISSUE TITLE
Feature: Supplier for default header in WebClient

### ISSUE THREAD

**Issue by Sam-Kruglov** [spring-projects/spring-framework#23115]
I have a function that I need to call to insert a token into all my requests, so I cannot use the `org.springframework.web.reactive.function.client.WebClient.Builder#defaultHeader` for that. But would be nice if that method also accepted a `java.util.function.Supplier` of `String`.

**Comment by rstoyanchev** [comment]
So you need this to be invoked at request time, and presumably the Supplier accessing some information from a `ThreadLocal` (e.g. Spring MVC controller with WebClient)? If so then use  `WebClient.Builder#defaultRequest`. It was designed for that use case is used in Spring Security.

**Comment by Sam-Kruglov** [comment]
Thank you @rstoyanchev! This works for my case.
