### ISSUE TITLE
Document that @TransactionalEventListener is not supported with ReactiveTransactionManager

### ISSUE THREAD

**Issue by Cepr0** [spring-projects/spring-framework#23127]
**Affects:** Spring Boot 2.2.0.M3

---

If we publish the events within the transactional reactive methods, for example:

```java
@Transactional
public Mono<Model> create(Model model, ModelEvent.Type type) {
    return repo.save(model)
            .doOnSuccess(m -> publisher.publishEvent(new ModelEvent(m, type)));
}
```
then the 'event listener' method with `@TransactionalEventListener` is not invoked (regardless of whether the `@Async` annotation is used or not):

```java
// @Async
@TransactionalEventListener(condition = "#event.inTransactionEventListener()")
public void handleEventInTransactionEventListener(ModelEvent event) {
    log.info("[i] Handled event: {}, in transactional event listener", event.getModel());
}
```

Related demo is [here](https://github.com/Cepr0/sb-reactive-transaction-publishing-event-issue).

**Comment by cwiejack** [comment]
Hi,
any updates on this issue? I'm having this problem with Spring Boot 2.4.0-RC1

**Comment by snicoll** [comment]
Thanks for the nudge and sorry this wasn't triaged earlier. `@TransactionalEvenListener` only works with impetrative transactions, not reactive transaction so we'll have to clarify that in the reference guide and, potentially, the javadoc of related classes.

**Comment by cwiejack** [comment]
Hi,
thank you for clarification.

**Comment by pkgonan** [comment]
@snicoll Hi.
Is there any plan to support TransactionalEventListener for Reactive ? (like @ReactiveTransactionalEventListener).

**Comment by snicoll** [comment]
I am afraid not.

**Comment by jhoeller** [comment]
As a documentation ticket, this duplicates #25805.

**Comment by jhoeller** [comment]
As of 6.1, `@TransactionalEventListener` can be triggered with reactive transactions through adding the transaction context as the event source: https://github.com/spring-projects/spring-framework/issues/27515#issuecomment-1660934318
