### ISSUE TITLE
Stop using `libs-*` repo in favour of consistent use of Maven Central

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#23124]
As we want to make sure we build and release against public artifacts available on Maven Central, let's stop using the `libs-*` repositories on repo.spring.io that are controlled by us and could potentially contain extra artifacts.

**Comment by snicoll** [comment]
The problem with this approach is that they are a few optional libraries that are not available on Maven central so we need a repo for those in any case. One approach would be to create a repo that only contain those.

**Comment by snicoll** [comment]
The following dependencies non available on Maven Central are currently required by the build:

* `com.ibm.websphere:uow:6.0.2.17`
* `io.spring.docresources:spring-doc-resources:0.1.0.RELEASE`

For the doc resources, we had a similar problem in Spring Boot and decided to use a different mechanism to retrieve the doc resource (ping @bclozel). Looks like only `uow` should be made available.

**Comment by snicoll** [comment]
@bclozel confirmed `spring-doc-resources` can be downloaded differently so it looks like we're left with a single dependency to manage.

**Comment by snicoll** [comment]
We can use https://repo.spring.io/ext-release-local/ for optional artifacts that aren't on Maven Central.

**Comment by snicoll** [comment]
Blocked on #23282

**Comment by bclozel** [comment]
@snicoll this task is not blocked anymore from our asciidoc build's perspective.

**Comment by snicoll** [comment]
Unfortunately, we're using a new resource that is not on Maven Central, `io.spring.asciidoctor:spring-asciidoctor-extensions:0.1.3.RELEASE`. It's only used for doc generation and moving that to the `ext-release-local` repo doesn't make sense to me so we're back to the idea of having a dedicated repo for the build

**Comment by snicoll** [comment]
We have now a new virtual repo (`libs-spring-framework-build`) that contains the `uow` dependency and the asciidoctor extension.
