### ISSUE TITLE
HtmlUtils Javadoc refers to deprecated Apache Commons Lang

### ISSUE THREAD

**Issue by pthorson** [spring-projects/spring-framework#23122]
**Affects:** 5.1.x

---
The javadoc for [HtmlUtils](https://github.com/spring-projects/spring-framework/blob/5.1.x/spring-web/src/main/java/org/springframework/web/util/HtmlUtils.java) refers users to the Apache Commons Lang [StringEscapeUtils ](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html) class 

     * <p>For a comprehensive set of String escaping utilities,
     * consider Apache Commons Lang and its StringEscapeUtils class.

But that is now deprecated and moved to commons-text as of 3.6. If this advice still applies, please update the javadoc to refer to the new location for the class. 

Alternatively, since commons lang is no longer required, consider using commons-text in Spring rather than maintaining separate string processing methods.

**Comment by sbrannen** [comment]
Thanks for bringing this to our attention.

> Alternatively, since commons lang is no longer required, consider using commons-text in Spring rather than maintaining separate string processing methods.

As stated in the Javadoc, "_We are not using that class here to avoid a runtime dependency on Commons Lang just for HTML escaping._" Thus, the same rationale holds true for Commons Text.

> But that is now deprecated and moved to commons-text as of 3.6. If this advice still applies, please update the javadoc to refer to the new location for the class.

I will update the Javadoc accordingly.
