### ISSUE TITLE
org.springframework.http.HttpStatus 5.1.x does not support Cloudflare responses.

### ISSUE THREAD

**Issue by lafual** [spring-projects/spring-framework#23136]
Cloudflare servers use extended HTTP response codes. See [Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) and scroll down for Cloudflare codes.

On receiving 520, `HttpStatus.valueOf(HttpStatus.java:527)` returns `IllegalArgumentException: No matching constant for [520]`

I am using version 5.1.5, but I also see the codes missing on 5.1.7's [API](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html)

**Comment by sbrannen** [comment]
Closing as a duplicate of #20336.

Also related to #22872.
