### ISSUE TITLE
Correct encoding and decoding of "message/x.rsocket.routing.v0"

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#23137]
Composite metadata is now supported as of M3 (see #22798) with the String route added as a `"message/x.rsocket.routing.v0"` entry in the composite metadata, plus the option to add more metadata entries. The route is still encoded as a simple String. That needs to be changed when rsocket-core provides an API for that.

**Comment by linux-china** [comment]
RoutingMetadata  implemented  on  https://github.com/rsocket/rsocket-java/tree/develop/rsocket-core/src/main/java/io/rsocket/metadata   
it's tagging, should some reserved tags  be introduced for routing?

**Comment by rstoyanchev** [comment]
@linux-china, currently we simply take the first tag value. Is this too simplistic perhaps, and is there a more idiomatic way, e.g. one tag with the some name (e.g. route) + 2nd tag with actual value?

**Comment by linux-china** [comment]
Now I think the first tag is ok, and developers can put URI string as tag value, and still flexible.
