### ISSUE TITLE
Document how to specify Jackson JSON view serialization hints

### ISSUE THREAD

**Issue by nekperu15739** [spring-projects/spring-framework#23150]
Hi, 

I have the problem to hide some fields according specific security role, one way to do it is using **JsonView** like this [sample](https://spring.io/blog/2014/12/02/latest-jackson-integration-improvements-in-spring#with-spring-boot) or even better this one [Filtering Jackson with security](https://www.baeldung.com/spring-security-role-filter-json), however, there no way to do it with **RouterFunctions**, there some post open in [stackoverflow](https://stackoverflow.com/questions/51972715/spring-webflux-functional-endpoints-jsonview-how).

Thanks.

**Comment by sdeleuze** [comment]
This is now properly documented and I have answered to the SO question.
