### ISSUE TITLE
onStatus throws away default status handler

### ISSUE THREAD

**Issue by 1nDivid** [spring-projects/spring-framework#23155]
**Affects:** 5.2.0.M3

**Description**
Using webflux `WebClient` i want to override behavior if service returns 404 http code. Documentation says to use `onStatus` but there is no warning that it will throw away the default handler and i will lose default behavior on 5xx/4xx statuses. 
Is it supposed to be like that? If i override one status i must provide handler for other error statuses?

```java
@Override
public ResponseSpec onStatus(Predicate<HttpStatus> statusPredicate,
        Function<ClientResponse, Mono<? extends Throwable>> exceptionFunction) {

    if (this.statusHandlers.size() == 1 && this.statusHandlers.get(0) == DEFAULT_STATUS_HANDLER) {
        this.statusHandlers.clear();
    }
    this.statusHandlers.add(new StatusHandler(statusPredicate,
            (clientResponse, request) -> exceptionFunction.apply(clientResponse)));

    return this;
}
```

**Comment by 1nDivid** [comment]
Also in custom handler i have no access to request.

**Comment by 1nDivid** [comment]
I see the solution is to add custom handlers in front of default one and use default as fallback.

**Comment by rstoyanchev** [comment]
This looks related to #22825.

**Comment by poutsma** [comment]
As of a9b3d95a14c316387f2b77328d6864b8e0a36721, we no longer delete the default error handlers when you add a new one, solving this issue. 

Now, we interpret an error handler that returns an empty mono as a signal to return the normal response (and thus override the default error handlers).
