### ISSUE TITLE
Improve RSocketRequester.ResponseSpec Kotlin extensions

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-framework#23164]
**Affects:** Spring Framework 5.2.0-M3

It would be nice to have _Kotlin extension functions_ for `RSocketRequester.ResponseSpec` so that one could write in Kotlin style, e.g.:

```
requester.route("find-by-id")
    .data(CustomerIdRequest(id))
    .retrieveMono<Customer>()
```

instead of

```
requester.route("find-by-id")
    .data(CustomerIdRequest(id))
    .retrieveMono(Customer::class.java)
```

In the same way it would be nice to have `.retrieveFlux<T>()`

**Comment by sdeleuze** [comment]
Another improvement I will make is to leverage https://github.com/spring-projects/spring-framework/commit/d6b5c2005849e0676781ec1086bf8fc994e1a2c4 to replace `dataFlow(flow: Flow)` extension by a general purpose reified `data(producer: Any)` one.
