### ISSUE TITLE
Outdated Spring project versioning page

### ISSUE THREAD

**Issue by kareemadel** [spring-projects/spring-framework#23190]
[This document](https://github.com/spring-projects/spring-build-gradle/wiki/Spring-project-versioning) that specifies the versioning used in the spring projects seems to be deprecated.

Could please update it or confirm whether you still use the same semantics for versioning or not?

Because I am updating some minor and micro versions of a couple of our projects but I need to confirm the backward-compatibility of these newer versions.

**Comment by rstoyanchev** [comment]
The page is still accurate.

**Comment by kareemadel** [comment]
In that case, maybe it's better to move this wiki page to another project since it's in the [spring-build-gradle](https://github.com/spring-projects/spring-build-gradle) which is now defunct. To avoid further confusion.
