### ISSUE TITLE
RestTemplate method patchForObject should also support Void response types

### ISSUE THREAD

**Issue by xXInfamousWolf** [spring-projects/spring-framework#23228]
In #13216 (see commit c472a163f114ba946974980be299deb0a7cb7f34), `exchange()` was adjusted so that it could handle `Void` response types.

I am currently using this for testing as my patch endpoint returns a 204. 

I was trying to implement the same using the `patchForObject()` method but ran into a type issue:

```java
ResponseEntity<Void> responseEntity = this.testRestTemplate.exchange(testUri + ENDPOINT_USER, HttpMethod.PATCH, new HttpEntity<>(userUpdate), Void.class);

ResponseEntity<Void> responseEntity2 = this.testRestTemplate.patchForObject(testUri + ENDPOINT_USER, new HttpEntity<>(userUpdate), Void.class);
```  

I face incompatible types with the second example.

**Comment by sbrannen** [comment]
> I face incompatible types with the second example.

This is to be expected. `patchForObject()` returns an object that has been converted from the response body. In other words, `patchForObject()` does not return that body wrapped in a `ResponseEntity`, and this aligns with the rest of the `*ForObject()` methods in `RestTemplate`.

Although, as you mentioned, `exchange()` can be used to achieve the same goal.

While it would be technically possible to introduce a `patchForEntity()` method, analogous to the existing `getForEntity()` and `postForEntity()` methods, there are no plans to introduce new functionality in the `RestTemplate` API. Here is the section of the `RestTemplate` Javadoc that explains that.

> **NOTE**: As of 5.0, the non-blocking, reactive `org.springframework.web.reactive.client.WebClient` offers a modern alternative to the `RestTemplate` with efficient support for both sync and async, as well as streaming scenarios. The `RestTemplate` will be deprecated in a future version and will not have major new features added going forward. See the `WebClient` section of the Spring Framework reference documentation for more details and example code.

In light of the above, I am closing this issue.

**Comment by xXInfamousWolf** [comment]
Thanks for the prompt reply.
