### ISSUE TITLE
MockMvc: Async result for handler [org.springframework.web.servlet.function.RouterFunctionDslKt$sam$org_springframework_web_servlet_function_HandlerFunction$0@6d4a65c6] was not set during the specified timeToWait=10000

### ISSUE THREAD

**Issue by FVershinin** [spring-projects/spring-framework#23226]
**Affects:** 5.2.0.M3

Async tests are failed when I try to test mvc router function:
`java.lang.IllegalStateException: Async result for handler [org.springframework.web.servlet.function.RouterFunctionDslKt$sam$org_springframework_web_servlet_function_HandlerFunction$0] was not set during the specified timeToWait=10000`

Spring Boot Version: 2.2.0.M4
Example: 
https://github.com/FVershinin/utf8-request/blob/master/src/test/kotlin/com/example/utf8request/ApplicationTests.kt
https://github.com/FVershinin/utf8-request/blob/master/src/main/kotlin/com/example/utf8request/Application.kt

**Comment by jeffawx** [comment]
have the same problem here

mockmvc async test works for annotation but not for functional DSL

Spring Boot Version: 2.2.6.RELEASE

**Comment by snicoll** [comment]
@FVershinin sorry this got overlooked. I've upgraded the sample to a supported version (Spring Boot 2.7 with Spring Framework 5.3) and both those tests are green for me. If you can reproduce the problem with a supported version of the framework, please update your sample and we can reconsider.
