### ISSUE TITLE
Support 'default' option in StringToTimeZoneConverter

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23232]
Originally raised in [in Spring Boot](https://github.com/spring-projects/spring-boot/issues/17414#issuecomment-508000948) it would be nice if our `StringToTimeZoneConverter` could support "default" -> `TimeZone.getDefault()`.

**Comment by philwebb** [comment]
We discussed this a little on our call and considered that most users server-side applications shouldn't be using `TimeZone.getDefault()`. However, I'm not sure if that's a strong enough argument for the fact that we don't offer converter support for it.

**Comment by snicoll** [comment]
Thanks for the suggestion but we feel that returning the default timezone based on "default" to be a bit too magical.
