### ISSUE TITLE
RouterFunction does not respect path matching set in WebFluxConfigurer

### ISSUE THREAD

**Issue by smwhit** [spring-projects/spring-framework#23236]
Spring Boot 2.1.4.Release

Trying to get the Webflux functional endpoints (RouterFunction) to ignore cases and trailing slashes when matching routes. There does not appear to be a documented way of doing this.

Would like a way of matching .GET("/user/", handler) to match "/User" irrespective of casing or trailing slashes.

Overriding configurePathMatching in an implementation of WebFluxConfigurer does not work.

**Comment by bclozel** [comment]
@poutsma I see that we're using a default instance for `PathPatternParser` in the `RequestPredicates` static methods. It seems we can provide a `PathPatternParser` as a method argument. Do you think there's something we could to here to make things easier?

**Comment by poutsma** [comment]
> Do you think there's something we could to here to make things easier?

That's certainly something we can consider for 5.3
