### ISSUE TITLE
Use System.nanoTime() instead of System.currentTimeMillis() in StopWatch

### ISSUE THREAD

**Issue by shenjianeng** [spring-projects/spring-framework#23235]
why does not StopWatch   use System.nanoTime()

**Comment by bclozel** [comment]
We don't use the Spring Framework issue tracker for questions, but judging from your question it looks like you're considering that to be a bug.

Why should `StopWatch` be using nanotime? Could you explain the use case and why the current implementation is wrong?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by pcdavid** [comment]
I'm not the original reporter, but I just had the same remark/question when stumbling on the `org.springframework.util.StopWatch` implementation.

The [Javadoc](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/System.html#currentTimeMillis()) for `currentTimeMillis()` indicates:

> Note that while the unit of time of the return value is a millisecond, the granularity of the value depends on the underlying operating system and may be larger.  For example, many operating systems measure time in units of tens of milliseconds.

[`nanoTime()`](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/System.html#nanoTime()) on the other hand is explicitly designed to measure precise time intervals between invocations (its absolute value however is meaningless). It is guaranteed to use a resolution at least as fine as `currentTimeMillis()`, and possibly much better.

So `currentTimeMillis()` answers "what time is it?" accurately, but with possibly a limited precision. `nanoTime` is more precise (though not necessarily to the nanosecond), but should only be used to measure time intervals. For the use case of a stop-watch, it seems `nanoTime` is better suited.

As additional data points:
* [Guava's `StopWatch`](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Stopwatch.java) implementation uses `nanoTime` (see [`com.google.common.base.Ticker.SYSTEM_TICKER`](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Ticker.java#L47)).
* Apache Commons Lang's [`StopWatch`](https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/time/StopWatch.java) too.

**Comment by sbrannen** [comment]
@pcdavid, thanks for raising those valid points.

We'll switch to using nano time in Spring Framework 5.2.

**Comment by sbrannen** [comment]
@shenjianeng and @pcdavid, the changes have been made in a532afb15d298f2114d6072f0d29138c89bda04f.

Feel free to try them out in the latest build snapshots for Spring Framework 5.2, and if you notice anything that's missing... just let us know.

Thanks
