### ISSUE TITLE
Why Spring does not use placeholders to output logs？

### ISSUE THREAD

**Issue by chenqimiao** [spring-projects/spring-framework#23242]
All places are using string concat to output logs, instead of using placeholders.
I'm confused about it.

**Comment by chenqimiao** [comment]
Doesn't the placeholder look more concise?

**Comment by PascalSchumacher** [comment]
I guess it is because spring uses commons-logging and commons-logging does not support placeholders.

**Comment by sbrannen** [comment]
> I guess it is because spring uses commons-logging and commons-logging does not support placeholders.

That's correct.

**Comment by chenqimiao** [comment]
@sbrannen @PascalSchumacher Thank you for your answers.
But Why not transfer commons-logging to SLF4J ? It seems more simpler in design and use .

**Comment by sbrannen** [comment]
> Why not transfer commons-logging to SLF4J ? It seems more simpler in design and use .

The core Spring Framework has used commons-logging since the beginning, and some classes expose `protected` loggers for use by third parties. Thus, changing the logging framework would be a breaking change.

**Comment by chenqimiao** [comment]
@sbrannen Oh, historical reasons. 
Thank you again for your reply.
