### ISSUE TITLE
Hibernate Query.list() is not included in SharedEntityManagerCreator.queryTerminatingMethods set, causing database connection not to be unreleased when query is proxied

### ISSUE THREAD

**Issue by wcandml** [spring-projects/spring-framework#23248]
The queryTerminatingMethods of the SharedEntityManagerCreator class does not contain the "list" method：

![image-2019-07-06-14-41-13-148](https://user-images.githubusercontent.com/6783771/60795173-c810ea80-a19d-11e9-926e-aaad47551d97.png)

In the DeferredQueryInvocationHandler class, when the EntityManager is closed, it is determined whether the method name is in "queryTerminatingMethods"：

![image-2019-07-06-14-43-21-734](https://user-images.githubusercontent.com/6783771/60795195-d3fcac80-a19d-11e9-979e-f2696d9aa55e.png)

 

When org.hibernate.query.Query.list() is used, and QueryImpl and NativeQueryImpl are delegated by DeferredQueryInvocationHandler, the database connection is not released：

![image-2019-07-06-14-56-26-274](https://user-images.githubusercontent.com/6783771/60795212-da8b2400-a19d-11e9-9caf-3da36905ae31.png)

**Comment by sbrannen** [comment]
Since `org.hibernate.Query.list()` is effectively an alias for `javax.persistence.TypedQuery.getResultList()` (which is in the `queryTerminatingMethods` set), why don't you just switch to using `getResultList()` instead of `list()`?

**Comment by jhoeller** [comment]
Generally the JPA `getResultList` method should be used there, indeed... but it doesn't hurt to add Hibernate's `list()` variant as well. I'll add it for 5.1.9.

**Comment by wcandml** [comment]
@sbrannen   Yes, I can replace `list` with `getResult`, but you can't stop others from using `list`, so i agree with @jhoeller ，add  `list `  to avoid this problem .Thanks @sbrannen and @jhoeller .
