### ISSUE TITLE
ExchangeFilterFunctions.basicAuthentication(String, String) should cache the encoded credentials

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-framework#23256]
Similar to gh-23204, `ExchangeFilterFunctions.basicAuthentication(String, String)` should also cache the encoded credentials.

At present, a new encoding takes place for any web request made through a `WebClient` configured with `.filter(ExchangeFilterFunctions.basicAuthentication(user, pass))`.

**Comment by sbrannen** [comment]
Good catch. I'll make the necessary changes in `ExchangeFilterFunctions` as well.

**Comment by sbrannen** [comment]
This has been resolved in f0d599493e5390e00ee14cbe6a66397a14459607.
