### ISSUE TITLE
Javadoc generation fails due to improper encoding

### ISSUE THREAD

**Issue by TianlinLIAO** [spring-projects/spring-framework#23253]
> Task :api
C:\Users\Documents\spring-source-code\spring-framework\spring-web\src\main\java\org\springframework\http\codec\multipart\DefaultMultipartMessageReader.java:255: error: unmappable character for encoding GBK
				builder.append("鈵?");
				                 ^
C:\Users\Documents\spring-source-code\spring-framework\spring-web\src\main\java\org\springframework\http\codec\multipart\DefaultMultipartMessageReader.java:258: error: unmappable character for encoding GBK
				builder.append("鈵?");
				                 ^
2 errors

> Task :api FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'C:\Users\liao_\Documents\spring-source-code\spring-framework\build\tmp\api\javadoc.options'

**Comment by sbrannen** [comment]
@TianlinLIAO, did you run into this when building against `master`?

**Comment by sbrannen** [comment]
I have been able to reproduce the problem by setting `options.encoding = "GBK"` for the `api` task in `docs.gradle`.

Changing that to `options.encoding = "UTF-8"` should therefore fix the issue.

**Comment by sbrannen** [comment]
This has been addressed in the build for `5.1.9` and `master` (i.e., `5.2.0`).

**Comment by TianlinLIAO** [comment]
> @TianlinLIAO, did you run into this when building against `master`?

Yes, I am building against `master` branch yesterday.

**Comment by TianlinLIAO** [comment]
> This has been addressed in the build for `5.1.9` and `master` (i.e., `5.2.0`).

Thank you so much!
