### ISSUE TITLE
FlowExecutionImpl does not have the serialVersionUID defined

### ISSUE THREAD

**Issue by nmargono** [spring-projects/spring-framework#23264]
**Affects:** \2.3.4.RELEASE

---
I'm running into an issue that's awfully similar to SPR-4826.

My issue is upgrading from spring-webflow 2.0.9.RELEASE to 2.3.4.RELEASE -- my previously existing snapshots can no longer be loaded/deserialized/unmarshalled:

`java.io.InvalidClassException: org.springframework.webflow.engine.impl.FlowExecutionImpl; local class incompatible: stream classdesc serialVersionUID = 507164007291131518, local class serialVersionUID = -4659689664429207075`

So I tried to approach it by hardcoding `private static final long serialVersionUID = -4659689664429207075L;` just like the fix for SPR-4826, but it's still throwing the same error, so maybe I missed a class/step?

What's my best option to approach this?

**Comment by sbrannen** [comment]
@rstoyanchev, I can't seem to transfer this issue to `spring-webflow`.

Can you do that?

**Comment by nmargono** [comment]
Apologies for posting it here, but https://github.com/spring-projects/spring-webflow doesn't seem to have an "Issues" tab to post this question (I'm sorta new to Github, too).

**Comment by sbrannen** [comment]
Oh yes... that's of course the reason I could not transfer it. Silly me! 😬

The issue tracker for Spring Web Flow is [here](https://jira.spring.io/projects/SWF/).

Please open an issue there, and I'll close this issue.

**Comment by nmargono** [comment]
Thanks for the follow-up @sbrannen!

Just for reference, I've created https://jira.spring.io/browse/SWF-1737, and it's been assigned to @rstoyanchev there. Thanks!
