### ISSUE TITLE
Please use AssertJ assertions. [expectedExceptionAnnotation]

### ISSUE THREAD

**Issue by TianlinLIAO** [spring-projects/spring-framework#23266]
> Task :spring-test:checkstyleTest FAILED

>[ant:checkstyle] [ERROR] C:\Users\liao_\Documents\spring-source-code\spring-framework\spring-test\src\test\java\org\springframework\test\context\testng\transaction\programmatic\ProgrammaticTxMgmtTestNGTests.java:102: Please use AssertJ assertions. [expectedExceptionAnnotation]
[ant:checkstyle] [ERROR] C:\Users\liao_\Documents\spring-source-code\spring-framework\spring-test\src\test\java\org\springframework\test\context\testng\transaction\programmatic\ProgrammaticTxMgmtTestNGTests.java:108: Please use AssertJ assertions. [expectedExceptionAnnotation]
[ant:checkstyle] [ERROR] C:\Users\liao_\Documents\spring-source-code\spring-framework\spring-test\src\test\java\org\springframework\test\context\testng\transaction\programmatic\ProgrammaticTxMgmtTestNGTests.java:114: Please use AssertJ assertions. [expectedExceptionAnnotation]
[ant:checkstyle] [ERROR] C:\Users\liao_\Documents\spring-source-code\spring-framework\spring-test\src\test\java\org\springframework\test\context\testng\transaction\programmatic\ProgrammaticTxMgmtTestNGTests.java:120: Please use AssertJ assertions. [expectedExceptionAnnotation]
[ant:checkstyle] [ERROR] C:\Users\liao_\Documents\spring-source-code\spring-framework\spring-test\src\test\java\org\springframework\test\context\testng\transaction\programmatic\ProgrammaticTxMgmtTestNGTests.java:126: Please use AssertJ assertions. [expectedExceptionAnnotation]
[ant:checkstyle] [ERROR] C:\Users\liao_\Documents\spring-source-code\spring-framework\spring-test\src\test\java\org\springframework\test\context\testng\transaction\programmatic\ProgrammaticTxMgmtTestNGTests.java:131: Please use AssertJ assertions. [expectedExceptionAnnotation]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-test:checkstyleTest'.
> Checkstyle rule violations were found. See the report at: file:///C:/Users/liao_/Documents/spring-source-code/spring-framework/spring-test/build/reports/checkstyle/test.html
  Checkstyle files with violations: 1
  Checkstyle violations by severity: [error:6]

**Comment by TianlinLIAO** [comment]
How to avoid run `checkStyle` task

**Comment by TianlinLIAO** [comment]
I commented out checkStyle related lines in build.gradle, then it can build successfully.

**Comment by sbrannen** [comment]
As of Spring Framework 5.2 we enforce the use of AssertJ assertions in the `master` branch.

You can see below that `ProgrammaticTxMgmtTestNGTests` already uses AssertJ assertions.

https://github.com/spring-projects/spring-framework/blob/2909de88297971fcdddeccfcdfb3a71c3b2f8b84/spring-test/src/test/java/org/springframework/test/context/testng/transaction/programmatic/ProgrammaticTxMgmtTestNGTests.java#L43-L45

Thus, you need to build against `HEAD` on `master`.
