### ISSUE TITLE
Obsolete documentation of  "autowire" property for @Bean

### ISSUE THREAD

**Issue by medzan** [spring-projects/spring-framework#23262]
Affected version : **since 5.1** 

Affected section : **_Spring core_ : 1.4.5. Autowiring Collaborators**

Documentation  always mentions the old obsolete description **vs**  the fact that the property is deprecated due to the @bean factory/@Autowired  resolution processing that supersede name/type-based bean property injection.

**Comment by sbrannen** [comment]
Closing due to https://github.com/spring-projects/spring-framework/pull/24574#issuecomment-590083989
