### ISSUE TITLE
Support application/json;charset=UTF-8 for ProtobufHttpMessageConverter

### ISSUE THREAD

**Issue by CluEleSsUK** [spring-projects/spring-framework#23271]
Currently the other mappers and converters default to UTF-8, but the protobuf to JSON HTTP utils don't.

For some context on the other tools see [here](https://github.com/spring-projects/spring-framework/issues/22100)

**Comment by sdeleuze** [comment]
Browsers now handle that correctly, so we don't specify charset parameter explicitly anymore, see https://github.com/spring-projects/spring-framework/issues/22788 for more details.
