### ISSUE TITLE
Add constants for X-Forwarded-* headers in HttpHeaders

### ISSUE THREAD

**Issue by amjedonline** [spring-projects/spring-framework#23275]
**Affects**
current/all

**Proposal**
There is a need of constants for X-Forwarded-* Headers in [HttpHeaders](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/HttpHeaders.java).
Below headers are good candidates:
1. X-Forwarded-Host
2. X-Forwarded-Port
3. X-Forwarded-Proto
4. X-Forwarded-Prefix
5. X-Forwarded-Ssl

**Some references of their usages:**
- [IETF - RFC7239 Forwarded HTTP Extension](https://tools.ietf.org/html/rfc7239#section-5.2)
- https://github.com/spring-projects/spring-framework/issues/20169
- [ServletUriComponentsBuilder.java](https://github.com/spring-projects/spring-framework/blob/9f4d4d18297581ad770a6281097f733c4f6342d3/spring-webmvc/src/main/java/org/springframework/web/servlet/support/ServletUriComponentsBuilder.java)
- [ForwardedHeaderFilter.java](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/filter/ForwardedHeaderFilter.java)

**Earlier related discussions**
- Proposal to map standard Http Headers in Guava - [HTTP Inbound Gateway headers not mapping Content-Disposition](https://jira.spring.io/browse/INT-3488)
- [Guava has these headers meanwhile](https://github.com/google/guava/issues/2430)

**Comment by rstoyanchev** [comment]
For Spring MVC there is built-in support with the `ForwadedHeaderFilter` and WebFlux has similar built-in support at the start of processing. Hence, we do not expect a typical application to access these headers directly. Do you actually need to work with them them, and if so simply create your own constants.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
