### ISSUE TITLE
Move Jackson2Json{De,En}coder to spring-core

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-framework#23283]
For the RSocket support in `spring-messaging` it would be quite handy to use the Jackson2JsonEncoder and Jackson2JsonDecoder without adding `spring-web` to the dependencies.

**Comment by rstoyanchev** [comment]
`spring-core` is for core support and has very few dependencies. The number 3-rd party codec libraries that could potentially end up there is quite open ended. This is why we chose to put Jackson in `spring-web` in the first place even if we knew it's more widely applicable. 

You'll have to add `spring-web` which is also useful to swapping out `AntPathMatcher` with the more efficient `PathPatternParser`. Spring Boot's RSocket starter [includes](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/spring-boot-starter-rsocket/pom.xml) `spring-web` (via the JSON starter), uses Jackson CBOR as the default code and also plugs in the `PathPatternParser` by default.
