### ISSUE TITLE
Add queryParam method to MockHttpServletRequestBuilder

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-framework#23296]
`ServletUriComponentsBuilder` uses `HttpServletRequest#getQueryString` to build on the current request.
However, in a GET or HEAD request, `MockHttpServletRequestBuilder#param` only adds to the combined parameter map and not the query string, causing it to fail.

The workaround is to provide the parameters directly in the URI string, but this is inferior to the fluent API. The different behaviour is probably surprising to many users.

See also https://github.com/spring-projects/spring-restdocs/issues/26

**Comment by rstoyanchev** [comment]
You can supply a URL with a query to `MockMvcRequestBuilders`. The query is parsed and appended to the params map. I suppose we could allow it in the reverse order too, if the request is GET or HEAD and there is no body, but isn't the first option a more self-explanatory way to do it?

**Comment by OrangeDog** [comment]
@rstoyanchev I know, that's why I mentioned it.

> The workaround is to provide the parameters directly in the URI string, but this is inferior to the fluent API. The different behaviour is probably surprising to many users.

Every other part of the the request has a structured way to set it except the querystring, which requires manual encoding and concatenation.

An alternative is to add `queryParam` or `query` methods as well as `param`. I'm not sure whether that would be more confusing, though it better supports the case of POST requests with both a querystring and a body.

**Comment by rstoyanchev** [comment]
Apologies I missed that part of your comment.

I don't see providing the query in the URI template as a workaround. It is the primary way of specifying the target URI with all of its components including the query. The URI template by the way [is encoded](https://github.com/spring-projects/spring-framework/blob/d6e3394b81778009b1ee74435fe1a96b40cad22b/spring-test/src/main/java/org/springframework/test/web/servlet/request/MockHttpServletRequestBuilder.java#L145) so I do not see a need for manual encoding. And you can also use `UriComponentsBuilder` to prepare the `URI` and pass that in.

That said we can add a queryParam method as an extra convenience, and that will append to query of the target URI.

**Comment by rstoyanchev** [comment]
This is now superseded by #23980.
