### ISSUE TITLE
Errors.NativeIoException from WebClient on WebFlux server does not set the response status

### ISSUE THREAD

**Issue by darklynx** [spring-projects/spring-framework#23319]
If `Errors.NativeIoException` is raised from controller while handling service logic it is not properly handled by Spring Framework / WebFlux.

I'm observing the issue in one of my services that runs on Linux, it uses `WebClient` to access another web-service and, if idled for a while in connection pool, it generates `Errors.NativeIoException` with error code indication "Connection reset by peer" (I have mentioned it here: https://github.com/reactor/reactor-netty/issues/641#issuecomment-512865171).

Disregarding the fact that this connection is not taken out from the pool automatically the behavior of the Spring WebFlux is odd: the service returns **HTTP 200 with empty content**, where as I have expected at least HTTP 500.

It can be easy reproduced by raising this Exception manually using latest versions of Spring-Boot, Netty and Java.
Spring-Boot version (maven):
```xml
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.6.RELEASE</version>
	<relativePath/>
</parent>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-webflux</artifactId>
	</dependency>
	...
```

Linux version (in Docker):
```
root@59a09bf2408a:/demo# uname -a
Linux 59a09bf2408a 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
```

Java version:
```
root@59a09bf2408a:/demo# mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /usr/share/maven
Java version: 11.0.4, vendor: Oracle Corporation, runtime: /usr/local/openjdk-11
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.9.125-linuxkit", arch: "amd64", family: "unix"
```

Example of controller to cause the issue:
```java
@RestController
@EnableWebFlux
public class DemoController {
	@GetMapping("/objects/{id}")
	public Mono<DemoObject> getObjects(final @PathVariable String id) {
		switch (id) {
			case "1":
				return Mono.error(new IOException("Failed to read object: " + id));
			case "2":
				// -104 Connection reset by peer
				return Mono.error(new Errors.NativeIoException("Failed to read object: " + id, -104));
			default:
				DemoObject data = new DemoObject();
				data.id = id;
				return Mono.just(data);
		}
	}

	public static final class DemoObject {
		public String id;
	}
}
```

`-104` is a [Connection reset by peer](https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno.h#L87) code on Linux generated in my service by underlying communication to the external service using `WebClient`

Standard `IOException` are handled as expected:
```
$ curl -v http://localhost:8080/objects/1
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /objects/1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json;charset=UTF-8
< Content-Length: 129
<
* Connection #0 to host localhost left intact
{"timestamp":1563573616713,"path":"/objects/1","status":500,"error":"Internal Server Error","message":"Failed to read object: 1"}
```

But the `Errors.NativeIoException` have weird handling:
```
~ $ curl -v http://localhost:8080/objects/2
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /objects/2 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 0
<
* Connection #0 to host localhost left intact
```

I believe `Errors.NativeIoException` is misinterpret by Netty as an error of incoming HTTP connection and not the underlying business / service logic. But should not this be a part of WebFlux to take care of any Exception that is raised from inside controllers and deliver them as HTTP 500 to outside clients?

Workaround: at the moment I am using `Mono.onErrorMap` to map any `Errors.NativeIoException` into `ResponseStatusException` before it leaves the controller to avoid **HTTP 200** response in case of internal issues. But this feels very wrong to me.

I'll be happy about any guidance and/or explanation about current behavior of WebFlux.
Thank you!

**Comment by rstoyanchev** [comment]
It looks like the "Connection reset by peer" triggers this [error handling](https://github.com/spring-projects/spring-framework/blob/957f0fac7a0dd1f0a7a5742fbeb8c40b7da439f0/spring-web/src/main/java/org/springframework/web/server/adapter/HttpWebHandlerAdapter.java#L270-L279) where the assumption is that the client is gone and we don't event set the response status.

We can at least try and set the status to 500, so if the error is a result of request handling, then the response would correctly reflect that.

We considered differentiating between IO errors on the server response vs request handling in #21875. However it was determined Reactor Netty already uses different exceptions. @violetagg is this case where the above `Errors.NativeIoException` somehow slips through and isn't getting translated to `PrematureCloseException`?
