### ISSUE TITLE
Invalid hibernate proxy entity id

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#23318]
When trying to delete an entity, nothing happens because spring is accessing the id directly, and because it is a hibernate proxy object, the member has default 0 value, thus it thinks it is a new entity and skips altogether the delete.

From debugging, this is the relevant part of the callstack:

```
getField:674, ReflectionUtils (org.springframework.util)
getPropertyValue:63, DirectFieldAccessFallbackBeanWrapper (org.springframework.data.util)
getId:154, JpaMetamodelEntityInformation (org.springframework.data.jpa.repository.support)
isNew:42, AbstractEntityInformation (org.springframework.data.repository.core.support)
isNew:233, JpaMetamodelEntityInformation (org.springframework.data.jpa.repository.support)
delete:170, SimpleJpaRepository (org.springframework.data.jpa.repository.support)
```

At the top, in `ReflectionUtils::getField(Field,Object)` method, the `target` variable is of type class `package.Class$HibernateProxy$HWnaDQWN`, and field is `private int package.Class.id`.

Note that accessing the `id` by method `target.getId()` returns non-zero id, as expected.

The `id` is defined inside the entity as follows:

```java
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
```

**Spring Boot 2.1.6.RELEASE** 
- Spring-core 5.1.8.RELEASE
- Hibernate-core 5.3.10.Final
- Spring-data-commons 2.1.9.RELEASE
- Spring-data-jpa 2.1.9.RELEASE

**Comment by cdalexndr** [comment]
After more debugging the cause was the entity's id getter method was **protected**, changing it to **public** solved this problem.
But shoudn't spring access using the protected method instead of direct member access?

**Comment by sbrannen** [comment]
To me, this sounds like it is potentially the expected behavior of [`DirectFieldAccessFallbackBeanWrapper`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/util/DirectFieldAccessFallbackBeanWrapper.html) which resides in Spring Data JPA, not in the core Spring Framework.

@mp911de, what are your thoughts?

**Comment by mp911de** [comment]
We should move that ticket to JIRA, here’s probably not the right place. I think we can improve on that end to align with JPA access rules and fetch the Id value in a better way.

**Comment by sbrannen** [comment]
@cdalexndr, please open an issue in JIRA for [Spring Data JPA](https://jira.spring.io/browse/DATAJPA).

**Comment by cdalexndr** [comment]
Opened https://jira.spring.io/browse/DATAJPA-1576
