### ISSUE TITLE
SpEL wrongly handles doubles in list of integers.

### ISSUE THREAD

**Issue by Kriska** [spring-projects/spring-framework#23312]
**Steps to reproduce issue:**

Given the following piece code: 

```java
ExpressionParser parser = new SpelExpressionParser();
List<Integer> numbers = (List<Integer>) parser.parseExpression("{1.1,2,3}").getValue();
System.out.println(numbers.get(0));
System.out.println(numbers.get(0).getClass());
```

**Now:**

The code compiles successfully.
1.1 is printed
Exception is thrown class java.lang.Double cannot be cast to class java.lang.Integer  (on line 4).

**Expected:**

The code compiles successfully.
Exception is thrown class java.lang.Double cannot be cast to class java.lang.Integer (on line 3).

I find rather misleading the fact that one can operate with the element of type Double as part of the list of Integers.

**Comment by sbrannen** [comment]
As soon as you have a value such as `1.1` in the list, SpEL must treat it as a list of doubles.

Thus, the exception you see is due to the fact that you are implicitly asking Java to cast a `Double` to an `Integer` in order to invoke `toString()` on it. This may seem a bit odd, but that's what Java is doing there.

If you modify your code as follows:

```java
public static void main(String[] args) {
	SpelExpressionParser parser = new SpelExpressionParser();
	@SuppressWarnings("unchecked")
	List<Double> numbers = parser.parseExpression("{1.1,2,3}").getValue(List.class);
	System.out.println(numbers.get(0));
	System.out.println(numbers.get(0).getClass());
}
```

... that will print the following:

```
1.1
class java.lang.Double
```

I am therefore closing this issue as _invalid_.

**Comment by Kriska** [comment]
Of course, if I treat it as Double it works as expected. What I am saying is: 
Given you expect list of integers,
When from a third party comes a list of double which you treat through the parser.
Then the above is observed which is quite misleading.

**Comment by sbrannen** [comment]
FWIW, in order to avoid making any assumptions about the types of elements in a list returned by SpEL, you should always treat the list as a raw list (i.e., `List<?>`).

```java
ExpressionParser parser = new SpelExpressionParser();
List<?> list = parser.parseExpression("{1.1, 2, '3'}").getValue(List.class);
list.forEach(element -> System.out.println(element + " : " + element.getClass().getName()));
```

If you execute the above, the output shows you that you really just have a list of objects.

```
1.1 : java.lang.Double
2 : java.lang.Integer
3 : java.lang.String
```

**Comment by Kriska** [comment]
This is a fair approach. Thanks for the suggestion. I also find useful the fact that with .getValue(List.class) you can be certain you are receiving a list. However, I still consider being able to check not only that but also the type of the generic within the list reasonable. Hope to see it in future versions of spring!

**Comment by sbrannen** [comment]
> However, I still consider being able to check not only that but also the type of the generic within the list reasonable. Hope to see it in future versions of spring!

I don't know that Spring would ever provide that functionality out of the box, but you can achieve that check with a single line of code as follows.

```java
list.forEach(element -> Assert.isInstanceOf(Integer.class, element));
```
