### ISSUE TITLE
Support for template routes with encoded separator in RSocketRequester

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#23310]
**Affects:** 5.2.0.BUILD-SNAPSHOT
---

`RSocketRequester` allows a route to be provided. It would be nice if there were a simple way to perform encoding of the route. For example, if a route were `foo.{id}` and `id` contains a `.` then it would not work. It would be nice if there were a simple mechanism to encode the route.

**Comment by rstoyanchev** [comment]
I've made two updates:
1. For the responder side `PathPattern` now supports HTTP ("/" separator with decoding of path segment values and parsing of path params) vs Message Route style parsing ("." separator with no decoding and no parsing of path params). The latter does decode encoded sequences for the separator char and is enabled with the default constructor of `PathPatternRouteMatcher`.
2. For the requester side, `RSocketRequester` now supports route variables to be expanded into the route, also replacing any "." with "%2E".
