### ISSUE TITLE
Publish STOMP WebSocket client as single artifact

### ISSUE THREAD

**Issue by smoldachev** [spring-projects/spring-framework#23328]
In our project (embedded java application), we need a standalone STOMP websocket client without additional dependencies (such as spring-messaging and spring-web) to avoid jar hell with client code.

As a "workaround", we use such an ugly hack in our pom.
![image](https://user-images.githubusercontent.com/47082582/61622998-8e9cac80-ac7e-11e9-8948-f31a585df3d3.png)

Thank you for the awesome spring! :)

**Comment by sbrannen** [comment]
> Thank you for the awesome spring! :)

You're very welcome.

Regarding this _issue_ that you've opened, are you reporting a bug, requesting an improvement, or merely sharing your solution with others?

**Comment by smoldachev** [comment]
@sbrannen 
This is an improvement request. I think that many developers will be happy to use the STOMP client as a separate spring-independent deps.

**Comment by rstoyanchev** [comment]
Can you clarify what you're using from `spring-web` relative to the STOMP client?

The STOMP client does use some classes from spring-core (util, Assert, etc). You must have that included also in your pom?

In general, client support is intended for use in Spring applications and we assume the presence of spring-core at least, sometimes also spring-context. This is true not only for STOMP but also for HTTP with `RestTemplate` and `WebClient`, for WebSocket both JSR-356 and reactive/WebFlux, among others. Creating separate jars for all those and carefully avoiding dependency from spring-core is not something we are going to do I'm afraid.

**Comment by smoldachev** [comment]
@rstoyanchev
It's bad news for us, unfortunately, but we'll try to somehow avoid the jar hell problem, thank you for your effort and time!
