### ISSUE TITLE
Consider generics when predicting FactoryBean types

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23338]
It would be beneficial if we could consider generics when trying to predict the result of `FactoryBean.getObjectType()`. We currently have difficulty with `getBeanNamesForType` if the bean being considered is a factory bean and we don't want to initialize it early.

It's possible that we can still deduce the type using generics of the factory method, or the class itself. For example:

```java
@Bean
public FactoryBean<MyBean> myBean() {
    ...
}
```

```java
public class MyFactoryBean implements FactoryBean<MyBean> {
    ...
}
```

We have logic to do this already as part of `DefaultListableBeanFactory.getTypeForFactoryBean`, however, in its current form that method  may also cause early initialization of the bean.

**Comment by philwebb** [comment]
I found an annoying edge case that means any `@Configuration` class picked up by component scanning won't be detected correctly. This is because the bean definition has a `String` type not a `Class` type and `hasBeanClass()` return `false`.

I think I have a fix in [this branch](https://github.com/philwebb/spring-framework/tree/gh-23338)

**Comment by jhoeller** [comment]
Resolving a `FacrtoryBean` class along the lines of that branch looks ok to me...
