### ISSUE TITLE
Incomplete cleanup after configuration class creation failure

### ISSUE THREAD

**Issue by szauner** [spring-projects/spring-framework#23343]
I'm using Spring Boot 2.1.5.RELEASE, which i recently upgraded two, and the corresponding versions of Spring Security, Spring JPA and Hibernate. One of the main reasons was the option to use `@Autowired` to inject code into a JPA Attribute Converter.

Doing so resulted in a strange behaviour when running my application. All works perfectly fine (at least it seems so) in tests and when running the application via `bootRun`. But if I run the same application using the jar-file I get from `bootJar` I will get the following exception:

    org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.handleException:169 Handling error: IllegalStateException, This object has not been built
    java.lang.IllegalStateException: This object has not been built
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.getObject(AbstractSecurityBuilder.java:55) ~[spring-security-config-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:508) ~[spring-security-config-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:71) ~[spring-security-oauth2-2.3.6.RELEASE.jar!/:?]
        ...

I opened a [stackoverflow ](https://stackoverflow.com/questions/57004314/how-to-solve-illegalstateexception-this-object-has-not-been-built-when-using)question for this, but with my own investigation going on, I think the issue is better suited to be filed here. I may be wrong though.

I also created a stripped down sample project and publish it in [Github](https://github.com/szauner/investigate-springsec-jar-only-problem). The readme-file includes instructions on how to reproduce the problem and how to identify possible causes.

Please let me know, if I should provide more information.

**Comment by szauner** [comment]
Thank you so much for the work you already put into this. I moved the configuration of the strong encryptor to another file, which solves the problem. I think that's enough information for an answer on SO. If you wrote an answer, I'd be happy to accept it. It's a solution to the problem at hand, regardless of the future work that might or might not be put into this issue.

It appeared to me to be a good idea, to split the configuration into more separate files to decrease the risk of another circular dependency like this. So I created a file `PersistenceConfiguration` and moved all related stuff into it including the corresponding class annotations. Unfortunately, if I move the datasource-definition out of the main application configuration file, it will not be found anymore. But I guess that's another story ^^'.

**Comment by jhoeller** [comment]
This turns out to have been fixed through #26167, registering `@Bean` definitions as dependent on the containing configuration class and therefore also enforcing cleanup of any such early-produced singletons when the configuration class itself gets removed.
