### ISSUE TITLE
interaction between @primary and registerBeanDefinition

### ISSUE THREAD

**Issue by okadhem** [spring-projects/spring-framework#23347]
hi 
the @Primary javadoc specifies that primary beans should be prioritized over non primary beans if both qualify for autowiring. yet DefaultListableBeanFactory.registerBeanDefinition gladly replaces a primary bean with a non primary one.
is this behavior a bug or am i missing something ?

spring version : 5.0.4.RELEASE

**Comment by snicoll** [comment]
`@Primary` is about what qualifies a bean for injection, not for registration. If you have more questions, please ask on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
