### ISSUE TITLE
Session.close() accidentally triggers creation of TransactionAwareDataSourceProxy Connection

### ISSUE THREAD

**Issue by jpozorio** [spring-projects/spring-framework#23346]
**Affects:** 3.1.4.RELEASE
Using hibernate: 3.6.10.Final

---
I'm facing an issue caused by opening connections with database on session.close call.
For some reason, hibernate throws an exception when is opening a connection with database, then he starts to rollback the transaction.
From now on, a proxy connection exists in session (`TransactionAwareInvocationHandler`), but real connection with database does not exists.

After that, _spring-orm_ call `SessionFactoryUtils.closeSession`, and this goes to close connection, but real connection failed to be created

Hibernate `ConnectionManager`, before close the connection call `JDBCExceptionReporter.logAndClearWarnings( connection );` (connection parameter is proxy `TransactionAwareInvocationHandler` connection without real connection because creation failed)

Then `TransactionAwareInvocationHandler` create a new connection with database because `getWarnings` and `clearWarnings` are not mapped methods in invoke
This connection is closed right after creation, but when I am inside a transaction, this connection resource is binded to thread and never unbinded. Because _spring-tx_ is alredy in a rollback block.

I think a connection should not be opened when some of those two methods `getWarnings` and `clearWarnings` are called and real connection does not exists.

https://github.com/zgsolucoes/spring-framework/commit/35c0b084906e6d122b13980df12383958a935213

**Comment by jhoeller** [comment]
Good point! We're locally handling `getWarnings` and `clearWarnings` calls in `TransactionAwareDataSourceProxy` now. I'll also backport this to 5.0.15 and 4.3.25.
