### ISSUE TITLE
build source failed

### ISSUE THREAD

**Issue by husterchen** [spring-projects/spring-framework#23355]
Problem：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distZip'.
> Failed to create MD5 hash for file 'E:\spring-framework-master\build\distributions\spring-framework-5.2.0.BUILD-SNAPSHOT-schema.zip' as it does not exist.

**Comment by vananiev** [comment]
Have same error for 5.2.2 at current master

>  Failed to create MD5 hash for file 'E:\git\spring-framework\build\distributions\spring-framework-5.2.2.BUILD-SNAPSHOT-schema.zip' as it does not exist.

**Comment by rstoyanchev** [comment]
What are the steps to reproduce this? I ran `./gradlew distZip` in master on Linux and it completed successfully. The CI servers are not encountering this either.

**Comment by sbrannen** [comment]
Closing as a duplicate of #23933
