### ISSUE TITLE
Can't wrap a ClientResponse with a custom status code in a builder 

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-framework#23366]
When using Spring WebFlux 5.1.8.RELEASE consider having the following code

```java
ClientResponse response = ...;
ClientResponse wrapped = ClientResponse.from(response)
					.body(response.bodyToFlux(DataBuffer.class)
					.transform(this.scopePassingTransformer))
					.build()
```

when `response` contains a custom status code e.g. `499` the `DefaultClientResponseBuilder` in the constructor uses `statusCode(other.statusCode());` and `statusCode()` throws an exception since it's a custom status code.

**Comment by rstoyanchev** [comment]
`ClientHttpResponse` and `ClientResponse` support custom status codes, but `ClientResponse.Builder` doesn't. In the very least `ClientResponse.from(response)` should not fail i this case.
