### ISSUE TITLE
SpEL could not call methods of Object on a Proxy-Object

### ISSUE THREAD

**Issue by MrCoffee77** [spring-projects/spring-framework#23369]
**Affects: Spring Framework 5.0/5.1**

---
I found the problem, that I couldn't call methods of Object in the SpEL, when the target-object is a Proxy. In my case it was the toString()-method.
I build a test, which shows the behavior and my workaround:
[SpelProxyText.zip](https://github.com/spring-projects/spring-framework/files/3435517/SpelProxyText.zip)

**Comment by snicoll** [comment]
Supersedes #25316
