### ISSUE TITLE
Pre-allocate NoTransactionException in TransactionContextManager

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#23360]
`NoTransactionException` should be pre-allocated in `org.springframework.transaction.reactive.TransactionContextManager` to prevent expensive exception creation when calling `TransactionContextManager.currentContext()`. Ideally, this exception captures no stack trace, that is irrelevant in the context of reactive flows.

/cc @simonbasle @bsideup

**Comment by bsideup** [comment]
Consider using a stackless exception instead ( http://shipilev.net/blog/2014/exceptional-performance/#_conclusion )

Pre-allocated (aka cached, aka static) are hard to deal with in the debug mode (where we mutate them, necessary evil)
