### ISSUE TITLE
Introduce gitattributes file

### ISSUE THREAD

**Issue by srdo** [spring-projects/spring-framework#23376]
Affects: This repository's master branch.

There is currently no .gitattributes file, which means line ending settings are left up to each developer. This can cause issues when Windows devs check in code, as they may not have set `core.autocrlf` to true, and may be committing files with CRLF. It can also cause issues on checkout, as checking out the directory with `autocrlf` set to true will convert all files to CRLF, which breaks e.g. the `gradlew` script.

Using a .gitattributes means we can check in EOL settings alongside the code. A decent approach would probably be to start with `* text=auto` in the .gitattributes, and then add exceptions as necessary.

Reference https://git-scm.com/docs/gitattributes

**Comment by sbrannen** [comment]
What about `* text eol=lf` instead of `* text=auto`?

**Comment by srdo** [comment]
Sure, that would be fine too.

**Comment by sbrannen** [comment]
If we introduce a `.gitattributes` file, we should move the localized configuration for multipart files from [here](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/test/resources/org/springframework/http/codec/multipart/.gitattributes) to the _root_ `.gitattributes` file. (thanks for the tip @poutsma)

**Comment by srdo** [comment]
Thanks for fixing this 👍

**Comment by sbrannen** [comment]
You're welcome!

And... hopefully it won't have any adverse side effects for anyone.
