### ISSUE TITLE
WebClient unable to send files using InputStreamResource from 2.1.5.RELEASE

### ISSUE THREAD

**Issue by gurudatta11** [spring-projects/spring-framework#23372]
**Use case is:**
 send files via Streaming using _InputStream_, since _spring webclient_ is not working with _InputStreamResource_, made some modifications created _MultiPartInputStreamFileResource_ (code pasted below)
Using _ByteArrayInputStreamResource_ is not an option for us, it will load everything into memory (causing memory issues) instead of streaming.
Works till 2.1.4.RELEASE of spring-boot-starter-parent using (_MultiPartInputStreamFileResource_ ), 
1) 2.1.5.RELEASE of spring-boot-starter-parent  -> throws unsupported operation exception 
2) 2.1.6.RELEASE of spring-boot-starter-parent  ->
unsupported operation exception is resolved, but  Getting "Unexpected end of multipart data" from server, while sending files.

```
 <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.4.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
```
```java
public class MultipartInputStreamFileResource extends InputStreamResource {

  private final String filename;

  public MultipartInputStreamFileResource(InputStream inputStream, String filename) {
    super(inputStream);
    this.filename = filename;
  }

  @Override
  public String getFilename() {
    return this.filename;
  }

  @Override
  public long contentLength() {
    return -1; // we do not want to generally read the whole stream into memory ...
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    if (!super.equals(o)) {
      return false;
    }
    MultipartInputStreamFileResource that = (MultipartInputStreamFileResource) o;
    return Objects.equals(filename, that.filename);
  }

  @Override
  public int hashCode() {
    return Objects.hash(super.hashCode(), filename);
  }
}

public class ResourceHttpMessageConverterHandlingInputStreams extends ResourceHttpMessageConverter {

  @Override
  protected Long getContentLength(Resource resource, MediaType contentType) throws IOException {
    Long contentLength = super.getContentLength(resource, contentType);

    return contentLength == null || contentLength < 0 ? null : contentLength;
  }
}

  private BodyInserter<?, ? super ClientHttpRequest> getMultipartBodyInserter(
      InputStream inputStream, String fileName, String version, String messageDigest) {
    MultipartInputStreamFileResource multipartInputStreamFileResource =
        new MultipartInputStreamFileResource(inputStream, fileName);
    MultiValueMap<String, Object> multiValueMap = new LinkedMultiValueMap<>();
    addHashToMap(multiValueMap, messageDigest);
    multiValueMap.put("version", Arrays.asList(version));
    multiValueMap.put("file", Arrays.asList(multipartInputStreamFileResource));

    return BodyInserters.fromMultipartData(multiValueMap);
  }

```
and use the body inserter in webclient as below,

```java
 WebClient webClient = webClientBuilder.baseUrl(url).defaultUriVariables(uriVariables)
        .build();
    WebClient.RequestBodySpec requestBodySpec = webClient.method(httpMethod);
    Mono<ResponseEntity> responseEntityMono = requestBodySpec.body(bodyInserter).exchange()
        .flatMap(clientResponse -> clientResponse.toEntity(responseClassType));
```

**Comment by rstoyanchev** [comment]
First I don't think you need all that code. It should be possible to replace just a few lines:
```java
MultipartBodyBuilder builder = new MultipartBodyBuilder();
builder.part("file", resource).filename("MyFile.txt");
// ...

webClient.post()
    .syncBody(builder.build())
    .exchange()
    ...
```

> 2.1.6.RELEASE of spring-boot-starter-parent ->
unsupported operation exception is resolved, but Getting "Unexpected end of multipart data" from server, while sending files.

If you're sending files, should that not be a `FileSystemResource`?

In any case I think I will need a sample to reproduce the issue.

**Comment by gurudatta11** [comment]
@rstoyanchev  
I have attached demo.zip (contains sample code which reproduces the issue), 
use "http://localhost:8080/hello" to trigger the api , 
in the pom.xml, please change version of spring boot starter parent accordingly (2.1.4, 2.1.6), works for 2.1.4, not for 2.1.5, 2.1.6

[demo.zip](https://github.com/spring-projects/spring-framework/files/3468770/demo.zip)

- Couldn't find filename method in MultipartBodyBuilder/ MultipartBodyBuilder.part
- We have file/s stored in a separate smb (samba server), so we get input stream, not FileSystemResource

**Comment by gurudatta11** [comment]
resolved by https://github.com/reactor/reactor-netty/issues/820

**Comment by ShubhaKV** [comment]
Hi,

I need to send the content of zip to post method.
Here byte[] is the binary file i uploaded in postman


public String publishZipFile(byte[] data)  {
	
	    System.out.println(data.length);

		String channelResp =null;
				webClientBuilder
				.build()
				.post()
				.uri("/appCatalogs/teamsApps")
				.headers(httpsHeader -> httpsHeader.addAll(headerMap))
				.syncBody(data)
				.retrieve()
				.bodyToMono(byte[].class)
				.block();
		
		
		return  channelResp;
		
	}

Anything wrong am doing here.
Pls help mw how i can send zip file content to body of webclient
