### ISSUE TITLE
Provide a way to predict bean types without initializing FactoryBeans

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23374]
See [this comment](https://github.com/spring-projects/spring-framework/pull/23341#issuecomment-515168796) for details.

I don't think we currently have a way to tell the predicted type of a bean without initializing it. It might be nice if we could either surface a `getType(String name, boolean allowEagerInit)` or perhaps add a callback based approach similar to the existing `getBeanNames...` methods:

```java
<T> void doWithBeanNamesForType(@Nullable Class<T> type, boolean includeNonSingletons, boolean allowEagerInit, BiConsumer<String, Class<T>> consumer);
```

We should wait until #23341 is merged before taking this on.

**Comment by jhoeller** [comment]
@philwebb Would you expect such a `getType(String name, boolean allowFactoryBeanInit)` method to be available on the `BeanFactory` interface, not just on the factory implementation hierarchy? And the flag would only affect the internal `getTypeForFactoryBean` call, I suppose?

**Comment by philwebb** [comment]
@jhoeller I haven't given too much thought, but I assumed on the interface next to `BeanFactory.getType(String name)` would be best. It probably doesn't matter too from our side since we can always cast.

> the flag would only affect the internal getTypeForFactoryBean call, I suppose?

I think so. I think all the other areas of the current implementation don't cause initialization.
