### ISSUE TITLE
Webclient getCookies() returns only one cookie when there is duplicate cookie in header

### ISSUE THREAD

**Issue by Odysseymoon** [spring-projects/spring-framework#23388]
**Affects:** \5.1.4.RELEASE

---

Spring-boot : 2.1.2.RELEASE
Spring-webflux : 5.1.4.RELEASE
reactor-netty : 0.8.4.RELEASE

When response header have many Set-Cookie header with same key like as shown below
webclient clientResponse.cookies() return only the first cookie  

```
Set-Cookie : CookieKey=firstCookieValue expires=Tue, 30-Jul-2019 11:17:56 GMT; path=/; HttpOnly
Set-Cookie : CookieKey=SecondCookieValue; path=/
```

**Comment by rstoyanchev** [comment]
The two have the same name and path, and no domain. My reading of [the RFC](https://tools.ietf.org/html/rfc6265#section-5.3) in section 5.3, 11 is that those are considered the same and only one should be stored.

In any case, you can see that Netty's [DefaultCookie](https://github.com/netty/netty/blob/718b7626e680530aa08be9f643268ef4c5f0b8bc/codec-http/src/main/java/io/netty/handler/codec/http/cookie/DefaultCookie.java#L128-L158) considers cookies to be same if they have the same name, path, and domain, and Reactor Netty [puts those](https://github.com/reactor/reactor-netty/blob/6563cf1d3c1ff2705078e334b3b13fc68dd12117/src/main/java/reactor/netty/http/Cookies.java#L100) in a `Map<String, Set<Cookie>>`. On the Spring side we simply [put them](https://github.com/spring-projects/spring-framework/blob/30132b42c6c0d6e0f6bf17c3c0385ae8293f646b/spring-web/src/main/java/org/springframework/http/client/reactive/ReactorClientHttpResponse.java#L101) in a `MultieValueMap`.

So feel free to add a comment but even if this was a valid requirement, which I'm not sure it is, there is nothing further we would have to do on the Spring Framework side. It would need to be a chance in Reactor Netty.
