### ISSUE TITLE
Deprecate mutable aspects of MethodParameter

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23385]
Issue #23352 has shown that the mutable nature of `MethodParameter` can cause problems. One particularly unusual aspect is that `getContainingClass()` can change as a side effect of calling `GenericTypeResolver.resolveParameterType()`.

Internally, we don't actually mutate `MethodParameter` instances that often so it's possible that we could deprecate the mutation methods in favor of calls that return a new instance.

**Comment by philwebb** [comment]
@jhoeller I have a branch here with a fix https://github.com/philwebb/spring-framework/tree/gh-23385. It will need to be rebased when #23352 is committed.

**Comment by jhoeller** [comment]
@philwebb This looks alright to me. Feel free to bring a corresponding commit into master ASAP.
