### ISSUE TITLE
Functional Bean Definition DSL for noarg functions

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-framework#23395]
**Affects:** 5.2.0.M3

When using the Kotlin-based _Functional Bean Definition DSL_ I'm having a definition like this one:

```
val beans = beans {
    bean<CustomerService>()
    bean<CustomerHandler>()

    // 3 args resp. 1 arg
    bean(::router)    
    bean(::securityWebFilterChain)

    // userDetailsService has no args
    // bean(::userDetailsService) DOESN'T COMPILE
    bean { userDetailsService() }
}
```

For readability reasons it would be nice to also use a function reference when the bean function has no arguments.

**Comment by sdeleuze** [comment]
Thanks for reporting it and sorry for the lag.
