### ISSUE TITLE
Properly encoded + (plus sign encoded with %2B) still replaced with blank space in @RequestParam

### ISSUE THREAD

**Issue by larsduelfer** [spring-projects/spring-framework#23400]
Hi all,

there are many issues here raised regarding the handling of "+" signs in URLs. Nevertheless, I understood that if they are properly encoded (replaced by %2B) they should be decoded again as a "+" and not as blank space. However, that is not the case (with Spring 5.1.8) Maybe I am still getting something wrong here but from my understanding this is not as it's supposed to be.

I have trouble using an ISO timestamp as a request parameter although I encoded the + sign with %2B.

Any help and explanations are very welcome!

Regards, Lars

**Comment by rstoyanchev** [comment]
hi @larsduelfer, it's not supposed to be, it's rather two alternatives and it depends which you want. Please review the section on [URI encoding](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#web-uri-encoding) and if you still have questions please show a snippet of the code you're using.

**Comment by larsduelfer** [comment]
Hi @rstoyanchev, maybe this is a missunderstanding: I was talking about decoding not encoding.

I have a @RestController that uses a date (Date class with ISO formatting) as a request parameter (annotated using @RequestParam) When I sent a properly encoded Request to this endpoint, the date cannot be converted, since the %2B is decoded to a blank space. So when I want to use an ISO timestamp, it currently only works for timezones like -XX:XX but not for those like +XX:XX (or the properly encoded version thereof).

**Comment by rstoyanchev** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by rstoyanchev** [comment]
`@RequestParam` obtains the value from `HttpServletRequest`, there is no extra decoding involved within Spring. Have you tried just accessing this via `HttpServletRequest#getParameter` to see what you get?

**Comment by larsduelfer** [comment]
Hi @rstoyanchev I must appologize for causing confusion. I was chasing a phantom error here. It actually works as expected. When the URL is properly encoded, the iso timestamp is parsed and converted to Date. I don't know what happened last week so that I got confused. Thanks for your help in anyway. Regards, Lars
