### ISSUE TITLE
spring-webmvc-4.3.16.RELEASE: MediaType 'application/hal+json' is not included in '*/*' or 'application/*'

### ISSUE THREAD

**Issue by Farix1337** [spring-projects/spring-framework#23403]
The Mediatype `application/hal+json` is not compatible with the Wildcard MediaType `*/*`

This will cause a `HttpMediaTypeNotAcceptableException` in `org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor#writeWithMessageConverters` of the libary spring-webmvc-4.3.16.RELEASE when an error message with `application/hal+json` is written, even if the client accepts it.

**Comment by rstoyanchev** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by rstoyanchev** [comment]
Can you provide a better description including request details, and relevant parts of controller. I don't quite understand what happens and the below is not true.

> The Mediatype application/hal+json is not compatible with the Wildcard MediaType */*

```java
MediaType mediaType = MediaType.parseMediaType("application/hal+json");
System.out.println(mediaType.isCompatibleWith(MediaType.ALL));

// Prints true
```

**Comment by membersound** [comment]
Maybe you have a content negotiation configuration that sets `ContentNegotiationConfigurer.defaultContentType())`? This might pervent the `*/*` wildcard from working correctly.

**Comment by Farix1337** [comment]
Sorry it seems i was of. My `@GetMapping` had a `produce="application/pdf"` but this could throw an Exception which was written as appliation/hal+json. The client accepted everything by using wildcard mediatypes but i still got a a `HttpMediaTypeNotAcceptableException` and a misleading error message.
This happens due the producableMediaTypes check in `AbstractMessageConverterMethodProcessor#writeWithMessageConverters`.
The behaviour is correct, but the error Message is really confusing
