### ISSUE TITLE
AnnotationReadingVisitorUtils does not log a warning when it encounters an exception

### ISSUE THREAD

**Issue by mwiacek** [spring-projects/spring-framework#23406]
**Affects:** 5.1.8

The following section causes the problem:
`
catch (Throwable ex) {
				// Class not found - can't resolve class reference in annotation attribute.
				result.put(entry.getKey(), ex);
			}
`
Catching any Throwable seems to be excessive.

**Comment by mwiacek** [comment]
Created a PR for this problem.

**Comment by sbrannen** [comment]
Superseded by gh-23408
