### ISSUE TITLE
Add a new RequestEntity$HeadersBuilder#headers(HttpHeaders) method

### ISSUE THREAD

**Issue by grimsa** [spring-projects/spring-framework#23404]
**Affects:** 5.1.9 and previous versions (spring-web)

---

`RequestEntity` builders are very handy, however adding multiple headers can currently only be done like this:

```java
        return RequestEntity.get(url)
            .header("first", "value")
            .header("second", "other value")
            .build();
```

This is cumbersome when a common set of headers needs to be added to various requests.

Adding a `B headers(HttpHeaders headers)` method to `RequestEntity$HeadersBuilder` would solve it by making this possible:

```java
        return RequestEntity.get(url)
            .headers(new CommonHttpHeaders())        // implements HttpHeaders
            .build();
```

The same method was added to `ResponseEntity$HeadersBuilder` with #16929, so this would also improve consistency between request and response builders.

**Comment by rstoyanchev** [comment]
In other places we have `headers(Consumer<HttpHeaders>)`. For consistency I would add since it is useful in any case to be able to modify the underlying headers. In your case it would look:

```java
return RequestEntity.get(url)
        .headers(headers -> headers.putAll(new CommonHttpHeaders()))
        .build();
```

**Comment by poutsma** [comment]
I added `headers(HttpHeaders)` to `RequestEntity` and `headers(Consumer<HttpHeaders>)` to both `RequestEntity` and `ResponseEntity`.
