### ISSUE TITLE
Improve Javadoc of ContentNegotiationManagerFactoryBean

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#23409]
About the javadoc for the [ContentNegotiationManagerFactoryBean](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/accept/ContentNegotiationManagerFactoryBean.htm) class, appears in the top the following:

```
Property Setter                 | Underlying Strategy          | Default Setting
setFavorPathExtension(boolean)  | Path Extension strategy      | On
favorParameter                  | Parameter strategy           | Off
ignoreAcceptHeader              | Header strategy              | On
defaultContentType              | Fixed content strategy       | Not set
defaultContentTypeStrategy      | ContentNegotiationStrategy   | Not set

```

Where again through the javadoc I can confirm the following: 

* The [setFavorPathExtension](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/accept/ContentNegotiationManagerFactoryBean.html#setFavorPathExtension-boolean-) method indicates that by default it is is set to **true**, same information as the table shown above, in this case **On**.
* The [favorParameter](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/accept/ContentNegotiationManagerFactoryBean.html#setFavorParameter-boolean-) method indicates that by default it is is set to **false**, same information as the table shown above, in this case **Off**. 

The situation is with the `ignoreAcceptHeader` method

* The [ignoreAcceptHeader](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/accept/ContentNegotiationManagerFactoryBean.html#setIgnoreAcceptHeader-boolean-) method indicates that by default it is is set to **false**, but this information is **not** the same information as the table shown above, in this case **On**.

It is confuse, I am assuming that should be `Off` instead of `On`

**Comment by rstoyanchev** [comment]
Yes I agree that is confusing. What it really means is that the "Header Strategy" is on but the column heading is mismatched with the rows. We could do this instead:

|Property Setter | Default | Underlying Strategy | Strategy On/Off |
|:---|:---|:---|:---|
| setFavorPathExtension(boolean) | true | Path Extension strategy | On |
| favorParameter | false | Parameter strategy | Off |
| ignoreAcceptHeader | false | Header strategy | On  |
| defaultContentType | null | Fixed content strategy | Off |
| defaultContentTypeStrategy | null | ContentNegotiationStrategy | Off |

**Comment by manueljordan** [comment]
Hello @rstoyanchev 

Yes, has sense the new structure. 

Consider to add perhaps a special note about a explanation for the `Property Setter` and `Underlying Strategy` columns and their relation, I think it  would be a nice complement too. It to let the understand reader/developer the relation.
