### ISSUE TITLE
Confusion in contribution guidelines regarding PR vs Issue

### ISSUE THREAD

**Issue by Syquel** [spring-projects/spring-framework#23427]
The contribution guidelines and the default Issue template on GitHub are inconsistent and confusing in regard to whether to create a Pull Request and / or a GitHub Issue.

While the default template for new issues states
> Issue or Pull Request? Create only one, not both.

the [CONTRIBUTING.md](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#submit-a-pull-request) in the section "Submit a Pull Request" states
> For all but the most trivial of contributions, please create a ticket.

It would be great to have that consistent, because I don't know if I should create an issue for my pending pull requests and rewrite my commits to include the ticket number or not.

**Comment by snicoll** [comment]
Thanks for bringing this to our attention @Syquel. The former is the most accurate version so please submit your PR right away.
