### ISSUE TITLE
Reference documentation for @Autowired's required attribute is misleading

### ISSUE THREAD

**Issue by aCodeRancher** [spring-projects/spring-framework#23428]
The Spring Framework 5 reference [documentation for `@Autowired`](https://docs.spring.io/spring/docs/5.1.9.RELEASE/spring-framework-reference/core.html#beans-autowired-annotation) states:
> The required attribute of `@Autowired` is recommended over the `@Required` annotation on setter methods. The required attribute indicates that the property is not required for autowiring purposes. The property is ignored if it cannot be autowired.

I think it should be `required=false` indicates that the property is not required.

Please update it if you think I am correct.

**Comment by sbrannen** [comment]
Thanks for pointing that out.

The wording is indeed misleading, so we'll improve it for Spring Framework 5.2.

**Comment by sbrannen** [comment]
This has been addressed in e4fec9364c1e3ffc4c5f8107eb74d1de717e02e9.

The wording of that particular sentence now reads as follows.

> Setting the `required` attribute to `false` indicates that the property is not required for autowiring purposes, ...
