### ISSUE TITLE
Reference documentation for ContextClosedEvent is misleading

### ISSUE THREAD

**Issue by akvone** [spring-projects/spring-framework#23436]
**Affects:** \<All Spring Framework versions>

---

The Spring Framework [reference documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-ctx-events-tbl) for `ContextClosedEvent` states the following:

> Published **when the ApplicationContext is closed** by using the close() method on the ConfigurableApplicationContext interface. **Here, “closed” means that all singleton beans are destroyed.** ...

It seems that such a definition may be misleading as soon as it sounds like event is triggered **after** beans destruction.

Actually `AbstractApplicationContext#doClose` defines the real execution order.

**Comment by sbrannen** [comment]
@akvone, this has been addressed in 1925526df5e45a44f4b0a2c5426c6bf5920aebb2.

Please let us know if that is clearer now.

**Comment by akvone** [comment]
Yes, it's definitely better.
Thanks

**Comment by sbrannen** [comment]
> Yes, it's definitely better.
> Thanks

Great! Thanks for the feedback.
