### ISSUE TITLE
RSocket data decoding for per payload support

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-framework#23431]
Now RSocketRequester uses global data MimeType for Payload data decoding,  for some cases,  the applications want to mix multi data mime types, it means that some payloads will include data mime type information in CompositeMetadata of payload.  Now MetadataExtractor can extract route from per payload,  any idea to add dataMimeType of decoding for per payload. If dataMimeType is null, please use global data MimeType for payload data decoding.  

Code as following: 

```
interface MetadataExtractor {
    String ROUTE_KEY = "route";
   // data mime type for per payload
    String DATA_MIME_KEY="dataMimeType";
}
```

**Comment by rstoyanchev** [comment]
Currently the data MimeType can only be specified globally in the SETUP frame. The protocol doesn't define anything further and I don't think we should define a framework specific mechanism for it. This discussion should probably start at https://github.com/rsocket/rsocket.

Thinking about it, It could be along the lines of an extension (e.g. in CompositeMetadata) or perhaps individual request frames should provide a way to specify it.

That brings up the question about the different levels to which it could go:
* one MimeType per request applying to all payloads
* one MimeType for the request and another MimeType for the response
* potentially different MimeType for every payload

Also who gets to decide the MimeType for payloads in a response -- the requester, the responder, or some type of content negotiation between the two? 

Concrete use cases would help to define the requirements.

**Comment by rstoyanchev** [comment]
@linux-china I am closing this for now. Could you start a discussion in https://github.com/rsocket/rsocket instead regarding per request metadata and data MimeType? We can link to that from here.
