### ISSUE TITLE
rootObject parameter should be nullable in SpEL Expression

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#23442]
Currently we have something like (including variants):

```java
public interface Expression {

    @Nullable
    Object getValue(Object rootObject) throws EvaluationException;

    @Nullable
    <T> T getValue(@Nullable Class<T> desiredResultType) throws EvaluationException;
}
```

This cause some type inference issue with Kotlin where calling `val value = expression.getValue(String::class.java)` uses the first variant, not the second one. Also in implementation `rootObject` is nullable.

As a consequence, `Object rootObject` parameters should be changed to `@Nullable Object rootObject`. It is more correct semantically and avoid the "issue" in Kotlin.

**Comment by jhoeller** [comment]
Sounds good, let's do this for 5.2 indeed.

Generally speaking, this is an interesting effect of Kotlin's type inference to keep in mind...
