### ISSUE TITLE
Synchronized blocks in MethodOverrides are hurting concurrency

### ISSUE THREAD

**Issue by kennymacleod** [spring-projects/spring-framework#23448]
**Affects:** 5.1.x, 4.3.x

---
The fix for issue #18905 introduced `synchronized` blocks into the `MethodOverrides` class to fix a race condition. While this fixed the original bug, the introduction of the `synchronized` blocks is really hurting the concurrency of our application. We make use of method injection in a hot spot in our application, which has very high request concurrency. All of those requests go through `MethodOverrides`, and through these `synchronized` blocks. While the individual operations are fairly quick, it's still significant enough to cause serious concurrency degradation.

Can this class be reworked to avoid synchronized blocks?

**Comment by smarquard** [comment]
It would be nice to backport this to 4.3.x as well. We saw this show up in a Sakai 20 (using spring-beans 4.3) thread dump with multiple request threads blocked because of this issue.
