### ISSUE TITLE
Consider addressing alerts reported by lgtm.com

### ISSUE THREAD

**Issue by jbduncan** [spring-projects/spring-framework#23461]
I learned about a static analysis website called [lgtm.com](https://lgtm.com) some time ago, and I noticed that the Spring Framework has an entry on the website where currently [115 alerts](https://lgtm.com/projects/g/spring-projects/spring-framework/alerts) are reported against it, a few of which seem to be security-related.

I personally think these alerts should be looked into and ideally fixed. What's the Spring team's thoughts on this? :thinking:

**Comment by jbduncan** [comment]
(I'm unsure whether I should disclose the security-related alerts to https://pivotal.io/security, so I'd love some guidance on this.)

**Comment by jbduncan** [comment]
I raised a similar issue at https://github.com/spring-projects/spring-boot/issues/17868, where I was told that I should have indeed responsibly disclosed the security-related alerts after verifying them. So I intend to do so when I next have free time.

**Comment by snicoll** [comment]
@jbduncan indeed. Closing as per https://github.com/spring-projects/spring-boot/issues/17868#issuecomment-521375630
