### ISSUE TITLE
WebClient's Uri Builder is not encoding "+" in query parameter.

### ISSUE THREAD

**Issue by VikramAdh** [spring-projects/spring-framework#23474]
I am using below code snippet to re-produce this issue.

```java
final MultiValueMap<String, String> queryParams = new LinkedMultiValueMap<>();
String value= "2+3 4";
String key = "val";
queryParams.add(key, value);
ResponseSpec response = agent.get(headers->{}, queryParams, "/data/read");
String responseBody = respnose.bodyToMono(String.class).block(); 
```

The service call to producer application is happening successfully but it returns 404-Not Found since the query parameter is not encoded completely.

Encoded final url: `/data/read?val=2+3%204`

Expected encoded URL: `/data/read?val=2%2B3%204`

Here `"+"` is not encoded. Appreciate any suggestion here.

Thanks,
Vikram.N

**Comment by VikramAdh** [comment]
I am using Spring core 5.1.8 version. I actually found similar issue on below page and the issue was closed saying this is resolved in 5.1.3. 

https://github.com/spring-projects/spring-framework/issues/22064

**Comment by rstoyanchev** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by rstoyanchev** [comment]
There is no way to know what `serviceCaller.callGet` does exactly. Most likely the query param value needs to be expanded as a URI variable to apply the stricter encoding. Please review https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#web-uri-encoding.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by cah-bindiyasameem** [comment]
Our team solved this issue with the help of this [stack-overflow](https://stackoverflow.com/questions/64805657/how-to-encode-properly-the-plus-sign-when-making-a-request-with-webflux-webc)
`webClient.get()
    .uri { uriBuilder ->
        val queryParams = mapOf(
            "phone-number" to "+33612345678",
            "mobile-number" to "+61432111222"
        )
        uriBuilder.path("/endpoint")
            .apply { 
                queryParams.keys.forEach { key ->
                    queryParam(key, "{$key}")
                }
            }
            .build(queryParams)
    }`
