### ISSUE TITLE
Remove statusCode state from ContentCachingResponseWrapper

### ISSUE THREAD

**Issue by lpickford-yozu** [spring-projects/spring-framework#23490]
As part of one of our services we have a `HandlerInterceptor` which has some logic dependant on the status code of the response. As such we've been using a [ContentCachingResponseWrapper](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/ContentCachingResponseWrapper.java) in order to gain access to the body of the response object dependant on if the response object's `status` is equal to certain values.

When our `ControllerAdvice` catches an exception the `status` of the resultant response is set, and the response is then intercepted by our `HandlerInterceptor` implementation.

Inside the `HandlerInterceptor` we wrap the response object with `ContentCachingResponseWrapper`, and at this point the `status` and `statusCode` do not match. I believe this is because the ctor for `ContollerAdvice` ultimately does not set `statusCode`, but defaults to `HttpServletResponse.SC_OK` instead, where I believe it should default to the status of the response being passed in.

Is there a reason why `statusCode` is separate to `status`? Or would it make sense moving forwards to use `setStatus` and `getStatus` and have `getStatusCode` just forward to `getStatus` to preserve backwards compatibility?

**Comment by rstoyanchev** [comment]
It looks like `getStatus()` was only added in Servlet 3.1 which in Spring Framework 5 is a minimum requirement, so can remove the `statusCode` field and deprecate the `getStatusCode()` method.
