### ISSUE TITLE
WebClient's ClientRequest.Builder#cookies and ClientRequest.Builder#cookie give different results

### ISSUE THREAD

**Issue by skrzyneckik** [spring-projects/spring-framework#23502]
### Summary

`ClientRequest.Builder#cookies(Consumer<MultiValueMap<String, String>> cookiesConsumer)` gives different results than `ClientRequest.Builder#cookie(String name, String... values)`

### Actual Behavior

**Code:**

`builder.cookies( cookies -> cookies.set(  "XSRF-TOKEN", "7ed2ea19-7442-413a-ab5d-4be9c2f4a3ed" ) )`
or
`builder.cookies( cookies -> cookies.add(  "XSRF-TOKEN", "7ed2ea19-7442-413a-ab5d-4be9c2f4a3ed" ) )`

**What is sent**

`Set-Cookie: XSRF-TOKEN=7ed2ea19-7442-413a-ab5d-4be9c2f4a3ed; Path=/; Secure`

**Code:**

`builder.cookie( "XSRF-TOKEN", "7ed2ea19-7442-413a-ab5d-4be9c2f4a3ed" ) `

**What is sent**

`Set-Cookie: XSRF-TOKEN=7ed2ea19-7442-413a-ab5d-4be9c2f4a3ed`

### Expected Behavior

Both methods create the same cookie or documentation indicates the difference.

### Version

spring-webflux - 5.1.8.RELEASE

### Sample

Discovered it when I was working on CsrfClientExchangeFilterFunction which can be found here: https://stackoverflow.com/a/57611121/2004186

**Comment by rstoyanchev** [comment]
There is no difference in how the two are processed as you can [see here](https://github.com/spring-projects/spring-framework/blob/ad6231ad2989ca5428bb51afdf48a9112710ce1d/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultClientRequestBuilder.java#L113-L125) so I've no idea. Further on we [turn these](https://github.com/spring-projects/spring-framework/blob/ad6231ad2989ca5428bb51afdf48a9112710ce1d/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultClientRequestBuilder.java#L241-L247) into `HttpCookie` which has only name and value (no path, and no secure flag which are added on the response side). 

Perhaps there is something else in the underlying HTTP client library. You can try debugging further based on these pointers or else I'm afraid I'll need a sample to debug.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
