### ISSUE TITLE
Gradle build fails on MS Windows

### ISSUE THREAD

**Issue by QBH-insist** [spring-projects/spring-framework#23507]
spring-framework : v5.2.0.RC1
Gradle  and JVM version: 
![image](https://user-images.githubusercontent.com/39401478/63576059-0a5f8100-c5be-11e9-8328-6732fd573999.png)

1.. when i clone the project, i execute the 'gradlew :spring-oxm:compileTestJava' in the cmd . And the result is **successful** 
![image](https://user-images.githubusercontent.com/39401478/63576345-85c13280-c5be-11e9-84af-3496732277df.png)

2. The i use Idea import the project , gradle build is **fail**
![image](https://user-images.githubusercontent.com/39401478/63576616-257ec080-c5bf-11e9-81a1-2015d68b832a.png)

and i try to solve this problem，but unsatisfactory

Thanks!

**Comment by bclozel** [comment]
The ["Build from source"](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source#build-from-the-command-line) wiki section mentions that you need to use our Gradle Wrapper.
I guess we're using an API (within scripts or plugins) which is not available in Gradle 4.6.

Could you try building using `./gradlew` instead of your local Gradle installation?

**Comment by QBH-insist** [comment]
hi, i execute the './gradlew build', but the reult still fail,
![image](https://user-images.githubusercontent.com/39401478/63580368-3f240600-c5c7-11e9-8596-526f5065ff32.png)

the image is 的‘ file:///F:/allworkspace/ideaworkspace/spring-framework/spring-context-indexer/build/reports/tests/test/index.html’ context，it tell me delete dir fail, but it excetue by admin role
![image](https://user-images.githubusercontent.com/39401478/63580753-0f293280-c5c8-11e9-9ae8-ba434c017761.png)

**Comment by bclozel** [comment]
This looks similar to spring-io/initializr#862 and I've just pushed a fix for the test you're having issues with. Could you try again after updating your master branch?

**Comment by QBH-insist** [comment]
Yes, of course, Thanks
**but there is an another problem** 
![image](https://user-images.githubusercontent.com/39401478/63592419-26761900-c5e4-11e9-9e30-8419747673e9.png)

![image](https://user-images.githubusercontent.com/39401478/63592399-1a8a5700-c5e4-11e9-8215-809f7865cb0b.png)

**Comment by bclozel** [comment]
@QBH-insist are you able to consistently reproduce this issue or does it happen sometimes only?
@sbrannen I'm not super familiar with that part of our codebase; do you see anything in that test that could result with this?

**Comment by sbrannen** [comment]
That's a bit strange. 

The test sleeps for 200 ms (i.e., 2,000,000,000 ns), but for @QBH-insist the test appears to sleep for less than that.

I've never seen that test fail locally or on our CI server, but I suppose we could subtract a `fudgeFactor` like we add for other assertions in that `StopWatchTests`.

**Comment by sbrannen** [comment]
@QBH-insist, I made some changes to `StopWatchTests` in bfbe84d1c67a743efbbdda06c64c4ae74c5fc221.

Please let us know if that helps.

**Comment by QBH-insist** [comment]
hi, i pull the Latest branch， execute the command './gradlew build',  the result like that，still exception.
Thank you very much for your patience and help me solve the problem opportune.
![image](https://user-images.githubusercontent.com/39401478/63631012-1433c380-c654-11e9-8429-385314aabc8d.png)
![image](https://user-images.githubusercontent.com/39401478/63631037-82788600-c654-11e9-918b-9df9da77b657.png)
![image](https://user-images.githubusercontent.com/39401478/63631045-93c19280-c654-11e9-9244-25c46909fe8d.png)

**Comment by youngfuture** [comment]
I have the same problem！

1.I clone the code 
2.cd  spring-framework
3.gradlew :spring-oxm:compileTestJava
4.build success but I import the code to idea fail!

idea201902-64
jdk1.8.0_221
gradle 4.9

Could  you update import-into-idea.md file to an new ? We look forward to your help！thanks so  much!
@sbrannen

**Comment by youngfuture** [comment]
![image](https://user-images.githubusercontent.com/12947405/64176318-c6a72a00-ce8f-11e9-85d6-76be83620f0f.png)

**Comment by bclozel** [comment]
@youngfuture did you run this command with the gradle wrapper `./gradlew`?
Do you have any specific Gradle configuration or script in your `$HOME/.gradle` folder?
This plugin [is published here](https://plugins.gradle.org/plugin/me.champeau.gradle.japicmp), so I don't know why your setup won't resolve this build dependency.

**Comment by sbrannen** [comment]
@QBH-insist and @youngfuture, have you tried again recently on MS Windows?

**Comment by QBH-insist** [comment]
> @QBH-insist and @youngfuture, have you tried again recently on MS Windows?

hi, i try again and is success，thanks!

**Comment by sbrannen** [comment]
Great! Glad to hear it now works for you, @QBH-insist.

Based on that feedback, I am now closing this issue.

@youngfuture, please try again with a fresh clone from `master`. If you still encounter issues, feel free to post back here or (preferably) create a new issue with details specific to the failures you encounter.
