### ISSUE TITLE
Support invoking static methods with ReflectionTestUtils.invokeMethod()

### ISSUE THREAD

**Issue by Thunderforge** [spring-projects/spring-framework#23504]
### Background

Spring Test's [ReflectionTestUtils](https://docs.spring.io/spring-framework/docs/5.1.9.RELEASE/javadoc-api/org/springframework/test/util/ReflectionTestUtils.html) includes methods for setting/getting fields, like so (bolded text is from me):

 - `getField(Class<?> targetClass, String name)`
    - Get the value of the **static field** with the given name from the provided `targetClass`.
 - `getField(Object targetObject, Class<?> targetClass, String name)`
    - Get the value of the **field** with the given name from the provided `targetObject`/`targetClass`.
 - `getField(Object targetObject, String name)`
    - Get the value of the **field** with the given name from the provided `targetObject`.

Note that `getField()` works for both static fields and regular fields (support for static fields was added in v4.2.0.RC1 with [this commit](https://github.com/spring-projects/spring-framework/commit/063ef240c185fe6ba2ed39ef2fc6767c7a8dd900), associated with #11458).

### Problem

In contrast, there is only one version of `invokeMethod()`, and it only works on an instantiated `Object`.

 - `invokeMethod(Object target, String name, Object... args)`
   - Invoke the **method** with the given name on the supplied target object with the supplied arguments.

There are no other versions of `invokeMethod()` that work for static methods. 

### Feature Request

To make the class more consistent with `getField()` and `setField()`, I would like to request a new version of `invokeMethod()` that works on static methods:

 - `invokeMethod(Class<?> targetClass, String name, Object... args)`
   - Invoke the **static method** with the given name on the provided `targetClass` with the supplied arguments.

If it makes sense, we should also add:

 - `invokeMethod(Object targetObject, Class<?> targetClass, String name, Object... args)`
   - Invoke the **method** with the given name on the provided `targetObject`/`targetClass` with the supplied arguments.

**Comment by sbrannen** [comment]
The necessary changes have been made for Spring Framework 5.2 in 5ce75f3d08be08536278e231b3ecacafd672dde8.

Thanks for raising the issue.
