### ISSUE TITLE
Provide a method to get the original bean name from a scoped target's bean name

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#23514]
We have a case in Spring Boot's `@SpyBean` support where we need to get the original bean name from a scoped target. `ScopedProxyUtils` provides a method to go from the original to the scoped target name but not the other way around. Could such a method be added please? 

For the time being, we'll probably do something like this:

```java
if (ScopedProxyUtils.isScopedTarget(beanName)) {
	beanName = beanName.substring("scopedTarget.".length());
}
```

**Comment by sbrannen** [comment]
@wilkinsona, let me know if this (9be6aa64ef190a930f51ded7562609b3a63d3613) is sufficient for you.

**Comment by wilkinsona** [comment]
It is indeed. Thank you. Could this be considered for a backport to 5.1.x please? It's not essential by any means, but we have the same `substring` logic in Boot 2.1 and 2.2 and it would be nice to be able to use `getOriginalBeanName` in both branches if possible.

**Comment by sbrannen** [comment]
Sure, we'll go ahead and backport this to 5.1.

**Comment by sbrannen** [comment]
Backported to `5.1.10` in 9d2a874e3ffcaf5549156aa3520f577bb504de1a.
