### ISSUE TITLE
java.lang.UnsupportedOperationException SuppressedExceptions: Collections$UnmodifiableRandomAccessList

### ISSUE THREAD

**Issue by dmitrius** [spring-projects/spring-framework#23510]
Hi All,

I have an issue with webflux - java.lang.UnsupportedOperationException is thrown inside the framework. 
I debugged into this [piece of code](https://github.com/spring-projects/spring-framework/blob/50decc43cea4cfbcb92afabd8fa892308a4a389d/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/ResponseEntityResultHandler.java#L155)

and found that 
`HttpHeaders responseHeaders = exchange.getResponse().getHeaders();
`
returns an object of ReadOnlyHttpHeaders (headers: NettyHeadersAdapter)
So the next [piece of code](https://github.com/spring-projects/spring-framework/blob/50decc43cea4cfbcb92afabd8fa892308a4a389d/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/ResponseEntityResultHandler.java#L158)
```
			if (!entityHeaders.isEmpty()) {
				entityHeaders.entrySet().stream()
						.forEach(entry -> responseHeaders.put(entry.getKey(), entry.getValue()));
			}

```
throws this kind of exception.

Could you please provide a workaround or a fix?

Thank you,
Dmitri

**Comment by dmitrius** [comment]
In my case the issue manifests whenever a server throws an exception and the client is waiting for Flux<>, so that I am unable to catch the server error with the onStatus(HttpStatus::isError)

**Comment by rstoyanchev** [comment]
`exchange.getResponse().getHeaders()` typically doesn't return read-only headers so generally describing what you've seen in a debugging session is not a good way to describe an issue. Please, start from the beginning and provide a proper description of what you're trying to do and include some sample code snippets as needed.

**Comment by dmitrius** [comment]
I put a sample code in [GitHub repo](https://github.com/dmitrius/spring-webclient-webflux-test-issue).

**Comment by poutsma** [comment]
The reason `onStatus` is not called is because the status code is 200 OK, and not 4xx or 5xx. The status code is 200 because you are sending a stream, and by the time the exception occurs (as the third element in the stream), the response status code has already been committed and cannot be changed anymore. The logs of the sample app even say so:

```
[3fae7f29] Error [test.AtomyTestApplication$TestException: exception] for HTTP GET "/v1/test2", but ServerHttpResponse already committed (200 OK)
```

The `UnsupportedOperationException` is due to the same cause: the response has already been committed, so any headers added in `CecRestControllerAdvice` result in this exception.
