### ISSUE TITLE
wiki build instructions out of date

### ISSUE THREAD

**Issue by jlawrynowicz** [spring-projects/spring-framework#23517]
**Affects:** project wiki / 5.2.0.BUILD-SNAPSHOT

---

Commit 7ce1f5e652fee3f0e21925ac12f0882d733badb3 (related to #23282) changes gradle task used for pushing artifacts to local maven repository, making instructions on project wiki obsolete:

https://github.com/spring-projects/spring-framework/wiki/Build-from-Source

`./gradlew install -x javadoc`

results in `Task 'install' not found in root project 'spring'.` error. Correct comand is:

`./gradlew publishToMavenLocal -x javadoc`

This change is not compatible with branches 5.1.x and earlier, so perhaps wiki article should be expanded to reflect that or install task should be restored to preserve old behavior.

**Comment by sbrannen** [comment]
Thanks for bringing this to our attention.

Since the wiki is not tied to `master` or any particular branch, we will in fact need to update the wiki accordingly.

**Comment by sbrannen** [comment]
The instructions on the wiki have now been updated: https://github.com/spring-projects/spring-framework/wiki/Build-from-Source#install-in-local-maven-repository
