### ISSUE TITLE
Add method to apply Consumer<RequestSpec> in RSocketRequester

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#23513]
Currently to include a credential within `RSocketRequester` a user needs to pass in a value and MediaType. If there are multiple values, the user has double the work to do. If there is a rich type being provided, the `RSocketStrategies` likely needs to be customized as well. For example, providing a username/password might look something like this:

```java
this.requester.route("secure.retrieve-mono")
		.metadata(credentials.getUsername(), USERNAME)
		.metadata(credentials.getPassword(), PASSWORD)
		...
```

It would be nice if a user could just do something like:

```java
this.requester.route("secure.retrieve-mono")
        // apply(Consumer<RequestSpec>)
		.apply(credentials(credentials))
		...
```

Another point is that it appears that RSocket APIs typically integrate using a Flyweight pattern such that encoding has access to lower level APIs (i.e. `ByteBuf metadata`). However, `RSocketRequester` does not provide access to these APIs. This means that direct support for `RSocket` cannot be leveraged with `RSocketRequester`. It would be nice if this could be reused somehow.

**Comment by rstoyanchev** [comment]
For the second point, I don't think it belongs in the same issue, but let me first ask which RSocket API you have in mind? At the moment there is only routing and composite metadata. `RSocketRequester` takes care of encoding metadata internally and it will also utilize the routing API too for RC2 which only became available recently. 

The way it's supposed to work currently, the applications provide metadata Objects that are serialized to bytes via `Encoder` and then added to composite metadata, and you can either register an `Encoder` to do the serialization. Such an `Encoder` could also utilize a RSocket APIs in theory but we could consider whether that's straight forward enough. I'm just curious if there are specific APIs you have in mind.

**Comment by rstoyanchev** [comment]
@rwinch take a look at the changes in 58e9266, including a new method at the builder level (e.g. for connection setup or other). Hopefully those work for you.

I've also added support for providing a `ByteBuf` as a metadata value in b144c7, which means you can use an RSocket API such as the one for tracing when it becomes available, and then pass the resulting `ByteBuf`. This basic option and check makes sense in any case so I've gone ahead and added it.
