### ISSUE TITLE
build source code failed

### ISSUE THREAD

**Issue by thyu-xiaoya** [spring-projects/spring-framework#23520]
**Affects:** \<Spring Framework version>

---

when i build source code ,the gradle plugin build error
there is no class named **org/gradle/api/plugins/internal/JvmPluginsHelper**
my gradle version is 5.5.1

**Comment by snicoll** [comment]
@thyu-xiaoya the [build from source instructions](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) request you to use the Gradle wrapper (that is using 5.6 at the moment). If you chose to ignore that, you should make sure you're using the same version.

Try with the wrapper and let us know how it goes.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
