### ISSUE TITLE
Add support for transaction by method + lambda

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-framework#23529]
Besides `@Transactional` annotation, add support for transaction by method + lambda. 

```java
connection.transaction(lambda)
```

or in Kotlin

```kotlin
connection.transaction {
}
```

Examples
- https://www.jooq.org/doc/3.11/manual/sql-execution/transaction-management/
- https://www.playframework.com/documentation/2.5.x/JavaJPA#Running-transactions-decoupled-from-requests
- https://github.com/JetBrains/Exposed/wiki/Transactions
- Another example is `use` extension method from Kotlin: https://github.com/Kotlin/kotlinx.support/blob/master/kotlinx-support-jdk7/src/main/kotlin/AutoCloseable.kt#L13

In this case we can write 2 separate transaction in one method, and no need to make 2 separate methods just for adding `@Transactional`. Also no need for annotation processing.

**Comment by mdeinum** [comment]
You can already do this by injecting a [`TransactionTemplate`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/transaction/support/TransactionTemplate.html) and use its `execute` method.

**Comment by raderio** [comment]
I can not find isolation level parameter for `execute` method

**Comment by mdeinum** [comment]
You configure that on the `TransactionTemplate`.

**Comment by raderio** [comment]
Hm, what if I need different levels for different methods?

**Comment by mdeinum** [comment]
Use different templates.

**Comment by sbrannen** [comment]
As @mdeinum has pointed out, this is already achievable via the `TransactionTemplate`, and as of Spring Framework 5.2 there is also a new [`execute(Runnable)`](https://docs.spring.io/spring/docs/5.2.0.RC1/javadoc-api/org/springframework/transaction/support/TransactionOperations.html#execute-java.lang.Runnable-) method to simplify such use cases.

**Comment by sbrannen** [comment]
**Team Decision**: In light of the above, I am closing this issue.
