### ISSUE TITLE
Add blank line between java and javax imports

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23539]
Currently it's impossible to configure Eclipse to organize imports in a way that makes checkstyle happy. There's no way to not add the gap between `java` and `javax`.

Rather than fighting the IDE, we could consider changing the import rules.

**Comment by sbrannen** [comment]
Thanks for raising the issue, @philwebb.

I'm fully in favor of making this change to our formatting since it will significantly simplify matters for developers that use Eclipse as an IDE, and it would also align with many other Spring portfolio projects.

**Comment by sbrannen** [comment]
**Team Decision**: proceed with the proposal to add a blank line between `java` and `javax` imports.

**Comment by philwebb** [comment]
@sbrannen I took the liberty of applying a fix since I had the rule already available in Spring Boot. Feel free to revert if there are issues.

**Comment by sbrannen** [comment]
Thanks, @philwebb!

I updated the Wiki as well to reflect that: https://github.com/spring-projects/spring-framework/wiki/Code-Style#import-statements
