### ISSUE TITLE
PathMatchingResourcePatternResolver cannot load resources with a '#' in their file name within JARs

### ISSUE THREAD

**Issue by tofdragon** [spring-projects/spring-framework#23532]
**Affects:** spring version 5.1.5

### Description

Given file `/validation/api#test.json` within `a.jar` which is in the classpath...

a project dependent a.jar, in project code 

```java
ResourcePatternResolver resourceLoader = new PathMatchingResourcePatternResolver();
Resource[] resources22 = resourceLoader.getResources("classpath*:/validation/**/api#test.json");
InputStream inputStream = resources[0].getInputStream();
```

error:

```
Exception in thread "main" java.io.FileNotFoundException: JAR entry validation/api not found in a.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
```

### Analysis

The `URL` created in `org.springframework.core.io.UrlResource.createRelative(String)` treats everything after `#` as the URL _fragment_, causing the file path to be incorrect when the file is last read.

URL object:
- file: `a.jar!/validation/api`
- path: `a.jar!/validation/api`
- ref: `test.json`

#### Solution 1

```java
extends PathMatchingResourcePatternResolver

@Override
protected Set<Resource> doFindPathMatchingJarResources() {
  ....
    
      result.add(rootDirResource.createRelative(ParseUtil.encodePath(relativePath)))
  ...
}
```

#### Solution 2

```java
 URL url = resources[0].getURL();
            if (ResourceUtils.isJarURL(url) || ResourceUtils.isJarFileURL(url)) {
                String parent = url.toExternalForm().substring(0, url.toExternalForm().indexOf("!/validation/") + 13);
                String encodeFileName = url.toExternalForm().substring(url.toExternalForm().indexOf("!/validation/") + 13);
                String encodeFile = ParseUtil.encodePath(encodeFileName);
                URL url21 = new URL(parent + encodeFile);
                inputStream = url21.openStream();
            } else {
                inputStream = resources[0].getInputStream();
            }
```

### Question

Is there any other better solution, or is there a problem with my use?

**Comment by sbrannen** [comment]
Thanks for raising the issue.

As an interim solution, is it possible for you to rename the JSON files so that they do not contain hash tags (i.e., `#`) in their file names?

Also, where does `ParseUtil.encodePath(String)` come from? Is that a utility that you wrote, and if so, what type of encoding does it perform?

**Comment by sbrannen** [comment]
> Is there any other better solution, or is there a problem with my use?

Are your JSON files **always** in JAR files?

If so, have you tried the following?

```java
Resource[] resources = resourceLoader.getResources("classpath*:/validation/**/api%23test.json");
```

**Comment by sbrannen** [comment]
I've edited this issue to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
FYI: b173a93e72fab22516baccbc9bb9898c54d2de81 demonstrates that `PathMatchingResourcePatternResolver` does not have a problem loading resources with a `#` in their file name from the filesystem.

**Comment by tofdragon** [comment]
@sbrannen 
1.where does ParseUtil.encodePath(String) come from? 

<1-1>ParseUtil is sun.net.www.ParseUtil.   java.net.URLEncoder.encode() is OK!

<1-2>java.net.JarURLConnection

private void parseSpecs(URL url) throws MalformedURLException {
        String spec = url.getFile();

        int separator = spec.indexOf("!/");
        /*
         * REMIND: we don't handle nested JAR URLs
         */
        if (separator == -1) {
            throw new MalformedURLException("no !/ found in url spec:" + spec);
        }

        jarFileURL = new URL(spec.substring(0, separator++));
        entryName = null;

        /* if ! is the last letter of the innerURL, entryName is null */
        if (++separator != spec.length()) {
            entryName = spec.substring(separator, spec.length());
            // *****  use ParseUtil ******
            entryName = ParseUtil.decode (entryName);
        }
    }

<1-3>I found that the spring boot also has a JarUrlConnection, and there is also a decoding function in the guess.

2.Resource[] resources = resourceLoader.getResources("classpath*:/validation/**/api%23test.json");

That does not work

PathMatchingResourcePatternResolver  method 

protected Set<Resource> doFindPathMatchingJarResources()

···
for (Enumeration<JarEntry> entries = jarFile.entries(); entries.hasMoreElements();) {
				JarEntry entry = entries.nextElement();
				String entryPath = entry.getName();
				if (entryPath.startsWith(rootEntryPath)) {
					String relativePath = entryPath.substring(rootEntryPath.length()); 
                                        // ******  Unable to match escaped  *****
					if (getPathMatcher().match(subPattern, relativePath)) {
						result.add(rootDirResource.createRelative(relativePath));
					}
				}
			}
···

3.It is best to say that the file name does not contain #. Because of the project, there is no way to make a large rewrite, and the decoding has been considered in JarUrlConnection. Does it mean that the contract of Url Jar is considered to support encoding?

**Comment by lgxbslgx** [comment]
@tofdragon Could you give us a demo code which can reproduce the bug?

**Comment by tofdragon** [comment]
@lgxbslgx  Please see the problem description
