### ISSUE TITLE
sendBufferSizeLimit exceeded should be logged at warn level

### ISSUE THREAD

**Issue by davidtinker** [spring-projects/spring-framework#23534]
SubProtocolWebSocketHandler catches SessionLimitExceededException exceptions, logs them at debug level and closes the session. The client sees a randomly closed socket and there is nothing in the server logs. These exceptions should be logged as a warning as they indicate a serious issue with the application that needs to be addressed.

    catch (SessionLimitExceededException ex) {
        try {
            if (logger.isDebugEnabled()) {
                logger.debug("Terminating '" + session + "'", ex);
	    }
            this.stats.incrementLimitExceededCount();
            clearSession(session, ex.getStatus()); // clear first, session may be unresponsive
            session.close(ex.getStatus());

[SubProtocolWebSocketHandler.java](https://github.com/spring-projects/spring-framework/blob/14558844bc4dba5586f6f9e27731bf52e802dcc5/spring-websocket/src/main/java/org/springframework/web/socket/messaging/SubProtocolWebSocketHandler.java#L368-L379)

**Comment by rstoyanchev** [comment]
> the client sees a randomly closed socket

The session should be getting closed with an [error status](https://github.com/spring-projects/spring-framework/blob/bba3553dfb2561b9e779a6ca13b080c12b5940b1/spring-websocket/src/main/java/org/springframework/web/socket/CloseStatus.java#L136-L143). Is that not the case? 

When this error occurs, the idea is that the server is far behind in writing and the client may have become even unreachable. That said it's true on the server side we can at least log a one line message at warn level.

**Comment by davidtinker** [comment]
Yes the client does get an error status but its not easy to figure out why from that alone. I had to grep the Spring source code for the error number. Would have been much easier if there had been a warning in the server logs. Tx.
