### ISSUE TITLE
Replace TestSourcesPlugin with Gradle test fixture support

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#23550]
## Overview

We should consider replacing our custom [`TestSourcesPlugin`](https://github.com/spring-projects/spring-framework/blob/master/buildSrc/src/main/java/org/springframework/build/testsources/TestSourcesPlugin.java) with Gradle's official support for [Test Fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures).

## Rationale

- Currently all test code is visible in all other (downstream) projects, and that makes it too easy to introduce unnecessary coupling.
  - For example, this made it more difficult to migrate to JUnit Jupiter.
- Having test fixture code in a dedicated source folder makes it readily apparent that the code is reused across the test suite.
- It will be much cleaner if projects explicitly declare that they rely on specific test fixtures of upstream projects.

## Related Issues

- #23282

**Comment by marcphilipp** [comment]
It will also make builds faster because test classes in downstream projects won't have to be recompiled and tests won't have to be executed if only a test class changes in an upstream project.

**Comment by sbrannen** [comment]
**Update**: the work on this is essentially complete and can be viewed in the following feature branch.

https://github.com/sbrannen/spring-framework/commits/issues/gh-23550-test-fixtures

The only open issue is disabling the publication of `*-test-fixtures` artifacts. There is a built-in feature for that in Gradle 6.x, but we'll have to find a custom workaround for Gradle 5.6.x.
