### ISSUE TITLE
WebFluxTest and GlobalScope.Launch

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-projects/spring-framework#23558]
On a coroutine-based Webflux app, there is a difference in behavior between making HTTP requests via `WebFluxTest` and making requests directly to the server if `GlobalScope.Launch() `is used in the handler function. This difference can yield false-positives on tests. 

For example, if we create an HTTP POST using `WebTestClient` and in the corresponding handler function we `GlobalScope.Launch()` a coroutine that attempts to access the ServerRequest body then we will successfully be able to retrieve it. However, if we perform the same operation against the same handler function using a direct HTTP request against a fully running server, then, we will not be able to retrieve the body and get null as a result. 

Please see the reproducer code in the repo below and read the `DemoApplication.kt` file along with `DemoApplicationTests` file for a concrete demonstration.

https://github.com/PedroAlvarado/webflux-globalscope-issue

It is not clear whether this behavior is intended and we need some additional documentation with regards to the risks/gotchas of using `WebFluxTest` and Coroutines or whether there is an actual bug in behavior.

**Affects:** Spring Framework 5.2

**Comment by sdeleuze** [comment]
I don't think it demonstrates a particular issue, if you need to change the context you should probably use `withContext` and not `GlobalScope` which will launches a new coroutine invisible from WebFlux. For the difference of behavior, I guess the spawn Coroutines never has the time to be spawn when running as tests.

Could you describe your use case to allow me to see if there is something to improve in the documentation?

**Comment by PedroAlvarado** [comment]
> For the difference of behavior, I guess the spawn Coroutines never has the time to be spawn when running as tests.

If you check the logs of the demo app provided, you will notice that all coroutines spawn and complete. There is a delay of 3s as part of the launched coroutine and the test has a Thread.sleep(5000L). The concern is that you can write a perfectly valid handler and corresponding test that will be green when running automated tests however the tested behavior will not work in production.

> Could you describe your use case to allow me to see if there is something to improve in the documentation?

Loosely coupled with the concern above, the use case at hand is making a fire-and-forget HTTP request for analytics purposes. To make this request, it is necessary to capture data from the incoming HTTP request body. This request is a side-effect to the normal operations of the handler and, hence, the handler need not block or wait for the completion of that side-effect. Moreover, the handler need not care about the success or failure of such side-effect. This side-effect does not share the scope of the handler (structurally).

**Comment by PedroAlvarado** [comment]
This is not an issue.
