### ISSUE TITLE
Have MockMCV's content method convert object to JSON

### ISSUE THREAD

**Issue by AlexJuca** [spring-projects/spring-framework#23556]
While using springs mock mcv class to handle tests in a spring boot API it is **necessary** to send JSON content with the request body.

Eg.
```java
mockMvc.perform(post("/api/v1/user_registration/phone_code/resend").content(jsonBody).contentType(MediaType.APPLICATION_JSON_UTF8))
                .andDo(print())
                .andExpect(MockMvcResultMatchers.status().isOk()); 
```
Unfortunately, the only way I can do this is by first converting the object that I wish to send in the request body to JSON and then pass it as an argument to the ```MockHttpServletRequestBuilder.content()``` method. 

This usually adds extra noise to tests to handle the object to JSON serialization.

It would be very handy for those of us writing tests for APIs to have a content() method that 
excepts a plain old java object and does the conversion to JSON for us as well as define the content-type to "application/js" since it is obvious by the context that we will be sending JSON in the request body.

**Comment by sbrannen** [comment]
Superseded by #23557
