### ISSUE TITLE
Entry set of read-only HttpHeaders loses original headers' ordering

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#23551]
**Affects:** 5.1.9.RELEASE

The entry set returned from the result of calling `HttpHeaders.readOnlyHttpHeaders(HttpHeaders)` does not maintain the original headers' ordering. This is a regression from 5.1.0 that I think was introduced in 5.1.1 in https://github.com/spring-projects/spring-framework/commit/ce7278aaf4f20348862267c2081c20dc5bd77128. I believe the set is unordered due to the use of `Collectors.toSet()` which creats an unordered `Set`:

https://github.com/spring-projects/spring-framework/blob/1ea6ce72bb3b1139abc370f6dc32c51fc27ae90b/spring-web/src/main/java/org/springframework/http/ReadOnlyHttpHeaders.java#L146

**Comment by sbrannen** [comment]
Thanks for bringing this to our attention.

Your analysis is spot on, and the fix is as easy as `.collect(Collectors.toCollection(LinkedHashSet::new)))`.

I'll push that to `5.1.x` and `master` soon.
