### ISSUE TITLE
Non-argument constructor is still needed for @Configuration class

### ISSUE THREAD

**Issue by aCodeRancher** [spring-projects/spring-framework#23552]
Hi, the @Configuration API does not mention that it needs a non-argument constructor as a constraint in Spring 5 documentation. I know this was a limitation in Spring 4. I am sure it is still true for Spring 5.
Please verify this. 
This is my proof:
[code]
@Configuration
public class ApplicationConfiguration{
   public ApplicationConfiguration(int test){ }
   //no other constructor is defined.
 ..... 

}
[/code]
[code]
 public class MyApp{
   public static void main(String... args){
    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(ApplicationConfiguration.class);
  ....
  }
}
[/code]
Output:
[quote]
 Error creating bean with name 'applicationConfiguration': Unsatisfied dependency expressed through constructor parameter 0;
[/quote]

@Configuration Spring 5 API Reference:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html

**Affects:** \<Spring Framework version 5>

---

**Comment by snicoll** [comment]
That error is because the context tries to call your constructor and it can't find a bean of type `int`. The javadoc is accurate and you can define constructor with autowired dependencies since Spring Framework 4.3.
