### ISSUE TITLE
Custom DefaultResourceLoader subclass should be able to consume context-provided ProtocolResolvers

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#23564]
**Affects:** 4.3+

`ConfigurableApplicationContext` has a `addProtocolResolver` method that can be used to register additional `ProtocolResolver` implementations. As far as I can see, this is the recommended approach that is followed by a number of implementations out there (example in [Spring Cloud AWS](https://github.com/spring-cloud/spring-cloud-aws/blob/f436ecab53dbdbd549e2e73298975a8c34b15931/spring-cloud-aws-context/src/main/java/org/springframework/cloud/aws/context/support/io/SimpleStorageProtocolResolverConfigurer.java#L55)).

When setting a custom `ResourceLoader` on the context, one could get the already registered  `ProtocolResolver` instances (via `getProtocolResolvers`) if they want to reuse them but there is no way to be notified that additional instances have been configured. Unfortunately, the vast majority of the current implementations will register their protocol resolver later.

A concrete example is Spring Boot Devtools that has to set a custom `ResourceLoader` but should be improved to honour `ProtocolResolver` as well, see https://github.com/spring-projects/spring-boot/issues/9331

One way to workaround this problem is to get the registered list every time a resource has to be resolved. If you just want the default behaviour it's not super obvious to do that. I have some prototype in https://github.com/snicoll/spring-boot/commit/1ceba096825869707f3c048d15c7068e3ef0e4a7, wondering if we could improve the code by a change in framework.

**Comment by jhoeller** [comment]
As per our discussion today, we should at least make it easier for a custom `DefaultResourceLoader` to consume context-provided ProtocolResolvers. It seems that using the `getProtocolResolvers()` method instead of iterating the internal collection is an easy step to take there, making it convenient enough for Spring Boot and others to arrange for such a scenario. This is also doable for 5.1.10.
