### ISSUE TITLE
Support suspending functions annotated with @Transactional

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#23575]
As a follow-up of #22915, this issue is about supporting suspending functions annotated with `@Transactional`. It seems not straightforward to call `CoroutinesUtils.invokeHandlerMethod(method: Method, bean: Any, vararg args: Any?): Any?` from `TransactionAspectSupport.ReactiveTransactionSupport#invokeWithinTransaction` where we deal with a parameter-less `InvocationCallback`.

**Comment by sdeleuze** [comment]
It looks like I won't have the bandwidth to do that for Spring Framework 5.2, so this is a good candidate for Spring Framework 5.3.

**Comment by ErolPeel** [comment]
This feature would be really nice. 👍

**Comment by davidb-e4s** [comment]
Is there a workaround for this?

**Comment by sdeleuze** [comment]
For now you can use the programmatic variant via `TransactionalOperator` Coroutines extensions.

**Comment by cpdyj** [comment]
Maybe an off topic question. How do you predict the really call of suspend function actual? Looks to predict the Continuation is difficult.
