### ISSUE TITLE
ClassUtils.isPrimitiveOrWrapper(…) and friends should consider Void.class a primitive wrapper for void.class

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#23572]
Currently, `ClassUtils.isPrimitiveOrWrapper(…)` and `isPrimitiveWrapper(…)` do not consider `Void.class` a wrapper for `void`. Other primitives are covered, so it would make sense to consider `Void.class` a wrapper for `void.class`.

Here's a test case to reproduce the issue:

```java
@Test
public void isPrimitiveOrWrapperShouldConsiderVoid() {

	assertThat(ClassUtils.isPrimitiveOrWrapper(void.class)).isTrue();
	assertThat(ClassUtils.isPrimitiveOrWrapper(Void.class)).isTrue();
	assertThat(ClassUtils.isPrimitiveWrapper(Void.class)).isTrue();
}
```

**Comment by sbrannen** [comment]
Related to #23573
