### ISSUE TITLE
Memory leak when using @Async after upgrading from 5.1 to 5.2

### ISSUE THREAD

**Issue by arian** [spring-projects/spring-framework#23571]
**Affects:** 5.2.0.RC1

---

In our application I upgraded from spring-framework 5.1.9 to 5.2.0.RC1 and our tests started leaking memory.

Previously it looked like this in VisualVM:

![image](https://user-images.githubusercontent.com/109243/64158877-8d43cf80-ce39-11e9-8582-85357e439198.png)

And now it looks like this:

![image](https://user-images.githubusercontent.com/109243/64158907-9b91eb80-ce39-11e9-963a-e2c08716f55a.png)

I've made a heapdump to see where the memory is going:

![image](https://user-images.githubusercontent.com/109243/64163425-8325cf00-ce41-11e9-922d-886c6feac4e4.png)

I've seen something similar in our application previously, but that was solved by using `@MockBean` instead of a lot of `@ContextConfiguration` with `@Configuration` classes inside our test classes to override beans with mocked objects :thinking:...

**Comment by sbrannen** [comment]
Hi @arian,

Can you possibly reduce this to the smallest application possible that demonstrates the behavior (and provide access to the full example application)?

At the very least, it would be helpful to know what kind of components are active in the `ApplicationContext` and what configuration (i.e., annotations) you are using in your tests.

Without being able to debug it, we don't really have much to go on.

Thanks in advance!

**Comment by arian** [comment]
Yes I completely understand! It's difficult to create a reproducible small application for me as I don't really figured out what causes the problem.

> At the very least, it would be helpful to know what kind of components are active in the ApplicationContext and what configuration (i.e., annotations) you are using in your tests.

Is there an easy way to print a log of this or something?

Anyway I'll try to do some more testing after the weekend and see if I can report back!

**Comment by sbrannen** [comment]
> Is there an easy way to print a log of this or something?

Not for the annotations is use; however, it appears that you're using `@Scheduled`. So perhaps focusing on that part of your application might reveal something.

If you're using Spring Boot, you could use the actuator endpoint to get a list of all beans in the `ApplicationContext`. Otherwise, you might try Spring's `LiveBeansView` support.

> Anyway I'll try to do some more testing after the weekend and see if I can report back!

Thanks.

**Comment by arian** [comment]
The problem seems to occur with `@EnableAsync`. Without it running some tests look like:

![image](https://user-images.githubusercontent.com/109243/64689716-29e81c00-d48f-11e9-9659-d244b073eab5.png)

With `@EnableAsync`

![image](https://user-images.githubusercontent.com/109243/64689752-3e2c1900-d48f-11e9-90ed-ebc36b7bd8ac.png)

Also a heapdump when running without `@EnableAsync` doesn't show the list with `org.springframework.scheduling.annotation.AnnotationAsyncExecutionInterceptor` objects in memory.

Also commenting out all `@Async` seem to run the tests ok too.

Checked with 5.2.0.RC2, same result as RC1.

**Comment by sbrannen** [comment]
Thanks for investigating further and providing us the detailed feedback!

We'll look into it.

**Comment by sbrannen** [comment]
Tentatively slated for 5.2 GA for further investigation since this appears to be a regression.

**Comment by sbrannen** [comment]
Hi @arian,

Since this appears to be a regression, we'd really like to get to the bottom of this before we release Spring Framework 5.2 GA next week.

We brainstormed a bit within the team about possible causes for this, but we're really just shooting in the dark without being able to debug a project that reproduces the memory leak.

Based on your knowledge that the issue involves the use of `@Async`, we would be very grateful if you could provide us a small application that reproduces the problem.

If that's not possible, can you please run your test suite against 5.2 M1, 5.2 M2, and 5.2 M3 and let us know for which milestone versions you experience the problem?

That would help us at least to pinpoint when the regression was introduced.

Thanks in advance!

**Comment by sbrannen** [comment]
@arian, don't worry about the requests in my previous comment.

The following test class seems to reproduce the problem.

The test class succeeds unless you uncomment `@DirtiesContext`, in which case it leads to `java.lang.OutOfMemoryError: GC overhead limit exceeded`.

```java
@SpringJUnitConfig
class AsyncTestCase {

	@RepeatedTest(1000)
	// @DirtiesContext
	void test() {
	}

	@Configuration
	@EnableAsync
	@Import(AsyncService.class)
	static class Config {
	}

	static class AsyncService {

		@Async
		void doSomething() {
		}
	}
}
```

**Comment by sbrannen** [comment]
@arian, one last question:

Which testing framework are you using?

- JUnit 4
- JUnit Jupiter
- TestNG
- ?

**Comment by arian** [comment]
Cool, I was just looking into a way to reproduce it!

We're still using junit 4 at the moment.

**Comment by sbrannen** [comment]
> Cool, I was just looking into a way to reproduce it!
> 
> We're still using junit 4 at the moment.

OK. Thanks for the feedback.

**Comment by sbrannen** [comment]
Same error occurs with JUnit 4:

```java
@RunWith(SpringRunner.class)
public class AsyncTestCase {

	@Test
	@Repeat(1000)
	@DirtiesContext
	public void test() {
	}

	@Configuration
	@EnableAsync
	@Import(AsyncService.class)
	static class Config {
	}

	static class AsyncService {

		@Async
		void doSomething() {
		}
	}
}
```

**Comment by sbrannen** [comment]
@arian, can you confirm that executing your test suite with `-Dcglib.useCache=false` works without a memory leak?

**Comment by sbrannen** [comment]
Mystery solved: the newly introduced `AnnotationMatchingPointcut.AnnotationCandidateClassFilter` class doesn't implement `equals()`.

I've got a fix locally that I'll apply tomorrow to `master`.

**Comment by arian** [comment]
> @arian, can you confirm that executing your test suite with -Dcglib.useCache=false works without a memory leak?

With that it seems to work without leaks.

> Mystery solved

Great!
