### ISSUE TITLE
Detect unsupported suspending handler methods in Spring MVC

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#23585]
Given the reports I already had from people trying to use suspending functions with Spring MVC, better to provide an explicit check for that. Only WebFlux support suspending functions for now.

**Comment by tdelev** [comment]
Having this assertion in places blocks users to upgrade to Spring Boot 2.2.x when they have already implemented support for suspending handler methods using 

https://github.com/konrad-kaminski/spring-kotlin-coroutine/blob/master/spring-webmvc-kotlin-coroutine/src/main/kotlin/org/springframework/kotlin/coroutine/web/CoroutinesWebMvcConfigurer.kt

Could this be fixed, or the only thing would be to wait for the promised Spring Framework 5.3 native Spring MVC support?

**Comment by bjaanes** [comment]
It seems like this change adds some confusion when using WebFlux too?
https://stackoverflow.com/questions/61032704/spring-webflux-reactive-and-kotlin-coroutines-startup-error/61046628#61046628

**Comment by sdeleuze** [comment]
I can't see how a code in WebMvc could trigger such error when just WebFlux is used, could you please share a repro project?
