### ISSUE TITLE
Update IntelliJ IDEA codestyle with new import structure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#23586]
Our [codestyle.xml](https://github.com/spring-projects/spring-framework/blob/master/src/idea/spring-framework.xml) should be upgraded with regards to #23539

**Comment by rstoyanchev** [comment]
It seems to already do that?

https://github.com/spring-projects/spring-framework/blob/40a55b412d2caa0ea6e1bc3d641c3bd484c7740f/src/idea/spring-framework.xml#L21-L23

**Comment by snicoll** [comment]
Indeed. Fixed ahead of the change, how wonderful is that!

**Comment by sbrannen** [comment]
Reopening since the IDEA config puts static imports first instead of last as documented [here](https://github.com/spring-projects/spring-framework/wiki/Code-Style#import-statements).
