### ISSUE TITLE
MockClientHttpResponse loses original HttpStatus code

### ISSUE THREAD

**Issue by skrser** [spring-projects/spring-framework#23599]
When server replies with non-standard Http Code, e.g. 250, this information is swallowed and 200 code is returned.

https://github.com/spring-projects/spring-framework/blob/35b967a8016f3798502c56b7a7f9dbd700b5e23b/spring-test/src/main/java/org/springframework/test/web/reactive/server/HttpHandlerConnector.java#L124

**Comment by poutsma** [comment]
The  HTTP 1.1 spec defines the first digit of the status code as being [1-5], so throwing an exception for 600 seems fine to me.

**Comment by wilkinsona** [comment]
The spec lacks any specific normative statements about how a non-standard series should be handled. However it does say " However, a client MUST understand the class of any status code" and then go on to say "The first digit of the status-code defines the class of response. … There are five values for the first digit". Those values are then listed as 1-5. My reading is that there's no requirement to reject a 600 but that there's also no requirement to accept it.

The HTTP spec aside, I'm still not sure about the current asymmetry. I can use MVC or WebFlux to send a 600 response. I can receive such a response with `WebClient` or `RestTemplate`, but I cannot receive it with `WebTestClient`.

**Comment by poutsma** [comment]
You are right, the behavior should be symmetrical. I changed it to allow for all three digit numbers.
