### ISSUE TITLE
@ConfigurationProperties in plain spring

### ISSUE THREAD

**Issue by pulkitmehra** [spring-projects/spring-framework#23601]
I have a feature request. In spring boot we have `@ConfigurationProperties` to read the properties directly into bean, but there is nothing equivalent on the plain Spring side.

In our organization, we have a light framework shim over Spring . And due to legacy reasons we have two flavors of framework
- First, expose controller as Jersey with Spring DI and deployed as WAR (legacy)
- Second, deploy as SpringBoot App with Jersey Controller.

Now, this all work but reading properties like SpringBoot becomes challenge in plain Spring. Is it possible or do you have any workaround to import  `@ConfigurationProperties` in plain Spring. Any support will be highly appreciated!

**Comment by snicoll** [comment]
Thanks for the suggestion but this was raised before and declined, see #18372 for more details.
