### ISSUE TITLE
When I use Swagger, I use the SpringVersion.getVersion() method to return null.

### ISSUE THREAD

**Issue by ywbjja** [spring-projects/spring-framework#23610]
I user Swagger in Spring Cloud but it prompts me to return Null when using SpringVersion to get the Spring version number.
I'm using Spring-core is 5.1.6.REALESE.
thank you!

**Comment by abhishek-abhi** [comment]
I want to contribute to resolve this issue. Can you assign this task to me ? 

Best Regards,
Abhishek Kumar Mandal

**Comment by sbrannen** [comment]
@ywbjja and @abhishek-abhi, please tell us what you wish to change so that we can assess the proposal.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
