### ISSUE TITLE
Improper UTF-8 handling in MockMvc for JSON response

### ISSUE THREAD

**Issue by sgybas** [spring-projects/spring-framework#23622]
When `MediaType.APPLICATION_JSON_UTF8` was deprecated, the content type of JSON that gets sent from a `@RestController` changed to `application/json` (without charset). 

This breaks `MockMvc` tests that use `.andExpect(content().json())`. Here is a sample test:

```java
@Test
public void returnsTheExpectedResponse() throws Exception {
    mockMvc.perform(get("/"))
        .andExpect(status().isOk())
        .andExpect(content().json("{\"name\":\"Jürgen\"}"));
}
```

The test runs fine with Spring 5.1.9 but fails with Spring 5.2.0.RC2

```
java.lang.AssertionError: name
Expected: Jürgen
     got: JÃ¼rgen
```

You can find a sample Spring Boot project to reproduce the problem at https://github.com/sgybas/mockmvc-json-utf8

There was a similar issue for `jsonPath()` (#23219).

**Comment by cbartolome** [comment]
Both overloads of `ContentResultMatchers.string()` do this, too. Three other functions in that class call `getContentAsString()` with no arguments, but I'm not sure if that results in the same issue.

**Comment by chrisaige** [comment]
I use getContentAsString and mockMvc seems to return my Content as ISO 8859-1.
Before (with Spring Boot 2.1.9) it was proper UTF-8

When I mark my Endpoint with @Produces("application/json; charset=utf-8") it works as indented.
But I dont want to go throught all my endpoints todo this.

**Comment by rstoyanchev** [comment]
In your tests, `ContentResultMatchers#json(String)`.
