### ISSUE TITLE
Make org.springframework.web.multipart.MultipartFileResource Public

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-framework#23634]
I don't see anypoint in makeing this class org.springframework.web.multipart.MultipartFileResource Package scoped. This class can be used
by any Spring Developer to convert MultipartFile to Spring Abstration of Resource and hence must be public.

**Comment by rstoyanchev** [comment]
The class is package private because it's intended to be accessed via `MultipartFile#getResource()` which is public, so there should be no need for the class to be public..

**Comment by ankurpathak** [comment]
@rstoyanchev I missed that. Thanks for same. Closeing the issue.
