### ISSUE TITLE
RequestSpec.metadata(Consumer<RequestSpec>) not intuitive name

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#23639]
The name for `RSocketRequester` [RequestSpec.metadata(Consumer<RequestSpec>)](https://github.com/spring-projects/spring-framework/blob/957f0fac7a0dd1f0a7a5742fbeb8c40b7da439f0/spring-messaging/src/main/java/org/springframework/messaging/rsocket/RSocketRequester.java#L258) is not very intuitive since it can modify the entire `RequestSpec`. I wonder if we should modify the name or change the argument?

**Comment by rstoyanchev** [comment]
The method returns `RequestSpec` so then you need to call `data(...)` to get to `ResponseSpec`. So in practice you can only use this to add metadata. Data is not additive, unlike (composite) metadata, and that means it can only be set by one party.

**Comment by rwinch** [comment]
I see that invoking `data` won't work, but the API is still a bit confusing because I am providing a `Consumer<RequestSpec>` which allows me to invoke `metadata` just as easily as I am `data`.

**Comment by rstoyanchev** [comment]
This has been addressed as part of #23649 and is now `metadata(Consumer<MetadataSpec<?>> configurer)`.
