### ISSUE TITLE
Mention Ordered and @Order support for components in Javadoc

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-framework#23636]
While debugging `PostProcessorRegistrationDelegate`, I realized `BeanFactoryPostProcessor` works with `Ordered`(and `PriorityOrdered`) interface but not `@Order` annotation.

It would be great that such information is documented on `BeanFactoryPostProcessor` javadoc.

In general, for ordering, it would be great to have a mention in javadoc that whether the component works with `Ordered` interface and/or `@Order` annotation.

**Comment by sbrannen** [comment]
When you say "components", did you have any other special types in mind other than `BeanFactoryPostProcessor` implementations?

**Comment by ttddyy** [comment]
I was thinking mainly lifecycle related classes, `BeanFactoryPostProcessor`, `BeanPostProcessor`, `InitializingBean`, etc.

Also, it would be nice that `@Order` and `Ordered` have list of classes that will be applied ordering.

Thanks,

**Comment by sbrannen** [comment]
> I was thinking mainly lifecycle related classes, `BeanFactoryPostProcessor`, `BeanPostProcessor`, `InitializingBean`, etc.

For `BeanFactoryPostProcessor` and `BeanPostProcessor` I agree that it would be helpful to document ordering support for `PriorityOrdered` and `Ordered`.

I don't think any ordering is applied to `InitializingBean` implementations.

> Also, it would be nice that `@Order` and `Ordered` have list of classes that will be applied ordering.

I fear that list would be too long and difficult to maintain. Support for ordering is normally documented in APIs that users interact with and or implement, not in something like `@Order` or `Ordered`.

@jhoeller, what are your thoughts on the matter?
