### ISSUE TITLE
Wait for complete disposal of Reactor Netty resources in ReactorResourceFactory

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#23631]
While chatting with @violetagg about #23594, we noticed that `ReactorResourceFactory`, when disposing of HTTP resources, is using the "void returning" variants of the APIs (for example, see `ConnectionProvider.dispose()` in reactor-netty).

Those variants are returning a `void` type but aren't synchronous and are not waiting for the operation to complete. Under the hood, they're calling the reactive version and subscribing to it, even sometimes in an elastic scheduler.

Spring Framework should in this case use `disposeLater().block();` to ensure that resources have been cleaned up before the method returns. This might explain part of the problem in #23594 if the resources aren't cleaned completely before the server shuts down.

**Comment by quaff** [comment]
after commit ca2b2f5 , webflux-http-kqueue-* is destroyed after context closed, but there is a thread named globalEventExecutor-1-1 not destroyed immediately, should wait for 1 second.

**Comment by quaff** [comment]
@violetagg the quiet time should be `1s` ? https://github.com/netty/netty/blob/c83904a12a603fe340477447d086674439ca8ac7/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L42

**Comment by violetagg** [comment]
@quaff the `quiet` period that I mentioned was for stopping the event loop. While this thread - yep it will be stopped when there is no task pending in the task queue for `1s`
https://github.com/netty/netty/blob/c83904a12a603fe340477447d086674439ca8ac7/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L34-L36
