### ISSUE TITLE
Failed to evaluate Jackson deserialization for type [[simple type, class void]]

### ISSUE THREAD

**Issue by jianhaifeng** [spring-projects/spring-framework#23654]
Warning log is as follows:
WARN o.s.h.c.json.MappingJackson2HttpMessageConverter - Failed to evaluate Jackson deserialization for type [[simple type, class void]]
com.fasterxml.jackson.databind.JsonMappingException: Internal error: can't find deserializer for void

**Comment by bclozel** [comment]
This is likely to be a Jackson usage problem rather than a bug in Spring Framework. Please reopen this issue if you believe that it's a bug in Spring Framework - you'll need a small project (a zip, a project that we can clone) that shows the problem.

Thanks!
