### ISSUE TITLE
Cannot build with javadoc errors for class ConcurrentReferenceHashMap

### ISSUE THREAD

**Issue by xiaoyiMia** [spring-projects/spring-framework#23652]
**Affects:** \<spring-framework-5.1.x>

---

Trying to run `./gradlew build` with spring-framework-5.1.x project. Got javadoc error:

com.sun.tools.javac.code.ClassFinder$BadClassFile: Erroed class file: E:\Programming\LearningResource\spring-framework-5.1.x\spring-core\build\libs\spring-core-5.1.10.BUILD-SNAPSHOT.jar(/org/springframework/util/ConcurrentReferenceHashMap$1.class)

ConcurrentReferenceHashMap$1(org.springframework.util.ConcurrentReferenceHashMap,org.springframework.util.ConcurrentReferenceHashMap.TaskOption[],boolean,java.lang.Object)

**Comment by sbrannen** [comment]
Please follow the instructions in [Build from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source).

If you still encounter errors after having done that, please post back here with more details.
