### ISSUE TITLE
In spring-mvc module doDispatch method, should we move getHandler method in front of checkMultipart method

### ISSUE THREAD

**Issue by liu316484231** [spring-projects/spring-framework#23667]
In our production environment, abusers try to request invalid urls, but the urls are not exist in our controller so we want to return a 404, but the attackers build invalid file-upload requests, spring call the checkMultipart first then the program encounter an exception in the checkMultipart method because of invalid file-upload requests and return a 500, so should we move getHandler method in front of checkMultipart method to avoid this.

**Comment by liu316484231** [comment]
I think we should make sure the request url is exist before we parse the request.  make less logic before the url is exist can decrease the risk of attackers and make code more efficient

**Comment by liu316484231** [comment]
hello, anyone have glance on this issue

**Comment by quaff** [comment]
@liu316484231 Why not send a PR?

**Comment by snicoll** [comment]
@quaff please don't suggest that. There is potential time wasted as the team hasn't triaged the issue and assigned a milestone to it.

**Comment by rstoyanchev** [comment]
Resolving the multiparts can add request params that in turn can be used for mapping, so we can't swap the order. For malicious requests, it would be a good idea to filter them out even earlier (Servlet Filter or perhaps proxy) or else even searching through all request mappings is using resources.

**Comment by liu316484231** [comment]
@rstoyanchev thanks for the advice
