### ISSUE TITLE
Field level permissions based on data classification

### ISSUE THREAD

**Issue by Tankske** [spring-projects/spring-framework#23666]
### Is your feature request related to a problem? Please describe.
I would like to classify entity properties according to a specific perspective and the manage access to them via permissions based on these classifications. 
EG. I would like to add a GDPR perspective classification (PII or non-PII). Then I would like to specify to certain users, roles or permissions if they are allowed to see PII and/or non-PII data. Another classification is confidentiality (public data, internal data, condifential and or strictly confidential) 

### Describe the solution you'd like
It would be great to have an annotation such as @classify that works in a similar was as @authorize. 

### Additional context
In my opinion, there are 3 levels of security being action (crud-operation), object level and field-property level. This last one is still missing. Views are an option, but it isn't fundamentalky about security, views are about representing behaviour and how you expose data. Not about if you are allowed to expose data. 

Looking forward on feedback about this!

**Comment by sbrannen** [comment]
This is the issue tracker for the core Spring Framework; whereas, your request is specific to Spring Security.

Please open an issue in the [Spring Security issue tracker](https://github.com/spring-projects/spring-security/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Or, @rwinch, can you transfer this issue?
