### ISSUE TITLE
WebMVC: Non-intuitive annotation names

### ISSUE THREAD

**Issue by nictas** [spring-projects/spring-framework#23664]
**Affects:** 5.1.2.RELEASE

---

I'm coming from a project that uses JAX-RS and is currently in the process of migrating to Spring WebMVC. One of the things that struck me as odd are the names of the annotations that can be used to extract things from requests. Namely, those are `@PathVariable`, `@MatrixVariable`, `@RequestParam`, `@RequestHeader`, `@CookieValue`, and `@RequestBody`. In JAX-RS there are annotations that serve the same purpose, but their names are a bit more consistent and therefore easier to remember (at least to me):

| Spring WebMVC  | JAX-RS |
| --- | --- |
| `@PathVariable` | `@PathParam` |
| `@MatrixVariable`  | `@MatrixParam`  |
| `@RequestParam` | `@QueryParam` |
| `@RequestHeader` | `@HeaderParam` |
| `@CookieValue` | `@CookieParam` |
| `@RequestBody` | `@BeanParam` ? |

Would it not be a good idea to get rid of the different suffixes/prefixes like variable/request/value and choose a more consistent naming?

**Comment by rstoyanchev** [comment]
Opinions on naming aside, as a framework with very wide use, we cannot rename the most widely used parts of our API even if we agreed with you. Not without causing lots of grief, and for every argument you make in favor there would be a justified uproar from existing users who would be broken and who may actually like the names as they are.
