### ISSUE TITLE
Set name for shutdown hook Thread

### ISSUE THREAD

**Issue by turbanoff** [spring-projects/spring-framework#23670]
Method `org.springframework.context.support.AbstractApplicationContext#registerShutdownHook` register shutdown hook Thread to close context on JVM shutdown,
https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L941
But it doesn't set name for this Thread. It's common good practice to set proper names for java thread to make diagnostic and troubleshooting easier.
I propose to set some name for shutdown hook Threads. For example `SpringContextShutdownHook-N` instead of current `Thread-N`.

This is how such threads look in Eclipse MAT
![image](https://user-images.githubusercontent.com/741251/65257232-96a38c00-db09-11e9-9c74-615335b9ebeb.png)

**Comment by sbrannen** [comment]
Great idea, @turbanoff.

I've implemented that in 3603e0c448643fbb8408737af30c60256f19a7f1.
