### ISSUE TITLE
RedeliveryDelay not working in ActiveMQ listeners when transactionManager is present

### ISSUE THREAD

**Issue by ceremo** [spring-projects/spring-framework#23688]
[demoJms.zip](https://github.com/spring-projects/spring-framework/files/3646869/demoJms.zip)

Hi,

I've created a demo with a spring boot application that has defined a listener to activemq broker, I can detect that the redeliveryDelay is not working when the transactionManager is available in the DefaultJmsListenerContainerFactory. I can reproduce it with atomikos and bitronix.

I've attached the project, so you can reproduce the problem.

Thxs.

**Comment by snicoll** [comment]
Sorry it took so long to look at this. Your `ConnectionFactory` is not XA capable so it's not enlisted as a resource when the transaction rollbacks. I can see that the session is invalidated, which explain why the redelivery is discarded.

You may find [this SO question](https://stackoverflow.com/questions/25792942/no-redelivery-on-rollback-of-xa-transaction-activemq-spring-integration-spri) to provide more context.
