### ISSUE TITLE
parameterized tests based on spring profiles

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-framework#23680]
I'm testing various FHIR endpoint functionality, these tests are functionally identical except an `@ActiveProfiles` I'd like to apply. Here's what I imagine writing, basically all tests in the test would be run for each parameterized profile, e.g. foo and bar, regular active profiles e.g. baz, would still be always applied.

```
@ParameterizedTestActiveProfiles("foo", "bar")
@ActiveProfiles("baz")
```

**Comment by sbrannen** [comment]
Duplicate of #13977 and #20849

See also: https://github.com/junit-team/junit5/issues/878
