### ISSUE TITLE
@Cachable serializes Map<Integer, String> as Map<String,String>

### ISSUE THREAD

**Issue by acaligiuri** [spring-projects/spring-framework#23683]
**Affects:** 5.0.9.RELEASE
---
When using @Cachable on a method that returns a Map<String, Object>, the map is serialised as a JSON object where all fields are Strings.
As a consequence, when deserialised, the Map will effectively be a Map<String, Object> and any subsequent get from it will likely fail (Integers never being equal to their String representation)

e.g. (code has been simplified and anonymised to adhere to company policies)
```
@Override
@Cacheable(cacheNames = "clientMap")
public Map<String, Object> getMap() {
    Object data = apiClient.getData();
    if (data == null) {
        return Collections.emptyMap();
    }
    return data;
}
```
the above code would produce a json serialisation like this:
```json
{
  "1": {"value": "value"}
  "2": {"value": "value"}
  "3": {"value": "value"}
}
```
while the expected serialisation is :
```json
{
  1: {"value": "value"}
  2: {"value": "value"}
  3: {"value": "value"}
}
```
As the first serialization causes the map to be deserialised in a Map<String, Object> leaving the programmer totally unaware since generics are only available at compile time.

This only seem to happen with maps. Collections are serialized just fine so I'm wandering if this has anything to do with json property names?
But apparently you can change the ObjectMapper and force it to treat any map as a Map<Integer, Object> so it does seem to be a missing feature. 
BTW using a custom Object mapper would apply to any map in the codebase and hence it's not a feasible solutions when you have Maps of different types that you want to serialise and cache.

**Comment by snicoll** [comment]
There's nothing to report here I am afraid. The cache abstraction doesn't deal with the actual serialization of keys and values. Whatever cache implementation you are using should be configured accordingly: if you believe you've found a bug in the cache implementation you are using, feel free to open an issue there.
