### ISSUE TITLE
Update documentation for importing projects into Eclipse

### ISSUE THREAD

**Issue by rakotkar** [spring-projects/spring-framework#23706]
I did follow the steps mentioned in https://github.com/spring-projects/spring-framework/wiki/Build-from-Source, but still getting errors in the project .Do we need to install kotlin support plugin for eclipse ? Also the version against which the version of STS is given doesnt seem to be available now ?

Kindly update the steps

**Comment by sbrannen** [comment]
> Do we need to install kotlin support plugin for eclipse? 

Yes

> Also the version against which the version of STS is given doesnt seem to be available now ?

Please use STS 4.3 instead.

> Kindly update the steps

OK. I plan to do that in the coming weeks.

**Comment by sbrannen** [comment]
@rakotkar, I just overhauled the documentation for importing projects into Eclipse.

Please try again with the [updated instructions](https://github.com/spring-projects/spring-framework/blob/master/import-into-eclipse.md), and let me know if that helps.
