### ISSUE TITLE
Extra empty line a["\n"] messages from ActiveMQ STOMP broker

### ISSUE THREAD

**Issue by seenimurugan** [spring-projects/spring-framework#23713]
**version:**:
```
spring-boot-starter-parent - version: 2.1.8.RELEASE
spring-boot-starter-websocket - as above
```

**issue:**
`Client receives extra/un-necessary message(a["\n"] or empty line) for each message sent  from external broker via brokerrelay
`

**Comment by rstoyanchev** [comment]
Are you sure about this conclusion? `AbstractMessageChannel` is a very generic component that [skips the send](https://github.com/spring-projects/spring-framework/blob/47a24ac3787414b4ed6652cba53755ba752136eb/spring-messaging/src/main/java/org/springframework/messaging/support/AbstractMessageChannel.java#L132-L135) if an interceptor returns null from `preSend` and this is not in any way related the STOMP broker is in use. The `a["\n"]` messages that you're seeing with the external broker are probably heartbeat messages.

**Comment by seenimurugan** [comment]
@rstoyanchev I double checked and the issue is with the message itself not with the preSend method i guess. If I send a simple string as payload in the convertAndSend method then it does not produce this noise. But if I use any object as string(using Jackson or gson converter) as payload then it sends the additional line. Please find the below link to test this issue. 
[Git hub url](https://github.com/seenimurugan/spring-websocket)

**Comment by seenimurugan** [comment]
![Screenshot 2019-09-26 at 11 43 45](https://user-images.githubusercontent.com/7019139/65682483-f55d8e00-e052-11e9-947f-8a69fba6c71b.png)

**Comment by rstoyanchev** [comment]
Thanks for providing the sample.

ActiveMQ appears to be sending extra new lines at the end of STOMP frames, i.e. after the terminating `\0` byte (NULL octet). I don't know what the logic of when it does that but it is allowed by the spec, from [section 2.1](https://stomp.github.io/stomp-specification-1.2.html#STOMP_Frames):

```
The NULL octet can be optionally followed by multiple EOLs.
```

The current logic does skip empty new lines at the start of a frame but if they arrive in the same chunk as the message, it ends up (incorrectly) interpreting that as a heartbeat.
