### ISSUE TITLE
Consider defaulting to UTF-8 in RestClientResponseException

### ISSUE THREAD

**Issue by ask4gilles** [spring-projects/spring-framework#23738]
Spring version: 5.2.0.RELEASE

Related to https://github.com/spring-projects/spring-framework/issues/22954 and the ```UTF-8``` charset removal, the ```RestClientResponseException``` now defaults to ```ISO_8859_1``` here https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-web/src/main/java/org/springframework/web/client/RestClientResponseException.java#L105
instead of ```UTF-8``` previously.

To mitigate this issue, we are now forced to create a custom ```ResponseErrorHandler``` and forcing ```UTF-8```

**Comment by rstoyanchev** [comment]
This issue is superseded by #23764.
