### ISSUE TITLE
bug  WebClient Header cannot upadte in org.springframework.http.codec.HttpMessageWriter

### ISSUE THREAD

**Issue by kosmosimonyi** [spring-projects/spring-framework#23734]
bug  WebClient Header cannot upadte in org.springframework.http.codec.HttpMessageWriter.
org.springframework.web.reactive.function.client.DefaultClientRequestBuilder.BodyInserterRequest 's HttpHeaders cannot readOnly, developer need add HttpHeader in org.springframework.http.codec.HttpMessageWriter,eg: add a HttpHeader xxx-bodyOfSignature

**Comment by kosmosimonyi** [comment]
eg: add a HttpHeader xxx-signatureOfBody, do this for security in tow company application.

**Comment by kosmosimonyi** [comment]
- [ ] `public BodyInserterRequest(HttpMethod method, URI url, HttpHeaders headers,
				MultiValueMap<String, String> cookies, BodyInserter<?, ? super ClientHttpRequest> body,
				Map<String, Object> attributes) {

			this.method = method;
			this.url = url;
			// cannot readOnly, developer need add HttpHeader in org.springframework.http.codec.HttpMessageWriter,eg: add a HttpHeader xxx-bodyOfSignature
			this.headers = new HttpHeaders(headers);
			this.cookies = new LinkedMultiValueMap<>(cookies);
			this.body = body;
			this.attributes = new HashMap<>(attributes);

			Object id = attributes.computeIfAbsent(LOG_ID_ATTRIBUTE, name -> ObjectUtils.getIdentityHexString(this));
			this.logPrefix = "[" + id + "] ";
		}`

**Comment by sbrannen** [comment]
Superseded by #23733
