### ISSUE TITLE
Handling of ResponseStatusException to also include setting of response headers

### ISSUE THREAD

**Issue by Zabelinski-Andrey** [spring-projects/spring-framework#23741]
Affects: 5.1.10
Spring RestController offers a nice function, one could filter requests by methods. E.g.:
```java
@RequestMapping(value = "/some-pattern", method = {RequestMethod.GET, RequestMethod.HEAD})
public Mono<Void> handler(...)
```
If a request matches the path pattern but does not match the method pattern spring-web automatically generates a response `405 Method Not Allowed` which is perfectly fine.

But RFC 7231 Explicitly requires servers to include the Allow header (https://tools.ietf.org/html/rfc7231#page-59):
`The origin server MUST generate an Allow header field in a 405 response containing a list of the target resource's currently supported methods.`

It request method filters must automatically insert an Allow header with a list of allowed methods into a response.

**Comment by rstoyanchev** [comment]
It should be doing that:
https://github.com/spring-projects/spring-framework/blob/b7f819c9e10fe0c30d599e6cb0f396c65bb3272a/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/support/DefaultHandlerExceptionResolver.java#L259

**Comment by Zabelinski-Andrey** [comment]
Thank you for the analysis, rstoyanchev.
I'm sorry I didn't show the vital detail. I use spring-webflux.
To be precise:
Dependencies:
  - org.springframework:spring-webflux:5.1.10
  - io.projectreactor:reactor-core:3.2.12.RELEASE

Project files:
  - class WebFluxConfiguration annotated with:
    - @org.springframework.context.annotation.Configuration
    - @org.springframework.web.reactive.config.EnableWebFlux

I create reactor.netty.http.server.HttpServer manually:
```
        HttpHandler handler = WebHttpHandlerBuilder.applicationContext(applicationContext).build();
        DisposableServer server = reactor.netty.http.server.HttpServer.create()
                .host(host).port(port)
                .tcpConfiguration(tcpServer -> tcpServer.bootstrap(
                        serverBootstrap -> serverBootstrap.group(...).channel(NioServerSocketChannel.class)))
                .handle(new ReactorHttpHandlerAdapter(handler))
                .bind().block();
```
And I also have some REST controllers like:
```
@org.springframework.web.bind.annotation.RestController
class MyRestController {
    @RequestMapping(value = "/some-pattern", method = {RequestMethod.GET, RequestMethod.HEAD})
    public Mono<Void> handler(ServerWebExchange exchange) {
        return Mono.just(exchange).subscribeOn(scheduler).flatMap(exch-> handle(exch));
    }
}
```
And when I request `DELETE https://addr:port/some-pattern` I get a response without Allow header:
```
HTTP/1.1 405 Method Not Allowed
content-length: 0
```

**Comment by antimpatel** [comment]
@rstoyanchev can I pick this up? If no one is working on it. seems good for a newbie.

**Comment by rstoyanchev** [comment]
@antimpatel sure. Probably something in `ResponseStatusExceptionHandler`?
