### ISSUE TITLE
Avoid default Accept header from HttpUrlConnection in RestTemplate with put and delete

### ISSUE THREAD

**Issue by nytro77** [spring-projects/spring-framework#23740]
**Affects:** 5.1.10

It seems that the RestTemplate does not handle exceptions thrown by DELETE the same way as it does for GET and POST.
`HttpStatusCodeException.getResponseBodyAsString()` returns whitelabel error page as HTML instead of the expected JSON.

**Example from exceptional DELETE:**
`<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Oct 01 15:38:04 CEST 2019</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>I am delete error</div></body></html>`

**Example from exceptional GET:**
`{"timestamp":"2019-10-01T13:38:04.682+0000","status":500,"error":"Internal Server Error","message":"I am get error","path":"/test"}`

Reproduced in [this simple Spring Boot project](https://github.com/nytro77/resttemplate-delete-errorhandling)

**Comment by nytro77** [comment]
Hmmm... can this have something to do with it?
Found in `SimpleBufferingClientHttpRequest.executeInternal` method:

> // JDK <1.8 doesn't support getOutputStream with HTTP DELETE
> if (getMethod() == HttpMethod.DELETE && bufferedOutput.length == 0) {
> 		this.connection.setDoOutput(false);
> }

Spring 5.1 is Java 8 and later, so this code should be deleted anyways i guess?

**Comment by rstoyanchev** [comment]
@nytro77 this sounds more like server-side behavior. `getResponseBodyAsString()` is a very simple convenience method to turn body from `byte[]` to `String`. It has no impact on what the format of the response is.

**Comment by nytro77** [comment]
Ok, so i guess the error is in Spring Boot then? Or somewhere else in the Spring code?

I have configured nothing at all in the [Spring Boot project](https://github.com/nytro77/resttemplate-delete-errorhandling) that reproduces the problem. Just a simple `@RestController` like this:

```
@RestController
public class MyRestController {

	@DeleteMapping("/test")
	public void testDeleteError() {
		throw new RuntimeException("I am delete error");
	}

	@GetMapping("/test")
	public void testGetError() {
		throw new RuntimeException("I am get error");
	}
}
```

I tried with boot 2.2.0.RC1 and the result is the same.

**Comment by nytro77** [comment]
I booted [the application](https://github.com/nytro77/resttemplate-delete-errorhandling) and called  GET and DELETE for http://localhost:8080/test using curl.
They both return nice JSON.

`curl -i -X GET http://localhost:8008/test` 
produces 
`{"timestamp":"2019-10-16T15:08:24.979+0000","status":500,"error":"Internal Server Error","message":"I am get error","path":"/test"}`

`curl -i -X DELETE http://localhost:8008/test` 
produces 
`{"timestamp":"2019-10-16T15:08:35.066+0000","status":500,"error":"Internal Server Error","message":"I am delete error","path":"/test"}`

So i guess that there must be something strange with the RestTemplate after all?

**Comment by rstoyanchev** [comment]
It looks like this is due to `sun.net.www.protocol.http.HttpURLConnection` [setting](https://github.com/JetBrains/jdk8u_jdk/blob/37551819bb63ac3bc4c80bc611618d5e5a2c223a/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L601) the Accept header to `"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2"` by default if not set. 

For `delete` and `put` methods in the `RestTemplate` which return `void` we should probably set the `Accept` header to `*/*` to allow for any error response.
