### ISSUE TITLE
some methods can be added in StringUtils

### ISSUE THREAD

**Issue by rsbeoriginal** [spring-projects/spring-framework#23749]
---

To make string to uppercase and lowercase.

**Comment by sbrannen** [comment]
Java has had built-in support for that since Java 1.0.

Please see `java.lang.String.toUpperCase()` and `java.lang.String.toLowerCase()`.

**Comment by rsbeoriginal** [comment]
yes java has it, but calling the method on null object will return Null Pointer. So to prevent that is it possible to have a wrapper function over it ?

**Comment by sbrannen** [comment]
As stated in the class-level Javadoc, `StringUtils` is...

> Mainly for internal use within the framework; consider Apache's Commons Lang for a more comprehensive suite of String utilities.

We typically do not introduce new utility methods unless there is a concrete need for them within the framework itself.
