### ISSUE TITLE
Add option to log HTTP method to AbstractRequestLoggingFilter 

### ISSUE THREAD

**Issue by mjustin** [spring-projects/spring-framework#23759]
This is the same as #18818, except that it concerns the HTTP method instead of the headers.

`AbstractRequestLoggingFilter` has options to include various parts of the request, including the URL, request headers, and the payload. It would be nice if it also had a standard option to log the HTTP method.  I imagine it could be something like `AbstractRequestLoggingFilter.setIncludeHttpMethod()`.

The rationale here is that sometimes it is helpful or necessary to know what the request headers were in order to troubleshoot an issue.  I recently came across such an issue where the client was troubleshooting an issue where it eventually turned out that they were making the request with the wrong HTTP method.  It was still technically a valid request returning `200 OK`, so they didn't initially notice that call was incorrect.

A workaround is to override the `createMessage` method to append the header information:

```
@Bean
public Filter logFilter() {
    CommonsRequestLoggingFilter filter = new CommonsRequestLoggingFilter() {
        @Override
        protected String createMessage(HttpServletRequest request, String prefix, String suffix) {
            return super.createMessage(request, prefix, ";method=" + request.getMethod() + suffix);
        }
    };
    return filter;
}
```

Note though that since the name of the logger that is used is based on the name of the class, the logging configuration has to be set to log the new subclass to DEBUG, not e.g. `CommonsRequestLoggingFilter`.

**Comment by rstoyanchev** [comment]
This was done recently in #23567.

**Comment by mjustin** [comment]
Looks like I missed it in my search since it was created as a PR but never as an issue.
