### ISSUE TITLE
Pre-flight requests return with error code: 401

### ISSUE THREAD

**Issue by rolaca11** [spring-projects/spring-framework#23752]
**Affects:** 5.2.0.RC2

---
When sending a POST request to the autoconfigured `/oauth/token` endpoint, most browsers send a preflight request to determine if the actual request has any chance of succeeding.

I have configured an application with [spring-secutiry-oauth2-autoconfigure](https://github.com/spring-projects/spring-security-oauth2-boot), [spring-security-oauth](https://github.com/spring-projects/spring-security-oauth) and the brand new [spring-security](https://github.com/spring-projects/spring-security).

I tried implementing the new implementation of OAuth2 authentication with JWTs, but that doesn't support an authorization server, which I need.

This works fine from _Postman_, if I send a POST request to the right endpoint, I get an access token. However, things get wrong, when I try the same from a browser, because of the above mentioned pre-flight request.

When the browser sends this request, the `/oauth/token` endpoint realises that there are no authentication data sent alongside the request, so it throws an error, Through some error handling path, the request gets to the cors processor, which realises that the original request was in fact a pre-flight one and sets the headers of the response accordingly, except for the status code, which remains 401. The browser, seeing the status code aborts the request with a `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/oauth/token. (Reason: CORS preflight channel did not succeed).` message.

I tried, from the debugger, set the status code to 200 manually and in this case, the browser sees it as a green light, to send the actual request, which in turn gives the access token in question.

I'm planning on creating a solution for this problem myself, since it's an easy one. This is the first problem that I'm trying to help solve for the spring framework and I'm really excited to start contributing.

Curious, if I'm getting something wrong. The problem originally occured with the latest stable release of spring boot, the _2.1.7.RELEASE_ version, that's why I'm trying out the milestone version.

**Comment by sbrannen** [comment]
Superseded by #23754
