### ISSUE TITLE
Add @EnableRSocket Configuration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#23751]
The current recommendation to add a reactive messaging `HandlerMethodArgumentResolver` is to [add a preProcess hook](https://github.com/spring-projects/spring-boot/issues/18356#issuecomment-537604973). 

Spring MVC provides `WebMvcConfigurer.addArgumentResolvers` which allows configuring `HandlerMethodArgumentResolver`. WebFlux provides `WebFluxConfigurer.configureArgumentResolvers` which allows configuring `HandlerMethodArgumentResolver`. These were provided, presumably, because there were enough people customizing them that Framework decided to provide a first class hook to modify it. I believe the same support should be added to reactive messaging.

**Comment by rstoyanchev** [comment]
It wouldn't be a one-off configuration hook. I suppose what you're suggesting is an `@EnableRSocket` setup along with `RSocketConfigurer` callbacks, as in WebMvc and WebFlux?

**Comment by rwinch** [comment]
> I suppose what you're suggesting is an @EnableRSocket setup along with RSocketConfigurer callbacks, as in WebMvc and WebFlux?

Yes that is what I was thinking.

**Comment by joshlong** [comment]
I would love to see this land, if possible.

**Comment by jhoeller** [comment]
@rstoyanchev If something along these lines is in consideration, we could do it for 5.3 RC1 still...

**Comment by rstoyanchev** [comment]
The config would be `RSocketMessageHandler` and `RSocketStrategies` beans along with `RSocketConfigurer` to provide argument resolvers, return value handlers, `Validator`, and `ConversionService`. The remaining `RSocketMessageHandler` properties can be set via `RSocketStrategies`.

On the Boot side there are currently customizers for `RSocketStrategies` and `RSocketMessageHandler` which covers everything that is needed so what extra value does `RSocketConfigurer` add? 

For `Encoder`, `Decoder`, `RouteMatcher`, and `MetadataExtractor` (the most common ones to customize I believe) the `RSocketStrategies` customizer is perfectly adequate. For what remains, argument resolvers, return value handlers, `Validator`, and `ConversionService` having an `RSocketConfigurer` would be slightly nicer than setting the same on an `RSocketMessageHandler` through a customizer but also with the added ambiguity of having multiple ways to do the same.

More broadly my concern is that RSocket has a wider range of possible setup scenarios. I could use `RSocketMessageHandler` for client side handling of messages from a server. This means potentially more than one, or even more than two `RSocketMessageHandler` instances in one application. I could create those programmatically and manual registration of handlers, or I could declare them in Spring configuration customized with custom handler predicates to target different subsets of controllers.

I feel we'd be adding a layer around what amounts to trivial configuration but also make things more opaque making harder to provide flexibility or imagine possibilities. So unless I'm missing some benefit I'd rather keep the current situation where it's easy to put things together manually without Boot and where pretty much nothing is missing in Boot.

**Comment by rstoyanchev** [comment]
**Team Decision:** We'll close this for now with the above as context.
