### ISSUE TITLE
Match route paths ignoring case sensitivity when using yml configuration files

### ISSUE THREAD

**Issue by xBentu** [spring-projects/spring-framework#23750]
**Affects:** \<Spring Framework version>

---

**Comment by xBentu** [comment]
I am trying to have my yml routing to match a path that is case insensitive.

e.g.

spring:
   cloud:
      gateway:
         routes:
            - id: somewhere
              uri: http://localhost:8000
              predicates:
                 - Path=/get/user

I want /get/user to be case insensitive.  So when I go to the browser url localhost:8888/gEt/UsEr it would match the Path /get/user and route to localhost:8000.

**Comment by bclozel** [comment]
I think you should open this issue against the Spring Cloud Gateway project - see https://github.com/spring-cloud/spring-cloud-gateway/issues

This issue tracker is for Spring Framework issues only.
Thanks!
