### ISSUE TITLE
How to extend distributed lock in CacheAspectSupport Class

### ISSUE THREAD

**Issue by yuanchangjin** [spring-projects/spring-framework#23771]
---

spring cache  is very usefull and convenient. for example, It's easy to use @Cacheable, @CacheEvict,@CachePut . but it has concurrency issues.  if  in CacheAspectSupport  class, method `private Object execute(final CacheOperationInvoker invoker, Method method, CacheOperationContexts contexts) ` , using lock can resove it, but now can not extend lock
in CacheAspectSupport  class.  can i extend lock in CacheAspectSupport  class source ?
and push it?

**Comment by snicoll** [comment]
@yuanchangjin I am not sure I understand what you mean by concurrency issues. If you have some code you'd like to share with us, feel free to open a PR and we can take it from there. If you have an app that demonstrates a concurrency issue, please share a small sample we can run and we can reopen this issue.
