### ISSUE TITLE
Rollback transactions in case if Exception was thrown

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-framework#23789]
At the moment a transaction is rollback only if it was thrown a `RuntimeException`.

In Kotlin there is no checked exceptions, so compiler to do not force to check when is was thrown an `Exception`.
When some library from Java throw an `Exception`, in Kotlin methods with `@Transactional` annotation do not rollback.

**Comment by raderio** [comment]
The quick-fix is to use `@Transactional(rollbackFor = [Exception::class])` instead of `@Transactional`.
But it will be better to handle this by default in Spring.

**Comment by snicoll** [comment]
Duplicate of #23473
