### ISSUE TITLE
Image serialization to JSON recurses infinitely

### ISSUE THREAD

**Issue by boiert** [spring-projects/spring-framework#23783]
**Affects:**  Spring Boot (v2.1.6.RELEASE)

I made a tiny test case: https://github.com/boiert/imgbug/
I'm JSONifying an Image object, but the Serializer gets stuck in infinite recursion on the image dimensions?
I'm unsure where to report this, so I chose here..

**Comment by jnizet** [comment]
The BufferedImage class hasn't been designed to beserialized to JSON by Jackson. You just shouldn't try to return a BufferedImage from a RestController method. And you should most probably not return JSON from an endpoint returning an image, either.

Design your api. Think about what your HTTP API is supposed to return in order for a client of this API to be able to deal with the result. Then write the code accordingly.

An HTTP API returning an image typically returns the encoded image bytes (in JPEG, PNG, or some othe standard format), and sets the appropriate response content type (i.e. image/jpeg or image/png for example)

**Comment by boiert** [comment]
I agree that this isn't a proper API, this was purely a demonstration.
Thanks for clarifying Jacksons design, I wish it was a bit more graceful about it though.
