### ISSUE TITLE
How to override the SameSite attribute of JSESSIONID cookie

### ISSUE THREAD

**Issue by AaronZhengkk** [spring-projects/spring-framework#23785]
@BoomManPro You should be able to [add a cookie initializer](https://github.com/vpavic/spring-framework/blob/8d3162352211c7edf05518c03236dae64223388e/spring-web/src/main/java/org/springframework/web/server/session/CookieWebSessionIdResolver.java#L91) which can override the default value. If you have additional questions problems, you might want to create a ticket in JIRA https://jira.spring.io/browse/SPR

_Originally posted by @rwinch in https://github.com/spring-projects/spring-framework/pull/1889#issuecomment-442980715_

**Comment by AaronZhengkk** [comment]
@rwinch Does cookie initializer no longer exist in version 5.1.8?How do I override the default values in version 5.1.8?

**Comment by rstoyanchev** [comment]
@AaronZhengkk the link provided Rob is still valid. The method has not gone away and is still there. I don't understand your question, what doesn't exist in 5.1.8?

**Comment by rstoyanchev** [comment]
Note also that there was an issue with actually having sameSite propagate through to the client, see #23693. It's possible that you were running into that.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
