### ISSUE TITLE
Autowiring performance degradation due to 5.2's MethodParameter.getParameterType() implementation

### ISSUE THREAD

**Issue by e-hubert** [spring-projects/spring-framework#23792]
Our applications makes considerable use of programmatic autowiring of beans via org.springframework.beans.factory.config.AutowireCapableBeanFactory#autowire.

Therefore we have a couple of performance tests, which directly and indirectly measure the throughput of the underlying Spring implementation.
All those tests degraded by about 20 to 25 percent, after only updating the Spring dependencies from version 5.1.9 to version 5.2.0.

We did a bit of work to pinpoint the changes in Spring, which resulted in this performance drop and thought it would be a good idea to report it here so you can verify, whether you like to accept this or have an idea how to achieve both, improved code robustness while maintaining performance.

The root of the actual performance degradation seems to originate from changes to org.springframework.core.MethodParameter#getParameterType to use org.springframework.core.ResolvableType (in our case itself used from org.springframework.beans.factory.support.ConstructorResolver#resolveAutowiredArgument).

The relevant issue motivating this change seems to be https://github.com/spring-projects/spring-framework/issues/23385

I quickly verified that it is enough to use 5.1.9 as base and only change the above mentioned two core classes, to observe the performance drop. I have not yet checked the Spring project for own performance tests.

**Comment by lgxbslgx** [comment]
I submit a PR to improve the performance of the method MethodParameter.getParameterType. Hope it could help.

**Comment by quaff** [comment]
I have the same issue. my web application built with both struts2 and spring mvc, after upgrade to spring 5.2.0, throughput of struts2 decrease to about 80%, but throughput of spring mvc is increased. struts2 action is autowired by `AutowireCapableBeanFactory::createBean(clazz, AUTOWIRE_BY_NAME, false)` .

BTW: @lgxbslgx's PR not helps much.

**Comment by quaff** [comment]
@e-hubert can you provide a simple project and try the PR https://github.com/spring-projects/spring-framework/pull/23811 ?

**Comment by jhoeller** [comment]
According to my local benchmarks, it seems sufficient to restore a `containingClass != null` check as we effectively had it in the 5.1.x code path. Refining it with a check for `containingClass != declaringClass` does not hurt but seems like an optimization beyond 5.1.x already, nevertheless worth it. I'll double-check the effect and will proceed with that change for inclusion in 5.2.1.

**Comment by jhoeller** [comment]
A variant of this is in master now for inclusion in the upcoming 5.2.1 build snapshot. Please do try it tomorrow if you can since it's your scenario that actually matters, not my local little benchmark ;-)

**Comment by quaff** [comment]
I confirm commit https://github.com/spring-projects/spring-framework/commit/dc59e50561eeaedbc6f7a50d8703d627be2c6847 works.

**Comment by e-hubert** [comment]
I can confirm the issue to be fixed as well. I tested with spring-core-5.2.1.BUILD-20191030.000554-48.jar containing this change. Thanks again!
