### ISSUE TITLE
Use getAvailableExtensionNames from JettyWebServerFactory 

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#23799]
Backport of gh-23565

**Comment by izeye** [comment]
This seems to be a duplicate of #23565.

**Comment by rstoyanchev** [comment]
Ah yes a bit of a mess it became. Thanks for pointing this out.

What happened is #23565 was created first for 5.2.1 while this here was meant to be the backport for 5.1.11 until I edited it manually (mistakenly) leading to the creation of #23804 as duplicate backport. I've corrected this.
