### ISSUE TITLE
Use getAvailableExtensionNames from JettyWebServerFactory 

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#23804]
Backport of gh-23799

**Comment by spring-issuemaster** [comment]
Fixed via 7f8966774e2096b9ddd55ee931643b48bfc30218

**Comment by rstoyanchev** [comment]
This is a backport that is a duplicate of #23799, which was edited incorrectly leading to the creation of this backport by the bot.
