### ISSUE TITLE
Optimize Connection.setReadOnly(false) in DataSourceUtils.resetConnectionAfterTransaction(…)

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#23801]
Backport of gh-23747

**Comment by jhoeller** [comment]
This turns to be somewhat more involved than expected, so I'll keep it as 5.2.1 only.

Several of the pieces involved might be used outside of our standard JDBC/Hibernate context, possibly leading to follow-up alignments for consistency within the 5.2.x line.
