### ISSUE TITLE
Allow processing of binary content via input streams with Websocket

### ISSUE THREAD

**Issue by nictas** [spring-projects/spring-framework#23818]
**Affects:** 5.1.2.RELEASE

---

Hi,

I want to use web sockets for upload of large files. The files need to be stored in a database for later processing. The problem I have is that `spring-websocket`'s `BinaryWebSocketHandler`s allow me to only process binary content as a byte array:

- If I keep the partial messages support disabled, this would mean that the entire file would be stored in-memory, which I want to avoid.

- If I enable the partial messages support, this means that I would have to collect the parts into a temporary file before persisting it in the database. I don't want this either.

It would be ideal if I could get access to the underlying `InputStream` and just forward that to my database driver, so it can stream the file's content directly to the database. This seems like it would be do-able, since as far as I saw, you use Java's WebSocket API under the hood and it provides https://docs.oracle.com/javaee/7/api/javax/websocket/MessageHandler.Whole.html. According to the documentation one of the supported types is `InputStream`.

Do you think it would be a good idea to allow us to have handlers for such `InputStream`s or would that be a bad idea somehow?

PS: Maybe it's somehow already possible to do this, but I couldn't find a way. I also asked a question in StackOverflow, but I didn't get an answer besides the partial messages feature:
https://stackoverflow.com/questions/58395489/how-to-process-binary-messages-as-input-streams/58395721
I was also pointed to this question:
https://stackoverflow.com/questions/37896551/spring-stomp-over-websocket-stream-large-files
Where some people also wanted to use `InputStream`s instead of byte arrays.

**Comment by rstoyanchev** [comment]
> According to the documentation one of the supported types is InputStream.

That is an `InputStream`  representing the content of the current message, i.e. a simple `ByteArrayInputStream` wrapper. It is not anything a stream of the content of all messages. You can see for example what [Tomcat does](https://github.com/apache/tomcat/blob/339f910ddd677cd2b48d86b59f5c7ad4d0ac4685/java/org/apache/tomcat/websocket/pojo/PojoMessageHandlerWholeBinary.java#L98-L100) for this.

What isn't clear is whether you want to upload one large file or upload many files in which case there would have to be some way to delineate where one file ends and the next one begins, which the server can't know that. Assuming that you have something in mind for that, consider using something `java.io.PipedOutputStream` that you can keep writing to, and that also gives you an `InputStream` to be read from the other end.
