### ISSUE TITLE
Why escaped comma is the delimiter for `@RequestParam List<String>`?

### ISSUE THREAD

**Issue by akrikheli** [spring-projects/spring-framework#23820]
**Affects:** \< Spring Boot 2.1.2.RELEASE>

---

I have a simple rest controller with the method the get requests mapped on:
```java
@GetMapping("/cis_list")
public Map<String, CisFrontendDto> cisList(@RequestParam(value = "cis") List<String> cis) {
        log.debug("#cisList: started with cisIds = {}", cis);
        return cisService.findByIds(cis);
    }
```

I try to pass string **hello, world!** as a single element of _List<String> cis_ parameter:
>curl -X GET "http://127.0.0.1:8095/api/v3/facade/cis/cis_list?cis=hello%2C%20world!" -H "accept: */*" 

I have expected the list contains only one string but аs it turned the list contains two elements although the comma has been escaped in source request.

![image](https://user-images.githubusercontent.com/23580186/66923800-27e71f00-f032-11e9-8539-e7642f9527df.png)

In this way there's not a difference between requests:
>curl -X GET "http://127.0.0.1:8095/api/v3/facade/cis/cis_list?cis=hello%2C%20world!" -H "accept: */*" 

and

>curl -X GET "http://127.0.0.1:8095/api/v3/facade/cis/cis_list?cis=hello,%20world!" -H "accept: */*" 

So, I'm not able to map parameters of HTTP GET requests to Java List if they contain escaped commas.

**Comment by rstoyanchev** [comment]
This is due to the `StringToCollectionConverter` which gets involved if there is 1 request parameter value and we have to convert from `String` to `List<String>`. When there are multiple values the `ArrayToCollectionConverter` is used. so the behavior is specific to single values. You can remove the `String` to `Collection` conversion if that gets in the way through the [formatters callback](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-conversion) in the WebMvcConfig.

**Comment by nschrader** [comment]
Guys, let's be honest, it's just broken. The parameter is sent with a percent escaped `,` (%2C) and according to RFC 3986, parameters need to be separated by an unescaped `,`. Things that belong together get ripped apart, although we have the information that they shouldn't.

(And the RFC even explicitly states that commas are allowed as parameter values as long as they are percent escaped.)

**Comment by artemptushkin** [comment]
@rstoyanchev I'd propose to consider a fix here indeed. Maybe somehow to customise this `ArrayToCollectionConverter`

I detail.
Having Java code like this:
```java
@RequestParam("sort") List<String[]> sortQueries
```

1. N queries: `?sort=status&sort=date,desc`. 
**Actual:** <img width="331" alt="image" src="https://user-images.githubusercontent.com/22632802/154070748-8e26217e-6743-4329-8783-caa9efb2955b.png">
**As expected**
2. 1 query: `?sort=date,desc`.
**Actual**: <img width="315" alt="image" src="https://user-images.githubusercontent.com/22632802/154070855-02dbc5e9-520e-4c1d-96fc-2c41467d9c4f.png">
**Expected** : array list contains 1 element with the array of 2 elements: `["date", "desc"]` as in the case of N queries

**Workaround**:
```java
@RequestParam("sort") List<List<String>> sortQueries
```

**Comment by helderhernandez** [comment]
I managed to solve the problem by applying the following:
- [How to prevent parameter binding from interpreting commas in Spring 3.0.5?](https://stackoverflow.com/questions/4998748/how-to-prevent-parameter-binding-from-interpreting-commas-in-spring-3-0-5)
- [How to prevent Spring MVC from interpreting commas when converting to a Collection in Spring Boot?](https://stackoverflow.com/questions/42120588/how-to-prevent-spring-mvc-from-interpreting-commas-when-converting-to-a-collecti)

The trick is done by the following lines of code

```java
@InitBinder
public void initBinder(WebDataBinder binder) {
  binder.registerCustomEditor(String[].class, new StringArrayPropertyEditor(null));
}
```

My classes were as follows:

## Clase Search (works as a wrapper)
```java
public class Search {
	private String[] search = new String[] {};

	public Search() {
		super();
	}

	public Search(String[] search) {
		super();
		this.search = search;
	}

	public String[] getSearch() {
		return search;
	}

	public void setSearch(String[] search) {
		this.search = search;
	}

	public List<String> toList() {
		return Arrays.asList(this.search);
	}

	@Override
	public String toString() {
		return "Search [search=" + Arrays.toString(search) + "]";
	}
}
```

## Endpoint
```java
@InitBinder
public void initBinder(WebDataBinder binder) {
  binder.registerCustomEditor(String[].class, new StringArrayPropertyEditor(null));
}

@GetMapping("/search")
@ResponseStatus(HttpStatus.OK)
@ApiOperation(value = "Search providers")
//@formatter:off
@ApiImplicitParams({
	@ApiImplicitParam(
	    name = "search", 
	    allowMultiple = true, 
	    dataType = "string", 
	    paramType = "query", 
	    value = "Search by field: description"
	) 
})
//@formatter:on
public List<String> search(Search search) {
	System.out.println(search.toList().size());
	search.toList().forEach(System.out::println);
	
	//..... your code
}
```

## Results

![image](https://user-images.githubusercontent.com/47677287/156850371-aff595b9-9c4d-4c15-91c4-e13c4d67397e.png)

![image](https://user-images.githubusercontent.com/47677287/156850387-15ecb221-acfb-4d69-95f6-d3e15448af58.png)

**Comment by Ashley-welcome583** [comment]
@rstoyanchev https://stackdev.space/questions/what-methods-are-available-to-stop-the-automatic-decoding-of-requestparam-strings-within-a-spring-controller
