### ISSUE TITLE
Incorrect value of the MediaType.APPLICATION_PROBLEM_JSON_UTF8

### ISSUE THREAD

**Issue by jstanik** [spring-projects/spring-framework#23825]
spring-web: 5.2.0
The media type `APPLICATION_PROBLEM_JSON_UTF8` has incorrect value ~`application/problem;charset=UTF-8`~ instead of `application/problem+json;charset=UTF-8` missing the `+json` part.

[APPLICATION_PROBLEM_JSON_UTF8 = new MediaType("application", "problem", StandardCharsets.UTF_8);](https://github.com/spring-projects/spring-framework/blob/d1aee0e8691c41753621332ff69b17be3f7c8ba2/spring-web/src/main/java/org/springframework/http/MediaType.java#L373)

This causes regression like: 

    org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class fully.qualified.name.of.our.Exception] with preset Content-Type 'application/problem;charset=UTF-8'

**Comment by rstoyanchev** [comment]
Seems like a good candidate for 5.1.x. I've added a backport issue.

**Comment by jhoeller** [comment]
@rstoyanchev This seems to have been a side effect of #22340 in 5.2 only. No need for a backport.
