### ISSUE TITLE
@RequestHeader and POJO binding

### ISSUE THREAD

**Issue by tsarenkotxt** [spring-projects/spring-framework#23838]
Hi, do you have plans to add support for `header` binding with `POJO`?

This issue based on stackoverflow question [@RequestHeader not binding in POJO but binding only in variable](https://stackoverflow.com/questions/49305099/requestheader-not-binding-in-pojo-but-binding-only-in-variable)

IMHO, it would be a useful feature, instead of writing custom and similar `HandlerMethodArgumentResolver` 

Some ideas:
add an annotation for method args - `@Header`
add an annotation for `POJO` fields - `@HeaderParam`
add support for validation - `@Valid`
add support for immutable  `POJO`

Thanks

**Comment by LuTongT** [comment]
related: #23618

**Comment by rstoyanchev** [comment]
Based on the SO question, you don't need a custom resolver. Just [register](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-conversion) a `Converter`. All method arguments sourced from String-based request values (e.g. `@RequestHeader`, `@CookieValue`, `@PathVariable`, etc) pass through to type conversion from `String` to the target type.

Support for such annotations on fields is something different.

**Comment by bankelal** [comment]
@rstoyanchev - could you please provide with an example that would be most useful for everyone.
