### ISSUE TITLE
Consider moving JSON support from spring-web to its own module

### ISSUE THREAD

**Issue by elefeint** [spring-projects/spring-framework#23830]
_Disclaimer:_ this is a philosophical question to which there are only two possible reactions: a fast "LOL, no! -> close issue" and a slow "let's deprecate a chunk of functionality in spring-web and move it to a different place".

Ideally, full JSON support should be able to get autoconfigured without a dependency on `spring-web`, as JSON has evolved beyond it web roots into a popular application data interchange format. I've raised spring-projects/spring-boot#18639 for the possibility of `spring-boot-starter-json` removing its dependency on `spring-web`, but that's not a reasonable request while the logic itself [lives in `spring-web`](https://github.com/spring-projects/spring-framework/tree/053b95ceeb12faced172c8f3d7069315c49cab18/spring-web/src/main/java/org/springframework/http/converter/json).

For `spring-cloud-stream` applications, there is often no need to depend on any web functionality, but there is often a requirement for JSON-to-Object conversion. Basic conversion works fine with just a `com.fasterxml.jackson.core:jackson-core` dependency, but Java 8 date conversion needs `jackson-datatype-jsr310`, which for all applications depending on `spring-web` is conveniently handled by `Jackson2ObjectMapperBuilder.registerWellKnownModulesIfAvailable()`.

It would be great to have the same autoconfigured functionality available to non-web applications automatically by pulling in a starter.

**Comment by rstoyanchev** [comment]
This was discussed before at #17872. I'll add some further comments.

Indeed JSON isn't specific to web and we have support for Jackson/JSON support in other modules like `spring-messaging` and `spring-jms` where we do the same more or less but in a different context (i.e. not HTTP request/response but message payload). 

It seems that both this and #17872 are about `Jackson2ObjectMapperBuilder` which is about configuring Jackson and applies to all those places. Unfortunately that class already exists in `spring-web` and creating a module for that only just isn't something that we would do.

We could consider a different module for it but for once that would be confusing for quite some time while we have two identical classes in different packages. The more important challenge however is that there isn't an ideal module. The `spring-messaging` and `spring-jms` are quite orthogonal and `spring-core` or even `spring-context` are too low level and not meant to have such dependencies.

So I'm afraid the answer is the same as in #17872.
