### ISSUE TITLE
Regression: Resource bundle message source custom validation message no longer resolved

### ISSUE THREAD

**Issue by rgolder1** [spring-projects/spring-framework#23839]
**Issue:**

Resource bundle message source custom validation message no longer resolved following upgrade from Spring 5.1.6.RELEASE to Spring 5.2.0.RELEASE.

DefaultListableBeanFactory preinstantiateSingletons() bean instantiation order:

1. LocalValidatorFactoryBean "defaultValidator"
2. RequestMappingHandlerAdapter "requestMappingHandlerAdapter"
3. LocalValidatorFactoryBean "mvcValidator"

**Spring 5.1.6 behaviour:**

WebMvcConfigurationSupport requestMappingHandlerAdapter() `@Bean` method takes no args. It calls WebMvcAutoConfiguration mvcValidator() which calls WebMvcConfigurerComposite getValidator() which calls the getValidator() `@Override` in my Configuration class, which creates a LocalValidatorFactoryBean setting the ValidationMessageSource to my ReloadableResourceBundleMessageSource messageSource.

_Upshot:_ requestMappingHandlerAdapter configured with the userResourceBundleLocator set to MessageSourceResoureBundleLocator as expected.

**Spring 5.2.0 behaviour:**

WebMvcConfigurationSupport requestMappingHandlerAdapter() `@Bean` method now takes a Validator. It is instantiated with the "defaultValidator" LocalValidatorFactoryBean. That has a PlatformResourceBundleLocator as the userResourceBundleLocator.

_Upshot:_ requestMappingHandlerAdapter configured with the userResourceBundleLocator set to PlatformResoureBundleLocator.

Subsequently, the mvcValidator() `@Bean` is instantiated, but too late for use in the requestMappingHandlerAdapter.

**Comment by sbrannen** [comment]
Hi @rgolder1,

Thanks for raising the issue.

Can you provide a minimal example that reproduces the exact issue you're encountering?

**Comment by rgolder1** [comment]
Hi Sam,

Here you go, replication steps are in the ReadMe:

https://github.com/rgolder1/error-handler-spring

Rob.

**Comment by sbrannen** [comment]
Thanks for the repo project!

We'll look into it.

**Comment by sbrannen** [comment]
Thanks to the provided repro project, I can confirm that this is a regression introduced in 5.2

```
Failed tests:   testNumberTooHigh(example.ConstraintErrorIntegrationTest): expected:<[The number must not be more than 10]> but was:<[{test.api.simpleupdate.number.max}]>
```

**Comment by sbrannen** [comment]
In light of https://github.com/spring-projects/spring-boot/issues/18672#issuecomment-547038652, I am closing this issue.

**Comment by sbrannen** [comment]
Please note that this issue is a _duplicate_ of https://github.com/spring-projects/spring-boot/issues/18672#issuecomment-547038652 (in Spring Boot) and was superseded by #23887 (in Spring Framework).

Thus, the "fix" for this issue is the combination of the fixes in https://github.com/spring-projects/spring-boot/issues/18672#issuecomment-547038652 and #23887.
