### ISSUE TITLE
ResponseEntity.of method returns 404 when empty, should return 204

### ISSUE THREAD

**Issue by tomhughesnice** [spring-projects/spring-framework#23845]
**Affects:** v5.2.0.RELEASE

---

With the `org.springframework.http.ResponseEntity` class their is the following method for mapping an `Optional` to an HTTP Response.

```java
public static <T> ResponseEntity<T> of(Optional<T> body) {
    Assert.notNull(body, "Body must not be null");
    return body.map(ResponseEntity::ok).orElse(notFound().build());
}
```

I think returning a 404 NOT FOUND is the incorrect response code. This should be a 204 NO CONTENT. 4XX codes usually indicate a client error: a 404 in this case is usually calling an invalid URI. 204 seems more appropriate. 

Happy to make a pull request.

**Comment by sbrannen** [comment]
Returning a different status code would be a breaking change, so I think we likely will not want to make any changes here.

In light of that, please hold off on submitting a PR.

**Comment by sbrannen** [comment]
**Team Decision**: Since the proposal would introduce a breaking change, we cannot change the status code for an empty body. In addition, returning a 204 could potentially mislead clients into believing that the request was _successful_ but simply did not contain content. Furthermore, one is not required to use `ResponseEntity.of()`: it's merely there for convenience for use cases suitable to the documented behavior.

**Comment by tomhughesnice** [comment]
Your point about the breaking change is fair. Everyone using this method will suddenly see different status codes and will not understand why.

> In addition, returning a 204 could potentially mislead clients into believing that the request was successful but simply did not contain content.

Thats exactly the reasoning I thought this method should change. The request was successful, but there was no content. If the body being empty is an error, I think thats up to service logic to determine.

**Comment by sbrannen** [comment]
> Your point about the breaking change is fair. Everyone using this method will suddenly see different status codes and will not understand why.

Exactly!

> Thats exactly the reasoning I thought this method should change. The request was successful, but there was no content. If the body being empty is an error, I think thats up to service logic to determine.

Well, since we cannot change the existing behavior, at least it's simple enough to achieve your goal with a single line:

```java
return body.map(ResponseEntity::ok).orElse(ResponseEntity.noContent().build());
```

You could even create your own static factory method based on that if you find yourself using it frequently.
