### ISSUE TITLE
webflux find a bug

### ISSUE THREAD

**Issue by liucyu** [spring-projects/spring-framework#23849]
![image](https://user-images.githubusercontent.com/13191643/67351504-4001f580-f580-11e9-80c8-1b97a9236b40.png)

**Comment by rstoyanchev** [comment]
The returned Flux is created from a custom Publisher that violates Reactive Streams [rule 1.9](https://github.com/reactive-streams/reactive-streams-jvm#1-publisher-code):

> Publisher.subscribe MUST call onSubscribe on the provided Subscriber prior to any other signals

I don't know what you're trying to do but this is the same as `Flux.just("test")`.

**Comment by liucyu** [comment]
@rstoyanchev I need to execute the RPC inside `Flux.from`, then return via onNext
