### ISSUE TITLE
Repeatable annotation container no longer found on custom composed annotation

### ISSUE THREAD

**Issue by Walliee** [spring-projects/spring-framework#23856]
Looks like migration of `AnnotationUtils` to use the `MergedAnnotations` API has introduced a regression to the `public static <A extends Annotation> A findAnnotation(Method method, @Nullable Class<A> annotationType)` method when finding repeatable annotations that are declared on custom composed annotations.

```java
// Repeatable annotation

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Repeatable(Roles.class)
public @interface Role {
	String value() default "";
}
```

```java
// Container annotation

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
public @interface Roles {
	Role[] value();
}
```

```java
// Custom composed annotation 

@Retention(RetentionPolicy.RUNTIME)
@Role("role_a")
@Role("role_b")
public @interface MyCustomRole {
}
```

```java
class MyObject {
	@MyCustomRole
	public void someMethod() {}
}
```

`AnnotationUtils.findAnnotation(someMethod, Roles.class)` returns `null` after upgrading to 5.2.0.RELEASE

I've created a sample here to better demonstrate: https://github.com/Walliee/repeatable-annotations

All 3 tests pass on 5.1.10.RELEASE but only 2 on 5.2.0.RELEASE

**Affected versions:** 5.2.0.RELEASE

**Comment by sbrannen** [comment]
Thanks for raising the issue and for supplying the repro project!

I have confirmed that this is a regression in 5.2.0.

We'll look into it.

**Comment by sbrannen** [comment]
See also #23767.
