### ISSUE TITLE
spring-context-indexer: support creating spring.components file in jar built with Spring 4

### ISSUE THREAD

**Issue by atsu85** [spring-projects/spring-framework#23861]
It would be nice, if spring-context-indexer would work with Spring 4 as well so that created jar file could contain `spring.components` file

# Benefits
* libraries that use Spring 4 could produce jar files that contain `spring.components` file
* applications that use Spring 5 with spring-context-indexer
    * wouldn't fail because of library built with Spring 4 that relies on classpath scanning (for example because it contains classes with `@Component`)
    * would start up faster (compared to disabling spring-context-indexer)

note, that libraries may even throw exceptions on application startup if spring-context-indexer is disabled (i stumbled upon one that doesn't support disabling indexer so as i understand it isn't possible to library requiring indexer to be turned on with another one that doesn't have `spring.components` file but relies on classpath scanning)

# Current situation
Currently when buliding jar from Gradle project that uses spring 4 with additional dependencies
```Gradle
dependencies {
  // ...
  annotationProcessor 'org.springframework:spring-context-indexer:5.2.0.RELEASE'
  testAnnotationProcessor 'org.springframework:spring-context-indexer:5.2.0.RELEASE'
}
```
then building jar succeeds without errors or even warnings, but jar file doesn't contain `spring.components`.

**Comment by snicoll** [comment]
Thanks for the suggestion. Mixing Spring Framework versions is not supported (that includes the use of an annotation processor). Support for Spring Framework `4.x` ends in Q1 2020 so an upgrade of those components is in order regardless.

Context indexer is a Spring Framework 5 features so I am afraid we won't backport it.
