### ISSUE TITLE
Support matching against multiple header values in HeaderAssertions

### ISSUE THREAD

**Issue by Adamovskiy** [spring-projects/spring-framework#23878]
The only way to validate multiple response header values – is to assert for strict equality with `valueEquals(String headerName, String... values)`. Got to be a way to also validate them against regular expression, and with any custom check, like in `value(String name, Consumer<String> consumer)` (which btw has wrong copy-pasted javadoc).

Other method javadocs say that they work with "primary value". There is no such term neither in [RFC7230](https://tools.ietf.org/html/rfc7230), nor in [RFC6265](https://tools.ietf.org/html/rfc6265). It seems that all values should be treated as equally significant.

This functionality is extremely important for work with response cookies (`Set-Cookie` header).

**Comment by sbrannen** [comment]
Thanks for raising the issue.

I improved the Javadoc in 46329d0b973eaf4698a5fb916996f3ad6274201f.
