### ISSUE TITLE
WebClient onStatus order changed

### ISSUE THREAD

**Issue by trecloux** [spring-projects/spring-framework#23880]
**Affects:** 5.2.0

Hi all,

It looks like the `onStatus` custom error predicates are now evaluated in the inverted error compared to version `5.1.x`

Using the `WebClient` this way:
```
webClient.

...

  .onStatus(
     HttpStatus.BAD_REQUEST::equals,
     res -> res.bodyToMono(Void.class).then(Mono.just(new SpecificException()))
  )
  .onStatus(
    HttpStatus::isError,
    res -> res.bodyToMono(Void.class).then(Mono.just(new GenericException())))
   )

...

```
Using `5.1.0` first `onStatus` was evaluated first, using version `5.2.0` with the same `WebClient` usage, last `onStatus` is evaluated first and behavior is significantly changed.

This behavior change was introduced in commit https://github.com/spring-projects/spring-framework/commit/a9b3d95a14c316387f2b77328d6864b8e0a36721

If this `onStatus` evaluation order is not guaranteed, I think that this should be documented.

I can submit a documentation or a fix pull request.

Thomas

**Comment by trecloux** [comment]
Thanks a lot guys.

**Comment by rstoyanchev** [comment]
Thanks for the offer to send a PR but I wanted to make sure this makes 5.2.1.
