### ISSUE TITLE
Exception loading LocalSessionFactoryBean -  signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [spring-projects/spring-framework#23889]
**Affects:** 5.1.4.RELEASE

---

Hello,

My application is running on Java 11 and I am using Spring 5.1.4.RELEASE with Hibernate Core 5.3.7.Final.  I am trying to run my application in Jetty via Maven and in the stack trace I see: 

`java.lang.SecurityException: class "javax.transaction.SystemException"'s signer information does not match signer information of other classes in the same package`

The full stack trace is shown in the attached file.  I can see from it that this happens when intialising the bean org.springframework.orm.hibernate5.LocalSessionFactoryBean .  

Also Attached is a copy of my Application Context with the bean definitions.

[security-datasource-context.xml.txt](https://github.com/spring-projects/spring-framework/files/3785233/security-datasource-context.xml.txt)

[stacktrace.txt](https://github.com/spring-projects/spring-framework/files/3785172/stacktrace.txt)

**Comment by snicoll** [comment]
Code in text and a stacktrace won't help us to help you. However, it's pretty clear from the stacktrace that Spring is not involved so I don't really understand why you're reporting this here.
