### ISSUE TITLE
component-scan load beans in unfixed order in different machine

### ISSUE THREAD

**Issue by jessin20161124** [spring-projects/spring-framework#23912]
we find the bean load order is different for component-scan in different machine, is this a bug?

**Comment by snicoll** [comment]
@jessin20161124 I am not sure what you mean by "load order". There are no guarantee as how beans are scanned indeed and you shouldn't be relying on any sort of order for components identified by classpath scanning. 

If you have more questions, please ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
