### ISSUE TITLE
Kotlin Extension Function for WebClient in Spring WebFlux

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-framework#23925]
I'd recommend a Kotlin Extension Function for _WebClient_ in the context of _Kotlin Coroutines_. Currently POST (PUT, PATCH) requests look like the following:

```
val customer: Customer = ...
val client = WebClient.builder()
    ...
    .baseUrl(...)
    .build()
val response = client.post()
    .body(customer.toMono())  // Project Reactor becomes visible inspite of awaitExchange
    .awaitExchange()
```

Just a suggestion for an _Extension Function_ (maybe there is a better name than `singleBody`):
```
inline fun <reified T : Any> WebClient.RequestBodySpec.singleBody(obj: T): WebClient.RequestHeadersSpec<*>
   = body(obj.toMono())
```

**Comment by sdeleuze** [comment]
With Kotlin Coroutines what you probably need here is `bodyValue()`, so you can write `client.post().bodyValue(customer)`, it is already available so I close this issue.
