### ISSUE TITLE
Default spring security cache-control disables ShallowETagHeaderFilter

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#23930]
**Affects:**  5.2.0.RELEASE

Using **ShallowETagHeaderFilter**, **ETag** is not checked in request because the response has **Cache-control: no-store** (_CacheControlHeadersWriter.java_).
Thus **ShallowETagHeaderFilter** is not compatible with **Spring Security** using _default_ configuration.

**Comment by rstoyanchev** [comment]
The `ShallowETagHeaderFilter` is unaware of what set the header or why so it's not a question of compatibility. The filter simply reacts to the fact that a cache-control directive was set that effectively says a cache must not store anything. 

So it is more of a Spring Security question, but it is already covered in its reference:
https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#headers-cache-control
