### ISSUE TITLE
Update docs on ShallowEtagHeaderFilter with regards to ASYNC dispatches

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#23958]
**Affects:** 5.2.0.RELEASE

Original issue: https://github.com/spring-projects/spring-boot/issues/18931

Registering **ShallowEtagHeaderFilter** with default configuration **breaks** async web requests, causing timeouts:
```
    @Bean
    public Filter etagFilter() {
        return new ShallowEtagHeaderFilter();
    }
```
The correct configuration is:
```
@Bean
public FilterRegistrationBean<ShallowEtagHeaderFilter> etagFilter() {
    FilterRegistrationBean<ShallowEtagHeaderFilter> registration = new FilterRegistrationBean<>(new ShallowEtagHeaderFilter());
    registration.setDispatcherTypes(EnumSet.of(DispatcherType.REQUEST, DispatcherType.ASYNC));
    return registration;
}
```

Please update the [documentation ](https://docs.spring.io/spring-framework/docs/5.2.1.RELEASE/spring-framework-reference/web.html#filters-shallow-etag)to include this configuration for async requests, or provide a way to automatically configure for async requests.

**Comment by rstoyanchev** [comment]
Actually, `FilterRegistrationBean` is a Spring Boot mechanism, so the Spring Framework reference isn't a good place for the above snippet. 

In the Spring Framework we [support a `WebApplicationInitializer`](https://github.com/spring-projects/spring-framework/blob/ffe69a51e197152509458c0ed56bba1d83e87632/spring-webmvc/src/main/java/org/springframework/web/servlet/support/AbstractDispatcherServletInitializer.java#L185) for `DispatcherServlet` setup. That lets you provide an array of Servlet Filter instances all of which are then automatically registered for ASYNC dispatches. 

The thinking behind this is that a) `DispatcherServlet` has asyncSupported enabled by default so filters would fail on async requests if they didn't have this flag enabled too, and b) once asyncSupported is enabled it becomes a runtime decision and all filters must be able to decide for themselves and that's what the `shouldNotFilterAsyncDispatch` flag in  `OncePerRequestFilter` is all about.

I hate bouncing this around but I'm afraid there is nothing further to do here. At best I see Spring Boot providing some guidance on using `FilterRegistrationBean` with regards to async, perhaps providing a general advice that ASYNC dispatches are safe to enable for `OncePerRequestFilter` which will do the right thing anyway. Another option is to automatically add ASYNC to any `OncePerRequestFilter`.

**Comment by wilkinsona** [comment]
We can take another look on the Boot side, but I do think it is worth noting somewhere in Framework that `ShallowEtagHeaderFilter` must be registered for async dispatches and that it will break if it is not. I don't think it's safe to make assumptions about how a user will register the filter. In addition to Boot's `FilterRegistrationBean, a user could register it via `web.xml` or via a sub-class annotated with `@WebFilter`. In both cases the Servlet spec's default of only `REQUEST` will be used and there's nothing in the documentation for `ShallowEtagHeaderFilter` to help someone avoid that mistake.

**Comment by rstoyanchev** [comment]
Okay, fair enough. I've added a paragraph on this for both ShallowEtagFilter and ForwardedHeaderFilter. Note however it is a little bit odd to effectively say "nothing to do with just Spring Framework, but with Boot don't forget to add the ASYNC dispatch". It is a hint that maybe an improvement in Boot is possible.

**Comment by wilkinsona** [comment]
Thank you, @rstoyanchev. I've opened https://github.com/spring-projects/spring-boot/issues/18953 to take another look at things on the Boot side.
