### ISSUE TITLE
DEFAULT_PHASE of SmartLifecycle interface has incorrect Javadoc

### ISSUE THREAD

**Issue by molekyla** [spring-projects/spring-framework#23956]
**Affects:** 5.1.x

Javadoc says:

> The default phase for SmartLifecycle Integer.MAX_VALUE. This is different from the common phase 0 associated with regular Lifecycle implementations, putting the typically auto-started SmartLifecycle beans into a separate **later shutdown phase**

But in fact instances with greater phase property in shutdown phase executed firstly. So there is a bug or staled javadoc?

**Comment by sbrannen** [comment]
Good catch!

We'll update the Javadoc to reflect the actual semantics.
