### ISSUE TITLE
SpelCompiler is unable to compile too often

### ISSUE THREAD

**Issue by tonyschwartz** [spring-projects/spring-framework#23963]
I need to allow allow a user to build an expression that will be used to evaluate a boolean result against millions of records per second, so I need to ensure the expression is compiled.  There is an apparent problem with the way the spring expression framework attempts to compile the expression.

Let's say I have this expression: `productType == 'Firewall' and categoryId == 400`

The issue is: If the first 100 records that are sent through this expression never contain `productType="Firewall"`, then `categoryId` is never evaluated by the parser due to short-circuiting of the boolean "and" operator.  Deep in the code, in `PropertyOrFieldReference`, `this.cachedReadAccessor` is always null for the `categoryId` field. Because of this, the spring expression parser will never be able to compile this expression.

Does anyone have any recommendations for me?

I'd like to use this framework for this use case, but I need to ensure these expressions are compiled.

**Comment by aclement** [comment]
Yeah, it is optimizing itself based on the shape of data it sees. I feel like there is a bug to investigate here but I am thinking about ways to workaround that for now.

You could:
- run the expression over items that do have a productType (test items that have the right structure) to create the right fields in the ast nodes then it will compile, then apply it to the data in question. Whether this works might depend on how the objects differ between those that have the productType and those that don't - should I be guessing the ones missing it are missing the field entirely? If they are entirely different it'll crash the first time you hit an object missing the field.

- adjust it to a (#productType(#this)=='Firewall' and categoryId==400) and add an implementation of that productType function to the evaluation context. It should be compilable even if that function is returning null for the first few objects (obviously you don't want that function using reflection though, but I'm not quite sure about the domain objects involved here - but maybe the function can use an 'instanceof' check (if `instanceof ThingWithProductType' return ((ThingWithProductType)object).getProductType()`)?

If you shared a bit more on the object types being evaluated against, I might be able to come up with other options.

**Comment by sbrannen** [comment]
If you cannot register a custom function, you can always invoke a static method from one of your classes or a method on a bean in the `ApplicationContext`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by sbrannen** [comment]
Related to:

- #29548
