### ISSUE TITLE
Technical Support Expiration Date

### ISSUE THREAD

**Issue by Sergindra** [spring-projects/spring-framework#23982]
Hello,

I work for a long-term project which requires strong and stable technical support for every software used.

I want to know how long you are providing technical support for Spring Framework 4.3.24.

Please I appreciate so much that you can give me expiration dates for this software product or expectations of its EOL.

Thank you!
Sergi

**Comment by jhoeller** [comment]
We have not announced a concrete target date for Spring Framework 4.3 EOL yet. At this point we expect support until the end of 2020, with an official EOL announcement by the end of 2019.

That said, please don't create GitHub issues for support timeline questions. This issue tracker is only really meant for code-level and doc-level issues in the open source codebase itself.
