### ISSUE TITLE
TypeDescriptor#getElementTypeDescriptor does not throw IllegalStateException anymore

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-framework#23996]
The JavaDoc of `TypeDescriptor#getElementTypeDescriptor` states 

>  @throws IllegalStateException if this type is not a {@code java.util.Collection} or array type

However, that is not the case:

```
public static void main(String...a) {
	System.out.println(TypeDescriptor.valueOf(String.class).getElementTypeDescriptor());
	System.out.println(TypeDescriptor.valueOf(String[].class).getElementTypeDescriptor());
}
```

This works without an exception.

I would provide a fix, if I knew what is wrong: The behaviour or only the JavaDoc.

**Comment by jhoeller** [comment]
Well spotted! This used to be true but changed in 5.0. I'll revise the javadoc accordingly.

**Comment by michael-simons** [comment]
Thanks, @jhoeller !

**Comment by jhoeller** [comment]
Turns out that it actually changed back in 4.0... The last one with actual `IllegalStateException` throwing there was 3.2.x :-)
