### ISSUE TITLE
Enhancement - Allow developers to catch the resolved params after getMethodArgumentValues() and before invoking custom handlers in WebFlux

### ISSUE THREAD

**Issue by JamesChenX** [spring-projects/spring-framework#24004]
**Affects:** v5.2.1.RELEASE
Scenario: WebFlux, Annotated Controllers

What expected: Developers can add a "filter" after getMethodArgumentValues() and before invoking custom methods in annotated controllers (between 137 to 146 line in org/springframework/web/reactive/result/method/InvocableHandlerMethod.java)

Why: I want to get all resolved params for controllers in a "filter".
Although I can achieve the function by resolving the params from requests in WebFilter but it's really wasteful and meaningless to resolve the params twice (one in WebFilter by myself and another by Spring).

**Comment by rstoyanchev** [comment]
This is in `InvocableHandlerMethod`?  Adding a "filter" at that point is not as straight-forward as it sounds. It would be a top-level contract of the API, and one that would require plenty of consideration in terms of how it interacts with other parts of the API. We'd also have to anticipate what other needs it might bring along.

This is unlikely to happen frankly, certainly not with this little information about the motivation. At this time I suggest providing more details about what you're trying to do to help us understand the motivation. For example when you say "params" could you be more specific? Also if you could describe a scenario.

**Comment by JamesChenX** [comment]
Thank you for your kind reply.

I have tried `HandlerMethodArgumentResolver` but it seems the resolved results won't be passed down to my resolver if the default revolvers have resolved the params from requests successfully (while I want the resolved results).

Scenario: My project has many controllers with a lot of handlers. I want to persist all resolved params (and body if necessary) from requests into MongoDB.
Although I can persist queryParams in String but it's should be the last choice since I want structure data.

What's more, I have also tried exchange.getResponse().beforeCommit() in WebFilter which should better pass the resolved params and body down to the callback in beforeCommit() but it hasn't.
Maybe it's also a good choice to pass resolved result (not only response) in beforeCommit()

**Comment by rstoyanchev** [comment]
Okay so when you say "params" you mean all the arguments passed into the handler method. Keep in mind those are in the form of an `Object[]` and an interceptor would have no way of finding out which argument without checking method parameter types and annotations. It's also not clear why you want to do this and that doesn't really help to motivate the change.

**Comment by rstoyanchev** [comment]
One last thought. This sounds like the sort of thing you might want to do via [AOP](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-api).
