### ISSUE TITLE
Cannot add a custom annotation to the defaults in AutowiredAnnotationBeanPostProcessor

### ISSUE THREAD

**Issue by kse-music** [spring-projects/spring-framework#24003]
**Affects:** \<all version>

---

when set my own (non-Spring-specific) annotation type to indicate that a member is supposed
to be autowired,but I found that I empty the original annotation (Autowired、Value) every time.I hope to add extra custom annotations just on the basis of the original.
can remove this.autowiredAnnotationTypes.clear(); ?
![{C78F474A-748A-402C-B41E-4FEF5D1F22FC}_20191115103431](https://user-images.githubusercontent.com/33364651/68912589-87506000-0793-11ea-9931-45923fffda26.jpg)

**Comment by sbrannen** [comment]
> Can you remove `this.autowiredAnnotationTypes.clear();` ?

The methods in question specifically *set* the new annotation type(s).

Thus, retaining the existing configured types would not be correct. Furthermore, that would be a breaking change.

So we cannot do that.

However, it sounds to me like what you're really requesting is the ability to *add* a custom annotation type to the existing configured types (which would typically be the defaults).

If so, we could consider introducing an `addAutowiredAnnotationTypes(...)` method with those semantics.

Is that what you are asking for?

**Comment by sbrannen** [comment]
@kse-music, can you please provide us some background on what it is you are trying to achieve?

For example, what is your concrete use case, and how are you configuring the the `AutowiredAnnotationBeanPostProcessor`?

**Comment by kse-music** [comment]
@sbrannen Thank you very much, addAutowiredAnnotationTypes is what my want.In fact,I just want to use Autowired.class function,But I don't want add spring dependency in my own common module, and I need AutowiredAnnotationBeanPostProcessor can deal my custom annotation.
Here are my implementations,but i don't like it.
![1](https://user-images.githubusercontent.com/33364651/68955622-60307780-0801-11ea-976b-28882abffe82.png)


![2](https://user-images.githubusercontent.com/33364651/68955650-6aeb0c80-0801-11ea-874e-7464f6eed1a8.png)

![3](https://user-images.githubusercontent.com/33364651/68955658-6d4d6680-0801-11ea-8c3b-060d587d8c19.png)

**Comment by sbrannen** [comment]
@kse-music, that seems overly complex to me.

To achieve your goal, you could just add another, custom-configured `AutowiredAnnotationBeanPostProcessor` to the `ApplicationContext` that handles only your `@McnAutowired` annotation.

For example, the following test demonstrates this approach.

If you comment out the `customAABPP()` `@Bean` method, the test fails since `bar` is equal to `null` (i.e., because it was not autowired).

```java
@SpringJUnitConfig
class CustomAutowiredAnnotationTests {

	@Autowired
	MyComponent myComponent;

	@Test
	void test() {
		assertThat(myComponent.foo).isEqualTo("foo");
		assertThat(myComponent.bar).isEqualTo("bar");
	}

	@Configuration
	static class Config {

		@Bean
		AutowiredAnnotationBeanPostProcessor customAABPP() {
			AutowiredAnnotationBeanPostProcessor bpp = new AutowiredAnnotationBeanPostProcessor();
			bpp.setAutowiredAnnotationType(MyAutowired.class);
			return bpp;
		}

		@Bean
		String foo() {
			return "foo";
		}

		@Bean
		String bar() {
			return "bar";
		}

		@Bean
		MyComponent myComponennt() {
			return new MyComponent();
		}
	}
}
```

```java
static class MyComponent {

	@Autowired
	String foo;

	@MyAutowired
	String bar;

}
```

```java
@Retention(RetentionPolicy.RUNTIME)
@interface MyAutowired {
}
```

Is that a suitable solution for your use case?

**Comment by sbrannen** [comment]
> But I don't want add spring dependency in my own common module

Have you considered using `@Inject` instead of `@Autowired`?

**Comment by kse-music** [comment]
> > But I don't want add spring dependency in my own common module
> 
> Have you considered using `@Inject` instead of `@Autowired`?

In fact,I hope no dependency on any third-party framework.@Inject in Javax. But the solution you provided above work nice,and It would be better if you could provide addAutowiredAnnotationTypes method.thanks a lot.

**Comment by sbrannen** [comment]
@kse-music, thanks for providing feedback.

> @sbrannen In fact,I hope no dependency on any third-party framework.`@Inject` in Javax. 

OK. Understood.

> But the solution you provided above work nice,

Great! I'm glad to hear that works well for you.

> and It would be better if you could provide addAutowiredAnnotationTypes method.thanks a lot.

Since the suggested alternative solution works for you, we will hold off on introducing a new `addAutowiredAnnotationTypes(...)` method for the time being but may reconsider it if there is greater interest from the community at a later date.
