### ISSUE TITLE
Improve SimpleCommandLineArgsParser's javadoc - add other invalid example

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#24016]
**Affects:** 5.x (perhaps olders)

---

I have the following situation:

* [Spring Framework: Why command line argument “--argument-name=” throws Invalid argument syntax?](https://stackoverflow.com/questions/58904260/spring-framework-why-command-line-argument-argument-name-throws-invalid-ar)

I read the javadoc of the [SimpleCommandLineArgsParser](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/env/SimpleCommandLineArgsParser.java#L19) class

Through a comment of the post, now is clear the reason, therefore I think has sense to include a new invalid scenario:

* `--foo=`

If it is acceptable I would add that scenario and send a pull request. But I need your confirmation first.

Thanks

**Comment by snicoll** [comment]
Looking at the SO, I don't think an update to the documentation is warranted for this. The Spring Boot documentation [already states](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.command-line-args) that command line arguments start with two dashes. If you decide to pass extra arguments with a single dash or two dots or whatever, you can't expect this to work with the same rule.
