### ISSUE TITLE
Spring Batch: AbstractFileItemWriter should support java.nio

### ISSUE THREAD

**Issue by rowi1de** [spring-projects/spring-framework#24011]
**Affects:** Spring Batch / spring-batch-infrastructure (master)

---

Spring Batch / spring-batch-infrastructure: [AbstractFileItemWriter.java ](https://github.com/spring-projects/spring-batch/blob/d8fc58338d3b059b67b5f777adc132d2564d7402/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/support/AbstractFileItemWriter.java) always uses java.io no matter which `org.springframework.core.io.Resource` is used. 
As the class represents a `FileItemWriter`, Resource could be specialized to a `WritableResource`. This allows a `AbstractFileItemWriter` java.nio based implementation.

**Comment by snicoll** [comment]
This issue tracker is for the spring framework only. Spring batch a has a dedicated issue tracker. 


https://jira.spring.io/projects/BATCH/issues
