### ISSUE TITLE
Alternative to @Qualifier for group beans

### ISSUE THREAD

**Issue by ntviet18** [spring-projects/spring-framework#24020]
**Affects:** 5.2.1

---

At the moment, we can autowire a bean within specialized scope using `@Qualifier` annotation, e.g.

```java
@Bean
@Qualifier("specialized-scope")
Dependency dependency() { /* code */ }

@Bean
Service service(@Qualifier("specialized-scope") Dependency dependency) { /* code */ }
```

But the process might become tedious and error prone, once we have multiple bean with the same qualifiers, for example:

```java
@Configuration
class GlobalModule {

  @Bean
  @Qualifier("specialized-scope")
  Dependency1 dependency1() { /* code */ }

  @Bean
  @Qualifier("specialized-scope")
  Dependency2 dependency2(@Qualifier("specialized-scope") Dependency1  dependency1) { /* code */ }

  @Bean
  @Qualifier("specialized-scope")
  Dependency3 dependency3(@Qualifier("specialized-scope") Dependency1  dependency1, @Qualifier("specialized-scope") Dependency2  dependency2) { /* code */ }

  // I want to expose only this bean to the global scope
  @Bean
  Service service(@Qualifier("specialized-scope") Dependency3 dependency3) { /* code */ }
}
```

Is it possible to create the qualifier once like below and have all the beans inherit the qualifier from configuration scope?

```java
@Configuration
@Qualifier("specialized-scope")
class SpecializedModule {

  @Bean
  Dependency1 dependency1() { /* code */ }

  @Bean
  Dependency2 dependency2(Dependency1 dependency1) { /* code */ }

  @Bean
  Dependency3 dependency3(Dependency1 dependency1, Dependency2 dependency2) { /* code */ }
}

@Configuration
class GlobalModule {

  @Bean
  Service service(@Qualifier("specialized-scope") Dependency3 dependency3) { /* code */ }
}
```

**Comment by sbrannen** [comment]
> Is it possible to create the qualifier once like below and have all the beans inherit the qualifier from configuration scope?

No, that's not possible.  If you declare `@Qualifier` on a `@Configuration` class, the qualifier is only associated with the `@Configuration` class, which typically would not make much sense.

You can, however, create custom qualifier annotations by using `@Qualifier` as a meta-annotation, which would make your use case less error prone. See [Fine-tuning Annotation-based Autowiring with Qualifiers](https://docs.spring.io/spring/docs/5.2.1.RELEASE/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers) in the reference manual for further details.
