### ISSUE TITLE
Protobuf MessageConverter in spring-messaging for use with STOMP

### ISSUE THREAD

**Issue by onlybytes** [spring-projects/spring-framework#24022]
Hi,

I have created a ReactorNettyTcpStompClient to connect to RabbitMQ STOMP.

My requirement is to send **protobuf ByteString** to the destination queue. I tried with all the message converters that are available under _org.springframework.messaging.converter_ package. Either i get `MessageDeliveryException: nested exception is java.lang.ClassCastException` or `MessageConversionException: Unable to convert payload with.... `

I am thinking of overriding/overloading the send() method of `DefaultStompSession `class and use it.

Is there any other easier way?

How to use protocol buffers with Spring Messaging?

Thanks,
Strive

**Comment by rstoyanchev** [comment]
Currently there isn't a [MessageConverter](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jms/support/converter/MessageConverter.html) in `spring-messaging` for Protobuf. The `spring-web` module however has an `ProtobufHttpMessageConverter` and it wouldn't be too hard to copy the implementation of that in order create a `MessageConverter` equivalent.

**Comment by onlybytes** [comment]
I created a converter that suits my needs (took a clue from ByteArrayMessageConverter).
Definitely will have look at ProtobufHttpMessageConverter.

Thanks for adding this to 5.x backlog

Regards,
Strive

**Comment by parviz-93** [comment]
Could i take this task ?

**Comment by rstoyanchev** [comment]
Yes, it is marked "ideal-for-contribution" and that means we've already identified it as something that should be straight-forward to address.

**Comment by parviz-93** [comment]
Please. check my [PR](https://github.com/spring-projects/spring-framework/pull/24087).
I also added a question on which I need advice

**Comment by rstoyanchev** [comment]
This is now superseded by #24087.
