### ISSUE TITLE
MultipartBodyBuilder should mention more explicitly it is for use in reactive applications

### ISSUE THREAD

**Issue by ST-DDT** [spring-projects/spring-framework#24031]
**Type:** Bug or missing/incomplete documentation
**Affects:** spring-web 5.2.1

If I try to use [`org.springframework.http.client.MultipartBodyBuilder`](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/client/MultipartBodyBuilder.java#L80) it instantly fails with:

````
Caused by: java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
	at test.InvalidRequestExceptionHandlerTest.test(InvalidRequestExceptionHandlerTest.java:97)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 70 more
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 72 more
````

If this class is only for reactive application this should be documented.
This might become more obvious if the import for the [`WebClient`](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/client/MultipartBodyBuilder.java#L44) is added, but currently this is unexpected. It would be nice if the class contains a link to the non-reactive version.

## Steps to reproduce

Add spring-web 5.2.1 to your dependencies.
Invoke the follwoing code:

````java
new MultipartBodyBuilder().build()
````

## Possible workaround

* Add the dependency for `org.reactivestreams.Publisher` to the classpath.

## Related issues

* https://github.com/spring-projects/spring-framework/issues/22876 (maybe)

**Comment by rstoyanchev** [comment]
This is expected indeed, assuming you're trying with the `RestTemplate`. See #23295 where we tried to make this more clear but I'm open to further suggestions. 

The Javadoc for `MultipartBodyBuilder` does mention the `WebClient` in its first paragraph and the example is based on the `WebClient`. 

> This might become more obvious if the import for the WebClient is added, but currently this is unexpected. It would be nice if the class contains a link to the non-reactive version.

I'm not really sure what you mean. Import where? Also a link to what exactly?

**Comment by ST-DDT** [comment]
Ok, if the class is for reactive content then this is not a bug, but I still would like to change the docs a bit. (It's still somewhat confusing because it doesn't have reactive in its name/package and there is no non-reactive equivalent for the well known term `MultipartBody`)

1) Add the term `reactive` somewhere in the first [paragrapgh](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/client/MultipartBodyBuilder.java#L42-L44).
2) Add a `@see MultiValueMap Use the MultiValueMap directly for non-reactive parts` or something similar

**Comment by rstoyanchev** [comment]
We do have a [multipart section](https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#rest-template-multipart) in the docs for `RestTemplate` that can be referenced.

As for "reactive" I think that can be ambiguous since `WebClient` can be used in Spring MVC controllers. I would rather keep it mentioning it's for use with the `WebClient`, and perhaps also explicitly mention it's not the best fit in scenarios where `RestTemplate` is used due to the dependency of the API on Reactive Streams.

**Comment by ST-DDT** [comment]
Thank you
