### ISSUE TITLE
UriComponentsBuilder should support repeated request parameters

### ISSUE THREAD

**Issue by jewertow** [spring-projects/spring-framework#24049]
## Background context

I have an endpoint for multi get requests:

```java
// GET /resources?id=1&id=2
@GetMapping
Resources getMultipleResources(@RequestParam("id") Set<String> ids)

```
which returns a json:

```javascript
{
    "resources": [
        {
            "id": "1"
             ...
        },
        {
            "id": "2"
             ...
        },
        ...
    ]
}
```

When I do http requests with `RestTemplate` I build URI using `UriComponentsBuilder`. 
But this builder has no convenient method to build URI with repeated query parameters. I have to modify the builder in `for` loop.

```java
final UriComponentsBuilder uriBuilder = UriComponentsBuilder
                .fromUriString("http://localhost:8080")
                .path("resources");
for (String id: ids) {
       uriBuilder.queryParam("id", id);
}
final URI uri = uriBuilder.build().toUri();
```

## Purpose

I would like to have a method dedicated for such case, e.g. 

```java
public UriComponentsBuilder queryParam queryParamRepeated(String param, Collection<Object> values)
```

Then a usage of such method could look like this:

```java
final Uri uri = UriComponentsBuilder
                .fromUriString("http://localhost:8080")
                .path("resources")
                .queryParamRepeated("id", ids)
                .build()
                .toUri();
```

If you think it would be valuable then I will prepare pull request.

**Comment by rstoyanchev** [comment]
The `queryParam` method is overloaded and built for this sort of thing. I don't see why we need another method for that.

For exampl this gives the expected result of `/resources?id=1&id=2`:

```java
List<Integer> ids = Arrays.asList(1, 2);
final URI uri = UriComponentsBuilder
		.fromUriString("http://localhost:8080")
		.path("resources")
		.queryParam("id", ids)
		.build()
		.toUri();
```

And so does:
```
final URI uri = UriComponentsBuilder
		.fromUriString("http://localhost:8080")
		.path("resources")
		.queryParam("id", 1, 2)
		.build()
		.toUri();
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
