### ISSUE TITLE
Jackson2TokenizerTest is missing a call to verify

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-framework#24056]
Hi,

I was trying to fix two places in the code that use an "unfinished" `StepVerifier` when I noticed an issue in the Jackson2Tokenizer handling. By applying the following patch, the test `Jackson2TokenizerTests#testLimit` starts to fail as the desired `DataBufferLimitException` is not thrown:
```patch
--- a/spring-web/src/test/java/org/springframework/http/codec/json/Jackson2TokenizerTests.java
+++ b/spring-web/src/test/java/org/springframework/http/codec/json/Jackson2TokenizerTests.java
@@ -19,6 +19,7 @@ package org.springframework.http.codec.json;
 import java.io.IOException;
 import java.io.UncheckedIOException;
 import java.nio.charset.StandardCharsets;
+import java.time.Duration;
 import java.util.List;

 import com.fasterxml.jackson.core.JsonFactory;
@@ -211,7 +212,7 @@ public class Jackson2TokenizerTests extends AbstractLeakCheckingTests {
                                .verifyComplete();

                StepVerifier.create(decode(source, false, maxInMemorySize - 1))
-                               .expectError(DataBufferLimitException.class);
+                               .expectError(DataBufferLimitException.class).verify(Duration.ofSeconds(5));
        }
```

I've done a lot of back and forth on this and tried the following patch for Jackson2Tokenizer that seems to let the tests pass again:
```patch
--- a/spring-web/src/main/java/org/springframework/http/codec/json/Jackson2Tokenizer.java
+++ b/spring-web/src/main/java/org/springframework/http/codec/json/Jackson2Tokenizer.java
@@ -186,7 +186,7 @@ final class Jackson2Tokenizer {

        private void assertInMemorySize(int currentBufferSize, List<TokenBuffer> result) {
                if (this.maxInMemorySize >= 0) {
-                       if (!result.isEmpty()) {
+                       if (this.tokenizeArrayElements && !result.isEmpty()) {
                                this.byteCount = 0;
                        }
                        else if (currentBufferSize > Integer.MAX_VALUE - this.byteCount) {
```
I'm not entirely confident that's the correct fix as I miss the domain knowledge if I'm totally honest.

While taking a deeper look though I noticed that Jackson2Tokenizer is always invoked with the `tokenizeArrayElements` switched turned on (apart from the tests obviously). So my preferred option would be to remove that field and its related logic entirely and therefore simplifying the class. Given that it's a package internal class, that shouldn't be a big problem.

In general, I would create two separate PRs:

- Remove `tokenizeArrayElements` from `Jackson2Tokenizer`
- Fix StepVerifier usage in `EncoderHttpMessageWriterTests#emptyBodyWritten` (that's the other broken StepVerifier usage)

I wanted to sync with you upfront before I create PRs that maybe don't make sense, so let me know what you think.

Cheers,
Christoph

**Comment by rstoyanchev** [comment]
@dreis2211 thanks for pointing this out. The logic in Jackson2Tokenizer is actually okay but the limit should be `maxInMemorySize - 2`  in this case.

**Comment by dreis2211** [comment]
Could you elaborate why this should be -2?

**Comment by rstoyanchev** [comment]
It's checking the size after every data chunk processed. The last chunk is 1 byte, so it's that last byte that pushes over the limit but at that point the TokenBuffer has been produced so the counting stops.
