### ISSUE TITLE
sorry-i am not found 2.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by Orgxiaowei** [spring-projects/spring-framework#24065]
Did I open it in the wrong way?

add this 
 <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>

add this
<repositories>

        <repository>
            <id>spring-milestone</id>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <url>http://repo.spring.io/milestone</url>
        </repository>

        <repository>
            <id>spring-snapshot</id>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>http://repo.spring.io/snapshot</url>
        </repository>

        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>

    </repositories>

ok  i am not found admin-server  

Do I need any other configuration?

**Comment by sbrannen** [comment]
Please contact the `spring-boot-admin` team for assistance with that project: https://github.com/codecentric/spring-boot-admin
