### ISSUE TITLE
Floating point conversion error with @Value

### ISSUE THREAD

**Issue by lanlystrong** [spring-projects/spring-framework#24079]
使用@Value解析配置文件的配置项时，数据转换错误；
例：配置文件中配置项：project.item.value=1234.5e1213453
当我们使用@Value(${project.item.value})接受参数时，spring默认先把1234.5e1213453当浮点型处理，这种情况导致数据内容超出浮点的范围时会放回invalid错误

**Comment by sbrannen** [comment]
Please submit issues in English.

If you need assistance, please use a translation tool such as Google Translate.

For example, Google Translate translates your issue description to the following.

> When using `@Value` to parse the configuration item of the configuration file, the data conversion error;
> Example: Configuration item in the configuration file: project.item.value = 1234.5e1213453
> When we use `@Value("${project.item.value}")` to accept parameters, spring first treats 1234.5e1213453 as a floating-point type by default. This situation causes the data content to return to the invalid error when it exceeds the floating-point range.

**Comment by sbrannen** [comment]
Can you please provide us more context regarding your use of `@Value`?

For example, what is the type of field/parameter on which you have declared `@Value`?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
