### ISSUE TITLE
Refine Throwable handling in spring-websocket

### ISSUE THREAD

**Issue by maczikasz** [spring-projects/spring-framework#24075]
https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-websocket/src/main/java/org/springframework/web/socket/handler/ExceptionWebSocketHandlerDecorator.java#L97

ExceptionWebSocketHandlerDecorator swallows all exceptions including OOM, I had a problem where all my apps went into zombie mode, because they did not crash with OOM as expected, because they were swallowed

**Comment by rstoyanchev** [comment]
The handling (and swallowing) of exceptions and closing the session is what the decorator was designed to do. We can however allow different treatment for `OutOfMemoryError` and allow that to propagate.

**Comment by maczikasz** [comment]
That would be awesome, my biggest problem is that spring automatically applies the decorator on every websocket connection in : org.springframework.web.socket.server.support.WebSocketHttpRequestHandler

and I did not see any elegant solution to disable this, without performing open hearth surgery using reflection

**Comment by rstoyanchev** [comment]
I've lowered Throwable handling to Exception in a number of places in spring-websocket including the decorator. I've also added a protected method to `WebSocketHttpRequestHandler` to allow overriding the decorators added.

**Comment by maczikasz** [comment]
Thank, you, will keep an eye out for the release
