### ISSUE TITLE
Data Access chapter 3.5.1 uses bad pattern

### ISSUE THREAD

**Issue by michael-o** [spring-projects/spring-framework#24084]
The Java sample code performs index-based operations on the `List` input with `int i`. This might incur a performance penalty depending on the list implementation of `O(n²)`. Lists are best acceessed with iterators. Don't use bad practices in samples.

**Comment by sbrannen** [comment]
Are you referring to the use of `actors.get(i)` in the `BatchPreparedStatementSetter` example?

If so, it's not possible to use an iterator there. The `setValues(...)` method is a callback that gets invoked multiple times by `JdbcTemplate.batchUpdate(String, BatchPreparedStatementSetter)`.

The only room for improvement that I see there is to store the result of `actors.get(i)` in a local variable.

**Comment by sbrannen** [comment]
> The only room for improvement that I see there is to store the result of `actors.get(i)` in a local variable.

I made that change in 52a1fc4329d6d97fb4a1e1832c74393dcc4f72e9.

**Comment by michael-o** [comment]
Yes, that is exactly what I mean. If you cannot substantially improve that, please a comment about the costs of that get operation.

**Comment by sbrannen** [comment]
While I certainly appreciate your focus on performance, we do not typically comment on performance considerations for Java collections or data structures within the Spring reference manual. Rather, we focus on how to use Spring and allow the reader to learn about Java elsewhere.

Having said that, if you are working with large data sets in your batch processing, you will likely benefit greater from the [Spring Batch project](https://spring.io/projects/spring-batch).
