### ISSUE TITLE
Data Access chapter 3.6.1 confuses with sample code

### ISSUE THREAD

**Issue by michael-o** [spring-projects/spring-framework#24085]
The Java sample code in that chapters used `SimpleJdbcInsert`, but still declares `JdbcTemplate` w/o any use. This is higly confusing to reader since the `SimpleJdbcInsert` is sold as an alternative to the former.

Please focus on the really used objects in sample code.

**Comment by sbrannen** [comment]
Good catch. I'll fix that.
