### ISSUE TITLE
Allow ExchangeStrategies customizations in WebClient

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#24106]
Backport of gh-23961

**Comment by spring-issuemaster** [comment]
Fixed via 43e047c523fefa1fc876208efd6946ceb2e472a3

**Comment by bclozel** [comment]
This change is breaking integrations with other projects. Reverting for now and rescheduling to another version.

**Comment by spring-issuemaster** [comment]
Fixed via 83683a13bbfbd6e9315605cc8e61b7ffb48abbf8
