### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by marco-ruiz** [spring-projects/spring-framework#24100]
The [Spring Cloud Function documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.0.RELEASE/reference/html/spring-cloud-function.html#_comparing_functional_with_traditional_bean_definitions) makes reference to an artifact named:

`spring-cloud-function-starter-web` 

instead of the real name of:

 `spring-cloud-starter-function-web`

**Comment by rstoyanchev** [comment]
This here is the Spring Framework. This issue belongs in [Spring Cloud Function](https://github.com/spring-cloud/spring-cloud-function/issues). Please, report it there.
