### ISSUE TITLE
XmlValidationModeDetector can't detect doctype when a comment follows the doctype declaration

### ISSUE THREAD

**Issue by gravin** [spring-projects/spring-framework#24129]
`XmlValidationModeDetector` can't detect doctype when has comment after doctype.

With XML like this, the comment is start after doctype line...

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd:/spring-beans.dtd"><!--to debug XmlValidationModeDetector detectValidationMode
second line
-->
```

... it will fail to detect DTD.

**Comment by sbrannen** [comment]
This appears to be a duplicate of #23605.

@gravin, which version of the Spring Framework are you using?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
