### ISSUE TITLE
ComponentScan excludeFilters via FilterType.REGEX does not work with escaping

### ISSUE THREAD

**Issue by jvs64893** [spring-projects/spring-framework#24133]
I tried to exclude an entire subpackage of my SpringBootApplication (Spring Boot Version 2.1.10.RELEASE) from component scan with annotations and values equivalent to this:

```
@SpringBootApplication
@ComponentScan(basePackages = "some.ba_se.package",
    excludeFilters = @Filter(type=FilterType.REGEX, pattern="some\\.ba_se\\.package\\.ignore\\..*"))
```

This does not exclude the some.ba_se.package.ignore package.

**Comment by jvs64893** [comment]
Nevermind, I've found a problem somewhere else that caused this.

**Comment by Sloloem** [comment]
@jvs64893 So what was the problem?
