### ISSUE TITLE
TOC generated by asciidoc for core-beans.adoc is truncated

### ISSUE THREAD

**Issue by Farteen** [spring-projects/spring-framework#24132]
**Affects:** 5.2.2.RELEASE
---

This is a trivial issue with table of contents which are generated by asciidoc. Look at the picture
I uploaded some tocs were missing. Last three days I had been reading the spring-framework-reference with previous RELEASE(maybe 5.1.9RELEASE). When I open the newest reference website, the missing happened.
![11575470056_ pic_hd](https://user-images.githubusercontent.com/5013543/70151290-5a360400-16e6-11ea-844c-1d06f049b8da.jpg)

I've been comparing the diff between previous RELEASE and 5.2.2 RELEASE, something wrong in
**core/core-beans.adoc**
![21575471072_ pic_hd](https://user-images.githubusercontent.com/5013543/70152672-9c604500-16e8-11ea-9d78-aa4fbb92ab2b.jpg)

After I delete the four equal marks which stand for Level 3 Section in asciidoc, and execute
` ./gradlew asciidoctor`
the reference generated in my computer has the complete tocs.
![31575471652_ pic_hd](https://user-images.githubusercontent.com/5013543/70153476-f7df0280-16e9-11ea-9b99-41227587b4d8.jpg)

**Comment by rstoyanchev** [comment]
It looks like there was a mismatched with a `====` at the end of a code sample and then an unbalanced `[NOTE]` a couple of paragraphs below, which made both go unnoticed for a while. Then a recent change in https://github.com/spring-projects/spring-framework/commit/55011e7a0fb92b3dbcc52da23bc28dfae5b2b6b0 fixed the `[NOTE]` which then exposed the other unbalanced marker.

**Comment by sbrannen** [comment]
I'm reopening this since the latest build snapshots display improper headings.

https://docs.spring.io/spring/docs/5.2.2.BUILD-SNAPSHOT/spring-framework-reference/core.html#beans-java-bean-annotation

**Comment by sbrannen** [comment]
Oops. That was a typo on my part. It's actually fixed in the `5.2.3` snapshot:

https://docs.spring.io/spring/docs/5.2.3.BUILD-SNAPSHOT/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers
