### ISSUE TITLE
XmlBeansMarshaller should be brought back, as Xmlbeans is unretired by Apache.

### ISSUE THREAD

**Issue by chirag519086** [spring-projects/spring-framework#24130]
XmlBeansMarshaller class was deperecated and removed because of retirement of Xmlbeans by Apache.

However, Xmlbeans is unretired and active development is also happening. 
Shouldn't Marshaller be reintroduced to support Xmlbeans ?

Update about Xmlbeans unretirement is published in below link.
http://xmlbeans.apache.org/news

**Comment by mdeinum** [comment]
Duplicate of #22403

**Comment by sbrannen** [comment]
Closing as a duplicate of #22403 which was declined.
