### ISSUE TITLE
Cannot override conversion service with custom one

### ISSUE THREAD

**Issue by michael-o** [spring-projects/spring-framework#24140]
Tried this on 5.0.x, 5.1.x, and 5.2.x.

I have a simple webapp for a REST API, WAR file, hosted on Tomcat. Root and webapp context as usual configured in `web.xml`.

I wrote a simple converter:

```java
@Component
public class RecordEtagConverter implements Converter<String, RecordEtag> {

	@Override
	public RecordEtag convert(String source) {

		if (source.startsWith("W/"))
			throw new IllegalArgumentException("weak ETags are not supported");

		if (!source.startsWith("\"") && !source.endsWith("\""))
			throw new IllegalArgumentException("ETag must be enclosed in double qoutes");



		return null;
	}

}
```

according to [chapter 3.4.5](https://docs.spring.io/spring/docs/5.2.0.RELEASE/spring-framework-reference/core.html#core-convert-Spring-config) I have added to my `servlet-context.xml`:

```xml
<beans:bean id="conversionService" class="org.springframework.format.support.FormattingConversionServiceFactoryBean"
		depends-on="recordEtagConverter">
	<beans:property name="converters">
		<beans:set>
			<beans:ref bean="recordEtagConverter" />
		</beans:set>
	</beans:property>
</beans:bean>
```` 

When I invoke the controller I only get converter not found, manually wiring `ConversionService` in my controller gives me:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'projectController': Unsatisfied dependency expressed through field 'conv'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.core.convert.ConversionService' available: expected single matching bean but found 2: org.springframework.format.support.FormattingConversionServiceFactoryBean#0,conversionService
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
```

This basically means that the default conversion service is not replaced. I have debugged the `TypeConverterDelegate` and my custom converter does not even appear with the `PropertyEditor`. I have also moved the conversion service bean to the root context. Same effect.

**Comment by michael-o** [comment]
It turns out that documentation could be better here, based on this [SO question](https://stackoverflow.com/q/13971279/696632) it requires a bit more [config](https://docs.spring.io/spring/docs/5.2.0.RELEASE/spring-framework-reference/web.html#mvc-config-conversion).

The regular user will stop at the core documentation. Feel free to close or change the documentation to avoid pitfalls like this.

**Comment by rstoyanchev** [comment]
The Spring Type Conversion section in the core documentation does have the following:

> It is also common to use a ConversionService within a Spring MVC application. See [Conversion and Formatting](https://docs.spring.io/spring/docs/5.2.0.RELEASE/spring-framework-reference/web.html#mvc-config-conversion) in the Spring MVC chapter.

Also in the core documentation, the next section on Spring Field Formatting, has a [similar reference](https://docs.spring.io/spring/docs/5.2.0.RELEASE/spring-framework-reference/core.html#format-configuring-formatting-mvc) to Spring MVC as well.

**Comment by michael-o** [comment]
@rstoyanchev My bad, thank you. The docs were just overwhelming. It works like a charms now.
