### ISSUE TITLE
ExtendedBeanInfo#isCandidateWriteMethod is wrong?

### ISSUE THREAD

**Issue by qianpingmao** [spring-projects/spring-framework#24149]
```java
public static boolean isCandidateWriteMethod(Method method) {
		String methodName = method.getName();
		int nParams = method.getParameterCount();
		return (methodName.length() > 3 && methodName.startsWith("set") && Modifier.isPublic(method.getModifiers()) &&
				(!void.class.isAssignableFrom(method.getReturnType()) || Modifier.isStatic(method.getModifiers())) &&
				(nParams == 1 || (nParams == 2 && int.class == method.getParameterTypes()[0])));
	}
```

This method is from `ExtendedBeanInfo`. I think it determines whether the method is 'set' method. But `!void.class.isAssignableFrom(method.getReturnType()` is wrong?

**Comment by sbrannen** [comment]
No, it is correct, as stated by the class-level Javadoc:

> Decorator for a standard `BeanInfo` object, e.g. as created by `Introspector.getBeanInfo(Class)`, designed to discover and register static and/or non-void returning setter methods.
