### ISSUE TITLE
Add "application/*+xml" as supported media type to XML decoders

### ISSUE THREAD

**Issue by Chr3is** [spring-projects/spring-framework#24164]
The `Jackson2JsonDecoder` supports own media types out of the box because it accepts `application/*+json` by default. The same does not work with xml (`Jaxb2XmlDecoder`). If you want to handle a xml response (with an own mediatype eg `application/my.type+xml`) with the spring webclient you'll get an error because no decoder can be found. You have to manually extend the `Jaxb2XmlDecoder` and let him accept any xml mediatype through the constructor and register this new decoder in the webclient. I think the Jackson and Jaxb decoder should behave the same way.

**Comment by rstoyanchev** [comment]
Indeed, looking at the `HttpMessageConverter` equivalents, all of them do have this.
