### ISSUE TITLE
spring.io site document display issue

### ISSUE THREAD

**Issue by doggerFrankXu** [spring-projects/spring-framework#24161]
**Affects:** current

there is something wrong in this document.
docs.spring.io/spring-framework/docs/current/spring-framework-reference/core.html

From somewhere the markdown grammar cannot be parsed. The categories on left panel only contains link before .1.9.4.
it is displaying raw string, ==== Receiving Lifecycle Callbacks, rather than rendered markdown title.
However the document in previous version displays well.
[link](https://docs.spring.io/spring/docs/5.1.12.RELEASE/spring-framework-reference/core.html#spring-core)

I am not sure if this is the right place to raise the issue. If not, could help guide me to the right one?

---

**Comment by snicoll** [comment]
Thanks for the report (yes, this was the right place). 

We've already fixed it, see [the doc for 5.2.3 snapshots](https://docs.spring.io/spring/docs/5.2.3.BUILD-SNAPSHOT/spring-framework-reference/core.html#beans-java-lifecycle-callbacks).
