### ISSUE TITLE
MethodValidationPostProcessor conflict with Scheduler 

### ISSUE THREAD

**Issue by Zheaoli** [spring-projects/spring-framework#24165]
I use the Spring Boot v2.0.5.RELEASE which depends on Spring 5.0.9 Release 

I got a problem when I need both `MethodValidationPostProcessor` and  `Scheduled`

here's the detail.

When I just use `Scheduled` like below 

```java
@SpringBootApplication
@EnableConfigServer
@EnableScheduling
public class SpringConfigServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringConfigServerApplication.class, args);
    }

    @Scheduled(fixedDelay = 5000)
    public void test() {
        System.out.println("Demo");
    }
}
```

the scheduler works well as what I want. But when I add a MethodValidationPostProcessor like below

```java
@SpringBootApplication
@EnableConfigServer
@EnableScheduling
public class SpringConfigServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringConfigServerApplication.class, args);
    }

    @Bean
    public MethodValidationPostProcessor methodValidationPostProcessor() {
        MethodValidationPostProcessor methodValidationPostProcessor = new MethodValidationPostProcessor();
        methodValidationPostProcessor.setProxyTargetClass(true);
        return methodValidationPostProcessor;
    }

    @Scheduled(fixedDelay = 5000)
    public void test() {
        System.out.println("Demo");
    }
}
```

the scheduler doesn't work. I have already checked the `org.springframework.scheduling.config.ScheduledTaskRegistrar`, the scheduler inits as well, but there isn't any task in all of the task variables such as `fixedRateTasks`, `fixedDelayTasks` and etc.

Is there any chance that we can use MethodValidationPostProcessor and the scheduler together?

**Comment by snicoll** [comment]
@Zheaoli the post-processor method should be static to prevent early initialization of the whole chain. You also should have a message in the log stating that some beans couldn't be post-processed. This is the reason why scheduling doesn't work with such arrangement. If moving it to static doesn't fix the problem, please share a small sample (zip or github repo) we can run ourselves and we can reconsider.

**Comment by Zheaoli** [comment]
Your suggestion is working! thanks! BTW, is there any chance to add a tips in documentation?  I think this chain make many people confuse
