### ISSUE TITLE
Upgrade to Kotlin 1.4 RC

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#24171]
A placeholder ticket for upgrading to Kotlin 1.4 in our Spring Framework 5.3 timeframe.

**Comment by sdeleuze** [comment]
[Kotlin 1.4 M1](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-4-m1-released/) has just been released.

**Comment by sdeleuze** [comment]
[Kotlin 1.4 M2](https://blog.jetbrains.com/kotlin/2020/06/kotlin-1-4-m2-released/) has just been released, I am doing tests with it before pushing this upgrade.

It is interesting to notice the addition of [explicit API mode](https://blog.jetbrains.com/kotlin/2020/06/kotlin-1-4-m2-released/#explicit-api-mode). We could maybe leverage it.

**Comment by sdeleuze** [comment]
I am currently blocked by a Kotlin compiler dependency to Coroutines (via the scripting support) which seems to be a kind of circular dependency that causes issue in Gradle dependency resolution in BOM handling. I am waiting a feedback from Kotlin team.
