### ISSUE TITLE
Deprecate use of path matching and content negotiation via path extension

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#24179]
The motivation for this has been described in the ["Suffix Match"](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-requestmapping-suffix-pattern-match) section of the reference docs for some time. This issue is about formally deprecating options for the use of path extensions for path matching and content negotiation.

When you have to consider all of the below together -- path patterns and URI variables, URL encoding (and double encoding tricks), path parameters ";"  and their treatment (or mistreatment) by frameworks and servers, relative paths `"../"`, the need for alignment between security and web framework path matching -- it is not surprising that incidental complexity makes it difficult to reason about potential attacks such as described in ["Suffix Match and RFD"](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-requestmapping-rfd) section of the reference docs. This is what makes path matching and content negotiation via path extensions an anti-pattern.

The preferred options should be to use the `Accept` header for content negotiation and `@RequestMapping(produces="...")` for path matching. These are and have been the defaults in Spring Boot auto-configuration. If a replacement for content negotiation via path extensions is needed, then using a query parameter should be preferred.

In 5.3, suffix pattern matching will be turned off by default, see https://github.com/spring-projects/spring-framework/issues/23915#issuecomment-563987147 for details.

**Comment by kev22257** [comment]
Currently we are setting PathMatchConfigurer.setUseSuffixPatternMatch to false.  How do we advance beyond Spring 5.2.3 without a deprecated warning and keep the functionality the same?  Do we have to wait for Spring 5.3 when this will presumably be the default?

**Comment by kev22257** [comment]
> Currently we are setting PathMatchConfigurer.setUseSuffixPatternMatch to false. How do we advance beyond Spring 5.2.3 without a deprecated warning and keep the functionality the same? Do we have to wait for Spring 5.3 when this will presumably be the default?
> 
> If that is true would it be possible to bridge the gap with a new method like disableUseSuffixPatternMatch() that explicitly sets the value to false without causing the warning considering GA for Spring 5.3 I think I saw was October 2020?

Never mind, I found the conversation you had in #24642.
