### ISSUE TITLE
Exposes local address in reactive ServerHttpRequest

### ISSUE THREAD

**Issue by bilak** [spring-projects/spring-framework#24174]
Hello,
is there any way how to obtain localAddr from incoming request? I mean if I have multiple virtual addresses/interfaces on host and I need to distinguish on which address was the request accepted.

Only way which I found now is little hack with netty's HttpServerRequest.

```
if ((((AbstractServerHttpRequest) exchange.getRequest()).getNativeRequest()) instanceof HttpServerRequest) {
    final InetSocketAddress localAddress = ((HttpServerRequest) (((AbstractServerHttpRequest) exchange.getRequest()).getNativeRequest())).hostAddress();
    logger.debug("!!! Hostname {}, HostString {}, Address {}",
            localAddress.getHostName(),
            localAddress.getHostString(),
            localAddress.getAddress()
    );
}
```

Is there any general approach?

Thanks

**Comment by rstoyanchev** [comment]
We already have `getRemoteAddress` in `ServerHttpRequest` and can add `getLocalAddress` next to that. By comparison the non-reactive `ServerHttpRequest` has both.

**Comment by bilak** [comment]
Yes that's the case. I was initially looking at non-reactive `ServerHttpRequest` so I was confused where can I get `localAddress`.
Just linking here [this](https://github.com/spring-cloud/spring-cloud-gateway/issues/1463) issue for reference.
