### ISSUE TITLE
HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header … Invalid token character ':' in token "http://www.wapforum.org/xhtml"

### ISSUE THREAD

**Issue by mixcloud-downloader** [spring-projects/spring-framework#24183]
**Affects:** 5.2.2

When doing this request:

    $ ACCEPT='application/xhtml+xml; profile=http://www.wapforum.org/xhtml, application/vnd.wap.xhtml+xml, application/vnd.wap.wmlc, application/vnd.wap.wmlscripc, text/vnd.wap.wml, image/vnd.wap.wbmp, image/gif, image/bmp, audio/amr, audio/imelody, audio/midi, audio/wav, application/vnd.wap.wtls-ca-certifiate, application/x-x509-ca-cert, application/vnd.wap.hashed-certificate, application/vnd.wap.signed-certificate, */*, text/html'
    $ curl -vH "Accept: $ACCEPT" localhost:8080/anything

Spring responses with a 406 and logs this warning:

> DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header [application/xhtml+xml; profile=http://www.wapforum.org/xhtml, application/vnd.wap.xhtml+xml, application/vnd.wap.wmlc, application/vnd.wap.wmlscriptc, text/vnd.wap.wml, image/vnd.wap.wbmp, image/gif, image/bmp, audio/amr, audio/imelody, audio/midi, audio/wav, application/vnd.wap.wtls-ca-certificate, application/x-x509-ca-cert, application/vnd.wap.hashed-certificate, application/vnd.wap.signed-certificate, */*, text/html]: Invalid mime type "application/xhtml+xml; profile=http://www.wapforum.org/xhtml": Invalid token character ':' in token "http://www.wapforum.org/xhtml"]

**Comment by rstoyanchev** [comment]
[RFC 7231, 5.3.2](]https://tools.ietf.org/html/rfc7231#section-5.3.2) defines parameter values as token or quoted string which is defined in [RFC 7230, 3.2.6](https://tools.ietf.org/html/rfc7230#section-3.2.6). This is implemented In [MimeType.TOKEN](https://github.com/spring-projects/spring-framework/blob/6e21b19999e967e4f4933bfda10b7a85206def34/spring-core/src/main/java/org/springframework/util/MimeType.java#L62). Specifically "any VCHAR, except delimiters" where ":" is a delimiter.

Quoting the value makes it work:
```
application/xhtml+xml; profile="http://www.wapforum.org/xhtml"
```

**Comment by mixcloud-downloader** [comment]
Well, this doesn't really help those guys with the broken client out there. This happens frequently enough on a real traffic site that it has my attention. It is fine that you don't want to tolerate that, but how can I disable this behavior of the framework (Spring) and present something useful to those poor users?

**Comment by rstoyanchev** [comment]
I'm not sure there is anything we can do to "disable this behavior". We can't parse the Accept header and therefore can't produce the correct response. Unless we somehow altered the header, e.g. to remove troublesome parameters, but I don't see how we could do that and not run into some other kind of trouble.

> this doesn't really help those guys with the broken client out there

The 406 status does communicate that there is an issue with the requested content type. If you want a more helpful error message in the response body, you'll have to add some error handling for this scenario, in addition also checking if the Accept header can be parsed with `MediaType#parseMediaTypes`.

**Comment by mixcloud-downloader** [comment]
> The 406 status does communicate that there is an issue with the requested content type.

I don't know those guys, but from the accept header, I have a pretty good idea that this is users with an old mobile phone. A 406 doesn't communicate nothing to them. Also they can't just simply update their client. To your surprise, I don't even want them to see an error page because I have a very good understanding what they would like to see, namely an html page. Unfortunately this behavior is wired very deep into the framework, and I fail to see how I could disable this.

**Comment by rstoyanchev** [comment]
Quite on the contrary. It is very much our philosophy wherever possible to be lenient when it comes to dealing with input. There are many examples of that. In this case however, I simply don't see how to recover from an Accept header we cannot parse. 

As a framework we cannot ignore the Accept header if it can't be parsed. If we ignored it and proceeded as if there wasn't one, i.e. `*/*`, it likely we would produce other errors, and in any case other applications could legitimately have completely different context and expectations than yours for how to handle this.

As an application however, you can choose to deal with problematic Accept headers in a way that you see fit, for example through a filter. 

Or do you have a specific algorithm you'd like to suggest for how re-parse the Accept header more leniently? Again I'm very open to suggestions. All I'm saying is I don't see any alternatives.
