### ISSUE TITLE
import spring-framework5.1.x to Idea

### ISSUE THREAD

**Issue by Ifdevil** [spring-projects/spring-framework#24193]
**Affects:** \<Spring Framework version> 5.1.x
 \<java version> 1.8.0_25
 \<gradle version> 4.9

spring-framework-5.1.x\spring-beans\src\main\java\org\springframework\beans\support\PropertyComparator.java:138: error：Incompatible types: PropertyComparator<CAP#1>Cannot be converted toComparator<? super CAP#1>
			source.sort(new PropertyComparator<>(sortDefinition));
			            ^
  Where CAP # 1 is a new type variable:
    CAP # 1 capture extension object from?
Note: Some messages have been simplified; use -Xdiags: verbose to recompile for full output

---

**Comment by rstoyanchev** [comment]
Please try with more recent [Java version](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot) and Gradle to match [the one used](https://github.com/spring-projects/spring-framework/blob/09b6730f3d89b55819ea9bea66314269b7cc4fd9/gradle/wrapper/gradle-wrapper.properties#L3) in the framework.

**Comment by rstoyanchev** [comment]
Please try with more recent [Java version](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot) and Gradle to match [the one used](https://github.com/spring-projects/spring-framework/blob/09b6730f3d89b55819ea9bea66314269b7cc4fd9/gradle/wrapper/gradle-wrapper.properties#L3) in the framework.

**Comment by Ifdevil** [comment]
> Please try with more recent [Java version](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot) and Gradle to match [the one used](https://github.com/spring-projects/spring-framework/blob/09b6730f3d89b55819ea9bea66314269b7cc4fd9/gradle/wrapper/gradle-wrapper.properties#L3) in the framework.

I have tested with jdk12 and gradle5.6.4 (default)，but the same error，very strange

**Comment by Ifdevil** [comment]
I changed a computer，no this error，it's my fault，maybe my local env problem
