### ISSUE TITLE
Regression: tracing context lost with WebTestClient

### ISSUE THREAD

**Issue by beltram** [spring-projects/spring-framework#24191]
Hi,
Once using Sleuth and injecting Tracing headers in a WebTestClient I was able to retrieve them in Reactor's context later on like this :
```kotlin
// Test
webTestClient.get()
    .uri("/api/tracing")
    .header("X-B3-TraceId", "463ac35c9f6413ad48485a3953bb6124")
    .header("X-B3-SpanId", "a2fb4a1d1a96d312")

// Controller
@GetMapping
    fun spanId(): Mono<String> {
        return Mono.subscriberContext()
                .filter { it.hasKey(Span::class.java) }
                .map { it[Span::class.java].context() }
                .map { it.spanIdString() }
    }
```

This worked with spring-test 5.2.1.RELEASE but no longer with 5.2.2.RELEASE.  

What happens is that a new Span is created [here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L186) because Context lacks original Span.  

I think root cause comes from [this commit](https://github.com/spring-projects/spring-framework/commit/5d2fc2fc32a73f2250addac1404ae3b8df309736#diff-03c4d94a51354f90b067904bc25811d4) or [this one](https://github.com/spring-projects/spring-framework/commit/21b2fc1f0129420a8da521cd1e7f33f19beffbc1#diff-03c4d94a51354f90b067904bc25811d4) in [HttpHandlerConnector](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/web/reactive/server/HttpHandlerConnector.java).

I've setup a reproducer [here](https://github.com/beltram/spring-test-sleuth-reproducer). Thank you 😄 

Affects: Spring Framework 5.2.2.RELEASE

**Comment by rstoyanchev** [comment]
Even though the changes from #23936 clearly have this effect, that doesn't mean the root cause is in the Spring Framework. I don't see anything in our changes that should problematic and I'm not familiar enough with how Sleuth is implemented to be able to debug the issue.

So please create re-open this against Sleuth and please link the two. I'm quite happy to follow and help figure out what the issue is.
