### ISSUE TITLE
Upgrade to Groovy 3.0

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#24215]
Groovy 3.0 is currently in RC3 and certainly going GA in our 5.3 timeframe. While it seems to be compatible for our purposes and therefore a seamless upgrade from Groovy 2.5 for Spring users, let's see whether there are specific things we can do towards making Groovy 3 a first-class citizen.

**Comment by sbrannen** [comment]
Reopening due to broken build: https://build.spring.io/browse/SPR-PUBM-791
