### ISSUE TITLE
Incomplete table of content in spring core reference doc

### ISSUE THREAD

**Issue by JohnWu-Pro** [spring-projects/spring-framework#24227]
**Affects:** 5.2.2-RELEASE

---

In the [spring core reference doc](https://docs.spring.io/spring/docs/5.2.2.RELEASE/spring-framework-reference/core.html#spring-core), the table of content shows only one chapter: "1. The IoC Container", all other chapters are not listed. All content seems visible though.

**Comment by rstoyanchev** [comment]
This was already reported and fixed in #24132, but the target release 24132 is not out yet.
