### ISSUE TITLE
Support JAX-RS annotations for REST controllers

### ISSUE THREAD

**Issue by rolaca11** [spring-projects/spring-framework#24242]
I'm putting together a project, where the different modules communicate via REST.

Not all of the modules use Spring, so I decided to use JAX-RS instead.

The way I'm making sure that all modules are on the same page when it comes to REST resources is that I created an interface, with DTO classes, annotated them with the typical JAX-RS annotations and put them into a maven depedency that both sides can depend on.

This got me the idea, that Spring could use a functionality, where these annotations are recognized and made into either a proxy in case of a Rest client, or when implementing an interface, these annotations could substitute `@RequestMapping` and similar annotations.

To my knowledge, Spring has most of the functionalities needed to implement this feature with the potential of a great, spring-independent way of sharing common rest resources.

**Comment by andrei-ivanov** [comment]
But why not use Jersey + Spring?

**Comment by rolaca11** [comment]
I blatantly overlooked this option. It sounds great and is so obvious. Thank you for the reminder.
