### ISSUE TITLE
branch 3.2.x cant compile

### ISSUE THREAD

**Issue by gravin** [spring-projects/spring-framework#24246]
:spring-orm-hibernate4:processResources UP-TO-DATE
:spring-orm-hibernate4:classes
:spring-orm:jar
:spring-aspects:compileJava
[ant:iajc] E:\src\spring-framework\spring-aspects\src\main\java\org\springframework\beans\factory\aspectj\AbstractBeanConfigurerAspect.aj:1 [error] The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
[ant:iajc] (no source information available)
[ant:iajc] E:\src\spring-framework\spring-aspects\src\main\java\org\springframework\mock\staticmock\AbstractMethodMockingControl.aj:1 [error] The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files
[ant:iajc] (no source information available)
[ant:iajc] E:\src\spring-framework\spring-aspects\src\main\java\org\springframework\mock\staticmock\AbstractMethodMockingControl.aj:19 [error] The import java.util.Arrays cannot be resolved
[ant:iajc] import java.util.Arrays;
[ant:iajc]        ^^^^^^^^^^^^^^^
[ant:iajc] E:\src\spring-framework\spring-aspects\src\main\java\org\springframework\mock\staticmock\AbstractMethodMockingControl.aj:103 [error] Arrays cannot be resolved
[ant:iajc] if (!Arrays.equals(this.args, args)) {
[ant:iajc]      ^
[ant:iajc] 
[ant:iajc] 4 errors
:spring-aspects:compileJava FAILED

FAILURE: Build failed with an exception.

**Comment by gravin** [comment]
used jdk 1.8 to compile,  change Jibx to 1.3.1, then can compile use the command gradlew :spring-oxm:compileTestJava cleanIdea idea

**Comment by snicoll** [comment]
@gravin for the record, 3.2.x is no longer supported anymore (December 2016, that’s almost 3 years!).

**Comment by airblock** [comment]
have you solved this problem ?

**Comment by airblock** [comment]
i have exactly same problem , and found no solution
