### ISSUE TITLE
unused LogFactory.getLog

### ISSUE THREAD

**Issue by pandening** [spring-projects/spring-framework#24259]
I think the follow code should be deleted:

```java
	
     protected final Log logger = LogFactory.getLog(getClass());

```

Any logger should be defined like this : 

```java

private static final Logger logger = LoggerFactor.getLogger(ClassName);

```

===============================
https://github.com/spring-projects/spring-framework/blob/9c17eb59a4312a9787b23ebaea3bff6e95f3657c/spring-webflux/src/main/java/org/springframework/web/reactive/result/condition/AbstractMediaTypeExpression.java#L38

**Comment by snicoll** [comment]
Thanks for the suggestion but it is non-static so that concrete classes get a logger with their name. Doing what you suggest means that logs from all subclasses would be emitted with `AbstractMediaTypeExpression`. Using such pattern is quite common in the framework.

**Comment by pandening** [comment]
I still think the define should be removed, since the code will cause cpu-hotspot with call  'getClass()' , the logger should define as ‘static final’ in concrete classes   ... |>.>| ....

**Comment by snicoll** [comment]
>  since the code will cause cpu-hotspot with call 'getClass()'

Do you have concrete CPU profiling that shows `getClass()` is actually a hotspot.

> the logger should define as ‘static final’ in concrete classes

Even that was a problem and we did that, that wouldn't save the per-instance instantiation in the parent and would be more harmful than anything else.
