### ISSUE TITLE
ConstructorResolver.resolveConstructorArguments calculates minNrOfArgs

### ISSUE THREAD

**Issue by gravin** [spring-projects/spring-framework#24258]
for (Map.Entry<Integer, ConstructorArgumentValues.ValueHolder> entry : cargs.getIndexedArgumentValues().entrySet()) {
			int index = entry.getKey();
			if (index < 0) {
				throw new BeanCreationException(mbd.getResourceDescription(), beanName,
						"Invalid constructor argument index: " + index);
			}
			if (index > minNrOfArgs) {
				minNrOfArgs = index + 1;
			}

for this part, looks should be index >= minNrOfArgs
because index starts from 0, if found a index is 5, can guess the minNrOfArgs at least 6, so if current minNrOfArgs is 5, when found a 5 index, the minNrOfArgs should be adjusted to 6.

**Comment by snicoll** [comment]
@gravin if you believe you've found a bug, please share a small sample that demonstrates the problem. I personally don't see a problem has one is an index and the other one is a size, so it's off-by-one by definition.

**Comment by gravin** [comment]
currently when config constructor-args, need specify all args, cant omit some.
so will not be a bug.  just below config is invalid.
    <bean id="exampleBean" class="examples.ExampleBean" autowire="constructor">
        <constructor-arg index="0" value="75"/>
        <constructor-arg index="2" value="42"/>
    </bean>
