### ISSUE TITLE
Support fetching Request/Reponse Body in Webflux's ExchangeFilterFunction.ofRequestProcessor/ofResponseProcessor - Required for logging purpose

### ISSUE THREAD

**Issue by ashoke-cube** [spring-projects/spring-framework#24262]
**Affects:** 
Spring Framework : 5.2.1.RELEASE
Spring Boot : 2.1.5.RELEASE

Added ExchangeFilterFunction to WebClient which logs request and response but while logging, there is no handle to get the request/response body as a string or JSON. 

	public static ExchangeFilterFunction logRequest() {
		return ExchangeFilterFunction.ofRequestProcessor(clientRequest -> {
                 //body
                 logger.debug(clientRequest.body()); //-> This returns BodyInserter<?, ? super ClientHttpRequest>, need to fetch the body as a String/JSON.
                 return Mono.just(clientRequest);
                 }
    }

**Comment by ashoke-cube** [comment]
Thank you for the response. I have a query on the writeWith() implementation. I have the following implementation as opposed to your suggestion.

Does the below implementation wait for the full body content before logging? Or it logs as and when the data is available? I would like the full body to be available before logging. If that is needed should I follow your way of _joining_ the body?

```
	@Override
	public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
		return super.writeWith(Flux.from(body).map(writeToLog()));
	}

        	private Function<DataBuffer, DataBuffer> writeToLog() {
		return dataBuffer -> {
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			try {
				Channels.newChannel(baos).write(dataBuffer.asByteBuffer().asReadOnlyBuffer());
				logResponse(baos.toString());
			} catch (IOException e) {
				LOGGER.error("Unable to log input response due to an error", e);
			} finally {
				try {
					baos.close();
				} catch (IOException e) {
					LOGGER.error("Unable to log input response due to an error", e);
				}
			}
			return dataBuffer;
		};
	}
```

**Comment by rstoyanchev** [comment]
Yes that should be fine. Generally, when decoding input you can't reliably turn chunks into String since you might have split (multi-)character issues. However, that shouldn't be an issue when encoding output since the Encoder would not split characters like that.

Note that as of 5.2, `DatBuffer` has a `toString()` so you could simplify to:

```java
private Function<DataBuffer, DataBuffer> writeToLog() {
	return dataBuffer -> {
		log(dataBuffer.toString(StandardCharsets.UTF_8));
		return dataBuffer;
	};
}
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by toxakktl** [comment]
@Override
    public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
        Mono<DataBuffer> buffer = Mono.from(body);
        return super.writeWith(buffer.doOnNext(dataBuffer -> {
            try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                Channels.newChannel(baos).write(dataBuffer.asByteBuffer().asReadOnlyBuffer());
                Instant now = Instant.now();
                String encodedSign = SignUtil.signRequest(now, baos.toByteArray());
                super.getHeaders().set("testHeader", encodedSign);
            } catch (Exception e) {
                e.printStackTrace();
                throw new BlackboxResponseFilterException("Error applying filter to response");
            }
        }));
    }

I am trying to set custom header, but super.getHeaders() returns empty result and they are read only, how can I set headers ? 
Here is how I set connector
HttpClient client = HttpClient.create();
//do some ssl stuff with client
ReactorClientHttpConnector connector = new ReactorClientHttpConnector(client);
        return WebClient.builder().clientConnector(new SignClientHttpConnectorDecorator(connector)).build();
