### ISSUE TITLE
Make BeanUtils copyProperties able to copy Immutable, Mutable and Mixed Java Bean

### ISSUE THREAD

**Issue by fborriello** [spring-projects/spring-framework#24267]
### Description

the `copyProperties` method in the `BeanUtils` class, is able to copy only public properties or the ones with a public setter method.
it would be really useful if this functionality can be extended in order to copy any kind of Java Bean: **Mutable**, **Immutable**, **Mixed**.

### Solution 

Evaluate the possibility to use, behind the scenes, an open-source library that is able to copy Mutable, Immutable and Mixed Java Bean. 
A good library that meets the above requirements is [BULL](https://github.com/HotelsDotCom/bull).
This library has already been adopted by huge IT companies in their project.
This would also make able to copy nested objects.

### More details about BULL

- DZone: [How to Transform Any Type of Java Bean With BULL](https://dzone.com/articles/how-to-transform-any-type-of-java-bean-with-one-li)
 - InfoQ: [How Expedia Is Getting Rid of Java Bean Transformers](https://www.infoq.com/articles/expedia-rid-of-bean-transformers/) [[EN](https://www.infoq.com/articles/expedia-rid-of-bean-transformers/)] [[PT-BR](https://www.infoq.com/br/articles/expedia-rid-of-bean-transformers/)]

**Comment by sbrannen** [comment]
Superseded by #24268
