### ISSUE TITLE
Issue with uri Variable in RestTemplate.exchange method

### ISSUE THREAD

**Issue by manish-birdeye** [spring-projects/spring-framework#24264]
**Affects:** 5.0.6.RELEASE

---

I am using spring-web version 5.0.6.RELEASE.

I tried calling the GET exchange method with the URI variable map, but these URI variables are not set to the final URL which hit the external system.

My code snippet is as below

```
Map<String,Object> queryParam =  new HashMap<>();
queryParam.put("id", 1);
queryParam.put("name", "ABC");
ResponseEntity<List<MyResponse>> responseEntity = restTemplate.exchange(serverUrl.toString(),HttpMethod.GET,null,
                        new ParameterizedTypeReference<List<MyResponse>>(){}, queryParam);
```
When I debugged , I found RestTemplate.execute method have a URI creation code `URI expanded = getUriTemplateHandler().expand(url, uriVariables);` which does not set the URI params to `URI` class.

I further debugged and found that in `DefaultUriBuilderFactory.build()` method the URI variable is not passed or set to URI component builder

`UriComponents uriComponents = this.uriComponentsBuilder.build().expand(uriVars);` which causes `HierarchicalUriComponents expandInternal(UriTemplateVariables uriVariables)` method of `HierarchicalUriComponents` class to set the URI variable as empty.

This seems to be an issue, can anyone check this? 
Raised the same on StackOverflow, but did not receive any response.
[StackOverflow link](https://stackoverflow.com/questions/59456693/issue-with-urivariable-in-resttemplate-exchange-method)
Thanks.

**Comment by snicoll** [comment]
Let's keep the conversation on StackOverflow for now as it looks like a usage problem at first glance. We can reopen if it turned out not to be the case.
