### ISSUE TITLE
MockMVC is not triggering Javax.Constraint.Validation for List of Objects

### ISSUE THREAD

**Issue by SumithraPrasad** [spring-projects/spring-framework#24260]
```
@RestController
@Validated
@Slf4j
public class TestController {

  @PostMapping(value = "/v1/test", produces = "application/json", consumes = "application/json")
  @ResponseStatus(HttpStatus.CREATED)
  public void postTest(@Valid @RequestBody List<TestDTO> testList) {
  }
}
```

MockMVC is not throwing BadRequest but when service is hit from postman we get BadRequest

**Comment by snicoll** [comment]
Duplicate of #16917

**Comment by SumithraPrasad** [comment]
@snicoll Its not working for mockmvc when parameter is of type List, it works from postman but from mockmvc its not working

**Comment by snicoll** [comment]
The linked issue I've referenced does seem to indicate otherwise and I can see you've added a comment there anyway.
