### ISSUE TITLE
Mongo Conditional Aggregation Expression: thenValueOf(field) does not append "$" to field reference 

### ISSUE THREAD

**Issue by andoneN4** [spring-projects/spring-framework#24275]
Version: Srping boot 2.1.5.RELEASE
I tried this: 

AggregationExpression someBool = Gt.valueOf(someField).greaterThanValue(0);
		Cond cond = ConditionalOperators.when(someBool)
				.thenValueOf(fieldRef1)
				.otherwiseValueOf(fieldRef2);

This produces the following query: 

"$cond": {
                                    "if": {
                                        "$gt": [
                                            "$someField",
                                             0
                                        ]
                                    },
                                    "then": "fieldRef1",
                                    "else": "$fieldRef2"
                                }

But the "then" clause should be : "then": "$fieldRef1". I assume the missing $ is a bug.

best wishes

**Comment by snicoll** [comment]
@andoneN4 I am not sure I got that but this issue tracker is for the Spring Framework only. It looks like you're trying to report an issue against Spring Data MongoDB. Their issue tracker [is on Jira](https://jira.spring.io/projects/DATAMONGO/issues). Before creating an issue there, please consider creating a small sample (zip or github repo) that the team can use to reproduce the problem. Thank you.
