### ISSUE TITLE
“Vary” headers for eot fonts with Spring 5.2 causes cache problems with IE9

### ISSUE THREAD

**Issue by MAJNaber** [spring-projects/spring-framework#24280]
Since Spring 5.2 the [Cors][1] [Handling][2] is changed, if the request is not a cors request. This impacts the loading of the fonts in IE9. Caching fonts in combination with IE9 is [kind of unstable][3]. Adding the the "Vary" headers on the fonts breaks the loading of the fonts after a reload of the page.

Best option is that visitors don't use IE 9 anymore, but I'm afraid I can't force that. It would be fine if this impacts only the font type. Unfortunately also some icons are loaded with a font, so this impacts functionality on some pages. 

  [1]: https://github.com/spring-projects/spring-framework/issues/22273
  [2]: https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-52
  [3]: https://stackoverflow.com/questions/13415073/on-ie-css-font-face-works-only-when-navigating-through-inner-links

**Comment by sdeleuze** [comment]
Hi, as described in the related issue, these changes have been done on purpose and I am afraid this IE9 bug is not something we should handle on Spring Framework side. Notice that IE9 is unsupported  since 1/12/16 and that [Microsoft itself recommends upgrading](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support). You can maybe write a filter to implement the behavior you need.

**Comment by MAJNaber** [comment]
I reproduced the same problem with IE 11, which is still supported by microsoft

**Comment by sdeleuze** [comment]
Then I guess Microsoft should fix this bug even if the reporting process is not clear to me.

**Comment by sdeleuze** [comment]
As hinted before, you should be able to write a filter or an interceptor which, based on the user-agent, removes the `Vary` headers for Internet Explorer.

**Comment by MAJNaber** [comment]
I fixed it with added the ShallowEtagHeaderFilter for fonts (but it is probably better to do this only it for Internet Explorer)
