### ISSUE TITLE
Broken guide : Accessing data with MySQL in spring.io

### ISSUE THREAD

**Issue by jimsar** [spring-projects/spring-framework#24294]
**I import project "complete" from "Accessing data with MySQL" in Android Studio and everything looks fine. But when i close the project and open it again, i take the following error message:**

APPLICATION FAILED TO START

Description:
**Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class**
Action:
Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**What is wrong with this project. It should be a running guide.** https://spring.io/guides/gs/accessing-data-mysql/

**Comment by bclozel** [comment]
Please use the dedicated repository for issues. Thanks!
https://github.com/spring-guides/gs-accessing-data-mysql/issues
