### ISSUE TITLE
CoroutinesUtils not found

### ISSUE THREAD

**Issue by shouwangqing** [spring-projects/spring-framework#24296]
my spring version is 5.2.2.RELEASE, and work in eclipse 4.8 of windows10。 when I import the source into eclipse by reading import-into-eclipse.md. 
it have errors in spring-core, spring-messaging, spring-webflux that cannot find CoroutinesUtils。 but I have found the module kotlin-coroutines in spring-core and it has been compile。 while does itCoroutinesUtils couldn't found

**Comment by sbrannen** [comment]
Do you have Buildship installed in Eclipse?

Also, did you follow the instructions step-by-step?

In any case, the instructions have been tested against Spring Tools 4.3.2 which is based on Eclipse 4.12. So we don't guarantee that the instructions work for Eclipse 4.8.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
