### ISSUE TITLE
Upgrade to JUnit Jupiter 5.6

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#24299]

**Comment by sbrannen** [comment]
JUnit 5.6 was released on January 20, 2020: https://twitter.com/junitteam/status/1219358379170242560

**Comment by jhoeller** [comment]
Could we do this upgrade for Spring Framework 5.2.x / Boot 2.3 already? Any backwards compatibility implications, in particular runtime compatibility with JUnit 5.5.x?

**Comment by snicoll** [comment]
Spring Boot 2.3 is already on JUnit Jupiter 5.6 for the record.

**Comment by jhoeller** [comment]
Ah good to know. This means that our JUnit 5.5.x compiled stuff is runtime compatible with JUnit 5.6 at least :-) Now that just leaves me wondering whether we can also assume the inverse, i.e. compiling our core stuff against JUnit 5.6 and runtime compatibility with JUnit 5.5.x. @sbrannen please advise...

**Comment by sbrannen** [comment]
> Ah good to know. This means that our JUnit 5.5.x compiled stuff is runtime compatible with JUnit 5.6 at least :-) 

Yes, that had better work! 

> Now that just leaves me wondering whether we can also assume the inverse, i.e. compiling our core stuff against JUnit 5.6 and runtime compatibility with JUnit 5.5.x. @sbrannen please advise...

To the best of my knowledge, there have not been any changes to Jupiter APIs that we compile against in the implementation of the `SpringExtension`, `EnabledIfCondition`, and `DisabledIfCondition`.
