### ISSUE TITLE
Objenesis NOTICE file contents missing from spring-core distribution

### ISSUE THREAD

**Issue by tazle** [spring-projects/spring-framework#24326]
It seems that Pivotal is distributing Objenesis binaries repackaged in the spring-core JAR. The spring-core binary JAR does not mention this in the license files included within, nor does it  include the information in the NOTICE file in Objenesis JAR file (META-INF/NOTICE in https://repo1.maven.org/maven2/org/objenesis/objenesis/3.1/objenesis-3.1.jar).

It is not clear to me if Pivotal is required to include the NOTICE contents in the binary distribution package by the Apache 2.0 terms, but doing so would certainly make it easier for redistributors of spring-core to discover that they must include the Objenesis NOTICE contents in their own documentation.

**Comment by sbrannen** [comment]
Thanks for bringing this up.

[license.txt](https://github.com/spring-projects/spring-framework/blob/master/src/docs/dist/license.txt) includes the licenses for ASM and CGLIB. Thus the omission of the license for Objenesis was an oversight that needs to be corrected.

As for your inquiries regarding inclusion of the Objenesis NOTICE file, I am not qualified to answer that.

**Comment by sbrannen** [comment]
Changes to the `license.txt` file will be addressed in #24340 and related issues.

**Comment by sbrannen** [comment]
The Objenesis NOTICE file contents will be included in Spring Framework 5.2.4 binaries as follows: https://github.com/spring-projects/spring-framework/blob/master/src/docs/dist/license.txt
