### ISSUE TITLE
Document that @Validated results in the use of a proxy and warn users about the side-effects

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#24338]
**Affects:** All supported versions

Using `@Validated` can result in a CGLib proxy being created for a bean. This has the sometimes unexpected side-effect of changing how the bean's fields behave when accessed directly. Please see [this Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/19638) for an example of a problem that this unexpected behavior can cause.

I think it would be good if the Framework reference documentation noted the use of a proxy and forewarned users about the side-effects.

**Comment by rstoyanchev** [comment]
We can add something to [this section](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#validation-beanvalidation-spring-method). 

Looking through that entire [3.7 Spring Validation](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#validation-beanvalidation) it looks like it could use a little bit of polishing, e.g. to avoid dated references. Also the title of that section should really be Bean Validation API as it is focused on JSR-303 support specifically (the section id is already `bean-validation`). 

Coverage of Spring Validation can be found even earlier at the [top of Section 3](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#validation) which could use a little polishing as well.
