### ISSUE TITLE
ClassPathResource can not find resources in named module

### ISSUE THREAD

**Issue by SW-Fantastic** [spring-projects/spring-framework#24335]
**Affects:** org.springframework 5.2.2

---

After updating java to jdk13, I used the named module in the project, because the unnamed module could not correctly handle some module relationships. At this time, I found that almost all the `ClassPathResource` that originally ran correctly in java8 failed, and the `ClassPathResource` should also run correctly in the unnamed module, the problem seems to exist in the named module only.    

 I try to use class to load resources directly. The result is different from what I expected. The modular JDK should change the processing of resources. When I find resources through module, I can get the resources correctly.

Before that, I didn't find a anything of this problem, so maybe it's a bug?

**Comment by snicoll** [comment]
> Before that, I didn't find a anything of this problem, so maybe it's a bug?

It's impossible for us to know. You haven't shared a lot of details or what was the previous JDK version you were using. The reference documentation has [some notes](https://docs.spring.io/spring-framework/reference/core/beans/classpath-scanning.html#beans-scanning-autodetection) about using classpath scanning on the modules path. Please review that and, if you're still affected, provide a sample we can run ourselves.
