### ISSUE TITLE
Expose the proxyPing property for client or server WebSocket with Reactor Netty 

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-framework#24331]
See https://github.com/reactor/reactor-netty/pull/945#issuecomment-571640355 for @violetagg's suggested places framework needs changing.

This is reactor-netty 9.3.x and 1.0.x so framework 5.2.x and 5.3.x respectively IIRC.

This is to support spring cloud gateway

**Comment by rstoyanchev** [comment]
@spencergibb this will have to be a configurable property on `ReactorNettyRequestUpgradeStrategy` and also on `ReactorNettyWebSocketClient`, similar to the `maxFramePayloadLength` that's already in both.

**Comment by JacobASeverson** [comment]
Hi folks, I've opened https://github.com/spring-projects/spring-framework/pull/24367 to address this.
