### ISSUE TITLE
Missing documentation of spring-webmvc-struts

### ISSUE THREAD

**Issue by Ceddaerrix** [spring-projects/spring-framework#24408]
**Affects:**  Documentation for _spring-webmvc-struts_, all versions

---

Under the link https://javadoc.io/doc/org.springframework/spring-webmvc-struts the following message appears:
No JavaDoc is released for artifact org.springframework:spring-webmvc-struts:\<version>. Please try other versions. You can retry or  report to us if you believe this is not expected.

All other spring components have such documentation available

**Comment by jhoeller** [comment]
I'm afraid `spring-webmvc-struts` has been removed from the Spring distribution more than ten years ago. The last version that contained it was Spring Framework 2.5.6. As a consequence, we are not going to actively distribute documentation for it anymore.
