### ISSUE TITLE
Error in link for @ControllerAdvice in Webflux doc

### ISSUE THREAD

**Issue by admoca60** [spring-projects/spring-framework#24461]
**Affects:** 5.2.3.RELEASE

---
The link for the word "@ControllerAdvice" in the page https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-ann-controller-exceptions is broken. Currently, the link goes to https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#mvc-ann-controller-advice but it should go to https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-ann-controller-advice

**Comment by rstoyanchev** [comment]
Thanks for the report! Looks like this was recently addressed with #24427.

**Comment by rstoyanchev** [comment]
Note the fix can currently be seen in the [snapshot reference][https://docs.spring.io/spring/docs/5.2.4.BUILD-SNAPSHOT/spring-framework-reference/web-reactive.html#webflux-ann-controller-exceptions]. When 5.2.4 is released the "current" reference will reflect this too.

**Comment by rstoyanchev** [comment]
Note the fix can currently be seen in the [snapshot reference](https://docs.spring.io/spring/docs/5.2.4.BUILD-SNAPSHOT/spring-framework-reference/web-reactive.html#webflux-ann-controller-exceptions). When 5.2.4 is released the "current" reference will reflect this too.
