### ISSUE TITLE
Revise generation of aggregated Javadoc in Gradle build

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#24473]
## Overview

The Gradle team has brought it to our attention that we should ideally generate aggregated Javadoc along the lines of the example provided by @jjohannes [here](https://github.com/jjohannes/gradle-demos/tree/master/aggregated-javadoc).

## Rationale

Adopting the aforementioned best practice for aggregating Javadoc across projects will...

- make parallel execution and build configuration caching safer/possible
- avoid potential breakage in future versions of Gradle
- introduce greater separation of concerns
- replace the current, hand-crafted approach with something more robust and maintainable

**Comment by sbrannen** [comment]
@rwinch, does the use of the `io.spring.javadoc-aggregate` plugin (#24715) make this issue obsolete?

**Comment by rwinch** [comment]
Yes
