### ISSUE TITLE
Support Optional in Jackson 2 message converters

### ISSUE THREAD

**Issue by daniel-shuy** [spring-projects/spring-framework#24498]
**Affects:** 5.2.3.RELEASE

---

Given an endpoint that returns a polymorphic JSON type, eg.

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({Impl1.class, Impl2.class})
public interface Parent {
}

public class Impl1 implements Parent {
}

public class Impl2 implements Parent {
}

@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public Parent get() {
    return new Impl1();
}
```

Jackson will serialize it with the property `@type`, eg.
```json
{
    "@type": "Impl1"
}
```

However, when wrapping it with an `Optional`/[Page](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html), the JSON polymorphism no longer works. Eg.
```java
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public Optional<Parent> getOptional() {
    return Optional.of(new Impl1());
}
```
returns:
```json
{}
```

According to FasterXML/jackson-databind#1594 this is due to type erasure, however the JSON polymorphism still works when wrapping with built-in `Collection`s (eg. `List`/`Set`/`Map`), eg.
```java
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public Collection<Parent> getCollection() {
    return Collections.singleton(new Impl1());
}
```

So it seems like Spring has special handling for built-in `Collection`s. Is it possible to apply them to `Optional`/[Page](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html) as well?

Currently the workaround is to create custom `JsonSerializer`s for `Optional`/[Page](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html), eg.
```java
@JsonComponent
public class OptionalSerializer extends JsonSerializer<Optional<?>> {
    @Override
    public void serialize(Optional<?> value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
        if (value.isPresent()) {
            gen.writeObject(value.get());
        }
    }
}
```

**Comment by encircled** [comment]
Hi.

I can confirm this issue. It works for collections thanks to Jackson support.

My PR fixes "Optional" only, for the Page it should be placed in a different repo I believe, spring-data-rest maybe?

**Comment by poutsma** [comment]
I don't see a way for Spring Framework to support Spring Data's `Page` type, so `JsonSerializer`s will still be required for those, but I can add support for `Optional`.

**Comment by daniel-shuy** [comment]
@poutsma Thank you! Should I request support for `Page` in [spring-data-commons](https://github.com/spring-projects/spring-data-commons) instead?
