### ISSUE TITLE
Incorrect mention of getPropertyValues in BeanWrapper section of documentation

### ISSUE THREAD

**Issue by zhuzhuman978** [spring-projects/spring-framework#24510]
In the section of  **3.3.1** in spring framework `version 5.1.3.RELEASE` **core technologies** document, the document describes that there is a `getPropertyValues` method. In fact, there is no such method in the `BeanWrapeer` class. I'm not sure if this is a version problem or refers to a method in another class instead of `BeanWrapper`.

![图片](https://user-images.githubusercontent.com/53943926/74342145-ff0a4700-4de3-11ea-9df0-1ea401621ba3.png)

**Comment by rstoyanchev** [comment]
It looks like that was `getPropertyValue(s)` at some point, i.e. meant to refer to all overloaded variants, but was edited in 395e3d008cc3fa63dbfc7319fad0f29120e84053.
