### ISSUE TITLE
Compatibility with JDK 15

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#24517]
Along the lines of #24453, this issue aims to track JDK 15 compatibility.

For the time being (i.e., during the 5.2.x time frame), we'll simply set up a CI build compiling and executing tests against JDK 15 early access builds.

**Comment by sbrannen** [comment]
We now have a `JDK 15` CI build plan in place: https://build.spring.io/browse/SPR-JDK15

**Comment by jhoeller** [comment]
Chances are that we'll officially support JDK 15 in the 5.2.x line still, giving it a JDK 8-15 range overall, expecting demand for early adoption there. The 5.3.x line is then expected to launch with a JDK 8-15 range, embracing JDK 16 and 17 in the course of its lifetime and therefore ending up with JDK 8-17.

We'll reschedule this ticket accordingly once a corresponding 5.2.x milestone is available on GitHub.

**Comment by jhoeller** [comment]
To the best of my understanding, the Spring Framework 5.2.x line is fully compatible with JDK 15 already, so I'll mark it as officially supported as of the 5.2.9 release. Support for JDK 16 and higher will follow in the Spring Framework 5.3 line, with the 5.2.x line ending at its current JDK 8-15 support range.
