### ISSUE TITLE
Spring Data Jpa - Query with SPEL - Named parameter not bound : __$synthetic$__

### ISSUE THREAD

**Issue by felixng1028** [spring-projects/spring-framework#24520]
In parseParameterBindingsOfQueryIntoBindingsAndReturnCleanedQuery, the matcher is referencing the parsed query.

	Matcher matcher = PARAMETER_BINDING_PATTERN.matcher(resultingQuery);

When checking for quotes in the matched parameters, the matcher passes its own indexes from the parsed query to the spelExtractor.isQuoted method which references the original non-parsed query.

				if (spelExtractor.isQuoted(matcher.start())) {
					continue;
				}

 By coincidence it appears the start index of some of your parameters in the parsed query match the start index of quotes in the original query. 

![quoteranges](https://user-images.githubusercontent.com/29769908/53455247-6bcbdc00-39ef-11e9-8ac0-00284680af26.png)

Thus, the above lines skip binding the parameters which results in the named parameter not bound exception. 

I was able to get your test to pass by changing the names of some parameters in the filter slightly.

![testpassedspringparser](https://user-images.githubusercontent.com/29769908/53455483-4b505180-39f0-11e9-819b-c422fa7e8bb6.png)
.

_Originally posted by @mfedirko in https://github.com/spring-projects/spring-framework/issues/22450#issuecomment-467665886_

**Comment by felixng1028** [comment]
I have encountered this issue many times, could Spring team help to fix this issue ASAP ?

**Comment by felixng1028** [comment]
Same behavior as 
https://github.com/spring-projects/spring-framework/issues/22450#issue-412862540

**Comment by odrotbohm** [comment]
Would you mind filing this in the [Spring Data JPA issue tracker](https://jira.spring.io/projects/DATAJPA)? Also, screenshots do not help that much. Please provide at least a stack trace and a bit code that's actually causing the issue.

**Comment by felixng1028** [comment]
https://jira.spring.io/browse/DATAJPA-1683
