### ISSUE TITLE
spring-data-mysqlx

### ISSUE THREAD

**Issue by lefred** [spring-projects/spring-framework#24545]
It would be very nice to have spring-data-mysqlx, supporting MySQL's DocumentStore and CRUD operations using the X protocol

**Comment by sbrannen** [comment]
@lefred, _this_ issue tracker is for the core Spring Framework. I am therefore closing this issue.

@odrotbohm, perhaps you can suggest which Spring Data project in [JIRA](https://jira.spring.io/projects/) would be best suited for this request.

**Comment by lefred** [comment]
Thank you for the feedback, and I would really appreciate to know where to add it in Jira as I don't see where to "ask" for what seems to be a new project.

Cheers,
