### ISSUE TITLE
AbstractClientHttpResponse not compatible with Cloudflare 521 status code

### ISSUE THREAD

**Issue by rubasace** [spring-projects/spring-framework#24554]
While trying to access the http status from an interceptor on the RestTemplate I'm getting the following exception:

```
No matching constant for [521] at 
org.springframework.http.HttpStatus.valueOf(HttpStatus.java:538) at 
org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33) at 
org.springframework.http.client.BufferingClientHttpResponseWrapper.getStatusCode(BufferingClientHttpResponseWrapper.java:50)
```

It seems that 521 (Web server is down) isn't a valid value for `org.springframework.http.HttpStatus`.  I can just get the raw number but does it make sense to support it from Spring side?

**Comment by sbrannen** [comment]
According to [this Wikipedia article](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes):

> Cloudflare's reverse proxy service expands the 5xx series of errors space to signal issues with the origin server.

Since `521` is specific to Cloudfare and since `HttpStatus` does not currently define any enum constants specific to Cloudfare, we recommend that you access the raw status code for such use cases.

**Comment by rstoyanchev** [comment]
You should be able to access that via [ClientHttpResponse#getRawStatusCode()](https://github.com/spring-projects/spring-framework/blob/e029dbf607468b65bc0811cc198fb771012d6da9/spring-web/src/main/java/org/springframework/http/client/ClientHttpResponse.java#L59).

**Comment by rstoyanchev** [comment]
Ignore my comment. What @sbrannen said.
