### ISSUE TITLE
BeanPostProcessor can eagerly initialize factory beans that use constructor injection

### ISSUE THREAD

**Issue by AlesD** [spring-projects/spring-framework#24553]
Auto configuration of `MethodValidationPostProcessor` in class `org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration` requires instance of Environment. Since the envirnonemt does not have `@Lazy` annotation it triggers autowire candidate resolution with `lazyInit=true` which in turn results in initialization of (at least) FactoryBeans.

Bean post processors should NOT use autowiring since the beans created just to check that they do not implement Environment are later not eligible for all other bean post processors - which is actually confirmed in log by lots of:

```
Bean 'xxx' of type [XXX] is not eligible for getting processed by all BeanPostProcessors
```

I have implemented custom `ImportBeanDefinitionRegistrar`. When I use it like this:

```java
@SpringBootApplication
@Import(GenesysRegistrar.class)
public class IntegrationServer {
...
}
```

everything works fine. But if I create my own auto-configuration class:

```java
@Configuration
@Import(GenesysRegistrar.class)
public class GenesysAutoConfiguration {
}
```

then bean definitions registered by `GenesysRegistrar` are created BEFORE `MethodValidationPostProcessor` during search for bean implementing Environment interface.

**Comment by snicoll** [comment]
@jhoeller Andy and I looked at it and we don't think there is anything we can do in Spring Boot. Andy also feels this can be related to #13893. Thoughts?

**Comment by AlesD** [comment]
OK - I changed the factory beans to use property injection instead of constructor injection.

What is strange is that the issue does not occur if you put @Import(MyRegistrar.class) on the main class or any other @Configuration class in application. It only happens during auto-configuration. I would expect that the bean definitions created by Registrar shall be created before MethodValidationPostProcessor is instantiated. But maybe tat is not true with JavaConfig.

Maybe it would be good to mention somewhere that constructor injection should be avoided for FactoryBean implementations. Maybe javadoc of PostProcessorRegistrationDelegate or its inner class BeanPostProcessorChecker that emits the "not eligible" info message?

Anyway thanks for feedback.

**Comment by wyhasany** [comment]
I've also stumbled upon on this issue in my starter. I've used `BeanFactory` to help instantiate bean definition with help of autowiring constructor arguments. Because of logic in `MethodValidationPostProcessor` all arguments has been initiated too early causing:
```
Bean 'x' of type [y] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```
Workaround with property autowiring works smoothly. Thanks @AlesD !

@snicoll / @wilkinsona could you consider add some notes in documentation encouraging autowiring custom `BeanFactories` by property?

**Comment by snicoll** [comment]
I have updated the sample to a supported version of the framework (5.3.x) and I can't reproduce the problem. Sorry we didn't get to it sooner but I can't reproduce. If you can, then please update the sample and we can reopen.

**Comment by AndreTeigler** [comment]
Maybe I can provide a sample. Basic Spring Boot App including RabbitMQ support. Extending the RabbitConnectionFactoryBean and importing the SslProperties from Spring:

@Component
public class SSLRabbitConnectionFactoryBean extends RabbitConnectionFactoryBean {

    private final SslProperties SslProperties;

    public SSLRabbitConnectionFactoryBean(SslProperties SslProperties){
        this.SslProperties = SslProperties;
    }
}

Starting the application results in the error:


 Bean 'spring.ssl-org.springframework.boot.autoconfigure.ssl.SslProperties' of type [org.springframework.boot.autoconfigure.ssl.SslProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [persistenceExceptionTranslationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.


If injection is done by Autowire the warning disappears.

[demo.zip](https://github.com/spring-projects/spring-framework/files/13887809/demo.zip)
