### ISSUE TITLE
A wrong logical for ConvertersForPair#getConverter

### ISSUE THREAD

**Issue by bonaluo** [spring-projects/spring-framework#24568]
**Affects:** \<5.2.3>
---
```java
if (!(converter instanceof ConditionalGenericConverter) ||
        ((ConditionalGenericConverter) converter).matches(sourceType, targetType)) {
    return converter;
}
```

it should be

```java
if ((converter instanceof ConditionalGenericConverter) &&
        ((ConditionalGenericConverter) converter).matches(sourceType, targetType)) {
    return converter;
}
```

**Comment by sbrannen** [comment]
If you feel that the boolean logic is incorrect, please provide a failing test case which demonstrates that the current implementation is flawed and that your proposed change fixes the flaw.

Thanks

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
