### ISSUE TITLE
Backport of ContentDisposition fixes to HttpHeaders

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#24580]
`ContentDisposition` was created in 5.0, supporting all Content-Disposition types including "form-data", "inline" and "attachment" for use in client and server scenarios. Prior to that,  `HttpHeaders` did have support for Content-Disposition of type "form-data", for use in client scenarios with the `RestTemplate`. This ticket is to review fixes in `ContentDisposition` that may be worth backporting to HttpHeaders in the 4.3.x branch for consistency.

**Comment by spring-issuemaster** [comment]
Fixed via 85c5a0c1a943f4485f3d4248d54c7b11cab176b3
