### ISSUE TITLE
Multipart/related support in Spring Webclient

### ISSUE THREAD

**Issue by niteshsinha** [spring-projects/spring-framework#24582]
Hi

Is `multipart/related` supported in spring webclient?
I am trying to create `multipart/related` mime request using webclient, but i dont see a corresponding `MediaType` listed for it, although i know it is possible with RestTemplate as per #23159

I have tried to make it work but i suppose i dont have then required [Convertor](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/converter/FormHttpMessageConverter.html#addPartConverter-org.springframework.http.converter.HttpMessageConverter-) in the chain, hence not able to correctly parse the individual parts.

This issue is more to get a traction on the SO [question](https://stackoverflow.com/questions/60359649/support-for-multipart-related-mime-type-in-spring-webclient) is posted.

P.S. Pardon me for ignoring the guidelines and creating the issue here. Please delete/remove this if required.

Thanks,
Nitesh

**Comment by rstoyanchev** [comment]
It looks like #23159 and #23209 took care of the RestTemplate but not the WebClient.
