### ISSUE TITLE
Additional pom with groupId io.spring.asciidoctor

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#24593]
When releasing Spring Framework `5.2.4.RELEASE` I noticed an extra package on Bintray for `io.spring.asciidoctor`.  Looking at our snapshot repo, we've started to recently deploy an extra pom for that `groupId`:  https://repo.spring.io/snapshot/io/spring/asciidoctor/spring/

Maybe this is related to 02e90a8645d34389d? 

I've removed the extra repo on Bintray. As part of fixing this we should also remove this pom from the snapshot repository.

**Comment by bclozel** [comment]
This has been fixed by e500456f1cc5bffef9bec3782001ed1fec78679d, the source of the problem was linked with gh-24605.
