### ISSUE TITLE
Distributions no longer deployed

### ISSUE THREAD

**Issue by JohnZ1385** [spring-projects/spring-framework#24605]
Usually I can find a full dist of the spring releases at:
https://maven.springframework.org/release/org/springframework/spring/
5.2.4 does not seem to have been posted despite most of the modules now being available on Maven central.

**Comment by snicoll** [comment]
Thanks for the report @JohnZ1385. This looks like a regression introduced by a change in our build script. 

FTR, the canonical url for that repo is https://repo.spring.io/release/org/springframework/spring/

**Comment by bclozel** [comment]
The [last successful SNAPSHOT deploy was done on February 7th](https://repo.spring.io/libs-snapshot/org/springframework/spring/5.2.4.BUILD-SNAPSHOT/), which leads me to think that the repository declaration done in 02e90a8645d34389d737718d72573947110e681a might have something to do with this problem.

**Comment by sbrannen** [comment]
> The [last successful SNAPSHOT deploy was done on February 7th](https://repo.spring.io/libs-snapshot/org/springframework/spring/5.2.4.BUILD-SNAPSHOT/), which leads me to think that the repository declaration done in [02e90a8](https://github.com/spring-projects/spring-framework/commit/02e90a8645d34389d737718d72573947110e681a) might have something to do with this problem.

@wilkinsona, thoughts?

**Comment by wilkinsona** [comment]
I can’t explain why that repository declaration would cause a publishing problem. The repository declaration should only affect dependency resolution and only dependencies in the `io.spring.asciidoctor` group at that. It would be particularly bizarre for it to only affect one module as well.

That said, it’s impossible to rule it out as the Bamboo Artifactory integration is a black box that could be doing pretty much anything.

**Comment by wilkinsona** [comment]
FWIW, the build logs show the artifacts being deployed:

```
build	28-Feb-2020 17:10:46	Deploying artifact: https://repo.spring.io/libs-snapshot-local/io/spring/asciidoctor/spring/5.2.5.BUILD-SNAPSHOT/spring-5.2.5.BUILD-SNAPSHOT-dist.zip
build	28-Feb-2020 17:10:53	Deploying artifact: https://repo.spring.io/libs-snapshot-local/io/spring/asciidoctor/spring/5.2.5.BUILD-SNAPSHOT/spring-5.2.5.BUILD-SNAPSHOT-docs.zip
build	28-Feb-2020 17:10:56	Deploying artifact: https://repo.spring.io/libs-snapshot-local/io/spring/asciidoctor/spring/5.2.5.BUILD-SNAPSHOT/spring-5.2.5.BUILD-SNAPSHOT-schema.zip
build	28-Feb-2020 17:10:56	Deploying artifact: https://repo.spring.io/libs-snapshot-local/io/spring/asciidoctor/spring/5.2.5.BUILD-SNAPSHOT/spring-5.2.5.BUILD-SNAPSHOT.pom

**Comment by wilkinsona** [comment]
I can explain it now and it was my fault. Sorry. It should be `includeGroup` rather than `group` when configuring the `mavenContent`.

**Comment by sbrannen** [comment]
Thanks for figuring out the solution, @wilkinsona! 👍 

We'll get that fixed.

**Comment by sbrannen** [comment]
Distribution zip files are once again being published.

https://repo.spring.io/snapshot/org/springframework/spring/5.2.5.BUILD-SNAPSHOT/

**Comment by snicoll** [comment]
And the proper zips have been staged for `2.2.5` as well.

**Comment by sbrannen** [comment]
> And the proper zips have been staged for `5.2.5` as well.

Indeed... staged and now available: https://repo.spring.io/release/org/springframework/spring/5.2.5.RELEASE/
