### ISSUE TITLE
TransactionInterceptor constructors should accept a generic TransactionManager

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-framework#24612]
Right now to configure a `TransactionInterceptor` programmatically with a `ReactiveTransactionManager` we need to call a default constructor and then `setTransactionManager(TransactionManager)`.

For consistency it would be better to have other constructors based on this `TransactionManager` abstraction instead of a `PlatformTransactionManager` trait.

I would even say it is not a breaking change since `PlatformTransactionManager extends TransactionManager`.

**Comment by artembilan** [comment]
It also looks like a `<tx:advice transaction-manager="">` type has to be be fixed for generic `TransactionManager` type as well.

**Comment by jhoeller** [comment]
For binary compatibility in the middle of the 5.2.x line, we'll have to introduce overloaded constructors on `TransactionInterceptor` (since relaxing the parameter type in the signature is only source compatible when freshly compiled) but that's not too big a deal.
