### ISSUE TITLE
CodecException (from JSON conversion) in RestController is not mapped to 400 but 500 (SB 2.2.5 & Kotlin)

### ISSUE THREAD

**Issue by csh0711** [spring-projects/spring-framework#24646]
We just upgraded our **Kotlin** project from Spring Boot 2.2.4 to 2.2.5.

Unfortunately now some **WebFlux**-RestController tests fail because a mandatory JSON payload field now leads to a _500 Internal Server Error_ instead of a _400 Bad Request_.

This is an exemplary RestController with its Kotlin data class for the request payload:

```
@RestController
class Controller {

    @PostMapping("/hello")
    fun post(@RequestBody request: RequestPayload) =
        ResponseEntity.ok().body("Hello ${request.foo} - ${request.bar}")

}

data class RequestPayload(
    val foo: String,
    val bar: String?
)

```

Please notice that attribute _foo_ is mandatory (no `?`).

This is the invalid payload (missing JSON field `foo`):
`{ 
    "bar": "bar text" 
} `

When calling this RestController in a **Spring Boot 2.2.4** app this results in a **_DecodingException_** which is correctly mapped to the status code **400**.

But when calling this RestController in a **Spring Boot 2.2.5** app this leads to **_CodecException_** which is **not** mapped to the status code 400 but results in a **500**.

Please find the example in my GitHub repo: https://github.com/csh0711/boot-2-2-5-kotlin-codec-exception

Or use this ControllerTest: 

```
@WebFluxTest(Controller::class)
internal class ControllerTests(
    @Autowired private val webTestClient: WebTestClient
) {
    @Test
    fun `responds with HTTP 400 BAD_REQUEST for missing foo in payload`() {
        webTestClient.post()
            .uri("/hello")
            .contentType(MediaType.APPLICATION_JSON)
            .bodyValue(""" { "bar": "bar text" } """)
            .exchange()
            .expectStatus().isBadRequest
    }
}
```

Many thanks in advance! :-)

**Comment by snicoll** [comment]
Thanks @dreis2211, I agree. I've moved the issue for further considerations. We might close it as duplicate if it turns out to be the same problem.

**Comment by csh0711** [comment]
Okay, thanks @snicoll and @dreis2211 👍

**Comment by jhoeller** [comment]
This is indeed the same problem, just in the reactive codec implementation as opposed to the `HttpMessageConverter` infrastructure (which are kept in sync in that respect). I'll keep this issue open as a variant of the same issue, closing it along with the others.
