### ISSUE TITLE
Experiment with aggregateJavadoc task in Spring Javadoc plugin

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#24653]
Experiment with the [`aggregateJavadoc` Gradle task](https://github.com/spring-gradle-plugins/javadoc-plugin) by @rwinch and provide feedback.

**Comment by rwinch** [comment]
Here is what I have using the snapshots https://github.com/rwinch/spring-framework/tree/gh-24653-aggregatejavadoc

**Comment by rwinch** [comment]
I have released 0.0.1 version and created a PR that will close this issue https://github.com/spring-projects/spring-framework/pull/24715

**Comment by sbrannen** [comment]
Thanks, @rwinch! I've slated your PR for 5.2.5.
