### ISSUE TITLE
Improve efficiency of mutating of ClientHttpResponse and ServerHttpRequest 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#24680]
`DefaultClientResponse` has `from(ClientResponse)` which copies status, headers, and cookies. It is only half as useful because it ignores the body which is [easy to forget](https://github.com/spring-projects/spring-framework/issues/24126#issuecomment-562519509) or otherwise leads to code like this as a starting point:

```java
ClientResponse.from(response).body(response.bodyToFlux(DataBuffer.class)
```

We should add `ClientResponse.mutate()` matching to similar options on the server side. Also both client and server `mutate()` should be careful not to parse cookies unnecessarily which can lead to surprises, see  #24663.

In addition since mutation can be quite common, it should be made as optimal as possible, avoiding object creation in parts not mutated, and also optimizing for repeated use, e.g. [response headers](https://github.com/spring-projects/spring-framework/blob/0dc1c7eb8b4ca17996567406f3e16267ff544a6d/spring-web/src/main/java/org/springframework/http/client/reactive/ReactorClientHttpResponse.java#L85)).

**Comment by SenthilPanneerselvam** [comment]
Hi Rossen,
Are you working on this issue? If not I would like to pick this up.

**Comment by rstoyanchev** [comment]
@SenthilPanneerselvam thanks for the offer to help. I'd afraid the issue is such that it requires a little experimenting but actual changes expected are not much. So by the time I can give you a proper answer I'd probably have the solution more or less ready.
