### ISSUE TITLE
MimeTypeUtils over-occupy the cpu 

### ISSUE THREAD

**Issue by com-poorbar** [spring-projects/spring-framework#24710]
In Spring-core-5.2.2-Release
Inner class ConcurrentLruCache,
When the LRU cache is full, it over-occupt the cpu.  Because of the excess CAS and locks

**Comment by mdeinum** [comment]
Isn't this related (or a duplicate of) #24671

**Comment by bclozel** [comment]
Closing as a duplicate of #24671, thanks @mdeinum !
