### ISSUE TITLE
WebClient decodes string array as one string

### ISSUE THREAD

**Issue by bringyou** [spring-projects/spring-framework#24734]
Assume we have an endpoint that returns string array, like this (ContentType is application/json)
```json
["a","a","a"]
```
and retrieve it's response as `Flux<String>`
```java
webClient.get().uri().retrieve()
.bodyToFlux(String.class)
.subscribe(s -> println(s))
```
In my opinion, it should print "a" for three times, but only prints `["a","a","a"]`.
However, **there is a workaround**, we can replace `String.class` with `String[].class`, but the result returned in semantic isn't a `Flux` anymore, but a `Mono`.
(The version of Spring Webflux is 5.2.3-RELEASE)

**Comment by bringyou** [comment]
Looks like this method is the cause `BodyExtractors.readWithMessageReaders`
```java
private static <T, S extends Publisher<T>> S readWithMessageReaders(
			ReactiveHttpInputMessage message, BodyExtractor.Context context, ResolvableType elementType,
			Function<HttpMessageReader<T>, S> readerFunction,
			Function<UnsupportedMediaTypeException, S> errorFunction,
			Supplier<S> emptySupplier) {

		if (VOID_TYPE.equals(elementType)) {
			return emptySupplier.get();
		}
		MediaType contentType = Optional.ofNullable(message.getHeaders().getContentType())
				.orElse(MediaType.APPLICATION_OCTET_STREAM);

		return context.messageReaders().stream()
				.filter(reader -> reader.canRead(elementType, contentType))
				.findFirst()
				.map(BodyExtractors::<T>cast)
				.map(readerFunction)
				.orElseGet(() -> {
					List<MediaType> mediaTypes = context.messageReaders().stream()
							.flatMap(reader -> reader.getReadableMediaTypes().stream())
							.collect(Collectors.toList());
					return errorFunction.apply(
							new UnsupportedMediaTypeException(contentType, mediaTypes, elementType));
				});
	}
```

**Comment by rstoyanchev** [comment]
This is described here https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-jackson. 

There is an ambiguity with `String` and "application/json". It could be a serialized JSON or a JSON array. We treat it as the former. To resolve the ambiguity you can encode/decode to `Mono<List<String>>`.

**Comment by borissedlak** [comment]
Can you provide a full request on that? I tried to follow the reference on the spring web documentation but I ended up with 

`Mono<List<String>>response = webClient.put()
.uri(**)
.retrieve()
.bodyToFlux(String.class)
.collectList()
.block();`

and the result is still a single element though my json is of form `["a","b","c"]`

**Comment by rstoyanchev** [comment]
If you want a single string, reduce the list by concatenating:
```java
webClient.get()
		.uri("/write-and-flush")
		.retrieve()
		.bodyToFlux(String.class)
		.collect(Collectors.joining())

**Comment by jdeex** [comment]
> 
> 
> Can you provide a full request on that? I tried to follow the reference on the spring web documentation but I ended up with
> 
> `Mono<List<String>>response = webClient.put() .uri(**) .retrieve() .bodyToFlux(String.class) .collectList() .block();`
> 
> and the result is still a single element though my json is of form `["a","b","c"]`

This in fact returns one String with the complete array in it



> 
> 
> If you want a single string, reduce the list by concatenating:
> 
> ```java
> webClient.get().uri("/path")
> 	.retrieve()
> 	.bodyToFlux(String.class)
> 	.collect(Collectors.joining())
> ```

We don't want a single String, we want the List of values

If you get a application/json reply like ["a","b","c"] and process it with .bodyToFlux(String.class) .collectList() .block() you should get a List<String> right?

**Comment by bringyou** [comment]
The workaround I mentioned is something like&nbsp;&nbsp; &nbsp; webClient.get().uri().retrieve().bodyToFlux(String[].class) &nbsp;
now we get a flux<String[]&gt; who only has one item, then you can convert it to any type you like




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月24日(星期六) 凌晨1:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spring-projects/spring-framework] WebClient decodes string array as one string (#24734)





  
Can you provide a full request on that? I tried to follow the reference on the spring web documentation but I ended up with
 
Mono<List<String&gt;&gt;response = webClient.put() .uri(**) .retrieve() .bodyToFlux(String.class) .collectList() .block();
 
and the result is still a single element though my json is of form ["a","b","c"]
  
This in fact returns one String with the complete array in it
  
If you want a single string, reduce the list by concatenating:
 webClient.get().uri("/path") 	.retrieve() 	.bodyToFlux(String.class) 	.collect(Collectors.joining())
  
We don't want a single String, we want the List of values
 
If you get a application/json reply like ["a","b","c"] and process it with .bodyToFlux(String.class) .collectList() .block() you should get a List right?

**Comment by bringyou** [comment]
The workaround I mentioned is something like
```java
webClient.get().uri().retrieve().bodyToFlux(String[].class);   // now we get a flux<String[]> who only has one item
webClient.get().uri().retrieve().bodyToMono(String[].class);  // or a mono<String[]>
```
then you can convert string[] to any type you like

**Comment by jdeex** [comment]
Thx for the workaround, I did something similar... I starting to think that this only happens with the String class, other pojos work as expected...

**Comment by pablo53** [comment]
Having read the maintainers' response, I still can't understand why is this ticket closed, and why the following:
`["a","b","c"]`
is interpreted by WebClient as a single string. Former RestTemplate interpreted it correctly as a collection. So, Flux should correctly parse it as a Flux<String> with 3 string elements, and not one string representing JSON. WebClient would be right, if the content was like this:
`"[\"a\",\"b\",\"c\"]"`.
Then I'd agree that Flux should return one string element `["a","b","c"]`.
