### ISSUE TITLE
@Conditional bean called multiple times 

### ISSUE THREAD

**Issue by JerryJavaCoding** [spring-projects/spring-framework#24759]
Whats happening is that my project which implements the Condition interface is getting instantiated multiple times and its match method also gets called 3 times.if any logic in matches method will to be called 3 times,is necessary?

**Comment by snicoll** [comment]
@JerryJavaCoding it is impossible to know with the level of details that you've shared. Please provide a small sample (github repo or zip) that we can run to reproduce the issue you've described.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by AmanMulani** [comment]
> Whats happening is that my project which implements the Condition interface is getting instantiated multiple times and its match method also gets called 3 times.if any logic in matches method will to be called 3 times,is necessary?

Any updates on what had happened? I am seeing the same issue now

**Comment by bclozel** [comment]
@AmanMulani if you're seeing the same issue, please share a minimal sample application that reproduces the problem and we'll have a look.
