### ISSUE TITLE
 webClient build url wrong when using UriBuilder [probably a bug]

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-framework#24787]
## affects
```
path = "http://a.b/c";
webClient = WebClient.builder().build();
webClient.get()
        .uri(uriBuilder -> uriBuilder.path(path).queryParams(myMutliValuedMapParams).build());
```
uri becomes: "http:/a.b/c", the double slash after schema becomes a single slash. And results in an 
`java.net.UnknownHostException: http:` But `webClient.get().uri(path);` does not have the same problem.
## possible reason
`UriComponentsBuilder.java`  buildInternal function causes the problem. the var `uric` is wrong.
```

private UriComponents buildInternal(EncodingHint hint) {
		UriComponents result;
		if (this.ssp != null) {
			result = new OpaqueUriComponents(this.scheme, this.ssp, this.fragment);
		}
		else {
// The PROBLEM: 
			HierarchicalUriComponents uric = new HierarchicalUriComponents(this.scheme, this.fragment,
					this.userInfo, this.host, this.port, this.pathBuilder.build(), this.queryParams,
					hint == EncodingHint.FULLY_ENCODED); 

			result = hint == EncodingHint.ENCODE_TEMPLATE ? uric.encodeTemplate(this.charset) : uric;
		}
		if (!this.uriVariables.isEmpty()) {
			result = result.expand(name -> this.uriVariables.getOrDefault(name, UriTemplateVariables.SKIP_VALUE));
		}
		return result;
	}
```
## version
spring-web-5.1.8.RELEASE

**Comment by bclozel** [comment]
Your code is feeding the entire URL to the path method. Please take a look at the interface so you can see how to use it: https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/UriBuilder.java

Thanks!

**Comment by miguel-botelho** [comment]
Hey @bclozel 👋 

We've noticed the same issue, but we have (for example) the following API we need to call: `https://test.com/relative/https://example.com`. When using the `uri` method, we've noticed the same behaviour, the slash is removed (which IMO it shouldn't). AFAIK, this URL is valid. The code we have on our side is quite similar:
```
WebClient
     .builder()
     .baseUrl("https://test.com")
     .build()
     .method(HttpMethod.POST)
     .uri("/relative/https://example.com")
     .accept(APPLICATION_JSON)
```

Should we open another issue?

**Comment by bclozel** [comment]
I believe the `:` character is illegal in path segment. Maybe [this section of the reference documentation on URL encoding](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#web-uri-encoding) is of interest?

**Comment by miguel-botelho** [comment]
I checked that code and documentation, many thanks for the link. However, it seems that according to RFC 3986, a full URL is valid in a relative path. I've also tried creating an URI Java object around my example, and no exceptions or issue arise from that. Should this be expected behaviour (removing one of the slashes), or, if it's not supported, should it just throw an exception while building the request? Again, thanks for the input

**Comment by bclozel** [comment]
@miguel-botelho I understand now - we are indeed sanitizing the path and removing duplicate`"/"`. This is a long standing behavior and I'm not sure we can easily change this now. Feel free to create a new issue, giving as much background information about this use case: why APIs are requiring this format, how common they are (any public one is a plus) and also the [limitations of this approach as explained in the RFC](https://www.rfc-editor.org/rfc/rfc3986#section-3.3).
