### ISSUE TITLE
i need to know which version of gradle you are using

### ISSUE THREAD

**Issue by eric521237** [spring-projects/spring-framework#24783]
Could not fetch model of type 'EclipseProject' using Gradle installation 'E:\gradle-3.1'.

i use ide of spring tool suite

**Comment by snicoll** [comment]
Everything you need to know is [on this help page](https://github.com/spring-projects/spring-framework/blob/master/import-into-eclipse.md). There is a gradle wrapper at the root that takes care of using the right Gradle version.

If you have more questions, please follow up on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
