### ISSUE TITLE
ImportAware

### ISSUE THREAD

**Issue by githubcheng2978** [spring-projects/spring-framework#24812]
if implements ImportSelector and ImportAware interfaces ,selectImports method can be invoke ,but setImportMetadata method cannot invoke

**Comment by sbrannen** [comment]
Please note that the class-level Javadoc for `ImportSelector` states which `*Aware` interfaces are supported, and `ImportAware` is not listed as supported.

So, what makes you think that you can implement `ImportSelector` and `ImportAware` in the same class, and why would you want to?

**Comment by githubcheng2978** [comment]
I see , there may be no problem
