### ISSUE TITLE
Allow setting SerializationInclusion with JsonInclude.Value

### ISSUE THREAD

**Issue by vkuzel** [spring-projects/spring-framework#24824]
**Affects:** \5.2.5
Enhancement

* There is a method `Jackson2ObjectMapperBuilder.serializationInclusion(JsonInclude.Include serializationInclusion)` which is an equivalent to Jackson's `ObjectMapper setSerializationInclusion(JsonInclude.Include incl)`
* Unfortunately there is no equivalent to `ObjectMapper.setPropertyInclusion(JsonInclude.Value incl)` which allows more elaborate configuration.

# Suggestion #1

* Replace (or add) `Jackson2ObjectMapperBuilder.serializationInclusion(JsonInclude.Include serializationInclusion)` with `Jackson2ObjectMapperBuilder.serializationInclusion(JsonInclude.Value serializationInclusion)` which covers more cases.

# Suggestion #2

* Add an object mapper post-processor to `Jackson2ObjectMapperBuilder` which would allow to perform exotic configurations not supported by builder by default.
* This would remove the need of extending builder class which comes handy in Spring Boot applications.

```java
//example
class Jackson2ObjectMapperBuilder {

    private Consumer<ObjectMapper> postProcessor;

    public void configure(ObjectMapper objectMapper) {
        // ...
        if (postProcessor != null) {
            postProcessor.accept(objectMapper);
        }
    }
```

**Comment by bclozel** [comment]
Hello @vkuzel ,

`Jackson2ObjectMapperBuilder.serializationInclusion(JsonInclude.Include serializationInclusion)` is mirroring `ObjectMapper. setSerializationInclusion(JsonInclude.Include serializationInclusion)`. Other ObjectMapper methods do accept `JsonInclude.Value` types as parameters.

Could you take a step back and give an example (ideally a code snippet) of what you're trying to achieve?

[Spring Boot already provides several ways to customize `ObjectMapper` instances](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-customize-the-jackson-objectmapper) and we'd like to remain consistent here.

Thanks!

Thanks!

**Comment by vkuzel** [comment]
Hi @bclozel 

**ad "serlization inclusion method")** There is a [`ObjectMapper.setPropertyInclusion(JsonInclude.Value incl)`](https://github.com/FasterXML/jackson-databind/blob/0e0ca2520114f790e2613c72508d90bad8fd6e38/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L1501) which should be mirrored. This means builder should have something like `Jackson2ObjectMapperBuilder.propertyInclusion(JsonInclude.Value incl)`. I am talking about Jackson 2.10.x currently used in Spring.

My goal is to do following configuration via builder.
```java
objectMapper.setDefaultPropertyInclusion(JsonInclude.Value.construct(JsonInclude.Include.NON_NULL, JsonInclude.Include.ALWAYS))
```

**ad "flexible solution to configure object mapper")** It seems like ObjectMapper's API is being developed faster than builder's API. Suggestion #2 is a way to allow developers to use ObjectMapper's new features that are not implemented in builder's API.

Thank you.

**Comment by bclozel** [comment]
Given we've got this issue, and #23017 as well - I'm wondering if we should instead follow a `Jackson2ObjectMapperBuilder.configure(Consumer<ObjectMapper>)` pattern.

Jackson seems to add more options, and adding all options might become brittle if we want to support several Jackson generations.

What do you think @jhoeller @sdeleuze ?

**Comment by rstoyanchev** [comment]
I think having `Consumer<ObjectMapper>` for more advanced customizations is a good idea.

**Comment by rstoyanchev** [comment]
I've added both `serializationInclusion(JsonInclude.Value)` and a `Consumer<ObjectMapper>` option.
