### ISSUE TITLE
Change MultiValueMap to extend Map<K, List<? extends V>>

### ISSUE THREAD

**Issue by jonfreedman** [spring-projects/spring-framework#24840]
If we change [MultiValueMap ](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/MultiValueMap.java) to wildcard the List type it extends then this code will compile

```java
final MultiValueMap<String, Object> formParams = new LinkedMultiValueMap<>();
final  List<String> enumFormStringArray = Collections.singletonList("foo");
formParams.put("enum_form_string_array", enumFormStringArray);
```

This will allow us to clear up some warnings in the openapi-generator (https://github.com/OpenAPITools/openapi-generator/issues/5782)

**Comment by jonfreedman** [comment]
I had a look at this change, it seems to me that the #addAll method was added to solve this, although the semantics are slightly different.  I think what really should happen is that this interface should not extend Map at all, similar to the Multimap interface in Guava.

**Comment by snicoll** [comment]
Thanks for the suggestion but we'd like to retain the same contract as what `java.util.Map` does.
