### ISSUE TITLE
Consider Hidden classes use cases

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-projects/spring-framework#24847]
The feature called Hidden classes has been officially marked as a candidate for Java 15 which will reach general availability by the 15 september of this year.

Hidden classes are a feature that I think is specifically made for frameworks like spring. 

You have far more expertise than me for considering what could be the use cases/benefits/optimizations that this feature could provide on spring, when detecting at runtime that the user supports Java 15.

https://openjdk.java.net/jeps/371

It might be used for beans or any other kind of dynamically generated classes.

Edit: BTW you could propose, influence the design of the feature while it can still change.

**Comment by grubeninspekteur** [comment]
Could this feature be used to fix #26266? Hidden classes are eligible for garbage collection as they are not referenced by class loaders. However, they have the drawback that they cannot be referenced by name, and thus not appear in any code (instances can be constructed using the hidden class's Lookup, however).

**Comment by snicoll** [comment]
Thanks for the suggestion but without a concrete request that we can evaluate this issue is not actionable. We're following JEPs and changes to the JDK and will make benefit of hidden classes if it turns out to be useful.

As for the referenced issue, it's been fixed in the meantime.
