### ISSUE TITLE
Add ability to provide additional extensions with @SpringJunitConfig

### ISSUE THREAD

**Issue by dustinschultz** [spring-projects/spring-framework#24849]
Add the ability to provide additional extensions when using `@SpringJunitConfig`

The convenience annotation is nice but can't be used when there's more than 1 extension. A common example of this would be utilizing LocalStack:

```
@ExtendWith({SpringExtension.class, LocalstackDockerExtension.class})
```
Note that multiple `@ExtendWith` annotations are supported but supporting multiple within `@SpringJunitConfig` would be a nice addition/convenience to reduce the amount of annotations ... especially since tests often have several on the class already.

**Comment by sbrannen** [comment]
This is unfortunately not possible.

`@SpringJUnitConfig` is an annotation provided by the Spring Framework; whereas, `@ExtendWith` is an annotation provided by JUnit Jupiter.

Although the Spring Framework has support for custom _composed annotations_ via the `@AliasFor` annotation, JUnit does not have such support.

Thus, although we could technically introduce an attribute in `@SpringJUnitConfig` that would allow one to _declare_ additional JUnit Jupiter extensions, JUnit Jupiter would never be able to find those declarations within the Spring annotation.

However, if you find that you are repeatedly declaring `@SpringJUnitConfig` alongside `@ExtendWith(LocalstackDockerExtension.class)` in your own projects, you could of course introduce your own composed version of `@SpringJUnitConfig` that is meta-annotated with `@ExtendWith({SpringExtension.class, LocalstackDockerExtension.class})`.
