### ISSUE TITLE
Zipkin: Deprecatead APIs in documentation for customization of client parsing of the HTTP related spans 

### ISSUE THREAD

**Issue by Vynnytska** [spring-projects/spring-framework#24851]
In the documentation, https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.1.0.M2/multi/multi__customizations.html is mentioned "If a customization of client / server parsing of the HTTP related spans is required, just register a bean of type brave.http.HttpClientParser or brave.http.HttpServerParser."

It works this way. However, HttpCLientParser and HttpServerParser are **deprecated** right now and customization doesn't work with suggested HttpRequestParser or without registration bean.
Please update the documentation on how to work with non-deprecated things.

**Comment by rstoyanchev** [comment]
Please, open this in the [spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth) repository.
