### ISSUE TITLE
Unable to find the license for Java HTTP Server component in spring-web-5.2.4.RELEASE.jar

### ISSUE THREAD

**Issue by chinmaypanda53** [spring-projects/spring-framework#24854]
In spring-web-5.2.4.RELEASE.jar for the below classes

spring-web-5.2.4.RELEASE.jar/org/springframework/remoting/caucho/SimpleHessianServiceExporter.class
spring-web-5.2.4.RELEASE.jar/org/springframework/remoting/httpinvoker/SimpleHttpInvokerServiceExporter.class
spring-web-5.2.4.RELEASE.jar/org/springframework/remoting/jaxws/SimpleHttpServerJaxWsServiceExporter.class

If we are checking the Source code of these class files from GitHub, below import statements are used for these files .

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;

For these import statements Black duck tool  is identifying the import statements are from the Java HTTP Server component (http (repo1.maven.org/maven2/com/sun/net/httpserver))
And the tool is not able to identify the license of this HTTP server component .

Please reply us with the license of this Java HTTP Server component

**Comment by sbrannen** [comment]
Those classes are not downloaded via any artifacts on Maven Central. They are part of the JDK and therefore have the same license as the JRE you are using.

For example, you will find the Javadoc for the Oracle JRE 8 here: https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/package-summary.html
