### ISSUE TITLE
Documentation for CORS WebFlux

### ISSUE THREAD

**Issue by tamaro-skaljic** [spring-projects/spring-framework#24863]
I've found no paragraph about CORS in the WebFlux part of the Spring Boot Documentation, is CORS only supported in Spring MVC? (It is shown [there](https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/htmlsingle/#boot-features-cors))

Because [here](https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/web/webflux-cors.adoc) is a document named 'webflux-cors.adoc' with paragraphs about Spring MVC.

**Comment by sbrannen** [comment]
CORS is supported both in Spring MVC and WebFlux. The `webflux-cors.adoc` document is about WebFlux, not MVC, although it has cross references to the MVC specific documentation.

If you would like for the Spring Boot reference manual to include CORS examples using WebFlux, please open an issue in the [Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
