### ISSUE TITLE
Scanned custom annotations ClassPathBeanDefinitionScanner encountered a problem

### ISSUE THREAD

**Issue by lxchinesszz** [spring-projects/spring-framework#24874]
Scanned custom annotations `ClassPathBeanDefinitionScanner` encountered a problem. When classes that need to be scanned have both the custom annotations and the system annotations, they are thought to be scanned by the system annotations, not by the custom annotations. So `doScan()` returns an empty array. What should I do in this case? Are there any available tools?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
