### ISSUE TITLE
Spring Data MongoDb - Unable to use @EnableMongoAuditing with multiple DB connections

### ISSUE THREAD

**Issue by hirowla** [spring-projects/spring-framework#24880]
Please see [this issue in StackOverflow ](https://stackoverflow.com/questions/60557848/couldnt-find-persistententity-fpr-type-class-when-using-enablemongoauditing-wi) for all of the details.

While thinking about it, I'm sure this is a defect or something to be completed. This is in the version of Spring Data which is with Spring Boot 2.1.12.

**Comment by sbrannen** [comment]
This issue tracker is for the core Spring Framework.

For issues with Spring Data MongoDB, please use the dedicated [Spring Data MongoDB issue tracker](https://jira.spring.io/projects/DATAMONGO/issues).
