### ISSUE TITLE
Built-in support for standard bean validation on controller method arguments 

### ISSUE THREAD

**Issue by hedgerocker** [spring-projects/spring-framework#24913]
Related to #11041.

I'm trying to validate `@PathVariable` and `@RequestBody` in one method. `MethodValidationPostProcessor` is registered. Simplified Controller looks like this:

```java
@RestController
@Validated
public class MyController {
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT)
    public ResponseEntity method_name(@PathVariable @NotNull String id, @Valid @RequestBody Body body) {
        /// Some code
    }
}
```

I noticed that request body validation is triggered twice - it wouldn't be an issue if it weren't custom `ConstraintValidator` with injected bean:

```java
public class CustomValidator implements ConstraintValidator<Body, String> {

	@Autowired
	private BodyVerificator bodyVerificator;
...
```

For first validation run the bean is injected properly, and for second run it's null so it results in NPE. Workaround is to either not use method parameter validation at all, or to annotate `@RequestBody` with `@Validated` so not mix `@Validated` and `@Valid`. I would actually prefer to have `@PathVariable` bean validation support in Spring like in #11041.

**Comment by encircled** [comment]
Hi,

Just use annotation `@Validated` instead of `@Valid` for `@RequestBody` parameter. Spring argument resolver triggers on both.

**Comment by rstoyanchev** [comment]
**Team decision:** we are going to provide first-class support for bean validation that's built into the web framework, without requiring a separate post-processor and an AOP proxy.

**Comment by rstoyanchev** [comment]
I'm closing this in favor of #29825 that summarizes issues with validation across multiple issues, and also highlights some of the design questions. Please take a look and provide further feedback if necessary under the new issue.
