### ISSUE TITLE
'StandardEnvironment' Optimize. 

### ISSUE THREAD

**Issue by cherishsince** [spring-projects/spring-framework#24937]
Th's 'StandardEnvironment' constructor should show call parent constructor. (Improve reading)

**Comment by sbrannen** [comment]
`StandardEnvironment` does not define a constructor. Thus, the default constructor will be used, and the default constructor automatically delegates to the default constructor in the parent class (`AbstractEnvironment`).

These are the standard semantics for the Java programming language. In light of that, I am closing this issue.

**Comment by PascalSchumacher** [comment]
@sbrannen I guess you accidentally forgot to close this issue?

**Comment by cherishsince** [comment]
Show that the call builder should be able to read the code better.

**Comment by cherishsince** [comment]
Show that calling 'constructor' should read the code better

**Comment by sbrannen** [comment]
> @sbrannen I guess you accidentally forgot to close this issue?

Indeed. Thanks for pointing that out.
