### ISSUE TITLE
xml and javaConfig are used in the same interceptor, javaConfig didn't work on swagger /v2/api-doc

### ISSUE THREAD

**Issue by minggen** [spring-projects/spring-framework#24940]
xml与javaConfig 配置同一个拦截器 ，javaConfig 对 swagger /v2/api-doc 不生效

javaConfig

```java
    @Bean
    public SignValidInterceptor logInterceptor() {
        SignValidInterceptor signValidInterceptor = new SignValidInterceptor();
        signValidInterceptor.excludePathPattern("GET", "/swagger/**");
        //        .excludePathPattern("GET", "/");
        return signValidInterceptor;
    }
    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(logInterceptor())
                //.excludePathPatterns("/swagger/**")
                .addPathPatterns("/**");
    }
```    

xml

```xml
    <mvc:interceptors>
        <mvc:interceptor>
            <mvc:mapping path="/**"/>
            <bean id="signValidInterceptor" class="com.wmg.tools.interceptor.SignValidInterceptor">
            </bean>
        </mvc:interceptor>
    </mvc:interceptors>
```

https://github.com/spring-projects/spring-framework/blob/376434eb7545c39dcc7f8f87a28eeb9f26bbfd6e/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/InterceptorRegistration.java#L130

您好，我在使用 `javaConfig `配置拦截器时，发现其对`swagger`接口不生效。
debug代码时，发现`InterceptorRegistration `将`HandlerInterceptor` 包装 `MappedInterceptor `时 没有把 `MappedInterceptor `实例放入容器。

以至于在 `org.springframework.web.servlet.handler.AbstractHandlerMapping.detectMappedInterceptors`
中 找不到 `MappedInterceptor`的实例，

`org.springframework.web.servlet.handler.AbstractHandlerMapping#initApplicationContext`

故而不能为`PropertySourcedRequestMappingHandlerMapping` 添加 `adaptedInterceptors`，
使得拦截器不拦截`PropertySourcedRequestMappingHandlerMapping` 类型的接口，例如`Swagger`的 `/v2/api-docs` 接口。

```	java
	mappedInterceptors.addAll(
				BeanFactoryUtils.beansOfTypeIncludingAncestors(
						obtainApplicationContext(), MappedInterceptor.class, true, false).values());
	}
```

**Comment by sbrannen** [comment]
@minggen, can you please either edit your description to use English or provide a comment in English that explains what you find inconsistent?

Thanks

**Comment by minggen** [comment]
Hello, I found it didn't make sense to iterator `swagger` when I use `javaConfig` on interceptor configuration.

When xml and javaConfig are used in the same interceptor, javaConfig didn't work on swagger /v2/api-doc.

Also, I create a demo about this issue [https://github.com/minggen/springmvc-questions], and the issue could be reproduced when modifying  `com.example.demo.config.AutoConfig` .

- When using xml configuration, there is no return value after calling http://localhost:8080/v2/api-docs .

- When using annotation configuration, the right return value would not be intercepted properly.

When I try to figure out the reason, in [this line of code](https://github.com/spring-projects/spring-framework/blob/376434eb7545c39dcc7f8f87a28eeb9f26bbfd6e/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/InterceptorRegistration.java#L130), I  found `InterceptorRegistration` will wrap the custom interceptor into an instance of the `MappedInterceptor` class, and then put the instance into `interceptors`, but not into the `applicationContext`,  so that `adaptedInterceptors` cannot be added for ` PropertySourcedRequestMappingHandlerMapping`. As a result,  the interceptor will not take effect.

```java
mappedInterceptors.addAll(
 BeanFactoryUtils.beansOfTypeIncludingAncestors(
  obtainApplicationContext(), MappedInterceptor.class, true, false).values());
```

**Comment by azouever** [comment]
I spent a long time  to set the interceptor for `/v2/api-docs` by java config ,  but not working;  eventually used  xml  ; spring-boot-starter-parent
2.1.4.RELEASE

**Comment by rstoyanchev** [comment]
Why not declare your interceptor as an `@Bean` of type `MappedInterceptor`, i.e. not using the `InterceptorRegistry` at all? The registry is for interceptors applied to the `HandlerMapping` beans of the MVC config.

**Comment by azouever** [comment]
do this ,but still not work , you can click here(i write the demo) :   https://github.com/azouever/demo 

Here: https://github.com/azouever/demo/blob/master/src/main/java/com/example/demo/InterceptorConfig.java

and  curl localhost:8080/v2/api-docs

**Comment by rstoyanchev** [comment]
That is not what I meant. I suggested to not use the InterceptorRegistry but to declare MappedInterceptor as a bean. The example does the opposite. 

Please, review the Javadoc for `MappedInterceptor`. When it is declared as a bean it is auto-detected directly by all sub-classes of AbstractHandlerMapping and that's an alternative to using the InterceptorRegistry.
