### ISSUE TITLE
can support ConnectionPoolDataSource ?

### ISSUE THREAD

**Issue by gMan1990** [spring-projects/spring-framework#24954]
https://github.com/spring-projects/spring-framework/blob/5721c747b26665ccf1afb5e823b9774be2bffbcf/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java#L164

getPooledConnection().getConnection()

**Comment by jhoeller** [comment]
`ConnectionPoolDataSource` is not meant to be used in application code and is therefore not a candidate for Spring's data access delegates either. It's rather an SPI for connection pool implementors which in turn expose a regular `DataSource` interface to applications.
