### ISSUE TITLE
ResourceUtils.isUrl not considers classpath*: a valid protocol

### ISSUE THREAD

**Issue by vkochnev** [spring-projects/spring-framework#24979]
**Affects:** \5.2.5

Discovered when trying to set `spring.cloud.bootstrap.location` to something like `classpath*:/config/`, but it didn't work because internally SpringBoot calls `org.springframework.util.ResourceUtils#isUrl` with supplied location and when receives `false` prepends it with `file:`. As a result it ends up with `file:classpath*:/config/` in my case, which is obviously incorrect.

### Expected result
`ResourceUtils.isUrl("classpath*:/some/path/") == true` just like in case of another pseudo-protocol `classpath:`.

**Comment by jhoeller** [comment]
If pattern support is desirable as well, then the method to use is `org.springframework.core.io.support.ResourcePatternUtils#isUrl`. The regular `ResourceUtils` is only really designed for single resource scenarios, not for matching patterns into multiple resources.

So if Boot intends to supports patterns there, it should simply call `ResourcePatternUtils` instead.
