### ISSUE TITLE
Connection not closed in WebFlux when JVM fatal error is raised on parallel Scheduler

### ISSUE THREAD

**Issue by czjxy881** [spring-projects/spring-framework#24975]
### Bug Description
When there is an jvm exception occur on Schedulers.parallel or other async thread pool, the connection will not close after the sever already finish the request.

### Example
```java
@GetMapping("test_exception")
public Mono<Object> handleEvent() {
	return Mono.just(true).subscribeOn(Schedulers.parallel()).map(x -> {
		throw new StackOverflowError("test");
	});
}
```
the server already throw exception
![image](https://user-images.githubusercontent.com/3929477/80300284-d9c78b00-87cd-11ea-89ec-5a80055cdc80.png)
but not finish the connection
![image](https://user-images.githubusercontent.com/3929477/80300289-e4822000-87cd-11ea-8447-0f85c4b7a38f.png)

### Probable Cause
- I read the code, and found when the exception is fatal error, it will direct throw the exception in thread pool without cancel subscription
- this is where the exception throw
![image](https://user-images.githubusercontent.com/3929477/80300348-83a71780-87ce-11ea-92e9-a071856e30e8.png)
- then, it go to the onNextError reactor.core.publisher.Operators#onNextError(T, java.lang.Throwable, reactor.util.context.Context, org.reactivestreams.Subscription)
![image](https://user-images.githubusercontent.com/3929477/80300359-9588ba80-87ce-11ea-8004-8824eb4ea165.png)
- just throw without cancel
![image](https://user-images.githubusercontent.com/3929477/80300362-9d485f00-87ce-11ea-9e7f-e74d60faf280.png)
- then the reactor.core.scheduler.SchedulerTask#call catch the ex, but still not call onError to cancel subscribtion
![image](https://user-images.githubusercontent.com/3929477/80300380-c8cb4980-87ce-11ea-80ea-51a5f439788a.png)

**Comment by rstoyanchev** [comment]
I can confirm the issue. It's easy to reproduce but only with both `subscribeOn(Schedulers.parallel())` and the exception being a "fatal" error.

From what I can see operators are propagating the error with `Exceptions.throwIfFatal(error)` via `Operators#onOperatorError` until it eventually reaches a [catch close in HttpServerHandle](https://github.com/reactor/reactor-netty/blob/c39404fa82c1a0020226cbd34dc577a09f673f8e/src/main/java/reactor/netty/http/server/HttpServerHandle.java#L67-L70) which closes the connection. However when  `subscribeOn` is used the error ends at `SchedulerTask` and nothing happens in the rest of the chain.

@sbasle what is your read on this? I don't see what we can do from a Spring Framework perspective  as there are no further signals.

**Comment by simonbasle** [comment]
@rstoyanchev @violetagg I don't know, I have no particular take. How would a blocking server react to something running in a `new Thread()` triggering an `OutOfMemoryException`? Does the exception ends up in the global uncaught exception handler and if so, can that help ?

**Comment by rstoyanchev** [comment]
I'm afraid there isn't much we can do in case of a SO exception other than let it bubble up. If the handling happens in the Netty thread then that will be caught by Reactor Netty, but with doOnSubscribe it simply bubbles out of the Scheduler thread and all we can do is log it.

Even if you were to catch this error within your code, there isn't much you could do with a StackOverflowException. You'll need to find and address the root cause for that overflow.
