### ISSUE TITLE
SpringFactoriesLoader should filter out duplicates

### ISSUE THREAD

**Issue by aclement** [spring-projects/spring-framework#24985]
Whilst doing some testing that caused duplicate `META-INF/spring.factories` files on the classpath it became apparent that the Spring loading wasn't filtering out duplicates.  There are some pieces of code (for example in Spring Data) that were checking 'how many implementations are there' to determine whether to switch to a multi-provider handler or not. In those cases the code was discovering there were two implementations but in fact they were the same thing (exact same name).

**Comment by sbrannen** [comment]
Thanks for bringing this to our attention.

Making this change would align the semantics of `SpringFactoriesLoader` with those of `java.util.ServiceLoader` in this regard:

> If a particular concrete provider class is named in more than one configuration file, or is named in the same configuration file more than once, then the duplicates are ignored.
