### ISSUE TITLE
AbstractReactiveTransactionManager bug

### ISSUE THREAD

**Issue by qinarmy-zoro** [spring-projects/spring-framework#25000]
org.springframework.transaction.reactive.AbstractReactiveTransactionManager#doGetTransaction method's return type should be Mono<Object> ,because maybe will go to get Connecion.

**Comment by snicoll** [comment]
I am not sure I understand what you're trying to report, nor what bug you've encountered. `doGetTransaction` is a protected method that is called within the scope of a `map` operation.
