### ISSUE TITLE
@Repository and custom scheduler switch mechanism problem when using reactor

### ISSUE THREAD

**Issue by marcinsobejko** [spring-projects/spring-framework#25008]
**Affects:**  5.2.0.RELEASE

`org.springframework.aop.framework.ReflectiveMethodInvocation` will crash suddenly when `@Respository` is used on Bean and invocation of method is made on another scheduler. In this case switching to another scheduler is done by custom AOP mechanism:

[Link](https://github.com/marcinsobejko/spring-data-problem) to github project that shows this problem.

Run `com.sobejko.marcin.springdata.problem.ReactorAopTestServiceTest#test`

**Comment by snicoll** [comment]
@marcinsobejko sorry it took so long to process this. I've upgraded your sample to a supported version of the framework and I can no longer reproduce the issue.
