### ISSUE TITLE
gradle dependency 

### ISSUE THREAD

**Issue by huifer** [spring-projects/spring-framework#25009]
- spring framework version : 5.2.3.RELEASE
- I introduced the following dependency when creating the subproject, but I did not find the dependency in the idea
```
plugins {
    id 'java'
}

group 'org.springframework'
version '5.2.3.RELEASE'

repositories {
    mavenCentral()
}

dependencies {
    compile(project(":spring-beans"))
    compile(project(":spring-core"))

    testCompile group: 'junit', name: 'junit', version: '4.12'
}

```
- gradle config 
![image](https://user-images.githubusercontent.com/26766909/80976040-843a5080-8e55-11ea-9732-1e83542afe89.png)

- Abnormal warehouse:  https://github.com/SourceHot/spring-framework-read/tree/source-hot-5.2.3/source-hot-spring-overview

**Comment by bclozel** [comment]
Declaring a Gradle dependency with `project(":module-name")` means that you're declaring a dependency to a module within your project. I can't see such a module in your project.

You might want to take a look at [the declaring dependencies section in the Gradle reference docs](https://docs.gradle.org/current/userguide/declaring_dependencies.html). For further questions, please use StackOverflow as this tracker is dedicated to Spring Framework bugs and enhancement requests.
Thanks,

**Comment by huifer** [comment]
> Declaring a Gradle dependency with `project(":module-name")` means that you're declaring a dependency to a module within your project. I can't see such a module in your project.
> 
> You might want to take a look at [the declaring dependencies section in the Gradle reference docs](https://docs.gradle.org/current/userguide/declaring_dependencies.html). For further questions, please use StackOverflow as this tracker is dedicated to Spring Framework bugs and enhancement requests.
> Thanks,


![image](https://user-images.githubusercontent.com/26766909/81027421-4f0f1c00-8eb0-11ea-85b2-d21a0c7f65ad.png)  `source-hot-spring-overview` just my son project , I hope it relies on the spring framework , But it couldn't find it
