### ISSUE TITLE
Grammatical mistake in PathMatchConfigurer#setUseSuffixPatternMatch's comment

### ISSUE THREAD

**Issue by ijliym** [spring-projects/spring-framework#25018]
See the image below, where the arrow points maybe lost a `no`.

![image](https://user-images.githubusercontent.com/43025881/81139425-53aeff80-8f98-11ea-899e-787334fa184d.png)

Commit title: `Turn off use of path extensions by default`;
Commit revision number: `147b8fb75550ebe25ebdae6a42af74c61b24439f`.

**Comment by rstoyanchev** [comment]
Thanks for spotting that, I've fixed it. For future reference, on such recent commits please add comments directly on the specific line of the commit.

**Comment by ijliym** [comment]
OK.
