### ISSUE TITLE
HttpHeaders equals may return false without comparing actual content

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#25034]
In 5.1 `HttpHeaders` became a `MultiValueMap` and it became possible to wrap existing `HttpHeaders` instances rather than copy their contents. As a result it's possible to have multiple `HttpHeaders` wrappers around the actual `MultiValueMap` content.

The `equals` method tries to compare the `MultiValueMap` content by nesting on the `headers` field but if the levels of nesting are uneven, it may return false. For example:

```java
HttpHeaders headers1 = new HttpHeaders();
HttpHeaders headers2 = new HttpHeaders(new HttpHeaders(headers1));

assertThat(headers1.equals(headers2)).isTrue(); // Pass
assertThat(headers2.equals(headers1)).isTrue(); // Fail
```

**Comment by jhoeller** [comment]
Let's backport this to 5.1.x as well then, given that it dates back to a 5.1 change... and that the `equals` implementation seems to be the same.

**Comment by snicoll** [comment]
This is a binary incompatible change that breaks Spring REST docs, can we please reconsider it?

**Comment by jhoeller** [comment]
It seems that the accepted argument got relaxed from `HttpHeaders` to `MultiValueMap<String, String>` which is source compatible but not binary compatible. The relaxed variant only seems to be used in master, so I suppose we'll keep it as an overloaded variant there, even if we still have to reintroduce the old signature there as well.

We need to change the signature back to the original in 5.2.x and 5.1.x. I've got a few other things to backport as well, so I'll take care of it.
