### ISSUE TITLE
HttpHeaders equals may return false without comparing actual content

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#25035]
Backport of gh-25034

**Comment by spring-issuemaster** [comment]
Fixed via b22e67066821eb89516f40c6d3e49012c1aada6f

**Comment by jhoeller** [comment]
Reopened for the binary compatible breakage reported in gh-25034.

**Comment by spring-issuemaster** [comment]
Fixed via 4b7890315f3884705fa7c308e615f83fe2ddef17
