### ISSUE TITLE
MockHttpServletRequest parse uri query params

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#25042]
**Affects:** 5.2.0.RELEASE

Currently the following returns an **empty** map:
`new MockHttpServletRequest( "GET", "http://test.com?a=b" ).getParameterMap()`

URI should be parsed and query parameters returned.

**Comment by rstoyanchev** [comment]
This is equivalent to:
```java
MockHttpServletRequest = new MockHttpServletRequest();
request.setMethod("GET");
request.setRequestURI("...")'
```

The argument maps to `HttpServletRequest#getRequestURI` which is [defined as follows](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getRequestURI--):
> Returns the part of this request's URL from the protocol name up to the query string in the first line of the HTTP request.

**Comment by rstoyanchev** [comment]
If you want a higher level builder, perhaps using `MockMvcRequestBuilders` could help.
