### ISSUE TITLE
Add ResponseEntity.created(void) overload

### ISSUE THREAD

**Issue by michael-o** [spring-projects/spring-framework#25068]
**Affects:** 5.2.5.RELEASE

---
https://tools.ietf.org/html/rfc7231#section-6.3.2 says the location URI is optional. For a `PUT` request the effective URI is already provided by the client. Please provide the `ResponseEntity.created()` overload additionally to `ResponseEntity.created(URI) `.

**Comment by amaralani** [comment]
Is someone working on this? May I take it?

**Comment by rstoyanchev** [comment]
**Team Decision:** The static methods in `ResponseEntity` are for the most common scenarios only. The rest should still be possible to do.
