### ISSUE TITLE
Publish documentation under reference/html folder

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#25071]
Most Spring projects publish their documentation under a `/html` or `/htmlsingle` subfolder. Spring Framework used to do this as well [in 4.x](https://docs.spring.io/spring-framework/docs/4.3.x/spring-framework-reference/) but in 5.x [it changed](https://docs.spring.io/spring-framework/docs/5.0.x/spring-framework-reference/).

For consistency with other projects, it would be nice to have the `/html` folder back.

See https://github.com/spring-projects/spring-security/issues/8420 for a similar request in Spring Security.

**Comment by liam33893** [comment]
Yes, please! /htmlsingle is a convenient way to find the required information very fast! We in our team use this method all the time.

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 RC1 for _team attention_

**Comment by sdeleuze** [comment]
I can probably take care of it for 5.3 RC1. I guess we should publish the doc to `reference/html/`.
