### ISSUE TITLE
Cannot update log level of SimpleBrokerMessageHandler using actuator

### ISSUE THREAD

**Issue by nickcaballero-mm** [spring-projects/spring-framework#25082]
The log level used by `SimpleBrokerMessageHandler` cannot be updated via actuator. When debugging, it seems that it uses a `org.springframework.core.log.CompositeLog` that determines the log levels when creating the instance. This means that the only way to increase the logging level is to stop the server and update the configuration.

As a workaround, we can start the server with a higher logging level and then reduce it using actuator once server has started.

**Affects:** spring-messaging 5.2.5.RELEASE

**Comment by jhoeller** [comment]
This should be addressed through #28477 as of 5.3.21 now.
