### ISSUE TITLE
Missing null checks in AbstractMessageChannel.addInterceptor

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#25089]
Backport of gh-25088

**Comment by jhoeller** [comment]
Since we don't generally assert against `null` in `Collection` arguments in 5.1.x, not even in `RestTemplate`, not even having a convenience method for it in `Assert`, I opted for making it consistent with that line through simply adding assertions to the `addInterceptor` methods.

**Comment by spring-issuemaster** [comment]
Fixed via 4ec02a7e53175159560f97d3a9d376843a399949
