### ISSUE TITLE
DefaultServerRequestBuilder does not respect attributes when building the ServerRequest

### ISSUE THREAD

**Issue by sergiisinelnychenko** [spring-projects/spring-framework#25106]
**Affects:** \<5.2.6>

spring-webflux. The class **org.springframework.web.reactive.function.server.DefaultServerRequestBuilder** does not respect **attributes** when building the **org.springframework.web.reactive.function.server.ServerRequest**. 
When you use
`
ServerRequest.from(initialRequest)
                .attribute("somename", "somevalue")
                .build();
`
- the resulting ServerRequest does not have the attribute specified. Could be easily tracked by source code
---

**Comment by sbrannen** [comment]
Indeed, the attributes are not copied to the `ServerWebExchange` that backs the request.

Thanks for pointing this out.

**Comment by sbrannen** [comment]
This has been fixed in `5.1.16`, `5.2.7`, and `5.3 M1`.

Feel free to try it out in the latest snapshots for those branches.
