### ISSUE TITLE
MonoToListenableFutureAdapter should not be in the package:org.springframework.util.

### ISSUE THREAD

**Issue by zinu-x** [spring-projects/spring-framework#25123]
The package {@code org.springframework.util} is the lowest-level abstraction for jdk。

I think the package  should not be dependent on any third-party libraries.

**Comment by jhoeller** [comment]
Indeed, `org.springframework.util` is generally about low-level JDK utilities, and a Reactor dependency is the odd one out there. That said, we also allow Commons Logging dependencies in that package and used to allow other Apache Commons dependencies as well, in an optional form. That same guideline still applies: We aim to avoid third-party dependencies there but do allow them in an optional form if they fit with the general abstraction level, e.g. ListenableFuture adapters.
