### ISSUE TITLE
QueryDslPredicateExecutor should support deleting by predicate

### ISSUE THREAD

**Issue by yissacharcw** [spring-projects/spring-framework#25134]
**Affects:** \5.2.6.RELEASE

[QueryDslPredicateExecutor](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/querydsl/QuerydslPredicateExecutor.java) supports querying by a QueryDsl predicate but does not support  deleting items by a Predicate. It would be useful to also support deletion via predicate.

**Comment by snicoll** [comment]
Thanks for the report but the link you've provided is in the Spring Data project. This is the issue tracker for the core Framework. Please create that request [in the appropriate issue tracker](https://jira.spring.io/projects/DATACMNS/issues).
