### ISSUE TITLE
run CglibProxyControllerTests have NullPointerException

### ISSUE THREAD

**Issue by liangkunJoin** [spring-projects/spring-framework#25139]
logger is null 

when run 

if (logger.isTraceEnabled()) {
			logger.trace("Mapped to " + handler);
		}
		else if (logger.isDebugEnabled() && !request.getDispatcherType().equals(DispatcherType.ASYNC)) {
			logger.debug("Mapped to " + executionChain.getHandler());
		}

this have NullPointerException

**Comment by liangkunJoin** [comment]
`public final HandlerExecutionChain getHandler(HttpServletRequest request) throws Exception {
		Object handler = getHandlerInternal(request);
		if (handler == null) {
			handler = getDefaultHandler();
		}
		if (handler == null) {
			return null;
		}
		// Bean name or resolved handler?
		if (handler instanceof String) {
			String handlerName = (String) handler;
			handler = obtainApplicationContext().getBean(handlerName);
		}

		HandlerExecutionChain executionChain = getHandlerExecutionChain(handler, request);

		if (logger.isTraceEnabled()) {
			logger.trace("Mapped to " + handler);
		}
		else if (logger.isDebugEnabled() && !request.getDispatcherType().equals(DispatcherType.ASYNC)) {
			logger.debug("Mapped to " + executionChain.getHandler());
		}

		if (CorsUtils.isCorsRequest(request)) {
			CorsConfiguration globalConfig = this.corsConfigurationSource.getCorsConfiguration(request);
			CorsConfiguration handlerConfig = getCorsConfiguration(handler, request);
			CorsConfiguration config = (globalConfig != null ? globalConfig.combine(handlerConfig) : handlerConfig);
			executionChain = getCorsHandlerExecutionChain(request, executionChain, config);
		}`

**Comment by sbrannen** [comment]
I assume you're talking about `org.springframework.web.servlet.mvc.annotation.CglibProxyControllerTests`; however, the tests in that class pass for me and also on all CI builds.

In light of that, I am closing this issue.

If you are encountering issues with a local build, please consult the [Build from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) wiki page.
