### ISSUE TITLE
Missing reference documentation for WebSocketScope

### ISSUE THREAD

**Issue by tamaro-skaljic** [spring-projects/spring-framework#25172]
**Affects:** 5,2,6.RELEASE

---
Didn't find any reference documentation about defining a WebSocketScope that mentioned at https://docs.spring.io/spring/docs/5.2.6.RELEASE/spring-framework-reference/core.html#beans-factory-scopes-other

**Comment by rstoyanchev** [comment]
It's there but in the Servlet/Web section and it's linked a little earlier from the [table with bean scopes](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-factory-scopes). However, it needs another mention from the section you were reading.
