### ISSUE TITLE
Why remove org.springframework.cache.guava.GuavaCacheManager in Spring 5.0?

### ISSUE THREAD

**Issue by steveguoshao** [spring-projects/spring-framework#25189]
In Spring 5.0, I found GuvaCache and GuavaCacheManager has been removed,  and use CaffeineCacheManager instead, remove a class is Incompatible behavior，GuvaCache and GuavaCacheManager can been recovery?

**Comment by snicoll** [comment]
Doing so in a new major release is acceptable, please review [the release notes and upgrade instructions](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#dropped-support) before creating an issue.

**Comment by bclozel** [comment]
See #18370
