### ISSUE TITLE
Spring not showing reason in RuntimeException class

### ISSUE THREAD

**Issue by RochaKaique** [spring-projects/spring-framework#25188]
Spring version: 2.3.0.RELEASE
Java Version: 8

I'm trying to handle de reason of a excetopn class:
```java
@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Cartão inválido")
    public class CartaoDebitoInvalidException extends RuntimeException {
}
```

In my service class I call the exception this way:
 ```java
throw new CartaoDebitoInvalidException();
```

But the reason is noa appearing in the response: 

```json
{
    "timestamp": "2020-06-05T00:12:37.391+0000",
    "status": 404,
    "error": "Not Found",
    "message": "",
    "path": "/pagar_debito"
}
```

Note: It works in version 2.2.7.RELEASE

**Comment by bclozel** [comment]
I believe this is working as designed. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content
