### ISSUE TITLE
RestTemplate adds Content-Length for multipart form-data

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-framework#25195]
by using `curl -F "foo=123;type=text/plain" url.com`, it give the following output:
```
Content-Disposition: form-data; name="foo"
Content-Type: text/plain

123
```

However, by using RestTemplate, it adds `Content-Length` in `MessageConverter addDefaultHeaders` methods, so the result becomes:
```
Content-Disposition: form-data; name="foo"
Content-Type: text/plain;charset=UTF-8
Content-Length: 3

123
```
And this Content-Length causes trouble to the other end server, that it could not understand. And I was thinking, since boundary is used to identify the boundary, can Content-Length be removed?

**Comment by poutsma** [comment]
There is currently no way to remove the Content-Length header, but there are ways to work around this problem.

One option is to create a custom subclass of (for instance) the `StringHttpMessageConverter` and override the `addDefaultHeaders` method to return null.

Another option would be to use an `ClientHttpRequestInterceptor` to intercept the request body, and remove the Content-Length header from it. This does cache the entire body in memory, so not recommend for large file uploads.
