### ISSUE TITLE
Update documentation - @Cacheable cannot be used on @PostConstruct

### ISSUE THREAD

**Issue by robertobatts** [spring-projects/spring-framework#25202]
I found out that @Cacheable cannot be used on a @PostConstruct because CacheAspectSupport may be initialized after the components on which I'm calling the cache.
I saw this has already been mentioned in this closed issue #17297 but the documentation hasn't been updated.

**Comment by snicoll** [comment]
The documentation mentions this, actually see the note [at the of this section](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#cache-annotation-enable).
