### ISSUE TITLE
UriComponentsBuilder does not resolve regex path variables

### ISSUE THREAD

**Issue by spc16670** [spring-projects/spring-framework#25246]
**Affects:** 5.2.5

---

```
System.out.println("template:: " + templateStr);
UriComponents uriComponents = UriComponentsBuilder.fromUriString(templateStr).build();
System.out.println(uriComponents.getPathSegments());
```

template:: http://localhost/{urlLocale:[a-z](?:-[a-z])?}/quotes/1
[{urlLocale:[a-z](]

Looks like the ? in regex is breaking the resolution.

**Comment by dPechman42** [comment]
Could you please explain what your regex is trying to do.
It appears that after the first '?' that the rest of the url is being saved as a query.

**Comment by snicoll** [comment]
I don't understand why you'd want to use a regexp as a path variable. There is already a warning about the use of special characters in the Javadoc of `UriComponentsBuilder#fromUriString`.
