### ISSUE TITLE
The AbstractTemplateViewResolver class is not abstract

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#25240]
**Affects:** \5.2.6.RELEASE and minor (since 1.1)

---

If I see the javadoc of the [AbstractTemplateViewResolver](https://docs.spring.io/spring/docs/5.2.6.RELEASE/javadoc-api/org/springframework/web/servlet/view/AbstractTemplateViewResolver.html) class, it indicates:

```
public class AbstractTemplateViewResolver
extends UrlBasedViewResolver

Abstract base class for template view resolvers, in particular for FreeMarker views.
```

Well the class really is not abstract how is expected.

Of course it comes from the source code:

* [AbstractTemplateViewResolver.java](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/view/AbstractTemplateViewResolver.java)

**Comment by jhoeller** [comment]
Well spotted! This class is primarily named after `AbstractTemplateView` (which is actually `abstract`) but nevertheless does not make sense as a concrete class (so should be declared `abstract` indeed).

**Comment by jhoeller** [comment]
It turns out that there are two more such cases: `AbstractJCacheConfiguration` and `AbstractJmxAttribute`. I'll fix those along with this issue.

**Comment by manueljordan** [comment]
No problem, I was doing a tech review for a book and I did realize this situation ... I had the doubt to arise or not this ... and well really is a bug
