### ISSUE TITLE
404 rather than 405

### ISSUE THREAD

**Issue by MRDcoder** [spring-projects/spring-framework#25249]
Hi Team,

I am getting 405 instead of 404 if the URL is not available. I looked into the existing issue and found that there is PR https://github.com/spring-projects/spring-framework/pull/962 which is merged. So, I have updated the spring framework to the latest version but still facing the same issue. 

for example : 
valid URL is **/employee/1/attendance** 

if user try to hit **/employee/1/atten** which is not valid, they will get 405 indicating URL is correct but the method is not valid 

Please have a look and let me know in case of more clarifications:).

/Mudassar

**Comment by bclozel** [comment]
Please provide a sample application that shows the issue. The issue you're linking to might not be related.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
