### ISSUE TITLE
Open single spring project

### ISSUE THREAD

**Issue by andresetevejob** [spring-projects/spring-framework#25259]
Hi all,
I have cloned the spring github repository and and i have build the all project.It's possible to open in inteelij idea community, a single project like spring-orm and working on without open all the spring projects.
When i open the spring-orm project in intellij idea.This is message that the ide show me : Task 'wrapper' not found in project ':spring-orm'.

**Comment by bclozel** [comment]
Hello @andresetevejob 

Unfortunately, the way our build is set up, it's not possible to import a single project.
Many projects depend on each other, and the main build itself is contributing plugins and configuration to all. The Gradle wrapper is located at the root of the project.

Thanks
