### ISSUE TITLE
Use neutral terminology instead of oppressive language

### ISSUE THREAD

**Issue by nealeu** [spring-projects/spring-framework#25262]
Let's please do this:

- blacklist / whitelist -> blocklist / allowlist
- change `master` branch to `main`
- white/black box testing -> clear/opaque

It's time!

**Comment by sbrannen** [comment]
Within the Spring Framework, work has already been done in a2d516d526b482c5824429480963dc92eb2fcd2f and 972c01cbbd8c99c9c175519dbbae67751c567d86 to avoid the use of whitelist / blacklist.

Are you aware of any further usage of those terms in Spring Framework?

Changing the name of the `master` branch to `main` is something that is being considered, but it will require further investigation to determine how best to do that with minimal impact on the community and contributors.

Regarding the terms white box and black box, I am not aware of any such usage within the Spring Framework. Were you listing general things that one could change, or are you aware of any further usage of those terms in Spring Framework?

**Comment by sbrannen** [comment]
> Regarding the terms white box and black box, I am not aware of any such usage within the Spring Framework. Were you listing general things that one could change, or are you aware of any further usage of those terms in Spring Framework?

I apologize: I made a mistake in my search.

The term black box appears in examples that use the `Blackbox CCI connector` from the JDK (`com.sun.connector.cciblackbox.CciConnectionSpec`). In that context, it is challenging to avoid use of the term. Otherwise, use of the term "black box" has now been removed in 9acb5b1a4aba8b8f8cdd070cccfbf43e2e9c5666.

Regarding the term "whitelist" in the Gradle build, see https://github.com/spring-io/nohttp/issues/37.

**Comment by dsyer** [comment]
I think you missed the extensive example in `core-beans.adoc`. Probably easy to rename that, since it's just an example in docs.

**Comment by nealeu** [comment]
Thanks for being on to this.  Look forward to master going and being only referenced in history lessons.  We've gone with main.  
It's good that it will disrupt developers that tiny little bit :-)

**Comment by sbrannen** [comment]
> I think you missed the extensive example in `core-beans.adoc`. 

Thanks, @dsyer! 👍 

I'll address that.

**Comment by sbrannen** [comment]
> I think you missed the extensive example in `core-beans.adoc`. Probably easy to rename that, since it's just an example in docs: https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/core/core-beans.adoc#standard-and-custom-events.

Addressed in 46c786167edbf3e89e4775acd7f7707f0963b1b0

**Comment by sbrannen** [comment]
See also: https://tools.ietf.org/id/draft-knodel-terminology-00.html

**Comment by sbrannen** [comment]
As far as I can tell, we have addressed the usage of whitebox/blackbox and whitelist/blacklist in the `5.2.x` and `master` (i.e., `5.3.x`) branches.

The only remaining task is the renaming of the `master` branch, and I have tentatively slated this issue for 5.3 M2 as a placeholder to consider that.

**Comment by sbrannen** [comment]
> The term black box appears in examples that use the `Blackbox CCI connector` from the JDK (`com.sun.connector.cciblackbox.CciConnectionSpec`). In that context, it is challenging to avoid use of the term.

In conjunction with #25287, that section of the reference manual has been removed in 3a653bd35fa70c96aa9cf4cc52bfe928bbed7ff2 for Spring Framework 5.3+.

**Comment by sbrannen** [comment]
Additional changes to wording in the reference manual have been addressed in conjunction with #25314.

In light of that, I am closing this issue.

> The only remaining task is the renaming of the `master` branch, and I have tentatively slated this issue for 5.3 M2 as a placeholder to consider that.

If renaming of the `master`/default branch occurs, that would likely take place as a coordinated effort across the Spring portfolio projects.

**Comment by rudiservo** [comment]
I would never think that a martial arts master would be oppressive... I actually resent such a wild claim about the word "master".
