### ISSUE TITLE
Snapshot introduces breaking change

### ISSUE THREAD

**Issue by elliedori** [spring-projects/spring-framework#25271]
Hi team,

It looks like the current snapshot version of spring-framework introduces breaking changes, potentially because of the Kotlin upgrade. We're seeing `org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call` errors in the spring security repository when we run our snapshots tests. We tried updating our Kotlin version locally to the one used in the current spring-framework snapshot to see if it would resolve the issue, but the issue persisted.

We put up a sample project that re-creates the error – you can reference it [here](https://github.com/eleftherias/spring-kotlin-expect-test) and can duplicate the error case by running the project's tests. Another example of the issue can be found in [this Jenkins build](https://jenkins.spring.io/job/spring-security/job/master/2962/execution/node/55/log/).

**Please note that this is currently blocking the spring security team's builds.** Thank you!

**Comment by erokhins** [comment]
Hi! I'm from the Kotlin team. Unfortunately I don't have the permissions to see the build. Could you please attach the log file from the build or at least the full stack trace?

**Comment by erokhins** [comment]
Never mind, I reproduced it locally and write the corresponding exception here: https://youtrack.jetbrains.com/issue/KT-39671

**Comment by sdeleuze** [comment]
We have decided to rollback to Kotlin 1.3 for now, we will make a new try in Spring Framework 5.3 M2 timeframe and I will check it does not break Spring Security @elliedori. Thanks for reporting this.
