### ISSUE TITLE
Support multiple Content-Language header values in MockHttpServletResponse

### ISSUE THREAD

**Issue by abollini** [spring-projects/spring-framework#25281]
**Affects:** 5.x+

---
The current code in https://github.com/spring-projects/spring-framework/blob/3aa2605fdaa56d5c007f476f3f9bd1c550ec368c/spring-test/src/main/java/org/springframework/mock/web/MockHttpServletResponse.java#L641-L644

prevent to set multiple languages in the response Content-Language header. A value of "en, it" is translated to the "en" Locale and the subsequent call to setLocale 

https://github.com/spring-projects/spring-framework/blob/3aa2605fdaa56d5c007f476f3f9bd1c550ec368c/spring-test/src/main/java/org/springframework/mock/web/MockHttpServletResponse.java#L344-L346

force the Content-Language to be only "en".

The use of comma separated values for languages is perfectly fine according to the specification, see second example here https://www.w3.org/International/questions/qa-http-and-lang#http_summary

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 M2, _pending design work_.

@rstoyanchev, let me know if you foresee any issues with that.

**Comment by sbrannen** [comment]
This enhancement will be available in upcoming Spring Framework 5.3 M2 snapshots.

Feel free to try it out and report back with any issues you encounter.

**Comment by sbrannen** [comment]
@Romster, please note that this issue was closed almost 5 years ago and that it was specific to `MockHttpServletResponse`.

If you feel there is an issue with `ServletServerHttpResponse`, please [create a new issue](https://github.com/spring-projects/spring-framework/issues/new/choose).
