### ISSUE TITLE
AllEncompassingFormHttpMessageConverter now uses both JAXB and Jackson by default

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#25291]
**Affects:** 5.3 snapshots

When both JAX-B and Jackson are on the classpath, `AllEncompassingFormHttpMessageConverter` will now configure both `Jaxb2RootElementHttpMessageConverter` and `MappingJackson2XmlHttpMessageConverter`. Previously, the latter was preferred. This change in behaviour was introduced in https://github.com/spring-projects/spring-framework/commit/1e501f2583efd7521fe457453e5f866bcb8c509a as the `jackson2XmlPresent` flag is no longer being checked when deciding if `Jaxb2RootElementHttpMessageConverter` should be configured.

**Comment by sdeleuze** [comment]
Fixed, sorry for the glitch, I missed it. Thanks for your report.
