### ISSUE TITLE
Need to know transaction.isReadonly while getting connection - spring-jdbc

### ISSUE THREAD

**Issue by johnny2002** [spring-projects/spring-framework#25323]
Backgroup:  I have a large project with more than 500 nodes need to connection to one Database,  so connection count is too high. In order to reduce db connections, I want to reuse one connection for all readonly transactions. So, I need to get the "TransactionSynchronizationManager.isCurrentTransactionReadOnly()" in Datasource.getConnection() method. While, in spring-jdbc-5.2.2, DataSourceTransactionManager.doBegin method, the connection is gotten at line 263, the readonly flag is setted at line 298.

Suggestion: Set the readonly flag before getting connection. e.g.  in DataSourceTransactionManager.doBegin method

> protected void doBegin(Object transaction, TransactionDefinition definition) {
>     **TransactionSynchronizationManager.setCurrentTransactionReadOnly(definition.isReadOnly());**
>     DataSourceTransactionObject txObject = (DataSourceTransactionObject) transaction;
>     ...
>     **Connection newCon = obtainDataSource().getConnection();**
>     ...

Then I will override a Datasource, that, return one shared connection to all readonly transactions.

**Comment by quaff** [comment]
Is it safe to reuse connection across threads?

**Comment by johnny2002** [comment]
> Is it safe to reuse connection across threads?

for readonly operations, it is.

**Comment by quaff** [comment]
> > Is it safe to reuse connection across threads?
> 
> for readonly operations, it is.

It depends on driver implementation.

**Comment by johnny2002** [comment]
> > > Is it safe to reuse connection across threads?
> > 
> > 
> > for readonly operations, it is.
> 
> It depends on driver implementation.

At least, as I tested, oracle, mysql, pgsql are no problem.

**Comment by johnny2002** [comment]
further more, no matter share connection is safe or not, let developers can get the readonly properties as earlier as possible is a good manner

**Comment by johnny2002** [comment]
> > > Is it safe to reuse connection across threads?
> > 
> > 
> > for readonly operations, it is.
> 
> It depends on driver implementation.

So, what's the decision? will you adopt the change request?

**Comment by eitan613** [comment]
Isn't the readonly flag set at line 277?

**Comment by eitan613** [comment]
@johnny2002  I am trying to write a test method after adding your extra line of code.  But I can't seem to get doBegin to work properly.  It blows up no matter what I pass in as the transaction object. any ideas?

**Comment by snicoll** [comment]
The PR has been declined, reopening to reconsider this.

**Comment by jhoeller** [comment]
This effectively got addressed through #31785 where `LazyConnectionDataSourceProxy` has dedicated support for a read-only DataSource now. And generally, as per #21415, ``LazyConnectionDataSourceProxy` is recommended for lazy-determined DataSource routing based on those thread-local settings.
