### ISSUE TITLE
Creating ServerRequest from MockHttpServletRequest changed behaviour 5.3.0-M1

### ISSUE THREAD

**Issue by jwalter** [spring-projects/spring-framework#25353]
**Affects:** 5.3.0-M1

---
In 5.2.7 we could call ServerRequest.create(MockHttpServletRequest()) in our tests. With 5.3.0-M1 this causes an assert error in ServerRequestPathUtils since it expects a request attribute containing the RequestPath (ServerRequestPathUtils:70).

**Comment by rstoyanchev** [comment]
This is an intentional change since the path is now expected to be parsed once during the handling of a request and saved for re-use. At runtime at least this should have no impact. It does impact tests more however so I've marked this as a regression to explore some solution.
