### ISSUE TITLE
Could not find reactor-core-3.4.0-M1.jar (io.projectreactor:reactor-core:3.4.0-M1).

### ISSUE THREAD

**Issue by kujin521** [spring-projects/spring-framework#25365]
Could not find reactor-core-3.4.0-M1.jar (io.projectreactor:reactor-core:3.4.0-M1).
Searched in the following locations:
    http://nexus.bsdn.org/content/groups/public/io/projectreactor/reactor-core/3.4.0-M1/reactor-core-3.4.0-M1.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by bclozel** [comment]
Reactor and Spring projects Milestone versions are available on the Spring artifactory instance and are not synchronized to Maven Central: https://repo.spring.io/milestone

Please configure your Nexus artifact repository accordingly.
Creating a new project on start.spring.io (using a Spring Boot milestone version) will provide the expected coordinates to resolve these artifacts.
