### ISSUE TITLE
Add support for LHS Brackets from query parameters

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-framework#25362]
LHS Brackets style of query parameters is commonly used, it used by Stripe, GoCardless, and others.
Sample: `htps://domain.com?price[gte]=200&price[lte]=500`

https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#lhs-brackets

Will be great to be possible to map this to the class
```
class Price {
    private Long gte;
    private Long lte;
    // ...
}

class Request {
    private Price price;
    // ...
}
```

It works if the `price` is a `Map`
```
class Request {
    private Map<String, String> price;
    // ...
}
```
But it doesn't work for a `class`.

**Comment by rstoyanchev** [comment]
Data binding uses JavaBean conventions and this is the syntax for maps:
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-beans-conventions

The following works:
```java
public class Request {

	private Map<String, Long> price;


	public Map<String, Long> getPrice() {
		return price;
	}

	public void setPrice(Map<String, Long> price) {
		this.price = price;
	}
}
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by eric-gymondo** [comment]
Hey Guys, I think this feat you be a nice addition to spring in general,  qs does something really cool with being able to parse brackets to objects and objects to brackets https://github.com/ljharb/qs.

I see that the issue was close, does it mean the spring team did not see a value on it?

**Comment by Jotschi** [comment]
I started work on a LHS filter parser for my own project. Found this issue while searching for an existing solution. Maybe someone finds this useful. https://github.com/metaloom/lhs-filter
