### ISSUE TITLE
Spring JMS and ActiveMQ: Automatic JMS message to POJO conversion support.

### ISSUE THREAD

**Issue by ifliunt** [spring-projects/spring-framework#25374]
Right now there is no way to automatically convert JMS message to POJO.
I have to set a type id from consumer side (listener) and a FQDN java name from a producer side for listener to infer(get) the type for message conversion.

The question really is, are there plans to add logic to Spring JMS that will do the automatic conversion?
Is it feasible at all?

```
MappingJackson2MessageConverter converter = new MappingJackson2MessageConverter();
converter.setTypeIdPropertyName("java_type");

other converter settings
```

**Comment by snicoll** [comment]
There is no way to automatically convert JMS messages to POJO as the framework can't determine what the structure of the message should be. The message format is part of your application as it may be used by other components. As such, configuring the converter you do know is the right thing to do.
