### ISSUE TITLE
builder.localeContextResolver is invoked twice in WebHttpHandlerBuilder.applicationContext

### ISSUE THREAD

**Issue by peacetrue** [spring-projects/spring-framework#25389]
**Affects:** \<5.2.6>
![image](https://user-images.githubusercontent.com/38878763/87452259-972a8780-c633-11ea-93a3-3f304bcd4bfc.png)

---

**Comment by sbrannen** [comment]
Good catch!

The duplicated code block was accidentally introduced in a8a1fc6de5be2307eb56844ac1df1a09168f2ad9 (likely due to copy-and-paste). We'll remove that.
