### ISSUE TITLE
Support alias for property name in web data binding

### ISSUE THREAD

**Issue by gitterhh** [spring-projects/spring-framework#25383]
For the class

```java
class Request {
    
    private String ftr;
    // more properties
}
```

And the method in controller class

```java
@GetMapping
public String list(@Valid Request request) {
    //...
}
```

When I send a request to the method the url is `https://example.com?ftr=sms`

Is it possible to have an alias to a query parameter like in the class

```java
class Request {
    
    @QueryParameter(name="ftr")
    private String filter;
    // ...
}
```

And to map same request URL to this class?

**Comment by sbrannen** [comment]
As far as I know, there is no mechanism that supports aliases for properties in web data binding.

**Comment by sbrannen** [comment]
See also #18012 and related issues linked from there.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
