### ISSUE TITLE
Add convert(Object, TypeDescriptor) method to ConversionService

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-framework#25394]
At the moment there is the method

```java
Object convert(@Nullable Object source, @Nullable TypeDescriptor sourceType, TypeDescriptor targetType);
```

And usually `sourceType` can be deduced from `source` and it is unnecessary to specify the `sourceType`. Please add a new `convert` method which will remove necessity to specify the type descriptor if it is the same as `source`.

```java
Object convert(@Nullable Object source, TypeDescriptor targetType) {
    return convert(source, TypeDescriptor.forObject(source), targetType);
}
```

**Comment by sbrannen** [comment]
Does the existing `<T> T convert(@Nullable Object source, Class<T> targetType)` method not meet your needs in terms of convenience?

**Comment by raderio** [comment]
Can you please advise how to use it when I need to convert an object to a `List<T>`?

**Comment by dPechman42** [comment]
Would it be possible for me to work on this?

**Comment by sbrannen** [comment]
> Can you please advise how to use it when I need to convert an object to a `List<T>`?

You would need a target `TypeDescriptor` for that.

**Comment by sbrannen** [comment]
**Team Decision**: assigned to the _General Backlog_ to allow this issue to gain wider community interest.
