### ISSUE TITLE
Please specify the version used for  iText, a JAVA PDF library JAR in spring-webmvc-5.2.4.RELEASE.jaR of AbstractPdfStamperView.class

### ISSUE THREAD

**Issue by Swagatika20** [spring-projects/spring-framework#25486]
Hi Team,

Can you please let me know which version of iText, a JAVA PDF library JAR is used during compilation of `spring-webmvc-5.2.4.RELEASE.jar`.

It's used in the `AbstractPdfStamperView` class of `spring-webmvc`.

**Comment by sbrannen** [comment]
The code was compiled against OpenPDF 1.3.13 as can be seen here:

https://github.com/spring-projects/spring-framework/blob/v5.2.4.RELEASE/build.gradle#L93
