### ISSUE TITLE
Lazy dependency proxy does not populate bean dependencies

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/spring-framework#25562]
Start off with the latest **spring-petclinic** project based on Boot 2.3.x
Launch the app and see the JSON response for `/actuator/beans`
Search for `OwnerController` bean. This bean should depend on `OwnerRepository` and `PetRepository`. The JSON for the bean however is this:
```
        "ownerController": {
          "aliases": [],
          "scope": "singleton",
          "type": "org.springframework.samples.petclinic.owner.OwnerController",
          "resource": "file [/Users/aboyko/Documents/runtime-sts4/spring-petclinic/target/classes/org/springframework/samples/petclinic/owner/OwnerController.class]",
          "dependencies": []
        },
```

If **spring-petclinic** is switched to Boot 2.2.x then the dependencies are detected correctly:
```
        "ownerController": {
          "aliases": [],
          "scope": "singleton",
          "type": "org.springframework.samples.petclinic.owner.OwnerController",
          "resource": "file [/Users/aboyko/Documents/runtime-sts4/spring-petclinic/target/classes/org/springframework/samples/petclinic/owner/OwnerController.class]",
          "dependencies": [
            "ownerRepository",
            "visitRepository"
          ]
        },
```

Something is off in the framework as **actuator** simply calls `org.springframework.beans.factory.config.ConfigurableBeanFactory.getDependenciesForBean(String)`

Try this in the `org.springframework.samples.petclinic.PetClinicApplication` for the **main** method:

```
	public static void main(String[] args) {
		ConfigurableApplicationContext context = SpringApplication.run(PetClinicApplication.class, args);

		final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

		final Runnable printDependnecies = new Runnable() {
			public void run() {
				String[] dependenciesForBean = context.getBeanFactory().getDependenciesForBean("ownerController");
				
				if (dependenciesForBean.length == 0) {
					System.out.println("no dependencies!!!");
				} else {
					System.out.println("Dependencies:");
					for (String dep : dependenciesForBean) {
						System.out.println(dep);
					}
					System.out.println();
				}
			}
		};

		scheduler.scheduleAtFixedRate(printDependnecies, 10, 10, TimeUnit.SECONDS);

	}
```

You'd see that there are no dependencies returned in the Boot 2.3.x case.

**Comment by snicoll** [comment]
@jhoeller I've tentatively assigned `5.2.9`.

**Comment by jhoeller** [comment]
This is more or less by design: Lazy proxy resolution doesn't know the actual targets upfront, and when it's eventually triggered, we cannot populate the original `autowiredBeanNames` mechanism anymore. We'd have to somehow mimic this in a separate code path within the lazy resolution proxy. I'll investigate this as an enhancement, possibly in 5.3 only though.

**Comment by jhoeller** [comment]
I got an implementation that's pretty straightforward, can easily make 5.2.9...

**Comment by jhoeller** [comment]
And since this is somewhat unintuitive indeed when switching to a lazy dependency proxy, I'll consider it a bug fix to backport...

**Comment by martinlippert** [comment]
Did this change make it into the 5.2.10 release? I am trying a pet clinic at Spring Boot 2.3.5 with Framework at 5.2.10 and the bean dependencies for the OwnerController (in our example above) are still empty. Will dive deeper tomorrow, but just wondering whether this fix made it into that version or not.

**Comment by jhoeller** [comment]
@martinlippert see the milestone above - it made it into 5.2.9 and got backported all the way down to 4.3.29. Not sure why it's not working for PetClinic with Boot 2.3.5 still. The fix here was only really addressing the core `@Lazy` problem, maybe some other difference between Boot 2.2 and 2.3 is involved as well?

**Comment by BoykoAlex** [comment]
I'm still seeing the same JSON for the `ownerController` bean with no dependencies and the `main` method snippet prints no bean dependencies (issue description)... Boot 2.3.5 and Spring 5.2.10. The workaround `spring.data.jpa.repositories.bootstrap-mode=default` still makes it work.
Seems like we may need to transfer this to boot now?

**Comment by jhoeller** [comment]
Please note that dependencies behind a lazy proxy are only going to be registered once the proxy is actually being initialized, that is, once a method invocation on the proxy led to the resolution of the target instance. That's the part that the fix addressed here.

**Comment by BoykoAlex** [comment]
@jhoeller Thanks for the last comment that clarified it really :-) Seems to all work as expected now. As soon as I add a new pet owner i see the clinic repo dependency. Think this is great :-)
