### ISSUE TITLE
Declare interfaces as @FunctionalInterface where feasible

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#25580]
As a follow up to #25571, in my opinion, the following are the remaining potential candidates for being annotated with `@FunctionalInterface`, especially the first two.

- `org.springframework.context.ApplicationContextInitializer`
- `org.springframework.test.web.servlet.DispatcherServletCustomizer`
- `org.springframework.validation.MessageCodeFormatter`
- `org.springframework.util.IdGenerator`
- `org.springframework.beans.factory.config.YamlProcessor.MatchCallback`
- `org.springframework.beans.factory.config.YamlProcessor.DocumentMatcher`

**Comment by jhoeller** [comment]
Sounds good to me... Even if it just a formal step since those comply with the convention anyway, let's consistently declare it in 5.3.
