### ISSUE TITLE
Document how to specify Jackson JSON view serialization hints with @RestController and Webflux

### ISSUE THREAD

**Issue by monstrfolk** [spring-projects/spring-framework#25596]
There is not documentation how to filter fields using JsonViews using specific security roles when using Webflux and non-functional endpoints, for example `@RestController`.

There  is a tutorial that explains how to achieve this using MCV.
https://www.baeldung.com/spring-security-role-filter-json

There is another issue that has been closed that explains similar functionality with RouterFunctions and Webflux.
https://github.com/spring-projects/spring-framework/issues/23150

**Comment by rstoyanchev** [comment]
@monstrfolk you have seen https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-jsonview?

**Comment by monstrfolk** [comment]
How can the JsonView be set within the controller method? Would like to set the view dynamically based off of some other property. The 2 examples in original post support dynamically setting the JsonView.

**Comment by rstoyanchev** [comment]
```java
@RestController
public class FooController {

	@GetMapping("/")
	MappingJacksonValue handle() {
		Foo foo = new Foo();
		return new MappingJacksonValue(foo);
	}
}

**Comment by monstrfolk** [comment]
How can something as following be achieved?
`
     @GetMapping("/")
     public Mono<ResponseEntity<?>> get(String uuid) {
          // Return mono response entity with mapping jackson value
    }
`

**Comment by rstoyanchev** [comment]
I don't understand what you're  missing. You would do exactly as your comment says: "Return mono response entity with mapping jackson value".

**Comment by jnfeinstein** [comment]
@rstoyanchev is there a setting I need to enable to allow WebFlux w/ annotation routing recognize `MappingJacksonValue`?  I have confirmed that the `@JsonView` annotation works fine.  The responsible code is [here](https://github.com/spring-projects/spring-framework/blob/0f6038af70434a20fc4112a79c00c411ab88e519/spring-web/src/main/java/org/springframework/http/codec/json/Jackson2CodecSupport.java#L154), and I cannot find the codepaths responsible for encoding a value wrapped by `MappingJacksonValue`.

**Comment by rstoyanchev** [comment]
@jnfeinstein on the WebFlux side the `Encoder` contract allows us to pass hints so we don't need to wrap with `MappingJacksonValue` but we're missing the ability to do so programmatically. Please, create a new issue and we'll add support for that.

**Comment by jnfeinstein** [comment]
Thanks @rstoyanchev.  I've opened #26035.
