### ISSUE TITLE
Error import for test class

### ISSUE THREAD

**Issue by wolfewf** [spring-projects/spring-framework#25599]
Jaxb2MarshallerTests and Jaxb2UnmarshallerTests can not import org.springframework.oxm.jaxb.test.FlightType and org.springframework.oxm.jaxb.test.Flights, can not find  org.springframework.oxm.jaxb.test package

spring version :5.1.18.BUILD-SNAPSHOT

**Comment by sbrannen** [comment]
It sounds like you did not first build the `spring-oxm` module.

Please consult the [Build from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) documentation for further details.

**Comment by wolfewf** [comment]
why is it designed？i can not understand

**Comment by sbrannen** [comment]
The JAXB types are generated from `flight.xsd` during the Gradle build: 

https://github.com/spring-projects/spring-framework/blob/1891f8af7086546ccbb5ac6dd0c8b48be08c04a8/spring-oxm/spring-oxm.gradle#L21-L55

**Comment by wolfewf** [comment]
i saw XStreamMarshallerTests class import Flight in the current package，so can not  understand. Thank you for your answers！！
