### ISSUE TITLE
Exception occurs when testing with TestNG 7.3.0

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#25606]
After upgrading TestNG from 7.1.0 to 7.3.0, tests fail with:

```
java.lang.IllegalStateException: org.springframework.web.context.support.GenericWebApplicationContext@5567c481 has been closed already
```

I have tests that create multiple application contexts.

Is TestNG 7.3.0 supported?

**Comment by sbrannen** [comment]
> Is testng 7.3.0 supported?

We already test `spring-test` against TestNG 7.3.0 in `master`, and all of our tests pass.

As Phil mentioned, please provide a sample application that demonstrates the issue you are encountering.

**Comment by cdalexndr** [comment]
Issue was caused by https://github.com/spring-projects/spring-framework/issues/11019 (and the multitude issues that it causes).
Seems that upgrading to 7.3.0 reordered tests so that this issue surfaced (running a @DirtiesContext test first, then the next test saw closed context).
