### ISSUE TITLE
Webclient Docker OffHeap Memory Leak

### ISSUE THREAD

**Issue by SentryMan** [spring-projects/spring-framework#25615]
**Affects:** 5.2.8

We're trying to use reactive in our microservice, but we're seeing the docker memory go up until the instance is killed. We were able to identify webclient as the culprit. To be more precise, the JVM memory is normal, but when API calls are made the docker memory is not released and the instance is eventually killed without any outOfHeap errors.

I was able to reproduce the issue using a simple project.

```
@Component
public class Controller {

  //This is an endpoint to another simple api
  //Naturally, I use my local IP instead of localhost in the container
  private static final String ENDPOINT = "http://localhost:9090/";

  private WebClient client;
  
  public Controller(WebClient.Builder client) {
    super();
    this.client = client.build();
  }

  @Bean
  public RouterFunction<ServerResponse> router() {

    return RouterFunctions.route(GET("helloworld"), this::handle);
  }

  Mono<ServerResponse> handle(ServerRequest request) {

    Mono<String> helloMono =
        client.get().uri(ENDPOINT + "/hello").retrieve().bodyToMono(String.class);

    Mono<String> worldMono =
        client.get().uri(ENDPOINT + "/world").retrieve().bodyToMono(String.class);

    return Mono.zip(helloMono, worldMono, (h, w) -> h + w)
        .flatMap(s -> ServerResponse.ok().bodyValue(s));
  }
}
```
Here's the dockerFile.
```
FROM openjdk:8

ENV SERVICE_NAME reactive-hello-world

ADD target/reactive-hello-world-*.jar $APP_HOME/reactive-hello-world.jar

RUN mkdir /opt/reactor-netty/


EXPOSE 9010

CMD java \
	-Dcom.sun.management.jmxremote=true \
	-Dcom.sun.management.jmxremote.local.only=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Djava.rmi.server.hostname=localhost \
	-Dcom.sun.management.jmxremote.port=9010 \
	-Dcom.sun.management.jmxremote.rmi.port=9010 \ 
         -Xmx190M \
	-jar reactive-hello-world.jar

EXPOSE 8080
```
Here's some images

Before Load Test:
[![Before load test][1]][1]

After Load Test
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/KX98k.jpg
  [2]: https://i.stack.imgur.com/0FRZZ.jpg

As you can see, the heap is fine but the memory hasn't decreased, I've tried a similar code using ``RestTemplate`` without issue. Edit: I've also tried the deprecated ``AsyncRestTemplate`` and I not seeing a problem with that either.

Edit: I have created the repos for this example. Please check if you can reproduce the issue. 

[The Hello World Backend](https://github.com/SentryMan/api-hello-world-backend)
[The Webclient Hello World](https://github.com/SentryMan/reactive-hello-world)(JMX is inside this repo)
[The RestTemplate Hello World](https://github.com/SentryMan/reactive-hello-world/tree/restTemplate)
[The AsyncRestTemplate Hello World](https://github.com/SentryMan/reactive-hello-world/tree/AsyncRestTemplate)
[The Exchange Strategy Hello World](https://github.com/SentryMan/reactive-hello-world/tree/ExchangeStrategy)

**Comment by rstoyanchev** [comment]
@SentryMan does it make a difference if you run it locally without Docker?

Ideally please provide an actual sample app to run and likewise the JMeter script you use. It would be useful to see what the code using RestTemplate looks like for comparison.

**Comment by mdeinum** [comment]
@SentryMan does it make a difference if you move the `RouterFunction` `@Bean` method to a different class which is annotated with `@Configuration` or make this class an `@Configuration`?

`@Bean` methods in `@Component` classes are handled differently than from `@Configuration` classes.

**Comment by SentryMan** [comment]
That doesn't seem to make a difference, in the microservice where we found the issue, the structure was organized as you say.

**Comment by SentryMan** [comment]
@rstoyanchev I have added the repos.

**Comment by SentryMan** [comment]
@rstoyanchev has any movement happened regarding this issue? I've been testing different configurations trying to understand why the problem is happening. most recently I tried replacing the ``retrieve()`` method for ``exchange()``. I still got the same massive memory usage.

**Comment by SentryMan** [comment]
perhaps the issue is deeper than ``Webclient``, I've tried using an ``ExchangeFunction``, and still saw the docker memory leak. 

```java
  private ExchangeFunction exchangeFunction;
  public Controller() {
    super();
    this.exchangeFunction = ExchangeFunctions.create(new ReactorClientHttpConnector());
  }

  Mono<ServerResponse> handle(ServerRequest request) {

    ClientRequest request1 =
        ClientRequest.create(HttpMethod.GET, URI.create(ENDPOINT + "/hello")).build();

    ClientRequest request2 =
        ClientRequest.create(HttpMethod.GET, URI.create(ENDPOINT + "/world")).build();

    Mono<String> helloMono =
        exchangeFunction.exchange(request1).flatMap(r -> r.bodyToMono(String.class));

    Mono<String> worldMono =
        exchangeFunction.exchange(request2).flatMap(r -> r.bodyToMono(String.class));

    return helloMono.zipWith(worldMono, (h, w) -> h + w).flatMap(ServerResponse.ok()::bodyValue);
  }
```

**Comment by SentryMan** [comment]
I've gone deeper still, I've just tried using netty's ``HttpClient`` and still saw the issue. @rstoyanchev does this mean the issue is with netty itself?

```java
private HttpClient client;
  
  public Controller() {
   super();
   this.client = HttpClient.create();
   }

  Mono<ServerResponse> handle(ServerRequest request) {

    Flux<String> helloMono =
        client.get().uri(ENDPOINT + "/hello").responseContent().asByteArray().map(String::new);

    Flux<String> worldMono =
        client.get().uri(ENDPOINT + "/world").responseContent().asByteArray().map(String::new);

    return ServerResponse.ok().body(helloMono.zipWith(worldMono, (h, w) -> h + w), String.class);
  }
```

**Comment by rstoyanchev** [comment]
@SentryMan apologies for the delay. I just came across your comment under https://github.com/reactor/reactor-netty/issues/1304 which I suppose is the same report as here?

**Comment by SentryMan** [comment]
Yeah, I'll close this.
