### ISSUE TITLE
Spring Content Indexer is not incremental

### ISSUE THREAD

**Issue by sergekukharev** [spring-projects/spring-framework#25614]
**Affects:** org.springframework:spring-context-indexer:5.2.8

Running Gradle build with `--info` shows that Spring Content Indexer causes full recompilation, even if totally unrelated file is changed in our project. 

> Full recompilation is required because org.springframework.context.index.processor.CandidateComponentsIndexer is not incremental. Analysis took 0.042 secs.

Anything I can do to help with this issue? Are there any practical reasons why we can't declare the processor as incremental? 

---

**Comment by sbrannen** [comment]
We need to investigate our options in Gradle's [Incremental annotation processing](https://docs.gradle.org/6.5/userguide/java_plugin.html#sec:incremental_annotation_processing) documentation.

**Comment by snicoll** [comment]
Thanks for the report and the suggestion. The indexer [has been deprecated](https://github.com/spring-projects/spring-framework/issues/30431) so we won't be making further changes to it.
