### ISSUE TITLE
Spring Web Client is not using proxy if its configured

### ISSUE THREAD

**Issue by kmariappan2016** [spring-projects/spring-framework#25673]
Hi,
When I use Spring web client behind corporate proxy its not using the proxy server to connect.
I thought its netty and oauth2 client. Seems its webclient is not using the proxy server.

Here is the link for the sample code :

https://github.com/kmariappan2016/spring-web-client.git

**Comment by bclozel** [comment]
@kmariappan2016 the client configuration looks right to me. Is this happening only for OAuth-related requests? Are you sure you don't need to customize your security configuration with that custom `WebClient`?

**Comment by bclozel** [comment]
Now I see that you've created both reactor/reactor-netty#1269 and spring-projects/spring-security#8966 - please link to related issues as it helps us narrowing down the problem.

I also see that Joe confirmed that you need configure security with that custom `WebClient`. I'm closing this issue for the time being. Please reopen this if you've got a sample project reproducing the issue, but without involving Spring Security or Kafka to isolate the problem (just a vanilla `WebClient` with your custom configuration).

Thanks!
