### ISSUE TITLE
Upgrading from Boot 2.3.3 or 2.4-M1 to Boot 2.4-M2 uses 125mb heap in BitsCronField

### ISSUE THREAD

**Issue by spazbob** [spring-projects/spring-framework#25687]
I have a small-ish Spring MVC app using Boot 2.3.3. Immediately after startup, this uses 20MB of heap (after triggering a GC).

Changing to Boot 2.4-M2, it uses 140MB. I've also tested with M1 which doesn't display the issue.

Heap dump analysis shows that 125MB of heap is being used by org.springframework.scheduling.support.BitsCronField, because there are 15 million objects in a long[].

My application doesn't use scheduling i.e. there is no @EnableScheduling annotation.

![image](https://user-images.githubusercontent.com/24962424/92111785-bdbfa000-ede4-11ea-9ec9-b2c63aa4b183.png)

**Comment by daniel-liy** [comment]
Is there a complete sample code and runtime environment? eg.

**Comment by spazbob** [comment]
Hi @poutsma - do you need anything from me for this or is it an obvious change? I can't share the full application code but could have a go at stripping things down to a working example.

**Comment by poutsma** [comment]
Thank you, but I don’t think (or hope) that I need application code to solve this. I simply had no idea that BitSet uses so much memory, and we should be fine by using a long or even int for this use case.

**Comment by poutsma** [comment]
This should be fixed now. @spazbob Can you try a recent [snapshot](https://repo.spring.io/snapshot/org/springframework/spring-core/5.3.0-SNAPSHOT/)  and see if that resolves things?

**Comment by spazbob** [comment]
Hi @poutsma, I had some issues moving our app to a snapshot release - I will try again in a few days.

**Comment by spazbob** [comment]
@poutsma now tests correct - sorry for the delay!
