### ISSUE TITLE
Optimize ConfigurationClassPostProcessor#enhanceConfigurationClasses method to shorten startup time

### ISSUE THREAD

**Issue by yourbatman** [spring-projects/spring-framework#25738]
The Version of the Spring Framework I used: 5.2.8

ConfigurationClassPostProcessor#enhanceConfigurationClasses method determines the @Configuration class in full mode:
![image](https://user-images.githubusercontent.com/18030368/92459323-1f26ab00-f1f9-11ea-8e29-1e88c18d41a9.png)

if `beanFactory.containsSingleton(beanName)` is true.The output info log tells me that the Bean cannot be enhanced，But it still puts it inside 'configBeanDefs'.And then execute `enhancer.enhance(configClass, this.beanClassLoader);` to enhance it.

Although,enhanced instances do not end up in the IoC container（Because it already exists in the container）.But it's semantically inconsistent.It also creates unnecessary overhead in terms of performance.Slow application startup.

For example：

1、Define a @Configuration class `AppConfig`:
```java
@Configuration
public class AppConfig {
    
    @Bean
    public BeanDefinitionRegistryPostProcessor postProcessor() {
        return new BeanDefinitionRegistryPostProcessor() {
            @Override
            public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry) throws BeansException {
            }

            @Override
            public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
            }
        };
    }

}
```
2、debug run Spring container.Screenshot as follows:
![image](https://user-images.githubusercontent.com/18030368/92462839-978f6b00-f1fd-11ea-9b96-3ea7514f2ec6.png)

![image](https://user-images.githubusercontent.com/18030368/92460295-62354e00-f1fa-11ea-983d-7240ab0b816c.png)

Console log：
![image](https://user-images.githubusercontent.com/18030368/92460385-809b4980-f1fa-11ea-95d8-58890b6c0bc2.png)

The log says that `AppConfig` will not be enhanced.But the enhanced logic is actually executed,and there are contradictions.

Solution：I think the following changes can be made to the code to avoid unnecessary performance losses and speed up startup
```java
public void enhanceConfigurationClasses(ConfigurableListableBeanFactory beanFactory) {
    ...
			if (ConfigurationClassUtils.CONFIGURATION_CLASS_FULL.equals(configClassAttr)) {
				if (!(beanDef instanceof AbstractBeanDefinition)) {
					throw new BeanDefinitionStoreException("Cannot enhance @Configuration bean definition '" +
							beanName + "' since it is not stored in an AbstractBeanDefinition subclass");
				}
				else if (logger.isInfoEnabled() && beanFactory.containsSingleton(beanName)) {
					logger.info("Cannot enhance @Configuration bean definition '" + beanName +
							"' since its singleton instance has been created too early. The typical cause " +
							"is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor " +
							"return type: Consider declaring such methods as 'static'.");
				} 
                                else {
                                        configBeanDefs.put(beanName, (AbstractBeanDefinition) beanDef);
                                }
				
			}
    ...
}
```
Just make `configBeanDefs.put(beanName, (AbstractBeanDefinition) beanDef);` at the independent `else` branch.

**Comment by mdeinum** [comment]
Which would still fail if **info** logging would be disabled because it is part of the expression.

**Comment by yourbatman** [comment]
> Which would still fail if **info** logging would be disabled because it is part of the expression.

What I mean is that if you print the **Info** log, you should not put it into `configBeanDefs` to perform the enhanced logic, because that makes no sense.

**Comment by mdeinum** [comment]
I know what you meant, but adding an else isn't going to solve it. When **warn**` is enabled and the bean is already in the bean factory it now still would be added. The whole point should be that the bean shouldn't be enhanced regardless of info being enabled or not.

**Comment by yourbatman** [comment]
> I know what you meant, but adding an else isn't going to solve it. When **warn**` is enabled and the bean is already in the bean factory it now still would be enhanced. The whole point should be that the bean shouldn't be enhanced when it is already existing as a singleton, regardless of info being enabled or not.

I take your point:“the bean is already in the bean factory it now still would be enhanced”.But for this judgment `beanFactory.containsSingleton(beanName)` does this mean that the singleton Bean already exists? If so, it should not be put into 'configBeanDefs' any more.

**Comment by brucelwl** [comment]
Similar issues : https://github.com/spring-projects/spring-framework/issues/22990
