### ISSUE TITLE
the type of the attribute "configurationClasses"  of class ConfigurationClassParser is LinkedHashMap

### ISSUE THREAD

**Issue by lwbkfc** [spring-projects/spring-framework#25761]
![image](https://user-images.githubusercontent.com/6101029/92997739-ee6faa00-f547-11ea-98c6-786cf5efb044.png)

is it better to replace the "LinkedHashMap" with "HashSet"?

**Comment by sbrannen** [comment]
Closing this issue as a duplicate of #23857.
