### ISSUE TITLE
Extending abstract class does not expose parameter annotations

### ISSUE THREAD

**Issue by couryrr** [spring-projects/spring-framework#25788]
I am on version 2.3.4.RELEASE and am seeing the same issue identified here https://github.com/spring-projects/spring-framework/issues/24127 except for abstract classes.

Here is the abstract class with the `@RequestBody` annotation:

![image](https://user-images.githubusercontent.com/2702992/93616176-5f78ec80-f9a2-11ea-8d6a-05d86243c7ff.png)

Here is the `extended` class without the annotation:

![image](https://user-images.githubusercontent.com/2702992/93616424-bb437580-f9a2-11ea-9a1f-4ff325b05023.png)

Postman showing the data being sent in but returning nulls in the object:

![image](https://user-images.githubusercontent.com/2702992/93616656-0198d480-f9a3-11ea-8f00-70e705850e3c.png)

If I move the `@RequestBody` annotation to the class that extends this works. Likewise if I make the abstract class an interface and do not provide the `@RequestBody` annotation it works as well.

**Comment by snicoll** [comment]
@couryrr sorry it took so long to look at this. 

I can reproduce this behavior. Looking at `org.springframework.web.method.HandlerMethod.HandlerMethodParameter`, it creates its `MethodParameter` from the base class and I don't see what would be looking for the presence of metadata on the parent class. That's a bit at odds with method-level metadata that is indeed found. 

@rstoyanchev wondering if that rings a bell?

**Comment by jhoeller** [comment]
As a follow-up to #30801 in 6.1, our common `AnnotatedMethod` inherits annotations from base classes as well in 6.1.3 now.
