### ISSUE TITLE
Set the sameSite cookie attribute in ReactorClientHttpResponse

### ISSUE THREAD

**Issue by DamianFekete** [spring-projects/spring-framework#25785]
**Affects:** Spring Framework 5.2.9 (and below)

I would like to have direct access to the sameSite attribute when using `WebTestClient` (`body.getResponseCookies()`).

[ReactorClientHttpResponse#getCookies()](https://github.com/spring-projects/spring-framework/blob/47a3a5c97011a4e147db9a4cab3e85c8486fcec7/spring-web/src/main/java/org/springframework/http/client/reactive/ReactorClientHttpResponse.java#L135) doesn't set the sameSite attribute on the `ResponseCookie`.

```java
this.response.cookies().values().stream().flatMap(Collection::stream)
	.forEach(c ->

		result.add(c.name(), ResponseCookie.fromClientResponse(c.name(), c.value())
				.domain(c.domain())
				.path(c.path())
				.maxAge(c.maxAge())
				.secure(c.isSecure())
				.httpOnly(c.isHttpOnly())
				.build()));
```

`this.response.cookies()` returns a `io.netty.handler.codec.http.cookie.Cookie` (the interface), but the implementation is `io.netty.handler.codec.http.cookie.DefaultCookie`, which supports the sameSite attribute.

Is there any compelling reason not to test if the implementation is [`DefaultCookie`](https://netty.io/4.1/api/io/netty/handler/codec/http/cookie/DefaultCookie.html#sameSite--) and if it is to set the sameSite attribute on the returned `ResponseCookie` ?

**Comment by jhoeller** [comment]
FWIW, we don't expose the sameSite attribute in `JettyClientHttpResponse` and `HttpComponentsClientHttpResponse` either. If we address this, we'd have to revise it all three implementations there.
