### ISSUE TITLE
Support for HTTP Request Method: SEARCH

### ISSUE THREAD

**Issue by joao-rebelo** [spring-projects/spring-framework#25797]
As of RFC 5323 (https://tools.ietf.org/html/rfc5323) a HTTP SEARCH method was proposed.
This RFC then got refined by https://trac.tools.ietf.org/id/draft-snell-search-method-00.html and others.

SEARCH is useful to replace GET methods which would require a long size of request parameters (exceeding the maximum query length), or that would require a body to be sent (although currently allowed by the specification many languages / browsers will not allow it)

Although this RFC is still not approved we start to see some support for it in multiple libraries.
Is this verb planned to be supported on Spring?

**Comment by bclozel** [comment]
There's a [new version of this draft published](https://tools.ietf.org/html/draft-snell-search-method-01) but it's expired. We're not seeing much activity in the Spring ecosystem around that. We might work on this if technologies we support offer this feature.

Do you have links to Java libraries supporting this?

**Comment by joao-rebelo** [comment]
It's not easy to google by SEARCH method... but I've found at least one reference on Java world:

Issue delivered on Rest Assured library
https://github.com/rest-assured/rest-assured/issues/339

Also in Javascript world that consumes these APIs, for example with fetch library, we can provide the SEARCH method for the library to consume it.

**Comment by bclozel** [comment]
We do support already custom methods on Controllers, would that support be enough? Are you expecting something more here?

**Comment by joao-rebelo** [comment]
From those issues it seems that the request could be processed, but I'm not understanding how can we define the @RequestMapping annotation (from MVC or Webflux).
It does require an HTTPMethod enumeration value, therefor we can't just provide a custom HTTP verb there.

**Comment by bclozel** [comment]
In the meantime, this has been replaced with the [`QUERY` HTTP method in a different draft](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-safe-method-w-body), which is expired and is now archived. Closing this issue as a result.
