### ISSUE TITLE
Provide public getter or part converter registration in FormHttpMessageConverter for partConverters

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-framework#25817]
Spring Boot has a reflection hack so that it can register additional part converters (see https://github.com/spring-projects/spring-boot/issues/23485). It would be good to at least provide a public API for doing that. Maybe go a bit further in 6.0?

**Comment by rstoyanchev** [comment]
A getter should be straight forward. Is 5.3 sufficient or does it help be in 5.2 as well?

**Comment by dsyer** [comment]
I think 5.3 is all we need.
