### ISSUE TITLE
@RequestBody can not parse body data correctly sometimes

### ISSUE THREAD

**Issue by s-c-c** [spring-projects/spring-framework#25834]
I used `@RequestBody` to parse `HttpServletRequest` body data in my POST method.  I repeatedly submit POST request, and possibly the jsonArray is null, but contentLength is not 0.

```java
@PostMapping("xxx")
public void verify(@RequestBody(required = false)String jsonArray, HttpServletRequest request, HttpServletResponse response) 
{
    if (jsonArray == null || jsonArray.length() == 0) {
        int contentLength = request.getContentLength();
        logger.error("contentLength= " + contentLength);
        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
        return;
    }
}
```

**Comment by sbrannen** [comment]
Have you tried removing `required = false` from the `@RequestBody` declaration?

**Comment by s-c-c** [comment]
The possible cause is that the remaining data has not arrived, inputStream cannot read the data and return -1 in advance.

**Comment by s-c-c** [comment]
I tried to remove @RequestBody and read the body data manually
```
public String getJsonFromRequest(HttpServletRequest request) {
        String json = null;
        try(InputStream inputStream = request.getInputStream()) {
            int len = request.getContentLength();
            byte[] buff = new byte[len];
            int readLen = 0;
            int time = 0;
            for (int i = 0; time < READ_RETRY_TIME && i < len;) {
                readLen = inputStream.read(buff, i, len - i);
                if (readLen != -1) {
                    i+= readLen;
                } else {
                    Thread.sleep(1000);
                    time++;
                }
            }
            json = new String(buff, "UTF-8");
        } catch (IOException e) {
        } catch (InterruptedException e) {
        }
        return json;

    }
```

**Comment by rstoyanchev** [comment]
If you'd like us to look further please provide clear instructions on how to reproduce the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by s-c-c** [comment]
the cause of the problem is that the server read -1 while the data havent totally submited by client. for example, the content len i get from request is 12396. but i read -1 when i read the 8397 byte data. i dont know why this hanpen.

**Comment by snicoll** [comment]
Given that we didn't get the instruction to reproduce the issue as requested, I am going to close this. We can reconsider if a sample is provided.
