### ISSUE TITLE
FormHttpMessageConverter to preserve parameters from the input MediaType  

### ISSUE THREAD

**Issue by alan-bond** [spring-projects/spring-framework#25839]
https://github.com/spring-projects/spring-framework/blob/9a43d2ec208d2e8cd0866431acf26af3529f8677/spring-web/src/main/java/org/springframework/http/converter/FormHttpMessageConverter.java#L354

The contentType could have prams inside of it when it comes into this method.  
This line of code will not look at those prams at those prams will will just over write them.  Instead of just making a new list here, you should take the content type that came in or was made new in the beginning of this method and start a new list from the prams of the contentType.
It could look something like:
Map<String, String> parameters = new LinkedHashMap(contentType.getParameters());
instead of:
Map<String, String> parameters = new LinkedHashMap(2);

This will allow the setting of the prams in the rest controller by adding them to the contentType at that level and this will no longer over write them when working with multipart content types.

Thank you for your time

Alan Bond

**Comment by rstoyanchev** [comment]
Indeed any parameters that may be present on the input `MediaType`. We are [handling it differently](https://github.com/spring-projects/spring-framework/blob/a6bede22c113e69206c13735dbf820c7cb043e2e/spring-web/src/main/java/org/springframework/http/codec/multipart/MultipartWriterSupport.java#L100-L105) on the WebFlux side where we start with the parameters from the input `MediaType` and then override "charset" and "boundary". We could do the same in `FormHttpMessageConverter` as well.

**Comment by alan-bond** [comment]
Thank you very much, that will help.
