### ISSUE TITLE
WebTestClient no longer captures the URI template

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#25854]
**Affects:** 5.3.0-SNAPSHOT

This is a regression introduced by https://github.com/spring-projects/spring-framework/commit/bedf2de6141ad2e667ca4f8805f495330d5ff9a6. All of the `uri` methods delegating to `uri(URI)` means that the URI template is captured and then immediately nulled out again. This breaks Spring REST Docs' ability to document a request's path parameters.

See https://stackoverflow.com/questions/64174707/spring-rest-docs-failing-to-document-pathparameters-using-webtestclient for background.

**Comment by rstoyanchev** [comment]
Thanks for catching this. I added a test as well.
