### ISSUE TITLE
A problem occurred evaluating project ':spring-beans'

### ISSUE THREAD

**Issue by NewDayxjc** [spring-projects/spring-framework#25851]
**Affects:** \<Spring Framework version>
> No such property: classesDirectory for class: org.gradle.api.internal.file.DefaultSourceDirectorySet
---
No such property: classesDirectory for class: org.gradle.api.internal.file.DefaultSourceDirectorySet

**Comment by bclozel** [comment]
How did you run the build? [Did you follow the instructions here](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source)?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
