### ISSUE TITLE
Document that pertypewithin is supported by Spring AOT

### ISSUE THREAD

**Issue by dngzs** [spring-projects/spring-framework#25887]
I can write like this.

```java
@Component
@Aspect("pertypewithin(com..*)")
@Scope("prototype")
public class TimeAspect {
 
    @Pointcut("execution(* com.dngzs.spring.service..*.*(..))")
    public void time() {
    }

    @Before("time()")
    public void before(JoinPoint joinpoint) {
        System.out.println("before：" + joinpoint);
    }
}
```

The [official document](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/core.html#aop-instantiation-models) is written like this:

> Spring supports AspectJ’s `perthis` and `pertarget` instantiation models; `percflow`, `percflowbelow`, and `pertypewithin` are not currently supported.

Is my example wrong？

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by dngzs** [comment]
My English is not very good, thank you very much for your modification

**Comment by dngzs** [comment]
HI
   Are there any results? Looking forward to your reply, thank you very much

**Comment by sbrannen** [comment]
Based on the [implementation of `AspectMetadata`](https://github.com/spring-projects/spring-framework/blob/master/spring-aop/src/main/java/org/springframework/aop/aspectj/annotation/AspectMetadata.java), it appears that Spring AOP does support `pertypewithin`; however, we don't have any tests in place to prove that, and as you pointed out the documentation does not list it as supported.

So perhaps we just need to update the documentation.

@jhoeller, thoughts?

**Comment by dngzs** [comment]
thank you very much！

**Comment by dngzs** [comment]
Is the problem ready to fix the document? When to fix , Looking forward to reply  @sbrannen @jhoeller
