### ISSUE TITLE
@EnableCaching(mode= AdviceMode.ASPECTJ)  doesn't work for me

### ISSUE THREAD

**Issue by case0079** [spring-projects/spring-framework#25895]
When I write a java @Aspect   ,It's work fine. but the  @EnableCaching does nothing, even no Exception is threw out

<img width="1302" alt="截屏2020-10-12 上午3 03 43" src="https://user-images.githubusercontent.com/7411184/95687657-90fa7600-0c37-11eb-9cf6-e9d290e16f3c.png">

the pom:

```
<properties>
    <java.version>1.8</java.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spring-boot-version>2.3.3.RELEASE</spring-boot-version>
    <spring-cloud-version>Hoxton.SR8</spring-cloud-version>
  </properties>
```

the cache config :

```java
@Configuration
@EnableCaching(mode= AdviceMode.ASPECTJ)
@EnableLoadTimeWeaving()
public class CacheConfig {

  @Bean
  public CacheManager cacheManager(RedisConnectionFactory redisConnectionFactory) {
      RedisCacheConfiguration conf= ....
       return rcm;
  }
}
```

the service method :

```
  @Cacheable(cacheNames = "bargain:product", key="#id" )
  public User get(long id){

  .....

}
```

**Comment by ypdaic** [comment]
你是不是没有引入这个依赖，AdviceMode.ASPECTJ模式需要下面的依赖
<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
        </dependency>

**Comment by snicoll** [comment]
Unfortunately, there's not much we can do with a screenshot and a few code snippet. Issues like this are best service with a small sample that we can run ourselves. Without it, we can't justify spending time trying to understand what steps you've missed, or what specific feature might be broken on our side. If you can share a sample, we can reconsider.
