### ISSUE TITLE
If a bean has @RefreshScope annotation and implements SmartLifecycle, SmartLifecycle failure

### ISSUE THREAD

**Issue by flangely** [spring-projects/spring-framework#25934]
**Affects:** \<5.2.6.RELEASE>

---
If a Bean has the @RereshScope annotation and implements the SmartLife interface, the SmartLife interface lifecycle method will not be invoked after the Spring container is started

Bean:
@Slf4j
@Component
@RefreshScope
public class NectorInvoker implements SmartLifecycle

start method:
@Override
    public void start() {
        if (this.running.compareAndSet(false, true)) {
            nectorClient.start();
        }
   }

As mentioned above, the start method will not be called

**Comment by sdeleuze** [comment]
`@RefreshScope` is not directly supported at Spring Framework level and it modifies some core concept that could imply this kind of side effect, so nothing we could do about it. Maybe to be raised on Spring Cloud side.

**Comment by flangely** [comment]
ok, thank you

**Comment by flangely** [comment]
> `@RefreshScope` is not directly supported at Spring Framework level and it modifies some core concept that could imply this kind of side effect, so nothing we could do about it. Maybe to be raised on Spring Cloud side.

ok, thank you
