### ISSUE TITLE
spring-web async restful api not support executor with Callable

### ISSUE THREAD

**Issue by yangelaboy** [spring-projects/spring-framework#25935]
when returning with a Callable response in a controlller method, I find it will use default AsyncTaskExecutor with thread name prefix "MvcAsync"。
I create a AsyncTaskExecutor, but find I can not be injected into WebAsyncTask with Callable way.

I think when creating a WebAsyncTask with Callable parameter, it should should get a bean with default executorName of type AsyncTaskExecutor.

**Comment by rstoyanchev** [comment]
I'm not sure I fully understand what you are asking.

Based on the title, `WebAsyncTask` does support a custom `Executor`. It can be passed in as a constructor arg or [configured globally](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#mvc-ann-async-configuration).

From what I can see however the `executorName` that can be passed to the constructor is not used unless a `BeanFactory` is also set on `WebAsyncTask` and I currently don't see that being set anywhere in framework code. Is this what you are trying to do but unable to?

**Comment by yangelaboy** [comment]
yes, WebAsyncTask does support a custom Executor, but a Callable response in a controller method will be as a arg to construct a WebAsyncTask。When using Callable way, I can't pass a custom Executor into WebAsyncTask which is created by spring-framework。
![image](https://user-images.githubusercontent.com/16263873/96532195-f694d500-12bd-11eb-8406-b12e1ad8f53a.png)
![image](https://user-images.githubusercontent.com/16263873/96532262-175d2a80-12be-11eb-96ef-ee11c953bb77.png)
![image](https://user-images.githubusercontent.com/16263873/96532353-4ffd0400-12be-11eb-8b92-f9c9d4246896.png)
The last image is the problem：when constructing WebAsyncTask with Callable instance, the method getExecutor return nul becase the executorName is not initialized。
I think that constructing WebAsyncTask with Callable instance, the method getExecutor should get an Executor Bean from beanFactory with default name and AsyncTaskExecutor class.

**Comment by rstoyanchev** [comment]
We already have a mechanism to select the `Executor` to use for a `Callable` return value. It's configured via `WebMvcConfigurer`. Please, [see the docs](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#mvc-ann-async-configuration-spring-mvc) and use that.
