### ISSUE TITLE
Wrong link in Spring framework tutorial 

### ISSUE THREAD

**Issue by eladAlfa** [spring-projects/spring-framework#25970]
In the following document:
src/docs/asciidoc/core/core-resources.adoc
(compared against master (version 5.2.9.RELEASE))

The link in line 566:
"See the {api-spring-framework}/jca/context/SpringContextResourceAdapter.html[`ClassPathXmlApplicationContext`]"
should replaced with: 
{api-spring-framework}/context/support/ClassPathXmlApplicationContext.html[`ClassPathXmlApplicationContext`]

**Comment by rstoyanchev** [comment]
Good catch. It looks like that was introduced with https://github.com/spring-projects/spring-framework/commit/395e3d008cc3fa63dbfc7319fad0f29120e84053#diff-e7ee4199d9eef01c72268eec533373fe8848c887c617df99303c24629a1fb4e7L462-L463.
