### ISSUE TITLE
@Nonnull annotation breaks ServletRequestMethodArgumentResolver for Principal

### ISSUE THREAD

**Issue by rcaspar** [spring-projects/spring-framework#25981]
If you have something like: 

```java
@GetMapping("/foo")
public ResponseEntity<?> method(@Nonnull Principal principal) {
    return ResponseEntity.ok("bar");
}
```

`ServletRequestMethodArgumentResolver` will fail to resolve the principal parameter because there's some annotation on it. 

I think this is a regression introduced by #19779

**Comment by sbrannen** [comment]
This is a regression introduced by #25780.

**Comment by rstoyanchev** [comment]
We might need to switch the approach for example by deferring its resolution so that custom resolvers have a chance.
