### ISSUE TITLE
@Transactional on suspending function returning a value always rollbacks

### ISSUE THREAD

**Issue by lujijiang** [spring-projects/spring-framework#25998]
**Affects:** 5.3.0

**Comment by sdeleuze** [comment]
Could you please provide a repro project ?

**Comment by lujijiang** [comment]
The Repro:https://github.com/lujijiang/app-demo.git 
Master branch is ok with use transactionalOperator, you can checkout issue code from branch  @TransactionalTest

**Comment by lujijiang** [comment]
You can testing with post to http://localhost:8080/savePerson ,and the data is 
```json
{
    "name":"lily",
    "age":100
}
```

**Comment by sdeleuze** [comment]
I have been able to reproduce it, it only happens when the suspending function returns a value. In that can the reactive transaction is always rollbacked because of a concellation. See https://github.com/sdeleuze/demo-coroutines-tx for a detailed repro.

**Comment by lujijiang** [comment]
Great, waiting to be fixed.
