### ISSUE TITLE
NamedParameterJdbcTemplate broken in Spring Boot 2.3.5

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/spring-framework#26032]
I'm using Spring Boot 2.3.5 release which looks to be on Spring Framework 5.2.10.

In NamedParameterJdbcTemplate, you have:

```
	private volatile ConcurrentLruCache<String, ParsedSql> parsedSqlCache =
			new ConcurrentLruCache<>(DEFAULT_CACHE_LIMIT, NamedParameterUtils::parseSqlStatement);

```

Imported as `org.springframework.util.ConcurrentLruCache`

Eclipse shows that ConcurrentLruCache is now a private static class in MimeTypeUtils. This breaks a lot of stuff.

**Comment by sbrannen** [comment]
`org.springframework.util.ConcurrentLruCache` was introduced as a top-level public class in Spring Framework 5.3.

Thus it appears that you have mixed versions of Spring Framework JARs in your classpath.

Please investigate your dependencies and let us know what you discover.

**Comment by SledgeHammer01** [comment]
> `org.springframework.util.ConcurrentLruCache` was introduced as a top-level public class in Spring Framework 5.3.
> 
> Thus it appears that you have mixed versions of Spring Framework JARs in your classpath.
> 
> Please investigate your dependencies and let us know what you discover.

Thanks. I guess some of the new data modules (jdbc, orm, cassandra, elastic) released over the past few days aren't compatible yet. Rolled all those back.
