### ISSUE TITLE
setTaskScheduler in StompBrokerRelayRegistration breaks chaining

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#26049]
The recently added `setTaskScheduler` returns `void` instead of `StompBrokerRelayRegistration` and so does `setTcpClient` which was added longer ago might be worth addressing.

Originally reported in https://github.com/spring-projects/spring-framework/issues/22822#issuecomment-723735475.

**Comment by jhoeller** [comment]
Let's address both in 5.3.1 indeed. This is still early enough, in particular since the change is source compatible (just not binary compatible), so fresh application builds won't see any regression.
