### ISSUE TITLE
Message converters list allows null elements

### ISSUE THREAD

**Issue by hariprasad-tallapalli** [spring-projects/spring-framework#26065]
Because of concurrent threads processing to add custom converter at the same time into the existing message converters list,it is leading to the issue "message converters doesn't contain null elements".

**Comment by rstoyanchev** [comment]
Please provide more details about what you're trying to do and the resulting output/stacktrace. Ideally provide a sample.

**Comment by ilam-natarajan** [comment]
@hariprasad-tallapalli I might be facing similar sort of issue, wonder if you found any mitigation.

**Comment by hariprasad-tallapalli** [comment]
We have extended RestTemplate class and creating single ton class. Using
this singleton class trying to add custom string converter of utf8 into the
existing list of converters. With multiple threads trying to run this at
the same time leading to null values in the converters list. If we can
create new rest template object everytime then this issue will not
occur again even if you try with multiple threads.

Correct me if I am wrong.

**Comment by ilam-natarajan** [comment]
@hariprasad-tallapalli did you add the custom string converter every time you issue the request, or only once during startup?
@bclozel suggested me in gitter to just do it once during startup

**Comment by rstoyanchev** [comment]
The list of message converters is meant to be initialized once on startup.

**Comment by hariprasad-tallapalli** [comment]
Only during start up.
