### ISSUE TITLE
`SimpleJdbcCall` with `namedBinding=true` for MS SQL Server

### ISSUE THREAD

**Issue by iignateva** [spring-projects/spring-framework#26072]
spring version: 5.0.8.RELEASE

I try to use `setNamedBinding(true)` on `SimpleJdbcCall` and get the generated statement in oracle syntax (`call @P0 = proc_name Param1 => @P1, Param2=> @P2 ...`).

I found this comment: https://github.com/spring-projects/spring-framework/issues/17398#issuecomment-453423378 

Was it implemented for the MS SQL Server?

**Comment by jhoeller** [comment]
MS SQL Server seems to use the same `@<parameter> = <value>` syntax as Sybase, so we should be able to deal with this along with #30231.
