### ISSUE TITLE
@rstoyanchev : RequestDispatcher forward not working with OncePerRequestFilter with Spring boot 2.3.* version but working fine till 2.2.10

### ISSUE THREAD

**Issue by hakuna16** [spring-projects/spring-framework#26103]
@rstoyanchev 
Don't you think it's a kind of hack we are having in the code?

What if we make it somehow configurable for the dispatcher types??

_Originally posted by @hakuna16 in https://github.com/spring-projects/spring-framework/issues/25816#issuecomment-728882509_

**Comment by rstoyanchev** [comment]
@hakuna16 there is no need to open additional issues. The conversation can contunie under #25816.
