### ISSUE TITLE
Wildcard is a valid Access-Control-Expose-Headers value

### ISSUE THREAD

**Issue by jnfeinstein** [spring-projects/spring-framework#26113]
[This check](https://github.com/spring-projects/spring-framework/blob/0e4e25d227dedd1a3ecddc4e40c263f190ca1c2b/spring-web/src/main/java/org/springframework/web/cors/CorsConfiguration.java#L337) is dated.  Wildcard is a valid configuration according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) and [spec](https://fetch.spec.whatwg.org/#http-new-header-syntax).

**Comment by rstoyanchev** [comment]
I think it's dated more than ill-informed. The code was written a year before the spec was changed it seems `https://github.com/whatwg/fetch/issues/252`.

**Comment by jhoeller** [comment]
@rstoyanchev since we have the same check in the older branches as well, I suppose this is a backport candidate? Even if it's not really a bug, depending on the impact of the fix, we could backport it as an enhancement to 5.2.x and 5.1.x at least.

**Comment by jnfeinstein** [comment]
@rstoyanchev fixed in original description.  👍
