### ISSUE TITLE
Broken links in reference manual reference old location for XSD configuration

### ISSUE THREAD

**Issue by eladAlfa** [spring-projects/spring-framework#26129]
Hi,
in spring core documentation version 5.3.1 
file: core-appendix.adoc
line 667:
"If you are not
familiar with Spring's current XML configuration extensions that come with the standard
Spring distribution, you should first read the appendix entitled <<appendix.adoc#xsd-configuration>>."

unfortunately the  appendix.html link leads nowhere.

**Comment by rstoyanchev** [comment]
That's a result of documentation restructuring in 5.0. That link I believe is referring to the section it's in. [Originally it was](https://docs.spring.io/spring-framework/docs/4.3.29.RELEASE/spring-framework-reference/html/xsd-configuration.html) in the previous section on XML schemas,

**Comment by sbrannen** [comment]
Note that `dynamic-languages.adoc` also refers to `appendix.adoc#xsd-configuration`.

**Comment by sbrannen** [comment]
I noticed that we now have two sections named `[[xsd-schemas]]` -- one in `integration-appendix.adoc` and one in `core-appendix.adoc`. So we'll need to give those different names in order not to have ambiguous links to those sections in the single-page reference manual. Perhaps we should keep the one in `core-appendix.adoc` as-is and rename the one in `integration-appendix.adoc` to something like `[[spring-integration-xsd-schemas]]`.
