### ISSUE TITLE
JPMS (Jigsaw) full support for use with jlink/jpackage

### ISSUE THREAD

**Issue by treilhes** [spring-projects/spring-framework#26159]
Hello,

Currently Spring use "Automatic modules" to support JPMS but it prevents the use of jlink and jpackage tools.
So, do you plan to fully support JPMS in a near future? Already on the roadmap?

Best regards

**Comment by bclozel** [comment]
There's an opened issue for declaring `module-info`, see #18079 (and [especially this comment](https://github.com/spring-projects/spring-framework/issues/18079#issuecomment-453430794)).

I'm closing this issue as a duplicate. Thanks!

**Comment by treilhes** [comment]
So fast, i love you guys/girls
