### ISSUE TITLE
5.3.0 and 5.3.1 versions published to Maven central missing .RELEASE suffix

### ISSUE THREAD

**Issue by sehrope** [spring-projects/spring-framework#26154]
**Affects:** 5.3.0 and 5.3.1

The latest 5.3.x versions published to Maven central and the Spring release repo do not have a `.RELEASE` suffix. Prior GA versions since 3.x are all named MAJOR.MINOR.PATCH.RELEASE:

https://mvnrepository.com/artifact/org.springframework/spring-core
https://repo.spring.io/release/org/springframework/spring-core/

Are the 5.3.0 and 5.3.1 versions GA releases and will this be the naming going forward (without the suffix)?

**Comment by snicoll** [comment]
> Are the 5.3.0 and 5.3.1 versions GA releases and will this be the naming going forward (without the suffix)?

Yes. You can read more about that [in this blog post](https://spring.io/blog/2020/04/30/updates-to-spring-versions).
