### ISSUE TITLE
ResponseStatusExceptionHandler should respond with the message of exception to clients

### ISSUE THREAD

**Issue by JamesChenX** [spring-projects/spring-framework#26164]
**Affects:** 5.3.1

---
**Motivation**
We have an internal website for our administrators, and if our website sends an illegal request to the server, the server should respond with both the status code and the error details so that we can know what happens.
But ResponseStatusExceptionHandler just sends the status code to clients currently.

![image](https://user-images.githubusercontent.com/44962329/100446667-29ff2680-30ea-11eb-83d2-06e9f46854ed.png)

**Solution**
Allow developers to choose whether to respond with the error message to clients.

**Comment by rstoyanchev** [comment]
You can [use a ResponseEntityExceptionHandler](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-rest-exceptions) to define the format and content of an error response which is application specific. Also Spring Boot provides such support out of the box.

**Comment by JamesChenX** [comment]
@rstoyanchev ResponseEntityExceptionHandler belongs to WebMVC but our server uses WebFlux so we cannot use ResponseEntityExceptionHandler.

And the problem is that we have our own WebExceptionHandler instance, but its priority is lower than ResponseStatusExceptionHandler. If ResponseStatusExceptionHandler thinks that it can handle the exception, it won't pass the exception to our own handler so we cannot customize the response to clients.

The following code snippet is how ResponseStatusExceptionHandler creates an HTTP response from an exception.
```
	public Mono<Void> handle(ServerWebExchange exchange, Throwable ex) {
		if (!updateResponse(exchange.getResponse(), ex)) {
			return Mono.error(ex);
		}

		// Mirrors AbstractHandlerExceptionResolver in spring-webmvc
		String logPrefix = exchange.getLogPrefix();
		if (this.warnLogger != null && this.warnLogger.isWarnEnabled()) {
			this.warnLogger.warn(logPrefix + formatError(ex, exchange.getRequest()), ex);
		}
		else if (logger.isDebugEnabled()) {
			logger.debug(logPrefix + formatError(ex, exchange.getRequest()));
		}

		return exchange.getResponse().setComplete(); // We, developers, cannot update the response
	}

	private boolean updateResponse(ServerHttpResponse response, Throwable ex) {
		boolean result = false;
		HttpStatus httpStatus = determineStatus(ex);
		int code = (httpStatus != null ? httpStatus.value() : determineRawStatusCode(ex));
		if (code != -1) {
			if (response.setRawStatusCode(code)) {
				if (ex instanceof ResponseStatusException) {
					((ResponseStatusException) ex).getResponseHeaders()
							.forEach((name, values) ->
									values.forEach(value -> response.getHeaders().add(name, value)));
				}
				result = true;
			}
		}
		else {
			Throwable cause = ex.getCause();
			if (cause != null) {
				result = updateResponse(response, cause);
			}
		}
		return result;
	}
```

**Comment by rstoyanchev** [comment]
Right, this is in WebFlux. By default [we register](https://github.com/spring-projects/spring-framework/blob/e9caee1b6e613185220be6296e1ede55965962e3/spring-webflux/src/main/java/org/springframework/web/reactive/config/WebFluxConfigurationSupport.java#L122-L126) the `ResponseStatusExceptionHandler` at 0. You could register your own `WebExceptionHandler` at -1.

**Comment by JamesChenX** [comment]
Thanks for your help. We can handle the exception by our own handler after we added "@Order(Ordered.HIGHEST_PRECEDENCE)" to our own ErrorWebExceptionHandler.

And I didn't notice that the default exception handler is registered in:
```
public class WebFluxConfigurationSupport implements ApplicationContextAware {
...
...
	@Bean
	@Order(0)
	public WebExceptionHandler responseStatusExceptionHandler() {
		return new WebFluxResponseStatusExceptionHandler();
	}
}
```
