### ISSUE TITLE
Subscriber context not propagated to WebSocketHandler for Tomcat websockets

### ISSUE THREAD

**Issue by philsttr** [spring-projects/spring-framework#26210]
In a WebFlux application that uses Tomcat as the webserver, the reactor subscriber context is not currently propagated from WebFilters down to WebSocketHandlers.   Therefore objects put into the subscriber context (such as the spring security context) by WebFilters are not available to WebSocketHandlers.

For comparison, when reactor-netty is used as the webserver, the reactor subscriber context _is_ propagated from WebFilters to WebSocketHandlers properly.

I have a WebSocketHandler that needs to access the spring security context.  Unfortunately, this is not currently possible when using tomcat as the webserver.

The disconnect occurs between `TomcatRequestUpgradeStrategy` and `StandardWebSocketHandlerAdapter`...

1. `TomcatRequestUpgradeStrategy.upgrade` constructs a `StandardWebSocketHandlerAdapter` and delegates to the container's websocket upgrade logic  (see [here](https://github.com/spring-projects/spring-framework/blob/8ac39a50feda71194e33a456c0f8207169a5a3a9/spring-webflux/src/main/java/org/springframework/web/reactive/socket/server/upgrade/TomcatRequestUpgradeStrategy.java#L140-L152)).  The context is lost at this point.
2. The container performs the websocket upgrade and calls into `StandardWebSocketHandlerAdapter.onOpen`.
3. `StandardWebSocketHandlerAdapter.onOpen` then delegates to `WebSocketHandler.handle` (see [here](https://github.com/spring-projects/spring-framework/blob/8ac39a50feda71194e33a456c0f8207169a5a3a9/spring-webflux/src/main/java/org/springframework/web/reactive/socket/adapter/StandardWebSocketHandlerAdapter.java#L84-L86)).  I need access to items in the subscriber context within a`WebSocketHandler`, but the context is empty.

To propagate the context, I believe `TomcatRequestUpgradeStrategy.upgrade` could pass the active context to the `StandardWebSocketHandlerAdapter` upon construction (during step 1 above).
Then `StandardWebSocketHandlerAdapter.onOpen` could pass the context to the handler stream (during step 3 above).

**Comment by rstoyanchev** [comment]
Sounds reasonable, will give it a try for 5.3.2.

**Comment by philsttr** [comment]
Thanks Rossen!

If it's simple, I'd love a backport to 5.2.x too if possible.

**Comment by rstoyanchev** [comment]
Sure, let's see how it works out.

**Comment by rstoyanchev** [comment]
It turned out slightly more involved. We can consider a backport but since 5.2.13 is not planned to be released at the same time, I'd prefer to defer for now and see first if 5.3.3 causes any issues.
