### ISSUE TITLE
ReactiveElasticsearchOperations does not have option to include request_cache path param in search request

### ISSUE THREAD

**Issue by oindrilabarik14** [spring-projects/spring-framework#26215]
Elastic search provides an option to add a path param to any search queries  called _request_cache=true which enables it to cache any incoming queries and its results.

The SearchRequest class provides a way to add this param using the .requestCache(Boolean.TRUE) method. But the RequestFactory.java present in Spring DATA that converts a NativeSearchQuery into SearchRequest doesn't support this argument.

Thus this parameter cannot be added to any request for search using ReactiveElasticSearchOperations

**Comment by sbrannen** [comment]
I'm closing this as a duplicate of https://jira.spring.io/browse/DATAES-992.

@oindrilabarik14, please do not open duplicates of the same issue in multiple issue trackers.

Thanks
