### ISSUE TITLE
Will interface"Cache" support "put" with TTL ?

### ISSUE THREAD

**Issue by VikkeyJiang** [spring-projects/spring-framework#26228]
as cache without ttl may cause dos problem (depends on developer )  and sometimes may want cache keys invalid after a period of time, i suggest that interface "Cache" should support "put" with TTL , like 
`void put(Object key, @Nullable Object value, Duration ttl);`

**Comment by snicoll** [comment]
No, it won't and this is already covered in the [reference guide](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-specific-config).

Surfacing such attribute in the higher-level abstraction does not make much sense I am afraid (and TTL values are cache-based, not entry based).
