### ISSUE TITLE
Add in the 'Build from Source' page: what must be the minimum or/and specific Gradle version to develop Spring

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#26221]
---

In the [Build from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) section/page, it has the `Build from the Command Line` section, in case the developer has many Gradle versions installed in the machine, for contributor purposes (play or do some experiments with the project itself). 

* Why not include explicitly a special note or add a new section indicating what must be the _minimum_ **or/and** _specific_ `Gradle` version?

It to import in peace the `spring framework` project in the IDE and avoid potential daemon locks by Gradle.

Remember, in the machine would exists many Gradle versions, 6.6, 6.7 etc installed. So Gradle wrapper would be not an option.

Thanks for your understanding

**Comment by jnizet** [comment]
The page explains that you're supposed to use `./gradlew`, i.e. use the wraper. The whole point of the wrapper is precisely to avoid having to rely on some globally installed gradle versioin, and instead use the version specified in source control ([here](https://github.com/spring-projects/spring-framework/blob/master/gradle/wrapper/gradle-wrapper.properties)), and automatically downloaded the first time you use it if it's not downloaded yet.

Read https://docs.gradle.org/current/userguide/gradle_wrapper.html for more information.

I really don't see why using the wrapper wouldn't be an option.

**Comment by snicoll** [comment]
Thanks @jnizet. 

@manueljordan your IDE is already supposed to use the Gradle wrapper automatically to import settings. If it does not and you want to know which version you should be using you can invoke  `./gradlew --version` from the root of the project.

**Comment by manueljordan** [comment]
Agree, I was very tired to remember that .properties file.  

But perhaps add a mention or indication for the developer to check or see the `gradle-wrapper.properties` file (for more information) would be mentioned in the `Build from the Command Line` section. Just in case. I hope you see the point.

Just doing a quick observation: 

In the [spring-framework/gradle/wrapper/](https://github.com/spring-projects/spring-framework/tree/master/gradle/wrapper) location: Why the `gradle-wrapper.jar` file targets (according with the description) to 6.6 and not 6.7 how the properties file has indicated?. Should be both have the same 6.7 version, right?

Thanks for the support

**Comment by jnizet** [comment]
TBH, I don't see the point. You don't even need to care what version of gradle is being used. You use the gradle wrapper (i.e. `./gradlew`, and not `gradle`), and you're guaranteed to use the correct version of gradle, i.e. the one that the Spring tem uses at that point of the history to build and test the framework.

Regarding the comment, it's probably just that the wrapper jar hasn't changed at all between the versions 6.6 and 6.7 of gradle, so the commit which upgraded to 6.7 only changed the properties file.

**Comment by manueljordan** [comment]
Thanks again for the feedback. Understood. Thank you
