### ISSUE TITLE
Add Hibernate Reactive support

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-framework#26223]
See: http://hibernate.org/reactive/documentation/1.0/reference/html_single/

Change the current Hibernate/JPA support and make it is easy to expose an EntityManagerFactory to use Hibernate Reactive.

Currently, Hibernate Reactive supports Java 8 Completable Stage and Munity, see #26222.
Also hope add Reactor API support to the EMFactory.

**Comment by lazyskulptor** [comment]
I'm making [bridge library](https://github.com/lazyskulptor/hibernate-reactive-spring-api) between Spring and Hibernate Reactive. 
I Hope it helps in any way. 
And give some advice.

**Comment by hantsy** [comment]
It is not difficult to integrate Spring and Hibernate Reactive, check https://itnext.io/integrating-hibernate-reactive-with-spring-5427440607fe

**Comment by jhoeller** [comment]
We still have no plans to provide out-of-the-box support for Hibernate Reactive itself, I'm therefore closing this ticket. If there is anything that blocks a custom integration arrangement there, e.g. some missing flexibility in our general reactive support, please create a dedicated ticket for it.

**Comment by hantsy** [comment]
@lazyskulptor Spring and Spring Data have no plan to support, you can consider moving to Micronaut, it is easy to micronuat if you have some Spring Boot experience. 

There is a Hibernate Reactive module in Micronaut to satisfy all of your requirements. 

Check my Micronaut example project: https://github.com/hantsy/micronaut-sandbox/tree/master/data-hibernate-reactive
