### ISSUE TITLE
AsyncServerResponse interoperability issue with path variables

### ISSUE THREAD

**Issue by alexfeigin** [spring-projects/spring-framework#26239]
**Affects:** \5.3.2
---
There is an interoperability issue with the new `AsyncServerResponse` and routing functions. I tried to create a test in the webmvc project, but I'm afraid I don't know the framework well enough to reproduce it there.
Instead there is a reproduction using springboot, with all the latest greatest spring, and webmvc is managed to 5.3.2-snapshot.
[spring-webmvc-interop-bug](https://github.com/alexfeigin/spring-webmvc-interop-bug)

when routing a request that has path variables, we get routed correctly, and get to a function that returns a `ServerResponse.async` response, but during the handling of the response, the routing function is called again, and we get an exception `org.springframework.web.util.pattern.PatternParseException: Not allowed to capture 'pathVariable' twice in the same pattern`

This does not happen if the response is a non async ServerResponse.

**Comment by alexfeigin** [comment]
@poutsma 
something changed in 5.3.2 snapshot of `AsyncServerResponse` (now `DefaultAsyncServerResponse`) that created the issue, and i'm pretty sure it wasn't the addition of `block` 😋

I just tested 5.3.2 snapshot to see the new block functionality in my tests, but something else is broken

**Comment by poutsma** [comment]
This should be fixed now.

When it has finished building, could you please try a recent snapshot and see if that solves it for you as well?

**Comment by alexfeigin** [comment]
tested against latest snapshot, and my test works!

**Comment by alexfeigin** [comment]
Tested again after this commit (snapshot build 84), everything still works fine.

**Comment by poutsma** [comment]
> Tested against latest snapshot, and my test works correctly, so from my prospective also seems fixed.
> 
> Thank you for the quick response!

Thank you for the quick test run!

I've refactored the code a bit in 2b77c08e09d978d35cfc85584972ce8a0270fd45. It should do the same, but for extra reassurance: could you try a recent snapshot again, and report back?

Thank you for being so quick about this.

**Comment by alexfeigin** [comment]
haha.. I refreshed the snapshot folder in maven waiting for the build to finish.. so I was ahead of you on that one

**Comment by poutsma** [comment]
Thanks!
