### ISSUE TITLE
Upgrade to Hibernate Validator 6.2

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#26255]
Hibernate Validator 6.2 is in the release candidate stage now, probably GA in time for our 5.3.3 release.

**Comment by mkurz** [comment]
@jhoeller Why not Hibernate Validator 7.0? See https://hibernate.org/validator/releases/7.0/#whats-new

**Comment by jhoeller** [comment]
Hibernate Validator 7.0 is `jakarta.validation` based, 6.2 is the last `javax.validation` based line there. That aside, this is just about the version that we use for testing in our build. Generally speaking, we're still compatible with any `javax.validation` based provider.
