### ISSUE TITLE
Cannot access spring repo: 401 repo.spring.io/libs-release 401 Unauthorized error

### ISSUE THREAD

**Issue by rajadas665** [spring-projects/spring-framework#26269]
I am not able to download from spring repo without error.

`[INFO] Building chain-integrations 2.12-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.pom
Downloading from spring-releases: https://repo.spring.io/libs-release/org/glassfish/jersey/media/jersey-media-json-jackson/2.7/jersey-media-json-jackson-2.7.pom
Downloading from spring-releases: https://repo.spring.io/libs-release/org/ehcache/ehcache/3.1.3/ehcache-3.1.3.pom
Downloading from spring-releases: https://repo.spring.io/libs-release/org/elasticsearch/elasticsearch/5.6.0/elasticsearch-5.6.0.pom
Downloading from spring-releases: https://repo.spring.io/libs-release/org/elasticsearch/client/elasticsearch-rest-high-level-client/5.6.0/elasticsearch-rest-high-level-client-5.6.0.pom
Downloading from spring-releases: https://repo.spring.io/libs-release/org/elasticsearch/client/elasticsearch-rest-client/5.6.0/elasticsearch-rest-client-5.6.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.723 s
[INFO] Finished at: 2020-12-14T16:15:18-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chain-integrations: Could not resolve dependencies for project com.cisco.chain.enterprise:chain-integrations:jar:2.12-SNAPSHOT: Failed to collect dependencies at org.apache.httpcomponents:httpclient:jar:4.5: Failed to read artifact descriptor for org.apache.httpcomponents:httpclient:jar:4.5: Could not transfer artifact org.apache.httpcomponents:httpclient:pom:4.5 from/to spring-releases (https://repo.spring.io/libs-release): Authentication failed for https://repo.spring.io/libs-release/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.pom 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
`

``
This is my pom.xml:

`		<repositories>
		<repository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/libs-release</url>
        </repository>`

**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
Could you take a look at [this blog post where we announced those repo.spring.io changes](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020)?

You can fix that by adding another repository definition in your build file as the dependencies listed in this issue are not maintained by the Spring team. The blog post should help you with that.

Sorry about the disruption - you'll find in the blog posts the reasons why we applied those changes.

Thanks!
