### ISSUE TITLE
Fallback with placeholder is evaluated even if the fallback is not required

### ISSUE THREAD

**Issue by FrancoCorleone** [spring-projects/spring-framework#26268]
Hello all,
used spring boot: 2.2.1.RELEASE
Problem: When defining application.yml properties I want to use something like:
property: ${FOO:someFallbackWithEnv_${BAR}}

someOtherProperty: ${property}

With `@ConfigurationProperties` it works as expected but with injection via `@Value` or in application.yml (someOtherProperty) it fails with "could not resolve BAR". I think it is not expected as FOO was defined as env variable so the other part should not be processed at all IMO.

**Comment by FrancoCorleone** [comment]
Great, I did a quick workaround of setting empty in nested env variable and checked it myself in the code, but it doesn't feel like an intuitive behavior. Thanks

**Comment by snicoll** [comment]
That looks like a bug to me and I wish we'd resolve the fallback lazily. I'll see what we can do.

**Comment by snicoll** [comment]
Unfortunately, fixing it goes in the direction of rewriting the parser for supporting the escape of placeholder and separator. This is ongoing but need a new feature release, see #9628
