### ISSUE TITLE
Update OncePerRequestFilter.isAsyncDispatch to use HttpServletRequest.getDispatcherType()

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#26282]
To ensure that the OncePerRequestFilter works when the servlet API is used directly it would be nice to update `OncePerRequestFilter.isAsyncDispatch` to use `HttpServletRequest.getDispatcherType()`

```java
@Override
protected boolean isAsyncDispatch(HttpServletRequest request) {
    return request.getDispatcherType() == DispatcherType.ASYNC;
}
```

See https://github.com/spring-projects/spring-security/issues/4211

**Comment by slyoldfox** [comment]
@rstoyanchev I just had this NPE in a unit test when moving from Spring Boot 2.4.1 to Spring Boot 2.4.3.

It might be safer to flip the arguments in:
```
	protected boolean isAsyncDispatch(HttpServletRequest request) {
		return request.getDispatcherType().equals(DispatcherType.ASYNC);
	}
```

**Comment by sbrannen** [comment]
@slyoldfox, can you please create a new GitHub issue to track that NPE?

**Comment by sbrannen** [comment]
@slyoldfox, out of curiosity, are you invoking `org.springframework.mock.web.MockHttpServletRequest.setDispatcherType(DispatcherType)` with a `null` value somewhere in your tests?

**Comment by slyoldfox** [comment]
@sbrannen it was a silly mockito mock of `HttpServletRequest.class` I have outlined it in the linked issue, thanks for the update :-)
