### ISSUE TITLE
Property resolution for multiple profiles

### ISSUE THREAD

**Issue by Betlista** [spring-projects/spring-framework#26285]
Hi, I asked a [question on StackOverflow](https://stackoverflow.com/questions/60333056/property-resolving-for-multiple-spring-profiles-yaml-configuration), but got no reply, so I'm trying here.

Is it specified somewhere, that when I define multiple profiles, the property resolution will be done in order of specified profiles?

Thanks!

**Comment by snicoll** [comment]
Thank you but let's keep that conversation on StackOverflow.

**Comment by Betlista** [comment]
Well, on StackOverflow it was closed without the conversation :-/

**Comment by snicoll** [comment]
It was closed as a duplicate see the header. Please follow-up there if you have more questions.

**Comment by Betlista** [comment]
From my point of view it was closed wrongly, as duplicate question does not have an answer, just same questions...
