### ISSUE TITLE
AopContext.currentProxy() Incorrect get proxy object

### ISSUE THREAD

**Issue by shenwuwu** [spring-projects/spring-framework#26292]
AopContext.currentProxy() Incorrect get proxy object

The returned object is inconsistent with this

spring版本：5.1.13.release jdk：1.8  springboot：2.1.13.release

`try {
            System.out.println("=========================================>" + this.toString());
            System.out.println("=========================================>" + AopContext.currentProxy());
            return (T)AopContext.currentProxy();
        }catch (IllegalStateException e){
            return (T)this;
        }`

system logs：
=========================================>OrderItemNode{orderItemId='BD22425420121615000607329', coordinate=0.0.0.3, stepType=COMMON, stepId='BusiDet', status=DEALING, orderItemFieldBitmap=5377687649, parentId='BP22929120121615000607317'} CommonNode{fsmInsId='null', contKey='null'}
=========================================>OrderItemNode{orderItemId='OI22425420121710000607900', coordinate=0.0.0.3.1, stepType=WORK_ORDER, stepId='SMS', status=SUBMITTING, orderItemFieldBitmap=1082982432, parentId='BD22425420121615000607329'}

**Comment by quaff** [comment]
提bug请附上单元测试用例，你这给出的信息对定位问题可以说是毫无帮助。

**Comment by snicoll** [comment]
Unfortunately, the description is nowhere near enough to make this issue actionable. I am going to close this now but if you provide a small sample that reproduces the problem we can reconsider.
