### ISSUE TITLE
Improve MockMvc samples in reference to show where static imports come from

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-framework#26311]
Reading https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-mvc-test-server-performing-requests it is not obvious where `post(...)` and the like methods start from.  With the apache http-client on my classpath my IDE wants to suggest that they come from that `RequestBuilder`. I did ultimately find an example with the location on the javadoc, of course the [MockMvc javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/servlet/MockMvc.html), which is not where I'd have looked for this.

**Comment by rstoyanchev** [comment]
Note that we have a section on that https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-mvc-test-server-static-imports but I can insert more links to that from a few places.
