### ISSUE TITLE
Switch to PathPatternParser for Spring MVC breaks welcome page auto configuration

### ISSUE THREAD

**Issue by samotoo** [spring-projects/spring-framework#26318]
Hi,

I'm developing a Spring MVC app using Spring Boot 2.4.1.

I add the following configurations to `application.properties` in order to switch path matching strategy to the new `PathPatternParser`:
```
spring.mvc.pathmatch.matching-strategy=path_pattern_parser
```
But after that access to the root path (/) won't be redirected to `/index.html`. Access the full path `http://xxxxx/index.html` is OK. If switching back to `AntPathMatcher`, redirect works normally.

PS: I set `spring.web.resources.static-locations` to a local directory which contains static resources.

**Comment by rstoyanchev** [comment]
For `PathPattern`, the `DispatcherServlet` determines the `RequestPath` once per request and cache it in a request attribute. The welcome page comes in as "/" initially and results in a forward to "/index.html" but on the forward we don't update the `RequestPath` and it remains as "/".
