### ISSUE TITLE
When default value is configured for property placeholder in @Value, subsequent embedded value resolvers are asked to resolve the default value instead of the original value

### ISSUE THREAD

**Issue by DS4XM** [spring-projects/spring-framework#26328]
Spring Framework version is `5.2.5.RELEASE`.

----

`org.springframework.beans.factory.support.AbstractBeanFactory#resolveEmbeddedValue`

![image](https://user-images.githubusercontent.com/39358545/103391634-609ae780-4b55-11eb-8351-4166135b66e2.png)

----

### Example configuration

```java
@Value("${server.servlet.context-path:/}")
```

### Current behavior

1. When there are multiple `embeddedValueResolvers` registered in the `AbstractBeanFactory` and the first resolver cannot resolve the supplied value, then return `/`.
2. The return value `/` is supplied as the argument for the next resolver's `resolveStringValue()` method, and even if the next resolver is configured to handle resolution of `server.servlet.context-path`, the final result is always `/`.

**Comment by sbrannen** [comment]
@DS4XM, have you configured an explicit `PropertySourcesPlaceholderConfigurer` bean in your `ApplicationContext`?

**Comment by sbrannen** [comment]
@DS4XM, I took the liberty of rewording this issue's title and description.

If I misunderstood your intentions and rephrased things incorrectly, please let me know so that we are certain that we understand what you are trying to convey.

**Comment by DS4XM** [comment]
Yes, in the project have configured an explicit PropertySourcesPlaceholderConfigurer bean to resolve some custom properties file. Then i configured value in application.yml,but application to obtion value still default,and when i configured value in custom properties file, it's working------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sam&amp;nbsp;Brannen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月2日(星期六) 晚上11:52
收件人:&nbsp;&quot;spring-projects/spring-framework&quot;<spring-framework@noreply.github.com&gt;;
抄送:&nbsp;&quot;ixiaobai&quot;<2504625989@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/spring-framework] when set @Value annotation default value, then the config value can&#39;t be obtain (#26328)

**Comment by sbrannen** [comment]
> Then I configured a value in `application.yml`, 

It sounds like you're using Spring Boot instead of the core Spring Framework on its own.

Can you please provide a complete yet minimal sample application (i.e., one that we can download from a GitHub repository or zip file) that demonstrates the behavior you are experiencing?

**Comment by DS4XM** [comment]
I'm sorry to get back to you now. Here is the demo git url: https://github.com/DS4XM/demo.git

**Comment by sbrannen** [comment]
Thanks for providing the demo application.

Before I look into that in detail, please allow me to clarify something first.

Is the behavior you are describing a regression for use cases that were supported in previous versions of the Spring Framework?

If so, which versions?

Or are you rather making a proposal for a change in behavior in the Spring Framework?

Or are you simply asking for assistance in achieving your goal in your own application without a change to the Spring Framework?

**Comment by DS4XM** [comment]
the Spring Framework version is 5.2.5.RELEASE

**Comment by sbrannen** [comment]
> the Spring Framework version is 5.2.5.RELEASE

OK. That is the version you are currently using.

Did your application work as expected in a version _prior_ to 5.2.5?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by DS4XM** [comment]
i am sory to late too response, in the demo application spring version is 5.2.5, the prior version without use
