### ISSUE TITLE
Getting Started Guides  - Links for Build with Maven, Gradle and IDE don't work

### ISSUE THREAD

**Issue by sam1999uk** [spring-projects/spring-framework#26356]
![Capture](https://user-images.githubusercontent.com/41189303/103912912-ccee8b80-50ff-11eb-84e0-56a67352e111.PNG)
For example, go to https://spring.io/guides/gs/accessing-data-gemfire/ and click on the Build With Maven link. It doesn't do anything.

**Comment by bclozel** [comment]
Sorry to close this issue here, but a dedicated team is taking care of Spring guides and this will be better handled in the dedicated repository.

Could you create an issue against https://github.com/spring-guides/gs-accessing-data-gemfire/issues ?

Thanks!
