### ISSUE TITLE
Spring Data Rest Documentation Issue

### ISSUE THREAD

**Issue by ejgreenwald** [spring-projects/spring-framework#26350]
Hi, this is my first ever issue so I hope I don't screw it up :)

In the Spring Data Rest [documentation](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.methods) it says:

`For details on how to tweak the default method exposure or dedicated HTTP methods individually see`

It doesn't have a link and seems to be missing part of the sentence. Hope I'm not missing anything and love the Spring Framework, thanks!!

**Comment by bclozel** [comment]
Could you create this issue against the Spring Data REST repository?

https://github.com/spring-projects/spring-data-rest/issues

Thanks!
