### ISSUE TITLE
Webflux and ServerResponse with generic type 

### ISSUE THREAD

**Issue by mmaryo** [spring-projects/spring-framework#26352]
Hello

I suggest an enhancement about types of `ServerResponse` for Spring Boot Webflux and Kotlin

All routes have to same response type like 

`fun post(request: ServerRequest): Mono<ServerResponse>`

But it's better to have 

 `fun post(request: ServerRequest): Mono<ServerResponse<CategoryResult>>`

Any plan about it ?

**Comment by poutsma** [comment]
Not all `ServerResponse` instances return entities, some do server-side rendering for instance. If you really care about the the entity type that will be serialized, there is a specific subtype `EntityResoponse<T>` that is parametrized and that you can use instead of a plain `ServerResponse`.
