### ISSUE TITLE
Request to log stack trace in AbstractHandlerExceptionResolver when enable `warnLogCategory`

### ISSUE THREAD

**Issue by sammyhk** [spring-projects/spring-framework#26358]
**Affects:** 5.2.12.RELEASE

---

Currently by default HandlerExceptionResolvers which enabled `warnLogCategory` only log a simple message such like "Resolved [<exception.toString()>]" without the stack trace, which is difficult to debug. Suggest to also log stack trace (https://github.com/spring-projects/spring-framework/blob/e36d4162c254826d8cde048bd17691e312b4fcaa/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerExceptionResolver.java#L207)

Interestingly, this behavior was introduced in https://github.com/spring-projects/spring-framework/issues/17691 (https://github.com/spring-projects/spring-framework/commit/a08c9f3137d114bbdd0cdb2800024d45a6a21e3a#diff-79219eb3028165aaa060f6e3db7e70a2a50b5dccd01387f03fed02a3bdf89ca8L183-R186), maybe we can balance the needs by introduce another option to enable/ disable logging stack trace.

**Comment by rstoyanchev** [comment]
We generally don't log resolved exceptions. The idea is that it provides hint if enabled. If you want to customize, the method in question is protected and intended for extension.
