### ISSUE TITLE
add module

### ISSUE THREAD

**Issue by JayisGH** [spring-projects/spring-framework#26391]
when I use source of spring-framework, the gradle build task pass though,
but there was error like below whether I add a module
what should I do
  
![截屏2021-01-15 下午9 09 33](https://user-images.githubusercontent.com/47267802/104731158-4298ce00-5776-11eb-9bf3-aec323778f5d.png)

![截屏2021-01-15 下午9 13 39](https://user-images.githubusercontent.com/47267802/104731414-9e635700-5776-11eb-9337-0d1edc0b36c2.png)

**Comment by bclozel** [comment]
Our build is configured to apply source code style checks. I guess your source code does not respect the style rules enforced by our build. The report linked in your console should tell you more.

If you'd like to contribute brand new code/modules to Spring Framework, please create an enhancement request first.
