### ISSUE TITLE
Use java 11 style with var when use val style for Kotlin

### ISSUE THREAD

**Issue by yilativs** [spring-projects/spring-framework#26395]
Documentation  uses old java 8 style and for code samples and at same time uses Kotlin val style.

Here is an example 
Java  (now)
`ApplicationContext context = new ClassPathXmlApplicationContext("services.xml", "daos.xml");`
Kotlin(now)
`val context = ClassPathXmlApplicationContext("services.xml", "daos.xml")`

Please, use Java 11 style so java section should be:
`var  context = new ClassPathXmlApplicationContext("services.xml", "daos.xml");
`

**Comment by snicoll** [comment]
Thanks for the suggestion but Spring Framework has support for Java 8 still and it would be misleading to have samples showcased in the doc that do not work with Java 8.
