### ISSUE TITLE
Two beanvalidation test packages look the same

### ISSUE THREAD

**Issue by limo520** [spring-projects/spring-framework#26419]
There are two test packages . one is 'org.springframework.validation.beanvalidation2' in spring-context-support, another is 'org.springframework.validation.beanvalidation' in spring-context. Is there a special purpose?

**Comment by jhoeller** [comment]
The only reason for it is that we test against distinct generations of the Bean Validation API - 1.1 and 2.0 - and corresponding Hibernate Validator versions there, and can only really separate those dependencies into different modules there.
