### ISSUE TITLE
code block displaying incorrectly in documentation for Restdocs

### ISSUE THREAD

**Issue by CubeOfCheese** [spring-projects/spring-framework#26417]
I'm not sure if this is the correct repository to report in, but the docs seem to have a display error on Creating API Documentation with Restdocs https://spring.io/guides/gs/testing-restdocs/
where it says
> The following example shows what to add if you use Gradle:

the code block is empty.
<img width="795" alt="Screen Shot 2021-01-20 at 7 50 20 PM" src="https://user-images.githubusercontent.com/16740469/105277681-bbbe6980-5b58-11eb-88df-a8ab551ad8b4.png">

**Comment by bclozel** [comment]
Thanks for raising this issue. This is now fixed.

Getting started guides have dedicated repositories where you can create issues and submit PRs.
If you find other problems with this guide, [please raise a new issue against its tracker](https://github.com/spring-guides/gs-testing-restdocs/issues).

Thanks!
