### ISSUE TITLE
WebMvcConfigurationSupport.beanNameHandlerMapping does not set PathPatternParser

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#26414]
[WebMvcConfigurationSupport.beanNameHandlerMapping](https://github.com/spring-projects/spring-framework/blob/584dabbb3980dbed5272f79a61aa996d390e528c/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L511) creates a `BeanNameUrlHandlerMapping` instance but does not call `setPatternParser`.

Other mappings in the class have the following code:

```java
PathPatternParser patternParser = getPathMatchConfigurer().getPatternParser();
if (patternParser != null) {
    mapping.setPatternParser(patternParser);
}
```

**Comment by rstoyanchev** [comment]
The idea probably was that you don't need it mappings in bean names but it looks like they do support patterns.
