### ISSUE TITLE
Use lambda form of Assert.notNull in UrlPathHelper

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#26413]
[UrlPathHelper.getResolvedLookupPath](https://github.com/spring-projects/spring-framework/blob/584dabbb3980dbed5272f79a61aa996d390e528c/spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java#L214) is called a lot and it constructs a new message String each time. We should switch to use the lamba call instead.

**Comment by jhoeller** [comment]
Isn't that String effectively a compile-time constant anyway since it just concatenates a local String with a static final constant value? I'd expect the present variant to be more efficient then since even the lambda instance has some minor overhead...

**Comment by philwebb** [comment]
Yes. Sorry. For some reason I read it a a concat of `lookupPath`.
