### ISSUE TITLE
Provide a way to modify RequestMappingInfo conditions

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#26428]
Spring Data Rest needs to take a `RequestMappingInfo` and modify the produces condition. It's currently not possible to do this because the [required constructor](https://github.com/spring-projects/spring-framework/blob/e537844a093d313595e20cc440506fe8b04bc7db/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/RequestMappingInfo.java#L154) is `private`.

I think that constructor either needs to be `public`, or we need some `with...` methods that return new instances with updated values (similar to [`addCustomCondition`](https://github.com/spring-projects/spring-framework/blob/e537844a093d313595e20cc440506fe8b04bc7db/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/RequestMappingInfo.java#L309).

**Comment by philwebb** [comment]
Relates to #26415

**Comment by rstoyanchev** [comment]
`RequestMappingInfo` has a builder which is why the public constructors are deprecated. We can add a `.mutate()` instance method on `RequestMappingInfo` that gives a Builder pre-populated with the content of the instance. Does that sound okay? What exactly needs to be changed on the produces condition, perhaps we can tailor the Builder even better to that somehow?

**Comment by philwebb** [comment]
We probably need some input from @odrotbohm. Currently the system looks quite flexible, it takes the `ProducesRequestCondition` and calls a protected method that can adapt it. You can see the code in [BasePathAwareHandlerMapping](https://github.com/spring-projects/spring-data-rest/blob/5ccf13927886fe001949e3cdc0ae4a0c4c135c4b/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/BasePathAwareHandlerMapping.java#L124).

> We can add a .mutate() instance method on RequestMappingInfo that gives a Builder pre-populated with the content of the instance

That might be an option, but there's currently no builder methods that take the `ProducesRequestCondition` objects. There's only `produces(String... produces)`.

**Comment by rstoyanchev** [comment]
There is an issue in the referenced code since the `RequestMapingInfo` may have a `PathPatternsRequestCondition` instead of a `PatternsRequestCondition`. I'll add a `.mutate()` method on `RequestMappingInfo` to support the use case of changing it.

**Comment by philwebb** [comment]
Unfortunately the `mutate()` build won't allow us to change the `ProducesRequestCondition`. It only has a `produces(String...)` version. I think we need a version that will allow us to set the `ProducesRequestCondition` directly.

Either that, or we need to change the `BasePathAwareHandlerMapping` contract.

**Comment by odrotbohm** [comment]
I have a fix ready that customizes the `ProducesCondition` and then extracts the media types to pass them into the `produces(…)` method. This looks like a bit of extra work but does the trick for now. Just waiting for @mp911de decision on when we can actually merge this as it requires Spring Data to upgrade to 5.3.4 snapshots.
