### ISSUE TITLE
Provide better lifecyle for WebMvcConfigurer.configurePathMatch

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#26427]
Currently `WebMvcConfigurer.configurePathMatch(...)` is called as a side-effect of `WebMvcConfigurationSupport.getPathMatchConfigurer()`. This makes it quite hard to use in `@Bean` method since it's hard to tell if the `@Bean` method or the `configurePathMatch(...)` method will be called first.

You can see an example of this in Spring Data Rest where the [restHandlerMapping](https://github.com/spring-projects/spring-data-rest/blob/5ccf13927886fe001949e3cdc0ae4a0c4c135c4b/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.java#L640) bean would ideally have a `PatternParser` on the delegates before the `afterPropertiesSet()` method is called. The current solution of overriding `configurePathMatch` and calling `setPatternParser` directly is brittle because the parser is needed before `afterPropertiesSet()` is called. This leads to issues such as #26415

It's possible to work-around the issue by adding `@DependsOn("mvcPathMatcher")` which will indirectly trigger the `WebMvcConfigurationSupport.getPathMatchConfigurer()` method, but this isn't ideal.

I wonder if we could make `PathMatchConfigurer` or the `PatternParser` a `@Bean` so that it can be injected directly if it's needed?

**Comment by rstoyanchev** [comment]
We could expose an `mvcPatternParser` bean that mirrors the `mvcPathMatcher()` bean and exposes a global `PathPatternParser` for use throughout the application. The `restHandlerMapping` bean in Spring Data REST would then make use of that and configure its own handler mappings before calling `afterPropertiesSet`. 

The one catch is that by doing this Spring Data REST opts into always using parsed patterns, which may be a reasonable choice I think. It performs better and supports largely the same syntax (except for notably `**` in any but the last segment of the path) so it should be transparent. What do you think @odrotbohm?

**Comment by rstoyanchev** [comment]
I've added assertions in HandlerMapping implementations to ensure the PathPatternParser is rejected if it is too late and I've also added an `mvcPatternParser` bean. Spring Data REST can inject this bean into its mappings, effectively always opting into parsed patterns.

**Comment by rstoyanchev** [comment]
@odrotbohm are the current changes sufficient in which case we can close this?

**Comment by odrotbohm** [comment]
I think we're set. Fixes already in Spring Data REST master and supported branches for quite a while.

**Comment by rstoyanchev** [comment]
Okay thanks.
