### ISSUE TITLE
Make it easy to run both Spring Messaging and RSocket-RPC simultaneously

### ISSUE THREAD

**Issue by bsideup** [spring-projects/spring-framework#26423]
As a user of [rsocket-rpc-java](https://github.com/rsocket/rsocket-rpc-java) in [Liiklus](https://github.com/bsideup/liiklus), I would like to be able to reuse Spring {Framework,Boot}'s RSocket support, and be able to handle `rsocket-rpc` requests while having some routes (as per [RSocket's Routing](https://github.com/rsocket/rsocket/blob/master/Extensions/Routing.md)) defined as Spring Messaging's handlers.

Expectation:
1. I create an instance of `RSocketRPCRouteHandler` that `rsocket-rpc` generated for me
2. I register it to _some_ registry of `RouteHandler`s
3. While handling RSocket requests, Spring's RSocket support delegates to _some_ abstraction that uses registered `RouteHandler`s to decide which one should handle the request

This all is very similar to the HTTP support & Servlets API, where a `Servlet` can be added next to Spring Framework's `DispatcherServlet` and handle a subset of requests.

**Comment by rstoyanchev** [comment]
This requires a lower level routing mechanism, so I've created https://github.com/rsocket/rsocket-java/issues/974. When that mechanism becomes available, I expect it to be possible to plug multiple, independent RSocket handlers which by definition should be independent of each other and not be aware of each other. So I'll close this for now and we can create a new one later one when it's more obvious what if anything needs to be done.
