### ISSUE TITLE
Difficulty importing root project 'spring' into IDEA

### ISSUE THREAD

**Issue by vmvm-org** [spring-projects/spring-framework#26444]
**Affects:** 5.3.4-SNAPSHOT

When importing into idea:

```
Warning:<i><b>root project 'spring': Unable to resolve additional project configuration.</b>
Details: java.lang.IllegalStateException: Resolving dependency configuration 'testFixturesCompileOnly' is not allowed as it is defined as 'canBeResolved=false'.
Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'testFixturesCompileOnly' should be resolved.</i>
```

**Comment by bclozel** [comment]
What do you mean by importing? Are you building the project on the command line? Or are you importing the project in your IDE?

In any case, did you have a look to the [CONTRIBUTING docs](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source)?

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by vmvm-org** [comment]
> What do you mean by importing? Are you building the project on the command line? Or are you importing the project in your IDE?
> 
> In any case, did you have a look to the [CONTRIBUTING docs](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source)?

I building the project on the command line and importing the project in my IDEA but that was fail.
