### ISSUE TITLE
Improve reference documentation on Resources

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#26447]
## Status Quo

As discussed in #26443, the [Resources section](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#resources) of the reference documentation is very outdated, focusing primarily on XML-based configuration of the resource locations for the `ApplicationContext` and not directly mentioning `ResourcePatternResolver` at all.

## Deliverables

- [x] Discuss the `ResourcePatternResolver` API as an alternative to the `ResourceLoader` API.
- [x] Document `PathResource` as a built-in `Resource`.
- [ ] Consider providing examples where resources are injected into fields of type `Resource` or `Resource[]` in `@Configuration` classes or annotated components via `@Autowired` or `@Value` semantics.

**Comment by sbrannen** [comment]
@nightswimmings, I've completed all planned changes to the [Resources](https://docs.spring.io/spring-framework/docs/5.3.5-SNAPSHOT/reference/html/core.html#resources) section of the reference manual.

Please take a look and let us know if we've addressed all of the concerns you raised in #26443.

**Comment by nightswimmings** [comment]
@sbrannen  Much clearer now, thanks!!
