### ISSUE TITLE
Difficutly building source code in IntelliJ

### ISSUE THREAD

**Issue by HappyDale** [spring-projects/spring-framework#26441]
Difficutly building source code in IntelliJ

Env:
OS: win10(10.0.18363.1316 showed by cmd)
jdk: jdk11.0.10(AdoptOpenJDK)
gradle: 6.7.1
idea: 2020.2
build was based on  commit: e4dc863ad09ed942430c4775623eda2867d9800d

I have followed this https://github.com/spring-projects/spring-framework/wiki/Build-from-Source#before-you-start
1.Problem presentation （annotation from jdk.jfr in FlightRecorderStartupEvent.java was not exist）
![image](https://user-images.githubusercontent.com/24730191/105704375-ae82ef80-5f49-11eb-81ae-5edc775f895b.png)
2.using jdk
![image](https://user-images.githubusercontent.com/24730191/105704424-be9acf00-5f49-11eb-9c79-46d74395ab07.png)
3.gradle setting
![image](https://user-images.githubusercontent.com/24730191/105704455-c9edfa80-5f49-11eb-86aa-b4b67dee787a.png)
4.my JAVA_HOME
![image](https://user-images.githubusercontent.com/24730191/105704538-ed18aa00-5f49-11eb-8650-7b9594470eb3.png)

am i using wrong jdk setting? Why can't I run my demo.Hope to get a reply

**Comment by mdeinum** [comment]
You did follow the guidelines on how to import into [Intellij](https://github.com/spring-projects/spring-framework/blob/master/import-into-idea.md)? That being said the language level should be JDK8 and not JDK11 although I believe it should work JDK11 when set to the correct language level.

**Comment by HappyDale** [comment]
> You did follow the guidelines on how to import into [Intellij](https://github.com/spring-projects/spring-framework/blob/master/import-into-idea.md)? That being said the language level should be JDK8 and not JDK11 although I believe it should work JDK11 when set to the correct language level.

Thank u! I only noticed the newer JDK version. Problem can be solved with JDK 8 update 262.
However i still can't understand why jdk11.0.10 doesnt work in my environment
