### ISSUE TITLE
Document the "SpringProperties mechanism" mentioned in the testing chapter

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#26492]
**Affects:** 5.3.3

The testing chapter mentions the `SpringProperties` mechanism or API in three places but doesn't explain what the mechanism is. I searched in the core chapter and couldn't find a description there. Apologies if I missed it. I presume it's `org.springframework.core.SpringProperties`. Perhaps some documentation could be added describing the mechanism or at least a link to the javadoc to help to join the dots?

**Comment by sbrannen** [comment]
> The testing chapter mentions the `SpringProperties` mechanism or API in three places but doesn't explain what the mechanism is. I searched in the core chapter and couldn't find a description there. Apologies if I missed it. 

No, you didn't miss anything. It's simply not documented.

> I presume it's `org.springframework.core.SpringProperties`. 

Yes, that's correct.

> Perhaps some documentation could be added describing the mechanism or at least a link to the javadoc to help to join the dots?

For the time being, I have linked to the Javadoc for `SpringProperties` in the Testing chapter, but we may later decide to provide more comprehensive documentation for all Spring properties in the reference manual.

**Comment by wilkinsona** [comment]
Thanks for the updates, Sam. Would it be better to use the `api-spring-framework` attribute to avoid hardcoding the whole link each time?

**Comment by sbrannen** [comment]
Ummmm.... yes it would!

Thanks for the reminder about that attribute. I'll fix it!
