### ISSUE TITLE
Inconsistency between source code and reference manual for StoredProcedure

### ISSUE THREAD

**Issue by tyutyutyu** [spring-projects/spring-framework#26505]
**Affects:** 2.0.0 - 5.3.3

---
The first paragraph of the `StoredProcedure`'s documentation mentions that the `execute` methods of this class are protected (which is the desired behavior), but in the source code they are public.

https://docs.spring.io/spring-framework/docs/2.0.0/reference/jdbc.html#jdbc-StoredProcedure
https://docs.spring.io/spring-framework/docs/2.5.x/reference/jdbc.html#jdbc-StoredProcedure
https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/htmlsingle/#jdbc-StoredProcedure
https://docs.spring.io/spring-framework/docs/4.3.x/spring-framework-reference/htmlsingle/#jdbc-StoredProcedure
https://docs.spring.io/spring-framework/docs/5.3.x/reference/html/data-access.html#spring-data-tier

3.0.0.RELEASE - StoredProcedure.java: https://github.com/spring-projects/spring-framework/blob/30604ae861d378669a9719918f3068dadcc5aed5/org.springframework.jdbc/src/main/java/org/springframework/jdbc/object/StoredProcedure.java#L114
5.3.3 - StoredProcedure.java: https://github.com/spring-projects/spring-framework/blob/91509805b759a108d7eca0b6b3041c434c61d837/spring-jdbc/src/main/java/org/springframework/jdbc/object/StoredProcedure.java#L110

**Comment by sbrannen** [comment]
This has been fixed in 59818ceca9c13e7181a11f6985746c946d5ce34b.

Thanks for bringing it to our attention.
