### ISSUE TITLE
@Cacheable or @CacheEvict invalid

### ISSUE THREAD

**Issue by panpengfei21** [spring-projects/spring-framework#26514]
**Affects:** \<spring-context  5.2.9.RELEASE>
---

@Cacheable @CacheEvict invalid

```
@service
pubic class TestService {

  @Cacheable(cacheNames ="user",key = "#userId")
  public User fetchUserById(Long userid) {
       return new User();
  }

  public User fetchCurrentUser() {
      return fetchUserById(124L);
  }

}

```

`@Cacheable` is valid, when I invoke `fetchUserById(Long userid)`.
`@Cacheable` is invalid, when I invoke `fetchCurrentUser()`.

**Comment by bclozel** [comment]
This is [the expected and documented behavior](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-annotation-enable):

> The default advice mode for processing caching annotations is proxy, which allows for interception of calls through the proxy only. Local calls within the same class cannot get intercepted that way. For a more advanced mode of interception, consider switching to aspectj mode in combination with compile-time or load-time weaving.

Thanks!
