### ISSUE TITLE
Tracing information is missing when Exception is thrown from JmsListener methods

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-projects/spring-framework#26532]
**Affects:** 5.3.3
---

The issue was originally reported for Spring Cloud Sleuth but it seems it is not a Sleuth issue (and I can't transfer issues across orgs) so I'm opening this one to track it at the right place.

The original issue is this: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1663 opened by @m-grzesiak
It contains the details to understand what is going on, a sample project that reproduces the issue and some investigation details. The issue is very similar to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1660

**Description**
When an exception is thrown from a method annotated with `@JmsListener` all tracing information is lost when it reaches the error handler and error logs do not contain tracing information.

**Sample**: https://github.com/jonatan-ivanov/sleuth-gh-1663

Investigation details: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1663#issuecomment-749835267 (also see spring-cloud/spring-cloud-sleuth#1660)
Possible fix (breaking change): should be similar to https://github.com/spring-projects/spring-amqp/pull/1287

**Comment by bclozel** [comment]
This is superseded by #30335
