### ISSUE TITLE
IllegalArgumentException due to lack of a cached lookupPath

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#26546]
After the changes to support parsed `PathPattern` in #24945, various components such as `MappedInterceptor`, `UrlBasedCorsConfigurationSource` and others expect to find a pre-resolved, cached lookupPath via  `ServletRequestPathUtils.getCachedPath`. This is done for sub-classes for `AbstratHandlerMethodMapping` and `AbstractUrlHandlerMapping` but others that extend directly from `AbstractHandlerMapping` would need to call `initLookupPath` in order for `MappedInterceptor` and others to find the lookupPath. 

This is the case with `FlowHandlerMapping` in Spring Web Flow, reported in [SWF-1744](https://jira.spring.io/browse/SWF-1744), which does not need the lookupPath itself but nevertheless that still breaks auxiliary components like `MappedInterceptor`. We can address this in `AbstractHandlerMapping#getHandlerExecution` to ensure the presence of a cached lookupPath if not already added by sub-classed in `getHandlerInternal`.

**Comment by rodwiddowson** [comment]
@rstoyanchev Just FYI.  Having got through out Servlet-build glitch I just ran the reproducer against 5.3.5-SNAPSHOT and all is good.  (We knew it would but but....)

**Comment by rstoyanchev** [comment]
@rodwiddowson thanks for checking. The fix is in 5.3.4. You should be able to use that. It is already out.
