### ISSUE TITLE
ResultSet holdability into the View layer broken by Hibernate 5

### ISSUE THREAD

**Issue by symposion** [spring-projects/spring-framework#26557]
Some time ago a fix was introduced for this: https://github.com/spring-projects/spring-framework/issues/16954 . It allows specifying that ResultSets should be held open beyond transaction commit. (Separate problem: there's no easy way to do this for JPATransactionManager, which makes usage with Spring Data hard). In the meantime, however, changes made in Hibernate 5 have re-broken this functionality. Hibernate now aggressively closes all JDBC resources on transaction commit, and the Hibernate maintainers have basically said that cursor holdability is evil and they're not interested in supporting it (https://discourse.hibernate.org/t/resultset-holdability-not-working-with-hibernate/1445/9)

As things stand, this makes it pretty much impossible (AFAICT) to build a fully streaming stack from database to MVC layer (using Open Session In View) - in particular a streaming REST API that returns a stream of JSON objects from a large dataset. It also renders HibernateTransactionManager.allowResultSetAccessAfterCompletion pointless because Hibernate closes the result set anyway, irrespective of the behaviour of the underlying JDBC driver.

It's not clear to me if there's a viable solution for any of this, but as a minimum it would be great if this was clearly documented as a limitation. I've spent hours wandering through issues, forum posts + SO answers getting conflicting information about this and it would be good to have a definitive statement of what is and isn't possible in this regard

**Comment by jhoeller** [comment]
Reading up on the current state of affairs, it seems appropriate to deprecate `setAllowResultAccessAfterCompletion` since there is no chance of this getting addressed in the Hibernate 5.x line. Also, Spring only supports Hibernate 6.x via JPA which does not have an equivalent setting to begin with.
