### ISSUE TITLE
Spring-test:5.3.4 - MockHttpServletRequest depends on javax.servlet-api:4.+

### ISSUE THREAD

**Issue by KevinMcT** [spring-projects/spring-framework#26570]
Not requesting a change more a concern regarding this patch release.

Following commit https://github.com/spring-projects/spring-framework/commit/f22e2ac578f6db8f988cbbee0af5f381a86fdd04
Changed MockHttpServletRequest to utilize HttpServletMapping internally.

HttpServletMapping is an interface provided by the latest servlet-api - javax.servlet-api:4.+

Our projects auto import patch releases, thus with the 5.3.4 release any project utilizing the MockHttpServletRequest resolved in a failed master build as the dependency to the latest servlet-api is not something we've imported as an explicit dependency.

Find it strange that this would be released as a patch version and not part of a minor.

**Comment by sbrannen** [comment]
Closing as a duplicate of #26555

**Comment by sbrannen** [comment]
> Find it strange that this would be released as a patch version and not part of a minor.

It was indeed a bit unconventional to include the _binary_ dependency on Servlet 4 APIs in the point release, but the Servlet API mocks have actually been based on Servlet 4 since Spring Framework 5.0.

**Comment by sbrannen** [comment]
Please note that the hard dependency on Servlet 4 in `spring-test` will be reverted in Spring Framework 5.3.5.

For details, see https://github.com/spring-projects/spring-framework/issues/26555#issuecomment-781992923.
