### ISSUE TITLE
Log level for SingleConnectionFactory.onException() callback should be WARN or ERROR

### ISSUE THREAD

**Issue by Evgen1000end** [spring-projects/spring-framework#26579]
In current version log level  for SingleConnectionFactory.onException() callback is INFO.

https://github.com/spring-projects/spring-framework/blob/274db2f7a934c1558eee25809ceab3982ab73e1c/spring-jms/src/main/java/org/springframework/jms/connection/SingleConnectionFactory.java#L367

Maybe change the logging level to WARN or ERROR?

**Comment by snicoll** [comment]
@IIShabalin thanks for the offer but we haven't triaged this one yet.

**Comment by snicoll** [comment]
@Evgen1000end this was set to `INFO` rather than `WARN` on purpose (see https://github.com/spring-projects/spring-framework/issues/21485). The idea is that the connection can reset itself so you shouldn't get such log unless you're opting-in for more info.

**Comment by IIShabalin** [comment]
> @IIShabalin thanks for the offer but we haven't triaged this one yet.

Ok.
Then, maybe, you can suggest an issue I could start from?
