### ISSUE TITLE
LinkedMultiValueMap replaces % with %25

### ISSUE THREAD

**Issue by M-Smits** [spring-projects/spring-framework#26582]
**Version: spring-boot-starter-web version 2.4.1.**

Hello,

I am trying to make a post request using LinkedMultiValueMap<>() for authentication but I keep receiving a 400 BAD REQUEST. 

When I send it as a raw string I get a 200. Code:

  ```
  String test = "client_secret=1234&grant_type=refresh_token&refresh_token=1%2F%2F&client_id=12345";
  ResponseEntity<String> stringResponseEntity = restTemplate.postForEntity("/token", test, String.class);
```

![Screenshot 2021-02-21 at 16 34 13](https://user-images.githubusercontent.com/9571065/108629984-da1eca00-7462-11eb-8dd6-e7418cca75a6.png)

When I send it as a LinkedMultiValueMap<>(). Code:

```    
        MultiValueMap<String, Object> formUrlEncoded = new LinkedMultiValueMap<>();
        formUrlEncoded.add("client_secret", "1234");
        formUrlEncoded.add("grant_type", "refresh_token");
        formUrlEncoded.add("refresh_token", "1%2F%2F");
        formUrlEncoded.add("client_id", "12345");

        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setContentType(MediaType.APPLICATION_FORM_URLENCODED);

        HttpEntity<MultiValueMap<String, Object>> httpEntity = new HttpEntity<>(formUrlEncoded, httpHeaders);

        ResponseEntity<String> stringResponseEntity = restTemplate.postForEntity("/token", httpEntity, String.class);
```

![Screenshot 2021-02-21 at 16 37 17](https://user-images.githubusercontent.com/9571065/108630046-3bdf3400-7463-11eb-96c0-b338a633eef4.png)

What I noticed is that the value of the **refresh_token is changed** and **% is replaced with %25**??  

I know the solution (Send as a string), but still I find this weird and I want to know why this is happening? What am I not seeing?

**Comment by M-Smits** [comment]
Further investigation:

I started to investigate the read() method from FormHttpMessageConverter.class.
I noticed the URLDecoder.decode() is used to decode the values for some reason?


```
case '%':
                /*
                 * Starting with this instance of %, process all
                 * consecutive substrings of the form %xy. Each
                 * substring %xy will yield a byte. Convert all
                 * consecutive  bytes obtained this way to whatever
                 * character(s) they represent in the provided
                 * encoding.
                 */

                try {

                    // (numChars-i)/3 is an upper bound for the number
                    // of remaining bytes
                    if (bytes == null)
                        bytes = new byte[(numChars-i)/3];
                    int pos = 0;

                    while ( ((i+2) < numChars) &&
                            (c=='%')) {
                        int v = Integer.parseInt(s, i + 1, i + 3, 16);
                        if (v < 0)
                            throw new IllegalArgumentException(
                                    "URLDecoder: Illegal hex characters in escape "
                                            + "(%) pattern - negative value");
                        bytes[pos++] = (byte) v;
                        i+= 3;
                        if (i < numChars)
                            c = s.charAt(i);
                    }
```


Now why are my values being decoded?

**Comment by rstoyanchev** [comment]
This is by design. Form data name-value pairs are [expected to be percent encoded](https://url.spec.whatwg.org/#urlencoded-serializing) and this is what the converter is doing. That means the values you pass in are not expected to be encoded already.

**Comment by M-Smits** [comment]
@rstoyanchev Thank you for your feedback. I do not see if I am not doing something wrong but based on your answer, neither is spring.  It seems I cannot use the LinkedMultiValueMap since 1%2% is send as 1%252%25 and the server returns a bad request because it expects the secret the be 1%2% and not 1%252%2. I send it as a www-x-form-urlencoded because that's how the documentation and test curls do it. Is there a way to avoid this behaviour?
