### ISSUE TITLE
Spring RSocket client send unexpected data whose payload is wrong when during connecting and cause unlimited retry

### ISSUE THREAD

**Issue by KaimingWan** [spring-projects/spring-framework#26626]
**Basic env info:**

OS: mac os 10.15.4
JDK: openjdk8
Springboot version: 2.3.4.RELEASE

**Reproduce:**

I create a spring rsocket client as follows. The requesterMono object is prepared for sending data.
```java
// prepare requester object
 Mono<RSocketRequester>   requesterMono = rsocketRequesterBuilder.setupRoute("conn-setup")
            .setupData(new ObjectMapper().writeValueAsString(connAuthDTO))
            .dataMimeType(MimeTypeUtils.parseMimeType(WellKnownMimeType.APPLICATION_JSON.getString()))
            .rsocketConnector(connector -> connector.acceptor(responder)
                .fragment(MTU_BYTE_SIZE)
                .keepAlive(Duration.ofSeconds(KEEP_ALIVE_INTERVAL_SEC), Duration.ofSeconds(KEEP_ALIVE_MAX_TIME_SEC))
                .reconnect(Retry.fixedDelay(Integer.MAX_VALUE, Duration.ofSeconds(RSOCKET_RETRY_INTERVAL_SECONDS))
                    .doAfterRetry(retrySignal -> log.warn("RSocket client is reconnecting to get the newest connection...."))))
            .connect(TcpClientTransport.create(TcpClient.create()
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, TCP_CONN_TIMEOUT)
                .option(ChannelOption.TCP_NODELAY, true)
                .option(ChannelOption.SO_KEEPALIVE, true)
                .host(clientAuthManager.acquireServerDomain())
                .port(SERVER_PORT)
                .secure(ssl -> ssl.sslContext(sslContext))));

//send data with requesterMono
    public RSocketRequester getWorkingRequester() {
        RSocketRequester requester = requesterMono.block(Duration.ofSeconds(1));
        if (requester == null || requester.rsocket().isDisposed()) {
            throw new RuntimeException("try to get rsocket requester ,but it is ABNORMAL....");
        }
        return requester;
    }
```

The expected setup payload should be a json value of ConnAuthDTO. 
```java
public class ConnAuthDTO {

    private String ak;

    private String sk;

    private String ip;

    /**
     * sidecar's unique identify
     */
    private String wsn;

    private long   sendAuthTimeMs;
}
```

The rsocket client have another schedule thread periodically send rsocket request like invoke method 'updateWorkerState' to send data by rsocket . The request will invoke getWorkingRequester to get the requester and send data. The data payload's related class is :
```java
@Data
public class WorkerUpdateDTO {

    private WorkerIdentity workerIdentity;

    private WorkerState    workerState;

    private String         localIp;

    private String         externalIp;

    private boolean        needUpdateLocalIp;

    private boolean        needUpdateExternalIp;

    private Date           sendDate;
}

//WorkerIdentity definition
@Data
@Builder
public class WorkerIdentity {

    @Tolerate
    public WorkerIdentity(){
    }

    private String workerSeqNumber;

    private String accessKey;

    private String localIp;
}



```

When server is restarted, client will try to reconnect and I will see the first stream is always retrying and its payload is not what we expected. The setup payload is not complete and it is just a part of WorkerUpdateDTO's json value.
![image](https://user-images.githubusercontent.com/4374015/109494881-72532980-7ac9-11eb-9335-ffb88adefa27.png)

I think it is a concurrency issue. Other thread's payload data will replace the correct setup payload during reconnecting. Is it a bug of spring rsocket?

**Comment by KaimingWan** [comment]
@wilkinsona I think this issue have some relationship with spring-rsocket projects in my view. I have configured the setup payload and what setup data to send when connection is created. Why after connection is recreated the client didn't send setup payload as I configured in my code. Normally, the setup payload ( ConnAuthDTO's json value) should be sent. Do I miss something important?

**Comment by OlegDokuka** [comment]
@wilkinsona I belive you wanted to mention me. 

Yeah, I guess I can move it to rsocket-java issue tracker to do the following investigations

**Comment by wilkinsona** [comment]
Oops, sorry. I did indeed. In the meantime, @bclozel's transferred this to Framework.

**Comment by OlegDokuka** [comment]
actually, we already have it in our issue tracker -> https://github.com/rsocket/rsocket-java/issues/970

**Comment by bclozel** [comment]
Thanks @OlegDokuka , we're going to close this one for now - we can reopen it if there's something to be done in Spring Framework.
