### ISSUE TITLE
How to get request header in webflux aspect?

### ISSUE THREAD

**Issue by Zengzehao** [spring-projects/spring-framework#26637]
**Affects:** \<Spring Framework 5.3.1>

**stackoverflow**
https://stackoverflow.com/questions/66468364/how-to-get-request-header-in-weblux-aspect

**Comment by bclozel** [comment]
Thanks for getting in touch, but there's no need to ping the team here for StackOverflow questions. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
