### ISSUE TITLE
Support global @MessageExceptionHandler via @ControllerAdvice in RSocket

### ISSUE THREAD

**Issue by kitkars** [spring-projects/spring-framework#26636]
This is specific to rSocket.

Add support for global **@MessageExceptionHandler** using **@ControllerAdvice**.
Currently **@MessageExceptionHandler** needs to be part of same controller to handle issues.

**Comment by soheilrahsaz** [comment]
Based on this issue, it is impossible to register `@MessageExceptionHandler`s with `@ControllerAdvice`.
Therefore, it should be removed from this documentation:
https://docs.spring.io/spring-framework/reference/web/websocket/stomp/handle-annotations.html#websocket-stomp-exception-handler
which states:
`Typically, @MessageExceptionHandler methods apply within the @Controller class (or class hierarchy) in which they are declared. If you want such methods to apply more globally (across controllers), you can declare them in a class marked with @ControllerAdvice. This is comparable to the [similar support](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-advice.html) available in Spring MVC.`
