### ISSUE TITLE
Fix bug in BeanUtils.copyProperties()

### ISSUE THREAD

**Issue by kafka009** [spring-projects/spring-framework#26646]
line 788

```java
if (!Modifier.isPublic(readMethod.getDeclaringClass().getModifiers())) {
	readMethod.setAccessible(true);
}
Object value = readMethod.invoke(source);
if (!Modifier.isPublic(writeMethod.getDeclaringClass().getModifiers())) {
	writeMethod.setAccessible(true);
}
```

may be

```java
if (!Modifier.isPublic(readMethod.getModifiers())) {
	readMethod.setAccessible(true);
}
Object value = readMethod.invoke(source);
if (!Modifier.isPublic(writeMethod.getModifiers())) {
	writeMethod.setAccessible(true);
}
```

**Comment by sbrannen** [comment]
Hi @kafka009,

If you believe you have fixed a bug, please provide a test case that fails before the fix and passes after the fix.

Thanks

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
