### ISSUE TITLE
Jaxb2XmlEncoder Support for Custom XML Media Types

### ISSUE THREAD

**Issue by jiantosca** [spring-projects/spring-framework#26655]
I'm trying to use WebClient with custom media types and found that the Jaxb2XmlEncoder only supports application/xml and text/xml media. Is it possible to have it support "*+xml", and/or have a way to customize  the types it supports? 

Jaxb2XmlDecoder supports "*+xml" and also exposes a constructor where we can provide our own media types, but for some reason the Encoder doesn't. 

Thanks for having a look.

**Comment by rstoyanchev** [comment]
I think it is just missing. By comparison, `AbstractXmlHttpMessageConverter` has `application/*+xml`.
