### ISSUE TITLE
Problems in applyprehandle processing

### ISSUE THREAD

**Issue by thankgoodness** [spring-projects/spring-framework#26667]
![bbs_1615476229893](https://user-images.githubusercontent.com/7982205/110884793-9eb84280-8320-11eb-8950-1c2ef1f22d3b.png)

![bbs_1615476501636](https://user-images.githubusercontent.com/7982205/110884814-a7a91400-8320-11eb-9f52-218b9181483d.png)

![bbs_1615476580222](https://user-images.githubusercontent.com/7982205/110884836-ae378b80-8320-11eb-96e1-0a2d7c6bef19.png)

As long as the interceptor throws an exception by executing prehandle, it will not perform the aftercompletion operation

If the after completion operation is not executed, there is no reasonable time to process the cleaning code (such as threadload and cache)

**Comment by rstoyanchev** [comment]
This is expected behavior for `afterCompletion`:
```
	 * <p>Note: Will only be called if this interceptor's {@code preHandle}
	 * method has successfully completed and returned {@code true}!
	 * <p>As with the {@code postHandle} method, the method will be invoked on each
	 * interceptor in the chain in reverse order, so the first interceptor will be
	 * the last to be invoked.
```
