### ISSUE TITLE
Unable to remove Transfer Encoding : chunked using WebClient

### ISSUE THREAD

**Issue by vaibsgharge** [spring-projects/spring-framework#26668]
Even after setting content length using the API webclient.contentLength() chunk encoding is not getting disabled.

**Comment by rstoyanchev** [comment]
Can you provide an example or at least snippet?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
