### ISSUE TITLE
Centralize copyright management with one cron job

### ISSUE THREAD

**Issue by delvh** [spring-projects/spring-framework#26677]
As far as I have seen,
basically any PR opened always uses the following line of code on changed files:
```java
 * Copyright 20XY-2021 the original author or authors.
```
I think it is unnecessary and error prone to do that manually for each file on its own.
There are for example files in the projects, where the copyright only ranges from `2014-2017`, meaning they were not updated at all in those 4 years since, which seems unintended when other files claim copyright until `2021`.

All that work should be easily automatable by simply defining **one** cron job that is run annually,
i.e. on Jan 01 of each year (`1 1 1 1 *` in cron terminology), using sed on all project files (of course, that requires a UNIX inspired OS like a Linux distro).
The cron job could even, if configured correctly, directly commit the changes and push them on GitHub.

**Comment by michael-o** [comment]
Why? Copyright notices denote the year of the first edition and years of update. If you don't change a file, no need to update the year also.

**Comment by delvh** [comment]
As there is no progress foreseeable regarding this issue, I'm closing it here.
