### ISSUE TITLE
Body recreation via getBodyFromServletRequestParameters for x-www-form-urlencoded POST is incorrect

### ISSUE THREAD

**Issue by andredasilvapinto** [spring-projects/spring-framework#26681]
When injecting the `@RequestBody` for `x-www-form-urlencoded` POST requests, Spring tries to recreate the original body payload via `javax.servlet.ServletRequest.getParameterMap()` in `org.springframework.http.server.ServletServerHttpRequest#getBodyFromServletRequestParameters`.

This operation is imperfect because there the URL encode operation does not entirely revert the previous decoding. An example is the `%2A` <-> `*` enconding/decoding. `%2A` is decoded into `*` but `getBodyFromServletRequestParameters` fails to transform it back into `%2A`, thus failing to produce the exact original payload. This is critical for for example, validating payload signatures, which require the exact same content that was used by the client that made the request.

Version: Spring Boot 5.2.3

**Comment by rstoyanchev** [comment]
I can't find anything in [the spec](https://url.spec.whatwg.org/#string-percent-encode-after-encoding) about encoding `"*"`. I do understand the point that if a client chose to encode it, then the payload won't be identical as what was received. For full control, you can inject `InputStream` into the controller method and consume it direclty.
