### ISSUE TITLE
WebClient - configuring reactor-netty's `disableRetry` setting

### ISSUE THREAD

**Issue by msmsimondean** [spring-projects/spring-framework#26693]
**Affects:** 5.3.4 and earlier versions

I'm using WebClient.  I've found that it automatically retries once any requests that experiencea connection reset.  This seams to be caused by a feature in `reactor-netty`: 

https://github.com/reactor/reactor-netty/issues/587#issuecomment-655686821

Is there a way to configure reactor-netty's `disableRetry` setting when using WebClient?  Thanks

**Comment by poutsma** [comment]
This section of the reference documentation explains how to configure a Reactor `HttpClient`: https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-reactor

**Comment by msmsimondean** [comment]
That's great.  Thanks @poutsma
