### ISSUE TITLE
Version agnostic URLs for Webjars fail on JBoss EAP7.3 with multiple deployments

### ISSUE THREAD

**Issue by jensdt** [spring-projects/spring-framework#26691]
**Affects:** 5.3.5

---

Please see https://github.com/jensdt/spring-webjar-resolve-issue for a project that easily reproduces this issue on an out-of-the-box JBoss EAP 7.3 installation.

If you deploy 2 completely separate WAR files on JBoss EAP 7.3 containing WebJar libraries for the same library but with a different version, only the WAR that is deployed first will be able to use version agnostic URLS. 

For example:

my-deployable contains swagger-ui-0.44.0.jar
my-second-deployable contains swagger-ui-0.45.0.jar

There are no cross-dependencies whatsoever between these applications.

Version-agnotic WebJar URLs only work for the application that is deployed first.  Note that webjars-locator-jboss-vfs has no impact on this (and it seems no longer required to run on newer JBoss versions, like 7.3).

It seems triggered by the Classpath scanning of the WebJar-locator library, where it picks up JAR files that are not on the classpath of the WAR itself, but also JARs that belong to other applications, but I'm unsure whether this is a bug in that library or in the way that Spring uses it, that's why I'm reporting this issue here.

**Comment by bclozel** [comment]
Sorry for the late reply, the classpath scanning does belong to the webjars project and this issue should be opened against it.
