### ISSUE TITLE
Spring Cache support for Async Caffeine

### ISSUE THREAD

**Issue by namila007** [spring-projects/spring-framework#26713]
Hi,

I'm currently using Caffeine with Spring Caffeine cache support implementation. I want to know is there any support for Async LoadingCache support on the spring cache? or if I want async caching do I want to move out with `AsyncLoadingCache` without spring caffeine cache support;? 
PS: I'm using spring-webflux

**Comment by snicoll** [comment]
Support for `LoadingCache` has been discussed several times in the past, see for instance #25173. Reactive types are not yet supported, see #17920. If you are using the annotation models, loading cache does not make much sense. If you are using the `Cache` API directly, the contract is blocking at the moment so not a great fit for a reactive app.

Going forward, please ask questions on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.

**Comment by ben-manes** [comment]
@snicoll fyi in case you weren't familiar or forgot, given everything you work on, Caffeine also offers an `AsyncCache` interface for reactive applications. This stores and returns `CompletableFuture` values, which Reactor can convert between easily enough. In these cases when users should use the native apis directly, that interface is the best fit.

**Comment by snicoll** [comment]
@ben-manes thanks for following up. I am aware, but the question above was about the Spring Cache abstraction, and so was my answer.
