### ISSUE TITLE
Both @Autowried and @Resource cannot be injected

### ISSUE THREAD

**Issue by puyongqqq** [spring-projects/spring-framework#26723]
**Affects:** \<Spring Framework version>

---

Hello. My project A split out project B, project B introduced part of project A module, and then added B to A to start, and then the following error message appeared.

`org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'kaasPropertyAttrDaoService' is expected to be of type 'com.koalii.kaas.system.service.KaasPropertyAttrDaoService' but was actually of type 'com.koalii.kaas.system.service.KaasPropertyAttrDaoService'`

But in my Application class into the 'KaasPropertyAttrDaoService, can print the object.
` ------ 
 ------ com.koalii.kaas.system.service.KaasPropertyAttrDaoService@6c61bea0`

**Comment by puyongqqq** [comment]
spring framework verion is 5.1.5

**Comment by bclozel** [comment]
I'm afraid the issue description is not enough for us to help you.
Could you provide a minimal, sample application showing the problem? Ideally, something we can git clone or download and run.

**Comment by puyongqqq** [comment]
Thank you for your help! I solved this problem temporarily by shifting the path of the class.
