### ISSUE TITLE
Reintroduce single-page HTML version of the reference manual

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-framework#26722]
We get requests (and just got another one) for a single-page HTML version of the Spring Framework documentation. People want it so that they can search the whole thing with Ctrl-F. Since we have no other functionality that offers searching across the multiple document files, that seems like a reasonable approach.

My other concern is that we set the expectation of having a single-page HTML file in other projects that have multi-page output (both Batch and Boot having both multi- and single-page HTML). Readers may reasonably ask why we have that arrangement in those places and not in Framwork.

**Comment by vpavic** [comment]
> People want it so that they can search the whole thing with Ctrl-F.

I find myself quite often in this situation when looking something up in the Framework docs. I'm also quite sure that single-page variant did exist in the past (pre-5.x?).

The consistency between the different Spring projects is also something that would be nice to achieve.

**Comment by vpavic** [comment]
Any updates on this? The Ctrl-F approach to searching the docs is really a common one and without a singe-page variant that's a bit painful. Thanks.

**Comment by sbrannen** [comment]
@vpavic, as far as I understand, several Spring portfolio projects are considering migrating to an Antora-based reference manual as has already been done for [Spring Security](https://docs.spring.io/spring-security/reference/index.html). Depending on the outcome of that effort, Spring Framework may also migrate to Antora-based docs. In light of that, I don't believe there are any plans to reintroduce a single-page HTML version of the reference manual.

**Comment by vpavic** [comment]
Hey @sbrannen, I'm aware of the initiative to move the portfolio to Antora-based docs but I didn't think of that as something that would happen anytime soon. I don't think there's a ticket tracking that effort in the Spring Framework.

In the mid-term, I thought it would be a reasonable compromise to reintroduce the single-page version.

**Comment by vpavic** [comment]
Is there an issue tracking the move to Antora based docs? [Searching the project for _antora_](https://github.com/spring-projects/spring-framework/search?q=antora&type=issues) returns only one hit and that's this issue.

**Comment by rwinch** [comment]
@vpavic You are right there wasn't an issue tracking it. I've created one here gh-29705
