### ISSUE TITLE
Docs missing Dynamic Language Support Refreshable: Refresh does not work with <lang:inline-script> beans

### ISSUE THREAD

**Issue by StephenOTT** [spring-projects/spring-framework#26728]
https://docs.spring.io/spring-framework/docs/5.0.20.RELEASE/spring-framework-reference/languages.html#dynamic-language-beans-concepts

Docs should indicate that `refresh-check-delay` does not work with <lang:inline-script> beans

Happy to make the update, but cannot find the source for the docs page.

**Comment by rstoyanchev** [comment]
This is the matching file https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/languages/dynamic-languages.adoc#common-concepts.

**Comment by rstoyanchev** [comment]
Closing for now. @StephenOTT feel free to suggest a change through a PR.
