### ISSUE TITLE
ScriptItemProcessor python implementation

### ISSUE THREAD

**Issue by EdgardHernandezp** [spring-projects/spring-framework#26738]
I wanted to use a web scraping python script in my batch program but this is not feasible in Spring Batch. I want to request for this feature in a future Spring version. Python grows in popularity and using a python script with ScriptItemProcessor I think is becoming a necessity.

**Comment by snicoll** [comment]
@EdgardHernandezp this issue tracker is for the Spring Framework. Spring Batch has [a dedicated issue tracker](https://github.com/spring-projects/spring-batch).
