### ISSUE TITLE
Typo in RequestBodyAdviceAdapter Javadoc

### ISSUE THREAD

**Issue by laiyubin** [spring-projects/spring-framework#26740]
Hi Guys

The javadoc said RequestBodyAdviceAdapter  is A convenient starting point for implementing **ResponseBodyAdvice**,
I think the correct one should be **RequestBodyAdvice**
```
/**
 * A convenient starting point for implementing
 * {@link org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice
 * ResponseBodyAdvice} with default method implementations.
 *
 * <p>Sub-classes are required to implement {@link #supports} to return true
 * depending on when the advice applies.
 *
 * @author Rossen Stoyanchev
 * @since 4.2
 */
```

**Comment by rstoyanchev** [comment]
Indeed it should refer to `RequestBodyAdvice`. We can actually add default methods on the interface and deprecate this class.

**Comment by rstoyanchev** [comment]
Never mind the part about deprecation. The `supports` method is still required.
