### ISSUE TITLE
Binding error with AspectJ @Around advice

### ISSUE THREAD

**Issue by wisty** [spring-projects/spring-framework#26743]
```java
@Aspect
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class TestTwoAop {

	@Around("@annotation(aopAnnoTwo)")
	public Object aroundAdvice(ProceedingJoinPoint proceedingJoinPoint,
			AopAnnoTwo aopAnnoTwo) throws Throwable {
		return proceedingJoinPoint.proceed();
	}
}
```

```
Error "java.lang.IllegalStateException: Required to bind 2 arguments, but only bound 1
```

the userAttributes of  Class ReflectiveMethodInvocation  null value ,cause JoinPointMatch is null 

then I set order sort  another value.Do not have any `RuntimeException`.

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by wisty** [comment]
Latest  spring version 2.4.4 have the same issue

**Comment by wisty** [comment]
Bean load   Sequence lead to the ExposeInvocationInterceptor is upfront in the interceptor chain

**Comment by rstoyanchev** [comment]
Superseded by #26752.
