### ISSUE TITLE
Spring Data Hadoop HBase - TableCallback incorrectly referencing HTableInterface instead of HTable 

### ISSUE THREAD

**Issue by shobson202** [spring-projects/spring-framework#26757]
spring-data-hadoop-hbase 2.5.0 has an interface TableCallback with doInTable method.  The method takes one parameter table of type org.apache.hadoop.hbase.client.HTableInterface.

The issue is that org.apache.hadoop.hbase.client.HTableInterface is not longer present in org.apache.hbase:hbase-client.  
org.apache.hadoop.hbase.client.HTableInterface was removed as from org.apache.hbase:hbase-client starting at version 2.0.0.
Verified org.apache.hbase:hbase-client versions 2.3.3 and 2.4.2 and they just have HTable.

The reference documentation for Spring for Apache Hadoop shows code with HTable instead of HTableInterface. 
See 7.1 Data Access Object(DAO) Support section for code example with HTable

The code I'm trying to execute is using the hbasetemplate.execute with the tablename and TableCallback.

**Comment by snicoll** [comment]
@shobson202 this is the issue tracker for the Spring Framework, not Spring Hadoop. Spring Hadoop has reached its end of life, you can read more about it on the relevant project: https://github.com/spring-projects/spring-hadoop
