### ISSUE TITLE
Event source not working with CORS

### ISSUE THREAD

**Issue by Kevin-Buntrock** [spring-projects/spring-framework#26754]
Do you think the limitation of SockJS EventSource on "same origin" is still relevant?

https://github.com/spring-projects/spring-framework/blob/58e40d1aa2c23f6d9c41d4289f5b5debc10868f6/spring-websocket/src/main/java/org/springframework/web/socket/sockjs/transport/TransportType.java#L45

I have the feeling this is reflecting the old lack of cors in event source specification, but the spec has been improved since : 
https://www.w3.org/TR/eventsource/

But once again, this is my very first time "playing" with SSE. Another point of view can help before working on any PR.

**Comment by rstoyanchev** [comment]
Probably a valid point but it goes back to the protocol, see http://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html#section-15. Looking at the [browser matrix](https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https) my best guess is that this isn't really important enough to change.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
