### ISSUE TITLE
Spring 5.3.x is it a GA version? 

### ISSUE THREAD

**Issue by baswarajk1** [spring-projects/spring-framework#26765]
As per Maven central repository spring 5.3.x jar are not released  

As spring framework tells link: https://spring.io/blog/2020/10/27/spring-framework-5-3-goes-ga   

spring 5.3.x jars are stable but we try to upgrade it in out project it throws BeanObjectCreation, illigaleObjectException.

Project technology
java11.x
jboss7.3
current spring 4.6.

Please guide us which jars are  stable to use in our project

**Comment by stevenschlansker** [comment]
We run Spring 5.3.5 from Maven Central with no problems, and see e.g. `spring-core` here: https://search.maven.org/artifact/org.springframework/spring-core/5.3.5/jar

**Comment by bclozel** [comment]
Yes, Spring Framework 5.3.x is the current stable generation. You can find more [information about the supported versions](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions) on our wiki.

If you're running into specific issues while upgrading, the ["Upgrading to" sections](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-53) are there to help. If that doesn't help, summarizing the issue in a StackOverflow question is the next step.

Thanks!
