### ISSUE TITLE
Fix Javadoc in AcceptHeaderLocaleResolver

### ISSUE THREAD

**Issue by m1stake** [spring-projects/spring-framework#26793]
**Affects:** spring-webmvc 5.1.6.RELEASE

---

org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver.setDefaultLocale, line 74

```java
// ...
// By default this is not set in which case when there is "Accept-Language" header 
// ...
public void setDefaultLocale(@Nullable Locale defaultLocale) { ... }
```
I think it means "when there is ***no*** 'Accept-Language' header".

**Comment by sbrannen** [comment]
This has been fixed in `master`.

Thanks
