### ISSUE TITLE
Support parse Illegal character in query at `ReactorServerHttpRequest`

### ISSUE THREAD

**Issue by mm23504570** [spring-projects/spring-framework#26808]
`ReactorHttpHandlerAdapter`
![image](https://user-images.githubusercontent.com/4693441/114832316-f30f8000-9e00-11eb-89d8-233a489fa362.png)

I need to pass the original Query to the Upstream use `SpringCloudGateway`. 
The URI is `http://localhost:8080/test-like-this?a={{bbb}}`. 

I can't encode Query for some reason such as not supported by third-party companies.

** Webflux can't pause this query too. ** 

``` java
@GetMapping("/test-like-this")
public String string(HttpServerRequest httpServerRequest){
  return httpServerRequest.params().toString();
}
```

Should we support it? Or other workarounds?

Tomcat's solution.
https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters/44005213#44005213

**Comment by mm23504570** [comment]
Same problems.

https://github.com/spring-cloud/spring-cloud-gateway/issues/944
https://github.com/spring-cloud/spring-cloud-gateway/issues/2164#issuecomment-810060248

**Comment by rstoyanchev** [comment]
We expose the URL as `java.net.URI` which can't be created with invalid syntax, so no there is no straight-forward way to do this I'm afraid.

**Comment by czjxy881** [comment]
same problem, please support
