### ISSUE TITLE
org.springframework.jdbc.core.metadata.GenericCallMetaDataProvider#processProcedureColumns does not find functions in Postgres 11+

### ISSUE THREAD

**Issue by riba2101** [spring-projects/spring-framework#26818]
What: 
without using SimpleJdbcCall.withoutProcedureColumnMetaDataAccess Postgres in version 11  uses an additional check for functions here: PgDatabaseMetaData.java:1041

This causes a `org.springframework.dao.InvalidDataAccessApiUsageException: Unable to determine the correct call signature - no procedure/function/signature for 'function_name'`

What should change: 
org.springframework.jdbc.core.metadata.GenericCallMetaDataProvider#processProcedureColumns should check if its a function or not and use the correct method

**Comment by jhoeller** [comment]
Which version of Spring are you encountering this with? We have introduced dedicated function metadata introspection in 5.2.8, driven by the behavior of recent Postgres driver versions: #25399

**Comment by riba2101** [comment]
Hi,

im fairly sure its 2.3.0 spring boot, but the underlying jdbc is currently unknown to me. let me check and ill get back at ya tomorrow

**Comment by riba2101** [comment]
So the current version of spring is 5.2.6, so ive just updated spring and the issue is gone. 
Sorry for this one, but while looking into the issue, i found a lot of unanswered questions regarding this topic.
This would be a great source of info for future references.

BR
