### ISSUE TITLE
Reduce log level in ExecutorConfigurationSupport.initialize

### ISSUE THREAD

**Issue by rupert-madden-abbott** [spring-projects/spring-framework#26810]
Please could the level of the logging within ExecutorConfigurationSupport.initialize be reduced to DEBUG?

Currently, this line is always logged at startup but I feel it doesn't convey very useful information and adds noise to the logs by default.

It is also hard to suppress when building on top of this in libraries. My end users often don't know (or care) what this means but I don't want to enforce logging configuration, or a logging implementation on them to hide it.

Happy to raise a PR if this change is agreed!

**Comment by jhoeller** [comment]
Indeed, this isn't particularly useful at info level, same for the shutdown log statement in the same class. I'll take the opportunity to revisit some related logging spots in other components, so no need for a PR from that perspective. (Thanks for volunteering, in any case!)
