### ISSUE TITLE
org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler does not handle vendor-specific application/x-ndjson media types

### ISSUE THREAD

**Issue by nlescure-pictet** [spring-projects/spring-framework#26817]
Hi,

At one point, the handler iterates over ReactiveTypeHandler#JSON_STREAMING_MEDIA_TYPES which contains two values: MediaType.APPLICATION_NDJSON and MediaType.APPLICATION_STREAM_JSON.

If a controller uses a custom vendor-specific "produces" streaming type such as application/vnd.myname.v1+x-ndjson (for API versioning for example), it won't "match" within the loop and the handler will not use a JsonEmitterSubscriber as expected.

Shouldn't ReactiveTypeHandler#JSON_STREAMING_MEDIA_TYPES contain the generic media type: application/*+x-ndjson so that it "includes" custom vendor-specific streaming type.

Thank you.

**Comment by nlescure-pictet** [comment]
Hi there,
Any update on that one ?

**Comment by simonbasle** [comment]
I have discussed that one with the team and it appear a bit overcomplicated to add a customization path for that particular aspect. we agree that your suggestion of adding a wildcard subtype _for that particular component_ is an acceptable middle ground.

**Comment by nlescure-pictet** [comment]
Great thanks !
