### ISSUE TITLE
hen allowCredentials is true, allowedOrigins cannot contain the special value "*"

### ISSUE THREAD

**Issue by zhangran2616** [spring-projects/spring-framework#26835]
After upgrading to use Spring Boot 2.4.5 from 2.3.x, it does not seem to be possible to use allowedOrigins = "*" in the StompEndpointRegistry. When connecting it results in the following Error:

![image](https://user-images.githubusercontent.com/6472032/115486079-7c530680-a288-11eb-8f1d-89e753ffc41c.png)

my config:
![image](https://user-images.githubusercontent.com/6472032/115486134-97257b00-a288-11eb-8224-ed6a60c6d6c2.png)

**Comment by zhangran2616** [comment]
I solved the。
thank you

**Comment by YOUSSEF-EL-MESSBAHI** [comment]
what is the solution for this error ?
