### ISSUE TITLE
Can't execute normally？

### ISSUE THREAD

**Issue by zoujinxing** [spring-projects/spring-framework#26859]
https://github.com/spring-projects/spring-framework/blob/01e50fb60ad0d82f96fe4df6054ed6029e2f6a12/spring-context/src/main/java/org/springframework/scheduling/annotation/ScheduledAnnotationBeanPostProcessor.java#L561

**Comment by bclozel** [comment]
I'm closing this issue as this seems to be a question - please use this issue tracker for bugs and enhancement requests.

Thanks
