### ISSUE TITLE
Is it possible to merge @RestController (@Controller) and @RequestMapping in one annotation?

### ISSUE THREAD

**Issue by akuma8** [spring-projects/spring-framework#26879]
This is not an issue but an improvement. 
When I look at my controllers all of them start with these 2 annotations: `@RestController` and `@RequestMapping`.
I wonder if it's possible to merge those annotations in one? Or adding all the attributes from `@RequestMapping` to `@RestController`. We could have something like: `@RestController(name="controllerName", requestMapping="/mymapping", ...)`
I know there are more critical issues than this request, it's just an improvement idea. 
Thanks

**Comment by snicoll** [comment]
This was raised yesterday, see #26872
