### ISSUE TITLE
Add PreFlightWebFilter

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#26885]
Similar to `CorsWebFilter` there should be a `PreFlightWebFilter` in Spring Framework that leverages the `PreFlightRequestHandler` API.

Related gh-26257 spring-projects/spring-boot#24541

**Comment by rstoyanchev** [comment]
We could a default method to `PreFlightRequestHandler`?

```java
default WebFilter asWebFilter() {
	return (exchange, chain) -> 
			CorsUtils.isPreFlightRequest(exchange.getRequest()) ? 
					handlePreFlight(exchange) : chain.filter(exchange);
}
```

**Comment by orubel** [comment]
Is there a way for us to DISABLE the inclusion of 'PreFlightRequestHandler'??

I already have CORS functionality for SimpleURLHandlerMapping and this creates an unnecessary requirement

**Comment by sdeleuze** [comment]
@orubel I would need to see a reproducer to be sure, but I think it should be possible by overriding the related method. If you are blocked, please create a dedicated issue with a reproducer and a description of the problematic behavior you would like to see refined.
