### ISSUE TITLE
RSocketRequester disposal of underlying RSocketClient

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-framework#26886]
**Affects:** 5.3.6

When using `RSocketRequester.builder().transport()` a new underlying RSocketClient is created (which is hidden from the user of this API). The RSocketClient must be disposed to free the underlying resources (or not?).

Imho the current API design totally hides that there are resources allocated and must be disposed - it is nowhere stated in the docs and also the RSocketRequester has not `dispose()` method or similar.

**Comment by rstoyanchev** [comment]
`RSocketRequest` wraps `RSocketClient` and delegate to it. You can access the underlying `RSocketClient` instance via `RSocketRequester#rsocketClient()`. In general this does not allocated resources by default. 

Once you start making connections, they are long lived, it's the nature of messaging communication, and it is necessary to call dispose on the `RSocketClient`. We can make `RSocketRequester` implement `Disposable` which would delegate to the underlying instance.
