### ISSUE TITLE
Error in Bean Definition Inheritance example in ref docs

### ISSUE THREAD

**Issue by lostblackknight** [spring-projects/spring-framework#26916]
In the [Bean Definition Inheritance](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-child-bean-definitions) example in the reference docs, when I used instance code, an error occurred.

```
Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'age' of bean class [org.springframework.beans.DerivedTestBean]: Bean property 'age' is not writable or has an invalid setter method. Did you mean 'name'?
```

The age's setter method is consistent with the configuration.

When I comment out the age attribute, it runs successfully.

**Comment by sbrannen** [comment]
For the example to work, `DerivedTestBean` either needs to extend `TestBean`, or they need to both have compatible `name` and `age` JavaBean properties.

I assume your implementations of `DerivedTestBean` and `TestBean` do not adhere to that.

For working example types, see the corresponding classes in [this package](https://github.com/spring-projects/spring-framework/tree/main/spring-beans/src/testFixtures/java/org/springframework/beans/testfixture/beans) in our test suite.

In light of that, I am closing this issue.

**Comment by izeye** [comment]
This seems to have been meant to be closed.
