### ISSUE TITLE
Improve support for port numbers in allowedOriginPattern of CorsConfiguration 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#26926]
Currently it's not possible to support any port or multiple, specific ports with a single pattern. The workaround is to create two origin patterns such as `"https://*.example.com"` and `"https://*.example.com:*"`.

One idea is to enhance the pattern syntax with a comma separated list of ports or a wildcard:
```
https://*.example.com:[8080]
https://*.example.com:[8080,9000]
https://*.example.com:[*]
```

This was originally reported in #26892.

**Comment by korektur** [comment]
@rstoyanchev can I do the change myself and open a merge request?

**Comment by izeye** [comment]
This seems to have been meant to be closed by @rstoyanchev as it has been superseded by #26927.
