### ISSUE TITLE
UriComponentsBuilder/UriComponents doesn't support encoding of semicolon ';' for query parameters

### ISSUE THREAD

**Issue by mazurkin** [spring-projects/spring-framework#26966]
**Affects:** Spring Web 4.3.9 / 5.2.8

`UriComponentsBuilder/UriComponents` doesn't support encoding of ";". 

For example it might be a value like:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
```

but ";" is not encoded:

```java
UriComponentsBuilder builder = UriComponentsBuilder.fromUriString("http://domain.net/q?param0=aaa");

// param1 is single-value parameter with a complex value
builder.queryParam("param1", "bb;%& b");

// param2 is multi-value parameter with a complex value
builder.queryParam("param2", "cc;%& c");
builder.queryParam("param2", "dd;%& d");

UriComponents components = builder.build(false).encode();

System.out.println(components.getQuery());
// param0=aaa&param1=bb;%25%26%20b&param2=cc;%25%26%20c&param2=dd;%25%26%20d
```

`org.springframework.web.util.UriUtils#encodeQueryParam` works in the same way.

```java
System.out.println(UriUtils.encodeQueryParam("bb;%& b", StandardCharsets.UTF_8));
// bb;%25%26%20b
```

Unfortunately W3 recommends to use ";" as "&" which makes this URL unusable with the big number of web servers.

https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2

> We recommend that HTTP server implementors, and in particular, CGI implementors support the use of ";" in place of "&" to save authors the trouble of escaping "&" characters in this manner.

Python can't process such a query string

```
$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import parse_qs
>>> parse_qs("param0=aaa&param1=bb;%25%26%20b&param2=cc;%25%26%20c&param2=dd;%25%26%20d")
{'param0': ['aaa'], 'param1': ['bb'], 'param2': ['cc', 'dd']}
```

**Comment by mazurkin** [comment]
Also `com/pulsepoint/datascience/avails/web/api/facet/FacetGroomerImplTest.java:79` does the same.

May be it worth to override `encode` with the extended version like `encodeStrict`. Please also check what `GNU/curl` does with encoding when `--data-urlencode` is specified.

**Comment by Birthright50** [comment]
The problem is not only with this character, but also with `+` and `:`. For example:
```
        String baseUrl = "http://item-service/api/external/items";
        final URI uri = UriComponentsBuilder.fromHttpUrl(baseUrl)
                .queryParam("from", OffsetDateTime.now().toString())
                .encode().build().toUri();
        System.out.println(uri);
```
output:
`http://item-service/api/external/items?from=2021-08-30T21:20:38.669121955+03:00`
But expected:
`http://item-service/api/external/items?from=2021-08-30T21%3A20%3A38.669121955%2B03%3A00`

And there is no solution to this issue, the [documentation](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#web-uri-encoding) does not say anything.

**Comment by rstoyanchev** [comment]
@Birthright50, for the URI template (the literal parts) we assume that characters there are used according to their meaning. For example a ";" in a path segment to separate path variables. We only apply strict encoding to dynamic parts (URI variables).

I agree the above code sample is not ideal. There is a method on `UriUtils` that helps to encode a map  variables, so you could do this:

```java
Map<String, String> queryParams = UriUtils.encodeUriVariables(Map.of("from", OffsetDateTime.now().toString()));

UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromHttpUrl("http://item-service/api/external/items");
queryParams.forEach(uriComponentsBuilder::queryParam);
URI uri = uriComponentsBuilder.build(true).toUri();

System.out.println(uri);
```

**Comment by mazurkin** [comment]
I would say this a total mess, JavaDoc to "org.springframework.web.util.UriComponentsBuilder#encode()" explicitly says:

> In comparison to {@link UriComponents#encode()}, this method has the
> same effect on the URI template, i.e. each URI component is encoded by
> replacing non-ASCII and illegal (within the URI component type) characters
> with escaped octets. However URI variables are encoded more strictly, 
> by also **escaping characters with reserved meaning**.

**Comment by mazurkin** [comment]
Ok, long story short: never ever use `builder.queryParam`, instead use `builder.uriVariables()`

But I see another bummer:
```
UriComponentsBuilder builder = UriComponentsBuilder
    .fromUriString("http://domain.net/q?param0=aaa&param4={token}");

builder.uriVariables(Map.of("token", "ee;%& e"));

// leads to java.lang.IllegalArgumentException: Invalid character '{' for QUERY_PARAM in "{token}"
UriComponents components = builder
    .encode()     // I encoded the builder, didn't I?
    .build(true); // So here I set `encoded=true`
    
// only with `encoded=false` it finally produces the expected string
//      http://domain.net/q?param0=aaa&param4=ee%3B%25%26%20e
System.out.println(components.toUriString());
    
```

**Comment by rstoyanchev** [comment]
The `encode` on `UriComponentsBuilder` (as the Javadoc says) encodes the template only, with URI variables to be encoded when expanded. This separation allows respecting reserved characters in the URI template, while using a stricter encoding for URI variable values.

**Comment by techouse** [comment]
You could use [`qs-kotlin`](https://github.com/techouse/qs-kotlin) for Proper RFC‑3986 Encoding.

[`qs-kotlin`](https://github.com/techouse/qs-kotlin) is my Kotlin/JVM port of the widely used Node.js [`qs`](https://www.npmjs.com/package/qs) library. It provides robust, standards‑compliant query string **encoding and decoding**, including correct handling of reserved characters like `;` (encoded as `%3B`).

**Why `qs-kotlin`?**

- **Faithful `qs` semantics**: Nested maps/lists, bracket & dot notation, multiple array formats.
- **RFC‑compliant encoding**: Reserved chars (`;`, `%`, `&`, space, etc.) are percent‑encoded where appropriate.
- **Well‑tested**: Extensive unit tests and production use across ports (Dart, Python, .NET, Swift).
- **Drop‑in utility**: Use it just to build the query string; keep the rest of your Spring stack unchanged.

## Example: Encoding a Query with Semicolons

```kotlin
import io.github.techouse.qskotlin.QS
import io.github.techouse.qskotlin.enums.ListFormat
import io.github.techouse.qskotlin.models.EncodeOptions

val params = mapOf(
    "param0" to "aaa",
    "param1" to "bb;%& b",
    "param2" to listOf("cc;%& c", "dd;%& d")
)

// Choose list format to match your server (REPEAT, BRACKETS, INDICES, COMMA)
val qs = QS.encode(params, EncodeOptions(listFormat = ListFormat.REPEAT))

println(qs)
// param0=aaa&param1=bb%3B%25%26%20b&param2=cc%3B%25%26%20c&param2=dd%3B%25%26%20d
```

Note how every `;` in values is encoded as `%3B`. This prevents downstream parsers from misinterpreting the semicolon as a separator.

## How to use with Spring

- **Build the URL yourself** (e.g., for `RestTemplate`/`WebClient`):  
  ```kotlin
  val base = "https://example.com/search"
  val url = "$base?$qs" // qs from QS.encode(...)
  // pass `url` directly to your HTTP client
  ```

- **If you must use `UriComponentsBuilder`**: create the encoded query string with `qs-kotlin` and set it as a raw query to avoid re‑encoding:
  ```kotlin
  val uri = UriComponentsBuilder
      .fromHttpUrl(base)
      .replaceQuery(qs) // qs is already encoded
      .build(true)      // true = components already encoded
      .toUri()
  ```

This approach acts as a safe, standards‑compliant workaround for semicolon handling, while also giving you a powerful encoder for nested/complex queries.

---

- Project: https://github.com/techouse/qs-kotlin  
- Artifact: `io.github.techouse:qs-kotlin` (Maven Central)
