### ISSUE TITLE
Issue #24395 broke "user" destinations

### ISSUE THREAD

**Issue by alienisty** [spring-projects/spring-framework#26983]
**Affects:** 5.3

User destinatinations are registered using the subscription-id and therefore they get ignored in SessionInfo in case the related "topic" destination has been registered before.
The optimisation performed in https://github.com/spring-projects/spring-framework/issues/24395 has removed such support by trying to optimise cache lookup, expecting that the subscription-id was unique for a destination, which is not. The same submission-id can be used for multiple destination, that is.

**Comment by nkavtur** [comment]
Having same problem. One ws connection establishes two subscriptions to my app.
Both of them having same sessionId and subscriptionId. DefaultSubscriptionRegistry registers only first one.

**Comment by alienisty** [comment]
Hi @nkavtur try reading https://github.com/spring-projects/spring-framework/pull/26986, specifically https://github.com/spring-projects/spring-framework/pull/26986#issuecomment-853035980 and following comments should help you solve your problem.

This issue should probably by closed.
