### ISSUE TITLE
Aspectj: @Async with @Transactional doesn't work

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#27000]
Both annotation on same method.
```
    @Async
    @Transactional
    public Future<?> asyncTask() {
    ....
```

First the transaction aspect is called, starting the transaction, then the async aspect, spawning a new thread.
The order should be inverse.

Sample repo: https://github.com/cdalexndr/spring-boot-issue-26699

**Spring Boot 2.4.4**

**Comment by cdalexndr** [comment]
[declare precedence ](https://www.eclipse.org/aspectj/doc/next/adk15notebook/annotations-decp.html#declare-precedence) should be used to order aspects.

**Comment by jhoeller** [comment]
Duplicate of #24309.
