### ISSUE TITLE
spring aop advise not applied for methods invoked from same class

### ISSUE THREAD

**Issue by 1zg12** [spring-projects/spring-framework#27029]
**Affects:** \<Spring Framework version>

2.0.5.RELEASE
---

## Issue

When a method is annotated for Spring AOP, if the method is invoked from the spring bean, the advise would be applied. 
```
class ABC{    
   @TimeIt
    public void processABC(String date) {

   }

    public void processABC() {
     String date = LocalDate.now(zoneId).toString();
      return processsABC(date)_;
   }
}
```

if processABC is directly invoked from the bean, the advise would be applied
```
abc.processABC("2021-06-07"); //the advise of TimeIt would be invoked.
```

However, if the method is invoked by another method in the same class, the advise is not applied.
```
abc.processABC(); //which subsequently call processABC(String date)
//however the advise of TimeIt is not invoked.
```

**Comment by snicoll** [comment]
That is to be expected considering that, in the second case, the call doesn't go through the proxy that is generated for the `@TimeIt` aspect.

Going forward, please ask questions on StackOverflow: as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. It should be noted that the use case you've described is [already covered](https://stackoverflow.com/questions/13564627/spring-aop-not-working-for-method-call-inside-another-method).
