### ISSUE TITLE
Default value of StandaloneMockMvcBuilder.useSuffixPatternMatch differs from the same property in RequestMappingHandlerMapping

### ISSUE THREAD

**Issue by perlan** [spring-projects/spring-framework#27030]
After upgrading to spring framework 5.3(5.3.7) the useSuffixPatternMatch default value in RequestMappingHandlerMapping was finally changed to false according to https://github.com/spring-projects/spring-framework/issues/23915#issuecomment-616566606 but the default value of useSuffixPatternMatch in StandaloneMockMvcBuilder is still set to true, forcing test cases to explicitly call the deprecated setUseSuffixPatternMatch method of StandaloneMockMvcBuilder to match the default behavior in RequestMappingHandlerMapping. I was expecting that StandaloneMockMvcBuilder should have the same behavior as RequestMappingHandlerMapping and also like to avoid calling deprecated methods in my code.

**Comment by jhoeller** [comment]
@rstoyanchev This might a simple oversight that we can fix for 5.3.8 still?
