### ISSUE TITLE
HttpComponentsClientHttpConnector should close underlying resources

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#27032]
As seen in https://github.com/spring-projects/spring-boot/issues/26214#issuecomment-856009156, the `HttpComponentsClientHttpConnector` can be instantiated with a custom client instance or create a default one. The connector implementation doesn't provide access to the underlying client nor implements the `Closeable`interface.

We should ensure that the connector can close the resources it's using. This should not be done through the `WebClient` interface since client resources can be shared amongst clients or even with the server.

In the case of the `HttpComponentsClientHttpConnector` in Spring Boot, it is created as a Spring bean and will be considered when components are shut down.

**Comment by JanHron** [comment]
@bclozel I realized I never thanked you for the quick fix of this. It actually solved our problem back then; if we ever meet on a conference or something, I'll treat you to a beer or another tasty beverage of your choice ;-)
