### ISSUE TITLE
Link to alternate format not rendering

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-framework#27088]
On the main docs page (https://docs.spring.io/spring-framework/docs/current-SNAPSHOT/reference/html/), the link to the other format is not rendering. Rather than a link to the PDF file, it shows `{doc-root}/spring-framework/docs/5.3.9-SNAPSHOT/reference/pdf/index.pdf[PDF]` Perhaps `doc-root` has not been set (the rest looks right). The same is true in the PDF file.

**Affects:** \<Spring Framework version>

---

**Comment by rstoyanchev** [comment]
Thanks, that should be fixed now. I've linked it to #27015 as a follow-up fix.
