### ISSUE TITLE
Copyright Notice in License is missing

### ISSUE THREAD

**Issue by divyank-vwits** [spring-projects/spring-framework#27091]
For companies that use this library, it is important to understand who is the copyright holder.
In the license file that is attached, the copyright holder is not clearly stated but it is still kept as the template value.

It would be great if you could add the name(s) of the copyright holder such that the legal situation gets clarified properly.

**Comment by sbrannen** [comment]
Hi @divyank-vwits,

Thank you for creating your first GitHub issue for the Spring Framework.

If you are referring to [LICENSE.txt](https://github.com/spring-projects/spring-framework/blob/main/LICENSE.txt), that is the standard Apache License 2.0 which we do not modify.

Please note, however, that every published artifact (JAR file) contains a copy of [notice.txt](https://github.com/spring-projects/spring-framework/blob/main/src/docs/dist/notice.txt) and [license.txt](https://github.com/spring-projects/spring-framework/blob/main/src/docs/dist/license.txt) which list the copyright holders.

In light of that, I am closing this issue.

**Comment by sbrannen** [comment]
> If you are referring to [LICENSE.txt](https://github.com/spring-projects/spring-framework/blob/main/LICENSE.txt), that is the standard Apache License 2.0 which we do not modify.

See also https://github.com/spring-projects/spring-boot/issues/27021#issuecomment-865890138 for details on the use of the license in source code.
