### ISSUE TITLE
Not annotation pointcut matches dynamic proxy methods incorrectly

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-framework#27119]
"target" and "not @annotation" combination not works as expected, but "target" and "@annotation" combination works fine.
```java
	// works as expected
	@Around("execution(public * *(..)) and target(repository) and @annotation(org.springframework.transaction.annotation.Transactional)")
	public Object interceptPositive(ProceedingJoinPoint pjp, Repository repository) throws Throwable {
		Method method = ((MethodSignature) pjp.getSignature()).getMethod();
		if (!method.isAnnotationPresent(Transactional.class))
			throw new RuntimeException("annotation should present here");
		return pjp.proceed();
	}

	// not works as expected
	@Around("execution(public * *(..)) and target(repository) and not @annotation(org.springframework.transaction.annotation.Transactional)")
	public Object interceptNegative(ProceedingJoinPoint pjp, Repository repository) throws Throwable {
		Method method = ((MethodSignature) pjp.getSignature()).getMethod();
		if (method.isAnnotationPresent(Transactional.class))
			throw new RuntimeException("annotation should not present here");
		return pjp.proceed();
	}
```
[test-pointcut.zip](https://github.com/spring-projects/spring-framework/files/6751811/test-pointcut.zip) is a test project

**Comment by sbrannen** [comment]
@quaff, have you tried the following?

```java
@Around("execution(public * *(..)) and target(repository) and !@annotation(org.springframework.transaction.annotation.Transactional)")
```

**Comment by quaff** [comment]
> @quaff, have you tried the following?
> 
> ```java
> @Around("execution(public * *(..)) and target(repository) and !@annotation(org.springframework.transaction.annotation.Transactional)")
> ```

Yes, same result.

**Comment by quaff** [comment]
Still not fixed in v6.0.6.

**Comment by sbrannen** [comment]
> Still not fixed in v6.0.6.

Indeed.

I've just assigned to this to the 6.1.x backlog, so that somebody from the team can pick it up.

**Comment by nakulmitra** [comment]
What if I used && in place of and, will it work?
```java
@Around("execution(public * *(..)) && target(repository) && !@annotation(org.springframework.transaction.annotation.Transactional)")
```

**Comment by quaff** [comment]
> @sbrannen what if I used && in place of and, will it work?
> 
> ```java
> @Around("execution(public * *(..)) && target(repository) && !@annotation(org.springframework.transaction.annotation.Transactional)")
> ```

I don't think it will works, `&&` is simply substitution of `and`.

**Comment by quaff** [comment]
https://github.com/spring-projects/spring-framework/blob/b4eb352e1dd2f7e95eb361483b5350dfd4290bd5/spring-aop/src/main/java/org/springframework/aop/aspectj/AspectJExpressionPointcut.java#L424
with my test case, `getMostSpecificMethod` seems return the wrong method to match.
`method` is `public abstract java.util.List com.acme.PersonRepository.findByLastname(java.lang.String)`
`targetMethod` is `public final java.util.List jdk.proxy2.$Proxy99.findByLastname(java.lang.String)`


It could be fixed by add this:
```java
if (Proxy.isProxyClass(targetMethod.getDeclaringClass())) {
	targetMethod = method;
}
```

I'm not sure it's a rightful fix or we should fix `AopUtils.getMostSpecificMethod()`, could you take a look? @sbrannen

**Comment by jhoeller** [comment]
Superseded by PR #30534.
