### ISSUE TITLE
Spring build failed

### ISSUE THREAD

**Issue by MykolaBova** [spring-projects/spring-framework#27123]
I am building Spring from source
https://github.com/spring-projects/spring-framework/wiki/Build-from-Source

Build failed with following errors
```
> Task :spring-webflux:test

WebClientIntegrationTests > [1] webClient [org.springframework.http.client.reactive.ReactorClientHttpConnector@5a2cb330] FAILED
    java.lang.AssertionError at MessageFormatter.java:115

WebClientIntegrationTests > [2] webClient [org.springframework.http.client.reactive.JettyClientHttpConnector@61cf40b] FAILED
    java.lang.AssertionError at MessageFormatter.java:115

WebClientIntegrationTests > [3] webClient [org.springframework.http.client.reactive.HttpComponentsClientHttpConnector@2aadb429] FAILED
    java.lang.AssertionError at MessageFormatter.java:115

1982 tests completed, 3 failed, 13 skipped

> Task :spring-webflux:test FAILED

FAILURE: Build failed with an exception.
```
Can you help?

**Comment by MykolaBova** [comment]
Please let me know if any additional information can be useful.

**Comment by sbrannen** [comment]
Sometimes tests fail intermittently.

Did you try running the build multiple times?

> Please let me know if any additional information can be useful.

What are the actual error messages and stack traces for the failed tests?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by MykolaBova** [comment]
`myk@myk-Bravo-17-A4DDK:~/z.prj.cc.code.3/spring-framework$ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :spring-core:compileTestFixturesJava FAILED
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:21: error: package org.xmlunit.assertj does not exist
import org.xmlunit.assertj.XmlAssert;
                          ^
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:22: error: package org.xmlunit.diff does not exist
import org.xmlunit.diff.DifferenceEvaluator;
                       ^
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:23: error: package org.xmlunit.diff does not exist
import org.xmlunit.diff.NodeMatcher;
                       ^
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:24: error: package org.xmlunit.util does not exist
import org.xmlunit.util.Predicate;
                       ^
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:42: error: cannot find symbol
        public XmlContentAssert isSimilarTo(Object control, Predicate<Node> nodeFilter) {
                                                            ^
  symbol:   class Predicate
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:48: error: cannot find symbol
                        DifferenceEvaluator differenceEvaluator) {
                        ^
  symbol:   class DifferenceEvaluator
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:60: error: cannot find symbol
        public XmlContentAssert isSimilarToIgnoringWhitespace(String control, NodeMatcher nodeMatcher) {
                                                                              ^
  symbol:   class NodeMatcher
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContent.java:22: error: package org.xmlunit.assertj does not exist
import org.xmlunit.assertj.XmlAssert;
                          ^
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:38: error: cannot find symbol
                XmlAssert.assertThat(super.actual).and(control).areSimilar();
                ^
  symbol:   variable XmlAssert
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:43: error: cannot find symbol
                XmlAssert.assertThat(super.actual).and(control).withNodeFilter(nodeFilter).areSimilar();
                ^
  symbol:   variable XmlAssert
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:49: error: cannot find symbol
                XmlAssert.assertThat(super.actual).and(control).withDifferenceEvaluator(
                ^
  symbol:   variable XmlAssert
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:55: error: cannot find symbol
                XmlAssert.assertThat(super.actual).and(control).ignoreWhitespace().areSimilar();
                ^
  symbol:   variable XmlAssert
  location: class XmlContentAssert
/home/myk/z.prj.cc.code.3/spring-framework/spring-core/src/testFixtures/java/org/springframework/core/testfixture/xml/XmlContentAssert.java:61: error: cannot find symbol
                XmlAssert.assertThat(super.actual).and(control).ignoreWhitespace().withNodeMatcher(nodeMatcher).areSimilar();
                ^
  symbol:   variable XmlAssert
  location: class XmlContentAssert
13 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-core:compileTestFixturesJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
74 actionable tasks: 3 executed, 4 from cache, 67 up-to-date

A build scan was not published as you have not authenticated with server 'ge.spring.io'.
`

**Comment by MykolaBova** [comment]
Hi Team!

Are there any updates?

Can any additional information be helpful?

**Comment by bclozel** [comment]
The second issue (a compiling issue for spring-core tests) is completely different from the first one (a probably falky test in webflux). Also, this means that the second one worked at some point since the build reached spring-webflux.

Maybe a library is corrupted in your Gradle cache?

**Comment by MykolaBova** [comment]
> The second issue (a compiling issue for spring-core tests) is completely different from the first one (a probably falky test in webflux). Also, this means that the second one worked at some point since the build reached spring-webflux.
> 
> Maybe a library is corrupted in your Gradle cache?
Thanks a lot for prompt response!!

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
