### ISSUE TITLE
Could you migrate @MockBean to Spring Framework?

### ISSUE THREAD

**Issue by diguage** [spring-projects/spring-framework#27130]
`@MockBean` is a great tool for the test. It helps me to write a lot of more efficient test code. But my company has some projects which do use Spring Boot. So it can not use `@MockBean`.

Could you migrate @MockBean to Spring Framework?

**Comment by snicoll** [comment]
Duplicate #18655

**Comment by sbrannen** [comment]
Effectively superseded by #29917 which introduces support for `@TestBean`, `@MockitoBean`, and `@MockitoSpyBean` in the `spring-test` module in Spring Framework 6.2.
