### ISSUE TITLE
ObjectToMapConverter and MapToObjectConverter

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-framework#27138]
I want something like `MapToMapConverter`, but allow an object to be converted, either way, seems feasible. I really wouldn't expect it to be able to do much more than reflective field name as key, and then value as value. Though perhaps MapToObject is harder?

**Comment by snicoll** [comment]
The way this would works is very specific I am afraid. Also, allowing any object can lead to question about how deep we go. Jackson, for instance, as support for that and requires additional metadata to do the right thing. I can't expect us doing anything better without it.

There hasn't been much interest for that feature either, so I am going to close this. Thanks for the suggestion, in any case.
