### ISSUE TITLE
Dokka generation is not including links to Coroutines

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#27169]
This is due to https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/package-list resulting in a 404.

- https://github.com/Kotlin/kotlinx.coroutines/issues/290

This should be backported as well, since `5.2.x` is affected.

**Comment by snicoll** [comment]
The Kotlin team was asking us to rely on https://kotlin.github.io/kotlinx.coroutines/package-list

**Comment by sdeleuze** [comment]
Unless I am mistaken, this is [correctly configured on `5.3.x`](https://docs.spring.io/spring-framework/docs/5.3.x/kdoc-api/spring-webflux/org.springframework.web.reactive.function.client/body-to-flow.html) as of [this commit](https://github.com/spring-projects/spring-framework/commit/ab41db474e2a94d672fa44f4f66c34c136f7db46).

For `5.2.x`, based on my tests and as pointed in [Sam's comment](https://github.com/spring-projects/spring-framework/issues/27169#issuecomment-942567747) this is no way to make it work with Dokka `0.10` so we can't fix it.

As a result, I close this issue with no milestone attached, feel free to set `5.3.10` if you think that's better (not sure we should do that with closed milestones).
