### ISSUE TITLE
Reference docs missing left-hand side navigation

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#27177]
It displays fine [in 5.3.8](https://docs.spring.io/spring-framework/docs/5.3.8/reference/html/web.html#spring-web) but [in 5.3.9](https://docs.spring.io/spring-framework/docs/5.3.9/reference/html/web.html#spring-web) it's missing.

**Comment by shivansh29** [comment]
Hey I see your issue 
and confused what kind of fix are you expecting is it a documentation fix
or code fix
feels like code fix

**Comment by sbrannen** [comment]
@shivansh29, the `type: documentation` label means that the work required is related to documentation published by the framework. Whether it is technically code (in the build scripts) or prose/markup that is to be changed does not matter.

The cause for the regression is likely commit 71995a90876fd5b0aa39259df35476fcc3b0c5ef.

**Comment by fupgang** [comment]
The table of content is still missing for the _current_ version (5.3.9). Won't this be fixed until the release of 5.3.10?
I wonder if there is a workflow to regenerate and publish a fixed reference documentation?
