### ISSUE TITLE
Tests hanging when adding mockito-inline dependency

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-framework#27180]
When adding the `org.mockito:mockito-inline` dependency to the project some tests get stuck.

It happens when we run a single test class, via IDE or CLI, and we have a `static` variable inside an inner class, like so:

```java
public class MyClassTestApplicationContext {

   @Test
   public void dontStuck() {
      GenericBeanDefinition beanDefinition = new GenericBeanDefinition();
      beanDefinition.setBeanClass(StuckConfig.myOtherClass.getClass());
      beanDefinition.setSource(StuckConfig.myOtherClass);
      GenericApplicationContext context = new GenericApplicationContext();
      context.registerBeanDefinition("myOtherClass", beanDefinition);
      context.refresh();
   }

   @Test
   public void dontStuckAlso() {
      AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
      context.register(DontStuckConfig.class);
      context.refresh();
      context.getBean(MyOtherClass.class);
   }

   @Test
   public void stuck() {
      AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
      context.register(StuckConfig.class);
      context.refresh();
   }

   @Configuration
   public static class StuckConfig {

      private static final MyOtherClass myOtherClass = Mockito.mock(MyOtherClass.class);

      @Bean
      public MyOtherClass myOtherClass() {
         return myOtherClass;
      }
   }

   @Configuration
   public static class DontStuckConfig {

      private final MyOtherClass myOtherClass = Mockito.mock(MyOtherClass.class);

      @Bean
      public MyOtherClass myOtherClass() {
         return myOtherClass;
      }
   }

}
```

**How to reproduce:** Run the `MyClassTestApplicationContext` tests in the sample.
You can make it work by doing one of the following:
 - Remove the `mockito-inline` dependency;
 - Remove the `static` modifier from the mock
 - Mock an arbitrary object inside the parent class, like so:
```java
public class MyClassTestApplicationContext {
    private static final Object obj = Mockito.mock(Object.class);
    //... remaining code
```

**Sample:** https://github.com/marcusdacoregio/mockito-inline-stuck-bug
There's a minimum setup in the sample to simulate the behavior on the `MyClassTestApplicationContext`.

**Additional information:** I could see that the Thread gets stuck at [this part of the ByteBuddyAgent](https://github.com/raphw/byte-buddy/blob/5d15c52af1c820e34c256ad0b47bc5dd456c5696/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L687-L697).
I first found this problem when running a [test class](https://github.com/spring-projects/spring-security/blob/main/config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurerTests.java) in the Spring Security project, which worked before [this change](https://github.com/spring-projects/spring-security/commit/14240b25597c9301d03dfabd480911a166977fdb#diff-5d66140e85ec0c0a94831758e4c49b8a36421c527e8ea21cd100a96b34633ba6R69).

**Affects:** 5.3.8

---

**Comment by sbrannen** [comment]
At a glance, this appears to be an issue with either Mockito, ByteBuddy, or a combination of the two.

@marcusdacoregio, what makes you think this has something to do with the core Spring Framework?

**Comment by marcusdacoregio** [comment]
Thanks for the response @sbrannen. The reason to open the issue within the core framework is because I couldn't simulate the problem without using it. So I thought it would be good to ask help from you.

**Comment by sbrannen** [comment]
If you annotate `StuckConfig` with `@Configuration(proxyBeanMethods = false)`, your test will pass.

That ensures that a dynamic subclass of `StuckConfig` is not created using CGLIB. 

I didn't dig into the details, but it appears that `mockito-inline` is not able to create a mock for the static field when it's inside a subclass generated by CGLIB.

In light of that, I don't consider this an issue for the core Spring Framework.

Please note that `mockito-inline` is an [experimental feature](https://javadoc.io/doc/org.mockito/mockito-core/2.23.0/org/mockito/Mockito.html#39). So please open an issue with the Mockito team to see if they can support such use cases.

**Comment by sbrannen** [comment]
As a side note, I typically try to avoid static fields in `@Configuration` classes solely for the purpose of testing. There are usually other options for achieving the same goal within your tests.
