### ISSUE TITLE
@Cacheable caches empty Optionals but documentation states otherwise

### ISSUE THREAD

**Issue by mwojterski** [spring-projects/spring-framework#27184]
`@Cacheable` javadoc states:

> Note that Java8's Optional return types are automatically handled and its content is stored in the cache if present. (...)

This seems to suggest only present optionals are cached, that's not true. English isn't my first lang, so please forgive if I misunderstood, I guess "if present" may refer to the cache.

spring-context v5.3.1

**Comment by sbrannen** [comment]
You're correct. The wording is slightly confusing. This applies to the Javadoc for `@Cacheable` as well as the documentation in the [reference manual](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-annotations-cacheable-condition).

If an `Optional` return value is _empty_, `null` will be stored in the `Cache` just as if the return value itself were `null`.

**Comment by sbrannen** [comment]
@mwojterski, thanks for opening your first issue for the Spring Framework.

We will update the documentation accordingly.
