### ISSUE TITLE
Missing side menu on Spring Core documentation page

### ISSUE THREAD

**Issue by crlikcngroup** [spring-projects/spring-framework#27192]
Hi guys,

just in case you haven't noticed. But after the last update, roughly a week ago, Spring Core HTML doc page doesn' have a side menu anymore.
(URL: https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#spring-core)

The page is pretty long and without a sidemenu, it's quite difficult to navigate on the page at the moment.

![image](https://user-images.githubusercontent.com/46486968/126335834-e709dac4-2853-4ab0-a040-1c79c87ca928.png)

**Comment by crlikcngroup** [comment]
Reproducible in Vivaldi and Firefox browser for me. So I suppose it's not a JS issue.

**Comment by bclozel** [comment]
Duplicates #27177
