### ISSUE TITLE
WebSocketMessageBrokerStats.getExecutorStatsInfo() throws exception because of the hardcoded word "pool"

### ISSUE THREAD

**Issue by leandrodalbo** [spring-projects/spring-framework#27209]
https://github.com/spring-projects/spring-framework/blob/d034a1f26d0ea3782f53b8ff7a2a0cea7c825b71/spring-websocket/src/main/java/org/springframework/web/socket/config/WebSocketMessageBrokerStats.java#L209

Hardcoded "pool" doesn't work, the class name ThreadPoolExecutor contains capital "P" instead of "p".

**Comment by sbrannen** [comment]
Hi @leandrodalbo,

Thanks for submitting your first issue for the Spring Framework!

> Hardcoded "pool" doesn't work, the class name ThreadPoolExecutor contains capital "P" instead of "p".

The expected `"pool"` string comes from the implementation of `java.util.concurrent.ThreadPoolExecutor.toString()`. Thus, the lowercase "p" is not the issue.

However, I can see that an exception could be thrown if the executor supplied to `WebSocketMessageBrokerStats.getExecutorStatsInfo()` is not an instance of `ThreadPoolTaskExecutor`.

For the sake of clarity, could you please provide the stack trace you encountered when the exception was thrown?

**Comment by sbrannen** [comment]
Have you overridden the `clientInboundChannelExecutor` and `clientOutboundChannelExecutor` beans to use a custom-configured `TaskExecutor` other than a `ThreadPoolTaskExecutor`?

**Comment by leandrodalbo** [comment]
I didn't override any of those beans when I discovered this. I was using a simple configuration class in conmbination with
netty-reactor and netty-all libraries.

I haven't got access to the code right now but it was simple Message broker configuration with stomp relay.

When I was debbuging it was using ThreadPoolTaskExecutor but because of the "P" instead "p" you get a -1 in the substring() method.

**Comment by leandrodalbo** [comment]
Overriding the the stats bean and using str.toLowercase() is a quick fix but maybe not the best option.

**Comment by sbrannen** [comment]
> I haven't got access to the code right now but it was simple Message broker configuration with stomp relay.

I already have a fix in place locally, but I'd appreciate if you could supply the stack trace once you get a chance, since that will give us a better idea of what exactly went wrong, possibly allowing us to provide a more _intelligent_ fix.

**Comment by leandrodalbo** [comment]
**Exception**
21-07-23 15:24:42.973 [ERROR] o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1960)
    at org.springframework.web.socket.config.WebSocketMessageBrokerStats.getExecutorStatsInfo(WebSocketMessageBrokerStats.java:209)
    at org.springframework.web.socket.config.WebSocketMessageBrokerStats.getClientInboundExecutorStatsInfo(WebSocketMessageBrokerStats.java:17**8)

**Configuration Class**


@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfiguration implements WebSocketMessageBrokerConfigurer {
    private static final int BROKER_HEARTBEAT_INTERVAL_MILLIS = 20000;

    @Autowired
    private Environment env;

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/ws")
                .withSockJS();
    }

    @Override
    public void configureMessageBroker(MessageBrokerRegistry registry) {

        if (Boolean.parseBoolean(env.getProperty("gfl.rabbitmq.enabled"))) {
            registry.setApplicationDestinationPrefixes("/gfl");
            registry.enableStompBrokerRelay("/topic/", "/queue/")
                    .setClientLogin(env.getProperty("gfl.rabbitmq.username"))
                    .setClientPasscode(env.getProperty("gfl.rabbitmq.password"))
                    .setSystemLogin(env.getProperty("gfl.rabbitmq.username"))
                    .setSystemPasscode(env.getProperty("gfl.rabbitmq.password"))
                    .setRelayHost(env.getProperty("gfl.rabbitmq.hostname"))
                    .setRelayPort(Integer.parseInt(env.getProperty("gfl.rabbitmq.port")))
                    .setSystemHeartbeatSendInterval(BROKER_HEARTBEAT_INTERVAL_MILLIS)
                    .setAutoStartup(true);
        } else {
            registry.setApplicationDestinationPrefixes("/gfl")
                    .enableSimpleBroker("/queue", "/topic");
        }
    }

}

**dependencies**

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>
           
            <dependency>
               <groupId>io.projectreactor.netty</groupId>
              <artifactId>reactor-netty</artifactId>
            </dependency>

           <dependency>
               <groupId>io.netty</groupId>
               <artifactId>netty-all</artifactId>
         </dependency>

</dependencies>	


Using the netty-reactor starter gave me the same result.

**Comment by sbrannen** [comment]
Thanks for providing the feedback!

The exception stack trace is as I expected. It indicates that the `clientInboundChannelExecutor` bean has been overridden with a `TaskExecutor` that is not a `ThreadPoolTaskExecutor` (or it is a `ThreadPoolTaskExecutor` that delegates to a subclass of `ThreadPoolExecutor` whose `toString()` implementation does not contain the "pool" text). Another option is that something invoked `WebSocketMessageBrokerStats.setInboundChannelExecutor(TaskExecutor)` with such a `TaskExecutor`.

I tried to reproduce the error using the configuration you supplied, but I unfortunately was not able to reproduce the failure scenario. 

In any case, I can fix the bug to ensure that a `StringIndexOutOfBoundsException` is not thrown in such scenarios.

Having said that, I would still like to reproduce the bug using your application in order to see if there is anything better we can do (for example, to support stats for other types of `TaskExecutor`). So if you could provide a minimal example application that reproduces the bug I would be grateful.

**Comment by sbrannen** [comment]
@leandrodalbo, I fixed this in 42edef0bccb75a09523040b9567866281b574629.

So please feel free to try this out in the upcoming 5.3.10 snapshot.

If you are able to provide us a minimal example that reproduces the error you encountered in your application, we will consider reopening this issue to investigate further options.

**Comment by leandrodalbo** [comment]
Hi, can't provide the app because it is no mine but I think I found what is overriding the bean.

`@Configuration
@EnableScheduling
@EnableAsync( mode = AdviceMode.ASPECTJ )
public class SchedulerConfiguration
{
	@Bean
	@Primary
	public TaskScheduler taskScheduler()
	{
		ThreadPoolTaskScheduler lThreadPoolTaskScheduler = new ThreadPoolTaskScheduler();
		lThreadPoolTaskScheduler.setPoolSize( 4 );
		return lThreadPoolTaskScheduler;
	}
}`

I am not sure, I would need to debug it a bit more, anyway what you have done fixes the problem.

- I would like it to depend on the interface and not a concrete implementation.
- I having the a hardcoded value like that might be dangerous, what if somebody completely rename the class in the future.

Thanks a lot.

**Comment by sbrannen** [comment]
>     * I would like it to depend on the interface and not a concrete implementation.

`java.util.concurrent.ThreadPoolExecutor` does not implement an interface that provides an API to access its stats.

Granted, depending on the format of the text returned by `java.util.concurrent.ThreadPoolExecutor.toString()` is a bit brittle, but that format has not changed from JDK 8 through JDK 16. And if it does change...

1. Our test suite will eventually fail, thereby notifying us of the change.
2. The code in my fix ensures that an exception is not thrown, resulting in "unknown" as the stats if the format changes.

>     * having the a hardcoded value like that might be dangerous, what if somebody completely rename the class in the future.

`java.util.concurrent.ThreadPoolExecutor` is part of the standard JDK library and will not be renamed.

> Thanks a lot.

You're welcome!
