### ISSUE TITLE
Spring Framework Documentation directory disappeared

### ISSUE THREAD

**Issue by innovationmech** [spring-projects/spring-framework#27205]
As mentioned in the title, the directory on the left side of the document still existed not long ago, but now it disappears for some reason. This has a great impact on the reading of the document, and I hope it can be fixed
<img width="1530" alt="截屏2021-07-23 下午5 11 50" src="https://user-images.githubusercontent.com/28939193/126761574-71023493-37d0-4ce7-94e7-6becb22936c8.png">

**Comment by bclozel** [comment]
Duplicates #27177
