### ISSUE TITLE
Support WebSocketSessionDecorator/WebSocketHandlerDecorator in StandardWebSocketClient

### ISSUE THREAD

**Issue by x-gnn** [spring-projects/spring-framework#27207]
Currently, it seems not to be possible to use any `WebSocketSessionDecorator` or `WebSocketHandlerDecorator` with StandardWebSocketClient. It would be great to use `StandardWebSocketClient` e.g. with a `ConcurrentWebSocketSessionDecorator` or any other decorator.

**Comment by rstoyanchev** [comment]
We could create a protected method in `StandardWebSocketClient` for the creation of the `StandardWebSocketSession` and you could override that to decorate it. For `WebSocketHandlerDecorator`, couldn't you apply that on the `WebSocketHandler` passed into the doHandshake method?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
