### ISSUE TITLE
Webflux does not serve static files from default locations

### ISSUE THREAD

**Issue by gerethd** [spring-projects/spring-framework#27202]
**Affects:** \<Spring Framework v5.3.9>

---

Have a project, docs say that /public /static /resources /META-INF/resources are all by default checked for static resources.

with what i have in this repo https://github.com/gerethd/webflux-example they do not and a 404 is received.

I have a copy of the static files in each of the specified folders on each level of the project that would even remotely make sense.

i.e. the files exist inside 
```
./resources/index.html
./resources/resources/index.html
./resources/META_INF/resources/index.html
./resources/public/index.html
./resources/static/index.html
./META_INF/resources/index.html
./src/main/resources/index.html
./src/main/resources/resources/index.html
./src/main/resources/META_INF/resources/index.html
./src/main/resources/public/index.html
./src/main/resources/static/index.html
./src/main/META_INF/resources/index.html
./src/main/public/index.html
./src/main/static/index.html
./public/index.html
./static/index.html
```

The intended functionality is when i run this project and go to http://localhost:8080/index.html I should get the index page but instead i get a 404.

Referenced documentation: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-web-applications.spring-webflux.static-content

**Comment by bclozel** [comment]
The correct location should be "src/main/resources/static" for this use case.
I haven't tried your sample but I did notice that you've annotated your application with `@EnableWebflux`, which signals to Spring Boot that you'd like to take full control of the web configuration.

This is explained [in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-web-applications.spring-webflux.auto-configuration). If you've got other questions, please use StackOverflow - the Spring team and the broader commmunity can help you out there.

Thanks!
