### ISSUE TITLE
why you use cheap and traditional and hated technologies in spring core like servlet, java ee, jsr and so on why you don't present new webserver java 8 or later with new design in serving #27529

### ISSUE THREAD

**Issue by loveyandex** [spring-projects/spring-framework#27227]
why you use cheap technologies in spring core like servlet, jsr and so on why you dont present new webserver java 8 or later with new design in serving

i can not understand why powerful spriong's developer use traditional web technologies like java ee
why u can not update yourself with new design
all java developers hate java ee ....

**Comment by sbrannen** [comment]
Closing this issue since its language and tone violate our [code of conduct](https://github.com/spring-projects/.github/blob/3d965e94708a0014f0f9a2ab05bfc5eb6efef7e4/CODE_OF_CONDUCT.md).
