### ISSUE TITLE
An erratum of micro-benchmark wiki page

### ISSUE THREAD

**Issue by Shawyeok** [spring-projects/spring-framework#27233]
In wiki page [Micro Benchmarks](https://github.com/spring-projects/spring-framework/wiki/Micro-Benchmarks)
> For example, we can run the MimeTypeBenchmark.cachedParserSomeMimeTypes benchmark, with 2 JVM forks, the GC profiler, and specific benchmark parameters with:

```
java -jar spring-core/build/libs/spring-core-5.3.0-SNAPSHOT-jmh.jar -f1 -prof gc -p customTypesCount=10,20 MimeTypeBenchmark.cachedParserSomeMimeTypes
```

I think `2 JVM forks` and `-f1` is a mismatch.

From JMH help doc:
>   -f \<int\>                    
How many times to fork a single benchmark. Use 0 to
                              disable forking altogether. Warning: disabling
                              forking may have detrimental impact on benchmark
                              and infrastructure reliability, you might want
                              to use different warmup mode instead. (default:
                              5)

**Comment by bclozel** [comment]
Thanks @Shawyeok , the typo has been fixed.
