### ISSUE TITLE
Add ability to rollback before close on SingleConnectionDataSource

### ISSUE THREAD

**Issue by marschall** [spring-projects/spring-framework#27249]
We use `SingleConnectionDataSource` with the Oracle driver for integration tests. Although we use the Spring TestContext Framework this sometimes results in commits when we abort tests. We believe this is due to the shutdown hook registered in `AbstractApplicationContext#registerShutdownHook()` ending up calling `SingleConnectionDataSource#destroy()` which calls `Connection#close()`. Calling `Connection#close()` with an open transaction results in the Oracle driver committing.

This behavior is documented in [several](https://in.relation.to/2005/10/20/pop-quiz-does-connectionclose-result-in-commit-or-rollback/) [places](https://stackoverflow.com/questions/218350/does-java-connection-close-rollback) and even mentioned in the official documentation.

https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/JDBC-getting-started.html#GUID-96D6787D-71A6-4282-B17E-0951DED3DEF9

> If the auto-commit mode is disabled and you close the connection without explicitly committing or rolling back your last changes, then an implicit COMMIT operation is run. 

Calling `Connection#close()` with an open transaction is not recommended and results in unspecified behavior according to the JDBC specification:

https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#close()

> It is **strongly recommended** that an application explicitly commits or rolls back an active transaction prior to calling the close method. If the close method is called and there is an active transaction, the results are implementation-defined.

We would welcome a property, for example named `rollbackBeforeClose` that behaves something like the following. Maybe with an additional `try-catch` around `Connection#rollback()`. An alternative would be to always try to rollback when auto commit is disabled to follow the JDBC reccomendation, however we don't know what the side effects of this would be.

```java
	private void closeConnection() {
		if (this.target != null) {
			try {
				if (this.rollbackBeforeClose && !this.target.getAutoCommit()) {
					this.target.rollback();
				}
				this.target.close();
			}
			catch (Throwable ex) {
				logger.info("Could not close shared JDBC Connection", ex);
			}
		}
	}
```

We would be willing to work on a PR.

**Comment by marschall** [comment]
> The TCF will rollback at the end of a test by default so I can only assume that you're not using that?

We are using that but as you say the TCF only rolls back upon test completion. If the JVM terminates before this then the shutdown hook (registered in `AbstractApplicationContext#registerShutdownHook()`) is executed which closes the application context which ends up calling `SingleConnectionDataSource#destroy()` which calls `Connection#close()`.

This can happen when for example a developer hits [Terminate](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fviews%2Fdebug%2Fref-terminate.htm) in the Eclipse debugger which then results in a commit of all open transactions.

**Comment by snicoll** [comment]
Thanks for the feedback. I wonder if that would make sense to register a similar mechanism when the test runs to make sure that the rollback happens if the test is stopped mid-flight. To me, that would be a more consolidated answer than your suggestion of `rollbackBeforeClose`. I am also puzzled that we didn't have more reports of this behavior.

Flagging for team attention to see what the rest of the team thinks.

**Comment by marschall** [comment]
Yes, there are other ways how this could be solved. TCF could roll back all in flight transactions or the transaction manager could roll back all in flight transactions.

**Comment by jhoeller** [comment]
Since `SingleConnectionDataSource` is primarily for testing environments anyway and the Oracle driver behavior can be hard to deal with indeed, I'm adding a `rollbackBeforeClose` property.

Being at it, I've also made `SingleConnectionDataSource` implement `AutoCloseable` for use with a try-with-resource statement.
