### ISSUE TITLE
Is it fine to add the BeanPostProcessorChecker in the first place?  

### ISSUE THREAD

**Issue by dpy1123** [spring-projects/spring-framework#27251]
I see some BeanPostProcessorChecker‘s mismatch log, and I have a question. 
Is it fine to add the BeanPostProcessorChecker in the first place? 
https://github.com/spring-projects/spring-framework/blob/451bcfc832dacbd601969e675dcd8e01fe92aa48/spring-context/src/main/java/org/springframework/context/support/PostProcessorRegistrationDelegate.java#L227

Since `beanFactory.getBean(ppName, BeanPostProcessor.class)` will also trigger the BeanPostProcessorChecker and at that time some of BeanPostProcessors were not added yet. 
I am thinking of add the BeanPostProcessorChecker just behind `registerBeanPostProcessors(beanFactory, internalPostProcessors);`.
Am I right?

**Comment by sbrannen** [comment]
> Is it fine to add the BeanPostProcessorChecker in the first place?

Yes, that is a feature that notifies the user whenever a bean (that is neither a `BeanPostProcessor` nor an _infrastructure_ bean)...

> is created during BeanPostProcessor instantiation, i.e. when a bean is not eligible for getting processed by all BeanPostProcessors.

> I am thinking of add the BeanPostProcessorChecker just behind `registerBeanPostProcessors(beanFactory, internalPostProcessors);`.
> Am I right?

No, that would defeat the purpose of the `BeanPostProcessorChecker`.

In light of that, I am closing this issue.
