### ISSUE TITLE
UrlPathHelper: checkReadOnly() called in read method shouldRemoveSemicolonContent()

### ISSUE THREAD

**Issue by lijinliangyihao** [spring-projects/spring-framework#27256]
**Affects:** 5.3.8

---

Method `checkReadOnly` is called in read method UrlPathHelper#shouldRemoveSemicolonContent, line 149. If we want to know whether we should `removeSemicolonContent` when `this.readOnly` is true, an error will be thrown.
```
public boolean shouldRemoveSemicolonContent() {
    checkReadOnly();
    return this.removeSemicolonContent;
}
```

**Comment by evpaassen** [comment]
Today I encountered this bug too. I created PR #27303 to fix it.

**Comment by sbrannen** [comment]
Superseded by #27303.
