### ISSUE TITLE
IllegalStateException after upgrading Spring MVC from 4.3.9 to 5.2.6: Ambiguous handler methods mapped

### ISSUE THREAD

**Issue by balaji-itorix** [spring-projects/spring-framework#27253]
I have two `@RequestMapping`  methods like below in my RestController class. One service methods is to consume the `application/x-www-form-urlencoded` Media Type and other to consume all the other type of requests. This is working correctly in Spring Boot 1.5.4 but results in Ambiguous handler methods exception after upgrading to Spring boot 2.2.7

```java
@RequestMapping(value = "/**")
public ResponseEntity service(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse,
		@RequestParam(required = false) MultiValueMap<String, String> requestParams,
		@RequestBody(required = false) String requestBody, @PathVariable(required = false) String pathVariables,
		@RequestHeader(required = false) MultiValueMap<String, String> headerVariables) {
	System.out.println("Inside Service method");
	return new ResponseEntity(HttpStatus.ACCEPTED);
}

@RequestMapping(value = "/**", consumes = "application/x-www-form-urlencoded")
public ResponseEntity serviceURLEncode(HttpServletRequest httpServletRequest,
			HttpServletResponse httpServletResponse,
		@RequestParam(required = false) MultiValueMap<String, String> requestParams,
		@PathVariable(required = false) String pathVariables,
		@RequestBody(required = false) MultiValueMap<String, String> formParam,
		@RequestHeader(required = false) MultiValueMap<String, String> headerVariables) {
	System.out.println("Inside Service method:application/x-www-form-urlencoded");
	return new ResponseEntity(HttpStatus.ACCEPTED);
}
```

The below block of code in `ConsumesRequestCondition:getMatchingCondition` introduced in the newer Spring MVC is causing this issue.

```java
if (!hasBody(request) && !this.bodyRequired) {
	return EMPTY_CONDITION;
}
```

**Comment by balaji-itorix** [comment]
The above issue results in actuator endpoints(/actuator/prometheus) being consumed by the RestController and throws ambiguous handler mapping error

**Comment by rstoyanchev** [comment]
This was updated in 5.2 with #22010 which you can see for more details on the reasons.

Your second mapping is declared with an optional request body, so for requests without a body, there is also no content type to begin with. So the mapping effectively means, when there is a body match if it is "application/x-www-form-urlencoded" or otherwise also match if there is no body.

You can change your second mapping to `@RequestBody`, i.e. required, and make it handle only "application/x-www-form-urlencoded" requests.
