### ISSUE TITLE
Write a new Getting Started Guide for Spring MVC without Spring Boot

### ISSUE THREAD

**Issue by danilopiazza** [spring-projects/spring-framework#27258]
Spring [Getting Started Guides](https://spring.io/guides#getting-started-guides) only explain how to create Spring Boot applications.

There should be a new tutorial explaining how to build a [simple Spring MVC application](https://spring.io/guides/gs/serving-web-content/) without Spring Boot, using either Java configuration or XML configuration.

**Comment by danilopiazza** [comment]
If this is a good idea, I am willing to write a new Getting Started Guide, starting from [Serving Web Content with Spring MVC](https://spring.io/guides/gs/serving-web-content/).

**Comment by bclozel** [comment]
Sorry but our getting started guides are only relying on Spring Boot. These guides are meant to onboard new developers or explain help Spring Boot users with specific projects or features.

The Spring team has been advocating for Spring Boot as the main entry point for a while, and it probably going to be reflected even more in the documentation in the future. Of course, the projects reference documentation will keep supporting developers using them independently.

Thanks!
