### ISSUE TITLE
Allow application to continue w/o using cache if  backing cacheing service is down

### ISSUE THREAD

**Issue by jbotuck** [spring-projects/spring-framework#27261]
See https://stackoverflow.com/questions/29003786/how-to-disable-redis-caching-at-run-time-if-redis-connection-failed and
https://stackoverflow.com/questions/44183715/how-to-disable-caching-at-runtime-if-couchbase-connection-failed?noredirect=1&lq=1

I don't want my application's ability to function to be conditional on the health of the cache. When something goes wrong with connecting to whatever is backing the cache (ie redis) the application should be able to recompute the value gracefully (if configured to do so)

**Comment by snicoll** [comment]
Duplicate #27826
