### ISSUE TITLE
dynamicLoader.loadClass  doesn't seem to be working

### ISSUE THREAD

**Issue by xjgkd** [spring-projects/spring-framework#27265]
ContextTypeMatchClassLoader ，a temporary ClassLoader for type matching（when use ltw）
but its loadClass always seems to  parental delegation，OverridingClassLoader‘s  overrideDelegate seems always null

**Comment by snicoll** [comment]
Sorry this got overlooked but that's not very actionable. I don't know what problem you're facing or if that's a question. If you attach a small sample that we can run ourselves, we can have another look.
