### ISSUE TITLE
missing table of content in spring framework document

### ISSUE THREAD

**Issue by zlqpzww** [spring-projects/spring-framework#27274]
Problem: The table of content in spring framework document are missing. 
Where: https://docs.spring.io/spring-framework/docs/current/reference/html/web.html
![image](https://user-images.githubusercontent.com/11763554/129317473-ae7f7129-1554-4055-8845-6d9abf8fdb4c.png)
Wanted: The TOC come back pls

**Comment by bclozel** [comment]
Duplicates #27177
