### ISSUE TITLE
The table of contents for Spring Framework  is missing

### ISSUE THREAD

**Issue by beWalter** [spring-projects/spring-framework#27272]
Hi~
I found that the The Spring Framework's table of contents  is missing.
And that makes it inconvenient to find the specified chapter.
And I remember it wasn't like this before.
Is that any wrong with this doc page?

https://docs.spring.io/spring-framework/docs/current/reference/html/core.html
![image](https://user-images.githubusercontent.com/19700715/129299505-432d8083-6f50-4bd0-9062-1c54dfa06cc6.png)

**Comment by beWalter** [comment]
And I found that the second one was normal and the others had problems
![image](https://user-images.githubusercontent.com/19700715/129300512-02c8f35a-ffd5-4582-8c27-9f2cc86b8a5b.png)

**Comment by bclozel** [comment]
Duplicates #27177
