### ISSUE TITLE
Many threads blocked on CachingMetadataReaderFactory$LocalResourceCache

### ISSUE THREAD

**Issue by YangyangLi0528** [spring-projects/spring-framework#27315]
many threads blocked on CachingMetadataReaderFactory$LocalResourceCache
spring-core-5.0.8.RELEASE
**Affects:** \<Spring Framework version>spring-core-5.0.8.RELEASE

---

**Comment by snicoll** [comment]
Sorry but the report is not actionable. If you can share a small sample that reproduces what you tried to describe, we can have another look
