### ISSUE TITLE
Annotation @Indexed does not work in enumerations

### ISSUE THREAD

**Issue by zhou-hao** [spring-projects/spring-framework#27321]
Annotation @Indexed  does not work in enumerations

**Affects:**  5.2.15-RELEASE

---
 
```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Indexed
public @interface Dict {

}

@Dict
public enum MyDict{
 
}

```

**Comment by snicoll** [comment]
@zhou-hao what are you trying to achieve? The context indexer is meant for beans candidate or infrastructure that we would need to scan. An enum does not fall in this category so that is to be expected that it isn't scanned.

**Comment by zhou-hao** [comment]
I wan't  to use @Indexed to implement custom type scanning.

**Comment by snicoll** [comment]
Sorry but the context indexer is primarily targeted at the `ApplicationContext` and there is no need for us to support Enums at this time. I am not keen to expand the scope of the scanning for something we don't need ourselves.
