### ISSUE TITLE
resttemplate can't invoke webflux service

### ISSUE THREAD

**Issue by cjdxhjj** [spring-projects/spring-framework#27362]
**Affects:** \<Spring Framework version>
all version

the webflux service can invoke with the content-type without the charset parameter, when invoke with charset it response 504,

even though i was special the content-type without the charset, the client add the charset automatic

the code is here
![image](https://user-images.githubusercontent.com/5616997/132179899-4a5f7bfa-b318-46b2-86c4-35942fcae57d.png)
![image](https://user-images.githubusercontent.com/5616997/132179927-7daad525-4bf5-4169-8f26-736ae78c6dd3.png)

there is no option to config this behavior, so the request aways failed

**Comment by bclozel** [comment]
Screenshots of our own codebase doesn't really help us understand the problem.
Could you instead provide a sample application that shows the issue? Ideally, a Spring Boot application generated on start.spring.io with a test using `RestTemplate`.

**Comment by cjdxhjj** [comment]
that was my fault, i have debug into the code, and found that, i wrote an form data resolver, i compare the content type, when it equal to MediaType.APPLICATION_FORM_URLENCODED, i resolve the parameter, but my controller is kotlin code, when the content-type contains charset parameter, the test was failed, the parameter not resolved, but my controller was expected one value,  that cause the error, i have just rewite to compare the content-type type and subtype value, that works.
mediaType.type == formContentType.type && mediaType.subtype == formContentType.subtype
