### ISSUE TITLE
Support Policy for Spring 5.[0-2].x is not clear

### ISSUE THREAD

**Issue by c-klinger** [spring-projects/spring-framework#27370]
The documentation on the https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions page does provide us the information, that the versions 5.1.x and 5.0.x "are not actively supported anymore" and 5.2.x is "to be actively supported until the end of 2021".

I would be interested and expected the page to describe a little more in detail what does "actively supported" mean? In particular: Will version 5.2.x still get releases for critical bugs or security issues after "end of 2021"?

I think this is an important information for many projects using Spring Framework and not clear in the document.

**Comment by bclozel** [comment]
Hi @c-klinger - you're right, our official support policy is not 100% clear for all Spring projects and we need to communicate consistently (same place, same words, easy to compare). We're also not always [featuring our commercial support](https://tanzu.vmware.com/spring-runtime) for the broader community.

We're going to address this issue soon on spring.io with clear timelines for each project.

Now about Spring Framework support:

* "current branch" means that this is the current generation and that we're working on new features there
* "actively supported" means that this branch is supported by the team with fixes and backports, including security fixes
* "not actively supported" means that only commercial support applies. Customers can ask for fixes, backports and security fixes. All releases are publicly available (there's no private, "customer artifact repository"), but the community cannot ask for backports under the open source support policy.
* EOL means we don't expect to release any new release for that line.

This comment reflects my personal understanding of our current support policy for Spring Framework - so don't consider this as an official statement. We're working on an improved support policy, to be featured on spring.io soon.
