### ISSUE TITLE
Spring-RSocket: potential server file descriptors exhaustion with idle connections

### ISSUE THREAD

**Issue by mostroverkhov** [spring-projects/spring-framework#27373]
Spring-RSocket server accepts idle connections that never send anything, then stay forever because initial frame is not received 
and server seemingly lacks timeout for handshake.

Bad clients may open arbitrary number of idle connections that exhaust server's available file descriptors, make It unable to accept further connections.

With [reproducer](https://github.com/mostroverkhov/springboot-repros) on 2.5.4 client opens 10k idle connections that are never timed out by server.

`./server.sh` , `idle_connections.sh`

**Comment by rstoyanchev** [comment]
Thanks for the report. For STOMP over WebSocket we have a [timeToFirstMessage](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/socket/messaging/SubProtocolWebSocketHandler.html#setTimeToFirstMessage-int-) property that sets the max time to wait for the first STOMP frame (`CONNECT`) after the connection is established. 

A `DuplexConnectionInterceptor` would probably gives us the ability to do something similar for RSocket although such an interceptor would require to installed. This could be done in Boot, but it does mean that other Java applications  that are not using Boot or that not using Spring would still have the issue. 

I think we should investigate for this to be done in RSocket Java as a built-in feature.

/cc @OlegDokuka

**Comment by OlegDokuka** [comment]
Observed same in the new version of rsocket-ts. Thus, I guess we can expose a property on the rsocket-server side to terminate idle connections

**Comment by rstoyanchev** [comment]
I don't think I can transfer the issue across organizations, so I've created https://github.com/rsocket/rsocket-java/issues/1025.

**Comment by mostroverkhov** [comment]
@rstoyanchev what about [1](https://github.com/spring-projects/spring-framework/issues/27462), [2](https://github.com/spring-projects/spring-framework/issues/27427), [3](https://github.com/spring-projects/spring-framework/issues/27428)? It seems current RSocket/RSocket-java servers are not safe to expose to 3rd party clients, and I see people [suggest](https://twitter.com/yschimke/status/1471840840775606284) using It even with mobile applications.
