### ISSUE TITLE
SpEL cannot evaluate or compile expression with null-safe `void` method invocation

### ISSUE THREAD

**Issue by rgrvontela** [spring-projects/spring-framework#27421]
`org.springframework.expression.spel.CodeFlow.toBoxedDescriptor()` throws "Unexpected non primitive descriptor V" while trying to create a `MethodReference` for a method with a `void` return type.

For an analogous scenario using `java.lang.Void` as the return type, no exception is thrown.

I think while checking for primitives using method `CodeFlow.toDescriptor()` that `"V"` is returned for a `void` return type, but the returned `"V"` is not handled in the `CodeFlow.toBoxedDesciptor()` method.

**Comment by xixingya** [comment]
Maybe Void is not boxed

**Comment by snicoll** [comment]
There is indeed an inconsistency here that we attempt to box `void` for null safety reason but that's not necessary with `void`. 

@rgrvontela that explains why `Void` works as it's a non-primitive type.

**Comment by sbrannen** [comment]
I think the bug is actually that `org.springframework.expression.spel.CodeFlow.isPrimitive(String)` should not return `true` for `"V"`.

I'll look into it.
