### ISSUE TITLE
Wrong Spring Framework apidoc link on spring.io website 

### ISSUE THREAD

**Issue by boszormenyip** [spring-projects/spring-framework#27434]
**Affects:** 5.3.10

---

On the https://spring.io/projects/spring-framework#learn site, the api doc of Spring Framework version 5.3.10. The apidoc link points to https://docs.spring.io/spring-framework/docs/current/api/, but I believe the right link is https://docs.spring.io/spring-framework/docs/current/javadoc-api/

Reproduction
* Open https://spring.io/projects/spring-framework#learn.
* Select API Doc. of version 5.3.10.

Expected
* I see the apidoc of Spring Framework 5.3.10.

Actual
* I see a "404 Oops! The page can’t be found." message

**Comment by bclozel** [comment]
Thanks for letting us know, this is now fixed.
We can't really milestone this issue in this project since this is taken care of in a different application.

Thanks!
