### ISSUE TITLE
Retain support for legacy JSR-250 javax.annotation.PostConstruct/PreDestroy and JSR-330 javax.inject.Inject in addition to Jakarta EE 9 annotations

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#27444]
After migration to Jakarta EE 9, it's easy to miss that `javax.annotation.PostConstruct` or `javax.inject.Inject` are no longer working when not covered by a test. This can be an easy-to-make bug when these annotations reside on the classpath after migrating to Jakarta EE 9. 

It would be neat to support both annotation variants for at least a grace period or to fail fast when these annotations are in use.

**Comment by mdeinum** [comment]
Would it make sense to, next to retain support, log a warning if the legacy JSR-250 annotations are detected? As to warning/incentive to the user to migrate to the Jakarta annotations?
