### ISSUE TITLE
Inconsistent validation order for different inputs and authorization

### ISSUE THREAD

**Issue by flix-** [spring-projects/spring-framework#27448]
Spring Boot version: 2.5.4

Consider the following controller:

```java
@RestController
@Validated
public class FooController {

    @PutMapping(
        value    = "/lorem/{loremId}",
        consumes = "text/csv",
        produces = "application/json"
    )
    @PreAuthorize("@authz.isAuthorizedForXyz(#loremId, #ipsumId)")
    public ResponseEntity<List<Bar>> handlePutBar(@PathVariable @Size(max = 16) String loremId,
                                                  @RequestParam(name = "ipsumId") @Size(max = 32) String ipsumId,
                                                  @RequestBody @Valid BarsHolder barsHolder) {
        // ...
    }
}
```

In this case only _barsHolder_ is validated before the method _isAuthorizedForXyz()_ is called for authorization. Both _loremId_ and _ipsumId_ are validated afterwards, straight before entering the controller logic. Basically, the method used for authorization is receiving unvalidated input here.

(Adding `@Valid` prior to _loremId_ / _ipsumId_ won't change behavior...)

Enhancement:

Validate all input parameters before authorization logic is applied as already done for `@RequestBody` annotated parameters. This allows to have validation logic consistently on the controller method.

Related:

https://github.com/spring-projects/spring-security/issues/6545
https://github.com/spring-projects/spring-boot/issues/10157

**Comment by StevenPG** [comment]
Also curious about any updates, my team is running into the same issue. 

It poses a major problem for UUID parameters since Jackson adds padding for the PreAuthorize and afterward runs the validation. So some invalid incoming UUIDs are made valid first using padding by Jackson, authorized incorrectly (in our flow), and then validated uselessly.

**Comment by Chuanhui-Liu** [comment]
Also looking for some helpful updates cause our team are facing the same issue =><=

**Comment by valh1996** [comment]
+1

In the meantime, do you know a workaround for using `@Valid` with `@PreAuthorize`? But have the role validation (@PreAutorize) done before please?

**Comment by Tockra** [comment]
I run into the same issue.
Did you find a work around for it?

**Comment by Aliaksie** [comment]
+1 
Any progress here? :)

**Comment by valh1996** [comment]
Hi @Tockra & @Aliaksie,

My temporary solution is to protect these POST/PUT routes in a custom `WebSecurityConfigurerAdapter` : 
```java
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true )
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // code
        
        
        // Entry points
        http.authorizeRequests()
                .mvcMatchers(HttpMethod.PUT, "/v1/users/{userId}")
                    .access("hasAnyRole('ADMIN', 'HR') or (hasAnyRole('CANDIDATE', 'EMPLOYEE') and @authorizationComponent.canEditUser(principal, #userId))")

                .anyRequest().authenticated();
     
       // Apply JWT
        http.apply(new JwtTokenFilterConfigurer(jwtTokenProvider));
    }
}
```

**Comment by Tockra** [comment]
OKay, thank you valh. 
I know, that I can do the authentification there, but I would like to continue to use the @PreAuthorize feature.
I built an ugly solution.
I wrote a class "ValidatorService" which seems like this:
```java

@Service
@Validated
public class ValidateService {
    public MyDtoToValidate springValidation(@Valid final MyDtoToValidate myDtoToValidate) {
        return myDtoToValidate;
    }
}
```

Controller:
```java
// Autowire this.validateService
   @GetMapping(value = "")
   @PreAuthorize("hasAuthority('SOME_RIGHT')")
    public void exampleEndpoint(@RequestBody final MyDtoToValid dto) {
         this.validationService.springValidation(dto);

         // do stuff
    }
```

**Comment by valh1996** [comment]
> Okay, thank you valh. I know, that I can do the authentification there, but I would like to continue to use the @PreAuthorize feature. I built following (not clear) solution. I wrote a class "ValidatorService" which seems like this:
> 
> ```java
> @Service
> @Validated
> public class ValidateService {
>     public MyDtoToValidate springValidation(@Valid final MyDtoToValidate myDtoToValidate) {
>         return myDtoToValidate;
>     }
> }
> ```
> 
> Controller:
> 
> ```java
> // Autowire this.validateService
>    @GetMapping(value = "")
>    @PreAuthorize("hasAuthority('SOME_RIGHT')")
>     public void exampleEndpoint(@RequestBody final MyDtoToValid dto) {
>          this.validationService.springValidation(dto);
> 
>          // do stuff
>     }
> ```
> 
> I write a own springValidation method for each dto. That works in java.

This solution adds code and complicates things unlike the one I propose. The disadvantage is that there are role checks in two different places (in the controllers and in this file), but I think it's still better than adding an extra layer that adds maintenance.

**Comment by Tockra** [comment]
> two different places (in the controllers and in this file), but I think it's still better than adding an extra layer that adds maintenance.

I don't know. There is no further complex functionality. There is just one additional class and one simple method for each dto. It seems to be manageable. 
You need to add a seperate line in the controller method and a method, which has no functionality, but causes the @Valid check after the authorization check in the controller method. This is a small bunch of additional work, but fits better in our roles and rights concept than moving the check to the Security class.

**Comment by rstoyanchev** [comment]
**Team Discussion:** we don't necessarily see the order in which these are applied as incorrect, with security applied first as an external concern and operating on the actual inputs, while validation through parameter annotations is more part of the method implementation.

That said, `BeanPostProcessor`s are ordered, and if you wanted to, you could try and set the order on the `MethodValidationPostProcessor`. Another alternative is to place security annotations could also be places on the service layer and have that invoked from the controller, with already validated inputs.

Keep in mind also that the current behavior, with the use of a bean post-processor and an AOP proxy for validation, is a result of an implementation detail since it's the only way to validate `@RequestParam` and `@PathVariable` arguments currently. In #24913 intend to make bean validation a first-class feature of Spring MVC and WebFlux, at which point will become more integrated with the controller method and come strictly after any AOP proxies like the security check.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
