### ISSUE TITLE
@MessageMapping is not registered when bean is created by hand

### ISSUE THREAD

**Issue by delor** [spring-projects/spring-framework#27458]
**Affects:** 5.3.9

I was messing with RSocket and have noticed that if I created bean with `@MessageMapping` with `@Bean` in `@Configuration` it wasn't registered but it works just fine if I add `@Controller` and let component scan create it.

I think both ways should work the same way.

**Comment by snicoll** [comment]
@delor thanks for the suggestion but adding `MessageMapping` to a factory method (the `@Bean` method) does not make much sense as it's not the target method for the mapping.
