### ISSUE TITLE
ConfigurationClassUtils#checkConfigurationClassCandidate judgment logic question

### ISSUE THREAD

**Issue by biuabiu** [spring-projects/spring-framework#27489]
in Spring Framework 5.2+,about checkConfigurationClassCandidate  i have a quetion for judgment,
[checkConfigurationClassCandidate ](https://github.com/spring-projects/spring-framework/blob/ac5dc698e2f0f6f758983f1af3039eea627ef54d/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassUtils.java#L125-L130)
 use true replace non-false more reasonable? It looks more concise

**Comment by snicoll** [comment]
@biuabiu the current code looks fine to me and the intent is to explicitly check that the value is not `false`.
