### ISSUE TITLE
Redirected calls should filter out bearer tokens

### ISSUE THREAD

**Issue by pasi-paasiala** [spring-projects/spring-framework#27500]
**Affects:** 5.3.10

When a call is redirected to AWS, the following message is given:
```
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Bearer 89QdsFtUXcgUKuMOgOVeCB</ArgumentValue><RequestId>XFJWT7AF8Q87Q5JC</RequestId><HostId>jofrQNGeH1bj2v5KrmcD0BBlqpy78iXk0D80Q1sI6oBl4TUXvFIzbV138t0V7Ua2T4Ms555aWuk=</HostId></Error>
```
---

The reason for this is that the original call is using a bearer token and when the call is redirected to AWS, the header with the bearer token gets copied.

**Comment by pasi-paasiala** [comment]
This seems to  be done in the [Apache client](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/execchain/RedirectExec.java#L128).
Don't know if updating to the latest client would make any difference here.

**Comment by bclozel** [comment]
Spring Framework has no required dependency on the Apache client.
If you believe this is a bug, could you report this problem to the Apache client project directly?

**Comment by pasi-paasiala** [comment]
> Spring Framework has no required dependency on the Apache client. If you believe this is a bug, could you report this problem to the Apache client project directly?

@bclozel 
[HttpComponentsClietHttpRequest](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L87) seems to use Apache HttpClient.

**Comment by pasi-paasiala** [comment]
I'm not an expert on this. Just debugged that this happens and trying to find my way around this. I agree that it should be improved in the Apache library and was thinking, if the new version of Apache http client already works better. At least, when I looked at the [code](https://github.com/apache/httpcomponents-client/blob/5.1.x/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/RedirectExec.java), it didn't seem to have copying of headers in the new version.

**Comment by bclozel** [comment]
Spring Framework also supports this version. Have you tried upgrading your project?

**Comment by pasi-paasiala** [comment]
According to [this](https://stackoverflow.com/questions/61210545/how-to-set-spring-httpcomponentsclienthttprequestfactory-with-apache-httpcompone), the support doesn't exist. The classpaths differ between Apache http client [4](https://github.com/apache/httpcomponents-client/tree/4.5.x/httpclient/src/main/java/org/apache/http) and [5](https://github.com/apache/httpcomponents-client/tree/5.1.x/httpclient5/src/main), so you cannot switch by just changing the dependency.

Am I missing something?

**Comment by bclozel** [comment]
Right, my bad.
Spring Framework is supporting Apache HttpComponents 5 client, but with `WebClient` using the `HttpComponentsClientHttpConnector`. `RestTemplate` is in maintenance mode these days so we don't add new features to this part of the codebase.
