### ISSUE TITLE
SimpleAsyncTaskExecutor should set thread prefix same way as ThreadPoolTaskExecutor

### ISSUE THREAD

**Issue by dmak** [spring-projects/spring-framework#27508]
I would assume that `SimpleAsyncTaskExecutor` and `ThreadPoolTaskExecutor` behave the same way with respect to thread name prefix initialization, namely, `SimpleAsyncTaskExecutor` should be `BeanNameAware` and set the thread name prefix the same way as implemented in [`ExecutorConfigurationSupport`](https://github.com/spring-projects/spring-framework/blob/d84ca2ba90/spring-context/src/main/java/org/springframework/scheduling/concurrent/ExecutorConfigurationSupport.java#L184).

**Comment by sbrannen** [comment]
As a workaround for having the thread name prefix based implicitly on the bean name, you can invoke the `SimpleAsyncTaskExecutor(String)` constructor.

**Comment by sbrannen** [comment]
Since `SimpleAsyncTaskExecutor` resides in `spring-core` it cannot implement `BeanNameAware` which resides in `spring-beans`.

In light of that, I am closing this issue.
