### ISSUE TITLE
Add annotation to execute MongoDB scripts during integration tests

### ISSUE THREAD

**Issue by sleepo581** [spring-projects/spring-framework#27510]
Hi all. There is a cool annotation [@Sql](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/jdbc/Sql.html), which allows to execute sql script before/after a test.

It may be good to have the same annotation for tests which use MongoDB. 
I'm thinking over a new annotation and a new test execution listener, that will run a MongoDB script before/after test, as `@Sql` annotation does.

For example:

```java
@DataMongoTest
class MovieRepositoryTest {
    
    @Test
    @MongoInsert(scriptLocation = "movie.json", collection = "movies")
    void findById() {
      ....
    }
}
```

movie.json
```json
{
  "_id": {
    "$oid": "573a1390f29313caabcd60e4"
  },
  "genres": [
    "Short",
    "Comedy",
    "Drama"
  ],
  "title": "The immigrant"
}

```

What do you think about it?

**Comment by sbrannen** [comment]
The core Spring Framework does not have support for MongoDB.

However, the [Spring Data MongoDB](https://spring.io/projects/spring-data-mongodb) project provides extensive support for MongoDB in Spring applications.

So perhaps this issue should be moved to that repository.

/cc @odrotbohm, @mp911de

**Comment by mp911de** [comment]
That's an generally interesting idea. I could think of other arrangements in the Data space such as setting up data in Couchbase, Elasicsearch and others. Could we leverage a general mechanism in the Spring Test context to evaluate annotations on test classes/methods from Spring Data?

In any case, let me take this to the data team.

**Comment by snicoll** [comment]
I am going to close this as not related to the core framework.

@sleepo581 if you haven't done so already, please follow-up with the Spring Data project.
