### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Jzow** [spring-projects/spring-framework#27585]
This is not a bug problem. I recently developed a deep learning (CV) example using AWS mxnet and tensorflow. I integrate through springboot 2.5. I don't see any AI framework on spring.io, so my idea is that I can do this through AWS djl and spring boot. I fell this plan is feasible

**Comment by bclozel** [comment]
There is no plan right now for a specific support in Spring Framework or Spring Boot.

You can start by creating your own Spring Boot starter and [get it published on the 3rd party starters page](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-starters#starters) once it's ready for public consumption.

Thanks!
