### ISSUE TITLE
Dependency junit-platform-native and plugin native-maven-plugin not found in Spring Native

### ISSUE THREAD

**Issue by einstein1401** [spring-projects/spring-framework#27626]
Hello,
Project generated by _Spring Initialzr_ including _Spring Native_ dependency has _pom.xml_ file in which _junit-platform-native_ and _native-maven-plugin_ are not found.
![issue_Spring_Native](https://user-images.githubusercontent.com/62645728/139512716-76289796-ed00-4ad5-9144-4461e0d8775b.png)
This happens only when _Spring Native_ is included in the project.
I use Idea IntelliJ as IDE.

**Comment by sbrannen** [comment]
This sounds like an issue for the [Spring Initializr](https://github.com/spring-io/start.spring.io) project.

@bclozel and @snicoll, can one of you transfer this issue?

**Comment by snicoll** [comment]
> can one of you transfer this issue?

We can't as the project is in a different org.

@einstein1401 This is an IDE concern. Before opening an issue like this, please take the time to build the project on the command line to see if that's something to do with the IDE not refreshing its internal model. I am going to close this now but if this project fails on the command line with similar errors, please report this against the project Sam referred.
