### ISSUE TITLE
Hamcrest-free version of `MockMvcResultMatchers`

### ISSUE THREAD

**Issue by soc** [spring-projects/spring-framework#27640]
As documented in the [wiki](https://github.com/spring-projects/spring-framework/wiki/Code-Style#tests), JUnit5 and AssertJ are required to be used, but `MockMvcResultMatchers` drags in Hamcrest, which is an older assertion library.

There should be an alternative/replacement that doesn't drag in a Hamcrest dependency, especially for projects that made efforts to move away from it.

**Comment by snicoll** [comment]
Thanks for the suggestion but that was raised already.

Closing as a duplicate of #21178

**Comment by soc** [comment]
Thank you, @snicoll!
