### ISSUE TITLE
Consistently replace String encoding names with StandardCharset arguments

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#27664]
On a related note to gh-27646, there also `URLEncoder`/`URLDecoder` variants with a `Charset` argument in JDK 10+ now. Also, our `EncodedResource` should consistently be used with `StandardCharsets` arguments instead of String encoding names.

**Comment by dreis2211** [comment]
Please check https://github.com/spring-projects/spring-framework/pull/27554

**Comment by jhoeller** [comment]
Oops, sorry for not noticing your PR before, @dreis2211 ... This consistency commit of mine only really covered a single URLEncoder case but the PR #27646 included some URLDecoder changes as well, next to the toString stuff.

If you could rebase #27554 against current main, we'll see whether we missed anything (possibly in our test sources).

**Comment by dreis2211** [comment]
@jhoeller Done

**Comment by jhoeller** [comment]
@dreis2211 Wow that was quick, thanks for the immediate turnaround!
