### ISSUE TITLE
Use ByteArrayDecoder in DefaultClientResponse::createException

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-framework#27666]
In `DefaultClientResponse::createException`, instead of "converting" the response body into DataBuffers and turning those in a byte array , we should use the `ByteArrayDecoder` which does that in a single step.

**Comment by KimJejun** [comment]
Hi there.

I have a problem on 5.3.13 version.
Can u check this question?

https://stackoverflow.com/questions/70691486/spring-webclient-getresponsebodyasstring-is-emptyover-spring-5-3-13
