### ISSUE TITLE
"assertBeanFactoryActive then use BeanFactory " is not a atomicity operation

### ISSUE THREAD

**Issue by shenjianeng** [spring-projects/spring-framework#27677]
sorry , my english is poor。

I came across a scene

| thread-1                                        | Thread-2       |
| ---------------------------------------------------- | -------------- |
| assertBeanFactoryActive                              |                |
|                                                      | close  context |
| getBeanFactory().getBean(name);  (create bean again) |                |

**Comment by snicoll** [comment]
You haven't shared the version that you're using, nor what specific problem you've faced. I am sorry this got overlooked but there's not much we can do based on this description.
