### ISSUE TITLE
Early removal of 5.x-deprecated code

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#27686]
Removing deprecated code in the `5.x` generation early in the 6.x milestone will give a chance to early adopters to adapt or raise concerns during their migration.

**Comment by jhoeller** [comment]
I've narrowed this issue to early removal of long-deprecated code for 6.0 M1. With a first local pass, there's plenty to remove there already. I intend to leave most 5.3.x and 5.2.x deprecations in place for the time being, except for some recent rather internal deprecations.
