### ISSUE TITLE
Update javadoc and reference docs for consistent version and package references to the Jakarta EE 9 APIs

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#27689]
The javadoc for `WebApplicationInitializer` and `SpringServletContainerInitializer ` references Servlet 3.0 in a few places. It should be Servlet 5 now.

**Comment by jhoeller** [comment]
Along with #27692, I'm also updating other EE doc references for Jakarta EE 9 package names (extending the scope of this issue).
