### ISSUE TITLE
Move Spring Boot's JsonParser utility over to Spring Core

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-framework#27694]
Spring Boot has a `JsonParser` that can be used for "quick-and-dirty" conversion from String to `Map`, e.g. for configuration data that comes in as JSON. I find it very useful and it seems like it would fit better in Framework as a very low-level utility. If we don't want the optional dependencies for the JSON libraries we could at least add the abstraction and the JDK-only implementation for lightweight parsing.

**Comment by rstoyanchev** [comment]
Utilities in the spring-core are for use in the Spring Framework and this would not be the case. The dependencies in spring-core are certainly not meant to be expansive and something like this opens the door for more such dependencies.

**Comment by rstoyanchev** [comment]
*Team Decision:* we'll keep it in Boot. A major reason to use the parser in Boot is for its testing support. The Boot team would like to retain control of it. From a framework perspective we're not keen on an abstraction with no major use cases.
