### ISSUE TITLE
Enable a properties journal

### ISSUE THREAD

**Issue by tomasbjerre** [spring-projects/spring-framework#27711]
# Problem

I have multiple applications running within same environment. They share some property files.

It is hard to figure out what properties are actually being used by each application. Not only what properties are available.

# Proposed solution

Enable a properties journal. Something that:

 * Prints all used properties on startup.
 * Allow users to configure a callback whenever a property is read.

This would allow note all used properties, in something like InfluxDB or whatever.

I have implemented this by listening for beans being created, using reflection to find usage of `@Value`, resolving values of those annotations... but would be nice if this was a feature in Spring.

**Comment by snicoll** [comment]
Thanks for the suggestion but such high-level, application-related,  feature belongs more in Spring Boot. This was raised before, see https://github.com/spring-projects/spring-boot/issues/11278 and the linked issues.
