### ISSUE TITLE
Property values not properly loaded when method is annotated @ConditionalOnExpression

### ISSUE THREAD

**Issue by vvijayv** [spring-projects/spring-framework#27718]
**Affects:** 2.5.4

Not all the properties are loaded when the bean is loaded based on the condition present in the configuration. Without the condition the values are loaded correctly.

       ```
	@Bean
	@ConditionalOnExpression("#{appProperties.approach2 eq false}")
	public String approch2(AppProperties properties) {
		System.out.println(properties.message); //prints null
		System.out.println(properties.degree); //prints 0
		return "";
	}
```

application.properties
```
application.message="some message"
application.degree=5
application.approach1=true
application.approach2=false
```
---

**Comment by jhoeller** [comment]
Bringing `BeanPostProcessorChecker` forward would mean bringing the `BeanPostProcessor` bean type retrieval forward, and that's a tough pill to swallow. From that perspective, I don't see us improving the warning situation here; we'll have to rely on documentation.
