### ISSUE TITLE
DataAccessUtils result accessors with Optional return value

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#27728]
Related to #724, `DataAccessUtils` should provide an `optionalResult` method for `Collection` as well as `Stream` arguments (and also for `Iterator` because we need that internally anyway), returning a corresponding `Optional` wrapper or `Optional.empty()`.

In addition, a `singleResult` overload for a `Stream` argument (and for `Iterator`) would complete the overall arrangement in `DataAccessUtils`.

**Comment by rstoyanchev** [comment]
Superseded by #27735.
