### ISSUE TITLE
ApplicationEvent#getSource does not need to be guarded against a null source

### ISSUE THREAD

**Issue by liaozan** [spring-projects/spring-framework#27745]
SmartApplicationListener getSource should Never be null，ApplicationEvent is extend from EventObject
source is set by Constructor
![image](https://user-images.githubusercontent.com/26990889/143799797-a173a7fc-8d43-4537-9a63-f0099c815334.png)

**Comment by snicoll** [comment]
@liaozan sharing screenshot like this isn't very helpful I am afraid. What `getSource` method are you talking about? There [isn't one](https://github.com/spring-projects/spring-framework/blob/ef696c787b3e9959b2aaa3c671c0647c76ae4b53/spring-context/src/main/java/org/springframework/context/event/SmartApplicationListener.java#L36) on `SmartApplicationListener`.

**Comment by liaozan** [comment]
sorry about sharing screenshot.
getSource is not directly present on `SmartApplicationListener`, It is used as a `supportsSourceType` method on `SmartApplicationListener ` and it annoted with `Nullable`, but I looked at the code and found that source comes from EventObject, and it will never be Null because he made a judgment in the construction method.
```java               
protected Collection<ApplicationListener<?>> getApplicationListeners(
                  ApplicationEvent event, ResolvableType eventType) {

    Object source = event.getSource();
    Class<?> sourceType = (source != null ? source.getClass() : null);
    ListenerCacheKey cacheKey = new ListenerCacheKey(eventType, sourceType);
    // other code
    return retrieveApplicationListeners(eventType, sourceType, newRetriever);
}
```

**Comment by snicoll** [comment]
Those are actually two different things. The code above is from `AbstractApplicationEventMulticaster` and the call on `getClass` could indeed be simplified but the `supportsSourceType` is disconnected from that and it is intentional that we want it to be nullable. I'll use this issue to simplify the code in `AbstractApplicationEventMulticaster`.

**Comment by jhoeller** [comment]
It's worth noting that the `getSource()` method may be overridden in custom `ApplicationEvent` subclasses, potentially returning `null`. Not that this is advisable but it may still happen for certain user event instances. This might be reason enough to keep the defensive check there.

**Comment by snicoll** [comment]
Ah, good point. Let's keep things as they are then.
