### ISSUE TITLE
Allow @Async qualifier to be declared with a placeholder or SpEL expression

### ISSUE THREAD

**Issue by LovelyJiuJiu** [spring-projects/spring-framework#27775]
`@Async` value attribute cannot be resolved if it is set to a placeholder, such as `@Async("${thread-pool.name}")`.

**Comment by sbrannen** [comment]
It looks like we could support this via the `EmbeddedValueResolver` in `org.springframework.aop.interceptor.AsyncExecutionAspectSupport.findQualifiedExecutor(BeanFactory, String)` if the supplied `BeanFactory` is a `ConfigurableBeanFactory`. See `org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.setBeanFactory(BeanFactory)` for an example.

**Comment by sbrannen** [comment]
Superseded by #27818

**Comment by sbrannen** [comment]
@LovelyJiuJiu, thanks for opening your first issue for the Spring Framework. 👍 

In case you missed it, the feature you requested has been implemented for 6.0. See https://github.com/spring-projects/spring-framework/pull/27818#issuecomment-1046038910.

**Comment by LovelyJiuJiu** [comment]
> @LovelyJiuJiu, thanks for opening your first issue for the Spring Framework. 👍
> 
> In case you missed it, the feature you requested has been implemented for 6.0. See [#27818 (comment)](https://github.com/spring-projects/spring-framework/pull/27818#issuecomment-1046038910).

Thanks for letting me know, let's make Spring family stronger!
