### ISSUE TITLE
Add CacheErrorHandler implementation that logs exceptions rather than rethrowing them

### ISSUE THREAD

**Issue by bananayong** [spring-projects/spring-framework#27788]
Hello.

I would like to suggest that the Spring framework provide another `CacheErrorHandler` Implementation.
Whenever I build a spring application that uses an external cache, I do write a class that implements CacheErrorHandler for just error logging rather than throwing an exception.

Maybe most developers don't want to fail a method invocation when the cache is not available because the original method can return results.

So, If Spring provides another CacheErrorHandler implementation for just logging, will be very convinient.

Thank you!

---

**Comment by Drezir** [comment]
I think that this is why we have `org.springframework.cache.annotation.CachingConfigurer` mechanism. But the implementation could be done, but the question is which logging level to use? Should it be configurable or not?

**Comment by bananayong** [comment]
If logging level is configurable It could be very useful, but I think It's ok just WARN.

**Comment by snicoll** [comment]
Closing in favor of PR #27826  - Thanks @Drezir!
