### ISSUE TITLE
Dead loop init when InitializingBean failed

### ISSUE THREAD

**Issue by hebelala** [spring-projects/spring-framework#27820]
version: 5.3.8
problem/bug: when throw exception with implement InitializingBean, spring always init beans, include failed bean, dead loop.

Be attention, my project have loop dependency bean.

I debug, and track stack trace, I found the problem maybe as follows:

https://github.com/spring-projects/spring-framework/blob/9dc5c9f935dd913440d4e0765952d85288d35a5c/spring-beans/src/main/java/org/springframework/beans/factory/support/BeanDefinitionValueResolver.java#L335 shouldn't renew BeanCreationException when it's UnsatisfiedDependencyException, otherwise cause:

https://github.com/spring-projects/spring-framework/blob/9dc5c9f935dd913440d4e0765952d85288d35a5c/spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractAutowireCapableBeanFactory.java#L1012 will ignore the BeanCreationException and swallow it

**Comment by rstoyanchev** [comment]
Can you provide snippets of code with example configuration or ideally an executable sample?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
