### ISSUE TITLE
Spring PathMatchConfigurer#setUseSuffixPatternMatch method is Deprecated, how to enable it?

### ISSUE THREAD

**Issue by RayBan2012** [spring-projects/spring-framework#27838]
**Affects:** \<Spring Framework version>

---

In 5.3.13, Spring PathMatchConfigurer#setUseSuffixPatternMatch method is Deprecated and default to be false, but we need this to be enabled, is there a solution or workaround?

**Comment by bclozel** [comment]
This is being deprecated without replacement. We'll probably drop it in the next major version.

See [the javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/PathMatchConfigurer.html#setUseSuffixPatternMatch-java.lang.Boolean-) and the discussion in #24642.
