### ISSUE TITLE
Support for parsing duration in @Scheduled annotation with the same way as with StringToDurationConverter

### ISSUE THREAD

**Issue by kaifeur** [spring-projects/spring-framework#27841]
`org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor` class parses durations from fields _fixedDelayString_, _fixedRateString_ and _initialDelayString_ with it's own conversion method `org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor#processScheduled`.

How about to use `org.springframework.boot.convert.StringToDurationConverter` (and other converters) to support `org.springframework.boot.convert.DurationStyle#SIMPLE`? It would be great if I can set initial delay (and also other delays) in my `bootstrap.yaml` with something like `10s`.

**Comment by rstoyanchev** [comment]
This is a converter in Spring Boot that we cannot use in the Spring Framework, and it gets the style from a `@DurationFormat` annotation on the target type, which in this case doesn't work because there is only an annotation attribute to work with. In short, I don't think this is feasible.
