### ISSUE TITLE
Why does @Cacheable not support configuring expiration time?

### ISSUE THREAD

**Issue by icankeep** [spring-projects/spring-framework#27851]
hello,
I have some confusion when using `spring-cache`
For example, when I use method's caching, I hope the results can be cached and the cache expires regularly. Now @Cacheable doesn't seem to support it. If I want to do this, I need to write some code. I don't know why doesn't Spring support cache expiration? It would be even better if it could support scheduled refresh, which could help me reduce some development time and avoid introducing other additional dependencies

**Comment by snicoll** [comment]
This is covered in the [reference guide](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-specific-config). The cache abstraction isn't an abstraction on how the cache actually operates, it wouldn't be wise to try to do that anyway. 

If you need expiry on your cache, choose a cache provider that supports this feature and configure it accordingly.
