### ISSUE TITLE
Conditional judgment can be optimized

### ISSUE THREAD

**Issue by 1725636955** [spring-projects/spring-framework#27856]
https://github.com/spring-projects/spring-framework/blob/544e9bb4036965cc4054fba72f2a5690539e44bf/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassUtils.java#L126-L128

Can be optimized

The following code，Optimal condition judgment，Increase readability
`if (config != null && Boolean.TRUE.equals(config.get("proxyBeanMethods"))) {
			beanDef.setAttribute(CONFIGURATION_CLASS_ATTRIBUTE, CONFIGURATION_CLASS_FULL);
}`

**Comment by snicoll** [comment]
@1725636955 thanks but there's no need to create both an issue and a PR as the latter supersedes the former.
