### ISSUE TITLE
Issue with Lookup autowire with generic type

### ISSUE THREAD

**Issue by vgaur** [spring-projects/spring-framework#27880]
Here is my sample code. This was working fine in 5.2 but when I upgraded to 5.3.13 it threw error "org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'UtilBean< DefaultBeanUtil >' available"

`Interface BaseUtil{}
`

```
@Component
Class DefaultBeanUtil implements BaseUtil{
}
```
```
@Component
@Scope(scopeName=ConfigurableBeanFactory.SCOPE_PROTOTYPE)
Class UtilBean<T extends BaseUtil> {
}
```

```
@Component
Class MyBean {
public void doSomething(){
  getUtilBean().doSomething();
}

 @Lookup
  public UtilBean<DefaultBeanUtil> getUtilBean() {
    return null;
  }
}
```

I can also see we have done some changes in here https://github.com/spring-projects/spring-framework/issues/26998

**Comment by kse-music** [comment]
As mentioned in #26998 , the lookup autowire takes into account the generic type of the return type, and none of the UtilBean bean generics in your code is DefaultBeanUtil

**Comment by vgaur** [comment]
I think we should not consider generics. And in the case of [#26998 ](https://github.com/spring-projects/spring-framework/issues/26998) We always have a way to use qualifiers. 

In my sample code It works if I remove generics
```
 @Lookup
  public UtilBean getUtilBean() {
    return null;
  }
```
So essentially in this case we are ignoring it.  I can not define bean of UtilBean of all possible implementation of BaseUtil.

**Comment by snicoll** [comment]
The exception looks legit to me. You're asking to inject a `UtilBean<DefaultBeanUtil>` and none of the bean in your sample matches that signature.
