### ISSUE TITLE
compute mapping size in every loop

### ISSUE THREAD

**Issue by kse-music** [spring-projects/spring-framework#27895]
in TypeMappedAnnotations's process method

<img width="899" alt="69E87538-9E01-4851-A1E1-B57CA90E4F8C" src="https://user-images.githubusercontent.com/33364651/148340314-7353b596-fcc4-4e88-b05c-b100be12b997.png">

**Comment by snicoll** [comment]
Thanks for the report but this method delegates straight to `List#size` so it doesn't do a costly operation. Do you have a benchmark that indicates that this causes a problem?

Also, please refrain from mentioning individual team members going forward.
