### ISSUE TITLE
Upgrade spring-r2dbc's test dependency on the H2 database to 2.0.x

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#27902]
This is a follow up to #27870, since we cannot upgrade `spring-r2dbc`'s test dependency to H2 2.0 until https://github.com/r2dbc/r2dbc-h2/pull/204 is released.

**Comment by DrZ7** [comment]
r2dbc-h2:0.9.0.RELEASE?

**Comment by sbrannen** [comment]
> r2dbc-h2:0.9.0.RELEASE?

Probably so, but we are likely waiting for the next umbrella GA release for R2DBC: https://github.com/r2dbc/r2dbc-bom/milestone/17

**Comment by sbrannen** [comment]
**Update:**

As far as I understand, `r2dbc-h2` 0.8 will continue to only support H2 1.4.x; whereas, `r2dbc-h2` 0.9 will support H2 2.0.x.

**Comment by sbrannen** [comment]
Superseded by #27976 and actually already addressed in `main` in e5af4aa608746faf55ddb96c352f6c95065a9d93.

Thanks, @jhoeller
