### ISSUE TITLE
ResourceHttpRequestHandler with PathPatternParser cannot resolve resources with a jsessionid URL

### ISSUE THREAD

**Issue by bennypi** [spring-projects/spring-framework#27913]
A simple showcase of this error can be found here: https://github.com/bennypi/thymeleaf-and-springboot

## Expected behaviour
The expected behaviour can be seen when changing the spring boot version to 2.5.6. With this version, the linked css 
can be retrieved and the form POST is working.

## Current behaviour
Starting with spring boot version 2.6.0 and still present in 2.6.1, requests with the jsessionid parameter are not processed correctly but lead to errors on the server. A call to a CSS-file with the jsessionid parameter leads to a 404, the form POST request with the jsessionid parameter also leads to a 404. The page starts working again when the page is refreshed in the browser because the browser then sends a cookie with in the request which in turn removes the jsessionid parameter in the links in the HTML.

I am not completely sure if this indeed a bug in spring boot or if thymeleaf must make changes so that it is compatible with spring boot 2.6.0 and newer, but I don't see anything in the release notes that could be a reason for this changed behaviour.

**Comment by philwebb** [comment]
Transferring to the Framework team. Run the sample and do `curl 'http://localhost:8080/css/main.css;jsessionid=27DE19AF0DE98353ECE4958BD868C6C5'` to replicate the problem. It should return the css, instead it 404s

**Comment by rstoyanchev** [comment]
In most places we use `PathPattern` to pattern matching to the input `RequestPath`. The matching uses `PathSegment#valueToMatch()` which returns a decoded path, also cleaned from path parameters. For static resources, however, we use the full path based on `PathContainer#value()`, which is the original, raw path. We might need to expose an additional `PathContainer#valueToMatch()` that returns the path cleaned from path parameters.
