### ISSUE TITLE
Introduce YamlBeanDefinitionReader

### ISSUE THREAD

**Issue by strongfist** [spring-projects/spring-framework#27911]
I would like to add YAML support to the bean definition reader like Kubernetes resource list to upgrade readability of bean definitions.

**Comment by sbrannen** [comment]
I'm afraid that's not enough information.

Can you please explain what issue you wish to address and your proposal for addressing it?

**Comment by strongfist** [comment]
Hi thanks for the comments.
![xml and yaml comparison](https://user-images.githubusercontent.com/71682114/148850041-2e82a26f-9430-478a-9d19-91b951e26bfb.png)
Spring framework supports bean definition of xml document/type  like this beans.xml file.

I would like to have them support yaml like example file beans.yaml
So this yaml code do exactly the same thing like xml one. 
perpose is to give the developer option to define his/her beans in yaml format.
 after this we can use xml and yaml both
This should however don’t effect the original functionality.

**Comment by sbrannen** [comment]
Thanks for explaining your proposal.

At this point in time we are not interested in supporting additional configuration formats such as YAML. In fact, we recently deprecated the [`PropertiesBeanDefinitionReader`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/support/PropertiesBeanDefinitionReader.html).

However, if you would like to implement your own `YamlBeanDefinitionReader`, you can use the `PropertiesBeanDefinitionReader` or the `GroovyBeanDefinitionReader` as inspiration.

In light of that, I am closing this issue.
