### ISSUE TITLE
Cannot read server-sent events without data (a.k.a. heartbeats)

### ISSUE THREAD

**Issue by BvanMunster** [spring-projects/spring-framework#27923]
**Affects:** 5.3.11+
`org.springframework.http.codec.ServerSentEventHttpMessageReader.buildEvent(List<String> lines, ResolvableType valueType, boolean shouldWrap, Map<String, Object> hints)` yields a StringIndexOutOfBoundsException if a line equals "data:", because `line.charAt(5)` is called.
This means that it fails at reading server-sent events that are heartbeats.

**Comment by jhoeller** [comment]
This seems to have been caused by #27098, replacing the previous `substring` call there.
