### ISSUE TITLE
BeanPropertyRowMapper underscoreName prepends redundant underscore when field descriptor begins in uppercase

### ISSUE THREAD

**Issue by patrickabner** [spring-projects/spring-framework#27929]
When pojo contains eMail field and Lombok generates setEMail accessor, then BeanPropertyRowMappers underscoreName is _e_mail, which breaks database integration. Symptom appeared with Spring 5.3 from commit https://github.com/spring-projects/spring-framework/commit/6316a353bb074b118ab71ad89fe60553c4d073c9

**Comment by sbrannen** [comment]
Superseded by PR #27941
