### ISSUE TITLE
Utility classes can be instantiated by its subclasses

### ISSUE THREAD

**Issue by scruel** [spring-projects/spring-framework#27934]
For now, there are many utility classes have the flaw that it can be instantiated by its subclasses.
I've created a pull request #27933 to fix this issue, but you have closed it, and the reason is not acceptable.
I think you should consider it over before make the final decision.
Thanks!

**Comment by bclozel** [comment]
#27933 has been closed and we've explained why. If the team changes its mind we'll reopen it.
In the meantime, please don't create duplicate issues/pull requests as it's not likely to push us to reconsider this.

**Comment by scruel** [comment]
> #27933 has been closed and we've explained why. If the team changes its mind we'll reopen it. In the meantime, please don't create duplicate issues/pull requests as it's not likely to push us to reconsider this.

Ok, I hope you will consider it again, thanks.

**Comment by scruel** [comment]
@bclozel Furthermore, if you think that the `throw` part is the noise and want me remove it, I will do the job.
