### ISSUE TITLE
AspectJ: @PostConstruct method cannot invoke @Cacheable method in another bean

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#27937]
**Affects:** 5.3.10

---
I'm using AspectJ `@EnableCaching(mode = AdviceMode.ASPECTJ)`.

Invoking an `@Cacheable` method from a bean's `@PostConstruct` method doesn't work, because the cache aspect is not initialized. (see [code](https://github.com/spring-projects/spring-framework/blob/316e84f04f3dbec3ea5ab8563cc920fb21f49749/spring-context/src/main/java/org/springframework/cache/interceptor/CacheAspectSupport.java#L339)).

The Cache aspect is a `SmartInitializingSingleton` and is initialized too late, after my bean was already created.

My use case: populate cache at startup, before accepting web requests.

**Comment by sbrannen** [comment]
Hi @cdalexndr,

Did this work for you in a previous version of the Spring Framework?

If so, which version?

**Comment by cdalexndr** [comment]
@sbrannen no, this is my first attempt.

**Comment by cdalexndr** [comment]
Note that if I try to deffer cache population by also making my bean a `SmartInitializingSingleton`, it will still run before the cache aspect is initialized, because during creation of singleton beans. the cache aspect bean has index 243 so it is processed after my bean.
eg. in `DefaultListableBeanFactory.preInstantiateSingletons()`, `beanNames.indexOf("org.springframework.cache.config.internalCacheAspect") == 243`

**Comment by sbrannen** [comment]
> My use case: populate cache at startup, before accepting web requests.

Have you tried implementing an `ApplicationListener` that reacts to the `ContextRefreshedEvent` application event to populate the cache?

**Comment by cdalexndr** [comment]
The `ContextRefreshedEvent` is sent too late, after tomcat server has started.
Tomcat starts at `WebServerStartStopLifecycle.start()`. which is called in `getLifecycleProcessor().onRefresh()` just before the event is published.

**Comment by sbrannen** [comment]
Since you're using Spring Boot, have you tried listening to Boot's `ApplicationStartedEvent`?

**Comment by cdalexndr** [comment]
Same issue with `ApplicationStartedEvent`, it's published after tomcat has started.

**Comment by sbrannen** [comment]
> The `ContextRefreshedEvent` is sent too late, after tomcat server has started. Tomcat starts at `WebServerStartStopLifecycle.start()`. which is called in `getLifecycleProcessor().onRefresh()` just before the event is published. Note that I'm using Spring Boot 2.4.11

Since there is no `ApplicationEvent` that suits your needs, you'll need to implement and register a custom `org.springframework.context.SmartLifecycle` bean that populates your cache in a _phase_ before the [phase of the `WebServerStartStopLifecycle`](https://github.com/spring-projects/spring-boot/blob/964f028f75e6f5471830a3e400c8028265714ba5/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/context/WebServerStartStopLifecycle.java#L60-L62).

Please give that a try and let us know if that solves your issue.

**Comment by cdalexndr** [comment]
This works, but it's only a workaround.
When using `@Cacheable` annotations, the aspect bean should be initialized so that the operation behaves as expected.

**Comment by snicoll** [comment]
The reference documentation [states that](https://docs.spring.io/spring-framework/reference/integration/cache/annotations.html#cache-annotation-enable) that you should not rely on this feature in your initialization code.
