### ISSUE TITLE
Deprecate SpringFactoriesLoader#loadFactoryNames

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#27954]
As seen in #27753, the `SpringFactoriesLoader#loadFactoryNames` (introduced in #15158 ) has been very useful over the years but is too permissive for our AOT and native work. Some existing use cases can use reflection in a way that's not predictable for AOT processors.

Here are three example use cases in Spring Boot:
* the [ConfigDataLoaders](https://github.com/spring-projects/spring-boot/blob/1e4e4f168d3956177d8dc81bdaba964bc54cf1ae/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigDataLoaders.java) are loading `ConfigDataLoader` class names and are calling non-default constructors using a set of dependencies maintained locally
* the [ImportAutoConfigurationImportSelector](https://github.com/spring-projects/spring-boot/blob/1e4e4f168d3956177d8dc81bdaba964bc54cf1ae/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/ImportAutoConfigurationImportSelector.java) is loading auto-configuration class names.
* the [FailureAnalyzers](https://github.com/spring-projects/spring-boot/blob/197203968aaa579e5fa7dac73b90a826fe7c6908/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/diagnostics/FailureAnalyzers.java#L83) is using class names to create objects directly and continue in failure scenarios.

Instead of Strings, the replacement should return a different type that allows for the actual type inspection and a Supplier to get an actual instance. Maybe something similar to `ServiceLoader.Provider`. This proposal will probably not solve the two use cases mentioned above, so we'll need to find proper replacements in Spring Boot or provide new features in Spring Framework to support them.

**Comment by snicoll** [comment]
Actually the related issue doesn't deprecate the method so let's reopen this one.

**Comment by snicoll** [comment]
Moving to the next milestone since  we just introduce the infrastructure and we'd need to give some time for team to use it before deprecating `loadFactoryByNames`.

**Comment by snicoll** [comment]
"Blocked" by #29699

**Comment by snicoll** [comment]
"Blocked" by #29699

**Comment by sbrannen** [comment]
If we deprecate `loadFactoryNames()`, we should keep in mind that it is still actively used in `spring-test` in `AbstractTestContextBootstrapper.getDefaultTestExecutionListenerClassNames()`.

`getDefaultTestExecutionListenerClassNames()` and `getDefaultTestExecutionListenerClasses()` were originally created to support custom exception handling since there was no equivalent of `SpringFactoriesLoader.FailureHandler` at the time.

Unfortunately, both of these methods are `protected`. Thus, a custom subclass of `AbstractTestContextBootstrapper` may rely on them.

**Comment by snicoll** [comment]
Can you please create an issue to get rid of its use? 6.0 is the right time to break this contract if we have to.

**Comment by sbrannen** [comment]
> Can you please create an issue to get rid of its use? 6.0 is the right time to break this contract if we have to.

See:

- #28666

**Comment by sbrannen** [comment]
This issue is no longer blocked by #28666.
