### ISSUE TITLE
Bean 'org.springframework.retry.annotation.RetryConfiguration' not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by mbadziong** [spring-projects/spring-framework#27975]
**Affects:** Spring Boot 2.3.12.RELEASE

---

Given these dependencies:

```groovy
plugins {
	id 'org.springframework.boot' version '2.3.12.RELEASE'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.retry:spring-retry'
	implementation 'org.springframework:spring-aspects'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

```

and having retry mechanism enabled:

```java
@SpringBootApplication
@EnableRetry
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```

I receive 

```
2022-01-25 13:37:51.354  INFO 7056 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration$$EnhancerBySpringCGLIB$$4b28449d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

and **retry mechanism isn't working**. Similar bug has been fixed in `5.2.4` as mentioned [here](https://github.com/spring-projects/spring-framework/issues/24508). I have newer spring-context version `5.2.15.RELEASE` and it still reproduces.

Looks like actuator dependency is in conflict with retry.

**Comment by snicoll** [comment]
@mbadziong Spring Boot has ended its OSS support period so you'd need to upgrade to a supported version first. If that doesn't help, sharing your build is unfortunately nowhere near enough to give you support. Please share a small sample that we can run ourselves. You can do so by attaching a zip to this issue or sharing a link to a GitHub repository.

**Comment by mbadziong** [comment]
[demo.zip](https://github.com/spring-projects/spring-framework/files/7939635/demo.zip)
I've upgraded to spring 2.6.0 and it still occurs. Sample project attached. Thx

**Comment by snicoll** [comment]
Thanks. I believe that `RetryConfiguration` is missing a role infrastructure. I've created https://github.com/spring-projects/spring-retry/issues/262.

In the meantime, you can safely ignore the info log as such low-level bean isn't meant to be pos-tprocessed anyway.
