### ISSUE TITLE
Add GraalVM native JSON configuration generation

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#27991]
As a follow-up of #27829, we need to implement GraalVM native JSON configuration generation for [reflection](https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/#manual-configuration), [JDK proxies](https://www.graalvm.org/22.0/reference-manual/native-image/DynamicProxy/#manual-configuration), [resources](https://www.graalvm.org/22.0/reference-manual/native-image/Resources/) and serialization as one of the possible outputs.

Other use cases could be generating HTML reports for example, so the APIs should be designed for other use cases, GraalVM native JSON configuration generation being just one use case among others.

**Comment by snicoll** [comment]
Superseded by PR #28131
