### ISSUE TITLE
RabbitMQ clustering - multiple TCP connection not working : springBootVersion = '1.5.11.RELEASE'

### ISSUE THREAD

**Issue by sharunthomas** [spring-projects/spring-framework#28003]
**springBootVersion = '1.5.11.RELEASE'**
**spring Version = '4.3.15.RELEASE'**
**Dependencies used for reabbitmq brocker connection :**

```
 compile group: 'io.projectreactor', name: 'reactor-core', version: '2.0.8.RELEASE'
 compile group: 'io.projectreactor', name: 'reactor-net', version: '2.0.8.RELEASE'
 compile group: 'io.netty', name: 'netty-all', version: '4.1.22.Final'
```
I'm using RabbitMQ clustering and adding these nodes address in a round-robin fashion using the below code

  ```
private Reactor2TcpClient<byte[]> createTcpClient() {
        final List<InetSocketAddress> addressList = new ArrayList<>();
        for (String hostnamesWithPort:hostnamesWithPorts) {
            String[] hostNameAndPort = StringUtils.split(hostnamesWithPort,':');  // consider there are 3 nodes added here
            addressList.add(new InetSocketAddress(hostNameAndPort[0], Integer.parseInt(hostNameAndPort[1])));
        }
        final RoundRobinList<InetSocketAddress> addresses = new RoundRobinList<>(addressList);
        Supplier<InetSocketAddress> addressSupplier = new Supplier<InetSocketAddress>() {
            @Override
            public InetSocketAddress get() {
               return addresses.get();
            }
        };
        StompDecoder decoder = new StompDecoder();
        Reactor2StompCodec codec = new Reactor2StompCodec(new StompEncoder(), decoder);
        return new Reactor2TcpClient<>(addressSupplier, codec);
    }
```

**The application works fine and it is connecting to one of the nodes first, but if that node failed the application is not picking another address for connection so the clustering is useless.
Is there anything that I'm missing here?**

**Comment by snicoll** [comment]
@sharunthomas The versions that you are using are EOL so we will need to upgrade first. It is also unclear why you are reporting a RabitMQ clustering issue to the Spring Framework. Please upgrade first and follow-up with a StackOverflow question if necessary.

**Comment by sharunthomas** [comment]
@snicoll This is not a RabbitMQ clustering issue, clustered env is working fine. The issue is in the spring boot app, which means I have provided a list of host and port values of RabblitMQ cluster instead of a single hostname and port. 
 It supposedly should connect to the second node if the first one fails, but what I can see is the app trying to connect to the same host and port after the failure of the first node.
Is it because of the version that I'm using?? is there any associated known issues in StompBrokerRelayMessageHandler related to this??

**Comment by snicoll** [comment]
I didn't mean to say that this was an issue with the server. The code you've shared is not part of the Spring Framework so I can only guess you suspect this is related. As I've indicated, you are using versions that are EOL so I am afraid we can't provide you support until you upgrade if you're still experiencing an issue after doing so.

**Comment by sharunthomas** [comment]
This is the websocket config file where I was using this code

```
public class WebsocketConfig extends AbstractWebSocketMessageBrokerConfigurer{
------
-----
 @Override
    public void configureMessageBroker(MessageBrokerRegistry registry) {
  ---- 
StompBrokerRelayRegistration messageBrokerRegistry = registry.enableStompBrokerRelay()


}




```

**Comment by snicoll** [comment]
@sharunthomas I think I made it clear what support we can provide to you. Please respect our time and I also invite you to review [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), where  we states we prefer to use GitHub issues only for bugs and enhancements.
