### ISSUE TITLE
`PatternMappingFilterProxy#addUrlPattern` not support `*` url pattern

### ISSUE THREAD

**Issue by Deycoesr** [spring-projects/spring-framework#28017]
**Affects:** 5.4.15

---
Does not work in MockMvc when `FilterRegistrationBean` url pattern is `*`.

See [demo](https://github.com/Deycoesr/SPR28017)

**Comment by bclozel** [comment]
Looking at [PatternMappingFilterProxy](https://github.com/spring-projects/spring-framework/blob/a0c97e4c36e5e07bc13bab4409ec740332a57871/spring-test/src/main/java/org/springframework/test/web/servlet/setup/PatternMappingFilterProxy.java), it seems that valid patterns are one of:
* prefix matching like `/*`, `/prefix/*`
* suffix matching like `/some/*.html`
* strict matching like `/sample`

In your case, does `/*` work in your sample application?

**Comment by Deycoesr** [comment]
`/*` can work

**Comment by Deycoesr** [comment]
Tomcat filter support url pattern `*`, see [FilterMap.java#L134](https://github.com/apache/tomcat/blob/7a33227760aa64dd50f2784923b9f0c849975d68/java/org/apache/tomcat/util/descriptor/web/FilterMap.java#L134).  
But [PatternMappingFilterProxy](https://github.com/spring-projects/spring-framework/blob/a0c97e4c36e5e07bc13bab4409ec740332a57871/spring-test/src/main/java/org/springframework/test/web/servlet/setup/PatternMappingFilterProxy.java) not support `*`

**Comment by bclozel** [comment]
I guess it would be nice to enhance a bit the Javadoc of this class. This is really replicating the behavior with Servlet mappings in general (see Servlet spec, "Specification of Mappings" section 12.2). In this case, `"*"` is treated as an exact match.

I'm not sure we should copy Tomcat's behavior here as it's not consistent with Servlet mapping in general - even though changing the behavior here is unlikely to break existing applications.

**Comment by a364176773** [comment]
> I guess it would be nice to enhance a bit the Javadoc of this class. This is really replicating the behavior with Servlet mappings in general (see Servlet spec, "Specification of Mappings" section 12.2). In this case, `"*"` is treated as an exact match.
> 
> I'm not sure we should copy Tomcat's behavior here as it's not consistent with Servlet mapping in general - even though changing the behavior here is unlikely to break existing applications.

I believe most business developers think "*" is equivalent to "/*", can I mention a PR for that?

**Comment by Deycoesr** [comment]
Undertow [ServletPathMatches.java#L264](https://github.com/undertow-io/undertow/blob/327fd4560820150fee4d626b2902dfc2d74f9de4/servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java#L264) also support `"*"`

**Comment by bclozel** [comment]
Closing in favor of #28041
