### ISSUE TITLE
`ArrayToCollectionConverter` should default to `List` if target type is `Collection`

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#28048]
If one asks `ArrayToCollectionConverter` to convert an array to a `Collection` the delegating call to `CollectionFactory` results in a `LinkedHashSet` being used as conversion target.

I think it makes sense to rather default to a `List` based implementation in that particular case, as arrays naturally allow duplicates and retain order and handing a `Collection` as conversion target kind of indicates no preference in whether to retain those semantics or rather drop duplicates.

**Comment by quaff** [comment]
> If one asks `ArrayToCollectionConverter` to convert an array to a `Collection` the delegating call to `CollectionFactory` results in a `LinkedHashMap`being used as conversion target. I think it makes sense to rather default to a `List` based implementation in that particular case, as arrays naturally allow duplicates and retain order and handing a `Collection` as conversion target kind of indicates no preference in whether to retain those semantics or rather drop duplicates.

`LinkedHashMap` should be `LinkedHashSet` here.
