### ISSUE TITLE
Introduce landing page for JavaDoc and KDoc

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#28055]
## Overview

Spring Framework's Kotlin API documentation is not discoverable via https://spring.io/projects/spring-framework#learn.

The `API Doc.` link points to the [JavaDoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/), and there is no way to navigate to the KDoc unless you follow one of the links buried in the reference manual.

## Deliverables

- [ ] Introduce a new HTML "landing page" for the API docs that provides links to the [JavaDoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/) and [KDocs](https://docs.spring.io/spring-framework/docs/current/kdoc-api/).
   - For example, this could be a new `api/index.html` file so that `/api` would be the link for the landing page.
- [ ] Update spring.io so that the `API Doc.` links point to the new landing page.
- [ ] Ensure that the landing page is included in the ZIP distribution that gets unzipped on the spring.io server.

**Comment by simonbasle** [comment]
Superseded by gh-31587
