### ISSUE TITLE
Expose MvcResult in WebTestClient

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-framework#28051]
It would be great to access the `MvcResult` in the `WebTestClient` validation flow.

Currently, if you want to validate eg. the exception message and type, you have to:

```java
webTestClient.post()
        ...
	.expectBody()
	.consumeWith(rsp -> {
             MvcResult mvc = ((MvcResult) rsp.getMockServerResult());
             assertEquals("expected message", mvc.getResolvedException().getMessage());
             assertTrue(mvc.getResolvedException() instanceof MyCustomException);
         });
```

It would be great if that could just be integrated and asserted inside the builder flow, if possible?

**Comment by bclozel** [comment]
I think you're looking for `MockMvcWebTestClient#resultActionsFor`:

```
FluxExchangeResult<Person> result = webTestClient.post().uri("/people/123")
				.exchange().returnResult(Person.class);

MockMvcWebTestClient.resultActionsFor(result).andExpect(mvcResult -> 
				assertThat(mvcResult.getResolvedException()).hasMessageContaining("expected message").isInstanceOf(MyCustomException.class));
```

Does this work?

**Comment by membersound** [comment]
While this might work, it would still be better if you could write `mvcResult` assertions directly in the `WebTestClient` builder method flow, like `.exchange().expect(mvcResult -> assertThat(mvcResult.getResolvedException()).hasMessageContaining("expected message").isInstanceOf(MyCustomException.class));`

**Comment by bclozel** [comment]
`MockMvcWebTestClient` transitively imports spring-webmvc classes, whereas `WebTestClient` has been designed initially for WebFlux usage. Implementing your suggestion would make Spring MVC a requirement here. This is not a change we want to introduce.

I'm closing this issue as a result.

**Comment by membersound** [comment]
Then the docs are a bit mislead, as they pretend that `WebTestClient` is a direct replacement for `MockMvc`:
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.with-mock-environment

**Comment by bclozel** [comment]
`WebTestClient` is focusing mainly on HTTP messages. To me, this sentence means that you can use the same client for mock and live server integration tests. `MockMvcWebTestClient` provides a lot of additional features, but `MockMvc` is definitely not deprecated, so keeping it in your test suite is perfectly fine.

**Comment by membersound** [comment]
I can confirm that `.resultActionsFor()` is sufficient to support some validation actions on MockMvc that are not possible inside the WebTestClient builder flow.
