### ISSUE TITLE
Controlling flashmap from a ModelAndView

### ISSUE THREAD

**Issue by sijskes** [spring-projects/spring-framework#28069]
Currently (Spring Boot2.6.2) it is not possible to add flashmap attributes to a `ModelAndView`.

In the `ModelAndView` constructor, the flash attributes from a `RedirectAttributesModelMap` are not merged into the regular `ModelMap` contained in `ModelAndView`. 

The test in `RequestMappingHandlerAdapter.getModelAndView` for `RedirectAttributes` fails, because the `ModelAndView` reads the attributes from the `RedirectAttributesModelMap` and merges them into the already existing `ModelMap` in `ModelAndView`.

The only way now to cause the `ModelMap` to be an instance of `RedirectAttributes` is by adding a `RedirectAttributes` to the `Controller` method.

What was expected is that the `RedirectAttributesModelMap` was passed to the `ModelAndViewContainer` so it could be picked up by the test in `RequestMappingHandlerAdapter.getModelAndView()`.

If a `RedirectAttributesModelMap` could turn up in `RequestMappingHandlerAdapter.getModelAndView` it would be a beautiful way to create a `View` factory returning a `ModelAndView` (with flash attributes) without having to signal this in the `Controller` method. And providing a clean separation. 

A workaround currently is to fetch the flashmap via `RequestContextUtils`, but that looks like a kludge.

**Comment by rstoyanchev** [comment]
`ModelAndView` is a simple holder of name value pairs and is the basic contract for the `DispatcherServlet` and related strategies like `HandlerAdapter` and `ViewResolver`. Flash attributes is a more opinionated solution that's supported mainly from annotated controllers where you are expected to have `RedirectAttributes` injected. 

I'm not sure what you're proposing from an API perspective, but adding attributes to a `ModelAndView` implies that you're creating it in the controller method. More often we expect the model to be passed into the controller method which can then just return the view name.

**Comment by rstoyanchev** [comment]
There is no intent to block anything to be honest, only some decisions from a number of years ago. Trying to recollect, so previously there was confusion with attributes from the "default" model ending up in redirect URLs (see #11462 and many related issues, both before and follow-ups). A specific goal was to clearly separate redirects from rendering, and encourage never using from the "default" model on redirect which is also a security concern. The reason this relates to flash attributes is they both apply to redirects and need the same approach.

Here you're returning `ModelAndView` and therefore not using the "default" model, but if support for redirect and flash attributes  in ModelAndView would have meant it should also be possible with a split Model and String view (one as input and the other as output, possible in both combinations), but it gets tricky to separate "default" model from non-default model use and moreover `Model` and `ModelMap` aren't even in web modules so can't really add web methods there.

In any case, it's been like this for a long time and not revisited much or discussed so I'm not keen to revisit the current arrangement and add more nuance. FWIW, based on the experience in WebFlux we added the [Rendering](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/result/view/Rendering.html) API which can be created within a controller method like `ModelAndView` and supports a variety of cases. If anything we could add something more along those lines.

I am also wondering if you've considered an approach with passing `RedirectAtributes` into your delegate?

**Comment by rstoyanchev** [comment]
Thanks for the feedback. I've created #28324 to revisit this area in more detail for 6.0.
