### ISSUE TITLE
configurationClasses has no useful data

### ISSUE THREAD

**Issue by Evanhelovex** [spring-projects/spring-framework#28072]
Hi,The beandifinition scanned by componentscan should not be placed in the configurationClasses container, because the loadBeanDefinitions method does not do any processing for this part of the data.

**Comment by Evanhelovex** [comment]
The Title Means ConfigurationClasses has userless data

**Comment by Evanhelovex** [comment]
Sorry about this,It is A suggestion of improvements.
I think the Beandifinition scanned by @Component Scan can be removed from configurationClasses which saves some memory.

**Comment by snicoll** [comment]
Can you please share a benchmark that shows concretely what you're describing? Thanks!

**Comment by Evanhelovex** [comment]
org.springframework.context.annotation.ConfigurationClassParser#processConfigurationClass
before fixing：this.configurationClasses.put(configClass, configClass);
after fixing:
if(configClass.isImported()){
			this.configurationClasses.put(configClass, configClass);
		}

**Comment by Evanhelovex** [comment]
I mean that  BeanDefination scaned by the @compoentScan is already been registered in the beanDefinitionRegistry before added to the configurationclass.

**Comment by snicoll** [comment]
@Evanhelovex I am afraid I don't and this doesn't help me to I am afraid. This is also the reason why I am asking for a benchmark since you're claiming that it would save memory and we need to validate that before considering any change.

**Comment by eagleandsanake** [comment]
I am tested this too, Although the size of metadata is pretty small，useless elements should not be put in the container at any time.

**Comment by snicoll** [comment]
@Evanhelovex I am going to close this now as there is no concrete information that you've provided that makes me think there is a problem and I can't justify spending time figuring out based on the code snippet you've shared.

**Comment by Evanhelovex** [comment]
Well, Stéphane，I'm in a serious attitude, let's explain it with screenshots, it won't break the existing functions through my modification, and it's helpful to read the source code, (org.springframework.context.annotation.ConfigurationClassParser#processConfigurationClass)
![image](https://user-images.githubusercontent.com/34882843/154793374-a07d335e-b9d3-43e3-b08e-587240a8128c.png)
![image](https://user-images.githubusercontent.com/34882843/154793400-32a407d6-8a2e-4388-a492-8cbf128583d2.png)
