### ISSUE TITLE
Missing documentation on WebClient retry functionality

### ISSUE THREAD

**Issue by dan-lind** [spring-projects/spring-framework#28077]
I don't know if I'm looking in the wrong place, but I cannot find a single paragraph [in the WebClient docs](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client) mentioning the retry functionality. 

While there are some examples in the community, I have not been able to find any examples on how to handle retries for `WebClientRequestException` which I believe was introduced 5.3, and related exceptions like `ReadTimeoutException`. 

I have posted [a question related to this on stackoverflow](https://stackoverflow.com/questions/71180105/how-to-retry-on-response-timeout-with-spring-webclient), but I think it's an issue that there are no official docs whatsoever related to retry (unless I'm looking in the wrong place...)

**Comment by snicoll** [comment]
Please don't post the same thing in two places. Give the SO question a chance to get replies and we can follow-up here if necessary.

**Comment by dan-lind** [comment]
I did not post the same thing twice. I posted my question on SO, and created this issue to highlight the fact that there is no official documentation whatsoever on how the WebClient retry mechanism works.

**Comment by snicoll** [comment]
You asked a question 10h ago with no indication whatsoever you are looking for support elsewhere. As I've said, let's give a chance for your question to be processed and we can adapt if necessary.

**Comment by snicoll** [comment]
`retryWhen` is [an operator](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#retryWhen-reactor.util.retry.Retry-)  available, for instance, on `Mono` and is part of Project Reactor so I don't think we should be documenting that here. That said, I think it is worth reconsidering to see at least if there is something we need to double check with regards to `WebClientRequestException`.

WDYT @rstoyanchev?
