### ISSUE TITLE
Let the DispatcherServlet get the HandlerMapping in advance

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#28082]
Currently, ``DispatcherServlet#initHandlerMappings`` is initialized in ``org.springframework.web.servlet.HttpServletBean#init``, But it is already executed in the servlet thread ``http-nio-8081-exec-1``，I hope it can be executed in advance to play the role of preloading，In this way, I can also get ``HandlerMapping`` earlier through ``DispatcherServlet#getHandlerMappings``

for example：DispatcherServlet can impl SmartInitializingSingleton and invoke ``DispatcherServlet#initHandlerMappings`` in method ``SmartInitializingSingleton#afterSingletonsInstantiated``

![image](https://user-images.githubusercontent.com/13413715/154843456-4f0805d6-36ec-4c34-b120-3119719d5381.png)

**Comment by poutsma** [comment]
`initHandlerMappings` is called by [`Servlet::init`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/Servlet.html#init-javax.servlet.ServletConfig-), part of the Servlet environment (i.e. Tomcat). `Servlet::init` is called by the servlet container to indicate to a servlet that the servlet is being placed into service. Before `init` is called, the `ServletConfig` is not yet available, and that's required for the web application context to be instantiated. Therefore, `init` is the earliest possible moment where Spring Framework can safely instantiate beans such as handler mappings.

**Comment by brucelwl** [comment]
but we can get the ``ServletContext`` before ``Servlet::init``
For example, implement the following interfaces:
``javax.servlet.ServletContainerInitializer#onStartup(Set<Class<?>> c, ServletContext ctx)``和``javax.servlet.ServletContextListener#contextInitialized(ServletContextEvent sce)``

**Comment by poutsma** [comment]
What problem are you trying to solve by having the `HandlerMappings` available earlier than `Servlet::init`?

**Comment by brucelwl** [comment]
> What problem are you trying to solve by having the `HandlerMappings` available earlier than `Servlet::init`?

Because I want to intercept the ``handler`` corresponding to the ``httpServletRequest`` through the ``javax.servlet.Filter``, so I can add my own current limit statistics to the ``handler``. Therefore, I must know all ``HandlerMapping``, Coincidentally, I found that all ``HandlerMapping`` will be loaded in ``DispatcherServlet``, and method ``DispatcherServlet#getHandlerMappings`` is also provided, but the initialization time is a little over

**Comment by brucelwl** [comment]
@poutsma Here is my sample code

```
@Component
public class HttpQpsFilter implements Filter, ApplicationContextAware, SmartLifecycle {

    private ApplicationContext context;
    private List<HandlerMapping> handlerMappings;
    private volatile boolean running;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.context = applicationContext;
    }

    /**
     * @see DispatcherServlet#initHandlerMappings(org.springframework.context.ApplicationContext)
     */
    @Override
    public void start() {
        running = true;
        initHandlerMappings();

        initFlowRules();
    }

    private void initHandlerMappings() {
        DispatcherServlet dispatcherServlet = context.getBean(DispatcherServletAutoConfiguration.DEFAULT_DISPATCHER_SERVLET_BEAN_NAME, DispatcherServlet.class);
        handlerMappings = dispatcherServlet.getHandlerMappings();
    }


    private static void initFlowRules() {
        List<FlowRule> rules = new ArrayList<>();
        FlowRule rule = new FlowRule();
        rule.setResource("handlerChain.getHandler().toString()");
        rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
        // Set limit QPS to 20.
        rule.setCount(2);
        rules.add(rule);
        FlowRuleManager.loadRules(rules);
    }

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
        HttpServletRequest request = (HttpServletRequest) servletRequest;
        HandlerExecutionChain handlerChain = getHandler(request);
        if (handlerChain != null) {
            log.info("url {}, handler {}", request.getRequestURI(), handlerChain.getHandler());
        }
        Entry entry = null;
        try {
            entry = SphU.entry("handlerChain.getHandler().toString()");
            
            filterChain.doFilter(servletRequest, servletResponse);
        } catch (BlockException ex) {
            HttpServletResponse response = (HttpServletResponse) servletResponse;
            
            response.addHeader("error", "BlockException:" + ex.getRule());
            response.setStatus(HttpStatus.SERVICE_UNAVAILABLE.value());
            System.out.println("blocked!" + ex);
        } finally {
            if (entry != null) {
                entry.close();
            }
        }

    }


    /**
     * @see DispatcherServlet#getHandler(javax.servlet.http.HttpServletRequest)
     */
    protected HandlerExecutionChain getHandler(HttpServletRequest request) {
        if (this.handlerMappings != null) {
            ServletRequestPathUtils.parseAndCache(request);
            try {
                for (HandlerMapping mapping : this.handlerMappings) {
                    HandlerExecutionChain handler = mapping.getHandler(request);
                    if (handler != null) {
                        return handler;
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        return null;
    }


    @Override
    public void stop() {

    }

    @Override
    public boolean isRunning() {
        return running;
    }
}

```

**Comment by brucelwl** [comment]
> What problem are you trying to solve by having the `HandlerMappings` available earlier than `Servlet::init`?

In addition, loading ``HandlerMapping `` in advance can warm up, instead of initializing the ``HandlerMapping`` after the user request arrives, because it is locked in the servlet thread ``http-nio-8081-exec-xxx``, so the first request will be slow

**Comment by brucelwl** [comment]
> What problem are you trying to solve by having the `HandlerMappings` available earlier than `Servlet::init`?

In addition, loading ``HandlerMapping `` in advance can warm up, instead of initializing the ``HandlerMapping`` after the user request arrives, because it is locked in the servlet thread ``http-nio-8081-exec-xxx``, so the first request will be slow

**Comment by poutsma** [comment]
Looking at the code you shared, I think you're running into problems because your component is dependant on the Servlet lifecycle as well as the Spring lifecycle.

So, instead of implementing a Servlet `Filter`, you should consider implementing `org.springframework.web.servlet.HandlerInterceptor`, as [handler interceptor are Spring components](https://www.baeldung.com/spring-mvc-handlerinterceptor) that live in the Spring lifecycle. Then, you can simply detect the handler mappings in your `ApplicationContextAware::setApplicationContext` implementation, which will be called before your `HandlerInterceptor` method implementations. I would also not implement `SmartLifecycle`, as all the initialization you need can be done in `setApplicationContext`.

As for the suggestion made in your original comment: `DispatcherServlet` is a Servlet that is instantiated by the web container (i.e. Tomcat). `DispatcherServlet` is not a Spring Bean, and therefore implementing `SmartInitializingSingleton` will not work.

As for implementing `ServletContainerInitializer`: I don't think that's going to help either, because Filters are executed (and initialized) before Servlets are, so you will most likely face the same problem of the servlet not being initialized yet. By implementing a handler interceptor as I suggested above, you are part of the same lifecycle of the `DispatcherServlet` that you're trying to query, so that seems the best way forward.
