### ISSUE TITLE
spring.main.allow-circular-references property does not effect in case of reading from Spring Cloud Config Server

### ISSUE THREAD

**Issue by vaclav-doubek** [spring-projects/spring-framework#28099]
The property **spring.main.allow-circular-references** work correctly when it's located directly to local application files as bootstrap.yaml or application.yaml(+profiles etc.) but don't work if it's obtained from **Spring Cloud Config Server**.
Affected versions:

- Spring Boot: **2.6.3**

- Spring Cloud: **2021.0.1** 

Test Spring Cloud Config client application:
https://github.com/vaclav-doubek/spring-config-client-test
Setup of Spring Cloud Config Server is needed.

The value is correctly readed regardless of Spring Cloud Config Server version.

When I check the value of spring.main.allow-circular-references property I got the expected value i.e. value from local files as well as Spring Cloud Config Server. But in case of Spring Cloud Config Server the application fail to start due to circular reference.

Expected behaviour is the Spring use the value of property spring.main.allow-circular-references for setup application context independently on the way of getting it.

**Comment by rstoyanchev** [comment]
This is the Spring Framework project. Spring Cloud projects are under a different Github org, and the issue tracker you want is probably https://github.com/spring-cloud/spring-cloud-config.
