### ISSUE TITLE
spring-core 5.3.16 Unknown class appears

### ISSUE THREAD

**Issue by livk-cloud** [spring-projects/spring-framework#28106]
org.springframework.cglib.beans.BeanMap.Generator#generateClass
as the picture shows
![image](https://user-images.githubusercontent.com/50291874/155638503-9dd07858-d072-43aa-969e-81f2a96aa4c0.png)
@spring-projects-issues

**Comment by snicoll** [comment]
`BeanMapEmitter` is not new and this issue tracker is not meant to address IDE misconfiguration you may have. If you can reproduce a problem on the command line using Maven or Gradle, please share a sample and we can reopen.

**Comment by livk-cloud** [comment]
![image](https://user-images.githubusercontent.com/50291874/155674377-4ea227aa-5ec7-46f5-bfd2-c58f3b7ff8f5.png)
![image](https://user-images.githubusercontent.com/50291874/155674404-470932a1-c5ba-4c8c-9b7c-fafd472ba30b.png)
I checked version 5.3.16 on github and found the same problem

![image](https://user-images.githubusercontent.com/50291874/155674966-20f9070e-0a72-4bdf-a38c-47d89fdea53f.png)
and I also tried using
