### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/cglib/beans/BeanMapEmitter

### ISSUE THREAD

**Issue by murainwood** [spring-projects/spring-framework#28110]
**Affects:** \<Spring Framework version>

---

Hi:
After we upgrade to spring boot 2.5.10 (spring-core 5.3.16), when invoke following method

`org.springframework.cglib.beans.BeanMap.create(BeanMap.java:68)`

got the the exception

`java.lang.NoClassDefFoundError: org/springframework/cglib/beans/BeanMapEmitter`

Checking the jar of spring-core-5.3.16, seems the class BeanMapEmitter was miss

**Comment by bclozel** [comment]
This looks related to #27802. I'm not sure why `BeanMap` is referring to the now excluded `BeanMapEmitter` type.

**Comment by jhoeller** [comment]
This seems like an accidental exclude of `BeanMap*` over just `BeanMap`. Sorry for the oversight, I'll fix this for 5.3.17.

**Comment by murainwood** [comment]
@jhoeller Wow,  thanks a lot!
So, I'm keeping springboot 2.5.9 (with spring core 5.3.15) now
