### ISSUE TITLE
`ReflectUtils#getBeanProperties` does not support chained setter methods

### ISSUE THREAD

**Issue by Deycoesr** [spring-projects/spring-framework#28118]
**Affects:** 5.3.16

---
```java
public class TestBean {

    private String name;

    public String getName() {
        return name;
    }

    public TestBean setName(String name) {
        this.name = name;
        return this;
    }

    public static void main(String[] args) {
        PropertyDescriptor[] beanProperties = ReflectUtils.getBeanProperties(TestBean.class);
        for (PropertyDescriptor beanProperty : beanProperties) {
            if (Objects.equals(beanProperty.getName(), "name")) {
                Method writeMethod = beanProperty.getWriteMethod();
                System.out.println("writeMethod = " + writeMethod);
            }
        }
    }
}
```
result:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/33995808/156155314-26be560c-4f0c-4a17-9a5a-3f19e35f7fa6.png">

**Comment by Deycoesr** [comment]
`BeanMap` also have this problem

```java
public class TestBean {

    private String name;

    public String getName() {
        return name;
    }

    public TestBean setName(String name) {
        this.name = name;
        return this;
    }

    public static void main(String[] args) {
        BeanMap beanMap = BeanMap.create(new TestBean());
        beanMap.put("name", "asd");
        System.out.println("beanMap = " + beanMap);
    }
}
```

result:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/33995808/156157566-51214760-1ebc-44b3-b0c9-a0886ef5344f.png">

**Comment by Deycoesr** [comment]
Can use [ExtendedBeanInfo](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/ExtendedBeanInfo.java) replace here [ReflectUtils.java#L354](https://github.com/spring-projects/spring-framework/blob/27ee9cdcde26e0e2a024c4b48c833ff1f36ed4d5/spring-core/src/main/java/org/springframework/cglib/core/ReflectUtils.java#L354) ?

**Comment by sbrannen** [comment]
> Can use [ExtendedBeanInfo](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/ExtendedBeanInfo.java) replace here [ReflectUtils.java#L354](https://github.com/spring-projects/spring-framework/blob/27ee9cdcde26e0e2a024c4b48c833ff1f36ed4d5/spring-core/src/main/java/org/springframework/cglib/core/ReflectUtils.java#L354) ?

No. `ExtendedBeanInfo` resides in the `spring-beans` module. So it cannot be used in `ReflectUtils` which resides in the `spring-core` module.

In any case, `ReflectUtils` is part of our repackaged CGLIB patch, which is not intended to be used by third parties.

Why are you using this repackaged version of `ReflectUtils` directly?

**Comment by jhoeller** [comment]
As Sam pointed out, `BeanMap` and its supporting classes are part of CGLIB (repackaged into `spring-core`). Standard JavaBeans setter methods need to be declared `void`, and that's what CGLIB is following; we are not going to deviate from that in our CGLIB fork (where we are not making use of CGLIB's `BeanMap` for any Spring features, it's just there because we happen to fully repackage the original CGLIB arrangement). Spring's own beans support is more lenient in that respect, but if you want that, you'll actually have to use Spring's `BeanWrapper`/ `DataBinder`/etc.
