### ISSUE TITLE
Configuring DataBuffer capacity for FilePart PartGenerator

### ISSUE THREAD

**Issue by saad14092** [spring-projects/spring-framework#28121]
**Affects:** \5.3.12

Hello @poutsma,

The problem : 
when generating the `FilePart#content()`, the `PartGenerator`  uses the following code 
```
private Flux<DataBuffer> partContent() {
	return DataBufferUtils
			.readByteChannel(
					() -> Files.newByteChannel(this.file, StandardOpenOption.READ),
					DefaultDataBufferFactory.sharedInstance, 1024)
			.subscribeOn(PartGenerator.this.blockingOperationScheduler);
  }
```

the generated `Flux<DataBuffer>` contains data buffers with a capacity of 1024 bytes. This becomes a performance issue when dealing with big files because the call to `FilePart#transferTo` take a significant amout of time (too many databuffers).
For example, the call to `FilePart#transferTo` for a 90 MB file takes 6.6 seconds with a capacity 1024 bytes. I used ByteBuddy to intercept the call to `DataBufferUtils#readByteChannel` and set the capacity to 32 KB and the operation took 312 milliseconds.

What I propose as an enhancement is to make it possible to configure the bufferSize either (by using properties or `ServerCodecConfigurer`) or at least use the **server.netty.max-chunk-size** as a basis. Other suggestions are also welcome.

Thank you and keep up the awesome work!

PS : I think the provided code has been moved to `DefaultParts` in newer versions of the Framework

**Comment by poutsma** [comment]
As of Spring Framework 5.3.13, we use [`Files.copy`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#copy(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)) in a bounded elastic scheduler, see [here](https://github.com/spring-projects/spring-framework/blob/0c7e0002504f728d3ca3e182406d19ed3c4c9973/spring-web/src/main/java/org/springframework/http/codec/multipart/DefaultParts.java#L312).

Can you check whether you are facing the same performance issue when using the most recent version of Spring Framework?

**Comment by saad14092** [comment]
I've tested using Spring Framework 5.3.13 and the issue is no longer relevant.

Thanks again for your reply !

**Comment by keyzj** [comment]
Hello!

I'm currently on 5.3.17 Spring version and experiencing the same performance issue: on the uploading of the large file (2.3 gb) it's parted into buffers of 1024 size, so it takes ages to upload it.
