### ISSUE TITLE
Broken link to webflux-cors.html in Spring WebFlux documentation

### ISSUE THREAD

**Issue by ikolomiets** [spring-projects/spring-framework#28152]
**Affects:** 5.3.16

---

[Spring WebFlux](https://docs.spring.io/spring-framework/docs/5.3.16/reference/html/web-reactive.html#webflux-filters-cors) documentation on **CORS Filter** has broken link to [webflux-cors.html](https://docs.spring.io/spring-framework/docs/5.3.16/reference/html/webflux-cors.html#webflux-cors-webfilter).

**Comment by sbrannen** [comment]
Thanks for noticing this and bringing it to our attention.

I already fixed it in bc973d70016602e62ce9d8b9f8c712b05e67d69d, and you can see it fixed in the [5.3.17 snapshot](https://docs.spring.io/spring-framework/docs/5.3.17-SNAPSHOT/reference/html/web-reactive.html#webflux-filters-cors) ref docs.
