### ISSUE TITLE
Introduce RuntimeHintsRegistrar

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#28160]
In order to provide the possibility for registering `RuntimeHints`, the proposal is to introduce a `RuntimeHintsRegistrar` abstraction designed to address the same needs than [`BeanFactoryNativeConfigurationProcessor`](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-aot/src/main/java/org/springframework/aot/context/bootstrap/generator/infrastructure/nativex/BeanFactoryNativeConfigurationProcessor.java) and [`BeanNativeConfigurationProcessor`](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-aot/src/main/java/org/springframework/aot/context/bootstrap/generator/infrastructure/nativex/BeanNativeConfigurationProcessor.java) in Spring Native. It could even be used initially to register static hints as done with `@NativeHint` annotations.

```
package org.springframework.beans.factory.hint;

public interface RuntimeHintsRegistrar {

	void registerHints(RuntimeHints hints, ListableBeanFactory beanFactory);

	default void ifPresent(String className, Runnable runnable) {
		if (ClassUtils.isPresent(className, null)) {
			runnable.run();
		}
	}
}
```

The `registerIfPresent` method is designed to provide a more discoverable mechanism to prevent `ClassNotFoundException` errors than inner classes.

Since they are designed to be used only AOT, `spring.factories` is not a good fit here, so implementations could be registered via a `META-INF/spring/org.springframework.beans.factory.hint.RuntimeHintsRegistrar.imports` file with the same format than [`org.springframework.boot.autoconfigure.AutoConfiguration.imports`]( https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports).

**Comment by snicoll** [comment]
> Since they are designed to be used only AOT, spring.factories is not a good fit here

I don't necessarily disagree but it is disruptive to introduce another mechanism for that reason alone. There are many other concepts in the core container that behave differently when AOT is involved. For instance, we could imagine a class-level annotation on the type that provides some opt-in metadata that the transformer can use to ignore transformation of those entries.

I am not huge fan of the `factory.hint` package. Perhaps it is a smell that something named `RuntimeHintsRegistrar` is taking the bean factory as an argument?

cc @philwebb as I know he's been brainstorming on this topic as well.
