### ISSUE TITLE
ProxyExchange discards all incoming request headers when making a request with a body.

### ISSUE THREAD

**Issue by ericyanush** [spring-projects/spring-framework#28168]
**Affects:** spring-cloud-gateway-webflux:3.1.1

---

**Setup**
Define an MVC RestController that accepts a ProxyExchange as an argument to a request handler method, and use the ProxyExchange object to issue a POST request (or any request that contains a body) to an upstream service, using a body created (or manipulated) in the request handler method.

**Expected Behaviour**
The ProxyExchange forwards the original request headers, minus filtered sensitive headers, and Content related headers in the upstream request.

**Observed Behaviour**
The ProxyExchange discards all original incoming headers, appending only the X-Forwarded-For and X-Forwarded-Proto headers. This behaviour is in contrast to the behaviour observed when using a ProxyExchange object to make requests to upstream services  that do not contain bodies (GET, OPTIONS, etc).

**Comment by bclozel** [comment]
I'm sorry I can't transfer this issue across orgs, could you open this issue against [the Spring Cloud Gateway issue tracker](https://github.com/spring-cloud/spring-cloud-gateway/issues)?
