### ISSUE TITLE
Need Spring Framwork version as per Compatiblility Matrix 

### ISSUE THREAD

**Issue by pardhukancharla** [spring-projects/spring-framework#28182]
Hi Team, Have one requirement to upgrade Spring Framwork version to compatible with Spring Boot 2.x

But here is my system's software/tool current version.
1. Spring Framework 4.1.5.RELEASE
2. Spring Boot 1.3.8.RELEASE
3. Oracle Java 8
4. IBM WebSphere 8.5.5.9

As part of future Roadmap we need to get rid of WebSphere & Use OpenJDK17 along with Spring Boot 2.x
Can anyone suggest a compatible Spring Framework version that can work for Spring Boot 2.x + OpenJDK 17 + IBM Webspehere 8.5.5.9

**Comment by bclozel** [comment]
Java 17 is supported with the latest Spring Boot 2.5.x and 2.6.x. You should [look at the support timeline for Spring Boot](https://spring.io/projects/spring-boot#support) and choose there accordingly. I'm afraid Spring Framework 5.x [requires Servlet 3.1+, so Websphere 9+](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-50).

**Comment by pardhukancharla** [comment]
Thanks for response @bclozel.
Can you suggest Higher version of Spring Framework(> 4.1.5.RELEASE)  which suits WAS 8.5.5.9 & Spring Boot 2.x

**Comment by bclozel** [comment]
That version doesn't exist I'm afraid. Only 5.x Framework versions are currently supported and Spring Boot is depending on those. See the list of [requirements here](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-50); you'll need to update your deployment stack.
