### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by qianxifu** [spring-projects/spring-framework#28192]
Hi, thank you for reading

my dev environment is spring-framework-5.0.19 , java8.

when i import the project into idea and run build , i got the error 'Could not HEAD 'https://repo.spring.io/libs-
release/io/netty/netty-bom/4.1.39.Final/netty-bom-4.1.39.Final.pom''. how could i resolve this error?

thanks again

**Comment by bclozel** [comment]
This is due to: https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020

Your build configuration should not refer to the "libs-release" artifact repository.
