### ISSUE TITLE
Mono Object wrapped by ResponseEntity cannot be passed correctly by mvc framework

### ISSUE THREAD

**Issue by YuanHao97** [spring-projects/spring-framework#28199]
**Affects:** 5.3.x

---

Please refer to this [disscusion ](https://github.com/spring-projects/spring-boot/issues/30158)for more detailed information.
In function `ResponseBodyEmitterReturnValueHandler.supportsReturnType`, it failed to recognize the correct type when a controller returns an object having a Mono object wrapped by ResponseEntity. However, the parameter `HandlerMethod.ReturnValueMethodParameter` actually has an attribute `returnValue` containing enough information.

I wonder if there's a way taking return value into consideration. I tried to fetch the actual return value at runtime, but the subclass `HandlerMethod.ReturnValueMethodParameter` is protected, so the type cannot be converted from `MethodParameter` to `HandlerMethod.ReturnValueMethodParameter`.

**Comment by rstoyanchev** [comment]
Please, don't create additional issues for existing issues.
