### ISSUE TITLE
Add support for processing test contexts ahead-of-time

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#28204]
## Overview

Now that we can process an application context for AOT optimizations, we'd like to extend that feature by providing support in other parts of the portfolio. One  that we have experimented with in Spring Native is processing the application contexts that the TCF uses for a module so that they are "native-friendly". 

In practice, this would mean introducing something like `TestContextAotProcessor` that builds on top of `ApplicationContextAotProcessor`, pre-processing the test infrastructure for each context identified amongst a set of test classes.

We'd need at least one additional context to provide a "prepared" `GenericApplicationContext` for a `MergedContextConfiguration` as each "bootstrapper" can have its own logic baked in.

## Related Issues

- #28824 
- #28906
- #28205 
- #28825

**Comment by sbrannen** [comment]
Current work on this feature can be viewed in the following feature branch.

- https://github.com/sbrannen/spring-framework/tree/spring-test-aot

As individual aspects of the feature set mature, I incorporate them into the `main` branch.
