### ISSUE TITLE
In the case of code redundancy, package scanning is performed in the spring container...

### ISSUE THREAD

**Issue by AssumeJson** [spring-projects/spring-framework#28206]
org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider
In spring5.3.x, there is code redundancy. During package scanning, when parsing class meta information, when creating a ScannedGenericBeanDefinition object, its constructor has set the source attribute. But after creating it, set it up again。It's still the same in the latest version

**Comment by snicoll** [comment]
It looks like you're trying to report an optimization in the code but it's far from obvious what it could be. In the absence of a concrete problem, I am going to close this.
