### ISSUE TITLE
Conversion Service not able to find Converter in Springframework 5.3.16

### ISSUE THREAD

**Issue by sharma-abhishek2023** [spring-projects/spring-framework#28219]
Below is a converter class I have created in my project, It was working fine in the previous version of the spring framework, and now it is not able to find the converter.
```java
@Component
public class BindingsFromEntityToApi implements Converter<BindingInfoEntity, Binding> {

    private final ObjectMapper om;
    
    public BindingsFromEntityToApi(Jackson2ObjectMapperBuilder objectMapperBuilder) {
        this.om = objectMapperBuilder.build();
    }  
    
    public Binding convert(BindingInfoEntity source) {
       //convert logic
    }
   
}
```
The weird part is in tests it is able to find and do the conversion , but when I start the app and then try to do same operation it is not able to find the converter

**Comment by snicoll** [comment]
Thanks for the report but we can't really help you with the information you've shared. If you want support, please take the time to share a minimal sample that reproduces the problem you've described. You can share it with us as a zip attached to this issue or as a link to a GitHub repository.

**Comment by sharma-abhishek2023** [comment]
@snicoll  The issue was resolved, it turns out because the consumer having Jackson2ObjectMapperBuilder made our Converter not visible to COnversion service, we removed the constructer and made ObjectMapper as a private variable and now it is working, hence closing the ticket, Thanks
