### ISSUE TITLE
@RequestParam with defaultValue of empty string on String parameter gives null but not empty String

### ISSUE THREAD

**Issue by Adamatoma** [spring-projects/spring-framework#28220]
I'm using a @RequestParam on a String parameter, gives `defaultValue = ""`. When I call the api without this parameter, I suppose to get an empty value of String "" but got null in my case.

Example that creates the bug:

```
@GetMapping
public String search(@RequestParam(defaultValue = "") String email) {
    System.out.println("Email should be an empty string if not provided: " + email);
    return email;
}
```
When I call this api with no parameter, I got "null" in my console rather than "" (empty String value).

**Comment by sbrannen** [comment]
What do you mean by “call this API”?

How are you invoking the API?

MockMvc, WebTestClient, …?

**Comment by Adamatoma** [comment]
HI sbrannen,
Thanks for replying! 
I put this part of code into a controller file in a java web spring-boot project as an restful API.
Then use postman to send requeset to invoke this API.

Hope the following code example helpful
`
@RestController
@RequestMapping(value = "/testurl/url", produces = "application/json")
public class emailController {
    @GetMapping
    public String search(@RequestParam(defaultValue = "") String email) {
        System.out.println("Email should be an empty string if not provided: " + email);
        return email;
    }
}
`

**Comment by Adamatoma** [comment]
> What do you mean by “call this API”?
> 
> How are you invoking the API?
> 
> MockMvc, WebTestClient, …?



> What do you mean by “call this API”?
> 
> How are you invoking the API?
> 
> MockMvc, WebTestClient, …?

HI sbrannen,
Thanks for replying! 
I put this part of code into a controller file in a java web spring-boot project as an restful API.
Then use postman to send requeset to invoke this API.

Hope the following code example helpful
```
@RestController
@RequestMapping(value = "/testurl/url", produces = "application/json")
public class emailController {
    @GetMapping
    public String search(@RequestParam(defaultValue = "") String email) {
        System.out.println("Email should be an empty string if not provided: " + email);
        return email;
    }
}
```

**Comment by rstoyanchev** [comment]
I was not able to reproduce the issue. Please provide a sample that reproduces the issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
