### ISSUE TITLE
Small planning suggest - spring-core-5.3.16

### ISSUE THREAD

**Issue by dylan-tao** [spring-projects/spring-framework#28229]
**Affects:** \<spring-core-5.3.16>

Now i need invoke method(org.springframework.util.ReflectionUtils#getDeclaredFields), The method cache is used to precisely cache parsed class instances at application startup, but this method is not public, so I need to write a similar method and the cache can not be managed uniformly. Can you go public with it?  My brother, thanks!

**Comment by snicoll** [comment]
There is `ReflectionUtils#doWithLocalFields` that is public and that you can use for whatever you need.

Please note that the Javadoc of `ReflectionUtils` states that this class is only intended for internal use. As such, updates to it will be done based on our own needs.

**Comment by dylan-tao** [comment]
but i need this method，otherwise there is no point in starting the precache.
