### ISSUE TITLE
request(converters): allow RequestParam conversion from null values.

### ISSUE THREAD

**Issue by codymikol** [spring-projects/spring-framework#28223]
**Affects:**  Spring 5.3. 16 and below

Currently in Spring, there is only one class `Optional<T>` that can be populated by a null value when annotated with @RequestParam in a given RestControllerMapping.

This is allowed because within Spring a private method checks to see if the class of the type Optional and will immediately return an Optional.empty() when a null value is received.

In my case, I would like to use the class Option<T> from the arrow library so I can differentiate between an incoming request to query for null vs a request never being sent.

this allows me to do something like this

@RequestMapping age: Option<Int?>

Where 

`Option.none()` is equivalent to not querying by age
`Option.some(null)` is equivalent to querying for entries where age is null
`Option.some(123)` is equivalent to querying for entries where age is 123

This allows me to dynamically build SQL predicates

In all cases except for Optional however, Spring will throw an exception if the parameter is not passed.

**Comment by rstoyanchev** [comment]
You should be able to register a custom converter for this. That should be checked before the `Optional` check in `TypeConverterDelegate`.

**Comment by codymikol** [comment]
I'll give this a try and report back, thanks!

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
