### ISSUE TITLE
ResponseEntity objects are accumulated in ConcurrentReferenceHashMap

### ISSUE THREAD

**Issue by KangChanSong** [spring-projects/spring-framework#28232]
Affects: 5.2.8

---
> First of all, sorry for my bad english. If you're hard to understand my sentence, please comment

Ive been testing my team's project and monitoring it with `scouter` APM.

And found that "used heap" keeps going high whenever I call an different API .

I debugged and found that `Spring` accumulates `ResponseEntity` in `ConcurrentReferenceHashMap` of `ResolvableType.cache`.

It puts the whole response body of each `ResponseEntity` in `ConcurrentReferenceHashMap` which is static.

I believe that the Spring developers intended it for some reasons but I cannot find any even if I googled a lot.

If It it's an issue , please fix this. 
if it's not, I would very appreciate you for giving me some explanation why `Spring` accumulates the `ResponseEntity` objects 
even if it has a BIG BIG body.

Thank you.
Best Regard.

**Comment by snicoll** [comment]
@KangChanSong the cache that you mention is a cache of resolvable types. `ResolvableType` does not have a link to `ResponseEntity` so I am afraid I don't understand the report. Can you point to the code that you believe is caching `ResponseEntity` objects?

**Comment by KangChanSong** [comment]
This is a stack strace when the object is cached.

        - at ConcurrentReferenceHashMap.put(:271) -> ResponseEntity object is put in it
        -  at ResolvableType.forType(:1441)
        - at ResolvableType.forMethodParameter(:1342) 
        - at ResolvableType.forMethodParameter(:1324)
        - at ResolvableType.forMethodParameter(:1291)
        - at ResponseBodyEmitterReturnValueHandler.supportsReturnType(:117)
        - at HandlerMethodReturnValueHandlerComposite.getReturnValueHandler(:63)
        - at HandlerMethodReturnValueHandlerComposite.supportsReturnType(:57)
        - at RepresentationModelProcessorHandlerMethodReturnValueHandler.supportsReturnType(:88)
        - at HandlerMethodReturnValueHandlerComposite.selectHandler(:92)
        - at HandlerMethodReturnValueHandlerComposite.handleReturnValue(:78)
        - at ServletInvocableHandlerMethod.invokeAndHandle(:123)
        – at RequestMappingHandlerAdapter.invokeHandlerMethod(:878)
        - at RequestMappingHandlerAdapter.handleInternal(:792)
        - at AbstractHandlerMethodAdapter.handle(:87)
        - at DispatcherServlet.doDispatch(:1040) 
        - at DispatcherServlet.doService(:943)
        - at FrameworkServlet.processRequest(:1006)
        - at FrameworkServlet.doGet(:898)
        - at HttpServlet.service(:626)
        - at FrameworkServlet.service(:883)
        - at HttpServlet.service(:733)
        - filter chains skipped....

**Comment by KangChanSong** [comment]
This is a stack trace where `ResponseEntity` object is cached in to `ConcurrentReferenceHashMap`

![스크린샷 2022-03-28 오전 9 21 42](https://user-images.githubusercontent.com/76604142/160307856-054c0610-cbe0-43cf-8180-de14f525c8a2.png)

And another screenshot of a ResponseEntity  object and its information

<img width="789" alt="스크린샷 2022-03-28 오전 9 18 36" src="https://user-images.githubusercontent.com/76604142/160307919-1ec04b0e-9d08-4d8f-9e9d-1cb89dcadb50.png">

**Comment by snicoll** [comment]
I can see that we have a `MethodParameter` implementation, `ReturnValueMethodParameter`, that keeps a reference to the actual return value. Spring HATEOAS seems to be using `ResolvableType#forMethodParameter` passing the actual `MethodParameter` implementation.

If the type is using `MethodParameterTypeProvider` I can see how that could have the side effect of keeping the return value in the cache there.

**Comment by jhoeller** [comment]
Indeed, and `ReturnValueMethodParameter` does not even do anything with the value itself, just obtaining the return value type on demand. Let's change this to a `ReturnTypeMethodParameter` that just holds on to the pre-determined value type.
