### ISSUE TITLE
If request body is missing i want to store null in db

### ISSUE THREAD

**Issue by abdullah7435** [spring-projects/spring-framework#28253]
@PutMapping("/item/categoryId/{srsCustomerId}")
    public ResponseEntity saveOmsFiltersWithCategoryIds(@PathVariable("srsCustomerId") Long srsCustomerId, @RequestBody (required=false) List<Long> omsFilters) {
       if (srsCustomerId != null || omsFilters == null ){
           adminBO.saveOmsFiltersWithCategoryId(srsCustomerId, null);
       }
        try {
            if (srsCustomerId != null || omsFilters != null) {
                adminBO.saveOmsFiltersWithCategoryId(srsCustomerId, omsFilters);
            }
            return ResponseEntity.ok(success());
        } catch (Exception e) {

            log.error("Exception trying to save SrsCustomer and SrsOmsFilterId", e);
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
I have tried above code and it is giving me 500 bad request

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
