### ISSUE TITLE
Where can I check the version comparison of spring framework corresponding to spring boot

### ISSUE THREAD

**Issue by wuaoya** [spring-projects/spring-framework#28259]
**Affects:** \<Spring Framework version>

---

**Comment by wuaoya** [comment]
Where can I check the version comparison of spring framework corresponding to spring boot，thank you.

**Comment by magJ** [comment]
@wuaoya There are a few ways to see which version of spring, a given version of spring-boot depends on.
One way is to use a website like mvnrepository.com, which lets you search and view maven dependency metadata.

Click on your version of spring-boot: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
Then on the artifact page, look at the version of spring-core referenced in the compile dependencies
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/2.6.5
![image](https://user-images.githubusercontent.com/1804354/161032661-426a8d39-ad54-4da3-9887-a7b4f45c76d1.png)

**Comment by wuaoya** [comment]
> @wuaoya There are a few ways to see which version of spring, a given version of spring-boot depends on. One way is to use a website like mvnrepository.com, which lets you search and view maven dependency metadata.
> 
> Click on your version of spring-boot: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot Then on the artifact page, look at the version of spring-core referenced in the compile dependencies https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/2.6.5 ![image](https://user-images.githubusercontent.com/1804354/161032661-426a8d39-ad54-4da3-9887-a7b4f45c76d1.png)

thank you so much.
