### ISSUE TITLE
Document how to configure the cache infrastructure globally

### ISSUE THREAD

**Issue by starriesWEB** [spring-projects/spring-framework#28250]
[@CacheConfig](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-annotations-config)
> An operation-level customization always overrides a customization set on @CacheConfig. Therefore, this gives three levels of customizations for each cache operation:
> 
> + **Globally configured**, available for CacheManager, KeyGenerator.
> 
> + At the class level, using @CacheConfig.
> 
> + At the operation level.

How to do global configuration？

**Comment by snicoll** [comment]
By implementing `CachingConfigurer`. I can see that the reference documentation can be improved there.

**Comment by linghengqian** [comment]
If I understand correctly, this is the same usage as `extends CachingConfigurerSupport` which is outdated on Spring 6. If you search for `CachingConfigurerSupport`, you will get a lot of integration information related to `Ehcache 3`.

**Comment by starriesWEB** [comment]
Because I didn't see it on the official website docs, but it's solved now, thanks

> 通过实施`CachingConfigurer`. 我可以看到可以在那里改进参考文档。
