### ISSUE TITLE
spring-web - Exchange response header values are overridden from the downstream calls

### ISSUE THREAD

**Issue by explorer-fullstack** [spring-projects/spring-framework#28275]
**Affects:** \<5.3.16 & up> (don't have this issue in 5.3.13)

As far as I've tested back, atleast beginning 5.3.16 this issue is occurring. To be specific, observed this issue in both spring-web 5.3.16 & spring-web 5.3.18

Issue Description:
**_Sequence of steps:_**
1. Spring Cloud Gateway(SCG) received the request
2. SCG added set of response headers to the exchange object 
3. SCG makes the downstream call
4. Downstream sets the same exact headers that were set in step#2 but with different values

What should've happened (and this is what happens with spring-web 5.3.13)?
- The response headers added by the downstream gets saved into exchange. If the downstream is setting the same response headers which are already present in the exchange, then the response header values from downstream saved into the "value" array

What's happening (and this is what happens at least beginning spring-web 5.3.16)?
- If the downstream is setting the same response headers which are already present in the exchange, then the response header values are not added to the header "value" object but overrides the response header values that was already set on the exchange prior to making a downstream call

Notes:
I've tested this scenario in different combinations and below are the findings

Springboot 2.5.7 (spring-web: 5.3.13) - No issue
Springboot 2.5.12 with spring-web: 5.3.18 - Issue present
Springboot 2.5.12 with spring-web: 5.3.16 - Issue present
Springboot 2.5.7 (spring-web: 5.3.18/16) - Issue present
Springboot 2.6.4 (spring-web: 5.3.16) - Issue present

Please advise and let me know if you have any questions.

Thanks.

**Comment by spencergibb** [comment]
What version of gateway? We just made a change to merge response headers in https://github.com/spring-cloud/spring-cloud-gateway/pull/2547

**Comment by explorer-fullstack** [comment]
> What version of gateway? We just made a change to merge response headers in [spring-cloud/spring-cloud-gateway#2547](https://github.com/spring-cloud/spring-cloud-gateway/pull/2547)

@spencergibb org.springframework.cloud:spring-cloud-gateway-server:**3.1.1**

Do you know approximately when will you be releasing the general availability version which will include this fix?

**Comment by bclozel** [comment]
It seems this has been solved in Spring Cloud Gateway directly with version 3.1.2.
