### ISSUE TITLE
BOM is missing for 5.3.18

### ISSUE THREAD

**Issue by koraktor** [spring-projects/spring-framework#28270]
The Maven artifact for spring-framework-bom 5.3.18 is missing from Maven Central. This prevents a quick update for projects that rely on the BOM.

See https://search.maven.org/search?q=g:org.springframework%20AND%20a:spring-framework-bom

**Comment by bclozel** [comment]
[The BOM is available on Maven Central](https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.3.18/). A search index (official or unofficial) can take time to catch up with new artifacts. You can raise this issue with the maintainers of the search.maven.org website.
Thanks!
