### ISSUE TITLE
how can i download 5.3.18 jar ?

### ISSUE THREAD

**Issue by manjeetdangi** [spring-projects/spring-framework#28300]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
You can [download JARs from maven central](https://repo1.maven.org/maven2/org/springframework/spring/). You can also get [a full distribution zip (jars, sources, javadoc, etc) from our own repository](https://repo.spring.io/ui/native/release/org/springframework/spring/5.3.18/).
