### ISSUE TITLE
repo.spring.io，The website is not accessible

### ISSUE THREAD

**Issue by renpengben** [spring-projects/spring-framework#28314]
https://repo.spring.io，The website is not accessible。
[ERROR]     Non-resolvable parent POM for com.example:demo:0.0.1-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:3.0.0-M2 from/to spring-milestones (https://repo.spring.io/milestone): Transfer failed for https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-parent/3.0.0-M2/spring-boot-starter-parent-3.0.0-M2.pom 504 Gateway Time-out。

**Comment by keybong** [comment]
same issue
I've never see this before

**Comment by bclozel** [comment]
Duplicates #28313
