### ISSUE TITLE
repo.spring.io is down

### ISSUE THREAD

**Issue by walec51** [spring-projects/spring-framework#28313]
https://repo.spring.io/ returns 504

builds using dependancies from it stopped working

**Comment by sebasira** [comment]
Same here!

**Comment by Ahseo** [comment]
same heree!!!

**Comment by snicoll** [comment]
There is a scheduled maintenance, see https://twitter.com/springops/status/1512176700288761864?s=21&t=Q5gDGGBEcE7vgza7OrdgyA
