### ISSUE TITLE
BeanFactory and BeanRegisty is extends ???

### ISSUE THREAD

**Issue by wangkm1** [spring-projects/spring-framework#28331]
Inheritance is a parent-child relationship. Singletonbeanregistry is an abstraction of registration capability. Beanfactory should have this capability, but beanfactory and beanregisty are not parent-child relationships. Should they be inclusion relationships? Well, but now is abstractbeanfactory extensions factorybeanregistrysupport

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but we prefer to use the issue tracker only for bugs and enhancements. If you have a concrete problem, please describe it and we'll consider it.
