### ISSUE TITLE
Add Coroutines support for `@EventListener`

### ISSUE THREAD

**Issue by rotilho** [spring-projects/spring-framework#28343]
**Affects:** Any

---

Spring introduced first-class support to kotlin and coroutines and while almost everything works flawlessly I really miss the support for coroutines in the `@EventListener`.

I used in the past [spring-kotlin-coroutine ](https://github.com/konrad-kaminski/spring-kotlin-coroutine)however this project is not updated for 3 years so I wonder if such support could be added to core Spring.

**Comment by martinformi** [comment]
It would be really helpful, do you have any working implementation that could replace it for now?

**Comment by hantsy** [comment]
The original [Spring Kotlin Corutines](https://github.com/konrad-kaminski/spring-kotlin-coroutine) has great Kotlin Coroutines support, unfortunately it is discontinued. A lot of features are not support in current Spring framework although Spring has supported Kotlin for years.

I used Kotlin Coroutines/Spring Boot in my project, and I found there are still some problems when using Coroutines in events, cache, schedule/async and Spring Security DSL config. I had to wrap the corourtines codes with a `runBlocking` to use the existing facilities in Spring.

**Comment by sdeleuze** [comment]
Spring supports Coroutines where it support reactive types, and since #21831 supports that use case, we should indeed support this use case.

**Comment by hantsy** [comment]
@sdeleuze I would like get the following cases working in a Spring/Kotlin Coroutines project.

1. Allow a `suspend` `main` fun for the application entry.
2. @EventListener on a `suspend` fun or a fun returns a Kotlin `Flow`.
3. Make cache annotation working on any suspend fun or Flow return type.
4. Make it work in Spring Security Kotlin DSL `http{}`(similar to `route`, there is `coRoute` for coroutines)
5. provides a coroutines versions of CommandLineRunner, ApplicationRunner, ReactiveAuditorAware, ReactiveEntityCallback, etc.

**Comment by hantsy** [comment]
Great to see schedule, cache, event listener to get Reactive/Coroutines support in Spring 6.1.

**Comment by rotilho** [comment]
@sdeleuze awesome work! Super thanks!
