### ISSUE TITLE
NettyHeadersAdapter may  be cause Cors problem 

### ISSUE THREAD

**Issue by scuhzq** [spring-projects/spring-framework#28358]
1、version：
org.springframework:spring-web:jar:5.3.18:compile
org.springframework.cloud:spring-cloud-starter-gateway:jar:3.1.1:compile
2、core case：
NettyRoutingFilter use the：【NettyHeadersAdapter#putAll】but【this.headers::add switch to this.headers::set】
<img width="759" alt="image" src="https://user-images.githubusercontent.com/14883790/164149632-4fdac34e-7e5a-4004-a5c4-cbf271f8874b.png">
<img width="773" alt="image" src="https://user-images.githubusercontent.com/14883790/164149598-0232934d-31b1-4c1a-842e-781cf6ab91df.png">
3、eg：
gateway server：set the Access-Control-Allow-Origin：http://gateway.com
gateway NettyRoutingFilter：return another  Access-Control-Allow-Origin：http://upstream.com
NettyHeadersAdapter#putAll：rewrite the Access-Control-Allow-Origin to：http://upstream.com

**Comment by bclozel** [comment]
This is by design, see #27887
