### ISSUE TITLE
Add an interceptor for Controller

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#28376]
It is hoped that an interceptor can be provided to allow users to do custom processing before and after the methods in the controller, such as recording the request parameter log

**Comment by poutsma** [comment]
Do you mean [HandlerInterceptors](https://www.baeldung.com/spring-mvc-handlerinterceptor)?

**Comment by brucelwl** [comment]
Unfortunately, ``HandlerInterceptor`` can't let me get the request body of ``Content-Type=application/json``. I hope there is an interceptor after spring MVC parses the request parameters

**Comment by Nidhi-Tanwar14** [comment]
The HandlerInterceptor contains three main methods:

prehandle() – called before the execution of the actual handler
postHandle() – called after the handler is executed
afterCompletion() – called after the complete request is finished and the view is generated

Can you please try using the posthandle() method.

**Comment by brucelwl** [comment]
https://github.com/spring-projects/spring-framework/issues/30758
