### ISSUE TITLE
404 occurs when configuring access to local static files, which may be caused by URL transcoding

### ISSUE THREAD

**Issue by Ziyear** [spring-projects/spring-framework#28381]
spring-boot:2.6.7
spring-webmvc:5.3.19

I have configured access to local static resources

```java
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/image1/**").addResourceLocations("file:D:\\Data\\TD\\image1\\");
    }
```

When I request a path: http://localhost:8080/image1/P/test%20simple.jpg Prompt 404 Not Found

Was found during debugging `org.springframework.web.servlet.resource.PathResourceResolver#encodeOrDecodeIfNecessary`

The code here will change the URI to: `P/test%2520simple.jpg`

The code is `org.springframework.web.servlet.resource.PathResourceResolver` on line 157

The `pathToUse` variable becomes `P/test%2520simple.jpg`

**Comment by bclozel** [comment]
Duplicates #27791
