### ISSUE TITLE
FormHttpMessageConverter should not have a dependency on the Jakarta Mail API

### ISSUE THREAD

**Issue by jomastel** [spring-projects/spring-framework#28392]
When working with `multipartCharset` the `FormHttpMessageConverter` uses the `MimeUtility.encodeText` method.
This forces a dependency for sending email inside a HTTP converter. 
In our case, we now need to import `org.springframework.boot:spring-boot-starter-mail` to fix this dependency.

Could an alternative import be used here to avoid such dependencies in the case of `Content-Type` `multipart`? 
We found this issue when using a simple REST API.

**Comment by poutsma** [comment]
The dependency to `MimeUtility` was [introduced in 2014](https://github.com/spring-projects/spring-framework/commit/9be0cf21e5d3537d2415fea5eaea152e7407d45b). In 2016, we [introduced the `Content-Disposition` type](https://github.com/spring-projects/spring-framework/commit/99a8510ace46af9b05b822e7c65f08aae885ca98), with it's own mime encoding logic in `encodeFilename`.

I will drop the call to `MimeUtility.encodeText` in favor of the mechanism in `Content-Disposition` as of 6.0 M4.
