### ISSUE TITLE
Option to toggle off CSRF token as url parameter

### ISSUE THREAD

**Issue by Asskali** [spring-projects/spring-framework#28429]
---

When activating CSRF protection you have the option to send in the token as either a header or a URL parameter.
It should be possible to introduce a toggle that toggles the option of sending in the CSRF token as a URL parameter, and only allows for it as a header.

**Comment by bclozel** [comment]
I think you meant to [open this issue against the Spring Security project](https://github.com/spring-projects/spring-security/).
