### ISSUE TITLE
Scheduled method runs twice when setting cron to run every 59 seconds

### ISSUE THREAD

**Issue by amirnajmi** [spring-projects/spring-framework#28467]
I realized when I set a scheduled method to run every 59 seconds, it runs twice, in the 59th second of its current minute and the first second of the next minute.

The cron that was used: `*/59 * * * * *`

The sample code is so simple but for more clarity: 

```java
@Component
public class LogScheduler {

    Logger logger = LoggerFactory.getLogger(LogScheduler.class);

    @Scheduled(cron = "${scheduler.logging.cron}")
    public void logMessage(){
        logger.info("some info");
    }

}

```

The output: 
```
2022-05-16 01:55:59.006  INFO 61503 --- [   scheduling-1] d.najmi.performantapp.task.LogScheduler  : some info
2022-05-16 01:56:00.004  INFO 61503 --- [   scheduling-1] d.najmi.performantapp.task.LogScheduler  : some info
```

For more information, I am using `Spring web flux(netty) version 2.6.7` on an arm64 machine.

**Comment by poutsma** [comment]
> I realized when I set a scheduled method to run every 59 seconds, it runs twice, in the 59th second of its current minute and the first second of the next minute.
> 
> The cron that was used: `*/59 * * * * *`

This expression means "run every 59 seconds **starting at 0 seconds**". So `0` and then `59` are valid second values. Just like `*/30 * * * * *`  would run at `0` and then `30` seconds. 

If you want an expression that only runs *at* 59 seconds, use `59 * * * * *`

**Comment by hari427** [comment]
Similarly issues observed my cron expression is (0  */30 * * * *). scheduled job every 30 mins.
My job is running 4 time..
Could you please suggest

**Comment by Azbesciak** [comment]
Same for me as hari427. Is there any way to run every 15 min for instance? Just once, so 4 times in one hour (at 0, 15, 30 and 45 - without setting that explicit)
