### ISSUE TITLE
Is it possible to use @Autowired like annotations instead of getBeansWithAnnotation

### ISSUE THREAD

**Issue by sleeprite** [spring-projects/spring-framework#28484]
Is it possible to use @Autowired like annotations instead of getBeansWithAnnotation , if not are there plans to support the feature

![image](https://user-images.githubusercontent.com/96010787/169237615-1d244f1b-bad3-4a47-a2c9-09839583d349.png)

**Comment by snicoll** [comment]
No, it is not possible. We have no plan to support injecting a bean when an annotation is present on it. This does seem a bit at odds with the current by-type and by-name semantic. Thanks for the suggestion in any case.
