### ISSUE TITLE
Add support for programmatically registered beans in AOT

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-projects/spring-framework#28487]
Programmatically registered beans are currently not supported by AOT. It is an important issue for Spring Cloud, as we rely on registering beans in the Bootstrap context. A related [issue](https://github.com/spring-projects-experimental/spring-native/issues/1606) has been created in spring-native, but since it's not going to be addressed within spring-native backlog, I'm opening one here as well.

The issue became apparent after merging [this commit](https://github.com/spring-cloud/spring-cloud-config/pull/2065) intended as a bug fix for [another issue](https://github.com/spring-projects-experimental/spring-native/issues/1516).

Log related to this issue:
```

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method singleTextEncryptorLocator in org.springframework.cloud.config.server.config.EncryptionAutoConfiguration required a single bean, but 2 were found:
	- defaultTextEncryptor: defined in null
	- textEncryptor: a programmatically registered singleton
```

**Comment by snicoll** [comment]
We don’t think the AOT engine will be able to detect these beans specifically but together we might be able to brainstorm other ways of achieving what Spring Cloud wants so that it works with AOT.
