### ISSUE TITLE
spring5.1.x error

### ISSUE THREAD

**Issue by zhouhui99** [spring-projects/spring-framework#28481]
who can help me？ When I compile Spring5.1.x use idea,always this error.
Error:Groovyc: While compiling spring.spring-beans.main: D:\spring\spring-framework-5.1.x\spring-beans\src\main\groovy\org\springframework\beans\factory\groovy\GroovyDynamicElementReader.groovy (系统找不到指定的路径。)

in spring project ,create a new module ,in module used spring-beans ,information above operation prompt

**Comment by bclozel** [comment]
Unfortunately, open source support for the 5.1.x generation has ended.
See https://spring.io/projects/spring-framework#support
