### ISSUE TITLE
Do you consider using annotations to register interceptors

### ISSUE THREAD

**Issue by sleeprite** [spring-projects/spring-framework#28485]
In most scenarios in spring, declarative development is used. Do you consider using annotations to register interceptors, such as

![image](https://user-images.githubusercontent.com/96010787/169226582-18a3f7a2-c66d-4f41-9264-c313c263ee85.png)

**Comment by rstoyanchev** [comment]
This has been considered before, in #9447 for example. It's not something we intend to support.
