### ISSUE TITLE
Spring Boot creates a lot of unused dependencies, resulting in a large deployment file. Is there any solution for this in upcoming releases?

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28509]
**Affects:** \<Spring Framework version>

---

**Comment by snicoll** [comment]
@Nidhi-Tanwar14 please review the guidelines for contributing where it states that we don't use this issue tracker for questions. Spring Boot-related issues are not handled here but in [its dedicated project](https://github.com/spring-projects/spring-boot/). I don't think that "creates a lot of unused dependencies" is accurate.
