### ISSUE TITLE
Add reflection hints for Web controllers

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#28518]
The core framework invokes `@RequestMapping`-annotated methods (`@GetMapping`, etc) using reflection. To run in a native image, we need hints for those. We may also want to infer that return types are going to be serialized, or that input times are going to be mapped from the request.

All this can go away if we generate an optimized code for the router but let's go the hints route for now.

**Comment by snicoll** [comment]
Considering that `MergedAnnotations` is required to automatically handle the creation of the proxy. I wonder if dealing with everything that is method specific can be a good thing. This would be more code but more tailored to what is actually happening in the application.

**Comment by sdeleuze** [comment]
This issue will be focused on reflection hints for controllers and reflection-based serialization of parameters annotated
with `@RequestBody` and return values annotated with `@ResponseBody`. I will create subsequent issues for other use-cases (`HttpEntity`, `@ControllerAdvice`, etc.)
