### ISSUE TITLE
Isn't it too aggressive to announce for the enforcement of java 17 in spring6

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28511]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
We've shared this plan over the last few months [here](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) and [here](https://spring.io/blog/2022/03/28/an-update-on-java-17-adoption). So far the community feedback has been very positive. Please read these blog posts and share your opinion in the comments.

Thanks!
