### ISSUE TITLE
HierarchicalUriComponents::getPort() throws NumberFormatException with invalid port in URI

### ISSUE THREAD

**Issue by Jackson-S** [spring-projects/spring-framework#28521]
**Affects:** 5.3.18

---

`HierarchicalUriComponents::toUri()` throws `java.lang.NumberFormatException` instead of the expected `IllegalStateException` when provided with a URI of the format `https://x.com:string`.

**Comment by sbrannen** [comment]
The underlying issue is that `HierarchicalUriComponents.getPort()` invokes `Integer.parseInt()` which throws the `NumberFormatException`.

Thus, invocations of `getPort()`, `toUri()`, and `toUriString()` are all affected.

**Comment by sbrannen** [comment]
Related Issues:

- #26905
- #27039

**Comment by sbrannen** [comment]
This has been addressed in `5.3.x` and `main`.

@Jackson-S, thanks for submitting your first issue for the Spring Framework! 👍
