### ISSUE TITLE
ApplicationContextAotGenerator should return the initializer class name

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#28525]
`ApplicationContextAotGenerator` doesn't currently return the class name of the generated initializer and it probably should. The method name might also be better as `generateApplicationContextInitializer` since that's what it actually generates.

**Comment by snicoll** [comment]
> ApplicationContextAotGenerator doesn't currently return the class name of the generated initializer and it probably should.

I am confused. Isn't that the third argument of that method?

> The method name might also be better as generateApplicationContextInitializer since that's what it actually generates.

I don't agree with this. This processes the context, kicks of the AOT engine and honors all sort of callbacks that generate everything related to the context. This includes build-time optimizations. From that perspective, even the third argument looks a bit off IMO. I wonder if some sort of report where contributions should state what they've done and potential links to resources could be helpful.

**Comment by philwebb** [comment]
> I am confused. Isn't that the third argument of that method?

I missed that, for some reason I thought it generated the class name directly.
