### ISSUE TITLE
Which version of JBoss eap is the minimum requirement of Spring framework upgrade from 3 to 5 please?

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28537]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
You'll find the Spring Framework 5 requirements [in our wiki](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#baseline-update). Please check that your Servlet container matches here.
