### ISSUE TITLE
OncePerRequestFilter gets hit over and over when batching using a FORWARD

### ISSUE THREAD

**Issue by orubel** [spring-projects/spring-framework#28534]
So as you know, the diff between a FORWARD and REDIRECT is that REDIRECT reissues the request and does a round robin outside the DMZ.

A FORWARD uses the saame REQUEST/RESPONSE to loop internally.

However in testing, I noticed that the 'OncePerRequest' filter keeps gets hit over and over when looping a batch call using a FORWARD.

Thats not 'OncePerRequestFilter' ... thats 'PotentiallySeveralDozenTimesPerRequestFilter' :)

I tested this by Using HTTPClient in my integration tests and outputting the request session id when it was hitting the doFilterInternal() method; it was the same request being used (session had NOT been reissued because request had NOT been dropped and recreated... thus same session, same request)

Is this expected functionality?? Or is this a BUG?

**Comment by orubel** [comment]
You bet. Have a spring-boot starter demoing it : https://github.com/orubel/spring-boot-starter-beapi

The example would be shown through the use of a batch job (as demo'd in the demo-application -> BatchFunctionalTest.groovy)

Request/response call flow is handled through ApiInterceptor and sent to BatchExchangeService where batchresponse() method handles forward:

```
			if(request.getAttribute('batchVars').isEmpty()) {
                          
                           ...

			}else{
				// concat output
				parseBatchOutput(body, request, response, this.responseFileType)

				//forward
				String path ="/b${this.version}/${this.controller}/${this.action}/**"
				def servletCtx = this.ctx.getServletContext()
				def rd = servletCtx?.getRequestDispatcher(path)
				rd.forward(request,response)
			}
```

**Comment by snicoll** [comment]
The link above is not valid anymore. If you still have it, please clarify what should be invoked to reproduce the issue.

**Comment by bclozel** [comment]
I've tried to reproduce this with supported versions and couldn't:

```java
public class TestFilter extends OncePerRequestFilter {

    private static final Logger logger = LoggerFactory.getLogger(TestFilter.class);

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        logger.info(request.getRequestURI());
        filterChain.doFilter(request, response);
    }
}
```


```java
@RestController
public class TestController {

    @GetMapping("/")
    public void home(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("/test").forward(request, response);
    }

    @GetMapping("/test")
    public String test() {
        return "test";
    }
}
```

The request is indeed forwarded but the filter is only called once. We'll reopen if we get a minimal application that reproduces this problem.

**Comment by orubel** [comment]
You are correct. I forgot this was still open. I was seeing this due to weird double request/response output
