### ISSUE TITLE
The value of method parameter may be reversed

### ISSUE THREAD

**Issue by HaimiZhou** [spring-projects/spring-framework#28539]
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry#registerDependentBean
![image](https://user-images.githubusercontent.com/18898924/170870624-d06f1c67-1dbe-4434-9230-240fadeab339.png)

![image](https://user-images.githubusercontent.com/18898924/170870604-a3ad8658-8730-4621-a6fe-227a87d5ca8e.png)

**Comment by rstoyanchev** [comment]
This is true, but it's not the only example in Spring and beyond. It's something to be avoided, but sometimes there isn't a good alternatives.
