### ISSUE TITLE
Which version of hibernate is suitable for spring framework 5.0.2?

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28536]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
Sorry but Spring Framework 5.0.x is out of open source support. You'll find more [information about the requirements in our wiki](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x).
