### ISSUE TITLE
Add CORS support for Private Network Access

### ISSUE THREAD

**Issue by sixcorners** [spring-projects/spring-framework#28546]
Chrome will want a `Access-Control-Allow-Private-Network` header from the application if `Access-Control-Request-Private-Network` is sent in the preflight request. It would be nice if the CrossOrigin annotation handled this.

See https://developer.chrome.com/blog/private-network-access-preflight/.

**Comment by rstoyanchev** [comment]
Thanks for raising this. 

My initial read is that this would be another boolean attribute in `CorsConfiguration` and `@CrossOrigin` that we would check if the `Access-Control-Allow-Private-Network` request header is present. It'll also require some additional logic for preflight checks given that:

> preflight requests for PNA are also sent for same-origin requests, if the target IP address is more private than the initiator

I note that the spec is still a draft, and it's unclear how much it is to evolve yet, even if it is in Chrome already.

**Comment by bgalek** [comment]
`Access-Control-Allow-Private-Network` is already there in your browsers, for now it's just a warning, but few days ago I've got caught in chrome experiment and it broke some internal stuff, can we update priority on this task?
@rstoyanchev?

![Screenshot 2023-12-21 at 20 01 32](https://github.com/spring-projects/spring-framework/assets/2291045/0eb2899f-c595-468e-b4c4-58af2da9dda3)

**Comment by sdeleuze** [comment]
Yes, we will.

**Comment by sdeleuze** [comment]
Backported to both Spring Framework 6.0 and 5.3.
