### ISSUE TITLE
Spring Framework 5.3.20 is reported as vulnerable 

### ISSUE THREAD

**Issue by shamkumarp** [spring-projects/spring-framework#28551]
**Affects:** \<Spring Framework version>

Spring Framework Version 5.3.20 is reported as vulnerable on blackduck, what is the next stable version we can upgrade to? also i see a new 6.x snapshot version is released but i read that in one of the comments that it needs Java 17. 

can you please advise on this showstopper issue we have. 

---

**Comment by bclozel** [comment]
Duplicates #24434, see https://github.com/spring-projects/spring-framework/issues/24434#issuecomment-744519525
