### ISSUE TITLE
Allow ApplicationContextAotGenerator to generated better class names

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#28565]
Currently `ApplicationContextAotGenerator` always generates a `__.BeanFactoryRegistrations` class. For context hierarchy support we're going to need multiple registration classes so we should use different names. We'd also like to be able to provide a target class so that we can use a package other than `__`.

**Comment by snicoll** [comment]
The default classname is still generated in that `__` package. Is that expected? I was under the impression that this issue would move it at the same level as the application class itself.
