### ISSUE TITLE
Unneeded current path check

### ISSUE THREAD

**Issue by kvaithin** [spring-projects/spring-framework#28581]
Inside the `StringUtils` class, method `cleanPath`, there is a conditional check for current path with no further logic inside it. 
Could we drop this if check? Could raise a PR. 

For reference: https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/util/StringUtils.java#L695

**Comment by snicoll** [comment]
I don't think we can. It's an optimization to drop it early. If we dropped the check we'd end up in the last `else` that would attempt to do something with the path. Thanks for the suggestion, in any case.
