### ISSUE TITLE
Support RouterFunction ordering in Spring MVC

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#28595]
`RouterFunctionMapping` in Spring MVC does not support ordering. By comparison, the WebFlux `RouterFunctionMapping` does, refactored in #21861 to use `ObjectProvider`, but always had the support for it. 

This was uncovered in https://github.com/spring-projects/spring-graphql/issues/404.

**Comment by tudormarc** [comment]
@rstoyanchev can I make a PR for this? :)

**Comment by rstoyanchev** [comment]
@tudormarc no objections, but it might not be as simple as making the two identical due to the `detectHandlerFunctionsInAncestorContexts` flag on the WebMvc side.
