### ISSUE TITLE
Fix Kotlin example for  @Required

### ISSUE THREAD

**Issue by SchroedingersGitHub** [spring-projects/spring-framework#28590]
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-required-annotation

```kotlin
class SimpleMovieLister {
    lateinit var movieFinder: MovieFinder
             @Required
              set
    // ...
}
```

**Comment by sbrannen** [comment]
Thanks for pointing this out.

This has been addressed in `5.3.x` and `main`.

In the future, when you come across issues like this with the documentation feel free to submit a PR that contains the fix.
