### ISSUE TITLE
Use PathPatternParser by default in Spring MVC

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#28607]
`PathPatternParser` was introduced for WebFlux in 5.0 as a replacement for `AntPathMatcher` that uses pre-compiled patterns, supports mapping without decoding the full URL path, and optimizes the pattern syntax for web (vs file system) paths. 

It has been available for use in Spring MVC since version 5.3 and has been enabled as the default in Spring Boot since version 2.6 with https://github.com/spring-projects/spring-boot/issues/24805.

This issue is to consider switching the default in Spring Framework to `PathPatternParser` for 6.0, and potentially deprecate `PathMatcher` and related options.

**Comment by bclozel** [comment]
I think we should do this (including the deprecation) for 6.0.

**Comment by rstoyanchev** [comment]
**Team decision:** we'll go ahead with it and align with the default in Boot.
