### ISSUE TITLE
Document need for `kotlin-spring` plugin regarding `open` keyword

### ISSUE THREAD

**Issue by maxbiu** [spring-projects/spring-framework#28604]
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-autowired-annotation-primary

kotlin to 

```kotlin
@Configuration
open class MovieConfiguration {

    @Bean
    @Primary
    open fun firstMovieCatalog(): MovieCatalog { ... }

    @Bean
    open fun secondMovieCatalog(): MovieCatalog { ... }

    // ...
}
```

**Comment by SchroedingersGitHub** [comment]
same question
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-generics-as-qualifiers

....

**Comment by sbrannen** [comment]
Good catch.

The assumption in the reference manual is that the user has set up the `kotlin-spring` plugin (see https://kotlinlang.org/docs/all-open-plugin.html#spring-support).

However, I don't believe that plugin is mentioned anywhere in the reference manual. Thus those examples will not work "as is".

So, let's add `open` where necessary in the reference manual and add a TIP pointing to the `kotlin-plugin` and mentioning that Kotlin projects created using start.spring.io will automatically have that plugin configured.

@SchroedingersGitHub, would you like to submit a PR to address this?

**Comment by sbrannen** [comment]
> So, let's add `open` where necessary in the reference manual and add a TIP pointing to the `kotlin-plugin` and mentioning that Kotlin projects created using start.spring.io will automatically have that plugin configured.

Or rather... let's not add `open` and instead

- add a new section about the `kotlin-spring` plugin to the [Kotlin section](https://docs.spring.io/spring-framework/docs/current/reference/html/languages.html#kotlin) of the reference manual
- for all affected examples, add a note that `open` would be necessary if you do not use the `kotlin-spring` plugin and point to the new section (see previous action item)

Side note: the `kotlin-spring` plugin is in fact mentioned in [Spring Boot's Kotlin](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.kotlin) documentation and in the [Spring Boot Kotlin tutorial](https://spring.io/guides/tutorials/spring-boot-kotlin/), but it takes several clicks to find that information (and you have to know that there is a dedicated Kotlin section in the Spring Framework reference manual).

**Comment by SchroedingersGitHub** [comment]
@sbrannen Thank you! Okay

**Comment by snicoll** [comment]
@SchroedingersGitHub please don't close the issue. There is still work to do.

**Comment by sdeleuze** [comment]
FWIW using `open` is not idiomatic at all in Spring + Kotlin, so I would indeed favor a documentation refinement where we clarify the pre-requisits like using `kotlin-spring` plugin for related samples (could be a comment in the Kotlin code).

**Comment by sdeleuze** [comment]
I think this is properly documented [here](https://docs.spring.io/spring-framework/docs/current/reference/html/languages.html#final-by-default).
