### ISSUE TITLE
Fix code sample for nested router functions

### ISSUE THREAD

**Issue by daehwan2yo** [spring-projects/spring-framework#28603]
Hi,
About nested Routes in Web on Reactive Docs ,
https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#nested-routes

says 
`path("/person", builder -> ...  .POST("/person", ...)).build();`
<img width="592" alt="스크린샷 2022-06-10 오전 11 52 05" src="https://user-images.githubusercontent.com/26921986/172980771-88910f1e-fc73-4621-a316-6c5730911c3a.png">

it means that API will be  `POST "/person/person"`,
however this example is how to construct nest path without duplication so I think it is not RESTful.

<img width="980" alt="스크린샷 2022-06-10 오후 12 04 02" src="https://user-images.githubusercontent.com/26921986/172982057-e21543f2-191f-4b00-9d9f-bb3707910eb9.png">

Is this intentional?
if not, how about to update like
``` java
RouterFunction<ServerResponse> route = route()
    .path("/person", builder -> builder 
        .GET("/{id}", accept(APPLICATION_JSON), handler::getPerson)
        .GET(accept(APPLICATION_JSON), handler::listPeople)
        .POST("", handler::createPerson))
    .build();
```

**Comment by poutsma** [comment]
Thanks for spotting this. It seems like the Servlet version [has the same issue](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#nested-routes).
