### ISSUE TITLE
Non Singletons being included even with includeNonSingletons

### ISSUE THREAD

**Issue by fsgonz** [spring-projects/spring-framework#28615]
Hi!

I have seen that [this verification](https://github.com/spring-projects/spring-framework/blob/v5.1.20.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java#L529) was removed.

I think that will result in beans being created even when you indicate that nonSingletons should not be included.

Can you verify if there is a reason [for not adding this change](https://github.com/fsgonz/spring-framework/commit/701b28d1230e830e17a1528fd244396706f1b1f5)?

This seems to be a bug introduced [here](https://github.com/spring-projects/spring-framework/commit/a0e462581fe1d27d5926809fbb21441a6685ef45#diff-7647ef528e5ffcfdb8ce8b88d189a906a1e7b46778323bc92cb9783a4991d5abR536)

Our app is failing because of this. I'll try to add a test but can you take a look at it meanwhile?

**Comment by fsgonz** [comment]
I've opened this PR. https://github.com/spring-projects/spring-framework/pull/28616

**Comment by fsgonz** [comment]
This[ issue and the comment in particular](https://github.com/spring-projects/spring-framework/issues/26851#issuecomment-826117580) may be related to this.

**Comment by sbrannen** [comment]
Superseded by:

- #28616
