### ISSUE TITLE
Replace build-time initialization by constant field evaluation at build-time

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#28624]
In order to compile to native images and to provide a reasonable footprint, we are currently forced to initialize classes containing `ClassUtils#isPresent` checks at build time. A meaningful concrete example of that requirement is provided by Spring MVC support that does not compile unless a few classes are initialized at build time, see 2b76a12b86a62cc46886e1b7f0e52ea9d256f899.

The drawback is that this build time init of `WebMvcConfigurationSupport` and `RestTemplate` forces to initialize transitively all classes used in static fields/blocks at build time as well : `ClassUtils`, `SpringProperties`, `ConcurrentReferenceHashMap`. Worse : for other classes with similar pattern, if they contain a static loggers, this will force to initialize Logback at build time which is a dead end in term of compatibility as shown multiple times in Spring Native.

We are working on a middle-long term solution with GraalVM to replace build time init by another mechanism, less viral, with less compatibility issues. But for time being, we need to find a solution to this issue.

A pragmatic solution would be isolate classpath checks in a per module (`spring-core`, `spring-web`) class that would be itself init at build time but with no other purpose, removing the risk of viral expension of the classes init at build time. If we take the `WebMvcConfigurationSupport` use case, we would have something like:

```java
public abstract class ClasspathUtils {

    private static final boolean romePresent;
    private static final boolean jaxb2Present;
    private static final boolean jackson2Present;

    static {
        // ...
    }

    public static boolean isRomePresent() { ... }
    public static boolean isJaxb2Present() { ... }
    public static boolean isJackson2Present() { ... }
    // ...
}
```
Bonus point, I think I like the fact that we provide reusable methods for classpath checks without arbitrary `String` parameter.
Implementation would potentially even not use `ClassUtils` to limit the classes init at build time (not sure what is would use instead, to be discussed, not a blocking point).

Any thoughts @jhoeller @snicoll @bclozel?

**Comment by philwebb** [comment]
Perhaps the `@Constant` annotation from this branch that we discussed in the past might help? https://github.com/philwebb/scratch-graal-conditions/tree/annotations

**Comment by sdeleuze** [comment]
I had a look to the branch shared above. it allows to declare with `@Constant` which field should be evaluated at build time but unless I am mistaken there is a blocking point : [it still initialize the said classes at build time programmatically](https://github.com/philwebb/scratch-graal-conditions/blob/annotations/src/main/java/gce/graalvm/ConstantFeature.java#L48) (@philwebb please let me know if my understanding is incorrect) which is what we want to avoid here because in real world use cases, it ends up initializing too much classes at build time transitively, leading to "by design" unsolvable compatibility issues, so I don't think we can leverage that or even a variant I had in mind (detecting certain patterns without annotations).

The proposed approach is also carrying different semantics compared to the path we are beginning to follow with the GraalVM working group @bclozel and I have joined where it is the invoked methods that will be tagged safe to inline at build time. This upcoming GraalVM replacement for build time class initialization is likely the way we would like to follow middle term, but we don't have any clue of the timeline, so I think we need a good enough workaround that does not cause the same compatibility issues than what we have on Spring Native.

My proposal for refactoring described in this issue description (see the `ClasspathUtils` code sample above) could be a solution, but enforcing a global refactoring for something that will likely be solved in a few months seems a artificial.

All things considered, and with the assumption that my analysis above is correct, I am going to propose to follow for now a continuation of the pragmatic path we have begin to follow:
 - Declare classes with `static final boolean *Present` as initialized at build time via `META-INF/native-image/native-image.properties` files in related modules
 - Make sure we do not introduce compatiblity issues, a known pattern that causes blocking issues is static loggers. For those use cases only, refactoring should be done (lazy logger init or moving related fields in a dedicated class/subclass). Those refactoring will be undone when we will have the right solution via the GraalVM working group.

cc @jhoeller @bclozel.

**Comment by sdeleuze** [comment]
@philwebb Could you please confirm that [this build time initialization of classes](https://github.com/philwebb/scratch-graal-conditions/blob/annotations/src/main/java/gce/graalvm/ConstantFeature.java#L48) is just required for class level `@Constant` not for field level ones?

**Comment by philwebb** [comment]
@sdeleuze correct, that's just for class-level use.

**Comment by sdeleuze** [comment]
Good news, I have been able to leverage the updated `@Constant` experiment to remove totally build time initialization from Spring Framework 6 (can be used for portfolio projects and Boot as well) while keeping the same benefits in tern of build time code removal, see [this related WIP branch](https://github.com/sdeleuze/spring-framework/tree/gh-28624). Thanks a lot @philwebb!

As soon as GraalVM team provides a builtin solution via the working group @bclozel and I have joined, it would replace this GraalVM feature. That's why I have preferred not introducing a new annotation like `@Constant` but just target a set of patterns. Since we don't have a real idea of the timeframe, the GraalVM feature provide a reasonable path for this transition period.

**Comment by sdeleuze** [comment]
https://github.com/sdeleuze/build-time-constant-fields allows to test it works as expected. Not sure yet if/how we should integrate that in the CI, but probably good enough for this milestone to have such side repository to test the behavior.

Logs printed during the native build allow to identify which fields are set to a constant value at build time.
