### ISSUE TITLE
Support adding rather than replacing modules in Jackson2ObjectMapperBuilder

### ISSUE THREAD

**Issue by AQS-DTheuke** [spring-projects/spring-framework#28633]
https://github.com/spring-projects/spring-framework/blob/67b1420b32cadef349bb60490b6e07cc5f882ecc/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L570-L574

Currently the `Jackson2ObjectMapperBuilderCustomizer` is only able to replace the modules that should be installed; however, it is possible to define multiple Spring Boot `Jackson2ObjectMapperBuilderCustomizer` beans that could each wish to add a Jackson module. However the later customizers will always remove the modules configured by the previous instance. It isn't possible to get the current list of modules either and extend that.

We wish to separate our customizers by their related modules/source libraries (api-docs, error-handling, ..., and the application itself).

So it would be nice if there was a `addModules(toInstall)` method that would add the modules to the list instead of replacing it.

Most of the other methods such as `serializers(JsonSerializer<?>...)` already work like that:

https://github.com/spring-projects/spring-framework/blob/67b1420b32cadef349bb60490b6e07cc5f882ecc/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L354-L363

Thanks for your awesome work.

**Comment by aooohan** [comment]
@sbrannen  hi,Sam. Does this issue need to be achieved? I personally think it would be more flexible to provide a method to add a Module separately, if it need to be implemented, can I be assigned? I would be happy to provide PR.

**Comment by sbrannen** [comment]
@aooohan, we will discuss within the team whether we wish to add such a method.

Please note that the `waiting-for-triage` label signals that the team has not yet reached a decision on the issue.

**Comment by aooohan** [comment]
> @aooohan, we will discuss within the team whether we wish to add such a method.
> 
> Please note that the `waiting-for-triage` label signals that the team has not yet reached a decision on the issue.

Alright, thank you for your reply.

**Comment by rstoyanchev** [comment]
We could maybe add a `Consumer` based overloaded variant `modulesToInstall(Consume<List<Module>> modules)` that lets you customize the configured set rather than set the modules.

**Comment by rstoyanchev** [comment]
Note that the builder currently has two methods for modules, `modules(List<Module> modules)` and `modulesToInstall(Module... modules)`, which have different semantics and mutually exclusive. It's a bit more challenging to come up with something that is clearly aligned with one or the other. The proposed `addModules` sounds like it is aligned with `modules` but your example was for `modulesToInstall`. 

This is why I think an overloaded method with a `Consumer` allows clear alignment plus the added benefit of full control over the list of modules, including where to insert, add, remove, etc.

**Comment by AQS-DTheuke** [comment]
Please note that you always need two methods (unless you refactor the whole thing to avoid the `findWellKnownModules` in these methods). 
`modules(...)` is exclusive. `modulesToInstall(...)` is inclusive.
And I am referring to both for consistency reasons, IMO its just somewhat redundant to always explicitly mention both.

Semantically, I wish to just add a module to the builder, so I would appreciate it, if there is a method for exactly that (similar to all the other existing methods). I explicitly added the two code examples in the issue description to show the difference in their implementation. Most of the other methods look like the serializer one (are adders not setters). 
IMO in the next major version of spring, this should be addressed further by renaming `modules()` to `replaceModules(...)` or `setModules(...)` and renaming `addModules(...)` to `modules(...)` so they behave the same as the other methods and don't disrupt developer expectations.

This is the workaround I currently use:

````java
@Bean
// Custom error details
public Jackson2ObjectMapperBuilderCustomizer apiErrorCustomizer() {
    // We cannot use the module directly
    // because the module methods are only setters and not adders
    // builder#serializers adds the passed serializers instead
    return builder -> builder.serializers(ApiErrorModule.requiredSerializers())
                             .deserializers(ApiErrorModule.requiredDeserializers());
}

// --------------------- in another configuration class/artifact

@Bean
// "2000" -> "2000-01-01" <= x < "2001-01-01"
public Jackson2ObjectMapperBuilderCustomizer dateishRangeCustomizer() {
    return builder -> builder.serializers(DatishRangeModule.requiredSerializers())
                             .deserializers(DatishRangeModule.requiredDeserializers());
}
````
