### ISSUE TITLE
suggestion for Aop

### ISSUE THREAD

**Issue by dayAndnight2018** [spring-projects/spring-framework#28639]
When we use aop to catch one function, offering a paramsMap for the method is very useful ! because we can not find any evidence for 

proceedingJoinPoint.getSignature().getParameterNames()

and 

proceedingJoinPoint.getArgs()

has the same order or determined pair of key and value.

**Comment by sbrannen** [comment]
Are you referring to APIs defined in AspectJ?

> proceedingJoinPoint.getSignature().getParameterNames()

Where is the `getParameterNames()` method defined?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
