### ISSUE TITLE
Add support for Kotlin inline/value classes in `BeanUtils`

### ISSUE THREAD

**Issue by MrBuddyCasino** [spring-projects/spring-framework#28638]
Kotlin value classes currently cannot be used in configuration bindings in Spring Boot 2.6.6.

This is a repro case:

```kotlin
package com.example

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.context.properties.ConfigurationPropertiesScan
import org.springframework.boot.context.properties.ConstructorBinding
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean

fun main(args: Array<String>) {
    System.setProperty("SPRING_APPLICATION_JSON", "{ \"predicate\": \"C\" }")
    runApplication<SpringTest>(*args)
}

@SpringBootApplication
@ConfigurationPropertiesScan(basePackages = ["com.example"])
class SpringTest {

    @Bean
    fun someBean(config: PredicateConfiguration): String {
        println("predicate: ${config.predicate.value}")
        return ""
    }

}

@JvmInline
value class Predicate(val value: Char)

@ConfigurationProperties
@ConstructorBinding
data class PredicateConfiguration(val predicate: Predicate)
```

It fails with the following error message:

```
Failed to bind properties under '' to com.example.PredicateConfiguration:

    Reason: java.lang.IllegalArgumentException: object is not an instance of declaring class
```

**Comment by aseemsavio** [comment]
Hello team - can support for Kotlin inline classes be expected in the near future? :)

**Comment by sdeleuze** [comment]
No promise, but let's try to tackle that as part of 6.1.0-M3.

**Comment by sdeleuze** [comment]
See related comments from @udalov in https://github.com/spring-projects/spring-data-commons/pull/2866#pullrequestreview-1533612845.

**Comment by ianbrandt** [comment]
Does this enhancement mean Kotlin value classes can be used in 6.1+ to disambiguate `@Bean` types, including when used as type parameters?

For example:

```kotlin

@JvmInline
value class LogsPath(val value: Path)

@JvmInline
value class PrefsPath(val value: Path)

@Configuration
class ApplicationConfiguration {

    @Bean
    fun logsPathSupplier(): Supplier<LogsPath> = ...

    @Bean
    fun prefsPathSupplier() : Supplier<PrefsPath> = ...

    @Bean
    fun logService(logsPath: Supplier<LogsPath>) = ...

    @Bean
    fun prefsService(prefsPath: Supplier<PrefsPath>) = ...
}
```

If not, I'd file that as an additional feature request. I'm currently using `@Named` to disambiguate multiple such beans. Strongly-typed value class beans would be far preferred to _stringly_-typed bean names.

Also, just a heads up regarding some docs that may need to be adjusted for this change, https://docs.spring.io/spring-framework/reference/6.1/languages/kotlin/requirements.html currently has a blanket warning that, "Kotlin inline classes are not yet supported."

**Comment by MrBuddyCasino** [comment]
Oh nice, been waiting for this one, thanks for testing.

**Comment by ianbrandt** [comment]
I stand corrected. It works for me with value classes as generic type parameters or function type return types (e.g. `Supplier<MyValueClass>`, `() -> MyValueClass`), even in Spring 6.0, but not as direct `@Bean` types as of 6.1.0-M5.

I filed a separate issue with reproducer: #31372.

**Comment by apankowski** [comment]
This issue has been resolved, but I have tried using Andy Wilkinson's [reproducer](https://github.com/spring-projects/spring-framework/issues/28638#issuecomment-1157526325) and it failed for me exactly with the message mentioned by Andy.

I've tried it with:

1. `org.springframework:spring-beans:6.1.11`
2. Kotlin 1.9.25
