### ISSUE TITLE
Spring official build and test, using OpenJDK?

### ISSUE THREAD

**Issue by TangDynasty06** [spring-projects/spring-framework#28644]
Spring官方构建和测试，使用的是OpenJDK吗

**Comment by TangDynasty06** [comment]
Spring official build and test, using OpenJDK?

**Comment by bclozel** [comment]
We have different CI pipelines for building and testing Spring Framework. The official build for the 5.3.x generation is built with the following: https://github.com/spring-projects/spring-framework/blob/5.3.x/ci/images/get-jdk-url.sh#L6
