### ISSUE TITLE
Consider using `LoggingCacheErrorHandler` as the default cache error handler

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-framework#28649]
These days, the cache backends used with Spring's caching abstraction are very frequently remote services (such as Redis, Memcached, Hazelcast in client-server topology...) which implies dealing with concerns such as networking, (de)serialization. These concerns mean there's far bigger chance of various (most often transient) errors occurring while interacting with the cache backend, unlike in-JVM cache solutions that dominated over a decade ago when caching abstraction was added to Spring.

With that in mind, I personally don't think `SimpleCacheErrorHandler` is a sensible default for the cache error handler as it breaks the application flow that's otherwise perfectly functional, just because the optimization (cache) was unavailable at that particular moment. Instead, the better option is to have `LoggingCacheErrorHandler` (with enabled stacktrace logging) as the default.

This is something that could be considered for 6.0.

**Comment by snicoll** [comment]
`LoggingCacheErrorHandler` has been added as a convenience for those who chose to let such exceptions be moved to log statements. The core framework couldn't use this by default, even in 6.0. 

For what it is worth, this has been asked to the [Spring Boot team as well](https://github.com/spring-projects/spring-boot/issues/30151).
