### ISSUE TITLE
Webclient seems to miss response on high spikes

### ISSUE THREAD

**Issue by NitzanShifrin** [spring-projects/spring-framework#28656]
Using Webclient we are doing the following
![image](https://user-images.githubusercontent.com/42731841/174477635-2e018787-8e0a-41e2-9963-58bc5540a650.png)

where timeout is set to 1 second.

Usually this code is doing great, handling our peak times easily, and there are no problems.

In some cases we are having pre-planned high spikes of traffic (10k requests at 2-5 seconds), and after those spikes it seems that this method never recovers (the load is back to minimal, around 1 request per sec).

It sends the request, on the other end we see the request is made and there is an answer, but here we wait 30 seconds (even though the timeout is 1 second) and after those 30 seconds there is the timeout.

Restarting the service fixed the issue.

Is there some known issues with high spikes? any way to investigate since onError is not emitted?

Thanks for your time and help!

springBootVersion = '2.4.13'
spring-webflux: 5.3.13

**Comment by bclozel** [comment]
It's hard to know without more information. Typically client logs and tcp dump possibly.

There were related issues like #26906 or reactor/reactor-netty#839 - pointing to connection pool issues possibly linked to proxies not handling connection state properly.

Please provide us with more information.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
