### ISSUE TITLE
The mail API problem in spring-context-support

### ISSUE THREAD

**Issue by llsi4275** [spring-projects/spring-framework#28650]
jakarta.mail-api has been released to 2.1, and the package name has been changed from javax.mail to jakarta.mail, why is the javax.mail api referenced in spring?

**Comment by bclozel** [comment]
The Jakarta upgrade is scheduled for Spring Framework 6 and is already done in the latest milestones.
See https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6
