### ISSUE TITLE
can't open spring.io in china

### ISSUE THREAD

**Issue by lzj960515** [spring-projects/spring-framework#28668]
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/38074718/174735748-a6ab0819-6155-4564-9f05-d1f59cb997e1.png">

<img width="598" alt="image" src="https://user-images.githubusercontent.com/38074718/174735979-ec8499c2-274e-4f97-883f-1aafc372eff9.png">

**Comment by lzj960515** [comment]
I don't know who to call. Can anyone tell me why?

**Comment by bclozel** [comment]
There is an ongoing incident with CloudFlare, our CDN provider. [Check this page for updates](https://www.cloudflarestatus.com/incidents/xvs51y9qs9dj) and [springops](https://twitter.com/springops) on Twitter.
