### ISSUE TITLE
Why Spring is to old

### ISSUE THREAD

**Issue by jsl1992** [spring-projects/spring-framework#28693]
Why Spring?
Spring makes programming Java quicker, easier, and safer for everybody. Spring’s focus on speed, simplicity, and productivity has made it the [world's most popular](https://snyk.io/blog/jvm-ecosystem-report-2018-platform-application/) Java framework.

Link is 2018 now 2022
Link is 2018 now 2022

https://snyk.io/blog/jvm-ecosystem-report-2018-platform-application/

**Comment by jsl1992** [comment]
https://spring.io/why-spring

**Comment by bclozel** [comment]
https://snyk.io/jvm-ecosystem-report-2021/
