### ISSUE TITLE
JmsTemplate ignores message priority & deliveryMode

### ISSUE THREAD

**Issue by borsch** [spring-projects/spring-framework#28695]
**Affects:** \5, 6

Using org.springframework.jms.core.MessagePostProcessor I can configure custom values for priority & deliveryMode but it seems like JmsTemplate doesn't take into account those values(check below link)

[			producer.send(message, getDeliveryMode(), getPriority(), getTimeToLive());](https://github.com/spring-projects/spring-framework/blob/16c43c2041a50a8e1fd0befbb71cc2aa9644620a/spring-jms/src/main/java/org/springframework/jms/core/JmsTemplate.java#L631)

Issue is that in such case I need to configure multiple `JmsTemplate` instances to be able to generate messages with different priorities & delivery models

```java
JmsTemplate jmsTemplatePriorityDefault;
JmsTemplate jmsTemplatePriority5;
JmsTemplate jmsTemplatePriority2;
.. and so on ..
```

---

**Comment by snicoll** [comment]
If am afraid that there is not much we can do about this. The JMS spec states that users can't change those QoS settings using the `Message` API, see https://javadoc.io/doc/jakarta.jms/jakarta.jms-api/latest/jakarta.messaging/jakarta/jms/Message.html for an example.
