### ISSUE TITLE
GraalVM conflict with spring.main.log-startup-info property in WSL

### ISSUE THREAD

**Issue by LtVaios** [spring-projects/spring-framework#28708]
Although the property is set to: _**false**_ **_(spring.main.log-startup-info=false)_** in my application.properties and even if you print it out it, spring still says it is set to false, the native-image logs of my app print out the spring startup-info like it is set to _true._ The process I am following is:

> mvn clean

> mvn -Pnative -DskipTests package

> Run the native-image of my app in my WSL

Versions:

- Java 17
- spring-boot-starter-parent: 2.7.0
- spring-aot-maven-plugin: 0.12.0
- native-maven-plugin: 0.9.11

**PS:** _If it has any meaning to the issue, I also tried doing the same with a very simple spring app too and this issue seems to persist._

**Comment by bclozel** [comment]
Could you open this issue against [the spring-native project please](https://github.com/spring-projects/spring-framework/issues/28708)?
Unfortunately I can't transfer this issue. Thanks!
