### ISSUE TITLE
`GenericApplicationContext` does not honor `ProtocolResolver` when a resource loader is set via `setResourceLoader()`

### ISSUE THREAD

**Issue by arteymix** [spring-projects/spring-framework#28703]
I'm trying to intercept certain URL patterns to resolve into the correct `UrlResource`, but the application context does not honour custom protocol resolvers.

In pseudocode:

```java
GenericApplicationContext applicationContext = new GenericApplicationContext();
applicationContext.setResourceLoader(someResourceLoader);
applicationContext.addProtocolResolver(new CustomUrlResolver());
applicationContext.getResource("http://some.custom.url/"); // never resolved via CustomUrlResolver
```

The `CustomUrlResolver` resolver is never invoked because `someResourceLoader` takes precedence in `getResource`. Unfortunately, there's no way to work around this issue by adding a delegating resource loader, since there's no accessor for the resource loader.

I believe that the `setResourceLoader(...)` call is done somewhere in Spring Boot.

I had to do `setResourceLoader(null)`. This is likely going to break things.

**Comment by arteymix** [comment]
In that case, you can put the for-loop within the `this.resourceLoader != null` condition.

**Comment by sbrannen** [comment]
> In that case, you can put the for-loop within the `this.resourceLoader != null` condition.

Yes. You are of course correct, and that's exactly how I implemented it. 👍 

When I said "at a glance", I meant that literally. It was the last thing I _glanced_ at before signing off for the day, and I hadn't even put any thought into how to optimize the code. 😇 

This is in place now for 5.3.22 (available soon in snapshots).
