### ISSUE TITLE
Replace java.util.Date and TimeUnit usage in scheduling with appropiate java.time classes

### ISSUE THREAD

**Issue by desiderantes** [spring-projects/spring-framework#28714]
Given that a lot of times we get the values for Triggers and such from configs or other places that use java.time types, and the fact that they're the proper types to model this sort of thing, it would be nice to reduce usage of java.util.Date (since it's so prone to improper handling).

**Comment by poutsma** [comment]
@desiderantes This is now complete, see https://github.com/spring-projects/spring-framework/commit/9b739a2310bac781c89a22bf92650615f9dd7406. Let me know if there are `java.util.Date` usages that I missed.

**Comment by desiderantes** [comment]
@poutsma Whoah, thanks a lot! I don't see other usages of java.util.Date in scheduling (and I can't judge the usages in the other parts)
