### ISSUE TITLE
Create well-known non-interface types in CollectionFactory without using reflection

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#28718]
**Affects:** 6.0

As [discussed with @sdeleuze](https://github.com/spring-projects/spring-boot/issues/31517#issuecomment-1168553144), it would be useful for native images if `CollectionFactory` could create instances of well-known non-interface collection types without using reflection. Aligning with the types that the factory creates for different interfaces, these well-known implementations could be `LinkedHashSet`, `TreeSet`, and `ArrayList`. Similar changes could be made for map creation as well.

**Comment by sbrannen** [comment]
- somewhat related to #28025
