### ISSUE TITLE
Support to guarantee transactions by using @EventListener and ReactiveTransactionManager

### ISSUE THREAD

**Issue by pkgonan** [spring-projects/spring-framework#28713]
Hi.
If you register ReactiveTransactionManager as Spring Bean and use @Transactional annotation, you can guarantee transaction. 

However, when using @EventListener or @TransactionalEventListener together, transaction cannot be guaranteed.

Do you have any plans to support this?

**Comment by snicoll** [comment]
Duplicates https://github.com/spring-projects/spring-framework/issues/25805
