### ISSUE TITLE
TestExecutionListener does not get applied for a new context for @Nested test class

### ISSUE THREAD

**Issue by vootelerotov** [spring-projects/spring-framework#28724]
When setting up `@SpringBootTest` as follows:

```kotlin
@SpringBootTest(classes = [MyTestComponent::class])
@TestExecutionListeners(value = [MyTestExecutionListener::class], mergeMode = MERGE_WITH_DEFAULTS)
@TestConstructor(autowireMode = ALL)
class TestExecutionListenersNestedApplicationTests(private val testComponent: MyTestComponent) {
  // ...
  @TestComponent
  class MyTestComponent(var enabled: Boolean = false)

  class MyTestExecutionListener : TestExecutionListener {

    override fun beforeTestMethod(testContext: TestContext) {
      testContext.applicationContext.getBean(MyTestComponent::class.java).enabled = true
    }

    override fun afterTestMethod(testContext: TestContext) {
      testContext.applicationContext.getBean(MyTestComponent::class.java).enabled = false
    }
  }
  // ...
}  
```

I would expect both of these `@Nested` test classes to behave the same way:

```kotlin
  @Nested
  inner class ClassWithSameContext {

    @Test
    fun noProblemo() {
      assertThat(testComponent.enabled).isTrue
    }
  }

  @Nested
  @TestPropertySource(properties = ["test=true"])
  inner class ClassWithDifferentContext {

    @Test
    fun problemo() {
      assertThat(testComponent.enabled).isTrue
    }
  }
```

However, the test in the first one passes and the test in the second one fails. 

This looks like a bug to me, or am I missing something?

Stepping through the test with a debugger shows that a context gets processed in the `beforeTestMethod()` method, but that context does not seem to be used in the test. 

See  [here](https://github.com/vootelerotov/test-execution-listener-with-nested-class/) for a runnable sample project.

**Comment by vootelerotov** [comment]
>Thus, when the MyTestExecutionListener is invoked for ClassWithDifferentContext, testContext.getApplicationContext().getBean(MyTestComponent.class) accesses the MyTestComponent bean in the ApplicationContext for ClassWithDifferentContext.

>But... the testComponent field/property is injected from the ApplicationContext for TestExecutionListenersNestedApplicationTests.

This seems to be what I missed in my mental model. Makes sense.

@sbrannen, thanks for taking the time to give a very thorough answer.

**Comment by sbrannen** [comment]
> @sbrannen, thanks for taking the time to give a very thorough answer.

You're welcome.

The reason it's so "thorough" is that your use case sparked some thought experiments in my head, and I wanted to verify what options actually exist to support such use cases.
