### ISSUE TITLE
Potential Refactoring Estimate

### ISSUE THREAD

**Issue by alvintanjianjia** [spring-projects/spring-framework#28749]
**Summary**
I have identified a few classes with refactoring potential along with its estimated time to refactor, specifically ObjectToObjectConverter.java. The estimated time is based on historical commits up to 2021 containing refactoring and the complexity of the involved classes. The class is recently refactored once in commit 97854d9fec8b89783443dd9571c0ce76efd041aa. I would like to know if the estimated time for refactoring matches the actual development time for refactoring.

1. ObjectToObjectConverter.java - 3.5 hours

Thank you.

Regards,
Alvin

**Comment by sbrannen** [comment]
Thanks for getting in touch, but we don't track metrics like that.

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.

In light of that, I am closing this issue.
