### ISSUE TITLE
Add example of buffering with WebClient to the reference documentation

### ISSUE THREAD

**Issue by alexanderankin** [spring-projects/spring-framework#28758]
The code samples in #26489 are very useful and I keep coming back to them. Recently I forgot the exact title and spent a while to remember how to find it. Perhaps it is a good candidate to add to the documentation, perhaps in [this section][section]? I would be willling to create that PR but I figured it probably makes sense to ask first.

[section]: https://docs.spring.io/spring-framework/docs/5.2.22.RELEASE/spring-framework-reference/web-reactive.html#webflux-client-filter

**Comment by rstoyanchev** [comment]
@alexanderankin, thanks for the suggestion. It is a good idea, so feel free to send a PR.
