### ISSUE TITLE
ResolvableType.forInstance should return NONE for null instance

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#28776]
`ResolvableType.forInstance(Object)` enforces a not-null argument which makes it unpleasant to use with input that can come from a nullable source (or even just an API call which in some circumstances may return `null` and is therefore marked as `@Nullable`, even if never actually `null` in a given usage scenario). A more usage-friendly variant is to accept `null` but turn it into `ResolvableType.NONE`.

**Comment by salmansharifov** [comment]
@jhoeller Can I take this issue?

**Comment by jhoeller** [comment]
@salmansharifov Thanks for volunteering but I got this locally prepared along with a few other backports to 5.3.22 already, to be committed today.
