### ISSUE TITLE
Support `@Value` on records

### ISSUE THREAD

**Issue by MiniDigger** [spring-projects/spring-framework#28770]
For context see https://github.com/spring-projects/spring-boot/issues/31603

Basically, I want to be able to do this
```
	@Component
	public record Test(@Value("${username}") String user) {}
```
right now that code fails, even tho the bean is created with the right value, because the AutowiredAnnotationBeanPostProcessor attempts to populate the record via field injection (even tho the values have already been set).

**Comment by 1004789224** [comment]
can i try this issues

**Comment by sbrannen** [comment]
- Superseded by #28774
