### ISSUE TITLE
Typo in `SockJsServiceRegistration#setSupressCors`

### ISSUE THREAD

**Issue by marcwrobel** [spring-projects/spring-framework#28806]
**Affects:** 5.3.21

---
There is a typo in `org.springframework.web.socket.config.annotation.SockJsServiceRegistration#setSupressCors`: the method should be named `setSuppressCors`.

**Comment by sdeleuze** [comment]
@rstoyanchev Should we use the opportunity of 6.0 to deprecate `setSupressCors` and introduce `setSuppressCors`, or even more aggressively just rename it and mentioning it in release notes?

**Comment by rstoyanchev** [comment]
A deprecation + a new methods sounds good. This could even be done in 5.3.x since it allows a migration period and is easy to change if you get a build warning.

**Comment by sdeleuze** [comment]
If we do deprecation + a new method in 5.3.x, is it fine from your POV if we just keep the new method in 6.0?

**Comment by marcwrobel** [comment]
@sdeleuze, I have created a PR against 5.3.x for this issue. I marked `setSupressCors` as deprecated for removal in 6.0 (@rstoyanchev seems OK with your reasoning).

**Comment by snicoll** [comment]
Thanks @marcwrobel. Closing in favor of PR #28853
