### ISSUE TITLE
Reintroduce Javadoc links to Apache HttpClient 5.1 APIs

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#28811]
## Overview

Commit 3af6a22b9f728d1029be41c06b064170f2f6b016 temporarily disabled the links due to issues with the Apache web site that break our Gradle build.

## Related Issues

- https://issues.apache.org/jira/browse/HTTPCLIENT-2227

**Comment by sbrannen** [comment]
> Can I take this issue? 
> I will regularly check the Apache doc URLs and post a PR once the links work.

There's not much to do really.

It's a single line in `build.gradle` that has to be "uncommented".

In addition, I created the aforementioned [HTTPCLIENT-2227](https://issues.apache.org/jira/browse/HTTPCLIENT-2227) issue, so I should receive updates whenever one of the maintainers acts on it.

But if you would like to monitor their web site and keep us posted (or even submit a PR once their web site is back up), feel free to do so! 👍

**Comment by adrianbob** [comment]
Hi @sbrannen,
Javadoc link is working, added a PR: https://github.com/spring-projects/spring-framework/pull/28842

**Comment by snicoll** [comment]
Closing in favor of PR
