### ISSUE TITLE
Exception when trying to use HTTP/2 with two different Spring versions

### ISSUE THREAD

**Issue by karolkrasnowski** [spring-projects/spring-framework#28827]
**Affects:** 2.3.12.RELEASE

I'm sending the data from one service (the client) to another (the server) using HTTP/2. Both services use reactive stack. When both services use version `2.7.1` of Spring Boot (reactor-netty version `1.0.20`), everything works fine. But when I downgrade the client to the version `2.3.12.RELEASE` (reactor-netty version `0.9.20.RELEASE`) the code stops working, and exception is thrown:

```java
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpRequest (expected: ByteBuf, FileRegion)
Caused by: java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpRequest (expected: ByteBuf, FileRegion)
```

I created a [minimal reproducible example](https://github.com/karolkrasnowski/HTTP2) to demonstrate the issue. It's a multi-module Gradle project. One module represents the server, and another module represents the client. The [main](https://github.com/karolkrasnowski/HTTP2/tree/main) branch contains working example (both services with version `2.7.1`), and the [minimal-reproducible-example](https://github.com/karolkrasnowski/HTTP2/tree/minimal-reproducible-example) branch illustrates the problem.

Unfortunately, in the real project, the client service uses `2.3.12.RELEASE` version, and upgrade to the newest one is not that easy. Is there any way to make it work without the Spring Boot upgrade?

**Comment by karolkrasnowski** [comment]
I don't want this to sound rude, but when can I expect someone to take care of this issue?

**Comment by bclozel** [comment]
Spring Boot 2.3.x is out of OSS support - can you reproduce this with a supported version?

See https://spring.io/projects/spring-boot#support

**Comment by karolkrasnowski** [comment]
Thanks for your reply. This problem does not occur in version `2.6.0` so I suppose that this issue can be closed.
