### ISSUE TITLE
MethodValidationPostProcessor still use javax.validation

### ISSUE THREAD

**Issue by 2012518013** [spring-projects/spring-framework#28844]
javax.validation is outdated. When can MethodValidationPostProcessor use jakarta.validation instead of javax.validation.

**Comment by sdeleuze** [comment]
No instance of `javax` in https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/validation/beanvalidation/MethodValidationPostProcessor.java as far as I can say, maybe you used the wrong branch.

**Comment by snicoll** [comment]
Also, you need to use Spring Framework 6 with JakartaEE. Spring Framework 5 will remain on the previous namespace.

**Comment by 2012518013** [comment]
However，we cannot find any jars of Spring Framework 6 in maven repository.
eg: https://mvnrepository.com/artifact/org.springframework/spring-context

**Comment by snicoll** [comment]
Spring Framework 6 is still in milestone phase.

**Comment by 2012518013** [comment]
So, when the problem I mentioned can be solved?

**Comment by 2012518013** [comment]
As javax.validation is outdated, is there any possibility that  jakarta.validation can be use in the next release version of Spring Framework 5? When a release version of Spring Framework 6 can be used in production environment?

**Comment by bclozel** [comment]
See https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6
