### ISSUE TITLE
REST endpoint resolution changed (broke?) from spring-boot v3.0.0-M3

### ISSUE THREAD

**Issue by whydoievenneedthis** [spring-projects/spring-framework#28848]
**Affects:** \spring-boot v3.0.0-M4

---
I have the following REST endpoint specification:
GET /v1/thingy/{thingyId}

Then I make a call, in the context of an integration test, to MockMvc.perform(GET, '/v1/thingy/'). Note the last forward slash in the URL.

What happened in spring-boot v3.0.0-M3: the endpoint above was found, and the handleMissingServletRequestParameter method was triggered on the ResponseEntityExceptionHandler controller advice.

What happens in spring-boot v3.0.0-M4: the endpoint above is not found, and the call is redirected to the static resource handler.

I did not find any indication in the changelog that such a change in behaviour is expected.

**Comment by bclozel** [comment]
This behavior change was contributed by Spring Framework in #28552.
I've added a [new section in the Spring Boot migration guide to help developers with the upgrade](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M4-Release-Notes#spring-mvc-and-webflux-url-matching-changes). 
Thanks for your feedback!
