### ISSUE TITLE
Deprecate support for themes

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-framework#28868]
These days, theme switching is purely CSS based and does not really benefit from some special support on the server side. See [this guide](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/) as an example.

With that in mind, Framework's [support for themes](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-themeresolver) is quite obsolete and 6.0 might be a good opportunity to deprecate it.

**Comment by bclozel** [comment]
Closing in favor of #29114
