### ISSUE TITLE
Deleting Sensitive Information from the Memory

### ISSUE THREAD

**Issue by xukun-cpu** [spring-projects/spring-framework#28883]
Sensitive information (for example, passwords in login requests) stored in the temporary memory is not cleared in time after being used. It depends on the recycling mechanism of the JDK and may be used.
![image](https://user-images.githubusercontent.com/54844681/181671792-13686097-26eb-4bc3-a06c-7421141cf80c.png)

**Comment by bclozel** [comment]
If you believe you've found a security issue, please report it using the appropriate channel as described in the issue template.

See https://spring.io/security-policy
