### ISSUE TITLE
spring start question

### ISSUE THREAD

**Issue by shepherd819** [spring-projects/spring-framework#28899]
I think here no need to traverse no singleton bean names.

for (String beanName : beanNames) {
	Object singletonInstance = getSingleton(beanName);
	if (singletonInstance instanceof SmartInitializingSingleton) {
		StartupStep smartInitialize = this.getApplicationStartup().start("spring.beans.smart-initialize")
				.tag("beanName", beanName);
		SmartInitializingSingleton smartSingleton = (SmartInitializingSingleton) singletonInstance;
		if (System.getSecurityManager() != null) {
			AccessController.doPrivileged((PrivilegedAction<Object>) () -> {
				smartSingleton.afterSingletonsInstantiated();
				return null;
			}, getAccessControlContext());
		}
		else {
			smartSingleton.afterSingletonsInstantiated();
		}
		smartInitialize.end();
	}
}

**Comment by bclozel** [comment]
If you believe you've found an improvement, please send a PR explaining the change in greater details. Note that the changes must pass the entire test suite.
You'll find more information in the CONTRIBUTING document.
Thanks!
