### ISSUE TITLE
How to make @Exceptionhandler execute without sorting by Map

### ISSUE THREAD

**Issue by RovingSea** [spring-projects/spring-framework#28893]
Recently, I want to use @Exceptionhandler to handle different exceptions, but I found that HttpMediaTypeException and UnsupportedMediaTypeException were not handled by my UnsupportedMediaTypeExceptionHandler, 
![_) 8WWZ~RMFRPDFZ9R%15 8](https://user-images.githubusercontent.com/69103691/181920507-ec72481b-5349-4dae-8f14-6ae6622206f2.png)

but caught by my UnexpectedExceptionHandlerHandler
![R%3_LLD3Q_1@$}V3%L%V62P](https://user-images.githubusercontent.com/69103691/181920520-9b2eecd4-d11f-40de-a205-aaa269c2ad68.png)

Then I found the reason is ExceptionHandlerExceptionResolver.getExceptionHandlerMethod(@Nullable HandlerMethod handlerMethod, Exception exception)  when processing,
![AOO2_@N ~RM0~O ~0S7C}A](https://user-images.githubusercontent.com/69103691/181920668-e656ca5f-4306-49e3-a7f3-37b6012288e4.png)

it executed in sequence according to the key order of the Map
![0B$%88{MVF@O6S$9E%Q7}PR](https://user-images.githubusercontent.com/69103691/181920651-5f66ba1f-4257-4969-958e-50ac962db250.png)

The UnexpectedExceptionHandlerHandler was catch any exception, and it was in front of the UnsupportedMediaTypeExceptionHandler. That's why it caused such a tragedy, so I want to ask how to make my UnexpectedExceptionHandlerHandler execute finally.

At present, my method is to rename my UnexpectedExceptionHandlerHandler to ZzUnexpectedExceptionHandlerHandler to ensure its final execution😀😀😀

**Comment by RovingSea** [comment]
If it can't achieve through the existing code, can developers judge the locking type first and then execute the added @ExceptionHandler method?

**Comment by kse-music** [comment]
you can set order annotation or implements Ordered interface
````
@Order(0)
public class UnsupportedMediaTypeExceptionHandler {}
````

**Comment by RovingSea** [comment]
I tried, but it didn't work

**Comment by RovingSea** [comment]
and set @Order(Integer.MIN_VALUE)

**Comment by RovingSea** [comment]
> you can set order annotation or implements Ordered interface
> 
> ```
> @Order(0)
> public class UnsupportedMediaTypeExceptionHandler {}
> ```

I tried, but it didn't work, and set @Order(Integer.MIN_VALUE)

**Comment by RovingSea** [comment]
Today, I chose a better method, which is to add @Order(Ordered.HIGHEST_PRECEDENCE) to other ExceptionHandler. 😅😅
