### ISSUE TITLE
 Can you provide uriEncode method in Stringutils?

### ISSUE THREAD

**Issue by 523179414** [spring-projects/spring-framework#28917]
The decode () method in UriUtils calls uriDecode () in stringutils, but there is no uriEecode () method in Stringutils.  Can you provide uriEncode method in Stringutils?

**Comment by snicoll** [comment]
Thanks for the suggestion. The Javadoc of StringUtils states:

> Mainly for internal use within the framework

We prefer to add additional methods to our internal utility when we have a need ourselves.
