### ISSUE TITLE
@RequestPart with array of MultipartFile doesn't raise exception when no file part is received

### ISSUE THREAD

**Issue by sunmaolin** [spring-projects/spring-framework#28942]
public void upload(@RequestPart MultipartFile[] files){ ...}

The above comments @RequestPart, Default property required=true.
When I receive an array of files, if the files property is not passed, the check still passes, because reading the source code shows that if the files property is not passed, the empty array is returned instead of null.

MultipartResolutionDelegate.java
![image](https://user-images.githubusercontent.com/55195813/183624265-7787f478-9522-403f-8954-2ba92273dbef.png)

RequestPartMethodArgumentResolver.java
![image](https://user-images.githubusercontent.com/55195813/183624384-4f593784-0d56-4943-b544-dd16ea51ace6.png)

**Comment by bclozel** [comment]
I can't reproduce the behavior you're explaining here with a Spring Boot 3.0 application.

Can you share a sample project that reproduces the problem, ideally minimal and starting from https://start.spring.io?
Thanks

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
