### ISSUE TITLE
resttemplate customized charset

### ISSUE THREAD

**Issue by fightzhong** [spring-projects/spring-framework#28956]
code in org.springframework.http.converter.FormHttpMessageConverter#writeMultipart

I use resttemplate to upload images, in alicloud oss server, If the encoding format is actively specified, an error will be returned

Can a configuration be added to allow the user to choose whether to actively increase the character set? Automatically add character set by default, but we can remove the character by cconfiguration?

I know that this active addition of character sets is a standard practice, but it will be less flexible in the case of hard writing
![image](https://user-images.githubusercontent.com/36877901/184329333-df7d13f4-a541-4b7d-b203-f3736e1c88ae.png)

**Comment by rstoyanchev** [comment]
As of #25885, we no longer add a charset parameter if the charset is UTF-8 or US-ASCII, which is used by default we use UTF-8, which means there should be no charset parameter unless you set it explicitly.
