### ISSUE TITLE
The corresponding file is placed in the dependent jar

### ISSUE THREAD

**Issue by firekirin67** [spring-projects/spring-framework#28960]
When I use classpath* : \*\*/mapper/\*. xml configuration searches for files and finds no corresponding files, but when configured to classpath* : com/\*\*/mapper/\*. xml can find the corresponding file.

What is the logical difference between these two configurations that results in different results.
The corresponding file is placed in the dependent jar.
spring boot version 2.7.2

**Comment by bclozel** [comment]
Please provide a sample application reproducing the problem, something that we can git clone and run.

Thanks!

**Comment by firekirin67** [comment]
Thank you for your reply

Project Address: https://github.com/firekirin67/classpath_test.git

The project uses the mybatis-plus ORM framework, an extended version of mybaits.
Configured in application. yml
  mybatis-plus:
    mapper-location: classpath*:**/mapper/*.xml

Here the Resourcepatternresolver is used internally to search for matches

**Comment by firekirin67** [comment]
When I read Pathmatchingresourcepatternresolver, the property configuration values described earlier are indeed different in their implementation.

It uses the classloader. class of the current class. The getResources method implementation.

When configuring \*\*/mapper/\* . XML, which is passed to the classloader. The getResources method is an empty string, gets the Classpath Directory, and the PATHMATCHINGRESOURCEPATTERNRESOLVER code retrieves the path of the current class object to its package and the jar package corresponding to the ExtClassLoader. The only thing you get from getresources is that the Classpath Directory doesn't get the file path of the dependencies under the Classpath package.

When using“com/\*\*/mapper/\*.xml” to match the search, the JVM's own implementation retrieves the dependency files in the Classpath and gets the corresponding dependency files. The pathmatching Resourcepatternresolver then performed a second file retrieval match

**Comment by bclozel** [comment]
I think this works as designed from a Spring perspective. Depending on the resource prefix being used, a different resolver will be used and resource resolution will be different. See https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#resources-resourcepatternresolver

If you disagree somehow with the behavior or the documentation you should reach out to the mybatis-plus-boot-starter maintainers as I don't think that Spring Boot is in charge of this configuration property.

Thanks!

**Comment by firekirin67** [comment]
Thank you for your reply
