### ISSUE TITLE
Remove `AopProxyUtils#completeJdkProxyInterfaces`

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#28998]
Follow-up of #28980 since it should not be useful anymore now that related proxies are inferred.

**Comment by sdeleuze** [comment]
@snicoll Maybe we should keep it (potentially with an updated Javadoc) for the manual proxy creation that can't be inferred?

**Comment by snicoll** [comment]
We could. I still don't like the current method arrangement. It's consistent with similar methods in this class but the consumers of the new method could use something a bit more explicit. 

I'd like to see something like `hints.proxies.registerJdkProxy(MyProxy.class, asSpringJdkProxy())` or something like that where `asSpringJdkProxy` is a consumer of the builder, adding the 3 interfaces.

**Comment by sdeleuze** [comment]
On one side, I am also bothered by the lack of discoverability of this `AopProxyUtils#completeJdkProxyInterfaces` method, and it can be tempting to add a more explicit method in `ProxyHints` and/or `JdkProxyHint`, but those are in `spring-core` and `SpringProxy` and `Advised` lives in `spring-aop`. We could technically create those from `String` but I am not comfortable with that.

Also since this is now not a first class concern since most of them should be inferred, I am not sure we should add to our API such methods. Current arrangement with `org.springframework.aot.hint.ProxyHints#registerJdkProxy(java.lang.Class<?>...)` Javadoc hinting using `AopProxyUtils#completeJdkProxyInterfaces` for AOP use cases is maybe the right level of visibility after all.

So unless you strongly disagree or I misunderstood your proposal, I plan to close this issue as won't fix and remove it from M6 bucket.

**Comment by snicoll** [comment]
I think you misunderstood it, indeed. I am not talking about adding something to the core hint API (that would be a conceptual cycle). I am rather advocating that `spring-aop` provides a first-class, idiomatic method that allows to register a JDK proxy as an AOP proxy. I believe that the method above achieves this scenario, something like:

```java
public static Consumer<Builder> asAopProxy() {
    return builder -> builder.proxiedInterfaces(SpringProxy.class, Advised.class, DecoratingProxy.class);
}
```

**Comment by sdeleuze** [comment]
Thanks for the additional details. I don't think `AopProxyUtils` should import hints APIs and creating a dedicated class in `spring-aop` for it seems too much for me as well. I would be for your proposal if there was a way to make it available directly in the hints API in `spring-core`. Since that's not the case, I think what we have currently is reasonable.
