### ISSUE TITLE
Remove call to requestCompleted in RequestMappingHandlerAdapter

### ISSUE THREAD

**Issue by wplong11** [spring-projects/spring-framework#29002]
`RequestMappingHandlerAdapter` calls `webRequest.requestCompleted();` even though the async request has not completed.

Is that intentional, or is it a bug?

https://github.com/spring-projects/spring-framework/blob/dd3e3b2989bb5fc3148298c70bdb183e44597355/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerAdapter.java#L906

**Comment by rstoyanchev** [comment]
This seems to have been added as part of 698f923fc3178bb9a35e1cb34c388d8703e45b99 but appears to be completely unrelated to the change, and other usages of this method are in more global places like `FrameworkServlet`, `RequestContextFilter`, and `RequestContextListener`. So it looks out of place in `RequestMappingHandlerAdapter`, and it's not clear why it was added. Removing it also does not cause any test failures.

In terms of async requests, `webRequest.requestCompleted` is also called in `FrameworkServlet` when the initial request dispatch exits, and that is also before the overall async request has completed. In that sense these `RequestAttributes` are per dispatcher, rather than per request (as it was originally before async requests).

Do you have a specific issue that you are experiencing?

Aside from that we should probably remove this call from `RequestMappingHandlerAdapter`. @jhoeller what do you think?

**Comment by wplong11** [comment]
@rstoyanchev I want to use RequestScope bean in a coroutine. For this, I created a SpringContext that restores the value in ThreadLocal when the Thread is changed. But ScopeNotActiveException was occured. 

```
INFO 0 --- [nio-0000-exec-1] c.e.c.controllers.TestController         : 1. 1
INFO 0 --- [DefaultExecutor] c.e.c.controllers.TestController         : Log message invocation failed: org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'scopedTarget.testService': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: Cannot ask for request attribute - request is not active anymore!
```


```kotlin
package com.example.coroutinemvctest.controllers

import kotlinx.coroutines.ThreadContextElement
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import mu.KotlinLogging
import org.springframework.stereotype.Controller
import org.springframework.stereotype.Service
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.context.annotation.RequestScope
import org.springframework.web.context.request.RequestAttributes
import org.springframework.web.context.request.RequestContextHolder
import kotlin.coroutines.AbstractCoroutineContextElement
import kotlin.coroutines.CoroutineContext

@Controller
class TestController(
    private val testService: TestService,
) {
    private val logger = KotlinLogging.logger { }

    @GetMapping("/hello")
    suspend fun hello(): String = withContext(SpringContext()){
        logger.info { "1. " + testService.id }

        delay(100)

        logger.info { "2. " + testService.id } // ScopeNotActiveException was occured

        return@withContext "HI"
    }
}

private var counter = 0

@RequestScope
@Service
class TestService {
    val id: Int = ++counter
}

class SpringContext(
    private val requestAttributes: RequestAttributes? = RequestContextHolder.getRequestAttributes(),
) : ThreadContextElement<RequestAttributes?>, AbstractCoroutineContextElement(Key) {
    companion object {
        object Key : CoroutineContext.Key<SpringContext>
    }

    override fun updateThreadContext(context: CoroutineContext): RequestAttributes? {
        val oldState = RequestContextHolder.getRequestAttributes()
        requestAttributes?.let {
            RequestContextHolder.setRequestAttributes(it)
        }

        return oldState
    }

    override fun restoreThreadContext(context: CoroutineContext, oldState: RequestAttributes?) {
        RequestContextHolder.setRequestAttributes(oldState)
    }
}
```

**Comment by rstoyanchev** [comment]
I'll go ahead and remove the call to `webRequest.requestCompleted()` in `RequestMappingHandlerAdapter` that doesn't seem to have a good reason to be there. 

That said, the same call will be still be made a little later in `FrameworkServlet`, on the way out from the initial REQUEST dispatch, and that does mean that you'll likely get the same result in your scenario. Generally, request scoped beans rely on `ThreadLocal` to the request, via `RequestContextHolder`, and that can only be done while we're on a Servlet container dispatch. For asynchronous request handling, we recommend keeping the objects you need in the controller and passing them to where they're needed.

**Comment by firekcc** [comment]
I have slove this problem，details please see [Cannot ask for request attribute - request is not active anymore!](https://github.com/firekcc/springboot/tree/main/practice/src/main/java/cc/firek/spring/practice/async)
