### ISSUE TITLE
Compiled JAR of Spring Context still contains javax imports even though the source code has been migrated to Jakarta

### ISSUE THREAD

**Issue by esivakumar18** [spring-projects/spring-framework#29003]
`Issue` :: Compiled JAR of Spring Context library still contains javax imports even though the source code has been migrated to Jakarta. Please find the difference below between the Source Code vs Compiled JAR.

`Source Code` ::
https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/validation/beanvalidation/LocalValidatorFactoryBean.java 
<img width="1461" alt="Spring Context Source Code " src="https://user-images.githubusercontent.com/23304630/186266075-fcc931d0-e68a-4fbd-b60d-acea0fecca1f.png">

`Compiled JAR` ::  
downloaded from https://mvnrepository.com/artifact/org.springframework/spring-context/5.3.22

<img width="1504" alt="Compiled Spring Context 5 3 22  JAR" src="https://user-images.githubusercontent.com/23304630/186266119-9ae53440-2e14-4ee2-8a35-eede2257ab45.png">

**Comment by bclozel** [comment]
The main branch has indeed moved to Jakarta but we haven't released a GA version for it on Maven Central, so we've only published 6.0.0-SNAPSHOT and Milestones on our own repo.spring.io. You can test that with a new project created on https://start.spring.io using Spring Boot 3.0 versions.
