### ISSUE TITLE
Refine `JacksonModulesRuntimeHints`

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#29001]

**Comment by snicoll** [comment]
Shouldn't the condition be on a Jackson class? Or the module as it's probably optional.

**Comment by sdeleuze** [comment]
I don't think so, the reflective instantiation is done in `Jackson2ObjectMapperBuilder` and here we are not doing a classpath check but a reachability one on the said builder.

**Comment by sdeleuze** [comment]
Good point, I will update accordingly.

**Comment by sdeleuze** [comment]
In fact, maybe the condition is ok with the builder but we should add a classpath check on the related modules since those are instantiated reflectively.
