### ISSUE TITLE
How does rsocket get the RSocketRequester according to the key in the context

### ISSUE THREAD

**Issue by sdack-cloud** [spring-projects/spring-framework#29004]
How does rsocket get the RSocketRequester according to the key in the context?

I'm using rsocket. I want to get the requester in context.

How to do this? Please provide some examples

webflux: 2.7.2

**Comment by rstoyanchev** [comment]
Is [this](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#rsocket-requester-server) what you're looking for? If not, please provide more details.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sdack-cloud** [comment]
How to find the corresponding RSocketRequester among numerous Rsocket links. Can information be obtained in context
