### ISSUE TITLE
Support jni-config.json generation

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-framework#29007]
While not needed by framework itself it'd be beneficial to create `jni` config with aot hints when application needs it so that you don't need to hand craft these config files.

**Comment by sdeleuze** [comment]
Indeed, allowing users to configure JNI hints on application side is IMO a relevant use case. I think this should be part of the GA but is not super high priority so even if we try to have a complete scope for M6, I move that one in the RC1 bucket (feel free to update if that's not accurate).

@snicoll As far as I remember from Spring Native, we should potentially be able to reuse `TypeHint` for this.

**Comment by sdeleuze** [comment]
@jvalkeal Do you need that for a specific library?

**Comment by jvalkeal** [comment]
I think only question really is if we want to 1. fully reuse `ReflectionHints` for jni as in graal format is documented to be same or 2. duplicate existing reflection as new `JniHints`.

Latter is a bit more work for us but would be safer in future if graal makes a choice to separate reflection/jni formats.

**Comment by jvalkeal** [comment]
@sdeleuze for jna used in jline. I've been talking with @snicoll and he asked me to create this ticket.

**Comment by sdeleuze** [comment]
@jvalkeal Ok please contribute a PR I will review it.
