### ISSUE TITLE
Request to improve KotlinSerializationJsonHttpMessageConverter logic in RestTemplate

### ISSUE THREAD

**Issue by meloning** [spring-projects/spring-framework#29008]
**Affects:** 5.3.22 (below 5.3.22)

---

Hello,
I was using the Kotlinx.serialization module well because of Spring registered `KotlinSerializationJsonHttpMessageConverter` through `WebMvcConfigurationSupport.addDefaultHttpMessageConverters`

However, even though I added the Kotlinx.Serialization module, it was not available in RestTemplate.
```Groovy
implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0")
```

After analyzing why, only Jackson, which is the default serialization, was registered due to the **`if-else if`** logic as shown below, so Kotlinx.Serialization could not be used.

![image](https://user-images.githubusercontent.com/50299857/186432443-928f589b-1fa0-418a-a719-4cbd836a1a08.png)

I can temporarily solve it like the configuration below.
![image](https://user-images.githubusercontent.com/50299857/186434334-ccfd9f73-a7d3-472c-92af-16649dbf9b66.png)
![image](https://user-images.githubusercontent.com/50299857/186434563-d304e620-d776-4bea-ae27-fb700efc4106.png)

I solved it, but I think it is very inconvenient to have to add KotlinSerializationJsonHttpMessageConverter to use kotlinx.serialization.

I as with WebMvcConfigurationSupport.addDefaultHttpMessageConverters, when the Kotlinx.Serialization module does not exist, it is hoped that Jackson2 Serialization will be used by default.
![image](https://user-images.githubusercontent.com/50299857/186436699-eb8dd559-b0cc-41a6-a037-4391d58efcef.png)

I'm going to post a PR on this issue.

please check.
thank you

**Comment by meloning** [comment]
Additionally, I checked the comments on RestTemplate to consider using WebClient.
```
NOTE: As of 5.0 this class is in maintenance mode, with only minor requests for changes and bugs to be accepted going forward. Please, consider using the org.springframework.web.reactive.client.WebClient which has a more modern API and supports sync, async, and streaming scenarios.
```

I checked the KotlinSerialization operation through the `BaseDefaultCodecs.initObjectReaders` method.
![image](https://user-images.githubusercontent.com/50299857/186439185-5cc1d3e9-4404-4ac5-96e5-5f4f39aa1d53.png)
![image](https://user-images.githubusercontent.com/50299857/186439651-7106f951-5a80-4d6f-9d0a-da84bcbf704f.png)

Through the above, the introduction of WebClient can be considered, but it is hard to introduce due to the project situation and schedule.

Please allow RestTemplate to use Kotlinx.Serialization by default.

**Comment by meloning** [comment]
@sdeleuze 
Hello, 
Thank you for checking the issue and merging. I am very happy that it has even been distributed.
However, I am asking because I am not included as a contributor in the release notes.
If you're okay, please add me as a contributor to the release notes.

**Comment by sdeleuze** [comment]
Sure, [done](https://github.com/spring-projects/spring-framework/releases/tag/v5.3.23) not sure why that was missed. Thanks for your contribution.
