### ISSUE TITLE
Autowire failed in some cases

### ISSUE THREAD

**Issue by wangweng** [spring-projects/spring-framework#29016]
**Affects:** \<5.3.22>

---

### Under normal conditions，everything is ok:

![image](https://user-images.githubusercontent.com/45789597/186793733-c4552b0b-0d83-4a45-89d1-03aec9e11571.png)
![image](https://user-images.githubusercontent.com/45789597/186794027-08f8c1fe-a03c-4c5c-909f-dc793897baf3.png)
![image](https://user-images.githubusercontent.com/45789597/186793793-f7105bb7-2252-496a-ae17-2891d2b08121.png)
![image](https://user-images.githubusercontent.com/45789597/186793827-3db24c4d-d0eb-4a05-9ec1-09028b74dd3f.png)
![image](https://user-images.githubusercontent.com/45789597/186794096-63a37210-e359-424b-96b7-d09901ffe0ef.png)

### But if I modify the getter like this:

![image](https://user-images.githubusercontent.com/45789597/186794303-3cf07dc1-b3f2-46e5-b291-974e5a51a958.png)

### autowire will fail:

![image](https://user-images.githubusercontent.com/45789597/186794475-c549498a-0b99-4326-a2c7-105f0eef4736.png)

### And in this case it also fails:

![image](https://user-images.githubusercontent.com/45789597/186794649-7d75957f-875f-47ac-b492-816c74c72f70.png)

### But sometimes it works:

![image](https://user-images.githubusercontent.com/45789597/186794862-c77ced46-940d-4dbe-940b-168cc8f35baf.png)

**or**

![image](https://user-images.githubusercontent.com/45789597/186794930-5d2ecc33-8071-4f31-888b-a1cd9c2b96ab.png)
![image](https://user-images.githubusercontent.com/45789597/186794952-274b10c6-bb35-4f9c-a698-718d27ba9887.png)

**Comment by coding2world** [comment]
You can display you code repo and use branch distinguishing bad code or good.

**Comment by coding2world** [comment]
@wangweng  
You can see the reason in this method named `org.springframework.beans.BeanUtils#isSimpleValueType`.

```java

public static boolean isSimpleProperty(Class<?> type) {
		Assert.notNull(type, "'type' must not be null");
		return isSimpleValueType(type) || (type.isArray() && isSimpleValueType(type.getComponentType()));
	}

	public static boolean isSimpleValueType(Class<?> type) {
		return (Void.class != type && void.class != type &&
				(ClassUtils.isPrimitiveOrWrapper(type) ||
				Enum.class.isAssignableFrom(type) ||
				CharSequence.class.isAssignableFrom(type) ||
				Number.class.isAssignableFrom(type) ||
				Date.class.isAssignableFrom(type) ||
				Temporal.class.isAssignableFrom(type) ||
				URI.class == type ||
				URL.class == type ||
				Locale.class == type ||
				Class.class == type));
	}

```

**Comment by wangweng** [comment]
> @wangweng You can see the reason in this method named `org.springframework.beans.BeanUtils#isSimpleValueType`.
> 
> ```java
> public static boolean isSimpleProperty(Class<?> type) {
> 		Assert.notNull(type, "'type' must not be null");
> 		return isSimpleValueType(type) || (type.isArray() && isSimpleValueType(type.getComponentType()));
> 	}
> 
> public static boolean isSimpleValueType(Class<?> type) {
>       return (Void.class != type && void.class != type &&
> 		(ClassUtils.isPrimitiveOrWrapper(type) ||
> 		Enum.class.isAssignableFrom(type) ||
> 		CharSequence.class.isAssignableFrom(type) ||
> 		Number.class.isAssignableFrom(type) ||
> 		Date.class.isAssignableFrom(type) ||
> 		Temporal.class.isAssignableFrom(type) ||
> 		URI.class == type ||
> 		URL.class == type ||
> 		Locale.class == type ||
> 		Class.class == type));
> }
> ```

Okay, I got it. In my intuition, I think it is only related to setters. But actually it use getters to check if the given type represents a "simple" property. That's what makes me confused. Thank you very much!

**Comment by wangweng** [comment]
> 
老哥，非常感谢，我看到你ip是在上海，早知道我就用中文跟你沟通了，我英语比较烂😂，虽然知道原因了，但是我感觉这里还是有点怪怪的，不知道能不能只用setter来做判断，这样逻辑上也比较一致，自动装配通过setter注入就只与setter有关。因为有时候万一想控制get的逻辑就可能会出现这个错误。

**Comment by wangweng** [comment]
> @wangweng You can see the reason in this method named `org.springframework.beans.BeanUtils#isSimpleValueType`.
> 
> ```java
> public static boolean isSimpleProperty(Class<?> type) {
> 		Assert.notNull(type, "'type' must not be null");
> 		return isSimpleValueType(type) || (type.isArray() && isSimpleValueType(type.getComponentType()));
> 	}
> 
> public static boolean isSimpleValueType(Class<?> type) {
>       return (Void.class != type && void.class != type &&
> 		(ClassUtils.isPrimitiveOrWrapper(type) ||
> 		Enum.class.isAssignableFrom(type) ||
> 		CharSequence.class.isAssignableFrom(type) ||
> 		Number.class.isAssignableFrom(type) ||
> 		Date.class.isAssignableFrom(type) ||
> 		Temporal.class.isAssignableFrom(type) ||
> 		URI.class == type ||
> 		URL.class == type ||
> 		Locale.class == type ||
> 		Class.class == type));
> }
> ```

老哥，非常感谢，我看到你ip是在上海，早知道我就用中文跟你沟通了，我英语比较烂😂，虽然知道原因了，但是我感觉这里还是有点怪怪的，不知道能不能只用setter来做判断，这样逻辑上也比较一致，自动装配通过setter注入就只与setter有关。因为有时候万一想控制get的逻辑就可能会出现这个错误。

**Comment by coding2world** [comment]
@wangweng  just practice english. 😂

**Comment by leihuazhe** [comment]
May be you can see this: 
- https://stackoverflow.com/questions/9724490/why-cant-spring-autowire-simple-types
- https://stackoverflow.com/questions/52136756/you-cannot-autowire-so-called-simple-properties-such-as-primitives-strings-and

**Comment by leihuazhe** [comment]
> > @wangweng You can see the reason in this method named `org.springframework.beans.BeanUtils#isSimpleValueType`.
> > ```java
> > public static boolean isSimpleProperty(Class<?> type) {
> > 		Assert.notNull(type, "'type' must not be null");
> > 		return isSimpleValueType(type) || (type.isArray() && isSimpleValueType(type.getComponentType()));
> > 	}
> > 
> > public static boolean isSimpleValueType(Class<?> type) {
> >       return (Void.class != type && void.class != type &&
> > 		(ClassUtils.isPrimitiveOrWrapper(type) ||
> > 		Enum.class.isAssignableFrom(type) ||
> > 		CharSequence.class.isAssignableFrom(type) ||
> > 		Number.class.isAssignableFrom(type) ||
> > 		Date.class.isAssignableFrom(type) ||
> > 		Temporal.class.isAssignableFrom(type) ||
> > 		URI.class == type ||
> > 		URL.class == type ||
> > 		Locale.class == type ||
> > 		Class.class == type));
> > }
> > ```
> 
> 老哥，非常感谢，我看到你ip是在上海，早知道我就用中文跟你沟通了，我英语比较烂😂，虽然知道原因了，但是我感觉这里还是有点怪怪的，不知道能不能只用setter来做判断，这样逻辑上也比较一致，自动装配通过setter注入就只与setter有关。因为有时候万一想控制get的逻辑就可能会出现这个错误。

Beacuse the Spring framework use the java Introspector.getBeanInfo(Class) to get the Bean info.It's the Introspector mechanism uses the Getter and Setter to determine the write method and the read method of the bean you defined.

**Comment by wangweng** [comment]
> > > @wangweng You can see the reason in this method named `org.springframework.beans.BeanUtils#isSimpleValueType`.
> > > ```java
> > > public static boolean isSimpleProperty(Class<?> type) {
> > > 		Assert.notNull(type, "'type' must not be null");
> > > 		return isSimpleValueType(type) || (type.isArray() && isSimpleValueType(type.getComponentType()));
> > > 	}
> > > 
> > > public static boolean isSimpleValueType(Class<?> type) {
> > >       return (Void.class != type && void.class != type &&
> > > 		(ClassUtils.isPrimitiveOrWrapper(type) ||
> > > 		Enum.class.isAssignableFrom(type) ||
> > > 		CharSequence.class.isAssignableFrom(type) ||
> > > 		Number.class.isAssignableFrom(type) ||
> > > 		Date.class.isAssignableFrom(type) ||
> > > 		Temporal.class.isAssignableFrom(type) ||
> > > 		URI.class == type ||
> > > 		URL.class == type ||
> > > 		Locale.class == type ||
> > > 		Class.class == type));
> > > }
> > > ```
> > 
> > 
> > 老哥，非常感谢，我看到你ip是在上海，早知道我就用中文跟你沟通了，我英语比较烂😂，虽然知道原因了，但是我感觉这里还是有点怪怪的，不知道能不能只用setter来做判断，这样逻辑上也比较一致，自动装配通过setter注入就只与setter有关。因为有时候万一想控制get的逻辑就可能会出现这个错误。
> 
> Beacuse the Spring framework uses the java Introspector.getBeanInfo(Class) to get the Bean info.It's the Introspector mechanism uses the Getter and Setter to determine the write method and the read method of the bean you defined.

okay, I see. Thank you!

**Comment by bclozel** [comment]
Please use StackOverflow for questions and discussions.
