### ISSUE TITLE
Issue with suppressed exception handling in DefaultSingletonBeanRegistry#getSingleton(String,ObjectFactory)

### ISSUE THREAD

**Issue by tangmingze7280** [spring-projects/spring-framework#29042]
**Affects:** 5.2.x

For bugs ,I found an invalid code from  `DefaultSingletonBeanRegistry#getSingleton(String, ObjectFactory<?>)`. There is a problem with exception handling in the above method. I need a screenshot to show this.

![image](https://user-images.githubusercontent.com/44865221/187328737-7faa42e6-de6e-45df-827b-f342393bbae7.png)

This block of code will not be executed:

```java
if (recordSuppressedExceptions) {
	for (Exception suppressedException : this.suppressedExceptions) {
		ex.addRelatedCause(suppressedException);
	}
}
```

As mentioned above, this is a minor problem that I discovered when I re-analyzed the Spring lifecycle source code.

**Comment by snicoll** [comment]
The boolean initialization works by making sure that the list is `null`. The list is fed by `onSuppressedException`. When you look at the code from top to bottom, it gives a feeling that the list is always empty but there is callback to the method above while the bean (or any of its dependency) is created.
