### ISSUE TITLE
Use methods from JDK to implement array hash methods in ObjectUtils

### ISSUE THREAD

**Issue by j3graham** [spring-projects/spring-framework#29051]
`java.util.Arrays` has methods for hashCode generation on primitive arrays that are equivalent to `nullSafeHashCode`

They do however calculate different hash values. If this was tolerable, then the JDK methods could be used.

**Comment by j3graham** [comment]
Found an existing pr - #25594

**Comment by snicoll** [comment]
The PR has been declined so let's reconsider this particular change.
