### ISSUE TITLE
Stop using RuntimeHintsUtils to register SynthesizedAnnotation proxies

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#29059]
Due to #29053, we should stop using `RuntimeHintsUtils` to register `SynthesizedAnnotation` proxies and verify that all smoke tests for our native image support still pass.

See also:

- #29058

**Comment by sdeleuze** [comment]
Temporarily [reverted](b8c1fc920275d69185e05ca89afb1dbeefe417e3) in order to let the time to portfolio projects to remove `RuntimeHintsUtils` usage.

**Comment by snicoll** [comment]
Shouldn't #29058 only be reopened? I understand that a single commit removed the usage and the class but perhaps the usage can be removed and this issue be closed?

**Comment by sdeleuze** [comment]
I should be able to restore the commit end of the day, so I think it is ok to just wait that to restore the original commit that will close those 2 issues at the same time.

**Comment by sdeleuze** [comment]
After a second thought, I will follow your proposal and refine the commit to just remove the usage. I does not hurt to have 2 separated commits indeed.
