### ISSUE TITLE
Improve support and documentation for the "default" bean definition profile name

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#29071]
The _default_ profile name is a `protected` constant: `AbstractEnvironment.RESERVED_DEFAULT_PROFILE_NAME` (`"default"`).

It is not documented in a public user-facing manner.

For example, it is not documented in `@Profile` and potentially in other pertinent locations.

We should improve that.

**Comment by bhuvanaindukuri** [comment]
To me, the concern is not just documentation. It is also the ability to use this variable or to get the name of the default profile. For example, to define a certain bean for default profile. Agree? If yes would this change also qualify as an enhancement?

**Comment by 1997sanket** [comment]
Hi @sbrannen I am new to open source and want to contribute. Can I try with the documentation change ?

**Comment by sbrannen** [comment]
Hi @1997sanket,

Thanks for the offer.

However, since we are considering more than a documentation change, we've yet to decide on the exact scope of this issue. In light of that, one of the core committers will likely take care of this issue.

Regards,

Sam
