### ISSUE TITLE
DisposableBeanAdapter requires Class#getMethods

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#29077]
The agent tests validating that the necessary reflection hints have been provided fail when a destroy method is set. The reason is that `DisposableBeanAdapter` relies on `BeanUtils#findMethodWithMinimalParameters` that itself calls `getMethods` on the target class.

It's unclear if GraalVM is supposed to return only the methods that have explicit hints, or if this method should fail if the wider "introspect declared methods" hint isn't set.

The registration of the hint itself is [very basic for now](https://github.com/spring-projects/spring-framework/blob/3b36171926d7b6b9f09abaaac3260f4e92200e90/spring-beans/src/main/java/org/springframework/beans/factory/aot/BeanDefinitionPropertiesCodeGenerator.java#L146), so whatever we end up doing, it would be nice if the logic was harmonized.

**Comment by bclozel** [comment]
I've created #29091 to align the agent's behavior with GraalVM. Maybe this is superseded?

**Comment by snicoll** [comment]
Thanks @bclozel. I've removed the workaround in the agent test in 1e8017107a2fd6 and the test passes now.
