### ISSUE TITLE
Spring Cache multiget and multiset

### ISSUE THREAD

**Issue by someshkoli** [spring-projects/spring-framework#29109]
Most of the cache providers ability to perform a multiget/multiset. Been trying to implement the same using spring Cache but I believe there's no support for it yet. Wanted to know if there are any other alternatives to this ? If not then have we considered building it ? 
Would be happy to help here and implement this feature after a through discussions wrt deliverables :raised_hands:

**Comment by snicoll** [comment]
I am not sure. I don't know what you mean by multiget and how that would look like. Please check if that's a duplicate of #23221

**Comment by someshkoli** [comment]
Its exactly I was looking for, thanks. closing this
