### ISSUE TITLE
ObjectFactory<List> with specified constructor args occurs error

### ISSUE THREAD

**Issue by qrqhuang** [spring-projects/spring-framework#29110]
`ObjectProvider` support a method to get bean with specified args.  (#18529)

But I have a collection beans to autowired, Use `ObjectProvider<List<T>>`,  but now it looks like the `args` not effect, and throw 
`No qualifying bean` for constructor. 

spring version: 4.3.25.RELEASE

**Comment by qrqhuang** [comment]
@snicoll Use spring 5.3.22,  still the same error.


model
```java
@Data
public class OrderContext {

    private String orderNo;
}

```

component
```java
@Component
@Scope(value = BeanDefinition.SCOPE_PROTOTYPE)
public class OrderTask {

    private OrderContext orderContext;

    public OrderTask(OrderContext orderContext) {
        this.orderContext = orderContext;
    }
}
```

test case.  should not throw  error
```java
    @Autowired
    private ObjectProvider<List<OrderTask>> objectProviders;

    @Test
    void testProviders() {
        OrderContext orderContext = new OrderContext();
        orderContext.setOrderNo("222");
        objectProviders.getObject(orderContext);
    }
```

**Comment by snicoll** [comment]
I don't understand what you're trying to achieve with a `List` on `ObjectProvider`. ObjectProvider` should be used against the target bean and handle the list use case using `stream`.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
