### ISSUE TITLE
After upgrading to soring framework 5.3.21, the response body us not auto converted to json

### ISSUE THREAD

**Issue by abe0503** [spring-projects/spring-framework#29142]
After upgrading to spring framework 5.3.21, the response body is not auto converted to json if content type use is other than application/json.

This is causing issues on client side when decoding a json due to invalud data:

**Comment by abe0503** [comment]
![image](https://user-images.githubusercontent.com/113435141/189888935-c65b1ecf-31aa-466b-ad0a-b7cd1ec538a8.jpeg)

**Comment by bclozel** [comment]
I'm not sure I understand. Do you have a sample application (ideally, minimal and created with https://start.spring.io) that demonstrates the issue?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by abe0503** [comment]
Oh sorry, i figured it out. There was a deprecated classs which gets the file extension and use it as negotiation strategy for the content type.

**Comment by bclozel** [comment]
ok thanks for letting us know, I'm glad this is sorted out on your side.
