### ISSUE TITLE
StreamingResponseBody is present in APIDocs but not accessible?

### ISSUE THREAD

**Issue by kouta-kun** [spring-projects/spring-framework#29172]
**Affects:** 6.0.0-M6

---

Hi! I'm currently undergoing an upgrade from Spring Boot 2.7.3 to Spring Boot 3.0.0-SNAPSHOT. One of the main problems I'm facing is that many of our endpoints make use of StreamingResponseBody, and it's still present in the [Spring Framework 6.0.0-M6 JavaDocs](https://docs.spring.io/spring-framework/docs/6.0.0-M6/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/StreamingResponseBody.html) but it doesn't seem to be accessible for me. Is there any chance it was split off into another maven package or something like that?

**Comment by kouta-kun** [comment]
Sorry, just figured out that it the newest Spring Boot doesn't bring in spring.webmvc automatically.

**Comment by snicoll** [comment]
> the newest Spring Boot doesn't bring in spring.webmvc automatically

I don't understand what you mean by that. There hasn't been any change in that area that I am aware of.

**Comment by kouta-kun** [comment]
> > the newest Spring Boot doesn't bring in spring.webmvc automatically
> 
> I don't understand what you mean by that. There hasn't been any change in that area that I am aware of.

You're actually right, sorry. It was brought in as a transitive dependency of spring-ws-core which we removed during the same process as the Java 17 update :P
