### ISSUE TITLE
Spring MVC should return 400 BAD_REQUEST on missing header [rfc2616].

### ISSUE THREAD

**Issue by zekicelik** [spring-projects/spring-framework#29218]
Mvm return 500 Internal Server Error if a requeired header is missinng & client shoul update request.
10.4.1 400 Bad Request 
The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

**Comment by poutsma** [comment]
Which specific header is missing? A 400 response is applicable when some headers are missing, but definitely not all cases.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
