### ISSUE TITLE
Add `ConstantReadableJavaField` caching in `ConstantFieldSubstitutionProcessor`

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#29250]
As discussed in https://github.com/oracle/graal/issues/5098, GraalVM expects a unique instance of `ConstantReadableJavaField` per field, so we need to use proper caching.

**Comment by nhandev552** [comment]
Why I don't see this code in Spring Framework 6.0.3?

I also got issue in version 6.0.3: https://github.com/oracle/graal/issues/5098

**Comment by sbrannen** [comment]
> Why I don't see this code in Spring Framework 6.0.3?

That code was superseded in commit 0889e47608a98e36ac88a904962adf0ecbd602a4 by code introduced in conjunction with #29081.
