### ISSUE TITLE
ResourcePatternHints should not be merged in a single json entry

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#29270]
As reported by #28977

The `ResourcePatternHints` is a container for `includes` and `excludes` and multiple `ResourcePatternHints` can be registered. It's possible that callers may expect that these includes and excludes are related, however, when the JSON is written all excludes and all includes are included together. See [ResourceHintsPredicates.AggregatedResourcePatternHints](https://github.com/spring-projects/spring-framework/blob/4556895e6e97931c642e30c8c874b690708f2ea1/spring-core/src/main/java/org/springframework/aot/hint/predicate/ResourceHintsPredicates.java#L101) for an example of the flattening that needs to occur when using the pattern hints.

**Comment by bdshadow** [comment]
I want to help with this, but please advise on what is expected.
For example, let's say that we have the following resource hints:
```java
ResourceHints hints = new ResourceHints();
hints.registerPattern(hint -> hint.includes("com/*").excludes("com/example/*"));
hints.registerPattern(hint -> hint.includes("com/example/*/all.properties").excludes("com/example/ignore/all.properties"));
```
Currently, it produces:
```java
{
	"resources": {
		"includes": [
			{ "pattern": "\\Q/\\E"},
			{ "pattern": "\\Qcom/\\E.*"},
			{ "pattern": "\\Qcom\\E"},
			{ "pattern": "\\Qcom/example/\\E.*\\Q/all.properties\\E"},
			{ "pattern": "\\Qcom/example\\E"}
		],
		"excludes": [
			{ "pattern": "\\Qcom/example/\\E.*"},
			{ "pattern": "\\Qcom/example/ignore/all.properties\\E"}
		]
	}
}
```
 Am I right that it's supposed to be the following way:
```java
{
	"resources": {
		"includes": [
			{ "pattern": "\\Q/\\E"},
			{ "pattern": "\\Qcom/\\E.*"},
			{ "pattern": "\\Qcom\\E"},
		],
		"excludes": [
			{ "pattern": "\\Qcom/example/\\E.*"},
			{ "pattern": "\\Qcom/example/ignore/all.properties\\E"}
		]
	}
}
```
I think it can be quite complicated in some cases to filter it out properly. However, a simple filter is possible - for example, if it's the same or if a particular "include" is of a particular pattern of some "exclude" - then remove this "include".

Alsoб just for a note, here is the corresponding implementation in the graalvm: https://github.com/oracle/graal/pull/2912/files#diff-4b973ff5fd08418824ad1f4c7ce54a757b0641094f899f02a1c54fdc112739f2R263. It goes the same way as [ResourceHintsPredicates.AggregatedResourcePatternHints](https://github.com/spring-projects/spring-framework/blob/4556895e6e97931c642e30c8c874b690708f2ea1/spring-core/src/main/java/org/springframework/aot/hint/predicate/ResourceHintsPredicates.java#L101), so making such filtering is better but not necessary. I meanб this ticket doesn't look like a bug to me (but probably, I'm missing smth).

**Comment by snicoll** [comment]
@bdshadow you are correct. I think the assumption made in https://github.com/spring-projects/spring-framework/issues/28977 was wrong. I think @philwebb thought that you could register an array of includes/excludes pair but, looking [at the documentation](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Resources/) it really is an array of includes and an array of excludes.

As such, I believe the current behavior is correct based on that constraints. Thanks for bringing this up!

**Comment by philwebb** [comment]
> I think @philwebb thought that you could register an array of includes/excludes pair

No, I didn't think that, but I was worried that users might as `include` and `exclude` are on `ResourcePatternHints`. I think I was thinking a `ResourceHints.registerInclude` and `ResourceHints.registerExclude` method might be better to show that includes/excludes are completely independent.

Given that the API is out there and nobody seems to have hit the issue it looks like my fears were unfounded.

**Comment by bclozel** [comment]
Excludes will go away in #31340 as GraalVM will simplify support on the resource-config format.
