### ISSUE TITLE
Add DataFieldMaxValueIncrementer for MariaDB

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-framework#29306]
Spring Framework started treating MariaDB as an independent database here: https://github.com/spring-projects/spring-framework/pull/28355. However, it does not provide a dedicated `DataFieldMaxValueIncrementer` for it.

To give a bit of context, we have the same request in Spring Batch (to treat MariaDB as independent database, see https://github.com/spring-projects/spring-batch/issues/3891), but due to the lack of a dedicated incrementer, we would have to use the MySQL one, which feels odd given the intent in the first place. Do you agree?

**Comment by jhoeller** [comment]
Superseded by PR #29379.
