### ISSUE TITLE
Decide on whether to rename ProblemDetail to ProblemDetails

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-framework#29303]
Keep it consistent with RFC title [Problem Details for HTTP APIs](https://www.rfc-editor.org/rfc/rfc7807)

**Comment by rstoyanchev** [comment]
Thanks for the comment. 

The spec opens with this:
```
   This document defines a "problem detail" as a way to carry machine-
   readable details of errors in a HTTP response to avoid the need to
   define new error response formats for HTTP APIs.
```

The double quotes around "problem detail" in particular show this isn't by accident. 

In singular form it refers to the fact there is one problem to explain, you can choose one HTTP status and reason, and there is one "detail", String field. That's the problem and the explanation for it. In plural form, it refers to all the other fields included in the response, which are auxiliary details.

So there is a bit of an overlap of terminology IMO. The spec could have used a different name for the "detail" field, perhaps "cause" or similar. Be it as it is, I think neither `ProblemDetail` nor `ProblemDetails" is wrong. The former being more focused on the (single) detail for the problem cause, and the latter on all the fields in the response.

We'll try and finalize this for RC2 next week, but comments welcome, in the mean time.

**Comment by membersound** [comment]
I would see the `ProblemDetail` class as a wrapper object, which should be singular.
Compare it with shopping: you have several products, and group them into a basket (not into baskets). Or you group them into an order (not orders).

Also, http APIs are usually kept in singular names as best practice.

In contrast, the naming `ProblemDetail**s**` could pretend that it contains multiple `ProblemDetail` objects as an array. Which is not the plan afaik.

**Comment by quaff** [comment]
FYI: spring-security use `UserDetails` instead of `UserDetail`, and .net use `ProblemDetails` instead of `ProblemDetail`.

**Comment by membersound** [comment]
And AWS is using `ProblemDetail` (https://docs.aws.amazon.com/de_de/devicefarm/latest/APIReference/API_ProblemDetail.html). You probably find both ways 50:50.

**Comment by rstoyanchev** [comment]
The Spring Security example isn't something to go by. Yes, the same ending, but other than that, its own context and reasons. Let's stick to the case of RFC 7807. I've already laid out [my interpretation](https://github.com/spring-projects/spring-framework/issues/29303#issuecomment-1275825339) of the language used there. If you have any comments or thoughts on that, please share.

@membersound I take it you see this as the plural applying to both "problem" and "detail", and that there is only one problem to be detailed.

**Comment by vpavic** [comment]
FWIW, I agree with the current naming and interpretation outlined by @rstoyanchev.

The way I see it, this is a part of story that's basically about translating an exception (singular) to some specific representation of the underlying error. The translation is 1:1 so it seems natural to me to name the representation as `ProblemDetail` (singular again).

**Comment by rstoyanchev** [comment]
I'm closing this in favour of the current choice, `ProblemDetail`, focusing on the actual problem and its description, rather than all the additional auxiliary details. Thanks for raising this in any case, it's good to have considered this with more scrutiny.
