### ISSUE TITLE
Setting a default timeout for all requests from Jetty reactive httpclient

### ISSUE THREAD

**Issue by AhmadAbdelghany** [spring-projects/spring-framework#29317]
I am using Jetty reactive http client as the httpclient in webClient. I would like to set a default timeout for all requests similar to the [documented usage of Reactor Netty](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-reactor-timeout). My understanding is that Jetty allows response timeout to be specified on the request-level not on the client. It would be great if I can access the native request in an `ExchangeFilterFunction` something like:

```java
WebClient.builder()
                .filter((request, next) -> {
                    HttpRequest jettyHttpRequest = request.getNativeRequest();
                    jettyHttpRequest.timeout(5000, TimeUnit.MILLISECONDS);
                    return next.exchange(request);
                })
                .build();
```

**Comment by rstoyanchev** [comment]
That method shown in your snippet, `request.getNativeRequest`, already exists. I'm not quite sure what's missing?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
