### ISSUE TITLE
Document how to use WebJars without `webjars-locator-core` dependency

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#29322]
Given current efficiency impact of `webjars-locator-core` (see [this related comment](https://github.com/spring-projects/spring-framework/issues/27619#issuecomment-1277925753)), an its incompatibility with native images, it makes sense to recommend to use versioned URLs with this kind of configuration instead of `WebJarsResourceResolver` without including `webjars-locator-core` dependency in Spring reference documentation.

```java
@Bean
public WebMvcConfigurer configurer() {
	return new WebMvcConfigurer() {
		@Override
		public void addResourceHandlers(ResourceHandlerRegistry registry) {
			registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:META-INF/resources/webjars/");
		}
	};
}
```
We can refine later recommending the regular `webjars-locator-core` + `WebJarsResourceResolver` approach with version-less URLs if/when `webjars-locator-core` implement resource resolution without scanning, which seems to be possible as experimented in #27619.

**Comment by sdeleuze** [comment]
Interestingly, WebJars versioned URLs work out of the box with Spring Boot which configures `/META-INF/resources` resource location by default (at least for now, see spring-projects/spring-boot#28295 related issue) so no need for `WebMvcConfigurer` bean for regular use case.

**Comment by vpavic** [comment]
Did you consider linking to WebJars' own documentation, more specifically to [its Spring MVC section](https://www.webjars.org/documentation#springmvc)?

It is a bit dated (I'll try to open a PR to address that) but it should cover everything.

**Comment by sdeleuze** [comment]
Good point, feel free to provide a PR to refine.
