### ISSUE TITLE
backoff

### ISSUE THREAD

**Issue by guysmart694** [spring-projects/spring-framework#29329]

**Comment by imkulwant** [comment]
`PathResourceResolver` is unable to find `404%E0%A4%8F.html` file. 

`2022-10-14T19:40:44.507+0530 WARN o.s.w.s.r.PathResourceResolver.getResource "Resource path "test/404%E0%A4%8F.html" was successfully resolved but resource "file:../../test/404%E0%A4%8F.html" is neither under the current location "file:../../test" nor under any of the allowed locations [URL [file:../../test], class path resource [static/]]`

It seems html file `404ए.html` name is encoded into `404%E0%A4%8F.html`

Which client are you using to load this HTML file?

**Comment by guysmart694** [comment]
If you see the URL contains utf8 encoded character and hence the warning. But the warning happens for the encoded url which are loaded from file:../../test/ folder and for for the encoded urls under classpath /static folder.

**Comment by guysmart694** [comment]
You can refer to Git Project 
HTTP URL  https://github.com/guysmart694/TestLanguage.git
Project URL https://github.com/guysmart694/TestLanguage
SSH URL git@github.com:guysmart694/TestLanguage.git

**Comment by guysmart694** [comment]
please let me know if you need any other input

**Comment by guysmart694** [comment]
Is there any progress on this issue

**Comment by guysmart694** [comment]
I have uploaded the sample on github
You can refer to Git Project
HTTP URL https://github.com/guysmart694/TestLanguage.git
Project URL https://github.com/guysmart694/TestLanguage
SSH URL ***@***.***:guysmart694/TestLanguage.git

**Comment by guysmart694** [comment]
Is there any progress on this issue

**Comment by bclozel** [comment]
Closing in favor of #29874
Please avoid creating duplicate issues, it's wasting the team's time.
