### ISSUE TITLE
Support sending large STOMP messages as fragmented frames

### ISSUE THREAD

**Issue by totakura** [spring-projects/spring-framework#29354]
#16152 added handling of fragmented STOMP frames. However, as of now there is no functionality to send such fragmented frames through `WebSocketStompClient`.  This issue is a feature request to add complimentary functionality in `WebSocketStompClient`.

Node libraries such as `stompjs` https://stomp-js.github.io/ allow for configuring a max chunk size. When STOMP message is bigger than the chunk size, it is sent as multiple websocket frames.

We would also need to expose the functionality to configure the max chunk size in `WebSocketStompClient`.

**Comment by injae-kim** [comment]
May I handle this issue? I checked `stomp.js` send&receive fragments impl, `stomp protocol spec doc` and I think I can implement this!

I'll create PR until `2024/01/14` next weekend. thanks! 🙇

**Comment by injae-kim** [comment]
I create PR https://github.com/spring-projects/spring-framework/pull/31970~! 😄

**Comment by rstoyanchev** [comment]
Thanks, @injae-kim. I'll close this in favor of the PR.
