### ISSUE TITLE
please support declarative RSocket-based clients in GraalVM / AOT images

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-framework#29377]
there's probably going to be issues using RSocketExchange in an AOT context for declarative RSocket-based clients, as there were using `HttpServiceProxyFactory` and `HttpExchange`. the root type in RSocket world is `RSocketExchange`. thanks to @sdeleuze for fixing the HTTP issue

**Comment by sdeleuze** [comment]
Should be similar to #29271.

**Comment by OlgaMaciaszek** [comment]
Will work on it next week.

**Comment by bclozel** [comment]
Closing in favor of #29877
