### ISSUE TITLE
Autowiring of a generic type produced by a factory bean fails after AOT processing

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#29385]
**Affects:** 6.0.0-RC2

We found this problem when testing Spring Boot's `JacksonTester` support but I believe it's a general AOT problem to do with factory beans that produce a generic type. Here's a small sample that reproduces the problem:

[factory-bean-problem.zip](https://github.com/spring-projects/spring-framework/files/9868890/factory-bean-problem.zip)

`./gradlew test` should result in two failures:

```
> Task :test FAILED

FactoryBeanProblemApplicationTests > contextLoads() FAILED
    org.springframework.beans.factory.UnsatisfiedDependencyException at AutowiredAnnotationBeanPostProcessor.java:744
        Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException at DefaultListableBeanFactory.java:1782

MinimalReproductionTests > aotConfig() FAILED
    org.springframework.beans.factory.UnsatisfiedDependencyException at MinimalReproductionTests.java:46
        Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException at MinimalReproductionTests.java:46
```

The first reproduces the problem that we've seen in Spring Boot. If you edit `build.gradle` to comment out the setting of the `spring.aot.enabled` system property and run `./gradlew test` again, `contextLoads()` should pass. The second is an attempt to reproduce the problem in a minimal (and slightly simplified) manner. It doesn't involve Boot or the Test Framework at all. 

From what I have seen in the debugger, the behavior diverges in `GenericTypeAwareAutowireCandidateResolver.checkGenericTypeMatch(BeanDefinitionHolder, DependencyDescriptor)`. In the Java config case, the target type is determined via a `BeanFactory.getType` call:

https://github.com/spring-projects/spring-framework/blob/997dd3ee65b0e30b396fa06db75eb6a80b3809bc/spring-beans/src/main/java/org/springframework/beans/factory/support/GenericTypeAwareAutowireCandidateResolver.java#L107-L110

This is sufficient for the result of the check to be `true` and for autowiring to succeed.

In the AOT-processed case, the target type is available from the bean definition:

https://github.com/spring-projects/spring-framework/blob/997dd3ee65b0e30b396fa06db75eb6a80b3809bc/spring-beans/src/main/java/org/springframework/beans/factory/support/GenericTypeAwareAutowireCandidateResolver.java#L90

As a result, the `getType` call on the bean factory never happens. The result of the check is false and autowiring fails.

**Comment by sdeleuze** [comment]
I tentatively add this one for 6.0 GA since that breaking some propular use cases.

**Comment by wilkinsona** [comment]
Things have improved, but the problem isn't fully resolved. While the slightly simplified reproducer now passes, the other test in the sample still fails:

```
> Task :test FAILED

FactoryBeanProblemApplicationTests > contextLoads() FAILED
    org.springframework.beans.factory.UnsatisfiedDependencyException at AutowiredAnnotationBeanPostProcessor.java:744
        Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException at DefaultListableBeanFactory.java:1812

3 tests completed, 1 failed

FAILURE: Build failed with an exception.
```

**Comment by wilkinsona** [comment]
With the recent changes, `ResolvableType.isAssignableFrom(ResolvableType, Map<Type, Type>)` is now called with `this` being `org.springframework.boot.test.json.JacksonTester<com.example.demo.Request>` and `other` being `org.springframework.boot.test.json.JacksonTester<java.lang.Object>`. `false` is returned as the generics do not align as `com.example.demo.Request` is not assignable from `java.lang.Object`.

**Comment by wilkinsona** [comment]
This failure to match the generics can be reproduced by changing the type of the `@Autowired` field in `Consumer` to `JacksonTester<Request>`:

```java
static class Consumer {

	@Autowired
	JacksonTester<Request> tester;

}
```

This then fails as `com.example.demo.MinimalReproductionTests$Request` is not assignable from `java.lang.Object`.

**Comment by jhoeller** [comment]
Andy, with the injection point changes as above, if the AOT-determined target type is then also set to `FactoryBean<JacksonTester<Request>>`, your revised test passes fine. So this is literally about `<JacksonTester<Object>>` not being assignable to `<JacksonTester<Request>>` now - a different problem where our lenient fallback matching for generics only kicks in if no target type has been pre-determined.

**Comment by jhoeller** [comment]
@wilkinsona This should be addressed in the upcoming snapshot now. Please let me know whether it works for Boot...
