### ISSUE TITLE
Generate reflection hints for custom types that SpringConstraintValidatorFactory will instantiate

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#29395]
**Affects:** 6.0

[This Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/32910) contains a sample application that's using Framework's `@Validated` and a custom constraint annotation that references a custom `ConstraintValidator` implementation. The annotation is used on a parameter of `@GetMapping` method. The `ConstraintValidator` implementation, `IdValidator`, is created by `SpringConstraintValidatorFactory` and this fails as it uses reflection.

It feels to me like Framework should be able to generate the necessary reflection hint automatically by following the trail of `@Validated` -> `@Id` -> `IdValidator`.

**Comment by sdeleuze** [comment]
Duplicate of #29823.
