### ISSUE TITLE
GET query parameters containing comma are not properly URL decoded

### ISSUE THREAD

**Issue by ionel-sirbu-crunch** [spring-projects/spring-framework#29411]
**Affects:** Spring Boot 2.7.5

---

Hello,

I recently realised that one of my `GET` endpoints has issues if the values passed in the query params contain commas (`,`).
Basically, I expect to be able to embed a comma into a single value being passed into a query param, however, the receiving end must define the data type as `List<String>` & Spring splits the value into 2 rather than keeping it in one piece.

To give an example, assume you have this endpoint:

```java
@GetMapping
public ResponseEntity<List<String>> getSomeResource(@RequestParam("res") List<String> resources) {
    return ResponseEntity.ok(resources);
}
```

If you hit it with this request:

```bash
curl http://localhost:8080/test?res=xx%2Cyy
```

then you get back `["xx","yy"]`, which is exactly the same result as requesting `curl http://localhost:8080/test?res=xx,yy`, but I expect to get back a list with a single element instead, `["xx,yy"]`.

Demo app can be found [here](https://github.com/ionel-sirbu-crunch/spring-decode-comma).

Thank you very much!

**Comment by ionel-sirbu-crunch** [comment]
Probably in the same functional area, spaces (` `) embedded in query params don't get decoded properly either, they are left as pluses (`+`). I've added a test to reflect that too in the demo app.

**Comment by dmytro-zhelieznyi** [comment]
Hello, It simply can be fixed by small changes for this code snipe. 
org.springframework.core.convert.support.StringToCollectionConverter class
But the question is will it affect the existing code if code base will be moved to this spring version or higher?
Related changes https://github.com/spring-projects/spring-framework/pull/29451

**Comment by ionel-sirbu-crunch** [comment]
The way I see it, at a very high level, the parameter resolution needs to be processed in 2 rather distinct initial stages:

1. extraction of raw query parameters from the query string - this is where we account for commas (`?q=what,where`) & repeated params (`?q=what&q=where`);
2. URL decoding of the extracted values.

That way commas, equal signs & ampersands encoded into the values (stage 2) are not mixed with the ones that are actually part of the URL syntax (stage 1).

Obviously, further processing will take place after these initial steps, e.g. data conversion.

**Comment by sbrannen** [comment]
Potentially related to:

- #23820

**Comment by rstoyanchev** [comment]
Thanks for logging the issue indeed, and indeed that is how the framework gets better. 

I'm afraid in this case there isn't much we can do. For once the `HttpServlettRequest#getParameter*` methods, which is what `@RequestParam` is a shortcut to, returns decoded values so we see "xx,yy" as the value in both cases. We could parse the queryString but that is a much more involved change because we also rely on `HttpServlettRequest#getParameter` not only for the query but also for form data and multipart data in the body. It would also be a breaking change for others.

At best it would need to be a different annotation, but we will not introduce one just for this. The recommendations under #23820, although you may see them as a workaround, do provide flexibility for this, and that is the best option in this case. You could also create your own custom argument resolver.

**Comment by ionel-sirbu-crunch** [comment]
> Thanks for raising the issue, and indeed that is how the framework gets better.
> 
> I'm afraid in this case there isn't much we can do. For once the `HttpServlettRequest#getParameter*` methods, which is what `@RequestParam` is a shortcut to, returns decoded values so we see "xx,yy" as the value in both cases. We could parse the queryString but that is a much more involved change because we rely on `HttpServlettRequest#getParameter` not only for the query, but also for form data, and multipart data in the body. And it would be a breaking change for others.
> 
> At best it would need to be a different annotation, but we will not introduce one just for this. The recommendations under #23820, although you may see them as a workaround, do provide flexibility around how this should be handled, and that is probably the best option in this case. You could also create your own custom argument resolver.

Well, something as simple as:

```diff
Index: spring-web/src/main/java/org/springframework/web/method/annotation/RequestParamMethodArgumentResolver.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/spring-web/src/main/java/org/springframework/web/method/annotation/RequestParamMethodArgumentResolver.java b/spring-web/src/main/java/org/springframework/web/method/annotation/RequestParamMethodArgumentResolver.java
--- a/spring-web/src/main/java/org/springframework/web/method/annotation/RequestParamMethodArgumentResolver.java	(revision 5ea8ba1b96084792a802cf7eef1ef176f53efe8d)
+++ b/spring-web/src/main/java/org/springframework/web/method/annotation/RequestParamMethodArgumentResolver.java	(date 1675861396950)
@@ -180,7 +180,11 @@
 		if (arg == null) {
 			String[] paramValues = request.getParameterValues(name);
 			if (paramValues != null) {
-				arg = (paramValues.length == 1 ? paramValues[0] : paramValues);
+				if (Collection.class.isAssignableFrom(parameter.getParameterType())) {
+					arg = paramValues;
+				} else {
+					arg = (paramValues.length == 1 ? paramValues[0] : paramValues);
+				}
 			}
 		}
 		return arg;
```

could potentially sort out the encoded comma issue, depending on how the underlying `HttpServletRequest` implementation handles `getParameterValues()`. e.g. with Spring's `MockHttpServletRequest` it works fine save for the `"/test?res=xx,yy%2Czz"` case, when it generates a single string. But `"/test?res=xx&res=yy%2Czz"` correctly generates 2 strings with the above change.

**Comment by techouse** [comment]
Suggestion: Consider using [qs-kotlin](https://github.com/techouse/qs-kotlin) to handle query parameters. This library is a faithful Kotlin/JVM port of Node.js’s popular qs parser￼, which means it brings the robust parsing behavior of qs to the JVM. It supports deep parsing options – for example, it can interpret nested query parameters (`foo[bar][baz]=qux`) as nested maps, and it recognizes dot-notation in keys (`a.b=c`) out of the box ￼. It also allows configuring parse depth, parameter limits, etc., similar to the Node.js version. Moreover, qs-kotlin comes with extensive tests (Kotest) to ensure reliability￼, so it’s thoroughly vetted.

Importantly, qs-kotlin handles comma-separated list values natively. One of its supported list formats treats commas as separators ￼. For example, if you have a query ?filter=a,b,c, you can decode it with the comma option enabled, and it will be parsed into a list of values for the "filter" key. In code:

```kotlin
val result = QS.decode("filter=a,b,c", DecodeOptions(comma = true))
// result: mapOf("filter" to listOf("a", "b", "c"))
```

This is demonstrated in qs-kotlin’s test suite (e.g. [ExampleSpec.kt](https://github.com/techouse/qs-kotlin/blob/3055a04f25dfbf3424a97c8954f3a1ce0a32ebe2/qs-kotlin/src/test/kotlin/io/github/techouse/qskotlin/unit/ExampleSpec.kt#L203) uses `DecodeOptions(comma = true)` to verify comma-separated values) ￼. By using qs-kotlin, you get out-of-the-box support for commas in query params without needing to manually split or worry about Spring’s decoding quirks. It will properly URL-decode and split such parameters as you expect.

For more details, check out the [qs-kotlin GitHub repository](https://github.com/techouse/qs-kotlin) – the README highlights its deep parsing capabilities and native support for lists (indices, brackets, repeat, and comma-separated formats) ￼. This library could cleanly solve the comma decoding issue you’re encountering by delegating query parsing to it.
