### ISSUE TITLE
ResourceHttpMessageConverter create incorrect type of Resource

### ISSUE THREAD

**Issue by ainGitHub** [spring-projects/spring-framework#29427]
[ResourceHttpMessageConverter](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/converter/ResourceHttpMessageConverter.java) class method [readInternal](https://github.com/spring-projects/spring-framework/blob/d492086c76344e1b87d32e326d49d0844a8d2bcb/spring-web/src/main/java/org/springframework/http/converter/ResourceHttpMessageConverter.java#L79) create InputStreamResource only when we use InputStreamResource in controller method, otherwice it create ByteArrayResource. 
I think it's incorrect, and we need write something like this, see code below. 
Or someone can explain why it created in that way?
```
    @Override
    protected Resource readInternal(Class<? extends Resource> clazz, HttpInputMessage inputMessage)
            throws IOException, HttpMessageNotReadableException {
        if (this.supportsReadStreaming && (InputStreamResource.class == clazz || Resource.class == clazz)) {
            return new InputStreamResource(inputMessage.getBody()) {
                @Override
                public String getFilename() {
                    return inputMessage.getHeaders().getContentDisposition().getFilename();
                }

                @Override
                public long contentLength() throws IOException {
                    long length = inputMessage.getHeaders().getContentLength();
                    return (length != -1 ? length : super.contentLength());
                }
            };
        } else if (ByteArrayResource.class.isAssignableFrom(clazz)) {
            byte[] body = StreamUtils.copyToByteArray(inputMessage.getBody());
            return new ByteArrayResource(body) {
                @Override
                @Nullable
                public String getFilename() {
                    return inputMessage.getHeaders().getContentDisposition().getFilename();
                }
            };
        } else {
            throw new HttpMessageNotReadableException("Unsupported resource class: " + clazz, inputMessage);
        }
    }
```

**Comment by bclozel** [comment]
This is selecting `InputStreamResource` only if streaming is supported (in the case `RestTemplate`, streaming is not supported) and the target type is `InputStreamResource`. The Javadoc of `InputStreamResource` states [why it should only be used in some cases](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/InputStreamResource.html).

Applying the change you've suggested would:

1. prevent developers from reading the stream multiple times
2. force them to properly drain and close the stream, otherwise the state of the HTTP connection would be invalid and would need to be closed.
3. break many applications out there if they're not dealing with 1) and 2) properly

**Comment by ainGitHub** [comment]
@bclozel thanks for the explanation. I assume that for my application, I can just create my own resourceConverter and use it without changing the implementations from Resource to InputStreamResource.
By the way, there is a similar question for [ResourceDecoder](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/codec/ResourceDecoder.java). There, in the decode method, for some reason, for InputStreamResource, data is created from ByteArrayInputStream. Whether it is impossible to implement receiving of the data from DataBuffer in a stream form there?

**Comment by bclozel** [comment]
> By the way, there is a similar question for [ResourceDecoder](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/codec/ResourceDecoder.java). There, in the decode method, for some reason, for InputStreamResource, data is created from ByteArrayInputStream. Whether it is impossible to implement receiving of the data from DataBuffer in a stream form there?

In this case, the data here is already read in memory as a `DataBuffer`, so there is no `InputStream` to plug in. The data should be read in a non-blocking fashion, so `InputStream` do not work there. If you wish to read asynchronously, `Flux<DataBuffer>` is a better choice there.

I'm closing this issue as the matter seems to be resolved. Thanks!
