### ISSUE TITLE
Remove APIs deprecated for removal in 6.1

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#29449]
Remove APIs that have been "deprecated for removal in 6.1".

## Candidates

- [x] methods in `org.springframework.util.Assert`
- [x] `org.springframework.core.task.support.ConcurrentExecutorAdapter`
- [x] `org.springframework.test.web.reactive.server.ExchangeResult.getRawStatusCode()`
- [x] `org.springframework.http.HttpMethod.resolve(String)`
- [x] `org.springframework.http.HttpRequest.getMethodValue()`
- [x] `org.springframework.http.client.HttpComponentsClientHttpRequestFactory.setReadTimeout(int)`
- [x] `org.springframework.http.client.reactive.ClientHttpResponse.getRawStatusCode()`
- [x] methods in `org.springframework.jdbc.datasource.init.ScriptUtils`
- [x] constructors in `org.springframework.web.HttpRequestMethodNotSupportedException`
- [x] `org.springframework.web.reactive.function.client.ClientResponse.rawStatusCode()`

**Comment by sbrannen** [comment]
I made an initial pass to remove deprecated APIs in af170f693a921f1d4e79205cdf49e2644f12ddaa and 7df2e2a8d2a845984cde806232181da486dcf7bd.

The team will make an additional pass in conjunction with #30604.

In light of that, I am closing this issue.

**Comment by GregTreat** [comment]
How should we handle interactions with servers that return non-standard HTTP status codes?

Previously, getRawStatusCode() was a reliable way to retrieve the raw status code without failing. However, now getStatusCode() throws an exception if the response contains an unknown status code, making it problematic when dealing with less strict servers.

What’s the recommended approach to handle this scenario in Spring 6+?

**Comment by bclozel** [comment]
@GregTreat Have you tried applying the advice in the deprecation notice? Using `getStatusCode` should work for both standard and non-standard status codes.

**Comment by GregTreat** [comment]
@bclozel Maybe I missed advice in the deprecation notice. Can you please point me.

**Comment by GregTreat** [comment]
@bclozel Oh, sorry! It looks like I wasn't up to date. In version 6.x, the failures no longer occur.

**Comment by sbrannen** [comment]
> Maybe I missed advice in the deprecation notice. Can you please point me.

It's in the Javadoc: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/client/ClientHttpResponse.html#getRawStatusCode()
