### ISSUE TITLE
CglibAopProxy errors should be logged as warning 

### ISSUE THREAD

**Issue by fvigotti** [spring-projects/spring-framework#29453]
Good morning ,

I'm not a usual committer, but if someone has 5 minutes...

The following types of errors should be logged as `WARNING` or `ERROR` instead of `INFO`.

> INFO 67074 --- [           main] o.s.aop.framework.CglibAopProxy          : Unable to proxy interface-implementing method [public final void org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.loginFail(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)] because it is marked as final: Consider using interface-based JDK proxies instead!

I've spent 2 days investigating the issue, and it was an `@Transactional` annotation added to my (Kotlin ) custom implementation of the `AbstractRememberMeServices` which together with final methods in the abstract class caused this very difficult to spot behavior.

**Comment by sbrannen** [comment]
PR #29773 will need to be merged or closed as a result of triaging this issue.

**Comment by snicoll** [comment]
Closing in favor of #29773
