### ISSUE TITLE
OAuth2 tutorial has incorrect curl to create tutorial project

### ISSUE THREAD

**Issue by davidnewcomb** [spring-projects/spring-framework#29504]
On page: https://spring.io/guides/tutorials/spring-boot-oauth2/
Section: Single Sign On With GitHub -> Creating a New Project
```
curl https://start.spring.io/starter.tgz -d style=web -d name=simple | tar -xzvf -
```
This returns:
```
{"timestamp":"2022-11-16T18:30:07.324+00:00","status":400,"error":"Bad Request","message":"Dependencies must be specified using 'dependencies'","path":"/starter.tgz"}
```

Please update documentation to give the correct `curl` incantation.

**Comment by snicoll** [comment]
Thanks but that's the wrong issue tracker to report this to. The page you've referenced has a "Go To Repo" on the right hand side. This points to https://github.com/spring-guides/tut-spring-boot-oauth2 and that's where you should have reported it.

Can you please report the issue there? Thanks.
