### ISSUE TITLE
"Spring Framework Versions" page is missing support information on 6.0.x

### ISSUE THREAD

**Issue by marcwrobel** [spring-projects/spring-framework#29502]
The https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions page is missing support information on 6.0.x in the "Supported Versions" section.

Moreover the "JDK Version Range" section contains `(expected)` mentions for 5.3.x and 6.0.x that can be removed I think.

**Comment by marcwrobel** [comment]
And congratulation for the 6.0.0 release !

**Comment by bclozel** [comment]
[Support dates are available on the website](https://spring.io/projects/spring-framework#support). We'll update the wiki shortly.

**Comment by marcwrobel** [comment]
Thanks @bclozel, missed that page.

**Comment by bclozel** [comment]
I've updated the wiki page, including a link to the support page.
I've left the `(expected)` in place as the JDK range we're supporting could be extended still.

Thanks!
