### ISSUE TITLE
Code example has callout from a different code example

### ISSUE THREAD

**Issue by dfjfj** [spring-projects/spring-framework#29505]
**Affects:** Spring Framework 6.0.0

---

There is a small problem in the `@ModelAttribute` section of the reference manual: https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-modelattrib-method-args  

There are a few redundant remarks such as : "Adding a BindingResult next to the @ModelAttribute." etc.

I think this should be easy to find and modify, thanks.

**Comment by snicoll** [comment]
@dfjfj sorry, but I don't understand the problem you're trying to report. What do you mean by "redundant remark"?

**Comment by dfjfj** [comment]
Sorry for the language trouble, please check the picture. 
incorrect:
![屏幕截图 2022-11-17 153638](https://user-images.githubusercontent.com/43194876/202386047-7843f0f4-2e96-4d1f-8d35-21589d684f1b.png)
correct:
![屏幕截图 2022-11-17 154229](https://user-images.githubusercontent.com/43194876/202386089-2052d871-6992-4c6b-85ef-ac7a562cd7ae.png)

**Comment by snicoll** [comment]
@dfjfj I see it now. Thanks very much.

**Comment by dfjfj** [comment]
You're welcome, a little effort.

**Comment by snicoll** [comment]
That looks like a bug in the asciidoc rendering as the callout isn't in the source. I've noticed that switching to the Kotlin sample makes it go away.

**Comment by sbrannen** [comment]
I have pushed a workaround for this bug in ac7d428a627e6dabbde500266eaeed4670e37bfb.

However, as mentioned in the commit message this appears to be a general bug that still needs to be addressed. As @snicoll pointed out elsewhere, this is likely an issue with the Javascript that supports this feature.

In light of that, I am leaving this issue open for the time being.
