### ISSUE TITLE
`AspectJExpressionPointcut#getTargetShadowMatch` tentatively creates proxies for every bean

### ISSUE THREAD

**Issue by goafabric** [spring-projects/spring-framework#29519]
So this is a continuation of
https://github.com/spring-projects-experimental/spring-native/issues/956
which is still an open issue with Boot 3 (RC2 + latest snapshot)

While simple methods expressions like this just work fine
"execution(public * org.goafabric.calleeservice.aspect.TestComponent.*(..))"

More complex expressions, that e.g. leverage an custom anntotation, don't.
To be more specific .. they work with console applications, but crash the moment wie have WEB on the classpath.
Which somehow explains the error.
Tried to set the jdk proxy interfaces that graalvm demands, but stopped after the 3rd roundtrip because this seems
to be a neverending road ...

I've attached a simple example that works with non native, but crashes on bootstrap of the native image.
What's also a little mind boggeling .. is that i have to register a simple hint for the Test Aspect.
While the aot-smoke-tests don't ...

[error.txt](https://github.com/spring-projects/spring-boot/files/10041368/error.txt)
[example.zip](https://github.com/spring-projects/spring-boot/files/10041400/example.zip)

**Comment by goafabric** [comment]
Thx for answering that fast .. insanely fast ...
https://github.com/spring-projects/spring-framework/issues/28711 is a little different 
It at least explains why i had to set the 
"hints.reflection().registerType(TestAspect.class, MemberCategory.INVOKE_DECLARED_METHODS)"

But with this the invocation works .. for all usecases as long as it is a simple console application

Combine it with web and it crashes .. so i guess this is a little different

**Comment by sdeleuze** [comment]
I confirm the example is now working as expected with method hints (`hints.reflection().registerType(TestAspect.class, MemberCategory.INVOKE_DECLARED_METHODS);`) which will be inferred via #28711.

**Comment by goafabric** [comment]
@sdeleuze 
thank you for finally having this fixed
is there any kind of way i can try it out myself already ?

boot 3.0.2-snapshot still seems to rely on framework-core 6.0.3
and including framework-core 6.0.4-SNAPSHOT did not solve the issue

or do i just have to wait for a release ? :)

thx

**Comment by sdeleuze** [comment]
Thanks should go to @jhoeller for the fix ;-)

You can override the Framework version in Boot, otherwise just wait a bit, Spring Framework 6.0.4 has been released today and will be picked up by Boot shortly.

**Comment by goafabric** [comment]
yes i saw it on twitter yesterday evening, thx 4 letting me know and of course also to @jhoeller

**Comment by goafabric** [comment]
@sdeleuze 
I can happily report that everything is working now with boot 3.0.2-SNAPSHOT
Even more complex applications finally including CircuitBreaker Annotation
So thx again to both of you.

As a sugar on top .. would it be possible to get rid of the "hints.reflection().registerType" ?
Because basically everything annotated with Aspect should qualify already qualify for reflection ?

Or .. "at least" as a fallback, at least have a working variant of "RegisterForReflectionBinding"

Then it would also be nice to have spring cloud resilience4j working out of the box.
I opened an issue a while ago, that was just closed
https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/159

And this basically needs 
" hints.reflection().registerType(CircuitBreakerAspect.class, builder -> builder.withMembers(MemberCategory.INVOKE_DECLARED_METHODS));"

**Comment by sdeleuze** [comment]
Please create a related issue with me mentioned with a minimal reproducer and a detailed description of the type hint inference you would expect.
