### ISSUE TITLE
if we should support a default restTemplate with SSL

### ISSUE THREAD

**Issue by siyuebin11** [spring-projects/spring-framework#29541]
Currently, restTemplate of spring-web module don't support SSL function for web client request， for example restTemplate。
However，current applications usually use HTTPS for communication, so we should  extend this function for resttemplate。 
So why not we support a default restTemplate with SSL in spring-web, it can reduce a lot of repetitive redundant code。

**Comment by bclozel** [comment]
`RestTemplate` does work with TLS, thanks to the underlying client libraries that it supports.
I'm closing this issue as a result.

Feel free to reopen it with a sample application (ideally, created on start.spring.io and shared as a repository on github) that reproduces the problem. Thanks!
