### ISSUE TITLE
ResponseStatusException not working correctly

### ISSUE THREAD

**Issue by ydemartino** [spring-projects/spring-framework#29567]
**Affects:** 6.0

The javadoc for the ResponseStatusException is
```
 * Subclass of {@link ErrorResponseException} that accepts a "reason" and maps
 * it to the "detail" property of {@link org.springframework.http.ProblemDetail}.
```

But when I set a reason, the detail is always null. It seems the class is missing `getBody().setDetail(getReason());`.
Or maybe this is an issue in the javadoc?
Or am I missing something?

---

**Comment by rstoyanchev** [comment]
This was the case, but [was removed](https://github.com/spring-projects/spring-framework/commit/b045e5baef0445e4feb16a5fc548bc4a7bf5555b#diff-63747db89909f3050833efe38439d4f5ba79d66baf952d1c16d6651652719d0fL80) when adding tests for all sub-classes, with the idea that the reason isn't always what should be present to the outside world. 

What I think it should say, and work, is that it uses the reason as the detail by default, but sub-classes can set the detail to something else if needed.
