### ISSUE TITLE
Throw exception if no handler found in Webflux

### ISSUE THREAD

**Issue by alxxyz** [spring-projects/spring-framework#29568]
How to throw exception if no handler found in Webflux?

**Comment by jaDEVirek** [comment]
Hi @alxxyz 

By default, the DispatcherServlet does not throw a NoHandlerFoundException. You need to enable that:

Check if you have right configuration in your application.properties. 
`spring.mvc.throw-exception-if-no-handler-found=true`

Besides, if you are using @EnableWebMvc then it is likely that your changes made, for example, in properties files will be overwritten.
https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-servlet-config

**Comment by alxxyz** [comment]
I am using Webflux instead of WebMvc, does it work also for Webflux?

**Comment by rstoyanchev** [comment]
@alxxyz that should be the case out of the box in WebFlux, [in DispatcherHandler](https://github.com/spring-projects/spring-framework/blob/7de8d81932c1a17d06f247b67110c3c9016fcc9d/spring-webflux/src/main/java/org/springframework/web/reactive/DispatcherHandler.java#L152).

**Comment by alxxyz** [comment]
@rstoyanchev can you please advise how I can catch it and override the response?
As I can not catch it in the `@ControllerAdvice`

**Comment by rstoyanchev** [comment]
@alxxyz, catching early exceptions from before a handler is chosen was added recently for 6.0 with #22991, so it's not supported in 5.3.x. Are you trying to add a body to the error response or something else?

**Comment by alxxyz** [comment]
Yes, we have an API contract and I need to send a custom body

**Comment by rstoyanchev** [comment]
I see, so that's supported from 6.0 onwards. In 5.3.x, you can use a `WebExceptionHandler` as a workaround, or Boot's [error handling](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#web.reactive.webflux.error-handling).

**Comment by alxxyz** [comment]
Thank you @rstoyanchev

**Comment by kitkars** [comment]
@rstoyanchev  - hate to trouble you.. Does it work with WebFilter exception as well? Because It does not seem to be!

I have attached a simple project.

[demo.zip](https://github.com/spring-projects/spring-framework/files/15491624/demo.zip)
