### ISSUE TITLE
Do you have any plans to translate Spring Framework official documents?

### ISSUE THREAD

**Issue by BictorLym** [spring-projects/spring-framework#29577]
I recently confirmed that React provides a lot of translation documents. I wonder if you are thinking of doing an open source project to provide translation services for Spring Project.
I'd like to translate the Spring Framework official document into Korean.

**Comment by bclozel** [comment]
This has been asked several times, see #9008 and #23786 (and probably more).
Maintaining the documentation is a lot of work already, doing so in several languages would result in quickly outdated translations. Feel free to host and maintain your own version of the translated documentation, as long as it points back to the official documentation.

Thanks!

**Comment by BictorLym** [comment]
I agree that managing documents is not easy. However, many projects such as React, fastapi, and django are undergoing open source projects to translate.
If it is not translated, it is a big barrier to entry for non-English speakers who use the project for the first time. Even if you give up document management in part, you can create an environment where more beginners, especially non-English-speaking students, are easy to enter

The people who participate in this project are mainly non-English-speaking students, and it gives them an opportunity to study this framework through official documents. All professional developers read the official documents of the project in English, so I think the problem of fragmentation of the documents is a small problem

Therefore, I think there is a good reason to proceed with the project. If you don't want to proceed with the project in Spring, I wonder if I can proceed. And I wonder if there is a possibility of integrating the project if the number of users of the project increases.
