### ISSUE TITLE
Do you have any plans to proceed with the translation open source project in the spring framework open source project?

### ISSUE THREAD

**Issue by BictorLym** [spring-projects/spring-framework#29580]
Recently, I was looking at the official documents of React and saw them provide official documents in various languages, for example, Korean, Japanese, and Chinese. I understand that they are conducting official document translation as an open-source project and that contributors are qualified as open-source contributors. Do you have any plans to provide open source for Spring Project to provide such official documents?
If I proceed with this open source, I would like to change the official document from English to Korean.

**Comment by bclozel** [comment]
Duplicates #29577
