### ISSUE TITLE
Upgrade to Gradle 7.6

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#29583]
Includes build support for JDK 19.

**Comment by vpavic** [comment]
Note that some Gradle releases (and 7.6 is one of those) also update wrapper scripts and/or wrapper binary. So it's necessary to run `./gradlew wrapper` after bumping the Gradle version in `gradle-wrapper.properties`, in order for those files to self-update.

**Comment by sbrannen** [comment]
Updated wrapper in 902f8dd1d8350bc7fbdf711fa92a8a01fd5d0036
