### ISSUE TITLE
Refine `BindingReflectionHintsRegistrar` Kotlin support

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#29593]
Originally reported at https://github.com/spring-projects/spring-boot/issues/33351. It looks like Spring Data isn't contributing the necessary reflection hints to allow `BeanWrapper.KotlinCopyUtil.setProperty` to find and invoke the copy method.

**Comment by sdeleuze** [comment]
We should also probably configure `queryAllDeclaredMethods` on those types, see [this comment](https://github.com/spring-projects/spring-data-commons/issues/2737?notification_referrer_id=NT_kwDOAAInNbE0OTI1ODExMDAxOjE0MTEwOQ#issuecomment-1328677161).
