### ISSUE TITLE
Align multipart codecs on client and server

### ISSUE THREAD

**Issue by CoderYellow** [spring-projects/spring-framework#29630]
According to this [check](https://github.com/spring-projects/spring-framework/blob/b50415062b3d9243c770ac7c59875a6076681bd1/spring-web/src/main/java/org/springframework/http/codec/multipart/MultipartWriterSupport.java#L88), the response type for controller method should be `Mono<MultiValueMap>`, but when I use this:
```kotlin
    @GetMapping("multi-part-map", produces = [MULTIPART_FORM_DATA_VALUE])
    fun multipartMap(): Mono<MultiValueMap<String, HttpEntity<*>>> {
        val builder = MultipartBodyBuilder()
        builder.part("fieldPart", "fieldValue")
        builder.part("filePart1", FileSystemResource("...logo.png"))
        builder.part("jsonPart", Person("Jason"))
        builder.part(
            "myPart",
            DefaultFormFieldPart(HttpHeaders(), "myPartName", "myPartData")
        ) // Part from a server request

        val parts: MultiValueMap<String, HttpEntity<*>> = builder.build()
        return Mono.just(parts)
    }
```
I got this error:
```java
java.lang.ClassCastException: class org.springframework.util.LinkedMultiValueMap cannot be cast to class org.springframework.http.codec.multipart.Part (org.springframework.util.LinkedMultiValueMap and org.springframework.http.codec.multipart.Part are in unnamed module of loader 'app')
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152) ~[reactor-core-3.5.0.jar:3.5.0]
```
Because [here](https://github.com/spring-projects/spring-framework/blob/917c41fd52f655fc4a7c4448e1164afd7e77d21a/spring-web/src/main/java/org/springframework/http/codec/multipart/PartHttpMessageWriter.java#L53) expects `Flux<Part>` response type, so I have to implement something like this:
```kotlin
class DefaultFormFieldPart(
    private val headers: HttpHeaders,
    private val name: String,
    private val value: String
) : Part,
    MultiValueMapAdapter<String, String>(emptyMap()) {

    override fun content(): Flux<DataBuffer> {
        return Flux.defer {
            val bytes = this.value.toByteArray(UTF_8)
            Flux.just(
                DefaultDataBufferFactory.sharedInstance.wrap(
                    bytes
                )
            )
        }
    }
    
    override fun name(): String {
        return name
    }

    override fun headers(): HttpHeaders {
        return headers
    }

}
```
```kotlin

    @GetMapping("multi-part", produces = [MULTIPART_FORM_DATA_VALUE])
    fun multipart(): Flux<DefaultFormFieldPart> {
        return Flux.fromIterable(listOf("part1", "part2"))
            .map { it ->
                DefaultFormFieldPart(HttpHeaders().also {
                    it.contentType = MediaType.TEXT_PLAIN
                }, it, "$it data")
            }
    }

```
It makes no sense to check against `MultiValueMap` if the encoder only treats it as `Flux<Part>`

**Comment by CoderYellow** [comment]
Are there built-in supports for reactive multipart response for server side, like `MultipartBodyBuilder` so that we don't have to implement it ourselves?
I can only find the client side implementation for client in the [doc](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-fn-response)

**Comment by rstoyanchev** [comment]
The `MultipartHttpMessageWriter` subclass of `MultipartWriterSupport` is meant to support this, but it looks like we're only configuring it on the [client side](https://github.com/spring-projects/spring-framework/blob/63d841664c4b7b11451c25104dc0d66c220ba24f/spring-web/src/main/java/org/springframework/http/codec/support/ClientDefaultCodecsImpl.java#L103) and not on the [server side](https://github.com/spring-projects/spring-framework/blob/63d841664c4b7b11451c25104dc0d66c220ba24f/spring-web/src/main/java/org/springframework/http/codec/support/ServerDefaultCodecsImpl.java#L84).

@poutsma what do you think about the differences between the client and server multipart codecs (`MultipartHttpMessageWriter` and `PartEventHttpMessageWriter` vs `PartHttpMessageWriter`) and about aligning them?

@CoderYellow as for building a multipart response, `MultipartBodyBuilder` prepares `MultiValueMap`. This issue aside, is there anything preventing you fro using it in a controller method too?

**Comment by CoderYellow** [comment]
I think we can support `Flux<Part>` first, and it's better to provide some api to create the `Part` like [this](https://github.com/spring-projects/spring-framework/blob/be7fa3aaa879cfb44fc976be7331caf5479a943f/spring-web/src/main/java/org/springframework/http/codec/multipart/FormPartEvent.java#L55)

**Comment by CoderYellow** [comment]
there are already [api](https://github.com/spring-projects/spring-framework/blob/a8c3c746afe7242d79713ba12f4696a5df81e801/spring-web/src/main/java/org/springframework/http/codec/multipart/DefaultParts.java#L50) to create the `Part`, why not expose it

**Comment by poutsma** [comment]
> @poutsma what do you think about the differences between the client and server multipart codecs (`MultipartHttpMessageWriter` and `PartEventHttpMessageWriter` vs `PartHttpMessageWriter`) and about aligning them?

Sounds good to me.

**Comment by poutsma** [comment]
@CoderYellow Returning a `Mono<MultiValueMap<String, HttpEntity<*>>>` is currently only supported on the client side, but not on the server side. I will make a commit that changes this, so that it also enabled on the server side.

> there are already [api](https://github.com/spring-projects/spring-framework/blob/a8c3c746afe7242d79713ba12f4696a5df81e801/spring-web/src/main/java/org/springframework/http/codec/multipart/DefaultParts.java#L50) to create the `Part`, why not expose it

Sending multipart/form-data as a server response is not something we have come across before, so it is quite uncommon. As a result, there was no need for exposing this API (yet).

**Comment by poutsma** [comment]
After team discussion, it was decided that we should also align the differences between server and client when it comes to multipart HttpMessageReader and decoders (i.e. `DefaultPartHttpMessageReader`, `MultipartHttpMessageReader`, and `PartEventHttpMessageReader`).
