### ISSUE TITLE
Support JdkClientHttpConnector in DefaultWebTestClientBuilder

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-framework#29644]
In `org.springframework.test.web.reactive.server.DefaultWebTestClientBuilder#initConnector` there are checks for Reactor Netty, Jetty and Apache Http for the `ClientHttpConnector` implementation. As there is now a `JdkClientHttpConnector` which works without external dependencies, I think it would be nice if `DefaultWebTestClientBuilder` could fallback to that instead of throwing an exception.

I don't know if there are more places which do this auto-detection of `ClientHttpConnector`, but if there are, it would be nice to update them to include `JdkClientHttpConnector`.

**Comment by mhalbritter** [comment]
`org.springframework.web.reactive.function.client.DefaultWebClientBuilder#initConnector` has the same detection, and there `JdkClientHttpConnector` is already integrated. I will create a PR which updates `DefaultWebTestClientBuilder`.

**Comment by mhalbritter** [comment]
See https://github.com/spring-projects/spring-framework/pull/29645

**Comment by jhoeller** [comment]
Superseded by #29645.
