### ISSUE TITLE
Component scanning no longer uses component index for `@Named`, `@ManagedBean`, and other Jakarta annotations

### ISSUE THREAD

**Issue by VNElinpe** [spring-projects/spring-framework#29641]
`ClassPathScanningCandidateComponentProvider#indexSupportsIncludeFilter` attempts to match `jakarta.annotation.ManagedBean`, but the match fails.

**Comment by sbrannen** [comment]
`StandardStereotypesProvider` was updated to support Jakarta annotations (such as `@jakarta.annotation.ManagedBean`) in https://github.com/spring-projects/spring-framework/commit/d84ca2ba90d27a7c63d7b35a6259b5b9cf341118#diff-2bdfddc22d2d1845f4ed7b6705fe73ba79a638f1d739909ab49099cd36a62e0c in conjunction with #25354, but `ClassPathScanningCandidateComponentProvider#indexSupportsIncludeFilter` was not updated accordingly and still matches against annotations whose fully qualified names start with `"javax."`
