### ISSUE TITLE
Add String to ResolvableType Converter

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-framework#29660]
As of Spring Boot 2.7.6, the `@ConfigurationProperties` binding supports converting a string value into a `Class` object to specify some Java type. However, this shares the usual limitations of `.class` references, particularly including lack of support for generics. It would be convenient to be able to bind a Spring `ResolvableType` so that I could specify `java.util.List<com.example.Foo>` in my Boot configuration.

At the moment, I don't see a converter or a factory method in `spring-core` to create a `ResolvableType` from a string representation; I think this would need to be written (and I'm open to taking a try at it if the obvious stack implementation would work).

**Comment by snicoll** [comment]
Thanks for the suggestion but I don't think us parsing a complex string structure to extra a generic type is something that we should offer out-of-the-box. While providing a class as a String in configuration properties can be useful in some cases if you wish to do so (Spring Boot tries to not offer such properties), a more advanced type definition is quite different.
