### ISSUE TITLE
Typo in Upgrading to Spring Framework 6.x

### ISSUE THREAD

**Issue by kk-zu** [spring-projects/spring-framework#29744]
There is a typo in https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#web-applications

> Due to the Jakarta EE migration, make sure to upgrade to Tomcat 10, Jetty 11, or Undertow 2.2.19 with the undertow-servlet-jakarta artifact, alongside switching your javax.servlet imports to jakarta.servlet (Jakarta EE 9). For the latest server generations, consider Tomcat 10.1 and Undertow 2.3 (Jakarta EE 10).
> 
> Several outdated Servlet-based integrations have been dropped: e.g. Apache Commons FileUpload (org.springframework.web.multipart.commons.CommonsMultipartyResolver), 
> ...

Incorrect: `org.springframework.web.multipart.commons.CommonsMultipartyResolver` 
Correct: `org.springframework.web.multipart.commons.CommonsMultipartResolver`

**Comment by simonbasle** [comment]
fixed, thanks for reporting @kk-zu  👍
