### ISSUE TITLE
Springframework version of StringUtils  support for org.apache.commons.lang3.StringUtils.repeat()

### ISSUE THREAD

**Issue by JooHyukKim** [spring-projects/spring-framework#29759]
it would be nice to have Spring version of[org.apache.commons.lang3.StringUtils.repeat](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#:~:text=LeftPad/RightPad/Center/-,Repeat,-%2D%20pads%20a%20String)

I have to add `org.apache.commons.lang3` as dependency just to use that function.

Would you like me to make a PR?

**Comment by fml2** [comment]
IMO Spring's StringUtil serves just the internal Spring needs, it's not a general purpose String library.

**Comment by bclozel** [comment]
We tend to only add utility methods that are generally useful in the Spring Framework codebase, and deprecate/remove them as soon as a JDK variant exists. In this case, `String::repeat` (as of JDK 11) fills that role, even if partially.

I'm declining this enhancement proposal as a result. Thanks!

**Comment by JooHyukKim** [comment]
@fml2 makes total sense.

@bclozel well understood. cheers!
