### ISSUE TITLE
Introduce `Cache` support for DynamoDB

### ISSUE THREAD

**Issue by IshankGulati** [spring-projects/spring-framework#29758]
Hello and thanks for the great work.

In addition to serving as a transactional database, DynamoDB is heavily used in serverless caching. Is there any plan to introduce Cache support for DynamoDB similar to what exists for Caffeine and other providers, and is this the right project for the same?

If this is the right place and someone else is not working on it, I can also plan on contributing the same.

**Comment by bclozel** [comment]
Spring Framework only maintains a Caffeine and a JCache implementation, but most cache providers ship their own (for example, [cache2k](https://github.com/cache2k/cache2k)).
We don't plan on investing in DynamoDB support in Spring Framework directly.

Maybe this implementation could be contributed to the [Spring Data community module](https://github.com/derjust/spring-data-dynamodb) or the DynamoDB Java SDK?

Thanks,
