### ISSUE TITLE
Clarify `ClientHttpRequestInterceptor#intercept()` must close response if it throws exception after receiving the response

### ISSUE THREAD

**Issue by frederic-boissiere** [spring-projects/spring-framework#29751]
**Affects:** Spring Framework 5.3.22

---

Hello, our application implements a custom `RestTemplate` using `org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager`.

Moreover, a custom `ClientHttpRequestInterceptor` is added to this `RestTemplate`.

In case an exception is raised during the execution of the `ClientHttpRequestInterceptor#intercept()` method then the connection stays in leased state, and it is never released leading to "Timeout waiting for connection from pool" exception.

In attachment a simple sample reproducing this behavior: [connpool.zip](https://github.com/spring-projects/spring-framework/files/10318311/connpool.zip)

**Comment by snicoll** [comment]
> In attachment a simple sample reproducing this behavior:

@frederic-boissiere thanks for the sample but running the main invokes your custom code ten times and then exit. What part specifically is showcasing the connection leak?

**Comment by frederic-boissiere** [comment]
Hello @snicoll, 
in order to reproduce the case, you have to start de "server application" using "python3 dumb-server.py"
then the following message will appear in the java console during execution of the main java application : `16:27:40.760 [main] ERROR com.test.CustomRestTemplate - Exception: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8080/": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool`

**Comment by rstoyanchev** [comment]
Normally, the response would be closed (and connection released) in `RestTempate#doExecute`, but if an interceptor throws an exception, then the rest of the execution chain is shortcircuited and doesn't get to see the response, and therefore can't close it. For this case you'll need to close the response.

**Comment by frederic-boissiere** [comment]
Hello @rstoyanchev, from my point of view, this information is missing from the javadoc. 
The signature of the method is not clear regarding this case : 	`ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException;` because it allows the propagation of IOException.

**Comment by rstoyanchev** [comment]
Fair enough, I'll update the Javadoc.

**Comment by rstoyanchev** [comment]
By the way, looking at the custom `RestTemplate`, one thing it does is to prepare the URL. I'll mention that there is a puggable  `UriTemplateHandler` that you could use for similar purposes in case you haven't noticed it.
