### ISSUE TITLE
Wrong default name of the JMS subscription

### ISSUE THREAD

**Issue by fml2** [spring-projects/spring-framework#29763]
I have a Spring application that uses annotation driven JMS listeners, i.e. I have some classes with methods annotated with `@JmsListener`. In this annotation, I do not set the attribute `subscription`.

However, since I want to work with topics (rather than queues) and use durable subsribers, I have configured a `JmsListenerContainerFactory` and set its property `subscriptionDurable` to `true`.

Now I expect all the JmsListeners to be durable and have sensible subscription names.

However, in the JMS admin tool, I see that all the subscriptions have the same name: `org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter`.

I'd expect the default subscription name to be something like `<className>.<methodName>` (where "className" is the class that contains the method annotated with `@JmsListener`), but not always the same. This can even lead to an error where several JmsListeners will overwrite each other's subscriptions.

**Comment by fml2** [comment]
I've found the reason for this behaviour.

When the subscription attribute is not set, [a default one is generated](https://github.com/spring-projects/spring-framework/blob/88cac6a4a3a84ff9891d226d7ad47d2707af6d96/spring-jms/src/main/java/org/springframework/jms/listener/AbstractMessageListenerContainer.java#L290).

In my case (I think, this will always be the case if annotation driven message listeners are used) the listener is of type [MessagingMessageListenerAdapter.java](https://github.com/spring-projects/spring-framework/blob/main/spring-jms/src/main/java/org/springframework/jms/listener/adapter/MessagingMessageListenerAdapter.java). This class does not implement the interface `SubscriptionNameProvider` hence the method `getDefaultSubscriptionName` [returns the class name of the listener](https://github.com/spring-projects/spring-framework/blob/88cac6a4a3a84ff9891d226d7ad47d2707af6d96/spring-jms/src/main/java/org/springframework/jms/listener/AbstractMessageListenerContainer.java#L333).

The solution could be as follows:
1. The class `MessagingMessageListenerAdapter` should implement the interface `SubscriptionNameProvider`.
2. The implementation of the interface's method `SubscriptionNameProvider` should generate the subscription name based on the field `handlerMethod`. There, the real class and method responsible for message processing is stored so that the generated name will be meaningful.

It should be decided how exactly the name should be generated. One could just take the class name of the "real" class.

**Comment by sbrannen** [comment]
- Superseded by #29790

**Comment by fml2** [comment]
> * Superseded by [Improve generated default name for a JMS subscription #29790](https://github.com/spring-projects/spring-framework/pull/29790)

Haha, this is an issue and #29790 is a PR for it :-)

**Comment by sbrannen** [comment]
> Haha, this is an issue and #29790 is a PR for it :-)

Yes, that's correct. We close an issue if a PR supersedes. Having both open clutters the issue tracker. That's our policy.
