### ISSUE TITLE
validation not working

### ISSUE THREAD

**Issue by cjdxhjj** [spring-projects/spring-framework#29783]
**Affects:** \<Spring Framework version>
6.0.3
---

![image](https://user-images.githubusercontent.com/5616997/211231858-57206b3a-bbaa-40a7-86b2-0dcaf5394ef3.png)

![image](https://user-images.githubusercontent.com/5616997/211231783-0731ff54-fae0-4a60-a098-f114f373df40.png)
i have add the @Size and limit the string length from 2 to 4, but it not working

**Comment by DanielLiu1123** [comment]
You should add `spring-boot-starter-validation` dependency, and annotate `@Validated` on you controller.

```java
@Validated
@Controller
public class xxController {
}
```

**Comment by cjdxhjj** [comment]
@DanielLiu1123 thanks very much, it works
