### ISSUE TITLE
CSRF token not available to FreeMarker templates

### ISSUE THREAD

**Issue by ardetrick** [spring-projects/spring-framework#29787]
Hi Team!

After upgrading to SpringBoot 3 a freemarker form no longer renders because the `_csrf` attribute is null.

Sample app (technically it's not rendering _csrf in a form, but it's the same problem): https://github.com/ardetrick/springboot3-freemarker-csrf-issue

There is a work-around where setting `spring.freemarker.expose-request-attributes=true` resolves the issue, however, this does not seem like the correct fix.

I recognize that there have been a few changes to Spring Security and CSRF as part of upgrading Spring Security from 5 to 6, however, the spring security team does not believe this issue is related. https://github.com/spring-projects/spring-security/issues/12462#issuecomment-1373957266.

In addition, at least one other person has also noted this issue: https://github.com/spring-projects/spring-security/issues/12462#issuecomment-1373911441.

Thanks for the help!

**Comment by jhoeller** [comment]
Revised to expose a custom `RequestHashModel` now, adding a request attribute fallback. This aligns with the way Servlet resource views such as JSPs work, without over-exposing everything from an `AllHttpScopesHashModel` as before.
