### ISSUE TITLE
Clarify `FactoryBean.OBJECT_TYPE_ATTRIBUTE` supported types

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#29799]
The `FactoryBean.OBJECT_TYPE_ATTRIBUTE` can be used to give type information to a `FactoryBean`. The documentation isn't clear about what types can be used.

Both [Spring Boot](https://github.com/spring-projects/spring-boot/issues/33746) and [Feign](https://github.com/spring-cloud/spring-cloud-openfeign/issues/337) have used `String` values. It appears that in reality only `Class` and `ResolvableType` are [supported](https://github.com/spring-projects/spring-framework/blob/8dbdfb0449f5223e102c090591d38ed956722147/spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java#L1699).

Should `AbstractBeanFactory` also accept `String` values containing class names? Or should the types supported be documented in `FactoryBean.OBJECT_TYPE_ATTRIBUTE`? If String types are not supported, the openfeign code should probably change.

**Comment by wilkinsona** [comment]
Spring Data [also uses a `String value](https://github.com/spring-projects/spring-data-commons/blob/8aff63103230780e319a34a5b95dd67cd7c90092/src/main/java/org/springframework/data/repository/config/RepositoryRegistrationAotContribution.java#L231-L232).

**Comment by snicoll** [comment]
I thought they would have removed it with the change to specify the targetType (the line above in your link). Ping @mp911de

**Comment by mp911de** [comment]
FWIW, Spring Data sets a `Class` object for `FactoryBean.OBJECT_TYPE_ATTRIBUTE`.
We could remove the attribute as we set the `targetType` as well.

**Comment by wilkinsona** [comment]
Sorry for the confusion. There are two usages in Spring Data and I evidently linked to the wrong one. [This](https://github.com/spring-projects/spring-data-commons/blob/8aff63103230780e319a34a5b95dd67cd7c90092/src/main/java/org/springframework/data/repository/config/RepositoryConfigurationDelegate.java#L186) is where a `String` is used.

**Comment by snicoll** [comment]
As of Spring Framework 6.1, a `FactoryBean.OBJECT_TYPE_ATTRIBUTE` value that is neither a `Class` nor a `ResolvableType` is rejected upfront, see https://github.com/spring-projects/spring-framework/commit/4786e2bf53a3f882c10e25d7ff79a18ff47b5e51.
