### ISSUE TITLE
about method #getSingleton(String beanName, boolean allowEarlyReference) since tag v5.2.9.RELEASE

### ISSUE THREAD

**Issue by dqq7617** [spring-projects/spring-framework#29821]
Environment: Spring v5.2.9.RELEASE
Class: DefaultSingletonBeanRegistry.java
Method: getSingleton(String beanName, boolean allowEarlyReference)

why did `synchronized(this.singletonObjects)`  change from before to after get bean from earlySingletonObjects, in the case of concurrency and exist circle dependency, wouldn't it be possible to get incomplete bean?

**Comment by snicoll** [comment]
Sorry this got overlooked. The code of the  core container changes often to accommodate various use cases and we don't use the issue tracker to answer questions. There are a number of open issues with regard to early init that we are reviewing.

In the absence of a concrete problem, I am going to close this now.
