### ISSUE TITLE
Js es6 import in regards to http caching 

### ISSUE THREAD

**Issue by benzen** [spring-projects/spring-framework#29834]
**Affects:** \<Spring Framework version>

---

In the same fashion as CssLinkResourceTransformer deal with import in css es6 js import should be dealt with.

asset request with version or hash works perfect when you require it from a template, but when you require it from another js file, there the importe is not rewritten.

I understand that js in the past wasn’t so great about this but with the rise of es6 we have a way to make it better.

it should be considered that some use will prevent any js manipulation from spring but we already have the mechanisms for that. Also if the js file use techniques other than native es6 import there is not so much that can be done.

The normal case of es6 import shipped to user can be made easier

**Comment by bclozel** [comment]
I think the ES6 [import syntax is more complex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and that this should be dealt with by JavaScript build tools as they have the proper knowledge about modules and can perform efficient operations like packing and tree shaking.

I'm closing this issue as a result. Thanks for creating this issue!
