### ISSUE TITLE
UriComponentsBuilder doesn't encode + in the query param value 

### ISSUE THREAD

**Issue by nitesr** [spring-projects/spring-framework#29838]
UriComponentsBuilder doesn't encode + in the value .. here is the test which it fails

```
UriComponents components = UriComponentsBuilder.fromHttpUrl("http://localhost/path")
                .queryParam("p","{v}")
                .buildAndExpand("a+b=")
                .encode();
assertEquals("p=a%2Bb%3D", components.getQuery());

```
Expected :p=a%2Bb%3D
Actual   :p=a+b%3D

**Affects:** org.springframework:spring-web:5.3.18

---

**Comment by bclozel** [comment]
Closing as invalid as this has been done on purpose in #23025, see [this comment in particular](https://github.com/spring-projects/spring-framework/issues/23025#issuecomment-495635976) and [the reference documentation on URI encoding](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc.web-uri-encoding).

**Comment by nitesr** [comment]
@bclozel - Thank you!  I also got the usage of RestTemplate from above thread.
