### ISSUE TITLE
Aot generated sources fail to compile with 'File name too long' error

### ISSUE THREAD

**Issue by adisesha** [spring-projects/spring-framework#29846]
### Steps to reproduce: 
1. Go to [start.spring](https://start.spring.io/)
2. Project: Gradle-Kotlin
3. Language: Kotlin
4. Spring Boot: 3.0.1
5. Packaging: Jar
6. Java: 17
7. Dependencies:  GraalVM Native Support, Spring Boot Actuator 
8. Generate the project(attached generated project for convenience) and run `./gradlew nativeRun`. I got the following error,

```
> Task :compileAotJava FAILED
/home/test/Downloads/actuator-bug/build/generated/aotSources/org/springframework/boot/actuate/autoconfigure/observation/ObservationAutoConfiguration__BeanDefinitions.java:115: error: error while writing OnlyMetricsMeterObservationHandlerConfiguration__BeanDefinitions: /home/test/Downloads/actuator-bug/build/classes/java/aot/org/springframework/boot/actuate/autoconfigure/observation/ObservationAutoConfiguration__BeanDefinitions$MeterObservationHandlerConfiguration__BeanDefinitions$OnlyMetricsMeterObservationHandlerConfiguration__BeanDefinitions.class: File name too long
    public static class OnlyMetricsMeterObservationHandlerConfiguration__BeanDefinitions {
```

### Environment:

-  Ubuntu 22.04.1 LTS
-  openjdk 17.0.5 2022-10-18
- OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
- OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

[actuator-bug.zip](https://github.com/spring-projects/spring-boot/files/10442947/actuator-bug.zip)

**Comment by philwebb** [comment]
Suggestion from @wilkinsona would be to remove `__BeanDefinitions` for nested classes. E.g

```
ObservationAutoConfiguration__BeanDefinitions$MeterObservationHandlerConfiguration__BeanDefinitions$OnlyMetricsMeterObservationHandlerConfiguration__BeanDefinitions.class
```

Becomes

```
ObservationAutoConfiguration__BeanDefinitions$MeterObservationHandlerConfiguration$OnlyMetricsMeterObservationHandlerConfiguration.class
```

**Comment by adisesha** [comment]
@snicoll Thank you. I will test it and let you know.
