### ISSUE TITLE
API Doc link Broken

### ISSUE THREAD

**Issue by pawankaushal** [spring-projects/spring-framework#29871]
the link for API in https://spring.io/projects/spring-cloud-function#learn is broken :

https://docs.spring.io/spring-cloud-function/docs/current/api/ is broken

**Comment by bclozel** [comment]
There is [no JavaDoc published for this project right now](https://docs.spring.io/spring-cloud-function/docs/current/). Could you [reach out to the project maintainers](https://github.com/spring-cloud/spring-cloud-function/issues) and explain which type of documentation you're looking for?

Thanks
