### ISSUE TITLE
Include all Hibernate query methods in `SharedEntityManagerCreator`'s `queryTerminatingMethods` set

### ISSUE THREAD

**Issue by mansonng** [spring-projects/spring-framework#29886]
Similar to the issue https://github.com/spring-projects/spring-framework/issues/23248

The `org.springframework.orm.jpa.SharedEntityManagerCreator.queryTerminatingMethods` does not contain the "uniqueResult" method:

<img width="563" alt="SharedEntityManagerCreator#queryTerminatingMethods" src="https://user-images.githubusercontent.com/22072576/214754760-2e9e2507-ea7b-4592-a34e-93566e1f9175.png">

When the EntityManager is closed and `org.hibernate.query.Query.uniqueResult()` is used, as QueryImpl is delegated by DeferredQueryInvocationHandler, the database connection could not be released:

<img width="563" alt="SharedEntityManagerCreator#queryTerminatingMethods-uniqueResult" src="https://user-images.githubusercontent.com/22072576/214754891-1b93ca93-15cc-4263-8080-3b3a87290b76.png">

Seems `uniqueResult` might not be used here, but add this could prevent this issue as it could not stop developers to use `uniqueResult`.
Would it be possitble to add `uniqueResult`?

**Comment by sbrannen** [comment]
Indeed, this is very similar to #23248 and therefore seems like a reasonable enhancement.

Though, if we're going to support Hibernate's `list()` and `uniqueResult()` methods, I think we should probably go ahead and support the following as well.

- `uniqueResultOptional()`
- `stream()`

@jhoeller, thoughts?

**Comment by jhoeller** [comment]
Indeed, it does not hurt to aim for complete coverage of Hibernate's query execution methods there. Since the aforementioned methods all seem to be present in Hibernate ORM 5.6 already, we should also backport this to Spring Framework 5.3.26.

**Comment by sbrannen** [comment]
This has been addressed as described in commit 57fb0722154696474e3b47911a4cbd491451fda8 for inclusion in `6.0.5` and backported to `5.3.26` in commit 3d6d853bbc99d2321a46385466e0150885b9f4bb.
