### ISSUE TITLE
Spring-Web Very High Vulnerability in 5.x.x Version

### ISSUE THREAD

**Issue by akash-chourasia** [spring-projects/spring-framework#29907]
We are using spring-web in one of our projects which uses Java 8 and Veracode has reported a v high flaw in spring-web framework.
I know updated 6.x.x has been released and it's vulnerability free but in order to update to spirng 6 Java needs to be updated considering our project is very old and on path of EOL by this Sept upgrading it to Java 17 is somewhat not a feasible option.
Can we have release for 5.x.x version with this vulnerability fixed?

**Comment by bclozel** [comment]
I assume this is a duplicate of #24434
