### ISSUE TITLE
Document instrumentation for RestTemplate and/or WebClient

### ISSUE THREAD

**Issue by oppegard** [spring-projects/spring-framework#29904]
**Affects:** 6.0.x

---

The following callout was written in the [Spring Sleuth documentation for HTTP clients](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-http-client-integration):

> You have to register RestTemplate as a bean so that the interceptors get injected. If you create a RestTemplate instance with a new keyword, the instrumentation does NOT work.

I can't figure out if the same guidance applies in 6.0.x for Micrometer Tracing at either:
- https://docs.spring.io/spring-framework/docs/6.0.4/reference/html/web.html#webmvc-client
- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.micrometer-tracing

**Comment by bclozel** [comment]
I'll create a follow-up issue in Spring Boot to do the same.
