### ISSUE TITLE
After Spring Upgarde to version 5.3.24 the tmp folder size keep on increasing till app server up gets 100% full

### ISSUE THREAD

**Issue by vishwanath-nuance** [spring-projects/spring-framework#29929]
Dear Team,
Recently we have migrated the Spring version to 5.3.24 from spring 4.x version. Our observation as bellow.
The tmp folder size keeps on grow when we ran load test and after specific hour the size gets 100% full.
When we ran the same application on older version Spring 4.3.30 everything works fine the size wont grow more than 10% even after we ran for 12 hour.I have attached snap shot.
Our Application run on different core size of 32 core/blade. During request process we always delete the file created in temp folder to make sure the folder size does not grow. But when we check manually the size show in on /tmp folder keeps on increase ,but inside tmp folder the size shows less than 50MB size. After some hour the tmp folder size gets full and we wont be able to do any process  say write , read and delete beacuse it show space full. When we stop app server the size of /tmp will reduced to 1%. Some where the Spring consuming /tmp folder the number request we hit, the size of /tmp folder keeps on grow.

Please guide us to resolve the issue. This is happening when we upgraded the spring with 5.3.24 version. Even tried 5.3.25 version same issue.
Java we use open jdk version 8 zulu, Server jetty 9.x version.

![Spring-5-upgrade-version 5 3 24](https://user-images.githubusercontent.com/60250684/216779715-64b1445b-1587-47f9-9a3f-0b324c6ed7ab.PNG)
![Spring-4-version-4 3 30](https://user-images.githubusercontent.com/60250684/216779730-11c5575e-ae75-48b8-b57d-10b80221a89d.PNG)

Thanks

**Comment by Cadarin212** [comment]
https://user-images.githubusercontent.com/122121545/217324339-44c61422-38df-4cde-ba28-1a19d66f385e.mp4

#29931

**Comment by rstoyanchev** [comment]
Maybe investigate what's in the tmp folder to try and get a clue if there are extra files, or larger files, and what they relate to? Could it be related to file uploads, for example, or something related to the server upgrade?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by vishwanath-nuance** [comment]
Thanks for the update. We have resolved the issue. It was problem of Resource we used for file reading but never closed the stream. Surprisingly how did it work for Spring 4.3.30 it is a still question.

**Comment by sbrannen** [comment]
@vishwanath-nuance, thanks for letting us know.
