### ISSUE TITLE
Update documentation according to testcontainer example

### ISSUE THREAD

**Issue by samuelstein** [spring-projects/spring-framework#29936]
According to the testcontainer example the container should be started first. Otherwise it could lead to container port mapping problems.
See: https://github.com/testcontainers/testcontainers-java/blob/main/examples/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java

**Comment by sbrannen** [comment]
- Superseded by #29937

**Comment by sbrannen** [comment]
Hi @samuelstein,

Congratulations on creating your first issue and PR for the Spring Framework. 👍 

In the future, please do not create an issue _and_ a PR for the same topic. The PR suffices since we will always close the issue as "superseded".

Thanks

**Comment by samuelstein** [comment]
Hi @sbrannen ,
thx for clarification. i will follow this process in the future
