### ISSUE TITLE
How to register a custom `CacheAwareContextLoaderDelegate` in Spring 6?

### ISSUE THREAD

**Issue by HzjNeverStop** [spring-projects/spring-framework#29952]
I custom an CacheAwareContextLoaderDelegate to cache context exception to make the tests use same configuration witch init fail could fail fast, and use “spring.test.context.default.CacheAwareContextLoaderDelegate” param to enable it, it works in Spring5.3.x version.

But it Spring 6, it dose not work, I see the issue that remove it: https://github.com/spring-projects/spring-framework/issues/29061.

So how to custom CacheAwareContextLoaderDelegate in Spring 6？

**Comment by sbrannen** [comment]
Hi @HzjNeverStop,

I am not sure if I understood the use case you described; however, it sounds like it might be the same as the following.

- #14182

If #14182 is implemented, would that suit your needs?

**Comment by HzjNeverStop** [comment]
> Hi @HzjNeverStop,
> 
> I am not sure if I understood the use case you described; however, it sounds like it might be the same as the following.
> 
> * [Avoid repeated attempts to load failing ApplicationContext in the TestContext framework [SPR-9548] #14182](https://github.com/spring-projects/spring-framework/issues/14182)
> 
> If #14182 is implemented, would that suit your needs?

yes，I register a custom CacheAwareContextLoaderDelegate to do same thing, It would be better if the authorities could provide a standard solution.

**Comment by sbrannen** [comment]
FYI: the following issue has been resolved. Built-in support for a "context failure threshold" will come with Spring Framework 6.1.

- #14182
