### ISSUE TITLE
ASM upgrade for JDK 20/21 support

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#29966]
While Spring Framework 6.0 is on ASM 9.4+ (latest ASM master including early JDK 21 support) in the meantime, the 5.3.x branch is still on ASM 9.3 (which cuts off at JDK 19 bytecode level). Catching up with #29305 and #29910, we intend to bring JDK 20 and 21 support to Spring Framework 5.3.26 as well now.

**Comment by kundana-boddeti** [comment]
Hi facing some issues "Spring framework 5.3.26 petclinic application and JDK21 " when petclinic is deployed on weblogic.Help is appreciated .

**Comment by bclozel** [comment]
This is being handled in https://github.com/spring-petclinic/spring-framework-petclinic/issues/98
