### ISSUE TITLE
DefaultHandlerExceptionResolver::doResolveException no longer returns resolved ModelAndView

### ISSUE THREAD

**Issue by ryber** [spring-projects/spring-framework#29971]
Impacted Version: spring-webmvc-6.0.4

Previously 

```DefaultHandlerExceptionResolver::doResolveException(HttpServletRequest request, HttpServletResponse response, @Nullable Object handler, Exception ex)``` 

would return the ModelAndView when it was resolved from one of the specific methods (like handleHttpRequestMethodNotSupported)

Starting with 6, this method now sets a local variable of the ModelAndView and then does NOT return it. It ALWAYS returns null. in these cases.

see https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/support/DefaultHandlerExceptionResolver.java#L167-L248

**Comment by rstoyanchev** [comment]
I presume in the case when you override a protected method to handle an exception, the resulting `ModelAndView` ends up being ignored.

**Comment by ryber** [comment]
yes, well, specifically I'm getting a NullPointerException because I am expecting it to be returned

**Comment by ryber** [comment]
for now I have copied in the method from Spring 5 as a workaround
