### ISSUE TITLE
A question about license.

### ISSUE THREAD

**Issue by wangliang181230** [spring-projects/spring-framework#29982]
In order to support `native-image`, `Seata` uses `spring-aot` related classes, but these classes are compiled based on `jdk17`.

In order to continue to provide what the `seata-*.jar` compiled based on `jdk8`, `Seata` has copied a lot of `spring-framework` classes, and removed their fields and method bodies. However, this module are only used at compile time, not at run time.

Does this violate the license?

See the copied classes https://github.com/seata/seata/tree/native/spring-framework-fake-for-java8.
At present, we have not released the branch `native` of seata.

**Comment by sdeleuze** [comment]
Hi, I am not a lawyer, but if you copied and modifed Spring Framework files, I think it would be better to retain the license header with the original copyright and Javadoc authors in the Javadoc.

So I would advise updating https://github.com/seata/seata/blob/native/spring-framework-fake-for-java8/src/main/java/org/springframework/aot/generate/GenerationContext.java with:
 `Copyright 1999-2019 Seata.io Group.`
changed to 
`Copyright 2002-2023 the original author or authors.`

And
```
@author wang.liang
```
To
```
@author Phillip Webb
@author Stephane Nicoll
@author wang.liang
```
Same for other files. Is it ok for your point of view?

**Comment by wangliang181230** [comment]
> Hi, I am not a lawyer, but if you copied and modifed Spring Framework files, I think it would be better to retain the license header with the original copyright and Javadoc authors in the Javadoc.
> 
> So I would advise updating https://github.com/seata/seata/blob/native/spring-framework-fake-for-java8/src/main/java/org/springframework/aot/generate/GenerationContext.java with: `Copyright 1999-2019 Seata.io Group.` changed to `Copyright 2002-2023 the original author or authors.`
> 
> And
> 
> ```
> @author wang.liang
> ```
> 
> To
> 
> ```
> @author Phillip Webb
> @author Stephane Nicoll
> @author wang.liang
> ```
> 
> Same for other files.

OK, I will update all the classes.


> Is it ok for your point of view?

Yes, Thanks.
