### ISSUE TITLE
Tracing: Allow specific paths to be excluded

### ISSUE THREAD

**Issue by rolaca11** [spring-projects/spring-framework#29995]
**Affects:** 6.0.0+

---

When I enabled tracing in spring-web, I noticed, that even the actuator endpoints are included in the reported traces, which creates a lot of clutter and potentially cost in deployments, where the actuator endpoints are periodically pinged to check the health of instances.

There should be an option to exclude specific endpoints from tracing.

From what I could gather, maybe the best starting point would be the `org.springframework.web.filter.ServerHttpObservationFilter`. Either during creation of the `FilterRegistrationBean`, or in the class itself, a URL matcher logic could fit pretty neatly.

Another idea is to allow the probability of traces to be configured more granularly.

**Comment by bclozel** [comment]
Duplicates #29210
