### ISSUE TITLE
org.hibernate.criterion.Criterion ClassNotFoundException in migrating to Hibernate 6.1.6 with spring-orm 6.0.0

### ISSUE THREAD

**Issue by KarunaSahu11** [spring-projects/spring-framework#30039]
I’m migrating a legacy application with spring-orm-6.x with Hibernate 6.1.6.Final version. While running the application, the at new HibernateTemplate(session), following error is being thrown: Caused by: java.lang.ClassNotFoundException: org.hibernate.criterion.Criterion at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) … 158 more

When tried to find this class, this looks to be removed from hibernate 6.x versions. As soon I downgrade to hibernate 5.x version this works fine and HibernateTemplate object gets created but I need to migrate to Hibernate 6.1.x version as this is the compatible version with spring framework 6.0. Please help on this asap.

I tried looking into build path related issues and removed all older versions but still issue persists.

**Comment by mdeinum** [comment]
There is no Hibernate6 version of the `HibernateTemplate` as it has been the recommendation for some time to use the plain `Session` API (from Hibernate) in favor of the `HibernateTemplate`. This is also mentioned in the [javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/orm/hibernate5/HibernateTemplate.html) of the `HibernateTemplate`. 

> NOTE: Hibernate access code can also be coded against the native Hibernate [`Session`](https://docs.jboss.org/jbossas/javadoc/7.1.2.Final/org/hibernate/Session.html). Hence, for newly started projects, consider adopting the standard Hibernate style of coding against [`SessionFactory.getCurrentSession()`](https://docs.jboss.org/jbossas/javadoc/7.1.2.Final/org/hibernate/SessionFactory.html#getCurrentSession()). Alternatively, use [`execute(HibernateCallback)`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/orm/hibernate5/HibernateTemplate.html#execute(org.springframework.orm.hibernate5.HibernateCallback)) with Java 8 lambda code blocks against the callback-provided Session which results in elegant code as well, decoupled from the Hibernate Session lifecycle. The remaining operations on this HibernateTemplate are deprecated in the meantime and primarily exist as a migration helper for older Hibernate 3.x/4.x data access code in existing applications.

With that said your best approach is to migrate to the use of the `Session` API.
