### ISSUE TITLE
Unable to create object for HibernateJpaVendorAdapter 

### ISSUE THREAD

**Issue by mprasanna-raj** [spring-projects/spring-framework#30044]
I am getting below error while creating object for HibernateJpaVendorAdapter 
_Class org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider does not implement the requested interface jakarta.persistence.spi.PersistenceProvider_

In HibernateJpaVendorAdapter constructor 
jakarta.persistence.spi.persistenceProvider = new SpringHibernateJpaPersistenceProvider();

but SpringHibernateJpaPersistenceProvider class extends the org.hibernate.jpa.HibernatePersistenceProvider hence this issue.

This is happening in latest spring version.

**Comment by mprasanna-raj** [comment]
I tried with hibernate 6.1.6 It looks fine now.. thank you

**Comment by sbrannen** [comment]
Thanks for the feedback, @mprasanna-raj.

Closing this issue as a result.

**Comment by wtprashant** [comment]
I am getting this error     -  
Unsupported property type [com.example.demo.entity.Branch] for @CreationTimestamp or @UpdateTimestamp generator annotation

**Comment by snicoll** [comment]
@wtprashant I don't see how that's related and this issue is closed anyway. Please ask questions on StackOverflow.
