### ISSUE TITLE
There is an unknown problem with transaction support for reactive projects

### ISSUE THREAD

**Issue by ht-coder-wu** [spring-projects/spring-framework#30050]
### Description
  A simple demo project, using spring boot+webflux+spring data-r2dbc, stress testing, and some requesters hang for a long time until timeout.
  I'm not sure which link caused the suspension，but i did some experiments at [](url)https://github.com/ht-coder-wu/demo.
  I think :

1.  there must be some problems with connection pool or transactions
2. request is suspended for some unknown reasons in the concurrent scenario for a long time

### Version

-   spring-boot-starter-parent 2.7.8
-   r2dbc-mysql  0.8.2.RELEASE
-   r2dbc-pool  0.9.2.RELEASE
-   jdk 8

### Recurrence（occasional）
**application.properties like this:**
`spring.application.name=demo`
`spring.r2dbc.url=r2dbcs:mysql://localhost:3306/test`
`spring.r2dbc.username=root`
`spring.r2dbc.password=root`
`spring.r2dbc.pool.enabled=true`
`server.port=8080`
`logging.level.org.springframework.r2dbc=info`
`spring.r2dbc.pool.initial-size=100`
`spring.r2dbc.pool.max-size=500`

**I did four sets of tests:**
<img width="593" alt="image" src="https://user-images.githubusercontent.com/55342352/221790381-6fa1713f-71b8-48b5-b7a4-1e3b9d99937f.png">

**Their difference is :**
_testA Declarative transaction+request db_
_testB Declarative transaction+do not request db_
_testC no transaction+do not request db_
_testD no transaction+request db_

**I use scripts for concurrency testing:**
`iwtbafpdeMacBook-Pro:~ iwtbafp$ ab -n 100000 -c 100 -s 120  http://localhost:8080/testA`
<img width="528" alt="image" src="https://user-images.githubusercontent.com/55342352/221798839-2850893b-2685-4dfb-98aa-9d0887a36adf.png">

**there are 4 requests timeout(cause i set timeout 100s in webfilter and do response status 400),If I don't restart the service, continue to pressure test testD**
> request is suspended for some unknown reasons in the concurrent scenario for a long time

`iwtbafpdeMacBook-Pro:~ iwtbafp$ ab -n 100000 -c 100 -s 120  http://localhost:8080/testD`
<img width="579" alt="image" src="https://user-images.githubusercontent.com/55342352/221800353-98a75a3a-0572-45eb-afb7-608cbf48d2f1.png">

**It looks like there's no problem but there are some tx hang in db**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/55342352/221801055-1377374d-d925-40fc-85fc-6291604f092b.png">

**If i restart the service after pressure test testA and test testD directly**
`iwtbafpdeMacBook-Pro:~ iwtbafp$ ab -n 100000 -c 100 -s 120  http://localhost:8080/testD`
<img width="618" alt="image" src="https://user-images.githubusercontent.com/55342352/221820715-9484b53f-de8e-4867-b53a-6ab4ad55254a.png">
> request is suspended for some unknown reasons in the concurrent scenario for a long time

**I think there must be some problems with connection pool or transactions,It looks like testA causes some connections in the thread pool to no longer be submitted automatically,then testD which not in transaction hang in db tx.**

> there must be some problems with connection pool or transactions

**Restart the service and pressure test testB directly**
`iwtbafpdeMacBook-Pro:~ iwtbafp$ ab -n 100000 -c 100 -s 120  http://localhost:8080/testB`
<img width="532" alt="image" src="https://user-images.githubusercontent.com/55342352/221809203-37ab9e23-4bfa-4a71-926b-c9658fc33c57.png">

> request is suspended for some unknown reasons in the concurrent scenario for a long time

**Restart the service and pressure test testC directly**
`iwtbafpdeMacBook-Pro:~ iwtbafp$ ab -n 100000 -c 100 -s 120  http://localhost:8080/testC`
<img width="553" alt="image" src="https://user-images.githubusercontent.com/55342352/221814163-de23e033-bbfa-43f8-b797-981caf1844d8.png">
**I have tried this scene several times ,It seems to be all right (no transaction,no db).**

### Summarize

- testA(transaction&db)+testD ，we see tx hang in db till i restart service, there must be some problems with connection pool or transaction(Declarative & Programmatic).

- testC(no transaction&no db),  it seems to be all right.
- testB(transaction&no db),request hang till time out.
- testD(no transaction& db ),request hang till time out (Occasional appearance).
 
I'm not sure what the problem is, but it does exist，hope to get helps,thanks.

**Comment by QuantumXiecao** [comment]
@ht-coder-wu
Please check with this: When your ab hung there, you open another terminal and just use curl http://localhost:8080/test*(ABCD is all OK) for test. I think the curling result should be ok.  One possible problem is than your sysctl config for port range is not enough which would cause ab to hung there(You could cat /proc/sys/net/ipv4/ip_local_port_range to check and ajust it to 1024~65536 and do your pressure test again).

**Comment by ht-coder-wu** [comment]
> @ht-coder-wu Please check as follows: When your ab hung there, you open another terminal and just use curl http://localhost:8080/test*(ABCD is all OK) for test. I think the curling result should be ok. One possible problem is that your sysctl config for port range is not enough, which would cause ab to hang there(You could cat /proc/sys/net/ipv4/ip_local_port_range to check and ajust it to 1024~65536 and do your pressure test again).

@QuantumXiecao 
Thank you for your suggestion,I ignored the possibility of port range ,but when i adjusted it to 1024~65536 ,my ab hung there as before.
indeed, when my ab hung there,,i can curl for test,the result is ok ,i think the problem is occasional.
<img width="393" alt="image" src="https://user-images.githubusercontent.com/55342352/222076965-ed57d466-3f87-4f99-9639-5135ac9e8ea5.png">

you can see the change:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/55342352/222068532-42ad2cba-e827-43e9-9c93-78fd15bcdea5.png">

and the ab results like this:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/55342352/222069427-47f4305f-1a5b-4355-b56f-2ed2cdf6b27f.png">

4 requests hung (100s) till time out as before ,then I didn't restart services and ab testD, problems existed as before.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/55342352/222073616-42fcdb2c-fd4d-4885-8f3d-d67c43d540ad.png">

**Comment by QuantumXiecao** [comment]
@ht-coder-wu  Please try ab -n 50000(modify from 100000 to 50000) -c 100 -s 120  http://localhost:8080/testC and show us the results. Many thx!

**Comment by ht-coder-wu** [comment]
> @ht-coder-wu Please try ab -n 50000(modify from 100000 to 50000) -c 100 -s 120 http://localhost:8080/testC and show us the results. Many thx!

request 5w's result:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/55342352/222349734-0af1361b-106c-4bda-a82b-c0f6594aaa57.png">
request 10w's result:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/55342352/222350064-656a6995-be4f-4baf-b46b-ea6e6b721dcb.png">

I ignored the influence of port range factors at first,so I ab 10w times testC again .

Compare  these results，increase or decrease in quantity of request will affect the final result,connect will waste more time ,what's your opinion?

**Comment by snicoll** [comment]
@ht-coder-wu I am trying to get to the bottom of this. Do you confirm the problem goes away if that custom  filter is not registered anymore?

**Comment by ht-coder-wu** [comment]
> @ht-coder-wu I am trying to get to the bottom of this. Do you confirm the problem goes away if that custom filter is not registered anymore?

If you are referring to ContextFilter, I confirm that the problem still exists,because initially, this issue occurred in the production environment.

**Comment by snicoll** [comment]
@ht-coder-wu thanks for following-up but that wasn't my question. I am asking if the problem does not occur if `ContextFilter` is not registered.

**Comment by ht-coder-wu** [comment]
> @ht-coder-wu thanks for following-up but that wasn't my question. I am asking if the problem does not occur if `ContextFilter` is not registered.

sorry,It's my fault,I forgot to mention that ContextFilter is not registed in my production env at first.
To clarify the issue more clearly,I comment out the register code like this
<img width="832" alt="image" src="https://github.com/spring-projects/spring-framework/assets/55342352/65a4d635-c4e4-4e60-bed4-f8976722f987">

then. do testA and testD.
<img width="720" alt="image" src="https://github.com/spring-projects/spring-framework/assets/55342352/422a85af-40b3-490e-894c-9bbfacac1b5f">
some request time out ,and some tx hung as before...
<img width="460" alt="image" src="https://github.com/spring-projects/spring-framework/assets/55342352/4963e19b-3afb-43ee-97f9-e58b76301e60">

**Comment by ht-coder-wu** [comment]
by the way ,my os port range

<img width="572" alt="image" src="https://github.com/spring-projects/spring-framework/assets/55342352/ce8f00b9-0818-43b4-adec-c59d4eee31d9">

**Comment by ht-coder-wu** [comment]
I'm not sure if this issue is due to the presence or absence of transactional DB requests in the code. As transactions are managed by Spring, the current session's auto commit is set to false before the request, while connections are taken out of the connection pool for reuse, causing transactional DB requests without transactions to be suspended

**Comment by ht-coder-wu** [comment]
So it's just because the usage is incorrect,right?

**Comment by sdeleuze** [comment]
Can you please:
 - Provide a `Dockerfile` with the version/configuration of MySQL to make the reproducer usable on my side
 - Upgrade to Spring Boot 3.2.2 to ensure this is still reproducible
 - Make sure that the code in the reproduced matches what you have in production (for `ContextFilter` that does not seems to be the case since it is enabled in your repro and not in production per your comments).
- Check if you observe the same issue without transactions
