### ISSUE TITLE
Add a list of observations produced by Spring Framework

### ISSUE THREAD

**Issue by dambott** [spring-projects/spring-framework#30060]
**Affects:** \<Spring Framework version>
All versions
---
Please add a comprehensive list of metrics that are generated by the framework so they can be properly understood by anyone trying to use them.
For reference, please see:
https://kubernetes.io/docs/reference/instrumentation/metrics/
and this:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html
for the type of thing I am looking for.

**Comment by bclozel** [comment]
This should be covered by this section in the reference documentation.

https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#integration.observability.http-server

Please let us know is something is missing.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by dambott** [comment]
The referenced section does NOT provide the detail I requested. There's no list of metrics or their meanings there. Please provide something like the links I provided.

**Comment by bclozel** [comment]
We're not creating metrics per se, we're creating observations. Those observations can then [be exported as timer metrics or traces](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#integration.observability.concepts) or anything else really, depending on the `ObservationHandler` instances configured with your registry.

We don't have much there right now, but we'll expand that in the future. Would the following table fill that need?

| Observation name         | Description                                                      |
|--------------------------|------------------------------------------------------------------|
| `"http.client.requests"` | Time spent for HTTP client exchanges                             |
| `"http.server.requests"` | Processing time for HTTP server exchanges at the Framework level |

**Comment by bclozel** [comment]
Reopening to add a table similar to the one above.
