### ISSUE TITLE
Assess null-safety semantics for newly annotated packages

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30083]
This is a follow up to #30056/#30069.

**Comment by sbrannen** [comment]
- Blocked until #30056 is completed

**Comment by sbrannen** [comment]
The packages to assess can be determined by analyzing commit 99e54fec3ac8dfedd2537fde5f19fbcc4f1f6202.

**Comment by edyda99** [comment]
Hi again, can I help you with this one?

**Comment by sbrannen** [comment]
Hi @edyda99,

Thanks for the offer, but this issue is better suited for core team members.

**Comment by sbrannen** [comment]
@jhoeller, I took a first pass at updating our null-safety declarations (see recent commits on `main`).

I have now co-assigned this issue to you so that you can take another pass (and/or review the changes I made) before the 6.0.7 release.
