### ISSUE TITLE
Links are broken in KDocs

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-framework#30090]
Currently I am working on a Spring WebFlux/Kotlin Coroutines project, and explored the Spring Kotlin extensions docs frequently, but the links in these docs are still broken in 6.0.6.

https://docs.spring.io/spring-framework/docs/6.0.6/kdoc-api/spring-tx/org.springframework.transaction.reactive/transactional.html

**Comment by bclozel** [comment]
Duplicates #30091
