### ISSUE TITLE
Links are broken in KDocs

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-framework#30091]
Currently I am working on a Spring WebFlux/Kotlin Coroutines project, and explored the Spring Kotlin extensions docs frequently, but the links in these docs are still broken in 6.0.6.

For example:

https://docs.spring.io/spring-framework/docs/6.0.6/kdoc-api/spring-tx/org.springframework.transaction.reactive/transactional.html

The `TransacationalOperator.transactional` is redirected to:

https://docs.spring.io/spring-framework/docs/6.0.6/kdoc-api/spring-tx/org.springframework.transaction.reactive/-transactional-operator/transactional.html

**Comment by sdeleuze** [comment]
I think this is potentially because we don't generate the Kdoc for Java code, on purpose to not loose the Kotlin specific APIs in the Java ones but as a result links are broken. A way to fix this would be to set regular links to Spring Java API.

**Comment by sdeleuze** [comment]
After a deeper look, I tend to think that Dokka should support this use case, I have created https://github.com/Kotlin/dokka/issues/2913 related issue.

**Comment by sdeleuze** [comment]
https://github.com/Kotlin/dokka/issues/2272 is the new blocking issue for this.

**Comment by sdeleuze** [comment]
Fixed via #32797.
