### ISSUE TITLE
spring-core 5.2.35 will not build from source - getSecurityManager() deprecated method

### ISSUE THREAD

**Issue by aboncok** [spring-projects/spring-framework#30119]
Hi,

We have a requirement that we have to build all of our dependencies from source code.
Trying to build spring-core 5.3.25 from source code fails because of deprecated method with jdk17.0.3.1 and jdk18.0.1.1.
It even fails with jdk11.0.16 but for a different deprecated method - but that might expected as the documentation says that JDK 17 should be used for builds.

Am I missing something from my config? spring-boot 2.7.9 relies on this version and there is no newer for spring-boot 2.x.x.

> [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
> val] AccessControlException in java.security has been deprecated and marked for removal
> [ERROR] [system.err]                                       catch (AccessControlException ex) {
> [ERROR] [system.err]                                              ^
> [ERROR] [system.err] ../spring-framework/spring-core/src/main/java/org/springframework/core/env/SystemEnvironmentPropertySource.java:152: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
> [ERROR] [system.err]               return (System.getSecurityManager() != null);
> [ERROR] [system.err]                             ^
> [ERROR] [system.err] 1 error
> [ERROR] [system.err] 18 warnings
> [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
> [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.

**Comment by bclozel** [comment]
You'll need to build Spring Framework 5.3.x with its baseline, which is JDK8. It will be still compatible with JDK17 at runtime.
