### ISSUE TITLE
Koltin RefreshScope making empty Configuration

### ISSUE THREAD

**Issue by Monax111** [spring-projects/spring-framework#30129]
boot:2.6.4
cloud:2021.0.1

My koltin [configuration ](https://github.com/Monax111/refresh-scope/blob/master/src/main/kotlin/com/example/demo/props/MyProps.kt) is inherited from another class.
If i add RefreshScope annotation, spring create empty CGLib wrapper with null field for my configuration

[demo project](https://github.com/Monax111/refresh-scope/blob/master/src/main/kotlin/com/example/demo/props/MyProps.kt)
1) run `gradle bootRun` 
2) see in console `0 null` [for configuration](https://github.com/Monax111/refresh-scope/blob/master/src/main/kotlin/com/example/demo/client/MyClient.kt#L15)

I expected value from my [application.yaml](https://github.com/Monax111/refresh-scope/blob/master/src/main/resources/application.yaml)

**Comment by bclozel** [comment]
Assuming that this problem only happens with RefreshScope, could you [raise this issue against Spring Cloud Commons](https://github.com/spring-cloud/spring-cloud-commons/issues)?

We can take the point here and reopen this issue if it turns out it's a Framework bug. Thanks!
