### ISSUE TITLE
Spring 5.3.26  still not compatible with snakeyaml 2.0 

### ISSUE THREAD

**Issue by lzysuqianqiu** [spring-projects/spring-framework#30154]
**java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at org.springframework.boot.env.OriginTrackedYamlLoader.createYaml(OriginTrackedYamlLoader.java:80)
	at org.springframework.boot.env.OriginTrackedYamlLoader.createYaml(OriginTrackedYamlLoader.java:75)**

I see the Spring 5.3.26 RELEASE Note
Allow SnakeYaml 2.0 runtime compatibility https://github.com/spring-projects/spring-framework/issues/30097

**Comment by bclozel** [comment]
The classes listed in this stack trace are from Spring Boot. This will be fixed with https://github.com/spring-projects/spring-boot/issues/34405 in the next Spring Boot version.
