### ISSUE TITLE
WebFlux - DispatcherHandler.handlePreFlight(ServerWebExchange exchange)

### ISSUE THREAD

**Issue by gksxodnd007** [spring-projects/spring-framework#30151]
**Affects:** \<spring-webflux:5.3.20>

---

```java
	@Override
	public Mono<Void> handlePreFlight(ServerWebExchange exchange) {
		return Flux.fromIterable(this.handlerMappings != null ? this.handlerMappings : Collections.emptyList())
				.concatMap(mapping -> mapping.getHandler(exchange))
				.switchIfEmpty(Mono.fromRunnable(() -> exchange.getResponse().setStatusCode(HttpStatus.FORBIDDEN)))
				.next()
				.then();
	}
```
cors process code exists in AbstractHandlerMapping.getHandler(..), and if the getHandler method return empty since not found route the cors process will not be invoked. but DispatcherServlet.handlerPreFlight() always set response status code FORBIDDEN(403) even if cors condition satisfy and not found route. i think when the request handler does not found and cors condition satisfy, server has to respond 404 status code. is this action intend for something?

**Comment by gksxodnd007** [comment]
i wonder the 403 response statue code even though the cors process does not invoked. it is not problem reject request. but it responds 403 response status code event if the cors normal

**Comment by rstoyanchev** [comment]
The problem is we can't verify the CORS conditions without.
