### ISSUE TITLE
org.hibernate.criterion in HibernateOperations and HibernateTemplate

### ISSUE THREAD

**Issue by o-frias** [spring-projects/spring-framework#30174]
Hello,

In spring-framework-6.0.7 this files:
org.springframework.orm.hibernate.HibernateOperations
org.springframework.orm.hibernate.HibernateTemplate

import code from org.hibernate.criterion but that package was removed since Hibernate 6.0

So this exception appears at runtime: java.lang.ClassNotFoundException: org.hibernate.criterion.Criterion when using spring-framework-6.0.7 and  hibernate-core 6.1.7.Final

Regards,
Óscar

**Comment by sbrannen** [comment]
- Closing as a duplicate of #30039
