### ISSUE TITLE
Ensure compatibility with JDK 20

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30185]
## Overview

We need to ensure that the core Spring Framework is compatible with JDK 20.

## CI Builds

We have introduced a [JDK 20 CI build pipeline](https://ci.spring.io/teams/spring-framework/pipelines/spring-framework-6.0.x/jobs/jdk20-build/) to test compatibility with JDK 20.

## Failing Tests

We have discovered that numerous tests begin to fail on JDK 20.

The ones related to JPA have been failing since JDK 18 but should still be investigated to determine why they no longer pass (and eventually better documented).

Other tests related to date/time parsing and formatting fail because of a switch from a normal space to a _narrow non-breaking space_ (NNBSP) between a time and an AM/PM unit (for example, the whitespace in `12:00 AM`). See commit 84714fbae9f335beb059753ee7d2a08653e6bb6c for details.

## Related Resources

- https://jdk.java.net/20/release-notes#JDK-8284840
- https://unicode-org.atlassian.net/browse/CLDR-14032
- https://bugs.openjdk.org/browse/JDK-8223587
- https://bugs.openjdk.org/browse/JDK-8284840
- https://bugs.openjdk.org/browse/JDK-8297316
- https://bugs.openjdk.org/browse/JDK-8304925

**Comment by NPException** [comment]
Just commenting to add another bug report with the same cause: https://bugs.openjdk.org/browse/JDK-8304925
