### ISSUE TITLE
@Async不支持循环依赖, 为什么不设计成支持循环依赖呢

### ISSUE THREAD

**Issue by stevenxyy** [spring-projects/spring-framework#30190]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
After translation:

> It does not support cyclic dependencies. Why is it not designed to support cyclic dependencies?

Please use StackOverflow for questions. If you believe this is a bug, please provide a sample application that demonstrates the issue and we can reopen this ticket.
