### ISSUE TITLE
"jdeps -jdkinternals" throwing usage of JDK internal API

### ISSUE THREAD

**Issue by ilapavuluri** [spring-projects/spring-framework#30234]
Hi Team,

As part of Java17 upgrade when I ran "jdeps -jdkinternals spring-core.jar" for 5.3.18 version I am getting below error:

spring-core.jar -> jdk.unsupported
   org.springframework.objenesis.instantiator.sun.UnsafeFactoryInstantiator -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)
   org.springframework.objenesis.instantiator.util.UnsafeUtils -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependence on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

It is complaining about usage of internal API's for objenesis. The version of objenesis is 3.2

Please do the needful.

Thanks
Ashok.

**Comment by snicoll** [comment]
@ilapavuluri thanks but we repackage Objenesis, which is a different project. This has been reported at the right place already, see https://github.com/easymock/objenesis/issues/70

**Comment by ilapavuluri** [comment]
@snicoll Thank you for the response, will look into that.
