### ISSUE TITLE
Document that `@Sql` requires `spring-jdbc` and `spring-tx` on the classpath

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#30280]
The current documentation - through _javadoc_ and _reference documentation_ -  has an interesting situation regarding `@Sql` behavior: it needs the `spring-jdbc` and `spring-tx` modules in the classpath. Otherwise, `@Sql` is completely ignored.

I noticed this when I had invalid paths referring to `.sql` files.

For more details, please read the following post on SO.

- [Why is @Sql ignored in my Spring integration tests?](https://stackoverflow.com/questions/75903775/spring-test-sql-working-directly-with-datasource-and-without-transactions)

Thanks for your understanding

**Comment by manueljordan** [comment]
@sbrannen thanks for the improvement, just a friendly observation, in the two files edited, appears twice the ` ... requires that that the ...` part, where exists a problem: the `that that` appears twice. 

As indicated, I confirmed that dependencies `spring-jdbc` and `spring-tx` are mandatory. Where the latter is a transitive dependency of the former. Of course to avoid confusions, is nice declare explicitly both

**Comment by sbrannen** [comment]
Thanks for the feedback, @manueljordan. 👍 

I pushed a polishing commit: 8bb4c167e443a25f1cd19a05242d30235c32ca1b.

**Comment by manueljordan** [comment]
@sbrannen  Just in case ... about the following part that appears twice 

> requires the {@code spring-jdbc} and {@code spring-tx}  modules as well as their transitive dependencies to be present on the classpath

should be 

> requires the {@code spring-jdbc} and {@code spring-tx} modules to be present on the classpath

I wrote just an observation to be _not_ included that `spring-tx` is a transitive dependency of `spring-jdbc`
