### ISSUE TITLE
Allow API-only MVC apps to never create HttpSessions

### ISSUE THREAD

**Issue by dougbreaux** [spring-projects/spring-framework#30292]
**Affects:** \<Spring Framework version>

---

See this request on StackOverflow, which I found when searching for how to do the same thing:

https://stackoverflow.com/q/53406486/796761

**Comment by dougbreaux** [comment]
No security stack, no JSPs. So I don't understand either. Neither did the OP on SO think they had anything else creating sessions. 🤷 

But, I'll say, I'm just using `@Controller`, not `@RestController`. I didn't see anywhere that this would make that difference, but maybe it does?

**Comment by bclozel** [comment]
Why not ask your own question on StackOverflow, sharing a code snippet of what you're trying to achieve? The question you're pointing at does use a security stack (apparently not Spring Security) so this does not relate to your case.

**Comment by dougbreaux** [comment]
Ok, I didn't detect that the question above used a security stack. And, when I did a standalone test for one of my controllers in question, I see that it does _not_ return a JSESSIONID, as you say. I must have been looking at a different application that did do additional things. 

Thank you for the dialogue.
