### ISSUE TITLE
Add support for converting a String to an Instant

### ISSUE THREAD

**Issue by JanecekPetr** [spring-projects/spring-framework#30312]
What I'm trying to achieve:

```java
@ConfigurationProperties
record ApplicationProps(Instant instant) {}
```

with the following `application.properties`:
```
instant = 1680612880417
```
where the value is millis since the epoch, see [`Instant.ofEpochMilli()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Instant.html#ofEpochMilli(long)).

Edit:
Currently this fails with a
```
...
Caused by: java.lang.IllegalArgumentException: Parse attempt failed for value [123456789]
	at org.springframework.format.support.FormattingConversionService$ParserConverter.convert(FormattingConversionService.java:224) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-6.0.6.jar:6.0.6]
	... 117 common frames omitted
Caused by: java.time.format.DateTimeParseException: Text '123456789' could not be parsed at index 0
```

Perhaps this is a good candidate for a default binding.

Considerations:
- Why are we choosing `Instant.ofEpochMilli()` and not `Instant.ofEpochSecond()`? It just felt more natural. Is this uncertainty reason enough to refuse this request? That said, there already is a registered-by-default `Converter<Long, Instant>` which uses `ofEpochMilli`. Therefore, an additional Formatter would be consistent with the already-existing Converter.
- Do we also need to add more similar formatters for types like `java.util.Date` or `java.sql.Timestamp`? I do no think think so as neither of them has a simple `ofEpochMilli()`-like creator method or clear semantics. Other `java.time` also are not good targets for this unless OffsetDateTime/ZonedDateTime is considered okay given a default timezone.

**Comment by RemusRD** [comment]
Hey! Can I take this one? :)

**Comment by simonbasle** [comment]
@RemusRD I think it is worth a shot yes. From my perspective it should be possible to retrofit this parsing into existing `InstantFormatter`. I have the following test to suggest in `DateTimeFormattingTests.java`, but please include other more direct unit tests as well:

```java

	@Test
	void testBindInstantAsLongEpochMillis() {
		MutablePropertyValues propertyValues = new MutablePropertyValues();
		propertyValues.add("instant", 1234L);
		binder.bind(propertyValues);
		assertThat(binder.getBindingResult().getErrorCount()).isZero();
		assertThat(binder.getBindingResult().getRawFieldValue("instant"))
				.isInstanceOf(Instant.class)
				.isEqualTo(Instant.ofEpochMilli(1234L));
		assertThat(binder.getBindingResult().getFieldValue("instant"))
				.hasToString("1970-01-01T00:00:01.234Z");
	}
```

**Comment by RemusRD** [comment]
> @RemusRD I think it is worth a shot yes. From my perspective it should be possible to retrofit this parsing into existing `InstantFormatter`. I have the following test to suggest in `DateTimeFormattingTests.java`, but please include other more direct unit tests as well:
> 
> ```java
> 	@Test
> 	void testBindInstantAsLongEpochMillis() {
> 		MutablePropertyValues propertyValues = new MutablePropertyValues();
> 		propertyValues.add("instant", 1234L);
> 		binder.bind(propertyValues);
> 		assertThat(binder.getBindingResult().getErrorCount()).isZero();
> 		assertThat(binder.getBindingResult().getRawFieldValue("instant"))
> 				.isInstanceOf(Instant.class)
> 				.isEqualTo(Instant.ofEpochMilli(1234L));
> 		assertThat(binder.getBindingResult().getFieldValue("instant"))
> 				.hasToString("1970-01-01T00:00:01.234Z");
> 	}
> ```

I already started working on this! I added your test which seems to be already passing, should I keep it? 

Also, would be great if you could share with me any other merge requests that are already implemented similar to this one so I can take inspiration :) from.

**Comment by simonbasle** [comment]
yeah `RandomInstantProvider` is not a good fit because it will create `Instant`s that fall off the limit of epochMillis (due to using seconds and not millis). You could take inspiration from it to create a similar provider which uses `ofEpochMillis(Long.MIN_VALUE)`/`ofEpochMilli(Long.MAX_VALUE)`. I would also advise to `truncateTo(ChronoUnit.MILLIS)` each generated `Instant`.

**Comment by simonbasle** [comment]
any progress @RemusRD ?

**Comment by RemusRD** [comment]
> any progress @RemusRD ?

Submitting the PR shortly, I added tests into the InstantFormatter, wondering if it would make sense to do a more end to end test? Like checking it works from parsing a yaml or something like that.

**Comment by RemusRD** [comment]
@simonbasle I have opened the PR, but not sure how I can link it here? https://github.com/spring-projects/spring-framework/pull/30546

**Comment by simonbasle** [comment]
superseded by gh-30546
