### ISSUE TITLE
Execution failed for task ':checkstyleNohttp'. > java.lang.IllegalStateException: Could not load file 'src/nohttp/allowlist.lines'

### ISSUE THREAD

**Issue by mlyszxy** [spring-projects/spring-framework#30311]
在编译Spring框架5.2.15版本源码时，报 Execution failed for task ':checkstyleNohttp'.
> java.lang.IllegalStateException: Could not load file 'src/nohttp/allowlist.lines'

**Comment by bclozel** [comment]
I'm sorry, but [Spring Framework 5.2.x is out of open source support](https://spring.io/projects/spring-framework#support), so we can't help you here.
