### ISSUE TITLE
`@SessionAttributes` handler invoked too early if controller method execution is deferred

### ISSUE THREAD

**Issue by daihuabin** [spring-projects/spring-framework#30337]
`saveModel` will be executed before the controller method when the return value is `Mono<View>`

https://github.com/spring-projects/spring-framework/blob/19c7527376233c6a5ea42fb6920d004b7be79d66/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/RequestMappingHandlerAdapter.java#L203

**Comment by rstoyanchev** [comment]
Indeed, this should be executed later, probably as part of result handling in `ViewResolutionResultHandler` where we also use `BindingContext` to update the model with `BindingResult`.

**Comment by rstoyanchev** [comment]
Fixed in 74972fb75139d46fa6873717728eca15e49c0558 but referenced the wrong issue.
