### ISSUE TITLE
Enhancement: Concurrentreferencehashmap implementation, using segment lock instead of CAS

### ISSUE THREAD

**Issue by lan-dian** [spring-projects/spring-framework#30379]
**Affects:** Spring Framework version ：2.3.7

---

I use this class, as the cache layer, we have very little data, but read and write frequently, data is acceptable to lose, so I use this class, but I find that this class still uses JDK 1.7's fragmentation lock implementation scheme, not 1.8's CAS implementation scheme.

**Comment by bclozel** [comment]
The usage profile you've just described doesn't fit well with what Framework is doing with this class. So I don't think we should change the behavior here to accommodate for this case.

Maybe our ConcurrentLruCache class would be an alternate solution, or even better using a caching library like Caffeine.
