### ISSUE TITLE
Improve documentation about @Value without SpEL for default values - when ":" vs "?:"

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#30384]
In the current documentation - about `@Value` by applying _default values_, assuming that the `host.ipv6` key does **not** exist

Therefore for Spring 6 working with `@Value` and **without** `SpeL` such as:

    @Value("${host.ipv6:not defined}")
    @Value("${host.ipv6?:not defined}")

Both work by returning `not defined` as expected - it as the _default value_.

What is not clear in the current documentation: When is mandatory `:` and `?:` each one over the other?

There are more details about this ... please see the following SO post:

* [@Value working to apply "default value" - When is mandatory ":" and "?:" each one over the other?](https://stackoverflow.com/questions/76095980/value-working-to-apply-default-value-when-is-mandatory-and-each-on)

Thanks for your understanding

**Comment by snicoll** [comment]
Thanks for the suggestion but I don't think we need to do anything. The [current section](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/value-annotations.html) of the documentation is already pretty explicit about what to do. It states how you can specify a default value and that SpEL is also possible. The elvis operator is actually using SpEL.
