### ISSUE TITLE
Improve documentation: Why getEnvironment().getActiveProfiles() reports the not applied profiles active?

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#30385]
It could be illogical this issue, but should be expanded the explanation about, what is the purpose of `getEnvironment().getActiveProfiles()`. 

Yes the method's name is explicitly is clear by itself and the javadoc is available, but the _practice_ over the _theory_ is **not** the same. It because `getEnvironment().getActiveProfiles()` shows or consider profiles that really were **not** applied.

For more details, see the following SO post

* [Why getEnvironment().getActiveProfiles() reports the not applied "profiles active"?](https://stackoverflow.com/questions/76105867/why-getenvironment-getactiveprofiles-reports-the-not-applied-profiles-activ)

Thanks for your understanding

**Comment by snicoll** [comment]
The `Environment` is not frozen once the context has been refreshed. You are misusing the API by mutating the `spring.profiles.active` property **after** the. context has refreshed. Essentially, you let the container start with whatever profile is there at that point and, once it has fully started, you set a different value for the property.

There are a lot of other cases where something like this happens. For instance you could a bean that is guarded by a condition on property. If you set the property to a different value, the bean will have been created anyway and your environment won't reflect the state in which the condition was evaluated.

I am going to close this now as I don't think we should be upgrading our Javadoc for an API misuse.
