### ISSUE TITLE
Documentation: ServletUriComponentsBuilder returns encoded UCBs

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-framework#30408]
**Affects:** 5.3.27

---
The methods in `ServletUriComponentsBuilder` return `UriComponentsBuilder` objects that are already encoded. (This is inconvenient, but for backwards-compatibility probably unchangeable.) This behavior is not obvious, and the Javadocs should mention this to clients.

**Comment by bclozel** [comment]
Closing as in the meantime we've updated the Javadoc and added [a dedicated section in the reference docs about this](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-uri-building.html).

Sorry it took us so long to get to your issue. Thanks!
