### ISSUE TITLE
Support for `InjectionPoint` in bean factory methods when using AOT

### ISSUE THREAD

**Issue by f-cramer** [spring-projects/spring-framework#30401]
**Affects:** Spring Framework 6.0.8

When using AOT (via gradle `bootBuildImage` task) any bean factory method that has a parameter of type `InjectionPoint` results in an `UnsatisfiedDependencyException` thrown in `BeanInstanceSupplier.java:343`.

It should be possible to inject such an instance because it is also created when creating the exception.

For an MCVE see [here](https://github.com/f-cramer/spring-aot-injectionpoint).

When started with `./gradlew :bootRun` it successfully executes and logs `running logging runner`.

When starting the image that is produced with `./gradlew :bootBuildImage` it fails with the following message

> ***************************
> APPLICATION FAILED TO START
> ***************************
>  
> Description:
>  
> Parameter 0 of method logger in com.example.injectionpoint.LoggerConfiguration required a bean of type 'org.springframework.beans.factory.InjectionPoint' that could not be found.

**Comment by snicoll** [comment]
Good catch @f-cramer and thanks for the reproducer.
