### ISSUE TITLE
@ComponentScan filter bean annotation error

### ISSUE THREAD

**Issue by CodeMan-cmd** [spring-projects/spring-framework#30426]
I am using a custom @ComponentScan.Filter(type = FilterType.CUSTOM, classes = {MyFilterType.class}) If MyFilterType is an internal class, an error will be reported.
After investigation, it was found that it was caused by parsing @ComponentScan.Filter(type = FilterType.CUSTOM, classes = {MyFilterType.class}). If it is an inner class, constructors[0].getParameterCount() > 0 will be equal to true. In fact, there are no parameters.

Error content:
Caused by: java.lang.IllegalStateException: Illegal method parameter type: org.tong.learn.tripartite_function.GlobalBeanConfig

Error code:
1、Judgment Constructor parameters
![image](https://user-images.githubusercontent.com/52879329/236417961-a8e44622-9ec3-4cf0-8ab0-523732797f05.png)
2、Error parsing constructor parameters
![image](https://user-images.githubusercontent.com/52879329/236419154-8ce8c58a-3506-45e6-a53d-2e66c0111192.png)

**Comment by snicoll** [comment]
`MyFilterType` should be `static`. If it isn't, we need access to the parent instance to create that and it's impossible for us to do that.

**Comment by CodeMan-cmd** [comment]
> `MyFilterType` should be `static`. If it isn't, we need access to the parent instance to create it and it's impossible for us to do that. Going forward, please show your code or share a sample project, rather than screenshots of our own code.

OK
