### ISSUE TITLE
Support Kotlin value class properties in SpEL

### ISSUE THREAD

**Issue by christianhujer** [spring-projects/spring-framework#30468]
It would be great if SpringEL could be improved to support Kotlin Value Classes (probably by unmangling mangled Kotlin names).

I had the following issue.

Class:
```kotlin
data class Something(
    val id: UUID<Something>,
    val name: String,
)
```
It worked everywhere except in Thymeleaf. When I was using it in Thymeleaf, I got an exception:
```
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/pages/Something.html]")
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "something.id" (template: "pages/Something" - line 277, col 4)
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "something.id" (template: "pages/Something" - line 277, col 4)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'id' cannot be found on object of type 'com.example.Something' - maybe not public or not valid?
```

Turns out, the problem was that the field `id` was of a type that itself is a _Kotlin Value Class_.

What are Kotlin Value Classes?

Kotlin Value Classes are classes that wrap other values, granting more type safety during compilation in Kotlin, without introducing the indirection overhead of a regular class.

Examples:
```kotlin
@JvmInline value class Latitude(val latitude: Double)
@JvmInline value class Longitude(val longitude: Double)
@JvmInline value class UUID<TargetType>(val value: java.util.UUID)
```

When value classes are used, the Kotlin compiler mangles the name of the context function to prevent name conflicts when overloading:
```kotlin
class Location {
    fun updateLocation(latitude: Double, longitude: Double)
    fun updateLocation(latitude: Latitude, longitude: Longitude)
}
```
The actual signature of the second `updateLocation` function would also be `updateLocation(Double, Double)`, which clashes with the first definition. To prevent that, Kotlin mangles the name into something like `updateLocation-hash`.

This also applies to the getter for properties:
```kotlin
data class Location(
    val latitude: Latitude,
    val longitude: Longitude,
)

@Entity data class Something(
    @Id
    val id: UUID<Something>,
    val name: String,
)
```
The names for the getters of the properties will be mangled.

To work nicely in Spring, a few pieces are required:
* Support by Jackson Serialization - done, Jackson detects and unmangles mangled names to get JSON property names without the mangling suffix. :+1:
* Support by Jackson Deserialization - open
* Support by Hibernate - done, Hibernate detects and unmangles mangled names to create column names without the mangling suffix. :+1:
* Support by SpringEL - missing, SpringEL is unaware of Kotlin's name mangling. This is of particular interest for Thymeleaf users as Spring Thymeleaf uses SpringEL inside HTML.

Workaround: Until SpringEL supports Kotlin name mangling, explicitly override the mangled getter name, like this:
```kotlin
data class Location(
    @get:JvmName("getLatitude")
    val latitude: Latitude,
    @get:JvmName("getLongitude")
    val longitude: Longitude,
)

@Entity data class Something(
    @Id
    @get:JvmName("id")
    val id: UUID<Something>,
    val name: String,
)
```

**Comment by quaff** [comment]
> Support by Jackson - done, Jackson detects and unmangles mangled names to get JSON property names without the mangling suffix. 👍

Jackson only supports serialization of value class, deserialization is not supported yet.
https://github.com/FasterXML/jackson-module-kotlin/issues/650

**Comment by christianhujer** [comment]
Might be related to this one? https://github.com/spring-projects/spring-framework/issues/28638

**Comment by christianhujer** [comment]
> > Support by Jackson - done, Jackson detects and unmangles mangled names to get JSON property names without the mangling suffix. +1
> 
> Jackson only supports serialization of value class, deserialization is not supported yet. [FasterXML/jackson-module-kotlin#650](https://github.com/FasterXML/jackson-module-kotlin/issues/650)

Ah thanks for clarifying. I've updated my comment accordingly. Seems I got lucky so far that I didn't have Deserialization issues on value classes.
