### ISSUE TITLE
InjectionMetadata AOT contributions do not check for existing property value

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#30476]
AOT contribution for `PersistenceContext` does not check for the presence of an existing property in the related bean definition. Rather than using the configured property, it will contribute some code that tries to inject the default EMF.

See also https://github.com/spring-projects/spring-data-jpa/issues/2753

**Comment by snicoll** [comment]
The same applies to autowiring (albeit being much rare).

**Comment by rishiraj88** [comment]
Thanks, @snicoll , for your comment.
