### ISSUE TITLE
Consistent Support Period across Spring, Spring Batch and Spring Boot

### ISSUE THREAD

**Issue by DhavalShewale** [spring-projects/spring-framework#30487]
Hi Team,

Can we pls have a consistent support period across Spring, Spring Batch and Spring Boot libraries.

Currently, spring libraries are marked EOL roughly after 24 months, spring batch is marked EOL roughly after 18 months and spring boot is marked EOL after 12 months.

As all libraries are dependent on each other, plus as there can be applications using different flavors of the library its difficult to plan periodic updates.

Can we pls have a uniform EOL support policy for all flavors of spring - Spring, Spring Batch, Spring Boot, Spring Cloud, etc. The support policy should align to the baseline framework i.e. Spring and we should support all flavors for upto 24 months.

Regards,
Dhaval

**Comment by bclozel** [comment]
The dates displayed on spring.io are all in line with the [VMware Tanzu OSS support policy](https://tanzu.vmware.com/support/oss): minimum of 12 months for OSS support and 24 months for commercial support. As you've noticed, we tend to extend timelines as we go "lower down the stack" to ensure that such policies overlap from Spring Framework all the way up to Spring Cloud, as projects aren't release all at once. In short, all support dates are consistent with this policy.

As for the planning of updates, we are very transparent with our support policy: all EOL dates are publicly shown even before generations are released. At the time of this comment, the Spring Boot EOL dates are known until 2025-08 and for Spring Framework until 2026-12. We hope that this helps project teams to plan accordingly.

Asking us to extend free OSS support to 24 months is a big ask and would make our commercial support irrelevant in lots of cases. [VMware Spring Runtime](https://tanzu.vmware.com/spring-runtime) customers do get additional support - they are after all sponsoring the free OSS support and make it possible for the Spring team to work on new features and technologies. If the current OSS support policy does not meet your needs, please consider a Spring Runtime subscription.

Thanks!

**Comment by snicoll** [comment]
@DhavalShewale please don't cross post, especially without indicating you've done so as it leads to wasted efforts. You already got a reply in https://github.com/spring-projects/spring-boot/issues/35422 and https://github.com/spring-projects/spring-batch/issues/4375
