### ISSUE TITLE
Skip class transformer in `PersistenceUnitInfoDescriptor` for native images

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#30492]
Due to [this change](https://github.com/hibernate/hibernate-orm/commit/800873c43d44bc954cef8f4abb11bfe4719570a8) in Hibernate 6.2, Bytebuddy class enhancement is now invoked via `SpringHibernateJpaPersistenceProvider` -> `PersistenceUnitInfoDescriptor` - > `EnhancingClassTransformerImpl` -> `BytecodeProviderInitiator.buildDefaultBytecodeProvider()`, breaking Hibernate integration when compiling to native images.

This change updates the `PersistenceUnitInfoDescriptor` instance created by `SpringHibernateJpaPersistenceProvider` in order to skip the class transformer with native.

Footprint optimization will require completing #29549 is is outside of the scope of this change.

**Comment by sdeleuze** [comment]
See also related issues:
- https://github.com/oracle/graalvm-reachability-metadata/pull/286
- https://github.com/spring-projects/spring-boot/issues/35423

**Comment by edeandrea** [comment]
Hi @sdeleuze if I use Spring Framework 6.0.10-SNAPSHOT should this issue be resolved? Or is there more to it?

**Comment by davidbilge** [comment]
@edeandrea using Spring Framework 6.0.10-SNAPSHOT should be enough, provided the maven-native-plugin uses the latest available reachability metadata version (0.3.1 at the time of writing).

See my comment https://github.com/spring-projects/spring-boot/issues/35659#issuecomment-1566804157 for more details.

**Comment by edeandrea** [comment]
Thank you @davidbilge but that unfortunately didn't work.

**Comment by davidbilge** [comment]
> Thank you @davidbilge but that unfortunately didn't work.

Did you try to use a specific version (0.3.1) of the reachability metadata in your pom.xml?

**Comment by edeandrea** [comment]
Yes I did. I opened https://github.com/oracle/graalvm-reachability-metadata/issues/297 for it.

**Comment by sdeleuze** [comment]
We are going to release GraalVM metadata `0.3.2` and Native Build Tools `0.9.23` that contains all Hibernate 6.2 fixes.
