### ISSUE TITLE
spring 6.1.0 compile failed

### ISSUE THREAD

**Issue by sukai-cheng** [spring-projects/spring-framework#30504]
<img width="679" alt="image" src="https://github.com/spring-projects/spring-framework/assets/35868545/c9a3121b-aca9-4f64-a0ba-733783fe27dd">

This is solution: 
<img width="1440" alt="image" src="https://github.com/spring-projects/spring-framework/assets/35868545/c101369b-927e-43e7-8909-fb9f376ea04f">

**Comment by bclozel** [comment]
You need a local install of JDK 21 ea, see https://github.com/spring-projects/spring-framework/wiki/Build-from-Source#before-you-start
