### ISSUE TITLE
Have the ErrorResponse.Builder take in a custom ProblemDetail instance 

### ISSUE THREAD

**Issue by mzeijen** [spring-projects/spring-framework#30568]
As a user I would like to be able to create an `ErrorResponse` instance with a custom `ProblemDetail` instance, while using the default `ErrorResponse.Builder` via the `ErrorResponse.builder` and/or `ErrorResponse.create` methods. This makes it easier for me to provide a custom ProblemDetail class while still being able to use the builder facilities. 

Currently there is no way to provide my own `ProblemDetail` instance to the builder, either via a method directly on `ErrorResponse.Builder` instance or via the `ErrorResponse.create` or `ErrorResponse.builder` methods (which is probably the preferred way).  

_Note: I have discussed this feature request with @rstoyanchev at Spring I/O 2023_

**Comment by rstoyanchev** [comment]
Thanks for raising this, @mzeijen. I've added dcba9475ba6f4d743419a32947619518f80575cd in time for 6.1 M1 with plenty of time to refine further if needed.

**Comment by mzeijen** [comment]
Thanks for addressing this so quickly.
