### ISSUE TITLE
Analysis of Error and Exception in Spring Boot Data Source Configuration

### ISSUE THREAD

**Issue by 780886** [spring-projects/spring-framework#30583]
Problem Link：https://github.com/spring-projects/spring-framework/issues/30563

I think this is more like a bug, which will cause Spring to be unable to initialize beans. Looking at the following code example, as long as a bean like @ ConditionalOnClass (DruidDataSource. class) exists in the @ Configuration class, at runtime, if that class does not exist, it will cause other beans in the entire class to fail to initialize

`package com.lesson.commons.config.wrong;

import com.alibaba.druid.pool.DruidDataSource;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
@configuration
public class ClassNotFoundConfig {
@bean
public ExistingClass existingClass() {
return new ExistingClass();
}
@bean(name = "sparrow_default")
@ConditionalOnClass(DruidDataSource.class)
public DruidDataSource druidDataSource() {
DruidDataSource druidDataSource = new DruidDataSource();
return druidDataSource;
}
}`

**Comment by snicoll** [comment]
Duplicates #30563
