### ISSUE TITLE
NPE in `ReactiveTransactionSupport.unwrapIfResourceCleanupFailure`

### ISSUE THREAD

**Issue by andruskutt** [spring-projects/spring-framework#30597]
**Affects:** spring boot 3.0.7

---
in method unwrapIfResourceCleanupFailure of org.springframework.transaction.interceptor.TransactionAspectSupport.ReactiveTransactionSupport class
if ex.getMessage() returns null then we get NullPointerException:

```java
			if (ex instanceof RuntimeException &&
					ex.getCause() != null &&
					ex.getMessage().startsWith("Async resource cleanup failed")) {
				return ex.getCause();
			}
```
https://github.com/spring-projects/spring-framework/blob/main/spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAspectSupport.java#L1088

**Comment by jhoeller** [comment]
This seems to be a regression caused by #27572. To be revised for 6.0.10.
