### ISSUE TITLE
Consider to indicate explicitly that DataAccessException's hierarchy applies to NoSQL too

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#30591]
About `Spring Data`, mostly for **some** projects under the umbrella of `NoSQL`, in the _overview_ tab exists any of the two following sentences located in the **Features** section.

* Exception translation into Spring’s portable **_Data Access Exception_** hierarchy - at [Spring Data MongoDB](https://spring.io/projects/spring-data-mongodb), [Spring Data Couchbase](https://spring.io/projects/spring-data-couchbase), [Spring Data Couchbase](https://spring.io/projects/spring-data-couchbase)
* Exception Translation to the familiar Spring **DataAccessException** hierarchy - at [Spring Data for Apache Cassandra](https://spring.io/projects/spring-data-cassandra#overview)

Could be consider to indicate _explicitly_ at the current reference documentation and javadoc of [DataAccessException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/DataAccessException.html) that works for SQL and NoSQL branches? Of course, this class is mostly known as defacto about the SQL world. But currently in the javadoc does not appear the SQL nor NoSQL terms.

Thanks for your understanding

**Comment by snicoll** [comment]
The javadoc of `DataAccessException` is fine as it is IMO. As you've noted yourself, it doesn't try to get into the details of what technology is being used behind the scenes. It uses JDBC as an example, and that's what we should stick to as there's nothing in that infrastructure that should tie it to SQL or NoSQL. Only the actual implementation does.
