### ISSUE TITLE
`path()` in `UriComponentBuilder` should be `@Nullable`

### ISSUE THREAD

**Issue by radSoftPer** [spring-projects/spring-framework#30594]
I think path() should be nullable in case you have a param that shouldn't always appear depending on the environment.   in my case, I have an ingress prefix when I'm sending a request from my PC to a remote service but when it's in production, I don't need it and I would send the request directly since both services would be running in the same k8s cluster.

**Comment by sdeleuze** [comment]
Even if the implementation of `UriComponentsBuilder#path` could take a null parameter, I tend to think that's on purpose we require a non null value here, in order to ensure that when this is invoked, the path is set. Also this is consistent with other methods of the same familly (`fromPath`, `fromUri`, `uri` and `UriBuilder#path`).

Are you ok with this line of reasoning @rstoyanchev @bclozel?

**Comment by sdeleuze** [comment]
@radSoftPer Could you please share a code sample of your use case to allow us to understand it correctly?

**Comment by radSoftPer** [comment]
the names are changed a bit but the part where ` .path("/{servicePrefix}")`  is the issue, when in production I don't need it but when I'm running it from IntelliJ i do.

```
        String urlTemplate = UriComponentsBuilder.newInstance()
                .scheme("http")
                .host(vmVip)
                .path("/{servicePrefix}")
                .path("/isReady")
                .buildAndExpand(servicePrefix)
                .toUriString();
```
production(inside k8s cluster i use the service endpoint so i dont need to use a prefix):

http://serviceName-srv/isReady

development (need a prefix because i'm going through the ingress):

http://vmVip/servicePrefixName/isReady

**Comment by bclozel** [comment]
I'm not sure I understand. In this case `.path("/{servicePrefix}")` expands to `"/"` (or an empty path) but not to `null`. Why should we make this method argument `@Nullable` then?

**Comment by sdeleuze** [comment]
Yeah and for this use case, I would recommend to just use a `UriComponentsBuilder` variable with a `if` block that set conditionnaly the service prefix or something approaching. So I don't see a need here to make the paramater nullable.

**Comment by rstoyanchev** [comment]
Given that `path(String)`, unlike `pathSegment(String)`, appends the value as-is without inserting any slashes, you can insert the complete path prefix conditionally:

```java
String servicePrefix = ... ; // Either "/servicePrefixName" or "" (empty String)

String urlTemplate = UriComponentsBuilder.newInstance()
		.scheme("http")
		.host(vmVip)
		.path("{servicePrefix}")
		.pathSegment("isReady")
		.buildAndExpand(servicePrefix)
		.toUriString();
```

**Comment by rstoyanchev** [comment]
@radSoftPer, yes please check the Javadoc of [path(String)](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html#path(java.lang.String)). It inserts into the path as-is, so you have full control there.

**Comment by radSoftPer** [comment]
awesome.
