### ISSUE TITLE
Remove additional APIs deprecated for removal in 6.1

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30604]
## Overview

This is a follow up to gh-29449.

## Candidates

- [x] `org.springframework.scheduling.support.CronSequenceGenerator`
- [x] `org.springframework.http.codec.multipart.DefaultPartHttpMessageReader.setStreaming(boolean)`
- [x] `org.springframework.http.server.reactive.AbstractServerHttpRequest`
- [ ] `org.springframework.web.filter.reactive.ServerWebExchangeContextFilter.get(Context)`
- [ ] `org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleBindException(BindException, HttpHeaders, HttpStatusCode, WebRequest)`
- [ ] `org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver.handleBindException(BindException, HttpServletRequest, HttpServletResponse, Object)`
- [ ] `org.springframework.web.reactive.HandlerResult`
- [ ] `org.springframework.web.reactive.socket.client.JettyWebSocketClient`
- [ ] `org.springframework.web.socket.client.jetty.JettyWebSocketClient`

## For Removal in 6.2

See  #30608

- [ ] ~`org.springframework.util.Base64Utils`~ was only marked for removal in a 6.0.x maintenance release, to be removed in 6.2.
- [ ] ~`org.springframework.http.client.AbstractClientHttpResponse`~ was only marked for removal in 6.1, though deprecated in 6.0.
- [ ] ~`org.springframework.http.client.ClientHttpResponse.getRawStatusCode()`~ was only marked for removal in 6.1, though deprecated in 6.0.
- [ ] ~`org.springframework.http.client.observation.ClientHttpObservationDocumentation.HighCardinalityKeyNames.CLIENT_NAME`~ was only marked for removal in a 6.0.x maintenance release, to be removed in 6.2
- [ ] ~`org.springframework.web.reactive.function.client.ClientHttpObservationDocumentation.HighCardinalityKeyNames.CLIENT_NAME`~ was only marked for removal in a 6.0.x maintenance release, to be removed in 6.2

**Comment by poutsma** [comment]
I have removed the APIs that I marked for removal. 

Note that `AbstractClientHttpResponse` and `ClientHttpResponse.getRawStatusCode()` were only marked for removal in 6.1—though deprecated in 6.0, so I think we should wait with removing those until 6.2.

**Comment by sbrannen** [comment]
@rstoyanchev, it appears that the remaining items fall under your area of expertise, so I've assigned this issue to you.

**Comment by rstoyanchev** [comment]
The remaining ones are relatively recent deprecations, 6.0.6 for `ServerWebExchangeContextFilter`, 6.0.7 for `ResponseEntityExceptionHandler` and `DefaultHandlerExceptionResolver`, and 6.0 for `HandlerResult` and the `JettyWebSocketClient` implementations. I think they can wait until 6.2.

**Comment by hantsy** [comment]
What is the replacement of CronSequenceGenerator?

**Comment by poutsma** [comment]
> What is the replacement of CronSequenceGenerator?

It says so right in the [Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html)

**Comment by hantsy** [comment]
> > What is the replacement of CronSequenceGenerator?
> 
> It says so right in the [Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html)

Thanks, update [my sample](https://github.com/hantsy/spring6-sandbox/blob/master/schedule/pom.xml#L27) and found it is missing in the imports.
