### ISSUE TITLE
org.hibernate.criterion.Criterion ClassNotFoundException in migrating to Hibernate 6.x with spring-orm 6.0.0

### ISSUE THREAD

**Issue by mhl20201031** [spring-projects/spring-framework#30607]
https://discourse.hibernate.org/t/org-hibernate-criterion-criterion-classnotfoundexception-in-migrating-to-hibernate-6-1-6-with-spring-orm-6-0-0/7300

**Comment by bclozel** [comment]
Duplicates #30439

**Comment by mhl20201031** [comment]
Thank you very much for the quick response, really appreciate it.
I read below comments in #30439:"The preferred solutions are described in the Javadoc of this class. Those warnings applied to the Hibernate 5.x generation and applications are expected to not use this class with Hibernate 6.x."
However my application doesn't used HibernateTemplate. I looked at HibernateDaoSupport class, and it has:
public final void setSessionFactory(SessionFactory sessionFactory)Set the Hibernate SessionFactory to be used by this DAO. Will automatically create a HibernateTemplate for the given SessionFactory.   
   - See Also:
      -       
      - createHibernateTemplate(org.hibernate.SessionFactory)
      - setHibernateTemplate(org.springframework.orm.hibernate5.HibernateTemplate)


The HibernateTemplate is created automatically. 

Do you have any suggestions?
Thanks

    On Wednesday, June 7, 2023 at 01:59:48 AM EDT, Brian Clozel ***@***.***> wrote:  
 
 


Duplicates #30439

**Comment by bclozel** [comment]
Same reasoning applies to `HibernateDaoSupport` - all classes in the `hibernate5` package are not meant to be used with hibernate 6.x.

**Comment by mhl20201031** [comment]
Thank you very much for the information!

    On Wednesday, June 7, 2023 at 09:34:12 AM EDT, Brian Clozel ***@***.***> wrote:  
 
 


Same reasoning applies to HibernateDaoSupport - all classes in the hibernate5 package are not meant to be used with hibernate 6.x.
