### ISSUE TITLE
Document `@DirtiesContext` semantics when declared at the class level and method level

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#30623]
About the current javadoc for the [DirtiesContext](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/annotation/DirtiesContext.html) annotation there is no an indication about what happens if the annotation is annotated twice, it in a _class_ level and _method_ level. 

So would be nice indicate if exists an overriding of the method over the class or a simply a merge of both.

Thanks for your understanding.

**Comment by sbrannen** [comment]
This has been addressed in `6.0.x` and `main.

**Comment by manueljordan** [comment]
As usual, thanks for your polite support.
