### ISSUE TITLE
Document if `@Sql` `scripts` and `statements` attributes can be used together at the same time

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-framework#30639]
About the current javadoc for the [Sql](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/jdbc/Sql.html) annotation there is no an _explicit_ indication if the  `scripts` and `statements` attributes/elements can be used together or not at the same time

Thanks for your understanding.

**Comment by sbrannen** [comment]
The Javadoc for `scripts` states:

> this attribute may be used in conjunction with or instead of `statements()`.

And the Javadoc for `statements` states:

> This attribute may be used in conjunction with or instead of `scripts()`.  

The Javadoc for `statements` goes on to say:

> Statements declared via this attribute will be executed after statements loaded from resource `scripts()`. If you wish to have inlined statements executed before scripts, simply declare multiple instances of `@Sql` on the same class or method.

I don't see how it can be any more explicit.

In light of that, I am closing this issue.

**Comment by manueljordan** [comment]
Oh ... I was so tired that I didn't read that. Sorry.
