### ISSUE TITLE
Support lenient parsing for dates using AM/PM in conjunction with `@DateTimeFormat`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30649]
## Overview

This is a follow-up to #30185 and #33151.

When applications run on JDK 23+, Spring Framework should support lenient parsing for date/time formats that include the time `period` (AM or PM) -- for example, by matching leniently against a _narrow non-breaking space_ (NNBSP) or a standard space between the hour and AM/PM declaration.

## Related Resources

- https://jdk.java.net/20/release-notes#JDK-8284840
- https://unicode-org.atlassian.net/browse/CLDR-14032
- https://bugs.openjdk.org/browse/JDK-8223587
- https://bugs.openjdk.org/browse/JDK-8284840
- https://bugs.openjdk.org/browse/JDK-8297316
- https://bugs.openjdk.org/browse/JDK-8304925
- https://bugs.openjdk.org/browse/JDK-8324665

## Related Issues

- #30185
- #33144
- #33151

**Comment by sormuras** [comment]
"Loose matching of space separators in the lenient date/time parsing mode" has been integrated into Java 23-ea+9:

- https://github.com/openjdk/jdk/commit/96eb0390d69ed2e0c3e59f77fb65fbb79615a11c

See [JDK-8324665](https://bugs.openjdk.org/browse/JDK-8324665) for more details.

**Comment by snicoll** [comment]
We should move this to `6.1.x` otherwise we can't build against Java 23. It's unfortunate we've been hiding this problem for so long.

**Comment by snicoll** [comment]
I've moved this issue to a task as I am not sure I understand how that is an enhancement if it only impacts our own tests.

**Comment by sbrannen** [comment]
After experimenting with the available options in this [feature branch](https://github.com/spring-projects/spring-framework/compare/main...sbrannen:spring-framework:issues/gh-30649-DateTimeFormat-lenient-parsing), we decided not to provide built-in support for lenient parsing of date/time formats in conjunction with `@DateTimeFormat`.

Instead, we will document the options that Spring users have, and I am therefore closing this as superseded by:

- #33151
