### ISSUE TITLE
Support handling of MethodValidationException

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#30644]
The new `MethodValidationException` introduced as part of #29825 as a subclass of `ConstraintViolationException` needs to have default web handling added. That includes RFC 7807 support, similar to the handling of `BindException` but reflecting errors for multiple method parameters / or return value, represented with `ParameterValidationResult` and `ParameterErrors`.

**Comment by rstoyanchev** [comment]
There is now a new `HandlerMethodValidationException`, similar to the `MethodValidationException` raised when method validation is applied via AOP (to any Spring component), but extending from `ResponseStatusException` and thrown from the built-in method validation support for `@RequestMapping` methods. 

The new exception is handled in `ResponseEntityExceptionHandler` and in `DefaultHandlerExceptionResolver`
as e 400 error if is for method arguments, and as a 500 error if it is for a return value. `MethodValidationException` (possibly from an underlying service) is handled as a 500 error.

**Comment by ctapobep** [comment]
From the documentation it's not clear - does this mean that the old `MethodArgumentNotValidException` isn't going to be used by Spring MVC anymore? We should always expect `HandlerMethodValidationException` on the API level from now on?
