### ISSUE TITLE
Cron expression scheduling might be triggered 1 millisecond earlier

### ISSUE THREAD

**Issue by yfei-z** [spring-projects/spring-framework#30666]
**Affects:** 6.0.8

---
The issue just like the title described, after I look into the code, I found the calculation of the delay time in [ReschedulingRunnable](https://github.com/spring-projects/spring-framework/blob/v6.0.8/spring-context/src/main/java/org/springframework/scheduling/concurrent/ReschedulingRunnable.java) might cause the issue.
```
Duration initialDelay = Duration.between(this.triggerContext.getClock().instant(), this.scheduledExecutionTime);
this.currentFuture = this.executor.schedule(this, initialDelay.toMillis(), TimeUnit.MILLISECONDS);
```
Above calculation of initialDelay keeps the nanosecond part, and truncate them at last in initialDelay.toMillis(). The next execution time of cron expression accurate to seconds, and current time has nanoseconds, that will make the initialDelay.toMillis() 1 millisecond less. If the execution fast enough the current time that is obtained in task will earlier than next execution time of cron expression.

Compare to [5.3.27](https://github.com/spring-projects/spring-framework/blob/v5.3.27/spring-context/src/main/java/org/springframework/scheduling/concurrent/ReschedulingRunnable.java)
```
long initialDelay = this.scheduledExecutionTime.getTime() - this.triggerContext.getClock().millis();
this.currentFuture = this.executor.schedule(this, initialDelay, TimeUnit.MILLISECONDS);
```
The nanoseconds has been truncated before the calculation of duration, that will make sure you can't got a unexpected current time.

**Comment by jhoeller** [comment]
I suppose calling `schedule` with `initialDelay.toNanos()` and `TimeUnit.NANOSECONDS` would fix this. We could do that for all our schedule calls in `ConcurrentTaskScheduler` and `ThreadPoolTaskScheduler` as well.
