### ISSUE TITLE
ClientHttpRequestFactory based on JDK HttpClient

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-framework#30699]
We have a `JdkClientHttpConnector` for use with the reactive `WebClient`, so we should have a JDK HttpClient-based `ClientHttpRequestFactory` as well.

**Comment by vpavic** [comment]
FWIW, a PR was opened for this not so long ago by @mdeinum:

- https://github.com/spring-projects/spring-framework/pull/30478

In any case, nice to see this landing in Spring Framework.

**Comment by poutsma** [comment]
Thanks for pointing that out!

**Comment by poutsma** [comment]
Closing this issue in favor of #30478
