### ISSUE TITLE
@The @RefreshScope annotation marks a Task class with a @Scheduled marked scheduled task method in the Task class. After changing the configuration, the scheduled task method is executed twice each time.

### ISSUE THREAD

**Issue by gwself** [spring-projects/spring-framework#30693]
The @RefreshScope annotation marks a Task class with a @Scheduled marked scheduled task method in the Task class. After changing the configuration, the scheduled task method is executed twice each time.

The Task class is @Autowired to the TaskController. When a method of the TaskController calls a method of the Task class, the scheduled task is executed twice.

**Comment by gwself** [comment]
![image](https://github.com/spring-projects/spring-framework/assets/20888271/69ad74e0-a3e1-44fc-86aa-ab409cc7e2a2)
![image](https://github.com/spring-projects/spring-framework/assets/20888271/ec9f7960-a823-487f-860e-1be1f8d14c86)

**Comment by gwself** [comment]
![image](https://github.com/spring-projects/spring-framework/assets/20888271/7c768f22-3df4-4c08-b33e-8e79b6aadce0)

There are two Task objects

**Comment by quaff** [comment]
`@RefreshScope` is neither part of `spring-framework` nor `spring-boot`, you should report it to the right project.

**Comment by gwself** [comment]
> 
I may have mentioned it in the wrong place, I should have mentioned the spring-cloud-common project

**Comment by gwself** [comment]
![image](https://github.com/spring-projects/spring-framework/assets/20888271/630e415b-b80c-4cb3-a82a-97b34059dd2a)
