### ISSUE TITLE
Improve conversion service infrastructure to be AOT aware

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#30722]
The use of conversion service in a native image requires hints that are not always very predictable. This is particularly the case with `ObjectToObjectConverter` that can default to a constructor that takes a `String` if you're trying to bind a property to an object. 

We've been discovering those and adding hints whenever necessary (for instance #30201). Doing so is brittle and we should try to find a way to allow the conversion service to run in dry mode or something, where the conversion decision can be retained, and the necessary hints inferred automatically.

**Comment by snicoll** [comment]
It's waiting for triage as I have no idea if that's feasible. Wondering if @jhoeller has an opinion about it.

**Comment by jhoeller** [comment]
It might be technically feasible to pre-determine some of this but I'm not sure it is worth the complexity in the conversion infrastructure itself. That aside, even the conversion infrastructure itself does not know which target classes it is going to be called for. From that perspective, we'd have to apply this to a set of pre-selected candidate classes even there.

**Comment by snicoll** [comment]
Alright, that confirms my suspicion. Let's close this.
