### ISSUE TITLE
Change AsciiDoctor command with Antora in contributing.md

### ISSUE THREAD

**Issue by Nheyll** [spring-projects/spring-framework#30735]
AsciiDoctor has been removed in april but the contributing.md still shows it as the command to build documentation. 
https://github.com/spring-projects/spring-framework/blob/main/CONTRIBUTING.md#reference-docs

**Comment by Nheyll** [comment]
I opened a PR for this issue :  #30739

**Comment by bclozel** [comment]
Thanks! Closing in favor of #30739
