### ISSUE TITLE
Searching the 6.0.10 documentation changes the version to 6.0.11-SNAPSHOT

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#30741]
At the time of writing, if I got to https://docs.spring.io/spring-framework/reference/index.html I am shown the documentation for 6.0.10. If I press CMD-K the search dialog is shown and it says "Search in the current documentation 6.0.10". Searching for "RegisterReglectionForBinding" produces three results:

- https://docs.spring.io/spring-framework/reference/6.0-SNAPSHOT/core/aot.html#aot.hints.register-reflection-for-binding
- https://docs.spring.io/spring-framework/reference/6.0-SNAPSHOT/core/aot.html#aot.hints.register-reflection-for-binding
- https://docs.spring.io/spring-framework/reference/6.0-SNAPSHOT/testing/testcontext-framework/aot.html#page-title

All three link to the snapshot documentation not 6.0.10 as the search dialog described.

**Comment by sdeleuze** [comment]
There was a need to run the crawler, it is now planned daily. cc @rstoyanchev @rwinch

**Comment by wilkinsona** [comment]
Thanks, @sdeleuze. That's fixed the version problem. Unfortunately the number has been reduced and a link to the test context framework's AOT docs is now absent. I've opened https://github.com/spring-projects/spring-framework/issues/30797.
