### ISSUE TITLE
Alternative to deprecated toByteBuffer() method to get byteBuffer from a DataBuffer

### ISSUE THREAD

**Issue by guillaume-1** [spring-projects/spring-framework#30765]
Hi,
I use Spring Webflux with Spring Boot 3.1.0.
I use this code snippet to log my request body on each request, but since Spring 6.0 I have no alternative to this deprecated method (toByteBuffer() ). Could you help me please ?

`
try (ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream()) {
                                Channels.newChannel(byteArrayOutputStream).write(dataBuffer.toByteBuffer().asReadOnlyBuffer());
                                String requestBody = IOUtils.toString(byteArrayOutputStream.toByteArray(), "UTF-8");
                                log.trace("Request body = {} ", requestBody);
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
`

**Comment by mdeinum** [comment]
Is there a reason not to use `DataBuffer.toString(StandardCharsets.UTF-8);` instead of what you have now?

**Comment by guillaume-1** [comment]
My bad... absolutely no, I haven't seen this method, it does the job. Thank you !

**Comment by missingfaktor** [comment]
> Is there a reason not to use DataBuffer.toString(StandardCharsets.UTF-8); instead of what you have now?

Thanks, @mdeinum. I was going crazy finding alternatives to the deprecated `DataBuffer#asByteBuffer`. Your comment helped.
