### ISSUE TITLE
@Scheduled suspend fun - support

### ISSUE THREAD

**Issue by denis-dbm** [spring-projects/spring-framework#30770]
Hi all

Is there preview to support Kotlin coroutines (`suspend fun`) annotated with `@Scheduled`? Example:

```
@Scheduled(fixedRate = 60_000)
suspend fun doIt() { }
```

**Comment by bclozel** [comment]
Can you try with the current 6.1.0 snapshots and let us know? This was recently implemented.
See #29924 and https://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/integration/scheduling.html#scheduling-annotation-support-scheduled-reactive

Feel free to create a new issue if the support needs refinements. Please provide a minimal sample app if you do so. Thanks!
