### ISSUE TITLE
Searching for RegisterReflectionForBinding produces an incomplete set of results

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#30797]
At the time of writing, if I search the Framework reference docs for `RegisterReflectionForBinding` a single result is returned:

- https://docs.spring.io/spring-framework/reference/core/aot.html#aot.hints.register-reflection-for-binding

I expected https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/aot.html to be returned as well.

FWIW, [a code search on GitHub](https://github.com/search?q=repo%3Aspring-projects%2Fspring-framework+RegisterReflectionForBinding+path%3Adocs&type=code
) finds both:

https://github.com/spring-projects/spring-framework/blob/72301dc861abadea71eb796a4004e74846ec4c02/framework-docs/modules/ROOT/pages/testing/testcontext-framework/aot.adoc#L37

https://github.com/spring-projects/spring-framework/blob/72301dc861abadea71eb796a4004e74846ec4c02/framework-docs/modules/ROOT/pages/core/aot.adoc#L425

**Comment by rwinch** [comment]
@wilkinsona Thanks for the report. There was an error in the crawler configuration that should now be fixed. Can you please check it? If it looks good, can you please close out? If not, can you describe the problem?

**Comment by wilkinsona** [comment]
Thanks, @rwinch. That's much better now. It's back to the 3 hits that were returned when I raised https://github.com/spring-projects/spring-framework/issues/30741. Looking more closely at those, two of the results are for the same link:

- https://docs.spring.io/spring-framework/reference/core/aot.html#aot.hints.register-reflection-for-binding
- https://docs.spring.io/spring-framework/reference/core/aot.html#aot.hints.register-reflection-for-binding
- https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/aot.html#page-title

Can we use this issue to address that or shall I open a new one?

**Comment by snicoll** [comment]
@rwinch any feedback for Andy here?

**Comment by wilkinsona** [comment]
I think this has been fixed. Only two results are returned and they're for two separate links.
