### ISSUE TITLE
Detect interface parameter annotations also from spring-messaging HandlerMethod

### ISSUE THREAD

**Issue by robert-engel** [spring-projects/spring-framework#30801]
**Affects:** all versions

---
For spring-web support was added which allows controller methods to inherit the annotations on parameters from interfaces. See #15682 and https://github.com/spring-projects/spring-framework/commit/790d515f8c49d9f80f41a2f0ca00535fa930ccc2

For spring-messaging this is not currently possible. It would be very nice if that could be possible there as well.

**Comment by jhoeller** [comment]
Implemented through extracting a common `AnnotatedMethod` base class from both of our `HandlerMethod` variants, managing the entire annotation introspection arrangement including the exposure of interface parameter annotations.

Thanks for raising this! It has been on our wishlist for a while but we never got around to it before.
