### ISSUE TITLE
Error page does not utilize forwarded prefix

### ISSUE THREAD

**Issue by bpfoster** [spring-projects/spring-framework#30828]
Not sure if this belongs in Boot or Framework or somewhere else..

Spring Boot version: 3.0.7

If my Spring Boot application is behind a proxy, and I've configured the X-Forwarded-* headers to be sent, and the Boot application is configured with `server.forward-headers-strategy=FRAMEWORK`, I would expect the `path` attribute in the default error response to reflect the forwarded path prefix, but it does not.

I have an extremely simple reproduction application at https://github.com/bpfoster/spring-boot-error-path-forwarded-prefix

Actuator includes the path prefix as expected:
```
$ curl http://localhost:8081/actuator -H 'X-Forwarded-Prefix: /api' | jq

{
  "_links": {
    "self": {
      "href": "http://localhost:8081/api/actuator",
      "templated": false
    },
    "health": {
      "href": "http://localhost:8081/api/actuator/health",
      "templated": false
    },
    "health-path": {
      "href": "http://localhost:8081/api/actuator/health/{*path}",
      "templated": true
    }
  }
}
```

The error response does not:
```
$ curl http://localhost:8081/foobar -H 'X-Forwarded-Prefix: /api' | jq

{
  "timestamp": "2023-06-22T12:29:30.173+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Foobar",
  "path": "/foobar"
}
```

Note the `href`s in actuator include the X-Forwarded-Prefix value vs the `path` in the error do not.

**Comment by rstoyanchev** [comment]
We could set the `jakarta.servlet.error.request_uri` request attribute, but ideally should also restore it. This could be done from `doFilter`, but I see we sometimes recalculate from within calls to `request.getRequestURI()` in which case there is no good place to set and then restore.

I'm wondering if Boot could rely on `request.getRequestURI()` instead of the attribute?

**Comment by wilkinsona** [comment]
Won't `request.getRequestURI()` return the URI for the forward to the error page? We want to URI for the original request that triggered the error. AFAIK, the `jakarta.servlet.error.request_uri` request attribute is the only way to get that.

**Comment by rstoyanchev** [comment]
Indeed, I'll give it a try.

**Comment by bpfoster** [comment]
Hi @rstoyanchev, sorry for the delayed response.  We've upgraded to framework 6.1.3 and I can confirm that I now see the path prefix in the error path.  Thank you!
