### ISSUE TITLE
Support use of MockRestServiceServer with RestClient

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#30821]
AFAICT `MockRestServiceServer` cannot currently be used with the new `RestClient` interface. Perhaps a `bindTo(RestClient.Builder)` or a way to create a `MockClientHttpRequestFactory` instance could be added.

**Comment by NicoStrecker** [comment]
In my opionion restclient is not fully supported for MockRestServiceServer in Spring-Boot version 3.2.4 . BindTo does not really work when the restclient is already injected.

**Comment by lalib** [comment]
@philwebb Is there any plans to support `RestClient` interface in `MockRestServiceServer` ? such as a `bindTo(RestClient)` ?

**Comment by philwebb** [comment]
@lalib That would probably be a question for @rstoyanchev. I'm not sure such a method can be offered because only the builder has a `ClientHttpRequestFactory` setter.
