### ISSUE TITLE
Setting last-modified to ResponseEntity

### ISSUE THREAD

**Issue by max91** [spring-projects/spring-framework#30827]
Hello, i try to set last-modified header in controller to `ResponseEntity` for get request, but `HttpEntityMethodProcessor` remove this in `isResourceNotModified`. I don't understand this behavior of this method. Can you help with this issue?

**Comment by bclozel** [comment]
This was done in https://github.com/spring-projects/spring-framework/issues/19333

In general if the app uses this class it means that the Etag, last modified etc information is set directly on it to support complex cases.
