### ISSUE TITLE
 Issue with Spring Boot 2.4.0 Actuator Startup Endpoint and spring-core version compatibility

### ISSUE THREAD

**Issue by elvisL** [spring-projects/spring-framework#30840]
Description:
I'm encountering an issue with the Spring Boot 2.4.0 Actuator feature, specifically related to the startup endpoint in combination with the spring-core module.

According to the official documentation, the Actuator in Spring Boot 2.4.0 should support the startup endpoint. However, when using this endpoint, I found that it requires the ApplicationStartup class, which is not available in the spring-core module included with the Spring Boot 2.4.0 starter.

The version of spring-core bundled with Spring Boot 2.4.0 seems to be too low to include the ApplicationStartup class. This causes compatibility issues when trying to use the startup endpoint without explicitly upgrading the spring-core version in the project.

It would be great if the Spring Boot 2.4.0 Actuator dependency could include a compatible version of spring-core that supports the ApplicationStartup class to avoid such compatibility issues.

Steps to reproduce:

Create a new Spring Boot 2.4.0 project using the starter template.
Enable Actuator in the project.
Attempt to use the startup endpoint.
Expected behavior:
The startup endpoint should work without requiring explicit upgrades to the spring-core version.

Actual behavior:
The startup endpoint throws a class not found exception for the ApplicationStartup class.

Environment:

Spring Boot version: 2.4.0
Java version: [your Java jdk8]

**Comment by bclozel** [comment]
This should work as we have integration tests checking this. This is likely to be an issue in your application dependencies.

[Note that Spring Boot 2.4 is out of support](https://spring.io/projects/spring-boot#support). Please upgrade to a supported version before requesting support or creating issues.
