### ISSUE TITLE
Revisit public API for `MBeanExporter`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30874]
## Overview

Inspired by #30846, we should revisit the public API for `MBeanExporter`, potentially deprecating the `AUTODETECT_` constants, etc.

If we deprecate those constants and the corresponding setter methods, we should close #17728.

## Related Issues

- #17728
- #30846

**Comment by jhoeller** [comment]
With `AnnotationMBeanExporter` in the picture, we can definitely deprecate the autowire constants. From an initial pass, nothing else jumps out as equally outdated, so from a backwards compatibility perspective it's probably better to preserve the remaining configuration options as-is.
