### ISSUE TITLE
Plugin version no longer available

### ISSUE THREAD

**Issue by brownp2k** [spring-projects/spring-framework#30875]
**Affects:** v5.3.23

---

Version 0.0.10 (specified in v5.3.23) of the "io.spring.ge.conventions.gradle.plugin" is no longer available via the three listed plugin repositories in settings.gradle.

Is there a plan to bring the missing plugin version back to support building older versions of spring?

I'm aware that v5.3.23 is quite old but we have a requirement to use it.

**Comment by bclozel** [comment]
Spring Framework 5.3.23 has been released almost a year ago and [we fixed several CVEs](https://spring.io/security/) in the meantime in the 5.3.x generation. I would not advise using this version at this point.

We did upgrade to the `0.0.13` version of the plugin in the 5.3.x branch in 33f1c9b6140d6e - this version is available on Maven Central. This is related to the [permission changes on repo.spring.io](https://status.spring.io/incidents/rl38k61jk6hr).
