### ISSUE TITLE
Make `GeneratedClasses#withFeatureNamePrefix(String)` `public`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30897]
## Overview

The `GeneratedClasses#withFeatureNamePrefix(String)` method is currently package-private which prevents code from other packages from being able to create a new `GeneratedClasses` instance with a feature name prefix based on an existing `GeneratedClasses` instance.

## Related Issues

- #30861 
- #30895

**Comment by snicoll** [comment]
Can we please hold? I’d like to avoid exposing too many public APIs there.

**Comment by sbrannen** [comment]
> Can we please hold? I’d like to avoid exposing too many public APIs there.

Oh. I didn't see your comment until I'd completed the work and pushed it. Sorry about that.

Making that method public seemed the easiest way to achieve the goals of #30861.

However, let me see if I can figure out a way to achieve that part of the feature without making `GeneratedClasses#withFeatureNamePrefix(String)` public.

**Comment by sbrannen** [comment]
Reopening to address the need in a different manner.

**Comment by sbrannen** [comment]
Closing as "not planned" due to the change of focus in #30895.
