### ISSUE TITLE
Recent tags missing from public repository

### ISSUE THREAD

**Issue by iay** [spring-projects/spring-framework#30901]
**Affects:** 6.x

---

I know the project has migrated to a new CI and publishing system recently, so I suspect this is a consequence of that.

Recent tags (for 6.0.x, or in my case more interestingly for the 6.1.0-Mx releases) appear to tag commits which are not in the repository. I'm guessing that they are tagged on some related, non-public repository that is visible to CI, but the effect is that it's very hard to understand exactly what's in a release.

For example, navigate to the v6.0.11 tag in the GitHub UI:

<https://github.com/spring-projects/spring-framework/tree/v6.0.11>

What I see is a tree as usual, but with a notification that "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.". Same if I open the commit:

<https://github.com/spring-projects/spring-framework/commit/84045374744aee245d1ed717454cb91e5d1c1ad3>

If I clone the repository, _none_ of the v6 tags are visible.

If I manually navigate to the _parent_ of one of these commits, in the above case commit c873a597c764492b0de917cb2f41adf67b6cfc67, I don't get the warning (i.e., that commit is regarded as part of the repository) and I can `git checkout c873a597c764492b0de917cb2f41adf67b6cfc67` in my clone.

I suggest that it would be useful, and certainly SOP in most projects, for the tagged releases to be available in clones/forks.

**Comment by bclozel** [comment]
Those are git tags, and they're publicly available in this git repository. It's just that we don't attach them to a particular branch. See the [git fetch documentation](https://git-scm.com/docs/git-fetch) and in particular `git fetch --tags`.

**Comment by iay** [comment]
Thanks, I'm not sure how I missed that.It's the not having the tags on commits reachable from branches that confused me, I think.
