### ISSUE TITLE
Deprecate OkHttp3ClientHttpRequestFactory

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-framework#30919]
Aptly named, the `OkHttp3ClientHttpRequestFactory` is based on OkHttp 3. Since the introduction of this type, OkHttp4 has been released, which is binary compatibly with 3, but it does requires Kotlin runtime. OkHttp 5 is currently in the works, and appears not backward compatible.

We should deprecate the `OkHttp3ClientHttpRequestFactory`, because it is unclear what kind of back porting policy has, and because keeping an outdated dependency introduces security risks. Furthermore, the  current and future implementation of OkHttp requires Kotlin at runtime, which makes it less suitable for Java usage.

New request factories have been introduced in 6.1 (see #30564, #30478, #30835), offering a wide choice of alternatives for the `OkHttp3ClientHttpRequestFactory`.

**Comment by swankjesse** [comment]
FYI, OkHttp 5 is strongly backwards-compatible.

**Comment by mpellicer** [comment]
Sorry for asking, what would be a good alternative in the next releases for this Factory and the 4.x series of the OkHttp client?

Thanks
