### ISSUE TITLE
Spring Source code construction , Unable to load Maven meta-data

### ISSUE THREAD

**Issue by jhx1024** [spring-projects/spring-framework#30929]
I encountered an error while building the Spring source code
![1](https://github.com/spring-projects/spring-framework/assets/80658404/6f773d31-e5d0-4327-9e19-6d3c8d2e5ec1)

IntelliJ IDEA version: 2020.1
gradle version:5.6.4
Spring version:5.2.9.BUILD-SNAPSHOT

**Comment by dadadadudu** [comment]
> I encountered an error while building the Spring source code ![1](https://user-images.githubusercontent.com/80658404/255442293-6f773d31-e5d0-4327-9e19-6d3c8d2e5ec1.png)
> 
> IntelliJ IDEA version: 2020.1 gradle version:5.6.4 Spring version:5.2.9.BUILD-SNAPSHOT

jdk version?

**Comment by jhx1024** [comment]
jdk 1.8

**Comment by jhx1024** [comment]
> > I encountered an error while building the Spring source code ![1](https://user-images.githubusercontent.com/80658404/255442293-6f773d31-e5d0-4327-9e19-6d3c8d2e5ec1.png)
> > IntelliJ IDEA version: 2020.1 gradle version:5.6.4 Spring version:5.2.9.BUILD-SNAPSHOT
> 
> jdk version?

jdk 1.8

**Comment by bclozel** [comment]
Can you check that you can access the following URL in your browser?

https://repo.spring.io/artifactory/snapshot/io/projectreactor/reactor-bom/Dysprosium-BUILD-SNAPSHOT/maven-metadata.xml

This could be a temporary failure or a missing proxy configuration in your setup.

**Comment by jhx1024** [comment]
![1](https://github.com/spring-projects/spring-framework/assets/80658404/44f29058-cdaf-4955-abb5-d259e62a36d1)
I can access

> Can you check that you can access the following URL in your browser?
> 
> https://repo.spring.io/artifactory/snapshot/io/projectreactor/reactor-bom/Dysprosium-BUILD-SNAPSHOT/maven-metadata.xml
> 
> This could be a temporary failure or a missing proxy configuration in your setup.

I have access, and I configured the proxy
![1](https://github.com/spring-projects/spring-framework/assets/80658404/24cef245-cbb0-4d1c-b336-6cd7d8fae36a)

**Comment by bclozel** [comment]
So this is probably an issue with your setup. Did you configure your proxy with gradle? https://stackoverflow.com/questions/5991194/gradle-proxy-configuration#22666646

**Comment by jhx1024** [comment]
> So this is probably an issue with your setup. Did you configure your proxy with gradle? https://stackoverflow.com/questions/5991194/gradle-proxy-configuration#22666646

I have tried to set up a proxy in the gradle.properties file, but it doesn't work either with or without a proxy. That's why I've come to you

**Comment by jhx1024** [comment]
> So this is probably an issue with your setup. Did you configure your proxy with gradle? https://stackoverflow.com/questions/5991194/gradle-proxy-configuration#22666646

I found it accessible in the browser
https://repo.spring.io/snapshot/io/projectreactor/reactor-bom/Dysprosium-BUILD-SNAPSHOT/maven-metadata.xml

But access
https://repo.spring.io/libs-spring-framework-build/io/projectreactor/reactor-bom/Dysprosium-BUILD-SNAPSHOT/maven-metadata.xml
Browser response 404
![image](https://github.com/spring-projects/spring-framework/assets/80658404/e3d603b0-40bd-447b-8a72-68343c8a447b)

**Comment by jhx1024** [comment]
> So this is probably an issue with your setup. Did you configure your proxy with gradle? https://stackoverflow.com/questions/5991194/gradle-proxy-configuration#22666646

But he made a new mistake
![image](https://github.com/spring-projects/spring-framework/assets/80658404/5a273dd6-01c7-4050-b008-6fabd163e42c)
