### ISSUE TITLE
application.yaml ignored from fatjar started from command line

### ISSUE THREAD

**Issue by scheruga** [spring-projects/spring-framework#30964]
build by calling
**gradle fatJar**

start with
**java -jar build/libs/demo-0.0.1-SNAPSHOT.jar**

Java version used: 17

the value defined in src\main\resources\application.yml is ignored.

It is used correctly if the application is started by
**gradle bootRun**

[demo.zip](https://github.com/spring-projects/spring-framework/files/12207042/demo.zip)

**Comment by mdeinum** [comment]
You are using Spring Boot for which you should use the Spring Boot plugin to build the executable jar, not your own task. Instead run `./gradlew build` and use the resulting jar. Remove the `fatJar` task.

**Comment by scheruga** [comment]
Thanks for the info.
That way it is working perfectly
