### ISSUE TITLE
Support custom properties file formats in `@TestPropertySource`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30981]
## Overview

In Spring Framework 4.3, we introduced the `PropertySourceFactory` SPI for use with `@PropertySource`. This issue aims to introduce the same support in `@TestPropertySource`.

## Related Issues

- #13603
- #16732
- #30982
- https://github.com/spring-projects/spring-boot/issues/33434

**Comment by snicoll** [comment]
Reopening as the deprecation of `MergedContextConfiguration#getPropertySourceLocations` requires to use MergedContextConfiguration#getPropertySourceDescriptors` which doesn't have any equivalent in `TestPropertySourceUtils`. 

There is a method that could work but it's private at the moment.
