### ISSUE TITLE
`WebClientResponseException.getResponseBodyAsString()` returns an empty `String`

### ISSUE THREAD

**Issue by Gieted** [spring-projects/spring-framework#30986]
**Affects:** 5.3.22

---

```java
webClient
.get()
.uri(orderPreviewFunction(request))
.header(HeaderConstants.Middleware.CALL_ID, callIdProvider.callId())
.header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
.accept(MediaType.APPLICATION_JSON)
.retrieve()
.toEntity(OrderPreviewsListReply.class) // let's say decoding failed, because response didn't match format of this class
.doOnError(WebClientResponseException.class, e -> {
    System.out.println(e.getResponseBodyAsString()); // returns "" (empty String)
});
```

Some people are mentioning that this functionality was broken by [24ebb5e](https://github.com/spring-projects/spring-framework/commit/24ebb5ecd5ebc778426839e757b4665d32f1d28a).

The whole purpose of this exception is to be able to get some information (like response body) in case of response processing failure, so it's makes absolutely no sense that it returns an empty String in this situation.

**Comment by rstoyanchev** [comment]
Have you confirmed a previous version where this worked? Generally, I don't see how it could since the response body can only be read once, and in this scenario it was already partially read before a decoding failure occurred.

**Comment by Gieted** [comment]
I haven't checked that, but It's very likely it was working before the change I've mentioned in my bug report. See [this](https://github.com/spring-projects/spring-framework/issues/27666).

**Comment by Gieted** [comment]
@rstoyanchev What you mean by 
> there is not much we can do

???

Even if it's not a regression problem it still is a bug, because just as I said, it makes absolutely no sense, that you cannot get the response as text in this scenario.

WebClient's internal implementation shouldn't consume the response when decoding fails.

This way, this exception would be actually useful. Right now, the behavior of `.getResponseBodyAsString()` is inconsistent, because it sometimes returns the response and sometimes nothing (depending on what caused the exception).

**Comment by rstoyanchev** [comment]
> WebClient's internal implementation shouldn't consume the response when decoding fails.

I'm not sure I understand what you are suggesting here. Unless the response is consumed, how can we know decoding will fail?

**Comment by Gieted** [comment]
> I'm not sure I understand what you are suggesting here. Unless the response is consumed, how can we know decoding will fail?

You can code it however you want, you can for example save it in some temp buffer and discard it once decoding fully success.

I'm saying that it doesn't make sense to consume response in case of error from an API design perspective.

**Comment by Gieted** [comment]
@rstoyanchev To be honest, it's the first time I've spent my time reporting an issue (which I personally don't even care about) and it was just completely ignored.
I seriously don't have any idea why you're treating contributors like that.

**Comment by rstoyanchev** [comment]
I'm not ignoring. It's just that what you're saying doesn't make sense.

**Comment by Gieted** [comment]
What doesn't make sense?

Our discussion TLDR:
  You should change the implementation, so the response can be read in case of an error.
  But you can read response only once.
  But I'm not reading the response, you're doing it internally inside your code.
  Sorry, there's nothing we can do.
  You can just change your code!

**Comment by rstoyanchev** [comment]
> But I'm not reading the response, you're doing it internally inside your code.

It doesn't matter who is reading the response. It doesn't change the fact you can't know if the response is not well formed and will lead to a parse error, until you actually read the response, and if you can only read it once, there is no way to back out. Technically, the response content could be buffered, allowing multiple reads, but that means using more memory and is not something that would be enabled by default. 

> You can just change your code!

I can't make changes if I don't see what changes can be made.
