### ISSUE TITLE
Fail fast if a `@Bean` method has a void return type

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#31007]
It is currently possible to craft the following faulty configuration:

```
@Configuration
public class FaultyConfiguration {

	@Bean
	public void faultyBean() {
		System.out.println("Hello");
	}

}
```

As a result of processing this configuration class, "Hello" is displayed during the processing phase and a `NullBean` bean is contributed. We should reject this upfront.

**Comment by jamesmoessis** [comment]
Hi @snicoll - In `6.1.0` this is causing a problem for us. I was using void beans to run setup methods, pairing them with the `@Conditional*` annotations. For example, enabling certain reactor hooks, if reactor is on the class path: 

```java
    @Configuration
    @ConditionalOnClass(Mono.class)
    static class ReactiveConfiguration {
        @Bean
        void enableAutomaticContextPropagation() {
            Hooks.enableAutomaticContextPropagation();
        }
    }
```

I couldn't see any other way to do this. Is there an alternative now that 6.1.0 blocks this behaviour?

**Comment by ttddyy** [comment]
@jamesmoessis fyi, see this [ReactorAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/reactor/ReactorAutoConfiguration.java) class in Spring Boot.

**Comment by jamesmoessis** [comment]
Perfect! Thanks @ttddyy

**Comment by snicoll** [comment]
Thanks @ttddyy. @jamesmoessis I don't see really how that change blocks anything considering it was abusing `@Bean` factory method. The [reference guide](https://docs.spring.io/spring-framework/reference/core/beans/factory-nature.html#beans-factory-lifecycle-initializingbean) has a number of alternatives for bean initialization. Remember that a `@Configuration` class is also a bean so it could have implemented `InitializingBean` if `@PostConstruct` does not work for you. However, the constructor-based approach is better as it is invoked early.

**Comment by GeneralNitin** [comment]
> Thanks @ttddyy. @jamesmoessis I don't see really how that change blocks anything considering it was abusing `@Bean` factory method. The [reference guide](https://docs.spring.io/spring-framework/reference/core/beans/factory-nature.html#beans-factory-lifecycle-initializingbean) has a number of alternatives for bean initialization. Remember that a `@Configuration` class is also a bean so it could have implemented `InitializingBean` if `@PostConstruct` does not work for you. However, the constructor-based approach is better as it is invoked early.

Can you please attach an example.
In my case I was doing something like this, and after upgrading to Spring 3.2 now my Tests are failing.
```
    @Bean
    @DependsOn(value = { "clientOverrideConfiguration" })
    public void initAwsCredentials() {
        System.setProperty("aws.region", awsRegion);
    }
```
Can you please give a suggestion on how should I refactor this?

**Comment by jamesmoessis** [comment]
@GeneralNitin 

```java
    @Bean
    @DependsOn(value = { "initSystemProperty" })
    public InitializingBean performAnotherAction() {
        return () -> setSomeValue()
    }
```
