### ISSUE TITLE
Versioned redirect seems to all redirect to "current" version

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#31009]
I am expecting https://docs.spring.io/spring-framework/docs/6.0.x-SNAPSHOT/reference/html to redirect to https://docs.spring.io/spring-framework/reference/6.0-SNAPSHOT/index.html and http://docs.spring.io/spring-framework/docs/6.1.x-SNAPSHOT/reference/html/ to redirect to https://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/index.html 

but they both redirect to https://docs.spring.io/spring-framework/reference/

cc @rwinch

**Comment by pernelkanic** [comment]
Can i work on this issue?

**Comment by snicoll** [comment]
@pernelkanic I am afraid not. We don't know ourselves what we can do about this, I've pinged @rwinch for that reason.

**Comment by rwinch** [comment]
The aliases are now updated, but there are not plans to update them beyond the 6.0.x and 6.1.x generations.

**Comment by snicoll** [comment]
Thanks @rwinch.
