### ISSUE TITLE
Reference guide should have stable URL for each generation

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#31018]
I am trying to adapt the links from the Spring Boot reference guide to the new scheme and I am hitting an issue that I don't find a "stable" url for `6.0.x`

This works: https://docs.spring.io/spring-framework/reference/6.1/
This doesn't (at the moment?): https://docs.spring.io/spring-framework/reference/6.0/

cc @rwinch

**Comment by rwinch** [comment]
Thanks for the ping @snicoll! I've provided a PR with a fix and some other improvements https://github.com/spring-projects/spring-framework/pull/31022

**Comment by snicoll** [comment]
That fixed it, thanks @rwinch!

Superseded by #31022
