### ISSUE TITLE
Add a protected `JdbcClient` field in `AbstractTransactionalJUnit4SpringContextTests`

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-framework#31059]
The class `AbstractTransactionalJUnit4SpringContextTests` contains a protected field `jdbcTemplate` of type `JdbcTemplate`.

This field assists in writing tests which inherit from `AbstractTransactionalJUnit4SpringContextTests`.

I suggest to also add a `jdbcClient` field of type `JdbClient`.

Then we can use this field in our tests.

**Comment by hansdesmet** [comment]
Hi Sam
I can indeed omit AbstractTransactionalJUnit4SpringContextTests from my code and use JdbcTestUtils instead.
But the methods of JdbcTestUtils expect a JdbcTemplate parameter.
I would like my code to use only JdbcClient, not JdbcTemplate.
Regards
Hans

**Comment by sbrannen** [comment]
Thanks for the feedback, @hansdesmet! 👍 

As a result, I've created the following issues.

- #31065
- #31066
