### ISSUE TITLE
Spring Cloud Dependencies 2021.0.8: active profiles on command-line are appended to those in bootstrap.yml

### ISSUE THREAD

**Issue by robsmorenburg** [spring-projects/spring-framework#31064]
**Affects:** \<Spring Framework version>
Spring Boot dependencies 2.7.14
Spring Cloud dependencies 2021.0.8
---

After upgrading from spring-cloud-dependencies 2021.0.7 to 2021.0.8 we notice that the active profiles are no longer as expected.

The bootstrap.yml specifies: dev,local-vault
The command-line specifies: production

In the past our pod would be started with just the production profile.
Since release 2021.0.8 it is started with all 3 profiles.

**Comment by bclozel** [comment]
I think this issue is meant to be created against Spring Cloud Config?
I can't transfer this issue right now, can you [create it in the dedicated project](https://github.com/spring-cloud/spring-cloud-config)? Thanks!

**Comment by robsmorenburg** [comment]
Done so.
