### ISSUE TITLE
Provide mock implementation of `org.springframework.web.servlet.function.ServerRequest`

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-framework#31087]
Testing `org.springframework.web.servlet.function.HandlerFunction` implementations would be easier if `spring-test` would provide a mock implementation of `org.springframework.web.servlet.function.ServerRequest`, analogous to the `org.springframework.mock.web.reactive.function.server.MockServerRequest` (that implements the reactive counterpart `org.springframework.web.reactive.function.server.ServerRequest`).

**Comment by PeguB** [comment]
Hello, I would like to claim this issue.
 I made a PR in advance that includes the required changes.

**Comment by bclozel** [comment]
Superseded by #31257
