### ISSUE TITLE
Allow overriding IgnoreUnresolvableNestedPlaceholders in @Value annotation

### ISSUE THREAD

**Issue by jmarchionatto** [spring-projects/spring-framework#31118]
It would be useful to be able to specify `IgnoreUnresolvableNestedPlaceholders` in the @Value annotation, to cover for cases where the global setup is not good.

**Comment by snicoll** [comment]
Thanks for the suggestion, but `@Value` is meant to be as simple as possible and we should not expose implementation-specific settings there.

**Comment by jmarchionatto** [comment]
HI, stumbled once again needing to skip nested @Value placeholder substitution and noticed that users are resorting to hacks to fulfill the need for some kind of proper substitution config override. See https://github.com/spring-projects/spring-framework/issues/9628 

@snicoll Requesting consideration of a simpler solution, like a `skipNestedSusbtitution` parameter.

Thanks
