### ISSUE TITLE
MultipartParser should respect read position

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#31110]
As a follow-up for #31095, we should explore potentially with @violetagg why Spring multipart tests fail with Reactor Netty 2. Could be due to Netty 5 adding additional EOL characters, see below the typical error we observe:
```
expected: 
  "FormBean[fieldValue,[fileParts:foo.txt,fileParts:logo.png]]"
 but was: 
  "FormBean[fieldValue
  ,[fileParts:foo.txt,fileParts:logo.png]]"
```

**Comment by violetagg** [comment]
I'll check that

**Comment by violetagg** [comment]
@sdeleuze I think that `MultipartParser` should handle the read position. See this change

https://github.com/violetagg/spring-framework/commit/8f9de720535e0b69dd8decc238351f6c5868fb83

**Comment by poutsma** [comment]
In retrospect, it appears that this issue only does not occur in 5.3.x, so the backport issue was closed.
