### ISSUE TITLE
`MBeanExporter` produces "Using deprecated '-debug' fallback for parameter name resolution..." warnings

### ISSUE THREAD

**Issue by Sebottenhof99** [spring-projects/spring-framework#31171]
I have a bean that implements `NotificationPublisherAware` in order to send JMX notifications. 

I put then this bean to `MBeanExporter`'s Bean Map: 

```java
 Map<String, Object> beans = new HashMap<>();
    String key =  someName;
    beans.put(key, jmxNotificationSender);
    exporter.setBeans(beans);
```

In this way created `MBeanExporter` bean then tries to prepare my `jmxNotificationSender`. Among others exporter invokes `createAndConfigureMBean` method, which in turn uses `MBeanInfoAssembler` to scan `jmxNotificationSender` to obtain some information. I could trace down, that `AbstractReflectiveMBeanInfoAssembler` as an implementation is used here. This `AbstractReflectiveMBeanInfoAssembler` invokes `getOperationParameters` method, which actually causes the warning since it discovers method parameters (introspection).

Will this issue somehow be handled in the future? 

Tested with Spring Framework 6.0.9 and Java 17

**Comment by bclozel** [comment]
Have you tried compiling your application with the `-parameters` compiler flag [as suggested in the upgrade notes](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#core-container)?

**Comment by Sebottenhof99** [comment]
Hello=) yes, sure. And it works out. With this solution I just have a feeling, that it is not a proper solution, but a workaround to push the warning away...maybe I am wrong here

**Comment by sbrannen** [comment]
> Hello=) yes, sure. And it works out. 

Thanks for the confirmation.

Closing this issue as a result.

> With this solution I just have a feeling, that it is not a proper solution, but a workaround to push the warning away...maybe I am wrong here

It's not a workaround. It's the appropriate action to take. The `-debug` option is deprecated.

**Comment by Sebottenhof99** [comment]
@sbrannen  got it, thank you!!
