### ISSUE TITLE
Deprecate `JOptCommandLinePropertySource`

### ISSUE THREAD

**Issue by drothmaler** [spring-projects/spring-framework#31207]
**Affects:** 6.x

Unfortunately [JOpt Simple](https://jopt-simple.github.io/jopt-simple/) seems to be dead:

- [Last Release: Jul 13, 2017](https://mvnrepository.com/artifact/net.sf.jopt-simple/jopt-simple/5.0.4)
- [Last Alpha: Sep 11, 2018](https://mvnrepository.com/artifact/net.sf.jopt-simple/jopt-simple/6.0-alpha-3)
- [Last Commit: Aug 4, 2021](https://github.com/jopt-simple/jopt-simple/commits/master)

(IMHO) All this does make it a bad option as a reference implementation for an advanced `CommandLinePropertySource`. It would be better to replace it with something actively maintained library. Some candidates might be: 

- [JCommander](https://jcommander.org/)
- [picocli](https://picocli.info/)
- Maybe [Commons CLI](https://commons.apache.org/proper/commons-cli/) - but they didn't release and new version since 2021... 
- [Airline 2](https://rvesse.github.io/airline/) might also be an option, but seem less common

**Comment by snicoll** [comment]
Thanks for the report. We've decided to deprecate our support for JOpt and do not consider a replacement at this time.
