### ISSUE TITLE
Illegal reflective access in `ContextOverridingClassLoader.isEligibleForOverriding`

### ISSUE THREAD

**Issue by geiliev** [spring-projects/spring-framework#31232]
**Affects:** 6.0.11

---

Related to #22791 
The fix in the related issue doesn't resolve the problem and the application still fails to start.
The problem is that event though the `findLoadedClass` method is inaccessible it is still called in `isEligibleForOverriding` which results in an `IllegalAccessException` and failure to start the application.

**Comment by bclozel** [comment]
Can you share a minimal sample application that reproduces the problem? Thanks!

**Comment by geiliev** [comment]
> Oops, looks like there is a `method = null;` missing there in the `catch` block in case of `makeAccessible` failing. This just missed the 6.0.12 release by a day, so we'll fix it for 6.0.13 where this will be available in snapshot builds soon.
> 
> For the time being, and actually as a general recommendation since it increases the performance of temporary class loading, please set `--add-opens=java.base/java.lang=ALL-UNNAMED` on the command line.

Thank you, I have added `--add-opens=java.base/java.lang=ALL-UNNAMED` anyway and it is working.
Just thought it will be nice to work without it as well.
