### ISSUE TITLE
How about adding more explict writing/reading converter interface?

### ISSUE THREAD

**Issue by lntuition** [spring-projects/spring-framework#31260]
Hello, thanks for supporting spring framework :)

It appears that Spring Framework's converter system currently distinguishes between writing converters and reading converters based on annotations. 

``` java
			Class<?> type = converter.getClass();
			boolean isWriting = type.isAnnotationPresent(WritingConverter.class);
			boolean isReading = type.isAnnotationPresent(ReadingConverter.class);

```

Is there a specific reason for controlling this solely through annotations? If there isn't a particular reason, how do you feel about adding `WritingConverter` and `ReadingConverter` interfaces that extend the Converter interface to define converters more explicitly?

**Comment by rstoyanchev** [comment]
I think this belongs in the issue tracker of [spring-data-commons](https://github.com/spring-projects/spring-data-commons) where those annotations exist.
