### ISSUE TITLE
Support string templates in `JdbcTemplate`

### ISSUE THREAD

**Issue by marschall** [spring-projects/spring-framework#31263]
It would be great if `JdbcOperations` or `JdbcTemplate` could be enhanced to support [String Template](https://openjdk.org/jeps/430).

The easiest way to support this is to provide a `StringTemplate.Processor<PreparedStatementCreator, DataAccessException>` implementation, ideally as a constant somewhere. Something like this can already be achieved today with `PreparedStatementCreatorFactory` but is a bit awkward due to the need to explicitly register `SqlParameter` with type `TYPE_UNKNOWN`.

Example:

```java
@Transactional
@SpringJUnitConfig(H2Configuration.class)
class JdbcTemplateTests {

  private static final StringTemplate.Processor<PreparedStatementCreator, DataAccessException> SQL = new PreparedStatementCreatorTemplateProcessor();

  @Autowired
  private DataSource dataSource;

  private JdbcOperations jdbcTemplate;

  @BeforeEach
  void setUp() {
    this.jdbcTemplate = new JdbcTemplate(this.dataSource);
  }

  @Test
  void query() {
    String name = "ok";
    List<String> names = this.jdbcTemplate.query(SQL."""
            SELECT \{name}
            FROM dual
          """, (rs, i) -> rs.getString(1));
    assertEquals(List.of(name), names);
  }

  static final class PreparedStatementCreatorTemplateProcessor implements StringTemplate.Processor<PreparedStatementCreator, DataAccessException> {

    public PreparedStatementCreator process(StringTemplate st) {
      String sql = String.join("?", st.fragments());
      PreparedStatementCreatorFactory factory = new PreparedStatementCreatorFactory(sql);
      List<Object> parameters = st.values();
      for (Object parameter : parameters) {
        factory.addParameter(new SqlParameter(JdbcUtils.TYPE_UNKNOWN));
      }
      return factory.newPreparedStatementCreator(parameters);
    }
  }

}
```

It's still a bit awkward as only methods accepting `PreparedStatementCreator` would work.

**Comment by simonbasle** [comment]
Thanks for the suggestion @marschall. Given that String Templates are still a _preview_ feature in Java 21 and that Spring 6's baseline is Java 17, it would be a challenge to integrate String Templates into the API directly at this stage.

Do you feel that your proposed `PreparedStatementCreatorTemplateProcessor` is too much boilerplate for your codebase?

Btw, one thing that I think could be improved wrt `TYPE_UNKNOWN` would be using `StatementCreatorUtils` like so:
```java
factory.addParameter(new SqlParameter(StatementCreatorUtils.javaTypeToSqlParameterType(parameter.getClass())));
```

**Comment by marschall** [comment]
> So I'm inclined to close this one for now. Would you be willing to reopen an issue when String Template feature is officially released in Java @marschall ?

Sure

**Comment by simonbasle** [comment]
This will need to be revisited once the String Template feature is GA in Java, at which point there should be a way for Spring to provide supporting methods to reduce the boilerplate in creating a `StringTemplate.Processor` (or even provide such a processor depending on the java baseline at the time).
