### ISSUE TITLE
Improve Documentation Around X-Forwarded- Headers

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#31273]
**Affects:** 6.0.12

---

Spring could improve the documentation (both reference and Javadoc) around `X-Forwarded-*` headers. In particular, the `X-Forwarded-Prefix` header could use some clarifications as demonstrated in https://github.com/spring-projects/spring-framework/issues/31241

I've discussed this with @rstoyanchev and I'm happy to send a PR with my [comment](https://github.com/spring-projects/spring-framework/issues/31241#issuecomment-1724299031) as a starting point for the updated documentation.

**Comment by snicoll** [comment]
Closing in favor of PR #31391
