### ISSUE TITLE
`JdbcClient` does not update `KeyHolder` when using positional parameters

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#31297]
This a follow-up to #31122.

**Comment by sbrannen** [comment]
This has been merged into `main` in 64b4a3cf0df7c4f4082a52553d5a842a42e513f0.

This will be available for testing in upcoming 6.1 [snapshots](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Artifacts#snapshots).

----

As can be seen in the aforementioned commit, there are now tests in place which verify the expected behavior for generated keys against an embedded H2 database.

@hansdesmet, it would be great if you can try out 6.1 snapshots against MySQL and any other databases you're using.

Thanks!

**Comment by hansdesmet** [comment]
I tested with the 6.1 snapshots.
- it works with the H2 database 👍.
- it works with the MySQL database 👍.

**Comment by sbrannen** [comment]
Glad to hear it works for you now, @hansdesmet.

Thanks so much for trying it out with the snapshots and for letting us know. 👍
