### ISSUE TITLE
Clarify documentation on Spring Web MVC pattern comparison

### ISSUE THREAD

**Issue by mrnst** [spring-projects/spring-framework#31294]
**Affects:** 6.0.12

---

The [current documentation on Spring Web MVC pattern comparison](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-pattern-comparison) says:

> Both help to sort patterns with more specific ones on top. A pattern is **less specific** if it has a lower count of URI variables (counted as 1), single wildcards (counted as 1), and double wildcards (counted as 2). Given an equal score, the longer pattern is chosen. Given the same score and length, the pattern with more URI variables than wildcards is chosen.

I would consider a pattern **more** specific (and therefore winning) if it has a lower count of URI variables etc.

**Comment by bclozel** [comment]
Thanks for the heads up @mrnst , this typo has been fixed.
