### ISSUE TITLE
`ConcurrentLruCache` no longer supports capacity = 0

### ISSUE THREAD

**Issue by kcichonczyk** [spring-projects/spring-framework#31317]
ConcurrentLruCache no longer allows for capacity = 0 (previously sizeLimit) breaking backward compatibility. Moreover, according to the javadoc above public constructor, it should be possible to use capacity = 0. Please either change the javadoc or revert behaviour.
https://github.com/spring-projects/spring-framework/blob/af0b39a722ca233bca1dd8e3287eb1bd852f238a/spring-core/src/main/java/org/springframework/util/ConcurrentLruCache.java#L84

**Comment by sbrannen** [comment]
This change was introduced in 6.0 in commit c470262c8ea733fd0846a50232599715ec2d2b83.

Thanks for bringing this to our attention.

**Comment by jhoeller** [comment]
Let's try to fix this in 6.0.13 if possible.

**Comment by kcichonczyk** [comment]
@sbrannen At first I created [this PR](https://github.com/spring-projects/spring-framework/pull/31316), but then realised it's not a typo but also changes around the logic. Sorry for confusion.
