### ISSUE TITLE
Error running spring native executable, error: A component required a bean of type 'com.example.MyInterface' that could not be found.

### ISSUE THREAD

**Issue by KaeYan93** [spring-projects/spring-framework#31310]
The project is built with command `mvnw native:compile -Pnative`. The command builds the executable successfully. However, it fails to start the application. 

The `MyInterface` is configured using a class annotated with `@Configuration`, with method returning `ServiceLocatorFactoryBean`. Here is an example code of the method:

```
@Bean
public ServiceLocatorFactoryBean myInterfaceBean() {
    ServiceLocatorFactoryBean slfb = new ServiceLocatorFactoryBean();
    slfb.setServiceLocatorInterface(MyInterface.class);
    return slfb;
}
```

Does Spring Native supports such bean? If not, what is the alternative? Thanks. 

Another reference to the issue on Stackoverflow that are very similar:
https://stackoverflow.com/questions/75881796/spring-boot-3-service-locator-interface-in-the-servicelocatorfactorybean-could-n

**Comment by snicoll** [comment]
This is documented in the [best practices for AOT](https://docs.spring.io/spring-framework/reference/core/aot.html#aot.bestpractices.bean-type). 

There's nothing we can do based on the construct above as you're not providing the signature of the bean to expose so we can't optimize it at build-time. I am wondering why you'd need to have this flexiblity with javaconfig. Given your `@Bean` method can call any regular code, that looks a bit overkill. Can you share why you're using such construct?

**Comment by KaeYan93** [comment]
Hi @snicoll , for my usecase, i am using `ServiceLocatorFactoryBean` with the ServiceFactory interface, which contains methods to get service (interface) based on name. Then, we have classes that implements the service interface with the name after the `@Component` argument, so that the Spring framework returns the correct service impl based on name, when the method is called. This is done because we have multiple type of services, and each service has different impl based on different protocol. 

So, if i using spring native, i cannot leverage this feature anymore?
