### ISSUE TITLE
Breaking change from 6.0.11 to 6.0.12 if you expect query parameters in `@RequestBody`

### ISSUE THREAD

**Issue by anderius** [spring-projects/spring-framework#31327]
I discovered a breaking change between Spring Boot  3.1.3 and 3.1.4. It only affects users that are doing something wrong (imho), but as I discovered it in a test, maybe others have done the same mistake.

I have replicated it here: https://github.com/anderius/spring-requestbody-demo

The tests passes with Spring Boot 3.1.3, but [change that to 3.1.4](https://github.com/anderius/spring-requestbody-demo/blob/master/build.gradle#L4), and the test fails.

It seems query parameters was previously put into a parameter annotated with `@RequestBody`, but that changed in 3.1.4. The new behavior is the correct one, I believe.

Relevant code snippets:

```java
@PostMapping(value = "/example", consumes = "application/x-www-form-urlencoded", produces = "text/plain")
public String take(@RequestBody String request) {
    return request;
}
```

```java
@Test
void queryParameterIsRequestBody(@Autowired TestRestTemplate restTemplate) {

HttpHeaders headers = new HttpHeaders();
headers.add("Content-Type", "application/x-www-form-urlencoded");

// Yes, I know this is not the way...
ResponseEntity<String> response = restTemplate.postForEntity("/example?query=123", new HttpEntity<Void>(headers), String.class);
assertThat(response.getBody()).isEqualTo("query=123");
}
```

**Comment by anderius** [comment]
I just had a test that did something wrong, and I have fixed that.

My purpose with this issue was just to raise the awareness of this changed behavior, as it COULD be a breaking change for someone else. For me it would be no problem if you closed this, because the breaking change was only if developers did something really wrong in the first place. :-)

**Comment by rstoyanchev** [comment]
We've decided to undo the optimization from #30942 for 6.0.13, while for 6.1 we'll avoid reconstructing the body from request parameters, if the query string is not null.

**Comment by membersound** [comment]
This also broke my application, and I had to switch from `@RequestBody` to `@RequestParam` for the `@PostRequest`
