### ISSUE TITLE
Spring Framework 6.1.x:

### ISSUE THREAD

**Issue by KatakamChandraManohar** [spring-projects/spring-framework#31344]
How to download Spring Framework 6.1 I am using windows

---

**Comment by KatakamChandraManohar** [comment]
I could install springboot not Spring Framework 6.1 I am using windows

**Comment by bclozel** [comment]
Spring Framework 6.1 has not been released yet. You can try its milestone versions by selecting Spring Boot 3.2 milestones on start.spring.io.
Also see https://spring.io/quickstart for an example.

**Comment by KatakamChandraManohar** [comment]
can I download the available version
Spring Framework 5.0.7  it tells don't have permission
How to download
i used this url
https://repo.spring.io/release/org/springframework/spring/
It went to JFrog and tells permission denied
Can you plase help

Thanks
Manohar

**Comment by sbrannen** [comment]
> can I download the available version

How to access binaries is documented [here](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Artifacts).
