### ISSUE TITLE
Prepare AOT resource hints for GraalVM changes

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#31340]
According to https://github.com/oracle/graal/issues/7354#issuecomment-1708924781 and other comments, we need to prepare for future changes in the `resource-config.json` format and apply them to our `ResourceHints` API.

First, the "exclude pattern" variant is going away as it breaks composeability of configs.

Also, the patterns themselves are going to be greatly simplified and won't support regexp patterns anymore. Currently our support outputs entries like

```json
      {
        "pattern": "\\Qbanner.txt\\E"
      },
```

In the future, only "glob patterns" will be allowed, like `"banner.txt"`, `"images/*.jpg"` or `"images/**"`.

**Comment by sbrannen** [comment]
- related to #31162
