### ISSUE TITLE
Spring Native Image Build Takes > 9GB memory

### ISSUE THREAD

**Issue by KaeYan93** [spring-projects/spring-framework#31356]
Hi,

Currently, when I build exe in the docker image, it takes > 9GB memory and it causes the error that the build is not successful because it has not enough memory to allocate.

Graal docker base image: ghcr.io/graalvm/graalvm-ce:22.3.1

**I have a few questions:**
1. Why it takes such lot of memory, especially during Stage 1 Initialization stage, what does it really do?
2. Can i limit the memory usage when building? Understanding that it might affect build performance/time

**Comment by bclozel** [comment]
Hello @KaeYan93 

This is really a GraalVM question. The latest versions [did improve in that space](https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5#3e1d) so I'm not sure what's going on. You can join the [GraalVM community support](https://www.graalvm.org/community/) and discuss this case.
