### ISSUE TITLE
Proposal: VirtualThreadPoolTaskExecutor

### ISSUE THREAD

**Issue by ilgrosso** [spring-projects/spring-framework#31421]
**Affects:** 6.1.0-M5

Similar to [ThreadPoolTaskExecutor](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.java) but for Virtual Threads.

I have assembled a quick prototype internally delegating to [SimpleAsyncTaskExecutor](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/task/SimpleAsyncTaskExecutor.java), available at https://github.com/apache/syncope/blob/13e5538116369da9ca3ef55ff5f93fb004a93847/core/spring/src/main/java/org/apache/syncope/core/spring/task/VirtualThreadPoolTaskExecutor.java

**Comment by bclozel** [comment]
I'm not sure I understand. Can you elaborate what's the goal of this contract, especially what's missing from the `SimpleAsyncTaskExecutor` and how the proposed implementation fills that void?

Virtual Threads are not supposed to be pooled, so the name itself is quite problematic.

**Comment by ilgrosso** [comment]
> Can you elaborate what's the goal of this contract?

Sorry, I could have explained that before.
The purpose is to provide an almost drop-in replacement for existing code using `ThreadPoolTaskExecutor`.

**Comment by ilgrosso** [comment]
Thank you for feedback.
