### ISSUE TITLE
Kotlin BeanFactory.getBean extension fails with nested generic in context

### ISSUE THREAD

**Issue by ianbrandt** [spring-projects/spring-framework#31439]
With 6.1.0-RC1 (and likely prior), the following test of the [`BeanFactory.getBean`](https://docs.spring.io/spring-framework/docs/6.0.13/kdoc-api/spring-beans/org.springframework.beans.factory/get-bean.html) extension fails, presumably due to erasure:

```kotlin
@SpringBootTest
internal class SpringGetBeanNestedGenericIT {

	@Configuration
	class TestConfig {

		@Bean
		fun listOfString(): List<String> =
			listOf("Testing")

		@Bean
		fun listOfListOfString(): List<List<String>> =
			listOf(listOf("Testing"))
	}

	@Test
	fun `test getBean with nested generic`(
		applicationContext: ApplicationContext
	) {
		assertThatNoException().isThrownBy {

			applicationContext.getBean<List<String>>()
		}
	}
}
```

Error message showing the `listOfString` and `listOfListOfString` beans being seen as the same type after erasure:

```text
java.lang.AssertionError: 
Expecting code not to raise a throwable but caught
  "org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'java.util.List' available: expected single matching bean but found 2: listOfString,listOfListOfString
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1310)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:484)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1192)
	at org.sdkotlin.springdemo.SpringGetBeanNestedGenericIT.test_getBean_with_nested_generic$lambda$0(SpringGetBeanNestedGenericIT.kt:37)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.NotThrownAssert.isThrownBy(NotThrownAssert.java:43)
	at org.sdkotlin.springdemo.SpringGetBeanNestedGenericIT.test getBean with nested generic(SpringGetBeanNestedGenericIT.kt:30)
```

If I remove the `listOfListOfString` bean from the configuration, the test passes.

I can inject both beans just fine, i.e. the following passes:

```kotlin
@Test
fun `test listOfString is injected`(
	@Autowired
	listOfString: List<String>
) {
	assertThat(listOfString).isEqualTo(LIST_OF_STRING)
}

@Test
fun `test listOfListOfString is injected`(
	@Autowired
	listOfListOfString: List<List<String>>
) {
	assertThat(listOfListOfString).isEqualTo(LIST_OF_LIST_OF_STRING)
}
```

I notice the [`BeanFactory.getBeanProvider`](https://docs.spring.io/spring-framework/docs/6.0.13/kdoc-api/spring-beans/org.springframework.beans.factory/get-bean-provider.html) extension uses the [_super type token_](https://gafter.blogspot.com/2006/12/super-type-tokens.html) approach. Perhaps this could be used as well for `getBean` to address this issue:

```kotlin
inline fun <reified T : Any> BeanFactory.getBean(): T =
	getBeanProvider<T>(ResolvableType.forType((object : ParameterizedTypeReference<T>() {}).type)).`object`
```

If I import that version of the extension instead, the test passes with the `listOfListOfString` bean in the configuration.

**Comment by ianbrandt** [comment]
Added #31444 to request `ParameterizedTypeReference` overloads to the Java `BeanFactory.getBean` methods, which would presumably streamline the implementation of the Kotlin extensions.

**Comment by sdeleuze** [comment]
You can get the behavior you want with `applicationContext.getBeanProvider<List<String>>().getObject()` since we are leveraging the underlying `ResolvableType` based capabilities. That said, we could maybe potentially leverage that instead of `getBean(T::class.java)` for the implementation of the `inline fun <reified T : Any> BeanFactory.getBean(): T` Kotlin extension. I will give it more thoughts and let you know.

**Comment by ianbrandt** [comment]
Thanks for the fix, @sdeleuze!
