### ISSUE TITLE
Can't link to Spring Framework 6.1.0 release candidate documentation

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-framework#31480]
In the version dropdown on https://docs.spring.io/spring-framework/reference/6.1/index.html, there's 6.1.0-SNAPSHOT and 6.1.0-RC1. Both link to https://docs.spring.io/spring-framework/reference/6.1/index.html, which seems to be the Snapshot documentation.

**Comment by mhalbritter** [comment]
I'm also wondering why there's a `6.0-SNAPSHOT` url but no `6.1-SNAPSHOT` url.

**Comment by sdeleuze** [comment]
I think this is a change done on purpose with the new Antora based website for SEO purpose.

**Comment by sdeleuze** [comment]
@rwinch Could you please let us know if that's expected or not?

**Comment by rwinch** [comment]
@sdeleuze It is not expected Please see https://github.com/spring-projects/spring-framework/pull/31502
