### ISSUE TITLE
Remove deprecated API from WebContentGenerator

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#31492]
Some API in `WebContentGenerator` was deprecated back in 4.2 and we should remove this support now. HTTP 1.0 is not supported anymore, the `CacheControl` configuration variant is much superior and the HTTP caching defaults are more in line with best practices.

**Comment by prakhar2451** [comment]
I've come across some deprecated APIs in the codebase in context of this issue. I wanted to seek your guidance on how you would like contributions related to these deprecated APIs to be handled. Specifically, I'm wondering if the intention is to simply remove the deprecated APIs, or if there is a preference to migrate to the CacheControl configuration.

**Comment by bclozel** [comment]
@prakhar2451 thanks for the proposal, but the changes are all ready here: https://github.com/bclozel/spring-framework/tree/gh-31492
