### ISSUE TITLE
Support `ContextLoader` config in `@SpringJUnitConfig` and `@SpringJUnitWebConfig`

### ISSUE THREAD

**Issue by neckbosov** [spring-projects/spring-framework#31498]
**Affects:** 5.3.26

`@SpringJUnitConfig` and `@SpringJUnitWebConfig` alias all attributes of `@ContextConfiguration` except `loader` for some reason, which forces one to replace them with 

```java
@ExtendWith(SpringExtension.class)
@WebAppConfiguration
@ContextConfiguration(loader = ...)
```

I think it would be great to add a `loader` attribute to these annotations to make them fully compatible with `@ContextConfiguration`.

**Comment by sbrannen** [comment]
> `@SpringJUnitConfig` and `@SpringJUnitWebConfig` wrap all parameters of `@ContextConfiguration` except `loader` for some reason

I believe that was merely an oversight on my part.

Thanks for bringing this to our attention! 👍

**Comment by sbrannen** [comment]
Since there are viable workarounds for Spring Framework 5.3.x and 6.0.x, I've incorporated these changes for the upcoming Spring Framework 6.1 RC2 in commit 6c4cbd2aab6a49cbd36438007ca296006e305a3a.
