### ISSUE TITLE
The following method did not exist: 'void org.springframework.orm.hibernate5.LocalSessionFactoryBuilder.addAttributeConverter(java.lang.Class)'

### ISSUE THREAD

**Issue by BornToCode1123** [spring-projects/spring-framework#31515]
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.orm.hibernate5.LocalSessionFactoryBuilder.scanPackages(LocalSessionFactoryBuilder.java:350)

The following method did not exist:

    'void org.springframework.orm.hibernate5.LocalSessionFactoryBuilder.addAttributeConverter(java.lang.Class)'

The calling method's class, org.springframework.orm.hibernate5.LocalSessionFactoryBuilder, was loaded from the following location:

    jar:file:/C:/Users/sreekanth.bathini.JOCATA/.m2/repository/org/springframework/spring-orm/6.0.11/spring-orm-6.0.11.jar!/org/springframework/orm/hibernate5/LocalSessionFactoryBuilder.class

The called method's class, org.springframework.orm.hibernate5.LocalSessionFactoryBuilder, is available from the following locations:

    jar:file:/C:/Users/sreekanth.bathini.JOCATA/.m2/repository/org/springframework/spring-orm/6.0.11/spring-orm-6.0.11.jar!/org/springframework/orm/hibernate5/LocalSessionFactoryBuilder.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.orm.hibernate5.LocalSessionFactoryBuilder: file:/C:/Users/sreekanth.bathini.JOCATA/.m2/repository/org/springframework/spring-orm/6.0.11/spring-orm-6.0.11.jar
    org.hibernate.cfg.Configuration: file:/C:/Users/sreekanth.bathini.JOCATA/.m2/repository/org/hibernate/orm/hibernate-core/6.2.7.Final/hibernate-core-6.2.7.Final.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.orm.hibernate5.LocalSessionFactoryBuilder

Process finished with exit code 1

Please use the blow code to replicate the issue.
https://github.com/BornToCode1123/HibernateIssue

**Comment by bclozel** [comment]
The `hibernate5` package is only meant to be used with hibernate 5.x, with a [minimum requirement of Hibernate 5.6 with Spring Framework 6](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#data-access-and-transactions-1). I see you're considering the Hibernate ORM 6.1 upgrade, which is what the team recommends.

See also [this comment](https://github.com/spring-projects/spring-framework/issues/30439#issuecomment-1537365127) explaining why this package shouldn't be used with Hibernate 6.

**Comment by BornToCode1123** [comment]
below core version i am using and spring framework 6.0.11 and SB 3.1.2
<dependency>
		<groupId>org.hibernate.orm</groupId>
		<artifactId>hibernate-core</artifactId>
		<version>6.2.7.Final</version>
	</dependency>

**Comment by bclozel** [comment]
Yes, that's the problem. Your code is still using infrastructure in the `hibernate5` package, it shouldn't.

**Comment by BornToCode1123** [comment]
> Yes, that's the problem. Your code is still using infrastructure in the `hibernate5` package, it shouldn't.

it's spring hibernate5 not hibernate core
