### ISSUE TITLE
The following method did not exist: 'void org.springframework.orm.hibernate5.LocalSessionFactoryBuilder.addAttributeConverter(java.lang.Class)'

### ISSUE THREAD

**Issue by BornToCode1123** [spring-projects/spring-framework#31512]
Description
We are using SB 3.1.2 and the Spring Framework 6.0.11  The following method did not exist: 'void org.springframework.orm.hibernate5.LocalSessionFactoryBuilder.addAttributeConverter(java.lang.Class)'.

When we created a customer converters class , we are adding into hibernate we facing this issue

**Comment by bclozel** [comment]
This method is inherited from `org.hibernate.cfg.Configuration`, so this is probably an issue in your build configuration or a corrupted hibernate JAR. I'm closing this issue as it's not related to Spring.

We can reopen this issue if you provide a minimal sample application (zipped here or that we can git clone) reproducing the problem. You can use httpss://start.spring.io to quickly create one. Thanks!

**Comment by nehachikki1234** [comment]
@BornToCode1123 Hey I am facing a similar issue when trying to upgrade hibernate from 5 to 6.2,Can you please tell me how did you solve this error?
