### ISSUE TITLE
Document that Micrometer's "error" tag should be preferred vs. legacy "exception" tag

### ISSUE THREAD

**Issue by chicobento** [spring-projects/spring-framework#31514]
On Spring Boot 3 besides `exception`, `method`, `outcome`, `status` and `uri`, the `error` tag is also being generated:

`http_server_requests_count{error="none" ... }`

This tag is [not on official docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.spring-mvc) neither [ServerHttpObservationDocumentation](https://github.com/spring-projects/spring-framework/blob/v6.0.2/spring-web/src/main/java/org/springframework/http/server/observation/ServerHttpObservationDocumentation.java) class and overlaps with _exception_ tag. 
Looking at the code it seems that this behavior is added by micrometer's [DefaultMeterObservationHandler](https://github.com/micrometer-metrics/micrometer/blob/22a81f0cf1ac3f21e3b0b1f93a2b8c5c079422e2/micrometer-core/src/main/java/io/micrometer/core/instrument/observation/DefaultMeterObservationHandler.java#L74) which is configured by [ObservationAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/c9c359fd271d1b51bf16f50d685c49fa40ca1b8a/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/observation/ObservationAutoConfiguration.java#L123).

A possible quick-fix would be to override `DefaultMeterObservationHandler#createErrorTags` to return `Tags.empty()`. 

On a side note, an additional undocumented behavior added by DefaultMeterObservationHandler is the `http.server.requests.active` metrics. Should this be documented ?

**Comment by lucasspiller-zero** [comment]
ahh guys it's 2026 and I just ran into this issue

after playing around with the metrics I had to

http.client.requests.active: false

to remove the http.server.requests.active metrics

and also noticed the duplication of exception and error tag. any news on this?
