### ISSUE TITLE
@WebServiceRef not being invoked in migration from Spring 5 to 6

### ISSUE THREAD

**Issue by tomasbjerre** [spring-projects/spring-framework#31524]
**Affects:** \6.0.13

---

I am migrating code from Spring 5 to 6. This code was working in 5 but not in 6.

```java
@Configuration
public class MyBeansProducer
{
   @Bean
   public MyDAO createDAO()
   {
      return new MyDAO();
   }
}
```

```java
public class MyDAO
{
   @WebServiceRef(WSMyInterfaceHttpService.class)
   public void setRef(Ref wsRef )
   {
      this.wsRef = wsRef ;
   }
}
```

Problem is that `setRef` is never invoked.

I have found this code in Spring 5 that used to make this work:
https://github.com/spring-projects/spring-framework/blob/5.3.x/spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java#L406

I'm not sure if this is a bug? If it is not a bug, I think it should be mentioned clearly somewhere in the docs.

I also asked on [StackOverflow](https://stackoverflow.com/questions/76356246/issue-with-webserviceref-not-being-invoked-in-migration-from-springboot-2-to-3)

**Comment by snicoll** [comment]
@tomasbjerre I am afraid this is to be expected. JAX-WS support has been removed in Spring Framework 6, see https://github.com/spring-projects/spring-framework/issues/27422
