### ISSUE TITLE
An attempt was made to call a method that does not exist.

### ISSUE THREAD

**Issue by GrRuan** [spring-projects/spring-framework#31533]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor.<clinit>(PaginationInnerInterceptor.java:70)

The following method did not exist:

    net.sf.jsqlparser.schema.Column.withColumnName(Ljava/lang/String;)Lnet/sf/jsqlparser/schema/Column;

The calling method's class, com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor, was loaded from the following location:

    jar:file:/D:/Guoal/apache-maven-3.6.3/maven_repository/com/baomidou/mybatis-plus-extension/3.5.2/mybatis-plus-extension-3.5.2.jar!/com/baomidou/mybatisplus/extension/plugins/inner/PaginationInnerInterceptor.class

The called method's class, net.sf.jsqlparser.schema.Column, is available from the following locations:

    jar:file:/D:/Guoal/apache-maven-3.6.3/maven_repository/com/github/jsqlparser/jsqlparser/1.2/jsqlparser-1.2.jar!/net/sf/jsqlparser/schema/Column.class

The called method's class hierarchy was loaded from the following locations:

    net.sf.jsqlparser.schema.Column: file:/D:/Guoal/apache-maven-3.6.3/maven_repository/com/github/jsqlparser/jsqlparser/1.2/jsqlparser-1.2.jar
    net.sf.jsqlparser.parser.ASTNodeAccessImpl: file:/D:/Guoal/apache-maven-3.6.3/maven_repository/com/github/jsqlparser/jsqlparser/1.2/jsqlparser-1.2.jar

**Comment by bclozel** [comment]
None of the mentioned classes belong in this project. Please reach out to the relevant projects as there is nothing we can do here.

Thanks
