### ISSUE TITLE
Vulnerability found in latest version of spring framework v5.3.30

### ISSUE THREAD

**Issue by minal107** [spring-projects/spring-framework#31535]
Recently in september the new version for major version 5.3 was released which was v5.3.30 many vulnerabilities were resolved in that version. But still our vercode scan is showing one high flaw in spring-web-5.3.30.

I wanted to raise a query to know that is there any plan to resolve that in near future?
Are we expecting a new version for spring 5.3 with no flaws in that?

**Comment by bclozel** [comment]
Is there a CVE id attached to this vulnerability? Without this information your report is not really actionable.

**Comment by minal107** [comment]
@bclozel  Thanks for commenting on the question. Yes when I searched with CVE id that was attached with this, there are multiple discussions done for this CVE.

I got my answers from those discussions. Closing this issue.

**Comment by bclozel** [comment]
Thanks for letting us know.
