### ISSUE TITLE
Enable `PropertyResolverExtensionsKotlinTests`

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#31553]
`PropertyResolverExtensionsKotlinTests` was disabled via 33fcba55d17ecebf82981049616ccf30f75314e1 due to intermittent build errors. I can't reproduce those errors locally anymore, so let's try to bring those tests back with Kotlin 1.9.20. This will be useful for #31523.

**Comment by vatsasiddhartha** [comment]
hey i want to try for contribution ...

**Comment by sdeleuze** [comment]
Thanks but I have already the commit and the PR locally.
