### ISSUE TITLE
Spring MVC can wrongly return 405 http code when using annotated controllers with other handler mapping methods (router functions for example)

### ISSUE THREAD

**Issue by FBibonne** [spring-projects/spring-framework#31563]
This issue stands for Spring framework 5.3.30 (spring-webmvc artifact) but the code seems to be the same in Spring 6

I use together annotated controllers and functional endpoints to handle http request in spring MVC and it happens that Spring MVC returns an 405 http code (Method Not Allowed) which is not expected.

For example : I declare an @PutMapping method in an annotated controller (class PersonController) to handle `PUT /persons/{id}` and I declare a functional endpoint (configuration class PersonConfig) to handle `GET /persons/{id}`. When I request `GET /persons/{id}`, the application returns a 405 http code (Method Not Allowed) because according to the annotated controller, the pattern /persons/{id} is only processed with PUT. That is not what is expected : when requested with `GET /persons/{id}` the application is expected to process the request with the method `personHandler`.

It happens because the implementation of [`handleNoMatch` in `RequestMappingInfoHandlerMapping`](https://docs.spring.io/spring-framework/docs/5.3.30/javadoc-api/org/springframework/web/servlet/mvc/method/RequestMappingInfoHandlerMapping.html#handleNoMatch(java.util.Set,java.lang.String,jakarta.servlet.http.HttpServletRequest)) seems to break the contract of [AbstractHandlerMethodMapping.lookupHandlerMethod](https://docs.spring.io/spring-framework/docs/5.3.30/javadoc-api/org/springframework/web/servlet/handler/AbstractHandlerMethodMapping.html#lookupHandlerMethod-java.lang.String-javax.servlet.http.HttpServletRequest-) : when a request doen't match, handleNoMatch may raise an exception to explain why it doesn't match and so doesn't return null. Therefore lookupHandlerMethod doesn't return null as expected if no match. Then the DispatcherServlet stops searching in others handlerMapping if there is a match for the request.

In such a case, maybe exceptions like `HttpRequestMethodNotSupportedException` should be treated as null value returns and only raised if no other handlerMapping matches.

**Class PersonConfig**

```java
@Configuration
public class PersonConfig {

    private static final String ID = "1";
    private static final String NAME = "Fabrice";
    private static final Person PERSON=new Person(ID, NAME);

    @Bean
    public RouterFunction<ServerResponse> personsGetters(){
        return route().path("/personsas", mapper->
                mapper.GET("/{id}", this::personHandler)
                        .GET(this::personHandler)).build();
    }

    public ServerResponse personHandler(ServerRequest req){
        if ((req.pathVariables().containsKey("id") && ID.equals(req.pathVariables().get("id")))
                || req.pathVariables().isEmpty()){
            return EntityResponse.fromObject(PERSON).build();
        }else{
            return ServerResponse.notFound().build();
        }

    }

}
```

**Class  PersonController**
```java
@RestController
@RequestMapping("/persons")
public class PersonController {

    @PutMapping("/{id}")
    public Person updatePerson(@RequestBody Person person, @PathVariable("id") String id){
        System.out.println("Update person with id "+id+" with "+person);
        return person;
    }

}
```

**Comment by sdeleuze** [comment]
Can you please test with Spring Boot 3.2.0-RC2 and Spring Framework 6.1.0-RC2 if you still this issue? I suspect https://github.com/spring-projects/spring-framework/issues/30278 could resolve it.

**Comment by FBibonne** [comment]
This issue doesn't happen with Spring Framework 6.1 : the reorder of the registered mappings  solved it

**Comment by sdeleuze** [comment]
Thanks for the quick feedback, I will close this issue since such change would be too breaking for 6.0.
