### ISSUE TITLE
semantics-pointcuts

### ISSUE THREAD

**Issue by Simo12138** [spring-projects/spring-framework#31562]
https://eclipse.dev/aspectj/doc/released/progguide/semantics-pointcuts.html

So
handler(java.util.*Map)
picks out the types java.util.Map and java.util.java.util.HashMap, among others, and

  handler(java.util.*)
picks out all types that start with "java.util." and don't have any more "."s, that is, the types in the java.util package, but not inner types (such as java.util.Map.Entry).

**Comment by Simo12138** [comment]
picks out the types java.util.java.util.HashMap ?

**Comment by bclozel** [comment]
I don't understand why you asked this question here.

I think you'll get better help in the AspectJ community directly. Maybe ask this question on the Eclipse forums or StackOverflow?
