### ISSUE TITLE
PATCH request is forbidden by `RestClient` but allowed by `WebTestClient`

### ISSUE THREAD

**Issue by donalmurtagh** [spring-projects/spring-framework#31590]
**Affects:** spring 6.1.0-RC2 with spring boot 3.2.0-RC2 and JDK21

**Description**
I've attached a sample Spring Boot application with a single endpoint that accepts PATCH requests. When the endpoint is invoked with a PATCH request from a `WebTestClient` it is allowed, but when it is invoked with a PATCH request from a `RestClient`, it fails with the following exception

```
org.springframework.web.client.ResourceAccessException: I/O error on PATCH request for "http://localhost:61668/api/endpoint": Invalid HTTP method: PATCH
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.createResourceAccessException(DefaultRestClient.java:489)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:414)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.retrieve(DefaultRestClient.java:380)
```

In `SecurityConfiguration.java` I've added PATCH to the allowed methods, so I guess `RestClient` is ignoring this configuration.

**Steps to Reproduce**
[demo.zip](https://github.com/spring-projects/spring-framework/files/13319638/demo.zip)

The application contains 2 integration tests, one of which invokes the endpoint with a `RestClient` and the other uses `WebTestClient`. The latter test passes, but the former fails.

**Comment by poutsma** [comment]
Spring Boot's `RestClient` support uses the `SimpleClientHttpRequestFactory` by default, which is based on the dated `java.net.HttpURLConnection`, and does not have support for `PATCH`.

Switching to the more modern Java HttpClient fixes it:

```java
@PostConstruct
private void buildRestClient() {
    restClient = restClientBuilder.baseUrl("http://localhost:" + port)
            .requestFactory(new JdkClientHttpRequestFactory())
            .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
            .build();
}
```

**Comment by andrei-ivanov** [comment]
Wouldn't it make sense to change the default client?

**Comment by donalmurtagh** [comment]
> Spring Boot's `RestClient` support uses the `SimpleClientHttpRequestFactory` by default, which is based on the dated `java.net.HttpURLConnection`, and does not have support for `PATCH`.
> 
> Switching to the more modern Java HttpClient fixes it:

@poutsma Thanks for the reply. Given that `RestClient`[ is brand new](https://spring.io/blog/2023/07/13/new-in-spring-6-1-restclient), shouldn't it use `JdkClientHttpRequestFactory` by default i.e. there doesn't appear to be a backwards compatibility argument for using `HttpURLConnection`

**Comment by poutsma** [comment]
> Wouldn't it make sense to change the default client?

FWIW, `RestClient`'s default request factory—without Boot—is the `JdkClientHttpRequestFactory`.

It is because Boot uses the same `ClientHttpRequestFactorySettings` between `RestTemplate` and `RestClient` that the `SimpleClientHttpRequestFactory` is used, doing otherwise would break backward compatibility because the factories have different behavior with regards to redirects.

There are plans to improve the situation, see https://github.com/spring-projects/spring-boot/issues/36266
