### ISSUE TITLE
`PathResourceResolver.getResource()` does not log warning if `Resource#getURL()` throws exception

### ISSUE THREAD

**Issue by matthiaskraaz** [spring-projects/spring-framework#31623]
If `ServletContextResource.getURL()` throws a `FileNotFoundException` because `ServletContext.getResource(String)` returns `null`, then `org.springframework.web.servlet.resource.PathResourceResolver.getResource(String, Resource)` does not log a warning as intended.

**Comment by sbrannen** [comment]
Hi @matthiaskraaz,

Congratulations on reporting your first issue for the Spring Framework! 👍 

I have a fix prepared locally, and we'll make sure to include it in the next release.
