### ISSUE TITLE
Pagination support in Spring JDBC.

### ISSUE THREAD

**Issue by iamgollapalli** [spring-projects/spring-framework#31620]
**Affects:** \<Spring Framework version>

---

As a **Spring JDBC User**, i want to query the records in **pageable** fashion so that i can effectively work with retrieval queries.

For example: It will be good if the jdcb exposes methods as follows.

Iterator<Page<T>> query(String query, Map<String, ?> params, RowMapper<T> mapper, int recordLimit);

**query**  -- Plain Sql query
**params** -- input params for the given SQL query.
**mapper** -- mapper converting ResultSet to coresponding Object (T)
**recordLimit** -- record limit is max records for each db query.

the Iterator implementation should handle the recursive queries for the next page.

**Comment by snicoll** [comment]
Thanks for the suggestion and, given your "as a Spring JDBC user", I suspect you might be aware of this but advanced queries capabilities like that are provided by the Spring Data JDBC project. I believe that pagination support is also available without their repository support which should be very close to what you're looking for.
