### ISSUE TITLE
Add support for reading classes from JPMS modules

### ISSUE THREAD

**Issue by PavelTurk** [spring-projects/spring-framework#31697]
Consider the following situation. JPMS application with layer tree. In Module X on  Layer C it is necessary to create Spring context while Spring framework is located on   Layer B :

```
boot layer
  |- Layer B with Spring framework.
       |- Layer C with Module X and Module Y
```
 
In Module X we have the following code

        System.out.println("ThreadContextClassLoader:" + Thread.currentThread().getContextClassLoader());
        System.out.println("This classLoader:" + this.getClass().getClassLoader());

        //now  resource as stream for class from Module Y:
        var stream1 = this.getClass().getClassLoader().getResourceAsStream("com/foo/moduley/ContextConfig.class");
        System.out.println("Stream 1 = " + stream1);
 
        var stream2 = this.getClass().getClassLoader().getResourceAsStream("org/springframework/context/ApplicationContextAware.class");
        System.out.println("Stream 2 = " + stream2);

        var clazz = this.getClass().getClassLoader().loadClass("org.springframework.context.ApplicationContextAware");
        System.out.println("Class:" + clazz);
        var stream3 = clazz.getModule().getResourceAsStream("org/springframework/context/ApplicationContextAware.class");
        System.out.println("Stream 3 = " + stream3);
 
And this is output:
   
        ThreadContextClassLoader:jdk.internal.loader.Loader@426bf2f2
        This classLoader:jdk.internal.loader.Loader@426bf2f2
        Stream 1 = sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@68dc2f53
        Stream 2 = null
        Class:interface org.springframework.context.ApplicationContextAware
        Stream 3 = sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@1d51b6a8

As we see `getResourceAsStream` works differently in JPMS. Now cosider ClassPathResource.getInputStream() and this line

https://github.com/spring-projects/spring-framework/blob/4e2d3573189b7c0afce62bce29cd915de4077f56/spring-core/src/main/java/org/springframework/core/io/ClassPathResource.java#L209

Because if this the given JPMS application won't work.

I suggest either add `ModulePathResource` class (I looked for it but didn't find) or modify ClassPathResource.getInputStream().

**Comment by snicoll** [comment]
Please share a sample that we can run ourselves. Code and log output like that is not complete enough, I am afraid.

**Comment by sbrannen** [comment]
Have you tried using `ModuleResource`?
