### ISSUE TITLE
TraceId is missing in WebFlux controller handlers

### ISSUE THREAD

**Issue by nstdio** [spring-projects/spring-framework#31706]
We upgraded from Spring Boot `3.1.5` to `3.1.6` and trace id and span id are missing from the logs. However, it's not only a logging issue but also baggage is lost too.

Please find an example application demonstrating the issue: [demo.zip](https://github.com/spring-projects/spring-boot/files/13488734/demo.zip). You can change Spring Boot version from `build.gradle.kts` to `3.1.5` and see that trance id and span id are present in the logs.

**Comment by bclozel** [comment]
This is due to a regression introduced by #31417.
