### ISSUE TITLE
OAuth2RestTemplate deprecated from spring boot 3

### ISSUE THREAD

**Issue by VanitaDhanagar** [spring-projects/spring-framework#31712]
Question Summary
If applicable, please mention:

client library (token-client) and 3.3.0
Environment: Cloud Foundry
Additional information
I want to migrate a application from spring boot 2 to 3 and we are stuck wth OAuth2RestTemplate which is no longer supported

	<dependency>
		<groupId>org.springframework.security.oauth</groupId>
		<artifactId>spring-security-oauth2</artifactId>
		<version>2.5.0.RELEASE</version>
	</dependency>
more info on code https://github.com/SAP-samples/cloud-espm-cloud-native/blob/main/worker/src/main/java/com/sap/refapps/espm/config/EnterpriseMessagingConfig.java

Kinldy guide us in migrating the application with proper document and steps with example

Regards,
vanita

**Comment by bclozel** [comment]
This is rather a question for the Spring Security project. Fortunately they have written a detailed guide: https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide
