### ISSUE TITLE
cannot resolve `ServerRequest::pathVariable` in nested `RequestPredicate`  again

### ISSUE THREAD

**Issue by nise-nabe** [spring-projects/spring-framework#31732]
**Affects:** 6.1.1

---

It seems to be regression #26163 on spring boot 3.2.0.
I checked 6.1.0-M4 is work and  6.1.0-M5 is not work.
I guess, 39786e479080a337691a3a7d0490547e37a900e3 is affect to this.

**Comment by poutsma** [comment]
We have a test that should verify this scenario, see https://github.com/spring-projects/spring-framework/blob/1734deca1e91fac25ea6b0f472a66e9882f63205/spring-webmvc/src/test/java/org/springframework/web/servlet/function/RouterFunctionsTests.java#L102, but looking at the sample code in #26163 not all scenarios are tested.

Specifically, the "/person2/{id}" and "/person4/{id}" from the sample in #26163 do not work on 6.1.1.

**Comment by poutsma** [comment]
Thanks for reporting this, it should be fixed in 6.1.2.
