### ISSUE TITLE
SimpleAsyncTaskScheduler: task with fixed delay stops working after unhandled exception

### ISSUE THREAD

**Issue by ztomic** [spring-projects/spring-framework#31749]
When using virtual threads all `@Scheduled` executors stop working after first exception on any `@Scheduled` executor and no error is logged. With disabled virtual threads `@Scheduled` executors continue working and exception is logged with `TaskUtils$LoggingErrorHandler` and `SimpleAsyncUncaughtExceptionHandler`.

Demo is here: https://github.com/ztomic/scheduling-demo

In this demo `DemoEvent` is generated every 5 seconds with `@Scheduled` task, and there are two listeners, one is `@Async` and other is synchronous and both of them are throwing exception on every second invocation. Also, there is one `@Scheduled` task which throws exception on every second invocation.

With disabled virtual threads, all `@Scheduled` tasks continue working after exception.

Run application with virtual threads disabled and after that with virtual threads enabled in `application.yml`.

**Comment by jhoeller** [comment]
I suppose this problem specifically materializes with fixed-delay tasks which we need to execute on the main scheduler thread... and which we therefore need to wrap in a defensive error handler.

**Comment by ztomic** [comment]
I have tested with `6.1.2-SNAPSHOT` and it seems that now is working ok. Loggers are different between virtual and platform threads, but that is not a problem.

**Comment by jhoeller** [comment]
Good to hear! Thanks for testing the snapshot.

**Comment by kSzajo** [comment]
> > Also ThreadPoolTaskSchedulerCustomizer is not used with virtual threads.
> 
> If you use virtual threads, `SimpleAsyncTaskScheduler` is doing the scheduling. You can customize the scheduler with `SimpleAsyncTaskSchedulerCustomizer`.
> 
> If you use platform threads, `ThreadPoolTaskScheduler` is doing the scheduling. You can customize the scheduler with `ThreadPoolTaskSchedulerCustomizer`.

`ThreadPoolTaskSchedulerCustomizer`does not contain setErrorHandler

Is it possible to declare exception handler for `SimpleAsyncTaskScheduler`?
