### ISSUE TITLE
Provide more control over charset parameter when sending form data

### ISSUE THREAD

**Issue by ffray** [spring-projects/spring-framework#31742]
The default charset-parameter added to the `Content-Type` header when using `FormHttpMessageWriter` or `FormHttpMessageConverter` with [SPR-16613](https://github.com/spring-projects/spring-framework/issues/21154) is causing some trouble if the server does not support specifying a charset.

As the spec for `application/x-www-urlencoded` did not exist for a long time and the one provided by [whatwg - application/x-www-form-urlencoded](https://url.spec.whatwg.org/#application/x-www-form-urlencoded) is still somewhat vague,
both clients and servers have implemented various approaches for dealing with this MIME-type.

Earlier HTML specs mention the non-intuitive behavior:
> Parameters on the [application/x-www-form-urlencoded](https://www.w3.org/TR/2014/REC-html5-20141028/iana.html#application/x-www-form-urlencoded) MIME type are ignored. In particular, this MIME type does not support the charset parameter.

At the moment I'm struggling to integrate a piece of software against such server, while trying to use Spring Securities `SpringReactiveOpaqueTokenIntrospector`, as there is currently no way to override the default behavior.

Though I'll use an entire custom implementation, I'd like to propose supporting that adding the charset can be turned off.
I've already created a patch and tests for the `FormHttpMessageWriter` and `BodyInserters` which uses `Hints` to control omitting the charset and would like to contribute if this proposal is accepted.

**Comment by ffray** [comment]
I like the custom codec solution way better than my code.
Didn't notice this simple approach, which comes quite handy!

**Comment by rstoyanchev** [comment]
This was also reported in #22588 and it led to the creation of the `getMediaType` method. Considering the lack of clear guidance in the spec, and that some servers don't handle it well, we should make it easier to submit without the charset parameter.
