### ISSUE TITLE
Add checkstyle rule to prevent unnecessary throws Exception for @Test methods

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-framework#31753]
There are too many unnecessary ` throws Exception`, for example:

https://github.com/spring-projects/spring-framework/blob/47fe61ef79573b4373e989d878524c1dea2d72d9/integration-tests/src/test/java/org/springframework/aop/framework/autoproxy/AdvisorAutoProxyCreatorIntegrationTests.java#L78-L83

Before add rule to enforce that, we must cleanup existing codes, It's a tough task.

**Comment by bclozel** [comment]
The team tends to "clean up" entire test classes when working on a particular feature/issue. Removing unnecessary `throws Exception` from method signature hasn't been priority so far. Given the amount of work and the fact that this adds very little value to the project maintenance, I don't think we should spend any time on this.

I'm not in favor of this rule nor this change but we'll discuss that as a team.

**Comment by bclozel** [comment]
Alright the team doesn't have lots of interest for that right now so I'm closing this issue.
In general, unless there's a clear maintenance improvement as a result, we'd rather polish tests as we update them than spend time applying broad changes like this.
