### ISSUE TITLE
Incorrect `#this` and `#root` variable examples in SpEL documentation

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-framework#31770]
There is something wrong or incomplete in the [SpEL documentation](https://docs.spring.io/spring-framework/reference/core/expressions/language-ref/variables.html).

- `SimpleEvaluationContext.forReadOnlyDataAccess()` doesn't compile. I think that should be `SimpleEvaluationContext.forReadOnlyDataBinding().build()`.
- The "following example" has no mention of `#root`.

> The following examples show how to use the #this and #root variables:

**Comment by sbrannen** [comment]
Thanks for bringing that to our attention, @mhalbritter. 👍 

I've fixed those errors (as well as some others that I noticed in the process) and added a new example using `#root`.

See the [6.1.2 snapshot reference docs](https://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/core/expressions/language-ref/variables.html#expressions-this-root).

**Comment by mhalbritter** [comment]
Thanks Sam!
