### ISSUE TITLE
`@ComponentScan` doesn't support class file versions above 61 (java-17)

### ISSUE THREAD

**Issue by tronwa** [spring-projects/spring-framework#31794]
**Affects:** 6.x

---
If the project java version is set up with a version higher than 17 (eg 21), the component scan is not able to proceed. The following error message is given as cause: Unsupported class file major version 65. It seems the Component scan annotation is not able to handle java versions above 17.

**Comment by sbrannen** [comment]
What Spring Framework version are you using?

**Comment by snicoll** [comment]
I don't understand the report. Spring Framework 6 is compatible with Java 21. It should be relatively easy to build a small sample that reproduces the error message you've described.

You can attach the project as a zip or push the code to a separate GitHub repository.

**Comment by tronwa** [comment]
Dang! 

I was cloning the last version of the Spring Pet Clinic, and assumed that it was using Spring version 6. Digging into the poms it seems like the Spring version is 5.3.x. 

Sorry for the inconvenience!

Yours, 
Tron
