### ISSUE TITLE
Avoid potential refresh deadlock with AbstractApplicationContext#registerShutdownHook

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#31811]
Originally reported in #29692. 

Courtesy of @wilkinsona, looking at the original PR:

> It looks to me like a better fix could be to only synchronize on `startupShutdownMonitor` while closed and active are being read or written so that those reads and writes are atomic.

**Comment by wilkinsona** [comment]
These changes have broken [this Spring Boot test](https://github.com/spring-projects/spring-boot/blob/a242bd81e29e70c3c7bc27b849d83a4c70bf7b39/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/SpringApplicationShutdownHookTests.java#L96-L123).
