### ISSUE TITLE
When using the new version of spring cloud gateway mvc, an exception occurs when the request address contains spaces

### ISSUE THREAD

**Issue by zengqinglei** [spring-projects/spring-framework#31840]
**Describe the bug**
Exception occurs when the request address contains spaces: Invalid character ' ' for QUERY_PARAM in "2023-12-11 00:00:00"
![image](https://github.com/spring-cloud/spring-cloud-gateway/assets/7374317/08dca86c-0178-4699-91e3-f3107ae82ee1)

Before this, I was using the webflux gateway and this problem did not occur.

**Details**
spring boot 3.2.0
spring cloud 2023.0.0
spring cloud starter gateway mvc 4.1.0
request url: http://localhost:8080/enterprise-service/api/v3/enterprise?start_created_time=2023-12-11 00:00:00&end_created_time=2023-12-12 00:00:00

 I hope your team can help us analyze the possible causes and provide some solutions as soon as possible. Thank you very much!

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-gateway/issues/3185

Please don't cross post.
