### ISSUE TITLE
Rest Client, automatically set content-length of body on put/post

### ISSUE THREAD

**Issue by gregjotau** [spring-projects/spring-framework#31854]
Put call that fails with 400:

```
restClient.put()
                .uri("/tickets/$ticketId")
                .contentType(MediaType.APPLICATION_JSON)
                .body(CloseTicketRequest())
                .retrieve()
                .body(String::class.java)
```

I already had "equivalent" code in python using requests library, so was a bit surprised. 

When inspecting the HTTP request I noticed that the RestClient do not add the content-length automatically, while the requests library did that. 

When missing, I get 400 bad request from the server. 

I propose either:

1. always automatically add content-length 
2. instead of or in addition of having a .contentLength() method, why not just have an option to set it automatically, why should I convert my payload to json and getting its length "manually"?

![content-length](https://github.com/spring-projects/spring-framework/assets/13047497/e6b10c0c-486f-4ec3-9e19-c6fe4d8f6d97)

**Comment by bclozel** [comment]
This is called out [in the upgrade guide here](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#web-applications).
