### ISSUE TITLE
DefaultServerRequestObservationConvention is silently used when multiple convention beans are defined

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-framework#31864]
With Spring Boot 3.1.6, a Spring WebFlux application with Micrometer Observation would fail to start when multiple beans of type `ServerRequestObservationConvention` are defined, which I consider expected behavior. However, with Spring Boot 3.2.0 this behavior changed, and now you don't get a startup failure when multiple `ServerRequestObservationConvention` beans are defined, but silently `DefaultServerRequestObservationConvention` is used. I think this is unexpected and confusing behavior.

I've created https://github.com/breun/spring-boot-reactive-observation-convention-issue to illustrate this issue.  See the tests on the `spring-boot-3.1` and `spring-boot-3.2` branches of this project.

**Comment by bclozel** [comment]
We'll align the Framework behavior with the previous Spring Boot setup.
