### ISSUE TITLE
Unable to use sync cache with reactivestreams

### ISSUE THREAD

**Issue by krizajb** [spring-projects/spring-framework#31861]
Since commit `f99faac` that affected sync cache, I believe one can not integrate sync cache anymore since`spring-context/src/main/java/org/springframework/cache/interceptor/CacheAspectSupport.java` enforces the use of `Cache.retrieve` when reactivestreams are present.

**Comment by jhoeller** [comment]
The asynchronous `Cache.retrieve` arrangement has support for a sync-like model as well as independent `retrieve`/´put` steps. We process `CompletableFuture` and reactive types specifically now, treating their contained values as cache values rather than the wrapper objects but we still adhere to `sync=true` vs `sync=false` semantics via delegating to the corresponding `Cache.retrieve` variant.

**Comment by jhoeller** [comment]
All of the caching annotations understand `CompletableFuture`/`Mono`/`Flux` now and store the produced values (or list of values) in the cache now, automatically re-adapting them for a cache hit. This works for `@Cacheable` as well as `@CachePut` and does not require any special preparations, just a regular `CompletableFuture` or Reactive Streams Publisher that we can attach to (e.g. waiting for the value to be requested and therefore produced and then automatically storing it in the cache).

**Comment by krizajb** [comment]
I was not able to make it work with the additional info you provided. I removed the `Mono.cache()` calls. Care for an example? Thank you.

**Comment by jhoeller** [comment]
With a `CaffeineCacheManager` and `setAsyncCacheMode(true)`, it should work out of the box. Or as above, you could also do `new CaffeineCache(CACHE_NAME, Caffeine.newBuilder().buildAsync(), true)`.

Any use of `@Cacheable` and `@CachePut` on a reactive method should automatically interact with the async `retrieve` facilities on the configured `Cache` then.

**Comment by krizajb** [comment]
This produces an async behaviour that isn't desired.

**Comment by jhoeller** [comment]
Well, the way we add those interactions to the reactive pipeline as a follow-up step to producing its value, the interactions have to be asynchronous. Regular `Cache.get` can block which must be avoided for the reactive pipeline. So for that new interaction model, this has to be a required setup, I'm afraid.

Theoretically you may keep using synchronous cache interactions with `Mono.cache()` if we add an escape hatch for this (which we could do for 6.1.3). That said, please be aware that you are adding potential blocking to your `getCompetition()` call then when `Cache.get` is trying to look for a cache hit.

Why do you prefer manually enforced caching through `Mono.cache()` over asynchronous cache interactions, actually? Or in other words, why is asynchronous behavior undesirable?

**Comment by krizajb** [comment]
It's an existing code that operates like that, since the framework supported it I guess.

**Comment by snicoll** [comment]
I don't think that answers our question. Here it is again

> Or in other words, why is asynchronous behavior undesirable for an environment which is inherently asynchronous through the use of a Mono-based reactive pipeline already?

**Comment by krizajb** [comment]
Since the app depends on a certain sequence of events. To be exact, if `@PutCache` is called before `@Cachable`, the instance freshly cached must be returned by the `@Cachable`. This can not be guaranteed with the use of async cache.

**Comment by jhoeller** [comment]
On the timing concerns between cache put and lookup operations, with a local cache this won't be very different from a synchronous cache in practice. Even with `retrieve`, Caffeine is able to determine a cache hit immediately, just lazily retrieving the associated value. And `put` remains a synchronous hand-off operation even in asynchronous mode. As a consequence, I suppose that Caffeine's async cache mode specifically might work for your scenario as well, and we generally recommend a migration to caching the produced values in 6.1 style going forward.

That said, given this report and #31868, there seem to be several scenarios where such manual adaptation through `Mono.cache()`/`Flux.cache()`  has worked with synchronous local caches before. While we recommend the 6.1 way of caching produced values, for scenarios where such a revision is not immediately possible/desirable, we introduce set the system property "spring.cache.reactivestreams.ignore=true" (can also be a similar entry in a `spring.properties` file on the classpath) as an escape hatch. I'll use this ticket for the introduction of that flag in 6.1.3.
