### ISSUE TITLE
Memory leak in SessionRegistryImpl

### ISSUE THREAD

**Issue by gitcastilar** [spring-projects/spring-framework#31895]
**Affects:** \<Spring Framework version>

---

The SessionRegistryImpl , has a memory leak in this.sessionIds = new ConcurrentHashMap<>();
because SessionInformation class hasn´t a equal I solve creating my own RegisterSessionAuthenticationStrategy(new SessionAuthentication())

**Comment by jhoeller** [comment]
I suppose you meant to report against Spring Security instead since these are not core Spring Framework classes:
https://github.com/spring-projects/spring-security/issues
