### ISSUE TITLE
java.lang.NullPointerException with Scheduled tasks through DefaultScheduledTaskObservationConvention

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-framework#31918]
original issue https://github.com/micrometer-metrics/micrometer/issues/4507

**Comment by bclozel** [comment]
Thanks for raising this @marcingrzejszczak - this is fixed for the next maintenance version.

**Comment by jofisiva** [comment]
Can you please share the changes available version 
Does anyone have any idea if these merged back to the 6.1.0 version ?

Thanks

**Comment by bclozel** [comment]
@jofisiva this has been fixed in 6.1.3 - if you're already using 6.1.0, you should be upgrading to the latest 6.1.x version: maintenance versions are meant to be drop in replacements with bug fixes and performance improvements.
