### ISSUE TITLE
Log warning if multiple `@PostMapping`, `@GetMapping`, etc. annotations are declared

### ISSUE THREAD

**Issue by calliduslynx** [spring-projects/spring-framework#31962]
If more than one of the `@(Method)Mapping` annotations are used, only one seems to be recognized.

**Reproduction:**

Put `@GetMapping` and `@PostMapping` together on a method of a controller:

```java
@RestController
class AnyController {
  @GetMapping("x")
  @PostMapping("x")
  fun x() = println("x")
}
```

If you now test the endpoint you see that `GET /x` is mapped, but `POST /x` is not (405 - Method Not Allowed).

**Expectation:**

The expectation is that both annotations are processed and both endpoints would be available.

At least there should be a warning that one is ignored.

**Tested with:**

Spring Boot 3.0.13 on Java 17.0.7

**Workaround:**

Use `@RequestMapping(method = { ... })`.

**Comment by calliduslynx** [comment]
@cdmatta Of course you're right from technical point of view. And the way how these things are "implemented" as a composed annotation is extremely elegant.

But from a Spring Boot (novice) users view I see these annotations in hundreds of tutorials and articles and if I use them combined they don't cause any problems (compile error, start error, log). One of them just don't work. And even for me (who uses Spring Boot every day for years) it was not clear. 

And the comment you marked is not very obvious. I read it and did not know that `@RequestMapping` is not repeatable. And even with this knowledge you have to think twice to realize that two `@(Method)Mapping` annotations will not work.

**Comment by sbrannen** [comment]
**Team Decision**:

For Spring Framework `6.1.x`, we have decided to detect multiple `@RequestMapping` declarations on a handler method and log a warning stating that only the first such annotation will be used. We may also update the documentation for the affected annotations to point out the current limitation.

For Spring Framework `6.x`, we would like to investigate the feasibility of supporting multiple `@RequestMapping` annotations on a single controller method. See #32043.
