### ISSUE TITLE
restTemplate issue with exchange functionality 

### ISSUE THREAD

**Issue by manjian14** [spring-projects/spring-framework#31994]
Hi

Recently, we encountered issues after upgrading our Spring Boot application from version 3.1.7 to 3.2.1, which relies on Spring Framework 6.1.2. Specifically, we faced problems with bad requests for certain API calls when utilizing the restTemplate exchange functionality. However, downgrading to Spring Framework web 6.0.15 resolved the issue, and the exchange functionality started working correctly.

The sender utilizes the restTemplate exchange to communicate with the receiver, which seems is running on Spring Framework web 6.1.2. Interestingly, the receiver doesn't experience any problems; the issue appears to be isolated to the sender, consistently resulting in a bad request.

It's worth noting that the issue persists both on the server and locally.

this is our restTemplate bean 

```
    @Bean
    public RestTemplate restTemplate(final RestTemplateBuilder templateBuilder) {
        templateBuilder.requestFactory((Supplier<ClientHttpRequestFactory>) HttpComponentsClientHttpRequestFactory::new)
                .setConnectTimeout(Duration.ofMillis(20000));
        return templateBuilder.build();
    }
```

**Comment by bclozel** [comment]
This issue is missing the sample project requested in https://github.com/spring-projects/spring-boot/issues/39067

We will reopen this issue once there is something actionable on our side, typically a simple way to reproduce the problem.
