### ISSUE TITLE
[spring-tx] Unable to override prepareSynchronization of AbstractPlatformTransactionManager from v6.1.0

### ISSUE THREAD

**Issue by tagorenathv** [spring-projects/spring-framework#32000]
From spring-framework v6.1.0, prepareTransactionStatus() has been changed from protected to private in AbstractPlatformTransactionManager. 
With this we are unable to extend JpaTransactionManager to override prepareSynchronization() to set `SESSION encrypt.key` for new transactions. 

Is this intended ? If yes, how to set for latest versions?
Reference doc links: [6.0.9](https://docs.spring.io/spring-framework/docs/6.0.9/javadoc-api/org/springframework/transaction/support/AbstractPlatformTransactionManager.html#prepareSynchronization(org.springframework.transaction.support.DefaultTransactionStatus,org.springframework.transaction.TransactionDefinition)) vs [6.1.0](https://docs.spring.io/spring-framework/docs/6.1.0/javadoc-api/org/springframework/transaction/support/AbstractPlatformTransactionManager.html)

Thanks in advance.

**Comment by jhoeller** [comment]
BTW depending on your initialization needs there, `JpaTransactionManager` also offers `setEntityManagerInitializer` with a `Consumer<EntityManager>` callback as of 5.3.
