### ISSUE TITLE
Async EventListener does not track traceId

### ISSUE THREAD

**Issue by mkubele** [spring-projects/spring-framework#32005]
**Affects:** 6.1.2

TraceId is not reported if the _EventListener_ function is also annotated with _Async_
Demo project is prepared [HERE](https://github.com/mkubele/tracing/tree/async_listener)

This used to work on v5.3.22

**Comment by bclozel** [comment]
I think this is working as designed. We don't configure context propagation by default on task executors. [See the `@EventListener` observability section in the reference documentation](https://docs.spring.io/spring-framework/reference/integration/observability.html#observability.application-events).
