### ISSUE TITLE
Improve testing with WebClient

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-framework#32011]
When we are using a `RestTemplate` or `RestClient` we can easily write tests using the `MockRestServiceServer` and register some behavior. For more complex testing scenarios it is possible to use things like wiremock etc. 

For the reactive version of the web there is no equivalent `MockRestServiceServer`, so when testing the `WebClient` we would always need something like wiremock or another library or totally mock the dependency. 

It would be nice if there would be an equivalent way of of testing `WebClient` based code like there is for `RestTemplate`/`RestClient`.

**Comment by snicoll** [comment]
Duplicate of #19852
