### ISSUE TITLE
`DefaultRestClientBuilder.defaultRequest(...)` doesn't do anything

### ISSUE THREAD

**Issue by ThomasKasene** [spring-projects/spring-framework#32028]
`DefaultRestClientBuilder.defaultClient(Consumer<RestClient.RequestHeadersSpec<?>>)` can be used to set a property, but that property is never actually used when building the `RestClient`.

Is this related to #31625?

**Comment by injae-kim** [comment]
https://github.com/spring-projects/spring-framework/blob/0c42965fc36f19868fbba382b2e03ed172087438/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultWebClientBuilder.java#L325-L330

https://github.com/spring-projects/spring-framework/blob/0c42965fc36f19868fbba382b2e03ed172087438/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultWebClient.java#L481-L484

Hi @poutsma ! I found that `DefaultWebClient&Builder` set&pass `Consumer<WebClient.RequestHeadersSpec<?>> defaultRequest;` from builder to client and `DefaulltWebClient` use it well on `initRequestBuiilder()` like above!

---

> https://github.com/spring-projects/spring-framework/commit/0820210c7c7dbc0a58730c09196b6b52c4732f17 Introduce RestClient

https://github.com/spring-projects/spring-framework/blob/0c42965fc36f19868fbba382b2e03ed172087438/spring-web/src/main/java/org/springframework/web/client/DefaultRestClientBuilder.java#L117

https://github.com/spring-projects/spring-framework/blob/0c42965fc36f19868fbba382b2e03ed172087438/spring-web/src/main/java/org/springframework/web/client/DefaultRestClientBuilder.java#L365-L380

But on `RestClient&Builder` that introduced on above commit, I think we miss to pass `defaultRequest` from builder to `DefaultRestClient` on `build()` 😅
(also there's no unit test for `defaultRequest` on `DefaultRestClient&Builder`)

---

https://github.com/spring-projects/spring-framework/blob/0c42965fc36f19868fbba382b2e03ed172087438/spring-web/src/main/java/org/springframework/web/client/DefaultRestClient.java#L516-L518

```java
private ClientHttpRequest createRequest(URI uri) throws IOException {
	ClientHttpRequestFactory factory;
	if (defaultRequest != null) {
            defaultRequest.accept(this); //👈👈
        }
	if (DefaultRestClient.this.interceptors != null) {
```
I think we can fix it like above (pass&use `defaultRequest` inside of `DefaultRestClient > DefaultRequestBodyUriSpec > createRequest`. WDYT?

If you agree with my investigation, I'll create PR right away~!

**Comment by injae-kim** [comment]
oh based on https://github.com/spring-projects/spring-framework/issues/31625, maybe `DefaultRestClientBuilder.defaultRequest` is intended to be unused. (it's experimental feature)

I think we can remove it now or later, so waiting your opinion~! thanks!

**Comment by injae-kim** [comment]
> already prepared a fix myself

@poutsma aha then feel free to just close my PR~! if there's anything I can contribute or help, please share to me. thanks! 👍
