### ISSUE TITLE
Document how to enable method parameter name resolution in a Groovy Application

### ISSUE THREAD

**Issue by jjathman** [spring-projects/spring-framework#32054]
**Affects:**  6.1

With the upgrade of Spring to version 6.1, method parameter names need to be enabled. This is documented here: https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention. This change is not enough on its own to solve this problem for Groovy based applications. 

I think the following should be added to the upgrade notes to help people with Groovy applications. I could not find this documented anywhere.

```groovy
tasks.withType(GroovyCompile).configureEach {
    groovyOptions.parameters = true
}
```

**Comment by sbrannen** [comment]
I've updated the Wiki page to mention `-parameters` support for Groovy in the opening paragraph and added Kotlin/Groovy examples for Gradle as well.
