### ISSUE TITLE
Reference Doc URL is Not Found

### ISSUE THREAD

**Issue by BykaWF** [spring-projects/spring-framework#32067]
[Screencast from 01-19-2024 07:04:12 PM.webm](https://github.com/spring-projects/spring-framework/assets/119706327/3b0e0e35-64f5-4cf5-a23f-dc9bb61c2aa0)

But this link works fine https://docs.spring.io/spring-framework/reference/index.html

**Comment by NilavroSeal2000** [comment]
In the web page Reference doc is redirecting to a different link [https://docs.spring.io/spring-framework/reference/6.1/index.html](url) 
The actual link for the document is [https://docs.spring.io/spring-framework/reference/index.html](url)

**Comment by snicoll** [comment]
@sdeleuze https://docs.spring.io/spring-framework/reference/6.1 does not work anymore. Could it be related to a recent change?

**Comment by jcw1031** [comment]
[https://docs.spring.io/spring-framework/reference/](https://docs.spring.io/spring-framework/reference/)

**Comment by sdeleuze** [comment]
Should be fixed by https://github.com/spring-projects/spring-framework/pull/32083.
