### ISSUE TITLE
Configure JDK 23 early access CI build

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#32090]
## Overview

[Java 23 early access builds](https://jdk.java.net/23/) are already available.

Our CI currently maintains [JDK 21](https://ci.spring.io/teams/spring-framework/pipelines/spring-framework-6.1.x/jobs/jdk21-build/builds/) and [JDK 22](https://ci.spring.io/teams/spring-framework/pipelines/spring-framework-6.1.x/jobs/jdk22-build/builds/) compatibility builds. We should do the same for JDK 23 as soon as the test suite is usable with early access versions.

## Related Issues

- #31459

**Comment by sbrannen** [comment]
An initial attempt via `./gradlew test -PtestToolchain=23` reveals issues with Mockito (Byte Buddy).

> Caused by: java.lang.IllegalArgumentException: Java 23 (67) is not supported by the current version of Byte Buddy which officially supports Java 22 (66) - update Byte Buddy or set net.bytebuddy.experimental as a VM property

**Comment by snicoll** [comment]
Gradle does not yet support Java 23, see https://docs.gradle.org/current/userguide/compatibility.html#java

**Comment by snicoll** [comment]
So it turns out that it works for our purpose with Gradle 8.8 (ping @ljacomet). There are a number of failures that I am not investigating.

First thing is that Awaitility does not work with EA builds, see https://github.com/awaitility/awaitility/pull/279

**Comment by snicoll** [comment]
This is blocked by https://github.com/spring-projects/spring-framework/issues/30649

Here's a build scan against `6.1.x` with `23.ea.29`: https://ge.spring.io/s/uyz33y2i7ezac/tests/overview?outcome=FAILED

**Comment by snicoll** [comment]
> Gradle does not yet support Java 23, see https://docs.gradle.org/current/userguide/compatibility.html#java

It turns out it doesn't affect us as much as I thought. We're using the toolchains to run the tests, which doesn't trigger any compilation and that work pretty much out of the box. As @ljacomet explained to me, the problem is incremental compilation and others advanced compiled scripts use cases. We don't use any of that.
