### ISSUE TITLE
Move ModifiedClassPathExtension from spring-boot-test-support to core-test

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-framework#32098]
It would be nice if class path modifications could be done as easy as by using `@ClassPathExclusions` in tests allowing users to test different behaviours when working with optional dependencies.

**Comment by snicoll** [comment]
Agreed but the current code is in an artifact that is not published as the team made a conscious code not to publish it to avoid having to maintain all the edge cases that the community may end up asking. I think that's the right call and making it a public API in framework will lead to a exacerbation of that. I suggest copying the code in your own projet, this is what I intend to do when tackling similar problems here.

**Comment by christophstrobl** [comment]
thanks @snicoll - will do.
