### ISSUE TITLE
Patch on RestClient on Spring Boot 3.2.1 not working.

### ISSUE THREAD

**Issue by testersen** [spring-projects/spring-framework#32114]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.web.client.ResourceAccessException: I/O error on PATCH request for "https://example.com": Invalid HTTP method: PATCH] with root cause

```kt
restClient.patch()
  .uri("https://example.com")
  .retrieve()
```

**Comment by poutsma** [comment]
See also https://github.com/spring-projects/spring-boot/issues/36266
