### ISSUE TITLE
[Spring Web Site] I can't subscribe to RSS feed as XML is blank

### ISSUE THREAD

**Issue by alexandertsukanov** [spring-projects/spring-framework#32127]
Hi, Spring team!

I would like to follow your news and updates using an RSS feed. However, I am currently unable to do so due to issues with the RSS feeds. Could you please have a look at the problem?

- https://spring.io/blog.atom/
- https://spring.io/blog/category/engineering.atom/
- https://spring.io/blog/category/releases.atom/
- https://spring.io/blog/category/news.atom/

They all are blank.

**Comment by sbrannen** [comment]
Hi @alexandertsukanov,

Congratulations on submitting your first issue for the Spring Framework! 👍 

Technically, those issues are related to the spring.io Web site which is for the entire Spring portfolio; however, I don't think there is a public issue tracker for the Web site.

So I'm closing this issue.

But I'll report this internally to the team responsible for the Web site, and I'll post back here once I hear they're addressed the issue.

Cheers,

Sam

**Comment by alexandertsukanov** [comment]
@sbrannen , Yep, sorry for that. But TBH I am unable to find other ways to report the problem.

**Comment by bclozel** [comment]
@alexandertsukanov in the meantime, cutting the trailing slash works:

* https://spring.io/blog.atom
* https://spring.io/blog/category/engineering.atom
* https://spring.io/blog/category/releases.atom
* https://spring.io/blog/category/news.atom

**Comment by alexandertsukanov** [comment]
@bclozel Thanks!
I have used the following links:

![CleanShot 2024-01-26 at 11 19 58@2x](https://github.com/spring-projects/spring-framework/assets/17796771/69f416c9-7838-49f5-8fea-8260a0c74a01)

**Comment by sbrannen** [comment]
Please note that RSS links generated on https://spring.io/blog/ no longer include the trailing slashes, and those links work.
