### ISSUE TITLE
R2DBC Core DatabaseClient.sql replacing column 'key' to '[*]key'

### ISSUE THREAD

**Issue by corebase2023** [spring-projects/spring-framework#32156]
Hi fellow developers,

Spring r2dbc DatabaseClient replace query that have column name 'key' to '[*]key' and this causes error in the query execution.

`Mono<Map<String, Object>> first = db.sql("SELECT key FROM table_a");`

The executed query will be "SELECT [*]key FROM table_a". This will cause error in the application as the query failed.

Anyone having this issue in their project? Any workaround?

source file: https://github.com/spring-projects/spring-framework/blob/main/spring-r2dbc/src/main/java/org/springframework/r2dbc/core/DefaultDatabaseClient.java

**Comment by snicoll** [comment]
@corebase2023 I am struggling to see where `DatabaseClient` replaces  `key` to `'[*]key'` but you seem to have found that. Can you expand and provide a small sample rather than a link to our own code? Thanks!

**Comment by snicoll** [comment]
I just saw you've asked the same question in the [Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/issues/39325). Don't cross post as it's a waste of time for everybody.
