### ISSUE TITLE
AbstractAspectJAdvice.invokeAdviceMethod does not seem to call ProceedingJoinPoint.proceed()

### ISSUE THREAD

**Issue by natl-set** [spring-projects/spring-framework#32167]
IMHO, AbstractAspectJAdvice.invokeAdviceMethod should call ProceedingJoinPoint.proceed() instead of invoking Method.invoke manually. So that it should call the generated byte code in case that CglibAopProxy is used.

**Comment by snicoll** [comment]
This code invokes before/after advice methods on the aspect, not the target method that is being intercepted. `ProceedingJoinPoint.proceed()` is for dispatching to that target method, and that's what we use it for.

**Comment by natl-set** [comment]
@snicoll I think we should use the same mechanism to invoke the proxy code. In cglib aop proxy case, it creates MethodProxy and wrap that in MethodInvocation so it should use that instead of trying to call Method.invoke directly.
