### ISSUE TITLE
Multipart resolving issue due to change in Undertow

### ISSUE THREAD

**Issue by Laurens-W** [spring-projects/spring-framework#32178]
Undertow has [fixed a CVE](https://github.com/undertow-io/undertow/commit/1f67f7a2f189a7de491bd42692e4860261866ff8) regarding a potential memory leak.

Since this fix, if you upload a part that is larger than the 16384 byte limit that is imposed, the parsing of a request goes wrong here because Undertow has created a "file" part that has a Disposition header without a filename:

https://github.com/spring-projects/spring-framework/blob/b61552b9df8e3f18f901fd30996ae0ec0f222060/spring-web/src/main/java/org/springframework/web/multipart/support/StandardMultipartHttpServletRequest.java#L99

**Comment by bclozel** [comment]
I don't understand. What is the ask here? How should we update Spring Framework?
This CVE is fixed in Undertow but I don't see how this is impacting our support.

**Comment by Laurens-W** [comment]
I wasn't too sure whether it was a spring issue or an Undertow issue, but giving it another thought After Juergen's comment I think this should be filed as an issue with Undertow!
Undertow is providing a Content-Disposition header that doesn't match with them writing the part to a file

**Comment by bclozel** [comment]
I guess they're not fixing the case where the given file name is null, but only fixing the fact that they'll make up a file name of their own when writing to disk for temporary storage. So this doesn't change anything to our support, it's rather an internal matter for Undertow. If you believe something needs to be done here or in Undertow, please create first a sample application that demonstrates the problem and share it with the relevant team. I'll close this issue now.

**Comment by Laurens-W** [comment]
FYI
https://github.com/undertow-io/undertow/pull/1541#issuecomment-1921364323
I've created a reproducer and mentioned that on a PR that proposes a fix related to this problem

**Comment by Laurens-W** [comment]
FYI: Undertow has merged a fix for this problem, and has release a 2.3.11.Final version
