### ISSUE TITLE
No longer able to override the `toString()` in `HandlerMethod` from `6.1.3`

### ISSUE THREAD

**Issue by mauriciogeneroso** [spring-projects/spring-framework#32184]
**Affects:** 6.1.3

---
Spring actuator has a [WebMvcEndpointHandlerMethod](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/servlet/AbstractWebMvcEndpointHandlerMapping.java#L164) that extends and overrides the `toString()` from HandlerMethod [here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/servlet/AbstractWebMvcEndpointHandlerMapping.java#L454).

After the change made on the issue #32007, ([this commit](https://github.com/spring-projects/spring-framework/commit/e7eaaaded1060f52dbe8530c1715fc33849d700a)), the `toString()` is no longer used because the HandlerMethod is wrapped into another instance of `HandlerMethod`, In this block of code:

```java
  // Enable method validation, if applicable
  handlerMethod = handlerMethod.createWithValidateFlags();
```
And this one:
```java
  /**
  * Re-create the HandlerMethod and initialise
  * {@link #shouldValidateArguments()} and {@link #shouldValidateReturnValue()}.
  * @since 6.1.3
  */
  public HandlerMethod createWithValidateFlags() {
     return new HandlerMethod(this, null, true);
  }
```

So, I found the issue because in [spring-open-api](https://github.com/springdoc/springdoc-openapi) it is no longer able to generate the correct name of the endpoints from actuator `/health`, `/info`, `/metrics`, etc.. due to code is calling the wrong `toString()` method. 

## Expected

The field validations implemented in the issue #32007 should not force the override of the `toString()` wrapping its subclasses back into `HandlerMethod`.

**Comment by jhoeller** [comment]
We could preserve the overridden toString result in the HandlerMethod copy constructor, setting the new description to `handlerMethod.toString()` instead of `handlerMethod.description`. I'll change this for the upcoming 6.1.4 snapshot, feel free to give it a try!

**Comment by jhoeller** [comment]
Thanks for double-checking!
