### ISSUE TITLE
c namespace injection Exception

### ISSUE THREAD

**Issue by PaceyWang** [spring-projects/spring-framework#32188]
The String name is injected into the int age using Spring c namespace injection
<img width="1225" alt="spring6 1 2" src="https://github.com/spring-projects/spring-framework/assets/130941966/2f6214a7-cceb-4001-9051-1188099a1293">

**Comment by jhoeller** [comment]
If you are using Spring Framework 6.1.x there, have you compiled your classes with `-parameters`? This is mandatory as of 6.1 since we do not detect debug symbols anymore.

**Comment by PaceyWang** [comment]
No, I use Maven3.8 to manage and compile my project, use Junit5.9 to test it. When I use Spring6.0.6,the problem seems solved, so I think the problem is from spring6.1.2.

**Comment by PaceyWang** [comment]
No, I use Maven3.8 to manage and compile my project, use Junit5.9 to test it. When I use Spring6.0.6,the problem seems solved, so I think the problem is from spring6.1.2.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spring-projects/spring-framework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月2日(星期五) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spring-projects/spring-framework] c namespace injection Exception (Issue #32188)





 
If you are using Spring Framework 6.1.x there, have you compiled your classes with -parameters? This is mandatory as of 6.1 since we do not detect debug symbols anymore.

**Comment by jhoeller** [comment]
Make sure to configure the Maven compiler plugin accordingly then: see https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x - as of 6.1, `-parameters` is a must-have for such scenarios.

**Comment by PaceyWang** [comment]
![image](https://github.com/spring-projects/spring-framework/assets/130941966/9894bdce-603e-46dd-a35f-9e6922f91faa)     I add -parameter in idea runnable param, and set in Maven like this, but the problem in 6
.1.2 is still existing. 
![Uploading image.png…]()

**Comment by PaceyWang** [comment]
![image](https://github.com/spring-projects/spring-framework/assets/130941966/39b0d209-e114-4688-bf88-a130433d3798)
I add -parameter in idea runnable param, and set in Maven like this, but the problem in 6
.1.2 is still existing.
![image](https://github.com/spring-projects/spring-framework/assets/130941966/ff5cf442-c640-43a1-a6cc-bad1e2f57bcd)

**Comment by PaceyWang** [comment]
![image](https://github.com/spring-projects/spring-framework/assets/130941966/c695bb25-6d40-4faa-8b80-d1de9015e5b3)
I set in Maven like this and add param -parameter in idea, but the problem is still existing.
![image](https://github.com/spring-projects/spring-framework/assets/130941966/fb5e5413-477d-4a3f-8abd-211bdeec64a8)

**Comment by PaceyWang** [comment]
and when I switch the version to 6.1.3, the problem is not existing. It seems only in 6.1.2

**Comment by sbrannen** [comment]
> and add param -parameter in idea

Please note that it is `-parameters` (with an "s").

In addition, the screenshot you've provided does not show that you added anything to the "Additional command line parameters" field, and (since I don't use IDEA) I don't know if that "Override compiler parameters per-module" feature achieves the exact same goal.

> and when I switch the version to 6.1.3, the problem is not existing. It seems only in 6.1.2

6.1.2 has been superseded by 6.1.3, so use 6.1.3.
