### ISSUE TITLE
Content-Length value and actual length value can be different

### ISSUE THREAD

**Issue by chanhyeong** [spring-projects/spring-framework#32186]
**Affects:** 6.1.x

## Condition

- spring-cloud-gateway (`ProxyExchange`)
- spring-mvc (`RestController`)
- spring-test
    - with restassured

## Bug

[`getContentLength()`](https://github.com/spring-projects/spring-framework/blob/ae17b11b703029616aed78e36ace11c3beb446fd/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L133-L136) value and [length of actual value](https://github.com/spring-projects/spring-framework/blob/ae17b11b703029616aed78e36ace11c3beb446fd/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L149-L152) can be different.

```json

                    {
                        "contextContent": {
                            "aSource": {
                                "a": "20242024"
                            },
                            "bSource": {
                                "b": "20252025"
                            }
                        }
                    }
                
```

1. I sent a body as json string like above, the byte array size of raw string is 369.
2. And that number filled as `Content-Length` header in [MockHttpServletRequestBuilder](https://github.com/spring-projects/spring-framework/blob/ae17b11b703029616aed78e36ace11c3beb446fd/spring-test/src/main/java/org/springframework/test/web/servlet/request/MockHttpServletRequestBuilder.java#L724-L729)
3. `Content-Length` header is sent as request header in apache [httpcore RequestContent](https://github.com/apache/httpcomponents-core/blob/028847b0251d7a05fa54a9e92717a86cc26a05c7/httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestContent.java#L133)
    - `HttpComponentsClientHttpRequest$BodyEntity#getContentLength`
4. But actual length value is 125, which is serialization result of jackson ObjectMapper ([AbstractJackson2HttpMessageConverter](https://github.com/spring-projects/spring-framework/blob/ae17b11b703029616aed78e36ace11c3beb446fd/spring-web/src/main/java/org/springframework/http/converter/json/AbstractJackson2HttpMessageConverter.java#L440))

This mismatch cause `Connection Reset` -> server wait until receiving 369 bytes, but client sent 125.

## Before 6.1.x

This issue didn't exist because `HttpComponentsClientHttpRequest` use `ByteArrayEntity` that contains a serialization result of jackson ObjectMapper

https://github.com/spring-projects/spring-framework/blob/72835f10b9b07921978da419abf2a182abf67967/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L91

**Comment by bclozel** [comment]
Rather than providing your analysis can you share an example of application that shows the issue? It's hard for us to help you as we are missing the entire context.

**Comment by chanhyeong** [comment]
@bclozel

I made a sample in https://github.com/chanhyeong/headersample
You can reproduce this issue by following below.

1. Run spring boot application
2. Run [failedBecauseOfInvalidContentLengthHeader()](https://github.com/chanhyeong/headersample/blob/6b071e2bc58ded29287168e5534618dfd9adfac4/src/test/java/com/example/headersample/controller/ProxyApiControllerTest.java#L26) to see this issue
    - boot application server blames SocketTimeoutException
3. Run [successWithMatchingContentLength()](https://github.com/chanhyeong/headersample/blob/6b071e2bc58ded29287168e5534618dfd9adfac4/src/test/java/com/example/headersample/controller/ProxyApiControllerTest.java#L51) to see success case when content length value matched

**Comment by bclozel** [comment]
@chanhyeong the project is not accessible.

**Comment by chanhyeong** [comment]
@bclozel

I'm sorry. I changed visibility as public.

**Comment by bclozel** [comment]
Thanks for the sample. I don't think this issue is related to Spring Framework.

Here, the request body is deserialized from JSON into a Map, then re-serialized as the request body to the proxied service. The "Content-Length" header is copied over directly. I don't think that this should happen. The "Content-Length" header should be overwritten, or the body should never be deserialized in the first place (this is quite inefficient in this case).

You can consider changing your controller to the following:

```java
	@PostMapping("/**")
	public ResponseEntity<?> serverProxy(
		ProxyExchange<byte[]> proxyExchange,
		HttpServletRequest request,
		@RequestBody byte[] body
	) {
		String url = assembleUrl(proxyExchange, request);
		return proxyExchange.uri(url).body(body).post();
	}
```

I think this has been raised already in spring-cloud/spring-cloud-gateway#3154 and I'll close this issue in favor of that one. There are other workarounds described there, and probably a future fix for this.

**Comment by chanhyeong** [comment]
Thanks. I doubted because `HttpComponentsClientHttpRequest` was changed.

Also, I'm going to add 'Content-Length' header into sensitive headers list temporarily to prevent propagating to downstream.
It will be added by [httpcore RequestContent](https://github.com/apache/httpcomponents-core/blob/028847b0251d7a05fa54a9e92717a86cc26a05c7/httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestContent.java#L133).
