### ISSUE TITLE
spring-context-indexer 6.1.3 does not work. I've read the source code and it's deprecated. How do I fix this?

### ISSUE THREAD

**Issue by tangllty** [spring-projects/spring-framework#32194]
![image](https://github.com/spring-projects/spring-framework/assets/58468628/e5f34df6-1ecb-4a11-a9ce-c5dfb7f7ad55)

**Comment by bclozel** [comment]
We have tests showing that the indexer works. It is deprecated since we've shown that AOT is more efficient and we don't think that maintaining both systems is a good use of our time.

Please share a minimal application that shows how the indexer does not work in your case.

**Comment by snicoll** [comment]
Irrespective of the sample, this issue isn't really actionable. If you can provide the application that Brian requested, we can reopen and have a look.
