### ISSUE TITLE
RestClient : interceptors are executed 2 times

### ISSUE THREAD

**Issue by rawadolb** [spring-projects/spring-framework#32196]
**Describe the bug**
When RestCient is initialized by a RestTemplate using RestClient.builder(restTemplate) the interceptors are executed 2 times.

**To Reproduce**
Create a RestTemplate with an interceptor (loggingInterceptor to make it simple).
Initialize a RestClient and then perform a call restClient.get().uri(uri).retrieve().body(YourObject.class)
LoggingInterceptor will be executed 2 times because 2 ClientHttpRequestInterceptor object are created. (Please find attached)

**Expected behavior**
The interceptor must be executed once

![image](https://github.com/spring-projects/spring-framework/assets/36637981/6db86b34-a59e-49fc-821c-3019f135a442)

**Comment by jhoeller** [comment]
This should be fixed in 6.1.4 snapshots already: #32038
