### ISSUE TITLE
Spring Boot with Active MQ  STOMP Failover (Active/Standby) - auto reconnect to Standby without closing existing connection 

### ISSUE THREAD

**Issue by dileeproopreddy** [spring-projects/spring-framework#32200]
Chat has been implemented using React JS with Spring Boot as the back-end. Relay to STOMP broker AWS Managed ActiveMQ service is enabled. The use-case is straight forward; chat has to be connected 24x7. Broker is setup in a active/standby configuration. As soon as there is a fail-over of active broker(url-1) the standby broker(url-2) kicks-in. A supplier of two addresses for active and standby is configured, the system fail-over is happening as expected. 

However, the existing connections to Active Broker (chats) are not ported automatically to standby broker, rather, it's just disconnected in UI and a fresh Web Socket connection had to be requested. The reconnection logic is not implemented for Client sessions, but rather, only System connection.

**Comment by snicoll** [comment]
Please do not comment in multiple places, see https://github.com/spring-projects/spring-framework/issues/26169#issuecomment-1928608240
