### ISSUE TITLE
[FIX REQUEST] cvc-elt.1.a: Cannot find the declaration of element 'project'.	pom.xml / Downloading external resources is disabled

### ISSUE THREAD

**Issue by rodneyazev** [spring-projects/spring-framework#32219]
Fix default maven-4.0.0.xsd project tag creation

Change https://maven.apache.org/xsd/maven-4.0.0.xsd (default project configuration value) to http://maven.apache.org/xsd/maven-4.0.0.xsd

Default:

![spring-tag-default](https://github.com/spring-projects/spring-framework/assets/40548312/2384fad4-21e7-4763-be2d-78c038efe98e)

Fix:

![spring-tag-fixed](https://github.com/spring-projects/spring-framework/assets/40548312/f9da6f3c-015d-4761-b00d-7d9ad3013acc)

**Comment by snicoll** [comment]
This is the wrong place to report this, see also https://github.com/spring-projects/spring-framework/issues/32220#issuecomment-1933486294.

There's nothing wrong having an XSD using https. You're showing an issue in your IDE but that doesn't mean the source is wrong. If you need support for that, please ask on StackOverflow.

**Comment by rodneyazev** [comment]
No problem. I know how to fix this. Just thinking about those who don't know having to correct something trivial, something that the IDE itself doesn't recognize, which it should.
