### ISSUE TITLE
System Requirements Specification

### ISSUE THREAD

**Issue by sharubitsi** [spring-projects/spring-framework#32213]
I am willing to start my open source software development. Can you help me find the first issue, please?  
Btw, I'am senior year student in Nazarbayev Univercity and i am taking the course related open source software.  
Thanks in advance.

**Comment by snicoll** [comment]
Thanks for the interest but we use this issue tracker for reporting bug or enhancement request. 

Any issue that is not currently assigned can be a candidate and feel free to add a comment to one of them to express your interest. I am afraid we don’t have issues for beginners at this time.
