### ISSUE TITLE
Avoid ASYNC dispatch if possible in DefaultAsyncServerResponse 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#32223]
Spring for GraphQL relies on the GraphQL Java `AsyncExecutionStrategy` as do most other solutions. However, the actual handling in some cases may return immediately without the need for blocking. For such cases, the ASYNC dispatch could be avoided to reduce overhead.

We are going to make a change https://github.com/spring-projects/spring-graphql/issues/904 in Spring for GraphQL to call `ServerResponse.async(future)` conditionally, only if the future is not done, but this might be more generally useful. 

This issue is to explore whether similar conditional logic could be done within the call to `ServerResponse.async`.

**Comment by poutsma** [comment]
@rstoyanchev Done. Note that I did some additional checks on the future, compared to Spring GraphQL, to ensure that the future has not been canceled nor completed exceptionally, see [here](https://github.com/spring-projects/spring-framework/commit/89d746ddf86550dd7177159838797823f20868e1#diff-c59a5e3aa6075c0928cbc3c8c8cc1ee557ac731119ac2991ef2d9fa494decce5R83-R85). You might want to include the same checks in Spring GraphQL.
