### ISSUE TITLE
Unable to use customConverters while upgrading the version of spring to 3.2.1 while using @ModelAttribute

### ISSUE THREAD

**Issue by thomajic** [spring-projects/spring-framework#32255]
affect:6+

**Comment by thomajic** [comment]
affect:6+

**Comment by snicoll** [comment]
@thomajic an issue report with only a title is not actionable. If you want us to investigate, please describe the problem you're facing, and in which version this was working. Attaching a sample we can run ourselves would significantly increase the likelihood of a speedy response.

**Comment by thomajic** [comment]
@GetMapping
    public MyModel exampleMethod(@ModelAttribute("myModel") MyModel model,
      BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            // Method logic
            return model;
        }
      return model;
    }


I am using basic code

for converter i am using conversionservice

/*
 *  Copyright (C) 2021 adidas AG.
 */

package com.adidas.m3.pb.m3pbcommonstarter.configuration;

import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.format.FormatterRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import java.time.Instant;
import java.util.Collection;


@AutoConfiguration
public class WebDataBinderConfig implements WebMvcConfigurer {
  
  @Override
  public void addFormatters(FormatterRegistry registry) {
    registry.addConverter(new CustomStringToSetConverter());
    registry.addConverter(String.class, Instant.class, Instant::parse);

    registry.removeConvertible(String.class, Collection.class);
  }
}


I am using java21 and springboot 3.2.1

I am getting below error

Failed to convert property value of type 'java.lang.String' to required type 'java.time.Instant' for property 'date'; Cannot convert value of type 'java.lang.String' to required type 'java.time.Instant' for property 'date': no matching editors or conversion strategy found\n\tat org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:135)\n\tat com.adidas.m3.pb.m3pbcommonstarter.web.bind.OpenApiDataBinder.applyPropertyValues(OpenApiDataBinder.java:47)

**Comment by thomajic** [comment]
May be you can use the attached

**Comment by thomajic** [comment]
[untitled 2.zip](https://github.com/spring-projects/spring-framework/files/14275191/untitled.2.zip)

**Comment by thomajic** [comment]
[untitled.zip](https://github.com/spring-projects/spring-framework/files/14275568/untitled.zip)

**Comment by snicoll** [comment]
@thomajic thanks for the sample but this is the third time I am asking. In which Spring Boot version the sample above worked?

**Comment by rstoyanchev** [comment]
The attached demo works just fine. I used:
```
curl -v "http://localhost:8040/test?date.from=2007-12-03T10:15:30.00Z&date.to=2007-12-03T10:15:30.00Z"
```

On the server side, `MyModel` is initialized as expected without BindingResult errors. 

I gather the issue has something to do with the registration of converters, but you need to provide something that fails. As it is there is no failure, and the registration of the `Instant` converter makes no difference, because this is already supported. I can remove `WebDataBinderConfig` completely and it works just the same.

Please, provide a sample that demonstrates the failure.

**Comment by youssef3wi** [comment]
I think there is an issue in the `applyPropertyValues` method of your `com.adidas.m3.pb.m3pbcommonstarter.web.bind.OpenApiDataBinder.applyPropertyValues(OpenApiDataBinder.java:47)`.

**Comment by thomajic** [comment]
Hello everyone i think i got the issue where it fails. Thank you.
