### ISSUE TITLE
[Test]RestTemplate default null timeout values are not propagated as infinite to underlying OkHttp3Client implementation

### ISSUE THREAD

**Issue by KrzysztofOwczarekDiscovery** [spring-projects/spring-framework#32269]
**Affects:** 6.0.13

---

Using **TestRestTemplate** with unspecified **connectTimeout** and **readTimeout** make it fall back to underlying **OkHttp3Client** defaults which are 10000ms each.

Using explicit timeout values in **TestRestTemplate** overrides **OkHttp3Client** successfully.

It is (well, not a good) standard that library timeouts set to `null`, `0`, or `-1` map to infinity, but right now, timeout settings are completely hidden from the library users, who widely believe that [Test]RestClient have infinite timeouts by default.

If it is so by design, it should probably be pointed out that spring-web users should always fall back to the default settings of the client implementation they are currently using (although they probably don't know which one is it).

<img width="435" alt="Screenshot 2024-02-14 at 15 37 48" src="https://github.com/spring-projects/spring-framework/assets/89917995/60527752-0dfa-40ab-aeca-bb970e3ee86e">
<img width="984" alt="Screenshot 2024-02-14 at 15 38 57" src="https://github.com/spring-projects/spring-framework/assets/89917995/3ca08a84-02b6-4dea-8492-bb09ffb8d6d8">

from: **org.springframework.http.client.OkHttp3ClientHttpRequest**
<img width="924" alt="Screenshot 2024-02-14 at 15 39 42" src="https://github.com/spring-projects/spring-framework/assets/89917995/4c17a946-7007-47b5-9960-b13be3c25990">

<img width="463" alt="Screenshot 2024-02-14 at 15 42 29" src="https://github.com/spring-projects/spring-framework/assets/89917995/95495a32-0845-401e-a220-41fc4fa5a4d7">
<img width="995" alt="Screenshot 2024-02-14 at 15 43 37" src="https://github.com/spring-projects/spring-framework/assets/89917995/b6456f0e-4652-40db-9158-34c92477f1d6">
from: **org.springframework.http.client.OkHttp3ClientHttpRequest**
<img width="912" alt="Screenshot 2024-02-14 at 15 43 53" src="https://github.com/spring-projects/spring-framework/assets/89917995/4a5ef1b2-dbfe-4d9c-a52d-656c87a8d740">

**Comment by snicoll** [comment]
@KrzysztofOwczarekDiscovery thanks for the report but OkHttp3 support is deprecated and will be removed so we don't intend to make further change to it.
