### ISSUE TITLE
Pagination / Sort support in http interface client

### ISSUE THREAD

**Issue by hesselapplications** [spring-projects/spring-framework#32286]
It would be great if [http interface clients](https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/integration.html#rest-http-interface) had support for:
- Page as a response type
- Pageable / Sort as request parameters

```kotlin
interface FooClient {
  @GetExchange("/foos")
  public fun getFoos(
    pageRequest: Pageable,
  ): Page<Foo>
}
```

This would bring feature parity for what is supported in controllers today. I believe spring openfeign clients support this as well

**Comment by snicoll** [comment]
There's no such concept in the  core framework. I think you're probably taking about Spring Data REST and both paging and sorting are Spring Data specific. Please direct that question there and we can see if there's something required in the core framework based on their analysis.
