### ISSUE TITLE
Revise approach for RequestAttributesThreadLocalAccessor

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#32296]
#32243 added a built-in `ThreadLocalAccessor` adapter for `RequestContextHolder`. However, the `FrameworkServlet` which manages the thread local, also calls `RequestAttributes#requestCompleted` on the way out, so in case of an asynchronous request, the propagated `RequestAttributes` instance ends up having `requestActive=false` which results in `IllegalStateException` if you try access any attributes.

We need to consider how to address this. The simplest option would be to create a separate `ServletRequestAttributes` instance for context propagation purposes.

**Comment by snicoll** [comment]
I've moved this to a task as the original proposal is not released yet and therefore this isn't user facing if it is fixed in the same milestone.
