### ISSUE TITLE
Revisit DatabaseMetadata#getProcedures to only apply fallback if original search yield more than one result

### ISSUE THREAD

**Issue by audunmeltzer** [spring-projects/spring-framework#32295]
**Affects:** \spring-jdbc 6.1.2

---
Upgrade from spring-jdbc 6.1.1 to 6.1.2 does not support schema name with underscore, ie 'schema_name'. When execute procedure call. 

`
SimpleJdbcCall(dataSource)
                .withSchemaName("schema_name")
                .withFunctionName("updateName")
                .declareParameters(
                                SqlParameter("id", Types.VARCHAR),
                                SqlParameter("name", Types.VARCHAR))
                .execute(MapSqlParameterSource(mapOf("id" to id, "name" to newName)))
                `
Exception thrown
`org.springframework.dao.InvalidDataAccessApiUsageException: Required input parameter 'RETURN_VALUE' is missing`

**Comment by jhoeller** [comment]
@snicoll is this possibly a regression caused by #22725?

**Comment by audunmeltzer** [comment]
I will create a simple project to illustrate the problem

We are using image mcr.microsoft.com/mssql/server:2017

**Comment by snicoll** [comment]
Thanks very much. Since you mention an image, adding a Docker compose or similar to setup the database will be very much appreciated as I suspect this might be key to the issue here.

**Comment by audunmeltzer** [comment]
I have created a simple repo that hopefully illustrates our issue, and might help find a soultion
https://github.com/ks-no/spring-jdbc-demo

As described in readme file, I have created different branches witch combines test with different spring-boot versions and schema name with and without underscore '_'. There is one test that calls a procedure that will run or fail on different branches

**Comment by snicoll** [comment]
Thanks for the sample but how do I run that test in an IDE?

**Comment by snicoll** [comment]
I've managed to reproduce the problem. @audunmeltzer FYI, the sample made it extra hard as I couldn't find a way to run your test in IntelliJ IDEA. I managed by using "run all tests under package" option.

This seems to be a bug in the JDBC driver that you're using. I've opened https://github.com/microsoft/mssql-jdbc/issues/2336. I'll see if we can offer an escape hatch for this.

**Comment by snicoll** [comment]
I've made the fix for the original issue a bit more lenient, with the exact same call as before and a fallback on escaping only if more than one procedures/functions are found. This should prevent the fallback from happening from the vast majority of cases and account for drivers that do not handle escaping consistently.
