### ISSUE TITLE
Could not resolve org.aspectj:aspectjweaver:1.8.0.M1

### ISSUE THREAD

**Issue by laithse1** [spring-projects/spring-framework#32307]
project :MCIE_Imove
      > Could not resolve org.aspectj:aspectjweaver:1.8.0.M1.
         > Could not get resource 'https://mvnrepository.com/artifact/org.aspectj/aspectjweaver/org/aspectj/aspectjweaver/1.8.0.M1/aspectjweaver-1.8.0.M1.pom'.
            > Could not GET 'https://mvnrepository.com/artifact/org.aspectj/aspectjweaver/org/aspectj/aspectjweaver/1.8.0.M1/aspectjweaver-1.8.0.M1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve org.aspectj:aspectjweaver:1.8.0.M1.
     Required by:
         project :MCIE_Imove > org.springframework:spring-aspects:4.0.0.RELEASE
      > Could not resolve org.aspectj:aspectjweaver:1.8.0.M1.
         > Could not get resource 'https://mvnrepository.com/artifact/org.aspectj/aspectjweaver/org/aspectj/aspectjweaver/1.8.0.M1/aspectjweaver-1.8.0.M1.pom'.
            > Could not GET 'https://mvnrepository.com/artifact/org.aspectj/aspectjweaver/org/aspectj/aspectjweaver/1.8.0.M1/aspectjweaver-1.8.0.M1.pom'. Received status code 403 from server: Forbidden

**Comment by jhoeller** [comment]
This is not a framework bug or feature request, in particular not for a supported version of the framework. That old AspectJ pre-release has been used for a short period a long time ago; please build a newer version that Spring Framework 4.0.0 there.

The current AspectJ version is 1.9.21, and even 1.8.0 is final for a long time already. If you are trying to locally build Spring Framework 4.0.0 for some reason there, feel free to locally patch the 1.8.0.M1 reference to 1.8.0 in the build script.

**Comment by bclozel** [comment]
Thanks for getting in touch but I don't see how this can be considered as a Spring issue.

mvnrepository.com is not an artifact repository as far as I know, it's merely indexing jars in a search engine. If you would like some assistance to configure your build, please use StackOverflow.
