### ISSUE TITLE
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils + spring-core-5.3.27.jar + java-11-openjdk-11.0.14.9-1.windows.redhat.x86_64

### ISSUE THREAD

**Issue by hellerEkc** [spring-projects/spring-framework#32306]
Hi, I have this warning in application start log. Do someone know how to solve this issue?

2024-02-02 12:31:19,660 [main] INFO  JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2024-02-02 12:31:19,755 [main] INFO  LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/C:/Users/ceh6yu/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.3.27/ff5e35f2d4f72d22c476ff9b7bce1de25c980ebd/spring-core-5.3.27.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by snicoll** [comment]
Duplicate #22019 and many others. See also https://github.com/spring-projects/spring-framework/issues/22019#issuecomment-453479344.
