### ISSUE TITLE
`constructor-impl` of Kotlin `value class` is not called

### ISSUE THREAD

**Issue by k163377** [spring-projects/spring-framework#32324]
The `init` block of the `value class` can contain processing.

```kotlin
@JvmInline
value class Value(val value: Int) {
    init {
        if (100 < value) throw IllegalArgumentException()
    }
}
```

This will be compiled into a method named `constructor-impl` in the bytecode.

When instantiating a `value class` using Java reflection, both `constructor-impl` and `box-impl` must be called in order to be equivalent to instantiating it on `Kotlin`.
On the other hand, there is no evidence that `constructor-impl` is called in the `spring-framework`, and only `box-impl` seems to be called.

Is this an intentional design?

**Comment by sdeleuze** [comment]
I have reached Kotlin team to get related guidance.

**Comment by efemoney** [comment]
Coroutine handling (in `CoroutineUtils.invokeSuspendingFunction`) calls `box-impl` directly. Ideally that would call the single primary constructor gotten from kotlin reflection.

**Comment by sdeleuze** [comment]
@efemoney Unless I am mistaken, and as confirmed by the Kotlin team, this is not possible due to #31698.

**Comment by efemoney** [comment]
Yeah I saw that but its slightly different from what I am saying which is

```
value class PlanId(val value: Int) {
  init {
    require(value >= 0) // Throw if value is negative
  }
}

assertEquals(
  PlanId(21),
  PlanId::class.primaryConstructor!!.call(21),
)

assertFails {
  PlanId::class.primaryConstructor!!.call(-21)
}
```

**Comment by sdeleuze** [comment]
Good point, should be ok to use this.
