### ISSUE TITLE
Restore Jetty 10 compatibility in JettyClientHttpResponse

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-framework#32337]
As part of 186d6e3, support for Jetty 10 was mistakenly removed. It should be restored.

Thanks for @sbordet for noting this regression in https://github.com/spring-projects/spring-framework/commit/186d6e370da7481688b1ede776891608d169e7d7#commitcomment-139066680.

**Comment by poutsma** [comment]
Resolved in e44f84e.

**Comment by poutsma** [comment]
@sbordet This should now be fixed. I tested it in a small sample app using reactive client 1.x and 2.x. It would be great if you try a 5.3.33 snapshot to confirm.

**Comment by sbordet** [comment]
@poutsma I could confirm that this issue is now fixed. Thanks!
