### ISSUE TITLE
Breaking change introduced from 6.1.3 to 6.1.4 by rejecting @RequestMapping and @HttpExchange declarations on the same element.prevents elegant designs. #32328

### ISSUE THREAD

**Issue by NemesisMate** [spring-projects/spring-framework#32364]
Spring Framework **6.1.4** is breaking compatibility with **6.1.3** (and therefore also breaking going from Spring Boot **3.2.2** to **3.2.3**) by throwing an exception when it detects that both annotations (`@RequestMapping` and `@HttpExchange`) are used in the same element, which, although made in purpose (https://github.com/spring-projects/spring-framework/issues/32065) I would assume it should not be part of a patch release.
Still, I'd appreciate for this constraint to be reviewed rather than just postponed as mentioned in https://github.com/spring-projects/spring-framework/issues/32328

**Comment by NemesisMate** [comment]
Hi @snicoll , why was this ticket closed as "not planned"?, is it a general approach to break compatibility between patch releases?

**Comment by bclozel** [comment]
@NemesisMate this was closed as a duplicate of #32328. There is no need to have this conversation in two different places.

**Comment by NemesisMate** [comment]
@bclozel , I opened both of them. The one you mention is to discuss a design decision while this one was meant to potentially fix a breaking change that should have not been introduced. Two different conversations really (this one could and likely should be addressed even if the mentioned one isn't).

Anyhow, if you still think it should remain closed I'll respect it.
Thanks.
