### ISSUE TITLE
`StringUtils.uriDecode` decodes strings with non-ASCII characters incorrectly

### ISSUE THREAD

**Issue by Romanow88** [spring-projects/spring-framework#32360]
**Affects:** 6.1.3

`StringUtils.uriDecode` will take two different paths depending if "%" is found. One of these does not handle non-ASCII characters.

Fast path:

```java
StringUtils.uriDecode("ü", StandardCharsets.UTF_8) // returns "ü"
```

Replace path:

```java
StringUtils.uriDecode("%20ü", StandardCharsets.UTF_8) // returns " �"
```

**Comment by dumbbelloper** [comment]
Hello, I've submitted a Pull Request that aims to address this issue: [PR #32373](https://github.com/spring-projects/spring-framework/pull/32373)

**Comment by poutsma** [comment]
StringUtils::uriDecode expects the input to be encoded, which means that the `ü` character should have been provided as `%C3%BC` instead. I will add a documentation note that makes this behavior clear.

Note that `StringUtils::uriDecode` is a low-level, internal utility method exposed via higher-level components, such as `UriComponentsBuilder`, that are better at dealing with [en|de]coded URIs.
