### ISSUE TITLE
Java 17 spring boot 2.7.12 AMD EPYC processor - ClassFormatError - java/lang/Class[] 

### ISSUE THREAD

**Issue by Hemanth2012** [spring-projects/spring-framework#32376]
HI team,

we are facing issue with specifically on AMD EPYC processor with Java 17 spring boot application.
When we deploy the application on windows local environment / intel processor based linux system, the application is working fine.
When we deploy the same code in AMD processor based VM in partner environment, we get the below error:
[org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mysqlDataSource' defined in class path resource [com/example/mysqlconnection/config/DatabaseConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'mysqlDataSource' threw exception; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file com/example/mysqlconnection/config/DatabaseConfig$$FastClassBySpringCGLIB$$8d6de34a

Please find attached the minimal application code to reproduce the issue.
[MySqlConnection.zip](https://github.com/spring-projects/spring-framework/files/14494213/MySqlConnection.zip)
Please help with the solution approach.

Regards,
Hemanth

**Comment by bclozel** [comment]
Thanks for getting in touch, but I can't reproduce the problem with the sample you've given. I don't have an AMP EPYC server available and I doubt that this problem is linked to Spring itself. It looks like a Java runtime issue or a Java version incompatibility.

Note that [Spring Boot 2.7 is out of open source support](https://spring.io/projects/spring-boot#support) so we won't be able to assist you further.

**Comment by Hemanth2012** [comment]
Thanks @bclozel for the quick response. 
However, can you please confirm if we can enforce usage of jdk proxy generator instead of default CGLib in this sample project if we move to 3.0 or 3.2.

Regards,
Hemanth

**Comment by Hemanth2012** [comment]
Can you pls update on this ?
