### ISSUE TITLE
Deploy Docs Action should only run on production branches

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#32434]
I've pushed a new branch on this repo for testing purposes and I could see that the action used to deploy the docs kicked off on it. It should only build our "production branches".

**Comment by snicoll** [comment]
@rwinch I was trying to figure this out but I can see that this action also runs on a tag (to build the doc for a release I assume). It's a bit strange that it kicks off for any branch (except the doc branch) and any tag. What am I missing?

**Comment by rwinch** [comment]
You can configure [on.push.<branches|tags|branches-ignore|tags-ignore>](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore) in [deploy-docs.yml](https://github.com/spring-projects/spring-framework/blob/e1b1435a001907c387671d02940d97ea9f501711/.github/workflows/deploy-docs.yml#L3-L5) to specify which branches/tags the docs will be built on.
