### ISSUE TITLE
Document AssertJ support for MockMvc

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#32454]
With #21178 merged, we still need to work on the documentation. The current MockMvc section is really focused on Hamcrest matchers and this makes some section harder to document that I would like. We've discussed to perhaps use different tabs for code sample to showcase "plain" MockMvc vs. the AssertJ counterpart but, with Kotlin, this leads to 4 tabs which is far from ideal.

**Comment by bclozel** [comment]
Should we consider separate pages for `MockMvc`/`MockMvcTester` and treat them as variants, just the way we do it for Servlet and Reactive? Each section could point to the relevant one like [this one](https://docs.spring.io/spring-framework/reference/web/webmvc/filters.html#forwarded-headers) and [this one](https://docs.spring.io/spring-framework/reference/web/webflux/reactive-spring.html#webflux-forwarded-headers).
