### ISSUE TITLE
I really need spring config editor. Help me

### ISSUE THREAD

**Issue by callor** [spring-projects/spring-framework#32503]
You really need the Spring config editor in STS 4.
I am creating Spring Legacy MVC in STS 4.
everything else is ok
However, I am having a lot of trouble creating the Spring Bean Configuration file.
Can you create a plugin so that I can use Spring Config Editor in STS 4?

please please

Thank you so much

**Comment by bclozel** [comment]
This is the issue tracker for Spring Framework. Please use https://github.com/spring-projects/sts4/issues
