### ISSUE TITLE
Spring-Boot dependency consistency

### ISSUE THREAD

**Issue by ahoehn** [spring-projects/spring-framework#32506]
Checking spring-boot-starter-xxx with the maven-enforcer-plugin shows that several spring-boot-starter projects do not depend on the same dependency versions.

TODO:
Add a check for the upcomming next minor version that all official spring-boot-starter projects depend on the same dependency versions.

Examples (there are more bugs than just this 2):
Dependency convergence error for org.slf4j:slf4j-api:jar:2.0.7 paths to dependency are:
  +-org.springframework.boot:spring-boot-starter-validation:jar:3.2.2:compile
    +-org.springframework.boot:spring-boot-starter:jar:3.2.2:compile
      +-org.springframework.boot:spring-boot-starter-logging:jar:3.2.2:compile
        +-ch.qos.logback:logback-classic:jar:1.4.14:compile
          +-org.slf4j:slf4j-api:jar:2.0.7:compile
and
  +-org.springframework.boot:spring-boot-starter-validation:jar:3.2.2:compile
    +-org.springframework.boot:spring-boot-starter:jar:3.2.2:compile
      +-org.springframework.boot:spring-boot-starter-logging:jar:3.2.2:compile
        +-org.apache.logging.log4j:log4j-to-slf4j:jar:2.21.1:compile
          +-org.slf4j:slf4j-api:jar:1.7.36:compile
and
  +-org.springframework.boot:spring-boot-starter-validation:jar:3.2.2:compile
    +-org.springframework.boot:spring-boot-starter:jar:3.2.2:compile
      +-org.springframework.boot:spring-boot-starter-logging:jar:3.2.2:compile
        +-org.slf4j:jul-to-slf4j:jar:2.0.11:compile
          +-org.slf4j:slf4j-api:jar:2.0.11:compile
and
  +-org.springframework.boot:spring-boot-starter-data-jpa:jar:3.2.2:compile
    +-org.springframework.boot:spring-boot-starter-jdbc:jar:3.2.2:compile
      +-com.zaxxer:HikariCP:jar:5.0.1:compile
        +-org.slf4j:slf4j-api:jar:2.0.0-alpha1:compile
and
  +-org.springframework.boot:spring-boot-starter-data-jpa:jar:3.2.2:compile
    +-org.springframework.data:spring-data-jpa:jar:3.2.2:compile
      +-org.springframework.data:spring-data-commons:jar:3.2.2:compile
        +-org.slf4j:slf4j-api:jar:2.0.2:compile
and
  +-org.springframework.boot:spring-boot-starter-data-jpa:jar:3.2.2:compile
    +-org.springframework.data:spring-data-jpa:jar:3.2.2:compile
      +-org.slf4j:slf4j-api:jar:2.0.2:compile
      
Dependency convergence error for jakarta.annotation:jakarta.annotation-api:jar:2.1.1 paths to dependency are:
  +-org.springframework.boot:spring-boot-starter-validation:jar:3.2.2:compile
    +-org.springframework.boot:spring-boot-starter:jar:3.2.2:compile
      +-jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
and
  +-org.springframework.boot:spring-boot-starter-data-jpa:jar:3.2.2:compile
    +-org.springframework.data:spring-data-jpa:jar:3.2.2:compile
      +-jakarta.annotation:jakarta.annotation-api:jar:2.0.0:compile

**Comment by bclozel** [comment]
You must ensure that your application is [inheriting the parent POM](https://docs.spring.io/spring-boot/docs/3.2.3/maven-plugin/reference/htmlsingle/#using.parent-pom) or that it's applying the [Spring Boot dependency management](https://docs.spring.io/spring-boot/docs/3.2.3/maven-plugin/reference/htmlsingle/#using.import) - Spring Boot provides a consistent set of versions with those options.
