### ISSUE TITLE
Add accessor methods WebClient.getBaseUrl() and RestClient.getBaseUrl()

### ISSUE THREAD

**Issue by honza-zidek** [spring-projects/spring-framework#32512]
The interfaces [WebClient](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.html) and [RestClient](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestClient.html) both have generic - **implementation agnostic** - builders:
[WebClient.Builder](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.Builder.html) and [RestClient.Builder](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestClient.Builder.html#baseUrl(java.lang.String))

Both the builders have - again **implementation agnostic** - methods [WebClient.Builder.html#baseUrl(String)](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.Builder.html#baseUrl(java.lang.String)) and [RestClient.Builder.html#baseUrl(String)](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestClient.Builder.html#baseUrl(java.lang.String))

Why then `WebClient` and `RestClient` **don't have** getters `getBaseUrl()` to access the value set by the **implementation agnostic** builder, and why is it left to the implementation classes? When I construct a `WebClient` or a `RestClient`, I don't specify the implementation, so I would expect that the value passed via the implementation agnostic _builder_ would be accessible from the implementation agnostic _interface_. 

I have a use case to ask the object later what its base URL is, but I cannot do it without reflexion.

It would be nice to have getters also for _other_ values passed to the builder.

**Comment by snicoll** [comment]
@honza-zidek I am not sure I am following, what is the use case?

**Comment by honza-zidek** [comment]
@snicoll A possible use case is e.g. in testing. Wherever you want to be *sure* which base URL has been _actually_ set for a specific client.

I can't see any reason why, when the base URL is set in the implementation agnostic builder, the interface is missing a method to get the value, and you have to use reflexion.

**Comment by bclozel** [comment]
If the use case is testing, then we're going to decline this enhancement request: you shouldn't test Spring Framework's code and if anything, you should test that the client generates URLs with the configured base.

Also, in the case of `WebClient`, that information is lost as the base URL is turned into a `UriBuilderFactory`, which is much more than a base URL. Same applies to `RestClient`. So even if we agreed to, there is no easy way to implement the feature you're asking for. I'm closing this issue as a result. Thanks!
