### ISSUE TITLE
ResponseStatusException thrown from exception handler methods is no longer respected

### ISSUE THREAD

**Issue by beytularedzheb** [spring-projects/spring-framework#32538]
Hi,
After upgrading from spring boot 3.2.3 (spring framework 6.1.4) to 3.2.4 (spring framework 6.1.5) I noticed that the status code for some _validated_ rest endpoints changed to status code _500 - Internal Server Error_ when validation errors occur.

For example prior to spring boot 3.2.4 with below exception handler I would get status code 400 but in 3.2.4 it returns 500.

I suspect that it could be due to this change: https://github.com/spring-projects/spring-framework/commit/5f601ceb4585fbb2e868ac9a6c50789b0e8b8263

```kotlin
@RestControllerAdvice
internal class RestControllerExceptionHandler {
    @ExceptionHandler(ConstraintViolationException::class)
    fun exceptionHandler(e: ConstraintViolationException) {
        throw ResponseStatusException(HttpStatus.BAD_REQUEST, e.message, e)
    }
}
```

**Comment by injae-kim** [comment]
> https://github.com/spring-projects/spring-framework/commit/5f601ceb4585fbb2e868ac9a6c50789b0e8b8263 handle exceptions from @ExceptionHandler regardless of whether
thrown immediately or via Publisher.

https://github.com/spring-projects/spring-framework/blob/186e70cd0490c1141dd936aac5bace6c0f9d6dc5/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/RequestMappingHandlerAdapter.java#L321

```java
private static Mono<HandlerResult> handleExceptionHandlerFailure(
	ServerWebExchange exchange, Throwable exception, Throwable invocationEx,
	ArrayList<Throwable> exceptions, InvocableHandlerMethod invocable) {

if (disconnectedClientHelper.checkAndLogClientDisconnectedException(invocationEx)) {
	return Mono.empty();
}

// Any other than the original exception (or a cause) is unintended here,
// probably an accident (e.g. failed assertion or the like).
if (!exceptions.contains(invocationEx) && logger.isWarnEnabled()) {
         // ☝️☝️ if exception is 500 and invocationEx from ExceptionHandler is 400, intend to respect 500 here?
	logger.warn(exchange.getLogPrefix() + "Failure in @ExceptionHandler " + invocable, invocationEx);
}

return Mono.error(exception); // ignore invocationEx and return origin exception!
}
```
Hmm maybe it's intended behavior from above commit?

```java
// Maybe we can fix it like this?
if (invocationEx != null && invocationEx instanceof ResponseStatusException) {
  return Mono.error(invocationEx);
}

return Mono.error(exception);
```


Maybe we can fix like above code, let's wait maintainer's opinion~!
If my suggestion makes sense, I'm ready to open fix PR :) thank you!

**Comment by bclozel** [comment]
Also see https://github.com/spring-projects/spring-boot/issues/40148#issue-2220129300 for another report of this.

**Comment by bclozel** [comment]
@mbanaszkiewicz-vonage @beytularedzheb Thanks for raising this issue. I discussed this with @rstoyanchev and we confirmed that the original behavior was invalid in the first place and that exception handlers are supposed to fully handle the exception or re-throw the original exception.

I initially marked this as a bug for 6.1.x as I thought the the handling of exceptions in different phases was maybe a mistake, but it turns out this is by design in WebFlux and that we may consolidate things in the future.

In the meantime, can you let us know whether returning a `ResponseEntity` would work for your application? We would like to know why you chose this setup in the first place. Thanks!

**Comment by beytularedzheb** [comment]
Hi @bclozel, 
Thank you for checking it.
It was just an easy & quick way of changing the status code and getting standard error response with already populated fields, like path, request id, etc. (DefaultErrorAttributes).
Actually, as you mentioned ResponseEntity, I realized that I can still use ResponseStatusException and achieve the same effect.
Instead of throwing an exception directly in the exception handler method, I can return it in a Mono:
`
@RestControllerAdvice
internal class RestControllerExceptionHandler {
    @ExceptionHandler(ConstraintViolationException::class)
    fun exceptionHandler(e: ConstraintViolationException): Mono<Throwable> {
          return Mono.error(ResponseStatusException(HttpStatus.BAD_REQUEST, e.message, e))
    }
}
`
This should also work for the case you shared above: https://github.com/spring-projects/spring-boot/issues/40148#issue-2220129300

I am closing my ticket.
And thank you again!
