### ISSUE TITLE
No support for SOAP webservices in 6.x

### ISSUE THREAD

**Issue by jbescos** [spring-projects/spring-framework#32546]
**Affects:6.x<Spring Framework version>

---

For Spring Boot there is support for SOAP webservices: https://spring.io/guides/gs/producing-web-service

However in 6.x it was removed: https://github.com/spring-projects/spring-framework/issues/27422

Are you planing to integrate that Spring Boot webservices in spring-framework, or is there any other way to produce a SOAP web service in spring-framework 6?.

**Comment by bclozel** [comment]
The [spring-ws project](https://spring.io/projects/spring-ws)[](https://spring.io/projects/spring-ws) being used by the getting started guide you're pointing to is using Spring Framework 6. SOAP is supported by that project and there is no need for specific support in Framework directly.
