### ISSUE TITLE
Support new Hooking Point.

### ISSUE THREAD

**Issue by chickenchickenlove** [spring-projects/spring-framework#32554]
Hi, Spring Team. 
This is chickenchickenlove, huge fan of you all.

I suggest adding a new Hooking point.
How about adding a new Hooking Point between `SmartLifeCycle#start()` and `@PostConstruct`?
Sometimes, IMHO, it could be useful at times.

It would be great if it could be used in a similar convention to `ApplicationEvent` and `@EventListener`.
```java
@EventListener(BeforeSmartLifeCycleStart.class)
public void doSomething(){
...
}
```

Thanks for reading this. 🙇‍♂️

**Comment by quaff** [comment]
Please describe your actual use case.

**Comment by snicoll** [comment]
> Sometimes, IMHO, it could be useful at times.

Thanks for the suggestion but, without at least one concrete example, this issue is not actionable I am afraid. Before we consider adding an extra API to the core framework, we need to understand what's lacking with what we have and how we could improve it.

**Comment by artembilan** [comment]
I think `SmartInitializingSingleton.afterSingletonsInstantiated()` is the way to go for this use-case.
This way all the beans have called their `afterPropertiesSet()` and no `SmartLifeCycle.start()` called yet.

**Comment by snicoll** [comment]
That was one callback I had in mind indeed, but we can't know for sure until @chickenchickenlove shares why he's asking for another hook point.

**Comment by artembilan** [comment]
In my feeling, according to the related Spring for Apache Kafka PR, the solution lays indeed in the `afterSingletonsInstantiated()`.
And this request was done because @chickenchickenlove had not been aware about `SmartInitializingSingleton`.

**Comment by snicoll** [comment]
OK I am trusting you have more context on that so let's close this.
