### ISSUE TITLE
`@RequestParam` binding does not support params with an empty array "[]" suffix

### ISSUE THREAD

**Issue by panovst** [spring-projects/spring-framework#32577]
**Affects:** 2.5.2

Many http clients pass an array to queryString in this form:
`?attributes[]=field1&attributes[]=field2`

I'm trying to get Controller to work with this format through RequestParam:
```
@RestController
public class FooController {
   
   @RequestMapping(method = RequestMethod.GET,
    value = "/foo",
    produces = "application/json")
   ResponseEntity<FooDto> getFoo(@RequestParam(value = "attributes", required = false) List<String> attributes) {
   }
}
```
However, when executing a request, null is passed to the controller method as the attributes value.

I found that the "RequestParamMethodArgumentResolver.resolveName" method receives "attributes" as the value of the parameter name, while this parameter is stored in the request object using the key "attributes[]". Therefore, the argument of the controller method is null, because resolver cannot find a match.

How would you like to add such support to RequestParamMethodArgumentResolver? The code could look something like this:

```
@Override
    protected Object resolveName(String name, MethodParameter parameter, NativeWebRequest request) throws Exception {
      if (
          (
              parameterTypeIs(List.class, parameter) || parameterTypeIs(Set.class, parameter)
          )
          && nameIsIndexParameter(name, request)) {
        return super.resolveName(name + "[]", parameter, request);

      }
      return super.resolveName(name, parameter, request);
    }

    private boolean parameterTypeIs(Class<?> parameterType, MethodParameter parameter) {
      return parameterType.isAssignableFrom(parameter.getParameterType());
    }

    private boolean nameIsIndexParameter(String name, NativeWebRequest request) {
      return request.getParameterMap().containsKey(name + "[]");
    }
```

In my project, I replaced the built-in RequestParamMethodArgumentResolver with a custom one. An [example](https://stackoverflow.com/questions/78271940/support-for-a-parameter-with-an-index-in-the-query-string-when-bound-to-request) can be found in the description of the question on stackoverflow

**Comment by snicoll** [comment]
> Many http clients pass an array to queryString in this form

Do they? I can see this being used in PHP but that's an implementation detail that's not backed by anything I am aware of in a spec. If you need to pass multiple values, you should use the attribute as requested and let the server rebuild the list  for you.

**Comment by snicoll** [comment]
I wasn't aware we did. That's a question for @rstoyanchev then

See https://github.com/spring-projects/spring-framework/issues/25836#issuecomment-704927342

**Comment by panovst** [comment]
Our situation is further complicated by the following: we use the open api to describe the contract, and the openapi-generator to generate the client and controller interfaces.

this means that even if we consider this option (from the link to the issue that you provided)
```
fun getAllEntities(@RequestParam(name="types[]") types: List<String>) {}
```
there are two disadvantages to this solution:
1. we have to use the attributes[] format in the openapi itself
2. only clients sending "attributes[]=" will be able to work with this method

**Comment by rstoyanchev** [comment]
I think this is the indeed the equivalent of #25836 but for `@RequestParam`.
