### ISSUE TITLE
JMSTemplate.sendAndReceive does not propagate tracer over the wire

### ISSUE THREAD

**Issue by Kantis-ATG** [spring-projects/spring-framework#32606]
**Affects:**  6.1.5

When using `JMSTemplate.sendAndReceive`, the JMS message is sent using [executeLocal](https://github.com/spring-projects/spring-framework/blob/a9fffa844f1bf170cbf80dcb46da8613d7ad735f/spring-jms/src/main/java/org/springframework/jms/core/JmsTemplate.java#L967) which does not forward observations properly. Compare with [execute](https://github.com/spring-projects/spring-framework/blob/main/spring-jms/src/main/java/org/springframework/jms/core/JmsTemplate.java#L527) which does so.

**Comment by bclozel** [comment]
Thanks for raising this @Kantis-ATG - this is now fixed in 6.1.6-SNAPSHOT and will be released on Thursday.

**Comment by Kantis-ATG** [comment]
Snapshot build tested, works great. Thanks for the quick fix 🙌
