### ISSUE TITLE
Introduce `CompilableIndexAccessor` SPI in SpEL

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#32613]
## Overview

Now that we've introduced the `IndexAccessor` SPI in the Spring Expression Language (SpEL), we should introduce support for compiling expressions that use a custom `IndexAccessor`, analogous to the `CompilablePropertyAccessor` SPI that a `PropertyAccessor` can optionally implement.

## Related Issues

- #26478
- #32694
- #32707
- #32708

## Deliverables

- [ ] Introduce `CompilableIndexAccessor` SPI in SpEL.

**Comment by selimdebresen** [comment]
> ## Genel Bakış
> Artık SPI'yi Spring İfade Dili'nde (SpEL) tanıttığımıza göre , a'nın isteğe bağlı olarak uygulayabileceği SPI'ye benzer şekilde `IndexAccessor`özel kullanan ifadeleri derlemek için destek sunmalıyız .`IndexAccessor``CompilablePropertyAccessor``PropertyAccessor`
> 
> ## İlgili konular
> * [`IndexAccessor`SpEL  #26478'i özelleştirmek için SPI'yi tanıtın`Indexer`](https://github.com/spring-projects/spring-framework/pull/26478)
> 
> ## Teslimat
> * [ ] `CompilableIndexAccessor`SpEL'de SPI'yi tanıtın .

**Comment by sbrannen** [comment]
Current work on this issue can be viewed in the following feature branch.

https://github.com/spring-projects/spring-framework/compare/main...sbrannen:spring-framework:issues/gh-32613-spel-CompilableIndexAccessor
