### ISSUE TITLE
@Interceptor annotation

### ISSUE THREAD

**Issue by lukalomidze** [spring-projects/spring-framework#32651]
Proposal for an `@Interceptor` stereotype annotation with values equivalent to `.addPathPatterns`, `.excludePathPatterns`, maybe something like `order` to facilitate chaining, etc, with the final goal of having spring boot auto config take care of registering it instead of having to create a `WebMvcConfigurer`, which seems like a weird mix of base spring and spring boot and somewhat contradictory to what spring boot strives for.

**Comment by bclozel** [comment]
Thanks for the proposal, but this has been already considered and declined here spring-projects/spring-boot#40360 as a duplicate of #9447
