### ISSUE TITLE
BufferingClientHttpRequestFactory should not set content length for empty request body

### ISSUE THREAD

**Issue by nhmarujo** [spring-projects/spring-framework#32650]
We were recently moving from `WebClient` to `RestClient` and one of the 3rd parties we deal with started returning us:
`HTTP Error 411. The request must be chunked or have a content length`

The given request is a `POST` without any body and looking at the outgoing requests the only difference between before and after  is that now the request we generate has a `Content-Length: 0` while before that header was absent.

I do concede that I'm not sure that the 3rd party is handling this properly, but I also have to say that I don't see why the framework would be setting `Content-Length: 0` when there is no body.

I was looking deeper into the code and I can see that the decision to add the `Content-Length` header is being taken [here](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/client/AbstractBufferingClientHttpRequest.java#L46) and that happens because `headers.getContentLength()` returns `-1`. Looking further at the logic on `HttpHeaders` I can see [here](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/HttpHeaders.java#L984) that when that header is not set it just returns `-1`, which is happening in my case.

In my view I don't think it makes sense to send this header in this case, so I was wondering if that could be fixed, perhaps by just doing instead:
```java
if (bytes.length > 0 && headers.getContentLength() < 0) {
	headers.setContentLength(bytes.length);
}
```

This should still ensure that the header is added if it is missing and there is a body, but will not add it if there is no body. It will also not override if explicitly set.

**Comment by onjik** [comment]
Hmm....
The RFC document says. 
> Any Content-Length greater than or equal to zero is a valid value.
   [Section 4.4](https://datatracker.ietf.org/doc/html/rfc2616#section-4.4) describes how to determine the length of a message-body
   if a Content-Length is not given.
https://datatracker.ietf.org/doc/html/rfc2616#section-14.13 

So I'm not sure if it's right to change the preferences like this. Would it be too complicated to eventually give you an interceptor to tamper with a request, or a way to customize a policy?

**Comment by onjik** [comment]
Thank you for your kind and detailed response! @nhmarujo 

I think you're right.

There's no provision that you must attach a content-length header when sending a POST request. I don't think it's the right direction to enforce it at the framework level.
Rather, if the framework doesn't force it, the user is given the option to add that header if they want, and not add it if they don't.

**Comment by nhmarujo** [comment]
Hi @onjik . Thank you!

If we followed something like my suggestion I think it would be the best option, because:
1. if the user didn't set the `Content-Length` but there is a body with size greater than 0, the header will be added with proper value
2. if the user did set the `Content-Length` explicitly, that one will be respected
3. if the user didn't set the `Content-Length` and body as not length, no header will be added

I'm not sure if a variation of this would make more sense in regards of use case 3. to actually check if `Content-Type` is set to take that decision in a more clear way (i.e. `Content-Type` presence would imply that a body is expected or not). So that actually would look like:
```java
if (bytes.length > 0 && headers.getContentLength() < 0 && headers.getContentType() != null) {
	headers.setContentLength(bytes.length);
}
```

What you think?

**Comment by onjik** [comment]
@nhmarujo 

As you mentioned in the first comment, I think [following code](https://github.com/spring-projects/spring-framework/blob/f21e05a9e42475bce0f99951fd2d5fbcbcf21b84/spring-web/src/main/java/org/springframework/http/HttpHeaders.java#L982) is already checking if there is explicit `content-length` header.
```java
	/**
	 * Return the length of the body in bytes, as specified by the
	 * {@code Content-Length} header.
	 * <p>Returns -1 when the content-length is unknown.
	 */
	public long getContentLength() {
		String value = getFirst(CONTENT_LENGTH);
		return (value != null ? Long.parseLong(value) : -1);
	}
```
If there is no explicit `content-length` header, it returns -1. So [following code](https://github.com/spring-projects/spring-framework/blob/f21e05a9e42475bce0f99951fd2d5fbcbcf21b84/spring-web/src/main/java/org/springframework/http/client/AbstractBufferingClientHttpRequest.java#L45) checks if there is explicit `content-length` header. 

```java
if (headers.getContentLength() < 0) {
	headers.setContentLength(bytes.length);
}
```

How about this code
```java
if (headers.getContentLength() < 0 && bytes.length > 0) {
	headers.setContentLength(bytes.length);
}
```
It's similar to the code you provided for the first time, but if threre is explicit `content-length` header, don't check bytes.length. (There's no big difference in performance 🤣)

What you think?

**Comment by nhmarujo** [comment]
Hi @onjik.

Yes, it is basically the same as my first proposal. The reason why I suggested `< 0` instead of `== -1` is because I saw [a commit](https://github.com/spring-projects/spring-framework/commit/570851e8e4ff0072492c18b8753ca185841f5488) on which it seems to be the preferred way to check it within the framework and they actually wanted to make it consistent (I take it was a team decision).

I think both proposals I made are valid, but the latter one might be more accurate (not sure), as the assumption is that if a `Content-Type` is set, then there is the expectation to have a `body` and therefore the `Content-Length` must be set if absent (even if the `body` is empty and in that case it would be set to `0`).

Any concerns about this last proposal or any reason why you would prefer the first one?

Thanks

**Comment by bclozel** [comment]
The "Content-Length" header is not set by Spring, but actually by the JDK HTTP client itself.

Executing the following code

```java
RestClient restClient = RestClient.create();
ResponseEntity<String> response = restClient.post().uri("http://localhost:8080/test").retrieve().toEntity(String.class);
```

Is equivalent to selecting the `JdkClientHttpRequestFactory`, using the `HttpClient` introduced in Java 11:

```java
RestClient restClient = RestClient.builder().requestFactory(new JdkClientHttpRequestFactory()).build();
```

Using another client, like the httpcomponents one, does not send a `Content-Length` request header in this case:

```java
RestClient restClient = RestClient.builder().requestFactory(new HttpComponentsClientHttpRequestFactory()).build();
```

I guess here the difference is that the `JdkClientHttpRequestFactory` is selected by default, whereas `RestTemplate` was using the `SimpleClientHttpRequestFactory` (which is using Java's `HttpURLConnection`). If you believe the behavior is invalid, please raise an issue to OpenJDK.

Thanks!

**Comment by bclozel** [comment]
Thanks for your comment @nhmarujo , I guess I got lost in the discussion around `HttpHeaders`, which now has its own issue with #32660.

**Comment by nhmarujo** [comment]
You're welcome @bclozel and thank you for reopening the issue. Do you have any view on the matter? 🙂

**Comment by bclozel** [comment]
@nhmarujo it's fixed now in 6.1.7-SNAPSHOTs and it will be released with next month's maintenance release. Thanks for your report!

**Comment by nhmarujo** [comment]
Thank you so much @bclozel !

**Comment by Mario-Eis** [comment]
This broke our whole system and we will not be able to upgrade spring from now on. Because our central NoSql database system expects a content-length set, even when there is no body present. Thats a critical issue for us right now.

**Comment by bclozel** [comment]
After discussing this more in-depth, the team decided to reconsider this issue and maybe revert this change.
See #32678 for more details.

@nhmarujo Can you elaborate on your use case? Is the server a well-known web server? Is this a custom implementation that is setting this header?
Also, the error message is a bit strange `HTTP Error 411. The request must be chunked or have a content length`. [This error code says the opposite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411): the server requires a "Transfer-Encoding" or "Content-Length" header. Here, setting "Content-Length: 0" is somehow raising this error but not when it's missing?

@Mario-Eis Thanks for your feedback. This means you have tested this change in production or in a testing environment? Can you share the name of the database product and the error that's raised?

**Comment by nhmarujo** [comment]
Hi @bclozel. Hard for me to say exactly what the provider is using, but looking at our access logs I don't see the header `Server: "cloudflare"` on the response for that failed request. I also see another header `Report-To: "{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=eSJjE3hVNEyXU9lMO9i9pFeNrJSSSMZ2KQSSl0ksgIdJIKygolfg5vUTdoprUUkd8GYFw7vJScF4fzt5blewS6s4fBFqBiL2BqLafUKe7Qrl%2BOZV4itD2V0wtFum2HamY6L%2FQ6JCntYvBA%3D%3D"}],"group":"cf-nel","max_age":604800}"`.

Hard to say much more.

**Comment by bclozel** [comment]
While the discussion around "no message body / empty message body" is relevant to the RFC, it seems that most clients send this "Content-Length: 0" request header for POST requests and that we're not in a position to consistently make the difference between those cases at the Framework level.

On top of that, the use case reported here is contradictory: the server complains about a missing "Content-Length" header when it's actually present. After discussing with the team, we're going to revert this change.

**Comment by bclozel** [comment]
Reverted in 64b0283.
