### ISSUE TITLE
Extend org.springframework.core.task.VirtualThreadTaskExecutor with support for TaskDecorator.

### ISSUE THREAD

**Issue by MihajloRa** [spring-projects/spring-framework#32688]
Hello, as of v6.1.6 there is not support for TaskDecorator on the VirtualThreadTaskExecutor class. This would be a useful inclusion and would allow for an easier transition from ThreadPoolTaskExecutor with a custom TaskDecorator to a VirtualThreadTaskExecutor. Is this extension planned as of now and are there any reasons for it not being implemented initially? Or am I free to open a PR with this inclusion as it is quite a straight forward addition.

**Comment by jhoeller** [comment]
The rationale is that `VirtualThreadTaskExecutor` should remain as lean as possible, without any customization options other than thread naming based on core Java policies.

For any Spring-style customization options (including Spring-style thread naming), we rather recommend `SimpleAsyncTaskExecutor` with `setVirtualThreads(true)` plus `setTaskDecorator`, `setConcurrencyLimit` etc.

Is there any reason you would need to stick with `VirtualThreadTaskExecutor` over `SimpleAsyncTaskExecutor` in general?

**Comment by jhoeller** [comment]
The `VirtualThreadTaskExecutor` javadoc points to `SimpleAsyncTaskExecutor` for those purposes already, so I don't see a need to document this further. Closing this issue on that basis.
