### ISSUE TITLE
Provide an example of custom request URL with RestClient in the reference guide

### ISSUE THREAD

**Issue by wosiwq** [spring-projects/spring-framework#32685]
**Affects:** 6.1.3

I'm currently working with the Spring RestClient and I'm curious about the best practice for performing a GET request with parameters. While it's straightforward to perform a basic GET request, I couldn't find clear documentation or examples regarding how to include parameters in the request.

Could someone please provide guidance or an example of how to properly perform a GET request with parameters using the Spring RestClient? It would be immensely helpful for understanding the best practices and ensuring compatibility with various API endpoints.

Thank you in advance for your assistance!

**Comment by snicoll** [comment]
The [Request URL section](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#_request_url) of the doc introduces this concept. It provides a link to [a more dedicated section](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-uri-building.html).

This [SO question](https://stackoverflow.com/questions/77592651/how-to-send-request-parameters-withe-the-new-spring-boot-3-2-restclient) provides an example. 

That all being said, I agree the doc could be a bit more explicit here, perhaps with a small example?

**Comment by wosiwq** [comment]
Thank you for your prompt response and the helpful information! I appreciate the clarification on where to find the concept of including parameters in the Request URL section of the documentation and the link to the SO question for an example.
﻿
I completely agree that the documentation could benefit from a more explicit example to better illustrate this concept for users like myself. Would it be possible to consider adding a small example in the documentation for clarity?
