### ISSUE TITLE
add support for request body in HTTP DELETE methods using RestClient

### ISSUE THREAD

**Issue by peter-ponzel** [spring-projects/spring-framework#32693]
Hello,

currently the RestClient is not supporting request bodies in DELETE requests which is very limiting - especially in cases where additional data beyond URL parameters are needed - such as [Remove Roles from Organization Members](https://auth0.com/docs/manage-users/organizations/configure-organizations/remove-member-roles) from Auth0.

Are there any plans to support this in upcoming releases ?

Best regards,
Peter

**Comment by quaff** [comment]
https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5
>> A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

Delete with payload is allowed but not recommended.

**Comment by snicoll** [comment]
> this is unfortunately not possible at the moment - which is why I have made a request here

Have you tried `restClient.method(HttpMethod.DELETE).body()`? 

> in my opinion it should be up to the consumer who makes the request to decide in what way he makes a request and then let a server decide how to respond to it

That's quite a one-side view of things IMO. Having the spec not recommending this in such a term is a certainly a valid reason for us not exposing a first-class concept for this. Does `method` help?

**Comment by peter-ponzel** [comment]
> Having the spec not recommending this in such terms is a certainly a valid reason for us not exposing a first-class concept for this

this was also mentioned from quaff before ... what makes you come to this conclusion ?
taking the quote from the RFC
> A payload within a DELETE request message has no defined semantics;
sending a payload body on a DELETE request might cause some existing
implementations to reject the request.

 I don't see anything saying that it's not recommended

> Have you tried restClient.method(HttpMethod.DELETE).body()?

now I have and thank you this one works :+1:
