### ISSUE TITLE
Questions about gemini support in the spring ai module

### ISSUE THREAD

**Issue by yangfeng20** [spring-projects/spring-framework#32700]
I want to use the gemini apiKey to access my gemini Ai instead of using project-id+location.

Currently, the spring ai module using gemini only supports project-id+location using google cloud.
The apiKey mode in Google ai studio is not supported.

My request was to support the apiKey pattern, similar to openai.

**Comment by jhoeller** [comment]
I suppose you meant to raise this with the Spring AI project: https://github.com/spring-projects/spring-ai/issues
