### ISSUE TITLE
Exclude static resources in InterceptorRegistration in Spring MVC

### ISSUE THREAD

**Issue by jakubkrolikowski** [spring-projects/spring-framework#32758]
I use the "HandlerInterceptor" to set some attributes to "request" at the invocation of each controller and check the URL parameters. I would like to easily exclude this interceptor from all static resources. For various reasons (including the migration of the application from another framework), I have static resources placed in several folders.

Currently I have to do it this way:

```java
@Configuration
public class WebAppConfigExample implements WebMvcConfigurer {

  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/packed/**","/app/img/**","/app/css/**");
  }
  
  @Override
  public void addInterceptors(InterceptorRegistry registry) {
    InterceptorRegistration r = registry.addInterceptor(new HandlerInterceptor() {
      public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
         request.setAttribute("some_specific_attribute", "value");
         if (request.getParameter("param") != null) {
           // do something
         }
         // other operations on request, 
         // or response.sendRedirect is some cases
         return true;
      }
    });
    r.addPathPatterns("/**");

    //  Here "excludeStaticResources" method would be very helpful!
    r.excludePathPatterns("/packed/**","/app/img/**","/app/css/**");
        
  }

}
```

It would be very useful to have an `excludeStaticResources()` or `excludeResource()` method in `InterceptorRegistration`, so that I don't have to repeat the list of folders with static resources.
Or the `includeControllersOnly` method, which would set the Interceptor exclusively for MVC Spring controllers.

**Comment by aditya78910** [comment]
can i try contribute?

**Comment by aditya78910** [comment]
I was exploring how we can provide an an option to a developer to configure a HandlerInterceptor only for RestControllers. One way, this can be achieved is by checking the type of the handler (whether it is RestController annotated).

The option to configure this can be added in the InterceptorRegistration and then we can add the related mappedinterceptor to the handlerexecutionchain accordingly depending on the handler being ( RestController annotated). We can do this by introducing a check in the MappedInterceptor [here](https://github.com/aditya78910/spring-framework/blob/b9ae996dfc93a0c886179e0bae1bb5f6e5de85b7/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/MappedInterceptor.java#L211)

Requesting the esteemed advice and feedback from the spring team if this thinking is in logical direction.

**Comment by bclozel** [comment]
I have looked into this topic and think that the current solution described in the original post is quite good.
In this case, you would like to ignore `ResourceHttpRequestHandler`, but there are other implementations of `WebContentGenerator` or handlers producing RSS, sitemap documents, etc - that still might qualify as ignored by your interceptor.

I think that excluding by path patterns makes a lot of sense here, as we can't check against all possible implementations here.
