### ISSUE TITLE
Broken "Try This Tutorial" link on the https://spring.io/cloud page

### ISSUE THREAD

**Issue by GlennInDC** [spring-projects/spring-framework#32762]
On the https://spring.io/cloud page, the "Try This Tutorial" link, which references https://spring.io/2019/10/15/simple-event-driven-microservices-with-spring-cloud-stream, returns an error 404.

**Comment by snicoll** [comment]
Thanks for the report but this is the wrong issue tracker to report this. Admittedly, I don't really know how to report that to the Spring Cloud team either, I've created https://github.com/spring-cloud/spring-cloud-commons/issues/1353
