### ISSUE TITLE
Document ControllerAdviceBean as internal usage

### ISSUE THREAD

**Issue by sinanoezdemir** [spring-projects/spring-framework#32776]
### Enhancement/ Misleading description in javadoc. 

In the Javadoc of `ControllerAdviceBean` you can read 

> Encapsulates information about an @ControllerAdvice Spring-managed bean without necessarily requiring it to be instantiated.
The findAnnotatedBeans(ApplicationContext) method can be used to discover such beans. **However, a ControllerAdviceBean may be created from any object, including ones without an @ControllerAdvice annotation.**

[ControllerAdviceBean](https://github.com/spring-projects/spring-framework/blob/168276aaab14456cfcc1b0bd440a26e0682f8f90/spring-web/src/main/java/org/springframework/web/method/ControllerAdviceBean.java#L47)

Reading this I assume, that it should be possible to create ControllerAdviceBeans and register them programmatically (without using the `@ControllerAdvice` annotation).

As far as I understood the [ExceptionHandlerExceptionResolver](https://github.com/spring-projects/spring-framework/blob/168276aaab14456cfcc1b0bd440a26e0682f8f90/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ExceptionHandlerExceptionResolver.java#L78) is the class keeping the ControllerAdviceBeans to apply matching ExceptionHandlers when an exception occurs. 

However, when [initialising the exceptionHandlerAdviceCache](https://github.com/spring-projects/spring-framework/blob/168276aaab14456cfcc1b0bd440a26e0682f8f90/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ExceptionHandlerExceptionResolver.java#L302) it uses ControllerAdviceBean.findAnnotatedBeans which scans the application context for beans annotated with `@ControllerAdvice`. 

The exceptionHandlerAdviceCache is otherwise not modifiable. So there is actually no other way to add ControllerAdviseBeans besides using the annotation.

I think that's why the Javadoc is misleading. 

However, it would be great to have the ability to define ControllerAdviseBeans without using the `@ControllerAdvice` annotation.  

- _Context:_ I am developing in a micro service environment and we have multiple micro services using the same ControllerAdvise which we extracted into a Library. I do not want libraries to contain spring component annotations. I rather would like to instantiate a bean in the configurations of each micro service. With the current implementation it's not possible to "just" remove the annotation and instantiate that bean in a configuration. 

I assumed something similar to this should work.

```java
@Configuration
public class SomeConfiguration {

  @Bean
  public ControllerAdviceBean myControllerAdvice() {
    return new ControllerAdviceBean(new MyControllerAdvice());
  }

}

//Example
public  class MyControllerAdvise {

    @ExceptionHandler({Exception.class})
    public ResponseEntity<Object> handleRemainingExceptions(Exception exception, WebRequest request) {
      // does something
      return ResponseEntity.internalServerError().body("Something went wrong");
    }
    
 }
```

Please excuse me if I misunderstood a concept here. Just trying to suggest an improvement.

**Comment by rishiraj88** [comment]
I agree with you, @sinanoezdemir , about your note on the Javadoc of ControllerAdviceBean (in the beginning of your comment). I, too, find the exact match between your statements and the Javadoc statements. That should be altered.

However, pardon me for not diving deep into your usecase and context of micro services.

**Comment by bclozel** [comment]
Hello @sinanoezdemir , thanks for bringing this up. We have discussed this today as a team and I'll summarize here.

We're not sure if you don't want your shared library to be scanned for components, or if it's scanned by micro-services but you would like to make this bit optional.
1. If you don't want your library to be scanned by mistake, this is a quite common concern. Spring Boot contributes numerous configuration classes that should never be scanned. If an application scans the `org.springframework.boot` namespace, this is considered as an invalid setup. There might be ways to explicitly reject such situations and tell the user.
2. If your library is scanned but you would like to optionally contribute this component, there are many ways to express that with Spring: profiles, conditions, functional registration of beans...

Are your applications using Spring Boot? If so, you could [contribute your own auto-configurations](https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html) and never rely on scanning for your library components. Your classes would still be annotated with `@ControllerAdvice` but could be conditionally contributed to the application context.

Now depending on the outcome of this discussion, we might revisit the `ControllerAdviceBean` javadoc and part of its implementation: this is a public type that needs to be shared for Spring MVC and WebFlux, but it's not meant for public use. As you've found out, non-annotated `@ControllerAdvice` instances are not supported at the moment and we could streamline the current implementation to reflect that as it's only partially there.

**Comment by sinanoezdemir** [comment]
@bclozel thanks for your response. 

I just mentioned this issue because of you sad in your last sentence 

> As you've found out, non-annotated @ControllerAdvice instances are not supported at the moment

In our team we try to avoid relying on component scanning for libraries. Instead we want to manually configure the beans within the services and use the libraries like a blue print for these kind of things. In this case exception handling. 

I have a working workaround but I think it would be great if it would be possible to register ControllerAdvices by annotation and programmatically. Off course I understand that this is probably easier sad then done.

**Comment by bclozel** [comment]
> In our team we try to avoid relying on component scanning for libraries. Instead we want to manually configure the beans within the services and use the libraries like a blue print for these kind of things. In this case exception handling.

Thanks for your response.

> I have a working workaround but I think it would be great if it would be possible to register ControllerAdvices by annotation and programmatically. Off course I understand that this is probably easier sad then done.

I don't think that pointing to a class would really qualify as programmatic registration. This class would still contain `@ExceptionHandler` method and would still be annotated-driven. You could look at how [we handle programmatic registration of mappings for controllers in Spring MVC](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-registration). As you can see, there is no annotation involved here anymore.

> Are your applications using Spring Boot? If so, you could [contribute your own auto-configurations](https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html) and never rely on scanning for your library components. Your classes would still be annotated with @ControllerAdvice but could be conditionally contributed to the application context.

The auto-configuration approach would be more aligned with your vision of programmatic registration in this case. Have you considered this?

**Comment by qzmer1104** [comment]
I have the same concerns。

1、common-spring.jar 
`
@RestControllerAdvice(basePackages="com.a")
class GlobalExceptionHandler {}
`
org.springframework.boot.autoconfigure.AutoConfiguration.imports
`
xxx.xxx.GlobalExceptionHandler
`

2、app-1
app package
`
com.a.xxxxConotroller
`
pom.xml
`
maven import  common-spring.jar 
`

GlobalExceptionHandler is useful

2、app-2
app package
```
com.c.controller
```
pom.xml
`
maven import  common-spring.jar 
`
GlobalExceptionHandler is useless

We may no need to package a new common-spring.jar  just modify the basePackages

**Comment by bclozel** [comment]
@qzmer1104 so you are looking [for something like this](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-registration), but for exception handling?

**Comment by sinanoezdemir** [comment]
Thank you, @bclozel, for your responses.

I agree that @ExceptionHandler and @Configuration would still be necessary, but that is acceptable. My main goal was to avoid relying on component scanning. With the configuration class, you have to register the bean manually, and the library containing the exception handlers does not create beans by itself. We try to avoid the creation of beans within libraries whenever possible.

We also considered auto-configuration, and that approach would work. There are ways to implement a workaround, so that is not the issue. I just thought it would be beneficial if the framework supported this method of declaring controller advices.

**Comment by bclozel** [comment]
We have discussed this as a team and think that conditional configurations or Spring Boot auto-configurations are the preferred way of handling this use case.

We'll repurpose this issue to update the `ControllerAdviceBean` Javadoc to make it obvious that this is for internal use (it's really public because it must be used from different packages). In the process, we should review its constructors and code paths to check whether some of those partially implement this "programmatic registration" feature that we don't intend to support. If we find any, we should deprecate/remove those code paths.

**Comment by antonmos** [comment]
My team is also avoiding ComponentScanning in the core libraries that we are developing, and we would also like to be able to dynamically register ControllerAdvice.

The reason that we are avoid ComponentScanning is that we believer that it easy easier to understand explicitly configured beans grouped in an @Configuration class, rather than using auto-configuration because in a framework library it is difficult  to 1) find all beans that are tagged with any variant of @Component; 2) understand all of the @Conditional variants applied to those complements and how they intersect for a given use case for the library.

**Comment by juriad** [comment]
We upgraded Spring from 6.1 to 6.2 but left springdoc in the original version. That lead to errors:
> java.lang.NoSuchMethodError: 'void org.springframework.web.method.ControllerAdviceBean.(java.lang.Object)'
	at org.springdoc.core.service.GenericResponseService.lambda$getGenericMapResponse$8(GenericResponseService.java:702)

and it was reported a few times: https://github.com/springdoc/springdoc-openapi/issues?q=is%3Aissue%20state%3Aclosed%20ControllerAdviceBean

It is nice that springdoc released a fixed version, but the main issue is here. You consider this class for internal use, but the world did not agree with you (the class was public and there was no hint of it being internal).

> In the process, we should review its constructors and code paths to check whether some of those partially implement this "programmatic registration" feature that we don't intend to support. If we find any, we should deprecate/remove those code paths.

You might have gone through Spring codebase but failed to check all the code out there, some public, some private that depends on Spring.

The design philosophy of Spring is to:
> Maintain strong backward compatibility. Spring’s evolution has been carefully managed to force few breaking changes between versions. Spring supports a carefully chosen range of JDK versions and third-party libraries to facilitate maintenance of applications and libraries that depend on Spring.

(https://docs.spring.io/spring-framework/reference/overview.html#overview-philosophy)
Now, was this breaking change *carefully managed*?

This sheds bad light on Spring as whole. Please be more careful next time.

**Comment by bclozel** [comment]
@juriad noted, thanks for the feedback.
