### ISSUE TITLE
Missing documentation for JSP TagLib spring.tld

### ISSUE THREAD

**Issue by jakubkrolikowski** [spring-projects/spring-framework#32774]
**Affects:** 6.x

---

In the Spring 6 documentation there is no section on TagLib JSP spring.tld.
In the Spring 4 documentation there still was:
https://docs.spring.io/spring-framework/docs/4.1.x/spring-framework-reference/html/spring.tld.html

This taglib still works and can be used in JSP, so in my opinion it should be documented. Especially the "message" tag, which I use quite often in my application.

```jsp
<%@taglib prefix="s" uri="http://www.springframework.org/tags" %>
<s:message code="mes.code"/>
```

Unless it is no longer developed and will be removed? I couldn't find information about that in the documentation either.

**Comment by sbrannen** [comment]
That's correct: the reference manual no longer includes detailed documentation for `spring.tld`.

However, the [Spring’s JSP Tag Library](https://docs.spring.io/spring-framework/reference/web/webmvc-view/mvc-jsp.html#mvc-view-jsp-tags) section of the reference manual provides the following guidelines to acquire further information.

> The `spring.tld` tag library descriptor (TLD) is included in the `spring-webmvc.jar`. For a comprehensive reference on individual tags, browse the [API reference](https://docs.spring.io/spring-framework/docs/6.1.6/javadoc-api/org/springframework/web/servlet/tags/package-summary.html#package.description) or see the tag library description.

For example, Javadoc for the `message` tag can be found [here](https://docs.spring.io/spring-framework/docs/6.1.6/javadoc-api/org/springframework/web/servlet/tags/MessageTag.html).

In light of that, I am closing this issue.
