### ISSUE TITLE
TextWebSocketHandler I think the method name of BinaryWebSocketHandler has changed

### ISSUE THREAD

**Issue by JunggiKim** [spring-projects/spring-framework#32789]
`TextWebSocketHandler` submethods seem to have been renamed to `BinaryWebSocketHandler`.

```java
public class TextWebSocketHandler extends AbstractWebSocketHandler {
	
    @Override
	protected void handleBinaryMessage(WebSocketSession session, BinaryMessage message) {
		try {
			session.close(CloseStatus.NOT_ACCEPTABLE.withReason("Binary messages not supported"));
		}
		catch (IOException ex) {
			// ignore
		}
	}
}
```

```java
public class BinaryWebSocketHandler extends AbstractWebSocketHandler {
	
    @Override
	protected void handleTextMessage(WebSocketSession session, TextMessage message) {
		try {
			session.close(CloseStatus.NOT_ACCEPTABLE.withReason("Text messages not supported"));
		}
		catch (IOException ex) {
			// ignore
		}
	}

}
```

**Comment by JunggiKim** [comment]
If this is the right issue, I would really appreciate it if you could give me a chance to do a pull request!!!

**Comment by sbrannen** [comment]
Hi @JunggiKim,

Congratulations on opening your first issue for the Spring Framework! 👍 

`TextWebSocketHandler` and `BinaryWebSocketHandler` both implement the correct methods to reject binary and text messages, respectively.

If you want to support text messages, you could extend `TextWebSocketHandler` and override the `handleTextMessage` method accordingly. For a concrete example, see `org.springframework.web.socket.sockjs.client.WebSocketTransport.ClientSockJsWebSocketHandler`.

Similarly, if you want to support binary messages, you could extend `BinaryWebSocketHandler` and override the `handleBinaryMessage` method accordingly.

In light of that, I am closing this issue.
