### ISSUE TITLE
Spring cache should support TTL by design

### ISSUE THREAD

**Issue by abccbaandy** [spring-projects/spring-framework#32792]
Without TTL feature, it's hard to use `@Cacheable` in real project.

For ex:
I use redis for cache, and have 3 method:
A method need ttl 1 days
B method need ttl 2 days
C method need ttl 3 days

How can I do that? It's easy with native redis command.

I know the abstraction reason, The design want have a universal cache support by any data store.
https://docs.spring.io/spring-framework/reference/integration/cache/specific-config.html
But it just make it less useful.

And this is common feature, you can see in stackoverflow, people use some ugly way to archive this requirement : 
https://stackoverflow.com/a/44203099/1686407
````java
@CacheEvict(allEntries = true, cacheNames = { "cache_1", "cache_2" })
@Scheduled(fixedDelay = 30000)
public void cacheEvict() {
}
````
Some even drop spring cache, and implement by himself with native data store and AOP.

I think better way is : add this feature, and throw NotSupportedException when the data store don't have TTL support.

Thanks.

**Comment by bclozel** [comment]
Duplicates #32633 and https://github.com/spring-projects/spring-framework/issues/23684 - see the discussions there for more details.

**Comment by abccbaandy** [comment]
Thanks for reply, 
But those links doesn't answer my question.

@bclozel Let's make it simple:
Can you tell me how to do my example with your design?
If not, maybe your design need some improve?

**Comment by valuetodays** [comment]
I think adding ttl to @Cacheable is usefully. 

In situation 1, the cache time is  one hour.
In situation 2, the cache time may differ.

```java
@Cacheable(value = "situation1#1h", cacheManager = "cacheMgr2")
public String situation1() {
}

@Cacheable(value = "situation2#3h",  cacheManager = "cacheMgr2")
public String situation2() {
}
```

There is no dynamic ttl in @Cacheable, so I have to create a new cacheManager and other classes:

- MyRedisCacheManager that extends org.springframework.data.redis.cache.RedisCacheManager
- RedisCache2 that  extends org.springframework.data.redis.cache.RedisCache

```
public class RedisCache2 extends RedisCache {
    private final String nameToUse;
    private final Duration ttlToUse;

    public RedisCache2(String name, RedisCacheWriter cacheWriter, RedisCacheConfiguration cacheConfig) {
        super(name, cacheWriter, cacheConfig);

        String[] arr = name.split("#");
        // example value: key-name#1h or key-name#pt1h or key-name
        if (arr.length == 2) {
            nameToUse = arr[0];
            String ttlStrToUse = arr[1];
            // use dynamic ttl in @Cacheable
            if (!StringUtils.startsWithIgnoreCase(ttlStrToUse, "pt")) {
                ttlStrToUse = "PT" + ttlStrToUse;
            }
            `ttlToUse` = Duration.parse(ttlStrToUse);
        } else {
            nameToUse = name;
            // use ttl in config
            `ttlToUse` = cacheConfig.getTtl();
        }
    }

    @Override
    public void put(Object key, Object value) {
        // skip some code
        // ttlToUse is here
        getNativeCache().put(nameToUse, createAndConvertCacheKey(key), serializeCacheValue(cacheValue), `ttlToUse`);
    }

    @Override
    public ValueWrapper putIfAbsent(Object key, Object value) {
        // skip some code
        // and here
        byte[] result = getNativeCache().putIfAbsent(nameToUse,
            createAndConvertCacheKey(key), serializeCacheValue(cacheValue),
            `ttlToUse`);
        // skip some code
    }
}
```
- a method with @Bean just copy from org.springframework.boot.autoconfigure.cache.RedisCacheConfiguration

But if @Cacheable supports ttl parameter or any other paramter to hold ttl, the above code can be saved. And the final code will be `@Cacheable(value = "situation1", ttl="1h")`. It's clear and readable.
