### ISSUE TITLE
Links to Framework and Servlet Javadoc from Framework's Kotlin API documentation are broken

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#32797]
**Affects:** 6.0.x and 6.1.x.

When the Kotlin API documentation links to types and methods in the Java API those links are broken. For example, https://docs.spring.io/spring-framework/docs/6.0.x/kdoc-api/spring-beans/org.springframework.beans.factory/index.html links to https://docs.spring.io/spring-framework/docs/6.0.x/kdoc-api/spring-beans/org.springframework.beans.factory/-listable-bean-factory/index.html which 404s.

`5.3.x` is not affected where, for example, https://docs.spring.io/spring-framework/docs/5.3.x/kdoc-api/spring-beans/org.springframework.beans.factory/index.html links to https://docs.spring.io/spring-framework/docs/5.3.x/javadoc-api/org/springframework/beans/factory/ListableBeanFactory.html.

We had the same problem in Spring Boot's Kotlin API documentation and fixed it by [configuring the package list URL to point to the element list for the Java API](https://github.com/spring-projects/spring-boot/blob/0934b68c6c234f32fc32c3b5f13f05d55a13a69b/buildSrc/src/main/java/org/springframework/boot/build/KotlinConventions.java#L81). We're using Dokkatoo but perhaps a similar fix is possible with the Dokka Gradle plugin.

**Comment by sbrannen** [comment]
Indeed, when running the `:spring-beans:dokkaHtmlPartial` Gradle task on `6.1.x`, we see the following error.

> Failed to download package-list from https://docs.spring.io/spring-framework/docs/current/javadoc-api/package-list, this might suggest that remote resource is not available, module is empty or dokka output got corrupted

Thanks for reporting this!

I'm looking into it.

**Comment by aSemy** [comment]
Looks like the link has changed:

* https://docs.spring.io/spring-framework/docs/current/javadoc-api/package-list ❌
* https://docs.spring.io/spring-framework/docs/current/javadoc-api/element-list ✅

IIRC the default name changed in a newer Java version.

**Comment by sbrannen** [comment]
@aSemy, we are aware of the changes regarding `package-list` and `element-list`.

Andy in fact already mentioned that in this issue's description.

In light of that, there is no need to repeat that information in the comments.

**Comment by aSemy** [comment]
> @aSemy, we are aware of the changes regarding `package-list` and `element-list`.
> 
> Andy in fact already mentioned that in this issue's description.
> 
> In light of that, there is no need to repeat that information in the comments.

Hi @sbrannen, your moderation doesn't seem to align with [the contribution guidelines](https://github.com/spring-projects/spring-framework/blob/v6.1.6/CONTRIBUTING.md).

> Reporting an issue or making a feature request is a great way to contribute. Your feedback and the conversations that result from it provide a continuous flow of ideas.

**Comment by sbrannen** [comment]
Hi @aSemy,

Thanks for the feedback.

> your moderation doesn't seem to align with [the contribution guidelines](https://github.com/spring-projects/spring-framework/blob/v6.1.6/CONTRIBUTING.md?rgh-link-date=2024-05-12T10%3A46%3A49Z).
> 
> > Reporting an issue or making a feature request is a great way to contribute. Your feedback and the conversations that result from it provide a continuous flow of ideas.

I don't think my moderation conflicts with our contribution guidelines or code of conduct.

Part of our job as maintainers is to hide comments that we feel are outdated, off-topic, or resolved, and that's what I did here.

Hidden comments remain in place and can still be viewed by anyone interested in reading them.

> The original comment does not say that the link has changed. 

That's correct: the original comment does not explicitly state that the link has changed.

But it does state that the Spring Boot team was able to fix the same issue "by configuring the **package list** URL to point to the **element list** for the Java API," and the linked configuration does exactly that -- both of which imply that that the link has changed.

> The information might have been clear to you, but wasn't clear to me. 
> ...
> Rephrasing it and asking relevant question provides a continuous flow of ideas, and helps with others in the future should they come across this issue.

Fair enough. In light of that, I have unhidden your comment so that others can view it without having to click on it.

Cheers,

Sam
