### ISSUE TITLE
ReactorNettyClientResponse should not throw exception if no body is available

### ISSUE THREAD

**Issue by r16turbo** [spring-projects/spring-framework#32805]
Environment: Spring Web 6.1.6, Java 17

The situation is the same as in #31719, which occurs when using Reactor Netty.

The reason is that the following code throws an exception:

https://github.com/spring-projects/spring-framework/blob/v6.1.6/spring-web/src/main/java/org/springframework/http/client/ReactorNettyClientResponse.java#L85

I believe that null should also be returned when using Reactor Netty, please let me know about a better way to implement this.

Thanks

**Comment by r16turbo** [comment]
The server was the cause of the problem, not RestClient.
I'm sorry for all the fuss.

**Comment by r16turbo** [comment]
It seems that the RestClient is still the cause of the problem, so we will reopen.

Example of fix (Java 11 or higher):

```java
	@Override
	public InputStream getBody() throws IOException {
		InputStream body = this.body;
		if (body != null) {
			return body;
		}

		body = this.connection.inbound().receive()
				.aggregate().asInputStream().block(this.readTimeout);
		if (body == null) {
			// throw new IOException("Could not receive body");
			body = InputStream.nullInputStream();
		}
		this.body = body;
		return body;
	}
```

**Comment by bclozel** [comment]
See comment in #32934

**Comment by r16turbo** [comment]
Sorry, I didn't know if reopen or repost was better.
best regards.
