### ISSUE TITLE
Unexpected exception in UriComponentsBuilder with a valid URI.

### ISSUE THREAD

**Issue by victorherraiz** [spring-projects/spring-framework#32815]
Query string parameters with equals in the value throw and exception in build method:

```java
    @Test
    public void equals_in_query_string_value() {
        var str = "https://localhost:8080/callback?param1=a%20b&param2=1=2";
        var uri = URI.create(str);
        var actual = UriComponentsBuilder.fromUri(uri)
            .build(true)
            .toUri();
        assertEquals(uri, actual);
    }
```

Exception:

```
java.lang.IllegalArgumentException: Invalid character '=' for QUERY_PARAM in "1=2"
```

I use `true` because the source is already a valid URI and I do not want a doble escape in the param1.

I did not find anything in any standard or convention that says that this character is forbidden, I tried different implementations and they worked as espected: URLSearchParams  in any browser, node queryparams, etc. 

Expected behaviour:

* Both URIs in the test should be equal.
* No exception should be thrown.
* `param2` equals  `1=2`

References:

* https://www.rfc-editor.org/rfc/rfc3986#section-3.4

URL (Web API) example:

```
new URL('https://localhost:8080/callback?param1=a%20b&param2=1=2').searchParams
URLSearchParams { 'param1' => 'a b', 'param2' => '1=2' }
```

**Comment by poutsma** [comment]
`UriComponentsBuilder` has stricter requirements than `java.net.URI`. Most of these were requested by users, for instance see [here](https://github.com/spring-projects/spring-framework/issues/21577#issuecomment-651725021) for someone who does want to encode `=` characters.

There are ways to bypass the validation, for instance:
```java
var str = "https://localhost:8080/callback?param1=a%20b&param2=1=2";
var uri = URI.create(str);
var uriString = UriComponentsBuilder.fromUri(uri).build().toUriString();
var actual = URI.create(uriString);

assertEquals(uri, actual);
```

**Comment by victorherraiz** [comment]
I have the following use case, the URI that I am calling is a CALLBACK, it sent by third parties. Those URIs (with equals in the value part) are understood and proccessed correctly for Tomcat, Netty, Node.  And valid from the standards point of view.

IMHO there is a diferent between validation and encoding. Not only the characters that you want to encode are valid ones. There are several examples and different recomendations.

I suggest to split the method `public abstract boolean isAllowed(int c);` in the class Type in two. One for validation and another for encoding.
