### ISSUE TITLE
Socket.io support

### ISSUE THREAD

**Issue by blackydev** [spring-projects/spring-framework#32823]
Spring boot provides support for websockets and sockjs. Shouldn't spring boot also give you the option to use the [socket.io](https://socket.io/) protocol, which is very popular?

**Comment by bclozel** [comment]
Not at the moment. Sock.js was mostly here as a fallback when WebSocket aren't possible. These days, we support both WebSocket and https://rsocket.io/ and so far we didn't get requests for this feature. I'm closing this issue for now, as we are not interested in investing in this area right now.

We can reopen this issue if we get significant feedback and requests from the community. Thanks!
