### ISSUE TITLE
`LocalValidatorFactoryBean` does not define or inherit an implementation of the resolved method `forExecutables`

### ISSUE THREAD

**Issue by WuJingLearn** [spring-projects/spring-framework#32844]
Version:spring4.3

Error:
Caused by: java.lang.AbstractMethodError: Receiver class org.springframework.validation.beanvalidation.LocalValidatorFactoryBean does not define or inherit an implementation of the resolved method 'abstract javax.validation.executable.ExecutableValidator forExecutables()' of interface javax.validation.Validator.

q:
After reading the code, it is true that the forExecutables method has not been implemented

Code cannot be upgraded to Spring version

**Comment by snicoll** [comment]
Spring 4.3 is EOL so we can't provide you support on that version. Perhaps you're trying to upgrade to a version that uses Jakarta rather than the old JavaEE package space?

This should be `jakarta.validation.executable.ExecutableValidator forExecutables()` in a recent version.

**Comment by jhoeller** [comment]
Spring Framework 4.3 was based on Bean Validation 1.0 and had optional support for Bean Validation 1.1 method validation. As a consequence, the only way to call the Bean Validation 1.1 `forExecutables()` method was to call `unwrap(Validator.class).forExecutables()` on the Spring-provided `LocalValidatorFactoryBean`. On newer Spring versions, this unwrapping is not necessary anymore.
