### ISSUE TITLE
Spring Framework 6.2.x EOS timeline

### ISSUE THREAD

**Issue by Vasanthakumar-murugan** [spring-projects/spring-framework#32849]
Hi,

Spring Framework 6.2.x EOS is set as 2025-11-14, a **one-year gap** from the release date 2024-11-14 , whereas the other version has a **two-years gap**.

It there any reason for this change. Please let know

Reference : https://spring.io/projects/spring-framework#support

**Comment by bclozel** [comment]
Thanks for letting us know - I've fixed the dates on our website to align with our usual policy. Note, those are provisional dates and are subject to change. We're trying to give as much visibility as we can, even before the version is actually published.
