### ISSUE TITLE
HttpComponentsClientHttpRequestFactory add constructor that takes HttpClient

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-framework#32875]
I'd like

```java
new HttpComponentsClientHttpRequestFactory(HttpClients.custom().disableRedirectHandling().build());
```

instead of
```java
    var rf = new HttpComponentsClientHttpRequestFactory();
    rf.setHttpClient(HttpClients.custom().disableRedirectHandling().build());
```

this would be consistent with `JdkClientHttpRequestFactory`

```java
        new JdkClientHttpRequestFactory(HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).build())
```

honestly, I wish both would just take the builder, although especially in this case to avoid exposure of the auto-closable which IDE's and other quality tools will warn about. That would be inconsistent though.

```java
new HttpComponentsClientHttpRequestFactory(HttpClients.custom().disableRedirectHandling());
```

The goal is to avoid creating a variable, because, why?

**Affects:** 6.1.6

**Comment by snicoll** [comment]
[Uh](https://github.com/spring-projects/spring-framework/blob/39320b904e034bae093da06d4cdf7cb10ff0cb08/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequestFactory.java#L89)?

**Comment by xenoterracide** [comment]
I'm going to go beat myself in the head with a hammer now, sorry for the PEBKAC
