### ISSUE TITLE
Analysis of the Duplicate Calls to addToClassHierarchy in the getClassHierarchy Method

### ISSUE THREAD

**Issue by fu-cheng1** [spring-projects/spring-framework#32906]
Hello, in the implementation of the getClassHierarchy method in GenericConversionService:
`if (Enum.class.isAssignableFrom(type)) {
    addToClassHierarchy(hierarchy.size(), Enum.class, array, hierarchy, visited);
    addToClassHierarchy(hierarchy.size(), Enum.class, false, hierarchy, visited);
    addInterfacesToClassHierarchy(Enum.class, array, hierarchy, visited);
}`
Why is addToClassHierarchy called twice, once with the variable array and once with false? In fact, when this if condition is met, array is always false. What is the significance of calling it twice here? This issue exists in Spring 4.1.x and later versions.

![image](https://github.com/spring-projects/spring-framework/assets/53570033/b7ea721b-fddd-49bd-ade9-02e445fc6e61)

**Comment by jhoeller** [comment]
Good point, that second call is superfluous indeed. We'll simply remove it.

**Comment by fu-cheng1** [comment]
I would like to ask why the Enum.class type needs to be handled separately?
