### ISSUE TITLE
Refine `KotlinDetector.isKotlinType` documentation for Kotlin 2.x lambdas

### ISSUE THREAD

**Issue by antechrestos** [spring-projects/spring-framework#32905]
Using the [spring cloud stream with reactive](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#reactive-functions-support)  used to work well by instanciating kotlin function  as follows

```kotlin
@Configuration(proxyBeanMethods = false)
class MessageConfiguration {

   @Bean
   fun myMessageConsumer() = { rawMessagesFlux ->
            rawMessagesFlux
                .flatMap { // ... }
                .then()
   }
```

Moving to **kotlin 2.0** fails as generated bean class returns `false` when passing it to `KotlinDetector.isKotlinType`. Hence starting of spring cloud stream module fails as `KotlinFunctionWrapper` is not put and the `Configuration` expects java `Function`,  `Consumer` or `Supplier` ...

**Comment by sdeleuze** [comment]
@antechrestos Can you please provide a reproducer as an attached project or a link to a repository?

**Comment by antechrestos** [comment]
@sdeleuze yes: https://github.com/antechrestos/spring-function-kotlin-2.0-bug

**Comment by antechrestos** [comment]
I confirm that the workaround using`@JvmSerializableLambda` makes the trick.

@sdeleuze do you want me to close this PR and let the PR on cloud-function repository be the reference?

**Comment by sdeleuze** [comment]
@antechrestos if I am not mistaken, this is an issue not a PR and I have repurpose it to refine the documentation, so please keep it opened, I will close it with a related commit.
