### ISSUE TITLE
Remove AllEncompassingFormHttpMessageConverter from WebMvcConfigurationSupport

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-framework#32917]
`WebMvcConfigurationSupport` currently includes the `AllEncompassingFormHttpMessageConverter`, see https://github.com/spring-projects/spring-framework/blob/6a8f0d6d7d4379860e0197f321f0784f8b46e5df/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L895. 

Including a form converter on the server side makes no sense, as the servlet environment already provides form support. Effectively, including this converter can result in controllers returning form data, which makes no sense. So, the `AllEncompassingFormHttpMessageConverter` should be removed from `WebMvcConfigurationSupport`.

**Comment by rstoyanchev** [comment]
It's not uncommon I think to access form data through an `@RequestBody` parameter like in [this test](https://github.com/spring-projects/spring-framework/blob/5cd4b87bfac54c4d34aa60397d99f299e2efa513/spring-webmvc/src/test/java/org/springframework/web/servlet/mvc/method/annotation/RequestResponseBodyMethodProcessorTests.java#L814), so I'm not sure we can just exclude `FormHttpMessageConverter` from server configuration. On the writing side, it supports multipart responses and I believe that's also used.

**Comment by poutsma** [comment]
> It's not uncommon to access form data through an `@RequestBody` parameter like in [this test](https://github.com/spring-projects/spring-framework/blob/5cd4b87bfac54c4d34aa60397d99f299e2efa513/spring-webmvc/src/test/java/org/springframework/web/servlet/mvc/method/annotation/RequestResponseBodyMethodProcessorTests.java#L814) I think, so I'm not sure we can just exclude `FormHttpMessageConverter` from server configuration. On the response side, the converter enables writing multipart that I believe is also a valid use case.

Understood. I guess we have no other way out that to revert #32826, as supporting maps will break too many applications. Fortunately there is still #32832, which we can keep.
