### ISSUE TITLE
Exception mapping does not work as expected when plugging in ReactorNettyClientRequestFactory into RestTemplate and RestClient

### ISSUE THREAD

**Issue by helmut-hackl-dynatrace** [spring-projects/spring-framework#32952]
**Affects:** Spring Framework Web 6.1.8

I use the `ReactorNettyClientRequestFactory` within `RestTemplate` and `RestClient`.
`RestTemplate` and `RestClient` take care of mapping `IOException`s to `ResourceAccessException`s.

In case of using the `reactor.netty.http.client.HttpClient`, `ReactorNettyClientRequest`, `ReactorNettyClientResponse` -
`RuntimeException`s like `IllegalStateException` (caused by .`block()` calls), `io.netty.handler.timeout.ReadTimeoutException` etc. bubble thru - up to `RestTemplate` and `RestClient` consumers which should only know the  `RessoureAccessException`s.
So most likely `IOException`s should be thrown in  `ReactorNettyClientRequest`, `ReactorNettyClientResponse` methods.

Furthermore the behaviour is not consistent with other `ClientHttpRequestFactory `implementations 
like `JettyClientHttpRequestFactory`, `OkClientHttpRequestFactory`, ...

**Comment by jhoeller** [comment]
A revision will be available in the upcoming 6.1.9 snapshot, consistently converting to IOExceptions. Feel free to give it an early try!

**Comment by helmut-hackl-dynatrace** [comment]
big thanks! i will give it a try ...

**Comment by helmut-hackl-dynatrace** [comment]
I patched your changes for testing - looks ok. thanks again.

**Comment by helmut-hackl-dynatrace** [comment]
one update:

in
[your fix](https://github.com/spring-projects/spring-framework/commit/e5be10d53defdff5b353a85555104c56d2865d7c)

you throw in `ReactorNettyClientRequest::convertException` - after falling thru - the `IOException` this way:

`return new IOException(ex.getMessage(), cause);`

In case of eg. a  `io.netty.handler.timeout.ReadTimeoutException` both are null - the message plus the cause.
So you loose the connex to `ex` and that it was a timeout that caused the exception.

**Comment by jhoeller** [comment]
Good point! Revised for 6.1.11 in #33080, including the original exception if there is no cause now.
