### ISSUE TITLE
Inconsistent character handling between MockMvc created from a context or standalone

### ISSUE THREAD

**Issue by lukas-krecan** [spring-projects/spring-framework#32997]
**Affects:** 6.2.0-SNAPSHOT

I was playing with the new `MockMvcTest` reusing some of my existing JsonUnit tests. When [executing the test through](https://github.com/lukas-krecan/JsonUnit/blob/master/json-unit-spring/src/test/java/net/javacrumbs/jsonunit/spring/testit/MockMvcTest.java#L74) `mockMvc` JSON content is serialized using UTF-8, [when using MockMvcTest](https://github.com/lukas-krecan/JsonUnit/pull/772/files#diff-9258720f39a0c1e23b9508b5c48c28cf4ea8dddb313ef208f697003b3737d424R15) non-latin characters are garbled. 

Maybe I missed some configuration, but I would expect the default behavior to be the same.

**Comment by snicoll** [comment]
Thanks for the report. That's not the same setup. The former is using a `WebApplicationContext`. The latter is configuring things with only one controller (and without a context at all).

`MockMvcTester` isn't doing anything fancy, it just delegates to the `MockMvc` instance that you'd create yourself otherwise. From that perspective, the report is invalid, that is you'd get the same problem by creating a `MockMvc` instance with just a controller (via `standaloneSetup`).

Having said that, I'd like to investigate a bit more why the default character encoding is different in those two modes.

**Comment by lukas-krecan** [comment]
If I remember correctly, the default for JSON in real controllers is UTF-8.

**Comment by snicoll** [comment]
> If I remember correctly, the default for JSON in real controllers is UTF-8.

No, it does default to `ISO-8859-1` (per spec). I am not sure what you're experiencing to be honest. You can dump the exchange using `andDo(MockMvcResultHandlers.print())` with `MockMvc` and with `apply(MockMvcResultHandlers.print())` with `MockMvcTester`. 

Give that a try and if you have UTF-8 in one and `ISO-8859-1` in the other, please share an isolated sample that demonstrates that. You can attach a zip to this issue or push the code to a GitHub repository.

**Comment by lukas-krecan** [comment]
Which spec are you talking about? For example [here](https://www.ietf.org/rfc/rfc4627.txt) I see

> JSON text SHALL be encoded in Unicode.  The default encoding is
   UTF-8.

**Comment by snicoll** [comment]
The servlet spec. Can you please get back once you've tried what I requested?

> Give that a try and if you have UTF-8 in one and ISO-8859-1 in the other, please share an isolated sample that demonstrates that. You can attach a zip to this issue or push the code to a GitHub repository.

**Comment by lukas-krecan** [comment]
It's even more confusing then I thought. There are two issues.

The one I have reported is caused by [this fix](https://github.com/lukas-krecan/JsonUnit/issues/212) - JsonUnit is using UTF-8 when character encoding is not explicitely specified. When `MockMvcTester` is used, the conversion to string is done by Spring and ISO-8859-1 is used. So you may say that the issue is on JsonUnit side.

But, when I tried reproducing it, I started with a [test based on RestTemplate](https://github.com/lukas-krecan/json-unicode-demo/blob/master/src/test/java/com/example/demo/DemoControllerRestTemplateTest.java) and there UTF-8 is used (due to [this](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/converter/StringHttpMessageConverter.java#L156)). [Test using MockMvc](https://github.com/lukas-krecan/json-unicode-demo/blob/master/src/test/java/com/example/demo/DemoControllerMockMvcTest.java) is using ISO-8859-1. So the inconsistency is between the RestTemplate based code that is assuming UTF-8 (and most likely the real controllers that produce UTF-8 encoded strings) for JSON and MockMvc. 

I have already spend too much time on this, feel free to close it but I still think it's a bug in MockMvc. Your reproducer is [here](https://github.com/lukas-krecan/JsonUnit/issues/212).

**Comment by snicoll** [comment]
FTR, This was closed in the scope of the issue as reported.

**Comment by lukas-krecan** [comment]
Shall I report another ticket, something like "MockMVC defaults to ISO-8859-1 for JSON while the rest of the framework defaults to UTF-8"?
