### ISSUE TITLE
Ambiguity in doc

### ISSUE THREAD

**Issue by lsc4719** [spring-projects/spring-framework#33002]
**Affects:** v6.1.8

Hello, I am reading docs happily. It's fantastic.

I think I found little something to fix.

https://github.com/spring-projects/spring-framework/blob/f85d5bd84a7e7bc810bb5a8179fc2fc130affc89/framework-docs/modules/ROOT/pages/core/beans/annotation-config/autowired-qualifiers.adoc?plain=1#L173

https://github.com/spring-projects/spring-framework/blob/f85d5bd84a7e7bc810bb5a8179fc2fc130affc89/framework-docs/modules/ROOT/pages/core/beans/annotation-config/autowired-qualifiers.adoc?plain=1#L179

`4.3` might be look like an unresolved chapter ref in the [doc](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired-qualifiers.html). But actually it stands for version. 

---

**Comment by sdeleuze** [comment]
"As of 4.3" stands for "As of Spring Framework 4.3". We could put the longer form to make it more obvious if that's unclear, but given the fact 4.3 has been released a long time ago, if we change something I think I would be in favor of modernising that part of the documentation by removing the 4.3 mention. 

Could you please elaborate more on what you mean by "unknown ref"?

**Comment by lsc4719** [comment]
Thank you for your comment.
I thought it was a chapter reference. 🤣
