### ISSUE TITLE
@EnableConfigurationProperties not work as expected when added in parent class

### ISSUE THREAD

**Issue by rujche** [spring-projects/spring-framework#33028]
## Problem brief description

When **@EnableConfigurationProperties** added in parent class, it didn't work as expected in some corner case. 

## Reproduce the problem

 - Here is the **sample project** to reproduce this problem: https://github.com/rujche/problem-reproduce/tree/EnableConfigurationProperties-not-work-well-when-added-in-parent-class . 
 - Please read **README.md** in the **sample project** to get more information.

**Comment by jhoeller** [comment]
This looks like a variant of #28676 which should be fixed in the 6.2 milestones already. Yet another case of "does this work when running against 6.2.0-M4" :-)

**Comment by jhoeller** [comment]
Thanks for the check, Andy. I'll close this issue as a duplicate then.

**Comment by rujche** [comment]
@wilkinsona , @jhoeller 

Thank you for your quick response. Now it's OK to close this issue.
