### ISSUE TITLE
Framework SSE documentation

### ISSUE THREAD

**Issue by krezovic** [spring-projects/spring-framework#33041]
**Affects:** 6.1.9
---

I am aware that Spring Framework supports SSE (Server Sent Events) in Spring WebMvc and Spring WebFlux, but I am unable to find any mention whatsoever in the official documentation. All that Google returns are links to 3rd party sites which may be outdated, and some of them link back to official documentation where SSE documentation was supposed to be or has been at some point.

A nice example would be at least how to use SseEmitter class from spring-web(mvc?) package.

**Comment by bclozel** [comment]
We do have a section about SseEmitter. See https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-ann-async.html#mvc-ann-async-sse

We cannot maintain samples for all features we support unfortunately.
