### ISSUE TITLE
Fail fast if a `@Bean` method declares `@Autowired` as well

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#33051]
Along the lines of #31007 in 6.1, we intend to tighten `@Bean` processing further in 6.2: rejecting an accidental `@Autowired` annotation on a `@Bean` method, following up on #33030.

**Comment by sbrannen** [comment]
This is also similar to what we decided to do on the testing side.

- https://github.com/spring-projects/spring-framework/issues/25966

**Comment by xgwcy** [comment]
niu bi

**Comment by rishiraj88** [comment]
Very nice and to-be-useful enhancement. Thanks for thinking upon and starting it, @jhoeller .
