### ISSUE TITLE
Duplicate observations recorded with RestClient

### ISSUE THREAD

**Issue by MilanSMA** [spring-projects/spring-framework#33068]
Hi,

I'm using spring-boot 3.3.0 (spring-framework 6.1.8). After migration from spring-boot 3.2.5, the metrics are false because the timer for RestClient counts twice the calls (`http.client.request`). 

This can be reproduced with a simple spring boot test:

```java 
@Test
void restClientMetricsBug() {
   // registry and clientBuilder are injected 
   clientBuilder.baseUrl("http://localhost:8080").build().get().retrieve().toEntity(String.class);
   var tm = registry.get("http.client.requests").timer();
   assertEquals(1, tm.count());  // fails with 1 != 2
}
```

The problem seems to be (to my opinion) that Timer.stop is called twice:
- the first time on [DefaultRestClient L230](https://github.com/spring-projects/spring-framework/blob/v6.1.8/spring-web/src/main/java/org/springframework/web/client/DefaultRestClient.java#L230) because `clientResponse` is `AutoClosable` (close stops the observation),
- the second time in `finally` on [L254](https://github.com/spring-projects/spring-framework/blob/f85d5bd84a7e7bc810bb5a8179fc2fc130affc89/spring-web/src/main/java/org/springframework/web/client/DefaultRestClient.java#L254)  (observation.stop is called a second time)  (observation.stop() calls indirectly Timer$Sample.stop()).

I hope my analysis will be helpfull.

Thanks.

**Comment by bclozel** [comment]
Thanks for your report @MilanSMA , this is now fixed in 6.1.10-SNAPSHOT and will be released later today.
