### ISSUE TITLE
Exception for validation failure in WebFlux does not match the documentation

### ISSUE THREAD

**Issue by xinxiong-tw** [spring-projects/spring-framework#33061]
**Affects:** \<Spring Framework 6.1.8 and maybe other versions>

---
I write a simple demo below, I write a Controller with a handler method receiving a post request and consume a valid request body 

```kotlin
@RestController
class Controller {
    @PostMapping("/test")
    fun test(@RequestBody @Valid foo: Foo) {
        println(foo)
    }

    @ExceptionHandler(Exception::class)
    fun handleException(e: Exception) {
        println(e)
    }
}

data class Foo(
    @field:NotEmpty
    val name: String
)
```
Then I send a post request with this body to the application.
```json
{
  "name": ""
}
```
Check out the console and you can see a exception printed and it's type is `WebExchangeBindException`
But according to the spring document [validation](https://docs.spring.io/spring-framework/reference/web/webflux/controller/ann-validation.html), it should throw a `MethodArgumentNotValidException`.
<img width="1099" alt="image" src="https://github.com/spring-projects/spring-framework/assets/56387181/092f2dd6-1b45-4e9d-ba97-b2c066e20495">

I also test this behavior in mvc and it's the expected exception.

**Comment by xinxiong-tw** [comment]
[spring-kotlin-webflux-playground.zip](https://github.com/user-attachments/files/15888146/spring-kotlin-webflux-playground.zip)
Sorry, here is the code in zip.

**Comment by snicoll** [comment]
Thanks. I've reproduced what you've described, we'll look into it.

**Comment by imvtsl** [comment]
Hi @snicoll 
I would like to begin contributing to spring framework. Do you mind assigning this to me?

**Comment by snicoll** [comment]
@imvtsl thanks for the offer but I am not sure yet what we want to do for this. While the issue title makes it sound like a documentation change, it might not be. You can see this by the "waiting-for-triage" label that means the team hasn't really determined the nature of the issue yet.

**Comment by xinxiong-tw** [comment]
@snicoll @imvtsl 

> While the issue title makes it sound like a documentation change
Maybe I didn't make it clean, IMO I would like this exception to be type of MethodArgumentNotValidException. Because in webmvc it's this exception type and align with the doc.

**Comment by snicoll** [comment]
I understood what you reported but I am not sure what we should do. @rstoyanchev should know.

**Comment by rstoyanchev** [comment]
WebExchangeBindException` is the expected exception for WebFlux. It is a `ResponseStatusException` as other exceptions in WebFlux and `BindingResult` is implemented as an interface only. `MethodArgumentNotValidException` on the other hand extends `BindException` and inherits the `BindingResult` implementation. In short, I confirm that it is a documentation issue.
