### ISSUE TITLE
Trace and Span IDs are no longer propagated RequestBodyAdvice beans

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#33091]
Originally raised in https://github.com/spring-projects/spring-boot/issues/41220 (with a reproducer project).

It looks to me like the reason for lack of Trance and Span IDs is the fix for #32730.

If you run the sample with Spring Boot 3.3.0 with a breakpoint in `OncePerRequestFilter.doFilter()` you'll see that the call to`skipDispatch()` return `false`. With Spring Boot 3.3.1 `skipDispatch()` returns `true` because [the `shouldNotFilterAsyncDispatch()` method has been removed](https://github.com/spring-projects/spring-framework/commit/66813948864df711e7cbbfff93406e90bd975d7a#diff-99efb238737ba04cb5175dbf05c5cb2268079dd4e1b4f8857a3f9df376e85838L97-L101).

**Comment by bclozel** [comment]
@syedyusufh just for confirmation, your sample application is named "webflux" but is actually using Spring MVC. Did you mean to use WebFlux instead? In this case, can you try with [`spring.main.web-application-type=servlet`](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.core.spring.main.web-application-type)?

Also, could you elaborate on why you're relying on a trace being present during an asynchronous write? This is outside the scope of the controller handler, quite similar to [spawning a new thread to process the request with Spring MVC async support](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-ann-async.html#mvc-ann-async-deferredresult) (in this case, the threadlocals would not be set there automatically).

I understand that #32730 changes the behavior here, but I'm not sure this was ever intended/supported.

**Comment by syedyusufh** [comment]
Hi @bclozel Our applications have always been Spring Web + Spring WebFlux combined, wherein Tomcat supports the Mono via Async.

This has been working fine for us since Spring Boot 2.5.x atleast and until the new v3.3.1

**Comment by bclozel** [comment]
@syedyusufh ok thanks for confirming - so the "webflux" in your sample is a typo, as it was never the intent to use WebFlux. I'll see if there's a way to support async dispatches again without undoing the previous fix.

**Comment by bclozel** [comment]
[I have a commit ready for this](https://github.com/bclozel/spring-framework/tree/gh-33091) but I'm not in favor of applying it right now for the following reasons:

* the main goal of this filter is to observe the handling of the HTTP request, especially in controllers
* we never guaranteed that observation scopes would be reinstated during async dispatches
* handling ASYNC dispatch types would also mean that the `onScopeOpened` method would be called multiple times (once for REQUEST dispatch, and another time for ASYNC). This is meant to be used to handle HTTP response headers. At the point of ASYNC dispatches, response headers are likely to be read-only.

I do understand that the trace id is not logged anymore for `ResponseBodyAdvice` implementations, but right now I'm leaning towards this being a niche use case, compared to the performance and consistency aspects.

I'm closing this issue for now, but we can always reconsider if we receive more feedback and descriptions of use cases that are not possible anymore.

**Comment by syedyusufh** [comment]
@bclozel TracingContext is lost in `RestControllerAdvice` as well where you define `ExceptionHandler` for logging and throwing user defined exceptions.

Also, `ResponseBodyAdvice` helps customimze the responseBody and definitely any info / failure there needs to be logged along with the original `TraceContext`

Having this been available since atleast `Spring Boot v2.5.x`, kindly reconsider. Thanks

**Comment by bclozel** [comment]
Reopening to check the `@ExceptionHandler` case.
