### ISSUE TITLE
Example in Method Injection section of Spring Framework documentation refers to wrong bean names

### ISSUE THREAD

**Issue by jourteen** [spring-projects/spring-framework#33096]
[Method Injection](https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-method-injection.html) section of Spring Framework documentation contains following XML snippet:

```xml
<!-- commandProcessor uses statefulCommandHelper -->
<bean id="commandManager" class="fiona.apple.CommandManager">
	<lookup-method name="createCommand" bean="myCommand"/>
</bean>
```

Here the XML comment seems to be wrong and should be changed to _'commandManager uses myCommand'_.

**Comment by sbrannen** [comment]
Good catch, @jourteen! 👍 

We'll get that fixed as you've suggested.
