### ISSUE TITLE
CRaC support: Checkpoint failing with CheckpointOpenSocketException

### ISSUE THREAD

**Issue by shanmuk256** [spring-projects/spring-framework#33098]
Trying to create check point in spring boot application but failing with the below error

jdk.crac.impl.CheckpointOpenSocketException: tcp6 localAddr :: localPort 8088 remoteAddr :: remotePort 0
	at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:88)
	at java.base/jdk.crac.Core.checkpointRestore1(Core.java:142)
	at java.base/jdk.crac.Core.checkpointRestore(Core.java:237)
	at java.base/jdk.crac.Core.lambda$checkpointRestoreInternal$3(Core.java:259)
	at java.base/java.lang.Thread.run(Thread.java:833)

I used the spring.context.checkpoint=onRefresh in application.yml file.

jdk : openjdk-17-crac+3_linux-x64
springBootVersion = "3.1.10"

**Comment by sdeleuze** [comment]
You likely need to configure your project to avoid early database connection during the training run, see [related documentation](https://github.com/spring-projects/spring-lifecycle-smoke-tests?tab=readme-ov-file#training-run-configuration). I will send a PR to Spring Boot to make that a bit more discoverable.

**Comment by shanmuk256** [comment]
upgraded to 3.3.0  but no luck.

do you need any details?
