### ISSUE TITLE
Trace and Span IDs are no longer propagated to Spring MVC after Async

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-framework#33110]
Sorry, this is to reopen https://github.com/spring-projects/spring-framework/issues/33091 and bring to your notice that 

`TracingContext` is lost in `RestControllerAdvice` as well where you define `ExceptionHandler` for logging and throwing user defined exceptions.

Also, `ResponseBodyAdvice` helps customize the responseBody and definitely any info / failure there needs to be logged along with the original `TraceContext`

Our implementation is quite similar to what is mentioned in this official documentation page https://docs.spring.io/spring-boot/reference/web/reactive.html#web.reactive.webflux

Having this been available since atleast Spring Boot v2.5.x, kindly reconsider. Thanks

**Comment by bclozel** [comment]
I'll reconsider this in the original issue. No need to create a duplicate one. Other community members are welcome to comment there as well.

**Comment by syedyusufh** [comment]
Thanks @bclozel , sorry for the duplicate issue.
