### ISSUE TITLE
docs.spring.io documentation navigation burger menu wouldn't scroll

### ISSUE THREAD

**Issue by jameshskoh** [spring-projects/spring-framework#33122]
There is a bug on `docs.spring.io`, where content of the top left corner navigation burger menu wouldn't scroll.

Steps to reproduce:
1. Go to one of the documentation pages, e.g. [Spring Framework](https://docs.spring.io/spring-framework/reference/core/beans/introduction.html)
2. Click the documentation content burger menu button at the top left corner
3. Attempt to scroll the expanded menu, and the whole page scrolls instead of the menu.
4. I can only see the content up to `Registering a LoadTimeWeaver`, but when I zoom out, I can see more content below (e.g. `The BeanFactory API`)

While this is a somewhat cosmetic issue, I still hope that the team will be able to fix this! Thank you!

**Comment by simonbasle** [comment]
Thanks for pointing that out. I was able to reproduce this when the sidebar is horizontally collapsed, including in other projects' documentation. This is more likely a bug in spring-io/antora-ui-spring and I will therefore open an issue there.

In the meantime, as a workaround, simply expand the sidebar horizontally by clicking on the chevron at the bottom of the sidebar: 
![image](https://github.com/spring-projects/spring-framework/assets/6986166/57c99622-bbe8-4721-a577-77608a2c83e8)

**Comment by simonbasle** [comment]
@jameshskoh please follow https://github.com/spring-io/antora-ui-spring/issues/261

**Comment by jameshskoh** [comment]
> Thanks for pointing that out. I was able to reproduce this when the sidebar is horizontally collapsed, including in other projects' documentation. This is more likely a bug in https://github.com/spring-io/antora-ui-spring and I will therefore open an issue there.
> 
> In the meantime, as a workaround, simply expand the sidebar horizontally by clicking on the chevron at the bottom of the sidebar: ![image](https://private-user-images.githubusercontent.com/6986166/344588653-57c99622-bbe8-4721-a577-77608a2c83e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mjk0NjIsIm5iZiI6MTcxOTkyOTE2MiwicGF0aCI6Ii82OTg2MTY2LzM0NDU4ODY1My01N2M5OTYyMi1iYmU4LTQ3MjEtYTU3Ny03NzYwOGEyYzgzZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMTQwNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ2NTA4NzIxNmVlN2YyNzQ2NDAyYzFhYjk3ZDU0NWZkMzIyNTc5MTRkNTExMmFjZjEwMjhkNGNlZWQyMDNhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHUS5y_dltZBYVs7kLCuGZz2Bn38s8tAGcL4Cx6_IMw)

Wow! Didn't notice the little chevron there! Thanks!
