### ISSUE TITLE
Allow passing non-generic `HttpMessageConverter` in AssertJ JSON test support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#33131]
As a follow-up of #33118, the following classes should be updated to allow providing a `SmartHttpMessageConverter` as an alternative to current `GenericHttpMessageConverter` arrangement in the following classes:
 - `org.springframework.test.json.AbstractJsonContentAssert`
 - `org.springframework.test.json.AbstractJsonValueAssert`
 - `org.springframework.test.json.JsonContent`
 - `org.springframework.test.web.servlet.assertj.AbstractMockHttpServletResponseAssert`
 - `org.springframework.test.web.servlet.assertj.DefaultMvcTestResult`
 - `org.springframework.test.web.servlet.assertj.MockMvcTester`
 - `org.springframework.test.json.JsonPathValueAssert`
 - `org.springframework.test.web.servlet.assertj.MvcTestResultAssert`
FYI we are considering using this contract for the upcoming Jackson 3 support.

End-users may also provide non-smart non-generic `HttpMessageConverter`, so maybe we should just use `HttpMessageConverter` arguments + `instanceOf` checks to support the 3 variants, check https://github.com/spring-projects/spring-framework/commit/4555384528d2d1870da330ffc9043da7555a4680 for inspiration.

**Comment by snicoll** [comment]
I am working on this to attempt to minimize the code change necessary to support `SmartHttpMessageConverter` as my need do not require the added contract.
