### ISSUE TITLE
Fix typo in integration docs

### ISSUE THREAD

**Issue by Pzz-2021** [spring-projects/spring-framework#33159]
https://github.com/spring-projects/spring-framework/blob/v6.1.10/framework-docs/modules/ROOT/pages/integration/cache/strategies.adoc

中的
This abstraction is materialized by the and interfaces.
应改为
This abstraction is materialized by the interfaces.

**Comment by snicoll** [comment]
@Pzz-2021 I am not sure what you mean. The content of the doc is: 

> This abstraction is materialized by the
org.springframework.cache.Cache and org.springframework.cache.CacheManager interfaces.

I couldn't find the "by the and interfaces" in your comment. If I've missed something, please provide more details.
