### ISSUE TITLE
NPE when trying to access RequestAttributes using RequestContextHolder from another thread

### ISSUE THREAD

**Issue by eugene-sadovsky** [spring-projects/spring-framework#33187]
Hello,

we started to (sometimes) get following exception when trying to read request headers in another thread using `RequestContextHolder`

```java
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.server.Request.getHeaders()" because the return value of "org.eclipse.jetty.ee10.servlet.ServletApiRequest.getRequest()" is null
	at a.b.c.feign.AuthorizationHeaderInterceptor.getAuthorizationHeader(AuthorizationHeaderInterceptor.java:30)
	at a.b.c.feign.AuthorizationHeaderInterceptor.apply(AuthorizationHeaderInterceptor.java:19)
       ...
```
I have described the  issue in good detail [here](https://github.com/jetty/jetty.project/issues/8024#issuecomment-2220038774)

in short, starting from jetty 12.0.1 it now [recycles more internal objects ](https://github.com/jetty/jetty.project/commit/cdf5035ab22f695af3084c5184abbe065c8c77ae#diff-08a987495c36d6ed1f41979826c3e93113157535428e3f9b0887704654001271R449) after request-response has finished, but `org.springframework.web.context.request.RequestAttributes` holds a reference to `org.eclipse.jetty.ee10.servlet.ServletApiRequest`. NPE may happen when request attributes are accessed from another thread

do I need to implement a caching wrapper around the `org.eclipse.jetty.ee10.servlet.ServletApiRequest` so I can access the attributes/headers without interacting with `org.eclipse.jetty.ee10.servlet.ServletApiRequest` outside the request processing loop?

**Comment by bclozel** [comment]
I'm not sure I understand. The Jetty issue you've linked to claims that request objects are recycled before the async request is completed; as far as I understand, this is a bug as async exchanges can be completed from other threads. You issue description claims that Jetty "now recycles more internal objects after request-response has finished" - in this case, I would argue that you should never access such instances once the async request is completed and you should expect such behavior.

Are you completing the async request from within this wrapped Runnable?

**Comment by eugene-sadovsky** [comment]
>  you should never access such instances once the async request is completed and you should expect such behavior

I agree, however after looking how spring-cloud-openfeign [propagates request attributes](https://github.com/spring-cloud/spring-cloud-openfeign/blob/7ec374f6a19a69186281e2bce16ca2f2a9566f13/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java#L138), I was under the impression this is supposed to work out of the box, and it does for us with jetty 12.0.0, not saying this is the way go.

Just to be clear, this is what I have

```java
@RestController
public class SomeController {

    @RequestMapping(value = {"/a/b/c"})
    public SomeDTO handleABC(){

	// will run on another thread, will need access to RequestAttributes
	service.runAsync()

        return new SomeDTO();
    };
}
```

`service.runAsync()` is annotated with `@Async` and we use TaskDecorator to propagate RequestAttributes:
```java
import org.springframework.core.task.TaskDecorator;
import org.springframework.web.context.request.RequestAttributes;
import org.springframework.web.context.request.RequestContextHolder;

public class AsyncRequestAttributesPropagator implements TaskDecorator {

    @Override
    public Runnable decorate(Runnable runnable) {
        RequestAttributes parentRequestAttributes = RequestContextHolder.getRequestAttributes();
        return () -> {
            try {
                RequestContextHolder.setRequestAttributes(parentRequestAttributes);
                runnable.run();
            } finally {
                RequestContextHolder.resetRequestAttributes();
            }
        };
    }
```

further down the line, `runAsync()` tries to access request headers (inside feign interceptor for another outbound request) and fails, because now jetty nulls
`_request = _servletContextRequest = null;` upon recycle. Looks like prior to 12.0.1 this was working "by accident", because `_servletContextRequest` was still available. And what's worse, may have even been associated with another request at the time of access (speculation)

My question is then:
1. wouldn't this cause issues for `FeignCircuitBreakerInvocationHandler` in async mode linked above ?
2. what is the recommended way to go about it? In may case I can think of implementing a wrapper around the  original request, something like[ this](https://github.com/spring-projects/spring-framework/blob/bb64e2226605b800d65eb2bfc75d043337a6deae/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/HandlerMappingIntrospector.java#L525) 
and setting new RequestAttributes with it inside my task decorator

p.s. I may have commented on a wrong jetty issue now that I re-read it

**Comment by eugene-sadovsky** [comment]
thank you for the answer 👍🏼
