### ISSUE TITLE
Javadoc not published for new GA and milestone release processes

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#33204]
The Javadoc was not published automatically for the latest 6.1.11 and 6.2.0-M5 releases. #33179 changed our release process to now use GitHub Actions. 

I think our "release" and "release-milestone" processes are not setting the expected properties on the API and schema artifacts, see https://github.com/spring-projects/spring-framework/blob/c93598835c13cdd0de9ead24581a69c22865c818/.github/workflows/build-and-deploy-snapshot.yml#L35-L38.

**Comment by snicoll** [comment]
I did miss that the artifact properties have to copied in two places now. We configure the deploy task for the snapshot workflow and for the staging workflow.
