### ISSUE TITLE
WebFlux non-streaming JSON array response is flushed after every value

### ISSUE THREAD

**Issue by 0xabadea** [spring-projects/spring-framework#33224]
We have an endpoint like this:

```
@GetMapping(path = "/api/v1/stuff", produces = { APPLICATION_JSON_VALUE })
public Flux<Stuff> getStuff() {
```

In our use case this endpoint can return tens of thousands of values. In production we see that all responses are
flushed often, most of the time after each value is written. These values can be quite small, so flushing after each results in many small packets, which is wasteful due to TCP/IP bookkeeping and a poor use of the connection bandwidth.

This is not a streaming use case. The way the code is written implies that flushing after each value is not intentional: `ReactorServerHttpResponse.writeWithInternal` is called, as opposed to `writeAndFlushWithInternal`.

I was not able to reproduce the behavior by simply returning the values from memory. I could only reproduce when streaming data from the database, in our case PostgreSQL. I'm attaching a simple demo project, which on my machine reproduces the flushing consistently. Start the application and run

```
curl http://localhost:8080/api/v1/stuff
```

[demo-flush.zip](https://github.com/user-attachments/files/16262238/demo-flush.zip)

Spring Boot version: 3.3.1

**Comment by sdeleuze** [comment]
Thanks for the repro, in your use case `ReactorServerHttpResponse.writeWithInternal` is indeed invoked as expected which invokes `NettyOutbound#send` with a flushing predicate set to false.

Could you please share more on how you identify that flushing happen after each element returned by a `Flux`, is it by debugging at Netty level, network level, etc?

**Comment by 0xabadea** [comment]
By looking at the network traffic. Attaching two capture files:

* [flush-spring-3.3.1.pcapng.gz](https://github.com/user-attachments/files/16266187/flush-spring-3.3.1.pcapng.gz) shows the behavior in Spring Boot 3.3.1 -- many small packets.
* [flush-spring-2.7.3.pcapng.gz](https://github.com/user-attachments/files/16266192/flush-spring-2.7.3.pcapng.gz) shows the behavior in Spring Boot 2.7.3 -- packets ~32K in size. I'm adding this just to show what I consider to be the right behavior. The implementation in 2.7.3 was different: it collected the flux into a list and Jackson-encoded the whole list.

**Comment by sdeleuze** [comment]
@violetagg @rstoyanchev Is it expected that Reactor Netty flushes on every element for the following use case?
> `ReactorServerHttpResponse.writeWithInternal` is indeed invoked as expected which invokes `NettyOutbound#send` with a flushing predicate set to `false`.

**Comment by violetagg** [comment]
@0xabadea Please enable `wiretap` and provide the logs (see how to do it below). We do try to combine the messsages and to flush on batches but it depends from the `Publisher`. We work with prefetch value `128`, which means we will try to request `128` items and to flush them with one batch. However if your `Publisher` produces only 1 by 1, we cannot do anything. But let's see what we will see from `wiretap`.

```
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> httpServer.wiretap(true));
    }
}
```

**Comment by 0xabadea** [comment]
Attaching the wiretap logs.

@violetagg, could you please advice? How do you suggest I should change the publisher to publish in a more effective manner than 1 by 1? Eventually, `onNext` is still going to be called for each individual value, so my understanding is that `MonoSendMany`should buffer several values before flushing.

**Comment by violetagg** [comment]
@0xabadea In the provided logs, I can see, that sometimes we flush many `writes`, sometime only one, and it is exactly how the implementation in Reactor Netty is done (async flushes that flush whatever was collected in the outbound buffer)
If this is not enough, then either apply the @rstoyanchev recommendation or consider to add to the Reactor Netty pipeline https://netty.io/4.1/api/io/netty/handler/flush/FlushConsolidationHandler.html
We cannot add this handler by default because it requires configuration that only the owner of the solution can decide.

**Comment by 0xabadea** [comment]
Thank you for the pointer to `FlushConsolidationHandler`. I gave it a try, but it made no difference. This is how I'm adding it to the pipeline:

```
@Component
public class MyNettyWebServerCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {

    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer ->
                httpServer.doOnConnection(conn -> conn.addHandlerFirst(new FlushConsolidationHandler(500, true)))
        );
    }
}
```

I tried both `true` and `false` for the `consolidateWhenNoReadInProgress` parameter, but that didn't make a difference either.

**Comment by 0xabadea** [comment]
@violetagg Indeed, at least the reproducer uses HTTP/1.1. I have followed your yesterday's suggestion, but unfortunately I got the same behavior of many small flushes.

**Comment by violetagg** [comment]
@0xabadea Then I will need some example project to play with it.

**Comment by 0xabadea** [comment]
An example project is attached to the original description. The only change I made to it is adding

```
@Component
public class MyNettyWebServerCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {

    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer ->
                httpServer.doOnConnection(conn -> conn.channel().pipeline().addBefore(NettyPipeline.HttpCodec, "some-name", new FlushConsolidationHandler(500, true)))
        );
    }
}
```

**Comment by violetagg** [comment]
@0xabadea Yeah you are right - in your case `FlushConsolidationHandler` uses the same strategy as Reactor Netty, but you can take a look at it and change it to some custom `FlushConsolidationHandler`.

**Comment by snicoll** [comment]
I am going to close this now as this is out of scope of this project. Thanks @violetagg for following up.
