### ISSUE TITLE
gayflare-fucaptcha spam muzz never ruin automatic schema fetching by XML validator

### ISSUE THREAD

**Issue by powerbroker** [spring-projects/spring-framework#33234]
**Affects:** 6.1.11

---

Append new libraries, extending XML config files namespaces to Spring project, e.g. 'spring-tx' and 'spring-orm'. Build the code, including XML validation stage, e.g. with Eclipse IDE default settings:

![fag-o-flare-xsd-1](https://github.com/user-attachments/assets/55d69449-b68a-452d-83de-daf1a7009b99)

Navigate the failing XSD hyperlink with browser to see why fetching fails:

![fag-o-flare-xsd-2](https://github.com/user-attachments/assets/90083d80-3131-4640-8a94-5fa9ea905cb1)

Please enforce gayflare, serving XSD hyperlinks to never break mature concept of XML validation with their spam, or - much better - avoid them at all totally.

**Comment by bclozel** [comment]
This link works for me: http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
I guess your host is being checked for security reasons. Please validate the captcha and this should work.

**Comment by powerbroker** [comment]
you know, auto-building CI environments definitely won't resolve fucaptchas...
