### ISSUE TITLE
Hibernate Search Bytecode Enhancement Issue

### ISSUE THREAD

**Issue by aiden-sim** [spring-projects/spring-framework#33255]
I reported the following issue to the Hibernate team: https://hibernate.atlassian.net/browse/HSEARCH-5205

```
org.hibernate.engine.spi.EnhancedEntity.isAssignableFrom(Parent.class) is false (Parent wasn't enhanced)
org.hibernate.engine.spi.EnhancedEntity.isAssignableFrom(Child.class) is true (was enhanced).
```

The response I received was that this is an issue that occurs before Hibernate ORM is initialized.

Here is the address of my personal repository that reproduces the issue, and I hope it will be fixed if it is a bug.
Please check it out 
https://github.com/aiden-sim/hibernate-search-bytecode-issue

**Comment by aiden-sim** [comment]
I have posted a new message on the Spring Boot Issues. It is okay to delete this post.

**Comment by bclozel** [comment]
@aiden-sim no need to create duplicates issues. This one was moved here on purpose.

**Comment by aiden-sim** [comment]
@snicoll 

```java
@Entity
@NoArgsConstructor
@Getter
@Setter
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "type")
@Table(name = "sample")
@Configurable
@Indexed
public abstract class Parent extends DomainBase<Long> {
    @Column(nullable = false, length = 50)
    @NotNull
    @GenericField(projectable = Projectable.YES, sortable = Sortable.YES, searchable = Searchable.YES)
    private String name;

    @Transient
    @JsonIgnore
    @Autowired
    @Expose(serialize = false, deserialize = false)
    protected transient ParentDetailService parentDetailService;

    public ParentDetail getParentDetails() {
        return parentDetailService.getParentDetail(getId());
    }

}
```

Thank you for your response.

Currently, in the Parent class, it is being used to directly invoke services like ParentDetailService. This is a piece of legacy code that has been carried forward to the present.

Regarding the part that I have reported, is it a bug, or are we using it improperly?

**Comment by snicoll** [comment]
> Regarding the part that I have reported, is it a bug, or are we using it improperly?

Using LTW with an entity the way you do is strongly discouraged as it can be quite fragile as we see here. It's not obvious to us why this used to work, but both Hibernate and Spring trying to enhance the same class is a recipe for trouble.

Please move that code outside of the entity. If you really can't, it would be nice to get some additional details such if the order between the Hibernate enhancer and the `Configurable` aspect changed between the versions.

**Comment by aiden-sim** [comment]
@snicoll 

removing @Configurable doesn't change the situation.
Instead, if I remove spring-instrument-6.1.10.jar at the LoadTimeWeaving stage, it works. I suspect that there is a conflict occurring when using Hibernate Search and spring-instrument together. Is there anything else I can check?

**Comment by snicoll** [comment]
> removing `@Configurable` doesn't change the situation.

What's left that requires LTW then?

**Comment by aiden-sim** [comment]
> > removing `@Configurable` doesn't change the situation.
> 
> What's left that requires LTW then?

We are also using LTW (Load-Time Weaving) to address self-invocation issues...

**Comment by snicoll** [comment]
I mean in the example that you’ve shared.

**Comment by aiden-sim** [comment]
@snicoll 
It seems that using `@Configurable` in domain is not related to the issue. 
Instead, using `spring-instrument` library for Hibernate Search feature and LTW like `@Indexed` in domain causes bytecode conflict. 
our team decided to remove LTW approach. 
I hope you share it if it's resolved later. 
Thanks.
