### ISSUE TITLE
UserCredentialsConnectionFactoryAdapter should provide credentials to createContext

### ISSUE THREAD

**Issue by TheCycoONE** [spring-projects/spring-framework#33270]
Since org.springframework.jms.connection.UserCredentialsConnectionFactoryAdapter exposes JMS 2.0 methods it should be extended to provide the same credential passing to createContext as it does for createConnection and other methods.

Currently is is surprising that createContext does not work, resulting in missing credentials.

**Comment by snicoll** [comment]
Thanks for the suggestion, this will be available in `6.2.0-SNAPSHOT` shortly.
