### ISSUE TITLE
WebClientResponseException.getMessage has changed to assume status code is not null

### ISSUE THREAD

**Issue by mikehalmamoj** [spring-projects/spring-framework#33287]
**Affects:** \6.1.11
---
This [commit](https://github.com/spring-projects/spring-framework/commit/06d267f04eb03ef1336d0cb937ea6f4ca0d42c50)
 to improve the message for WebClientResponseException has broken some of our unit tests with setup that look like this:
```
doThrow(WebClientResponseException.BadGateway::class)
        .whenever(someService).someMethod(anyString())
```
The exception thrown by Mockito is "hollow" in that it has no status code or any other details:
![image](https://github.com/user-attachments/assets/1d6cd19f-8d0f-4f67-b3b0-1d92bffc2196)

So the test fails with `Cannot invoke "org.springframework.http.HttpStatusCode.is1xxInformational()" because "this.statusCode" is null`.

I guess the question is - is it fair to assume that WebClientResponseException has a status code? If so this code is fine and I'll need to ask Mockito to fix or find a workaround. If there are genuine reasons for having a null status code then you might need to add some null checks?

**Comment by Tree4Free** [comment]
You can also pass an instance of an exception to the doThrow method, so something like:

```java
Exception e = new WebClientResponseException.BadGateway();
e.setStatusCode(...);
doThrow(e).whenever ...;
```
(I did not check if the `BadGateway` exception has such a setter but I hope you get the idea)

**Comment by snicoll** [comment]
> is it fair to assume that WebClientResponseException has a status code?

Yes. 

> If so this code is fine and I'll need to ask Mockito to fix or find a workaround. 

Your code isn't IMO. There's really no reason to mock the exception in the case above. @Tree4Free provided an example.

**Comment by NicoStrecker** [comment]
I would also have prefered a if check before the statuscode so the tests would still work

**Comment by mikehalmamoj** [comment]
@NicoStrecker If you look at how WebClientResponseException is constructed (with a factory method including the status) then I think it's a fair assumption that every one has a status code.

I think the real problem is that on `doThrow(Class clazz)` Mockito uses reflection to create an instance of the Class - this means you're not testing the real method of constructing the class, so the test is almost meaningless. Therefore the workaround suggested above is the best way to use `doThrow` and if anything Mockito should only accept real exceptions and avoid reflection in this case.
