### ISSUE TITLE
Field shadowMatchCache of AspectJExpressionPointcut Occupied a large amount of memory

### ISSUE THREAD

**Issue by MrWanglu** [spring-projects/spring-framework#33289]
Hello developer, in our production practice, I found that the attribute shadowMatchCache of AspectJExpressionPointcut occupies a large amount of memory. We have more than 20 facets, and each facet will save an object shadowMatchCache, which is a map type. Each map object occupies nearly 8M of memory, totaling about 150M of memory. This causes us to experience memory overflow when setting lower memory. Please see the following figure

![image](https://github.com/user-attachments/assets/78f6b319-541b-4f98-8c46-a50369a170d8)
Thank you for helping me figure out how to reasonably avoid this issue. I see that Spring 6 has already fixed this problem. In the AspectJAwareAdvisorAutoProxyCreator class, I released it through reflection when calling the afterSingletonsIntitated method. However, when I started my project, I ran out of memory before I could clear it. I don't have a better solution now, and I hope to get your help. Thank you

**Comment by MrWanglu** [comment]
my spring version is 5.3.31, 
sorry My mistake! 
the "facet" I means that is aspect[@Aspect], our project has 22 aspects, 
I  saw this issue which you sent to me，but when  i start my project，OutOfMemory before I clear the shadowMatchCache

**Comment by MrWanglu** [comment]
I clear shadowMatchCache in afterSingletonsInstantiated method, But the memory overflowed before it was cleared

**Comment by snicoll** [comment]
> but when i start my project，OutOfMemory before I clear the shadowMatchCache

It's unclear why you think the shadow cache is responsible for this. Spring 6 didn't fix anything if the shadow cache is the component that's preventing your app to start. How did you come to that conclusion? Can you run your app with more memory? How much memory does the app can use at the moment?

**Comment by MrWanglu** [comment]
Thank you for your reply. After thinking about it, I realized that this is not a problem with the framework. I raised this issue because I wanted to save memory as much as possible. Thank you for your patient reply, and I will close this issue

**Comment by dijkstral** [comment]
@MrWanglu hi guys, I think you tried to use MAT to analysis memory leak, right? I may have same issue like yours. 
So can you share your final solution since the aspect was not the root cause. 
Appreciate!

**Comment by MrWanglu** [comment]
I referred to this issue：


Clear AspectJExpressionPointcut cache when it is no longer used · Issue #12334 · spring-projects/spring-framework


You can take a look




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spring-projects/spring-framework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年4月21日(星期一) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spring-projects/spring-framework] Field shadowMatchCache of AspectJExpressionPointcut Occupied a large amount of memory (Issue #33289)



   
@MrWanglu hi, I think you tried to use MAT to analysis memory leak, right? I may have same issue like yours.
 So can you share your final solution since the aspect was not the root cause.
 Appreciate!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  dijkstral left a comment (spring-projects/spring-framework#33289)
 
@MrWanglu hi, I think you tried to use MAT to analysis memory leak, right? I may have same issue like yours.
 So can you share your final solution since the aspect was not the root cause.
 Appreciate!

**Comment by dijkstral** [comment]
> I referred to this issue：
> 
> 
> Clear AspectJExpressionPointcut cache when it is no longer used · Issue [#12334](https://github.com/spring-projects/spring-framework/issues/12334) · spring-projects/spring-framework
> 
> 
> You can take a look
> […](#)

hi buddy, thanks for your reply. 

I check the issue [#12334](https://github.com/spring-projects/spring-framework/issues/12334) you sent to me, and seems the solution is to `upgrading to Spring Framework 6.2` ?  Is there any other solution without upgrade the Spring version?

Thanks again!

**Comment by MrWanglu** [comment]
You can access the following link in the world. According to the code, it means clearing a portion of the cache at a certain stage
Clear AspectJExpressionPointcut cache when it is no longer used · Issue #12334 · spring-projects/spring-framework



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spring-projects/spring-framework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年4月23日(星期三) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spring-projects/spring-framework] Field shadowMatchCache of AspectJExpressionPointcut Occupied a large amount of memory (Issue #33289)



    
I referred to this issue：
 
Clear AspectJExpressionPointcut cache when it is no longer used · Issue #12334 · spring-projects/spring-framework
 
You can take a look
 …
  
hi buddy, thanks for your reply.
 
I check the issue #12334 you sent to me, and seems the solution is to upgrading to Spring Framework 6.2 ?  Is there any other solution without upgrade the Spring version?
 
Thanks again!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  dijkstral left a comment (spring-projects/spring-framework#33289)
  
I referred to this issue：
 
Clear AspectJExpressionPointcut cache when it is no longer used · Issue #12334 · spring-projects/spring-framework
 
You can take a look
 …
  
hi buddy, thanks for your reply.
 
I check the issue #12334 you sent to me, and seems the solution is to upgrading to Spring Framework 6.2 ?  Is there any other solution without upgrade the Spring version?
 
Thanks again!
