### ISSUE TITLE
Support Passing Objects to RestClient interceptor similar to Retrofits @Tag with Http Interfaces

### ISSUE THREAD

**Issue by KrishnaST** [spring-projects/spring-framework#33284]
Implement feature to pass Objects to interceptor similar to retrofit's Tag annotation.

![image](https://github.com/user-attachments/assets/4d264472-eb4f-48dd-9e59-40c7d04c7b15)

![image](https://github.com/user-attachments/assets/bf859e22-084d-4fd9-bc4a-5eea2855b97a)

**Comment by bclozel** [comment]
duplicates #32027
