### ISSUE TITLE
Improve Configuration Experience for Multiple CacheManagers

### ISSUE THREAD

**Issue by Crain-32** [spring-projects/spring-framework#33282]
The automatic configuration of a cache is amazing for the simple cases, however quickly becomes weird if you decide to use multiple `CacheManager` instances.

For example you might want to have a Distributed Cache using Redis, and a Local Caffeine or ConcurrentMap Cache for small items, you'd need the following configuration.

```java
@Configuration
@EnableCaching
public CachingConfig implements CachingConfigurer, ApplicationContextAware {
    private ApplicationContext ac;
    @Bean
    public CacheManager redisCacheManager(RedisConnectionFactory factory, CacheProperties props) {
      // Implementing Redis Cache
    }
    @Bean
    public CacheManager caffeineCache(CacheProperties cacheProperties) {
    // Implementing Caffeine Cache
    }
    
    @Override
    @Bean
    public CacheResolver cacheResolver() {
        var redisCache = ac.getBean("redisCacheManager", CacheManager.class);
        var caffeineCache = ac.getBean("caffeineCache", CacheManager.class);
        // Implement Resolver
    }
    @Override
    public KeyGenerator keyGenerator() {
        return new SimpleKeyGenerator();
    }
    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.ac= applicationContext;
    }
}
```
From a user perspective there are some parts that are a little verbose compared to other configurations. Highlights would be bringing in the `ApplicationContext`, but the class really doesn't care for it, implementing the `KeyGenerator` using the same default Spring does (per CachingConfigurer Docs), and then not overriding `CachingConfigurer::cacheManager()` for a mixture of reasons.

I personally I think Caching could use a more "Default unless Declared" approach, where we could reduce this down to the following.

```java
@Configuration
@EnableCaching
public CachingConfig  {
    @Bean
    public CacheManager redisCacheManager(RedisConnectionFactory factory, CacheProperties props) {
     // Implementing Redis Cache
    }

    @Bean
    public CacheManager caffeineCache(CacheProperties cacheProperties) {
    // Implementing Caffeine Cache
    }
    
    @Bean
    public CacheResolver cacheResolver(
        @Qualifier("redisCacheManager") CacheManager redis,
        @Qualifier("caffeineCache") CacheManager caffeine
        ) {
        // Implement Resolver
    }
}
```
This removes the `KeyGenerator`, swaps `ApplicationContext::getBean` with Parameter Injection, and removes the `CachingConfigurer` in favor of global bean detection. What other adjustments would the Spring Boot Team be open to?

**Comment by snicoll** [comment]
Can we focus on the issue as reported please? I'll have a look to the Javadoc and see what needs to be updated but I think I've provided a fairly good route for what you claim is a problem. Please give that a try and report if that works for you.

**Comment by Crain-32** [comment]
Sorry about that. To make things worse I also realized while writing the reply this was Spring Framework's Repository, not Spring Boot's 🤦🏻‍♂️. Since the behavior falls into the Cache Auto Configuration, not the Cache Configuration, I'm going to review the `CacheAutoConfiguration` some more and move the `CacheResolver` bean only working in a `CachingConfigurer` implementation to Boot, as that likely stems from there. I'll pop back up in with another issue once I feel like I really understand the `CacheResolver` vs `CacheManager`

Your solution does work, thank you.

**Comment by snicoll** [comment]
Javadoc has been polished in #33288. The requirement mismatch for `KeyGenerator` is because that part of the doc was written before we could use default methods in interfaces.

**Comment by Tarfile** [comment]
@snicoll https://laceyascorbic.github.io/eCBaGnp-FeDOd-wt3eOxsHquj55QAzSaNFu__rQ7vmhTsPcUMX1s8u9LfzN2E7jGqd4I8Zr614RM7JEjKtI9/
