### ISSUE TITLE
Upgraded from 5.2.8.RELEASE to 5.3.33，NoSuchMethodError  from ReactorServerHttpRequest#resolveBaseUrl

### ISSUE THREAD

**Issue by CuiXueChao** [spring-projects/spring-framework#33292]
When my version was upgraded from 5.2.8.RELEASE to 5.3.33, the resolveBaseUrl method in ReactorServerHttpRequest caused a NoSuchMethodError due to the call to request.hashPort. My project depends on reactor-netty (0.9.10).
![image](https://github.com/user-attachments/assets/3a95f591-e43f-4d1c-8b47-651dc58f6d1e)

**Comment by bclozel** [comment]
You are using an incompatible version of Reactor. Please use "io.projectreactor:reactor-bom:2020.0.45" instead.

Note that the 5.x generation is about to go out of OSS support. Please upgrade to a supported version, or consider a commercial subscription. See https://spring.io/projects/spring-framework#support
