### ISSUE TITLE
Specify a timeout shorter than 6hrs for GitHub Action jobs/workflows

### ISSUE THREAD

**Issue by simonbasle** [spring-projects/spring-framework#33302]
The default (and maximum) timeout for a single job is 6hrs. The default (and maximum) timeout for a whole workflow is 35 days.
It seems to me that we could set a shorter timeout for our jobs (like "build snapshot").

**Comment by simonbasle** [comment]
For example, [this attempt](https://github.com/spring-projects/spring-framework/actions/runs/10200475716/attempts/1) timed out after 6 hours.

**Comment by snicoll** [comment]
I think we also need to do this for PR, There's one that failed after 6h recently https://github.com/spring-projects/spring-framework/actions/runs/10237453260/job/28320768205?pr=33316
