### ISSUE TITLE
Race condition in HeaderWriterFilter when returning StreamingResponseBody in Spring MVC

### ISSUE THREAD

**Issue by chschu** [spring-projects/spring-framework#33304]
**Affects:** 6.0.x, 6.1.x (list is not exhaustive) 

When using `HeaderWriterFilter` and controller methods that return `StreamingResponseBody`, headers may be set twice.

The following two things happen in parallel:

- The asynchronous processing of the `StreamingResponseBody`. If enough data is transferred to the response body, the response is forcefully committed. This causes the `HeaderWriterFilter` to write headers from the asynchronous thread.
- The synchronous execution of the `HeaderWriterFilter`, which will write headers from the request handling thread.

Both threads may successfully pass the `isDisableOnResponseCommitted()` check in `HeaderWriterFilter.HeaderWriterResponse#writeHeaders`, causing the `HeaderWriter`s to be invoked twice. This alone may already cause duplicate headers.

It gets even worse: The implementation of `HttpServletResponse` is not guaranteed to be thread safe according to the [Servlet Spec](https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1#thread-safety).

When using Apache Tomcat, adding headers in parallel causes nasty race conditions (visible as `NullPointerException`s) that (because of garbage avoidance) may permanently break the inner workings of their `org.apache.tomcat.util.http.MimeHeaders` class, leading to strange errors in threads that use recycled response instances.

My current workaround: Write all headers and flush the response in the handler method.

**Comment by snicoll** [comment]
Thanks for the report and the analysis. `HeaderWriterFilter` is part of Spring Security, did you mean to report the issue there? If not, we'd need a small sample that reproduces what you've described. Thanks

**Comment by chschu** [comment]
You're right, I simply didn't notice that `HeaderWriterFilter` is located in Spring Security. I'll report the issue there.

**Comment by chschu** [comment]
Reported as https://github.com/spring-projects/spring-security/issues/15510 with additional information and a reproducer.
