### ISSUE TITLE
A JSON serialization exception can lead to corrupted output being written to the OutputStream of the response.

### ISSUE THREAD

**Issue by light0x00** [spring-projects/spring-framework#33358]
**Affects:** 5.3.31
---

Happening in the phrase of writing object returned by endpoint(controller method)  to the `OutputStream` of response body.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/208bbb0c-aa06-432b-93bc-a1d9dc0e9377">

When the `ObjectWriter#writeValue(JsonGenerator g, Object value)`  throw exception, eg: due to a null key of HashMap:
 
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/d65d8e53-3157-4edb-9fcf-a0f9ce830b7d">

In such case, the`ObjectWriter#close` method will be called( invoke by the try-resources statement), it will write the intermediate corrupted result to the `OutputStream`.

<img width="825" alt="image" src="https://github.com/user-attachments/assets/910e3ec7-890e-4dc7-ade4-73c07e5a8ecb">

Whereafter, the `DispatcherServlet#processDispatchResult` method will trigger `HandlerExceptionResolver`, which will cause a secondary writing.

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/7473b5b8-2659-47c6-acf1-d942e2bb1a47">

Stand in the perspective of the client, a corrupted response they will get.

```
{"success":true,"data":{}}{"success":false}
```

The `{"success":true,"data":{}}` written by `ObjectWriter#close`, and the `{"success":false}` written by `HandlerExceptionResolver`.

**Comment by bclozel** [comment]
This is a known behavior - once the response is written to, there is no strong guarantee that we can reset it to write the payload contributed by error handlers.

We improved this in #31104, but unfortunately we cannot backport this change so late in the 5.3.x generation. Please consider upgrading to a newer version of Spring Framework.
