### ISSUE TITLE
Potential Security Issue: Sensitive Data Logged at DEBUG Level in WebAsyncManager (Spring-web 6.1.5+)

### ISSUE THREAD

**Issue by WolFoxx** [spring-projects/spring-framework#33359]
**Description:**

We have encountered a potential **security issue** in the `org.springframework.web.context.request.async.WebAsyncManager` class using it along with `org.springframework.boot.web.servlet.support.SpringBootServletInitializer` starting from **Spring-web version 6.1.5.+**  The class logs outgoing messages at the DEBUG level, which could lead to sensitive data being exposed in logs.
See: [WebAsyncManager:401](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/[…]/springframework/web/context/request/async/WebAsyncManager.java](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/context/request/async/WebAsyncManager.java#L401))

**Environment:**

- **Spring-web Version**: 6.1.5+
- **SpringBoot Version:** 3.2.7
- **Java Version**: 17
- **Env:** WildFly / JBOSS with standalone.xml

**Issue Details:**

1. **Observed Behavior**:
Since upgrading to Spring-web version 6.1.5, we have noticed that the WebAsyncManager class logs outgoing messages at the DEBUG level. This behavior poses a risk of logging sensitive data, which is a significant concern in production environments

`DEBUG [DefaultDispatcher-worker-10] [  /    ] - Async result set to: <200 OK OK,<sensitiveData></sensitiveData>,[Content-Type:"application/xml"]> for "/ExampleServlet" [org.springframework.web.context.request.async.WebAsyncManager:401] []`

2. **Expected Behavior:**
Sensitive data should not be logged at any log level by default. If DEBUG level logging is necessary, it should be configurable to exclude sensitive information or to disable specific log statements.

**Steps to Reproduce:**

1. Upgrade to Spring-web version 6.1.5 or later.
2. Run an application that uses the `WebAsyncManager` along with `org.springframework.boot.web.servlet.support.SpringBootServletInitializer`
bean.
3. Enable root DEBUG level logging.
4. Observe that outgoing messages, potentially containing sensitive data, are logged.

**Workarounds Attempted:**
- Downgrade "spring-web" to 6.1.4 and lower - WORKS but vulnerabillites are present

**Comment by bclozel** [comment]
As explained in our issue template, we do not discuss potential security issues publicly. See https://spring.io/security
