### ISSUE TITLE
Allow avoiding lower-casing host/domain in UrlParser

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-projects/spring-framework#33360]
In some of the Spring Cloud scenarios, we expect the users to place serviceId instead of actual host/domain, and then we use it for load-balancing, getting instances from service registries, resolving contract stubs, etc., and various of these integrations are case-sensitive. Could a way be introduced to skip lower-casing (for example as a temporary solution till the next portfolio major is released)?

**Comment by rstoyanchev** [comment]
This should work out again after #33639.

**Comment by OlgaMaciaszek** [comment]
Thanks @rstoyanchev. Our tests now pass against FW snapshots.
