### ISSUE TITLE
Spring Framework compressed body issues, resulting servers to wait for more packets and blocking(potential DOS attack)

### ISSUE THREAD

**Issue by esrimed** [spring-projects/spring-framework#33367]
**Affects:** \<working in spring5.3.5 but not working in spring6.1.5+( I am using 6.1.5>

---

**Comment by snicoll** [comment]
@esrimed if you intend to submit a potential security thread, please use https://github.com/spring-projects/security-advisories

**Comment by esrimed** [comment]
Dear Stephane,
New to this and i posted in public view. Now I moved this to security
advisory thread. Thanks a lot for your help.
Thx//
Srinivas.
