### ISSUE TITLE
MultipartFile transferTo() copies the previously uploaded file as a new file

### ISSUE THREAD

**Issue by java-Learner-lx** [spring-projects/spring-framework#33396]
This project uses the springframework: spring-web:6.1.4. It uses the MultipartFile transferTo to upload files. However, after a successful upload, it finds an exception when downloading and then returns the files after follow-up. At that time, the A file was uploaded in the ppt format, but the uploaded file was a Word file that was uploaded 6 days ago and was changed to the ppt format. After looking at the code, I found no need to replace the file. Have you ever experienced this situation?

**Comment by sdeleuze** [comment]
Please update the description to english in order to allow us to understand it.

**Comment by java-Learner-lx** [comment]
The project used springframework: spring web: 6.1.4, and uploaded files using MultipartFile transferTo. However, after successfully uploading the files, it was found that the download and opening were abnormal. After following up, a refund was received. At that time, the uploaded file was in PPT format, but the uploaded file was a Word file that was uploaded 6 days ago and was changed to PPT format. After reading the code, no additional file replacement or other processing was done. Have you ever experienced this situation

**Comment by sdeleuze** [comment]
I am not aware of such issue, and we will need a self contained reproducer to be able to do something, otherwise maybe better to close this issue.

**Comment by java-Learner-lx** [comment]
We are currently unable to provide a reproducible scenario

**Comment by bclozel** [comment]
Thanks for letting us know.
