### ISSUE TITLE
Migrating to Spring Boot v2 to v3 and Getting ClassNotFoundException for javax.xml.bind.annotation.XmlElement

### ISSUE THREAD

**Issue by ved-asole** [spring-projects/spring-framework#33419]
While migrating from Spring Boot v2.7.14 to v3.3.2, I'm getting the below error :

### ClassNotFoundException for javax.xml.bind.annotation.XmlElement

To resovle the issue I have to add the below dependency :

```xml
<!--        Additional dependencies after moving from Spring Boot v2 to v3-->
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
```

## Request 

Could you please resolve the issue with the Spring Boot 3 versions of manually adding this dependency in the pom.xml?

**Comment by bclozel** [comment]
Please stop creating duplicates across projects, this is wasting the team's time.
Duplicates spring-projects/spring-boot#41997
