### ISSUE TITLE
Add constant for 'Alt-Svc' to org.springframework.http.HttpHeaders

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-framework#33426]
Please add a constant for [Alt-Svc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc) to `org.springframework.http.HttpHeaders`.

This is useful for HTTP/3 endpoint advertisement.

Maybe useful for Spring Cloud Gateway as well.

**Comment by bclozel** [comment]
Thanks for the proposal, but we try to only add specific methods/attributes only for headers that Spring Framework ships support for. We are trying to keep the numbers of statics down in the `HttpHeaders` class. This header can still be supported out of the box with generic methods.
