### ISSUE TITLE
Is this considered as a bug of the Spring framework?

### ISSUE THREAD

**Issue by xgwcy** [spring-projects/spring-framework#33516]
`@Configuration
  @EnableAsync
  public class AppConfig {
    @Resource
    private AppConfig app ;
    @Async
    public void fn() {}
  }`
When defining an @Async asynchronous method in a configuration class, the program may fail to start normally and throw an exception like the following:
![image](https://github.com/user-attachments/assets/3bda1469-8b0a-45b4-bdae-7d7b5d164881)

**Comment by bclozel** [comment]
No, the error message says it all. If you need further assistance, please create a new question on StackOverflow with a minimal sample showing the problem.
