### ISSUE TITLE
GatewayRouterFunctions throwing for path variable with space throwing  400 bad request error

### ISSUE THREAD

**Issue by susantabehera32** [spring-projects/spring-framework#33510]
When i am sending get request with path variable having space in between throwing 400 bad request error while gateway is trying to routing to the back end server, The path variable is converting into test%25252520susanta and throwing 400 error.

/api/test susanta

http://localhost:19093/test/api/test susanta

spring boot- 3.3.3
org.springframework.cloud - 2023.0.3

i observed this issue after spring boot 3.x migration in using spring cloud gateway. Is  this  a bug in spring clod gateway.

**Comment by bclozel** [comment]
Duplicates #33494

**Comment by susantabehera32** [comment]
This issue is related to path variable not query  param.. I am facing different issue in this case..
