### ISSUE TITLE
HeartbeatTask should update the lastWriteTime value of SessionInfo after sending the heartbeat

### ISSUE THREAD

**Issue by liuhr-ncu** [spring-projects/spring-framework#33534]
![d62d25256635cd00fdc9ef3d26baaad](https://github.com/user-attachments/assets/4e44900d-b467-494e-861a-33726c9c42ed)

**Comment by bclozel** [comment]
If we update this information for heart beats, this makes this information rather useless. The goal is to know when an actual message was sent for the last time.
