### ISSUE TITLE
Cannot invoke "org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(java.sql.SQLException, String)" because the return value of "org.hibernate.resource.transaction.backend.jdbc.internal.JdbcIsolationDelegate.sqlExceptionHelper()" is null

### ISSUE THREAD

**Issue by Harisankar-Panigrahi** [spring-projects/spring-framework#33540]
**Affects:** \<Spring Framework version>

---

**Comment by Rojojun** [comment]
Actually, no one can know how to solve the problem without details!

I guess you should check your application.properties or yaml file of property firtst

**Comment by sdeleuze** [comment]
We indeed can't do anything with such report, I will reopen it if a complete valid reproducer is provided.
