### ISSUE TITLE
spring session 

### ISSUE THREAD

**Issue by MiMonkey** [spring-projects/spring-framework#33600]
**Affects:** \<Spring Framework version>

---

Gateway generated sessionId，but not send set-cookie to client/response
![image](https://github.com/user-attachments/assets/48e5c709-4836-44a0-811c-126e5589d5f1)

**Comment by bclozel** [comment]
Thanks for getting in touch, but we don't think that this issue is actionable on our side. Rather than a vague title and a screenshot, please provide a detailed description of the problem and a minimal application showing the problem. We can reopen this issue when this is provided.
