### ISSUE TITLE
Upgrade to Kotlin 2.x and set a new related baseline

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#33629]
Spring Framework 7 will use Kotlin 2.x as a new baseline, TBD if we use 2.0, 2.1, 2.2 or 2.3 as the minimal version supported, this kind of decision could be driven by #21546 requirements.

Kotlin Serialization and Kotlin Coroutines should be upgraded accordingly, related upgrade issue will be created when it is clearer what version we will use.

**Comment by bcmedeiros** [comment]
Do we know the earliest Spring Boot public release that will contain this issue and the expected timeline for it?

**Comment by sdeleuze** [comment]
Yes, it will be Spring Boot 4.0 that should be available towards in end of 2025 as mentioned in [this announcement](https://spring.io/blog/2024/10/01/from-spring-framework-6-2-to-7-0). That said, it should be possible to use Kotlin 2 with Spring Boot 3 and Spring Framework 6, but you should pay attention to dependency management.

**Comment by silviuburceadev** [comment]
We are using Kotlin 2 with SB 3.4 without any issues.
