### ISSUE TITLE
CODE_OF_CONDUCT references return 404

### ISSUE THREAD

**Issue by fedpet** [spring-projects/spring-framework#33663]
References to this file point to https://github.com/spring-projects/spring-framework/blob/main/CODE_OF_CONDUCT.adoc which returns 404

[Example](https://github.com/spring-projects/spring-framework/blob/main/CONTRIBUTING.md#code-of-conduct)

**Comment by bclozel** [comment]
Indeed, this is set to the entire org now, there is a dedicated tab for this: https://github.com/spring-projects/spring-framework/?tab=coc-ov-file

We should update that link.
