### ISSUE TITLE
Upcoming release of webjars-locator-lite

### ISSUE THREAD

**Issue by dodgex** [spring-projects/spring-framework#33693]
With the deprecation of support for `webjars-locator-core` in Spring Framework 6.2 (havent found a confirmation) and Spring Boot 3.4 (as of https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4.0-M1-Release-Notes), I wonder what the chances are to get the (hopefully soon) upcoming release of `webjars-locator-lite` into 6.2 / 3.4.

Currently there is a PR https://github.com/webjars/webjars-locator-lite/pull/15 ([related issue](https://github.com/webjars/webjars-locator-lite/issues/13)) open to add the ability to use custom webjars and even old (officiall unsupported) bower based webjars with `webjars-locator-lite` by providing a `META-INF/webjars/locator.properties` mapping a webjar name to a version.

While this reintroduces some classpath scanning that you guys [tried to get rid of by switching to the lite locator](https://github.com/spring-projects/spring-framework/issues/27619), but I think the overhead should be way less than in the previous locator.

While it is not strictly necessary to get the upgraded version directly from the upcoming release, it could make migrating to the new locator possible (without overriding the dependency version) for projects using bower (should be able to switch to non-bower variants) or custom webjars (would need to change the groupId to one of the [two supported](https://github.com/webjars/webjars-locator-lite/blob/main/src/main/java/org/webjars/WebJarVersionLocator.java#L25-L26) by `webjar-locator-lite`).

I have no Idea on when the PR is going to be merged, although the current feedback seems positive, or when it is going to be release and with which version number. So this is primarily asking for the overall chance and possible deadlines for a release of the webjars locator to get into the upcoming Spring Versions.

Thanks in advance!

**Comment by bclozel** [comment]
Milestone dates are public on GitHub, for example the upcoming RC2 is scheduled this week: https://github.com/spring-projects/spring-framework/milestone/380

If those changes are merely internal and don't change the API, then it's mostly a dependency management concern and Spring Boot will pick up automatically the new version when it's out. Let's figure things out when this PR is merged and we know what this means for the Spring integration.

Thanks!
