### ISSUE TITLE
ExchangeFilterFunction are applied in reverse order when chained with `andThen`

### ISSUE THREAD

**Issue by sruthigunti** [spring-projects/spring-framework#33700]
Configured `ExchangeFilterFunction` using `andThen` and expected them to be applied in the order provided. That is first handled for bad request, then retried and then handled for any other status codes. However any expection including 400 is handled by `handleUnexpectedStatus()` filter only.
[WebClientExchangeFilter.zip](https://github.com/user-attachments/files/17363696/WebClientExchangeFilter.zip)

```
    @Bean
    public ExchangeFilterFunction webClientFilterChain() {
        return handleBadRequest()
                .andThen(retry())
                .andThen(handleUnexpectedStatus());
    }
```

**Comment by sdeleuze** [comment]
@sruthigunti As far as I can tell, this new archive still only contains 2 Java files like the initial attached file in the description. In my previous comment, I was asking you a self contained reproducer (full project including the Maven or Gradle build). Please provide that if you want us to have a deeper look.

**Comment by sdeleuze** [comment]
What happens is that request processors (created with `ExchangeFilterFunction#ofRequestProcessor`) are applied in the order they are defined and response processors (created with `ExchangeFilterFunction#ofResponseProcessor`) in the reverse order, I think by design and as expected.
