### ISSUE TITLE
Verify static resource location ends on slash

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#33712]
A location that does not end on "/" does not actually work as intended, which is probably why it hasn't been reported as an issue. We should append the slash where we can, e.g. String location values, and assert `Resource` locations.

**Comment by cagliostro92** [comment]
> A location that does not end on "/" does not actually work as intended, which is probably why it hasn't been reported as an issue. **We should append the slash where we can, e.g. String location values**, and assert `Resource` locations.

@rstoyanchev I know this is already closed, but I'm wondering why actual code doesn't try at all to append a slash, but it simply throws an exception if not already present.
