### ISSUE TITLE
Load-time weaving support for WildFly 24+

### ISSUE THREAD

**Issue by mkoskin** [spring-projects/spring-framework#33728]
Support for wildfly delegating transformer is broken since wildfly-core 19 https://github.com/wildfly/wildfly-core/commit/c0d775692adbed37724d6f4ce22a6dc900c0e69d

Spring class org.springframework.instrument.classloading.jboss.JBossLoadTimeWeaver expects to load class  org.jboss.as.server.deployment.module.DelegatingClassFileTransformer. However, this class has been renamed to org.jboss.as.server.deployment.module.DelegatingClassTransformer in wildfly-server 19.0.0. Also, the DelegatingClassTransformer doesn't implement java.lang.instrument.ClassFileTransformer any more. Instead, it implements org.jboss.modules.ClassTransformer.

**Comment by jhoeller** [comment]
I've added conditional support for WildFly 24+ to `JBossLoadTimeWeaver`. This will be available in the upcoming 6.1.15 and 6.2.0 snapshots; feel free to give it an early try. Note that this has not been tested in an actual WildFly deployment yet, so any such test would be highly appreciated.

**Comment by mkoskin** [comment]
I tested this with 6.1.15 snapshot together with WildFly 31.0.1.Final and EclipseLink 4.0.4 with load time weaving enabled. This combination is now working correctly. Thank you!

**Comment by jhoeller** [comment]
Good to hear! Thanks for the immediate feedback.
