### ISSUE TITLE
Drop `JettyHttpHandlerAdapter` in favor of `JettyCoreHttpHandlerAdapter` / `ServletHttpHandlerAdapter`

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#33747]
Our new `JettyCoreHttpHandlerAdapter` for Jetty 12 supersedes the Servlet bridge for Jetty in general. That aside, as of Servlet 6.1, there is `ByteBuffer` support in `ServletInputStream`/`ServletOutputStream` out of the box; a Jetty-specific subclass of `ServletHttpHandlerAdapter` won't be necessary for that purpose anymore.

**Comment by bclozel** [comment]
Done in 3b65506c13f18535e2fb055fd790bf45e

**Comment by philwebb** [comment]
Just a quick note that https://github.com/spring-projects/spring-framework/blob/main/framework-docs/modules/ROOT/pages/web/webflux/reactive-spring.adoc still mentions the handler
