### ISSUE TITLE
Add micrometer instrumentation for transactions to spring-tx

### ISSUE THREAD

**Issue by edudar** [spring-projects/spring-framework#33751]
With the migration from Spring Cloud Sleuth to Micrometer Tracing, the direction was to move instrumentation support to [respective projects](https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#instrumentations). Looking through the code, it doesn't look like support for transactions has been migrated to spring-tx.

The original tx support in Sleuth: https://github.com/spring-cloud/spring-cloud-sleuth/tree/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/tx that supports imperative and reactive transaction managers.

**Comment by bclozel** [comment]
This was considered and declined in https://github.com/spring-projects/spring-framework/pull/28156#issuecomment-1882648708
