### ISSUE TITLE
Will this merge request about AsyncRequestNotUsableException be added to the milestone of 6.1.x？

### ISSUE THREAD

**Issue by hw207165** [spring-projects/spring-framework#33757]
Will this merge request be added to the milestone of 6.1.x？

https://github.com/spring-projects/spring-framework/commit/dbc69284c8ff8a1bcd11d0116299b56710cf301f#diff-2561f5cef97c1c92815616fd4e3df4f38b8bb92e6e2b0c3c366ebc601b768bd6R51

**Comment by snicoll** [comment]
No. We don't do delayed backport so if it's not scheduled when it's closed, it's not meant to be. You can also see a `@since` on the commit you've shared that confirms it's 6.2 only https://github.com/spring-projects/spring-framework/commit/dbc69284c8ff8a1bcd11d0116299b56710cf301f
