### ISSUE TITLE
Code snippet rendering issue in reference documentation

### ISSUE THREAD

**Issue by bohni** [spring-projects/spring-framework#33760]
https://github.com/spring-projects/spring-framework/blob/ac5c8adb9830939e2329f1e16727c522a172c7c8/framework-docs/modules/ROOT/pages/web/webmvc/mvc-controller/ann-requestmapping.adoc?plain=1#L122

This line in the docs is not rendered correctly.
In this case passthrough should be marked with double plus signs, because the plus sign of the regex is interpreted as the end of the inline passthrough.

* `++"/projects/{project:[a-z]+}/versions"++`

double plus ist documented on https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/

**Comment by Torres-09** [comment]
Hi! If this issue is still open, I would like to work on it. Thanks!

**Comment by bclozel** [comment]
I've assigned the issue to you @Torres-09 !

**Comment by bclozel** [comment]
Superseded by #33766
