### ISSUE TITLE
Remove APIs marked as deprecated for removal

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#33809]
## Overview

In 7.0, we should aim to remove all classes, methods, and features marked as deprecated for removal (as of 6.2.0 in November 2024).

Any remaining deprecations (or new post-6.2.0 deprecations) are expected to stay around for 7.0.x at least.

## Related Issues

- #28761

**Comment by learnconcept** [comment]
Can you assign to me
