### ISSUE TITLE
Fix XML bean reference example in reference manual

### ISSUE THREAD

**Issue by kumaraman528** [spring-projects/spring-framework#33855]
[spring-framework.pdf](https://github.com/user-attachments/files/17653727/spring-framework.pdf)

Page : 32 (33)

In the equivalent code snippet for idref element property is wrongly set using the value attribute. Instead it should be set using ref attribute.

Context:

```xml
<bean id="theTargetBean" class="..."/>
<bean id="theClientBean" class="...">
  <property name="targetName">
    <idref bean="theTargetBean"/>
  </property>
</bean>
```

Existing code:

```xml
<bean id="theTargetBean" class="..." />
<bean id="client" class="...">
    <property name="targetName" value="theTargetBean"/>
</bean>
```

Proposed Code:

```xml
<bean id="theTargetBean" class="..." />
<bean id="client" class="...">
   <property name="targetName" ref="theTargetBean"/>
</bean>
```

**Comment by sbrannen** [comment]
Hi @kumaraman528,

Good catch, and congratulations on submitting your first GitHub issue ever! 👍 

I've fixed the example in `6.1.x` and `main`.

Cheers,

Sam

**Comment by kumaraman528** [comment]
Thankyou @sbrannen

**Comment by vikozyr** [comment]
Hi @sbrannen,

I believe this change is incorrect. `idref` is used to pass the bean's ID as a string value. The updated snippet uses the `ref` attribute, which passes the bean instance itself. Therefore, the new snippet is semantically different and not equivalent to the `idref` version.

I could be missing something, so please correct me if that’s the case.

Kind regards,
Vitalii Kozyr

**Comment by sbrannen** [comment]
Hi @vikozyr,

Indeed, you are correct, and I've created #35560 to address this.

Thank you for bringing this to my attention! 👍
