### ISSUE TITLE
DefaultClientRequestObservationConvention generates uri tag with incorrect value for a URL of format 'https://server'

### ISSUE THREAD

**Issue by jourteen** [spring-projects/spring-framework#33863]
When RestTemplate accesses a URL of format 'https://server' generated http client requests metrics get uri tag of value '/https:\/\/server'. I expect correct uri tag's value to be '/'. 

A demo application [demo.zip](https://github.com/user-attachments/files/17684924/demo.zip) is attached. Run it, then check http client requests metrics at http://localhost:8080/actuator/prometheus.

**Comment by bclozel** [comment]
Closing in favor of #33867
