### ISSUE TITLE
Resources link points to wrong section of reference guide

### ISSUE THREAD

**Issue by yeoleobun** [spring-projects/spring-framework#33882]
I think there is a false link at https://github.com/spring-projects/spring-framework/blob/ac5c8adb9830939e2329f1e16727c522a172c7c8/framework-docs/modules/ROOT/pages/core/beans/context-introduction.adoc?plain=1#L886
which link `Resources` to WebFlux WebClient configuration. but the context is "Spring's `Resource` abstraction" , xref:core/resources.adoc#resources-introduction will be more appropriate.

**Comment by sbrannen** [comment]
Hi @yeoleobun,

Congratulations on opening your first issue for the Spring Framework! 👍 

You're correct: that does link to the incorrect "Resources" section.

We'll fix it.

Cheers,

Sam
