### ISSUE TITLE
Update UndertowHttpHandlerAdapter to dispatch

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#33885]
As per the discussion under https://issues.redhat.com/browse/UNDERTOW-2512, `UndertowHttpHandlerAdapter` needs to start async handling explicitly by calling dispatch.

**Comment by philwebb** [comment]
Will this one be backported?

**Comment by simonbasle** [comment]
The plan is to backport it to 6.1.x at some point indeed. We want to be a tiny bit more cautious with upgrading the Undertow baseline in the existing 6.1.x line, and delaying the backport could be an opportunity to gather feedback on the change from 6.2.
