### ISSUE TITLE
DefaultListableBeanFactory.registerBeanDefinition() does not respect isPrimary()

### ISSUE THREAD

**Issue by ayeracaris** [spring-projects/spring-framework#33926]
6.1.13

**Comment by bclozel** [comment]
This is not a valid bug report.
We can reopen this if you provide a clear description of the problem.

If you need some help to define the problem, you will find some useful explanations here: https://github.com/spring-projects/spring-boot/wiki/How-To-Get-Help#defining-the-problem

**Comment by ayeracaris** [comment]
Sorry. What more information do you need? What is not clear?

It's pretty unreasonable for you to close this without actually looking at it.
