### ISSUE TITLE
@Value cases SpringCGLIB$$0 required a bean of type java.lang.String that could not be found in Native compile when migrating to SB 3.4

### ISSUE THREAD

**Issue by mshima** [spring-projects/spring-framework#33960]
Seems to be an incomplete fix to https://github.com/spring-projects/spring-framework/issues/33030.

Workaround is to use [proxyBeanMethods = false ](https://github.com/spring-projects/spring-framework/issues/33030#issuecomment-2172072420).

```
@Configuration
public class LoggingConfiguration {
    public LoggingConfiguration(@Value("${spring.application.name}") String appName, @Value("${server.port}") String serverPort) {}
}
```

**Comment by snicoll** [comment]
Thanks for the report. I tried to reproduce based on the example you've shared and I am getting a different error with Spring Framework `6.2.1-SNAPSHOT`.
