### ISSUE TITLE
Some links in 6.2 release notes point to 6.2-SNAPSHOT documentation

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-framework#33983]
Perhaps this is on purpose, in that case please just close the issue. Otherwise, I found the following places from https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes that are pointing to the 6.2-SNAPSHOT documentation:

* https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes#support-for-escaping-property-placeholders
* https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes#fragment-rendering
* https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes#url-parsing

**Comment by sbrannen** [comment]
Hi @filiphr,

Good catch!

I fixed 4 links: https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes/_compare/e60a1a0edfc4d0a7f8e035dc61455df5d80db2c3...7b735dadcaa9f5add7e4727d778c2b41b731a888

Cheers,

Sam
