### ISSUE TITLE
`RepositoryEntityController` incompatible with devtools

### ISSUE THREAD

**Issue by muliyul** [spring-projects/spring-framework#33996]
Cannot run application with devtools `org.springframework.boot:spring-boot-devtools`

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryEntityController' defined in class path resource [org/springframework/data/rest/webmvc/RestControllerConfiguration.class]: Could not generate CGLIB subclass of class org.springframework.data.rest.webmvc.RepositoryEntityController: Common causes of this problem include using a final class or a non-visible class

Seems like `RepositoryEntityController` is non-visible (no public modifier).

**Comment by bclozel** [comment]
Please [raise this problem to the Spring data rest project](https://github.com/spring-projects/spring-data-rest/issues).
