### ISSUE TITLE
General upgrade to Jakarta EE 11 APIs

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#34011]

**Comment by m1ngyuan** [comment]
Is it necessary to upgrade the following APIs for Jakarta XML Binding 4.0 as part of Jakarta EE 11? I hope my understanding is correct. Thank you.

> jakarta.xml.bind:jakarta.xml.bind-api:4.0.2
com.sun.xml.bind:jaxb-core:4.0.5
com.sun.xml.bind:jaxb-impl:4.0.5
com.sun.xml.bind:jaxb-xjc:4.0.5
