### ISSUE TITLE
Remove path mapping options marked as deprecated for removal 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#34036]

**Comment by ukpagrace** [comment]
Hi @rstoyanchev if you are not working on this can I pick it up?

**Comment by bclozel** [comment]
@ukpagrace the issue is already assigned, thanks for reaching out!

**Comment by ukpagrace** [comment]
Oh no problem, thought he was one of the maintainers.

**Comment by bclozel** [comment]
@ukpagrace He is, it's just that we prefer community contributions on unassigned issues and especially on ["ideal-for-contribution"](https://github.com/spring-projects/spring-framework/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+ideal-for-contribution%22) issues.

**Comment by ukpagrace** [comment]
This is noted, thank you
