### ISSUE TITLE
OOM due to NoTransactionInContextException in reactive pipeline

### ISSUE THREAD

**Issue by ajax-kovalchuk-d** [spring-projects/spring-framework#34048]
At commit [8e3846991d30a9a577dae9664996c036895f04cc](https://github.com/spring-projects/spring-framework/commit/8e3846991d30a9a577dae9664996c036895f04cc#diff-9af4980fc216d76a02c6acb6e0929df34009dd7b017e8850ff1213fe0b7cc901R41) in the Spring Framework, the NoTransactionInContextException was made a static instance. While this change can reduce overhead in non-reactive contexts, it introduces a potential issue in reactive pipelines: it can cause OutOfMemoryError (OOM) due to suppressed exceptions being accumulated.

In the Reactor Core implementation, as seen in the file [FluxOnAssembly.java](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java), the problem is appears at line 612:

Here, the NoTransactionInContextException is reused statically, and when it is thrown inside a reactive pipeline, it retains references to OnAssemblyException instance. This can lead to suppressed exceptions being stored indefinitely, creating a memory leak.

The behavior can be reproduced with the following Kotlin code:

```
/**
 * Stackless variant of [NoTransactionException] for reactive flows.
 */
private class NoTransactionInContextException : NoTransactionException("No transaction in context") {

    @Synchronized
    override fun fillInStackTrace(): Throwable {
        // Stackless exception
        return this
    }
}

private val NO_TRANSACTION_IN_CONTEXT_EXCEPTION = NoTransactionInContextException()

fun main() {
    repeat(1000) {
        runCatching {
            Flux.fromIterable((1..2))
                .flatMap<Unit> { Mono.error(NO_TRANSACTION_IN_CONTEXT_EXCEPTION) }
                .blockLast()
        }
    }

    System.gc()
}
```
Explanation of the Issue:

 - Each time the static NO_TRANSACTION_IN_CONTEXT_EXCEPTION is thrown within a reactive flow, the OnAssemblyException created by Reactor is added to the suppressed exceptions of NO_TRANSACTION_IN_CONTEXT_EXCEPTION.

- Since the exception is static, it retains all these references, causing memory consumption to grow unbounded.

- This pattern can quickly lead to an OutOfMemoryError, especially in high-throughput reactive applications.

**Comment by sdeleuze** [comment]
Reverted after double-checking with @chemicL that the deferred exception accumulation mechanism is the founding technology for `checkpoint()` for instance, or used in `block()`, so static exception should be avoided with Reactor, as [recently documented](https://github.com/reactor/reactor-core/pull/3944).
