### ISSUE TITLE
NoSuchMethod after upgrading to springboot 3.4

### ISSUE THREAD

**Issue by sfarhaazmi** [spring-projects/spring-framework#34089]
NoSuchMethod 'java.util.LinkedHashSet org.springframework.util.CollectionUtils.newLinkedHashSet(int)' - exception after upgrading to springboot 3.4.0 
All versions are compatible as per the dependency tree

sprint-test version used is 6.2.1
Junit-Jupiter version 5.11.3

**Comment by bclozel** [comment]
This methods exists and has been introduced in https://github.com/spring-projects/spring-framework/pull/32291.
The problem is likely a dependency management issue.

Please provide a minimal sample application.

**Comment by sfarhaazmi** [comment]
@bclozel here is the sample code of the test class -

import static org.mockito.Mockito.when;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import com.example.platform.api.Document;
import com.example.services.testapp.rest.services.DateTimeService;

@ExtendWith(SpringExtension.class)
public class TestApplication {

   private static final OffsetDateTime date = OffsetDateTime.now();

   @InjectMocks
   private TestServiceImpl testService;

   @Mock
   private DateTimeService dateTimeService;

   @BeforeEach
   public void setup() {
        MockitoAnnotations.openMocks(this);
   }

   @BeforeEach
   public void mockTimestamp() {
       when(dateTimeService.getDateTime()).thenReturn(date);
   }

   @Test
   public void testDocumentUpdate()
   {
	//Some test cases
    }
}

**Comment by sfarhaazmi** [comment]
mockito:
 version: 5.14.2

byte-buddy:
 version: 1.15.10

junit-jupiter:
 version: 5.11.3

spring:
 version: 6.2.1

spring-boot:
 version: 3.4.0

spring-cloud-dependencies:
 version: 2024.0.0

spring-cloud-aws-dependencies:
 version: 3.2.1

spring-security:
 version: 6.4.1

springdoc-openapi:
 version: 2.7.0

**Comment by bclozel** [comment]
Sorry but this is not actionable on my side. We can reopen this issue once a minimal sample application is provided. Thanks!

**Comment by RenatiusvanSander** [comment]
I had same error message and had to change version of Spring 6 to 6.2.5.
