### ISSUE TITLE
Support Bean Overrides (such as `@MockitoBean`) on test constructor parameters

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#36096]
Like there is a parameter resolver for `@Autowired`, it would be useful to have one for `@MockBean`, especially in Kotlin where it would enable using `val` instead of `lateinit var`.

cc @sbrannen

**Comment by wilkinsona** [comment]
Please use the 👍 and 👎 reactions on the issue description to indicate your interest rather than spamming the issue with comments.

**Comment by xenoterracide** [comment]
It would seem currently that the only option is to write a second test class since I only wanted to mock this for one test method.

**Comment by wilkinsona** [comment]
Given the plan to [deprecate `@MockBean`](https://github.com/spring-projects/spring-boot/pull/39864) in Spring Boot 3.4 and the introduction of `@MockitoBean` in Spring Framework 6.2, I don't think we should do anything here. A parameter resolver for `@MockitoBean` could be added to Spring Framework if there's still demand for this.

**Comment by xenoterracide** [comment]
@wilkinsona do you guys have the ability to move tickets between spring projects? I know that GitHub added that ability a while back. Would it be possible simply to move (And reopen ) this issue over to the spring framework instead of having to have someone rewrite the whole thing?

**Comment by wilkinsona** [comment]
I don't, but some of the team do as they're commiters on both projects.

@bclozel can please transfer this if appropriate or would the Framework team prefer a fresh issue?
