### ISSUE TITLE
Load files in <import resource=.../> only once [SPR-1142]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#5845]
**[Martin Zeltner](https://jira.spring.io/secure/ViewProfile.jspa?name=swisswheel)** opened **[SPR-1142](https://jira.spring.io/browse/SPR-1142?redirect=false)** and commented

Example:

file1.xml:
\<beans>
\<import resource="classpath:common/common-config.xml"/>
...
\</beans>

file2.xml:
\<beans>
\<import resource="classpath:common/common-config.xml"/>
...
\</beans>

If I load now an application context which has "file1.xml" and "file2.xml" as config locations, the file "common-config.xml" will be loaded twice. I suggest to remember the url of already loaded config files.

Thanks,
Martin

---

**Affects:** 1.2.1

**Attachments:**
- [SPR-1142-xml-application-context-import-once-2010-01-05.patch](https://jira.spring.io/secure/attachment/16066/SPR-1142-xml-application-context-import-once-2010-01-05.patch) (_17.65 kB_)

**Issue Links:**
- #14160 Ignore duplicated import files or property-placeholder files
- #12263 When a bean definition is overridden, detect whether the definition has changed and log accordingly

67 votes, 52 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by sbrannen** [comment]
If you were following this issue, you may be interested in the following.

- #27978
