### ISSUE TITLE
Provide a "best efforts" 1PC transaction manager out of the box [SPR-3844]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#8524]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-3844](https://jira.spring.io/browse/SPR-3844?redirect=false)** and commented

There have been detailed discussions about a "best efforts" transaction strategy that allows any number of local resource transactions to be part of a single Spring-managed transaction. Spring 2.0 already supports synchronized local JMS transactions in that style; this issue is effectively about extending that approach to all of Spring's supported resources.

Important 'side' features are commit ordering and customizable transaction logging (see #7996). This JIRA issue (together with #7996) serves for tracking requirements, suggestions and contributions, as well as the status of the "best efforts" transaction manager implementation in Spring.

---

**Issue Links:**
- [DATACMNS-310](https://jira.spring.io/browse/DATACMNS-310) Integrate best-effort TransactionManager from Spring Data Neo4j
- #18308 Move ChainedTransactionManager from spring-data commons to spring-tx
- [DATAGRAPH-256](https://jira.spring.io/browse/DATAGRAPH-256) Move ChainedTransactionManager from Spring Data Neo4j to Spring Framework

68 votes, 60 watchers

**Comment by jhoeller** [comment]
At this point, we have no intentions to provide a unified transaction management approach at the Spring Framework level, and neither does the Spring Data project. Picking an appropriate resource transaction manager for each transaction is what we recommend for multi-resource scenarios. From that perspective, it seems fair to close this issue.
