### ISSUE TITLE
Should AbstractTestNGSpringContextTests use @BeforeSuite instead of @BeforeClass? [SPR-4072]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#8750]
**[Sam Brannen](https://jira.spring.io/secure/ViewProfile.jspa?name=sbrannen)** opened **[SPR-4072](https://jira.spring.io/browse/SPR-4072?redirect=false)** and commented

AbstractTestNGSpringContextTests's springTestContextPrepareTestInstance() method is currently annotated with `@BeforeClass`, which prohibits `@BeforeSuite` methods in subclasses from interacting with the ApplicationContext.

Essentially, the question raised in the forum is: would it be better to annotate the springTestContextPrepareTestInstance() method with `@BeforeSuite` instead of `@BeforeClass`?

---

**Affects:** 2.5.6, 3.0.7, 3.1.1

**Reference URL:** http://forum.springframework.org/showthread.php?p=148532#post148532

**Issue Links:**
- #10077 AbstractTestNGSpringContextTests: Spring beans not available within `@BeforeTest` methods (_**"is duplicated by"**_)

13 votes, 14 watchers

**Comment by sbrannen** [comment]
Due to the age of this issue and the fact that the current behavior of `AbstractTestNGSpringContextTests` has not changed since Spring Framework 2.5 (i.e., late 2007), I am closing this issue.
