### ISSUE TITLE
Load dedicated child ApplicationContext for test instance in the TestContext framework [SPR-4632]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#9309]
**[Eberhard Wolff](https://jira.spring.io/secure/ViewProfile.jspa?name=eberhardwolff)** opened **[SPR-4632](https://jira.spring.io/browse/SPR-4632?redirect=false)** and commented

#### Status Quo

The `loadContext(\*\)` methods in `AbstractGenericContextLoader` and `AbstractGenericWebContextLoader` invoke `AnnotationConfigUtils.registerAnnotationConfigProcessors(context)`.

The result is that `@Autowired`, `@Resource`, `@Inject`, etc. all work by default, even if annotation-driven dependency injection is not explicitly configured in the test's `ApplicationContext`. Consequently, if a developer is not aware of this, then errors related to the lack of explicit annotation-driven DI support in production configuration will not be noticed until after testing which is typically undesirable.

Note, however, that this unexpected behavior only applies to XML-based configuration. With JavaConfig, an `AnnotatedBeanDefinitionReader` (used internally by `AnnotationConfigContextLoader` and `AnnotationConfigWebContextLoader`) automatically registers the _annotation config processors_.

Furthermore, `BeanPostProcessors` may inadvertently be applied to the test instance -- even though the test is not truly a _bean_ in the `ApplicationContext`. This leads to potentially problematic behavior such as accidental proxying of the test instance, as described in #14113.

---

#### Deliverables

1. [ ] As suggested in comments for this issue, create an `ApplicationContext` dedicated solely to the test instance (for the purpose of dependency injection and bean initialization) and set the `parent` of that context to the `ApplicationContext` loaded by the TCF.
2. [ ] Stop invoking `AnnotationConfigUtils.registerAnnotationConfigProcessors()` in:
   - [ ] `AbstractGenericContextLoader`
   - [ ] `AbstractGenericWebContextLoader`
3. [ ] Ensure that _child_ contexts are properly closed with regard to context caching in the TCF.

---

#### Original Issue Summary

_Do not enable annotation-driven DI for the entire ApplicationContext in the TestContext framework_

#### Original Proposal

It would be better if the TestContext framework (TCF) only enabled annotation-driven dependency injection for test instances and not for the entire `ApplicationContext`.

---

**Affects:** 2.5.2

**Attachments:**
- [AnnotationConfigProcessorTestExecutionListener.java](https://jira.spring.io/secure/attachment/14662/AnnotationConfigProcessorTestExecutionListener.java) (_1.42 kB_)

**Issue Links:**
- #13149 Spring Test should not modify the application context under test (_**"is duplicated by"**_)
- #14496 Support WebApplicationContext hierarchies in the TestContext Framework
- #10284 Provide support for context hierarchies in the TestContext Framework
- #18295 Support 'throw-away' context for a test class
- #10719 Provide mechanism for disabling automatic annotation-driven autowiring in tests
- #14113 Test instances should not be proxied in the TestContext framework

6 votes, 6 watchers

**Comment by sbrannen** [comment]
Since #14113 was addressed in 5.1 and due to other enhancements in the framework in the interim, we have not heard from the community about a concrete need for loading a child context in the TCF in modern Spring applications. In addition, as stated in the above discussions, introducing a child context also introduces issues of its own.

In light of that, I am closing this issue.
