### ISSUE TITLE
Introduce strategy for determining if a profile value is enabled for a particular test environment [SPR-4862]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#9538]
**[Sam Brannen](https://jira.spring.io/secure/ViewProfile.jspa?name=sbrannen)** opened **[SPR-4862](https://jira.spring.io/browse/SPR-4862?redirect=false)** and commented

ProfileValueSourceConfiguration allows one to configure an implementation for the ProfileValueSource strategy; however, AbstractJUnit38SpringContextTests and SpringJUnit4ClassRunner are currently hard coded to use ProfileValueUtils.isTestEnabledInThisEnvironment() which only matches on an exact _value_.

It would be beneficial to be able to configure different strategies for determining if a profile value is enabled for the current environment. The above classes could then delegate to the configured strategy. For backwards compatibility, the default strategy should simply delegate to ProfileValueUtils.isTestEnabledInThisEnvironment(); whereas, additional, pluggable strategies (e.g., one using regular expressions) could be provided for greater flexibility.

Further input from #10572:

It is a typical situation when one might have to run a combination of tests belonging to different test-groups. For example, a test method A is part of the 'smoke' test group, and test method B belongs to 'integration' test group. If you want to execute test methods A and B, you have to run two separate JUnit runs: one for 'smoke' and a separate one for 'integration'.

It would be great to have a way to combine tests from more than one test group in a single test run, for example:

```
% ant -Dtest-groups=smoke,integration run-tests 
```

A strategy which considers the _value_ to be a comma-separated list could provide such support with OR semantics.

---

**Affects:** 2.5.4, 2.5.5, 2.5.6

**Reference URL:** http://forum.springframework.org/showthread.php?p=182516

**Issue Links:**
- #12615 TestContext framework should support declarative configuration of bean definition profiles
- #13622 Allow overriding `@ActiveProfiles` in test classes with system property
- #16300 Introduce annotation to skip test based on active Spring profile
- #8334 Create annotation to group tests
- #10572 Allow multiple values be specified in the runtime for tests filtering by `@IfProfileValue`
- #10572 Allow multiple values be specified in the runtime for tests filtering by `@IfProfileValue` (_**"supersedes"**_)

5 votes, 3 watchers

**Comment by sbrannen** [comment]
I am closing this issue due to the age of this issue, the lack of recent community interest, and the fact that Spring provides flexible support for conditional test execution in JUnit Jupiter via `@EnabledIf` and `@DisabledIf`.
