### ISSUE TITLE
Ability to specify default-lazy-init behavior for imported bean definitions [SPR-5146]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#9819]
**[Eric Sirianni](https://jira.spring.io/secure/ViewProfile.jspa?name=sirianni)** opened **[SPR-5146](https://jira.spring.io/browse/SPR-5146?redirect=false)** and commented

There doesn't seem to be a way to configure Spring so that imported bean definition files inherit the default-lazy-init behavior from the parent.

For example:

<beans ...
default-lazy-init="true">

    <import resource="classpath:META-INF/cxf/cxf.xml"/>
    <import resource="classpath:META-INF/cxf/cxf-extension-soap.xml"/>
    <import resource="classpath:META-INF/cxf/cxf-servlet.xml"/>

\</beans>

The CXF beans are "eagerly" instantiated even though the parent bean XML speficies "default-lazy-init=true". Is there a way to get the CXF beans to obey the lazy-init behavior that I want (aside from editing the META-INF/cxf/cxf.xml files myself and re-jarring CXF?).  (the CXF beans take a few seconds to initialize and this is a problem with client apps in short-running JVMs that may not hit CXF on all code paths)

It seems like either:
1. 'default-lazy-init' should be inherited from the parent bean definition reader
2. There should be an attribute on the import element that allows for specifying the desired default-lazy-init behavior for the imported bean defs.

---

**Affects:** 2.5.5

6 votes, 6 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by Avinm** [comment]
I think this is still relevant as resource imports should work just like nested bean imports.

**Comment by Avinm** [comment]
Any plans on a fix for this? Could contribute myself if someone where to point in the right direction

**Comment by Avinm** [comment]
As a work around to enable lazy-init by default for test cases, I have added the below post processor to my test configurations:
```java
@Bean
public BeanFactoryPostProcessor lazyInitProcessor() {
    return beanFactory -> {
        for (String beanName : beanFactory.getBeanDefinitionNames()) {
            beanFactory.getBeanDefinition(beanName).setLazyInit(true);
        }
    };
}
```

**Comment by snicoll** [comment]
So there are two requests here, really. The original one is about changing the defaults when importing dedicated XML configurations. Each XML file is self-contained and we have no desire to change that at this point.

The other request is about changing all beans to be lazy (typically in integration tests). The `BeanFactroyPostProcessor` above is a good solution for this (the method could be `static` though). Spring Boot has a similar solution that is exposed via the `spring.main.lazy-initialization` property.
